### ISSUE TITLE
cmd/gc: constant divide by zero should be ok if not reachable

### ISSUE THREAD

**Issue by randall77** [golang/go#10004]
const N = 0
if N != 0 && x % N != 0 { ... }

The above code doesn't compile because it has a divide by a constant zero in it.  But that divide isn't reachable.  Maybe we should not error in this case.

I ran into this with a configuration variable in the runtime that is set for some architectures and not set (zero) for others.  It is possible to use a different sentinel (-1) in my case but may not be so in general.

**Comment by minux** [comment]
It's up to the interpretation of the spec:
"If the divisor is a constant, it must not be zero."

It doesn't say the division must be reachable to count.

Trying to define reachability in the spec might open another can of
warms.

FTR, the context of this issue: https://go-review.googlesource.com/#/c/6020/

**Comment by griesemer** [comment]
This is a correct compiler error per the spec.

Whether the spec decision (to not permit divisions by constant 0) was correct or not is a different question. Note that we could revisit that and permit it since it would be a backward-compatible change (it will permit programs that are not currently permitted, and not the other way round).

Closing this. Please file a spec issue if you feel strongly about it.

**Comment by griesemer** [comment]
Actually assigned this to myself.
