### ISSUE TITLE
misc/gdb: TestGdbPython fails on ppc64

### ISSUE THREAD

**Issue by rsc** [golang/go#10017]
TestGdbPython fails on the ppc64le builder. Don't know what the failure means.
http://build.golang.org/log/d81ea75267328ddf3441a74c92bc930679b9b69f

	--- FAIL: TestGdbPython (0.42s)
		runtime-gdb_test.go:103: print mapvar failed: No symbol "mapvar" in current context.
	FAIL
	FAIL	runtime	19.616s

Turning off. Might be nice to understand for Go 1.5 but not terribly concerned.

**Comment by minux** [comment]
The reason is that when you break on 'main.finish', gdb breaks on
the finish's frame, and because gdb can't backtrace our stack frames
on RISC architectures, the 'up' command will go to the wrong frame,
so mapvar can't be found there.

At least this is the reason for #10002, as I don't have access to
ppc64le systems to verify my hypothesis.

However, if we say `break main.go:10` so that the breakpoint in the
the 'main.main' frame, then gdb can indeed print the correct map
out.

The easiest way to fix the gdb backtrace problem is to use
frame pointers like what we did with the framepointer experiment
on amd64. I'm not sure if we can write a python helper to unwind
the stack for gdb, is that possible? Interpreting our pclntab in Python
is at least simpler than interpreting that in DWARF. Or we can
use our spadj to generate cfa pseudo-instructions for gdb to
unwind the stack. @ianlancetaylor

**Comment by jankratochvil** [comment]
I did not test it on ppc64 but hopefully the FAIL gets fixed by: https://go-review.googlesource.com/#/c/6267/
