### ISSUE TITLE
cmd/stringer: fails when the code uses the to-be-generated String() method

### ISSUE THREAD

**Issue by satran** [golang/go#10045]
**What version of Go are you using (go version)?**
1.4
**What operating system and processor architecture are you using?**
Linux x64-64
**What did you do?**
I came across a question in [stackoverflow](http://stackoverflow.com/questions/28792884/go-generate-stringer-invalid-operation-has-no-field-or-method-string/) which described how the user was trying to use stringer to implement `String` function which he/she was trying to use in the code. Here follows the question:
> I'm trying to use the stringer cmd so that I can generate String() methods for some int types. Here is how the code looks like

```
//go:generate stringer -type=MyIntType
type MyIntType int

const (
    resource MyIntType = iota
)
func myfunc(){
print(resource.String())
}
```

> The error I'm getting on go generate command is invalid operation: resource (constant 0 of type MyIntType) has no field or method String which makes sense because there is no String method yet. How am I supposed to fix this error if stringer cmd is supposed to actually generate the String method? Should I use fmt.Sprintf("%s", resource) all over the code ? it looks a bit ugly to me. At least not as nice as resource.String().

**What did you expect to see?**
go generate should have worked.

**What did you see instead?**
`invalid operation: resource (constant 0 of type MyIntType) has no field or method String`

**Comment by davecheney** [comment]
I think you have to put a space between the //go:generate line and the next
declaration.

**Comment by satran** [comment]
No, that does not work either.

**Comment by minux** [comment]
The problem is that your Go file uses the String method, and stringer fails
to type check
the file because the String method doesn't exist at that time. This is a
chicken-and-egg
problem.

One workaround is to separate the code that defines the type and constants
and the
code that uses the String method into different files, and then in the //
go:generate line,
use $GOFILE explicitly, so that stringer won't try to type check the whole
package.

e.g.
// a.go
package main

//go:generate stringer -type=MyIntType $GOFILE
type MyIntType int

const (
resource MyIntType = iota
)

// b.go
package main

func main() {
println(resource.String())
}

This is a limitation of stringer implementation, but not an easy bug to fix.

**Comment by robpike** [comment]
This is a bootstrap or chicken-and-egg problem that is easy to work around and hard to fix.
