### ISSUE TITLE
Should this be escaping to heap?

### ISSUE THREAD

**Issue by kidoman** [golang/go#10060]
http://play.golang.org/p/3vSZMFAFR_

```go
package main

import "fmt"

func main() {
	buf := make([]byte, 4)
	fmt.Printf("%v", buf[1:2])
}
```

**Comment by adg** [comment]
The issue tracker isn't the place for such questions.

https://groups.google.com/group/golang-nuts

**Comment by davecheney** [comment]
Please reopen this, I asked @kidoman to log this here as I couldn't explain why `buf` was escaping
```
% go run -gcflags -m x.go
# command-line-arguments
./x.go:6: make([]byte, 4) escapes to heap
./x.go:7: main ... argument does not escape
```

**Comment by minux** [comment]
any reference type that is passed as an interface{} argument is escaping.
known limitation of the gc escape analysis and interface implementation.
(interfaces always contain a pointer.)

**Comment by kidoman** [comment]
Should this also escape:

```
package main

import (
	"io"
	"os"
)

func main() {
	b := make([]byte, 6)
	io.ReadFull(os.Stdin, b)
}
```

```
# command-line-arguments
./test.go:9: make([]byte, 6) escapes to heap
```

**Comment by bradfitz** [comment]
Please, let's move this to a mailing list.  The bug tracker is for bugs, not Q&A.

**Comment by kidoman** [comment]
Sorry. Its done: https://groups.google.com/forum/#!topic/golang-nuts/kXEpVo6Bek8

**Comment by minux** [comment]
this one will definitely escape because the compiler
(when compiling io.ReadFull) don't know whether the
buf passed to Reader.Read will escape or not, so it
has to make a conservative decision.

again, it's a known limitation of the current escape
analysis architecture. We need whole program analysis
to determine that buf in this case doesn't actually escape.
