### ISSUE TITLE
cmd/internal/obj/arm64: add frame pointers

### ISSUE THREAD

**Issue by 4ad** [golang/go#10110]
RISC architectures fare much worse in gdb compared to x86. Right now we can't have stack traces in gdb, on arm64. Adding frame pointers would fix this.

**Comment by 4ad** [comment]
Replaces 4ad/go#101

**Comment by minux** [comment]
And Apple's ARM64 abi mandates frame pointer.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by zhongweiy** [comment]
https://go-review.googlesource.com/#/c/20193/ fixes backtrace in gdb under arm64. And it turns out that the break backtrace is caused by incorrect handling ra position relative to CFA during function call in DWARF '.debug_frame' under arm64.

I find frame pointer is still needed in linux perf tool to unwind stack when using "--call-graph fp". But it could be workarounded by telling perf unwind stack using DWARF info.

**Comment by 4ad** [comment]
Yes, we we add frame pointers in 1.8.
