### ISSUE TITLE
cmd/link: better support for non-4K page size systems

### ISSUE THREAD

**Issue by minux** [golang/go#10180]
At least three problems here:
`1`. cmd/ld INITRND needs to be at least as large as the page size, otherwise
we might trigger kernel bugs. See https://groups.google.com/forum/#!topic/golang-nuts/29RraQ-t3gc
for a case.

However, just using a larger INITRND value will make the binary bigger because
of the zero padding between segments.

I think we can have a way to have a much larger INITRND without increasing
the size of the binary by leaving a VM hole between the segments.
(e.g. text segment ends at `N*INITRND + x`, then we make the next segment's
load address start at `(N+1)*INITRND + x + 1`, so there is no hole in the file, but
different segments end up on different pages (if `INITRND >= page size`).

`2`. _PhysPageSize in runtime needs to be a variable and auto detected
at process start up. This might incur a performance overhead, but as the
proliferation of non-4K page size systems (power64, arm, arm64), we should
make the change to continue the Go tradition that it just works without extra
tuning. At least, we should make cmd/dist detect page size and tune the
const in runtime.

`3`. syscall.Getpagesize should return the value in the runtime. Right now,
it's hardcoded on all systems.

**Comment by davecheney** [comment]
Detecting the page size inside cmd/dist sounds reasonable.

Dumb question time, what are the downsides of just assuming 64k pages
everywhere?

**Comment by randall77** [comment]
I don't see any problem with _PhysPageSize being a variable, it is not used anywhere performance critical (except in the new memory barriers, but we can probably switch those to _PageSize if it matters).

The more difficult thing is to pick the right segment alignment in the binary.  Because we cross compile you can't use any autodetection scheme.  Picking the maximum alignment of all of our platforms might be fine.

**Comment by davecheney** [comment]
On 17 Mar 2015 09:17, "Keith Randall" <notifications@github.com> wrote:
>
> I don't see any problem with _PhysPageSize being a variable, it is not
used anywhere performance critical (except in the new memory barriers, but
we can probably switch those to _PageSize if it matters).
>

That was the one location that I saw that would be a performance concern if
it were not a constant expression.

We can get the system page size at startup from auxv or a syscall.

> The more difficult thing is to pick the right segment alignment in the
binary. Because we cross compile you can't use any autodetection scheme.
Picking the maximum alignment of all of our platforms might be fine.
>

I'd like that to be the case.

**Comment by mwhudson** [comment]
I think assuming the page size of the build and execution machines is a bad idea, even without thinking about cross compiling.  OTOH, I can't see a downside to leaving plenty of VM space between different segments. What does binutils do?

**Comment by ianlancetaylor** [comment]
There are two linkers in the GNU binutils.  They both support options -z common-page-size and -z max-page-size to set, at link time, the usual page size and the maximum page size.  The default values for these are processor specific.  These all feed into the algorithm that determines the layout of the segments in memory.  Basically, each segment is aligned to the maximum page size.  The linkers try to save a page on disk by offsetting the start of the data segment so that the last page of the text segment and the first page of the data segment can be on the same page of the executable (obviously that page gets mapped twice in memory, once executable, once writable).  When trying to save this page, they use the usual page size, not the maximum page size.

On amd64, for gold, the default maximum and usual page size are both 0x10000.  That is, gold does not support huge pages by default.  For the GNU linker, the default maximum page size is The usual page size is 0x200000 and the default usual page size is 0x1000.

I'm sure you're glad you asked.

For these kinds of numbers, I agree that the amount of VM space wasted by large segment alignments is not very important (although there used to be an interesting bug in glibc when it was able to map a small shared library into the gap between the text and data segments of the executable).  For Go, I think the linker should align the segments to the maximum page size that is really used on the processor.  I don't see why this would make the binary bigger, at least I don't see why it would be bigger on ELF systems.

**Comment by gaillard** [comment]
:+1:

**Comment by rsc** [comment]
I'd strongly prefer **not** to put more autodetection in cmd/dist. Every step we take in that direction makes cross-compilation harder.

The main thing that needs to be done is that the linker needs to be made clearer about the difference between virtual alignment requirements and file offset alignment requirements. That is, the systems with 64 kB pages do not require the file data mapped into those pages to be 64 kB aligned within the file. They only require something smaller, probably 4 kB. With that distinction made, we can adjust the virtual address alignment upward without affecting binary size. We should do that.

Changing _PhysPageSize in the runtime and syscall.Getpagesize are both trivial, especially in comparison.

But it's now too late to be doing any of this for Go 1.5.

**Comment by gaillard** [comment]
With 1.4 we are changing arch_arm.h to set the page size and then passing into -R into ldflags, what will we need to do for 1.5 when on custom page sizes?

**Comment by ianlancetaylor** [comment]
@gaillard Please ask questions like that on the mailing list, not on an issue.  Thanks.  (I don't know the answer to your question--I'm not really sure what you are asking.)

**Comment by aclements** [comment]
> quentinmit assigned aclements

The runtime should have no trouble with non-4K pages at this point. If there are any remaining issues, they're in the linker (IMO, they're really in the kernel's ELF loader).

I'm not quite sure who "owns" the linker at this point. I'm reassigning to David Crawshaw, but feel free to redirect as appropriate.

**Comment by vielmetti** [comment]
This issues affects the overlay2 filesystem on Docker, manifesting itself as https://github.com/docker/docker/issues/27384

**Comment by aclements** [comment]
> This issues affects the overlay2 filesystem on Docker, manifesting itself as docker/docker#27384

If the assessment in the docker issue is right, this should be fixed on Go tip.

**Comment by rsc** [comment]
Per @aclements, the runtime is safe for larger page systems.

Looking at archinit in src/cmd/link/internal/\*/obj.go, all the 64-bit non-x86 systems seem to already default FlagRound (formerly INITRND) to 64 kB.

So it sounds like both the runtime and the linker are fixed. I'm not worried about the binary size of an extra (average) 32 kB in this case due to rounding, so we can skip the INITRND VM tricks that Minux suggested in the original report.

I think we're all set on this issue. Closing. Reopen if I'm wrong, but please also explain why. Thanks.

**Comment by vielmetti** [comment]
Just confirming that a test build with Go 1.8 beta 1 on arm64 (armv8, aarch64) passes all tests.

**Comment by oshimaya** [comment]
Is this fix only for 64 bit?
The default pagesize is 8K in the current netbsd/arm (32bit, EABI).
So if the round size set by linker is 4K by default, this binary is not be loaded .
I'm very happy if the default value will be increased for netbsd/arm.
(The binaries of OS created by gnu-binutils is  64K)

**Comment by binarycrusader** [comment]
I'd like to add that our almost-compete sparc64 port also has no issues once we backported the pagesize related fixes in 1.8 to 1.7.  As such, I'd tend to guess that there are no general issues left with pagesize -- only platform-specific ones.

**Comment by vielmetti** [comment]
@binarycrusader - was the backport from 1.8 to 1.7 easy? (It looked like it might be.)

I've put together this tiny test at https://github.com/vielmetti/go-pagesize-test with the assistance of code from @bradfitz - hoping to backport this to aarch64 as well since the Ubuntu 16.04 LTS go for aarch64 is 1.6 vintage and exhibits this defect.

**Comment by tmm1** [comment]
The backport is quite straightforward with a few cherry-picks. I did it here: https://github.com/fancybits/go/compare/release-branch.go1.7...arm-pagesize-64k
