### ISSUE TITLE
playground: bad error message in Go Playground when package != "main"

### ISSUE THREAD

**Issue by ImJasonH** [golang/go#10183]
http://play.golang.org/p/gnZZOxKTko (or just use the standard Playground template and change `package main` to `package foo`)

The error message is confusing and seems like an internal error:

```
Error while loading "/tmp/sandbox046656083/a.out": Cannot open NaCl module file
Using the wrong type of nexe (nacl-x86-32 on an x86-64 or vice versa)
or a corrupt nexe file may be responsible for this error.
```

A better error message would hint that the package must be `main`, like the error message when a `func main()` is missing.

**Comment by adg** [comment]
Agree.

**Comment by shawnps** [comment]
I took a stab at this...it's been a while since I've contributed so let me know if I did anything wrong regarding the contribution process: https://go-review.googlesource.com/#/c/7923/1/sandbox/sandbox.go

I'm also not sure if this is the best way to check if the package != 'main', please critique or just throw it away.

Contributing to playground as a newcomer was kind of difficult, I would love to help improve the docs if someone could answer a couple of dumb questions for me:

1. How do I tail the log? I'm using `boot2docker` as the README mentions, but I couldn't find the output anywhere so I was sending stuff to myself in API responses.
2. How do I see the web stuff locally? Do I have to use the python development server for GAE?

**Comment by Thomasdezeeuw** [comment]
That patch won't work if you add a comment at the top of the file. And add some tests for the change.

**Comment by andrewaustin** [comment]
This was fixed in https://github.com/golang/playground/commit/c81e550ea6345d3dba3e51f69cc2c23cf8eefe35

See http://play.golang.org/p/gnZZOxKTko. 

You can close this issue.
