### ISSUE TITLE
cmd/compile: inline all type assertions

### ISSUE THREAD

**Issue by rsc** [golang/go#10208]
CL 7862 inlined y.(*T) for types that fit in the interface.
It's only one extra indirection to get the types that are
stored indirectly. We probably should do that.
Then assertE2T, assertE2T2, assertI2T, assertI2T2
can all be deleted from the runtime.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by haya14busa** [comment]
I'm sorry if i'm wrong but this issue was fixed by https://github.com/golang/go/commit/688995d1e91fcc36ac33bf34d6303e935d1b0a70 ?

FWIW, I grepped assertE2T, assertE2T2, assertI2T, assertI2T2 and I found that below comment may be outdated?

	// Special: use temporary variables to hold result,
	// so that assertI2Tetc can take address of temporary.
	// No temporary for blank assignment.

https://github.com/golang/go/blob/9ffbdabdb02c1fd95eabee82457aaa0dd79d46ac/src/cmd/compile/internal/gc/order.go#L569

**Comment by randall77** [comment]
Yes, this issue is fixed.  As for that comment, it is still kind of true, we allocate a temporary for non-SSAable types.
