### ISSUE TITLE
syscall: audit missing syscalls on linux/arm64

### ISSUE THREAD

**Issue by minux** [golang/go#10235]
Despite our efforts, it seems there are still syscalls in the syscall
package that are missing on linux/arm64.

Getpgrp is one.

**Comment by suihkulokki** [comment]
At least the following deprecated syscalls still need warppers for arm64:
epoll_create -> epoll_create1
epoll_wait -> epoll_pwait
futimesat -> utimensat
getpgrp -> getpgid
pause -> ?
time -> gettimeofday?
ustat -> statfs
utime -> utimes

There are also some syscalls in the unimplemented table that need to be taken care when implemented:

evenfd -> eventfd2
signalfd -> signalfd4
poll -> ppoll

**Comment by suihkulokki** [comment]
looking at glibc, pause is implemented as
sigset_t set;
rt_sigprocmask(SIG_BLOCK, NULL, &set, 8)  = 0
rt_sigsuspend(&set, 8

and time is implemented as gettimeofday from the vdso. - which is how go seems to do Time on amd64 as well.

**Comment by suihkulokki** [comment]
And dup2 -> dup3 wrapper needed (see #11981)

**Comment by suihkulokki** [comment]
Any way to make this less unplanned? I keep bumping into go packages that naively call syscalls not being aware they have been deprecated and are not available on arm64.. 

cc @davecheney and @4ad

**Comment by bradfitz** [comment]
@suihkulokki, which? Those packagess are buggy, then. Using syscall is like using unsafe... you have to really know what you're doing. They probably don't run well on Windows or Plan 9 or Solaris either.

**Comment by suihkulokki** [comment]
@bradfitz This is typically linux-specific code, such as some of the libraries used by docker (example: libcontainer) or code where linux implementation is in a different file then windows one (fsnotify). Both examples have now fixes commited, but I expect that more are being created as we talk. Developers are not aware that bunch of syscalls go provides are actually deprecated ones, because they work just fine on amd64. My faith that people who use the syscall package know what they are doing is not very strong...

**Comment by 4ad** [comment]
> My faith that people who use the syscall package know what they are doing is not very strong

People that use the syscall package (and unsafe, as already mentioned) should know what they are doing.

It's not clear to me why we should cater to poorly-written programs, thereby decreasing the incentive to move to the go.sys package.

**Comment by suihkulokki** [comment]
> It's not clear to me why we should cater to poorly-written programs, thereby decreasing their incentive to move to the go.sys package even more.

Ok, I didn't know about go.sys. However, the same problems are there too. People who need Epoll will use EpollCreate() instead of EpollCreate1() because nothing hints that the former is deprecated. We can:

1) whenever a arm64 user compiles the affected code, send a patch upstream to change it
- this is the current somewhat inconvenient state
2) add a EpollCreate -> EpollCreate1 wrapper to go.sys 
- this is the "cater poorly written programs choice"
3) remove legacy syscalls like EpollCreate from go.sys
- this breaks backward compatibility

I would assume 2, is preferred choice, since the current arm64 has a bunch already, example:

https://github.com/golang/sys/blob/master/unix/syscall_linux_arm64.go#L132

**Comment by anthonyfok** [comment]
But what about the unimplemented syscall.EpollPwait() when syscall.EpollWait() is supposedly deprecated?  Unless I am mistaken, there is currently no way out for ARM64: syscall.EpollWait() gives ENOSYS: function not implemented error (from Linux kernel), but EpollPwait is not yet implemented in Go.

This currently affects fsnotify, which in turn affects Hugo and others, see go-fsnotify/fsnotify#112 and spf13/hugo#1772

@bradfitz, I see that you dealt with a similar issue for the Perl Sys::Syscall package at bradfitz/sys-syscall#6, so you can't simply dismiss that that Linux-specific code requiring syscall.EpollPwait() as buggy, right?  :wink:

Should this problem be addressed here, or over at golang.org/x/sys?  Many thanks!

**Comment by minux** [comment]
It should be addressed at x/sys/unix. Thanks.

**Comment by anthonyfok** [comment]
Thank you @minux!

（对不起，昨天有眼不识泰山，一下子没认出来！）感谢 Minux 大神！  :pray:

**Comment by luxas** [comment]
Kubernetes is affected by this also as I'm adding support for `arm64`.
Quick question: Is `syscall.Dup2` equalient to `syscall.Dup3` on `arm64`?
It would be great if you added some more wrappers for `arm64`...

**Comment by 4ad** [comment]
> Quick question: Is syscall.Dup2 equalient to syscall.Dup3 on arm64?

This has nothing to do with Go, it has to do with Linux: http://linux.die.net/man/2/dup3

**Comment by mildred** [comment]
I would say https://golang.org/src/syscall/syscall_linux.go#L933 contains a good list of unimplemented syscalls. In particular I'm missing the syscalls about extended attributes on symlinks:

- lgetxattr
- llistxattr
- lremovexattr
- lsetxattr

**Comment by suihkulokki** [comment]
I've hopefully implemented missing ones for arm64 in x/sys/unix . What was left is Ustat, which I think is too obscure to bother wrapping. Use Statfs instead.

**Comment by ianlancetaylor** [comment]
@suihkulokki Thanks!  Closing this issue on the assumption that the work is done.

**Comment by suihkulokki** [comment]
Thanks, feel free to @ me if new issues with arm/arm64 syscalls appear.
