### ISSUE TITLE
x/mobile/webview: is a cross iOS/android web view possible?

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10247]
Embedding a web browser is a common strategy for apps that are not heavily focused on UI, on both Android and iOS. The web also provides a very easy way to use other UI systems in a Go application.

Is there enough commonality between the embedded web views on Android and iOS to build an API usable entirely from Go? The Android WebView has a wide interface and its not clear what subset lines up with iOS. Still, this would be very nice to have.

Assigning to myself, unless someone else really wants this.

/cc @hyangah @rakyll

**Comment by rakyll** [comment]
I would suggest you to target a small subset first. The initial step should be page loading, intercepting the requests and navigation-related APIs are secondary.

A web view is critical to pop-up a welcome screen with instructions, listing credits, documenting help, etc. I'd like to have the possibility to switch to a web view for text-dominated screens.

Recommended APIs to begin with:
```
loadDataWithBaseURL (String baseUrl, String data, String mimeType, String encoding, String historyUrl)
- (void)loadData:(NSData *)data MIMEType:(NSString *)MIMEType textEncodingName:(NSString *) encodingName baseURL:(NSURL *)baseURL

loadUrl(String url)
- (void)loadRequest:(NSURLRequest *)request

reload()
- (void)reload

stopLoading()
- (void)stopLoading
```

**Comment by kalopsia** [comment]
I'm sorry for off topic, but still.. @crawshaw, thanks for support, it's very pleased that you raised this issue!

**Comment by tqangxl** [comment]
u r right, Embedding a web browser on Android and IOS will unified development environment ,Let the developers don't focus on os environment!

Android fragmentation is very serious, coupled with highly customized , multi-version (2.4-4.2 now V5), multi-resolution ,this  allowing developers a headache , if you can solve this problem , many developers will adopt this platform.

eg. When we release a  android app run Android 2.4 or 4.2 and above, A Company and B Company were modified on customized Android system , the situation is often occur in the A Company B model can run , but in the B Company can not run on the C model！

**Comment by lunny** [comment]
+1. It's a good idea than a cross-platform UI library.

**Comment by neclepsio** [comment]
So, it's done and unreleased?

Go + WebView + Polymer would be a great way to make Android applications; if working also on iOS it would be even better.

**Comment by minux** [comment]
No, it is not done yet.

**Comment by joeblew99** [comment]
So i saw the Code at:  https://github.com/golang/mobile/commit/8f20c3e9d3f264676a801751a87ccd5d37e45d34

Thansks @crawshaw !

So is this closed ? Does NativeActivity generate Android code thats usable for loading web views ?

**Comment by joeblew99** [comment]
@minux @crimshaw


Is this still on the table in terms of an objective ?

There are some good ways to bridge is inside the webview down into the golang code I think.

**Comment by crawshaw** [comment]
Given I have no time to work on this, I'm going to close this issue.

It is still a quite reasonable project, and I believe the gobind bindings are now good enough that this could be built in an external repository by anyone who is interested.

**Comment by joeblew99** [comment]
@cramshaw

thanks for update, and yes there seems to be be enough to get the job done.
We are iterating on it over here:
https://github.com/gu-io/gu-x

**Comment by microo8** [comment]
Here is a tool to do that (it's not tested/stable yet) https://github.com/microo8/gowebview

**Comment by joeblew99** [comment]
thanks @microo8 . Code looks really good tooo. Like the way you code gen the boiler plate parts.
Any plans for IOS ?

There is a really nice desktop version for webview with golang  here:
https://github.com/murlokswarm
It currently supports OSX and Windows, with mobile planned.
It also has an unusual approach in that on the backend (on the client) you can use golang templates  for all the rendering with the ability to target the froentend( the webview on the client)  HTML DOM nodes.  So the FrontEnd is very dumb.
Its a very simple and elegant approach i feel, because all data mutations are sent to the backend, and then all views on the frontend get repopulated automatically if you set things up right.

If your interested i would be happy to visit the idea of collaborating on this

**Comment by microo8** [comment]
Thanks for the praise @joeblew99 :) but it isn't fully tested yet. And also i'm making some changes to it in short. Trying to make it as an tool, not just an project template generator. I don't know if this is the plate to discuss it, but I'd like to make some commands, like `create`, `build`, `debug`, `install`. So that it can generate the template code, or it will build the production/debug apk right away.

IOS is not in plan, android does it for me, but wouldn't mind to pull some changes to support it as well :P

When @murlokswarm will have the mobile support, I'll definitely look at it, but this "framework style" development isn't for me :) I like the minimalistic approach that you are not bound to an framework, but create your own http server as you wish and then just wrap it with some code to create the mobile webview app. 
You know: "Less is exponentially more" :)

**Comment by joeblew99** [comment]
@microo8 very true about the framework style. Can see your point - just wanted to introduce the pattern they use in case it was useful for you.


Regarding IOS. I am pretty useless at xCode. Over at the murlok team though the first one built was for OSX, and so its going to be likely that they could whip up an IOS version i suspect. 
You should ask I reckon. I dont see any reason why it cant work as a base, and they can layer their framework approac on top. Everyone wins.

Regarding the design time tooling of "create, build, debug, install" thats a great idea.
