### ISSUE TITLE
cmd/internal/gc: unexported fields visible to reflect

### ISSUE THREAD

**Issue by albhaf** [golang/go#10332]
- What version of Go are you using (go version)?

  `go version devel +bb29875 Thu Apr 2 17:05:09 2015 +0000 darwin/amd64`

- What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
)

type foo struct {
	bar string
}

func main() {
	a := foo{}
	b, _ := json.MarshalIndent(a, "", "\t")
	fmt.Println(string(b))
}
```

- What did you expect to see?

```
{}
```

- What did you see instead?

```
{
	"bar": ""
}
```

it appears to have been introduced by https://github.com/golang/go/commit/0de359da301d1ed5a63c87a8853bedbd829ab906

**Comment by vanthanh2305** [comment]
capital letter of bar
```type foo struct {
    Bar string
}```
if you want rename Bar to bar use `json:"bar"`
```type foo struct {
    Bar string `json:"bar"`
}```

**Comment by albhaf** [comment]
Yes, I would have capitalised it and used a struct tag in case I actually wanted it included in the JSON.

However, I expected it to not be included since it wasn't capitalised and that is the unexpected change in behaviour.

**Comment by josharian** [comment]
Confirmed; thanks. I'm quite surprised that there isn't a test for this. I wonder whether anything else reflect-y broke.

/cc @mwhudson

**Comment by mwhudson** [comment]
It only happens for structs defined in the main package it seems, which goes some way towards explaining why it didn't break any tests.

**Comment by mwhudson** [comment]
I think http://pastebin.ubuntu.com/10736457/ is a fix, will do the CL thing tomorrow.

**Comment by nathany** [comment]
I ran into the same issue today where `go version devel +6d3a7e7` was reporting ` json: unsupported type: func() time.Time` due to tls.Config data several levels down being encoded. A simplified example:

```go
package main

import (
	"encoding/json"
	"log"
	"time"
)

type Client struct {
	// should not export conn or anything below it
	conn *Conn
}

type Conn struct {
	// Conf *tls.Config contains
	Time func() time.Time
}

func main() {
	_, err := json.Marshal(Client{conn: &Conn{}})
	if err != nil {
		log.Fatal(err)
	}
}
```

It took me some time to track down that it was this issue. It turns out that logging e.String() from unsupportedTypeEncoder was quite helpful in determining the offending field.

The comment regarding this only happening in `package main` explains why I wasn't able to write a test case for this.
