### ISSUE TITLE
runtime: TestGdbPython fails with 'module' object has no attribute 'error' 

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#10359]
From https://groups.google.com/d/msg/golang-nuts/WFPWHpG1NOM/JWXHWwgb_WMJ

The build fails running the runtime tests, with:

--- FAIL: TestGdbPython (0.73s) 
        runtime-gdb_test.go:99: info goroutines failed: Traceback (most recent call last): 
                  File "/home/gb113119/Go/source/go/src/runtime/runtime-gdb.py", line 395, in invoke 
                    except gdb.error: 
                AttributeError: 'module' object has no attribute 'error' 
                Error occurred in Python command: 'module' object has no attribute 'error' 
FAIL 
FAIL        runtime        16.320s 

This is on RHEL 6.6, GCC version 4.4.7, GDB version 7.2, Python versoin 2.6.6.

**Comment by aclements** [comment]
It appears gdb.error was introduced in GDB 7.3. I'm kind of surprised the test even gets that far in 7.2. Since 7.3 was released in July of 2011, I'm happy to say "we don't support GDB < 7.3", but please reopen if you disagree. I would add a version check to runtime-gdb.py, but there appears to be no way to get the running GDB version from the Python API other than redirecting and parsing the rather verbose output of "show version".
