### ISSUE TITLE
go/types (std repo): enable disabled tests

### ISSUE THREAD

**Issue by griesemer** [golang/go#10368]
https://go-review.googlesource.com/8594 skips tests for some platforms.

Root cause is incomplete/incorrect FindPkg function in go/types/internal/gcimporter/gcimporter.go. The relevant package files are not found.

**Comment by minux** [comment]
To re-enable the tests on nacl, we need to include every
Go source file in $GOROOT into the test file system zip
file.

**Comment by griesemer** [comment]
@minux But the missing files here are the compiler-built package files (the ones that the compiler would import). It appears that the gcimporter doesn't compute the correct location.

**Comment by minux** [comment]
oh, for gcimporter tests, I think we have to disable the tests on nacl,
because
nacl process doesn't have access to the (real) file system.

We prepare a fake file system implemented in syscall package that read files
from a zip file. The zip file contains most testdata, /lib and /test.

That's the reason why go/types and gcimporter test currently fail on nacl.

We can include package sources into the fake file system zip, but we
definitely
don't want to also include pkg/nacl_$GOARCH/, because it's too large (and
actually impossible, due to recursive dependencies (the file system zip is
contained
in the syscall package.)

**Comment by griesemer** [comment]
@minux Thanks for the clarification. The explains much. How about windows? Anything special for Windows builds on the builders? Or specifically, given a package source, say "$GOROOT/src/math" (with correct path separators), where is the location of the compiled package?

**Comment by alexbrainman** [comment]
I don't think windows is special in any way. Why do you think windows would be different? Package binary for %GOROOT%\src\math would be in %GOROOT%\pkg\windows_386\math.a.

**Comment by griesemer** [comment]
@minux Just making sure. Thanks.

**Comment by minux** [comment]
On windows, the only failing test is test/recover4.go, which uses
syscall.Mmap.

We can just add a special case to only parse test/recover4.go on linux and
darwin.
That would also fix solaris.

**Comment by griesemer** [comment]
@minux https://go-review.googlesource.com/8611
