### ISSUE TITLE
runtime: TestCgoExternalThreadPanic fails on ppc64

### ISSUE THREAD

**Issue by davecheney** [golang/go#10410]
Inadvertently broken in e8694c8196e3

```
--- FAIL: TestCgoExternalThreadPanic (0.66s)
	crash_cgo_test.go:50: want failure containing "panic: BOOM". output:
		fatal error: unexpected signal during runtime execution
		[signal 0xb code=0x1 addr=0x8 pc=0x3fffae653ad0]
		
		runtime stack:
		runtime.throw(0xa8870, 0x2a)
			/home/ubuntu/workspace/linux-ppc64le-canonical-4b21be46701c/go/src/runtime/panic.go:543 +0x8c
		runtime.sigpanic()
			/home/ubuntu/workspace/linux-ppc64le-canonical-4b21be46701c/go/src/runtime/sigpanic_unix.go:12 +0x64
		
		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/home/ubuntu/workspace/linux-ppc64le-canonical-4b21be46701c/go/src/runtime/asm_ppc64x.s:1132 +0x4 fp=0xc208038fe0 sp=0xc208038fe0
		
		goroutine 1 [select (no cases)]:
		main.main()
			/tmp/go-build916459717/main.go:9 +0x28
		
		goroutine 18 [syscall, locked to thread]:
		runtime.goexit()
			/home/ubuntu/workspace/linux-ppc64le-canonical-4b21be46701c/go/src/runtime/asm_ppc64x.s:1132 +0x4
		
FAIL
FAIL	runtime	29.467s
```

**Comment by spetrovic77** [comment]
Looking at this...

**Comment by spetrovic77** [comment]
https://go-review.googlesource.com/#/c/8766/1 will fix this test.

Dave, this seems to be a linking problem on PPC64le, please look at the CL description and tell me if you know what's going on.

**Comment by aclements** [comment]
@austin

**Comment by davecheney** [comment]
I wish I knew what was going on. I agree linking is involved as there are
other tests in that file which are excluded on ppc64 due to a lack of
external linking.

**Comment by spetrovic77** [comment]
The build failure is fixed, but the question on why the test has failed still remains.  Here is the simplest code that demonstrates the failure (before CL 8766).

package main

// void gopanic(void);
//
// static void start(void) {
//  gopanic();
// }
import "C"

//export gopanic
func gopanic() {
	panic("BOOM")
}

func main() {
	C.start()
}

The failure occurs when start() invokes gopanic(), in the _cgo_wait_runtime_init_done() call.  If  _cgo_wait_runtime_init_done() is non-empty (say, fprintf is added to it), it will fail.

**Comment by ianlancetaylor** [comment]
The PPC ELF v2 ABI requires that every function start with a small prologue that computes the TOC pointer in r2 from the function address in r12.  This computation is two instructions; in normal PPC assembler it looks like this:

0:      addis 2,12,.TOC.-0b@ha
        addi 2,2,.TOC.-0b@l

The symbol .TOC. is not defined in an object file, and is magically defined by the linker.  The linker must arrange that every function in the same module (shared library or executable) compute the same value for r2.

The problem here is that 9l is using a different value for .TOC. for functions defined in different object files.  I haven't sorted it all out, but 9l seems to use a different .TOC. symbol for each object file, and to give them different values.  This may be correct for the ELF v1 ABI; I'm not sure.  It's not correct for the ELF v2 ABI used on PPC64le.

The different TOC value causes some calls to pthread_mutex_lock to load the wrong value from the GOT and branch to the wrong function, leading to a crash.

I hope somebody else can take it from here.

**Comment by mwhudson** [comment]
Ah, I recently found the same cmd/link (nee 9l) behaviour around using a different .TOC. for each object file that Ian refers to and was very confused by it. Glad to hear Ian thinks it's wrong too :-)

External linking will fix this though.

**Comment by rsc** [comment]
We're not going to make it to Go 1.6 for ppc64 external linking.

**Comment by ianlancetaylor** [comment]
Has this problem been fixed by the use of external linking?  If we drop runtime/cgo/gcc_libint_linux_ppc64x.c and simply use runtime/cgo/gcc_libint.c on linux-ppc64 and linux-ppc64le, do all the tests pass?

CC @spetrovic77 @laboger

**Comment by laboger** [comment]
This testcase worked for me on master latest on an Ubuntu system and RHEL 7.2 ppc64le.
The intent of this issue is not ppc64 BE, is it?  The title says ppc64 but the first stack trace posted shows ppc64le.

./runtime.test -test.run=TestCgoExternalThreadPanic -test.v
=== RUN   TestCgoExternalThreadPanic
--- PASS: TestCgoExternalThreadPanic (1.15s)
PASS

go version devel +1492e7d Fri Apr 22 10:08:05 2016 +0000 linux/ppc64le

**Comment by ianlancetaylor** [comment]
I think this issue was ppc64le specific, because it was due to ELF ABI v2.  I sent a CL.
