### ISSUE TITLE
fmt: empty byte slice prints one value with format "% 02x"

### ISSUE THREAD

**Issue by robpike** [golang/go#10430]
https://play.golang.org/p/S51xT7K4Au

package main

import "fmt"

func main() {
	fmt.Printf("% 02x\n", []byte{0})
	fmt.Printf("% 02x\n", []byte{})
}

prints 00.

**Comment by bradfitz** [comment]
So?

https://play.golang.org/p/35pyRrGLXN 
```
package main

import "fmt"

func main() {
	fmt.Printf("% 08x\n", []byte{1})
}
```
prints:
```
00000001
```

Are those leading zeros wrong too?

The user asked for it to be zero-padded.

**Comment by paulhankin** [comment]
I think while this is surprising, it isn't a bug as it works as documented in https://golang.org/pkg/fmt/:
"""
For most values, width is the minimum number of runes to output, padding the formatted form with spaces if necessary.

  0	pad with leading zeros rather than spaces;
"""

"% 08x" applied to an argument of type []byte doesn't mean "format the bytes in the argument with 8 hex characters per byte, separated by spaces."

It means "format the bytes in the argument with 2 hex characters per byte, separated by spaces, and then pad the result with 0s on the left if the string has length less than 8."

Thus, fmt.Printf("% 04x", []byte{}) first produces "" which is padded to "0000".
And fmt.Printf("% 04x", []byte{2}) first produces "02" which is padded to "0002".

Examples: https://play.golang.org/p/lvP2PBEdJZ

**Comment by robpike** [comment]
"For compound operands such as slices and structs, the format applies to the elements of each operand, recursively, not to the operand as a whole. Thus %q will quote each element of a slice of strings, and %6.2f will control formatting for each element of a floating-point array."

So for an empty slice it should print nothing. Fix coming.

**Comment by rajender** [comment]
As brad asked, isn't this change effectively make width not applicable for string and byte slices? Should we mention that in docs? 

It seems, the previous behavior was adhering to the following statement in the docs.

"For most values, width is the minimum number of runes to output, padding the formatted form with spaces if necessary."


raj@rajender:~/go/src> cat ~/a.go
package main

import "fmt"

func main() {
	      fmt.Printf("% 20x\n", []byte{1})
	      fmt.Printf("% 20x\n", []byte{1, 1})
	      fmt.Printf("% 20x\n", []byte{1, 1, 1})
	      fmt.Printf("% 20x\n", []byte{1, 1, 1, 1})
}
raj@rajender:~/go/src> ~/go1.4/bin/go version
go version go1.4.2 linux/amd64
raj@rajender:~/go/src> ~/go1.4/bin/go run  ~/a.go
                  01
               01 01
            01 01 01
         01 01 01 01
raj@rajender:~/go/src> ~/go/bin/go version
go version devel +2f98bac Tue Apr 14 07:22:44 2015 +0000 linux/amd64
raj@rajender:~/go/src> ~/go/bin/go run  ~/a.go
01
01 01
01 01 01
01 01 01 01


raj@rajender:~/go/src> cat ~/a.go
package main

import "fmt"

func main() {
	fmt.Printf("% 05s\n", []byte{})
}
raj@rajender:~/go/src> ~/go/bin/go version
go version devel +2f98bac Tue Apr 14 07:22:44 2015 +0000 linux/amd64
raj@rajender:~/go/src> ~/go/bin/go run  ~/a.go
00000

**Comment by martisch** [comment]
hi,

the statement in the patch notes that the loop applies the padding is false.

See a testcase like:
{"% 03x", []byte{1, 2, 3}, "001 002 003"},

it works for 02x because hex 1 is already 01.
 
i was working on the todo in the function that changed and had make some testcases for the old padding behavior which as explained above by rob would be wrong. They are failing now but also reveal that no padding is applied anymore regardless if it should per element or not. 

{"%20X", []byte("xyz"), "              78797A"},
{"% 20X", []byte("xyz"), "            78 79 7A"},
{"%#20X", []byte("xyz"), "            0X78797A"},
{"%# 20X", []byte("xyz"), "      0X78 0X79 0X7A"},
{"%-20X", []byte("xyz"), "78797A              "},
{"% -20X", []byte("xyz"), "78 79 7A            "},
{"%-#20X", []byte("xyz"), "0X78797A            "},
{"%-# 20X", []byte("xyz"), "0X78 0X79 0X7A      "},

--- FAIL: TestSprintf (0.00s)
	fmt_test.go:729: Sprintf("%20X", [120 121 122]) = "78797A" want "              78797A"
	fmt_test.go:729: Sprintf("% 20X", [120 121 122]) = "78 79 7A" want "            78 79 7A"
	fmt_test.go:729: Sprintf("%#20X", [120 121 122]) = "0X78797A" want "            0X78797A"
	fmt_test.go:729: Sprintf("%# 20X", [120 121 122]) = "0X78 0X79 0X7A" want "      0X78 0X79 0X7A"
	fmt_test.go:729: Sprintf("%-20X", [120 121 122]) = "78797A" want "78797A              "
	fmt_test.go:729: Sprintf("% -20X", [120 121 122]) = "78 79 7A" want "78 79 7A            "
	fmt_test.go:729: Sprintf("%-#20X", [120 121 122]) = "0X78797A" want "0X78797A            "
	fmt_test.go:729: Sprintf("%-# 20X", [120 121 122]) = "0X78 0X79 0X7A" want "0X78 0X79 0X7A      "

**Comment by martisch** [comment]
adding to the above - not sure if this is another inconsistency if we need to format per element:

currently:
Sprintf("% 02x", [1]) = "01"

but if the format is applied per element shouldnt the ' ' mean we need to make a space for the sign?
Sprintf("% 02x", [1]) = " 01"

**Comment by robpike** [comment]
Reverting this change. An empty slice or empty string printed with padding should show the padding. I will adjust the documentation to make this clear.
