### ISSUE TITLE
net/http: some left out logging in net/http/cookie.go

### ISSUE THREAD

**Issue by omerkirk** [golang/go#10454]
There are log statements that cannot be suppressed in net/http/cookie.go file. These statements create too much log when we redirect output to log file. Is there anyway to connect these to a parameter like ```isDebug```.
sanitizeOrWarn function
```
 332			log.Printf("net/http: invalid byte %q in %s; dropping invalid bytes", v[i], fieldName)
```

String() function
```
 153			} else {
 154				log.Printf("net/http: invalid Cookie.Domain %q; dropping domain attribute",
 155					c.Domain)
 156			}
```

**Comment by bradfitz** [comment]
@omerkirk, have you considered just filtering out things you don't want by installing your own filtering `io.Writer` implementation with `log.SetOutput(io.Writer)`?  I think that might be cleaner than https://golang.org/cl/9411 

Thoughts?

**Comment by bradfitz** [comment]
@josharian and I looked into those warnings and they appear to only happen for when your own code is sending invalid cookies out. There are no other places to report those, so you should really be fixing your application instead of ignoring them.

Closing this bug for now, but feel free to argue otherwise if we're missing something.
