### ISSUE TITLE
go/build: deps_test.go should check transitive dependencies?

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10475]
If I add

    import _ "net/smtp"

to net/http/client.go, then deps_test.go fails.

If I add the same line to net/http/internal (which is imported by net/http/transport.go), then deps_test.go doesn't complain.  It seems like deps_test.go should still catch this somehow.

Possible ideas: check a package's transitive dependencies rather than just its immediate dependencies, or check that all of its immediate dependencies are also listed in pkgDeps.

**Comment by minux** [comment]
Or add net/http/internal to the table and lock down its dependencies.

**Comment by mdempsky** [comment]
That would be my second suggestion ("check that all of its immediate dependencies are also listed in pkgDeps"), but my point is that deps_test.go should have caught this.  It's also missing at least image/internal/imageutil, mime/quotedprintable, internal/singleflight, internal/mime, container/list, internal/syscall/unix, and internal/syscall/windows, so it's blind to transitive dependencies added via those packages too.

**Comment by minux** [comment]
the dep test is designed before the internal package thing, a time
when adding packages to std packages is way harder.

I think the problem is that when a new internal package is introduced,
its dependency must be locked down in deps_test.go, but that was
not followed.

deps test just need to caught any package not explicitly locked down.

**Comment by bradfitz** [comment]
Yes, any package not listed in the map should be treated as having no allowed dependencies.

Good find.
