### ISSUE TITLE
crypto/elliptic:  Note to Validate Curve Points

### ISSUE THREAD

**Issue by Bren2010** [golang/go#10502]
This is a follow-up for issue #2445.

If there ever was a note in the `elliptic` library warning programmers to check if adversarially-chosen points are on the right curve or in the right subgroup, it's no longer there.  Implementers often forget or assume that `Unmarshal` or `ScalarMult` does the checks for them, so stating that they don't somewhere conspicuous should help avoid lots of stupid vulnerabilities in production code.

**Comment by coruus** [comment]
Unmarshal now checks that points are on the curve, so this issue is effectively closed by d86b8d3

**Comment by Bren2010** [comment]
@coruus It doesn't look like that code has been officially released and it probably won't be widely run until a few months after it has been.  We still need a security warning *now* and for people running older versions of Go.

**Comment by coruus** [comment]
I'm pretty sure that a point release for this issue is unlikely. If you
want to contribute documentation about this, that would be helpful.

It really isn't that serious -- compared to the implementations of P384 and
P521 not being constant-time -- for any of the curves included in the Go
standard library, save P224. Does anyone actually use 224 for anything?

**Comment by ianlancetaylor** [comment]
It sounds like this is fixed in Go 1.5, so closing the issue.

I don't know how to issue a security warning.  That is something to discuss on the golang-dev mailing list.
