### ISSUE TITLE
cmd/go: remove cross-GOPATH rebuild barrier

### ISSUE THREAD

**Issue by rsc** [golang/go#10509]
The code at the bottom of isStale that bypasses the source file mtime checks was added to fix a bug (issue #3149) about writing to a system GOROOT, but the fix also (intentionally) separated out different GOPATH entries. This causes problems when people use fine-grained GOPATHs (not the common case, but also not something that should be broken), because installing a binary or package in one GOPATH uses stale packages from the other.

The system GOROOT has been the subject of many follow-on bugs and is now handled separately. We should remove the GOPATH barrier.

**Comment by shurcooL** [comment]
Thank you! This sounds incredibly good.

I will finally be able to `go install` my packages. I couldn't do that before of non-zero possibility of stale installed packages being used for compilation instead of the latest source code. This is also going to be immensely helpful for automated Go code generation and execution (e.g., see https://github.com/jimmyfrasche/goutil/issues/2).

**Comment by hyper-carrot** [comment]
This is a great decision!! It will eliminate the barriers for a lot of third-party tools.
