### ISSUE TITLE
build: dragonfly-amd64 builder broken since April 19th

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10520]
From http://build.golang.org/log/88b8d8099fa3386966d859854d9db45621a7c66e:

    ERROR: Cannot find /go1.4/bin/go.
    Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.

According to https://code.google.com/p/go-wiki/wiki/DashboardBuilders, that bot's operated by Justin Sherrill.  I think that's @fupjack.

**Comment by fupjack** [comment]
It is - the machine it's on was rebooted, and the command that restarted the go builder didn't set up the environment correctly.  I've restarted it correctly and modified the crontab job so that it should survive the next time.  I can't test surviving a restart right now, but it's already built the most recent commit ( 3a56aa0d3eb1 ) successfully.

**Comment by mdempsky** [comment]
LGTM, thanks!
