### ISSUE TITLE
net: missing /etc/resolv.conf on Linux means query localhost

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10566]
http://man7.org/linux/man-pages/man5/resolv.conf.5.html

       If this file does not exist, only the name server on the local
       machine will be queried; the domain name is determined from the
       hostname and the domain search path is constructed from the domain
       name.

See also Alex Skinner's comments at https://go-review.googlesource.com/#/c/8945/

**Comment by mdempsky** [comment]
FreeBSD and NetBSD also document:

     On a normally configured system this file should not be necessary.	 The
     only name server to be queried will be on the local machine, the domain
     name is determined from the host name, and the domain search path is con-
     structed from the domain name.

**Comment by axaxs** [comment]
Thank you.  Further testing reveals this is the behavior also if resolv.conf exists and no nameservers are listed.

**Comment by mdempsky** [comment]
Yeah, that seems to be the behavior I see looking at glibc, FreeBSD, NetBSD, and illumos's res_init functions: if /etc/resolv.conf is either missing or there are no "nameserver" lines, then localhost is used by default.

If I'm reading FreeBSD and NetBSD's correctly, it looks like they explicitly register both 127.0.0.1 and ::1 as default nameservers.

glibc and illumos only use 127.0.0.1 as the default name server.

OpenBSD also defaults to 127.0.0.1 if there's no "nameserver" line, but /etc/resolv.conf still has to exist or else it only uses /etc/hosts.

**Comment by axaxs** [comment]
Do you think it's acceptable to just use 127.0.0.1 and ::1 regardless of flavor?  I don't see much harm in it.  This is what my previous patch did.  Secondly, should we differentiate openbsd in case that resolve.conf doesn't exist if we fix in dns_config?  If we don't, regular builds will behave because Brad's change detects this.  However people who build with netgo in openbsd would get the Linux behavior.  If nobody else is working on it already, I can shoot a fix over tomorrow pending thoughts on the above.

**Comment by axaxs** [comment]
I have a fix for this written, just need to fix a couple tests and will submit.  It's a rather large change because as I dug deeper there was more wrong/inconsistent.  To name a few things, three global dns related structs named 'cfg', 'conf', and 'confVal' which was fun keeping track of, having resolv.conf rechecks only in netgo, and double parsing resolv.conf.  I've removed conf and cfg, removed redundancies, and added rechecks for nsswitch and resolv.conf to the conf.go file.  Not sure if more bug reports need to be opened individually, but I'd rather fix it in one go than peacemeal.

**Comment by bradfitz** [comment]
Mail the change out once you have new tests (which fail now but should pass).

I may not be able to look at it until Tuesday morning.

**Comment by axaxs** [comment]
Thanks.  I've submitted https://go-review.googlesource.com/#/c/9380/  
It's my first in a while, and since move to git, so hopefully it's not too nightmarish.  

Please review and if someone could kick off trybots on it that would be great.
