### ISSUE TITLE
runtime: TestMemStats-2 fails with "Bad sys value" when run with -cpu=1,2,4

### ISSUE THREAD

**Issue by josharian** [golang/go#10585]
CL 9350 changed run.bash from:

```
GOMAXPROCS=2 go test runtime -short -cpu=1
GOMAXPROCS=2 go test runtime -short -cpu=2
GOMAXPROCS=2 go test runtime -short -cpu=4
```

to

```
GOMAXPROCS=2 go test runtime -short -cpu=1,2,4`
```

The latter failed on all the linux builders. See e.g. http://build.golang.org/log/da902358a2f5babbca5dc405364c912987e396b7.

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestMemStats-2 (0.00s)
	malloc_test.go:41: Bad sys value: {Alloc:2492744 TotalAlloc:312910744 Sys:31721720 ...
```

Fix the test, and then re-submit CL 9350. (It was rolled back in CL 9394.)

/cc @aclements

**Comment by aclements** [comment]
Looks to be related to the shuffle from StackInuse to StackSys in readmemstats_m. With the single runs of the runtime test, StackSys == 0 before this shuffle, so it's fine to clobber it with StackInuse and pull that amount out of HeapSys. Everything still adds up to Sys. But with the multiple runs StackSys != 0 at this point, so when we clobber it, the new sum differs from the original sum in Sys by this much.

I'm not sure why multiple runs changes this, but this shuffle smells wrong.

**Comment by aclements** [comment]
Ah. I think newosproc0 is the only function that manipulates memstats.stacks_sys directly. It gets called in the runtime test suite by TestNewOSProc0, which presumably runs after TestMemStats. In a single run, this means when TestMemStats runs, stacks_sys==0. But in a multi-run, the first run of TestNewOSProc0 will run before the second run of TestMemStats, so the second run of TestMemStats sees stacks_sys!=0.

The problem is just as easy to trigger with
    go test -short runtime -cpu=1,1

**Comment by aclements** [comment]
https://go-review.googlesource.com/9366
