### ISSUE TITLE
cmd/compile: Biobuf duplication

### ISSUE THREAD

**Issue by davecheney** [golang/go#10652]
There are two copes of `Biobuf` in the compiler, `cmd/internal/obj/util.go` and `cmd/internal/ld/util.go`. Both are in various stages of decomposition, for example 05d53165 was applied to the latter, but not the former. The former has sort of had 05d53165 applied accidentally, and now `Bungetc` is inconsistent, some methods check the unget buffer, others do not.
- If there must be a wrapper around `bufio.Buffer`, then there should be at most one in the compiler.
- Preferably we should be using `bufio.Buffer` directly everywhere.

@rsc @robpike thoughts ?

**Comment by randall77** [comment]
I'm all for deleting code, using bufio.Buffer everywhere sounds great.
For 1.5, however, it is a bit late.  That's a lot of lines to change after the freeze.

**Comment by davecheney** [comment]
That's fair, but please consider at least applying https://go-review.googlesource.com/#/c/9529/

**Comment by odeke-em** [comment]
I think the original issue was resolved if we are just talking of the copies of Biobuf.
After:
+ @mdempsky's CL https://go-review.googlesource.com/#/c/21644 to make package `cmd/internal/bio`
+ @davecheney's CL https://go-review.googlesource.com/#/c/21720 to replace bio.Buf with bio.Reader and bio.Writer
we now use "cmd/internal/bio" in both.

However, in @davecheney's CL https://go-review.googlesource.com/#/c/21720 he noted at https://github.com/golang/go/commit/8f2edf11998a30b497586ac0e9f75036a318280a#diff-c6708995b52ed026c5e6632418f7a3b6R247 that the logic of bio.Writer was duplicated in a small internal struct. Perhaps a new issue to refactor/replace that unexported code can then be opened since the original duplication issue was solved?

Any thoughts?

**Comment by davecheney** [comment]
I think when gri deletes the old importer code from the compiler in 1.8
this should expose a few more places where bio is not used and will
probably seal its fate.

**Comment by bradfitz** [comment]
This no longer seems to be the case:

```
$ git grep -i Biobuf
cmd/link/internal/ld/ldpe.go:// TODO(brainman): maybe just add ReadAt method to bio.Reader instead of creating peBiobuf
cmd/link/internal/ld/ldpe.go:// peBiobuf makes bio.Reader look like io.ReaderAt.
cmd/link/internal/ld/ldpe.go:type peBiobuf bio.Reader
cmd/link/internal/ld/ldpe.go:func (f *peBiobuf) ReadAt(p []byte, off int64) (int, error) {
cmd/link/internal/ld/ldpe.go:   sr := io.NewSectionReader((*peBiobuf)(input), input.Offset(), 1<<63-1)
cmd/vendor/golang.org/x/arch/x86/x86asm/testdata/libmach8db.c:  Biobuf bstdout;
```
