### ISSUE TITLE
debug/macho: No support for objc sections such as __objc_data

### ISSUE THREAD

**Issue by fabiensanglard** [golang/go#10662]

**Comment by minux** [comment]
Why do you think debug/macho only supports 64-bit segments?

**Comment by fabiensanglard** [comment]
Checkout the struct segment_command and segment_command_64 on apple documentation page: https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/index.html#//apple_ref/doc/uid/20001298-89026

The size of the fields declared in the go struct SegmentHeader match segment_command_64 but are wrong is you read a segment_command (from a 32 bits binary)

**Comment by minux** [comment]
That's because the package will automatically translate the struct
so that portable code only need to handle one type that is big
enough to hold both kinds of segment headers.

http://golang.org/src/debug/macho/file.go#L317

**Comment by fabiensanglard** [comment]
I completely missed this part :) ! Renaming to "no support for objc sections"

**Comment by minux** [comment]
Could you please elaborate what do you expect for objc support?

**Comment by fabiensanglard** [comment]
I want to add ability to parse objc class, method, category and prototypes

**Comment by minux** [comment]
That's definitely out of scope for debug/macho.

**Comment by fabiensanglard** [comment]
Please elaborate. Why not add support to parse objc ?

**Comment by minux** [comment]
The main reason debug/macho exists is because of cmd/cgo
needs it to read the section contents. Interpreting the contents
of sections is generally out-of-scope for that package (unless
interpreting the content helps accessing other information in
the file, for example, symtab)

Parsing the objc stuff doesn't need to be in the standard library,
it's perfectly fine for a go-gettable package.
