### ISSUE TITLE
x/mobile: bind/java/seq_test.go cannot find aar on latest android studio

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10668]
When running go test, adb logcat reports:

```
F/go/Seq  (13579): cannot find go/Seq
```

It looks like go.Seq is in the testpkg.aar, but gradle is not making it part of the apk.

**Comment by timcooijmans** [comment]
+1
The go.Seq is not included in the build: It is missing from the intermediate/classes directory, where I would expect is. Only the R.class file is present.

**Comment by hyangah** [comment]
@crawshaw : I could reproduce the problem myself. The class files are in the apk (so, Go.init was called) and could be found from the app package but not from bind/java package. It seems that when find_class is called from the Go thread, a wrong class loader was picked up. Verified with logging the exception details.

http://developer.android.com/training/articles/perf-jni.html#faq_FindClass
"You can get into trouble if you create a thread yourself (perhaps by calling pthread_create and then attaching it with AttachCurrentThread). Now there are no stack frames from your application. If you call FindClass from this thread, the JavaVM will start in the "system" class loader instead of the one associated with your application, so attempts to find app-specific classes will fail."

I will try to cache the loader or class from JNI_OnLoad as recommended in the doc.

@timcooijmans Is the problem related to the bind/java/seq_test.go? In seq_test.go setup, go.Seq is in  build/intermediates/exploded-aar/testpkg/classes.jar.

**Comment by timcooijmans** [comment]
@hyangah I'm seeing exactly the same problem in other projects. However both in seq_test.go and in my project I was surprised to see that the go-related Java-class-files were not present during gradle-building in the intermediate/classes directory. I expected them there but maybe I am wrong on that.
