### ISSUE TITLE
go/defer: unexpected behavior with defer and closure

### ISSUE THREAD

**Issue by johnmcconnell** [golang/go#10693]
https://play.golang.org/p/07BTwrFI91<- Defer using direct method call syntax
https://play.golang.org/p/wAGS9ZneTb<- Defer using a call in a first order function
With the first order function, I expected the same output:
```
Again
World
Hello
```

It could be that this is expected but it appears to me to be unexpected behavior to me.
I'm guessing that the first time defer stores the complete closure the first time the higher order function is called when i == len(o) -1. The other defer calls are using the same closure even though i has been updated.
^^ I stand corrected

**Comment by invino4** [comment]
This is a common misconception about the way closures work for by-value variables and has nothing to do with defer.  When a closure captures a by-value variable it extends the actual variable's lifetime by hoisting its storage to the heap.  Effectively all references to the variable are rewritten as pointer dereferences to the heap allocated storage.  In your case the variable i is hoisted to the heap.  Since all references to i (including the assignment performed by each iteration of the for loop) reference the same piece of storage, that variable's value is updated each time the loop goes around.  When the defer statements run later then execute the closure which itself then references the same heap storage for i reading what ever value it had last, which was of course the last value assigned by the last for-loop iteration.  Since all closures are sharing the same hoisted storage for i they all see the same value and hence print the same string.

For instance consider this version which defines a brand new variable that has local-iteration scope (and so is not shared across loop iterations).  It once again prints what you expected.

https://play.golang.org/p/QmLKrKHf2p
