### ISSUE TITLE
fmt: %*d is too picky about type of length

### ISSUE THREAD

**Issue by rsc** [golang/go#10732]
I am writing a program with a bit buffer and a bit count. For good reasons it makes sense for the count to be something other than int (for example, you're shifting by it a lot, so it makes sense for it to be unsigned).

	package main
	import "fmt"
	func main() {
		var bits uintptr = 5
		var count uintptr = 5
		fmt.Printf("%*b\n", count, bits)
	}

prints "%!(BADWIDTH)101". http://play.golang.org/p/BGxyBdPV5E

It seems like maybe fmt should allow any integer type for the width. It's a tiny bit more effort in the code and it eliminates an annoyance for users. In my case I didn't know what BADWIDTH meant and at first thought the value was actually bad in some way. It was only when I was about to read the docs that I realized the problem was likely the type.

@robpike

**Comment by robpike** [comment]
Don't know how to fix this without adding an allocation to every print. I tried the obvious thing and the test failed:

	fmt_test.go:961: Sprintf("%x"): got 3 allocs, want <=2

etc. I believe the problem is that the arrival of reflection causes the argument to escape.

Before the change, given Printf("%x", 3):

go tool 6g -m x.go
x.go:6: 3 escapes to heap
x.go:6: main ... argument does not escape

After the change:

dunnart=% go tool 6g -m x.go
x.go:6: ... argument escapes to heap
x.go:6: 3 escapes to heap

Without reflection there is no way to handle every integer type. I could handle int and uint but that seems unsatisfactory.

**Comment by robpike** [comment]
Update: This now works without allocation:
		v := reflect.ValueOf(a[argNum])
		switch v.Kind() {
		case reflect.Int:
			isInt = true
			num = int(v.Int())
		}
so we are clear to fix this. Not sure what changed, if anything. Adding to 1.6.
