### ISSUE TITLE
net: TestAcceptIgnoreSomeErrors is flaky on Windows

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10785]
Flaky test noticed in trybot run https://storage.googleapis.com/go-build-log/9bd00409/windows-amd64-gce_98deed0d.log :

```
--- FAIL: TestAcceptIgnoreSomeErrors (0.34s)
	net_windows_test.go:126: recv failed: read tcp 127.0.0.1:49346->127.0.0.1:49349: wsarecv: An existing connection was forcibly closed by the remote host.
FAIL
FAIL	net	3.165s
```

/cc @mikioh @alexbrainman for any ideas

**Comment by mikioh** [comment]
Sent https://go-review.googlesource.com/#/c/9911/, but not addressed @alexbrainman' comments yet. Perhaps using internal/socktest might be enough because only thing we need to test here is simply observing that Accept never returns any errors when it receives broken connection requests from pending queue.

**Comment by alexbrainman** [comment]
I can reproduce it on my windows-386 computer. So it was easy to fix https://go-review.googlesource.com/9942.

Alex
