### ISSUE TITLE
x/sys: add darwin/arm support

### ISSUE THREAD

**Issue by robpike** [golang/go#10813]

**Comment by ianlancetaylor** [comment]
Original syscall CL is http://golang.org/cl/2123 , but these files should be re-generated for x/sys.

**Comment by minux** [comment]
I think this issue is moot because it's not possible to generate all
the required definitions for iOS.

A lot of facilities implemented on desktop darwin are lacking headers
in the official iOS SDK. Most notably, the bpf, ptrace and low-level
networking headers are missing.

Moreover, why would someone want to use ptrace, bpf or raw socket
on iOS?
