### ISSUE TITLE
tour: [short description of the issue]

### ISSUE THREAD

**Issue by mcarlo** [golang/go#10988]
Context: /flowcontrol/7

The output doesn't seem to change if I change the order of the items in the fmt.Println statement.

The output for 
fmt.Println(
		pow(3, 2, 10),
		pow(3, 3, 20),
	)

is

27 >= 20
9 20

Why isn't the output

9 20
27 >= 20

?

**Comment by ALTree** [comment]
The output does change. The following:
```
fmt.Println(
    pow(3, 2, 10),
    pow(3, 3, 20),
)
```

prints

```
27 >= 20
9 20
```

while

```
fmt.Println(
    pow(3, 3, 20),
    pow(3, 2, 10),
)
```

prints

```
27 >= 20
20 9
```

note that `20` and `9` swapped position.

The `27 >= 20` line is always printed first because the `pow` function calls are evaluated before the call to `Println`.

p.s. This kind of question is better suited for the [golang-nuts mailing list](https://groups.google.com/forum/#!forum/golang-nuts).

**Comment by minux** [comment]
Yeah, please ask questions on the mailing list (or on the IRC). The issue
tracker is for bugs. (It's always OK to send the question, even if you
think it's a bug, to the mailing list.)
