### ISSUE TITLE
travis ci integration

### ISSUE THREAD

**Issue by c9s** [golang/go#11005]
Hi! Have you ever considered of integrating Travic CI on GitHub? that way, forkers can continously test their changes on GitHub.  If you are willing to accept a patch of this,  I can submit a patch.

**Comment by ALTree** [comment]
The go dashboard is here: https://build.golang.org

I don't think Travis CI integration with Github would be very useful for the go project, since development does not happen via github pull requests (so contributors usually don't fork the go repository on gihthub).

p.s. The github tracker is for issues, please use the [golang-dev mailing list](https://groups.google.com/forum/#!forum/golang-dev) for discussion about development of the Go Project.
