### ISSUE TITLE
x/tools/cmd/godoc: Panic in loader.(*importer).addFiles

### ISSUE THREAD

**Issue by jacobsa** [golang/go#11012]
I'm running Go 1.4.2 installed from homebrew on OS X:

    % go version
    go version go1.4.2 darwin/amd64
    
    % go env
    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/Users/jacobsa/go"
    GORACE=""
    GOROOT="/Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec"
    GOTOOLDIR="/Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"

I've just a minute ago updated godoc to golang/tools@8ccf558e8ad400746c297c66f6493427d382cfe4 using:

    go get -u -v golang.org/x/tools/godoc

When I run it like this:

    godoc -analysis type,pointer -http :1234

It always crashes after 5-6 seconds with:

```
2015/06/01 11:02:30 Loading and type-checking packages...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x37d816]

goroutine 1111 [running]:
golang.org/x/tools/go/loader.(*importer).addFiles(0xc2081fc000, 0x0, 0xb2e9a0, 0x0, 0x0, 0x0)
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/go/loader/loader.go:1108 +0x276
golang.org/x/tools/go/loader.(*Config).Load(0xc20813e140, 0x7ff750, 0x0, 0x0)
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/go/loader/loader.go:710 +0x1b39
golang.org/x/tools/godoc/analysis.Run(0x6e2001, 0xc208036b30)
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/godoc/analysis/analysis.go:378 +0xc17
created by main.main
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/cmd/godoc/main.go:307 +0x1af0

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2084f2290, 0x72, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2084f2290, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2084f2230, 0x0, 0xc39e30, 0xc2082696b8)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2084aada0, 0x934e4, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2084aada0, 0x0, 0x0, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2086d2cc0, 0xc55738, 0xc2084aada0, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2086d2cc0, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x7fff5fbffafb, 0x5, 0xc54670, 0xc20803c990, 0x0, 0x0)
        /Users/jacobsa/.homebrew/Cellar/go/1.4.2/libexec/src/net/http/server.go:1808 +0xba
main.main()
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/cmd/godoc/main.go:311 +0x192e

goroutine 1093 [sleep]:
golang.org/x/tools/godoc.(*Corpus).refreshMetadataLoop(0xc2080369c0)
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/godoc/meta.go:142 +0x62
created by golang.org/x/tools/godoc.(*Corpus).Init
        /private/tmp/go20150526-58358-v7wg96/go/src/golang.org/x/tools/godoc/corpus.go:145 +0x89
```

[Here](https://gist.githubusercontent.com/jacobsa/b5940132827bf5bbfac6/raw/9717cf2772652f5f0b4076ab8110cc3e13576b5c/gistfile1.txt) is a full log.

**Comment by rsc** [comment]
This comment is clearly false:

		info := imp.imported[path].info // must be non-nil, see above

addFiles is being called with info == nil.

Does this also happen with godoc compiled against Go 1.5?
If it's a skew problem, like the current tip godoc not being able to read Go 1.4 object files, I'm less concerned.

**Comment by jacobsa** [comment]
I haven't seen this in weeks; I'm willing to say it was either fixed or was due to version skew caused by me.

**Comment by jacobsa** [comment]
(To be clear: for the weeks I mention I've been building Go from tip.)

**Comment by jeffallen** [comment]
When I build godoc tip with go1.5 and analyze go1.5 source, I can repro this.

$ pwd
/Users/jeffall/gopath/src/golang.org/x/tools/cmd/godoc
$ go version
go version devel +aad4fe4 Thu Jul 23 05:50:53 2015 +0000 darwin/amd64
$ go build
$ GOPATH=$HOME/none GOROOT=$HOME/go ./godoc -analysis type,pointer -http :1234
(boom)

 When I build godoc tip with go1.4, and then analyze go1.4 source, I can't:

$ ~/go1.4/bin/go version
go version go1.4 darwin/amd64
$ ~/go1.4/bin/go build
$ GOPATH=$HOME/none GOROOT=$HOME/go1.4 ./godoc -analysis type,pointer -http :1234
(works as advertised)
$ GOPATH=$HOME/none GOROOT=$HOME/go ./godoc -analysis type,pointer -http :1234
/Users/jeffall/go/src/syscall/syscall_darwin_arm64.go:9:6: Getpagesize redeclared in this block
/Users/jeffall/go/src/runtime/arch1_arm64.go:8:2: thechar redeclared in this block
2015/07/23 16:15:11 Loaded 313 packages.
2015/07/23 16:15:11 Transitively error-free main packages: []
(no panic, but not useful because it analyzes no packages)

Note: Setting GOPATH to something that does not exist is helpful, because it takes all of the random code from GOPATH out of the equation.

Still diggin.

**Comment by rsc** [comment]
Retracted by @jacobsa
