### ISSUE TITLE
x/mobile/cmd/gomobile: add iOS build support

### ISSUE THREAD

**Issue by rakyll** [golang/go#11043]
This is the tracking bug for the gomobile’s iOS build support.

There are two obvious strategies we can follow to build an *.app file from a Go package.

The first alternative is what misc/ios/go_darwin_arm_exec.go has been doing.

* Require user to set GOIOS_DEV_ID, GOIOS_APP_ID, and GOIOS_TEAM_ID manually.
* Target darwin/arm (and darwin/arm64 in the future) and build a binary.
* Generate Info.plist, Entitlements.plist and ResourceRules.plist.
* Compile the asset catalog and generate asset catalog plist file. (TBD)
* codesign the the application directory.
* Output the app file and optionally generate an IPA for ad-hoc distribution.

Or a simpler alternative is to create a minimal Xcode project.
* Create the minimal Xcode project. (TBD, CLI tools like xcodeproj is able to create projects, it must be doable.)
* Target darwin/arm and build a binary.
* Shell out to xcodebuild to build and app. (It will fail if there are no default signing authorities.)
* Optionally we can output the generated xcode project to allow users to open it in Xcode.

Any feedback or opinions about which way to follow?

cc/ @crawshaw @hyangah @minux

**Comment by rakyll** [comment]
I may move the discussion to golang-dev@ if any extensive discussion is required.

**Comment by crawshaw** [comment]
If the latter approach works, creating an Xcode project and building it with xcodebuild, I would prefer that as it offers users more flexibility. However I'm not sure how it will be compatible with our linking process. For gomobile bind this strategy will definitely work, because we provide .a files and expect the entry point to be a main function in a .m/.c file, which xcode understands how to link.

Perhaps it is possible to replace the binary compile command with an xcode project setting?

One alternative would be to forgo real binary building and build with -buildmode=c-archive and let xcode do the linking (with a tiny .c file containing a main function). It would be odd, building libraries and passing them to xcode because there's no other way to get at its app building machinery, but if there's no other way it would probably work.

Minor notes:
- darwin/arm64 binaries are required by the app store, so we should build both. The tool to build universal binaries is called lipo.
- the build should copy assets to xcode resources.
- a slash page image is required to get the iPhone 5S/6 to use its full resolution. according to the UI guideline this splash page is not a "company icon"-style splash page but an image of the first page. For game-like apps, I suspect that's a simple black page.

**Comment by rakyll** [comment]
> However I'm not sure how it will be compatible with our linking process. 

I was able to skip the compile/link step just by removing the main.c, adding a static binary to the project and setting the CFBundleExecutable. I will investigate if it is achievable with lipo files.

> I suspect that's a simple black page.

We may look for a, let's say, splash.png in the assets directory and fall back to a default image (which is likely to be a black image).

**Comment by rakyll** [comment]
The idea worked with fat binaries! I pushed a minimal Xcode project to https://github.com/rakyll/go-xcode and suggesting to follow this path. Being able to work with Xcode is great for the developer experience. I am seamlessly pushing the debug builds to the test device, can export the app as an ad-hoc distribution or publish the app to the App Store.

**Comment by rakyll** [comment]
Blocked by https://github.com/golang/go/issues/11075.

**Comment by rakyll** [comment]
Blocked by https://github.com/golang/go/issues/11311.

**Comment by rakyll** [comment]
Blocked by https://github.com/golang/go/issues/11339.

**Comment by rakyll** [comment]
Blocked by https://github.com/golang/go/issues/11342.

**Comment by rakyll** [comment]
Blocked by https://github.com/golang/go/issues/11337.
