### ISSUE TITLE
cmd/compile: delete Debugzerostack dead code

### ISSUE THREAD

**Issue by josharian** [golang/go#11060]
After CL 10315, code guarded with Debugzerostack is dead. Delete it for Go 1.6. Also check whether CL 10315 orphaned any other code.

**Comment by rsc** [comment]
The code guarded with Debugzerostack became unreachable when we moved liblink into the compilers, in Go 1.3 (golang.org/s/go13linker). I've left it this long because I figured that we might want it, and we could turn it on with a GOEXPERIMENT or a compiler flag. But I think the record shows that we no longer need it.
