### ISSUE TITLE
runtime: documentation for LockOSThread is not clear

### ISSUE THREAD

**Issue by joaonrb** [golang/go#11069]
I plan to bind a functionality in my app to not run in parallel but without losing the concurrency solutions, much like a GIL but for a specific thread. I planned to use runtime.LockOSThread() but the documentation is unclear. 

First of all is the current goroutine that will bind to a OS thread or is the next being created?

And second any goroutine created by the one locked to the OS thread will also execute exclusively to that OS thread or any other?

I used an example suggested [here](http://stackoverflow.com/a/30647648/2521743):

    package main
    // #include <pthread.h>
    import "C"
    import (
 	 "fmt"
	 "runtime"
         "time"
    )

    func main() {
	    runtime.GOMAXPROCS(runtime.NumCPU())
	    ch1 := make(chan bool)
	    ch2 := make(chan bool)
	    fmt.Println("main", C.pthread_self())
	    runtime.LockOSThread()
	    go func() {
		    fmt.Println("locked", C.pthread_self())
		    time.Sleep(1000 * time.Millisecond)
		    go func() {
			    time.Sleep(1000 * time.Millisecond)
			    fmt.Println("locked child", C.pthread_self())
			    ch1 <- true
		    }()
		    ch2 <- true
	    }()
	    <-ch1
	    <-ch2
    }

And I come up with the result:

    main 139673634682688
    locked 139673609656064
    locked child 139673609656064

It looks that the second goroutine executes in the same OS thread as the first one (witch fits my needs but I don't know if is a reliable way).

**Comment by adg** [comment]
The docs for `LockOSThread` say

> LockOSThread wires the *calling* goroutine to its current operating system thread. 

(emphasis mine)

So in your program it is the main goroutine (the one executing the `main` function) that is locked to a specific OS thread (and no other goroutine may execute in that thread).

It is just a coincidence that the other two goroutines execute in the same thread. There is no facility to ensure that a group of goroutines all execute in the same thread (although the scheduler is likely smart enough to run related goroutines in the same thread).

Closing this issue because the docs are explicit about which goroutine is locked to the thread.
