### ISSUE TITLE
net/http: Transport VerifyHostname should be optional when using TLS

### ISSUE THREAD

**Issue by agj32mrgibbits** [golang/go#11076]
There should be an option to verify the certificate chain without verifying the hostname. Currently you can only disable both certificate and hostname verification using InsecureSkipVerify.

`https://tools.ietf.org/html/rfc6125#appendix-B.2` 
```
...
If the client has external information as to the expected identity of
the server, the hostname check MAY be omitted.  (For instance, a
client may be connecting to a machine whose address and hostname are
dynamic but the client knows the certificate that the server will
present.)
...
```
A new boolean should be added to tls.Config named `InsecureHostnameSkipVerify`.

**Comment by bradfitz** [comment]
Why?

**Comment by bradfitz** [comment]
Why can't you just use Transport.DialTLS?

**Comment by agj32mrgibbits** [comment]
Are there examples anywhere?

**Comment by bradfitz** [comment]
Let's move this to the golang-nuts mailing list. We don't use our bug tracker for support requests.

**Comment by agj32mrgibbits** [comment]
That's OK, we just found it cheaper to patch 6 lines in the golang source for our project vs implementing a new method.

**Comment by bradfitz** [comment]
That sounds like a bad idea and a painful maintenance cost going forward. You're now running a forked version of Go instead of using the mechanisms it already provides. The `Transport.DialTLS` does exactly what you want.

But like I said, this should be discussed on the golang-nuts list. I'm just leaving this note here in case anybody finds this and considers making your same mistake.
