### ISSUE TITLE
runtime: darwin/arm64 doesn't detect a deadlock case

### ISSUE THREAD

**Issue by rakyll** [golang/go#11094]
Consider the program below.

```
package main

func main() {
	select {}
}
```
It should panic with deadlock. 

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select (no cases)]:
main.main()
	/Users/jbd/src/github.com/rakyll/helloworld/main.go:4 +0x1b
```

But on darwin/arm64, the process doesn't panic and keep running.

**Comment by minux** [comment]
This is working as intended. darwin/arm64 always uses
cgo (because it has to use external linking), and deadlock
detector is effectively disabled in cgo programs (even though
all the goroutines might be blocked, external code could
still be running and might wake the goroutine up with cgo
callbacks).

If you run this program on darwin/amd64, the result will be
the same:

package main
import _ "runtime/cgo" // force cgo
func main() {
    select {}
}

**Comment by rakyll** [comment]
Sorry, thanks for the brief explanation. I totally omitted the fact that CGO is auto enabled.
