### ISSUE TITLE
x/tools/cmd/vet: check for time.Sleep(1)

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11137]
I recently had a problem that was due to my writing time.Sleep(2), and thinking that it would sleep for 2 seconds, when it actually sleeps for 2 nanoseconds.  It's fairly unlikely that anybody really wants time.Sleep(some small constant).  We should consider having vet check for this.

**Comment by josharian** [comment]
Nice idea; this bites me too. I'll write a prototype and see what it turns up.

**Comment by josharian** [comment]
/cc @robpike for opinions

CL 10882 has a quick-and-dirty implementation. It looks for durations that are integer literals, i.e. that are missing units. The idea is that if someone went to the trouble of writing `1 * time.Nanosecond`, they probably mean it, and that if someone wrote `1e9`, the code would be much clearer if they used `time.Second`.

It allows things like `time.Duration(30)`, because most instances of that I encountered were of the form `time.Duration(30) * time.Second`. The explicit conversion is unnecessary, but it is clear and probably correct.

This check flags a few instances inside the standard library:

```
flag/flag_test.go:104: time.Duration without unit: 7
time/internal_test.go:34: time.Duration without unit: 1
time/sleep_test.go:76: time.Duration without unit: 1
time/sleep_test.go:124: time.Duration without unit: 1
time/sleep_test.go:430: time.Duration without unit: 1
time/tick_test.go:70: time.Duration without unit: 1
time/time_test.go:330: time.Duration without unit: 1
time/time_test.go:958: time.Duration without unit: 1
time/time_test.go:987: time.Duration without unit: 1
time/time_test.go:988: time.Duration without unit: 1000
time/time_test.go:1005: time.Duration without unit: 1
time/time_test.go:1006: time.Duration without unit: 60000000000
time/time_test.go:1023: time.Duration without unit: 1
time/time_test.go:1024: time.Duration without unit: 3600000000000
```

I think that these would all be clearer with a unit.

Running it over a large open source corpus flags a whole bunch of code. I didn't see anything that was obviously a bug, although most of the code flagged would definitely benefit from units; `time.Second` is much nicer than `1e9`.

(Incidentally, since vet has moved into the main repo, I've changed the milestone from Unreleased to Unplanned.)

**Comment by josharian** [comment]
Restricting to small values (< 100) as originally suggested does seem to uncover some bugs, such as this one:

```go
var updateInterval = flag.Duration("interval", 10, "The number of seconds between each poll to etcd.")
```

There are still significantly more false positives (in the sense of the code being correct, even if not clear) than bugs. These seem to show up mostly in test code.

**Comment by josharian** [comment]
Due to a high false positive rate, this probably belongs in lint if anywhere. https://github.com/golang/lint/issues/130
