### ISSUE TITLE
cmd/go: Test exports should be visible to tests in other packages

### ISSUE THREAD

**Issue by willfaught** [golang/go#11198]
My particular scenario is exporting a test suite (like from testify) per package, so they can be run individually as unit tests, but also aggregated together for integration tests.

**Comment by minux** [comment]
That means when compiling the test for one package, you need to recompile
all its dependencies (to get the test exports).

**Comment by willfaught** [comment]
Perhaps test binaries can be cached in $GOPATH/pkg like non-test ones (if they aren't already, I don't know).

**Comment by minux** [comment]
You can already simulate this with build tags.

Just put the test exports that need to be accessed
by other packages in a file guarded by "// +build test",
and use go test -tags test somepkg to test.

**Comment by willfaught** [comment]
Thanks for the workaround. This probably involves either documenting and communicating how this works to the rest of my team, or requiring the team use a make file to test. Neither are great for obvious reasons. Ideally this would be possible through a plain "go test" command.

**Comment by rsc** [comment]
Test exports should not be visible to tests in other packages. This is by design. What you expose for your own tests might be very different from what you want to expose for other clients, even clients writing tests. 

Put another way, tests are only for the package author. Anything used by other packages is public API.
