### ISSUE TITLE
runtime: on PPC64x, arm64, mips64x time.Now precision is in microseconds, not nanoseconds

### ISSUE THREAD

**Issue by laboger** [golang/go#11222]
libgo/runtime/go-nanotime.c calls gettimeofday which only provides microsecond precision, not the nanosecond precision that is documented for Time.

Here is a testcase that demonstrates the problem.  I built it using gccgo from the latest gcc5 branch, and I can see the libgo code for go-nanotime.c is the same in trunk so would expect the same behavior there.  The problem occurs on ppc64le and x86 with gccgo; did not try ppc64 but would expect that behavior there too.   Problem does not occur with golang.

```go
package main

import (
        "fmt"
        "time"
)

const (
        defaultTimeOut = 30
)

func abort(start time.Time, timeOff time.Duration) bool {
        since := time.Since(start)
        now := time.Now()
        fmt.Printf("start: %s since: %d now: %s\n", start.String(), since, now.String())
        return timeOff.Nanoseconds()+time.Since(start).Nanoseconds() > (time.Duration(defaultTimeOut) * time.Second).Nanoseconds()
}

func main() {
        cases := []struct {
                timeOff  time.Duration
                expAbort bool
        }{
                {time.Duration(1), false},
                {time.Duration(2), false},
                {time.Duration(10), false},
                {time.Duration(30), true},
                {time.Duration(40), true},
        }

        for _, c := range cases {
                s := c.timeOff * time.Second
                if a := abort(time.Now(), s); a != c.expAbort {
                        fmt.Printf("Duration %v, expected %v, was %v\n", c.timeOff, s, a)
                }
        }

}
```

```
start: 2015-06-15 13:09:04.675845 -0500 CDT since: 7000 now: 2015-06-15 13:09:04.675856 -0500 CDT
start: 2015-06-15 13:09:04.676307 -0500 CDT since: 0 now: 2015-06-15 13:09:04.676307 -0500 CDT
start: 2015-06-15 13:09:04.67633 -0500 CDT since: 0 now: 2015-06-15 13:09:04.676331 -0500 CDT
start: 2015-06-15 13:09:04.676351 -0500 CDT since: 1000 now: 2015-06-15 13:09:04.676352 -0500 CDT
start: 2015-06-15 13:09:04.676373 -0500 CDT since: 0 now: 2015-06-15 13:09:04.676374 -0500 CDT
```

The value of 0 occurs intermittently for the "since" value in the output due to the lack of precision.

Could clock_gettime be called instead to get nanosecond precision?

**Comment by laboger** [comment]
Originally I opened this as gccgo only, but now I see it applies to golang as well.  The time.now function in sys_linux_ppc64x.s is calling gettimeofday which only has microsecond precision instead of nanosecond precision like Time is supposed.

**Comment by ianlancetaylor** [comment]
This is now fixed on gccgo mainline but the problem remains for the GNU/Linux targets arm64, mips64x, ppc64x.  They should call clock_gettime, not gettimeday.

**Comment by tophj-ibm** [comment]
As of go1.7rc3, I'm still seeing this as an issue, at least on ppc64le. Running the same test as above gives.
```sh
start: 2016-07-27 14:21:51.111599 +0000 UTC since: 0 now: 2016-07-27 14:21:51.1116 +0000 UTC
start: 2016-07-27 14:21:51.112122 +0000 UTC since: 1000 now: 2016-07-27 14:21:51.112124 +0000 UTC
start: 2016-07-27 14:21:51.112142 +0000 UTC since: 1000 now: 2016-07-27 14:21:51.112144 +0000 UTC
start: 2016-07-27 14:21:51.112162 +0000 UTC since: 260000 now: 2016-07-27 14:21:51.112423 +0000 UTC
start: 2016-07-27 14:21:51.112441 +0000 UTC since: 1000 now: 2016-07-27 14:21:51.112443 +0000 UTC
```

**Comment by mwhudson** [comment]
The bug is still open so that's not very surprising?

**Comment by laboger** [comment]
We're going to look into fixing this for ppc64x.  Just wondering if there was any additional information to share on this.  We don't know if it is only wrong for ppc64x or still incorrect on the other platforms mentioned above.

**Comment by vogtd** [comment]
I don't actually get where it is required that timestamps in Time format returned by time.Now() have actually nanosecond precision.  Certainly not here:
https://golang.org/pkg/time/#Now

**Comment by bradfitz** [comment]
@vogtd, it's not required. It's nice.

**Comment by clnperez** [comment]
And also would be consistent between platforms. :+1:

**Comment by vogtd** [comment]
All right, so it's rather an improvement request than a bugreport.

I'm a bit lost about about the status regarding s390[x]:
* Is it already fixed in Golang for s390[x] (or was it an issue there at all)?
* If it's been fixed already, will that fix trickle down automatically into the Gofrontend or should I make a patch for that?

**Comment by billotosyr** [comment]
It is not yet fixed in golang for s390x.

**Comment by ianlancetaylor** [comment]
@vogtd The gofrontend used by gccgo uses different code to get the time.  It already returns nanosecond precision for `time.Now` on s390 (by calling `clock_gettime(CLOCK_REALTIME, ...)`).

**Comment by justincormack** [comment]
@ianlancetaylor interested in the case of s390x on 1.7 ie not using gccgo, as that is what we are using now.

**Comment by rsc** [comment]
Ian says gccgo is already OK. I assume it uses clock_gettime(CLOCK_REALTIME) always.

As for the gc toolchain, I surveyed all the time.now implementations in runtime/*.s:

- darwin/386: kernel time equation + RDTSC, fallback to gettimeofday (microsecond)
- darwin/amd64: kernel time equation + RDTSC, fallback to gettimeofday (microsecond)
- darwin/arm: gettimeofday (microsecond)
- darwin/arm64: gettimeofday (microsecond)
- dragonfly/amd64: clock_gettime(CLOCK_REALTIME) (nanosecond)
- freebsd/386: clock_gettime(CLOCK_REALTIME) (nanosecond)
- freebsd/amd64: clock_gettime(CLOCK_REALTIME) (nanosecond)
- freebsd/arm: clock_gettime(CLOCK_REALTIME) (nanosecond)
- linux/386: clock_gettime(CLOCK_REALTIME) (nanosecond)
- linux/amd64: vdso_clock_gettime(CLOCK_REALTIME) (nanosecond) if available, or else vdso_gettimeofday (microsecond)
- linux/arm: clock_gettime(CLOCK_REALTIME) (nanosecond)
- linux/arm64: gettimeofday (microsecond)
- linux/mips64x: gettimeofday (microsecond)
- linux/ppc64x: clock_gettime(CLOCK_REALTIME) (nanosecond)
- linux/s390x: clock_gettime(CLOCK_REALTIME) (nanosecond)
- nacl/386: clock_gettime(CLOCK_REALTIME) (nanosecond)
- nacl/amd64p32: clock_gettime(CLOCK_REALTIME) (nanosecond)
- nacl/arm: clock_gettime(CLOCK_REALTIME) (nanosecond)
- netbsd/386: clock_gettime(CLOCK_REALTIME) (nanosecond)
- netbsd/amd64: clock_gettime(CLOCK_REALTIME) (nanosecond)
- netbsd/arm: clock_gettime(CLOCK_REALTIME) (nanosecond)
- openbsd/386: clock_gettime(CLOCK_REALTIME) (nanosecond)
- openbsd/amd64: clock_gettime(CLOCK_REALTIME) (nanosecond)
- openbsd/arm: clock_gettime(CLOCK_REALTIME) (nanosecond)
- plan9/386: nsec (nanosecond)
- plan9/amd64: nsec (nanosecond)
- plan9/arm: nsec (nanosecond)
- solaris/amd64: clock_gettime(CLOCK_REALTIME) (nanosecond)
- windows/386: read from kernel memory (100 nanosecond)
- windows/amd64: read from kernel memory (100 nanosecond)

On OS X, there is no nanosecond system call. If the kernel equation is not available, the only fallback is gettimeofday (microseconds).

On Linux, arm64 and mips64x should use clock_gettime(CLOCK_REALTIME). That's easy since there is assembly for clock_gettime(CLOCK_MONOTONIC) already that I can copy. I sent CL 32177 for those.

Otherwise it looks like everything is fetching nanosecond precision already.

Of course, precision does not imply accuracy. I doubt that windows is updating the kernel memory copy of the current time every 100ns, for example, and invoking a clock_gettime(CLOCK_REALTIME) system call to fetch the time at nanosecond accuracy may itself take 10s or 100s of nanoseconds. In fact precision does not even imply precision. There's no guarantee that the kernel is even computing nanoseconds during the system call. It might always come back with only microseconds, for example. But that's not Go's problem.
