### ISSUE TITLE
x/pkgsite: support linked examples

### ISSUE THREAD

**Issue by adg** [golang/go#11397]
Reviewing [this CL](https://code-review.googlesource.com/#/c/2943/4/storage/example_test.go) I saw a cute thing done with related examples. In short:

```
func Example_a() int {
    return 42
}

func Example_b() {
    n := Example_a()
    fmt.Println(n)
}

func Example_c() {
    n := Example_a()
    fmt.Println(n)
}
```

It might be helpful for godoc to recognize this and show the user that the latter examples continue from the first one. I'm not sure exactly how that might look, but it's something to think about.

**Comment by meirf** [comment]
I think the "dependency" should only be revealed when the example is revealed. Currently non-runnable examples just show "Code:" and then the block of code within the examples. Dependencies (there could be more than one) could be shown just above "Code:":

> Dependencies: [DB.Query](https://golang.org/pkg/database/sql/#example_DB_Query), [DB.QueryRow](https://golang.org/pkg/database/sql/#example_DB_QueryRow)
> Code:
> ...

To determine what the dependencies are we would have to choose between the user including some metadata (eg via comment) or by parsing the code.

Also it's not clear to me whether the current go official convention is to condone examples (even non-runnable ones) to `return` as Example_a does here. Perhaps we're totally fine with it. I noticed that GoLand gives a warning for this so I've created an issue with them: https://youtrack.jetbrains.com/issue/GO-5726 to determine if the warning is because of go or a bug on their end.

@agnivade ccing you since you've worked on godoc UI recently. (I assume you might not have seen this in the backlog due to its age or because the title uses "go/doc" instead of the more recent x/tools/cmd/godoc. Perhaps we should change the title to make this more easily searchable.)

**Comment by agnivade** [comment]
> I assume you might not have seen this in the backlog due to its age or because the title uses "go/doc" instead of the more recent x/tools/cmd/godoc

The latter :smile: 

>  I'm not sure exactly how that might look

Neither do I. I can't see how this "linking" is going to be helpful, whatever that's supposed to look like. It's fine to use an `Example` function like a normal Go function and return from it. But it might be cleaner not to glean any special meaning out of it and just let it be.

**Comment by meirf** [comment]
> It's fine to use an Example function like a normal Go function and return from it.

Looks like it's actually against go vet (probably [`-test`](https://golang.org/cmd/vet/#hdr-Tests_and_documentation_examples)) to have an example return anything:

`./example_test.go:5: Example_a should return nothing`

I don't know if this means we should close this issue, but if we want to keep it open go vet would need to be relaxed.

**Comment by seankhliao** [comment]
let's close as the vet check has been there for a long time.
