### ISSUE TITLE
encoding/json: incorrect handling of tagged anonymous fields

### ISSUE THREAD

**Issue by mxk** [golang/go#11408]
go1.4.2 windows/amd64

https://play.golang.org/p/YGsBuS5Acz

The json package documentation says "an anonymous struct field with a name given in its JSON tag is treated as having that name, rather than being anonymous." I expected the same encoding of both structs in the example above. The same problem exists when unmarshaling values, which is how I bumped into this in the first place.

**Comment by nodirt** [comment]
This happens because `time.Time` implements `json.Marshaler`: https://godoc.org/time#Time.MarshalJSON

As a result, `S1` "inherits" JSON marshalling of the embedded `time.Time`.

I assume you embed `time.Time` because you want to have all its methods in `S1`. An alternative to making `time.Time` a named field is to override `MarshalJSON` and `UnmarshalJSON` in `S1`:

```go
func (s S1) MarshalJSON() ([]byte, error) {
  return json.Marshal(S2{s.Time, s.Value})
}

func (s S1) UnmarshalJSON(data []byte) error {
  var s2 S2
  err := json.Unmarshal(data, &s2)
  s.Time = s2.Time
  s.Value = s2.Value
  return err
}
```

It works https://play.golang.org/p/FGjjXIdOWY

**Comment by minux** [comment]
Working as intended.
