### ISSUE TITLE
runtime: fatal error: free list corrupted

### ISSUE THREAD

**Issue by mikioh** [golang/go#11411]
See http://build.golang.org/log/b299c1d60cfc629928282e042e2cbcb1277b4101
Hope this is a NaCl-specific issue.
```
--- FAIL: TestTraceStressStartStop (0.91s)
	trace_test.go:365: failed to parse trace: g 85 is not running while GoBlock (offset 133954, time 75555878)
runtime: free list of span 0xfeec8b88:
0x10da7420 -> 0x75da75e0 (BAD)
fatal error: free list corrupted

runtime stack:
runtime.throw(0x28a738, 0x13)
	/tmp/workdir/go/src/runtime/panic.go:527 +0x100
runtime.mSpan_Sweep(0xfeec8b88, 0x0, 0x51, 0x5000)
	/tmp/workdir/go/src/runtime/mgcsweep.go:186 +0x960
runtime.sweepone(0x10900460, 0x10901260)
	/tmp/workdir/go/src/runtime/mgcsweep.go:97 +0x1c0
runtime.gosweepone.func1()
	/tmp/workdir/go/src/runtime/mgcsweep.go:109 +0x40
runtime.systemstack(0x0)
	/tmp/workdir/go/src/runtime/asm_amd64p32.s:215 +0xa0
(snip)
```

**Comment by aclements** [comment]
It just happened on 2015-06-29T16:07:14-434e0bc/openbsd-amd64-gce56: http://build.golang.org/log/a8139726d53bba365ad3e843efbf0886d559958b :(

It's happened twice so far on nacl:
2015-06-26T03:38:21-8628688/nacl-amd64p32: http://build.golang.org/log/b299c1d60cfc629928282e042e2cbcb1277b4101 (original report)
2015-06-26T18:54:11-77132c8/nacl-amd64p32: http://build.golang.org/log/e8d8fd09fa5e3bd5ba026308c0d19ec842a761b1

On nacl, both failures were in the runtime/pprof test. They were in different tests, but since this is a delayed effect, that's not surprising. On openbsd, it happened in when linking test/fixedbugs/issue8961.go (so the actual test is probably immaterial).

**Comment by rsc** [comment]
Still happening?

**Comment by aclements** [comment]
We haven't seen this since the three failures in my comment and we've fixed at least two memory corruption issues since the last occurrence (8c3533c and cc8f544). I'm closing, but of course please reopen if it happens again.
