### ISSUE TITLE
cmd/compile/ssa: mark if { panic } blocks as unlikely

### ISSUE THREAD

**Issue by josharian** [golang/go#11451]
Given a block like

```go
if condition {
  // basic block
  panic(...)
}
```

we should mark `condition` as unlikely. Unlikely to make a huge difference, but many things in the runtime have guards like this; we may as well help the branch predictor. Inspired by CL 11541.

**Comment by josharian** [comment]
This should probably happen at the SSA stage, perhaps as part of a general branch prediction pass.

We should also make sure that SSA preserves likelihood hints passed in by the frontend.

**Comment by dr2chase** [comment]
Generalization (from years ago working on Java) -- everything post-dominated by (a) panic(s) is marked as unlikely.

In years past, people have proposed training neural networks to infer branch frequencies from program characteristics -- I recall a presentation by Ben Zorn where he showed how well a by-the-book evaluation worked, doing 20 trials of train-on-19-test-on-remaining-1, with the bonus unethical slide at the end where he does 20 trials of train-on-20 -- which is what all the compiler writers would use, because benchmarks.

**Comment by tzneal** [comment]
Is there any good way to determine what function the Aux value of an OpStaticCall refers to?   I'm working on a branch prediction pass that works the way David suggested (branches to blocks post-dominated by a panic are unlikely). 

CC @randall77

**Comment by josharian** [comment]
(general advice) Poke around syntax.go. Request docs/clarification as desired. Off the top of my head, you probably want `v.Aux.(*Node).Func.Nname.Sym.Name` and `....Sym.Pkg.Path`, but take those with a grain of salt.
