### ISSUE TITLE
cmd/go: make git repo special-casing more generic

### ISSUE THREAD

**Issue by josharian** [golang/go#11458]
I propose that in addition to the list of well-known domains, `go get` use the following heuristic to identify cases in which `git` is the right vcs: Split the domain into components. If any component is exactly "git" or "github", assume it is a git repo. This would cover git.apache.org (#10797) as well as most GitHub Enterprise installations.

10 of the 84 domains at found at godoc.org fit this pattern, so this provides pretty decent coverage.

Thoughts?

/cc @adg @bradfitz

**Comment by adg** [comment]
Would this address enterprise GitHub installations?

**Comment by josharian** [comment]
It would address every GitHub Enterprise installation I've encountered, because basically everyone puts theirs at github.mycompany.com.

**Comment by adg** [comment]
Sounds good to me. Having trouble seeing a downside.

**Comment by kostya-sh** [comment]
@josharian #10797 issue is different though it might be hard to understand from the ticket itself.

Currently (with Go 1.4) Git repos from git.apache.org are correctly cloned using `git://` schema.

Go 1.5 treats `git://` as insecure and tries to clone it using `https://` by default. However it doesn't resolve the repo URL properly. For example the correct repo URL for `git.apache.org/thrift.git/lib/go/thrift` package should be `https://git.apache.org/thrift.git` while the current code resolves it to `https://git.apache.org/thrift/`.

https://go-review.googlesource.com/#/c/10092/ fixes this problem.

**Comment by rsc** [comment]
This doesn't work. In addition to knowing to use git, you also have to know
how to split the path into the repository root URL and the directory within that repo.
For example for github.com/rsc/foo/bar/baz, we know (because it's github)
that the repo is always the first three elements, so github.com/rsc/foo, and the
directory is the rest. 

For other git servers it's far from clear that the rule would always be the first 
three elements just like github.

It's of course already possible to put a .git into the import path to specify the
split point, at which point no well-known domain is needed.
