### ISSUE TITLE
path/filepath: document that filepath.Join("c:", "a") returns `c:\a` not `c:a` on Windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11551]
This program:
```
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Join("a"))
	fmt.Println(filepath.Join("c:", "a"))
}
```

displays:
```
C:\dev\src\foo>go run main.go
a
c:\a

C:\dev\src\foo>
```

but should display:
```
C:\dev\src\foo>go run main.go
a
c:a

C:\dev\src\foo>
```
or
```
C:\dev\src\foo>go run main.go
a
c:.\a

C:\dev\src\foo>
```

Alex

**Comment by jhoonb** [comment]
No...
the doc says:
"The returned path ends in a slash only if it represents a root directory, such as "/" on Unix or `C:\` on Windows." 
http://golang.org/pkg/path/filepath/#Clean

See code: 
http://golang.org/src/path/filepath/path.go?s=2213:2243#L71

**Comment by akavel** [comment]
Related thread: https://groups.google.com/forum/#!topic/golang-nuts/xFWpetTOPp4

**Comment by xiofen** [comment]
Whatever the correct or preferred behaviour is I would request that the documentation for filepath.Join be made clearer.

There's an ambiguity on the behaviour of filepath.Join("a:",x) as to whether an absolute or relative path is returned. I could look at the code, but that's not the point.

 the docs state ".adding a Separator if necessary.." - in the ambiguous case a separator isn't necessary.

Better to state "adding a separator between all elements" (for the current behaviour)

**Comment by alexbrainman** [comment]
@xiofen I am no good at writing documentation. So, if you feel strongly about it, suggest you own change - http://golang.org/doc/contribute.html

Thank you.

Alex

**Comment by jhoonb** [comment]
I agree

**Comment by mattharden** [comment]
Perhaps "adding a separator if one is not already present"

**Comment by xiofen** [comment]
Sorry, somehow I missed the inventing emails.

If non-one has already altered the documentation , then as per mattharden

*Join joins any number of path elements into a single path, adding a Separator between all elements. The result is Cleaned, in particular all empty strings are ignored.*

I'd be tempted make the 'gotcha' explicit - eg from the discussion (Daniel Theophanes)  *"However if you join "D:" to "a", it assumes you want an absolute path."*  to do this could say "no terminal separator is added" 

*Join joins any number of path elements into a single path, adding a file separator between all elements. No terminal separator is added. The result is Cleaned, in particular all empty strings are ignored.*

Sorry no good at documentation

**Comment by alexbrainman** [comment]
@minux and me disagree about https://go-review.googlesource.com/#/c/11882 change. We need more reviewers to lean us one way or the other. Please help. Thank you.

Alex

**Comment by Thomasdezeeuw** [comment]
Although I do think the new behaviour is better, I also think this is a breaking change. So this should be a no-go for Go1.x.

**Comment by ianlancetaylor** [comment]
I don't see a clear justification for the change in CL 11882.  I see the logic in it, but the function was never documented to work that way, and it could clearly break existing programs.  I think we should document the current behavior, as this issue suggests.

**Comment by mattharden** [comment]
Intuitively, I see filepath.Join as giving the path you would get if you did a Chdir to each path in sequence (without looking at the filesystem, so you could end up with a relative path). On Windows if I Chdir("c:") and then Chdir("abc") I end up in the same place as if I did Chdir("c:abc"). This is different from Chdir(`c:\abc`) because on Windows you have a working directory for each drive letter.

I don't have any valid intuition about the current behavior. It strikes me as just a symbol manipulation that makes Unix-specific assumptions even though filepath is supposed to be a cross platform module.

Although it could break existing code, I suspect any such existing code is already buggy, and this change would make it less buggy.

**Comment by minux** [comment]
@mattharden, the intuition is wrong if there is .. in the sequence
and symlinks are involved.

And indeed, filepath.Join is just symbolic manipulation. You can
imagine that we  implement filepath.Join in a way you described
(chdir into each element, and then return the current directory),
but that's not how filepath.Join currently works.

I wouldn't call existing code as buggy. People might look at our
test cases and assume that filepath.Join("C:", "Windows")
returning "C:\Windows" is the expected behavior of filepath.Join
and then rely on that. If we don't have such a test case, then
perhaps we can argue that it's unintended behavior. But with
that test case, I don't think we can call the behavior buggy as
we basically told people it's the intention.

**Comment by xiofen** [comment]
To qualify a possible real issue with the current behaviour / and/or a need to improve the description in the docs  - this program is illustrative

```
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	a, b, c := "c:", "x", "y"
	fmt.Println(filepath.Join(filepath.Join(a, b, c)))
	fmt.Println(filepath.Join(filepath.Join(a, b), c))
	fmt.Println(filepath.Join(filepath.Join(a), b, c)) //this one is different 
	fmt.Println(filepath.Join(a, filepath.Join(b), c))
	fmt.Println(filepath.Join(a, b, filepath.Join(c)))
}
```
 This issue is practically easily fixed easily, but the potential problem is not obvious from a reading of the docs.

At another level there is an issue with the behaviour - many reasonable people might expect the above program give the same output ie expectations of deterministic behaviour.

Personally I'd prefer a change in behaviour to for the above reason - it's a subjective call.

**Comment by xiofen** [comment]
An addendum - I just noticed these two lines give different output too 
```
fmt.Println(filepath.Join(filepath.Join(a), b, c))     //
fmt.Println(filepath.Join(filepath.Join(a, ""), b, c)) //different to above - do not like
```

**Comment by alexbrainman** [comment]
Thanks to everyone for their input. It seems to me I don't have support for my change. I just want to clarify my reasoning (before I abandon my change). With this code:
```
a := ...
b := filepath.Join(a, ...)
```
If "a" contains absolute path (filepath.IsAbd(a) returns true), should I expect "b" to contain absolute path?

If "a" contains relative path (filepath.IsAbd(a) returns false), should I expect "b" to contain relative path?

The answers to these questions are "yes" on unix. Not so on windows. This program http://play.golang.org/p/_DOiToc8cD prints:
```

a is "c:\\" and filepath.IsAbs(a) is true
b is "c:\\file.txt" and filepath.IsAbs(b) is true

a is "c:" and filepath.IsAbs(a) is false
b is "c:\\file.txt" and filepath.IsAbs(b) is true
```

I think that this invariant is important. If only because Go team developers (none of who use windows) assume that invariant is there. So no amount of documenting will stop them (and others) from making mistakes.

Alex

**Comment by ianlancetaylor** [comment]
@alexbrainman To be clear, I agree with your rationale, and if we were designing this function now, that is how it should work.

But that's not the question we are facing.  The question is: given that the function has behaved as it presently does since before the Go 1 release, should we change it?  The current behaviour is meaningful, is not always wrong, and is easy to avoid if you know about it.  Given that, it's hard for me to support a change that may silently break some currently working programs.

**Comment by mattn** [comment]
If the interface is like below, I agree with your opinion.

```
func MakePath(drive string, elems... string) string
```

But this is `Join` that mean joining the given path and path independently.
```
C:\dev\src\foo>go run main.go
a
c:\a

C:\dev\src\foo>
```
So I'm thinking this is right.
