### ISSUE TITLE
runtime: reconsider periodic GC heuristic

### ISSUE THREAD

**Issue by aclements** [golang/go#11637]
4b2774f made sysmon-triggered GC concurrent instead of STW. This means that sysmon will asynchronously signal the forcegc helper, which will asynchronously trigger concurrent GC. Prior to this CL, the forcegc helper synchronously ran a STW GC, which is why we needed the forcegc helper. Now it's unnecessary and sysmon should just trigger concurrent GC directly. This isn't entirely trivial: sysmon can't simply call startGC(gcBackgroundMode) because the bail-out condition at the top of startGC will trigger and nothing will happen.

Another possibility is to simple eliminate the sysmon-triggered GC.

**Comment by randall77** [comment]
I think we still want a sysmon-triggered gc.  We need it so that a program that allocates a bunch and then stops will have its unused memory returned to the OS.

**Comment by RLH** [comment]
Yes, we should note in the code that the concurrent GC might take more than
one cycle to discover the unused memory. Basically because the sweep that
discovers the empty spans happens after the GC that does not mark it.
I now believe we should leave the trigger in so
LGTM

**Comment by RLH** [comment]
We need to justify sysmon triggering. I did a quick literature search of Java. It appears that Java's RMI implementations force GCs every hour. The rationalization is that distributed GCs are needed but without periodic local GCs dead objects can survive too long and cause a lot of grind for the other local GCs.
The periodic GCs used to happen every minute, now they happen every hour.
I will also note that if the application wants periodic GCs then kicking off a Goroutine that sleeps for some time, say an hour, before calling runtime.GC().

The only justification I can find is so that the GC has a chance to return memory to the OS, and perhaps is helps force finalizers to run sooner. Neither seem to be a good enough reason to fire off an asynch GC.

**Comment by aclements** [comment]
Originally this issue was about simply eliminating the unnecessary go-between goroutine for sysmon-triggered GC, but it turns out that with the decentralized GC we actually need that goroutine to be responsible for performing the GC start transition now that it's not handled by a central coordinator and can't be done in the P-less sysmon thread.

However, there's still the issue of whether periodic GC needs a better heuristic, so I'm re-milestoning and re-titling this to "runtime: reconsider periodic GC heuristic."

**Comment by rsc** [comment]
@RLH I don't think we can just turn off periodic GC. Returning memory to the OS was the motivation, and it's still important. (There was no consideration of distributed GC, since we have none.)

**Comment by rsc** [comment]
@aclements can you clarify what this issue is about in the title?

**Comment by rsc** [comment]
Ping. Do we need to do anything here? Getting a bit late for Go 1.6.

**Comment by aclements** [comment]
Since there haven't been any suggestions for what to replace the "after 2 minutes of not GC'ing" heuristic with, I'm closing this.

**Comment by crawshaw** [comment]
Several OSs have interfaces that could be used instead of a timing heuristic:
- iOS: [applicationDidReceiveMemoryWarning](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/applicationDidReceiveMemoryWarning:)
- Android: [onLowMemory](http://developer.android.com/reference/android/content/ComponentCallbacks.html#onLowMemory())
- Windows: [CreateMemoryResourceNotification ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366541(v=vs.85).aspx)

What's missing is a Unix story. I wonder, has anyone ever tried to measure memory pressure by counting page faults? (I realize disk swap is unusual in servers, but with zswap becoming a thing maybe page faults aren't a useless signal.)
