### ISSUE TITLE
runtime: panics during gc

### ISSUE THREAD

**Issue by zeebo** [golang/go#11640]
I recently upgraded one of our systems to use go1.5beta1 (b6ead9f) and observe this crash periodically:

```
panic: runtime error: index out of range
fatal error: panic holding locks
runtime: nonempty check fails b.log[0]= 0 b.log[1]= 0 b.log[2]= 0 b.log[3]= 0
fatal error: workbuf is empty
runtime: nonempty check fails b.log[0]= 0 b.log[1]= 0 b.log[2]= 0 b.log[3]= 0
fatal error: workbuf is empty

goroutine 28 [running]:
runtime.throw(0x93e588, 0x13)
	/home/jeff/go/src/runtime/panic.go:527 +0x78 fp=0x10e18e4c sp=0x10e18e40
runtime.gopanic(0x83a6b8, 0x10e20008)
	/home/jeff/go/src/runtime/panic.go:385 +0x2a4 fp=0x10e18e90 sp=0x10e18e4c
runtime.panicindex()
	/home/jeff/go/src/runtime/panic.go:12 +0x48 fp=0x10e18ea4 sp=0x10e18e90
runtime.(*gcWork).put(0x10e15328, 0x10f5d1c0)
	/home/jeff/go/src/runtime/mgcwork.go:87 +0x70 fp=0x10e18eb4 sp=0x10e18ea4
runtime.greyobject(0x10f5d1c0, 0x10f05200, 0x888, 0x10dea2e3, 0x0, 0xb69ae8f8, 0x10e15328)
	/home/jeff/go/src/runtime/mgcmark.go:898 +0x304 fp=0x10e18f00 sp=0x10e18eb4
runtime.scanobject(0x10f05200, 0x10e15328)
	/home/jeff/go/src/runtime/mgcmark.go:821 +0x294 fp=0x10e18f68 sp=0x10e18f00
runtime.gcDrainUntilPreempt(0x10e15328, 0x7d0, 0x0)
	/home/jeff/go/src/runtime/mgcmark.go:686 +0x1dc fp=0x10e18f94 sp=0x10e18f68
runtime.gcBgMarkWorker(0x10e14a00)
	/home/jeff/go/src/runtime/mgc.go:1261 +0x48c fp=0x10e18fd4 sp=0x10e18f94
runtime.goexit()
	/home/jeff/go/src/runtime/asm_arm.s:1016 +0x4 fp=0x10e18fd4 sp=0x10e18fd4
created by runtime.gcBgMarkStartWorkers
	/home/jeff/go/src/runtime/mgc.go:1173 +0x84
```

```
panic: runtime error: index out of range
fatal error: panic holding locks

goroutine 41 [running]:
runtime.throw(0x93e588, 0x13)
	/home/jeff/go/src/runtime/panic.go:527 +0x78 fp=0x10e1fefc sp=0x10e1fef0
runtime.gopanic(0x83a6b8, 0x10e20008)
	/home/jeff/go/src/runtime/panic.go:385 +0x2a4 fp=0x10e1ff40 sp=0x10e1fefc
runtime.panicindex()
	/home/jeff/go/src/runtime/panic.go:12 +0x48 fp=0x10e1ff54 sp=0x10e1ff40
runtime.(*gcWork).tryGet(0x10f6c928, 0x3cf54)
	/home/jeff/go/src/runtime/mgcwork.go:115 +0x9c fp=0x10e1ff68 sp=0x10e1ff54
runtime.gcDrainUntilPreempt(0x10f6c928, 0x7d0, 0x0)
	/home/jeff/go/src/runtime/mgcmark.go:681 +0x158 fp=0x10e1ff94 sp=0x10e1ff68
runtime.gcBgMarkWorker(0x10f6c000)
	/home/jeff/go/src/runtime/mgc.go:1261 +0x48c fp=0x10e1ffd4 sp=0x10e1ff94
runtime.goexit()
	/home/jeff/go/src/runtime/asm_arm.s:1016 +0x4 fp=0x10e1ffd4 sp=0x10e1ffd4
created by runtime.gcBgMarkStartWorkers
	/home/jeff/go/src/runtime/mgc.go:1173 +0x84
```

It's running on a GOOS=linux GOARCH=arm GOARM=5 system. It's a large program so I can't provide a simple reproduction at this time, but I can do my best to give any information that might be helpful, including running any diagnostics you ask for.

**Comment by ianlancetaylor** [comment]
CC @RLH @aclements

**Comment by aclements** [comment]
I'm not sure about the "index out of range", but "workbuf is empty" has happened a few times on the dashboard:

http://build.golang.org/log/4d7105aa956e30a136c581c484b1f2bfa95b102f (2015-06-19T00:44:13-2f3d103/freebsd-386-gce101)
http://build.golang.org/log/326b99e52a01821104fee8c4876747b4e5c71c34 (2015-06-24T17:53:25-7708248/dragonfly-amd64)
http://build.golang.org/log/6ab73292382bb07bb17cc8b0febcad0110339595 (2015-06-24T22:22:55-6613090/darwin-amd64)
http://build.golang.org/log/d48d254daec0fb8bd9d8cf24483cf824bf44dca0 (2015-06-26T17:26:09-e0e47e2/linux-arm-arm5)
http://build.golang.org/log/c91832b92d18c925e37c068b7a82a49d0e937f17 (2015-07-02T08:29:33-be2a3e2/linux-arm-arm5)
http://build.golang.org/log/fc7e8da4d904c0464b84516a9a100c2240ae3b88 (2015-07-09T20:05:33-4c33250/darwin-386)
http://build.golang.org/log/5606c2ad1639caa9a681957bf5efac37fc47e350 (2015-07-12T20:43:01-7e4c06d/darwin-386)

Given the variety of archs and OSs, this doesn't appear to be arch- or OS-specific. In particular, since it's also happening on x86, I don't think this is a memory ordering issue.

Where it happens is also scattered. It's often testing $GOROOT/test, but several are in test/run.go itself or the linker invoked by test/run.go. This makes me wonder if this is related to #11617.

I worked through an informal backwards proof that we're satisfying all of the invariants that *should* ensure checknonempty never fails in trygetfull or getfull. This depended on a few assumptions, like that the compiler is correct, that our lock-free list is correct (note that the above failures cover three different implementations of the platform-dependent part, so that's unlikely to be the problem), and that there's no memory corruption.

**Comment by aclements** [comment]
To clarify: the "no memory corruption" assumption is more specifically "no writes through bad pointers". We've had some memory corruption problems resulting from premature collection of reachable objects; that alone isn't sufficient except as a springboard for aliasing a pointer and a non-pointer, where the non-pointer happens to be the address of a workbuf, which is quite unlikely.

**Comment by aclements** [comment]
Another assumption I made is that the per-P gcWork cache is never accessed concurrently. That's perhaps the most likely assumption to be wrong.

**Comment by aclements** [comment]
@zeebo, are you able to reproduce this fairly reliably? Would you mind trying out https://go-review.googlesource.com/12124 and see if it fixes the problem for you? Otherwise I think we'll have to wait a week or so to see if it pops up on the dashboard again before declaring this fixed.

**Comment by zeebo** [comment]
Yeah, it's pretty reliable. I get 2-3 crashes per day at least. I'll try again with that change first thing tomorrow morning and report back.

**Comment by aclements** [comment]
@zeebo, did you get a chance to try it?

**Comment by zeebo** [comment]
Sorry, no. I'm doing it right now.

**Comment by zeebo** [comment]
It has been a day and I've seen no panics. Usually it happens by now, but you can never be sure with these things. :)

**Comment by aclements** [comment]
Great! Maybe give it another day and if it hasn't fallen over, we'll call this issue closed.

Thanks for testing!

**Comment by zeebo** [comment]
No problem. A picture is worth a thousand words, so here's a graph of the uptime with the go version the binary was compiled with:

![Uptime Graph](http://i.imgur.com/uWSY32G.png)

Green is go1.4.2, red is go1.5beta1, and blue is with the cherry picked change. The purple line is the uptime. It looks like what might have been triggering the restarts recently slowed down in the past few days for whatever reason, so yeah it's probably for the best to wait another day or two.

**Comment by zeebo** [comment]
![uptime](http://i.imgur.com/sGyU8cS.png)

Looks like no crashes in two days. I'd be happy with you closing this bug on the condition that I can reopen it if I observe it again over longer periods of time. :)

**Comment by aclements** [comment]
Awesome. Please do reopen if you observe it again.
