### ISSUE TITLE
cmd/go: test slow/not working

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#11683]
1. What version of Go are you using (go version)?

go version devel +b6ead9f Tue Jul 7 21:53:11 2015 +0000 windows/amd64

2. What operating system and processor architecture are you using?

Windows 7 64bit, Intel i7.

3. What did you do?

Tried to run `go test`.

4. What did you expect to see?

Report of the tests. Normally (go 1.4) within two seconds or so.

5. What did you see instead?

Nothing, after about 30 secs I killed the test and nothing got reported back. Sometimes I get (maybe 1 in 10 times):

```
exit status 2
FAIL    github.com/Thomasdezeeuw/markdown       15.857s
```

**Comment by ALTree** [comment]
> Tried to run go test.

On what? 

(`github.com/Thomasdezeeuw/markdown` seems to be private)

**Comment by ianlancetaylor** [comment]
If your tests take a long time to run, then "go test" is going to take a long time run.  That is definitely the first thing to investigate.

If you are absolutely certain that the problem is not in your code, then you need to give us a test case we can use to replicate the problem ourselves.  Otherwise there is nothing we can do.

**Comment by Thomasdezeeuw** [comment]
The code is indeed private at the moment, however normally the tests run fine in under two seconds. But even if the code is problem isn't there a timeout option normally?

**Comment by Thomasdezeeuw** [comment]
Running `go test timeout 2s`, it correctly timeouts. Could it be that 1.4 had a default timeout and 1.5 doesn't?

**Comment by ianlancetaylor** [comment]
Both Go 1.4 and 1.5 have a default timeout of 10 minutes.  However, I don't how that could be the issue here.  You seem to be suggesting that your tests complete quickly with Go 1.4 but sometimes hang with Go 1.5.  Look at http://tip.golang.org/doc/go1.5#runtime .  Is it possible that your tests or code are depending on a specific goroutine scheduling order?

**Comment by ALTree** [comment]
You could also try to run the test with the race detector on

`go test -race`

**Comment by Thomasdezeeuw** [comment]
I'm going to close this, running with a timeout is good enough for me.

**Comment by trichner** [comment]
In case anyone wonders why 'go test' takes forever (>10s) on a Windows machine with Avast, you might want to disable Avast's DeepScreen, it tries to sandbox the code and analyze your binary.

It took my way too long to figure this out. More details [here](https://forum.golangbridge.org/t/solved-slow-go-test-with-avast-on-windows-8-1/1272).
