### ISSUE TITLE
cmd/compile:Unexpected semicolon error

### ISSUE THREAD

**Issue by vikram06** [golang/go#11708]
i was try to run hello world program in http://play.golang.org/
what is different between???
func main() {
}
func main
{
}    
![go](https://cloud.githubusercontent.com/assets/5701382/8673555/30508494-2a55-11e5-91df-ae95a2744f0c.png)

![go1](https://cloud.githubusercontent.com/assets/5701382/8673557/377f259a-2a55-11e5-9ce7-8018284ebc31.png)

**Comment by snakeru** [comment]
Semicolons are inserted automatically in certain cases: https://golang.org/ref/spec#Semicolons

The second program is invalid, you *are not allowed* to have opening curly brace on a new line. This was introduced a few years ago and was an undesirable, but unavoidable side effect.
Since having opening curly brace on new line was against the style guide anyways, this was considered acceptable.

But the error text is misleading, I agree.

**Comment by snakeru** [comment]
Actually, no. The error says "unexpected semicolon **or newline** before {"

So that seems to be working as intended.

**Comment by ianlancetaylor** [comment]
This is not a bug.

In general, please ask questions on the golang-nuts mailing list, not on the issue tracker.  Thanks.
