### ISSUE TITLE
encoding/xml: simple use of EncodeToken fails

### ISSUE THREAD

**Issue by rsc** [golang/go#11719]
https://play.golang.org/p/DnUU5PWitz should not say 'empty buffer' unless I am very confused about how this package works.

	package main
	
	import (
		"bytes"
		"encoding/xml"
		"log"
	)
	
	func main() {
		log.SetFlags(0)
		var buf bytes.Buffer
		enc := xml.NewEncoder(&buf)
		if err := enc.EncodeToken(&xml.StartElement{Name: xml.Name{"", "object"}}); err != nil {
			log.Fatal(err)
		}
		if err := enc.EncodeToken(&xml.EndElement{Name: xml.Name{"", "object"}}); err != nil {
			log.Fatal(err)
		}
		enc.Flush()
	
		if buf.Len() == 0 {
			log.Fatal("empty buffer") // where did the tokens go!?
		}
	
		log.Print(buf.String())
	}

**Comment by dspezia** [comment]
EncodeToken expects a value, not a pointer. There is no default case in the type switch, that's why a token with "wrong" type is just ignored. We have different solutions to fix this:

- option 1: issue an error when the type is invalid (this includes pointers to valid tokens)
- option 2: like 1, but if a pointer is provided, just convert it to a value (one level only), and consider this value.
- option 3: like 1, but if a pointer or an interface is provided, drill down until a value is find, and then consider this value.

Submitting a CL to implement option 2, to be changed if another behavior is preferred.

**Comment by dspezia** [comment]
Following code review, option 1 is preferred over option 2 (for go1.5). CL changed accordingly.
