### ISSUE TITLE
runtime: bootstrap fails on linux/arm

### ISSUE THREAD

**Issue by mwhudson** [golang/go#11853]
For example, from https://launchpadlibrarian.net/212522322/buildlog_ubuntu-wily-armhf.golang_2%3A1.5~snap~upstream201507222050git92390e4ubuntu1_BUILDING.txt.gz

```
...
go/build
hash
crypto
crypto/sha1
debug/dwarf
debug/elf
cmd/go

##### Building packages and commands for linux/arm.
./make.bash: line 161: 10782 Segmentation fault      CC=$CC_FOR_TARGET "$GOTOOLDIR"/go_bootstrap install $GO_FLAGS -gcflags "$GO_GCFLAGS" -ldflags "$GO_LDFLAGS" -v std cmd
```

But I can reproduce it locally.  It's the fault of https://go.googlesource.com/go/+/77d38d9cbe9b4047e7155569e7b9485093807e17 ("runtime: handle linux CPU masks up to 64k CPUs"), but I don't understand why.

**Comment by mwhudson** [comment]
Oh well I think the reason is clear enough: this code attempts to put 8kb on the system stack, which is only 8kb on ARM. I don't know why that would be -- all other platforms have it as 64kb.

**Comment by crawshaw** [comment]
It looks like the 8kb system stack on arm has been around since the initial arm commit:

https://github.com/golang/go/blob/f52c02/src/runtime/arm/asm.s#L51

I cannot work out why it is so small. @mwhudson for Go 1.5 your change is probably the best minimal option, but for Go 1.6, should we bump the system stack to 64kb?
