### ISSUE TITLE
cmd/gofmt: align struct tags

### ISSUE THREAD

**Issue by pvinis** [golang/go#11857]
take this struct for example
https://github.com/go-gitea/gitea/blob/master/models/issue.go#L33

why not have all the `` under each other? so instead of having little blocks and some of them are in column 30, some in column 33 etc, why not all be in max column of those blocks, like say column 37?

**Comment by griesemer** [comment]
They are not aligned because they are not in an uninterrupted column. All the tags across a sequence of lines where each line contains a tag are aligned. As soon as a line doesn't have a tag, the "tag column" is terminated. This is very much the intent and a strategy applied everywhere throughout gofmt (the same applies for comments).

Working as intended.

**Comment by pvinis** [comment]
sure, i understand that. is there a reason why this way was chosen over the way i was describing?

**Comment by griesemer** [comment]
@pvinis The reason it works as it does is because there was no intent to make it work differently than any other alignment. It's the absence of making a (different) choice.
