### ISSUE TITLE
encoding/json: Change of behaviour when decoding json null values into RawMessage

### ISSUE THREAD

**Issue by gsalgado** [golang/go#11937]
https://github.com/golang/go/commit/1a99ba55df902a2657d1ccfc52a60024c22dba98 seems to have changed how json null values are decoded into json.RawMessages. After that commit a null value is decoded into an empty byte array whereas before they were decoded into []byte("null"), as can be seen here:

  https://play.golang.org/p/m4ubMyAcqL

**Comment by dspezia** [comment]
Confirmed. This CL has changed the behavior with json.RawMessages.

**Comment by dspezia** [comment]
The behavior change with json.RawMessage was not intended.

But the documentation says: "The JSON null value unmarshals into an interface, map, pointer, or slice by setting that Go value to nil." A json.RawMessage is a []byte, so setting it to nil (instead of [110 117 108 108]) seems to be in line with the documentation.

I'm not sure the original authors of this package consider a json.RawMessage should always have the same behavior than a []byte though.

**Comment by dspezia** [comment]
The CL has just been reverted anyway.

**Comment by OttoAllmendinger** [comment]
Some of my code has been hit by this bug. 

I'm relying on the fact that `json.RawMessage` decodes to the raw json literal, as explained in the Godoc

> [RawMessage] implements Marshaler and Unmarshaler and can be used to delay JSON decoding or precompute a JSON encoding.

If `null` decodes to `[]byte()`, that is no longer true.
