### ISSUE TITLE
x/build/watcher: mirror tags to github repo

### ISSUE THREAD

**Issue by adg** [golang/go#11954]
It appears that repository tags aren't being pushed to the GitHub repo from Gerrit (there's no `go1.5beta3` tag shown in the GitHub UI, for instance).

**Comment by rsc** [comment]
Is watcher updating github? Because so is my cron job.

Anyway, my cron job (by virtue of using --mirror) does push tags.
I checked by hand - they are all up to date on Github.

They appear here: https://github.com/golang/go/tags

They do not appear in the 'tags' tab of the 'branch' dropdown on the main golang/go page however. Maybe that page has a limit to the number of tags it will fetch, and it only grabs the oldest N. It also doesn't have things like release.r56. That seems like a Github problem, not our problem.

**Comment by adg** [comment]
The watcher is updating GitHub for all repos that appear on the build dashboard. I thought you knew this and had removed those from your cron job. (You can now.)

Closing this issue, agree that it's clearly a GitHub issue not ours.
