### ISSUE TITLE
proposal: pack small values into interface again.

### ISSUE THREAD

**Issue by funny-falcon** [golang/go#12128]
Reason: improve generic json/msgpack/etc marshalling performance

Go <1.4 packed small values (upto sizeof(uintptr_t)) into interface itself.
Go >=1.4 allocates this values separately to simplify GC.

I propose scheme which does not complicate GC much and allows to pack non-pointer small values (integers, doubles, small structs) into interface:

As I understand, currently type of memory location is described with 1bit mark:
  0 - non-pointer
  1 - pointer

I propose describing with 2bit mark:
  00 - non-pointer definitely
  01 - pointer definitely
  10 - interface `type` field
  11 - interface `value` field (perhaps, could be omitted)
So that, marker may distinguish interface `value` field kind (pointer/non-pointer) by analysing  interface type field.

To make this analysis fast, I propose to play with interface descriptor allocation:
  - interface descriptor of pointer type should be allocated as usual (with at least 16byte alignment)
    (the same for struct which contains one pointer)
  - interface descriptor for non-pointer type is allocated with 8byte offset from 16byte alignment.

So, GC marker may just analyse pointer stored in the interface `type` field: if it is 16bit aligned, then `value` field is a pointer, otherwise `value` is not a pointer.

Excuse me for disturbing if it were already discussed.

**Comment by RLH** [comment]
The runtime discussed it and our decision is part of 1.5 as you noted. The reasoning was that 1 bit per pointer sized word on a 64 bit machine is a 1.56% memory overhead. On a 32 bit machine it is twice that. We would need some numbers that would lead us to believe that this optimization will not only pay for itself in terms of memory savings but would also pay for itself in terms of a more complicated GC. Perhaps there is a clever bit encoding we have yet to discover but things are pretty crowded in the bit map. Feel free to reopen with supporting information.

**Comment by crawshaw** [comment]
An alternate way to pack non-pointers into an interface I've been mulling:

For each declared type in a program, designate a single pointer from an specially reserved address range. For these non-pointer values, pack the data into the first word, and the sentinel pointer into the second word.

Every type check has to look at both words instead of just the first. That is, to determine the type of an interface we ask:

1. Is the second word of the interface in the sentinel pointer range?
2. If so, look up the offset of the pointer and use that as the type. Use the first word as the data.
3. If not, use the first word as the type, and the second word as the data.

From the GC's perspective, pointers are always in the second word. No extra bits are needed, just extra work on an already-loaded cache line.

**Comment by funny-falcon** [comment]
it will simplify gc, but complicate runtime
