### ISSUE TITLE
Cast from int32 to uint64

### ISSUE THREAD

**Issue by saturn4er** [golang/go#12187]
a:= int32(-823050840)
fmt.Println(uint32(a), uint64(a))

Result: 3471916456 18446744072886500776

go version go1.4.2 windows/386

**Comment by randall77** [comment]
This is expected behavior.  From the spec:

When converting between integer types, if the value is a signed integer, it is sign extended to implicit infinite precision; otherwise it is zero extended. It is then truncated to fit in the result type's size. For example, if v := uint16(0x10F0), then uint32(int8(v)) == 0xFFFFFFF0. The conversion always yields a valid value; there is no indication of overflow.
