### ISSUE TITLE
fmt, log: messages are not appearing on device log for darwin/arm,arm64

### ISSUE THREAD

**Issue by rakyll** [golang/go#12194]
Update the x/mobile/example/basic.main to fmt.Println and log.Println.
```
...
func main() {
	fmt.Println("starting")
	log.Println("log starting")
...
```
Build and deploy the app to the device. Run `idevicesyslog`, launch the app.

The expected result is to see "starting" and "log starting messages" to appear, even though there is no output from the example app.

/cc @crawshaw @hyangah @nigeltao

**Comment by nigeltao** [comment]
Is it easy for you to check if those messages appear on Android instead of iOS?

**Comment by crawshaw** [comment]
On android we redirect stdout and stderr to logd (the system logger) because there is no way to get access to an app's stdout for debugging on a non-root android phone, the usual development environment.

But that's not so on iOS, where stdout and stderr fit neatly with starting an app from inside Xcode. The attached lldb picks them up and drops them neatly in the output window, interleaved correctly with results from NSLog.

So redirecting os.Stdout and os.Stderr as we do for android would be consistent but an unpleasant development experience, so I think the inconsistency is worth it.

For the log package, there's a question: should we mirror the output to the system log? (We can do so quite easily by calling log.SetOutput(io.MultiWriter(os.Stdout, ...)).) I think we should match the behavior of NSLog here. Does it go to both?

**Comment by hyangah** [comment]
NSLog writes to ASL. ASL provides an option to write the same log to stderr. (man asl_open)

**Comment by rakyll** [comment]
Are you sure that it is working? I can't see any log output.

$ go version
go version devel +b733234 Thu Aug 20 12:13:41 2015 +0000 darwin/amd64

**Comment by crawshaw** [comment]
I tested that a log.Printf line in example/basic appeared in the output of idevicesyslog, both starting from lldb and starting the app by clicking on the icon. What are you testing?

(Note that fmt.Printf will not appear in idevicesyslog, as per my comment earlier on this issue.)

**Comment by rakyll** [comment]
I unfortunately can't see the log.Printf output on my device log by starting app by clicking on the icon. This is the main function I am testing:

```
func main() {
	log.Printf("-----main called")

	//...
}
```

Do you need any additional information about my device?

**Comment by crawshaw** [comment]
Does your app import x/mobile/app?
Have you synced x/mobile past golang/mobile@ab223cf?

As this is a low priority issue, without a way to reproduce this I don't expect to get to this soon.

**Comment by rakyll** [comment]
I must have had an ASL faulty. I rebooted the device and I can see the messages are appearing on the log. Thanks.

**Comment by rakyll** [comment]
For anyone who comes across the same problem of not being able to see the logs, note that you need to relaunch idevicesyslog every time you launch a new application on the device.
