### ISSUE TITLE
x/playground: update to Go 1.5

### ISSUE THREAD

**Issue by rajender** [golang/go#12222]
http://golang.org/pkg/go/types/#example_MethodSet failing with following error. Seems like it is using older go version.

/tmp/sandbox407065635/main.go:6:2: cannot find package "go/importer" in any of:
	/usr/src/go/src/go/importer (from $GOROOT)
	/go/src/go/importer (from $GOPATH)
/tmp/sandbox407065635/main.go:9:2: cannot find package "go/types" in any of:
	/usr/src/go/src/go/types (from $GOROOT)
	/go/src/go/types (from $GOPATH)

**Comment by adg** [comment]
The playground hasn't been updated yet.

**Comment by rajender** [comment]
It is updated.

**Comment by rajender** [comment]
Getting another error...

2009/11/10 23:00:00 celsius.go:3:8: could not import fmt (can't find import: fmt)

**Comment by minux** [comment]
This is expected, that particular example needs to access the local filesystem
in order to resolve the imports, but the playground can't support that for
obvious reasons. You can run that example if served from your computer
(godoc -play -http localhost:6060)

The playground has already updated to Go 1.5, so closing.
