### ISSUE TITLE
compress/gzip: NewWriter doc clarity

### ISSUE THREAD

**Issue by bradfitz** [golang/go#12361]
The docs for gzip.NewWriter include:

> The Comment and Name header fields are UTF-8 strings in Go, but the underlying format requires NUL-terminated ISO 8859-1 (Latin-1). NUL or non-Latin-1 runes in those strings will lead to an error on Write.

But I'm not exactly sure what it's trying to say.

/cc @nigeltao @mdempsky @adg @dsymonds (not sure who owns this)

**Comment by minux** [comment]
@bradfitz: should we have a OWNERS file in the tree?
if you think it's reasonable, I will file a separate issue.
(actually I'm thinking that once an issue is triaged, the
gopherbot should automatically add /cc of the package
owner to the issue, and this should save us some work.
see also golang.org/cl/13475 for background)

**Comment by mdempsky** [comment]
I've never seen that comment before, and I agree it seems somewhat out of place at first impression.  Here's my understanding:

1. It's talking about the Comment and Name fields in gzip.Header.
2. Those fields are Go `string`s.
3. Canonically, Go `string`s are UTF-8, so they can represent any sequence of Unicode characters (including embedded NULs).
4. However, the underlying gzip file format only allows Comment and Name to contain the Unicode characters U+0001 through U+00FF (because it's actually Latin-1 with a NUL terminator).
5. If the Comment or Name fields contain other characters, then `gzip.(*Writer).Write` will return an error.

**Comment by bradfitz** [comment]
@minux, yes, it's probably time for something like that.
