### ISSUE TITLE
time.Parse not parsing PST properly

### ISSUE THREAD

**Issue by vivekmenezes** [golang/go#12388]
http://play.golang.org/p/NYza3grttO

As you see PST is landing up with an offset from UTC of 0!

The correct answer is as documented in

https://golang.org/src/time/example_test.go line 196

Thanks

**Comment by vivekmenezes** [comment]
This is in go 1.5

**Comment by ianlancetaylor** [comment]
The playground does not have timezone information.

Time zone names like PST are parsed based on your local timezone information. On my Ubuntu GNU/Linux system, I get the correct value because the file /usr/share/zoneinfo/PST8PDT exists. If a file like that  does not exist on your system, then the results are expected.

I'm closing this as expected, but please feel free to reopen if you disagree.

**Comment by vivekmenezes** [comment]
Sounds good.

// printed for 1970-2469 will apply as well to 2470-2869.  Even the days

Can you change the years on this line to 1970-2369 and 2370-2769

Thanks!

**Comment by minux** [comment]
The playground does have timezone.zip embedded in its
fake filesystem.

The reason the program doesn't work is because to interpret
a short time zone time, the time package needs to know
the location, and the playground doesn't have a default
location.

For example, if you specifically parse in a location where
PST make sense, it should work.

http://play.golang.org/p/hdv8x1WYXt

**Comment by ianlancetaylor** [comment]
Sent https://golang.org/cl/14034 .  Thanks.
