### ISSUE TITLE
cmd/go: relative path argument should not cause search

### ISSUE THREAD

**Issue by rsc** [golang/go#12385]
```
f$ pwd
/usr/local/google/home/rsc/src/code.google.com/p/rsc
f$ go install ./jfmt
can't load package: package code.google.com/p/rsc/jfmt: cannot find package "code.google.com/p/rsc/jfmt" in any of:
    /usr/local/google/home/rsc/go/src/code.google.com/p/rsc/jfmt (from $GOROOT)
    /usr/local/google/home/rsc/src/code.google.com/p/rsc/jfmt (from $GOPATH)
f$ 
```

There is no ./jfmt directory in this example. That should be the end. It should not figure out that I am in $GOPATH/src/code.google.com/p/rsc and go looking for code.google.com/p/rsc/jfmt in other work spaces.

**Comment by dominikh** [comment]
I've started looking into this.

The underlying issue happens in `cmd/go/pkg.go` around line 1570. The code attempts to turn something like `"./ioutil"` into `"io/util"`. The code is problematic because when specifying a path inside GOROOT or GOPATH, go/build will set ImportPath to a plausible import path. Whether the package actually exists isn't checked.

Thus, with `GOPATH=/go`, `ImportDir("/go/src/foo", 1)` will unconditionally set ImportPath to "foo".

I am wondering whether the ./ioutil -> io/ioutil rewrite is even a useful feature and whether the logic should be fixed, or removed entirely.

**Comment by rsc** [comment]
It's useful, it just shouldn't trigger a search. When you're in src/math and run go test ./rand you want to get math/rand not a relative import.

**Comment by rsc** [comment]
CL 16944 didn't work and was abandoned. (Writing this because I click on it every time I view this issue.) The actual fix is not obvious.

**Comment by bcmills** [comment]
This is fixed in module mode, but not in `GOPATH` mode.

```
_gopath/src/example.com$ go env GOPATH
/tmp/tmp.VrFzeLPnb6/_gopath:/tmp/tmp.Nz3gatY2ZI:/tmp/tmp.MZ8FiGUB8Q

_gopath/src/example.com$ GO111MODULE=off go install ./aoeuhtns
can't load package: package example.com/aoeuhtns: cannot find package "example.com/aoeuhtns" in any of:
        /usr/local/google/home/bcmills/go/src/example.com/aoeuhtns (from $GOROOT)
        /tmp/tmp.VrFzeLPnb6/_gopath/src/example.com/aoeuhtns (from $GOPATH)
        /tmp/tmp.Nz3gatY2ZI/src/example.com/aoeuhtns
        /tmp/tmp.MZ8FiGUB8Q/src/example.com/aoeuhtns

_gopath/src/example.com$ GO111MODULE=on go install ./aoeuhtns
can't load package: package example.com/aoeuhtns: unknown import path "example.com/aoeuhtns": cannot find package
```

**Comment by seankhliao** [comment]
The current error is:

```
go install ./doesntexist
stat /home/user/tmp/testrepo0928/doesntexist: directory not found
```
