### ISSUE TITLE
cmd/compile: escape analysis says shadowed variable that's copied gets leaked

### ISSUE THREAD

**Issue by dsnet** [golang/go#12389]
Using ```go1.5```

Compile the following package:
```go
package foo

func foo(str string) string {
	str = string([]byte(str)) // Make copy
	return str
}

func bar(str string) string {
	str2 := string([]byte(str)) // Make copy
	return str2
}
```

I currently see (unrelated lines removed):
```
$ go build -gcflags=-m foo.go
./main.go:3: leaking param: str to result ~r1 level=0
./main.go:8: bar str does not escape
```

I expect to see (unrelated lines removed):
```
$ go build -gcflags=-m foo.go
./main.go:3: foo str does not escape
./main.go:8: bar str does not escape
```

**Comment by rsc** [comment]
The variable is not "shadowed". It is reassigned. Escape analysis works on variables. One value assigned to the variable str does indeed escape. The result is therefore correct.

You might argue a broader point, that we should use a much more sophisticated escape analysis that works on values instead of variables, but I am skeptical that there's much evidence for that.

In any event when you really care about escape analysis results there is a clear workaround, as you've shown.

If you did use a shadowed variable that would work too:

	{
		str := string([]byte(str))
		return str
	}

Russ
