### ISSUE TITLE
cmd/link: incompatible with i386:x86-64 output

### ISSUE THREAD

**Issue by mattn** [golang/go#12448]
build app with linking go-sqlite3.

```
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\mattn\AppData\Local\Temp\go-link-872546559/000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
```
I'm on windows7 x86_64. Using head of master branch.

**Comment by ianlancetaylor** [comment]
What is GOARCH set to?

**Comment by ianlancetaylor** [comment]
E.g., `go env GOARCH`

**Comment by minux** [comment]
are you trying to build 32-bit windows program with
a 64-bit-only mingw gcc?

**Comment by mattn** [comment]
@ianlancetaylor 
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:/dev/go
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
@minux 
no. just building x86_64 app. if not link to go-sqlite3, it doesn't occur.

**Comment by ianlancetaylor** [comment]
@mattn You are somehow linking against a version of go-sqlite built using GOARCH=386, which fails because you are using GOARCH=amd64.  This normally shouldn't happen, as the different GOARCH value should store the package in a different location.  Can you run `go clean go-sqlite3` and then show us the output of `go install -x go-sqlite3`.  Perhaps that will suggest something.

**Comment by mattn** [comment]
Ah, I figure out. I put syso file in the directory. It contains windows resource objects.
Sorry.
