### ISSUE TITLE
cmd/cgo: `unexpected: 8-byte pointer type` errors with GOARCH=arm

### ISSUE THREAD

**Issue by jacobsa** [golang/go#12442]
I'm attempting to regenerate the darwin/arm code for golang.org/x/sys/unix from the latest iOS SDK, but running into a problem with `go tool cgo -godefs` on that architecture. Here is a file that reproduces the issue:

```Go
package blah

/*
typedef struct foo {
	void* a;
} foo_t;
*/
import "C"

type Foo_t C.struct_foo
```

Put that in `foo.go` and this happens:

    % GOARCH=arm go tool cgo -godefs foo.go
    /Users/jacobsa/go/src/golang.org/x/sys/unix/foo.go:10:12: unexpected: 8-byte pointer type - *void

I'm not sure what that message means in this context, since I haven't given `cgo` any input on the size of that pointer except by setting `GOARCH`. I wonder if I've misconfigured something, but can't find any relevant documentation so I'm not sure. It may be relevant that this doesn't happen when `GOARCH` is set to `386`.

This happens at tip on OS X:

    % go version
    go version devel +dd42eff Tue Sep 1 22:13:16 2015 +0000 darwin/amd64

**Comment by ianlancetaylor** [comment]
cgo works by building a C file, compiling it, and examining the debug info.  In this case it is complaining because it expects pointer types to have the size of a pointer.  For GOARCH=386 a pointer is obviously 4 bytes, but the debug info is indicating that the pointer is 8 bytes.

In order to use cgo in a cross-compilation situaiton like this one, you need to set CC tin the environment o a cross-compiler for ARM.  Look for "when cross-compiling" in https://golang.org/cmd/cgo .

I'm going to close this on the assumption that you didn't set CC.  Please reopen if I've misunderstood.

**Comment by jacobsa** [comment]
@iant: Thanks. Do you happen to know what an appropriate value of `CC` is for building arm and arm64 respectively on OS X?

**Comment by minux** [comment]
Use the wrapper in misc/ios/clangwrap.sh as CC for ios.

**Comment by jacobsa** [comment]
Whoa, that's exactly what I've been looking for this whole time! Thank you. :-)
