### ISSUE TITLE
x/tools/cmd/godoc: turn URL in struct comments to links

### ISSUE THREAD

**Issue by dsnet** [golang/go#12479]
This is already done for function comments, but it would be nice if URLs in struct, interface, and slice comments were turned into links as well.

See [crypto/tls.ClientHelloInfo](http://golang.org/pkg/crypto/tls/#ClientHelloInfo).

**Comment by rsc** [comment]
Comments inside struct { } and interface { } definitions and inside struct, interface, and slice literals are not doc comments. Godoc only reformats doc comments.

There is a long-standing issue that we should probably do better in general with comments inside top-level struct { } and interface { } definitions, since those are effectively the doc comments for individual fields.

Whether godoc should apply hyperlinking to arbitrary non-doc comments (such as inside slice literals) is much less clear.
