### ISSUE TITLE
html/template: escape first char for XML

### ISSUE THREAD

**Issue by alexandreStein** [golang/go#12496]
It looks like HTML template escape characters out of the variable.
In my case I tried to build a simple XML file, and the the first charset is escaped.
http://play.golang.org/p/PUylzjxJfW

It looks like a bug to me.

Best regards.

**Comment by bradfitz** [comment]
Probably because this is the HTML templating package and you're trying to produce XML. I suspect that it doesn't know how to parse the `<?foo>` directives with the question mark there.

You probably want to use the `text/template` package instead, if you're not going to be taking advantage of any of the HTML auto-escaping features.

/cc @robpike @adg to decide what (if anything) to do here.

**Comment by alexandreStein** [comment]
I made it with encoding/xml package but the behavior is not as expected.

**Comment by robpike** [comment]
I believe Brad answered the question. Use text/template not html/template, and escape manually.

**Comment by alexandreStein** [comment]
Ok, but it looks like a bug.
That's it.
