### ISSUE TITLE
runtime: "objectstart: bad pointer in unexpected span" running golang.org/x/tools/oracle on arm64

### ISSUE THREAD

**Issue by mwhudson** [golang/go#12552]
Full output here: http://paste.ubuntu.com/12319496/

I've had this happen on an ubuntu builder (with the 1.5 release) and with tip as of 5cbca8d84ba4625893c3a0b28a279d664b4125ec

Seems to happen roughly every other time.

**Comment by mwhudson** [comment]
I ran it in a much longer loop: 17 failures out of 100 runs. And each run takes a minute...

**Comment by ianlancetaylor** [comment]
CC @RLH @aclements

**Comment by aclements** [comment]
@mwhudson, I just pushed some improvements to this error message to master. Could you try reproducing it at tip?

**Comment by mwhudson** [comment]
https://gist.github.com/mwhudson/db0c9def25e417c03cb1

Seems marginally more intermittent now (~10% but maybe that's just due to load or someting)

**Comment by aclements** [comment]
Excellent. Thanks.

Since it sounds like you're able to reproduce the failure regularly, could
you paste a few more panics? That'll help with establishing a pattern.

**Comment by mwhudson** [comment]
Yep sure, I'd noticed that the three I've made so far this morning do look slightly different. I'll let it run for a few hours and post what I get.

**Comment by mwhudson** [comment]
http://people.canonical.com/~mwh/oracle-fails.tgz is 41 failures from 314 runs. Have fun :-)

**Comment by aclements** [comment]
Interesting. This didn't at all show the sorts of patterns I was expecting to see, but it did show a different pattern: in every case, the bad pointer has changed between when we first read it from the object (and checked it) and when we printed the object it was found in. Furthermore, excepting the cases where it's 0 the second time, the first read is always a *zero-padded prefix* of the second read:

panic.txt.103:runtime: pointer **0x4824000000** to unallocated spanidx=0x2000 span.start=0x4829326000 span.limit=0x482932a000 span.state=4
panic.txt.103: *(object+8) = **0x48241811f0** <==

panic.txt.11:runtime: pointer **0x4825000000** to unused region of spanidx=0x2800 span.start=0x4820a8a000 span.limit=0x4820a8c000 span.state=0
panic.txt.11: *(object+8) = **0x4825a62640** <==

panic.txt.129:runtime: pointer **0x4821f80000** to unallocated spanidx=0xfc0 span.start=0x4821f7a000 span.limit=0x4821f7e000 span.state=2
panic.txt.129: *(object+296) = **0x4821f8a0c0** <==

Whether there are two or three bytes of prefix varies. I suspect there can also be one or four bytes of prefix, but that we don't see one because it lands outside the heap and we don't see four because it lands inside of a valid span (just not the right object in the span).

Almost certainly something is doing a byte-at-a-time copying and the garbage collector is catching it in the middle of copying a pointer. The runtime's arm64 memmove does byte copying, which could cause exactly this failure. @4ad, @minux, it looks like we need to implement doubleword memmove at least for doubleword-aligned pointers on arm64. It looks like the compiler's blockcopy does 8-byte moves, so it should be good. I'm not aware of anything else in the compiler or runtime that does bulk memory copying.

**Comment by aclements** [comment]
This also affects ppc64. It always uses byte copying.

This also affects amd64p32, though more subtly: it uses 8 byte moves and then falls back to 1 byte moves, so if a pointer is the last field in an object and it's 4-byte aligned, but not 8-byte aligned, it will be copied one byte at a time.

I believe the other architectures are okay.

**Comment by mwhudson** [comment]
Oh hah, that's one of those things that had never occurred to me but is totally obvious in retrospect. At least the fix is fairly simple even if it's a bunch of typing.

**Comment by aclements** [comment]
Yeah, I had the same reaction. :) It's a standard optimization, of course, but it hadn't occurred to me that it was a *required* optimization in Go.

**Comment by davecheney** [comment]
Awesome detecting work Michael and Austin. Adding a better memcpy to arm64
shouldn't be too hard. Do you think this would be a candidate for go 1.5.2 ?

Thanks

Dave

**Comment by aclements** [comment]
> Do you think this would be a candidate for go 1.5.2 ?

Yes, since this is a runtime bug that affects correct programs. I don't think it can actually lead to memory corruption, but I haven't been able to completely convince myself of that. It can certainly lead to over-retention.

**Comment by mwhudson** [comment]
Well I implemented word by word copying and the bug still presents. It's possible I've messed it up, or is there something else that does byte-by-byte copies?

**Comment by davecheney** [comment]
Look for duffcopy paths, I think there is a path that copies n bytes by
hand, n may be ~8

**Comment by mwhudson** [comment]
They look OK to me, but maybe I'm mistaken. I found one more thing that does byte-by-byte memory setting (memclr) and fixed that but I'm still seeing failures. I uploaded a few as http://people.canonical.com/~mwh/oracle-fails-2.tgz

**Comment by mwhudson** [comment]
Argh was mistaken and testing the wrong binary. It does actually seem to work when I test the right one (63 runs with no failure so far).

**Comment by mwhudson** [comment]
Over 200 runs without failure. Pretty sure it's fixed now.

**Comment by aclements** [comment]
Since it's not at all obvious from the issue log, here's the set of commits that actually fix this and should be cherry-picked for 1.5.2, in cherry-picking order:

2c91114 runtime: adjust the ppc64x memmove and memclr to copy by word as much as it can (https://golang.org/cl/14840)
9f6df6c runtime: use 4 byte writes in amd64p32 memmove/memclr (https://golang.org/cl/15370)
168a51b runtime: adjust the arm64 memmove and memclr to operate by word as much as they can (https://golang.org/cl/14813)
4b7d5f0 runtime: memmove/memclr pointers atomically (https://golang.org/cl/16668)

I've confirmed that they cherry-pick cleanly (in this order) to the 1.5 release branch.
