### ISSUE TITLE
cmd/link: external link for mips64

### ISSUE THREAD

**Issue by minux** [golang/go#12560]

**Comment by eswierk** [comment]
Work description is similar to https://github.com/golang/go/issues/8912, but for mips64 rather than ppc64. It includes:

- completing elfreloc1, elfsetupplt, adddynsym, adddynrela, etc. in src/cmd/link/internal/mips64/asm.go
- adding missing cgo support to src/runtime/asm_mips64x.s
- enabling cgo external link tests and getting (cd misc/cgo/test && go test -linkmode=external) to pass for mips64 and mips64le

**Comment by mwhudson** [comment]
I think that's a little inaccurate and muddles implementing cgo and external linking. External linking mostly just requires elfreloc1 (it might also require changes to the entrypoint?). elfsetupplt, adddynsym, adddynrela are required for cgo with internal linking (they are not implemented for arm64, for example, which only supports cgo via external linking).

The runtime stuff in asm_mips64x.s is required for either flavour of cgo, but not external linking.

**Comment by eswierk** [comment]
Thanks @mwhudson for helping un-muddle my understanding of cgo vs. internal linking vs. external linking. So to build a Go program with embedded C code (via extern "C") that calls functions in an external library, I need just
- cgo runtime support in asm_mips64x.s
- external linking support in elfreloc1

but not the internal linking support in elfsetupplt, adddynsym, adddynrela. Is that correct?

**Comment by minux** [comment]
Yes. Some small modification to other parts of the runtime
will be needed for cgo, but that shouldn't take too much
time.

**Comment by eswierk** [comment]
I reverted the issue description to cover only external linking, and opened https://github.com/golang/go/issues/14126 for complete cgo support.
