### ISSUE TITLE
Proposal: add Ioctl function to x/sys/unix for solaris and add TCGET*, TCSET*, TCSBRK, and TCXONC constants

### ISSUE THREAD

**Issue by kim-racktop** [golang/go#12574]
Currently on solaris in the syscall package, the ioctl function is private for solaris.

In syscall/exec_solaris_test.go, there is a line:

    var Ioctl = ioctl

which makes Ioctl public for test purposes.  I propose moving this line from syscall/exec_solaris_test.go to syscall/syscall_solaris.go so that Ioctl is available on solaris.

In addition, I propose adding the following lines:

    $2 ~ /^TCGET/ ||
    $2 ~ /^TCSET/ ||

to the awk script embedded in syscall/mkerrors.sh so that the following constants get defined in syscall/zerrors_solaris_amd64.go.

    TCGETA
    TCSETA
    TCSETAF
    TCSETAW
    TCGETS
    TCSETS
    TCSETSF
    TCSETSW

Making these changes allows for Go code to access the termios and termio structures.

**Comment by minux** [comment]
The syscall package is frozen. Please propose the changes to x/sys/unix
instead.

**Comment by kim-racktop** [comment]
My impression was that syscall was not 100% frozen.  The proposed changes bring solaris closer to other platforms that have Ioctl and function constants that access the termios structure.  Since the other platforms have supporting code in syscall, it seemed better to add these changes to syscall as well.

If my impression is not correct, I have no problem changing this to the x/sys package.

**Comment by minux** [comment]
No, the syscall package is frozen. Unless the system in question is just
added in this release cycle, or the functionality must be in syscall
package, all new changes should go to x/sys.

**Comment by kim-racktop** [comment]
Should I close this issue or just edit it for x/sys?

**Comment by bradfitz** [comment]
Feel free to edit this issue.

**Comment by ianlancetaylor** [comment]
Quite apart from the fact that the syscall package is frozen, ioctl is a problematic system call for Go.  I think we need to handle it the way we handle setsockopt: by providing a set of functions that take different types, rather than providing a single unsafe Ioctl function.  As much as possible, we would like people to be able to use x/sys/unix without having to themselves import unsafe.

**Comment by minux** [comment]
Just edit this issue is fine. Thanks.

**Comment by binarycrusader** [comment]
@kim-racktop I suspect our paths are going to cross.  See issue #12101.

The right answer seems to be creating a new terminal package as @ianlancetaylor suggested.

Email me if you want to collaborate as I'm working in this area right now :-) (my username at binarycrusader.com)

**Comment by kim-racktop** [comment]
Redoing the original to propose changes to x/sys/unix instead of syscall.

Currently in x/sys/unix, the ioctl function is not exposed at all.  I propose to add code to expose this in asm_solaris_amd64.s and syscall_solaris.go, as well as make changes to mkerrors.sh so that the constants:

    TCGETA
    TCSETA
    TCSETAF
    TCSETAW
    TCGETS
    TCSETS
    TCSETSF
    TCSETSW
    TCSBRK
    TCXONC

get defined in zerrors_solaris_amd64.go.

I looked at setsockopt and I am not sure I follow your argument about wrapping it.

**Comment by ianlancetaylor** [comment]
What I mean about setsockopt is that there is no syscall.Setsockopt function nor is there a x/sys/unix.Setsockopt function.  Instead there is SetsockoptInt, SetsockoptByte, SetsockoptInet4Addr, etc.

Similarly, there should not be any x/sys/unix.Ioctl function.  There should be IoctlInt, IoctlTermios, etc.

**Comment by kim-racktop** [comment]
I have a question regarding naming conventions for the IoctlXXX functions.

In the case of socket options, we have SetSockOptInt and GetSockOptInt so we know the difference between setting and getting an option.

For Ioctl, should I do the same thing and have SetIoctlInt and GetIoctlInt functions?

For my immediate needs, I would need Int, Termios, and Winsize versions of ioctl.  Should I implement others?

**Comment by ianlancetaylor** [comment]
I think IoctlSetInt and IoctlGetInt would be better names--the sockopt names correspond to the setsockopt and getsockopt system calls, and I think in all cases we want the system call name first.

No need to implement any system calls you aren't going to use.

**Comment by kim-racktop** [comment]
I have submitted https://go-review.googlesource.com/#/c/14587/ for this issue.

**Comment by 4ad** [comment]
Why do we need to do this?

We established in #12101 that we want a new terminal package. ISTM that these new definitions and ioctls should live there (maybe even unexported) rather than in x/sys/unix.

**Comment by ianlancetaylor** [comment]
A new terminal package seems higher level to me.  I don't see that as an argument against adding support for the low level ioctls to x/sys/unix, any more than the os package is an argument against syscall.Open.

**Comment by gdamore** [comment]
This will be hugely useful.  I can see a call for size typed ioctls though too.  E.g. IoctlSetInt64 etc.  The reason here is that some of the lower level system calls may expect integers of specific bit widths.

I'd still also like to have a public ioctl that allows me to pass unsafe pointers.  Yes, I hate the idea of needing to do that, but there are occasions where I have to interface with low level software (e.g. kernel drivers that I have written) where the control interfaces are ioctls.  In the specific cases I've dealt with, I solved this by writing small C programs as microservices, and communicating with them over a messaging framework.  But it would be even nicer if I could have written them entirely in Go.

**Comment by gdamore** [comment]
What about TCFLSH? - useful for tcflush() style implementation.

**Comment by gdamore** [comment]
Btw, with respect to termios specifically, the preference ought to be to use POSIX standard functions (tcsetattr & co) at least on Solaris.  That said, these ioctls *are* documented for Solaris/illumos systems, and therefore considered stable.  Using the ioctl() function is certainly superior to directly making a system call on this platform.

**Comment by kim-racktop** [comment]
The TCFLSH constant was already in zerrors_solaris_amd64.go so it is available.

I can see replacing my proposed IoctlSetTermios() and IoctlGetTermios() functions with tcsetattr and tcgetattr functions.

Since the only way to get at Winsize and Termio is through ioctl, I think those should stay.

Would people rather see something like:

    Tcgetattr(fd int) (*Termios, error)
    Tcsetattr(fd int, opt int, attr *Termios) (error)

added to x/sys/unix for solaris?

What about the other tc* functions?

**Comment by ianlancetaylor** [comment]
Solaris is kind of a special snowflake.  I don't much care which way you go.  Other systems are going to have direct ioctls in the x/sys/unix package, though, so if they are going to look the same on Solaris as on other systems there would be a minor advantage to using the ioctls on both.  If they are going to look different then it doesn't much matter what Solaris does.

**Comment by binarycrusader** [comment]
Most of the existing consumers use ioctl()-based interfaces, so I think it's perfectly fine to provide that interface for now.  You're really just getting Solaris to match the status quo on other platforms where Go is used.

Personally, I think #12101 can cover the more general, higher-level abstractions that Go should have in the long-run for terminal manipulation.  I wouldn't worry about exposing the tc*() functions for now -- that really seems like a separate issue.

**Comment by gdamore** [comment]
ioctls are fine for Solaris -- these ioctls are indeed stable & documented.

HOWEVER, I would *vastly* prefer to see a direction oriented towards POSIX
equivalent functions rather than ioctls.  The fact that it may use an ioctl
under the hood is fine, but IMO every benefits if the public API is closer
to documented POSIX standards.  This isn't about Solaris, its about using
an interface that is well documented and familiar to many more people, and
also a heck of lot more portable.

A reasonable approach might be to have both the ioctls *and* the termios
wrappers; much like we have low level implementation details exposed via
syscall package, but higher level interfaces elsewhere.

I'm not convinced that a very high level interface like a terminal package
satisfies the desire for a "system" level, yet portable, interface like the
POSIX termios functions.

**Comment by 4ad** [comment]
Let's go with ioctls now, we can also add the tc* functions later as well.
