### ISSUE TITLE
spec: Do exact floating-point constants differentiate between -0.0 and 0.0?

### ISSUE THREAD

**Issue by griesemer** [golang/go#12576]
The spec does not seem to be clear.

The test test/fixedbugs/bug434.go says that -0.0 and 0.0 are the same.

Clarify.

**Comment by ianlancetaylor** [comment]
My understanding has always been that exact floating point constants do not include concepts like infinity, NaN, or negative zero.  Those are features of the IEEE floating point format due to their limited size.  They aren't features of exact floating point constants.

**Comment by randall77** [comment]
The compiler's ideal floating point implementation does have a sign, which I think is the root of this confusion.  We need a -0 -> +0 conversion at lots of places where we read out an ideal float and put it in a concrete float.

**Comment by griesemer** [comment]
Please file a separate issue for that. I can fix it.

**Comment by dr2chase** [comment]
It would be nice if people accustomed to IEEE floats got an unsurprising answer when they wrote -0.
The only place I've ever seen it mentioned in Go code was tests, so we're unlikely to break anyone's non-test code if we changed this.

**Comment by griesemer** [comment]
There are two separate issues here:

1) Do exact floating-point constants have a -0?

2) What happens when a very small negative floating-point constant gets materialized to be assigned to a (say, float64) variable, and the constant's magnitude is smaller than then smallest negative float64? In this case, does the constant silently underflow to -0 or 0?

Or in other words, should:
```
var x float64 = 1e-1000 // underflows to 0
y := -x // y == -0
```
produce the same result as:
```
var x float64 = -1e-1000 // currently underflows to 0 even though value is negative
y := x // y == 0
```

**Comment by dr2chase** [comment]
I think the answer for (1) is "they can if we say they can, and we should say they can". 
I think the answer for (2) is that we would minimize surprise if y "is" -0 in both cases.

Maybe we want to sanity check this against what Python does; I think if you ask the numerical guys, they'd be in favor of this.

**Comment by ianlancetaylor** [comment]
To date exact floating point constants have not had a negative zero, and I don't see how we can change that now without breaking the Go 1 compatibility guarantee.  The behaviour of programs like test/fixedbugs/bug434.go should not change.

More philosophically, the concept of a negative zero is meaningless in the world of exact floating point constants.  There is no negative zero in mathematics.  There is only zero.  You can talk about zero as the limit of a function that produces negative numbers, and you can refer to that as negative zero, but there is no notion of that value as distinct from positive zero.

For better or for worse, Go's exact constants do not follow the rules of computer arithmetic.  You can't write `const c = int32(0x80000000)`.  There's no necessary reason for them to support negative zero.

There are two ways to interpret Robert's second question.  One is what should happen when handling an exact floating point constant that is too small to represent.  The spec says fairly clearly that it should be converted to the nearest representable constant, which would be zero (neither negative zero nor positive zero, just plain zero).

The other interpretation is what should happen when converting an exact floating point constant to float32/float64 when the value is too small to represent and is negative.  I don't think the spec says anything about that.  As it happens, the gc and gccgo compilers behave differently, which also suggests that the spec doesn't cover the case.

This program

    package main
    
    import (
    	"fmt"
    	"math"
    )
    
    var v float32 = -1e-46
    
    func main() {
    	fmt.Println(v)
    	fmt.Println(math.Float32bits(v))
    }

prints `0 0` with gc and `-0 2147483648` with gccgo.

My current inclination is to say that gc is correct and gccgo is wrong: we should convert a negative floating point number that is too small to represent to IEEE positive zero.  But I think we could decide the other way here.

**Comment by dr2chase** [comment]
I've gone looking for programs that would depend on -0.0 converting to +0.0, and (1) I can count them on my fingers and toes and (2) all their names end in _test.go.  If we were looking for a least-impact way to break compatibility, this might be it.

If we were especially paranoid about this change we could do it in two dot releases -- in one, we warn that float32(-0) and float32(-1e-1000) will convert to -0.0 in the next dot release, and in the next we change it.  The fix is trivial, and even if unfixed it's not that likely to cause problems.

**Comment by ianlancetaylor** [comment]
@dr2chase That's true, we could change how it worked if we really had to.  But as far as I can tell, we don't really have to.  So why change it?

The current behaviour is not an accident.  It's what we decided.

**Comment by dr2chase** [comment]
Sure, but IEEE decided differently first, it does get used in numerical code from time to time, and it's practically cost-free to do a better job at conforming to that standard.

**Comment by ianlancetaylor** [comment]
I don't find that to be an especially compelling argument by itself.  Exact floating point constants also don't have infinities or NaNs or denormal numbers.

**Comment by dr2chase** [comment]
Since you bring it up...

+Inf = (>0)/0 = (<0)/-0 = -(-Inf)
-Inf = etc
Nan = Inf - Inf = Inf + (-Inf)
and  division of finites by infinites yields appropriately signed zeroes.
Also pretty painless, also friendly to IEEE.
These changes are even less worrisome w.r.t. compatibility with the past, since they are currently errors.
We can preserve errors for Inf/Nan conversion to integers -- that seems least likely to surprise, and I think that using +/-Inf as an encoding for Max/Min value for the various integer types risks a cuteness violation.  uint8(1/0) == 255, not going there.

Denormals I think we get already as a consequence of conversion from tiny-magnitude exacts to IEEE fp.

**Comment by robpike** [comment]
We don't really have floating-point constants, although that's what they're called. We have scientific notation for representing a real number, which we then represent as a floating-point number when necessary. This may sound pedantic and you may disagree, but I believe this is true and that it's important to keep the wretched peculiarities of floating-point arithmetic from leaking back across the boundary. For instance, there are no NaNs in Go constants and there shouldn't be.

There should be no negative zero in Go constants. There is no such thing as a true negative zero anywhere, there is only a fiction called negative zero that is an accident of the way floating point numbers are represented in computer memory.

They are (or used to be) called "ideal constants" for a reason.

**Comment by griesemer** [comment]
@r I think we agree that exact constants don't have a -0.

But there's an open question to what happens when an exact constant x < 0 is assigned to a floating-point variable v but the magnitude abs(x) is too small for x to be represented by v as a nonzero value. Variables follow IEEE-754 arithmetic, and one might argue that in this case, v should become -0.

**Comment by robpike** [comment]
One might, but one could also argue that they become 0. I simply do not see any need for -0 here. The value -0 isn't less than 0, so the fact that the underflow happened with a negative value says nothing about preferring -0 over regular 0.

**Comment by griesemer** [comment]
For the reference: gccgo materializes negative floating-point constants too close to 0 to represent as a float64 as -0. But it is otherwise inconsistent. See also #12621.

**Comment by dr2chase** [comment]
I realize that many things could be argued, but these are mostly old arguments that were hashed out back when IEEE FP was defined.  I think we should support -0, NaN, +Inf, -Inf in our ideal constants for the following reasons:

- it will break no non-test code, and even if I am wrong (because I have not searched all the Go code in the world) the fix is trivial.

- it's not a wholesale destructive change to the rules for ideal constants.  It adds 4 special values, and the rules for those values have relatively little interaction with the other rules of constant arithmetic.  We don't lose the sign when the magnitude is zero, we replace certain error cases with special values, and 0-0 = +0 (i.e., -0 + +0 = +0 ).  For non-float conversions from constants, -0 becomes 0, and Inf and Nan become errors.

- it will slightly reduce surprise for new users, and reduce the friction of porting (some) FP code written in other languages to Go.

- it's rarely a bad thing to bring a computer language into closer conformance with a well-accepted and well-understood standard.

Go has quirks, but for most of the quirks there's at least a reason.  The reason here seems to be "because", and five years from now that will be really embarrassing that we didn't fix this now when the cost is still low.

**Comment by ianlancetaylor** [comment]
IEEE 754 was solving a different problem.  They had to decide what would happen at runtime for division by zero.  For Go we are only talking about floating point constants and constant expressions.  There are no floating point constant functions, so we are limited to what we can write using the builtin arithmetic operations.  Division by constant 0 is a compile time error.  We don't have to answer the question of how to represent division by 0, because it is impossible.  We don't need to support infinity or NaN, because there is no way to write any constant expression that will produce them.  It's not quirks of the language.  It's just logic.

Negative zero is a different case, because it is possible to write constant expressions that produce negative zero.  Of course, for constant expressions, there is no way to distinguish positive zero from negative zero.  So what we are talking about here is whether there should be any way to write a constant expression that, when converted to float32 or float64, produces a negative zero.

For me, the argument that IEEE supports a negative zero is not a sufficient argument.  Floating point constants are a different solution for a different problem.  There can not be an isomorphic mapping from constants to IEEE values.  There might be a good reason to support producing negative zero when converting to IEEE.  But I think it needs to be more than simply the fact that IEEE supports negative zero.

**Comment by griesemer** [comment]
@dr2chase As an aside, go/types, which currently implements compile-time numeric constants mathematically exactly (as rational numbers, rather than as a floating-point number with super-high precision), the discussion about a -0 for compile-time constants is moot. -0 is not representable.

The reason -0 exists in IEEE is an artifact of the implementation. And then that artifact is used to "squeeze out" a bit more "precision" (information) from a limited format. The compiler is not restricted to this limited format.

(I regret having formulated the issue title as is: This was mostly a reminder for me to clarify the spec if need be; posed as a question. The notion of exact constant arithmetic was from the beginning that it would be, well, exact, for simplicity and clarity of concept. The fact that compilers may use a limited- but high-precision (256bits of mantissa at the least!) floating-point number internally is an implementation detail that is invisible for all practical purposes but esoteric corner cases and academic exercises.)

Regarding the outstanding question of what happens when a negative too-tiny-to-represent-as-float64 constants gets assigned to a variable - the only argument I can come up with for making it -0 is that it would provide a tiny bit more information about the original value, which is probably in the spirit of IEEE-754. For instance, this program ( http://play.golang.org/p/_v68BLI5XQ ):
```
package main

import "fmt"

func main() {
	const c = -1e-1000
	fmt.Println(c, c < 0)

	var x float64 = c
	fmt.Println(x, x < 0)

	var y float64 = -1
	for i := 0; i < 1000; i++ {
		y /= 10
	}
	fmt.Println(y, y < 0)
}
```
would print -0 for both the value of x derived from a constant, and the same value y derived via explicit computation (note that the playground at the moment disagrees, hence the issue).

But on the other hand, the "extra bit of information" does not even carry over into comparisons: a -0 is not < 0 in IEEE. So while c < 0 is true (constant expression), x < 0 is not even if x were -0.

**Comment by griesemer** [comment]
It turns out that the spec is already authoritative, see http://tip.golang.org/ref/spec#Conversions:
```
A constant value x can be converted to type T in any of these cases:
...
x is a floating-point constant, T is a floating-point type, and x is representable by a value of type T after rounding using IEEE 754 round-to-even rules. The constant T(x) is the rounded value.
...
```
In an assignment of the form:
```
var x = -1e-1000
```
we effectively have
```
var x = float64(-1e-1000)
```
which is valid if -1e-1000 is representable as a float64 after rounding using IEEE 754 round-to-even rules. float64(-1e-1000) is representable, and the value can be explicitly computed, for instance with math/big: http://play.golang.org/p/wY1ulpXxdp . The result of rounding is -0 .

There is a chance that math/big.Float doesn't round correctly, but the same behavior can be observed in pure IEEE-754 arithmetic, by taking the smallest representable float64 value < 0 and dividing it by 2. The resulting value will underflow and round to 0, and the sign is the sign after round-to-even per IEEE-754: http://play.golang.org/p/C1XTOEZier . The result of rounding is again -0 .

**Comment by griesemer** [comment]
It's more complicated: The spec is also conflicting. The section on conversions http://tip.golang.org/ref/spec#Conversions mentioned above clearly says that T(x), if representable at all, is a *constant* and that it is the *rounded value* after rounding according to IEEE 754 round-to-even rules.

For float64(-1-1000), the rounded value according to these rules is -0 which is not representable as a constant (or so we have concluded separately).

We probably need to augment the conversion rule to exclude -0.

**Comment by dr2chase** [comment]
Why would you modify the conversion rule to exclude negative zero, and not modify the constants rule to include it?  This gets us easy expression of an otherwise unsayable FP value.

I've discussed this with Austin also, he thinks that permitting constants to evaluate to +/- Inf is a net lose because of bugs-not-caught, and I think that might be right.  But -0 is easy -- "constant values have signs, even the zero constant, where signs obey the usual rules, and -0 obeys the following two additional rules: -0==+0, and -0 + +0 = +0".

There's the additional startling glitch in the spec where we allow a Go implementation to panic in the case of
```
x := float64(0.0)
y := 1/x
```
instead of assigning +Inf to y.  If people actually believed this could panic,  they'd be forced to code all their FP divisions defensively -- I'll bet they don't, and if they did, it would slow their code down (slightly) and they would curse us for not providing clean, sensible, and widely-understood semantics.

Or to put this in Go-centric terms -- well-defined division semantics are simpler and easier for programmers than ambiguous semantics, so why don't we choose simpler?

**Comment by ianlancetaylor** [comment]
I think we might have added that note about division by floating-point zero because some platforms send a SIGFPE signal when that occurs.  I agree, though: we should take that out, and change the compiler to add a zero check if necessary.

**Comment by ianlancetaylor** [comment]
@dr2chase I find your argument about negative zero to be overly abstract.  I'm going to encourage you to write a program that works better if we permit floating point constants to represent negative zero.
