### ISSUE TITLE
cmd/go: Cross compiling Go c archives for iOS does not generate bitcode

### ISSUE THREAD

**Issue by swisspol** [golang/go#12682]
> Go 1.5.1 on OS X 10.10.5 with Xcode 7

Even if setting `CC` and `CXX` to include `-fembed-bitcode` while building against the iPhoneOS SDK, the resulting static library does not contain bitcode.

I made a sample test project here: https://github.com/swisspol/Go-Bridge

**Comment by minux** [comment]
The Go toolchain doesn't generate LLVM bitcode.
so there is nothing to do here.

**Comment by swisspol** [comment]
I figured as much with the new Go toolchain. That might turn into a major problem going forward though, assuming Go wants to support mobile development on iOS (which is I assume the intent of https://github.com/golang/mobile/).

Bitcode is part of the [new app thining](https://developer.apple.com/library/prerelease/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html), and submission to the App Store for WatchOS apps must already be in bitcode. It's currently optional for iOS apps, but maybe it will be required for iOS 10 next year. I would bet that it is at most 2 years away. Apple has a long history of architecture transitions and they are typically quite aggressive as well.

PS: What do you mean by the "gc toolchain"?

**Comment by minux** [comment]
LLVM still lacks essential features to support the Go runtime (i.e. stack
map, write barriers?). Perhaps the write barrier thing isn't too big as we
can emulate it, but we cannot emulate stack map without also implement our
own stack -- then much of the benefit of LLVM is gone.)

If bitcode is required, then iOS development might need to use an
alternative toolchain (e.g. llgo), until we figure out a way to support a
LLVM backend (probably won't happen because gc has always been using its
own backend and it allows much faster evolution as we don't need to wait
before required features are implemented in 3rdparty software)

The gc toolchain refers to the toolchain in this GitHub repository.

**Comment by swisspol** [comment]
Got it, thanks.
