### ISSUE TITLE
cmd/go: do not replace existing $GIT_TERMINAL_PROMPT

### ISSUE THREAD

**Issue by ScottMansfield** [golang/go#12706]
The go get command was changed in 1.5 to disable git prompts universally (see issue #9341). This change reduced choice for how people want to work with the go get command (and was slightly aggrivating to track down). I'd suggest reverting the change and letting people set their own (git-standard) environment variable to disable the prompts themselves. It shouldn't be go's purview to allow or disallow prompts.

Even if the previous change isn't reversed, it should be easy to check for a GO_GET_GIT_COMMAND_PROMPT env var or something along those lines to make it easier to configure. Currently, I have to make sure git knows my username and password for every place I want to download from, where it would be easier to just set an env var and say I want those interactive prompts back.

**Comment by rakyll** [comment]
You can cache your password for a limited time in the cache by `git config --global credential.helper 'cache --timeout=x'`. Then, use the keychain credential cacher to set your username and password and go get.

**Comment by rsc** [comment]
I'm sorry this disrupted your workflow, but as discussed in #9341, otherwise we get spurious username/password prompts from Git for non-existent GitHub repositories. This isn't about personal preference on password prompts; it's about ensuring correct operation in that case, so it is certainly the go command's purview.

I'm not particularly inclined to add yet another environment variable.

Perhaps we could change the go command to leave any existing $GIT_TERMINAL_PROMPT in place, so that people who really want the broken behavior can set GIT_TERMINAL_PROMPT=1.

**Comment by ScottMansfield** [comment]
Ah, that makes sense. I didn't read #9341 closely enough. I agree adding another environment variable would add unnecessary complication.

Being able to say `GIT_TERMINAL_PROMPT=1 go get ...` would be great, so your solution sounds good to me.
