### ISSUE TITLE
x/tour: len(T) discussed before explaining

### ISSUE THREAD

**Issue by KarthikNayak** [golang/go#12758]
Context: https://tour.golang.org/moretypes/8

In this slide we have "// missing high index implies len(s)" before even
explaining what len(T) does. Although this is quite trivial, anyone new
to programming might not understand this.

**Comment by kytrinyx** [comment]
Since this is in a comment in the example, it's a bit tricky to explain it in the slide itself. Also, rewriting it to something else doesn't sit very well.

* `// missing high index implies the rest of the slice` - imprecise
* `// missing high index implies the highest valid value, the length of the slice` - wordy, imprecise

How about working around it by introducing `len` on the previous slide?

**Comment by kytrinyx** [comment]
Looking at this again, `len(s)` is even used on the previous slide (for loop), so it would be pretty straight forward to add a short description about this.

**Comment by rakyll** [comment]
I'd add a description for len saying it returns the length.

**Comment by adg** [comment]
@kytrinyx agree, let's mention len earlier.

**Comment by KarthikNayak** [comment]
Makes sense, a small description was what I was looking for. Thanks

On Thu, Oct 8, 2015, 8:07 AM rakyll <notifications@github.com> wrote:

> I'd add a description for len saying it returns the length.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/12758#issuecomment-146400009>.
>
-- 

Regards,
Karthik
