### ISSUE TITLE
Error message in tutorial

### ISSUE THREAD

**Issue by Dysmondad** [golang/go#12759]
Context: https://tour.golang.org/basics/3

Simply load the page and click 'Run'

prog.go:9: cannot refer to unexported name math.pi
prog.go:9: undefined: math.pi

**Comment by Mr4x** [comment]
Please read the task:
> Then rename `math.pi` to `math.Pi` and try it again.

**Comment by dominikh** [comment]
Each page in the tour is accompanied by an explanatory text to its right, which you're encouraged to read. In this case, it says

> Run the code. Then rename math.pi to math.Pi and try it again. 

The error in the initial code is intended. I'd suggest that instead of filing more issues (#12761 and #12762), you read the actual text. That should surely take less effort than filing all these issues.
