### ISSUE TITLE
image/jpeg: Decode incorrectly complains about missing SOF marker

### ISSUE THREAD

**Issue by opennota** [golang/go#12784]
http://play.golang.org/p/qUNLzBVraB

The image was generated using ImageMagick and libjpeg's cjpeg and is a valid image with a SOF0 marker, but Decode() complains about `invalid JPEG format: missing SOF marker`.

**Comment by ALTree** [comment]
If I dump your `jpg` array to file and then try to decode it I get

```
$ djpeg ~/Desktop/imm.jpg 
Corrupt JPEG data: 3 extraneous bytes before marker 0xc4
Invalid JPEG file structure: SOS before SOF
```

Are you sure you are using a valid JPEG image?

**Comment by opennota** [comment]
@ALTree Oops. Something went wrong. Closing the issue as invalid.

**Comment by blazeeboy** [comment]
For the record, I stumbled across this issue while debugging an image resizer, I had some images that wasn't resized and the error message was the same as this issue, so I tried to get the type of the file and turns out to be png and I forgot to import the png and also gif decoders to my app.

just to save some time for other people who gets here.
