### ISSUE TITLE
cmd/go: get transport failure unhelpful unless -v is used

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#12810]
Today, if you execute go get on a package and it fails due to a connection timeout, the resulting error is too literal.

Recently, I was helping another developer who encountered this failure and was somewhat mystified as to the result:

```
$ go get golang.org/x/net
package golang.org/x/net: unrecognized import path "golang.org/x/net"
```

They could reach other websites, etc. just fine so assumed that somehow Go itself must be broken or they typed the wrong path.  However, when they talked to me, it was clear they were using the correct import path.

On a whim, I decided to use '-v' instead to see if that would be more helpful, and of course it became obvious what the likely failure was:

```
$ go get -v golang.org/x/net
Fetching https://golang.org/x/net?go-get=1
https fetch failed.
import "golang.org/x/net": https fetch: Get https://golang.org/x/net?go-get=1: dial tcp [2607:f8b0:4003:c08::8d]:443: i/o timeout
package golang.org/x/net: unrecognized import path "golang.org/x/net”
```

In this particular case, the issue was a misbehaving proxy that for some reason has problems with the forwarding in place, and once they used a different proxy, 'go get' succeeded.

I would like to suggest that if 'go get' fails due to a transport issue that the related transport errors should be printed; it's less likely to lead to failures that mystify users and generate unnecessary angst.  I don't think it's fair to expect users to intuit that they should run again with '-v' for failures to get the actual errors.  The current failure message, at the very least, can be misleading.

**Comment by orvado** [comment]
I received the same issue here with the error listed below.  Go get is not using the proxy settings on my system which is behind an authenticating Windows proxy.  If the software would just use the same proxy settings as IE (which is just one line of code in .NET), it would solve the problem.  Obviously, you don't have that luxury here.

F:\Documents\Go>go get -v golang.org/x/net/context
Fetching https://golang.org/x/net/context?go-get=1
https fetch failed.
import "golang.org/x/net/context": https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 74.125.25.141:44
3: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, o
r established connection failed because connected host has failed to respond.
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context"

**Comment by adg** [comment]
I also experienced the same issue recently. We need better error reporting.

**Comment by rakyll** [comment]
It has a trivial fix but not a priority in my list. Removing my assignment and would be happy to see it's fixed by someone else. I am often coming across this issue.

**Comment by msepehr** [comment]
Hi, I have exactly the same issue : go get -v golang.org/x/net/context
Any idea?

**Comment by bradfitz** [comment]
@msepehr, you don't describe your problem enough. Also, this is a closed issue. Please file a new bug.
