### ISSUE TITLE
x/tools/oracle: freevars with bound variables used in return doesn't report them as free

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#12821]
Since the main use for freevars is to pull subsequences into new functions, it seems weird that bound variables within a block doesn't get marked as free when used in a return.

Example:

```
func blah() int {
	if true {
		var i int
		i = 20
		return i
	}
}
```
If you get the freevars within the `if true {` block, the `i` variable will not show as free.

Since a return behaves as an assignment to the return variable and then exit, I think it's reasonable to consider it as a free variable, even though it doesn't follow the definition exactly.

**Comment by alandonovan** [comment]
Hi Daniel.  You are right that the return acts like an assignment, but it is an assignment not to `i` but to the result variable, which is unnamed in your example.  The variable `i` is definitely not free in this block.  Had the result variable been named, as in this example

```
func blah() (result int) {
    if true {
        var i int
        i = 20
        return i // implicitly: result = i
    }
}
```

it would also not be free, because there are no explicit uses of the name `result` within the block, although of course there is an implicit use.

There is quite a bit more to the "extract function" refactoring than what the oracle `freevars` query does.
