### ISSUE TITLE
net/url: url.Error should propagate the net.Error interface

### ISSUE THREAD

**Issue by jum** [golang/go#12866]
At some points in a program it might interesting to find out if a network error is transient or a timeout. If the program uses Dial et. al. this is handled by calling the Temporary() or Timeout() interfaces on net.Error. But if the program uses http.Get or similar, the net.Error is hidden behind url.Error.Err. one has to use a logic like this check for transient errors:

				testErr := err
				if e, ok := testErr.(*url.Error); ok {
					testErr = e.Err
				}
				// As we are called regularly by cron, ignore some errors.
				type timeout interface {
					Timeout() bool
				}
				if e, ok := testErr.(timeout); ok {
					if e.Timeout() {
						err = nil
					}
				}
				type temporary interface {
					Temporary() bool
				}
				if e, ok := testErr.(temporary); ok {
					if e.Temporary() {
						err = nil
					}
				}
If url.Error would embed Err anonymously, any interfaces would be available without the type assertion to *url.Error.

**Comment by bradfitz** [comment]
Sure. If somebody wants to send a CL to make `url.Error` implement `net.Error`, that's fine with me at least.

**Comment by davecheney** [comment]
I'll take a shot

**Comment by davecheney** [comment]
@jum I started to look into this, and I cannot find a place where url.Error.Err is assigned something that conforms to net.Error. I think there is nothing to do on this ticket because url.Error never wraps a net.Error.

Can you please provide some sample code that shows a url.Error holding a net.Error.

Thanks

Dave

**Comment by davecheney** [comment]
@jum sorry, I found it. There is one place in http/client.go, https://github.com/golang/go/blob/master/src/net/http/client.go#L417,  where url.Error is used to record the url that failed in a redirect chain.

**Comment by davecheney** [comment]
https://go-review.googlesource.com/15672

**Comment by arvenil** [comment]
I just wasted way more than 15 minutes trying to figure out why some network error was not catch by `err.(net.Error)` even though docs stated it should. Turned out `url.Error` implements `net.Error` since go 1.6.
I wonder if anyone thought/propose adding go version numbers to docs saying from which version given method is available?

**Comment by bradfitz** [comment]
@arvenil, there is a separate bug open for that. I don't know its number off hand, though.

**Comment by arvenil** [comment]
@bradfitz I didn't found it before posting, but I've tried again now and I think it is this one https://github.com/golang/go/issues/5778 ? Thank you!
