### ISSUE TITLE
spec: add __FILE__ and __LINE__ macro

### ISSUE THREAD

**Issue by j16sdiz** [golang/go#12876]
The current `Caller()` method is more flexible, but it encourage hardcoded stack depth constant (see https://golang.org/src/log/log.go#173 ). This is easy to bitrot.

Constant (or marco) like `__FILE__` push the responsibility to the caller. Maybe a little bit hard to use, but it is simpler to maintain.

Reference: https://groups.google.com/d/msg/golang-nuts/3_UFKPKIzRU/HKCC8KqOhQYJ

**Comment by minux** [comment]
Go doesn't have anything like this before, so I'd hesitate
to introduce these.

Also __FILE__ and __LINE__ look quite ugly in Go.

The reference you cited is a few years old, and I'm wonder
if @ianlancetaylor still thinks we might want to add these to
Go?

**Comment by griesemer** [comment]
I can see the use for access to what are constants known to the compiler, and it's not entirely unprecedented in Go: The predeclared constant iota exposes such a mechanism (it counts semicolons inside a const declaration, not unlike __LINE__ counts lines inside a file).

But I think introducing more such predeclared constants is not the right path. For one, __FILE__ and __LINE__ don't really fit into the aesthetics of Go. Also, it opens the door for ever more explicitly named such constants.

We do have other means to handle such things in a more Go-like way. I can think of 2:

1) Introduce a new predeclared built-in function (better name choice welcome):
```
// compilerinfo accepts a string argument "filename", "line", or "timestamp" and returns the
// filename of file being compiled, the line number of the compilerinfo invocation, or the
// time of compilation, respectively. The argument must be constant string, and the result is
// a constant string.
func compilerinfo(string) string
```
Such a mechanism would be easily extensible. It does mean we extend the language by this additional builtin.

2) Introduce a new compiler-known magic package, say "compiler" (similar to package "unsafe"). Or maybe it should be in "unsafe" since results depend on file names, line numbers etc. which might not be considered "portable". Something to think about. Either way, such a packet could export functions like Filename(), Line(), Timestamp(), etc. that produce constant results (package unsafe does this already, so maybe that's the right place for these).

Something to think about.

**Comment by ianlancetaylor** [comment]
I (now) agree that __FILE__ and __LINE__ can't be right.

It's hard for me to picture how these would be used.  Not many people write out __FILE__ and __LINE__ in C code.  Instead, they refer to them in macros.  But obviously Go doesn't have macros, and you can get already the information in a function by using runtime.Caller.  I don't think the concern about a hardcoded stack depth constant is valid, particularly if that depth is 1.  That is, the equivalent of a C trace #define that uses __FILE__ and __LINE__ is a Go function that uses runtime.Caller(1) to find out its caller's file and line.

So I would like to see a real example of how these would be used before we even consider adding them.

**Comment by j16sdiz** [comment]
@ianlancetaylor 
I was trying to solve the concern in this comment https://github.com/Sirupsen/logrus/issues/63#issuecomment-118905844

logrus have multiple logging code path and unstable internal API. Hardcoded stack depth are prone to bitrot. 

I agree compiler magics are hard to use, but they are hard to break too.

**Comment by minux** [comment]
Without going through the long issue, could you please give
an example where __FILE__ and __LINE__ macro could
help whereas calling runtime.Caller(0) won't?

**Comment by ianlancetaylor** [comment]
It occurs to me that you can actually write these yourself very easily as functions.

func file() string {
    _, file, _, _ := runtime.Caller(0)
    return file
}

func line() int {
    _, _, line, _ := runtime.Caller(0)
    return line
}

Now for __FILE__ write file() and for __LINE__ write line().

I'm going to close this.

**Comment by mingodad** [comment]
Here is an implementation of it.
Go 1.6.2:
https://github.com/mingodad/go/commit/d7eed6118264a8e06fef3f90264bb394fdf2e2c5

Go master (1.7):
https://github.com/mingodad/go/commit/6f7c0679a3177282a1f3b81b2a03d4b9c90d1598

For gccgo (6.1):
https://gist.github.com/mingodad/e9ccc835021f9004ef9d82d178c0f460
