### ISSUE TITLE
x/mobile/bind: lowercase function names for objC

### ISSUE THREAD

**Issue by scisci** [golang/go#12889]
This is definitely just a nice-to-have! 

In order to comply with style guidelines for objective c and swift, it would be nice if the gomobile bind command had an option to lowercase the first character of exported function names.

**Comment by hyangah** [comment]
yes, I am thinking about converting all method names to start with lowercase. Any objection?

**Comment by crawshaw** [comment]
SGTM

**Comment by rakyll** [comment]
SGTM, method names must start with lowercase in both languages.

**Comment by hyangah** [comment]
I have a draft cl l for objective-c (cl/15780). Avoiding name conflicts seems tricky.

1) what if the lower-case'd method names override NSObject's method names (ex. Init)
2) what if the struct has an exported field Foo, and has a method SetFoo?
3) what if the lower-case'd method names turn out to be objective-c or swift keywords that cannot be used as identifiers (ex. Do)

Similar exceptions will occur for Java too.

**Comment by crawshaw** [comment]
I think it's worth attempting to do this anyway, because the visible effect on the code is to make it look far more like Obj-C.

For conflicts, a carefully placed suffix calculated recursively (_1, _2, etc) can work. Both your points 1 and 3 can be covered by a static list of identifiers, for 2 it is a per-object list of identifiers.

**Comment by hyangah** [comment]
need to update documentation https://godoc.org/golang.org/x/mobile/cmd/gobind 

It seems that some of name conversions (due to conflicts with reserved keywords) are not intuitive.
