### ISSUE TITLE
release: go1.4.3 binary distribution does not include vet

### ISSUE THREAD

**Issue by rhysh** [golang/go#12883]
The [go1.4.3 binary distribution](https://golang.org/dl/go1.4.3.linux-amd64.tar.gz) does not include a `vet` binary. Other versions, including go1.4.2 and go1.5.1, ship a vet binary.

```
$ go version
go version go1.4.3 linux/amd64
$ go vet ./... 
go tool: no such tool "vet"; to install:
	go get golang.org/x/tools/cmd/vet
$ go tool vet -h
go tool: no such tool "vet"; to install:
	go get golang.org/x/tools/cmd/vet
$ go env GOTOOLDIR
/usr/local/go/pkg/tool/linux_amd64
$ ls $(go env GOTOOLDIR)
6a  6c  6g  6l  addr2line  cgo  dist  fix  nm  objdump  pack  pprof  tour  yacc
```

This is likely related to 1421bc10a4f61f92f3a3790a599fd7a02e7909d7 and the return of vet to the main repo.

**Comment by adg** [comment]
Does the suggested `go get` command work for you?

**Comment by rhysh** [comment]
Yes, `go get` works for installing the vet tool, but that's oversimplifying my goal. I maintain some build processes that confirm that code passes vet before compiling, and using the unversioned `go get` command means that they're no longer strictly reproducible. This regression in the go1.4.3 tarball vs the other go1.4.x tarballs means that it's not a drop-in replacement.

I can make sure my build containers have git installed and then `git clone`/`git checkout`/`go install` a specific version, I can repackage the tarball, or I can finish upgrading everything to go1.5 -- so I'm not without options. This just makes the upgrade process less smooth for me and anyone else using vet and go1.4.

If go1.4 is going to be an LTS release for bootstrapping, I think this should go into the go1.4.4 tarball when the time comes.

**Comment by adg** [comment]
1.4 isn't an LTS release. We release 1.4.3 because to address security issues close to the release of 1.5, and since 1.5 contains significant changes to the runtime we felt it wasn't right to force people to upgrade to a new major release to get those security fixes.

1.4 is not necessary for bootstrapping. You can bootstrap with any version of Go beyond 1.4. And it's not necessary to include vet for bootstrapping, either.

The fix to this issue is to restore the functionality to include vet from the tools repo to the x/build/cmd/release tool, but I just don't see it being worth the time to fix it at this point.
