### ISSUE TITLE
playground: Why sharing is forbidden in China mainland ?

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#12908]
AFAIK, Go developers all over the world use playground as examples or demo.
I just wonder whether IPs from China mainland made any abuse on playground? 
If it is not, I am VERY DISTURBED  about such discrimination.

#12747 
https://github.com/golang/playground/commit/7d7eb09c862b75dad445f22fa2706e2626941507

**Comment by hyper-carrot** [comment]
I will continue to focus on this issue. There are a lot of people in China use Golang. We love Golang, although it closed the door on us. But it should be borderless world.

**Comment by ianlancetaylor** [comment]
Our apologies.  This is not something we are able to change.

**Comment by adg** [comment]
The Go project has not "closed the door" on China. Quite the opposite. The change was motivated by a desire to reach *more* Chinese uses, not to discriminate against them.

Quoting @jbuberel replying to @minux from [the original change](https://go-review.googlesource.com/#/c/14190/):

> > Why do we block sharing requests from Chinese users?
Is there a policy for this? Thanks.
> > And I think the reason Chinese users are not able
to access *.golang.org is not due to IP based
blocking at Google's side. Each and every one of
Google's public IP is being black-holed by a
famous firewall.
> You are correct in that Chinese users are unable to access *.golang.org sites because those network blocks have been firewalled by the GFC. However, Google does have several network blocks that have not yet been black-holed from which the *.golang.org services can be served. 
>
> But in order for that to happen, we are required to ensure that we do not permit the *.golang.org sites to be used for creating User Generated Content by Chinese internet users in accordance with those laws. And the Go Playground was highlighted as a method of creating User Generated Content that could get the sites banned explicitly. 

I hope we can agree that it is better for Chinese users to be able to access golang.org, even if that means they can't share or retrieve shared playground snippets.

**Comment by hyper-carrot** [comment]
@adg OK, I see, so sad. :-(

**Comment by shahix** [comment]
@adg but obviously there is discrimination against Iranians. 


![golang](https://cloud.githubusercontent.com/assets/12282326/10436919/8032cd5a-7136-11e5-8b58-5e974c1ef0dd.png)

**Comment by bradfitz** [comment]
@shahix, please realize that neither the Go team nor Google sets either the US government or Iranian government policies on such matters. Or the Chinese policies, for that matter.

**Comment by shahix** [comment]
@bradfitz There is no regulation preventing access to open source software from Iran. Even there is a general license released past year which lift some restrictions on exporting paid software and communication hardwares to Iran. ( http://www.treasury.gov/resource-center/sanctions/Programs/Documents/iran_gld1.pdf ) (Paragraph 6 is pretty interesting)

Around same time (2013~2014) google allowed Iranian users to access google play but limitation still exist for google code and golang.

I am almost sure there is no legal ground to enforce such restriction on accessing open source software from Iran and its company's choice to restrict access. Same codes freely accessible from github mirror repo.

**Comment by adg** [comment]
@shahix thanks for pointing that out. Obviously we (the Go project) would like to make golang.org available in Iran, and also other countries from which it is inaccessible. As you can imagine, there are bureaucratic and technical issues involved in doing that, so it will take time. We are doing what we can.

I'm going to lock this issue to further comments, since there is nothing more I can say about these issues.
