### ISSUE TITLE
runtime: signal.Ignore not work for SIGTRAP

### ISSUE THREAD

**Issue by nyushi** [golang/go#12906]
1. What version of Go are you using (go version)?
    - go1.5.1
2. What operating system and processor architecture are you using?
    - linux/amd64
3. What did you do?
    - Run this program
    ```go
    package main
    
    import (
    	"os"
    	"os/signal"
    	"syscall"
    )
    
    func main() {
    	signal.Ignore(syscall.SIGTERM)
    	syscall.Kill(os.Getpid(), syscall.SIGTERM)
    	println("sigterm ignored")
    
    	signal.Ignore(syscall.SIGTRAP)
    	syscall.Kill(os.Getpid(), syscall.SIGTRAP)
    	println("sigtrap ignored")
    }
    ```
4. What did you expect to see?
    - I want to ignore SIGTRAP
5. What did you see instead?
    - Process killed by SIGRAP
    ```
$ go run main.go
sigterm ignored
SIGTRAP: trace trap
PC=0x46044f m=0

goroutine 1 [running]:
...
```

**Comment by minux** [comment]
os/signal.Ignore can only ignore signal that can be Notified.
SIGTRAP is not one of the signal that can be notified.

(I think the reason might be that SIGTRAP is used by the
debugger and runtime.Breakpoint)

Leaving for @ianlancetaylor to decide what to do.

**Comment by ianlancetaylor** [comment]
I can't think of any reason why we should refuse to ignore a signal that can not be notified.  I think we do that because the sigignore function was copied from sigenable, which does correctly skip signals that can not be notified.

Looking at the os/signal package now, though, I'm a bit puzzled: it looks like once you call Ignore, you can call Notify, but Reset doesn't seem to restore an Ignore'd signal back to the default behavior.

**Comment by nyushi** [comment]
FYI: SIGTRAP can handle by `signal.Notify` in go1.5.1 linux/amd64. (but can't handle in darwin/amd64).

**Comment by minux** [comment]
@nyushi are you sure that Go 1.5.1 on linux/amd64 can Notify SIGTRAP?

The source code clearly says SIGTRAP won't notify.
https://golang.org/src/runtime/signal_linux.go#L20

**Comment by nyushi** [comment]
I tested by this program on docker golang:1.5.1 image.

```go
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGTRAP)
	s := <-c
	fmt.Println("Got signal:", s)
}
```

```
# go version
go version go1.5.1 linux/amd64
# go build
# ./run  # and execute kill command by another shell(kill -TRAP <PID>)
Got signal: trace/breakpoint trap
#
```

**Comment by sprstnd** [comment]
broken to the core, misguided docs. the strangle-hold the core devs have on the language is bringing it to its knees. Too bad, was a promising language.

**Comment by avdva** [comment]
Firstly, a simple program in C can ignore this signal and handle it, so a go program should do this as well. In this case a call to `sigignore(sig uint32) ` does nothing because of the following check:
```go
	if t.flags&_SigNotify != 0 {
		t.flags &^= _SigHandling
		setsig(int32(sig), _SIG_IGN, true)
	}
```
If we call `Notify()`, it calls `sigenable(sig uint32)`, which contains the same check and does not actually set the handler.
However, in `func initsig()` called in `mstart1()`, `SIGTRAP` is assigned the handler `sighandler`. Thus, this handler is called whether we want to ignore the signal or to be notified. The difference is in `func sigsend(s uint32)`, which does the following check:
```go
	if !sig.inuse || s >= uint32(32*len(sig.wanted)) || sig.wanted[s/32]&bit == 0 {
		return false
	}
```
`sig.wanted` is set in `signal_enable()` (which is called by `Notify()`), but `signal_ignore()` resets it. As a result, `sighandler` cannot send a signal and panics.
I think, that the possible solution is to remove the check
```go
	if t.flags&_SigNotify != 0 {
```
in `sigdisable(), sigenable(), and sigignore()`, because, as I understand, if `_SigNotify` is not set, it does actually mean, that we cannot handle or ignore a signal. In this particular case `SIGTRAP` has the flag `_SigThrow`, which means, that the *default* action is "Terminate (core dump)", but we can install own handlers as well.
With these fixes `sigignore` will actually set `_SIG_IGN` as a handler for such signals.
If this solution looks logical, I can make a CL.

**Comment by ianlancetaylor** [comment]
I haven't tried to think through all the details, but that does seem plausible.

@eliasnaur Do you remember why you added the test of _SigNotify to those functions?

**Comment by eliasnaur** [comment]
I believe my reason was cargo culting. Signal handling is subtle enough that I tried to stay as close to the original code as possible, and as far as I can tell, _SigNotify was there in the original code. As far as I can tell, the original checks were introduced in 

commit cb4428e555f664a64b0e2f5f4fe6e3c5991dbdd7
Author: Russ Cox <rsc@golang.org>
Date:   Fri Mar 15 00:00:02 2013 -0400

    os/signal: add Stop, be careful about SIGHUP
    
    Fixes #4268.
    Fixes #4491.
    
    R=golang-dev, nightlyone, fullung, r
    CC=golang-dev
    https://golang.org/cl/7546048


I'm sorry for not being more helpful.

**Comment by avdva** [comment]
If we look at `func sighandler(sig uint32, info *siginfo, ctxt unsafe.Pointer, gp *g)` in `signal_*platfom*.go`, we'll see the following check (ex. line 134 in `signal_amd64x.go`):
```go
if c.sigcode() == _SI_USER || flags&_SigNotify != 0 {
	if sigsend(sig) {
		return
	}
}
```
Which means, that we should send all the signals from a user or all signals with `_SigNotify`. In checks in  `sigdisable(), sigenable(), and sigignore()` the author wanted to ensure, that handlers can be installed for signals with `_SigNotify`, but it seems that the fact, that this flag is actual for signals from kernel only was not taken into account.

**Comment by avdva** [comment]
There is a line in `os2_darwin.go:9`:
```go
_SI_USER     = 0 /* empirically true, but not what headers say */
```
@rsc , could you remember, why you used 0?
Consider the following program:
```C
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void sig_handler(int number, siginfo_t *info, void * unused) {
  printf("si_code = %d\n", info->si_code);
}

int main(void) {
  struct sigaction sig_action;
  sig_action.sa_sigaction = sig_handler;
  sigemptyset(&sig_action.sa_mask);
  sig_action.sa_flags=SA_SIGINFO;

  if(sigaction(SIGTRAP,&sig_action,NULL))   {
    fprintf(stderr,"sigaction(SIGTRAP) fail\n");
    exit(1);
  }
  while (1) {
    sleep(1);
  }
}
```
If we send a signal `kill -s SIGTRAP pid`, the output will be `si_code = 1` on OSX Yosemite.
Thanks in advance.

**Comment by rsc** [comment]
@avdva I used 0 because that's what the kernel sends. There is no guarantee that C exposes to its clients the same values the kernel sends, and in this case I believe it does not. If you look in the C library shipped with OS X I believe you will find a mapping somewhere.

Or try putting a print of si_code in the signal handler in the Go runtime, write an equivalent Go program, and kill -TRAP it and see what the print says.

**Comment by avdva** [comment]
You are right. I was confused by the following. I added in the beginning of `signal_amd64x.go` code
`print("\n sigcode = ", c.sigcode(), "\n")`.
There is a program:
```go
package main

/*
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

void trap() {
	asm ("int $3");
}
*/
import "C"

import (
	"os"
	"os/signal"
	"syscall"
)

func trap() {
	C.trap()
}

func main() {
	const fromUser = false
	var raise func()
	if fromUser {
		raise = func() {
			syscall.Kill(os.Getpid(), syscall.SIGTRAP)
		}
	} else {
		raise = trap
	}
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGTRAP)
	raise()
	<-c
	println("sigtrap notified")
}

```

If I run it on linux/amd64, the output is 0 for `user` path and 128 for another path.
But if I run it on darwin/amd64, I get 1 for both cases. Moreover, I get 1 if I send this signal via kill(). That is why the test in cl fails.

**Comment by rsc** [comment]
Maybe we are just fundamentally misreading what the OS X kernel is telling
us. But if it really does treat user- and kernel-generated signals the
same, we have to err on the side of assuming they are kernel-generated, to
avoid infinite loops.

**Comment by avdva** [comment]
Well, the same program for SIGSEGV works fine. 0 - for user and 1 - for kernel.
For SIGFPE it outputs 0 and 7.
I want to say, that 0 really means `user signal`, but, probably, there are some hidden details for SIGTRAP.

**Comment by rsc** [comment]
How often do you run kill -TRAP I guess?

**Comment by avdva** [comment]
I run `kill -s TRAP pid` or `kill -s SIGTRAP pid`. Both produce sigcode=1
