### ISSUE TITLE
x/tools/cmd/godoc: add way to select GOOS/GOARCH for syscall pkg

### ISSUE THREAD

**Issue by techtonik** [golang/go#12988]
https://golang.org/pkg/syscall/#pkg-variables
`syscall` documentation only shows docs for LInux, which makes it harder than necessary to troubleshoot cross-platform bugs
https://github.com/golang/go/issues/12978#issuecomment-149130465

**Comment by bradfitz** [comment]
This is super low priority since it basically only affects the syscall package, and people can just run godoc locally with GOOS= and GOARCH= set to see the syscall docs on another platform.

Maybe we could merge GOOS=windows and GOOS=linux symbols together in godoc by default for just the syscall package.

/cc @griesemer @adg

**Comment by techtonik** [comment]
@bradfitz do you have stats how often people run these commands? I am asking because I read and search for everything online.

**Comment by bradfitz** [comment]
We don't track stats.

**Comment by bradfitz** [comment]
Pending CL at   https://go-review.googlesource.com/1371

**Comment by larzconwell** [comment]
https://go-review.googlesource.com/#/c/1371/ Has been merged so this can probably be closed now.

You can change the default GOOS/GOARCH using the query string in golang.org/pkg requests.
