### ISSUE TITLE
test: 25 out of 100 finalizer are not called in tinyfin.go

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#13100]
Failed on windows-amd64-gce builder a few times recently: http://build.golang.org/log/1a2e106640beae06227ade2c6cef55bc7d0cf611

```
...
##### ../test
# go run run.go -- tinyfin.go
exit status 1
25 out of 100 finalizer are not called
panic: not all finalizers are called

goroutine 1 [running]:
main.main()
	C:/workdir/go/test/tinyfin.go:59 +0x29f
exit status 2

FAIL	tinyfin.go	1.074s
```

Alex

**Comment by bradfitz** [comment]
Yes, I've been seeing this too.
https://storage.googleapis.com/go-build-log/7f62c78e/windows-amd64-gce_97ebdf8d.log

Flaky test needs to be fixed or die. But I suspect it might be real, being GC-related?

/cc @aclements @RLH @dvyukov

**Comment by dvyukov** [comment]
This used to work, so looks like a regression.

**Comment by RLH** [comment]
The actual test appears not to be valid.  Perhaps Go should produce an
error while trying to do setFinalizer on an x that is not valid based on
the following restriction from the docs.

"The argument x must be a pointer to an object allocated by calling new or
by taking the address of a composite literal. "

**Comment by dvyukov** [comment]
@RLH Why?
We would need to associate a new bit of meta-information with each heap object just for the sake of this check. And runtime actually does not care how it was allocated. Am I missing something?
There are other such cases in std lib tests.
I think we need to refine the documentation. As far as I understand the intention was to say "beginning of an individual object".
+ @rsc

**Comment by aclements** [comment]
Here are the current failures on the dashboard:

[2015-10-26T23:36:22-53d43cb/windows-amd64-gce](http://build.golang.org/log/0793cfa0a066d651c1bdab5c3f89235461c56432)
[2015-10-27T03:48:21-00f4243/solaris-amd64-smartos](http://build.golang.org/log/e7bf79834cc17d3952ee35d2422c8d3fabdd442e)
[2015-10-28T19:51:05-72180c3/windows-amd64-gce](http://build.golang.org/log/34340d3911c30230e5823ec9bf07918e262a113b)
[2015-10-29T21:12:08-a59a275/windows-amd64-gce](http://build.golang.org/log/1a2e106640beae06227ade2c6cef55bc7d0cf611)
[2015-11-01T04:45:37-3d5163c/windows-amd64-gce](http://build.golang.org/log/c8d9424ea0456a91bb4207af8ab6bb983c2c850f)

Note that it has happened once on a non-Windows OS.

Looking at the commits before this started, d18167f "runtime: fix tiny allocator" seems like the likely culprit. However, this commit fixed the previously broken tiny allocator so that it actually reused tiny blocks rather than creating a new one for each allocation, so it most likely just revealed an existing bug.

All of these failures are exactly "25 out of 100 finalizer are not called," though note that 25 is the smallest number of not-run finalizers that this test will fail at. It's necessary to accept a few not-run finalizers because of combined tiny allocations, but I'm not sure where the 25 threshold came from. It may just be arbitrary. In the theoretical worst case, every allocation by the test could be combined with some other tiny allocation that's still live, and none of the finalizers will run.
