### ISSUE TITLE
runtime: decide GOTRACEBACK default setting

### ISSUE THREAD

**Issue by rsc** [golang/go#13107]
CL golang.org/cl/16512 introduces a "GOTRACEBACK=single" mode to print only the current goroutine and make it the default behavior. We need to decide whether to keep this default or restore the old default (GOTRACEBACK=all aka GOTRACBACK=1).

**Comment by aclements** [comment]
One place this has harmed is test time outs. Since the time out panic happens on a different goroutine than the test, you can no longer tell what test was running or where it was stuck. For example: http://build.golang.org/log/a7048d0c840f1815694b38306ce9e7f723d4e382

We could make testing/testing.go:startAlarm print all of the stacks before panicking (or perhaps exiting) by calling runtime.Stack with all set to true. AFAIK, there's no way for a user to change GOTRACEBACK at runtime.

**Comment by davecheney** [comment]
What about passing GCTRACEBACK=all to the test binary. That should make it
generate the full stack dump if the timeout goroutine fires, or the dead
timer in the upper cmd/go process fires off SIGQUIT.

**Comment by aclements** [comment]
That only helps if you're running the test through go test. It doesn't help if you're, say, running a test binary compiled by go test -c.

**Comment by davecheney** [comment]
That is true, I had not considered that. I thought that the problem was
.all.bash which runs the go tool, which runs the runtime test, so my
solution might be applicable. Sorry if I misunderstood the requirement.

**Comment by aclements** [comment]
>One place this has harmed is test time outs.

Moved to a new issue: #13681

**Comment by rsc** [comment]
The default seems to be working well. Let's keep it.
