### ISSUE TITLE
crypto/tls: Dotted-quad Servername given in ServerNameList extension

### ISSUE THREAD

**Issue by RalphCorderoy** [golang/go#13111]
http://tools.ietf.org/html/rfc6066#section-3 defines Server Name Indication and says «The hostname is represented as a byte string using ASCII encoding without a trailing dot... Literal IPv4 and IPv6 addresses are not permitted in "HostName"». I take that to mean a dotted-quad ASCII string isn't allowed, perhaps to avoid the ambiguity of it and the destination IP address differing. The alternative is it means a 32-bit IPv4 address cannot be given, but that's already ruled out by "ASCII encoding".

A tls.Dial("tcp", "3.1.4.1:5", ...) passes "3.1.4.1" in the TLS's ClientHello.

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by agl** [comment]
https://go-review.googlesource.com/16742

**Comment by RalphCorderoy** [comment]
The commit that closed this issue was promptly reverted by @agl, https://go-lang.org/cl/16770
What's the reason?  I'd like to know if I misunderstood.  Did it break a server that's expecting dotted quad?

**Comment by bradfitz** [comment]
Unknown. @agl?

**Comment by willmo** [comment]
@agl It's still broken for IPv6 literals with HTTPS, since HTTP encloses IPv6 literals in square brackets so that net.ParseIP can't recognize them.

I'm not sure if tls should handle square brackets, or if http should strip the brackets when setting ServerName, or what.

Should I reopen this issue, or create a new one?

**Comment by mikioh** [comment]
@willmo, please open a new issue.
