### ISSUE TITLE
tour: Change links color

### ISSUE THREAD

**Issue by kbariotis** [golang/go#13121]
Context: https://tour.golang.org/

Links in the slides are black, as the text, and it's hard to differentiate them.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by minux** [comment]
(Copied from comment on #13122, sorry for the duplication)

This seems intentional, but I don't understand the intention.

In https://tour.golang.org/static/css/app.css, both the normal
color and text-decoration properties of a elements are suppressed:
a {
    color: inherit;
    text-decoration: none;
}

/cc: @campoy, this change is made in the tour redesign commit.
https://github.com/golang/tour/commit/4d282f83d3f705f38e724c60a36f48680e90a71e

**Comment by campoy** [comment]
Agreed links should be easier to see

https://go-review.googlesource.com/17405

Please review
