### ISSUE TITLE
Can't see a link in tour of go

### ISSUE THREAD

**Issue by psylone** [golang/go#13122]
Context: https://tour.golang.org/flowcontrol/13

In a sentence: "To learn more about defer statements read this blog post" the phrase **blog post** is really the link, but looks like a regular text.

Ubuntu 15.04
Google Chrome Version 46.0.2490.71 (64-bit)

**Comment by psylone** [comment]
Oh, sorry, there was the same issue #13121

**Comment by minux** [comment]
This seems intentional, but I don't understand the intention.

In https://tour.golang.org/static/css/app.css, both the normal
color and text-decoration properties of a elements are suppressed:
a {
    color: inherit;
    text-decoration: none;
}

/cc: @campoy, this change is made in the tour redesign commit.
https://github.com/golang/tour/commit/4d282f83d3f705f38e724c60a36f48680e90a71e
