### ISSUE TITLE
runtime: fatal error: malloc deadlock with Go 1.5.1

### ISSUE THREAD

**Issue by fjl** [golang/go#13143]
A go-ethereum user reported a [crash](https://github.com/ethereum/go-ethereum/issues/1962) with the following stack trace:
https://gist.github.com/CJentzsch/31aab5b31fae6805f893

The issue occurred on linux/arm with go-ethereum built using Go 1.5.1.
The binary in the trace [can be downloaded here](https://build.ethdev.com/builds/ARM%20Go%20develop%20branch/geth-ARM-20151103142042-1.4.0-dda3bf3.tar.bz2).
It does not seem to be reproducible, but looks similar to https://github.com/golang/go/issues/10469 (x/mobile issue on android/arm).

**Comment by karalabe** [comment]
Just to add to the above report, although this is the first dump we manage to capture (was running on an Raspberry Pi), we've also seen two eerily similar scenarios (no crash dumps were generated for those so we couldn't place them), where our code crashed after processing the same amount of data. One of them was an Android cross compilation running on on Galaxy Nexus phone (direct cross compile, not through `gomobile`), and another was an ARM cross compilation running on the Tizen platform.

**Comment by ianlancetaylor** [comment]
CC @aclements @dvyukov @rsc

**Comment by dvyukov** [comment]
The real bug here is this:
```
runtime.panicindex()
	/usr/local/go/src/runtime/panic.go:12 +0x48
runtime.mHeap_Grow(0xdef668, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:647 +0x25c
runtime.mHeap_AllocSpanLocked(0xdef668, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:532 +0x6c8
```

I suspect it can happen on OOM, some of the paths in mHeap_SysAlloc are not well tested.
I've mailed a fix a potential cause in cl/16622.

**Comment by aclements** [comment]
I have now proven both by hand and using an automated theorem prover* that either:
1) this index out of bounds is impossible,
2) the traceback is lying about the npage argument to mHeap_Grow,
3) there was some horrible memory corruption, or
4) there are bugs in both of my proofs.

The automated proof did, however, uncover a wrap-around bug where a very large allocation could cause an out of bounds index rather than rejecting the allocation. That would suggest case 2. Assuming I can reproduce this in real code, the fix is trivial.

@fjl, @karalabe, is it possible your code attempted a particularly large allocation (like over 3GB)? Also, could you run "getconf PAGESIZE" on the system that generated the traceback? I assumed it was 4096 because that's what the runtime uses on 32-bit non-NACL ARM, but if it isn't that could be important.

* I used concolic execution of a model of the memory system, which doesn't lend itself to infinite code paths, so specifically I proved that no sequence of four allocations ending in an allocation of 8 pages can cause an index out of bounds on the last allocation. I chose four to exercise all combinations of code paths within the same final program state and because running four already took a really long time. :)

**Comment by aclements** [comment]
Scratch the wrap-around I'd found. The wrap-around does happen, but assuming the kernel is correctly bounds-checking the mmap call itself (which I hadn't previously modeled in my proof), the allocation will fail anyway, just at a slightly later point.

**Comment by aclements** [comment]
@fjl, @karalabe, what was the GOARM level on the machine that produced the traceback?

**Comment by aclements** [comment]
Also, what kernel version were you running?

**Comment by aclements** [comment]
I increased the fidelity of the system call model in my proof and finally found a way this can happen and I've managed to reproduce it with a few helping hacks in the runtime.

The cause is ultimately quite simple: In mHeap_SysAlloc, if an allocation at arena_used would exceed arena_end (but wouldn't yet push us past arena_start+_MaxArean32), we try to extend the arena reservation by another 256 MB. Note that this could be a small allocation, which is consistent with this bug. We extend the arena by calling sysReserve, which calls mmap without MAP_FIXED on 32-bit, which means the address is just a hint and the kernel can put the mapping wherever it wants. If it happens to choose an address below arena_start (the kernel also chose arena_start, so there could be lots of space below it), then it's the beginning of the end. We don't detect that case in mHeap_SysAlloc. In fact, mHeap_SysAlloc will totally screw up arena_end and arena_used and then return the low pointer to mHeap_Grow, which will subtract arena_start from the pointer, which will underflow and produce a huge value of p, which we'll then use as an index in to h_spans, which will panic.

The fix is just to check for this case in mHeap_SysAlloc. I'll roll a CL tomorrow or Monday.

**Comment by RLH** [comment]
Nicely done...

**Comment by aclements** [comment]
For reference, this is the symbolic model and execution engine I used: https://gist.github.com/aclements/cd6cd1a93732099ff982

This requires fixes to the STP Python bindings that are currently in STP pull request https://github.com/stp/stp/pull/204
