### ISSUE TITLE
net: TestDialTimeout failed "connection reset by peer"

### ISSUE THREAD

**Issue by WanliTian** [golang/go#13144]
--- FAIL: TestDialTimeout (0.01s)
        dial_test.go:108: got error "dial tcp 127.0.0.1:21743: connection reset by peer"; not a timeout
FAIL
FAIL    net     1.989s

**Comment by WanliTian** [comment]
go 1.4.3
centos 6.3

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by mikioh** [comment]
Sorry, I cannot assume what happened exactly because that test case is not written by me, although we fixed that sort of flakiness in go1.5. IIRC, test cases in go1.4 and below have two problems: no care about interference btw tester goroutines and insanely dependance on the protocol stack inside kernel.

Please try go1.5 and above, and feel free to reopen this issue if you see the same error in go1.5 and above. Thanks.
