### ISSUE TITLE
encoding/binary: Write() struct int type no output.

### ISSUE THREAD

**Issue by codinl** [golang/go#13156]
```
// right：int32 is ok
type T struct {
	A int32
}

// wrong：int has no output,and no error
type T struct {
	A int
}

func main() {
	buf := new(bytes.Buffer)
	t := T{1}
	err := binary.Write(buf, binary.BigEndian, t)
	if err != nil {
		panic(err)
	}
	fmt.Println("buf.Bytes()=", buf.Bytes())   // if t.A is "int" but not "int32" type, here no out put.
}
```

**Comment by ianlancetaylor** [comment]
I get an error with this program: http://play.golang.org/p/1ssllTW1H- .

If you still think there is a bug, please provide a complete standalone program and show the output you get.

**Comment by dominikh** [comment]
What version of Go are you on? Here (1.5.1), it does return an error: binary.Write: invalid type main.T`. It's invalid because encoding/binary is for fixed size data, and `int` isn't fixed size: it can be 32 or 64 bits wide, depending on the architecture.

See also http://play.golang.org/p/BoCMunGSHA for the error.
