### ISSUE TITLE
x/mobile: app crashed, android 2.3.6 

### ISSUE THREAD

**Issue by 230v** [golang/go#13172]
I build basic example, but it crashed. gomobile suported old android?

**Comment by hyangah** [comment]
It's not surprising that the gomobile compiled app doesn't run on Gingerbread (API level 10)
Gomobile uses NDK of platform-15 internally. 
I propose to update the minSDKVersion in the default AndroidManifest to be 15, not 9, and clearly document it.

/cc @crawshaw @rakyll @dskinner

**Comment by dskinner** [comment]
wasn't aware of ndk constraint on api-15.  As mentioned on #13109 I believe the appropriate thing to do is abort on compilation if a manifest declares a minimum api level. The gomobile cmd should then insert the min api tag itself to whatever is decided (+2 to api-15). These are the tentative plans in the issue I linked, but it may be a month or two before that issue is actually resolved.

In the interim, there's little reason the current implementation couldn't go ahead and do this now. This would result in the following behavior as related to the reported issue.

* Specifying a minimum or target api would result in compilation abort and error message logged.
* Attempting to install the resulting apk on an older version of android would result in android reporting that the app is for newer versions of android and abort the install.

I can put together a CL this weekend if this sounds ok.

**Comment by hyangah** [comment]
In this particular case (the basic example), the manifest file is the default one filled by gomobile tool.
We need to update it to be api-15. 

https://github.com/golang/mobile/blob/master/cmd/gomobile/manifest.go#L64

In case a custom manifest file is given, yes, I think it's okay to abort and output helpful error message. 
I hope android gives already a useful error message if the device platform is too old for the app. (I am not sure)

Assigning to @dskinner. Thanks!

**Comment by 230v** [comment]
thanks to all.
