### ISSUE TITLE
runtime: reconsider stack shrinking

### ISSUE THREAD

**Issue by randall77** [golang/go#13183]
Issue #13169 has pointed out an issue which has bothered be for a while: when is it safe to shrink a stack?  Direct goroutine->goroutine copies are touchy - how do we know that the destination stack isn't being shrunk?  In a world without stop-the-world, it isn't easy to know that the destination goroutine isn't being shrunk right when we're trying to copy data to the receiving goroutine.

We get away with this right now by doing shrinking in marktermination.  If we do shrinking some other way, we could shrink without having all threads stopped, which would help our pause times.

A possible solution is to only allow stack shrinking in place.  I wouldn't be too hard to do so, I had a buddy allocator stack scheme coded up about a year ago that could do this (by only freeing the unused half of the stack, leaving the rest in place).  I didn't pursue the idea because it can make fragmentation somewhat worse than the current scheme.  But maybe that problem is not as bad as this one.

Or maybe there is some synchronization scheme that could lock stacks so that channel sending and shrinking were mutually excluded?

@aclements

**Comment by aclements** [comment]
Interesting. It hadn't occurred to me that the exact problem that was preventing easily moving stack shrink out of STW was, in fact, already a bug.

What do you think of my suggestions in https://github.com/golang/go/issues/12967#issuecomment-151196217?

**Comment by dr2chase** [comment]
Another possibility is to make stack shrinking the responsibility of the
thread whose stack is being shrunk -- or if we add that mutex for shrinking
and channelling, perhaps the stack will sometimes be asked to shrink itself
at a convenient moment.

David

**Comment by aclements** [comment]
You don't want it to be *solely* the responsibility of the goroutine itself because a common pattern is to have a top-level loop that blocks on a channel and when it receives something, use a bunch of stack, then unwind the stack, then block again. Since it could be blocked for a long time, you either need it to shrink its stack on the way in to the receive (very hard to predict when this is worthwhile) or you need something else to be able to shrink its stack when it has been blocked for a long time, which gets us right back to the problem of stack shrinking racing with a channel receive.

**Comment by RLH** [comment]
Is the cost of a level of indirection and not sharing your stack worth all
of this pain?

**Comment by randall77** [comment]
No point in having this discussed in two places, let's move to #12967 .
