### ISSUE TITLE
GOLANG TOUR IN OTHER LANGUAGES (DOES NOT WORK ! ) - DIFERENCES BETWEN GOOGLE AND MICROSOFT FORUM

### ISSUE THREAD

**Issue by elmoro777** [golang/go#13189]
IN MICROSOFT FORUM PEOPLE COLABORATE WITH SOLUTIONS IN ALL KIND OF WAYS 

IN GOOGLE ... "GURUS" CLOSE ISSUE FIRST - DRINK COFFE AND PLAY GAMES AT HOME 

GOOD LUCK ALPHABET !

**Comment by DisposaBoy** [comment]
Just so you know: I don't work for Google or have any relation with them.

If you came anywhere near anything I was a moderator of with this dickish attitude I'd close and delete all your post immediately without response.

Stop spamming me without your bullshit!

**Comment by elmoro777** [comment]
OHHHH !!!! REALLY ???? 
YOUR ANSWER IS ANOTHER KIND OF CRAP LIKE GOOGLE GUYS ANSWER MY ISSUE
SAME SHIT.

**Comment by mattn** [comment]
AFAIK, This is not forum. This is bug tracker. If go team remaining the issues with opening status, we will not be able to manage bugs. So they close invalid issues, duplicate issues. If you have opinion that the issue is not duplicated or invalid, you should reopen the issue and explain why you think not so.

**Comment by minux** [comment]
The translated Go tour is not maintained by this project,
and there is already an open issue for the translated tour
project. I don't see there is any problem closing the issue.
