### ISSUE TITLE
syscall: Getpagesize should consult OS on arm64

### ISSUE THREAD

**Issue by hrw** [golang/go#13191]
There is code in src/syscall/syscall_linux_arm64.go file:

```go
func Getpagesize() int { return 65536 }
```

But this architecture supports three values for PAGE_SIZE: 4K, 16K and 64K which are selected at kernel compilation time.

Userspace is expected to check which value is set. Simplest solution is to use sysconf(_SC_PAGESIZE) function call (same as getpagesize()).

**Comment by dmcgowan** [comment]
This is causing an issue in Docker running on arm64 with the new overlay driver. We use the pagesize to determine when we the mount arguments are too large. It would be preferable to report the PageSize as the minimum value rather than the maximum to avoid unexpected truncation to syscalls.

See https://github.com/docker/docker/blob/3b0660da30a23b86a2f29f1ecf3ded52ab7fe577/daemon/graphdriver/overlay2/overlay.go#L476

**Comment by vielmetti** [comment]
Thanks @dmcgowan - good catch!

**Comment by vielmetti** [comment]
This commit

https://github.com/golang/go/commit/1b9499b06989d2831e5b156161d6c07642926ee1

looks like it addresses this problem, with the other related issue at

https://github.com/golang/go/issues/10180

**Comment by bradfitz** [comment]
Oh, yeah, @aclements already did this in 1b9499b
