### ISSUE TITLE
wiki: post policy for editing the github wiki

### ISSUE THREAD

**Issue by natefinch** [golang/go#13226]
The github wiki is editable by anyone (I think?) and does not support PRs (to my knowledge).... this makes it somewhat troublesome when you see something you want to change or add to the wiki.

I suggest adding a section to the top of the wiki, where it is very easy to find, about the process for editing or suggesting edits to the wiki.

**Comment by adg** [comment]
cc @jbuberel

**Comment by jbuberel** [comment]
I agree @natefinch that we should have a policy, and that it should be easily findable by people browsing the wiki.  I do keep an eye on the changelogs, and have only had to rollback one commit (someone accidentally added a new file).

How about this for a policy:

* Anyone logged into their GitHub account can submit edits to the contents of the Go Wiki.
* If you would like to add a new page, please first open an issue in the golang/go/issues tracker with prefix 'wiki' to propose the addition. Clearly state why the content doesn't fit into any of the existing pages.
* Because renaming of pages in the wiki can break external links, please open an issue before renaming or removing any wiki page.

Once we have a finalized version of a policy, I can add it to the head/foot of the Home.md page.

**Comment by rakyll** [comment]
@jbuberel 

SGTM

And let's mirror the wiki repo git somewhere.

**Comment by jbuberel** [comment]
This is now visible at the top of the [home](https://github.com/golang/go/wiki/Home) page.

**Comment by rakyll** [comment]
That's a lot of text to scroll on each page. Can't we just have a CONTRIBUTING page for the wiki?

**Comment by jbuberel** [comment]
It is only at the top of the Home.md file for now. If it were placed in a separate file, it would fail to meet @natefinch's request for being visible, IMO.

If we get complains about the current positioning, we can revisit.

**Comment by natefinch** [comment]
FWIW, I'm fine with it being a link from the top of the home page, or even the top link in the table of contents or whatever.  It just needs to be highly visible, since anyone can just go edit the wiki, and while I doubt few people would be malicious, knowing the proper policy will save the maintainers a lot of work undoing editing that were not done through proper channels.
