### ISSUE TITLE
net/http: Please offer function "ServeTLS"

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#13228]
In package net/http, there's a pair of Listen\* functions: ListenAndServe, ListenAndServeTLS.

It would be incredibly helpful to offer both Serve and ServeTLS as well.

**Comment by bradfitz** [comment]
Serve already exists:
https://golang.org/pkg/net/http/#Server.Serve

We may do something more in Go 1.7, especially in light of LetsEncrypt, making that a bit easier. We'll see.

**Comment by Gurpartap** [comment]
I had to serve on systemd socket activation's fds listener, along with TLS.

Here's a [`Server.ServeTLS`](https://github.com/Gurpartap/go/commit/31135bf3c299a13672c3eb846f9efdfd13b372ed) I put together from existing code in `Server.ListenAndServeTLS`:
https://github.com/Gurpartap/go/commit/31135bf3c299a13672c3eb846f9efdfd13b372ed

Tested to work with systemd socket listening on `443` and using ServeTLS with listener provided by https://github.com/coreos/go-systemd/tree/master/activation

(If it matters, I'm using this with LetsEncrypt provided cert/key in my project, not that the function's exclusively for this purpose)

**Comment by odeke-em** [comment]
@Gurpartap are you interested in making that a patch that's code reviewable on Gerrit since we
can't review patches here?

**Comment by niklas88** [comment]
@bradfitz I haven't seen any changes or comments to address your comments from March, is there some way I can help and take over this CL? This would be very helpful for my home automation project which uses systemd socket activation. If this doesn't make it into 1.9 I'll have to resort to a much uglier custom copy of this code.

**Comment by bradfitz** [comment]
@niklas88, sure, feel free to take it over.

I left new comments on https://go-review.googlesource.com/c/38114/ so be sure to incorporate those too.

**Comment by niklas88** [comment]
@bradfitz ok, so I have incorporated your comments and added a test. However I don't know how to mail this since it will then also contain the original change by @Gurpartap and git codereview doesn't let me mail changes with another author. I added commits on top of his change only to keep his authorship intact (by using the download copy paste from gerrit). Any idea how to best resolve this? It's my first time using gerrit...

**Comment by bradfitz** [comment]
@niklas88, just send a change in a single commit that's a copy of his under your own git Author name. You can give @Gurpartap credit in your commit message and reference his original Gerrit URL.

**Comment by niklas88** [comment]
Ok thanks for that tip, I'm not sure I've done this right as I ended up with two reviews instead of a combined one as it wouldn't let me mail it with the existing Change-Id but here it is:

- https://go-review.googlesource.com/44074 is an updated version of Gurpartap's change with your comments addressed
- https://go-review.googlesource.com/c/44075/ adds a test
