### ISSUE TITLE
x/tools/cmd/godoc: incomplete list of callers

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13235]
At head (f762d0d2, golang/tools@d94e6fe0), if I run

    GOPATH= godoc -http=:6060 -analysis=type,pointer

and go to http://localhost:6060/src/runtime/runtime2.go, and click "func" in

    81	func efaceOf(ep *interface{}) *eface {

it lists only two callers:

    Callers of runtime.efaceOf:
    getgcmask at line 1640
    BenchSetType at line 134

But there's at least several more:

    $ grep efaceOf *.go
    error.go:	e := efaceOf(&x)
    export_test.go:	e := *efaceOf(&x)
    heapdump.go:		eface := efaceOf(&p.arg)
    mbitmap.go:	typ := (*ptrtype)(unsafe.Pointer(efaceOf(&x)._type)).elem
    mbitmap.go:	e := *efaceOf(&ep)
    mfinal.go:	e := efaceOf(&obj)
    mfinal.go:	f := efaceOf(&finalizer)
    mfinal.go:		if assertE2I2(ityp, *efaceOf(&obj), nil) {
    runtime2.go:func efaceOf(ep *interface{}) *eface {

CC @alandonovan

**Comment by alandonovan** [comment]
The pointer analysis treats calls to exported functions in the runtime package specially because when the analysis was written, the package was mostly C code so there wasn't much to analyze.  Instead of looking at the source for that package, the analysis has built-in knowledge of the aliasing and callgraph effects of the important functions, which are few.

Even though the runtime package is now in Go, I would not revisit this decision because the package makes such extensive use of unsafe.Pointer conversions, which the pointer analysis handles unsoundly: it treats a conversion from unsafe.Pointer to T just like new(T).

You can see the list of PTA intrinsics in golang.org/x/tools/go/pointer/intrinsics.go.

So, working as intended, and tough luck if you work on the runtime. :(

**Comment by mdempsky** [comment]
Hm, I'm having trouble understanding how PTA and package runtime instrinsics would be relevant to the particular issue I pointed out.  All of the efaceOf calls are direct calls via the function's name, so it's odd to me that it finds a couple of them, but not all?
