### ISSUE TITLE
x/tools/cmd/godoc: goroot flag has no effect when running in command-line mode

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#13296]
When running in command-line mode, specifying the `-goroot` flag has no effect.  Running:

```
godoc -goroot=/usr/local/go1.4.2 math/big
```

would list `Float` too:

```
Package big implements multi-precision arithmetic (big numbers). The
following numeric types are supported:

    Int    signed integers
    Rat    rational numbers
    Float  floating-point numbers
```

If served over HTTP (`godoc -goroot=/usr/local/go1.4.2 math/big -http=:6060`), the resulting documentation page is as expected.

Setting `GOROOT` environment variable instead works as expected:

```
GOROOT=/usr/local/go1.4.2 godoc math/big
```

**Comment by agnivade** [comment]
This happens because when a relative path is passed, the GOROOT is assumed to be `build.Default.GOROOT`. 

If you do - `godoc -goroot=/usr/local/go1.4.2  /usr/local/go1.4.2/src/math/big`. It gives the correct output. Although it defeats the purpose of passing goroot in the first place.

Will send a fix.
