### ISSUE TITLE
cmd/compile: The compiler does not detect an initialization loop

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#13343]
... as in the following program:

```go
package main

var (
	a, b = f()
	c    = b
)

func f() (int, int) {
	return c, c
}

func main() {}
```

Related, though different issue here: #7320

go version go1.5.1 darwin/amd64
go version go1.5.1 linux/amd64
go version devel +af8cd3f Fri Nov 20 19:56:51 2015 +0000 linux/amd64

**Comment by ianlancetaylor** [comment]
FYI, gccgo reports

foo.go:4:8: error: initialization expressions for ‘b’ and ‘c’ depend upon each other
     a, b = f()
        ^
foo.go:5:5: note: ‘c’ defined here
     c    = b
     ^
foo.go:5:5: error: initialization expressions for ‘c’ and ‘b’ depend upon each other
foo.go:4:8: note: ‘b’ defined here
     a, b = f()
        ^
/home/iant/foo4.go:5:5: error: initialization expression for ‘c’ depends upon itself
     c    = b
     ^

**Comment by griesemer** [comment]
gotype reports:

foo.go:4:8: initialization cycle for b
foo.go:4:8: 	b refers to
foo.go:8:6: 	f refers to
foo.go:5:5: 	c refers to
foo.go:4:8: 	b

**Comment by kvu787** [comment]
Interestingly, swapping `a` and `b` does generate a cycle error:

```
package main

var (
	b, a = f()
	c    = b
)

func f() (int, int) {
	return c, c
}

func main() {}
```

`cmd/compile/internal/gc/sinit.go:init1` is responsible for producing a list of definitions needing initialization code in dependency order, and for detecting initialization loops. `init1` incorrectly marks function nodes as `InitDone` prior to traversing them.

Hence, in the first example, it will not detect the cycle on `b` because that involves traversing `f` twice:

```
a, b = f()
a
f()
f // mark f as done, but still traverse it
c
b
f()
// f has been marked done, so it is not checked and the cycle is undetected
```

In the second example, it will detect the cycle because `f` only has to be traversed once:

```
b, a = f()
f()
f
c
b // cycle detected
```
