### ISSUE TITLE
runtime: default handler for terminate signals should resend signal to itself, not call exit()

### ISSUE THREAD

**Issue by eswierk** [golang/go#13484]
According to [How to be a proper program](http://www.cons.org/cracauer/sigint.html), a UNIX process that handles SIGINT in order to clean up before exiting must resend the signal to itself, rather than calling exit() or the like. Otherwise its parent process has no way of knowing that the signal is the reason for the process exit.

The same logic applies to other signals that result in terminating the process, including SIGTERM and SIGQUIT. In particular, failing to handle SIGTERM in this manner causes confusing behavior when running as a service under systemd, which sends SIGTERM to stop the service cleanly. systemd expects the process to indicate it exited due to SIGTERM. Instead it sees an exit status of 2 and treats it as a failure, logging misleading error messages like "Unit entered failed state".

Instead of calling exit(2), the sighandler() for UNIX runtimes should reset the handler to SIG_DFL and resend the signal to itself.

**Comment by rsc** [comment]
I am OK with doing this for SIGTERM and SIGQUIT. I am less convinced about the other signals.

On OS X it's important not to do this for any signal that might cause a core dump, because due to brain damage in OS X, the core dump will include lots of uninitialized but mapped memory and take up 100s of GBs. Every time I accidentally cause a Go program to dump core on OS X without "ulimit -c 0" set, the core dump fills my 500 GB laptop disk.

Perhaps we should leave this for Go 1.7, although the systemd use case suggests that maybe we should do SIGTERM/SIGQUIT/maybe SIGINT for Go 1.6.

@ianlancetaylor, what do you think? You may have all the mechanism in place now.

**Comment by ianlancetaylor** [comment]
This is actually done and committed in https://golang.org/issue/18156.  I couldn't find this issue and I thought it was just discussed in e-mail (sorry).  We now exit with the signal status for SIGHUP, SIGINT, and SIGTERM; these are the signals for which the SigKill flag is set, the same set of signals for which we previously did a silent exit(2).

We don't do it for SIGQUIT, since raising SIGQUIT would cause a core dump; we only want a core dump if GOTRACEBACK=crash.

**Comment by rsc** [comment]
OK. golang.org/cl/18156 fwiw
