### ISSUE TITLE
project: releases are not "GitHub Releases"

### ISSUE THREAD

**Issue by enzochiau** [golang/go#13497]
I can't use GetReleases of "go-github" to get the list of your release.

**Comment by mdempsky** [comment]
Can you be please give a more descriptive explanation of your problem?  E.g., what commands/code are you trying to run?  What errors are you getting?  What behavior do you expect instead, and why do you expect that?

**Comment by enzochiau** [comment]
Sorry about that. I bring up this issue according to [this question and answers] (http://stackoverflow.com/questions/34100738/how-to-get-releases-for-golang-go-with-go-github) on stackoverflow.

**Comment by mdempsky** [comment]
It seems like the root issue here is the Go project is not using GitHub's "Releases" feature.  If you switch to ListTags like the Stack Overflow responder suggests, it appears to correctly list the Go releases.

I'm going to close, because I think this is working as intended at the moment.  If you think the Go project should alter its release workflow to make use of GitHub Releases, I suggest going through the [Go proposal process](https://golang.org/s/proposal-process).
