### ISSUE TITLE
internal/syscall/windows/registry: TestWalkFullRegistry fails

### ISSUE THREAD

**Issue by mattn** [golang/go#13500]
```
c:\dev\go\src\internal\syscall\windows\registry>go test
--- FAIL: TestWalkFullRegistry (10.73s)
        registry_test.go:585: opening sub-keys btmshell of CLASSES_ROOT\VirtualStore\MACHINE\SOFTWARE\Intel\Bluetooth failed: The system cannot find the file specified.
FAIL
exit status 1
FAIL    internal/syscall/windows/registry       10.968s
```
I don't make sure but this seems that this key is guarded on windows.
```c
#include <windows.h>
#include <stdio.h>

int
main(int argc, char* argv[]) {
	HKEY subkey;
	printf("%d\n", RegOpenKeyEx(HKEY_CLASSES_ROOT, "VirtualStore\\MACHINE\\SOFTWARE\\Intel\\Bluetooth\\btmshell", 0, KEY_ALL_ACCESS, &subkey));
	return 0;
}
```
for example this return 2. Eventhough, I run this on administrator's privileges. But return 2.

/cc @alexbrainman

**Comment by rsc** [comment]
@mattn, what version of Windows are you using?

**Comment by mattn** [comment]
Windows10 64bit

On 12/6/15, Russ Cox <notifications@github.com> wrote:
> @mattn, what version of Windows are you using?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/golang/go/issues/13500#issuecomment-162249196


-- 
- Yasuhiro Matsumoto

**Comment by alexbrainman** [comment]
I think this works as expected. Your C program's output is the same as Go - it returns ERROR_FILE_NOT_FOUND.

I don't know why the RegOpenKeyEx fails on your computer. But I have seen all sorts of errors when reading all registry keys of various computers. People run all sorts of programs they download from Internet - buggy and shifty. These programs are free to do whatever they like with your registry - they have all your rights (more often then not administrator rights).

So I do not consider failing TestWalkFullRegistry to be a problem. I have added the test while I was developing package functionality, and left it in because it is helpful sometimes to debug things. But it is only running during "go test -short", so we ignore any registry inconsistencies.

Please, reopen if you disagree.

Alex

**Comment by mattn** [comment]
I do not have a strong opinion. It's a mental issue that all of the test is not passed. Also I am guessing that it is enough that you don't need to enumerate all of the registry.

**Comment by mattn** [comment]
For the memo or knowledge. There are another problem to run this test case on non-clean environment. This is not objection.

### 1. `CLASSES_ROOT\VirtualStore\` require UAC to read

So should be ignored.
```go
diff --git a/src/internal/syscall/windows/registry/registry_test.go b/src/internal/syscall/windows/registry/registry_test.go
index f63248c..564a126 100644
--- a/src/internal/syscall/windows/registry/registry_test.go
+++ b/src/internal/syscall/windows/registry/registry_test.go
@@ -10,6 +10,7 @@ import (
 	"bytes"
 	"crypto/rand"
 	"os"
+	"strings"
 	"syscall"
 	"testing"
 	"unsafe"
@@ -578,7 +579,7 @@ func walkKey(t *testing.T, k registry.Key, kname string) {
 		func() {
 			subk, err := registry.OpenKey(k, name, registry.ENUMERATE_SUB_KEYS|registry.QUERY_VALUE)
 			if err != nil {
-				if err == syscall.ERROR_ACCESS_DENIED {
+				if err == syscall.ERROR_ACCESS_DENIED || strings.HasPrefix(kname, `CLASSES_ROOT\VirtualStore\`) {
 					// ignore error, if we are not allowed to access this key
 					return
 				}
```

### 2. There are some broken registry values.

One of example, `HKEY_CURRENT_USER\Software\PostgreSQL\StackBuilder`

![](http://go-gyazo.appspot.com/7facc4a6600bf298.png)

Those values seems to be stored as wide characters.

![](http://go-gyazo.appspot.com/93c349814e571be6.png)
