### ISSUE TITLE
path/filepath: GlobEscape function

### ISSUE THREAD

**Issue by ElegantMonkey** [golang/go#13516]
Sometimes, when using Glob, valid filepaths are mistakenly understood as a expression (e.g. paths with [] or ?). Python, as of 3.4, has a glob.escape function to avoid that.

**Comment by mvdan** [comment]
The CL above was closed more than a year ago by @rsc. Quoting him:

> * Glob is built on top of Match; this is really an escaper for Match.
> * It's unclear we want to add new API here.
> * There is no escaping at all on Windows, making this even more dubious.

I'm going to close this for now, as I understand that the rejection was meant for the new API proposal rather than for the patch itself.

If you would like to propose this addition again (or a similar one), please use the proposal process: https://github.com/golang/proposal
