### ISSUE TITLE
spec: Variadic receiver types

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#13595]
This is a defect/deficiency in the specification.
The following changeset https://github.com/golang/go/commit/187ee2cf2bfd221d8c03daf69a08adb9ede44c84
defers parsing a `Receiver` to parsing `Parameters`, which *syntactically* allows a receiver to be variadic. Yet the additional receiver-related rules do not explicitly state that a receiver cannot be variadic. 

I propose the grammar production for `Receiver` to be changed to:
```
Receiver  = "(" [identifier] Type [","] ")"
```
which still allows for a parenthesized type and an optional trailing comma and at the same time more clearly conveys the intent that the receiver is exactly one.
If the above suggestion is accepted, no code changes whatsoever would be needed and the specification text can be reverted back to 
```html
The receiver type must be of the form <code>T</code> or <code>*T</code> where
<code>T</code> is a type name. The type denoted by <code>T</code> is called
the receiver <i>base type</i>; it must not be a pointer or interface type and
it must be declared in the same package as the method.
```

**Comment by griesemer** [comment]
The point of that change was to highlight the fact that the receiver section is no different from other parameter sections and that the receiver is indeed very much a parameter.

The simpler change would be to verbally state that that receiver cannot be variadic. But note that in the explanations for parameters it is very clearly stated that only the last parameter in a function (incl. methods) can be variadic, so this may not even be necessary. Note also that the grammar is not always expressing the accepted language exactly, for simplicity of exposure. Sometimes it's just easier to refer to an already known concept (parameters) and explain constraints verbally.

**Comment by griesemer** [comment]
I've looked at this in a bit more detail and played with various rewordings, incl. your proposal. I sent out a CL to clarify the wording instead of changing syntax.

(Specifically, adding the explicit syntax for receivers brings undue attention to the optional comma, which we want to permit for regularity and simpler implementation, but would likely raise question marks for a more novice reader.)

I am very sympathetic to the idea that the formal grammar in the spec should be exactly the grammar that is accepted by a compiler. However, in many cases that would make the grammar much more unwieldy. Keep in mind that the spec is meant for human consumption; i.e., there is a delicate balance between formalism and readability. Another aspect is the implementation: As is, it is clear that a compiler can simply re-use all the work that went into parameter parsing, followed by a few semantic checks.
