### ISSUE TITLE
How can I empty input stream? The fmt.Scanf in a main cannot use more than 2 times, the second will appear to skip a need for input.

### ISSUE THREAD

**Issue by CodyGuo** [golang/go#13607]
How can I empty input stream?

package main

import (
	"fmt"
)

func main() {
	var a int
	var f float32
	var str string

	fmt.Print("Please input : ")
	fmt.Scanf("%d %f %s", &a, &f, &str)
	fmt.Println("Output: ", a, f, str)

	fmt.Println("----------------------------")

	var sIP, sMac string
	fmt.Print("Please input: ")
	fmt.Scanf("%s %s", &sIP, &sMac)

	fmt.Println("Output: ", sIP, sMac)
}

**Comment by mdempsky** [comment]
Please see https://github.com/golang/go/wiki/Questions

**Comment by CodyGuo** [comment]
I'm sorry, I don't have access to mailing lists and BBS address.

**Comment by ianlancetaylor** [comment]
The mailing list and forums are accessible through a web browser, including posting new issues.  I can't think of a reason why you would be able to access Github issues but not access them.

To empty the input stream you need to read from it until the end.  Although your problem is not clear to me, It's likely that you should be using something like bufio.Readstring and fmt.Sscanf rather than using fmt.Scanf directly.
