### ISSUE TITLE
net/http/httputil: ReverseProxy uses CloseNotifier before body consumption

### ISSUE THREAD

**Issue by orivej** [golang/go#13666]
Since https://github.com/golang/go/commit/99fb19194c03c618c0d8faa87b91ba419ae28ee3, one of Consul tests does not pass because `CloseNotify` for `clientGone` gets triggered in `httputil.ReverseProxy.ServeHTTP` when the client in fact is not gone.

How to reproduce:
```
go get -u -v github.com/hashicorp/consul
go test github.com/hashicorp/consul/api -run TestLock_MonitorRetry
```
The test should not fail, but does since aforementioned commit. If I comment out `requestCanceler.CancelRequest(outreq)` in `net/http/httputil/reverseproxy.go`, it passes again.

Downstream issue: https://github.com/hashicorp/consul/issues/1524

**Comment by bradfitz** [comment]
Are you using HTTP/1.1 pipelining?

**Comment by bradfitz** [comment]
Nevermind, I see now that httputil.ReverseProxy doesn't obey the new tightened rules for CloseNotifier.

I can fix.

**Comment by pwaller** [comment]
@bradfitz I can't see mention of the tightened rules [in the release notes](https://tip.golang.org/doc/go1.6) or on the mailing list. I guess you're referring to [this CL](https://go-review.googlesource.com/#/c/17750/) and this [new rule](https://tip.golang.org/pkg/net/http/#CloseNotifier)?:

> CloseNotify is undefined before Request.Body has been fully read.

For me, I get the `RequestProxy` giving `http: proxy error: net/http: request canceled` whenever there is a HTTP post; which I assume is this issue.

I guess the fix is straightforward and [the call to `CloseNotify()` just needs hoisting inside RunOnFirstRead](https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L153) ?

**Comment by starchou** [comment]
@pwaller I have the same issue . and I use POST,PUT,DELETE method ,they all output error :`http: proxy error: net/http: request canceled` .
@bradfitz can you fix it ? 
3q

**Comment by starchou** [comment]
@pwaller I copy it and move code like that: https://gist.github.com/starchou/3fa257ea20fdf6babeab
it's work now.

**Comment by orivej** [comment]
This was discussed a little on the list: http://thread.gmane.org/gmane.comp.lang.go.general/170241
