### ISSUE TITLE
expose crypto/tls.alert type in API

### ISSUE THREAD

**Issue by jmhodges** [golang/go#13747]
In order to provide nicer feedback to users, the Let's Encrypt boulder project attempts to determine if a TLS error was the cause for the HTTP domain validation failure. However, it has to do it in a hack-y way because the `crypto/tls.alert` error type is not exposed in the API.

Currently, that hack-y way is:

    } else if fmt.Sprintf("%T", netErr.Err) == "tls.alert" {

as seen in the [validation authority code](https://github.com/letsencrypt/boulder/blob/e36895c9c5f08ce8546ab3656345f02b92e7edf8/va/validation-authority.go#L408).

**Comment by bradfitz** [comment]
You did state the problem but you jumped to the solution pretty quickly (exporting a type). Let's try to understand the problem more and think about all possible solutions before doing anything here.

**Comment by jmhodges** [comment]
Open to suggestions!

**Comment by bradfitz** [comment]
You only call `parseHTTPConnError` twice in the boulder codebase.

1) Your first use is after a call to *http.Client.Do, where you create the http.Client on the line immediately before the call, and the http.Transport right above it. But http.Transport has a `DialTLS` hook you can use. Implement that hook (with a normal tcp.Dial followed by a tls.Conn+tls.Handshake (without VerifyHostname) and return any specific error value you want for TLS errors.

2) Your second call is after tls.DialWithDialer. But you don't need to do that all in one step. Dial first with your Dialer, and then give the connection to the crypto/tls package after you have it (with tls.Conn+tls.Handshake again), and then you know which step failed.

Both of your problems are because you call some convenience method that does N things and then try to infer from the error value which step of N failed, instead of just doing N things in serial.

Yes, it's possible we could make the error values from those convenience methods better typed, but it's probably not worth the API pollution & mental overhead for readers new to the packages.
