### ISSUE TITLE
os: File.Readdir can return more than n

### ISSUE THREAD

**Issue by dsoprea** [golang/go#13778]
[`File.Readdir`](https://golang.org/pkg/os/#File.Readdir) takes an `n` parameter that specifies a maximum count to return ("If n > 0, Readdir returns at most n FileInfo structures."). However, I'm seeing more than `n` being returned when `n` is both 3 and 5 (and likely other values as well).

Channelizing the `File.Readdir` call:

```go
func (self *Path) List(path string) (<-chan *os.FileInfo, <-chan bool, error) {
    entriesChannel := make(chan *os.FileInfo)
    doneChannel := make(chan bool)

    go func() {
        f, err := os.Open(path)
        if err != nil {
            panic(err)
        }

        defer f.Close()

        for {
            fmt.Printf("Batch!\n")

            entries, err := f.Readdir(PathListBatchSize)
            if err == io.EOF {
                break
            } else if err != nil {
                panic(err)
            }

            for i := range entries {
                entriesChannel <- &entries[i]
            }
        }

        doneChannel <- true
    }()

    return entriesChannel, doneChannel, nil
}
```

Using it:

```go
func main() {
    p := pfinternal.NewPath()
    entriesChannel, doneChannel, err := p.List("/tmp/test_root")
    if err != nil {
        panic(err)
    }

    done := false
    for done == false {
        select {
            case entry := <-entriesChannel:
                fmt.Printf("ENTRY: %s\n", (*entry).Name())

            case done = <-doneChannel:
                break
        }
    }
}
```

With n = 3:

```go
$ ./pfmain 
Batch!
ENTRY: a
ENTRY: b
Batch!
ENTRY: c
ENTRY: d
ENTRY: e
ENTRY: f
Batch!
ENTRY: g
ENTRY: h
Batch!
ENTRY: i
Batch!
ENTRY: j
```

With n = 5:

```go
$ ./pfmain 
Batch!
ENTRY: a
ENTRY: b
ENTRY: c
ENTRY: d
Batch!
ENTRY: e
ENTRY: f
ENTRY: g
ENTRY: h
ENTRY: i
ENTRY: j
Batch!
```

**Comment by ianlancetaylor** [comment]
Your program has a race condition.  There is no necessary connection between the print of "Batch!" and the print of the ENTRY lines, so there is no required order.  It would be easy for you to prove your case: check the len of the value returned by Readdir directly, rather than doing it indirectly by looking at print statements.

I'm going to close this.  If you are sure this is a bug, please provide a non-racy test case.  Please also provide a complete standalone program, rather than portions of a larger program.  Thanks.
