### ISSUE TITLE
go/build: reverse the sense of AllowVendor

### ISSUE THREAD

**Issue by aclements** [golang/go#13772]
We recently added an AllowVendor ImportMode flag to go/build. This requires go/build API users to opt-in to vendoring. Given that vendoring will be enabled by default in Go 1.6, it seems like asking for subtle bugs in users of go/build if this isn't also the default behavior of go/build.

@rsc @griesemer

**Comment by rsc** [comment]
My original rationale was that there might be other uses of the go/build package, in other build systems with different file tree layouts, and that silently breaking them would be bad. But on second thought that's not a concern, because the code here is looking through GOPATH and GOROOT and so is already very tied to the go command's file tree. Other build systems with different file trees wouldn't be using this code.

**Comment by rsc** [comment]
(So I agree. I'll prepare a CL.)
