### ISSUE TITLE
runtime: scalability problem with allocation

### ISSUE THREAD

**Issue by totemtang** [golang/go#13805]
I’m working on multi-core systems with golang. I find that there exist a scalability problem when interface type transformation involved.

The test program consists of several go routines accessing its own private data (i.e. one golang map), which means each go routine would never exchange any data with others. The number of go routines is the same as the number of cores used. Ideally, this should be fully scalable, that is, with more cores added, the throughput of each go routine would not change.

This program tests two cases of read and write data in golang maps. Each case is tested with and without interface type transformation.

I have made experiments on one machine with 4 NUMA nodes. Each NUMA node comprises 8 physical cores and 24MB shared L3 cache. Each physical core has 32KB L1 cache and 256KB L2 cache. My experiments only include 100 keys for each map to avoid the shared L3 cache problem. I report the operations executed of each core per second. One operation could be reading or writing data in the private golang map. I test my program with 1 and 32 cores. Here are the results:

               | 1 core | 32 cores
------------ | ------------- | -------------
interface-read	 | 555285 | 105001
interface-write | 526274 | 99069
no-interface-read | 983947 | 1004945
no-interface-write | 977462 | 1006021

It is found that the pre-core throughput with interface transformation is much slower under 32 cores (i.e. less than 20% of 1 core test). However, the pre-core throughput without interface transformation has the similar performance under both 1 core and 32 cores tests.

The source code of my test program is as follows:

```
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"runtime"
	"sync"
	"time"
)

var nsecs = flag.Int("nsecs", 5, "number of seconds to run")
var ncores = flag.Int("ncores", 1, "number of cores to scale")
var nkeys = flag.Int("nkeys", 100, "number of keys per worker")
var read = flag.Bool("read", true, "true for read; otherwise, write")
var iface = flag.Bool("i", true, "use interface or not")

type Value interface{}

type Record struct {
	intVal int
}

func (r *Record) UpdateValue(val Value) {
	r.intVal = val.(int)
}

func (r *Record) GetValue() Value {
	return r.intVal
}

func (r *Record) UpdateInt(intVal int) {
	r.intVal = intVal
}

func (r *Record) GetInt() int {
	return r.intVal
}

func main() {
	flag.Parse()

	// set max cores used
	runtime.GOMAXPROCS(*ncores)
	workers := *ncores

	var wg sync.WaitGroup
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func(n int) {
			store := make(map[int]*Record)
			for i := 0; i < *nkeys; i++ {
				store[i] = &Record{
					intVal: i,
				}
			}
			var txn int
			var val Value = nil
			var intVal int
			rnd := rand.New(rand.NewSource(1))
			end_time := time.Now().Add(time.Duration(*nsecs) * time.Second)
			for {
				tm := time.Now()
				if !end_time.After(tm) {
					break
				}
				for j := 0; j < 10; j++ {
					k := rnd.Intn(*nkeys)
					r := store[k]
					if *iface {
						if *read {
							val = r.GetValue()
						} else {
							r.UpdateValue(0)
						}
					} else {
						if *read {
							intVal = r.GetInt()
						} else {
							r.UpdateInt(0)
						}
					}
				}
				txn++
			}
			if val != nil {
				intVal = val.(int)
			}
			intVal++
			fmt.Printf("Worker %d issues %v transactions\n", n, txn)
			wg.Done()
		}(i)
	}
	wg.Wait()
}
```

**Comment by davecheney** [comment]
Could you rewrite this as a standard go benchmark ?

**Comment by randall77** [comment]
There is an allocation involved in the assignment
   val = r.GetValue()
(building an interface{} from a non-pointer).  I suspect it is the garbage collector that isn't scaling.
@aclements @RLH

**Comment by totemtang** [comment]
What about the statement
```
r.UpdateValue(0)
```
I think there is no allocation here
@randall77

**Comment by randall77** [comment]
No, there is.  Converting int(0) to an interface{} allocates.

It doesn't have to.  There are optimizations that could get rid of this allocation (and the allocation on the read).  But the current Go still allocates.

**Comment by totemtang** [comment]
Here is my go benchmark

```
package main

import (
	"math/rand"
	"testing"
)

type Value interface{}

type Record struct {
	intVal int
}

func (r *Record) UpdateValue(val Value) {
	r.intVal = val.(int)
}

func (r *Record) GetValue() Value {
	return r.intVal
}

func (r *Record) UpdateInt(intVal int) {
	r.intVal = intVal
}

func (r *Record) GetInt() int {
	return r.intVal
}

func BenchmarkIfaceRead(b *testing.B) {
	nkeys := 100
	b.RunParallel(func(pb *testing.PB) {
		store := make(map[int]*Record)
		rnd := rand.New(rand.NewSource(1))
		for i := 0; i < nkeys; i++ {
			store[i] = &Record{
				intVal: i,
			}
		}
		var val Value = nil
		var intVal int
		for pb.Next() {
			k := rnd.Intn(nkeys)
			r := store[k]
			val = r.GetValue()
		}
		if val != nil {
			intVal = val.(int)
		}
		intVal++
	})
}

func BenchmarkIfaceWrite(b *testing.B) {
	nkeys := 100
	b.RunParallel(func(pb *testing.PB) {
		store := make(map[int]*Record)
		rnd := rand.New(rand.NewSource(1))
		for i := 0; i < nkeys; i++ {
			store[i] = &Record{
				intVal: i,
			}
		}
		for pb.Next() {
			k := rnd.Intn(nkeys)
			r := store[k]
			r.UpdateValue(0)
		}
	})
}

func BenchmarkNoIfaceRead(b *testing.B) {
	nkeys := 100
	b.RunParallel(func(pb *testing.PB) {
		store := make(map[int]*Record)
		rnd := rand.New(rand.NewSource(1))
		for i := 0; i < nkeys; i++ {
			store[i] = &Record{
				intVal: i,
			}
		}
		var val Value = nil
		var intVal int
		for pb.Next() {
			k := rnd.Intn(nkeys)
			r := store[k]
			intVal = r.GetInt()
		}
		if val != nil {
			intVal = val.(int)
		}
		intVal++
	})
}

func BenchmarkNoIfaceWrite(b *testing.B) {
	nkeys := 100
	b.RunParallel(func(pb *testing.PB) {
		store := make(map[int]*Record)
		rnd := rand.New(rand.NewSource(1))
		for i := 0; i < nkeys; i++ {
			store[i] = &Record{
				intVal: i,
			}
		}
		for pb.Next() {
			k := rnd.Intn(nkeys)
			r := store[k]
			r.UpdateInt(0)
		}
	})
}
```

I try the command "go test -bench=. -cpu=1,32". The result is:
PASS
BenchmarkIfaceRead      	10000000	       177 ns/op
BenchmarkIfaceRead-32   	50000000	        31.6 ns/op
BenchmarkIfaceWrite     	        10000000	       189 ns/op
BenchmarkIfaceWrite-32  	100000000	        30.0 ns/op
BenchmarkNoIfaceRead    	20000000	        96.7 ns/op
BenchmarkNoIfaceRead-32 	500000000	         3.23 ns/op
BenchmarkNoIfaceWrite   	20000000	        97.3 ns/op
BenchmarkNoIfaceWrite-32	500000000	         3.13 ns/op
ok  	test/scale-test	16.772s

**Comment by totemtang** [comment]
@randall77 
If I change the implementation of
```
func (r *Record) UpdateValue(val Value) {
    r.intVal = val.(int)
}
```
into
```
func (r *Record) UpdateValue(val Value) {
        intVal := val.(int)
        r.intVal = intVal
}
```
It scales well. When I tried the command "go test -bench=. -cpu=1,32" again, I see
BenchmarkIfaceRead      	10000000	       178 ns/op
BenchmarkIfaceRead-32   	50000000	        30.1 ns/op
BenchmarkIfaceWrite     	        10000000	       128 ns/op
BenchmarkIfaceWrite-32  	300000000	         4.12 ns/op
BenchmarkNoIfaceRead    	20000000	        96.9 ns/op
BenchmarkNoIfaceRead-32 	500000000	         3.04 ns/op
BenchmarkNoIfaceWrite   	20000000	        97.2 ns/op
BenchmarkNoIfaceWrite-32	500000000	         3.12 ns/op

which shows that UpdateValue (i.e. BenchmarkIfaceWrite) scales well.

**Comment by nuss-justin** [comment]
@totemtang The difference between these two versions of UpdateValue is that the second version doesn't allocate, while the first does one allocation. (you can use the '-benchmem' flag to see allocations and use '-memprofile <file>' to create a profile of your allocations. [see here for more information](http://blog.golang.org/profiling-go-programs). you can also use '-gcflags -S' to see the assembly generated by the compiler)

**Comment by aclements** [comment]
@totemtang, have you tried a differential profile to see where the extra time is going? Also, do you know, based on the CPU time versus the wall-clock time, whether the time is going to computation (e.g., spinning) or idle (blocking)?

**Comment by randall77** [comment]
It looks like in your latter case the compiler allocates the interface on the stack.  In the first case it doesn't.  I'm not really sure why that is the case.  Both instances get inlined.
I'll open a second bug for that problem.  Let's keep this bug about scaling.

**Comment by totemtang** [comment]
@aclements 

I follow the comment from @nuss-justin and see that

```
func (r *Record) UpdateValue(val Value) {
        intVal := val.(int)
        r.intVal = intVal
}
```

does not have any memory allocation while 
```
func (r *Record) UpdateValue(val Value) {
    r.intVal = val.(int)
}
```
has one allocation per operation. Therefore, I think the extra time is spent on memory allocation.

I do not understand why there is an extra memory allocation since both versions do the same task. I think it is related to how golang itself compiles the two statements.

**Comment by aclements** [comment]
@totemtang, sorry, that's not what I meant by a differential profile. That indicates why one version is slower than another, but not why the version that doesn't scale slows down with more CPUs. I meant to CPU profile the one that doesn't scale at 1 CPU and 32 CPUs and compare those profiles.

**Comment by aclements** [comment]
> Therefore, I think the extra time is spent on memory allocation.

That may be true, but "memory allocation" is a complex operation with many secondary effects (e.g., the actual allocation could be perfectly scalable, but the increased memory pressure makes other parts of the runtime not scale). That's why I was hoping you could perform a differential profile to compare where the time is going at a small number of cores with where the time is going with a large number of cores. If we're spending a much larger fraction of the time in some code at a large number of cores, we'll know that's the culprit and we may be able to fix it.

> I do not understand why there is an extra memory allocation since both versions do the same task. I think it is related to how golang itself compiles the two statements.

Yes; this is just a flaw in how the compiler sees these two programs. To you and me they're obviously equivalent, but right now the compiler can't see that. @randall77 opened #13807 to investigate this specific issue.

**Comment by totemtang** [comment]
@aclements Thanks for your reply.

I have profiled the time consumption of BenchmarkIfaceWrite under 1 Core and 32 Cores.

![1-core](https://cloud.githubusercontent.com/assets/4866453/12383641/f8bc0b32-bd6d-11e5-9ed8-ededc3288536.png)
![32-cores](https://cloud.githubusercontent.com/assets/4866453/12383644/fed24658-bd6d-11e5-854d-0f675935f6e9.png)

The result of 1 Core (i.e. the first figure) show that memory allocation, which I guess is the "runtime.newObject", occupies about 31% of the total time, while in 32 Core benchmark (i.e. the second figure) memory allocation occupies about 16.7%  of the total time. The reason for this decrease is that 25.9% time is spent on "runtime.morestack", which does not appear in 1 Core benchmark.

I also profiled the time consumption of BenchmarkNoIfaceWrite under 32 Cores, which does not involve memory allocation. I see "runtime.newObject" and "runtime.morestack" do not appear also.
![32-cores-nomalloc](https://cloud.githubusercontent.com/assets/4866453/12383643/fec2cdb8-bd6d-11e5-83c4-c4fe7de37499.png)

I hope this could help you improve Golang. In fact, the advice from the above comments help me a lot with my project.

**Comment by tshprecher** [comment]
I looked into this and believe it has to do with the way values are escaped during assignments where the source is a dottype expression. Consider the following source:

https://gist.github.com/tshprecher/208b160a6dd9732d5510

Running `go tool compile -m` on the file returns the following:

> set_interface.go:14: can inline setOneLine
set_interface.go:18: can inline setTwoLines
set_interface.go:59: inlining call to setOneLine
set_interface.go:60: inlining call to setTwoLines
set_interface.go:14: leaking param: v
set_interface.go:14: setOneLine p does not escape
set_interface.go:18: setTwoLines p does not escape
set_interface.go:18: setTwoLines v does not escape
set_interface.go:23: leaking param: v
set_interface.go:23: setOneLineNoInline p does not escape
set_interface.go:34: setTwoLinesNoInline p does not escape
set_interface.go:34: setTwoLinesNoInline v does not escape
set_interface.go:51: err escapes to heap
set_interface.go:53: f escapes to heap
set_interface.go:59: 1 escapes to heap
set_interface.go:61: 3 escapes to heap
set_interface.go:51: main ... argument does not escape
set_interface.go:59: main &i does not escape
set_interface.go:60: main &i does not escape
set_interface.go:60: main 2 does not escape
set_interface.go:61: main &i does not escape
set_interface.go:62: main &i does not escape
set_interface.go:62: main 4 does not escape

Notice on lines 59 and 61 the constant values 1 and 3 escape to the heap for the calls that set on one line. It turns out inlining is not a factor. The parameter 'v' leaks.

I created the following patch with test: https://go-review.googlesource.com/#/c/19489/

Running `go tool compile -m` with the patch:

> set_interface.go:14: can inline setOneLine
set_interface.go:18: can inline setTwoLines
set_interface.go:59: inlining call to setOneLine
set_interface.go:60: inlining call to setTwoLines
set_interface.go:14: setOneLine p does not escape
set_interface.go:14: setOneLine v does not escape
set_interface.go:18: setTwoLines p does not escape
set_interface.go:18: setTwoLines v does not escape
set_interface.go:23: setOneLineNoInline p does not escape
set_interface.go:23: setOneLineNoInline v does not escape
set_interface.go:34: setTwoLinesNoInline p does not escape
set_interface.go:34: setTwoLinesNoInline v does not escape
set_interface.go:51: err escapes to heap
set_interface.go:53: f escapes to heap
set_interface.go:51: main ... argument does not escape
set_interface.go:59: main &i does not escape
set_interface.go:59: main 1 does not escape
set_interface.go:60: main &i does not escape
set_interface.go:60: main 2 does not escape
set_interface.go:61: main &i does not escape
set_interface.go:61: main 3 does not escape
set_interface.go:62: main &i does not escape
set_interface.go:62: main 4 does not escape

The parameter 'v' no longer leaks and the literal values 1 and 3 do not escape to the heap.
