### ISSUE TITLE
doc: write gomote wiki docs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13834]
Document how to use gomote for all common tasks for all major OS types.

/cc @randall77

**Comment by randall77** [comment]
Some things that came up from a recent gomote session:

- Make sure GOROOT is set on your local machine before doing "gomote push"
- build: gomote run <instance> go/src/make.bat
- test: gomote run <instance> go/bin/go test <pkg>
- cd: any way to change directories?
- set an evironment variable before running a command? (particularly, windows)  Also querying an environment variable.
- on my local machine, "go version" returns "go version devel +a4650a2 ...".  On a gomote instance, it returns "go version devel gomote.XXXXX ...".  Why isn't the commit hash in there?

**Comment by josharian** [comment]
Other notes:

* Start by just running `gomote` and explore a bit.
* It'd be useful to be able to set GOPATH and PATH, maybe in a sticky way. That'd (a) make it possible to go get things like the stress util and (b) make lots more of the stdlib tests pass -- they expect to be able to find the go command.
* The million "Remote doesn't have" log lines when initially running `push` are overwhelming.
* It'd be useful to have a way to set the user (in a config?) for folks whose whoami doesn't match their gomote username.

For the sake of others looking here for docs, here's how I did some stress testing:

```
gomote -user josharian create linux-amd64-sid
gomote -user josharian push user-josharian-linux-amd64-sid-0
gomote -user josharian run user-josharian-linux-amd64-sid-0 go/src/make.bash
for f in `seq 1000`; do gomote -user josharian run user-josharian-linux-amd64-sid-0 go/bin/go test -short net/http crypto/x509; done
```

(One could use the `-count` flag to go test to loop instead of a bash loop, but that wasn't as effective at reproducing for my particular bug.)

**Comment by bradfitz** [comment]
Other notes, running cmd/go tests on Windows:

```
gomote run -path '$PATH,$WORKDIR/go/bin' -e 'GOROOT=c:\workdir\go' user-bradfitz-windows-amd64-gce-0 go/bin/go.exe  test cmd/go -short
```

**Comment by josharian** [comment]
`gomote push` should not push files that are .gitignored. This will prevent giant uploads from uploading local object files, etc.

**Comment by josharian** [comment]
Wiki: https://github.com/golang/go/wiki/Gomote
