### ISSUE TITLE
cmd/objdump: should be able to disassemble Go .o files

### ISSUE THREAD

**Issue by randall77** [golang/go#13862]
$go tool compile fib.go
$go tool objdump fib.o
objdump: disassemble fib.o: pcln not available in go object file

It would be nice if this worked.  The pcln info is in there somewhere.
"go tool nm fib.o" works.

**Comment by randall77** [comment]
@griesemer

**Comment by cmarcelo** [comment]
Inspected the code a bit. The error comes from `cmd/internal/objfile/goobj.go`

```
// pcln does not make sense for Go object files, because each
// symbol has its own individual pcln table, so there is no global
// space of addresses to map.
func (f *goobjFile) pcln() (textStart uint64, symtab, pclntab []byte, err error) {
	return 0, nil, nil, fmt.Errorf("pcln not available in go object file")
}

// text does not make sense for Go object files, because
// each function has a separate section.
func (f *goobjFile) text() (textStart uint64, text []byte, err error) {
	return 0, nil, fmt.Errorf("text not available in go object file")
}
```

These are used (via rawFile interface) in Disasm(). The common disassemble code expects a single table and a single slice of text, and operate on that. But these are not directly available in goobj files.

What would be the direction to go here: change Disasm side to be able to consume data in a more flexible way, or collect and construct data in goobj.go to fulfill the existing interfaces (e.g. build a gosym.Table)? Or neither?

/cc @rsc (since he reworked a bit Disasm back then, might have opinion)

**Comment by jacobsa** [comment]
I've landed on this issue because I'm trying to do the same thing (disassemble a `.a` file in this case). Is there a workaround that would let me do so in another way?

**Comment by ianlancetaylor** [comment]
@jacobsa There is no direct workaround as far as I know.  One approach is to use the compiler's -S option.  Or, of course, link the program and use the system objdump tool.

**Comment by jacobsa** [comment]
Thanks. I was looking for pre-link output, so `-S` did it for me.

**Comment by randall77** [comment]
See https://go-review.googlesource.com/c/22685/ for a quick, bad pass at this.
