### ISSUE TITLE
tour: This does not adequately tell you the difference between how to declare a slice vs an array

### ISSUE THREAD

**Issue by traceypowers** [golang/go#13883]
Context: http://tour.golang.org/moretypes/7

When reading the tutorial page on arrays, and then on slices, it is NOT obvious how to declare one vs the other.

To declare an ARRAY, you need to provide a length
To declare a SLICE, you may not provide a length, but you must provide initialized values that end up defining the length.

I had to read this entire article:
http://openmymind.net/The-Minimum-You-Need-To-Know-About-Arrays-And-Slices-In-Go/

to figure out the subtleties of declaring a slice vs declaring an array.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
@traceypowers would it have been easier to understand if the array slide had been more similar to the slice slide? Perhaps instead of:

```
var a [2]string
a[0] = "Hello"
a[1] = "World"
```

The array could be declared like so:

```
a := [2]string{"Hello", "World"}
```

This would make it symmetrical with the declaration of the slice in the next slide:

```
s := []int{2, 3, 5, 7, 11, 13}
```

This doesn't cover the subtleties of arrays vs. slices, but the tour isn't really the place for subtleties, I think.

We could also link to the blog post about slices on golang.org: http://blog.golang.org/go-slices-usage-and-internals
