### ISSUE TITLE
Slow performance problems than JS

### ISSUE THREAD

**Issue by woniu369** [golang/go#13915]
win7 64
go1.6beta1

go
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	t1 := time.Now()
	count, a, b := 0, 1, 3
	for 2*a-b < 0 {
		for i := 12000; i > 0; i-- {
			if (a*i+1)%b == 0 {
				count++
				a, b = (a*i+1)/b, i
				break
			}
		}
	}
	t2 := time.Since(t1).Seconds() / int64(time.Millisecond)
	fmt.Println("Time: ", t2, "ms") //236362 ms
	fmt.Println(count-1)
}
```
js
```js
    console.time('TIME');
    var count = 0;
    var a = 1;
    var b = 3;

    while (2 * a - b < 0) {
        for (i = 12000; i > 0; i--) {
            if ((a * i + 1) % b == 0) {
                count++;
                a = (a * i + 1) / b;
                b = i;
                break;
            }
        }
    }
    console.timeEnd('TIME'); //127927.607ms
    console.log(count-1);
```

http://www.oschina.net/code/snippet_95905_53494

**Comment by woniu369** [comment]
cup:i7 3770k

**Comment by ianlancetaylor** [comment]
The line `t2 := time.Since(t1).Seconds() / int64(time.Millisecond)` doesn't compile and doesn't make sense.

In any case, I don't think there is anything clear for us to do here.  Javascript and Go are very different languages that work in very different ways.  If you can identify specific reasons why Go is slower, then perhaps we can improve it.

This is a case where gccgo is likely to generate faster code than the gc compiler.  On my laptop the code generated by gccgo -O2 is 6% faster.  Both print 7295372 at the end.  Of course, that is much less than the difference you report between Go and Javascript.  I admit to being puzzled by how Javascript can be so much faster.  It would be interesting to find out what the Javascript JIT turns the inner loop into.

However, I'm going to close this issue as there is nothing useful we can do to fix it.

**Comment by kostya-sh** [comment]
Javascript integer type is 4 bytes (int32 in Go). If you change your Go program to use int32 it will be much faster (1m46s vs 4m55s on my PC). int is int64 on 64 bit processor and int64 division is slower than int32 division.

**Comment by zh-lab** [comment]
@kostya-sh  int64 division is slower than int32 division.Thanks! :satisfied:
