### ISSUE TITLE
x/mobile/example/audio compilation error on Linux

### ISSUE THREAD

**Issue by emshack** [golang/go#13927]
When I try to compile the audio example app on my Linux desktop, I get the following error:
 ```
$ go build golang.org/x/mobile/example/audio
# golang.org/x/mobile/exp/audio/al
src/golang.org/x/mobile/exp/audio/al/al_notandroid.go:22:19: fatal error: AL/al.h: No such file or directory
 #include <AL/al.h>
                   ^
compilation terminated.
```
I tried removing the gomobile binary and reinstalling, but the issue remains.

go version: go1.5.2 linux/amd64
OS: Ubuntu 14.04 trusty (x86-64)

**Comment by rjammala** [comment]
According to the godoc page you need to install the following package: libopenal-dev

https://godoc.org/golang.org/x/mobile/exp/audio/al
In order to use this package on Linux desktop distros, you will need OpenAL library as an external dependency. On Ubuntu 14.04 'Trusty', you may have to install this library by running the command below.

sudo apt-get install libopenal-dev

**Comment by rakyll** [comment]
@emshack, please update the issue if the suggestion above doesn't work for you.
