### ISSUE TITLE
proposal/RFC: continue for switch statements

### ISSUE THREAD

**Issue by gabeio** [golang/go#13935]
`continue` within a `switch` statement would continue checking cases below for their validity.

This would be in contrast to `fallthrough` which just executes all the other branches below, this only executes VALID branches below.

an example of a fizzbuzz using the continue within switch:
```go
package main

func main(){
	for i := 1; i<101; i++ {
		fizzbuzz(i)
	}
}

func fizzbuzz(num int) {
	// when num=15 all branches would be hit.
	fizzSwitch: switch {
	case true:
		print(num)
		continue fizzSwitch // continues to check other cases for true also
	case num%3==0:
		print("fizz")
		continue fizzSwitch // continues to check other cases for true also
	case num%5==0:
		print("buzz")
		continue fizzSwitch // continues to check other cases for true also
	case true:
		print(num)
	}
}
```

**Comment by ianlancetaylor** [comment]
This change would break existing programs, so it's hard to see it being adopted as is.

**Comment by minux** [comment]
If want to do this, why not use the more general if/else statement? Nothing
is gained by using switch here.

**Comment by james-lawrence** [comment]
wouldn't this lead to irritating bugs if you had a sequences of cases where they'd evaluate to true, false, true? i.e.) someone may expect it to hit the two cases that match but the second (false) case would short circuit no?

**Comment by griesemer** [comment]
If I understand this proposal correctly, what you are suggesting is that
```
    fizzSwitch: switch {
    case true:
        print(num)
    case num%3==0:
        print("fizz")
        continue fizzSwitch // continues to check other cases for true also
    case num%5==0:
        print("buzz")
        continue fizzSwitch // continues to check other cases for true also
    case true:
        print(num)
    }
```
is executed as
```
    if true {
        print(num)
    }
    if num%3==0 {
        print("fizz")
    }
    if num%5==0 {
        print("buzz")
    }
    if true {
        print(num)
    }
```
(I am assuming that there's a continue missing in the first case because otherwise this example makes no sense: The first case always hits, and w/o a continue it doesn't matter that the other cases have one since they are never executed.)

In this special case it would even simplify to:
```
    print(num)
    if num%3==0 {
        print("fizz")
    }
    if num%5==0 {
        print("buzz")
    }
    print(num)
```
which is much shorter and cleaner than the switch.

There's already quite a bit of overlap between switch statements and if-statements - mostly for historical reasons and notational convenience. This would increase this overlap and make it more difficult to decide what construct to use. It also doesn't seem to make the code shorter or clearer.

I see no benefit in this construct and I am against this proposal, Go 2.0 or not.

**Comment by gabeio** [comment]
> (I am assuming that there's a continue missing in the first case because otherwise this example makes no sense: The first case always hits, and w/o a continue it doesn't matter that the other cases have one since they are never executed.)

Yes whoops, added.

> There's already quite a bit of overlap between switch statements and if-statements - mostly for historical reasons and notational convenience. This would increase this overlap and make it more difficult to decide what construct to use. It also doesn't seem to make the code shorter or clearer.

That is what the proposal/RFC is for I wanted to see other's points of view and know whether anyone might benefit from it. Though in other languages switches are supposed to perform better than if statements, though in this language they really do seem identical. I just don't see why there is a `fallthrough` which executes everything below *without checking validity* when there isn't some way to continue and only execute other things that are valid.

**Comment by ianlancetaylor** [comment]
Some languages do have breaking changes between versions.  Go does not.  See https://golang.org/doc/go1compat.html .  While it's possible that there will some day be a Go 2, and that Go 2 may have some breaking changes, even then we will want to minimize them.

The `fallthrough` keyword exists mainly because that's how C/C++ switch statements work, and because everybody thinks Duff's Device is cool.  In retrospect we could have dropped `fallthrough` from the language and all would have been well.

**Comment by griesemer** [comment]
@gabeio Regarding "Though in other languages switches are supposed to perform better than if statements, though in this language they really do seem identical": This is really more a statement about the compilers than the languages. In Go, if the switch contains only constant values in the cases (like in a C switch), there's no reason why the switch cannot be compiled (and perhaps optimized) just like a C switch. Vice versa, a sequence of if-else-if statements where each condition is of the form "tag == constant" and only the constant changes could conceivably be recognized by an optimizing compiler and translated into a dispatch via a table (as switch statement might).

**Comment by robpike** [comment]
I agree with @griesemer, and I dislike the proposal as not carrying enough weight.

**Comment by gabeio** [comment]
It was just a thought 👍
