### ISSUE TITLE
cmd/compile: "stupid shift" might offend somebody

### ISSUE THREAD

**Issue by bits01** [golang/go#13940]
(I'm not personally offended but others may be and in the spirit of the Code of Conduct this should probably be fixed and the code scanned for other potentially offensive words; code comments should also be kept clean)

http://play.golang.org/p/GTaPuKn5JX

https://github.com/golang/go/search?utf8=%E2%9C%93&q=stupid

**Comment by AeroNotix** [comment]
This is ridiculous.

**Comment by griesemer** [comment]
offensive shift

**Comment by dr2chase** [comment]
This is not a ridiculous complaint for a "stupid" appearing in an error message, but "ridiculous shift" is also a fractionally better way of phrasing it.  Putting it in an error message is slightly insulting to the user, whereas comments or method names in the compiler itself are less so.

"Overflowing shift" or "Shift beyond word length" are both better ways of saying it (IMO), since they provide more information about what is stupid/ridiculous about the shift.

**Comment by ianlancetaylor** [comment]
"invalid negative shift count"
"integer constant overflow"
