### ISSUE TITLE
x/tools/cmd/godoc: strange HTML whitespace and indentations in source generated

### ISSUE THREAD

**Issue by johanfo** [golang/go#13944]
Take a look at the HTML source of https://golang.org/pkg/fmt/
There are quite some whitespace and strange indentation there, that probably is quite easy to trim.

**Comment by agnivade** [comment]
I took a look into this. This has to do with the "text/template" package. Whitespaces in the source code translate to actual whitespace in the html file. Even assignment statements like `{{$name := printf "%s_%s" $tname .Name}}` create a whitespace in the generated html. It can be somewhat mitigated by using "-" as mentioned here https://golang.org/pkg/text/template/#hdr-Text_and_spaces. But it does not go away completely. And moreover, littering the codebase with "-" does not look good.

I am not fully sure, but I think using the "html/template" package should help in mitigating this naturally.

**Comment by andybons** [comment]
Thanks for the report.

As @agnivade said, the underlying issue here is with the template/* packages, which translates source code whitespace to actual whitespace.

I believe the right path forward would be to propose a change to the template package semantics if you’d like this to change (golang.org/s/proposal) since as of now, this is not a bug, but working as intended.
