### ISSUE TITLE
runtime/pprof: TestMathBigDivide is flaky on FreeBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13943]
https://storage.googleapis.com/go-build-log/e3e88a69/freebsd-amd64-gce101_29908d64.log

```
--- FAIL: TestMathBigDivide (0.49s)
	pprof_test.go:97: profile too short: [0x0 0x3 0x0 0x2710 0x0 0x0 0x1 0x0]
FAIL
FAIL	runtime/pprof	2.557s

```

**Comment by ianlancetaylor** [comment]
Isn't this kind of the same as #13846 ?

**Comment by bradfitz** [comment]
Kind of. They both use testCPUProfile. I was going to send out a CL moving the if-crappy-timer-OS conditionals to testCPUProfile instead, but it didn't feel totally right. The comments didn't exactly belong in the new place, so I'm letting Austin decide.

**Comment by aclements** [comment]
> Isn't this kind of the same as #13846 ?

I can't be positive without checking the timer behavior of that benchmark, but I'd be surprised if it was anything different.

I'm weary of putting a huge blacklist (or a small whitelist) in all of the profiling tests. For most of these, I think we should instead back off and just try running it for longer if we get an empty profile. We've seen flakes all over the profiling tests and I suspect some of them are just because we're running a bunch of other package tests in parallel and the profile test genuinely doesn't get enough CPU time to get samples.
