### ISSUE TITLE
compress/bzip2: oversized block allocation

### ISSUE THREAD

**Issue by mikispag** [golang/go#13941]
At line 79 of `bzip2.go`, you multiply level by 100 * 1024, while the original bzlib.c uses 1000 consistently. They also specify this in the documentation about allocation - see section 3.3.1 of http://www.bzip.org/1.0.5/bzip2-manual-1.0.5.html:

```
Parameter blockSize100k specifies the block size to be used for compression.
It should be a value between 1 and 9 inclusive, and the actual block size used
is 100000 x this figure. 9 gives the best compression but takes most memory.
```

So, instead of:

```
bz2.blockSize = 100 * 1024 * (int(level) - '0')
```

you should probably do:

```
bz2.blockSize = 100 * 1000 * (int(level) - '0')
```

**Comment by dsnet** [comment]
You are correct that the block size used in ```compress/bzip2``` is incorrect, but using a larger block size for decoding shouldn't cause any problems. It may cause it to be able to decode something that the C version otherwise would not be able to.

Is this causing a problem for you?

The wrong block-size is not the only inconsistency between the Go version and the "canonical" C implementation.

**Comment by mikispag** [comment]
You are right, this is not causing problems, but it is using more memory than necessary.

**Comment by mikispag** [comment]
Good point - "the bzip2 decoder would incorrectly decode files with larger block sizes when it should have otherwise failed".

Thanks for fixing this!
