### ISSUE TITLE
x/tools/cmd/goimports: rewriting imports leaves out stdlib imports with '/' in them

### ISSUE THREAD

**Issue by ScottMansfield** [golang/go#14075]
with imports like:

```
import "bytes"
import "encoding/binary"
```

and code that adds a dependency on another package, like bufio:

```
bufio.NewReader(os.Stdin)
```

goimports will rewrite the imports to look like:

```
import (
	"bufio"
	"bytes"
)
import "encoding/binary"
```

The formatting here is odd. I expected it to look like either:

```
import "bufio"
import "bytes"
import "encoding/binary"
```

where the established convention in the code of using `import` before every import is left alone or

```
import (
	"bufio"
	"bytes"
	"encoding/binary"
)
```

where the convention of using grouped imports is properly done.

**Comment by mdempsky** [comment]
The behavior here is unrelated to the '/' character in "encoding/binary"; e.g., I can repro the issue with "os" instead of "encoding/binary".

goimports is just adding all of the new imports to the first import declaration in the file, and leaving other existing imports separate.  Arguably this is working as documented.  /cc @bradfitz

**Comment by bradfitz** [comment]
I suppose we could make it have a merging pass afterwards. Somebody could add that to https://godoc.org/golang.org/x/tools/go/ast/astutil

/cc @griesemer
