### ISSUE TITLE
After calling ioutil.ReadFile() in a goroutine,  the read data will not be garbage collected

### ISSUE THREAD

**Issue by pinkfloyda** [golang/go#14089]
I tested the below code in OSX 10.10.5 x64 using go1.5.3 darwin/amd64, it turns out consume all the memory quickly.
```
package main
import "io/ioutil"
func main() {
	for {
		go func() {
			ioutil.ReadFile("xx.pdf")
		}()
	}
}
```
However, if I just call ioutil.ReadFile in a for loop, the memory is stable.
```
package main
import "io/ioutil"
func main() {
	for {
	     ioutil.ReadFile("xx.pdf")
	}
}
```

**Comment by post-l** [comment]
Obviously in the first code, you will allocate `buf := bytes.NewBuffer(make([]byte, 0, capacity))` for each goroutine so it's not a bug from go but your usage and you will maybe runout of file descriptor depending of your system. In the second code, the buf will be garbage collected when the function ReadFile return because you are not using it so the memory will remain stable. You should understand more what you are doing before posting an issue ;)

**Comment by ianlancetaylor** [comment]
This seems like expected behavior to me.  Starting a goroutine in each iteration of a for loop is going to push your system into overload as fast as possible, as the program tries to read as many copies of the file as it can handle.  In the non-goroutine version, you are reading one instance of the file at a time, so when you read the second instance the garbage collector can discard the first.

**Comment by pinkfloyda** [comment]
actually, I encounter this when I read this post in "https://blog.golang.org/pipelines/bounded.go"
i found out that even it limits the calls to some limited number of workers, it still consumes a lot of memory, seems the memory is not reclaimed fast. So I just create the above as a demo.

**Comment by pinkfloyda** [comment]
okay... I just found that piece of code stores the hash into a hashtable, which is consuming memory, my bad, :-(

**Comment by pinkfloyda** [comment]
@ianlancetaylor @post-l , I just change to the code to below, the issue I observed is not out-of-memory, it is the memory not reclaimed after each goroutine finishes. As the below code shows, for each goroutine, after running ReadFile, the memory should be reclaimed. But we wait at time.Sleep,
I observe in the "Activity Monitor", the process remains using a few GBs of memory.......
```
func main() {
	for i := 1; i <= 100000; i++ {
		go func() {
			data, err := ioutil.ReadFile("xxx.pdf") // choose some relatively large file
			if err == nil && len(data) > 0 {
				return
			}
		}()
	}
	time.Sleep(time.Second * 100)
}
```

**Comment by ianlancetaylor** [comment]
I still think this should go to a forum, not the issue tracker.

The activity monitor shows memory allocated to the process.  It does not show how much memory is in use by Go itself.  For that you need to use https://golang.org/pkg/runtime/#ReadMemStats .

Over time the Go runtime will return unused memory to the system, and that will (I believe) be visible on the activity monitor.  This process takes 5 minutes or more; the Go runtime is conservative, since the program might need the memory again soon.

**Comment by daemonfire300** [comment]
I can report on this issue to, since I am working on a solution for 3-4 days now.

```go
// some DownloadFileFunction
func download() (*bytes.Buffer, err){
response, err := defaultHttpClient.Do(req)
//..
defer response.Body.Close() //yadayada
buf := bytes.NewBuffer(make([]byte, 32 * 1024)) // io.Copy makes this anyway if I pass in an empty one, I also tried it with size 0
_, err = io.Copy(buf, response.Body)
return buf, err // buf is obviously *bytes.Buffer
}

func  Run() {
	go func() {
		for {
			select {
			case job := <-w.Job:
                            buf, err := download(job.URL.String())
                            job.dataChannel <- buf.Bytes()
			}
		}
        }
}

func httpHandler(....){
// fill jobQueue with jobs to be consumed by Worker goroutines
dataChan, errChan = AddDownloadJob(dlJobCollector, u.String())
// wait for error
err = <-errChan
// no error? receive on the dataChannel
data = <-dataChan
// close after receiving
close(dataChan)
// pass data []byte to another goroutine for Upload
errChan = AddUploadJob(uploadJobCollector, data)
}
```

Using  `go tool pprof -inuse_space mybinary`
```
(flat,cum)
  .    61.25MB     98:   _, err = io.Copy(buf, response.Body) 
  .    61.75MB    168:  buf, err := download(job.URL.String())
```
```
(pprof) top
81.35MB of 82.35MB total (98.79%)
Dropped 491 nodes (cum <= 0.41MB)
Showing top 10 nodes out of 58 (cum >= 0.50MB)
      flat  flat%   sum%        cum   cum%
   61.25MB 74.38% 74.38%    61.25MB 74.38%  bytes.makeSlice
    8.84MB 10.73% 85.11%     8.84MB 10.73%  main.fileReadAppend
    3.50MB  4.25% 89.36%     3.50MB  4.25%  net/textproto.(*Reader).ReadLine
       3MB  3.64% 93.01%    12.55MB 15.24%  main.uploadHttpHandler
       2MB  2.43% 95.44%        2MB  2.43%  main.(*UploadWorker).Run.func1
    0.54MB  0.66% 96.96%     0.54MB  0.66%  html.init
    0.50MB  0.61% 97.57%     0.50MB  0.61%  crypto/tls.(*block).reserve
    0.50MB  0.61% 98.18%     0.50MB  0.61%  encoding/pem.Decode
    0.50MB  0.61% 98.79%     0.50MB  0.61%  reflect.unsafe_NewArray
```

I tried this with difference approaches with ioutil etc, and on a high traffic server this quickly runs into 500MB - 1000MB memory usage just for `bytes.makeSlice`.
I even tried lowering `GOGC` to 30.

**Comment by bradfitz** [comment]
We do not have discussions on closed bugs. Let's move this to the mailing list. See https://golang.org/wiki/Questions
