### ISSUE TITLE
x/crypto/ssh: Support OpenSSH protocol extension for host key rotation

### ISSUE THREAD

**Issue by tt** [golang/go#14114]
OpenSSH supports [a protocol extension for host key rotation](https://anongit.mindrot.org/openssh.git/tree/PROTOCOL?id=deb8d99ecba70b67f4af7880b11ca8768df9ec3a#n284). While it probably isn't widely deployed yet, the world would be better if it were. See [this blog post](http://blog.djm.net.au/2015/02/key-rotation-in-openssh-68.html) for background information.

[The `AddHostKey` function](https://github.com/golang/crypto/blob/59a4410d829a8bb774b02b56d4aeab633414f233/ssh/server.go#L77-L89) currently overwrites host keys of the same algorithm. I suspect this could be extended to track all keys and offer them to clients using the "hostkeys-00@openssh.com" message.

**Comment by ianlancetaylor** [comment]
CC @agl @hanwen

**Comment by hanwen** [comment]
in the handshake, the server can only offer one key of each type to the client. Hence, it doesn't make much sense to change AddHostKey.

The document you describe is a global request/response call, which can be implemented in the application layer, in particular, the request will be sent to the request channel returned from https://godoc.org/golang.org/x/crypto/ssh#NewServerConn . Since the SSH library doesn't include a real server application layer implementation, it's not obvious where to hook it up.

I have the following suggestion: you could write a set of functions that will let a client issue the request, let the server send a set of new keys, and let the client verify them. If you implement both sides, you can unittest them against each other. Then people can install these functions into clients or servers as they please.

I think these functions should live outside the SSH package proper, since it is an application level mechanism, and not really a protocol extension. If we have a library, we could put it into standard library as (say) x/crypto/ssh/keyrotate/

I am strongly in favor of putting any and all application extensions into separate packages, rather than adding them to the ssh library. This makes the SSH package more maintainable, and easier to understand to callers.
