### ISSUE TITLE
net/http/httputil: ReverseProxy doesn't remove Trailer header due to misspelling

### ISSUE THREAD

**Issue by opennota** [golang/go#14174]
https://github.com/golang/go/blob/af15beeab5ff9cde411c3db086ca9a24ace4c898/src/net/http/httputil/reverseproxy.go#L113

It says "Trailers" while it should be "Trailer"

**Comment by bradfitz** [comment]
Thanks!

Sent a CL. We'll get it submitted for Go 1.7 at least, unless @rsc thinks it's okay for Go 1.6.

It's been many releases with the current bug and doesn't seem to have bitten anyone. That's probably because nobody's used trailers much until recently, with gRPC depending on them. So maybe this will become more noticeable as people start to proxy gRPC.
