### ISSUE TITLE
x/exp/shiny: assigning to *buf.RGBA() works on gldriver but not x11driver

### ISSUE THREAD

**Issue by jnjackins** [golang/go#14191]
I had some code like this:

```go
*buf.RGBA() = *img
tx.Upload(image.ZP, buf, buf.Bounds())
win.Copy(min, tx, tx.Bounds(), screen.Src, nil)
```

This worked on gldriver, but not x11driver. After switching to the following, it worked on both:

```go
draw.Draw(buf.RGBA(), img.Bounds(), img, image.ZP, draw.Src)
tx.Upload(image.ZP, buf, buf.Bounds())
win.Copy(min, tx, tx.Bounds(), screen.Src, nil)
```

I have not yet investigated why it works on one but not the other, but first: should this work? It feels like I'm paying a performance penalty by drawing my image to buf.RGBA() when I already have exactly the image that I want.

**Comment by jnjackins** [comment]
CC @nigeltao @crawshaw

**Comment by nigeltao** [comment]
The short answer is, no, it should not work.

A Buffer is essentially an *image.RGBA, but not all *image.RGBAs are valid Buffers. (If they were, the Upload method might as well take an *image.RGBA instead of a Buffer). Drivers may assume that the memory backing a Buffer's pixels are specially allocated, such as shared memory, shared across multiple processes. Arbitrary *image.RGBAs do not satisfy that assumption.

As I tried to say on #14026, your Editor shouldn't have an *image.RGBA or be an *image.RGBA. Instead, it should be able to render itself onto a Buffer's *image.RGBA (where the Buffer is provided by Screen.NewBuffer).

On a side note, with your original code snippet:

*buf.RGBA() = *img
tx.Upload(image.ZP, buf, buf.Bounds())
win.Copy(min, tx, tx.Bounds(), screen.Src, nil)

you might not need to explicitly use a Texture. A Window already has an Upload method, which takes a Buffer.

**Comment by jnjackins** [comment]
> As I tried to say on #14026, your Editor shouldn't have an *image.RGBA or be an *image.RGBA. Instead, it should be able to render itself onto a Buffer's *image.RGBA (where the Buffer is provided by Screen.NewBuffer).

Ah, thank you. This is obvious now that you say it (I missed it last time, apparently). I've been stuck on the idea that I need to construct my own image, and then copy it to the buffer.

> you might not need to explicitly use a Texture. A Window already has an Upload method, which takes a Buffer.

Yes, my example code was simplified. Usually I can reuse the texture (which I believe is much cheaper than uploading the buffer each time).
