### ISSUE TITLE
go 1.6rc2: cgo error when executing non-cgo tests

### ISSUE THREAD

**Issue by aaronbee** [golang/go#14247]
What version of Go are you using (go version)?

go1.6rc2

What operating system and processor architecture are you using?

Mac OS 10.11.3 El Capitan

What did you do?

`go test -race -timeout 5s PACKAGE`

What did you expect to see?

`ok  	PACKAGE	1.303s`

What did you see instead?

```
# runtime/cgo
clang: error: couldn't open cache file '/var/folders/dh/8tf0gx091zs_02mw_s0c956w0000gp/T/xcrun_db' (errno=File exists)
ok  	PACKAGE	1.303s
```

As you can see above I got this seemingly harmless error related to cgo and clang, but the code I am executing has no cgo component at all. I have run these exact same tests before and after this instance and have not seen the error message again.

**Comment by davecheney** [comment]
This error is caused by Xcode being updated. Apple injects a wrapper around each component distributed with Xcode, including open source tools like clang and git, to ensure you've agreed to Apple's licence.

Running clang, git, or `xcode-select --install` from the terminal will trigger the interactive licence process and licence your toolchain. You will probably need to repeat this process every time Xcode is updated.
