### ISSUE TITLE
compress/flate: Add optimizations and re+balance.

### ISSUE THREAD

**Issue by klauspost** [golang/go#14258]
We should merge optimizations added to https://github.com/klauspost/compress

Typical speedup is around 1.7x for web content, when maintaining roughly the same compression. 

With [re-balanced compression settings](https://github.com/klauspost/compress/pull/31), the default level will be 3.1x faster at a 7% compression loss. Mixed content (disk images) show a 3.1x speedup with a 3% compression loss.

Extensive benchmarks in this [google spreadsheet](https://docs.google.com/spreadsheets/d/1nuNE2nPfuINCZJRMt6wFWhKpToF95I47XjSsc-1rbPQ/edit?usp=sharing).

**Comment by rsc** [comment]
@nigeltao, @klauspost, what is left here? Did the rebalancing happen?

**Comment by nigeltao** [comment]
Some optimizations landed. Others didn't make the code freeze deadline. @klauspost would probably know better than me what's out that he'd still like to bring over from https://github.com/klauspost/compress

Re-balancing, in terms of tweaking what parameter settings correspond to "compression level == 6", didn't happen, but when compared to Go 1.6, I believe that compression is still generally faster on GOARCH=amd64 at the default setting. I don't have any numbers on me right now.

Also, "compression level == 1" aka "best speed" now uses the Snappy algorithm, for higher throughput but larger encoded size. That encoding size can come down with further algorithmic changes, but there was a correctness bug found in the fancier algorithm just before code freeze, so that will have to wait for Go 1.8.

I don't think there are any open CLs. Please correct me if I'm wrong.

**Comment by klauspost** [comment]
I think the overall goal has been achieved, with some details left.

>Did the rebalancing happen?

No - I haven't tested the current build, but I suspect it could need a re-balance and that "standard" is quite close to "best" in terms of both compression and speed.

There are a few things that I would like to look at in the future, mainly:

* Split lazy/non-lazy matching, and add 3-length matching to the lazy matcher as an elegant fix for #15622. Not sure if Nigel agrees through.
* Re-balance. If lazy is made capable of 3 byte matches, that will be even more relevant, and "lazy" belongs to level 7-9 or thereabout.
* The token storage can be made to avoid bounds checks. This is trivial and can be quite nicely implmented, but I couldn't make the 1.7 deadline.

>I don't think there are any open CLs. Please correct me if I'm wrong.

Correct, AFAIK.
