### ISSUE TITLE
net/http: HttpClient does not close connection after timeout

### ISSUE THREAD

**Issue by janisz** [golang/go#14335]
Hi

I experienced a problem with HttpClient. For following code, I expect to have some opened TCP connections, but usually it's over 700.

```
package main

import (
	"io"
	"io/ioutil"
	"net/http"
	"fmt"
)

func main() {

	client := http.DefaultClient
	client.Timeout = 1
	fmt.Println("Sending requests:")
	for i := 0; i < 1000; i++ {
		resp, err := client.Get("http://google.com/")
		fmt.Print(".")
		if err == nil {
			fmt.Println("\nClose response")
			io.Copy(ioutil.Discard, resp.Body)
			resp.Body.Close()
		}
	}
	fmt.Println("\nWaiting")
	for {}
}
```
I tried changing configuration of http client (`DisableKeepAlives`, `MaxIdleConnsPerHost` etc) but always ended up with many open connections.

Similar issue was mentioned here:
* http://grokbase.com/t/gg/golang-nuts/14aptz82rv/go-nuts-fd-leak-in-http-client
* http://biasedbit.com/blog/golang-custom-transports
* #4049 

Tested on:
* go version go1.5 darwin/amd64
* go version go1.5 linux/amd64
* go version go1.6rc2 linux/amd64

CC: @dankraw

**Comment by cespare** [comment]
cc @bradfitz

**Comment by mjarco** [comment]
You've set timeout for one nanosecond and then blocked main goroutine. So none of your requests were send but you initiated some syscalls, and didn't give any time for transport/dialer to shut down initiated connections. That's why they hang infinitely. 
I would not consider it as a bug.
Some code that proofs my theory:
https://play.golang.org/p/uGxH_OpBMX

**Comment by ianlancetaylor** [comment]
Don't write `for {}`.  Write `select {}`.

Please feel free to reopen if you disagree.
