### ISSUE TITLE
make.bash: make default GOROOT_BOOTSTRAP more useful

### ISSUE THREAD

**Issue by perillo** [golang/go#14339]
There are currently two problems with default `GOROOT_BOOTSTRAP` handling in the `make.bash` script.

The first problem is that the default value set in `make.bash` (`$HOME/go1.4`) will not be used by the `go dist` tool, since the new `GOROOT_BOOSTRAP` environment variable is not exported.  The code works only because the `go dist` tool uses the same default value.

The second problem is that `$HOME/go1.4` will be an invalid `GOROOT` for the majority of users, thus forcing the user to explicitly set the `GOROOT_BOOSTRAP` environment variable.

I propose to change the default `GOROOT_BOOTSTRAP` value to the value returned by `go env GOROOT`, where the `go` command in `PATH` is used.  The `GOROOT_BOOSTRAP` should be exported.  As an example:

``` bash
export GOROOT_BOOTSTRAP=${GOROOT_BOOTSTRAP:-$(go env GOROOT 2>/dev/null)}
export GOROOT="$(cd .. && pwd)"
```

**Comment by minux** [comment]
Changing the default GOROOT_BOOTSTRAP to $(go env GOROOT)
will break users of go tip.

**Comment by perillo** [comment]
On Mon, Feb 15, 2016 at 8:57 PM, Minux Ma <notifications@github.com> wrote:

> Changing the default GOROOT_BOOTSTRAP to $(go env GOROOT)
> will break users of go tip.
>

But using $HOME/go1.4 will force everyone to explicitly set
GOROOT_BOOTSTRAP.
What is better: forcing "normal " users to explicitly set GOROOT_BOOTSTRAP
or forcing users of go tip to explicitly set GOROOT_BOOTSTRAP?

**Comment by minux** [comment]
I don't think it's unreasonable to rebuild Go with make.bash
with the current $GOROOT/bin in $PATH. It's not necessarily
specific to Go tip users.

**Comment by rsc** [comment]
I strongly disagree about using the current PATH's 'go', because many times that will be the Go distribution being rebuilt at that moment, and you'll get into weird circularity problems.

However, if you can filter out the current directory's go command, for example with appropriate processing of "which -a go", then using the next go in the path might be reasonable. That seems fine if someone wants to write the CL (and it's simple!), but it's not a release blocker.
