### ISSUE TITLE
runtime: gcMarkRootCheck contributes significantly to mark termination time

### ISSUE THREAD

**Issue by rhysh** [golang/go#14419]
When profiling the reproducer for #14406 with "go version go1.6 linux/amd64", stack shrinking off, and numactl disabling memory migration, I see calls to `runtime.gcMarkRootCheck` on 12% of the stacks that include `runtime.gcMark`. The comment for the function indicates that it's for debugging—is that for producing higher-quality bug reports if there's memory corruption or incorrect GC behavior in production releases, or for debugging while writing the GC?

@aclements

**Comment by aclements** [comment]
Confirmed. This mark termination latency regression happened in 82d14d7 when I introduced gcMarkRootCheck. The cost is ~30ns per goroutine, similar to #14420.

I could simply remove it. I'm a bit weary of doing that because it's a good check. If I lift gcscandone into a contiguous array as I proposed in #14420, I suspect the check will be roughly free (and now I have the benchmarks to confirm that :)

**Comment by aclements** [comment]
It looks like gcMarkRootCheck is only about 10ns of that 30ns per goroutine. I'm not entirely sure where the rest of it is coming from, but I have some ideas for how I might be able to restructure mark termination so there are no O(# goroutines) steps at all. (That's obviously not for Go 1.6.1, especially since it depends on concurrent stack shrinking. :)
