### ISSUE TITLE
fmt: inconsistency in 0 padded formatting of Inf and Nan float values

### ISSUE THREAD

**Issue by martisch** [golang/go#14421]
For e.g. "%020f" Inf is not 0 padded but NaN is.

```
00000000000000000NaN
                +Inf
                -Inf


https://play.golang.org/p/qiO-mme4S6

There is no test case for 0 padded NaN (but for Inf) and it seems this behavior has existed throughout Go 1.x .
C does not 0 pad NaN and Infs which seemed the reason the Infs are treated special in Go too.

This might not be changed anymore due to the Go 1 guarantees but the API documentation does not seem to explicitly mention the treatment for NaN or Inf either.

Not sure if it should just be document or if this should be fixed for 1.7 
If ok i can submit a patch that just adds a test case for current Go behavior with a comment that references this issue or make the treatment of NaN consistent with Inf.

**Comment by robpike** [comment]
It's just saying, "Oooooh, a Nan!".

Might be a consequence of https://go-review.googlesource.com/19721 or might be old. Should be easy to fix regardless.

**Comment by minux** [comment]
The NaN issue has existed since Go 1.0. But
the Inf case has changed a little bit:

go version go1
00000000000000000NaN
0000000000000000+Inf
0000000000000000-Inf
go version go1.1.2 linux/amd64
00000000000000000NaN
0000000000000000+Inf
0000000000000000-Inf
go version go1.2.1 linux/amd64
00000000000000000NaN
+0000000000000000Inf
-0000000000000000Inf
go version go1.2.2 linux/amd64
00000000000000000NaN
+0000000000000000Inf
-0000000000000000Inf
go version go1.3 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.3.3 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.4 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.4.1 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.4.3 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.5 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.5.3 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version go1.6 linux/amd64
00000000000000000NaN
                +Inf
                -Inf
go version devel +e6d6ad4 Sat Feb 20 20:16:27 2016 +0000 linux/amd64
00000000000000000NaN
                +Inf
                -Inf

so Go 1.3 fixes the Inf problem, but the NaN problem persists.

**Comment by martisch** [comment]
Writing the patch that rob mentioned made me aware of the NaN case.  
I write a patch to fix the NaN case now. 
Just wanted to make sure its ok to correct and does not break any Go 1.x guarantees. But since Inf only changed in 1.3 i guess its ok to make them consistent.
