### ISSUE TITLE
The biggest 3 things that golang should do first.

### ISSUE THREAD

**Issue by iamybj** [golang/go#14461]
**android/ios
bigdata
GUI**

I think these 3 things should have the highest priority.
If golang doesn't notice this, it will lost the time.

**Comment by minux** [comment]
Thanks for the comment.

Works are already underway for the first and 3rd point.
x/mobile and x/exp/shiny, respectively.

bigdata is too board a term for me to comment.

This issue is not quite actionable, so closing.

If you want to propose the addition of a specific feature
or package, please elaborate.

**Comment by iamybj** [comment]
Fuck , you dont know anyting.
you even dont know bigdata like : lucene, solr, hadoop, spark.....

**Comment by integrii** [comment]
![big data](http://cdn.meme.am/instances/47510205.jpg)

**Comment by pobri19** [comment]
Do you even bigdata?

**Comment by integrii** [comment]
I need to know if golang is webscale ASAP.
