### ISSUE TITLE
csv package LazyQuotes bug

### ISSUE THREAD

**Issue by naxels** [golang/go#14525]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
https://play.golang.org/p/Ibi4KpmgiE

4. What did you expect to see?
[[2 The Godfather 1972]]

5. What did you see instead?
[[2 The Godfather|1972]]
 - notice the | character that means, it is not split

**Extra notes:**
In the play.golang.org example, if you move the double quote after the letter T
then it works just fine
however it seems like if the double quote is right after the delimiter, the outcome is not as expected

**Comment by ianlancetaylor** [comment]
As far as I can tell this is working as documented.

    // Fields which start and stop with the quote character " are called
    // quoted-fields.  The beginning and ending quote are not part of the
    // field.

    // If LazyQuotes is true, a quote may appear in an unquoted field and a
    // non-doubled quote may appear in a quoted field.

Your field starts with a quote character, and is therefore a _quoted field_.  Setting `LazyQuotes` means that a non-doubled quote may appear in a quoted field, but that is not the case here.

Please feel free to reopen if you disagree.

**Comment by naxels** [comment]
Thank you,

The documentation just seems confusing to me then, because I can put the " anywhere else with LazyQuotes on
but the only time it goes 'wrong' (no error) is when I put the " as first character on the right of the delimiter (or start of line)

If this is not a bug, how can I request a feature, that would add a config option to totally disable the "quoted field" ability?
the reason is, I want to use the csv package to check data not generated by myself, which could contain any character, however the only consistent item is the delimiter. therefor a " can exist anywhere in the data.

Thanks for your help

**Comment by ianlancetaylor** [comment]
> The documentation just seems confusing to me then, because I can put the " anywhere else with LazyQuotes on
> but the only time it goes 'wrong' (no error) is when I put the " as first character on the right of the delimiter (or start of line)

This is consistent with the documentation as I read it.  Any fields that starts with a " is a quoted field.  The `LazyQuotes` configuration only affects unquoted fields.  `LazyQuotes` doesn't mean that quotes are ignored.

In the past we've rejected requests to add further configuration parameters to encoding/csv, because there are just too many variants.  We can't support them all and still have a comprehensible package--you can see how even the `LazyQuotes` configuration parameter is confusing.  I would suggest that you copy the package and adjust it for your needs.

Actually, if you really don't care about quotes at all, then it seems to me that encoding/csv becomes almost trivial.  You may as well just read line by line and call strings.Split(line, ",").

**Comment by naxels** [comment]
Awesome tip, I did replace csv with bufio pkg
and added strings.Split() and it almost instantly passed my tests

Thank you
