### ISSUE TITLE
debug/gosym: TestPCLine failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#14536]
The TestPCLine test is failing on Plan 9:

```
entry not text: main
--- FAIL: TestPCLine (0.17s)
	pclntab_test.go:50: exit status: 'go 149759: 1'
FAIL
FAIL	debug/gosym	0.174s
```

This failure can only be seen on the plan9/amd64 builder, because this test is only enabled on amd64.

The test runs the following commands:

```
% go tool asm -o /tmp/pclinetest.o pclinetest.asm
% go tool link -H linux -E main -o /tmp/pclinetest /tmp/pclinetest.o
entry not text: main
```

The [Entryvalue](https://github.com/golang/go/blob/92bf58c238/src/cmd/link/internal/ld/lib.go#L2029) function return "entry not text: main", because s.Type is type SXREF instead of STEXT.

In fact, in the [libinit](https://github.com/golang/go/blob/92bf58c238/src/cmd/link/internal/ld/lib.go#L416) function, INITENTRY was set to type SXREF because DynlinkingGo() returns false on Plan 9.

**Comment by ianlancetaylor** [comment]
`DynlinkinGo` normally returns false on GNU/Linux too.  I think there must be some other aspect to this.

**Comment by ianlancetaylor** [comment]
This is working on GNU/Linux because the linker is being invoked with -E main, and runtime/rt0_linux_amd64.s defines a symbol main, thus ensuring that the INITENTRY symbol gets to be STEXT.  plan9 doesn't define main, so the symbol remains SXREF, and the linker balks.

I don't know why the test is passing a -E option; it might work fine if it simply didn't do that.  The -E option dates back to revision f277ebfc7615f6b18856919917bc62e7628109bb in September, 2009, and has simply been carried forward since then.

**Comment by 0intro** [comment]
Yes, you're right. I propose [CL 19973](https://golang.org/cl/19973) instead.
