### ISSUE TITLE
cmd/compile: fails to reject empty blocks after fallthrough statement

### ISSUE THREAD

**Issue by mdempsky** [golang/go#14540]
cmd/compile accepts this source:

```
package f

func g() {
        switch {
        case true:
                fallthrough
                {}
        case false:
        }
}
```

It shouldn't.

(See also #14422.)

**Comment by josharian** [comment]
The problem here is that order.go eliminates the empty block before it gets to walk, which is where this error ("fallthrough statement out of place") is usually detected.

It seems to me that this error can be easily detected syntactically and that we should move the error checking for it much earlier, perhaps to noder. But not for 1.9.
