### ISSUE TITLE
net/url: Trailing question marks in query string appears to be misparsed

### ISSUE THREAD

**Issue by bjkail** [golang/go#14573]
Commit  9f26170 from issue #13488 appears to improperly parse URLs if the query string ends in `?`, such as `http://host/?q=?`.  I noticed through code inspection, so I don't have a way to verify and so this issue might be invalid.  The current playground seems to behave correctly: http://play.golang.org/p/khxLopsBd0

**Comment by dghubble** [comment]
I noticed this in some test logs as well. A test made a request with a URL ending in "?" to assert the service dealt with some unexpected query value. Following 9f26170a0, `http.NewRequest` fails to create the `http.Request` due to the `url.Parse` change.

    _, err := http.NewRequest("GET", "http://a.io?mac=?", nil)
    fmt.Println(err)
    
Output

    &url.Error{Op:"parse", URL:"http://a.io?mac=?", Err:"?"}

I expected `url.Parse` to parse the URL ending in "?".
