### ISSUE TITLE
io/ioutil: possible legal issue with random number generator

### ISSUE THREAD

**Issue by perillo** [golang/go#14773]
The random number generator used in ioutil package is the `ranqd1` function implemented in Numerical Recipes.  The problem with Numerical Recipes is that all the code is under copyright, and it is illegal to use it inside the Go standard library.

I suggest to replace the comment `// constants from Numerical Recipes` with something like `the constant a has been suggested by Knuth and the constant b has been extensively tested by H.W. Lewis`.

**Comment by dgryski** [comment]
The line in question is https://github.com/golang/go/blob/5fea2ccc77eb50a9704fa04b7c61755fe34e1d95/src/io/ioutil/tempfile.go#L32

**Comment by rsc** [comment]
Thanks. I will check with our open source lawyers.

**Comment by dberlin** [comment]
Hey perillo,
"The problem with Numerical Recipes is that all the code is under copyright, and it is illegal to use it inside the Go standard library."

Thanks for your concern.

A few things:
1. It's not "illegal" in any case :)
2.  This is clearly not a copy of the code from numerical recipes, it simply implements the same algorithm from scratch and uses the same constants.
3. Constants from mathematical formulas are not copyrightable, and reusing them here is actually just fine.  Even more so, because, as you point out, they didn't even come up with them (which means even if it was copyrighted, the copyright would not cover this portion which was pre-existing).

You suggested the following fix:
"I suggest to replace the comment // constants from Numerical Recipes with something like the constant a has been suggested by Knuth and the constant b has been extensively tested by H.W. Lewis."

We should not do this. This would simply hide where the constants came from.  This makes it seem like something wrong has happened here, but nothing bad has actually happened.  Instead, we are comfortable with what happened here - reuse of two well known mathematical constants.  We should keep this comment as-is and close this issue.

**Comment by ianlancetaylor** [comment]
Thanks, Danny.
