### ISSUE TITLE
cmd/compile: xdcl_list / testdclstack slow when there are lots of decls

### ISSUE THREAD

**Issue by josharian** [golang/go#14781]
```bash
$ go get github.com/davecheney/genpkg
$ genpkg -n 50000 > x.go
$ go tool compile -cpuprofile=cpu.prof -d=ssa/check/off x.go  # slow!
$ go tool pprof -pdf `go tool -n compile` cpu.prof > cpu.pdf
```

testdclstack shows up as ~20% of the cpu time, with xdcl_list one frame up.

I quick look suggests that there may be an O(n^2) interaction between xdcl_list and testdclstack--it looks like xdcl_list adds decls one at a time and calls testdclstack for the entire stack each time. (Could testdclstack be called after the loop instead?)

I think that @mdempsky or @griesemer may be looking into this (and I am not); just filing an issue so we don't forget about it.

cc @davecheney -- thanks for the test case :)

**Comment by griesemer** [comment]
testdclstack is a consistency check only - fine to disable (and only run in a special debug mode in the compiler)

In the long run we should replace this sequential list and use a proper block structure. I've started working on this yesterday but hit some roadblocks.

**Comment by mdempsky** [comment]
I'm curious if the problem is that declare is adding PFUNC declarations (i.e., global function declarations) to dclstack, rather than adding them to externdecl like it already does for PEXTERN declarations (i.e., global variable, const, type declarations).  There shouldn't be any need for us to track package scoped symbols in dclstack.
