### ISSUE TITLE
spec: gotype accepts a[1.0<<s] though the compilers do not - which is correct?

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#14844]
The spec says (https://golang.org/ref/spec#Operators):

> If the left operand of a non-constant shift expression is an untyped constant, it is first converted 
> to the type it would assume if the shift expression were replaced by its left operand alone.

Consider the following program (http://play.golang.org/p/LsZYy_l_hD):

``` Go
package main
import "fmt"
func main() {
    s := uint(0)
    a := []int{1, 2}
    // A
    x := a[1.0]
    // B
    x = a[1.0<<s] // error
    fmt.Println(x, s)
}
```

According to the above part of the spec, it would seem that `1.0` in statement B should be converted to `int`, as it was converted in statement A, since A is what B looks like after, quote, "shift expression were replaced by its left operand alone."

However:
-  `go` version devel +f2772a4 Tue Mar 15 19:57:40 2016 +0000 linux/amd64 reports an error:

> ./shift-5.go:11: invalid operation: 1 << s (shift of type float64)
- corresponding `gotype` produces no output
- `gccgo` (GCC) 6.0.0 20160314 (experimental) [master revision 96e5a1e:5a53517:1bd2aefdf63c38093e950d365c5b4fa9ed4a5197]

> shift-5.go:11:7: error: index must be integer
>  x = a[1.0<<s] // error
>       ^
> shift-5.go:11:11: error: shift of non-integer operand
>  x = a[1.0<<s] // error

Indeed, the spec does not require the index in non-map index-expressions to be of or convertable to `int`. Nonetheless, one would expect either both or none of A and B to fail.

**Comment by martisch** [comment]
The way i would view it is in A 1.0 is untyped but converted to int because the index demands it. So its untyped -> int. In b 1.0 is first converted to float, then the float (not the untyped constant) is shifted which results in float. However float cant just be cast implicitly to int which the index demands. So its untyped -> float -> float |-error-> int. Which is different from just untyped -> int.

**Comment by ianlancetaylor** [comment]
I think the compilers are correct and go/types (which I gather does not give any errors) is wrong.

In A `1.0` is an untyped constant.  In B `1.0` is not untyped, because `s` is not a constant.  So your comparison between them is misleading.  The correct comparison would be something like

    f := 1.0
    x := a[f]

**Comment by griesemer** [comment]
@ianlancetaylor According to the spec ("If the left operand of a non-constant shift expression is an untyped constant, it is first converted to the type it would assume if the shift expression were replaced by its left operand alone."), there's no difference in typing of `1.0` in A and B --- for typing purposes, it is as if the shift doesn't exist.

Specifically, in B, `1.0` is an untyped constant no matter the type of the shift count ("Except for shift operations, if one operand is an untyped constant and the other operand is not, the constant is converted to the type of the other operand."; i.e., shifts are special, and the shift count type has no influence on the type of the shift result whatsoever - nor does it matter here if `s` is constant or not).

We do accept `a[1.0]` and thus we must accept `a[1.0 << s]` since the type of this non-constant shift depends only on the type that the left operand would assume.

If `1.0 << s` would indeed assume a floating-point result independent of context (in this case its use in an index expression), then an operation such as `var m int = 1.0 << s` would be invalid as well. However, this is explicitly permitted (see example in http://golang.org/ref/spec#Operators).

That is, it really depends on what the context is. The question is, for index expressions, does the context require an integer value? The spec says: "(If a is not a map) the (non-constant) index x must be of integer type or untyped" (http://golang.org/ref/spec#Index_expressions).

I believe the spec is vague here. But since we accept `1.0` as integer value (which would become a float64 in `c := 1.0`), it makes sense to accept `1.0 << s` as integer value (which would become a float64 in `c := 1.0 << s`) since for non-constant shifts only the type of the left operand matters.

I argue that gotype is correct and the compiler(s) should accept this code. Alternatively, the spec could be made more restrictive in this case, but that would add extra rules which don't seem to be necessary.

**Comment by rsc** [comment]
I think we all agree that

    func f(int64)
    f(1.0<<s)

is OK and that

    func g(interface{})
    g(1.0<<s)

is NOT OK. (And the playground agrees too: https://play.golang.org/p/WS65K_B_hd).

The problem is:

    var h []int
    _ = h[1.0<<s]

Slice index is halfway between these: there's no one type dictated by context, but there are some types excluded, unlike interface{}. 

I believe that the slice index here is disallowed by the spec. Ian agrees too (above), and Robert agreed in 2013 when I wrote these lines in test/shift1.go (https://golang.org/cl/7861045):

        // For now, the spec disallows these. We may revisit past Go 1.1.
        _ = a[1.<<s]  // ERROR "integer|shift of type float64"
        _ = a[1.1<<s] // ERROR "integer|shift of type float64"

It seems fine to revisit the spec, of course. It's not a big deal if we change this.

At this point, not for Go 1.8 though.

**Comment by bradfitz** [comment]
@griesemer, Go 1.9 or punt to Go 1.10?

**Comment by griesemer** [comment]
I like to fix this one. I think we all agree that the spec is not 100% clear here. To restate, the problem is:
```
var a []int
var s uint
_ = a[1.0 << s]  // valid or not? (compiler says no, go/types says yes)
```
The relevant rules are:
1) Non-constant shifts: "If the left operand of a non-constant shift expression is an untyped constant, it is first converted to the type it would assume if the shift expression were replaced by its left operand alone." (https://tip.golang.org/ref/spec#Operators)

2) Indexing: "(If a is not a map:) the index x must be of integer type or untyped; it is in range if 0 <= x < len(a), otherwise it is out of range", and "a constant index must be non-negative and representable by a value of type int" (https://tip.golang.org/ref/spec#Index_expressions).

As @rsc argues above, there's no type dictated by the context, but there some types excluded. The question is, does "1.0" become a "1" in this context or not (it does if there were no shift per 2), and 1) implies that we can look at this as if there were no shift for the purpose of type-checking).

It turns out that there is precedence in the implementation of `make`. Regarding its size arguments the spec says:

3) "The size arguments n and m must be of integer type or untyped. A constant size argument must be non-negative and representable by a value of type int." (https://tip.golang.org/ref/spec#Making_slices_maps_and_channels).

This rule 3) for size arguments is exactly the same as 2) for indices (which makes sense since the size is the upper limit for an index).

In this case, the compiler *does* permit the shift (https://play.golang.org/p/fs_w8BH_YR):
```
var s uint
_ = make([]int, 1.0<<s)
```
go/types agrees as well.

We should expect that `1.0 << a` is either accepted or not accepted in both cases for consistency. We cannot change the behavior of `make` as it might invalidate existing code (highly unlikely but possible). Thus we should allow the slice operation in question as well.

**Comment by griesemer** [comment]
Here's another intuitive argument in favor of making the advocated behavior valid. If one were to provide an indexing operator (a method) for a user-defined type one might declare:
```
type A struct {...}  // some user-defined indexable data structure with elements of type T
func (a A) At(index int) T {...}  // returns a[index]
```
In this case `a.At(1.0 << s)` is permitted. It should also be for `a[1.0 << s]`.

**Comment by rsc** [comment]
I'm OK with changing this behavior. Note that if s is a constant then the compilers already accept [1.0<<s]int as a valid type and also accept h[1.0<<s] as a valid index operation. It's only the non-constant s case that is being rejected.
