### ISSUE TITLE
all.bash fails with -newexport

### ISSUE THREAD

**Issue by tzneal** [golang/go#14877]
1. What version of Go are you using (`go version`)?

go version devel +3dd4f74e060b Fri Mar 18 23:08:24 2016 +0000 linux/amd64

I discovered this while testing [CL 20773](https://go-review.googlesource.com/20773) which has since been merged.  This is the revision before it was submitted.

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?

GO_GCFLAGS=-newexport ./all.bash

4. What did you expect to see?

Successful build and test.

5. What did you see instead?

```
# sync_test
sync/cond_test.go:10: method redeclared: sync.Mutex.Lock
        method(*sync.Mutex) func()
        method(*sync.Mutex) func()
-- cut --

##### ../misc/cgo/testgodefs
skipped due to earlier error
2016/03/19 05:02:51 FAILED
```

**Comment by mdempsky** [comment]
This appears to be due to CL 20602 (b2b5e779). :/

**Comment by mdempsky** [comment]
The regression was caused because in b2b5e77, I didn't correctly preserve the Eqtype semantics needed in addmethod.  In particular, Eqtype for functions ignores the parameter names, but because I added the check to compare the entire receiver parameter tuple as a struct, that means suddenly the receiver parameter name did matter.

More over, GO_GCFLAGS=-newexport only influences how the standard library is built.  The failing sync_test test is actually being built without the -newexport flag.  Specifically, the installed copy of package testing has binary export data for `sync.Mutex`.  But then because sync/export_test.go adds code to package sync, it's being recompiled with the non-binary export data.

The problem then arises because the binary export data format is exporting short hand parameter names (e.g., just `m`), but the text format uses the long hand names (e.g., `sync.m·1`).  These are separate identifiers, so they cause the receiver parameter list struct comparison to fail.

I have a fix for the regression at least.  Not sure how/if to handle the second part.  It'll be a non-issue once we switch to the new export format,  so maybe not worth worrying about.
