### ISSUE TITLE
x/image/font: provide access to font height and ascent.

### ISSUE THREAD

**Issue by eaburns** [golang/go#14885]
There is no way to access the height and ascent metrics of a font with x/image/font. The per-glyph bounds are available, but the global height and ascent are needed to properly space lines.

1. What version of Go are you using (`go version`)?

```
$ go version
go version go1.6 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOOS="linux"
[…]
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Read the godoc x/image/font.

4. What did you expect to see?

A way to access the font's height and ascent metrics.

5. What did you see instead?

It's possible to get the metrics for individual glyphs, but fonts typically have a global height and ascent that can be used for spacing lines. These aren't available.

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
Yes, that's the "TODO: per-font Metrics" in x/image/font/font.go. See also issue #14436.

As for a specific API, it's probably be something like:

Face.Metrics() Metrics
and
type Metrics struct{ etc }

instead of

Face.VerticalMetrics() (height, ascent fixed.Int26_6)

in case we want to add other Metrics fields in the future (e.g. descent). But I haven't given this a lot of thought yet.

**Comment by eaburns** [comment]
Perfect. Mind if I send you a CL?

**Comment by nigeltao** [comment]
Go for it. My instincts would be to say

type Metrics struct {
  Height fixed.Int26_6
  Ascent fixed.Int26_6
  Descent fixed.Int26_6 // Usually positive, not negative.
}

(plus comments, of course) so that, for TTFs, Height = Ascent + Descent + LineGap. But I'm open to discussing other ideas (e.g. inspired by what Win / Mac / Linux APIs offer). We can do that on the CL.

**Comment by nigeltao** [comment]
CC @josharian @stephenwithav.
