### ISSUE TITLE
time:timer stop panic 

### ISSUE THREAD

**Issue by koggle** [golang/go#14946]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
https://play.golang.org/

`package main

import "time"
import "fmt"

func main() {
	timer1 := time.NewTimer(time.Second * 2)
	<-timer1.C

	fmt.Println("Timer 1 expired")
	timer2 := time.NewTimer(time.Second)
	go func() {
		stop2 := timer2.Stop()
		if stop2 {
			fmt.Println("Timer 2 stopped")

		}

	}()
	<-timer2.C
	fmt.Println("Timer 2 expired")
	time.Sleep(time.Second * 5)
}`

`Timer 1 expired
Timer 2 stopped
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
	/tmp/sandbox826749351/main.go:20 +0x1e0

Program exited.`

example：
https://gobyexample.com/timers

**Comment by ianlancetaylor** [comment]
You stopped the timer, and then your main goroutine is sitting there waiting for a value that will never come, because the timer has been stopped.  I don't see a bug here.

If you have questions about how this works, please don't use the issue tracker.  Please see https://golang.org/wiki/Questions .  Thanks.

**Comment by koggle** [comment]
This command has been run, what the thread is still waiting

fmt.Println("Timer 2 expired")

**Comment by ianlancetaylor** [comment]
See previous comment: this is not the place for questions.  Thanks.

As I said, the thread is waiting for a value that will never be sent.  The program is deadlocked.
