### ISSUE TITLE
x/build/cmd/gopherbot: include CL name in CL notification comments on issues

### ISSUE THREAD

**Issue by minux** [golang/go#14954]
The notification issue comment gopherbot add for each CL only
include the CL URL, but for certain issues (like #6853), it's of
not much use because there are so many CLs mentioning the
issue, without the issue title included, the comments are not
that useful.

**Comment by digitalbytes** [comment]
I looked into this issue because it seemed like a simple place for me to start contributing. After reviewing the code it appears that it may be implemented in https://go-review.googlesource.com/c/51116. 

An example of it in the wild can be seen in gopherbot's last comment in this issue: https://github.com/golang/go/issues/21392

**Comment by josharian** [comment]
Indeed; I didn't know an issue existed for this when I implemented CL 51116. Thanks for discovering this—you've contributed now. :)

Happy hunting for your next issue.
