### ISSUE TITLE
runtime: assignment to nil map panics with string, not Error type

### ISSUE THREAD

**Issue by alexhornbake** [golang/go#14965]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
$ go version
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
Assignment to a nil map.
http://play.golang.org/p/ES8UfghkFv

4. What did you expect to see?
assignment to nil map should panic with type Error as specified here:
https://golang.org/ref/spec#Run_time_panics

5. What did you see instead?
assignment to nil map panics with type String

**Comment by ianlancetaylor** [comment]
There are cases like this in chan.go and select.go also, and perhaps error.go as well.  In general any panic("string") in non-test code in the runtime is suspect, except for cases like panic("not reached").

**Comment by odeke-em** [comment]
The only tricky thing though is that since importing errors or even fmt would result in circular imports and fail, using runtime's errorString is the way to go. However errorString's Error() method prefixes `runtime error: ` before every message.
This will mean that the panics that will now be fixed e.g originally "assignment to entry in nil map" will now be "runtime error: assignment to entry in nil map". If this is deemed as not a compatibility problem, since this code has been in the stdlib for a while since July 2014
<img width="748" alt="screen shot 2016-03-27 at 2 45 17 pm" src="https://cloud.githubusercontent.com/assets/4898263/14068004/c98854bc-f42a-11e5-819a-e871a6a8d8ee.png">


I can spin up a CL to fix this.

**Comment by minux** [comment]
we can define a new string type that implements
error in runtime for those cases.

**Comment by davecheney** [comment]
Should some of these be throw cases, not panic cases? I think most of these
are not recoverable.

**Comment by odeke-em** [comment]
@minux we already have errorString
<img width="643" alt="screen shot 2016-03-27 at 5 16 41 pm" src="https://cloud.githubusercontent.com/assets/4898263/14068674/bbfb6900-f43f-11e5-893f-54c23ec43c29.png">
If we defined a new string type for just these cases, it might look out of place and moreover there are already usages of errorString in runtime so that might look confusing when the only difference between the two different error strings' Error() results is the prefix "runtime: ".

@davecheney  IMO I think we could do this in a separate issue as that changes the behavior as opposed to first fixing this issue and conforming to the docs that say panics from the runtime should be with Error's as defined here https://golang.org/ref/spec#Run_time_panics.

**Comment by minux** [comment]
what's your proposal?

I don't want to change any existing outside-visible behavior,
except making those panic implements runtime.Error.

**Comment by odeke-em** [comment]
@minux thanks. In this case, we have no other option then but to define a new string type.
I just wanted to get clarification that we were on the same page.
