### ISSUE TITLE
tour: 'A nil slice has a length and capacity of 0.' is not always true

### ISSUE THREAD

**Issue by gefarion** [golang/go#14978]
Context: https://tour.golang.org/moretypes/11
The description says: 'A nil slice has a length and capacity of 0.'
But if i change the code a little the sentence is not true:

	var s = make ([]int, 0)
	fmt.Println(s, len(s), cap(s))
	if s == nil {
		fmt.Println("nil!")
	}

only prints:
[] 0 0

Beacause 's == nil' return false!!!

**Comment by OneOfOne** [comment]
That is not a nil slice, a nil slice would be `var s []int`.

**Comment by bradfitz** [comment]
A nil slice means that it has length and capacity 0, but the reverse is not necessarily true: just because it has length and capacity 0 does not imply that it's nil. It's possible to have both nil and non-nil slices of length/capacity 0.

Let's move any further discussion to a forum. See https://golang.org/wiki/Questions
