### ISSUE TITLE
time: ParseDuration fails for large strings

### ISSUE THREAD

**Issue by siritinga** [golang/go#15011]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go 1.6

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu x64 but it fails on play.golang.org too.

3. What did you do?
I ran http://play.golang.org/p/N0A7ph_xkj which contains a large string (not really that large) to be parsed. 

4. What did you expect to see?
Duration parsed with no errors. It works if you remove the last number of duration. 

5. What did you see instead?
2009/11/10 23:00:00 time: invalid duration 0.12345678912345678912h

**Comment by martisch** [comment]
From what i remember when changing ParseDuration it does not use infinite precision math: 
Everything after the . is read in as an int64 and then scaled to get a duration in nanoseconds.
"12345678912345678912" overflows int64 but "1234567891234567891" as int64 does not. 
Whether it is 0.12345678912345678912 or 0.1234567891234567891 is used does not seem to make a difference for the duration as both would at the end result in the same duration, 444444440844 nanoseconds. So in principle one could parse more digits only to discard them since they have no affect on the final duration in nanoseconds. Not sure if that would be preferred since it gives a false sense of how accurate the duration really is.

**Comment by siritinga** [comment]
Hi, thanks for checking this.

I understand that there is no benefit in using so many digits. I found the issue because I was parsing the duration as I got it from somewhere else and this string came.

However, it seems that this case also fails, but it is a valid time inside precision (59 seconds and one nanosecond, expressed in hours): http://play.golang.org/p/wGcCA18oxU. If you start removing the last 6, you get 59s, not 59s1ns.
