### ISSUE TITLE
cmd/compile: <N> in byte conversion error message

### ISSUE THREAD

**Issue by josharian** [golang/go#15055]
Try to compile `_ = []byte("abc", "def")`.

http://play.golang.org/p/b8yffUjLNq

Result:

`too many arguments to conversion to []byte: ([]byte)(<N>)`

That error message is unhelpful; it looks like we have an unexpectedly nil Node.

**Comment by odeke-em** [comment]
@josharian I don't think this bug only happens for []byte, I think it happens for all "collections"/arrays/slices so []<T> ie []string, []int, []struct. Please see https://play.golang.org/p/c2vPXbl0Ew
or inlined
```go
package main

func main() {
	_ = []int(12, "123", "485")
	_ = []byte("a", "cd")
	_ = []string("af", "be")

	// Ones that pass
	_ = int(15, "a")
	_ = string("n", "e", "w")
	_ = byte("info", "a$ap")
}
```

when run or compiled gives error 
```shell
prog.go:4: too many arguments to conversion to []int: ([]int)(<N>)
prog.go:5: too many arguments to conversion to []byte: ([]byte)(<N>)
prog.go:6: too many arguments to conversion to []string: ([]string)(<N>)
prog.go:9: too many arguments to conversion to int: int(15, "a")
prog.go:10: too many arguments to conversion to string: string("n", "e", "w")
prog.go:11: too many arguments to conversion to byte: byte("info", "a$ap")
```
Notice that the obscure error message only happens when we have `[]<Type>`

**Comment by odeke-em** [comment]
I've mailed https://go-review.googlesource.com/25361.
