### ISSUE TITLE
database/sql: add Context support

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15123]
This bug is about adding Context support the `database/sql` package.

Parent bug is #14660

**Comment by bradfitz** [comment]
@pbnjay wrote on the parent bug:

> I'm a bit late to the discussion, but would it make more sense to add a Context to sql.Tx instead of the Query args? Automatic rollback on cancellation would be desirable, no? Alternative, maybe less desirable version would be a method like BeginWithContext(ctx)

"instead of"? Remember you can also query outside of transactions.

**Comment by cihangir** [comment]
I started implementing this a while back ago with having context as the first parameter to all the api functions. Apart from SetMaxIdleConns  and SetMaxOpenConns all functionality implemented. Given the fact that my implementation breaks the whole api, implementation is purely done in a third party manner (without touching to std lib code)

For the ref, you can find the docs here https://godoc.org/github.com/cihangir/ctxdb

I would like to help on the implementation if need.


-- 

> Automatic rollback on cancellation would be desirable, no?

I tried to achieve this by closing the connection to the [database](https://github.com/cihangir/ctxdb/blob/ca4e0c809743fbc4f3ee5ef2c769ea166d9480ac/ctxdb.go#L336) Some of the database vendors handle it properly, but i am not sure if it is a general solution.

**Comment by pbnjay** [comment]
You can query outside of transactions, but I think combining a user-space context with the database transaction (even for a single-query transaction) is troublesome. If you run an UPDATE but your context times out, user space indicates a cancellation/error, but the database may complete the request successfully. Sure this would be a user error, but ensuring that all Context usage occurs within a transaction allows for consistent results.

Surely I'm missing something?

**Comment by extemporalgenome** [comment]
I like the idea of having tying contexts into Tx -- even if we have to add a way to "begin" a fake transaction, or create an interface that `*sql.Tx` will be made to implement, and which is additionally consumed for non-transactional database contexts.

With the "magic first argument" behavior, there are too many open questions. What happens if a user passes in a first argument that implements both `driver.Value` _and_ `context.Context`? There is already also the open question about whether it should be the first or last value, and users will have the same question (and make mistakes which may pass silently, depending on how much validation the driver does). The only way to find out if a context with a 5 minute deadline is actually being used for query aborts is to construct a query that takes 5 minutes.

Also, users may infer that multiple contexts may be passed in (whichever is cancelled first), or have subtle bugs that didn't occur before but can occur now, such as sorting the parameter `[]interface{}` for a generated "IN" query, say for debugging clarity, in a wrapper in front of Query/Exec.

I don't think we need a parallel API, but we can shift the proposal to a couple new methods that flow into the existing API (and don't sacrifice type-safety).

**Comment by ymmt2005** [comment]
FWIW, I have just implemented a context-oriented query canceler for MySQL.

Not only in Go, but MySQL server should also be able to cancel running queries
to avoid wasting CPU and memory resources.  In my implementation, I used two
techniques:

1. (for MySQL < 5.7.8) [KILL](https://dev.mysql.com/doc/refman/5.6/en/kill.html) by another connection.
2. (for MySQL >= 5.7.8) [SET max_execution_time](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_execution_time).

From this experience, I'm not sure whether it is good or not that database drivers
implicitly executes this kind of queries with side effects for native support of contexts.

The code is here for your reference:
https://github.com/cybozu-go/goma/blob/ac585a21752104d5ce69601c310eed753bf8f135/probes/mysql/probe.go#L27

**Comment by pbnjay** [comment]
This one may need `sql/driver` support to function, I did some testing here with Postgres and the query keeps running even if you kill the code entirely with ctrl-C :

https://gist.github.com/pbnjay/96f829f8aa77d7ae1d88bca094e5d6ec

Since @ymmt2005 also mentioned mysql-specific commands, it leads me to think it can't be done from the current generic interface.

**Comment by j7b** [comment]
Context support isn't a good fit for database/sql, there's no portable way to add deadlines or cancellation signals, I'd prefer to see a separate package like database/context that wraps *database.DB methods with checks to see if Done() is closed for a passed context and adds appropriate errors.

**Comment by johto** [comment]
> If you run an UPDATE but your context times out, user space indicates a cancellation/error, but the database may complete the request successfully. Sure this would be a user error, but ensuring that all Context usage occurs within a transaction allows for consistent results.

With explicit transactions you're merely moving this problem from the UPDATE to the COMMIT command, not eliminating it.

**Comment by derekperkins** [comment]
> This one may need sql/driver support to function

Seems very likely.

**Comment by kardianos** [comment]
@bradfitz 

Context is a great fit for sql. Almost all rdbms have a query cancel method and all databases need to ensure their connections are returned to the pool when the request is finished.

One option I could see is in sql.DB add a `Ctx(context.Context) *sql.DB` method who'd methods use a context under the covers.

In the driver you might need new interfaces that could be tested for, such as
```
type ConnCtx interface {
        PrepareCtx(ctx context.Context, query string) (sql.Stmt, error)
        CloseCtx(ctx context.Context) error
        BeginCtx(ctx context.Context) (sql.Tx, error)
}
type DriverCtx interface {
        OpenCtx(ctx context.Context, name string) (Conn, error)
}
type ExecerCtx interface {
        ExecCtx(ctx context.Context, query string, args []Value) (Result, error)
}
type QueryerCtx interface {
        QueryCtx(ctx context.Context, query string, args []Value) (Rows, error)
}
type StmtCtx interface {
        CloseCtx(ctx context.Context) error
        ExecCtx(ctx context.Context, args []Value) (Result, error)
        QueryCtx(ctx context.Context, args []Value) (Rows, error)
}
type TxCtx interface {
        CommitCtx(ctx context.Context) error
        RollbackCtx(ctx context.Context) error
}
```

Does that sound about right?

**Comment by kardianos** [comment]
@bradfitz 
> One option I could see is in sql.DB add a Ctx(context.Context) *sql.DB method who'd methods use a context under the covers.

I hope to start designing some CLs for testing. What do you think of adding a Ctx method to *sql.DB which returns a *sql.DB, but allows any queries from the returned DB to use the context. This would be done per request obviously. I want to make sure I'm not barking up the wrong tree on this.

**Comment by quentinmit** [comment]
I think we have a convention of calling such a method `WithContext`. If you do this for queries, how do you propose applying a context to the process of connecting to the database? Would you just not use a context for that?

**Comment by kardianos** [comment]
@quentinmit I think with a connection pool, you may specify a connection timeout in the DSN. You then pass a context to the context pool with a timeout for acquiring the connection.

You are correct about the method name. Agree it should be spelled `*sql.DB.WithContext(context.Context) *sql.DB`..

**Comment by kardianos** [comment]
I haven't used context everywhere it needs to be used, but the API and basic plumbing is present.
https://go-review.googlesource.com/28532

Feedback on the approach welcome.

**Comment by bradfitz** [comment]
@kardianos, remove the "DO NOT REVIEW" label from your CL if you want a review.

**Comment by bradfitz** [comment]
@kardianos and I discussed this today. He's going to write up a summary of our discussion here.

**Comment by kardianos** [comment]
Current design adds the following methods to the `database/sql` package.
```
func (*DB) BeginLevel(ctx context.Context, level IsoLevel) (*Tx, error)
func (*DB) ExecContext(ctx context.Context, query string, args ...interface{}) (Result, error)
func (*DB) QueryContext(ctx context.Context, query string, args ...interface{}) (*Rows, error)
func (*DB) QueryRowContext(ctx context.Context, query string, args ...inerface{}) *Row

func (*Stmt) ExecContext(ctx context.Context, args ...interface{}) (Result, error)
func (*Stmt) QueryContext(ctx context.Context, args ...interface{}) (*Rows, error)
func (*Stmt) QueryRow(ctx context.Context, args ...interface{}) (*Row)

func (*Tx) ExecContext(ctx context.Context, query string, args ...interface{}) (Result, error)
func (*Tx) QueryContext(ctx context.Context, query string, args ...interface{}) (*Rows, error)
func (*Tx) QueryRowContext(ctx context.Context, query string, args ...interface{}) *Row
func (*Tx) StmtContext(ctx context.Context, stmt *Stmt) *Stmt
```

The goal is to drive a middle ground between having a context on every Rows method, but not on what is designed to be globals such as *DB or *Stmt nor store context in what looks like a *DB. The context parameter is designed to signal the driver to close the connection (cancelling the query if the driver supports it) and return the connection to the database pool at the end of the request.

**Comment by ymmt2005** [comment]
Off topic, but this new API catches my attention:
>func (*DB) BeginLevel(ctx context.Context, level IsoLevel) (*Tx, error)

It would be better if we can also pass a flag to turn the transaction read-only.
Some databases can prohibit (and optimize) a transaction from modifying data.
For instance, MySQL can do it by `START TRANSACTION READ ONLY` statement.

Any chance can BeginLevel takes the third parameter as `readonly bool`?

**Comment by kardianos** [comment]
@ymmt2005 Thank you for pointing that out. I've done a rough survey of systems that support this. I'll need to do a more in depth survey before having an opinion, but so far I'm in favor of doing something for  that.

**Comment by noblehng** [comment]
Two concerns:

- Would a context for a whole transaction be engouh? What are the use cases for having separated contexts for each operations inside a transaction? And I don't think cancellation works for `commit` and `rollback`.

- Leaving operation in-flight after cancelling may corrupt data for non-idempotent operations.

**Comment by freeformz** [comment]
Instead of the new methods on *Stmt and *Transaction, why not add a `PrepareWithContext(ctx context.Context, query string) (*Stmt, error)` and BeginWithContext(ctx context.Context) (*Tx, error)` to *DB? Internally those would set a `Context context.Context` field and if that's != nil then it would be used in the right places. It's strange to me (not sure why) that I would/could inject different contexts at different points for both prepared statements and transactions. I'm sure I'm just missing something?

**Comment by kardianos** [comment]
@noblehng The methods on Tx are mainly for symmetry with the other methods. Cancelation works for Tx, if you define it to trigger Rollback. The in-flight argument could be true for any persistent server operation that gains a cancellation method. However, if you define what you care about in a Tx, then it will get rolled back properly. Non-Tx statements that might time out would be long selects often. So if you misuse the database, yes, context won't help you.

**Comment by kardianos** [comment]
@freeformz Brad wants the design of *DB and *Stmt to be global, so no context defined on those (exception is Stmt from Tx, which isn't global). I don't think you're missing anything, there's lots of places to inject context. If I'm missing what you're saying drop me an email/slack, I'd like to ensure I'm not missing anything.

**Comment by freeformz** [comment]
Discussed with @kardianos in slack, during which he clarified the meaning of *global*, so this now makes sense. (s/global/so that instances of these types can be reused again and again with different contexts).

**Comment by noblehng** [comment]
@kardianos 

- I can see one might do a rollback after a timed out `commit` , but what to do with a timeout when doing `rollback`? Cancel the rollback then close the connection to let the database start the rollback again? I'm talking about the `TxContext` interface.

- It still seems racy if you return early and let the operation in-flight for drivers that doesn't support cancellation. You can insert the rollback after the operation, but you need to first check whether it had been canceled, that check could happen after the concurrent set. Or you need to close the physical connection and let the database handle the auto rollback. And for `Commit()` that can't be cancel, you still have to wait.

**Comment by bradfitz** [comment]
Yeah, Rollback probably shouldn't take a context.

**Comment by noblehng** [comment]
About transaction isolation level, almost all database could set it and the access mode after the transaction begin with a `SET TRANSACTION ...` statement, so a *Tx.Exec() could already do that.

If it would be set when start a tranction, the signature should like `func (*DB) BeginLevel(ctx context.Context, flags uint32) (*Tx, error)`, and the meaning of the flags should be driver defined.

The reason is that different databases could have different flags or different value for a same meaning flag. And most importantly, different databases or even different database versions have different meaning for a same isolation level name. For example, Oracle's serializable is just snapshot isolation, which is repeatable read in current PostgreSQL, and which in turn is stricter than repeatable read defined by SQL-92 but still not true serializable.

**Comment by kardianos** [comment]
@noblehng Wire protocols often support setting the transaction level in the protocol itself. Like types the ISO standard defines a set number of types. Unlike types, databases rarely deviate from that list.

I agree that different database implementations will give slightly different meaning to different iso levels. However here are the levels I would define:
```
type Isolation byte
const (
    IsoDefault Isolation = iota * 2
    IsoReadUncommited
    IsoReadCommited
    IsoWriteCommited
    IsoRepeatableRead
    IsoSerializable
    IsoSnapshot
    IsoLinearizable
)

const IsoReadOnly Isolation = 1
```
If you can't fit your isolation level into one of those logical levels, it probably isn't a transactional database. There are implementation differences, but there are only so many logical ways to read and write data concurrently.

For example, in some database drivers, `IsoSerializable` and IsoSnapshot` could mean the same level and IsoLinearizable would return `errIsoNotSupported` and that's okay to me.

**Comment by noblehng** [comment]
@kardianos In wire protocol when start a transaction, isolation level and access mode can just pass by using the `flags uint32` argument. Database can support vendor defined flags other than isolation level and access mode, this will cover that.

For users using the database, they probably just want to use isolation level name defined by their vendor, and don't want to map it to what others mean. Note that even ISO standard is not consistent. I'm not saying this is the best way to use a database, but that is what happen if the developer just read the vendor  docs.

**Comment by kardianos** [comment]
@noblehng Can you give examples of DB Servers which has different names then ISO?

**Comment by noblehng** [comment]
I had give a sample above. Oracle's serializable is just snapshot isolation because ANSI/ISO SQL-92's definition of serializable is unconsistent. You can see snapshot isolation is not true serializable [here](https://en.wikipedia.org/wiki/Snapshot_isolation). Old versions of PostgreSQL use similar definition as Oracle, but it rename it to repeatable read and provide serializable snapshot isolation now as serializable which is true serializable. I think old versions of MySQL are also unconsistent.

**Comment by kardianos** [comment]
@noblehng I'm aware of what ISO defines is only 4 levels. But you didn't give an example of a *different* iso level, just that a particular existing isolation level may have different meaning. It think that is where we differ in opinion. Is it okay to have different database system take the same const when they might be implemented differently have have different properties?

**Comment by derekperkins** [comment]
What about defining an interface for drivers to define supported transaction levels?

**Comment by kardianos** [comment]
@derekparker I don't understand what you mean by that. Could you give an example?

**Comment by noblehng** [comment]
@kardianos You can provide some predefined flags in the stdlib, I have no objection to that, but you will also need to add a big warning in its documentation. Database driver specific flags can also coexist with stdlib predefined flags. Use a `flags uint32` to `BeginContext` supports both.

**Comment by kardianos** [comment]
@noblehng Can you give me an example of a name of a transaction level that is not represented in the list above? Your previous examples have listed different behavior between different servers on the same iso level name, but you have not given a different iso level that is on the list.

**Comment by noblehng** [comment]
@kardianos Your list for transaction isolation level is enough, except I will put IsoSnapshot before IsoSerializable. But you can have other vendor specific flags that can be passed to when starting a transaction, For example, Oracle has some flags to specify rollback segment for a transaction, and I don't think that is universal across vendor, you can see that [here](https://docs.oracle.com/database/121/SQLRF/statements_10005.htm).

**Comment by kardianos** [comment]
@noblehng Thank you for the pointers to the docs. While not exactly the same, another, separate issue is to support `Tx.Savepoint(name string)` and `Tx.RolebackTo(name string)`. The API at large doesn't support resuming transactions at present. I don't know what a Loosely coupled branch or tightly coupled branch is, nor do I know what a separable transaction is.

I'm open to having an API like:
```
type TxFlag interface{
    TxFlagValue() interface{}
}

type Isolation byte
func (i Isolation) TxFlagValue() interface{} {
    return i
}

const (
    IsoDefault Isolation = iota * 2
    IsoReadUncommited
    IsoReadCommited
    IsoWriteCommited
    IsoRepeatableRead
    IsoSerializable
    IsoSnapshot
    IsoLinearizable
)

type TxAccessMode byte

const ReadOnly TxAccessMode

func (m TxAccessMode) TxFlagValue() interface{} {
    return m
}

func (db *DB) BeginLevel(ctx context.Context, flags ...TxFlag) (*Tx, error)
```
 
That way the driver has the option to define additional flags, and the flags could contain data for the something like the Oracle `USE ROLLBACK SEGMENT <name>`, where `<name>` would be the value in the interface.
```
package oracle

type TxRollback string
func (r TxRollback) TxFlagValue() interface{}
    return string(r)
}
```

Used like:
```
db.BeginLevel(ctx, sql.IsoSerializable, oracle.TxRollback("DANCING_CATS"))
```

I would be interested to hear what you and @bradfitz think of that.

**Comment by derekperkins** [comment]
@kardianos Your example is basically what I was suggesting.

**Comment by noblehng** [comment]
@kardianos I think using a interface is overkill. For vendor specific settings, you will need to import the driver expicitly (not just register with a '_') anyway. So for more complex transaction settings, driver could provide helper functions like: `func SetTxXXX(tx *sql.Tx)`, which just call `tx.Exec("SET TRANSACTION ...")` under the hood. It is just that if you are adding a flag like argument to `BeginContext()` to support isolation level and access mode etc, we could make it a little more generic by making it a `flags uint32`, which could both use with stblib defined or driver specific flags without much overhead.

And I still want to ask the reason to put `IsoSnapshot` behind `IsoSerializable`. MSSQL's wire protocol MS-TDS seems to use the same ordering. But I think that is just because `Snapshot` for them is added after, so they can't change the ordering for backward compatibility.

Also the encoding of the Isolation constants could be more efficiently, as different isolation levels can't be used together.

**Comment by kardianos** [comment]
@noblehng I heard you express the user requirement "as a user, I want to enable usage such as Oracle's USE ROLLBACK SEGMENT <name>".  I then see you are pushing the technical solution to have transactions be a uint32 flag set. Because the use rollback needs a <name>, I don't see how your proposed technical solution satisfies your previous user requirement.

**Comment by noblehng** [comment]
@kardianos I said that above, it can be done with a `func SetTxXXX(tx *sql.Tx) error` in driver. Because this is too driver specific, no need to specially support that in the stdlib. I want the constants to be extendable because there is already a uint32 or byte like argument in your proposal, better make it more extendable. It is more about api design than just user requirement.

For predefined constants, it could be like:
```go
const (
    DefaultTx iota

    // isolation level, 3bits
    ReadUncommitedTx
    ReadCommitedTx
    WriteCommitedTx
    RepeatableReadTx
    SnapshotTx
    SerializableTx
    LinearizableTx

    // access mode, 2bits
    ReadOnlyTx    0x1000
    WriteOnlyTx   0x10000
    ReadWrite     0x11000

    // remaining bits are for custom driver defined flags
)
```

**Comment by andlabs** [comment]
If you don't mind me asking: when I first read the context package docs, I assumed I would do something like this to have per-request database transactions associated with per-request contexts:

```
func (h *MyHTTPHandler) Handle(w http.RequestWriter, r *http.Request) {
    ctx := context.Background()
    tx, err := globalDBConn.Begin()
    if err != nil { /* report error and return */ }
    ctx = context.WithValue(ctx, "tx", tx)
    err = h.realHandle(ctx, w, r)
    if err != nil { tx.Rollback(); /* report error */ }
    err = tx.Commit(); // and so on
}
```

Am I wrong about this, given all these new methods? I admittedly don't quite get what a context *should* store, apart from the general "request-scoped values".

**Comment by derekperkins** [comment]
This doesn't change anything about where you keep your database or your transaction variables (which should not be in the context).

Where this adds value is to allow for cancelation of queries and transactions for whatever purpose, plus adding some ability for extra tooling like traces, logs, etc.

**Comment by kardianos** [comment]
context does store values and that can be useful at times. But context is mostly about limiting the life span of requests in a consistent manner. Cancellation and timeout. This might be worthy of a blog post, but here is how you might use context here:
```
var db *sql.DB
func InitialProgramSetup() error {
    var err error
    db, err = sql.Open("pg", "connect-to-server")
    return err
}
func (h *MyHTTPHandler) ServeHTTP(w http.RequestWriter, r *http.Request) {
    // r.Context() will automatically cancel when this request is done.
    // TODO: use trace package to inject UUID to context used for tracing execution.
    ctx, cancel := context.WithTimeout(r.Context(), time.Second * 1)
    defer cancel() // Not needed, the r.Context() will cancel when the request is done already.
    r = r.WithContext(ctx)

    switch r.URL.Path {
    default:
        http.Error(w, "not found", 404)
    case "/d/user":
        h.dataUser(w, r)
    }
}

func (h *MyHTTPHandler) dataUser(w http.RequestWriter, r *http.Request) {
    tx, err := db.BeginContext(r.Context())
    if err != nil {...}
    // The following would timeout and and the Tx would rollback any changes.
    // The err would be "context.DeadlineExceeded".
    // Drivers can also tie into this to cancel the query on the server to prevent the
    // server from consuming additional resources.
    row, err :=  tx.QueryRow(r.Context(), "sleep 99999; select * from user where ID = ?;", 42)
    if err != nil {...}
    tx.Commit()
}
```

**Comment by andlabs** [comment]
Good to know; thanks!

**Comment by bradfitz** [comment]
@kardianos wrote a doc summarizing what's new for `database/sql` in Go 1.8:

https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit
