### ISSUE TITLE
cmd/gofmt: doesn't simplify slices if there is a dot import

### ISSUE THREAD

**Issue by dominikh** [golang/go#15153]
Please answer these questions before submitting your issue. Thanks!

What version of Go are you using (go version)?
go version go1.6 linux/amd64

What operating system and processor architecture are you using (go env)?
/

What did you do?
Run gofmt -s on http://play.golang.org/p/9NhvjR24S1

What did you expect to see?
I expected s[:len(s)] to be simplified to s{;}

What did you see instead?
It wasn't simplified.

gofmt has a special check for dot imports and refuses to simplify slices in that case, claiming that it's impossible to know whether len is referring to the built-in function or not. I don't see how that could be true. Even a dot import will only pull in exported identifiers from a package, and no exported identifier can be called "len". Am I missing something here?

**Comment by griesemer** [comment]
@dominikh You're absolutely correct. In fact, even w/o the dot-import we actually can't be certain whether `len` is the builtin `len` since it might be declared in another file of the package, and gofmt is by design only working on a file-by-file basis and thus cannot type-check the package and resolve an identifier for certain.

So in some sense this was always wrong, but in practice, nobody in his/her right mind is going to declare a `len` function (as opposed to a `len` method which might be quite common).

I'm not sure how I got to this code - for sure it's pretty old code. Would need to track down the history of that line to figure it out. Let's blame it on lack of coffee. Fix coming shortly.

**Comment by dominikh** [comment]
Great, thanks.

P.S.: Anyone know where the description of the issue went? It certainly wasn't empty earlier :-)

**Comment by griesemer** [comment]
@dominikh No idea what happened here - I certainly didn't touch it. Hmm...

**Comment by dominikh** [comment]
I've restored the description… let's hope GitHub doesn't eat it again.

**Comment by martisch** [comment]
btw origin of the code:
https://github.com/golang/go/commit/0cbca268d8aba5d7ffb24be58ea1ea92fcd5f6f5
