### ISSUE TITLE
tour: provide instructions for those who built the tour from source too

### ISSUE THREAD

**Issue by juliaferraioli** [golang/go#15183]
Context: https://tour.golang.org/welcome/3

My understanding from @campoy is that the recommended way to run the tour locally is by executing:

``$GOPATH/bin/gotour``

after getting the tour if necessary:

``go get golang.org/x/tour/gotour``

If that's the case, than the instructions on this page should be updated to reflect the recommendation.

**Comment by adg** [comment]
That was the recommendation once, but we changed it to recommend the version of the tour that comes with the Go installation.

A major benefit of this approach is that the user doesn't need to have `GOPATH` set up to run the tour.

The notable drawback is that—if the tour has changed since the last release—the local version will be out of sync with the web version. I don't think this is a big deal.

@campoy, what do you think?

**Comment by campoy** [comment]
I'd be ok with the `go tool tour` if it worked, but as @juliaferraioli it appears that after installing go, running that command fails with the error `go tool: no such tool "tour"`

On my machine it also fails, I'm assuming because I installed go from source.

**Comment by adg** [comment]
@juliaferraioli did you also install the tour from source?

**Comment by adg** [comment]
Maybe we should link to a wiki page that explains both approaches?

**Comment by juliaferraioli** [comment]
@adg Yep. A wiki would be a good compromise.

**Comment by adg** [comment]
Moving this to golang/tour#8
