### ISSUE TITLE
x/sys/unix: unix.SysctlUint64 fails on 32-bit FreeBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15186]
The freebsd-386 builder has been failing on this x/sys/unix test for some time now:

https://storage.googleapis.com/go-build-log/68ac1f77/freebsd-386-gce101_03efe3a9.log

```
freebsd-386-gce101 at 68ac1f774624faf99e7f6ec6592acb50f23b7874 building sys at 4c24bcbb85d58313623349380489486f9b3934ec

?       golang.org/x/sys/plan9  [no test files]
--- FAIL: TestSysctUint64 (0.00s)
    syscall_freebsd_test.go:18: input/output error
FAIL
FAIL    golang.org/x/sys/unix   0.006s


Error: tests failed: exit status 1
```

/cc @adg @mikioh @minux

**Comment by mikioh** [comment]
EIO usually indicates an error of "size mismatched" or "unaligned access" to the kernel. I'm not sure why the test uses vm.max_kernel_address. Because vm usually consists of ton of machine-dependent stuff. Also freebsd-386-gce101 is actually a complicated "freebsd-386 on freebsd-amd64" host. It depends on the implementation whether the value is returned from 32-bit kernel part or 64-bit kernel part. It's would be better to use more appropriate syscall entry in testing.

Also s/TestSysctUint64/TestSysctlUint64

**Comment by bradfitz** [comment]
`vm.max_kernel_address` doesn't look like it matters. It's an arbitrary sysctl name. The test doesn't even look at the value.

**Comment by mikioh** [comment]
I guess vm.max_kernel_address is a read-only value inside the kernel, hm, am I missing something?
```
vm/kern_vm.c:

SYSCTL_ULONG(_vm, OID_AUTO, max_kernel_address, CTLFLAG_RD,
#if defined(__arm__) || defined(__sparc64__)
    &vm_max_kernel_address, 0,
#else
    SYSCTL_NULL_ULONG_PTR, VM_MAX_KERNEL_ADDRESS,
#endif
    "Max kernel address");

sys/sysctl.h:

/* definitions for sysctl_req 'flags' member */
#if defined(__amd64__) || defined(__ia64__) || defined(__powerpc64__) ||\
    (defined(__mips__) && defined(__mips_n64))
#define SCTL_MASK32     1       /* 32 bit emulation */
#endif

kern/kern_sysctl.c:

int
sysctl_handle_long(SYSCTL_HANDLER_ARGS)
{
(snip)
ifdef SCTL_MASK32
        if (req->flags & SCTL_MASK32) {
                tmpint = tmplong;
                error = SYSCTL_OUT(req, &tmpint, sizeof(int));
        } else
#endif
                error = SYSCTL_OUT(req, &tmplong, sizeof(long));
```

**Comment by bradfitz** [comment]
Why do we care whether it's read-only? All we're doing is reading it anyway.

**Comment by mikioh** [comment]
> Why do we care whether it's read-only?

Nope, I just mentioned it's `a value` because you said "The test doesn't even look at the value." As I mentioned above, the kernel returns either a 4-byte length value or an 8-byte length for vm.max_kernel_address. If the test (or API) expects an 8-byte length value, it should use an appropriate sysctl entry instead of vm.max_kernel_address.

**Comment by mikioh** [comment]
This is a low hanging fruit, https://github.com/golang/sys/blob/master/unix/syscall_bsd.go#L532, for someone who wants to contribute this package. Please don't forget to fix the typos in test functions; s/TestSysct/TestSysctl/g
