### ISSUE TITLE
cmd/compile: fail to capture invalid field name in struct initializer

### ISSUE THREAD

**Issue by mikioh** [golang/go#15311]
The following snippet can compile with tip,
```
package main

type T struct {
	toInt    map[string]int
	toString map[int]string
}

var t = T{
	foo.toInt:    make(map[string]int),
	bar.toString: make(map[int]string),
}

func main() {}
```
though, go1.4 fails with the following:
```
./typ.go:9: invalid field name foo.toInt in struct initializer
./typ.go:10: invalid field name bar.toString in struct initializer
```

**Comment by bradfitz** [comment]
Nice find! Indeed, it's a recent regression:

```
bradfitz@laptop ~$ cat x.go
package main

import "fmt"

type T struct {
        toInt    map[string]int
        toString map[int]string
}

var t = T{
        foo.toInt:    make(map[string]int),
        bar.toString: make(map[int]string),
}

func main() {
        fmt.Printf("Got: %#v\n", t)
}

bradfitz@laptop ~$ GOROOT=$HOME/go1.4 go run x.go
# command-line-arguments
./x.go:11: invalid field name foo.toInt in struct initializer
./x.go:12: invalid field name bar.toString in struct initializer

bradfitz@laptop ~$ GOROOT=$HOME/go1.5 go run x.go
# command-line-arguments
./x.go:11: invalid field name foo.toInt in struct initializer
./x.go:12: invalid field name bar.toString in struct initializer

bradfitz@laptop ~$ GOROOT=$HOME/go1.6 go run x.go
# command-line-arguments
./x.go:11: invalid field name foo.toInt in struct initializer
./x.go:12: invalid field name bar.toString in struct initializer

bradfitz@laptop ~$ GOROOT=$HOME/go go run x.go
Got: main.T{toInt:map[string]int{}, toString:map[int]string{}}
```

/cc @josharian @mdempsky @griesemer

**Comment by mdempsky** [comment]
Regression introduced by 5f525ca.

/cc @ianlancetaylor

**Comment by mdempsky** [comment]
This is a little tricky, because the parser has already resolve (or tried to resolve) names, including package-qualified names as well as dot-imported names.  In particular, I'm not sure off hand how to best handle:

    package p

    import (
        "errors"
        . "unsafe"
    )

    type T struct {
        New int
        Pointer int
    }

    var t = T{
        errors.New: 1,  // ERROR
        Pointer: 2, // ok
    }

because at this point `errors.New` and `Pointer` have both been parsed as references to the underlying ONAME and OTYPE Nodes (respectively).  I'm not sure there's a way to distinguish whether the name was qualified or not.

Relatedly, I discovered that cmd/compile accepts

     package p
     import . "fmt"
     type T struct { Println int }
     var t = T{ Println: 0 }

even though the fmt import isn't actually used.  The parser is misrecognizing the "Println: 0" as a use of fmt.Println and marking fmt as used.
