### ISSUE TITLE
cmd/go: Windows: link.exe: chdir .: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by pquerna** [golang/go#15355]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6.1

2. What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
```

3. What did you do?

Running a `go test -v ${PACKAGES}` with a proprietary repository.  Invoked via a powershell script, like this:
```powershell
$GOPKG = (go list ./... ) | Out-String -stream | select-string -NotMatch vendor
iex "go test -v $GOPKG"
```
Currently this is about 60 package names passed into go test.

4. What did you expect to see?

Tests to build & pass 👍 

5. What did you see instead?

As best as we can see, about 5% of the time in a CI build, we get this build error during the test run:

```
go build testmain: C:\Go\pkg\tool\windows_amd64\link.exe: chdir .: The process cannot access the file because it is being used by another process.
```

**Comment by alexbrainman** [comment]
@pquerna 

I cannot reproduce your problem.

The "The process cannot access the file because it is being used by another process." is ERROR_SHARING_VIOLATION. And, going by your description, it is happening in Stat in exec_posix.go:26 in os package. Perhaps you can insert some prints to see if we can reproduce it somehow. We need that for new test.

I suspect it fails when GetFileAttributesEx is called on some directory.

I tried making GetFileAttributesEx fail with files. GetFileAttributesEx works even if I open file exclusively (dwShareMode set to 0 of CreateFile) in a different process. GetFileAttributesEx works also if I LockFileEx with dwFlags set to LOCKFILE_EXCLUSIVE_LOCK in a different process. Opening file fails with ERROR_SHARING_VIOLATION, but GetFileAttributesEx works.

I can only make GetFileAttributesEx fail with ERROR_SHARING_VIOLATION for c:\pagefil.sys on my pc. I created https://go-review.googlesource.com/22796 that fixes Stat(`c:\pagefil.sys`) on my computer. Perhaps CL fixes your problem too. Please try it and let me know.

Thank you

Alex

**Comment by rsc** [comment]
This can wait until Go 1.8. @pquerna, any reply to Alex? Thanks.
