### ISSUE TITLE
Test example involving runtime.Caller is broken with ssa backend

### ISSUE THREAD

**Issue by davecheney** [golang/go#15427]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +63ceeaf Fri Apr 22 05:27:51 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

darwin/amd64

3. What did you do?

http://play.golang.org/p/yTUc41Vxc8

4. What did you expect to see?

test passed

5. What did you see instead?
```
--- FAIL: ExampleNew_fprint (0.00s)
got:
example_test.go:7: whoops
want:
example_test.go:66: whoops
FAIL
exit status 1
FAIL    tt      0.009s
```
Test passes with Go 1.6 and earlier, test also passes if ssa backend is disabled.
```
% go test -gcflags=-ssa=false
PASS
ok      tt      0.013s
```

**Comment by randall77** [comment]
I think that's a bug in your program.  You need to subtract 1 from the pc to get the line of the call itself (see the godoc for runtime.Callers).  The file and line returned by runtime.Caller are correct.

You happen to be getting lucky because with the old compiler, the line after the call happens to get the same line # as the call itself.
```
	0x002b 00043 (issue15427.go:66)	CALL	"".New(SB)
	0x0030 00048 (issue15427.go:66)	MOVQ	16(SP), BX
```
With the SSA compiler, the following instruction is from a different line:
```
	0x0027 00039 (issue15427.go:66)	CALL	"".New(SB)
	0x002c 00044 (issue15427.go:7)	MOVQ	os.Stdout(SB), AX
```
Why that's line 7 is strange, but we should probably consider that a different bug.

**Comment by davecheney** [comment]
Thanks Keith.

**Comment by ianlancetaylor** [comment]
By the way, on tip you can `runtime.CallersFrames` which I hope will make this slightly less error-prone.
