### ISSUE TITLE
cmd/go: can't use `go generate` in package called documentation

### ISSUE THREAD

**Issue by dominikh** [golang/go#15483]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.6 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
3. What did you do?

```
 $ cat gen.go
//go:generate ./gen.sh

package documentation

$ go generate
can't load package: package .: no buildable Go source files in /home/dominikh/work/gopath/doc
```
1. What did you expect to see?
   The `go generate` to work
2. What did you see instead?
   
   ```
   can't load package: package .: no buildable Go source files in /home/dominikh/work/gopath/doc
   ```

Package documentation is special because the Go tool ignores files belonging to it. However, it would be useful to be able to use `go generate` with those, instead of having to rely on another build system.

Concrete use case: I have a documentation package at the root of the project, documenting the architecture, dependencies and so on of the project. Part of that documentation has to be generated.

**Comment by rsc** [comment]
The implications here are unclear to me, and this is not new in Go 1.7. Leaving for Go 1.8.

It seems OK to try for Go 1.8 as long as it fits nicely into the go command.
(For example, if the go command completely ignores all package documentation files and therefore required significant special case paths to make go generate not ignore them, that would probably not be correct.)

**Comment by rsc** [comment]
Seems worth trying at least. Sending CL.

**Comment by robpike** [comment]
I am against this. I think it's a mistake because if there are, for instance, arch-specific files you don't want to generate all of them, which may cause multiple generates to run with conflicting results.

Needs more thought.

**Comment by rsc** [comment]
Can you elaborate? I thought about this kind of case a bit but couldn't figure out a concrete example that made sense to me.

**Comment by robpike** [comment]
Let's say you have one go:generate in a _linux.go file and another in a _windows.go file. What do you expect to happen?

**Comment by rsc** [comment]
I would expect the go:generate line in the _linux.go file to generate a Linux-specific code (probably in a Linux-specific output file) and the go:generate line in the _windows.go file to generate Windows-specific code (probably in a Windows-specific and therefore different output file) but that both generators would typically be portable. So running "go generate" would invoke both generators to update both files. That way if you need to update all the generated code in the directory you run "go generate". You don't have to run "go generate" once for every OS/ARCH combination you have.

Many of our generators work that way: for example you might reasonably mention the generator for amd64 assembly in foo_amd64.go, but the generator itself - while it produces amd64-specific output - is a portable program and can be run on any system.

For example, we had in #16368 a problem where the generate line for Windows system calls - a portable program - was naturally recorded in syscall_windows.go. This had the effect of being ignored on Linux, and there was no work around: if you said GOOS=windows go generate, then the generator itself would run with GOOS=windows, and it ran "go run", which - because of the GOOS override - tried to build and run a Windows exe binary. With the change being proposed in this issue / CL 31147, "go generate" would just work in that case.

The only case where I can see an argument for the current behavior is if you intend to put go:generate lines that can only be run on Linux in _linux.go files and go:generate lines that can only be run on Windows in _windows.go files. But that conflates "this source code is for this system" and "this pre-build step must be run on this system". The latter seems inconsistent with our general focus on cross-compilation and portability. It doesn't seem like it should be forced as the default behavior.

**Comment by robpike** [comment]
I will accept that argument but have two points in return. First, the assumptions there need to be documented. Second, I believe there should be a controlled way to say "run only the -tags=linux generators" other than hiding files before running "go generate", because sometimes you might not have a portable generator - it might need to run on Linux. The proposal would eliminate that ability.

**Comment by rsc** [comment]
@robpike, agreed about a way to run just Linux-specific generators. But assuming those command lines mention linux in some way (for example because they say things like -o foo_linux.go), then you can already do "go generate -run=linux" to filter by command line text. Do you think that's sufficient?

**Comment by robpike** [comment]
I think it's helpful but not sufficient, although it may be all we get (and would also need to be explained well in the documentation). I am also thinking about tags within files, invisible on the command line. Perhaps it's too unusual a case but I guarantee you'll see an issue filed about it at some point.

What if go generate honored tags if they are explicitly provided, but handled all files if tags were not on the command line?

**Comment by rsc** [comment]
At this point I think we should just leave the status quo. I can't find a way to look at package documentation files without causing more serious problems.
