### ISSUE TITLE
Unable to set constant with errors.New()

### ISSUE THREAD

**Issue by hhsnopek** [golang/go#15493]
1. What version of Go are you using (`go version`)?
`go version go1.6 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
`GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/henrysnopek/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
`

3. What did you do?
https://play.golang.org/p/4UYQnL1rBc

4. What did you expect to see?
Ability to have set a constant with `errors.New()`

5. What did you see instead?
`errors.New()` is not a constant

**Comment by ianlancetaylor** [comment]
That's right: errors.New does not return a constant value.  There is no bug here.

If you want to discuss this, please do not reply on this  issue.  Use a forum.  See https://golang.org/wiki/Questions .  Thanks.

**Comment by minux** [comment]
FTR, if we implemented errors.errorString as a simple
alias of string, then it will be possible to have a const
errors.errorString. (You still can't create a constant
from errors.New() though, because one can't use a
function call to initialize a constant.)

However, that will also allow you to assign an arbitrary
string to such an error, and that's one of the reason
errors.errorString is a struct around a string. And to
speed up comparison, errors.New() returns a pointer
to errorString rather than errorString itself.

**Comment by hhsnopek** [comment]
apologies @ianlancetaylor - I will do so next time
Thank you @minux for the explanation behind the implementation
