### ISSUE TITLE
crypto/tls: regression in Handshake behavior for bad certificates

### ISSUE THREAD

**Issue by dsnet** [golang/go#15709]
Commit 37c28759ca46cf381a466e32168a793165d9c9e9 caused a regression in the `tls` package that causes some tests to fail.

This is my hypothesis (I'm not an expert in the TLS protocol):
Previously, in the event of a bad client certificate (using the [`ClientAuth`](https://golang.org/pkg/crypto/tls/#ClientAuthType) feature), the server would inform the client that the client's certificate was rejected before returning from the Handshake method. After the change mentioned, it seems that Handshake would return before the client is informed of the failure.

Consider the following code (where the client is using a bad certificate and should fail the Handshake):
```go
// Snippet of server-side logic.
if err := tc.(*tls.Conn).Handshake(); err != nil {
	// If the client presented a bad cert, it seems reasonable to
	// Close the connection immediately.
	tc.Close()
}


// Snippet of client-side logic.
if err := c.Handshake(); err != nil {
	// The client is intentionally using a bad certificate, so we expect that
	// the error be "bad certificate". However, it is more often a "pipe error" instead.
	panic(err)
}
```
If the server's `Handshake` returns before it informs the client of a bad certificate, then there is a race condition going on here. As the client's `Handshake` is asking the server for the status of the TLS handshake, the client's packet may be received by the server *before* the server calls `tc.Close` or it may be received *after* calling `tc.Close`. If received before, then the client's `Handshake` will properly return an "bad certificate" error. However, if received after, then the client's `Handshake` will return a "broken pipe" error, which is more indicative of a network failure, than an authentication error.

Putting a `time.Sleep(time.Second)` before calling `tc.Close` on the server makes the client's `Handshake` almost always return 'bad certificate', further indicating that this is a race.

See this example: https://play.golang.org/p/7aY0K9wcEW

@agl, @bradfitz

**Comment by dsnet** [comment]
I might as post these from my debugging yesterday. They are TCP dumps of the communication between client and server. `stream_good` is from running on go1.6, while `stream_bad` is from running `81a8960`. In the files `peer0` is the client and `peer1` is the server.

[steam_good.txt](https://github.com/golang/go/files/268915/steam_good.txt)
[stream_bad.txt](https://github.com/golang/go/files/268916/stream_bad.txt)

**Comment by adg** [comment]
cc @agl

**Comment by ianlancetaylor** [comment]
CC @tamird

**Comment by tamird** [comment]
Not sure what help I can provide here without a failing test. The change in 37c2875 only does better error handling, so whatever is happening here is the result of an unmasking of some other bug.

**Comment by ianlancetaylor** [comment]
@tamird There is a failing test in the initial report.  The program wants to consistently see a "bad certificate" error.  Instead it sometimes sees a write error.

I don't think there is a hidden bug here.  What seems to be happening is that the server reads some data, detects a bad certificate, sends an alert, and closes the connection.  The client seems to write some data including a bad certificate, then write some more data.  The second write fails and the client reports a write error, rather than checking for the alert sent from the server.  I think.

**Comment by tamird** [comment]
OK, looking.

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/23604

**Comment by agl** [comment]
https://go-review.googlesource.com/23609 is my take on this. It appears to solve the problem and also saves some packets on the wire.

I am not sure whether it's suitable for landing during the freeze, however.

**Comment by adg** [comment]
@agl if this is a fix for a regression then it seems suitable to the release for me.

Getting it in before the beta means that it should be sufficiently tested before the final release. 

How would you rate the risk of this change?

**Comment by agl** [comment]
I think it has a low risk, but there's a fair amount of uncertainty in that. It's possible that some implementations may be sensitive to how the handshake is cut up into packets and that's very hard to predict.

If you're happy using the beta process to test it then I've no problem with it landing. (I'm not sure how to write a good test for it, however, because it's inherently about a race. I think counting the number of writes in a handshake might be the best solution.)

**Comment by adg** [comment]
I'd be happy to include it in the beta and encourage testing by people doing interesting things with TLS.

If it were any later then I wouldn't accept it.
