### ISSUE TITLE
gccgo: erroneously accepts method expressions with named pointer types

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15722]
gccgo accepts this Go source:

    package x

    type T int
    type P *T

    func (T) t() {}

    func _(p P) {
            // Equivalent to "p.t()", which gccgo correctly rejects.
            P.t(p)
    }

cmd/compile and gotype reject both the original source above and the suggest alternative.

/cc @ianlancetaylor

**Comment by thanm** [comment]
The problematic code for this bug is in Selector_expression::lower_method_expression, on or around lines 11422 - 11441. The issue there if the receiver expression has pointer type, it goes directly to the type pointed to in order to look up the method. This works for calls like "(*T).x" but not with the scenario in the bug where you have separately named pointer type.

I have a tentative fix, which is to capture the named object when creating type expressions, then check the type expression to see whether it has a named object before the method lookup. This seems to do the trick.

Still working on setting up a new testcase (gccgo test suite is not as nice to work with as regular go test suite).
