### ISSUE TITLE
net/http, crypto/tls: cloneTLSConfig is out of sync with tls.Config

### ISSUE THREAD

**Issue by tombergan** [golang/go#15771]
I added a new tls.Config field in Issue #14376
https://tip.golang.org/src/crypto/tls/common.go#L384

but didn't know I needed to update cloneTLSConfig
https://tip.golang.org/src/net/http/transport.go#L2014

Is there a reason to not add a Clone method to tls.Config? Cloning that struct from another package seems brittle. transport.go has a comment about a race between transport.go and tls.Server -- that race seems more simply resolved if tls.Server clones the config before mutating it internally. (There's also no comment on tls.Server saying that it will mutate the provided config, which makes the behavior surprising.)

/cc @bradfitz

**Comment by bradfitz** [comment]
We could add a Clone method to TLSConfig, but where do we draw the line at adding clone methods to all types? I don't know.

But let's fix up cloneTLSConfig for now. I thought it had a test for testing that all fields are cloned, but maybe I'm remembering a different clone test.

We can keep this bug open for thinking of a better solution (and tests) in Go 1.8.

**Comment by bradfitz** [comment]
See also @ianlancetaylor's https://go-review.googlesource.com/24287 (which adds a private *tls.Config.clone method)

**Comment by bdarnell** [comment]
A `tls.Config.Clone` method is needed for more than the standard library. [Several](https://github.com/cloudflare/gokeyless/pull/61/files) [projects](https://github.com/fsouza/go-dockerclient/blob/b669abaf878a47a91653a738176f3b5edf47c8c9/tls.go) have their own copies of this method, which will need to be updated for Go 1.7 (and again for 1.8 if #16363 goes in). 

GRPC [recently](https://github.com/grpc/grpc-go/commit/78e558bbc17465d318acd499a9610e120a837860) stopped doing a naive copy of the `tls.Config` struct to avoid the incorrect copying of a lock, which resulted in [bugs](https://github.com/cockroachdb/cockroach/pull/7949) due to mutating caller-supplied memory.

**Comment by bradfitz** [comment]
@tombergan, @bdarnell, yeah, I'm sold at this point. We'll add one early in Go 1.8.

**Comment by bradfitz** [comment]
KeyLogWriter was added in golang.org/cl/27434 too.

**Comment by josharian** [comment]
Related: #16492. The implementation of Clone/Copy should be fairly trivial. Any volunteers to send a CL?

**Comment by bradfitz** [comment]
On it.

**Comment by F21** [comment]
@bradfitz, with this change is it safe to clone an existing `tls.Config`, modify the config and then replace the old config for http servers and clients?

I am using [Vault](https://github.com/hashicorp/vault) to manage my certificates internally and plan to rotate the certificates every 12 hours and would like to do the following:

Rotate the root certificates in the `RootCAs` and `ClientCAs` fields by cloning the `tls.Config`, setting a new `x509.CertPool` to those fields, and replacing the existing tls config of an http server with the new one. This is so that I can rotate the Root CAs without restarting the http server. Is this safe?
