### ISSUE TITLE
x/exp/io: introduce pin mappings

### ISSUE THREAD

**Issue by rakyll** [golang/go#15773]
Due to the fact that every board has different mappings of the actual physical pins, we need to introduce a higher level layer numeric system to name the pins. Being able to have such a layer will make the user code portable across multiple boards. E.g. the GPIO package might use names like "IO25" to refer to the physical pin 22 on Raspberry Pi boards.

**Comment by rakyll** [comment]
Chatting more about this issue with @proppy offline, we are thinking that the virtual pin space doesn't have to be of string names but we can keep using ints to defer to the GPIO numbers. Yet, we still need to have a mechanism to map the virtual pin space to the physical pins (at least for the /dev/mem implementation).

/cc @minux

**Comment by minux** [comment]
We could consider a register mechanism, and introduce board support
packages that registers pin names to the io/gpio package.

Because usually a pin will have multiple uses (btw, which package should
control the pin mux that selects the functionality of each pin?), if we're
going to use string for pin names, we will need to allow multiple aliases
for a single pin.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/exp/commit/abad524d5b70b024ecec3dc78d89b2a578408cac.
