### ISSUE TITLE
cmd/vet: Incorrect warning shown when code isn't built

### ISSUE THREAD

**Issue by martinp** [golang/go#15787]
1. What version of Go are you using (`go version`)?

  ```
$ go version
go version devel +1f8d276 Sat May 21 01:30:43 2016 +0000 linux/amd64
  ```

2. What operating system and processor architecture are you using (`go env`)?

  ```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/tmp/go"
GOTOOLDIR="/tmp/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build009147319=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
  ```

3. What did you do?
  I ran `go vet` on the following program: https://play.golang.org/p/-AbGnFT_3W
 
  The struct `foo` is intentionally undefined. The same problem occurs if `foo` is defined in another package, and that package hasn't been built yet.

4. What did you expect to see?

  No warnings reported by `go vet` (this is the case when using 1.6).

5. What did you see instead?

  ```
$ go vet main.go
main.go:16: first argument to Fprintln is os.Stdout
exit status 1
  ```

It seems that building the code is required before running `go vet` now, is this an intentional change from 1.6?

**Comment by valyala** [comment]
I'll look into this issue on this week

**Comment by ianlancetaylor** [comment]
Some vet tests do require that the packages be built, so that vet can do type checking.  Some vet tests do not require this.  As far as I know nothing in this regard has changed since 1.6.

What has changed here is the test.  The test looks for the function name and guesses based on the name what it does.  It looks for a set of names.  Since the 1.6 release, the following names were added: fprintln, panicln, println, sprintln.  That's why 1.6 doesn't warn.

It's not clear to me that this is worth fixing.  The nature of the vet program is that some errors are false positives, especially if the code has not been built.  You can disable the test for your code base with `go tool vet -printf=false`.

**Comment by valyala** [comment]
@ianlancetaylor , this may be easily fixed - see [the CL](https://go-review.googlesource.com/23351).

**Comment by martinp** [comment]
@ianlancetaylor I'm aware that `go vet` might produce false positives, but it wasn't immediately obvious that building packages would impact the reported errors in this case.

I spent some time trying to reproduce it, as it only happens in a clean environment (where nothing has been built in the past), e.g. when using Travis CI.
