### ISSUE TITLE
cmd/compile: load after writebarrier call instead of spilling

### ISSUE THREAD

**Issue by josharian** [golang/go#15845]
The inplace append optimization (CLs 21813 and 22197) use a trick to avoid a spill: When doing `*dst = src` via a write barrier, immediately do `src = *dst`. (Search for a comment like "load the value we just stored to avoid having to spill it" in ssa.go.)

If `src` is used again, it doesn't need to be spilled before the write barrier; it is a load either way, but we can skip the spill/store. If `src` isn't used again, the load will be eliminated as dead code.

Perhaps should we investigate extending this trick to all writebarrier-enabled pointer stores. Thoughts?

**Comment by josharian** [comment]
@cherrymui you might be interested in this. :)

**Comment by aclements** [comment]
@josharian, could you give an example of what the code would look like before and after with this change?

**Comment by josharian** [comment]
> could you give an example of what the code would look like before and after

I'm not sure what kind of answer would be helpful here. The goal is to replace "spill src, *dst = src, load src, use src" with "*dst = src, src = *dst, use src".

**Comment by aclements** [comment]
That's actually exactly the kind of answer I was looking for. Thanks.

Is the goal here just to reduce the needed spill space? It's not at all obvious to me that the new memory access pattern would be better.

This obviously has weird effects if the program has races, but maybe we're okay with that.

Alternatively, since we're passing src to the write barrier, should we just have the write barrier return src? (Or if the write barrier promises not to write to its argument, it can be reloaded straight from the argument slot, if that's not too scary. :)

Even more alternatively, @RLH and I have talked a bit about using an SSB-style write barrier, mostly to improve register utilization around write barriers. This would have a very short fast path that just added the pointer to a per-P buffer (with a slow path to handle when this buffer overflows). The fast path could be coded in assembly to guarantee that it only uses some small set of registers, so the compiler could keep the rest across the write barrier call. The slow path would probably just save all registers; the type information doesn't matter here because it wouldn't be preemptible anyway.

**Comment by josharian** [comment]
> Alternatively, since we're passing src to the write barrier, should we just have the write barrier return src?

This sounds good to me--at least worth trying out.

> The fast path could be coded in assembly to guarantee that it only uses some small set of registers, so the compiler could keep the rest across the write barrier call.

This also sounds promising.

**Comment by josharian** [comment]
> The fast path could be coded in assembly to guarantee that it only uses some small set of registers, so the compiler could keep the rest across the write barrier call.

This happened, and it's great.
