### ISSUE TITLE
html/template: add helper functions for type conversion

### ISSUE THREAD

**Issue by localvar** [golang/go#16058]
I have a template like below

```html
...
<script>
    var opts = {{.Config}};
</script>
...
```

where `.Config` is a json string like `{"a":123,"b":"333"}`, but because the type of `.Config` is `string`, the result becomes:

```html
...
<script>
    var opts = "{\"a\":123,\"b\":\"333\"}";
</script>
...
```

Because I don't own the code., I cannot change the type of `.Config` to `template.JS`, so I add a function `ToJS` to fix the issue:

```go
tpl.Funcs(template.FuncMap{
		"ToJS": func(v string) template.JS {
			return template.JS(v)
		},
	})
```

and changed my template to:

```html
...
<script>
    var opts = {{ToJS .Config}};
</script>
...
```

My suggestion is: could we add serveral helper functions to `html/template` to help convert `string` to types like `template.JS`, `template.HTML`, `template.CSS` and etc.? this would make the package much easier to use.

**Comment by rsc** [comment]
You're asking for a magic override to say "I am sure this is JavaScript, just stuff it here please". This package used to provide a builtin called "noescape" that basically did this, but we decided it was too dangerous, that it made it too easy for people to write unsafe templates, to bypass the template system instead of working with it. This was removed as #3528.

The cost of having to write something like ToJS is intentional here. Hopefully at the same time you will read the docs for JS and think about the security implications.

Specifically:

    Use of this type presents a security risk: the encapsulated content should
    come from a trusted source, as it will be included verbatim in the template
    output.

    Using JS to include valid but untrusted JSON is not safe. A safe alternative
    is to parse the JSON with json.Unmarshal and then pass the resultant object
    into the template, where it will be converted to sanitized JSON when
    presented in a JavaScript context.

/cc @mikesamuel

**Comment by mikesamuel** [comment]
Can `.Config`  not be passed as a value of type `JS`

**Comment by mikesamuel** [comment]
OK.  I see the ownership issue.  I agree that adding such functions is a bad idea.
