### ISSUE TITLE
Please Write A Pauseless Garbage Collection

### ISSUE THREAD

**Issue by liuhuasong** [golang/go#16123]
Ther is a pauseless garbage collection from Azul Zing JVM:
[https://www.azul.com/files/wp_pgc_zing_v5.pdf](https://www.azul.com/files/wp_pgc_zing_v5.pdf)
Please write one for Golang.

**Comment by adg** [comment]
There's not pauseless GC on our roadmap, although we continue to work on improving our low-latency GC.

In what ways is the current GC inadequate for you?

**Comment by liuhuasong** [comment]
I'd like to write real time controller to control industrial devices in golang on Linux, or write firmware run in an MCU chip.

**Comment by mezoni** [comment]
>> There's not pauseless GC on our roadmap, although we continue to work on improving our low-latency GC.

Go compiler does not allow to have alternatives (at runtime, at compile time)?

[GCLatencyMode Enumeration](https://msdn.microsoft.com/en-us/library/system.runtime.gclatencymode.aspx)

[GCSettings.LatencyMode Property](https://msdn.microsoft.com/en-us/library/system.runtime.gcsettings.latencymode.aspx)

**Comment by ianlancetaylor** [comment]
Go is not Java, and different garbage collection techniques are appropriate.

Although the paper describes the GC as pauseless, if you read it you will see that that is not the case.  I quote:

    While the Azul C4 algorithm actually requires zero
    pauses in applications, the JVM implementation
    does include brief pauses at phase transitions for
    simplicity and implementation expedience. These
    pauses are well below the threshold that would
    be noticeable to users and are not affected by
    application scale or data set size. The C4 algorithm
    completely decouples pause time from memory heap
    size, allowing applications to scale and use large
    amounts of heap memory without impacting performance
    or user response time. The result is a
    highly scalable environment that offers predictable
    performance for large Java applications.

These same statements are already true of the current Go garbage collection algorithm.  Go GC pause times are very short and are independent of heap size.

I also note that the Azul algorithm, unlike the current Go algorithm, requires read barriers, which impose a performance cost on the entire application.

The Go runtime team is continuing to work to improve the Go garbage collector.  We welcome specific suggestions and specific problem reports.  However, I'm going to close this general issue as not actionable.

It would be better to discuss general GC issues, like this, in a forum, rather than on the issue tracker.  See https://golang.org/wiki/Questions .
