### ISSUE TITLE
text/template: not able to redefine template as an empty string

### ISSUE THREAD

**Issue by evandigby** [golang/go#16156]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

- go version go1.6 linux/amd64
- go version go1.6 darwin/amd64
- go playground

2. What operating system and processor architecture are you using (`go env`)?

- darwin/amd64
- linux/amd64
- go playground

3. What did you do?

Attempt to redefine a text/template as an empty string using parse, and then executed the template:
https://play.golang.org/p/gotXx8qF3e

4. What did you expect to see?

I expected the template to successfully execute and produce an empty string.

Alternatively, if it is expected behaviour to not allow redefining as an empty string, I expect an error to be returned on the "Parse" call.

5. What did you see instead?

The execute function returned the following error:
template: test: "test" is an incomplete or empty template; defined templates are: "test"

**Comment by jfrazelle** [comment]
dibs

**Comment by shurcooL** [comment]
I ran into this as well, and I had a hard time figuring out if this was a bug or intended behavior, because when I tried to find documentation for template redefinition, I couldn't. It seems to be mentioned in passing on https://golang.org/pkg/text/template/#hdr-Actions and nowhere else:

> The typical use is to define a set of root templates that are
> then customized by redefining the block templates within.

Glad to see it was indeed a bug and is already fixed.
