### ISSUE TITLE
Wrong output generated for concurrency example from tour.golang.org

### ISSUE THREAD

**Issue by nagarajasr** [golang/go#16200]
while experimenting with the concurrency examples from https://tour.golang.org/concurrency/1, came across this issue. 

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```go 1.6.2 linux/amd64```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxxx/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.

```
package main

import (
	"fmt"
	"time"
)

func say(s string) {
	for i := 0; i < 5; i++ {
		time.Sleep(100 * time.Millisecond)
		fmt.Println(s)
	}
}

func main() {
	say("hello")
	go say("world")
	
}
```

4. What did you expect to see?
```
hello
world
world
world
world
world
```
5. What did you see instead?
```
hello
hello
hello
hello
hello
```

**Comment by dsnet** [comment]
This is working as intended.

It prints 5 hellos because of the `say("hello")` function calls does that exactly 5 times, with a 100ms pause between each printout. Once it reaches the `go say("world")`, it will start a goroutine which asynchronously starts executing `say("world")`. Since `main` does not block on the goroutine, it will keep executing and reach the end of the `main` function. Once `main` returns, the program exits even if there are goroutines still running. At this point in time, the goroutine running `say("world")` is still executing `time.Sleep`, so it never got around to printing anything.
