### ISSUE TITLE
go-rename.el doesn't work with symbolic link

### ISSUE THREAD

**Issue by enzochiau** [golang/go#16219]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   
   go version go1.6.2 linux/amd64 
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/enzoc/App/go_path"
   GORACE=""
   GOROOT="/home/enzoc/.local/share/umake/go/go-lang"
   GOTOOLDIR="/home/enzoc/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   My environment:

project directory:   /home/enzoc/tmp/GoLang/emacs_setup_test   (/home/enzoc/tmp is a symbolic to /opt/enzoc/tmp)
go file directory:    /home/enzoc/tmp/GoLang/emacs_setup_test/src/cmd/helloworld/t.go

The Emacs "go-mode" would automatic set my GOPATH to /opt/enzoc/tmp/GoLang/emacs_setup_test (true directory). When I call the "go-rename", it forms the "-offset=%s" with buffer name as "/home/enzoc/tmp/GoLang/emacs_setup_test/src/cmd/helloworld/t.go" which doesn't match with the GOPATH. Then I go "Can't find package contains ..." error.

I tried from terminal to set both GOPATH and "-offset=" file name to true directory and file name, it works well. 

So I guess, if "go-rename.el" can make both the GOPATH and buffer name use the true file name or directory name, that issue should be solved. 
1. What did you expect to see?

I would like to see both GOPATH and --offset is set with true directory or file name as:

```
GOPATH=/opt/enzoc/tmp/GoLang/emacs_setup_test/
--offset=/opt/enzoc/tmp/GoLang/emacs_setup_test/src/cmd/helloworld/t.go:XXX
```
1. What did you see instead?

But what I saw is:
    GOPATH=/opt/enzoc/tmp/GoLang/emacs_setup_test/
    --offset=/home/enzoc/tmp/GoLang/emacs_setup_test/src/cmd/helloworld/t.go:XXX

That causes "gorename" return error as "Can't find package contains ...".

**Comment by ianlancetaylor** [comment]
CC @alandonovan

**Comment by dominikh** [comment]
The Emacs integration is not part of the x/tools repository anymore. If this is indeed an issue specific to Emacs and not rename itself please consider filing the issue at https://github.com/dominikh/go-mode.el

**Comment by alandonovan** [comment]
Even though it may be possible to work around the problem with editor-specific fixes, I think the underlying problem is in the gorename command.  (guru has an almost identical problem, Issue #17515). The solution is that gorename's logic to find the package containing a given file should use inode (`os.SameFile`) not textual equivalence when comparing file names.

**Comment by chmouel** [comment]
not sure where is the real underlying (my gut feeling think it would be in go-rename) but it is much easier to fix in emacs so submitted one

**Comment by alandonovan** [comment]
Why does `go-guess-gopath` in go-mode.el apply `file-truename` to the candidate GOPATH directory?  Generally it's best to avoid "normalizing" filenames (absolutizing, resolving symbolic links, etc) unless and until it's absolutely necessary.  Removing that function call would be a better workaround for the underlying gorename bug than additional additional compensatory calls to `file-truename`.

**Comment by dominikh** [comment]
@alandonovan I don't fully remember, but most uses of file-truename in go-mode are because of the following Emacs behaviour: Given a link `/a -> /b`, opening `/a` in Emacs will report `/a` as the file name, not `/b`, and vice versa. If the user opens the file one way, but has the other version (resolved or unresolved) in his GOPATH, we need to normalize one of them if we want to match them. The easiest way to do so is to always resolve symbolic links.
