### ISSUE TITLE
runtime: revert https://go-review.googlesource.com/18835 on dragonfly 4.4.4 and above

### ISSUE THREAD

**Issue by mikioh** [golang/go#16329]
See https://go-review.googlesource.com/c/18835/ and http://gitweb.dragonflybsd.org/dragonfly.git/commit/e5cb2f520ad7ece129e45b29e2b4024e7acfeee6

I've just tested and confirmed that #14067 and friends are fixed on v4.4.3.9.ge5cb2-RELEASE.

**Comment by quentinmit** [comment]
Can you suggest a way to test if the dragonfly kernel is new enough to have this fix, or would you recommend dropping it entirely?

**Comment by bradfitz** [comment]
Dragonfly users tend to update approximately always.

We got an email saying they'd restarted our builder with this almost immediately too.

**Comment by mikioh** [comment]
I think it's fine to drop support for DragonFly BSD 4.3 and below from Go 1.8. I guess that typical use cases are an alternative to nginx-on-linux and an alternative to freebsd-on-{many,multi}core machine, so probably the drop of support doesn't matter because the users are pretty familiar with kernel.

PS: Of course we can read out the running kernel version via sysctl system call.

**Comment by tdfbsd** [comment]
The Dragonfly team officially supports the current OS release (4.6 currently) and one prior (4.4), so the answer to someone running 4.3 or earlier would be stay on Go 1.6 or upgrade the OS.

I don't know how frequently most people update Dragonfly, but I personally like to track the master branch simply because I get the latest goodies and historically it has been quite stable.
