### ISSUE TITLE
go/build: does not know about buildmode pkg directories

### ISSUE THREAD

**Issue by josharian** [golang/go#16378]
Create and build/install imp.go:

```go
package main

import (
	"fmt"
	"go/build"
	"log"
)

func main() {
	pkg, err := build.Import("fmt", "", build.FindOnly|build.AllowBinary)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(pkg.PkgObj)
}
```

Then try to use it with `darwin/arm`:

```bash
$ GOOS=darwin GOARCH=386 go install std
$ GOOS=darwin GOARCH=arm go install std
$ cd $GOROOT/pkg
$ pwd
/Users/josh/go/tip/pkg
$ ls -d darwin_arm* darwin_386*
darwin_386		darwin_arm_shared
$ GOOS=darwin GOARCH=386 ./imp
/Users/josh/go/tip/pkg/darwin_386/fmt.a
$ GOOS=darwin GOARCH=arm ./imp
/Users/josh/go/tip/pkg/darwin_arm/fmt.a
```

Observe that the installed arm packages are in `darwin_arm_shared`, but according to go/build, the PkgObjs are to be found in `darwin_arm`.

This comes up in practice when attempting to do a cross-platform `go vet` invocation, because vet cannot find the `fmt` (and other) packages, which results in a flood of incorrect errors.

I'd love help fixing this. I'm not sure what/where the correct fix is, or even who to ask for help. This will shortly block my progress on #11041, so an R=go1.8 CL would be deeply appreciated.

**Comment by ianlancetaylor** [comment]
I expect that cmd/go/build.go needs to update buildContext.InstallSuffix.

**Comment by ianlancetaylor** [comment]
Hmmm, sorry, it already does that.  But I guess the problem is that cmd/vet doesn't know about the installsuffix.

I see: the `buildModeInit` functions sets an install suffix of `"shared"` as the default for several targets: "android/arm", "android/arm64", "android/amd64", "android/386", "darwin/arm", "darwin/arm64".  For "darwin/arm" and "darwin/arm64" it's odd that not passing a `-buildmode` option is not the same as passing an explicit `-buildmode=archive` or `-buildmode=exe` option.  I'm not sure what the right fix is.  If we are always going to pass `-shared` to the compiler, then perhaps we should not be setting the install suffix in that case.

**Comment by josharian** [comment]
Thanks, Ian, that was exactly the information I needed to get unstuck. I'll send a CL shortly for preliminary feedback.
