### ISSUE TITLE
x/text/cases: linker crash

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16390]
Both the `linux-amd64` and `linux-amd64-nocgo` builders are failing with Go 1.6:

https://build.golang.org/log/d2d3e2b25eb7f7940e0a2fd9c7e664297f040695
https://build.golang.org/log/aeac6e494aca0d048349019a986341d9c2d6accb

```
?       golang.org/x/text   [no test files]
go build testmain: /tmp/workdir/go/pkg/tool/linux_amd64/compile: signal: killed
go build testmain: /tmp/workdir/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /tmp/workdir/go/pkg/tool/linux_amd64/link: signal: killed
FAIL    golang.org/x/text/cases [build failed]
```

(which causes the golang.org/x/text/language and golang.org/x/text/unicode/norm builds to fail, presumably)

@mpvl, any clue?

Massive memory usage by the linker? But it's fine with Go 1.5 and Go 1.7? Should we disable those tests if `+build go1.6,!go1.7`?

(part of #11811, cc @quentinmit)

**Comment by mpvl** [comment]
It is also flakey.  The link succeeds on most trials even when there are unrelated changes.

**Comment by mpvl** [comment]
This seems to somewhat more frequently with about 4 packages in the text repo (though still the minority of the builds) and less frequently with other packages.  I suspect this linking resource issue can happen with many of the packages in the repo. So rather than exclude each package from testing, I would prefer if the framework could ignore or retry in case of flakey tests. Or allow for a manual retry option of some sort.

Or, we could remove the text repo from 1.6 altogether as to not give a false illusion that it is tested after marking half or all of the packages to be excluded from 1.6.

**Comment by mpvl** [comment]
Actually, the same problem also exists on 1.5 and 1.7.  So I propose increasing the timeouts.

**Comment by bradfitz** [comment]
> So I propose increasing the timeouts.

What timeout?

I see no use of the time package in that code.

I had guessed it was a memory issue.

/cc @quentinmit

**Comment by mpvl** [comment]
Ah. Either way, I don't think I can do much on my side. The building is flakey, so I think the only thing to do is to either raise some limits or increase capacity.

/cc @quentinmit

**Comment by mpvl** [comment]
I believe this is no longer an issue.
