### ISSUE TITLE
tour: inconsistency in text over where & operator can be used

### ISSUE THREAD

**Issue by StevenMaude** [golang/go#16482]
The Tour's [description of pointers](https://tour.golang.org/moretypes/1) currently states:

>  A pointer holds the memory address of a *variable*.

(Emphasis mine.)

Fine, I think. And maybe I even try taking addresses of types of values (e.g. `int`, `string`) I've seen by that point in the Tour, and find that this rule is accurate.

OK, let's continue reading. Only a few pages on, [the rule quoted above changes](https://tour.golang.org/moretypes/5):

> The special prefix & returns a pointer to the struct *value*.

(Emphasis again mine.)

Revealing subtleties after explaining the basics is often preferable over having everything thrown at a reader simultaneously. But, if attention is not drawn to such a change, it can lead to confusion. Particularly, as a learner, I may not immediately think to check the language specification to clarify fine details.

Even prefacing the second quote with a short clarification might help, maybe along the lines of:

> Not only can the special prefix `&` be used to return a pointer to a variable, but you can use it in the same way with struct (and other composite) literals.

**Comment by cznic** [comment]
IMO, technically are both quotations OK. The composite literal syntax used in, for example, 

```go
v := &T{...}
```

is more or less syntactic sugar for 
```go
tmp := T{...}
v := &tmp
```

**Comment by robpike** [comment]
The first use of 'variable' is probably misleading but correct. It's a technical term that appears often in the spec, for example, to avoid other jargon like C's l-value. In that use, a variable can be thought of as something addressable, so v is a variable and a[i] is a variable buf f() is not because you cannot write f() as the target of an assignment (f() = 2 is not legal). This is subtle.

There were discussions about this terminology when writing all the documentation.

That use of the term variable should probably be avoided in introductory material. Instead, variable here should mean something declared with var or :=, the more commonly understood simpler definition.
