### ISSUE TITLE
x/net/http2: investigate Server default stream & conn flow control values

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16512]
What do other servers pick as their default conn- and stream-level flow control values?

Expose user tunables?

**Comment by tombergan** [comment]
FWIW, [h2o uses a 16MB initial window](https://github.com/h2o/h2o/blob/5d422ce12ef41fb05c00f39f8e34c93311586a42/lib/http2/connection.c#L42) and [apache uses a configurable initial window](https://github.com/apache/httpd/blob/72bc10168a907950c4a98c0ee8a71a73833f535e/modules/http2/h2_session.c#L1092) that defaults to the standard default of 2^16-1. I believe the GFE uses 1MB.

Abstractly, the "right" value is probably min(MaxBufferPerRequest, LinkBDP), where MaxBufferPerRequest is user-configurable and LinkBDP is the connection's BDP (perhaps estimated from the current TCP cwnd). It's probably sufficient to use 1MB for now, then close this bug and wait for someone to ask for a knob.

**Comment by tombergan** [comment]
The above numbers are per-stream. The GFE uses 1MB per-connection as well.

Say we pick a constant 1MB per-stream. If we continue to used a fixedBuffer for each request body, then we might as well set the connection's send window to NumOpenRequestBodies * 1MB since we'd be allocating a 1MB buffer per request anyway. If we want more control over the connection's send window, we should use something smarter than a fixedBuffer.
