### ISSUE TITLE
net/http/fcgi: REMOTE_USER not exposed

### ISSUE THREAD

**Issue by quentinmit** [golang/go#16546]
`http.Request` is used to represent the incoming request state for `net/cgi` and `net/fcgi`. `net/fcgi` uses `http.RequestFromMap` to construct the `Request` to pass to the handler. `RequestFromMap` does nothing with the REMOTE_USER parameter, which contains the authentication information from the web server. In the `net/cgi` case, that's fine because the user can just access the environment variable directly, but in `net/fcgi`, the underlying params map is not exposed to the user.

Either the underlying params should be exposed somehow, or a RemoteUser needs to be added to the `Request` struct and filled in from params.

/cc @bradfitz

**Comment by bradfitz** [comment]
For something as specific as this, I'd rather add something to `net/http/fcgi` than add something to the `net/http.Request` struct.

**Comment by luca76** [comment]
Any news about this? We use Apache2/FCGI with Kerberos authentication to our Active Directory, and this missing REMOTE_USER is preventing to use Golang in this case.

**Comment by bradfitz** [comment]
No news. Are you interested in adding this? I'm not sure whether you're already familiar enough with Go to add this support. If so, it's all yours. Otherwise, I'm happy to review a change from anybody.

(As long as the change doesn't expand the `http.Request` struct.)

**Comment by meirf** [comment]
The mechanics here don't seem super complicated. Rather the most contentious aspect is probably the API. Here's a first crack at something that would be  **added** to `net/http/fcgi`:

```
// Serve accepts incoming FastCGI connections on the listener l, creating a new goroutine for each. 
// The goroutine reads requests and then calls handler to reply to them.
// If l is nil, Serve accepts connections from os.Stdin. If handler is nil, http.DefaultServeMux is used.
func ServeWithCgiVariables(l net.Listener, handler Handler) error // 1.

// Handler responds to incoming requests which contain http data and cgi environment variables.
type Handler interface { // 2
    ServeHttpCgiParams(http.ResponseWriter, *Request) // 3.
}

// Request includes an http request and cgi environment variables that were 
// set at the time of the specific request.
type Request struct {
    HTTPRequest http.Request
    CGIEnvVars map[CGIEnvVariable]string // 4.
}

// CGIEnvVariable is a variable set 
type CGIEnvVariable string
const (
    REMOTE_USER CGI EnvVariable = "REMOTE_USER"
    //... 5.
)
```

Some of the documentation is redundant, but I include it here to illustrate the intention of code that I've left out.
Some of the documentation is left out, but is discussed below:
1. This is not a great function name but we can't overload in go.
2. I'm keeping the same name as the Handler in net package. I thought this was okay to do in go because names are package-prefixed anyway.
3. I package the http and the params in one Request struct instead of having two separate params because I see them as part of the "input" to the handler so we can keep the spirit of the net.Handler with Server*(output, input).
4. Although this issue's focus is just one of the env variables, probably good to be more general.
5. One of the biggest things this code/documentation leaves out is which variables are being included. Should it be (a) [all environment variables](https://en.wikipedia.org/wiki/Common_Gateway_Interface#Example) or (b) just variables that the code doesn't make a best effort of including in the request? I'm not sure which of these it should be. If either case, the documentation should specify that a best effort is made to include the param values in the http.Request.

(I'd like to work on this issue.)

**Comment by luca76** [comment]
Thank you for your effort. Could you post anywhere a working version of the code, so we can test it?

**Comment by meirf** [comment]
The snippet above is an interdace sketch. I didn't want to waste time implementing an interface that @bradfitz rejects. 

(When code is uploaded for review and the commit references an issue, a comment is generated on that issue with a link to the code review. So if you're subscribed to this issue you'll be notified of the new code and you can test it with your system/complain if it doesn't behave as you'd like.)

**Comment by meirf** [comment]
For further motivation, [an SO post](http://stackoverflow.com/questions/34006957/golang-with-fastcgi-how-to-read-remote-user) shows that a resolution to this exact problem has been in demand since 2015.
