### ISSUE TITLE
doc: specify new automatic HTTP/2 behavior of net/http.Server.Serve

### ISSUE THREAD

**Issue by wjkohnen** [golang/go#16550]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7rc3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?

Compile github.com/mholt/caddy

4. What did you expect to see?

Caddy serves HTTP/2.

5. What did you see instead?

Caddy serves HTTP/1.1 only. 

The semantics of net/http/(*Server).Serve() [have changed](https://tip.golang.org/pkg/net/http/#Server.Serve):

>  If srv.TLSConfig is non-nil and doesn't include the string "h2" in Config.NextProtos, HTTP/2 support is not enabled. 

Apparently that was not the case with Go 1.6. Caddy used to use (or still uses) an empty slice for NextProtos and HTTP/2 worked fine. Adding "h2" works.

**I did not expect this change**, as it is not mentioned in the Go 1.7 Release Notes DRAFT. Please add a note about that changed behaviour.

Thanks

See also mholt/caddy#975.

**Comment by bradfitz** [comment]
This was #15908 in b5f0aff49503e31002b33198e06708e263c445a7. The old behavior was racy and not documented. It was also a little too magic before.

We could document it in the release notes, but the main party it would affect (which I thought was already aware and not affected?) was Caddy. But I guess I was wrong about that, since it did affect Caddy.

**Comment by wjkohnen** [comment]
OK, interesting. Well, to be more precise with "I did not expect" I meant I didn't expect re-reading package doc would help me while debugging Caddy. :)
