### ISSUE TITLE
tour: Run Error in example

### ISSUE THREAD

**Issue by kerbelp** [golang/go#16561]
Context: http://127.0.0.1:3999/basics/13

math.Sqrt(x*x + y*y) gets an int where it should get a float64.

# command-line-arguments
./compile7.go:10: cannot use x * x + y * y (type int) as type float64 in argument to math.Sqrt

**Comment by odeke-em** [comment]
@kerbelp it seems like you might have forgotten to cast the result of the multiplication to float64 ie
you have in your bug report
```go
math.Sqr(xx + yy)
```
instead of what is on tour.golang.org
```go
float64(xx + yy)
```
The code on tour.golang.org/basics/13 seems right otherwise
<img width="1120" alt="screen shot 2016-07-31 at 11 27 26 pm" src="https://cloud.githubusercontent.com/assets/4898263/17285254/8474bcb2-5776-11e6-8295-d4d8d79e60fc.png">

Did you get that result directly from the tour tree or was it modified? Also what version of Go are you using?

**Comment by quentinmit** [comment]
The tour has had the float64 cast in there since the page was added in 2013. I'm going to close the issue for now. If you are able to replicate seeing the wrong thing in the tour, please let us know what version of Go you are using.
