### ISSUE TITLE
net/http: imperva HTTP/2 attack vectors report

### ISSUE THREAD

**Issue by dlsniper** [golang/go#16630]
Hello,

I've just seen the issues highlighted by this report: https://www.nginx.com/blog/the-imperva-http2-vulnerability-report-and-nginx/ (download shortcut: http://www.imperva.com/docs/Imperva_HII_HTTP2.pdf) with regards to HTTP/2 implementation in web servers and I'd like to ask if this is something that the Go team is aware of and if Go itself is vulnerable to the issues described there.
Sorry if this is the wrong place to ask, I wasn't sure if I should ask here or on golang-dev.

Thank you.

**Comment by bradfitz** [comment]
Can I reply in text or do I need to generate a PDF?

**Comment by dlsniper** [comment]
I couldn't see a text version of it, aside from this rather useless link: http://investors.imperva.com/phoenix.zhtml?c=247116&p=irol-newsArticle&ID=2192322 , sorry.
I understand that the issues are in the specific implementations not the protocol itself.

Thank you.

**Comment by as** [comment]
The PDF is wordy, so here's a summary of the article's contents. None of the specific issues mentioned are about Go, and some do not even seem possible (1 thread per stream, buffer overflow, etc). 

(page 7) HTTP/2 Stream Multiplexing 

- [CVE-2016-0150](https://technet.microsoft.com/en-us/library/security/ms16-049.aspx) Microsoft's HTTP/2 kernel driver crashes after seeing two requests for the same stream

(page 9) HTTP/2 Flow Control

- [CVE-2016-1546](https://httpd.apache.org/security/vulnerabilities_24.html)  "Slow Read Attack." Four non-Go implementations (IIS, Apache, Nginx, Jetty) affected. Paper mentions one-thread-per-stream. 

(page 12) Dependency and Priority
- [CVE-2015-8659](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8659) Implementation-specific (Nginx) use-after-free bug

(page 16) HPACK Bomb
- [CVE-2016-1544](https://nghttp2.org/blog/2016/02/11/nghttp2-v1-7-1/) Nghttp2 out of memory
- [CVE-2016-2525](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2525) Wireshark "dissector" out-of-memory crash due to large header

**Comment by bradfitz** [comment]
The only one I'd want to double-check is the HPACK bomb (haven't read the details yet). But https://github.com/golang/net/commit/6050c111928ef9186beb82e4395437607bb24bdb and https://github.com/golang/net/commit/21c3935a8fc0f954d03e6b8a560c9600ffee38d2 and https://github.com/golang/net/commit/59e870b2963d78af46909371603f8c4de3debcc2 and https://github.com/golang/net/commit/d8f3c68ddd4bb686ca3bd70e49bbc64b80c78144 and https://github.com/golang/net/commit/29704b8f8f57fa48a0d8237fc20ed7c6744b86b1 seem to cover it.

**Comment by bradfitz** [comment]
Yeah, I think we're fine here. Please file a bug if you find a problem in Go's implementation.
