### ISSUE TITLE
x/crypto/openpgp: Support Encrypted OpenPGP PrivateKey packet

### ISSUE THREAD

**Issue by tcz001** [golang/go#16664]
Hi, 
We are working on providing an alternative of GnuPG, 
With the help of x/crypto/openpgp we can easily read and parse a key, and decrypt it with passphrase, 
But there's no support for encryption & serialization of PrivateKeys, as the [comment](https://github.com/golang/crypto/blob/master/openpgp/packet/private_key.go#L134) says: TODO(agl): support encrypted private keys

We made some [implementation](https://go-review.googlesource.com/#/c/26773/) of this feature, but it needs review and suggestion about the configuration for s2k related parameters (s2kMode, salt, hashFunction, iteratedCount)

Related RFC4880 https://tools.ietf.org/html/rfc4880#section-3.7.2.1

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by andybons** [comment]
@FiloSottile

**Comment by asminozhka** [comment]
2 years later... Where is this feauture?

**Comment by FiloSottile** [comment]
x/crypto/openpgp is looking for maintainers.

https://groups.google.com/d/msg/golang-openpgp/_P6AmeCmD9w/raw7JhKuCAAJ

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
