### ISSUE TITLE
cmd/compile: convert s390x to SSA backend

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16677]
As part of deleting the legacy compiler (#16357) and letting the frontend assume an SSA backend, the s390x port needs to be converted to SSA.

I assume @mundaym et al will be doing this?

/cc @randall77 @cherrymui

**Comment by billotosyr** [comment]
@mundaym will be handling the changesets.

**Comment by randall77** [comment]
Any progress report?  Can I help with anything?

**Comment by billotosyr** [comment]
We have done the basic work and built the runtime and the compiler itself with SSA, but there still some bugs to sort out. These are functional bugs, not just performance issues. @mundaym will begin pushing CL's in the next while. I guess maybe we're not quite as fast as you are :-) It's coming....

**Comment by mundaym** [comment]
The SSA backend for s390x is fully functional now. Many thanks to Yu Heng Zhang (@annitazhang) and Yu Xuan Zhang (@zyxsh) over at IBM China for doing a lot of the work. There are still quite a few improvements I'd like to make but those can wait until it's in master (we haven't done the intrinsics yet for example).

I'll probably start by sending CLs for the assembly/assembler changes. The SSA backend uses 32-bit ops where it can (as opposed to 64-bit ops everywhere) so it needs some additional instructions. I've also re-purposed R0 as general purpose register (rather than always holding zero) which is an ABI change so there are some changes related to that. The old backend does still work though (although R0 needs to be removed from the list of allocatable registers when using a mix of SSA and non-SSA).

Once this is all in master do you think you'll keep the old back-end around for long, or is the plan to get rid of it straight away?  I'd like to remove the current requirement to have dedicated temporary registers and it will be cleaner to do this once the old backend is gone.

**Comment by randall77** [comment]
Excellent.

The plan is to start excising the old backend ASAP.

**Comment by bradfitz** [comment]
Great news!

> Once this is all in master do you think you'll keep the old back-end around for long, or is the plan to get rid of it straight away? I'd like to remove the current requirement to have dedicated temporary registers and it will be cleaner to do this once the old backend is gone.

I think everybody wants to see the old backend deleted straight away for similar ease-of-cleanups reasons. Having two backends makes things trickier everywhere.
