### ISSUE TITLE
Misleading file/line in stack traces during function pointer w/receiver invocations

### ISSUE THREAD

**Issue by jupierce** [golang/go#16670]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64  & 1.6.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
The go stack includes a highly unpredictable stack frame when using function references/with receivers. 
https://play.golang.org/p/VICvYCyvtR

See frame in bold which references a counterintuitive line number:
```
3*****************
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa0
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x20
main.(*anObject).PrintSomething(0x1f6af4, 0x151a04, 0x1, 0x1)
	/tmp/sandbox895538073/main.go:18 +0x120
main.(*anObject).PrintSomething-fm(0x151a04, 0x1)
```
**/tmp/sandbox895538073/main.go:30 +0x40**
```
main.main()
	/tmp/sandbox895538073/main.go:34 +0x140
```

If you comment out f2 in the example and leave f3 unmodified, the stack frame in question moves:
https://play.golang.org/p/EAy6Ct5Uw2

4. What did you expect to see?
The stack frame in question would ideally reference an intuitive file/line number. 

5. What did you see instead?
In a real world example, the file and line number can change to seemingly random locations. Likely just the first to generate the closure.

**Comment by randall77** [comment]
The line `f2 := a.PrintSomething` makes a function closure which captures `a`.  The `-fm` function is a wrapper that reads `a` out of the closure and passes it as an argument to `PrintSomething`.

So there is a real function there on the stack, and the traceback is showing it to you.  The line number looks correct, it mentions the line where the wrapper is generated.  Just like if you had defined a func(){} inside your function and then later called it.

So yes, the line number is somewhat strange.  But I don't think it's incorrect.  I'm not sure what would be a better line number.  For instance, if you did:
```
1:    f2 := a.PrintSomething
2:    f2("a")
3:    f2("b")
```
The current code reports line 1 for the `-fm` entry if either call panics.  It sounds like you want it to report line 2 when the first call panics and line 3 when the second call panics.  But the PC is the same for both of those instances, so that wouldn't be easy to manage with the current traceback setup.

```
1:    f := func(s string) { ... maybe panic ... }
2:    f("a")
3:    f("b")
```
With an explicit function `f`, reporting line 1 is ok, right?

**Comment by jupierce** [comment]
Thanks for taking a look @randall77 .

>  It sounds like you want it to report line 2 when the first call panics and line 3 when the second call panics.

No. The current behavior of your first example is just fine. It is only when the generated wrapper is  **shared** by unrelated assignments that the -fm entries become problematic. Consider:

```
1:    f2 := a.PrintSomething
2:    f2("a")
3:    f3 := a.PrintSomething
4:    f3("b")
```

If f3("b") panics in this situation, I would expect it to report an -fm entry on line 3. Instead, it will report an -fm from line 2. Demo: https://play.golang.org/p/QT5pkBEqSS

This is particularly confusing if f2 and f3 reside in separate files / packages. You end up analyzing a stack that has an effectively random file & line for the -fm entry.

**Comment by minux** [comment]
For it to report line 3, each closure must be a distinct function and this
will bloat the binary a lot. Right now, all such closures share code and
that's the reason it's always printing line 1.

**Comment by jupierce** [comment]
Understood. Thanks for looking into it!
