### ISSUE TITLE
flag: panic in flag.PrintDefaults when zero value violates invariants

### ISSUE THREAD

**Issue by creachadair** [golang/go#16694]
(version details below)

Repro: https://play.golang.org/p/UU4V3BQDHA

Note that the playground is currently running an older version that doesn't have this problem. Download the code and use "go run" with a recent 1.7 release candidate (≥ rc3 has the break, as far as I can tell). 

I believe this was introduced by https://github.com/golang/go/commit/3659645cb1f32d7b1eeefdb65f1339fe54f0f6eb

Summary: Given a user-defined type implementing the flag.Getter interface, register a value of the type using flag.Var. In some cases a panic occurs when flag.PrintDefaults tries to print a value for it. This appears to happen because the package is reflectively constructing an empty value of the implementing type—and that value may violate invariants of the original value.

I discovered this because I have a custom flag type whose package provides a constructor to ensure the value is always correct. The reflection bypasses this, of course, and constructs a value that crashes when its methods are called. 

I can work around this by making sure my methods "work" when the invariants are violated, but this is a regression from go1.6 and arguably should be fixed. It's too subtle for a documentation patch.

$ go version
go version go1.7rc6 darwin/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/share/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by creachadair** [comment]
I have also reproduced this with 1.7rc3 on linux/amd64, but I assume you probably don't care about earlier versions that much.

**Comment by ianlancetaylor** [comment]
I'm inclined to just document this restriction.

**Comment by creachadair** [comment]
On Aug 14, 2016, at 20:37, Ian Lance Taylor <notifications@github.com> wrote:
> 
> I'm inclined to just document this restriction.
> 
That seems ugly at best. What problem is solved by requiring the zero to have this subtle property, that would justify such an odd complication?

–M

**Comment by ianlancetaylor** [comment]
The problem fixed by that commit: when the default value of a flag is the zero value, don't report the default value in the usage message.  I don't want to unwind that commit (it's too late to unwind it for the 1.7 release in any case) and I definitely don't want to start catching a panic in that code.

It's a subtle property in this case, but as you know in general we strongly encourage Go types to have valid zero values (https://golang.org/doc/effective_go.html#allocation_new).

**Comment by creachadair** [comment]
I argue that this is contrary to the spirit of the Go 1 guarantee, in that I had code that previously worked and did not depend on any unusual behaviour of the language or the library, and now my code breaks. My code isn't widely-used, so perhaps that doesn't matter.

Granted the wording of the guarantee allows for undefined cases in the API. But since the API is defined to take a _value_ implementing `flag.Value` rather than a _type_, I think that wouldn't be a good use of the exception.

I understand this can't be fixed for the 1.7 release, but I claim it's still a bug, and that documentation isn't an adequate fix in the long term.

**Comment by ianlancetaylor** [comment]
I agree that it's a grey area.

In practice we can not say that we will not break any Go program ever.  That would make it impossible to ever make progress.

In the discussion of issue #14058 we eventually agreed that we would proceed with that change even though it broke existing code.  This problem is a consequence of that decision.
