### ISSUE TITLE
file lock auto closed by go

### ISSUE THREAD

**Issue by galric** [golang/go#16700]
i come across a problem and can not find a same issue, using go1.4 

i used a file lock for process anti-reentry setting it to syscall.LOCK_EX|syscall.LOCK_NB in a function, but this lock would always be auto closed  after 2 minutes

i have attempted to use an struct member variable to store this file descriptor, but it was closed after 2 minites again

i have attempted to use an global variable to store it , and it works.

```
func LockUntilEx(lockfile string) (*os.File, error) {
    var mode os.FileMode = 0777
    file, err := os.OpenFile(lockfile, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, mode)
    if err != nil {
        return nil, err
    }

    err = syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB)
    if err != nil {
        return nil, err
    }

    _, _, errno := syscall.RawSyscall(syscall.SYS_FCNTL, file.Fd(), syscall.F_SETFD, syscall.FD_CLOEXEC)
    if errno != 0 {
        return nil, errors.New(fmt.Sprintf("fail to set FD_CLOEXEC, for ", lockfile))
    }
    return file, nil
}
var usefulLock *os.File

type TestLock struct {
    uselessLock *os.File
}

func (this *TestLock) Lock() (err error) {
    path := "/tmp/filename"
    this.uselessLock, err = LockUntilEx(path)
    if err != nil {
        return err 
    }   
    return nil 
}

func  Lock() (err error) {
    path := "/tmp/filename"
    uselessLock, err := LockUntilEx(path)
    if err != nil {
        return err 
    }   
    fmt.Println("lock succ ", uselessLock)
    return nil 
}

func main() {
    l := new(TestLock)
    if err := l.Lock(); err != nil {
        fmt.Println(err)
        return
    }   
    for {
        fmt.Println(time.Now())
        time.Sleep(time.Second)
    }   
}
```

my questions are:
1.  is this file descriptor closed by gc? why struct member variable closed and global variable not? 
2. is there any suggested way to use file lock

**Comment by davecheney** [comment]
Yes, your file descriptor is being closed when all references to the
os.File you created to lock goes out of scope.

**Comment by galric** [comment]
when i used member variable of a struct to store this  os.File object, it was also closed even if the struct object not out of scope

**Comment by davecheney** [comment]
Can you provide a complete runnable example?

**Comment by RLH** [comment]
The GC and the compiler are conspiring here to do their best to clean up a
program that does not close a file. "Their best" in this case means that
the compiler notices that "l" is dead after line 3 in main. The GC notices
that it hasn't done a GC is a long time so it executes a GC. The GC
correctly notices that "l" is no longer live and the referent is collected.
The GC sees that the file that has not been closed so it runs a finalizer
that closes the file.

All this could have been avoided if the program simply closed the file
instead of relying on when the GC and finalizers are run and how good the
compiler is about identifying dead variables.

Your questions.
my questions are:
1. is this file descriptor closed by gc? Yes, by the finalizer.
 why struct member variable closed and global variable not?
    The compiler thinks the global variable is live. The compiler can prove
the local variable is dead. The GC relies on this information.
2. is there any suggested way to use file lock
    If a program opens a file, close the file. Never rely on a finalizer,
they will cause pain. "Never rely on a finalizer to close a file" is an
instance of the more general statement "Never rely on a finalizer". Sure
sometimes a program has no choice but finalizers should never be the first
choice.

The compiler and the GC will keep getting smarter. In this case 1.7 figured
out that "l" is dead after line 3.

**Comment by bradfitz** [comment]
Closing, since this is more of a question than a bug report. It's also about a quite-old release of Go.

(Question policy: https://golang.org/wiki/Questions)
