### ISSUE TITLE
unsafe: allow Offsetof for array entries

### ISSUE THREAD

**Issue by randall77** [golang/go#16740]
It would be nice if `unsafe.Offsetof` could handle array entries as well as struct fields.
```
package main

import "unsafe"

type T struct {
	a int
	b [3]int
}

func main() {
	println(unsafe.Offsetof(T{}.b))
	println(unsafe.Offsetof(T{}.b[1]))
}
```
At the second line of main, I get an invalid expression error:
```
go/tmp1.go:12: invalid expression unsafe.Offsetof((T literal).b[1])
```
@griesemer @mdempsky

**Comment by randall77** [comment]
@edressel

**Comment by randall77** [comment]
See #16727

**Comment by mdempsky** [comment]
Note that currently Offsetof(a.b.c) tells the offset of c from a.b, not from a.  So to be consistent, in your example, Offsetof(T{}.b[1]) would be 4 (the offset from T{}.b), not 8 (the offset from T{}).

**Comment by griesemer** [comment]
A minor language change, would be backward-compatible.

**Comment by randall77** [comment]
Another tricky bit: should we require the index to be constant?  If not, then there's some evaluation that needs to happen inside the Offsetof(), which is contrary to what Offsetof does now.

@mdempsky : I didn't realize that it only applied to the last field.  That's surprising.

**Comment by randall77** [comment]
So if Offsetof only works on the last offset, then this proposal isn't useful.
Offsetof(a.b.c[2]) would be the same as 2 * Sizeof(a.b.c[0]).
Or maybe it could do the last two offsets if the last one was an index, so at least a.b[2] would work.  But this is getting weird, I'm just as inclined to drop it.

**Comment by mdempsky** [comment]
FWIW, I've brainstormed before about extending Offsetof to take two parameters like C++'s offsetof operator.  Then you could write Offsetof(a, b.c) vs Offsetof(a.b, c) to distinguish intent.

It would be a bit awkward though because then "b" in Offsetof(a, b) doesn't actually refer to a free variable b.  Not a problem per se, but some tools might need to be aware of that.

It also wouldn't work for array indexes since Offsetof(a, [1]) isn't currently valid syntax, but at least Offsetof(T{}, b[1]) would be.
