### ISSUE TITLE
go/internal/gcimporter: detect and gracefully fail on old versions

### ISSUE THREAD

**Issue by josharian** [golang/go#16881]
gcimporter does not fail gracefully when it encounters old versions. This trips up a lot of people--they think it's a bug, and do not think to re-install the relevant packages (why would they?). Related bugs: #16879 and #16859 and #16112 and #15728 and #16826 and #16781 and lots more. I think at this point some kind of fix, even a kludgy one, is called for.

The best case scenario, to my mind, is that importers just work (#10276). Failing that, gcimporter should treat the input package as potentially hostile (i.e. as user input) and on error, suggest a package re-install. Failing that, gcimporter should explicitly check for and recognize known prior versions and suggest a package re-install.

**Comment by griesemer** [comment]
The new export format does recognize old versions and does try to work gracefully around them.

Many of the prior issues had to do with the transition from textual to binary format. The textual format had no versioning, and the binary format was in development, with people using mixes of the two, and sometimes even mixes of two different binary formats.

The "gracefully working around issues" was done only partially (in x/tools/gcimporter) as I (wrongly) assumed that people would always re-build when working at tip (we don't guarantee anything across different compilers). That's obviously not the case.

The trivial solution is to bail with an explicit error requesting recompiles - at least when working at tip. It's a bit more complicated than that because x/tools/gcimporter15 also needs to work on tip but also legacy installed packages.

On it.

**Comment by dolmen** [comment]
This issue (and how to fix it: what must be rebuilt/reinstalled) should be mentionned in Go 1.7 release notes.
