### ISSUE TITLE
go/printer: Fprintf uses different settings than go fmt 

### ISSUE THREAD

**Issue by kevinburke** [golang/go#16963]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7

### What operating system and processor architecture are you using (`go env`)?

All

### What did you do?

If I write a Go file with go/printer.Fprintf, structs get printed like this - I've replaced the tab characters with `\t` so it's clear what is going on.

```
type User struct{
\tName\t\tstring
\tLongConfig\tuint
}
```

If you immediately run `go fmt ./...` on the file, some of the tabs are replaced by spaces:

```
type User struct{
\tName        string
\tLongConfig  uint
}
```

`go/printer.Fprintf` uses the following default printer.Config argument: 

```go
return (&Config{Tabwidth: 8}).Fprint(output, fset, node)
```

However, `go fmt` uses this config argument:

```go
const (
	tabWidth    = 8
	printerMode = printer.UseSpaces | printer.TabIndent
)

// ...

res, err := format(fileSet, file, sourceAdj, indentAdj, src, printer.Config{Mode: printerMode, Tabwidth: tabWidth})
```

### What did you expect to see?

I expect the two "default" functions to print the file the same way

### What did you see instead?

One prints with tabs in the middle and one doesn't. This led to a lot of thrash when running anything automated over the codebase; I noticed this first as part of the investigation for https://github.com/Shyp/bump_version/pull/1.

Far more people run `go fmt` than write AST parsing/hacking functions, so it seems like the fix, if there is to be one, should be to have `printer.Fprintf` match the `go fmt` behavior.

**Comment by kevinburke** [comment]
I've signed the CLA and happy to submit a fix, but not sure if this would count as a breaking API change.

**Comment by quentinmit** [comment]
Changing this seems reasonable to me. In general, we shouldn't make breaking changes to the format, but since it would be to match what `go fmt` already does, I think I agree that it's a net win.

**Comment by kevinburke** [comment]
@griesemer - thoughts? Maybe I should just submit a patch?

**Comment by griesemer** [comment]
@kevinburke My apologies but I haven't looked into this yet as it doesn't seem urgent. I will look into this in the next couple of days.

**Comment by griesemer** [comment]
@kevinburke I agree there's a discrepancy.

The intention behind the printer's default settings was to produce tab-aligned output. gofmt's fine-tuning (using blanks for all alignment but indentation) came later. (There was a long period of trial and error with gofmt's settings before it eventually settled to what we have now).

I'd be somewhat reluctant to change the settings here simply because I don't know how much code depends on what's here now.

Instead, I'd recommend that you use go/format (format.Node) instead of printer.Fprint. It has the same signature and it supposed to produce gofmt-compliant output.

If you're ok with this answer I'll close this issue. Otherwise, please raise your objections. Thanks.

**Comment by bradfitz** [comment]
Maybe documentation somewhere saying a short version of that?
