### ISSUE TITLE
x/crypto/openpgp: encrypt private key documentation missing

### ISSUE THREAD

**Issue by acasajus** [golang/go#16994]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go version go1.7 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/acasajus/Devel/gospace"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_m/s8xbjvsx05d7g5vm9b0wlsc00000gn/T/go-build341779350=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### What did you do?

Tried to encrypt a openpgp.packet.PrivateKey and dump it in a PGP armor. 
### What did you expect to see?

An example on how to do it. I haven't found any way to do it. I would like a pointer in how to export a private key encrypting it with a passphrase. The inverse of openpgp.packet.PrivateKey.Decrypt.
### What did you see instead?

No information on how to do it.

**Comment by odeke-em** [comment]
From https://github.com/golang/go/issues/16664 it seems like encrypting Private keys is not yet implemented so IMO this issue is a feature request for something non-existent right now, thus we should merge it into #16664. What do y'all think?

**Comment by asminozhka** [comment]
and... where is it?

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
