### ISSUE TITLE
cmd/go: improve the "no buildable Go source files" message

### ISSUE THREAD

**Issue by rakyll** [golang/go#17008]
Consider the following main source file:

```
// +build cgo

package main

func main() {

}


$ CGO_ENABLED=0 go build .
go build hello/subtests: no buildable Go source files in /Users/jbd/src/hello/subtests
```

The error message is very unfriendly for the new comers. It should better say "no buildable Go sources for buildtags=%q". And the user can double check if they are setting all the build tags right or will understand that the package is not supporting their build tag combination.

**Comment by quentinmit** [comment]
I suggest only changing the error message if there was a source file that was ignored due to build tags. Otherwise I think it will confuse new users to see the build tags.

**Comment by rakyll** [comment]
(It might be beyond the scope of this bug, but it might be nice to think how the go tool can report a package's build tags.)

**Comment by davecheney** [comment]
I agree, there are 7 implicit build tags applied quietly by the go tool,
go1.1, go1.2, etc. Any failure message would have to include those tags as
well as any supplied and that's going to be super confusing for newcomers,
not to mention the implicit GOOS and GOARCH tags. Especially as they cannot
see where those tags are defined or how to turn them off or on.

**Comment by ironiridis** [comment]
What about simply mentioning "(some files were excluded due to unmet build tags)"?

**Comment by rakyll** [comment]
@ironiridis, it sounds like a good and easy-to-implement idea. I will create a CL.

**Comment by minux** [comment]
If we fix it again, perhaps we should just make go build -x
show the reason for each ignored file.

$ go build -x cmd/go
# file cmd/go/bootstrap.go ignored due to build tag cmd_go_bootstrap not
satisfied.
WORK=/tmp/go-build638479375
mkdir -p $WORK/cmd/go/_obj/
...

Not only it's clearer, it will actually help more you're debugging
a build tag problem. Right now it's very hard to debug such
problems (precisely because usually it's caused by a typo,
and it's really really hard for people to spot such things.
and this will also help if we introduce a new GOOS, and
make some random x_NEWGOOS.go excluded. People
who debug this issue might not know about this new GOOS)
