### ISSUE TITLE
cmd/cgo: add ability to run C function pointers in Go

### ISSUE THREAD

**Issue by stgleb** [golang/go#17096]
Quote from https://golang.org/cmd/cgo/

``Calling C function pointers is currently not supported``

Is there any plans to add ability to run C function pointers passed to Go code?

**Comment by ianlancetaylor** [comment]
If you can work out how to do it safely, then, sure, I don't think anybody would object to adding this feature.  I dropped the proposal label because I don't see this as something that needs to go through the proposal process.  The problem here is not a concern about whether it is a good idea, but a concern as to whether it is possible at all.  A call to a C function needs to change stacks and change the calling convention, so it's not simple.

**Comment by stgleb** [comment]
@ianlancetaylor Thanks, yep, that might be difficult, i just would like to have it for passing python callbacks wrapped with ctypes.Function to golang code, likewise we can do with C.

**Comment by quentinmit** [comment]
If you're willing to write cgo, you can always just write a function in a comment in the cgo file that takes a void* and calls it, no?

**Comment by stgleb** [comment]
@quentinmit , do you mean write function signature only? I'm not sure about that, I will be very grateful if you provide a code snippet.

**Comment by stgleb** [comment]
Thanks, i've found a way to do it, not very straightforward, but works
