### ISSUE TITLE
cmd/gofmt

### ISSUE THREAD

**Issue by tmatsuo** [golang/go#17196]
### What version of Go are you using (`go version`)?

go version go1.7rc3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/tmatsuo/go"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build401308622=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

My gofmt formats spaces around operator differently.

```go
package main

import (
        "fmt"
        "time"
)

func main() {
        time.Sleep(8 * time.Second)
        err := fmt.Errorf("test", time.Sleep(8*time.Second))
}
```

### What did you expect to see?

I expect consistent rules about spaces around operators like:

```go
package main

import (
        "fmt"
        "time"
)

func main() {
        time.Sleep(8 * time.Second)
        err := fmt.Errorf("test", time.Sleep(8 * time.Second))
}
```

**Comment by griesemer** [comment]
Formatting of expressions depends on nesting. A multiplication stand-alone is formatted "a * b", but together with other lower-precedence operators is formatted as "a*b + c"; etc.

Working as intended.

**Comment by griesemer** [comment]
PS: To be fair, one might argue that in this case, since we have a single argument, it is incorrect. See also: https://play.golang.org/p/LYF_I6JW0J . But we've been living with this for years now; changing it would cause unnecessary formatting changes in a lot of code and lead to unnecessary churn. Let's leave this for the future (perhaps as part of a larger gofmt format update). Unfortunate.

**Comment by tmatsuo** [comment]
Yeah I can live with that. Thanks for the explanation.
