### ISSUE TITLE
doc: minimum versions info

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17215]
I created https://github.com/golang/go/wiki/MinimumRequirements to document minimum OS/kernel and arch notes.

Can I get some eyeballs & corrections for it?

@ianlancetaylor, @minux, @cherrymui, @mikioh, @mundaym?

**Comment by minux** [comment]
Our installation docs says we need Linux 2.6.23+, but that's architecture
dependent. For example, ppc64le requires a much more recent kernel, and I
remember we also require a very recent kernel for the s390x port (due to a
kernel bug exposed by Go.)

If we do document the minimum linux kernel for each architecture, it makes
sense to have a builder at that version to catch regressions. I think it's
highly unlikely that all.bash could actually pass on 2.6.23 today.

**Comment by minux** [comment]
And establishing the minimum requirement is pretty hard, especially for
slower builders and non-x86 platforms (we are more limited by the first
kernel to support the given SoC/platform than actual kernel API
requirements.)

Instead, I suggest we document the minimum tested kernel version for each
architecture.

Opinions?

**Comment by bradfitz** [comment]
Definitely what the minimum tested is.

But I think what the minimum might be is also valuable, as long as we're honest that it might be untested.

**Comment by mikioh** [comment]
I think we can use https://github.com/golang/go/wiki#platform-specific-information for people who need more detailed information. Having another page for describing QA?-passed platforms is fine.

**Comment by bradfitz** [comment]
Closing this. We've been using this wiki page for some time now.
