### ISSUE TITLE
Remove inappropriate "references" words in go faqs.

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#17228]
### What did you expect to see?

The meaning of the word "reference" in Golang is totally different from other languages.
In Golang, "reference" means a pointer referring another value.
There is no reference values in Golang (if pointers are not viewed as reference values).

In the faq, maps, slices, and channels references are viewed as reference values (https://golang.org/doc/faq#references), this is inappropriate and will make many confusions in the process of learning Go.

In fact, maps, slices, and channels (and function values) are all wrappers of pointers. They are just normal internal struct values.

I proposal to replace the question "why are maps, slices, and channels references while arrays are values" with an appropriate one, which will explain the internal structure of maps, slices, and channels. 

Remove the "reference value" concept is good to unify the definitions and make the docs clear.

### What did you see instead?

There are 4 occurrences of "references", 3 of them are inappropriate.

**Comment by bradfitz** [comment]
This has been discussed ad nauseam in various forums. If there were a single definition of any of these words, we'd use the obvious words. But there are a dozen possible meanings of these words depending on the reader's background.

I think we're done changing this for now, sorry.

**Comment by minux** [comment]
Our usage of reference is actually correct. It's C++ that assigns another
meaning to the word. Even C uses "reference" and "dereference" for pointers.

**Comment by yaxinlx** [comment]
@minux, it is ok to call pointers as reference values, but it is not ok to call maps/slices/channels as references.

**Comment by cespare** [comment]
Related to #5083.

**Comment by minux** [comment]
Why? map/slices/channels is actually behaving more like C++'s
reference than regular pointers.

**Comment by yaxinlx** [comment]
By calling map/slices/channels reference values, is the reason for they are pointer wrappers?
If this is the reason, then any custom struct values containing pointer fields should also be called reference values. The docs shouldn't make map/slices/channels look special on this point.

With the reference concept in docs, it gives people the impression that the implementations of Map/Slice/Channel are different from Struct. In fact, there is no differences. 

The docs for syntax should be as simple and consistent as possible. By eliminating the reference concept, the docs will be more clear.

**Comment by minux** [comment]
You can think of C++ references are a struct wrapping a pointer, which
is passed as value as whole. In fact, the map and channel act exactly
as C++ reference to underlying runtime implementation of map and
channel.

**Comment by yaxinlx** [comment]
@minux, c++ references are just const pointers but fake as not in most implementations. 
In fact, maps and channels in Golang are very possibly implemented like this. (for slices, surely not)

The problem of the go docs is not to choose a proper word to describe the implementation. 
It is how to choose an more consistent explanation for map/slice/channel values.
Again, my opinion is it is unnecessary to choose a word to make maps/slices/channels as special values.

**Comment by randall77** [comment]
The reason to distinguish "reference" types in the documentation is because they really are different than other types (I'll call the non-reference types "value" types.  For example, `complex128`).  For reference compound types you don't get the whole compound object.  You only get part of it, the rest of it is possibly shared among other values in the program.  As such, operations on those types can observe aliasing among other modifications of that object in different functions or even goroutines.

In other words, "reference" means there's a pointer hidden in there somewhere, and assignments like "a = b" copy the pointer but don't copy the pointed-to shared part of the compound object.

If you defined your own type with a pointer in it, and the pointed-to data was not copied by the Copy method you define on your type, then that's a reference type (if the type has mutators - otherwise the missing copy is not observable, as it is for Go strings and interfaces).  So a `struct` can be a reference type, depends on how you use it.  The language can't call it that, of course, because it isn't always.  (In fact, it seldom is.)

I'm not wedded to the word "reference", but there needs to be some distinguishing word for that concept.

**Comment by yaxinlx** [comment]
@randall77, if I define an exported struct type which contains a non-exported pointer field, can I call it a reference type in another package?

**Comment by minux** [comment]
You confused the general concept of reference types (as compared to value
types, as explained by Keith), with the language level construct of
reference
types (which Go doesn't have). Those two are different.

**Comment by yaxinlx** [comment]
ok, looks our opinions are generally the same. The small difference is I think it is not a good explanation to just say maps/slices/channels are different for they are reference values in the faq. 
The faq should make further explanation how Map/Slice/Chan types are represented internally (just show they are pointer wrappers is ok, no need to make detailed explanation).

The current faq makes people think maps/slices/channels are the only reference values in Golang. (In fact, I ever encountered many go developers who think so). 

I think, the faq will be more clearer and eliminate much confusing if it both states:
1. all value assignments in Golang are shallow copies
2. Map/Slice/Channle are just pointer wrappers.

**Comment by yaxinlx** [comment]
@minux, sorry, I misunderstood your words in your first comment.
