### ISSUE TITLE
x/text/secure/precis: too many allocations

### ISSUE THREAD

**Issue by robpike** [golang/go#17423]
The x/text/secure/precis package allocates several times, even when there is literally no work to do. For a plain ASCII identifier, which is a very common case, it could return the original string, and discover cheaply that it can do so.

% cat x_test.go
package x

import (
    "testing"

```
"golang.org/x/text/secure/precis"
```

)

func TestPrecisMallocs(t *testing.T) {
    t.Fatal(testing.AllocsPerRun(100, func() { precis.UsernameCasePreserved.String("helloworld") }))
}
% go test 
--- FAIL: TestPrecisMallocs (0.00s)
    x_test.go:10: 6

**Comment by SamWhited** [comment]
Now that @mpvl has added spanning transformers to reduce allocations and I've added an ASCII fast path to make things quicker in the all-ascii case, can this issue be marked as resolved, or are there any other big tasks remaining that should be tracked as part of this issue instead of having their own?

**Comment by robpike** [comment]
Seems good to me.
