### ISSUE TITLE
cmd/compile: imag(0) is valid but not accepted

### ISSUE THREAD

**Issue by griesemer** [golang/go#17446]
```
package p
var _ = imag(0)
```

doesn't compile:

```
$ go tool compile y.go
y.go:2: invalid argument 0 (type int) for imag
```

But it's clearly accepted by the spec ("If the argument evaluates to an untyped constant, it must be a number, and the return value of the function is an untyped floating-point constant."). Both gotype and gccgo accept it.

**Comment by griesemer** [comment]
See also #17398 (indirectly related).

**Comment by odeke-em** [comment]
I think when we fix this issue, we should also pay attention to https://github.com/golang/go/issues/11945 because fixing that mentioned issue will mean that
imag(0) will return an untyped value instead of a floating point constant not as the spec is quoted in https://github.com/golang/go/issues/17446#issue-183120570
```
But it's clearly accepted by the spec ("If the argument evaluates to an untyped constant, it must be
a number, and the return value of the function is an untyped floating-point constant."). Both gotype 
and gccgo accept it.
```

**Comment by josharian** [comment]
When we test this, make sure to test real too: `const x = real(0)`. (go-fuzz just re-found this bug.)
