### ISSUE TITLE
cmd/compile: go build -race fails with `label .inlret7 already defined`

### ISSUE THREAD

**Issue by adamfaulkner** [golang/go#17449]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/repos/server/go:/home/adamf/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build433458907=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

`cat /tmp/master/compiler_bug.go`
```
package master

type PriorityList struct {
	elems []interface{}
}

// Implement sort.Sort interface to sort a PriorityList by ascending Priority.
func (x *PriorityList) Len() int { return len(x.elems) }

func (l *PriorityList) remove(i int) interface{} {
	elem := l.elems[i]
	l.elems = append(l.elems[:i], l.elems[i+1:]...)
	return elem
}

// Removes the next element from the list, in order of priority (e.g. higher priority first).
// Returns nil if list is empty.
func (l *PriorityList) Next() interface{} {
	// The last element from the list has the highest priority.
	return l.remove(l.Len() - 1)
}

var l *PriorityList

func Foo() {
	for elem := l.Next(); elem != nil; elem = l.Next() {
	}
}
```

`go build -race /tmp/master/compiler_bug.go`
```
/tmp/master/compiler_bug.go:26: label .inlret7 already defined at /tmp/master/compiler_bug.go:26
```

### What did you expect to see?
I expected it to successfully build this program.

### What did you see instead?
```
/tmp/master/compiler_bug.go:26: label .inlret7 already defined at /tmp/master/compiler_bug.go:26
```

Restructuring the code in various ways makes this go away. For instance, rewriting the for loop as
```
elem := l.Next()
for elem != nil {
    elem = l.Next()
}
```

will make the compiler error go away. Also, disabling the race detector or trying with go 1.6 will make this go away. Similarly, "inlining" the Len() call will make this go away.

**Comment by dhananjay92** [comment]
Looks like race instrumentation duplicates the labels created for function inlining.


Confirmed with following steps. Assuming pwd is `/src/`, compile with:
  1. **Inlining enabled and race detection disabled**: No issues, compiles just fine.

    ```shell
    $ ./../pkg/tool/linux_amd64/compile ~/tmp/race/race.go
    ```
  2. **Inlining and race detection both enabled**: Fails to compile. Notice ".i4" is repeated in dumped code.

    ```shell
    $ ./../pkg/tool/linux_amd64/compile -race ~/tmp/race/race.go
    ```
  3. **Inlining disabled and race detection enabled**: Compiles just fine.
    
   ```shell
    $ ./../pkg/tool/linux_amd64/compile -race -l ~/tmp/race/race.go
    ```

I also dumped the function [before and after race instrumentation](https://github.com/dhananjay92/go/commit/98b22bc14105e1c3f0e01c64d3eb7610004fbf38). Side by side diff of generated codes is at https://www.diffchecker.com/68vuYuaq. Notice that label (and corresponding GOTO statement) `.i4` is repeated in right side. (In master, inline-labels are of format `.iX`, where X is some number.)


Looking into how to prevent this.

**Comment by dhananjay92** [comment]
Okay, so code duplicated by race instrumentation is more than just inline-label.

[Here](https://gist.github.com/dhananjay92/936885ee83e40e6d3e358402947aed28#file-1-human-readable-ultra-clean) is a human readable form of dumped code after race instrumentation. Notice that code between `ORIGINAL CODE BEGINS` and ` ORIGINAL CODE ENDS` is repeated inside `AS-init` block (marked with `REPEATED CODE BEGINS/ENDS`). 

This happens because in [`instrumentnode()`](https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/racewalk.go#L166), it copies parent's generated nodes to `outn` and then [appends `outn` to child's `Ninit`](https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/racewalk.go#L172). This copies over all the parent block's generated nodes so far which in this case includes inline-label, `i4`. 

I have a solution at https://github.com/dhananjay92/go/commit/7b1b24d58da6477243f243b902dbd7bbbb1eac1d. It passes all the tests and compiles this code successfully, but I am not sure if that's good enough.

(Side note: [Another file](https://gist.github.com/dhananjay92/936885ee83e40e6d3e358402947aed28#file-2-dumped-code-with-manually-added-pseudo-code) that shows `<output of Dump()> : <human readable pseudo code>`.)

**Comment by dhananjay92** [comment]
*Adding some folks who last modified that part of racewalk.go*

@ianlancetaylor @dr2chase : Can you confirm if [the potential solution](https://github.com/dhananjay92/go/commit/7b1b24d58da6477243f243b902dbd7bbbb1eac1d) is good enough to be sent for review? Other than running tests and manual inspection of generated code, how can I tell if the code is working correctly?

**Comment by ianlancetaylor** [comment]
There's no need for pre-review of a change review.  We are used to reviewing in Gerrit, so it will be easier for us if you simply send the change following the guidelines at https://golang.org/doc/contribute.html .

Your patch should include a new test.

**Comment by dhananjay92** [comment]
Sent it for review with test : https://go-review.googlesource.com/#/c/31317/

**Comment by dhananjay92** [comment]
Who should I add as reviewer?
