### ISSUE TITLE
json: Cannot expand this json into a struct 

### ISSUE THREAD

**Issue by nemothekid** [golang/go#17521]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
play/`go version go1.6.2 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nimi/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
https://play.golang.org/p/pUe-e0u6cf

### What did you expect to see?
sLabel.Value should be filled with a value.

### What did you see instead?
Its empty

**Comment by odeke-em** [comment]
Hello there @nemothekid, the issue there is that your sLabel field is an unexported value, making it SLabel instead of sLabel, makes in unmarshal-able. Please see https://play.golang.org/p/pmsIs2GW0O,

 The Unmarshal docs talk about it that Unmarshal will only set exported fields.
<img width="1011" alt="screen shot 2016-10-19 at 10 56 05 pm" src="https://cloud.githubusercontent.com/assets/4898263/19547787/3fa66d98-964f-11e6-8473-bb20d30b4d1c.png">

Also we use the issue tracker for tracking bugs, you can post questions on the mailing list https://groups.google.com/forum/#!forum/golang-nuts.

**Comment by nemothekid** [comment]
Ah, sorry - such an obvious mistake in hindsight. I've been staring at that piece of code for far too long.
