### ISSUE TITLE
x/arch/ppc64/ppc64spec: build fails on 386

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17635]
The x/arch subrepo is broken for 386:

```
freebsd-386-gce101 at 2f6557233c5a5c311547144c34b4045640ff9f71 building arch at fcea5eadff8971892040173c479da59c6f11436a

ok      golang.org/x/arch/arm/armasm    0.009s
?       golang.org/x/arch/arm/armmap    [no test files]
ok      golang.org/x/arch/ppc64/ppc64asm    0.005s
?       golang.org/x/arch/ppc64/ppc64map    [no test files]
# golang.org/x/arch/ppc64/ppc64spec
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:146: undefined: pdf.Outline
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:153: undefined: pdf.Outline
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:174: undefined: pdf.Page
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:271: undefined: pdf.Content
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:271: undefined: pdf.Text
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:396: undefined: pdf.Rect
```

/cc @odeke-em

**Comment by odeke-em** [comment]
Interestingly when I cross-compile it on my Mac, I don't get any problems
<img width="578" alt="screen shot 2016-10-28 at 12 09 25 am" src="https://cloud.githubusercontent.com/assets/4898263/19797933/e235988c-9ca2-11e6-85e5-dc6e03bba31d.png">

Perhaps we need to refresh the code on the builders with `go get -u` since the code that introduces rsc.io/pdf was added 16 days ago with commit https://github.com/golang/arch/commit/21375ab36ac3450884ce73b7b4bc00cb75416f7f

**Comment by bradfitz** [comment]
The builders don't run `go get -u`. They live in a hermetic world and test exactly what's in the repo.

**Comment by odeke-em** [comment]
Ah gotcha, I see that now they have vendored code that was last updated on July 15 2016 https://github.com/golang/arch/commits/master/vendor.

**Comment by odeke-em** [comment]
Got it, mailed https://go-review.googlesource.com/32241.
