### ISSUE TITLE
cmd/compile: "<T> literal" in error messages for type literals that don't type check

### ISSUE THREAD

**Issue by dominikh** [golang/go#17645]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go version go1.7.3 linux/amd64
go version devel +b679665 Fri Oct 28 07:58:47 2016 +0000 linux/amd64
### What did you do?

https://play.golang.org/p/gGiuxRMO-h
### What did you expect to see?

```
main.go:9: cannot use "" (type string) as type int in field value
main.go:9: cannot use append(s, Foo literal) (type []int) as type string in assignment
```
### What did you see instead?

```
main.go:9: cannot use "" (type string) as type int in field value
main.go:9: cannot use append(s, <T> literal) (type []int) as type string in assignment
```

**Comment by dhananjay92** [comment]
It should give three errors.
```
main.go:9: cannot use "" (type string) as type int in field value
main.go:9: cannot use Foo literal (type Foo) as type int in append
main.go:9: cannot use append(s, Foo literal) (type []int) as type string in assignment
```

**Root cause:** [`typecheckcomplit()`](https://github.com/golang/go/blob/833f57ed502d686ce054ff557cf3bf5b6ed1a1d2/src/cmd/compile/internal/gc/typecheck.go#L3116&q="n.Type = nil") nils out the `n.Type` upon finding new errors. That hides new errors in children node as well as the type info of current node. Sending out the fix.
