### ISSUE TITLE
go/types: investigate representation of byte/rune as aliases

### ISSUE THREAD

**Issue by griesemer** [golang/go#17656]
Tracking issue.

**Comment by griesemer** [comment]
cc: @alandonovan

**Comment by alandonovan** [comment]
I can't see how this can be done without breaking the API.  

In any case, the go/types API already uses a representation that deviates from the concepts of the spec in a couple of places.  For example, predeclared types like `int` are named types, but are not represented by `types.Named` because... what would be its underlying type?.  And `unsafe.Pointer` is a pointer type, but is not represented by `types.Pointer` because... what its its element type?  These design choices are clearly trade-off but are not obviously wrong.  Not representing `rune` and `byte` using `types.Alias` provides clients with the invariant that Alias.Orig returns a package-level const/var/func/type object.

**Comment by griesemer** [comment]
Proposal #16339 was declined and the implementation removed.
