### ISSUE TITLE
time: Zero value of time.Month fails to print

### ISSUE THREAD

**Issue by kokes** [golang/go#17720]
### What version of Go are you using (`go version`)?

`go version go1.7 windows/amd64`

### What did you do?
I set a variable I was to reuse, `var m time.Month`, but forgot to set it. When printing everything to check my inputs, `fmt.Println` panicked.

A trivial replication: https://play.golang.org/p/lGKrw6nBb3

### What did you expect to see?
A printed zero value for my month.

### What did you see instead?

`%!v(PANIC=runtime error: index out of range) 0`

### Discussion

If one initiates `time.Month` without setting it to a specific month, it fails to print, because int defaults to zero, but months are expected to be within [1, 12], so the `String()` method goes out of bounds on the slice of prepared strings.

I don't think the zero value can feasibly be January, because while that would solve the String() issue, comparisons to `time.January` would not work (since `time.January` is `time.Month(1)`). Perhaps prepending the [`months`](https://golang.org/src/time/time.go#L94) array with something (not sure if there's a precedent for this) and changing the String() method from `func (m Month) String() string { return months[m-1] }` to `func (m Month) String() string { return months[m] }` might be enough.

**Comment by martisch** [comment]
I do not think changing the array and using months[m] is generally enough since month=99 will return a similar error. And if we change it we should make sure all invalid values are handled.

Open question would be what an invalid month (including the zero value) should print as error string instead. If there is a better agreed answer than a printing a runtime error then we can change the String method to print that for invalid values.

The same question can be asked for the weekdays String method too.

**Comment by kokes** [comment]
Good point. Shall we perhaps use `stringer` to generate all the months and weekdays? (Weekday's zero value prints just fine, because it's Sunday, but no other invalid values do.)

Running `stringer` within the `time` package for these two types results in [these generated files](https://gist.github.com/kokes/b3adb1e0438b40b8d1b76a90be03e434). I presume these would need to get checked in, since stringer is not within the standard toolkit. Also, existing `String()` methods need to be deleted then.

**Comment by martisch** [comment]
I do not think Stringer helps or does make the code better. I rather keep the string array. It is more readable and simpler at least to me. I think the issue is not with the string array as such but what to print or do when the value String should print is outside the valid range.

We can then do something like:

```
if 0 < i && i < len(months)-1 {
    // valid value
    return[m-1]
}
// invalid value
?
```

Your proposed solution for ? seems to be to return fmt.Sprintf("Month(%d)", i+1).

However as outlined above this will print "Mon" when truncated by methods that call String() and just truncate the returned string s[:3]. Which can even be confused for Monday in a date format.

**Comment by bradfitz** [comment]
No need for stringer. Just add a simple `if m < 1 || m > 12`. I agree that `s[:3]` returning `Mon` for `Month(0)` or `Month(15)` could be confusing. Maybe `%!Month(0)`, similar to the bogus fmt Printf style.
