### ISSUE TITLE
go/constant: passing nil to BinaryOp or Compare panics with `unreachable`

### ISSUE THREAD

**Issue by dominikh** [golang/go#17812]
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What did you do?
https://play.golang.org/p/G0V0HApS-t

### What did you expect to see?
true

### What did you see instead?
```
panic: unreachable

goroutine 1 [running]:
panic(0x122680, 0x1050a130)
	/usr/local/go/src/runtime/panic.go:500 +0x720
go/constant.ord(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/constant/value.go:865 +0xa0
go/constant.match(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/constant/value.go:875 +0xc0
go/constant.Compare(0x0, 0x0, 0x27, 0x0, 0x0, 0x200, 0x0, 0x3274)
	/usr/local/go/src/go/constant/value.go:1179 +0x80
main.main()
	/tmp/sandbox842734224/main.go:10 +0x40
```

I don't know if an untyped nil is a valid constant.Value – I obtained it from a `*ssa.Const.Value` from the following typechecked package, the BinOp specifically:

```
package foo

func foo() {
	_ = (interface{})(nil) == (interface{})(nil)
}
```

which compiles to

```
func foo():
0:                                                                entry P:0 S:0
	t0 = nil:interface{} == nil:interface{}                            bool
	return
```

If nil is valid, no panic should occur. If nil is not valid, it should have a more descriptive panic, and go/ssa might have a bug of its own.

/cc @alandonovan @griesemer

**Comment by griesemer** [comment]
nil is not a valid go/constant Value. In general, we don't describe in every package that nil is not valid - we usually describe when nil is valid. We also don't test every single impossible value (see https://play.golang.org/p/O62KzUF86T for instance). The documentation says "The comparison must be defined for the operands." - admittedly vague but it's clear to expect the unexpected otherwise.

**Comment by dominikh** [comment]
@griesemer Should I file a bug for go/ssa instead, or is it also expected that an `*ssa.Const.Value` can be nil?

**Comment by griesemer** [comment]
In retrospect I agree that the error message is wrong: That code clearly is reachable after all, even if it means incorrect input. I will fix that.

And yes, if go/ssa produces a nil constant Value it probably should say that either nil is possible and means "no constant value", or there's a bug (documentation or otherwise).

**Comment by dominikh** [comment]
I.e. is https://play.golang.org/p/ONBGaMJD1d valid and expected to disagree with `go/constant`'s definition of a valid Value?

**Comment by alandonovan** [comment]
The ssa and `go/constant` packages are both working as intended.

The constant package does not allow nil operands to its functions.  (When a Go function accepts optional arguments or nil, this is usually explicitly documented and in the absence of documentation it should be assumed unsafe.)

The ssa package uses a nil `constant.Value` to indicate a typed nil value, even though nil is not a constant according to the language spec.  See https://godoc.org/golang.org/x/tools/go/ssa#Const:

> [...] a Const may represent the nil value of any reference type---interface, map, channel, pointer, slice, or function---but not "untyped nil". [...] Value holds the exact value of the constant, independent of its Type(), using the same representation as package go/exact uses for constants, or nil for a typed nil value.

As a result, you must check the ssa.Const.Value field is non-nil before passing it to a function such as `constant.Compare`.
