### ISSUE TITLE
usage of golang comments in language spec

### ISSUE THREAD

**Issue by bamarni** [golang/go#17829]
As mentioned [here](https://golang.org/ref/spec#Notation), the language specification follow the extended [Backus-Naur Form](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form). However some EBNF blocks on the spec page also contain golang style comments. It seems like they could use valid EBNF symbols instead.

~~For example in this case :~~
```
0.
72.40
072.40  // == 72.40
```
~~It could be a comment symbol :~~
```
0.
72.40
072.40  (* == 72.40 *)
```

Or in this situation it could use the "special sequence" symbol :

```
newline        = /* the Unicode code point U+000A */ .
unicode_char   = /* an arbitrary Unicode code point except newline */ .
```

```
newline        = ? the Unicode code point U+000A ? .
unicode_char   = ? an arbitrary Unicode code point except newline ? .
```

Is it worth the change? Or maybe adding a note about comment usage at the beginning of the spec?

**Comment by ALTree** [comment]
I believe the parts with `\\`s are not meant to be in EBNF. For example, for floating-point literal, this part is EBNF:

```
float_lit = decimals "." [ decimals ] [ exponent ] |
            decimals exponent |
            "." decimals [ exponent ] .
decimals  = decimal_digit { decimal_digit } .
exponent  = ( "e" | "E" ) [ "+" | "-" ] decimals 
```

But the block below (the one with the go comment) contains a few examples of valid literals:

```
0.
72.40
072.40  // == 72.40
```

It's not meant to be a valid EBNF rule. It's just go code.

**Comment by bamarni** [comment]
@ALTree : definitely, they're just examples in go indeed. So I think this is only about the second snippet.

**Comment by griesemer** [comment]
@bamarni I'm not sure what you are suggesting. The production for unicode_char is "pseudo" EBNF if you will - simply because there's no easy way to get all those Unicode code points listed in compact for. For newline we could write the newline char but what we have is just as clear.

The point here is not strict consistency of syntax representation using EBNF. The point is to convey what the representation is in a form that's clear and precise. Strict EBNF is used where it's clear and precise. In those two cases, it's simpler and just as clear to use plain English.

**Comment by bamarni** [comment]
@griesemer : I was confused with the first example as it's go code there. My only suggestion left was the second example, which uses plain english and valid EBNF at the same time.

**Comment by bamarni** [comment]
@griesemer : I've opened a more generic issue, as it seems related to the golang.org/x/exp/ebnf package implementation (#17848).
