### ISSUE TITLE
all: inconsistent spelling: canceling or cancelling

### ISSUE THREAD

**Issue by mikioh** [golang/go#17938]
canceling:
```
./src/net/http/h2_bundle.go:	http2errStopReqBodyWriteAndCancel = errors.New("http2: canceling request")
./src/net/http/transport.go:		var timer *time.Timer // for canceling TLS handshake
./src/net/http/transport_test.go:	eventLog.Printf("canceling")
./src/net/http/transport_test.go:canceling
./src/net/dial_unix_test.go:			t.Logf("canceling context")
```
cancelling:
```
./src/context/context_test.go:	checkChildren("after cancelling WithCancel child", ctx, 0)
./src/context/context_test.go:	checkChildren("after cancelling WithTimeout child", ctx, 0)
./src/os/exec/exec_test.go:			t.Fatal("cancelling context did not stop program")
```

**Comment by dsnet** [comment]
Related #11626.

Other inconsistencies:
* `panicing` vs `panicking`
* `big-endian` vs `big endian`
* `gray` vs `grey`

**Comment by dgryski** [comment]
Maybe overkill, but could the trybots or git-codereview have a test for this?

**Comment by griesemer** [comment]
The 1-l approach seems more common in Go source, though personally (and I'm not a native speaker), the 2-l solution looks more correct to me (probably because I'm not a native speaker).

One more data point: Bose sells noise cancelling head phones... ( https://www.bose.com/en_us/products/headphones/over_ear_headphones/quietcomfort-25-acoustic-noise-cancelling-headphones-apple-devices.html )

**Comment by bradfitz** [comment]
Not sure why this is Go 1.8 material, but .... https://go-review.googlesource.com/34147

Doing gray/grey (we should use "gray", the American spelling) and big-endian vs big endian are too invasive for now. I did the canceling and easy bits @dsnet mentioned.
