### ISSUE TITLE
plugin: noopt builder broken by plugin change

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17937]
The noopt builder is broken by the 03da269 (plugin versioning)

https://build.golang.org/log/857ba03fe3293b11a67a4391292aff2d3b29c28e
```
##### ../misc/cgo/testplugin
2016/11/15 16:27:25 plugin.Open failed: plugin.Open: plugin was built with a different version of package sync/atomic
2016/11/15 16:27:25 Failed: exit status 1
2016/11/15 16:27:25 FAILED
```

**Comment by wendigo** [comment]
Is it related to https://github.com/golang/go/issues/17928 ?

**Comment by crawshaw** [comment]
It looks like the noopt builder found a potentially interesting bug.

Code included in plugins is all compiled with the `cmd/compile` arg `-shared`. However binaries that load the plugin do not (by default on linux) build with `-shared`. As the dynamic linker will favor loaded code, that means plugins sometimes get different code when they are loaded. This trips over the package-hashing versioning check with noopt.

I can't think of any cases where this causes a program to fail. The `-shared` flag changes the way code references other symbols and restricts its register use. But the register use shouldn't matter across function calls, and as the binary is compiled as not-shared, the code it has loaded has to be able to reach other symbols already.

Unfortunately because of the way the `go/build` package works, fixing this in `cmd/go` is a bit of a kludge. It's hard to justify a kludge like this to get a builder working again and fix a potential bug. But I'll send the CL anyway.
