### ISSUE TITLE
reflect: regression in Type.ConvertibleTo

### ISSUE THREAD

**Issue by dsnet** [golang/go#17952]
8d0c105407d235c85a163c0cda5bda86e5219c36 caused a regression in functionality of `ConvertibleTo`.

The following test passes on Go 1.6 and 1.7, but fails on tip:
```go
type timeTime time.Time

func Test(t *testing.T) {
	t1 := reflect.TypeOf((*time.Time)(nil))
	t2 := reflect.TypeOf((*timeTime)(nil))
	if !t1.ConvertibleTo(t2) || !t2.ConvertibleTo(t1) {
		t.Error("pointers not convertible")
	}

	t1 = reflect.TypeOf(time.Time{})
	t2 = reflect.TypeOf(timeTime{})
	if !t1.ConvertibleTo(t2) || !t2.ConvertibleTo(t1) {
		t.Error("values not convertible")
	}
}
```

/cc @rsc, @crawshaw, @ianlancetaylor

**Comment by ianlancetaylor** [comment]
The problem is that for a definition like `type timeTime time.Time` the `pkgPath` of the struct is the package in which it is defined (in this case, `main`) and we use that `pkgPath` for the `pkgPath` of all the fields.  But of course the fields are defined in package `time`.

Similarly, printing `Field(i).PkgPath` of `reflect.TypeOf(timeTime)` also prints the wrong value.

`dnameField` in cmd/compile/internal/gc/reflect.go assumes that it never needs to set the `pkgPath` of a field, but as far as I can tell that simply isn't true.
