### ISSUE TITLE
encoding/*: tags agnostic type conversion not complete

### ISSUE THREAD

**Issue by ikrabbe** [golang/go#18071]
This is not a bug against a release version, as tag agnostic type conversions is prerelease.

### What version of Go are you using (`go version`)?

go version devel +25a81e7 Mon Nov 28 03:30:55 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ingo/go"
GORACE=""
GOROOT="/home/ingo/src/go.local"
GOTOOLDIR="/home/ingo/src/go.local/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build646795175=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

Run go test -v on the code (on origin/master!): https://gist.github.com/ikrabbe/1a325fe6eac21f5bef74f22e5742248e

and replace Plain with PlainFail on Line 118

### What did you expect to see?

See it run with Plain AND PlainFail

### What did you see instead?

Only Plain conversion works!

**Comment by ianlancetaylor** [comment]
Using `PlainFail` does not work because the type `Body` is not assignment compatible with the field `Body` in the type `PlainFail`.  The change in the language permits conversions between types that only differ in field tags.  It does not permit direct assignments between such types.  Your composite literal is trying to use a direct assignment to set the `Body` field, not a conversion.

Closing because this is working as documented.

**Comment by ikrabbe** [comment]
sorry, you are right. I got lost within all those xml and tags.
