### ISSUE TITLE
x/net/http2: many tests are flaky: Error while expecting an RSTStream frame: timeout waiting for frame

### ISSUE THREAD

**Issue by dsnet** [golang/go#18111]
https://storage.googleapis.com/go-build-log/0b1b6d4c/openbsd-amd64-gce58_f9489e71.log

```
--- FAIL: TestServer_Request_Reject_Pseudo_scheme_invalid (2.02s)
	server_test.go:475: Error while expecting an RSTStream frame: timeout waiting for frame
--- FAIL: TestServer_Request_Connect_InvalidPath (2.03s)
	server_test.go:475: Error while expecting an RSTStream frame: timeout waiting for frame
FAIL
FAIL	golang.org/x/net/http2	44.630s
```

**Comment by bradfitz** [comment]
We're seeing this across the board on basically on all GOOS now.

**Comment by bradfitz** [comment]
Closed dup #18235. See some debugging notes there.

**Comment by bradfitz** [comment]
With @tombergan's new debugging,

https://build.golang.org/log/b8e6726f6ff2fecdaebc69ebbd16e2f3c34a7ea4
```
--- FAIL: TestServer_Rejects_HeadersSelfDependence (2.07s)
	server_test.go:510: Error while expecting an RSTStream frame: timeout waiting for frame
	server_test.go:229: Framer read log:
		2016-12-08 17:00:48.731964688 Framer 0x3a776c00: read SETTINGS len=18, settings: MAX_FRAME_SIZE=1048576, MAX_CONCURRENT_STREAMS=250, MAX_HEADER_LIST_SIZE=1048896
		2016-12-08 17:00:48.732088456 Framer 0x3a776c00: read SETTINGS flags=ACK len=0
	server_test.go:235: Framer write log:
		2016-12-08 17:00:48.700756846 Framer 0x3a776c00: wrote SETTINGS len=0
		2016-12-08 17:00:48.73199436 Framer 0x3a776c00: wrote SETTINGS flags=ACK len=0
		2016-12-08 17:00:48.732123435 Framer 0x3a776c00: wrote HEADERS flags=END_STREAM|END_HEADERS|PRIORITY stream=1 len=21
FAIL
FAIL	golang.org/x/net/http2	24.016s
```

**Comment by bradfitz** [comment]
Oh, is this due to "http2: schedule RSTStream writes onto its stream's queue" (https://github.com/golang/net/commit/00ed5e97ea3a5ac46658b98e50259941947cec04) ?

**Comment by tombergan** [comment]
Are you suggesting the stream is somehow closed before the RSTStream is flushed from the queue? A stream's queue is wiped when the stream is closed, so this is vaguely possible, although I haven't thought through the specific buggy sequence.

**Comment by tombergan** [comment]
If that's the problem, it might also be related to the remaining flake here:
https://github.com/golang/go/issues/17243#issuecomment-261109144

**Comment by bradfitz** [comment]
I haven't thought through it all yet either. But that's my hunch, since a bunch of tests (all involving RSTStream frames) are now failing where the tests had been stable for ages.

**Comment by tombergan** [comment]
This looks like the buggy line:
https://github.com/golang/net/blob/c46f265c325130a7a6c7b27db8c6fe14b64f1a68/http2/server.go#L1044

What if we instead modify endStream to return true for RST_STREAM, then wait for the RST_STREAM to be written before closing the stream?
https://github.com/golang/net/blob/c46f265c325130a7a6c7b27db8c6fe14b64f1a68/http2/server.go#L930
https://github.com/golang/net/blob/c46f265c325130a7a6c7b27db8c6fe14b64f1a68/http2/write.go#L50

**Comment by bradfitz** [comment]
Yeah, that should probably work. Only thing I'd be concerned about is what else could happen in the meantime (between the `.resetStream()` call and the write of the frame and the delayed close stream) that would differ in behavior. For instance, which incoming frames would then see a not-closed frame and do something whereas before they'd get dropped or get more rejects?

Alternative, just for completeness (but not well-considered) is: the `sc.writeSched.CloseStream(st.id)` in `closeStream` could maybe go through its list of queued frames and promote some to the global queue instead of the per-stream queue. But that feels a little gross and violating the abstraction. But maybe it's lower risk?

Your fix sounds good, though. Want to send a CL? It probably doesn't need a test, since we have tons of failing builders already which are effectively the test. If the existing tests pass, that's a good sign.

**Comment by tombergan** [comment]
Sure, I'll send a CL soonish.
