### ISSUE TITLE
cmd/compile: unaligned float64 load/store on mips

### ISSUE THREAD

**Issue by cetinsert** [golang/go#18140]
### What version of Go are you using (`go version`)?

```
go version go1.8beta1 windows/amd64
```

### What operating system and processor architecture are you using (`go env`)?

Building on `windows-amd64` for `linux-mips`.

```
set GOARCH=mips
set GOBIN=
set GOEXE=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=C:\Users\cetin\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-fPIC -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### What did you do?

Windows PC (`cmd.exe`):

```
set GOOS=linux&&set GOARCH=mips&&go build
```

MIPS Router:

```
./hello
Illegal instruction
```

### What did you expect to see?

```
Hello world!
```

### What did you see instead?

```
Illegal instruction
```

---

What kind of hardware products does the recent mips support merge target then?

**Comment by vstefanovic** [comment]
The supported instruction set is mips32(r1). Illegal instruction you're seeing is likely due to the kernel not handling unaligned loads and stores. Fixing go compiler to not emit such loads and stores is currently in the works and thanks to this issue we could treat it as a fix instead of new feature - so hopefully it can be included in the 1.8 release.

**Comment by bradfitz** [comment]
Looks like those devices are:

https://wikidevi.com/wiki/MIPS_24K and
https://wikidevi.com/wiki/MIPS_74K

@vstefanovic, it sounds like you expect those to work?

How much work and how invasive is it? If it only affects mips and nothing else, it might still be acceptable for Go 1.8.

But it would need to be soon regardless.

**Comment by cherrymui** [comment]
I don't think the compiler generate any unaligned loads/stores. @vstefanovic, does it?
The only thing I see is the assembly functions in the runtime that have MOVWL, MOVWR.

**Comment by pqyptixa** [comment]
I was seeing the same problem ("Illegal instruction") in a TP-Link TL-WR1043ND router running OpenWRT, and after attaching a debugger, I noticed that the problem was that the CPU lacks support for floating point instruction.
Perhaps the OP has the same problem? Also, related: https://github.com/golang/go/issues/17984
You'll probably get many similar bug reports in the next month(s) :)

**Comment by minux** [comment]
I think we should mention the mips port requires MIPS32r1 support
and also either native FPU or kernel FPU emulation in the release
docs.

**Comment by bradfitz** [comment]
@minux, yes. Want to send a CL? Or @cherrymui?

Also, https://github.com/golang/go/wiki/MinimumRequirements needs to be updated.

**Comment by minux** [comment]
Sent CL 33853 and updated the MinimumRequirements wiki page.

**Comment by cetinsert** [comment]
How can I check if an already compiled and flashed OpenWRT has kernel FPU emulation enabled or not?
Also for GL-AR150, we are using self-compiled images which in the default settings of OpenWRT's `make menuconfig` suggest FPU emulation is enabled.

---

Which consumer router meets the requirements of the MIPS 32 support the way it is in Beta 1?

If anyone needs online access to any of the devices, I can set them up a permanent tunnel for as long as they need. It would be great to

**Comment by vstefanovic** [comment]
@cherrymui
There are non-8-byte aligned ldc1's and sdc1's for accessing doubles on the stack because $sp is often not 8-byte aligned - the first reason for that is reserving only 4 bytes for $ra on the stack.

@bradfitz
I expect the issue with these two CPUs is kernel not handling unaligned loads and stores. 
The patch for compiler not emitting them is not invasive or large, it has a few "if arch == 'mips'" in the common code. It should be ready during the next week.

@cetinsert 
If this c code doesn't raise illegal instruction, then your machine can stand FP instructions:

int main(int argc, char** argh) {
  asm("add.d $f0,$f0,$f0");
  return 0;
}

And this one should tell you if the kernel handles unaligned loads and stores:

int main(int argc, char** argh) {
  asm("ldc1 $f0,4($sp)");
  return 0;
}

Btw, mips soft float patch is almost ready.

**Comment by cherrymui** [comment]
> There are non-8-byte aligned ldc1's and sdc1's

Those probably shouldn't be there. Maybe we should make the assembler rewrite `MOVD x, F0` to something like `MOVF x, F0; MOVF x+4, F1`?

**Comment by vstefanovic** [comment]
The proposed change skips 4 bytes after $ra and places args starting from $sp +8. Then we could keep using ldc1 instead of two lwc1.

**Comment by minux** [comment]
Even if we align the SP at function entry, what about unaligned
function float64 arguments such as this case:

func f(uint32, float64, uint32, float64)

No matter how we align the stack pointer, one of the two float64
arguments will be unaligned.

Softfloat change is probably too large for Go 1.8, but I think we
do need to solve the unaligned float64 problem for Go 1.8.

BTW, I hope the upcoming softfloat reuses the runtime/softfloat64.go
code.

**Comment by vstefanovic** [comment]
These are aligned with
  t.Align = uint8(2 * Widthreg)
in case of mips and float64 (in align.go:dowidth()).

Yes, the softfloat code is using runtime/softfloat64.go.

**Comment by minux** [comment]
OK, then mips is following is different ABI than all
the other ports. Other 32-bit ports only do max 32-bit
alignment.

**Comment by vstefanovic** [comment]
The alignment diffs:
https://go-review.googlesource.com/34073
https://go-review.googlesource.com/34074
https://go-review.googlesource.com/34075
https://go-review.googlesource.com/34076

**Comment by bradfitz** [comment]
@vstefanovic, that's a fine comment as an FYI, but we don't track closed issues, so be sure there's an open bug somewhere actually tracking those changes.

**Comment by cetinsert** [comment]
@vstefanovic I appreciate continued comments under this issue and would love to learn where to track further development in case you follow the advice of @bradfitz .

**Comment by minux** [comment]
Let's repurpose this issue to misaligned float64 load/store to keep all
relevant discussions together.

I think making 64-bit types having 64-bit alignment has larger
implications. For Go 1.8, why not adopt Cherry's suggestion of using two
lwc1 to load a 64-bit fp values? That should be a minimal change because we
just need to modify cmd/internal/obj/mips to emit 8-byte two-instruction
sequence for ldc1 and stc1.

**Comment by minux** [comment]
The tracking issue for increasing 64-bit value alignment on 32-bit
architectures is #599.

**Comment by cetinsert** [comment]
For all, why / where does a Hello World binary even touch any `float`s before it gets to execute any user code (`fmt.Println("Hello World!")`)?

**Comment by minux** [comment]
Because the runtime uses floating points, e.g. in the garbage collector.

**Comment by bradfitz** [comment]
@randall77, @ianlancetaylor ... thoughts on this? As mips is a new architecture in Go 1.8, what's acceptable to still get in for Go 1.8?

**Comment by vstefanovic** [comment]
Replacing a ldc1 with two lwc1 would be more than ok for 1.8, especially if we'll be 8-byte aligning arm and 386 too in 1.9. Then we can align them all at the same time.

**Comment by l2dy** [comment]
I'm building with `go version go1.8beta2 darwin/amd64` for `linux/mipsle` and still got `Illegal instruction` on my MIPS router (Lenovo Y1, OpenWrt with musl).

**Comment by minux** [comment]
The illegal instruction might be FPU instruction.
Please see the revised Go 1.8 release note:

Go now supports 32-bit MIPS on Linux for both big-endian (linux/mips) and
little-endian machines (linux/mipsle) that implement the MIPS32r1
instruction set with FPU or kernel FPU emulation. Note that many common
MIPS-based routers lack an FPU and have firmware that doesn't enable kernel
FPU emulation; Go won't run on such machines.

Anyway, if your cpu matches the requirement (mips32r1+FPU),
and still encounters SIGILL, please file a new issue with details
on which instruction triggered SIGILL.

**Comment by icexin** [comment]
I have the same issue on wndr4300. After kernel FPU emulation is enabled, the binary can run normally. Hoping to help you.

**Comment by cetinsert** [comment]
@icexin how did you enable that?

**Comment by icexin** [comment]
Change directory to openwrt build dir, `make kernel_menuconfig`， `Kernel type  ---> MIPS FPU Emulator`

**Comment by cetinsert** [comment]
@icexin that indeed did the trick! I was not even aware there was a `kernel_menuconfig` I had beenlooking for that option under `menuconfig` o__O"

**Comment by pqyptixa** [comment]
@vstefanovic : you say the "mips soft float patch is almost ready". I wonder, will this patch be merged in Go 1.8?

**Comment by vstefanovic** [comment]
@pqyptixa
Well, no, the code for 1.8 has been feature-freezed quite a while ago.

**Comment by pqyptixa** [comment]
@vstefanovic
ah, right... are these patched published somewhere? if they aren't, do you plan to?
thanks a lot for your work.

**Comment by vstefanovic** [comment]
@pqyptixa 
No, not yet, they will be after 1.8 is released.

**Comment by pqyptixa** [comment]
@vstefanovic any news regarding the mips/FP-emulation patches?

**Comment by vstefanovic** [comment]
@pqyptixa we've switched to #18162 for the soft-float news; I still expect to submit the code some time next week.
