### ISSUE TITLE
cmd/go: inconsistency about no text after "Output:" in examples

### ISSUE THREAD

**Issue by mikioh** [golang/go#18191]
`go doc cmd/go` says that `An example with no such comment, or with no text after "Output:" is compiled but not executed` but the current implementation behaves differently. Also the testing package never mentions the behavior. It might be better to clarify what's the correct behavior.

**Comment by quentinmit** [comment]
Changing the docs is fine now, but if you want to change the behavior, this has to wait for 1.9 at this point.

**Comment by bradfitz** [comment]
> but the current implementation behaves differently

What is the current behavior you see?

Our standard bug report template has a section "What did you expect to see?" and "What did you see instead?". If you're not going to use the template, at least include all the relevant information.

**Comment by mikioh** [comment]
> "What did you expect to see?"

It's hard to describe to me because I'm not sure whether the behavior must be the same and what's the expected behavior by the original author. The observable things are the following:
- The testing package mentions nothing about `no text after "Output:"`,
- The cmd/go package says that `no text after "Output:"` never executes examples,
- Running `cmd/go test` with an example containing `no text after "Output:"` executes the example.

**Comment by ALTree** [comment]
Examples with no `output` comment are compiled but not executed (which is correct):

```
package foo_test

import "fmt"

func ExampleReverse() {
	fmt.Println("hello")
}
```

Examples with no text after `//Output:` behaves differenty from what `go doc cmd/go` says. The following:

```
package foo_test

import "fmt"

func ExampleReverse() {
	fmt.Println("hello")
	//Output:
}
```

is compiled **and** executed, both on `go1.7.3` and on `tip` (and it fails at run-time because the output is not empty).

Note that rsc asked for an example with no text after `//Output:` to be actually run. This was Issue #4485.

It looks like it's the documentation that is outdated(?). We actually want to run Examples with no text after `//Output:`, and check that there's, in fact, no output.

The issue was fixes in https://codereview.appspot.com/7071050 but the author forgot to update the documentation.

**Comment by mikioh** [comment]
Nice, thanks for the investigation, @ALTree.

**Comment by ALTree** [comment]
I sent https://golang.org/cl/34512 (for 1.8 or 1.9, you decide).
