### ISSUE TITLE
10 Connection with 5 minute testing time. Http server appear err: can not connect to server

### ISSUE THREAD

**Issue by hzmnet** [golang/go#18208]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Any Version 

### What operating system and processor architecture are you using (`go env`)?
**Window 10  64Bit**

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Testing tool : **HttpTest4Net  with not keep-alive option**

**Comment by minux** [comment]
There isn't enough detail to reproduce the issue.

Please answer the questions in the issue template (what did you do,
what did you expect to see and what did you see instead) in more
detail so that we can understand and reproduce the problem.

If you're just asking a question, please see
https://golang.org/wiki/Question.

Thanks.
