### ISSUE TITLE
cmd/compile: generate static calls when callee is known

### ISSUE THREAD

**Issue by alandonovan** [golang/go#18270]
It would be nice if the compiler optimized dynamic function calls into static ones when the callee is known.  This would save ~2ns/call for calls to functions with no free variables, and ~3ns/call for functions that need a closure.

Benchmark: https://play.golang.org/p/lWR1t6LMEP

**Comment by minux** [comment]
In addition to using static calls, I'd also like the compiler to be able to
inline your B and C cases.

**Comment by josharian** [comment]
Too late for 1.9.

**Comment by huguesb** [comment]
As of CL 65071 the compiler can inline f inside B
As of CL 72490 the compiler can inline f inside C

The more general problem of turning dynamic calls into static ones is still open though and will probably require some sort of copy propagation for function values. I'd like to take a stab at it at some point.

**Comment by agnivade** [comment]
As of tip (`go version devel +e96c4ace9c Mon Mar 18 10:50:57 2019 +0530 linux/amd64`), the times are now - 

name  time/op
A-4   14.9ns ± 1%
B-4   16.5ns ± 1%
C-4   16.6ns ± 0%

So the differences are closing in. B-A is 1.6ns, C-A is 1.7ns

**Comment by randall77** [comment]
All of A, B, C now generate basically identical code.

A gets inlined into BenchmarkA, whereas B and C do not get inlined into BenchmarkB and BenchmarkC, respectively (I think we don't inline functions with closures in them). That makes BenchmarkA a bit faster, but that's not really what this issue is about.

But I'm calling this fixed. We do convert dynamic to static calls.  If there are specific instances where this is not happening, we should probably use a new bug.

**Comment by alandonovan** [comment]
Thanks!
