### ISSUE TITLE
x/tools/go/loader: TypeCheckFuncBodies doesn't work with packages specified as files

### ISSUE THREAD

**Issue by mvdan** [golang/go#18288]
`go/loader.Config` has the following:

```
// TypeCheckFuncBodies is a predicate over package paths.
// A package for which the predicate is false will
// have its package-level declarations type checked, but not
// its function bodies; this can be used to quickly load
// dependencies from source.  If nil, all func bodies are type
// checked.
TypeCheckFuncBodies func(path string) bool
```

I wrote a linter that needs to typecheck func bodies for the packages/files it is linting. But outside of those packages, doing that work is wasting time. For example, typechecking all of the std dependencies can bump the run time from ~0.3s to ~1.2s when running the linter on a small package.

I've tried getting around it with something like the following:

```
paths := gotool.ImportPaths(args)
isArgPkg := make(map[string]bool, len(paths))
for _, path := range paths {
        isArgPkg[path] = true
}
config := loader.Config{TypeCheckFuncBodies: func(path string) bool {
        return isArgPkg[path]
}}
if _, err := config.FromArgs(paths, false); err != nil {
        return err
}
prog, err := config.Load()
```

To clarify, [gotool](https://github.com/kisielk/gotool) is a clone of Go's unexported code that handles package arguments. This runs fine if using the linter with arguments like `.`, `./...`, `mypackage` or `bytes`.

But it breaks if using filenames like `foo.go`, because `paths` will be `[]string{"foo.go"}`. The `package` node hasn't been read yet. I assume the call that ultimately reads it is `config.Load()` - but by then, it's too late to set `TypeCheckFuncBodies`.

Is there a way to do this? If not, I would suggest the API should allow it somehow.

CC @alandonovan

**Comment by mvdan** [comment]
Another way to pharse this - I only want to typecheck the packages specified by `args`, and not their dependencies, to save time.

**Comment by mvdan** [comment]
Maybe I meant @adonovan?

**Comment by alandonovan** [comment]
>  I only want to typecheck the packages specified by args, and not their dependencies, to save time.

You can't accurately type-check a package without type information for each package that it imports.

The gc and gccgo compilers save type information from one package and use it when compiling the next one; this information about package P can be found in a section of the archive library $GOPATH/pkg/$GOOS_GOARCH/${P}.a.  This works well for a compiler because the build tool (go build) ensures that dependencies are built in order.  However, the loader is not part of a build tool and so cannot assume that the .a files in $GOPATH/pkg are up to date, or exist at all.  So, it loads source code for all the packages transitively imported by the initial packages.  This is somewhat wasteful, but simple to understand and implement and fast enough in practice for most users, though Go workspaces are getting larger and it may be time to consider making the loader stash type information too.

You're right that the TypeCheckFuncBodies hook doesn't work with packages specified as files.  That's something to think about as we reconsider the API.

**Comment by mvdan** [comment]
Thanks for the update. Should this issue remain open about `TypeCheckFuncBodies` working with files in the updated API?

**Comment by alandonovan** [comment]
Yes, it's a valid bug report, so let's keep it open.

**Comment by mvdan** [comment]
`go/packages` with `LoadSyntax` solves this for me with flying colors - it uses `GOCACHE`, and even populates it if anything is missing. Loading a small project with tons of dependencies is now fast, once the cache is warm. I don't think there's a reason to keep this open.
