### ISSUE TITLE
cmd/cover: doesn't work with tip when using //go: annotations

### ISSUE THREAD

**Issue by mikioh** [golang/go#18285]
With go1.7.4:
```
go test -short -cover runtime
PASS
coverage: 58.7% of statements
ok      runtime 38.548s
```
With devel +0716fef:
```
go test -short -cover runtime
# testmain
runtime.nanotime1: relocation target libc_clock_gettime not defined
runtime.pipe1: relocation target libc_pipe not defined
runtime.usleep2: relocation target libc_usleep not defined
runtime.osyield1: relocation target libc_sched_yield not defined
runtime.nanotime1: undefined: "libc_clock_gettime"
runtime.pipe1: undefined: "libc_pipe"
runtime.usleep2: undefined: "libc_usleep"
runtime.osyield1: undefined: "libc_sched_yield"
FAIL    runtime [build failed]
```

**Comment by dhananjay92** [comment]
They look like linker errors. Does it work without `-cover`?

**Comment by mikioh** [comment]
@dhananjay92,

> Does it work without -cover?

See https://build.golang.org.

The cmd/cover package just generates annotated source files. So just guessing that some modification to runtime package during Go 1.8 development cycle breaks the existing plumbing work for shared libraries.

**Comment by dhananjay92** [comment]
Okay, root cause is that the compiler directives in [`src/runtime/os3_solaris.go`](https://github.com/golang/go/blob/master/src/runtime/os3_solaris.go#L9-L81) disappear during coverage instrumentation. 

Confirmed with,
```shell
$ go tool cover -mode=count runtime/os3_solaris.go
# .. notice the compiler directives are present ...

$ ../pkg/tool/linux_amd64/cover -mode=count runtime/os3_solaris.go
# ... notice absence of compiler directives ...
```

This is happening because of my own change: [golang.org/cl/30161](http://golang.org/cl/30161). Coverage instrumentation [removes all comments that are not present as nodes in the AST](https://github.com/golang/go/blob/master/src/cmd/cover/cover.go#L363-L364); because they were interfering with inserted code.

Parser doesn't keep these compiler directives as nodes in AST, but instead as `CommentGroup` in [`ast.File.Comments`](https://golang.org/src/go/ast/ast.go?s=30592:30663#L977) with all other comments. The fix that solves both this and #17315 would be to keep all compiler directive into AST as nodes.

Working on the fix.

PS: *The issue will go away with https://github.com/dhananjay92/go/commit/4a16ac8c3669f60db8a2746cabf767d4c59719eb because doing that makes parser keep those comments in AST. Parser only keeps comments into the tree that can potentially be document-comments*

**Comment by dhananjay92** [comment]
I think Ian had told me some time earlier that the compiler directives are associated with something (a function or variable, etc). If that's the case, fix would be https://github.com/dhananjay92/go/commit/4a16ac8c3669f60db8a2746cabf767d4c59719eb.

Let me confirm with him again.

**Comment by mikioh** [comment]
@dhananjay92,

Thanks for the investigation. As you mentioned above, a few packages that import runtime symbols by using `//go:cgo_import_dynamic` or `//go:linkname` annotation, for example vendor/golang_org/x/net/lif, golang.org/x/net/lif or golang.org/x/sys, surely crash when using cmd/cover.

/CC @ianlancetaylor

**Comment by dhananjay92** [comment]
[golang.org/cl/34563](http://golang.org/cl/34563) takes care of such compiler directives that aren't attached to any node in the AST.

[My another attempt](https://github.com/dhananjay92/go/commit/d8c83d498960d61efce41b7d665c3449bc4f5f52) to let printer print such compiler directives, failed. Because `ast/printer` can either print from `ast.File.Comment` or from nodes in the tree, but not from both.
