### ISSUE TITLE
cgo not support CXXFLAGS?? or just a bug??

### ISSUE THREAD

**Issue by songtianyi** [golang/go#18308]
````
/*
// go preamble
#cgo CXXFLAGS: -I/root/MXNet/mxnet/include/
#cgo LDFLAGS: -L/root/MXNet/mxnet/lib
#include <mxnet/c_api.h>
*/
import "C"
````

````
fatal error: mxnet/c_api.h: No such file or directory
````

This error could be avoid by change CXXFLAGS to CPPFLAGS
````
/*
// go preamble
#cgo CPPFLAGS: -I/root/MXNet/mxnet/include/
#cgo LDFLAGS: -L/root/MXNet/mxnet/lib
#include <mxnet/c_api.h>
*/
import "C"
````

BUT when i did like that go compiler seemed to use gcc to compile the header file which written by C++ not g++ compiler.
Frankly, i am fucking confused! i am sorry.

**Comment by ianlancetaylor** [comment]
The code in the cgo comment must always be C code, not C++ code.  The cgo tool does not support C++.

The `#cgo CXXFLAGS` directive provides flags that are used to compile C++ files in the same directory, as documented at https://golang.org/cmd/cgo.

The `#cgo CPPFLAGS` directives provides preprocessor flags that are used to compile both C and C++ files in the same directory, and is also used to compile the cgo comment.

Closing because there is no bug here.  If you have further questions, please see https://golang.org/wiki/Questions for good places to send them.  Thanks.

**Comment by songtianyi** [comment]
@ianlancetaylor 
I am still not clear about this. 
DOES cgo can support **c++** code that could be compiled by **gcc compiler** no matter where they are?
WHY cgo could compile c++ code in the same directory except the code in any other directory.
It doesn't make sense.

**Comment by ianlancetaylor** [comment]
For questions, please see https://golang.org/wiki/Questions .  Thanks.

**Comment by sisyphsu** [comment]
@songtianyi 

I think `cgo` don't support c++ code/library, so we can't use c++ headers by `cgo CXXFLAGS ` directly.

I google this issue a lot, and some people suggest that, you should wrap c++ code as c function, and then you can use them by `cgo`.

**Comment by sisyphsu** [comment]
The `https://golang.org/wiki/Questions` has nothing, That guy just want to close this issue.

**Comment by yaswagner** [comment]
Hey! Did you manage to use C++ directly with cgo. I am having the same issue right now. Thank you!

**Comment by yaswagner** [comment]
Hey @sisyphsu and @songtianyi ! Did you manage to use C++ directly with cgo. I am having the same issue right now. Thank you!
