### ISSUE TITLE
cmd/go: ".go files ignored due to build tags" inaccurate

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18396]
Go 1.8 has a new error message and new field https://beta.golang.org/pkg/go/build/#NoGoError.Ignored

The go tool now interprets that `NoGoError.Ignored` bool as meaning that the ignored files were because of build tags, but that's not necessarily true:

```
ward5k:~ bradfitz$ cd $GOPATH/src
ward5k:src bradfitz$ mkdir demo
ward5k:src bradfitz$ cd demo/
ward5k:demo bradfitz$ touch .foo.go
ward5k:demo bradfitz$ go fmt .
can't load package: package demo: no buildable Go source files in /Users/bradfitz/src/demo (.go files ignored due to build tags)
```

Note that the "(.go files ignored due to build tags)" part isn't true.

Should we change the error mesage, or reconsider eee727d0855b9e78f9df87e08d57b1d7f264876c for Go 1.8? Are we happy with the new `NoGoError.Ignored` bool field?

/cc @rakyll @rsc

**Comment by rsc** [comment]
At this point I think we should just revert the CL instead of trying to fix it up. The old message was about as precise as it is possible to be: there are no buildable Go source files in the directory. There may be unbuildable Go source files or not. The new message, by trying to be more precise, turns out to be incorrect.

I thought this wording change was not worth the effort when it went by, but I didn't see it until it was already in, so I didn't say anything then. It definitely doesn't seem worth the effort to fix now, and since it's demonstrably incorrect, let's just revert it.

**Comment by rakyll** [comment]
Reverting sounds the best. Let's try to properly detect the case in 1.9.
