### ISSUE TITLE
cmd/cgo: Go type not supported in export: struct

### ISSUE THREAD

**Issue by pharic** [golang/go#18412]
# go version
go version go1.7.4 linux/amd64
 
# go env
```
# go env
GOARCH="amd64"
GOBIN="/root/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go_pkgs"
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build716839048=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
I am trying to build a shared object from go code (code has a struct and some functions). I am exporting all the functions and then run go build, but I see this error: `Go type not supported in export: struct`. There's [this thread](https://groups.google.com/forum/#!topic/Golang-nuts/MDoqVSXszdU) on the go-nuts mailing list about this issue, but there doesn't seem to be a resolution.

Here's an example program that generates the error:

**vertex.go**
```
package main

import "C"
import "fmt"

type Vertex struct {
  X,Y int
}

//export getVertex
func getVertex(X,Y int) Vertex {
  return Vertex{X,Y}
}

func main() {
  fmt.Println(getVertex(1,2))
}
```

**go build commandline output**
```
# go build -buildmode=c-shared -o vertex.so vertex.go
# command-line-arguments
./struct.go:6:13: Go type not supported in export: struct {
	X, Y int
}
./struct.go:6:13: Go type not supported in export: struct {
	X, Y int
}
```

### What did you expect to see?
I expect the `go build` to run successfully, and generate the shared object.

### What did you see instead?
I see an error `Go type not supported in export: struct`.

**Comment by bradfitz** [comment]
You can only export basic function signatures. @ianlancetaylor, are the rules documented somewhere?

**Comment by ianlancetaylor** [comment]
The documentation, in https://golang.org/cmd/cgo, is "Not all Go types can be mapped to C types in a useful way."  That said, struct types could be handled better than they are.  Right now they are a TODO in cmd/cgo/Package.cgoType.  Because of that TODO, you can't //export a Go function that uses a struct type.  And, frankly, using it in C would be tricky, since C does not have `:=`.  You would have to define the struct type in C yourself, and be certain that the C definition is identical to the Go definition.  This particular example, for example, is easy to mishandle, especially if you want the code to be portable, since `int` is different in C and Go.

But, of course, we should find a way to make this work.  This issue can track that.

**Comment by minux** [comment]
Actually, I think this is working as intended.

The correct program should use a type defined in C, rather than in Go,
because otherwise the external C programs have to manually define
a C struct matching the Go struct, which is non-trivial and error-prone.
(cgo is about interfacing C to Go, not about making Go interfaces
available to C, so it's understandable that cgo doesn't support exporting
arbitrary Go types to C -- you should do the other way around, and
define the necessary structs in C.)

For example, this works today:
package main

/*
struct Vertex {
int X;
int Y;
};
*/
import "C"
import "fmt"

//export getVertex
func getVertex(X, Y C.int) C.struct_Vertex {
return C.struct_Vertex{X, Y}
}

func main() {
fmt.Println(getVertex(1, 2))
}

**Comment by bradfitz** [comment]
I'll keep this open as a documentation CL.
