### ISSUE TITLE
cmd/cgo: document that C.CString should be matched with C.free

### ISSUE THREAD

**Issue by danderson** [golang/go#18457]
Someone in the Go Slack channel had a memory leak in their program, that turned out to be a misunderstanding of how CStrings work. Their code did:

```
C.myfunc(C.CString(goStr))
```

They expected that C.CString would be a normal GC-able object, and so lost some time tracking down the non-obvious memory leak. The cgo documentation states that `C.CString` must be accompanied by a `C.free`, but if that docstring gets glossed over, the result is a hard to find bug.

It would be nice if `go vet` could warn on the pattern of calling a C function with a `CString` allocated inline in the function call. Such a call is most often wrong, since there's no way to free the resulting *C.char. One exception is if the C function itself frees the memory, but that is relatively unusual pattern of memory ownership in C APIs.

**Comment by minux** [comment]
I don't think this passes the three requirements for cmd/vet (see
cmd/vet/README).

You will need to demonstrate at least this error's frequency and that
people don't actually wrap a C function in cgo preamble that frees the
argument after calling the function it wraps.

Perhaps this is better addressed with better documentation. (If you think
about the issue, it's very obvious Go's GC cannot track memory returned by
C.CString as C code can retain a reference and Go can't see the reference.)

**Comment by elubow** [comment]
I was the person who came in with the issue.  My initial request was actually documentation since I found the docs that said I should be running the `C.free()` myself anytime a `C.CString()` is allocated.  The confusion came when I expected the GC to free that on it's own.  So a note in the docs would be incredibly helpful.  Additionally, the docs would also be more helpful if they explain that `C.free()` doesn't just show up when one does an `import "C"` and that they will likely need to `include <stdlib.h>` inside the comment section with compilation arguments.  Both of those things would have been incredible time savers.

**Comment by rsc** [comment]
Let's start with documentation and move to vet if someone can show this meets the frequency bar.

**Comment by ALTree** [comment]
This looks fixed. In golang.org/cmd/cgo I see:

```
// Go string to C string
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func C.CString(string) *C.char
```

So both the fact that the caller must `free` and the note about `stdlib.h` are already there. 

Closing.
