### ISSUE TITLE
html/template,(?:) makes me feel annoyed

### ISSUE THREAD

**Issue by forsaken628** [golang/go#18466]
```
package main

import (
	"html/template"
	"os"
)

func main() {
	t := template.New("a")
	t.Parse(`
	<script type="text/tpl">
	<label></label>
	<div class="{{.A}}">
	</script>
	`)
	t.Execute(os.Stderr, struct {
		A string
	}{})
	//
	//	<script type="text/tpl">
	//	<label></label>
	//	<div class="(?:)">
	//	</script>
	//
}
```

**Comment by shurcooL** [comment]
Hi there. This issue report does not follow the [issue template](https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE) and it's not clear where the issue lies.

Before submitting an issue, I suggest you read the suggestions in [CONTRIBUTING.md](https://github.com/golang/go/blob/master/CONTRIBUTING.md#filing-issues).

Another resource I would highly recommend is [this one](https://github.com/primer/primer-markdown/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker), specifically its "Bug reports" section. It has great tips for how to make really high quality bug reports. Thanks!

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
