### ISSUE TITLE
cmd/compile: rsc/compilebench -alloc is broken

### ISSUE THREAD

**Issue by mdempsky** [golang/go#18641]
Using rsc/compilebench's -alloc flag, all compiles currently report "0 B/op 0 allocs/op". Presumably something in cmd/compile changed that broke this. We should either revert that change, or update rsc/compilebench accordingly.

**Comment by mdempsky** [comment]
This appears to be because runtime/pprof switched to writing binary pprof files, so compilebench's code to parse the `# TotalAlloc` and `# Mallocs` lines no longer work.

/cc @matloob

**Comment by josharian** [comment]
Just hit this myself. Sadness. (I wonder whether anyone else was parsing the pprof output to get memstats and will also be impacted by this change.)

I don't see an obvious way to add ignored to the binary pprof output, and I really don't want to embed a protobuf decoder in compilebench anyway.

I propose instead that we add a `-memstats=<file>` flag to cmd/compile. When provided, on exit, we call `runtime.ReadMemStats` and write the JSON-encoded results to `<file>`.

`compilebench` will have to probe whether the compiler accepts the flag. If yes, it uses it and reads the result. If no, it omits it and attempts to read the pprof output. There will be a stretch of commits in Go 1.8 and the beginning of Go 1.9 for which `compilebench` forever cannot emit alloc info. (Or in dire straights you can patch runtime/pprof/pprof.go's `WriteHeapProfile` to call `writeHeap(w, 1)` instead of `writeHeap(w, 0)`.)

How does that sound?

**Comment by minux** [comment]
Perhaps we should add a GODEBUG variable to switch back to the old pprof
format?

**Comment by josharian** [comment]
I assume that at some point @matloob will want to eliminate the old code, but as an interim measure, that'd be really useful. Particularly if it could go in for 1.8--it is a tiny, safe change--but I'm not going to hold my breath for that.

**Comment by minux** [comment]
In general, I'd argue that changing file format should give the users at
least one release to migrate to new format, which means we should at least
release Go 1.8 to support both formats and also with the ability to switch
format at runtime (so that people using Go 1.8 compiled programs without
source code can still use tools that only works with the old format.)

I think we should address this before Go 1.8.

**Comment by bradfitz** [comment]
Can you prepare a non-scary CL before Monday?

**Comment by josharian** [comment]
False alarm. While preparing a CL, I accidentally read the documentation (oops). CL on its way.

**Comment by josharian** [comment]
gopherbot down? [CL 35484](https://golang.org/cl/35484)

**Comment by minux** [comment]
I think the problem remains, we can't change all programs to pass non-zero
debug argument to WriteTo.

**Comment by josharian** [comment]
But those who have the problem have a one line fix available. They'd have to do the same thing with a GODEBUG envvar.
