### ISSUE TITLE
cmd/compile: improve error message when if statement brace is on next line

### ISSUE THREAD

**Issue by golang101** [golang/go#18747]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.4 linux/amd64

### What did you do?

	package main

	func main() {
		a := 1
		
		for a = 1; a < 2; a++ // syntax error: missing { after for clause
		{
		}
		
		if a == 1 // missing condition in if statement
		{
		}
	}

### What did you expect to see?

the two error messages should be alike.

### What did you see instead?

the the second error message is not very accurate.

**Comment by mvdan** [comment]
Happens all the same on `go version devel +4cce27a3fa Sat Jan 21 03:20:55 2017 +0000 linux/amd64
`.

@golang101 perhaps retitle to something like `cmd/compile: wrong error when opening brace is on a new line`

**Comment by josharian** [comment]
@golang101 thanks for filing issues. Would you mind helping [the folks doing triage](https://github.com/golang/go/wiki/Gardening#triage-new-bugs) by identifying the relevant component in the issue title, when you know it? Thanks!

cc @odeke-em

**Comment by mvdan** [comment]
@josharian did you mean that triage sentence towards me? I haven't requested github access, maybe I should.

**Comment by josharian** [comment]
It was meant for @golang101. But you should definitely request GitHub access.

**Comment by golang101** [comment]
@josharian I would like to.

**Comment by mdempsky** [comment]
Syntactically,

    if foo
    {
    }

is the same as

    if foo; {}

And the latter produces a "missing condition in if statement" error, which is why the former does too.

It's not obvious that the former deserves a different error message; or that if it does, what exactly should be the criteria for producing something different. I'd like to establish that before we worry about CLs.

**Comment by bradfitz** [comment]
@mdempsky, I bet only about 2% of Go users know that semicolons are even in the language at all, much less know the insertion rules.

I personally think it deserves a better error message. A fair number of newcomers to the language are going to write code in that style before they discover gofmt.

**Comment by odeke-em** [comment]
@mdempsky, yeah, I agree with @bradfitz's explanation,
I too think it deserves a better error message.

As we can see in the issue report, the user who reported it found the same problem.
```go
if condition
{
}
```
wasn't intuitive since visually they already provided the condition `a == 1`

Getting the same message for
```go
if expression; {
}
```
that tells me to think about the missing condition in the style
```go
if expression; condition {
```
even though `expression` might be a condition.

**Comment by griesemer** [comment]
This was fixed by https://go-review.googlesource.com/#/c/36930/.
