### ISSUE TITLE
Use consts in field tags

### ISSUE THREAD

**Issue by LukeMauldin** [golang/go#18760]
Using Go 1.7.3.  Would like to use const string definitions in struct field tags.  Example: [https://play.golang.org/p/dtxXbSwvzY](https://play.golang.org/p/dtxXbSwvzY)

Use case: using mgo driver to serialize data to MongoDB using bson.  Would like to reference struct tag field names in custom queries.

**Comment by bradfitz** [comment]
Are you proposing a language change? If so, see https://github.com/golang/proposal/

I'm going to close this for now. If you want to write up a bit more of a formal proposal feel free to reopen this or file a new bug. Otherwise I don't see this happening. The language is pretty frozen at this point.
