### ISSUE TITLE
Float operation need explanation

### ISSUE THREAD

**Issue by ThibaultRiviere** [golang/go#18794]
### What version of Go are you using (`go version`)?
**go version go1.7.1 linux/amd64**

### What did you do?
```go
package main

import (
	"fmt"
)
func main() {
	datas := []float64{
		1.30,
		1.35,
	}
	fmt.Println("should not be :", (datas[0]+datas[1])/2)
	expected := (1.30 + 1.35) / 2
	fmt.Println("should be :", expected)
}

```

### Output
```sh
should not be : 1.3250000000000002
should be : 1.325
```

If anyone can explain to me what i did wrong, i'm a new rookie on golang.
Can be related to #18772 ?

**Comment by ALTree** [comment]
This is how floating point arithmetic works, it's the same in every language. Python:

```
>>> (1.30 + 1.35) / 2
1.3250000000000002
```

You can find a friendly treatment of floating point arithmetic here: http://floating-point-gui.de; or a more technical treatment here: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

Since the Go project does not use its bug tracker for general discussion or asking questions, I'm closing this issue. If you have other questions, please see  the [Questions wiki page](https://github.com/golang/go/wiki/Questions).

**Comment by ThibaultRiviere** [comment]
@ALTree thanks for your response .
My question was why the result is different ? Like you said floating work like that, so both should be the same right ?

**Comment by ALTree** [comment]
`(1.30 + 1.35)/2` is a constant expression and is evaluated at compile time by the compiler using arbitrary-precision arithmetic, and only after the evaluation the result is cast to `float64`; while the `(datas[0]+datas[1])/2` expression is evaluated ad run-time using the usual 64-bit floating point arithmetic. 

For this reason, the two values are actually a little different. Here's a more extreme example when the compiler gets the result right, while computing the same expression at run-time using IEEE arithmetic gives an unexpected result:

https://play.golang.org/p/onLkEow06U

**Comment by ThibaultRiviere** [comment]
@ALTree make sens thanks for your time :)
