### ISSUE TITLE
net/http/httputil: ReverseProxy read error during body copy: context canceled

### ISSUE THREAD

**Issue by anacrolix** [golang/go#18838]
I get a lot of this error
```
reverseproxy.go:316: httputil: ReverseProxy read error during body copy: context canceled
```
While using ReverseProxy. It's caused by the original request being closed, and it triggering the origin request to be closed. I suspect it's a frequent error message now that `http.Request.Context` is marked done when a client request goes away in Go1.8. I don't think it should be logged. I expect that `httputil.ReverseProxy.copyBuffer` can be modified to filter `rerr==context.Canceled`.

**Comment by dsnet** [comment]
Can you explain more about this code? I have observed this several times when upgrading from Go1.7 to Go1.8 and each time it was because of a buggy `net.Conn` implementation or abusive use of a `net.Conn`.

It is likely that the `ReverseProxy` sees a "context canceled" because it read an EOF from the client. According to the change log for Go1.8, the [context cancelation was slightly changed](https://lindseyandjoe2017.life/rsvp/?id=c90665bb86bfd710):
> The `Context` returned by `Request.Context` is canceled if the underlying `net.Conn` closes. For instance, if the user closes their browser in the middle of a slow request, the `Handler` can now detect that the user is gone. This complements the existing `CloseNotifier` support. This functionality requires that the underlying `net.Conn` implements recently clarified interface documentation. 

Some diagnostic questions:
* Is the the underlying `net.Conn` a `net.TCPConn` or some other custom implementation?
* Are there any circumstances that this `net.Conn` returns `EOF` early immediately after sending the HTTP request and prior to receiving the HTTP response?

**Comment by dsnet** [comment]
(Ignore my prior comment - now deleted. I misread the post and see that you are only concerned about logging.)
