### ISSUE TITLE
cmd/compile: fix line number during yyerror in pragcgo

### ISSUE THREAD

**Issue by rsc** [golang/go#18882]
Merged position changes from dev.inline into master.
The only part I wasn't sure about was how to translate this one line added to master since the dev.inline branched forked off. I commented it with TODO(gri) instead:

	case strings.HasPrefix(text, "go:cgo_"):
		// TODO(gri): lineno = p.baseline + int32(line) - 1 // pragcgo may call yyerror
		p.pragcgobuf += pragcgo(text)
		fallthrough // because of //go:cgo_unsafe_args

**Comment by odeke-em** [comment]
@rsc  I had mentioned in https://github.com/golang/go/issues/18459#issuecomment-269566840, that I had encountered this and perhaps we can fix it like I did here https://go-review.googlesource.com/c/34562
```go
p.error(syntax.Error{Pos: pos, Line: line, Msg: err.Error()})
```

We didn't include the suggested change because it was very late in the Go1.8 cycle and my
suggestion was a lot larger than the two liner change @griesemer made in 
https://go-review.googlesource.com/c/34721/

**Comment by griesemer** [comment]
@odeke-em While your change is maybe the right approach long-term, it's too large for the (small) issue, and doesn't fit the current error handling model (which is going to change anyway, down the road).

It appears that the test I added with https://go-review.googlesource.com/c/34721/ is passing, so we may not have an issue here, but I will investigate.

**Comment by griesemer** [comment]
@odeke-em It turns out your fix is actually the correct one - my initial approach won't work anymore due to the concurrency we have now (pragcgo is called concurrently since files are parsed concurrently). Working on a correct solution...

**Comment by odeke-em** [comment]
Cool, glad to know it worked 🍻
