### ISSUE TITLE
cmd/compile: handle subslices in range -> memclear optimization

### ISSUE THREAD

**Issue by josharian** [golang/go#18908]
```go
package p

func f(x []byte) {
	for i := range x {
		x[i] = 0
	}
}

func g(x []byte, a, b int) {
	for i := range x[a:b] {
		x[a+i] = 0
	}
}
```

The core of `f` gets compiled into a memclear call. The core of `g` does not, because the current pattern matcher looks for an exact match between the range expression and the LHS of the zeroing statement. We should expand this to allow the range expression to match the LHS of the zeroing statement plus slicing. The generated code should first generate any required bounds checks for the slicing, then call memclear with appropriately adjusted values, taking care if necessary not to generate a pointer to the end of the slice.

If/when this gets implemented, also update some quirky code in the compiler that was written to work around this shortcoming. (For a sample, grep for `tail :=`. I suspect https://go-review.googlesource.com/36212 will introduce more such code.)

This might be a good moderate-difficulty medium-sized project for someone learning the compiler.

cc @martisch @randall77

**Comment by randall77** [comment]
The code in `g` should be `x[a+i] = 0`, right?

**Comment by josharian** [comment]
Yes. Thanks. :)

**Comment by josharian** [comment]
(Or `x[i] = 0` if `a` is `0`, e.g. if the range expression is `x[:b]` or `x[0:b]`. I know you know this, just writing out extra details in case someone wants to use this as a starter issue.)

**Comment by minux** [comment]
Because it's easy to get wrong on the index for the 2nd form, I still
prefer to create a temp slice and then use the first form (unless a = 0).

**Comment by martisch** [comment]
Looks like a nice project and i am happy to work on it for 1.9.
I just will not have time for it in the next 3 weeks as i want to get some other CLs wrapped up first. Self assigning to me now but if someone feels strongly about finishing this earlier just reassign.

**Comment by martisch** [comment]
Had a quick look whats involved and i think this is not as localized a change as i thought. 

By the time we get to memclrrange the order pass seems to have moved the slicing into a temporary. So we would need to add a isMemclrrange and intercept that case early by adding a OCLEARRANGE Node and teach order and other walks to not hide the slicing away from memclrrange. But adding that much special casing to write e.g.:

```
for i := range x[:b] {
	x[i] = 0
}
```

instead of 

```
y := x[:b]
for i := range y[:b] {
	y[i] = 0
}
```

does not seem to pay for the added complexity in the compiler.

Thoughts or hints how to possible make adding this feature easier (or if i understand the interference from the order pass wrong)?

**Comment by josharian** [comment]
> does not seem to pay for the added complexity in the compiler.

I agree. I think we should simply not do this. Thanks for digging into it, @martisch.
