### ISSUE TITLE
cmd/go: get should fall back to the git protocol

### ISSUE THREAD

**Issue by willfaught** [golang/go#18927]
`go get` doesn't work for private GitHub repos because it only tries HTTPS (or HTTP if you use -insecure IIUC). Why not have a fallback for HTTPS that tries SSH as well?

**Comment by rakyll** [comment]
AFAIK, URL rewrite via a git config is working  for others but we need a more reliable solution for this case. It is a large majority of the users who has to maintain private packages and `go get` doesn't support such a common case out of the box.

URL rewrite config:
```
git config --global url."git@github.com:".insteadOf "https://github.com/"
```

**Comment by willfaught** [comment]
That's the workaround I use, but now I have to use a make file to ensure
Git is configured correctly on new machines like Travis. This makes the Go
tool useless out of the box, and one of the nice things about Go in my
opinion is that you don't need make to build code.

I think it should actually try SSH before HTTPS, but I'll take even SSH
being the fallback.

**Comment by johansglock** [comment]
I feel this is more a documentation issue rather then a problem that needs solving, I'm perfectly happy using .netrc authentication for example:
https://gist.github.com/cactus/3925422

In the case of git there seem to be plenty more solutions (which I haven't tested):
https://git-scm.com/docs/gitcredentials

Go uses different VCS and so far as I know has chosen to use HTTP(S) as it's common transport protocol. For me it would make more sense to document how each VCS would be properly configured for authentication since in the end it should be the responsibility of the VCS to authenticate.

Adding SSH as an extra transport protocol seems unnecessary complicated to combine with canonical imports and any other potential edge cases.

**Comment by willfaught** [comment]
It uses http/s because they're most commonly left open in firewalls (from the Go FAQ, if I recall correctly). SSH is yet another common transport that any VCS could use; how they use it, I shouldn't have to care about; it should work out of the box. If I have to configure a VCS to use SSH, then in general I have to know what VCS a package is hosted with before I try to import it.

**Comment by rsc** [comment]
I think private Github repos work with HTTPS. The assertion above is that they only work over SSH. Can someone clarify?

**Comment by johansglock** [comment]
They work over HTTPS by provisioning a .netrc config for example.

**Comment by willfaught** [comment]
@rsc If private GitHub repos did work with HTTPS, then wouldn't the Go FAQ explain how to do that instead of how to do the Git URL rewrite configuration?

**Comment by rsc** [comment]
I sent out a doc update in response to the comment above, and then we'll call this fixed.

golang.org/cl/107775.
