### ISSUE TITLE
crypto/subtle: ConstantTimeCompare leaks information about whether the compared slices are of equal length

### ISSUE THREAD

**Issue by opennota** [golang/go#18936]
`ConstantTimeCompare` [returns early](https://github.com/golang/go/blob/6ee8c6a7ce30a3c0613617dcc182874d36b2ea94/src/crypto/subtle/constant_time.go#L13-L15) if its arguments are of different length, thus if one of the slices is controlled by an attacker, the length of the second one can be leaked.

I think the doc comment should warn about using `ConstantTimeCompare` for comparing slices of different lengths.

**Comment by odeke-em** [comment]
@opennota this was previously discussed in an issue https://github.com/golang/go/issues/16336#issuecomment-238097001 by @agl 
saying 
<img width="880" alt="screen shot 2017-02-03 at 11 14 16 pm" src="https://cloud.githubusercontent.com/assets/4898263/22616228/87dd9030-ea66-11e6-9664-13e3669603d6.png">

I'll let him chime and then close the issue if it suffices or if necessary to document.

**Comment by minux** [comment]
As discussed previously, using ConstantTimeCompare to compare slices of
different length is simply a design error (the code should have already
rejected such obviously invalid input).

In fact, there is no way to write a constant time implementation that could
handle the case where the inputs are of different length in constant time.
If you know how to write one, please don't hesitate to show one.

Additionally, this information leak is not interesting, because generally
the attacker already know the length of the correct slice (e.g. when it's
implementing a HMAC, then the length is the length of the underlying hash
function), so there is no need to hide this.

**Comment by opennota** [comment]
[The commit](https://github.com/golang/go/commit/446bfffcd6cfcaca141988a9d844aac61a704866) which made `ConstantTimeCompare` return zero instead of panicking says

> This is more useful than panicking, since otherwise every caller needs to do the length check before calling; some will forget, and have a potential submarine crasher as a result.

And so now some will forget and never know of their error? Is that more useful?

**Comment by minux** [comment]
Even though I don't agree with the change at that time, that ship has
already sailed and we can't change the behavior now.

**Comment by opennota** [comment]
@minux  The issue is about documentation.

**Comment by minux** [comment]
The docs says:
The time taken is a function of the length of the slices and is independent
of the contents.

I think it already implies that it's not constant time for slices of
different lengths.

**Comment by arvenil** [comment]
Some people are using `ConstantTimeCompare` for checking plain-text `BasicAuth()` credentials https://stackoverflow.com/a/39591234/916440

Do I understand correctly that this way attacker can guess password length because it will return immediately if password has different length? So this kind of usage mitigates only half of timing attacks? After guessing the length, then `ConstantTimeCompare` protects from guessing the content.

**Comment by ALTree** [comment]
@arvenil are you suggesting we do something? Like a doc change making it even more clear than the function will return immediately if the slices have different lengths? If yes, please open a new issue. Closed issues are not monitored.

**Comment by arvenil** [comment]
Well, firstly I would like to know what do you think about such usage like
I've mentioned for BasicAuth. I'm not a security expert but to me this
falls into giving false impression of security. It would be nice if golang
team could provide goish way to securely do BasicAuth. In case of
`ConstantTimeCompare` I liked the initial implementation. Changing doc also
could help as current doesn't seem to be obvious of consequences of using
it for slices with different size.

If it's worth to create new issue for that I can do it;)


Best, Kamil

On Jun 27, 2017 8:59 PM, "Alberto Donizetti" <notifications@github.com>
wrote:

@arvenil <https://github.com/arvenil> are you suggesting we do something?
Like a doc change making it even more clear than the function will return
immediately if the slices have different lengths? If yes, please open a new
issue. Closed issues are not monitored.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/golang/go/issues/18936#issuecomment-311452783>, or mute
the thread

**Comment by agl** [comment]
When `ConstantTimeCompare` panicked on unequal lengths, it ended up being a subtle crash in several cases. That's why it was changed to be less sharp. However, since constant-time requires a fixed memory-access pattern for all inputs, it's not possible to compare variable length strings in constant-time. Calling these functions in that context is fundamentally a misunderstanding. That's why they're in a package called `subtle`.

(Although, at least it'll still stop the contents of the secret leaking, even if the length of the secret still leaks.)
