### ISSUE TITLE
cmd/internal/obj/ppc64, cmd/link/internal/ppc64: change function alignment to 16

### ISSUE THREAD

**Issue by ceseo** [golang/go#18963]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8rc3

### What operating system and processor architecture are you using (`go env`)?
ppc64le, Linux

### What did you do?
I noticed that cmd/internal/obj/ppc64/asm9.go and cmd/link/internal/ppc64/l.go set funcAlign to 8 bytes.

### What did you expect to see?
The function alignment on Power should be 16 bytes, as stated by the User Manual: "**Branches** not from the last instruction of an aligned quadword and **not to the first instruction of an aligned quadword cause inefficiencies in the IBuffer**".

I'll submit a small change shortly to address this.

**Comment by laboger** [comment]
Other compilers and assemblers that target ppc64x use function alignment 16.
This change is related to #14935.  We need the right function alignment first to determine if adding an alignment directive is worthwhile.

Carlos is generating some performance information on this change as requested.

**Comment by laboger** [comment]
It is hard to find a benchmark that shows a performance improvement due to this change alone, because most golang mini benchmarks are highly dependent on loops, and if the function alignment is changed then loop alignment might change from good to bad causing a degradation.

All other compilers and assemblers for ppc64x use 16 as the function alignment.  In theory it should improve performance by a few percent.  It would be more important if we had a way to indicate which loops should be aligned but we currently do not.
