### ISSUE TITLE
template.ParseFiles(filename... string) does not support funcMap

### ISSUE THREAD

**Issue by ittaigolde** [golang/go#18998]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

template.New(....).Funcs(funcMap) is the way to define templates functions. This functionality is missing from the ParseFiles helper function

### What did you expect to see?

support for adding functions to ParseFiles

**Comment by odeke-em** [comment]
Hello there @ittaigolde, ParseFiles' signature is
```go
 func ParseFiles(filenames ...string) (*Template, error)
```

It needs to return an error otherwise the caller would never be able to handle errors that
we encounter quite often if not properly used.
It returns you a *Template on which you can invoke Template.Funcs(funcsMap).

Now just in case you'd like to continue with the chaining as you did with template.New(...),
you can invoke `template.Must(template.New(...).ParseFiles(...))`, but this means that you
like living on the edge and can tolerate panics if you encounter an error in `template.Must()`
that returns a *Template hence we can directly invoke .Funcs on it.

I don't see us changing the signature of ParseFiles.

In the future, for questions about Go, you can ask questions at https://golang.org/wiki/Questions.
