### ISSUE TITLE
Go Templating : Problem with {{if eq on range & variable comparision

### ISSUE THREAD

**Issue by jmlambert78** [golang/go#19008]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
Windows

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Here is the piece of the template tha causes problem 

```
<label for="Org">DC :{{.Roles.DC}}</label>
				<select name="Org">
					{{range $key, $dc := .DCs}}
					<option value="{{$dc.Name}}" **{{if ne $dc.Name .Roles.DC}}selected="selected"{{end}}**  >{{$dc.LongName}}</option>
					{{end}}
				</select>
```

**The issue comes when I use the  .Roles.DC comparision,** if I put a constant string, it works.
Also the ROles.DC exists, as it is displayed on the DC:{{.Roles.DC]] correctly.

### What did you expect to see?
I expect the selected keyword inserted when the option value = .Roles.DC 

### What did you see instead?
I get an {"message":"Internal Server Error"}

**Comment by robpike** [comment]
Please provide a complete runnable program that demonstrates the error.

**Comment by jlubawy** [comment]
I was curious so I made a working example here (it includes the fix detailed below): https://play.golang.org/p/XTTnvKqY7h

The problem is that when you iterate over the DCs in ```{{range $key, $dc := .DCs}}``` the '.' operator is now referring to the current DC (in other words, the '.' and $dc are the same object). So when you call ```{{if ne $dc.Name .Roles.DC}}``` it causes a panic because DC has no field '.Roles' (assuming a 'DC' doesn't have a fields '.Roles' from your description).

To fix the code you need to change ```.Roles.DC``` to ```$.Roles.DC```. The $ is set to the initial value of . when Execute is called [[1]](https://golang.org/pkg/text/template/#hdr-Variables).

**Comment by jmlambert78** [comment]
thx, very good answer.

2017-02-10 11:14 GMT+01:00 Josh Lubawy <notifications@github.com>:
