### ISSUE TITLE
cmd/compile: bad return shows <T> in type list

### ISSUE THREAD

**Issue by rsc** [golang/go#19012]
```
$ cat /tmp/x.go
package p

func f(x int, y uint) {
	z := x - y
	return x > z
}
$ go tool compile -S /tmp/x.go
/tmp/x.go:4: invalid operation: x - y (mismatched types int and uint)
/tmp/x.go:5: too many arguments to return
	have (<T>)
	want ()
```

The problem is that z's type is not known, because x-y does not type check
(already reported), and I guess that makes x > z's type not known,
which in turn displays as `<T>`.

But since the type of the result is not known at all, probably
it's safe not to complain about the argument count for the return at all.

So probably the entire error at line 5 should be suppressed.

/cc @griesemer @mdempsky

**Comment by josharian** [comment]
cc @odeke-em

**Comment by odeke-em** [comment]
Thanks for the shoutout as always @josharian 🙏🏾

@rsc in this case we already got an error on line 4, but am thinking if we suppress the one on
line 5, in the future if we haven't previously encountered an error or if the type is unknown with no
previous error. In cases where the type is unknown, perhaps we can change the message to be like it was in issue https://github.com/golang/go/issues/4215 before CL https://go-review.googlesource.com/25156
so that error message will be 
```shell
$ go tool compile -S /tmp/x.go
/tmp/x.go:4: invalid operation: x - y (mismatched types int and uint)
/tmp/x.go:5: too many arguments to return
```
and we can still indicate to them that there is an error on that line.

What do y'all think?

**Comment by odeke-em** [comment]
I've mailed https://go-review.googlesource.com/36806.
