### ISSUE TITLE
http.CloseNotifier regression?

### ISSUE THREAD

**Issue by creack** [golang/go#19022]
Hello,

I just found out that travis was failing one of my [package](https://github.com/creack/ehttp) on `tip` and after a quick
test, it seems that it might be an issue with `http.CloseNotifier`.

#### What did you do?

Use http.CloseNotifier to get notification of Close.

This simple test was working in 1.6 and 1.7: https://play.golang.org/p/31vBaJrp-g

1. Create a httptest.Server, write "hello" and pull the closenotifier chan.
2. Wait 2 seconds for the chan to receive the notification.

#### What did you expect to see?

CloseNotifier chan to receive a message.

#### What did you see instead?

Timeout.

#### Does this issue reproduce with the latest release (go1.7.5)?

No, works fine on go1.7.5.

#### System details

```
go version devel +f44e587031 Fri Feb 10 13:40:08 2017 +0000 darwin/amd64
GOARCH="amd64"
GOBIN="/Users/guillaume/go1.8/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/guillaume/go1.8"
GORACE=""
GOROOT="/Users/guillaume/goroot"
GOTOOLDIR="/Users/guillaume/goroot/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tj/br466x5s0qd1f7d248bp1chc0000gn/T/go-build456915522=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version devel +f44e587031 Fri Feb 10 13:40:08 2017 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +f44e587031 Fri Feb 10 13:40:08 2017 +0000 X:framepointer
uname -v: Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
lldb --version: lldb-360.1.70
gdb --version: GNU gdb (GDB) 7.12.1
```

**Comment by bradfitz** [comment]
Doesn't look like a regression. It seems you've been relying on undefined behavior. The docs even at Go 1.6 say:

https://golang.org/pkg/net/http/#CloseNotifier

>        // After the Handler has returned, there is no guarantee
>        // that the channel receives a value.

A few other comments about your test code: 

* `w.Header().Set("Connection", "Close")` -- the HTTP spec does say the `connection-option` is case-insensitive, but I've never seen anything other than lowercase in the wild. I wouldn't be surprised if there were bugs in the ecosystem assuming lowercase. If you find Go bugs around this, please file them. 
* the assignment & read of `ch` looks racy. There's nothing explicitly ordering those. I suppose the http request indirectly. The race detector says you're getting lucky (false negative?), but I'd audit your wrapper library to be sure.
* why the `defer func() { _ = resp.Body.Close() }()` instead of `defer resp.Body.Close()` ? style only, I suppose. But the latter should also be faster, if that's a concern.
* `resp.Body.Read(buf)` is not guaranteed to read all of `"hello"`. It could read only a few bytes per the `io.Reader` contract. You'd want `io.ReadFull` or `ioutil.ReadAll(io.LimitReader(..))` probably.

You'll probably need to update your wrapper library for Go 1.8 and do your own notification that the handler is done. Or use the `Reqest.Context().Done()` channel instead/additionally, which will end when the handler ends.
