### ISSUE TITLE
cmd/bug: does nothing if there is no windowing system

### ISSUE THREAD

**Issue by broady** [golang/go#19131]
### What version of Go are you using (`go version`)?

go1.8

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Run `go bug` on a headless system.

### What did you expect to see?

Anything.

### What did you see instead?

Nothing.

```
$ go bug
$
```

**Comment by bradfitz** [comment]
Let's bug @josharian.

**Comment by shurcooL** [comment]
> ```
> $ go bug
> $
> ```

What was the exit code from `go bug` (ala `echo $?`)?

**Comment by broady** [comment]
Zero exit code.

**Comment by josharian** [comment]
`go bug` should have handled the fallback case where there was no browser: https://github.com/golang/go/blob/master/src/cmd/go/internal/bug/bug.go#L63.

Would you mind instrumenting the browser opening code and finding out what's happening there? See https://github.com/golang/go/blob/master/src/cmd/internal/browser/browser.go#L38. I'd be curious about which browser command is succeeding, and what happens if you run it manually.

**Comment by rakyll** [comment]
@broady,

Can you share any more information about the headless system you are on? I cannot experience this neither when I am ssh'ing into Debian or Ubuntu.

**Comment by ronin13** [comment]
Able to reproduce on a headless system. `web.OpenBrowser` doesn't check if the command succeeds or not (only that it is runnable) and doesn't print any stderr, so if any of the browsers in https://github.com/golang/go/blob/master/src/cmd/internal/browser/browser.go#L17 are installed (xdg-utils  (providing xdg-open) is the one most probably installed on a headless system), it will silently fail on headless system with exit code of 0 without printing the body.

```
BROWSER=/usr/bin/false go bug
echo $?
0
```

It is better to log the browser being used to open (in browser.go) and/or to provide a `-headless` option to `go bug` to just print. (otherwise, checking `DISPLAY` and printing is not portable).

**Comment by josharian** [comment]
This will impact any command that opens a browser, including go trace, go tool pprof, etc.

We don't check the exit code or wait for the command because some browser commands block.

I don't want to log every time; that'd be ugly, and almost all invocations succeed.

Let's start by fixing the specific problem on the specific system, even if it is not very portable. Sounds like maybe checking DISPLAY might work?

**Comment by ronin13** [comment]
In the last case, one can do like:

```
 diff --git a/src/cmd/go/internal/bug/bug.go b/src/cmd/go/internal/bug/bug.go
 index 963da94c49..214108d945 100644
 --- a/src/cmd/go/internal/bug/bug.go
 +++ b/src/cmd/go/internal/bug/bug.go
 @@ -60,7 +60,7 @@ func runBug(cmd *base.Command, args []string) {

         body := buf.String()
         url := "https://github.com/golang/go/issues/new?body=" + web.QueryEscape(body)
 -       if !web.OpenBrowser(url) {
 +       if len(os.Getenv("DISPLAY")) == 0 || !web.OpenBrowser(url) {
                 fmt.Print("Please file a new issue at golang.org/issue/new using this template:\n\n")
                 fmt.Print(body)
         }
```

This should work on a headless systems with Xorg (which covers everything except windows).

Tested with:

```
DISPLAY= $HOME/bin/go bug     # Prints to terminal
```

and 

```
echo $DISPLAY
:0
$HOME/bin/go bug       # Opens browser.
```

**Comment by bradfitz** [comment]
DISPLAY won't work on OS X, though. (at least, I assume our target audience is not XQuartz users) Will it even work on Wayland? Or do you also have to check WAYLAND_DISPLAY?

**Comment by ronin13** [comment]
For Wayland, yes, $WAYLAND_DISPLAY needs to be checked.  Does the X server in OSX export any similar variable?

**Comment by bradfitz** [comment]
macOS doesn't use an X server.

**Comment by josharian** [comment]
Could we only use display if there is a DISPLAY envvar? Or hard code some OSes?

And this code belongs in the browser-handling code, not go bug.

**Comment by ronin13** [comment]
Regarding browser.go, strictly speaking, there are browsers which work without X server, will be harder to impose with that constraint there. 

But, again, if we restrict to graphical browsers only, then one can fail early in https://github.com/golang/go/blob/master/src/cmd/internal/browser/browser.go#L20 depending on the platform (so fail only for known platforms in the beginning).

**Comment by broady** [comment]
More details on my setup:

```
$ echo $BROWSER,$DISPLAY
,
$ which xdg-open
/usr/bin/xdg-open
```

Added some logs and confirm xdg-open is the command being used.

Suggested fix: wait 5 seconds for the process to exit. If it's nonzero or takes >5 seconds to return, print out the URL to stdout.

That is, keep the current behaviour if the command returns a nonzero exit code within 5 seconds.

**Comment by shurcooL** [comment]
I've seen at least one reported case where where "xdg-open" seemed to block and not return until browser was closed. To help the issue, I had to run it in a background goroutine. See https://github.com/shurcooL/Go-Package-Store/commit/a15fc561fd6d4e10f65506b3842dba7799fa4b70 and https://github.com/shurcooL/Go-Package-Store/issues/26#issuecomment-70617610.

However, this was 2 years ago, and it looked like an outdated, possibly misconfigured linux system.

**Comment by josharian** [comment]
> Suggested fix: wait 5 seconds for the process to exit. If the exit code is nonzero or takes >5 seconds to return, print out the URL to stdout.

I think waiting 5s is reasonable. On most systems, the command exits almost immediately, so I doubt anyone will notice.

But we shouldn't print the URL to stdout. As I keep saying, the fix should go in the browser-opening code, not in 'go bug', and each individual command can decide how to handle the browser not opening; 'go bug' already has handling for that case.

**Comment by broady** [comment]
Well, apparently xdg-open does also complete within 5 seconds with a non-zero exit code.

I hooked up stdin/stdout and get the following:

stderr:
```
/usr/bin/xdg-open: line 461: links2: command not found
```
stdout:
```
<snip>
Looking up host
<snip>
```

Presumably it's opening up links (I don't have links2 installed) but exiting right away.

I guess xdg-open is at fault here? It's opening up links without a tty.
