### ISSUE TITLE
cmd/objdump: implement arm64 disassembler

### ISSUE THREAD

**Issue by randall77** [golang/go#19157]

**Comment by bradfitz** [comment]
I see that ARM released machine-readable architecture specs:

https://alastairreid.github.io/alastairreid.github.io/ARM-v8a-xml-release/

/cc @rsc @cherrymui

**Comment by bradfitz** [comment]
@williamweixiao, is this happening for Go 1.9? It's looking pretty late, unless the work is already done and non-invasive to other ports.

**Comment by williamweixiao** [comment]
@bradfitz I submitted the patch (https://go-review.googlesource.com/c/43651/) three weeks ago but still get no feedback. The patch is non-invasive to other ports and parts at all.

**Comment by cherrymui** [comment]
A CL is submitted for x/arch. We can review and submit the CL to x/arch during the freeze. I don't think this will be in Go 1.9.

**Comment by bradfitz** [comment]
@cherrymui, I'm fine with this as a late addition if you can review these CLs. I'm a little sad we've let this sit so long.

I'm okay with it as a late addition because it's well isolated from everything else. There's very little risk.

**Comment by bradfitz** [comment]
@randall77, maybe you can help review too?

**Comment by cherrymui** [comment]
I thought it probably includes some new instructions (in CL https://go-review.googlesource.com/c/41654/) which will not go into Go 1.9, so this as well. But I may be wrong.

**Comment by williamweixiao** [comment]
@cherrymui yes, it supports almost all armv8 instructions and is fully tested by comparing to GNU objdump output. As for Go syntax part, the basic instructions (include FP) are fully tested with assembler as inputs and we will add these tests into assembler soon. The only untested part is for the new instructions added by CL41654 since it has not been merged. But we'd like to keep this part and submit bug fixing patch if needed in the future because the decoder table is automatically generated by tool and it's hard to isolate new instructions.

**Comment by williamweixiao** [comment]
The issue can be closed since the patch (CL 43651) has been merged.

**Comment by bradfitz** [comment]
@williamweixiao, let's keep this open until it's vendored into std for Go 1.10.

**Comment by williamweixiao** [comment]
When will it be vendored into go repo? 
I need to submit another patch to "cmd/internal/objfile" for enabling arm64 disassembler to be used by other tools such as objdump and pprof.

**Comment by bradfitz** [comment]
@williamweixiao, there is no automatic process that vendors this into the main go repo. It requires a human to do that manually, and it's nobody's job. It is done when needed, by whoever needs it. Feel free to send a change.
