### ISSUE TITLE
x/tools/go/loader: tests are too brittle

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19152]
The x/tools/go/loader tests have a history of breaking whenever something in the standard library
changes.

Or breaking when testing Go 1.6 vs Go 1.7 vs Go 1.8 vs Go tip, etc.

I think it's time to rethink those tests to not be a maintenance burden.

(Latest example: https://go-review.googlesource.com/c/37148/)

/cc @ianlancetaylor

**Comment by dmitshur** [comment]
Another instance is #38318.

**Comment by stamblerre** [comment]
Given that `golang.org/x/tools/go/loader` is now deprecated, I think it's reasonable to say that no one will probably have the time/desire to invest into fixing this issue. In that case, I think we can either continue to fix breakages like https://github.com/golang/go/issues/38318 as they come up (and make sure that they get caught sooner rather than later), or decide that these tests aren't worth it and disable them. Given the discussion on https://golang.org/cl/227772, I would say that we do consider these tests worthwhile, in which case I propose we close this issue and fix breakages as they happen.
