### ISSUE TITLE
x/tools/cmd/goimports:  allow multiple -local flags

### ISSUE THREAD

**Issue by gregory-m** [golang/go#19188]
My company use flowing imports schema:

```
import (
    "some-std-lib"
    "other-std-lib"

    "github.com/some/dependency"
    "github.com/some/other-dependency"

    "mycompany.com/foo/bar"
    "mycompany.com/foo/baz"
)
```

goimports perfectly supports such imports schema by using -local flag.

But our company acquire some other company and they code also become local to us, e.g. we want to use flowing imports schema:

```
import (
    "some-std-lib"
    "other-std-lib"

    "github.com/some/dependency"
    "github.com/some/other-dependency"

    "mycompany.com/foo/bar"
    "mycompany.com/foo/baz"
    "othercompany.com/foo/bar"
)
```

Can we add multiple  -local flags support to goimports?
If no objections I will create CL.

**Comment by bradfitz** [comment]
Seems like your company is big enough now to warrant having a internal fork of goimports with your desired policy.

I forgot about the `-local` flag. I don't normally approve flag additions, especially to goimports where users don't really run it by hand.

But sure. Since it's already there, feel free to make it support comma-separated value or something. That's probably the least invasive.

**Comment by mvdan** [comment]
> especially to goimports where users don't really run it by hand.

I'm curious, why do you think that? I do run it manually quite often.

**Comment by bradfitz** [comment]
I'm pretty sure that almost all users run it automatically from their editor on save, and not by hand.

**Comment by mvdan** [comment]
Sure, but editors can still make use of these options if I understand correctly.

**Comment by cjcjameson** [comment]
next level for this would be to fix the ordering more strictly based on the comma-separated list, but good enough for now. Thank you for this feature!
