### ISSUE TITLE
ConnBeginTx

### ISSUE THREAD

**Issue by PublicForest** [golang/go#19192]
What version of Go are you using (go version)?
Go 1.8 

Hi

Sorry for not raising this during the beta, but I just started testing mysql read only transactions. 

It appears that query cancellation in mysql would require a non-trivial design https://github.com/go-sql-driver/mysql/issues/496 which might delay the availability of TxOptions.

Perhaps context and TxOptions should be separated into two interfaces as they appear to be two orthogonal concerns..

Something like:
```
type ConnBeginTx interface {
	BeginTx(opts TxOptions) (Tx, error)
}

type ConnBeginCancelableTx interface {
	BeginCancelableTx(ctx context.Context, opts TxOptions) (Tx, error)
}
```
Regards,

-Itai

**Comment by bradfitz** [comment]
Sorry, too late.

The API is now frozen due to the Go1 compat promise.

Closing because any fix will have to be in the MySQL driver at this point. I'll trust @kardianos to track the MySQL driver progress and file concrete bugs for API additions in database/sql as appropriate. But we can't change or remove things now.
