### ISSUE TITLE
html/template: Parse overrides templates with empty templates

### ISSUE THREAD

**Issue by DDRBoxman** [golang/go#19204]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ddrboxman/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hf/vcfpg1rd77qdcxmt5dwqr2nw0000gn/T/go-build688954702=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

https://play.golang.org/p/xsexXsdE5x

### What did you expect to see?
2009/11/10 23:00:00 
placeholder

### What did you see instead?
2009/11/10 23:00:00 

### Other Info
https://golang.org/pkg/html/template/#Template.Parse
"A template definition with a body containing only white space and comments is considered empty and will not replace an existing template's body"

**Comment by bradleypeabody** [comment]
One other important point on this issue is that the behavior is not consistent.  I ran into this same issue separately and made this example: [https://play.golang.org/p/mpBOEdhkFR](https://play.golang.org/p/mpBOEdhkFR)  Both playground examples exhibit different behavior if you open it, add a space somewhere (to force a cache miss), and hit run again.  Do that about 10-20 times and you should get at least one or two times where it produces a different result.  Some sort of race condition happening here.

**Comment by robpike** [comment]
This has been fixed by recent changes, most likely https://go-review.googlesource.com/c/38420/
