### ISSUE TITLE
x/net/http2/hpack: optimize constantTimeStringCompare

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19238]
hpack's constantTimeStringCompare shows up in profiles as slow.

Investigate optimizing it.

/cc @jeffallen @tombergan

**Comment by ALTree** [comment]
"Optimize" like in "call it less" or like in "make it faster"? If uglier code is fine, unrolling the loop gives a nice boost (at least on amd64):

```
ConstantTimeStringCompare/3-4     6.20ns ± 1%  8.53ns ± 0%  +37.48%  (p=0.000 n=7+8)
ConstantTimeStringCompare/4-4     7.17ns ± 0%  7.55ns ± 0%   +5.32%  (p=0.001 n=7+7)
ConstantTimeStringCompare/16-4    18.9ns ± 0%   7.6ns ± 0%  -59.99%  (p=0.000 n=7+8)
ConstantTimeStringCompare/64-4    66.2ns ± 0%  18.5ns ± 1%  -72.07%  (p=0.000 n=8+8)
ConstantTimeStringCompare/256-4    212ns ± 0%    61ns ± 1%  -71.06%  (p=0.000 n=7+8)
ConstantTimeStringCompare/1024-4   804ns ± 1%   229ns ± 0%  -71.50%  (p=0.000 n=8+8)
```

**Comment by bradfitz** [comment]
> "Optimize" like in "call it less" or like in "make it faster"?

Either/both?

**Comment by TocarIP** [comment]
How long are typical inputs to constantTimeStringCompare?
For long strings pseudo-simd can help:
x:= a[0] | a[1] << 8 ..  //should compile to single bound check + machine-word sizedload
y:= b[0]...
z |= x^y
However code will be different for little and big endian, and won't work on architectures requiring aligned loads. It will also be quite ugly. Alternatively unsafe (or even asm) can be used.
In any case representative benchmarks are needed as a first step.

**Comment by bradfitz** [comment]
Inputs are HTTP header values, so typically less than 100 bytes. (The longest would probably be some random UUID/hex-looking session identifier.)

**Comment by bradfitz** [comment]
@tombergan, are you able to share a histogram of HTTP header value sizes from the Flywheel data?

I tried looking at https://telemetry.mozilla.org/ too but don't see it.

**Comment by tombergan** [comment]
I'm not sure why constant time string comparison is needed in the first place. [RFC 7541](http://httpwg.org/specs/rfc7541.html) does not mention a need for this AFAICT. I couldn't find any reported vulnerabilities after a quick search. It seems like staticTable could be implemented as a map rather than an array. I looked at the source code for two other HTTP2 implementations. Neither appears to use constant-time string comparisons:

* [nghttp2](https://github.com/nghttp2/nghttp2/blob/4aab15999d88f9bbe9fcf5ccd72a95564b41d71b/lib/nghttp2_hd.c#L497)
* [Chrome](https://cs.chromium.org/chromium/src/net/spdy/hpack/hpack_header_table.cc?rcl=c11089bf7758213d1259cf23880119e5c407a83d&l=86)

/cc @tatsuhiro-t who originally wrote the code, thoughts?

**Comment by fraenkel** [comment]
There was a statement regarding prevention of timing attacks, but it was removed.
See https://github.com/http2/http2-spec/commit/f4ec4e3f0d17459a8af9eb80645ad0c1d6520972

**Comment by tombergan** [comment]
Thanks for digging that up. In that case, I think it's safe to remove the constant-time string comparison entirely.

**Comment by bradfitz** [comment]
SGTM. Sent you a CL.

**Comment by tatsuhiro-t** [comment]
I think it was removed because Never Indexed has been introduced for the sensitive header fields.
