### ISSUE TITLE
crypto/des: invalid key size 32

### ISSUE THREAD

**Issue by squallcx** [golang/go#19254]
des.NewTripleDESCipher is 24 key length, who to handle 32 key length condition?

**Comment by ALTree** [comment]
Is this a question or a bug report?

The first 3 lines of `NewTripleDESCipher` are:

```
if len(key) != 24 {
	return nil, KeySizeError(len(key))
}
```

so you'll need to handle any key-length-related error that the function returns.

We don't use the issue tracker for questions, so if you have further questions please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking them. 

Closing, since this appears to be not-a-bug-report.
