### ISSUE TITLE
x/crypto/acme/autocert: support ForceRSA as a per domain option

### ISSUE THREAD

**Issue by phuslu** [golang/go#19265]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8

### What did you expect to see?
Currently, [autocert.Manager.ForceRSA](https://github.com/golang/crypto/blob/453249f01cfeb54c3d549ddb75ff152ca243f9d8/acme/autocert/autocert.go#L148) is a global option for all domains. I expect it's a per domain option.
e.g.
```
type Manager struct {
	GetForceRSA func (domain string) bool
}
```
we can build multiple-domains https server with mixed RSA/ECC certificates base on this option.

**Comment by bradfitz** [comment]
Sorry, this isn't an option I want to see added.

ForceRSA is a bit gross on its own. I don't think it needs more complication and configuration around it, especially since you can already wire it up yourself: just implement tls.Config.GetCertificate and delegate to two different Managers (one with true vs false) depending on the hostname.

I think that the number of users of such a feature would be low enough (and decreasing over time) to not warrant adding this complexity for everybody.
