### ISSUE TITLE
x/tools/cmd/godoc: global variable example is not rendered

### ISSUE THREAD

**Issue by rakyll** [golang/go#19372]
x/oauth2 package wants to attach an example to a global variable, see https://github.com/golang/oauth2/commit/efb10a30610e617dbb17fc243f4cc61a8cfa2903.

godoc fails to render the example under `HTTPClient` even though it lists the example in the table of contents.

See the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/108380/23525539/aab4b326-ff43-11e6-9915-38e03fa6ba0f.png)

**Comment by agnivade** [comment]
@rakyll - Looks like you fixed it with this commit https://github.com/golang/oauth2/commit/d89af98d7c6bba047c5a2622f36bc14b8766df85. I think the example names have to match either a top-level function or a type, which is why `ExampleCustomHTTP` wasn't getting rendered, but `ExampleConfig_customHTTP` did.

Should this be closed then ?

**Comment by rakyll** [comment]
@agnivade, this issue looks obsolete now. I am closing it.
