### ISSUE TITLE
go/internal/gccgoimporter: misleading use of pkg parameter

### ISSUE THREAD

**Issue by mvdan** [golang/go#19407]
In https://github.com/golang/go/blob/d4451362c0fa47b25fc2e69129e68cbbee4a6bdf/src/go/internal/gccgoimporter/parser.go#L736, we have:

```
func (p *parser) discardDirectiveWhileParsingTypes(pkg *types.Package) {
        for {
                switch p.tok {
                case ';':
                        return
                case '<':
                        p.parseType(p.pkg)
                case scanner.EOF:
                        p.error("unexpected EOF")
                default:
                        p.next()
                }
        }
}
```

This seems off. Either we want to use `pkg` instead of `p.pkg`, or the parameter is unnecessary. I would assume the former is the correct solution, but opening this issue first to confirm that.

Found via https://github.com/mvdan/unparam.

**Comment by mvdan** [comment]
I've filed https://go-review.googlesource.com/c/37839/ to make it use `pkg` instead of `p.pkg`.

**Comment by shurcooL** [comment]
It seems most of `parser` methods take `pkg *types.Package` as first parameter. I've looked at the call graph, and if you trace it back to where it's being provided, it all comes from `p.pkg`. So in a way, all those `pkg` parameters are largely redundant.

Doing anything about that is probably out of scope for that CL, because you'd need to know what the owner of the code is planning to do next, but I just wanted to point it out.

**Comment by mvdan** [comment]
@shurcooL I assumed that to be the case, otherwise this `pkg` and `p.pkg` mixup should be breaking things. I opted for the smallest CL possible for now.
