### ISSUE TITLE
website: tip.golang.org godoc browsing is broken

### ISSUE THREAD

**Issue by josharian** [golang/go#19401]
https://golang.org/pkg/runtime/ shows docs for package runtime.

https://tip.golang.org/pkg/runtime/ shows an error.

cc @broady (is that right?)

**Comment by shurcooL** [comment]
I believe this is because of https://groups.google.com/d/msg/golang-codereviews/tju2mJPjAwI/N8RKEFRvAQAJ. Note that https://tip.golang.org/pkg/ also displays an error.

I've sent [CL 37768](https://golang.org/cl/37768) that fixes the issue, and its commit message contains a detailed explanation of the cause.

**Comment by shurcooL** [comment]
https://tip.golang.org/pkg/runtime/ works ok now, this issue can be closed.

**Comment by bradfitz** [comment]
@shurcooL, I gave you [github edit access](https://golang.org/wiki/GithubAccess). Feel free to close it yourself. :)

**Comment by shurcooL** [comment]
Thanks Brad!

Closing because this issue is resolved.
