### ISSUE TITLE
spec: `operators, delimiters, and special tokens` not used consistently

### ISSUE THREAD

**Issue by zerkms** [golang/go#19450]
At the moment the standard uses the term `delimiter` multiple (4) times as a syntactic/language unit but does not provide any definition for it.

Eg

> The following character sequences represent operators, delimiters, and other special tokens:

In this text there are operators and other lexical units are mixed together, without any explanation which is which.

Additionally to that the lexer https://github.com/golang/go/blob/752d7bad4fc6/src/cmd/compile/internal/syntax/tokens.go#L100-L111 adds more confusion and puts `.` to the section of delimiters, while in most other imperative programming languages it's a member access operator.

So, I think the terms might be clarified better.

**Comment by griesemer** [comment]
@zerkms I doesn't matter. Nothing depends on this definition. Where we care we enumerate the tokens explicitly.

It's clear what the operators are, there's a section about them. Delimiters delimit, which is they describe boundaries of something, and thus are pretty obviously all the various parenthesis and brackets.

It's just going to be a turf war trying to decide whether a ';' is a delimiter or a special token. The only reason why we don't just have operators and special tokens is that parenthesis, curly braces, etc. seem not that special.

I'll leave this open because there's some inconsistencies: The semicolon rules appear to count `++` and `--` as operators (which is not how they are defined elsewhere); and the general section on tokens doesn't mention special tokens. We should fix those sections. And perhaps just get rid of operators, delimiters and special tokens" in favor of "operators and other tokens" (or something along those lines). No need for needless complexity for the sake of taxonomy.

**Comment by zerkms** [comment]
> Delimiters delimit, which is they describe boundaries of something, and thus are pretty obviously all the various parenthesis and brackets.

What does the "delimiter" `.` delimits in the expression like `o.foo`?

**Comment by griesemer** [comment]
@zerkms Nobody does the spec say that `.` is a delimiter. For all practical purposes it's a special token.

**Comment by zerkms** [comment]
@griesemer the code does state it's a delimiter (which has a spelling mistake) https://github.com/golang/go/blob/752d7bad4fc6/src/cmd/compile/internal/syntax/tokens.go#L100-L111

In C++, C#, Java, ES - it's an operator. It's awkward to see semantically identical unit in Go that is classified differently

**Comment by ianlancetaylor** [comment]
I don't think you can blame the spec for something in the compiler code.  By all means send a CL to change the comment in the compiler.

**Comment by griesemer** [comment]
@zerkms Please leave that code and comment alone. It's needless churn. As I have said before, there is no formal definition of `delimiters`, nor does it matter in the spec or the compiler. I will clean up the spec where there are inconsistencies and that will be it.

As an aside, Go is not C++, C#, Java, nor ES. For what it's worth, the terminology `deliminator` is borrowed from the Pascal spec (1970), "Pascal - User Manual and Report", N. Wirth, Chap. 1, Notation and Vocabulary, which states, among other things, "The special symbols are operators and delimiters", and it predates all the languages you mentioned above (Pascal was developed around 1968-1969). We don't use it as consistently in the Go spec, which is what I am going to fix. Thanks.

**Comment by zerkms** [comment]
@iangudger 

> I don't think you can blame the spec for something in the compiler code. By all means send a CL to change the comment in the compiler.

I did not blame anything surely, it was just a quick demonstration on the inconsistent use of terms due to lack of definitions.
