### ISSUE TITLE
*Why Plugin Not available at Windows,MAC,...

### ISSUE THREAD

**Issue by lovegolang4fun** [golang/go#19517]
Hello,
Why `Plugin` Not available at Windows,MAC,...
https://tip.golang.org/pkg/plugin/
>Why only available on Linux?

It's just not good.
I'm about a month waiting for these cases.

When will this be done?
Do I wait enough? :full_moon_with_face: 

please do it.
Thanks a lot.

**Comment by questionpython** [comment]
i also need `PLUGIN` pkg. :heart:

**Comment by mvdan** [comment]
Dup of #19282. Removing +1 comments.

**Comment by lovegolang4fun** [comment]
Hello Golang Team,
When will it be done?:-1: 
I've been waiting for you a lot of time.

**Comment by mvdan** [comment]
@lovegolang4fun I believe asking for ETAs is not the best way to contribute to get something done :)

**Comment by lovegolang4fun** [comment]
Yes that's right.
But I have to complete my project require this functionality.

But in this case did not give any response from the Golang(Google) team!

**Comment by mvdan** [comment]
> Why do not specify time around? How much time is needed to complete this task?

Even assuming the best of scenarios, Go 1.9 won't come out until August (I think?). So it's impossible for Go plugins to land on Windows and OSX before then, unless you're willing to run on tip instead of a released version.

**Comment by mvdan** [comment]
In any case, follow issues like https://github.com/golang/go/issues/19282 for details on the Windows progress.

**Comment by jan4984** [comment]
at last of issue [#19282 ](https://github.com/golang/go/issues/19282), it is said "Vote with emoji reactions at top instead."  But users can not add reaction it if the issue is locked.  We really need a plan.

**Comment by mvdan** [comment]
The thread was locked because people wouldn't stop posting "+1" comments, so I don't think it will be reopened again. The issue will be worked on eventually, so adding reactions would not change things much.

If you would like to contriubute to the discussion, perhaps use this issue and @-mention the people there, open a new issue or send an e-mail to golang-dev.

**Comment by ianlancetaylor** [comment]
@jan4984 The truth is that voting on issue #19282 will have absolutely no effect on whether anybody implements Go plugins on Windows.  It requires somebody interested and able to do the work.  Simply voting in favor of an issue is not going to somehow create that person.

**Comment by jan4984** [comment]
Voting must have effect, that's why many open source projects have the voting system. There will always be new feature requests, the developer may pick the features people wanted.

**Comment by mvdan** [comment]
I might agree with you if people were voting properly. But since that particular thread was being spammed with +1 comments, it had to be locked. See https://github.com/golang/go/wiki/NoMeToo.

As Ian and myself have said, there are ways to help an issue get resolved. If you're interested in it and want pointers on where to get started, I'm sure people on the golang-dev list will be happy to help.
