### ISSUE TITLE
x/crypto/ssh: Support setting a banner for a server that shows before authentication

### ISSUE THREAD

**Issue by jaksi** [golang/go#19567]
This is described in [RFC 4252](https://tools.ietf.org/html/rfc4252#section-5.4).

**Comment by kissgyorgy** [comment]
I need this functionality also. I want to implement [TOFU authentication](https://en.wikipedia.org/wiki/Trust_on_first_use) and it's important to let users know when they authentication fails what's the problem. Currently this is not possible with x/crypto/ssh because `config.PublicKeyCallback` doesn't have access to the underlying transport and if authentication fails, `NewServerConn` conn will be `nil` so it's too late to send banner message after that call.

**Comment by GeorgeGkinis** [comment]
I had issues logging in with Password when faced with an auth banner from the remote server.
Specifically the error I was getting was : 

> ssh: handshake failed: ssh: parse error in message type 53

Adding a **_Language string_** field in userAuthBannerMsg definition solved it for me.

```
type userAuthBannerMsg struct {
	Message 	string `sshtype:"53"`
	Language 	string
}
```
