### ISSUE TITLE
cmd/vet: false negative in vet -shadow

### ISSUE THREAD

**Issue by mcandre** [golang/go#19597]
### What version of Go are you using (`go version`)?

```console
$ go version
go version go1.7 darwin/amd64
```

### What did you do?

`go tool vet -shadow` finds one shadow for the `hash` variable, but fails to notice the `password` shadow.

Source:

https://github.com/mcandre/go-ios7crypt/blob/61a282b2d8003e9372cbe37449c7008ee142f1fa/cmd/ios7crypt/main.go#L29-L43

Perhaps the shadow checker bombs out on the first occurrence, before it has a chance to scan the rest of the file?

**Comment by robpike** [comment]
The shadow tool is very weak and has many known bugs. I'll leave this open but don't expect a fix. A likelier resolution is a complete replacement of the checker.

**Comment by mvdan** [comment]
`go vet` has been rewritten since this issue was opened, and the `shadow` check is no longer available via a flag. It can still be installed, but manually from x/tools; see https://go-review.googlesource.com/c/go/+/154584/.

Given that the check never made it out of the "experimental" phase, and that it's no longer part of vet, and that noone plans to fix this issue in particular, I'm closing it for now.
