### ISSUE TITLE
go/fmt:  Inconsistent/unexpected formatting of map values

### ISSUE THREAD

**Issue by dlsniper** [golang/go#19607]
### What version of Go are you using (`go version`)?
go 1.8

### What operating system and processor architecture are you using (`go env`)?
Windows 10 / WSL

### What did you do?

I've formatted the code here: https://play.golang.org/p/ovFFE7vsGf

### What did you expect to see?

I've expected to see this: https://play.golang.org/p/6XpISWc-bq

### What did you see instead?

I've seen the code that appears initially. 

My question is: why does this happen? It's unexpected and I'd like to understand what's the rule behind this.

Thank you.

**Comment by mvdan** [comment]
This is expected - gofmt (or rather, go/printer) has a treshold, so that really long keys don't add tons of whitespace to short keys right next to them.

I don't know what the details of the mechanism are, but I'm sure the code isn't too complicated. There are other closed issues around this padding confusion.
