### ISSUE TITLE
test: add -ldflags -s and -w tests to all.bash

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#19753]
The `-s` and `-w` linker flags are documented, [commonly recommended](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/) (a bit my fault I guess), and mentioned as a workaround by a few issues (#11887, #19734).

However, they are associated to the folklore about strip(1) breaking binaries (which happens and is not Go's problem) and apparently not tested as part of the release process (https://twitter.com/davecheney/status/846844080227213312).

I'll try to find a bit of time to find out how the linker artifacts are tested and add rounds with `-w`, `-s` and both, but of course I'd be happy for someone to jump on it first.

**Comment by rsc** [comment]
We already build test binaries with -w when not leaving the binary behind. That is, if you run 'go test strings', the test binary (which is written to a temp directory, executed, and deleted) has no DWARF debug information, because why bother. So I'm quite sure that -w works just fine. We could add -s too.
