### ISSUE TITLE
runtime: cannot ReadMemStats during GC

### ISSUE THREAD

**Issue by aclements** [golang/go#19812]
GC holds the worldsema across the entire garbage collection, which means nothing else can stop the world, even during concurrent marking. Anything that does try to stop the world will block until GC is done. Probably the most interesting such operation is ReadMemStats.

We should fix GC to only hold worldsema during sweep termination and mark termination. The trickiest part of this is probably dealing with GOMAXPROCS changing during GC, which will affect mark worker scheduling.

/cc @RLH

**Comment by andreimatei** [comment]
This issue is kind of a pain for CockroachDB because we use `ReadMemStats()` to get periodic heap stats. Because the `ReadMemStats()` blocks for GC to finish (and we've seen it take many seconds), we've had to collect these heap stats separately from the loop that sample other stats in our server (which we care about collecting periodically, and in a timely manner), and so now our heap stats are out of sync with those other stats.

FWIW, we'd rather have more approximate heap stats that we can collect cheaply than more accurate heap stats that can only be collected at specific points.

**Comment by beorn7** [comment]
Note that there is a work around in client_golang now, see https://github.com/prometheus/client_golang/pull/568 (check the final state of the PR, not the whole discussion). It will be released any moment as v0.9.3.

**Comment by beorn7** [comment]
Meaning: If you use prometheus/client_golang, you are good now. If you are doing it on your own, it might serve as inspiration.

**Comment by aclements** [comment]
Thanks for the reports of this happening in real systems. I knew this was a theoretical problem, but this is the first data I've had on it happening in production.

Making the stats approximate doesn't really help in this case. We're just doing some heavy-handed synchronization that we need to figure out how to break up.

**Comment by go101** [comment]
Is it acceptable to cache and return the stats before GC starts?

**Comment by mknyszek** [comment]
I spoke with @aclements and there may be a simple way to do this. Most of the trickiness arises from dealing with GOMAXPROCS changing during the mark phase, but we can also ignore that case by just adding a new semaphore. Turns out we also have to retain the old behavior for trace start for other reasons.

I have a quick and dirty change which seems to work OK in `all.bash` locally. I'll upload it in a bit.

**Comment by aclements** [comment]
Reopening because of revert.

**Comment by mknyszek** [comment]
We're pretty sure we know how to fix this properly now. I'll have a more complete patch ready early in the Go 1.15 cycle.

**Comment by dmitshur** [comment]
This issue is currently labeled as early-in-cycle for Go 1.15. That [time is now](https://groups.google.com/d/msg/golang-dev/y0yM_Xi665Q/mk35pLnjCAAJ), so friendly ping. If it no longer needs to be done early in cycle, that label can be removed.

**Comment by mknyszek** [comment]
@dmitshur I'm my reviewers. This should go in ASAP given how much trouble it gave us last release.

It should be a lot better this time though; the fix to this bug last time was a bit sloppy, and everything here has been re-done in a more principled manner (with a new benchmark).

**Comment by mknyszek** [comment]
> @dmitshur I'm pinging my reviewers. This should go in ASAP given how much trouble it gave us last release.
> 
> It should be a lot better this time though; the fix to this bug last time was a bit sloppy, and everything here has been re-done in a more principled manner (with a new benchmark).
