### ISSUE TITLE
cmd/compile: wrong names during nested struct decomposition

### ISSUE THREAD

**Issue by randall77** [golang/go#19868]
```
import "runtime"

type T struct {
	x, y *int
}
type U struct {
	a, b T
}

func f(p *T) int {
	c := *p
	runtime.GC()
	return *c.x + *c.y
}
func g(p *U) int {
	c := *p
	runtime.GC()
	return *c.a.x + *c.b.y
}
```

The struct variable in `f` gets decomposed correctly.  The generated code spills the two parts of c to stack slots named "c.x" and "c.y".  We should get similar stack slots named "c.a.x" and "c.b.y" in `g`, but we don't.  We just get autotmps.

@heschik @dr2chase @mdempsky

**Comment by heschik** [comment]
For the record, the CL for this got abandoned a little while ago.

**Comment by dr2chase** [comment]
I am trying to revive this, I assume it would be helpful.

**Comment by heschik** [comment]
I think so. I found the problem by inspection, not by hitting it myself, so I don't know how critical it is. But it seems like anything working with small nested structs would be affected, so it seems worth fixing to me.

**Comment by dr2chase** [comment]
The tests are very broken because of refactoring, I'm wondering how hard it would be to turn this into an end-to-end test.  Seems like if it matters, there must be a way to make it be user-visible.

I've also as yet had poor luck with any of my little tests when I optimize them.  Everything is always reported as <optimized out>, which may be true, but so far I haven't written anything that isn't.
