### ISSUE TITLE
spec: admissible argument types for print/println

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19885]
The builtin functions `print` and `println` have very vague documentation under ["Bootstrapping"](https://golang.org/ref/spec#Bootstrapping). In particular, they don't mention what argument types are permitted.

go/types accepts any argument types, whereas cmd/compile and gccgo reject code that tries to print arrays or structs.

    $ cat print.go
    package main

    func main() {
            print(struct{x int}{42})
            print([3]int{1,2,3})
    }

    $ gotype print.go

    $ go tool compile print.go
    print.go:4:7: illegal types for operand: print
            struct { x int }
    print.go:5:7: illegal types for operand: print
            [3]int

    $ gccgo -c print.go
    print.go:4:2: error: unsupported argument type to builtin function
      print(struct{x int}{42})
      ^
    print.go:5:2: error: unsupported argument type to builtin function
      print([3]int{1,2,3})
      ^

/cc @griesemer @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Considering how vague the spec already is I suggest we just add "Not all implementations support all argument types, but printing ints and strings should always work."

**Comment by mdempsky** [comment]
I'm okay with specifying that accepted argument types is also implementation-specific.

**Comment by griesemer** [comment]
I suspect it's just predeclared types.

It's very useful to have print/ln work, not just for bootstrapping/debugging, but also when teaching programming (from scratch) using Go: imports can be left away for quite some time before they need to be explained.

I'd prefer to say that at least the predeclared types should be supported; especially since we already appear to do so ( https://play.golang.org/p/d_EypuaelE ).
