### ISSUE TITLE
cmd/go: vendoring does not work for main package directly  in $GOPATH/src

### ISSUE THREAD

**Issue by sparkthu** [golang/go#19899]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
I have a main.go just in $GOPATH/src/，any other works well for this project. But if I import something in this main.go and put the packages in vendor directory, go build will report an error.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
vendoring should work for the main package in $GOPATH/src

**Comment by davecheney** [comment]
I'm sorry, you cannot place any Go source code at the root of $GOPATH/src
because it implies the import path of that package would be blank.

**Comment by rsc** [comment]
You _can_ put Go source code in $GOPATH/src, but only because you can put Go source code in any directory, even outside $GOPATH. For the purposes of the Go command, code in $GOPATH/src is considered not part of the usual $GOPATH processing - only subdirectories of $GOPATH/src are subject to that. (As Dave says, a distinguishing characteristic is that in $GOPATH/src there is no clear import path, just like anywhere else outside $GOPATH.) 

That's why vendor doesn't work, and why vendor isn't going to work.

If you do drop a source file in $GOPATH/src and run 'go build', the resulting binary is named 'src', because the heuristic to use the name of the containing directory still applies. Unless you are actually building a program named 'src', you have to create a subdirectory to set the name properly. You also have to create a subdirectory to pick up vendored code. 

Sorry.
