### ISSUE TITLE
Standard library licensing question

### ISSUE THREAD

**Issue by JonasT** [golang/go#19893]
The license of go has this paragraph:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Now I'm assuming the standard library is possibly covered by this license too, and when I compile my program the parts of it that I use are baked into the binary.

Does that mean that every program I make would be required to have a notice like "Contains code written by The Go Authors, originally available under the BSD license https://github.com/golang/go/blob/master/LICENSE" or something like that? Does anyone actually do that? Is there some sort of exception somewhere that makes this unneeded for the standard library parts that are baked into programs?

**Comment by ianlancetaylor** [comment]
> Does that mean that every program I make would be required to have a notice like "Contains code written by The Go Authors, originally available under the BSD license https://github.com/golang/go/blob/master/LICENSE" or something like that?

Every program that you distribute to a third party in binary form, yes.  Technically it should have a copy of the LICENSE file, not just a reference to it.

For the record, this license is known as "The 3-Clause BSD License" and the generic form can be found at https://opensource.org/licenses/BSD-3-Clause.  It is described in Wikipedia at https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22BSD_License_2.0.22.2C_.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29.

> Does anyone actually do that? 

Yes.  For example, although Chrome is not written in Go, it is written using a bunch of different projects that use the same license or other licenses with similar conditions.  If you use Chrome, go to the URL chrome://credits.  You will see all the projects that Chrome uses, and you will be able to see a copy of their license.

> Is there some sort of exception somewhere that makes this unneeded for the standard library parts that are baked into programs?

No.

Clearly, we are not going to come after you if you forget to do this.  Equally clearly, I can not speak for "The Go Authors" as a whole, so you should not rely on this assurance.

I'm going to close this issue since there is no bug here.  If you want to discuss this further, please do not this issue.  Please use a forum such as golang-nuts instead.  See https://golang.org/wiki/Questions.
