### ISSUE TITLE
access to Gerrit denied because of location

### ISSUE THREAD

**Issue by zs1379** [golang/go#20065]
when use git mail to push the code to the go.googlesource.com, i have get an error

fatal: remote error: Access Denied (not available from your location)
(running: git push -q origin HEAD:refs/for/master)
git-codereview: exit status 128

but when i use a same account in other ip range, it have been success.

the denied ip address range is 58.23.0.0/16.

**Comment by mvdan** [comment]
I recall @bradfitz helping someone with similar issues recently, but can't find any public details.

**Comment by bradfitz** [comment]
Sorry, we do want your contributions, but our Gerrit server doesn't accept pushes from Chinese IP spaces. This is similar to how https://play.golang.org/ doesn't permit generating "Share" URLs from Chinese IP spaces.

We used to be totally blocked in China due to the Great Firewall of China, so this "read-only" state is  an improvement at least, even if it's not ideal. The Go team would love if we could have no location restrictions anywhere in the world, but one step at a time. Getting to this "read-only" state was enough work.

Good to hear some of your IP ranges work at least.
