### ISSUE TITLE
Issue on strings.TrimRight("about.html", ".html")

### ISSUE THREAD

**Issue by subchen** [golang/go#20085]
go 1.8.1
macos 10.12.4

I got `abou`, NOT `about` on following code

```
s := strings.TrimRight("about.html", ".html")
fmt.Print(s)
```

And I try other cases on `strings.TrimRight()`, they are all OK.

Why above case is failed? A bug?

**Comment by slimsag** [comment]
This isn't a bug.

> TrimRight returns a slice of the string s, with all trailing Unicode code points contained in cutset removed.

The cutset `.html` contains the letter `t` in the trailing part of the string, therefore the trailing `t` in `about` is removed. For example, see that `strings.TrimRight("abouta.html", ".html")` produces `abouta` -- that's because `a` is not in the trailing set.

For your case, you should be using `TrimPrefix` NOT `TrimRight`.

**Comment by subchen** [comment]
@slimsag, thanks for your explains. I should use `TrimSuffix`
