### ISSUE TITLE
go run: An equivalent to `go build -i' ?

### ISSUE THREAD

**Issue by VojtechVitek** [golang/go#20114]
Is there any equivalent to `go build -i` for `go run`, which would make recompiling much faster?

```
go build --help

The -i flag installs the packages that are dependencies of the target
```

```
go run -i main.go
flag provided but not defined: -i
```

**Comment by bradfitz** [comment]
There is not.

go run is intended for quick hacks and learning, not day-to-day development, so complicating it with more options is not a priority.

Also, if #4719 is fixed and we get proper build caching in cmd/go, then "go build -i" and "go test -i" both become useless, and that's really where we'd like to get to. @rsc was going to work on that sometime here.

I'm going to close this because proper build caching everywhere (already tracked) is the better solution.

**Comment by VojtechVitek** [comment]
Thanks for explanation, @bradfitz.
