### ISSUE TITLE
cmd/go: regression in "go get" with relative paths

### ISSUE THREAD

**Issue by kevinburke** [golang/go#20175]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Tip (`go version devel +c4335f81a2 Fri Apr 28 23:38:15 2017 +0000 darwin/amd64`)

### What operating system and processor architecture are you using (`go env`)?

Mac

### What did you do?

```
export GOPATH=/Users/kevin
mkdir -p "$GOPATH/src/github.com/kevinburke"
pushd "$GOPATH/src/github.com/kevinburke"
    rm -rf rest # just to make sure it's empty
    go get ./rest
popd
```

### What did you expect to see?

I expected github.com/kevinburke/rest to get cloned from Github and checked out to $GOPATH/src/github.com/kevinburke/rest. (You should be able to reproduce this problem with any relative path, there's nothing specific to this repository)

This is the behavior of Go 1.5 through Go 1.8 (didn't test earlier versions than this).

### What did you see instead?

```
$ go get ./rest
can't load package: package ./rest: cannot find package "./rest" in:
	/Users/kevin/src/github.com/kevinburke/rest
```

My apologies as I believe someone was working on this previously, but I searched the issue history for related terms and couldn't find anything about it.

**Comment by vcabbage** [comment]
Bisected this to #17863 (https://golang.org/cl/33158/).

**Comment by ianlancetaylor** [comment]
CC @shurcooL

**Comment by shurcooL** [comment]
Thanks for the report, I'll be able to investigate this fully tomorrow.

From a brief look at this issue, it looks like `cmd/go` is relying on the previous behavior of `go/build`, before #17863 was fixed, when `go get`ing relative import paths. It needs to be updated to take into account the post-#17863-fixed behavior of `go/build`.

**Comment by rsc** [comment]
Why not just roll back the incompatible change made for #17863?

**Comment by shurcooL** [comment]
> Why not just roll back the incompatible change made for #17863?

It's possible to do that, but it seems it would take more steps. That change was made 2 months ago. If rolled back now, it would break `x/tools/cmd/godoc` tests. Since it's clear where the problem is, it's possible to fix this issue directly. But I can act differently if advised so.

The problem is that `cmd/go` relies on previous behavior of `build.Import` that was not tested. Specifically:

```
// If the path is a local import path naming a package that can be imported
// using a standard import path, the returned package will set p.ImportPath
// to that path.
```

In combination with:

```
// If an error occurs, Import returns a non-nil error and a non-nil
// *Package containing partial information.
```

In the case of local import path pointing to a directory that doesn't exist, that behavior was broken by the change in [CL 33158](https://golang.org/cl/33158).

A fix I'm come up with is to bring back that previous behavior of `build.Import` and add tests for it. This can be done without re-introducing #17863 issue, so tests for that continue to pass.

I've sent [CL 42350](https://golang.org/cl/42350), can you comment on how it looks?

**Comment by shurcooL** [comment]
@rsc, did you see my comment above? This is related to #19769 and CL https://go-review.googlesource.com/c/33158/#message-93b2fc6b74efcb9936bc119782ee3485ca897450.
