### ISSUE TITLE
x/tools/godoc: Remove the function declaration link

### ISSUE THREAD

**Issue by 178inaba** [golang/go#20269]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.8.1 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/i178inaba/work/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8b/5j9t64vs0sg_n1jjfkkrg88m0000gn/T/go-build329351097=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

I referred to the following documents.

https://golang.org/pkg/net/http/#Client.Get
https://golang.org/pkg/net/http/#Header.Get

### What did you expect to see?

The Fragment link should be as follows.

```
#Client.Get
#Header.Get
```

```html
<pre>func (c *<a href="#Client">Client</a>) <a href="#Client.Get">Get</a>(url <a href="/pkg/builtin/#string">string</a>) (resp *<a href="#Response">Response</a>, err <a href="/pkg/builtin/#error">error</a>)</pre>
```

```html
<pre>func (h <a href="#Header">Header</a>) <a href="#Header.Get">Get</a>(key <a href="/pkg/builtin/#string">string</a>) <a href="/pkg/builtin/#string">string</a></pre>
```

### What did you see instead?

The function name link of the part displaying the signature of the method is invalid.

```html
<pre>func (c *<a href="#Client">Client</a>) <a href="#Get">Get</a>(url <a href="/pkg/builtin/#string">string</a>) (resp *<a href="#Response">Response</a>, err <a href="/pkg/builtin/#error">error</a>)</pre>
```

```html
<pre>func (h <a href="#Header">Header</a>) <a href="#Get">Get</a>(key <a href="/pkg/builtin/#string">string</a>) <a href="/pkg/builtin/#string">string</a></pre>
```

**Comment by shurcooL** [comment]
I've investigated this. This issue is actually 2 issues, and the correct fix is different from what's suggested above. One is a deploy/release issue (what's running at golang.org), and the other is a code issue in latest master of tools subrepo. Both need to be resolved.

The version of cmd/godoc that's running at http://golang.org/pkg/ is weird. I can't easily tell what version exactly it is, but I can tell it's not the version that's a part of go1.8.1 release (which didn't have this bug), and it's not the latest master of tools subrepo (which has this bug, but the fix is different from what the issue suggests). So, I'm going to ignore it below and discuss what I can reproduce locally with latest master version of cmd/godoc in tools subrepo.

This bug was actually introduced in https://github.com/golang/tools/commit/e1bdc76d0461f7041136c70e0a1356ea0f5e01d0 (similar to https://github.com/golang/go/issues/19894#issuecomment-292761048). /cc @jayconrod

With the parent commit (https://github.com/golang/tools/commit/00f7cd5589365aa8eb6e88f55d845eea9ca39f25), the generated HTML looked like this:

![image](https://cloud.githubusercontent.com/assets/1924134/25830188/2ac1a320-3429-11e7-8887-d56f739fcdb9.png)

With https://github.com/golang/tools/commit/e1bdc76d0461f7041136c70e0a1356ea0f5e01d0, it becomes:

![image](https://cloud.githubusercontent.com/assets/1924134/25830284/c1404bbc-3429-11e7-8fe2-499f142d7655.png)

Notice that the `Get` method name was not linked before, but it becomes linked after. And the link is wrong.

So, the correct fix is to remove the link, not to fix the URL. The link wasn't meant to be added, it was an unintentional regression caused by https://github.com/golang/tools/commit/e1bdc76d0461f7041136c70e0a1356ea0f5e01d0. Its commit message confirms it was meant to be a fix for composite literals anchors only.

(The link doesn't make sense in this context, because it points to the same location as the function/method. There's already a heading that does that too. That's why it should be removed.)

**Comment by 178inaba** [comment]
Thank you so much for review!
I'm going to fix it according to your review.
