### ISSUE TITLE
encoding/json/stream.go:250  : json.RawMessage.MarshalJSON() returning always nil error

### ISSUE THREAD

**Issue by qJkee** [golang/go#20363]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

### What did you do?
use json.RawMessage

### What did you expect to see?
error if message is nill

### What did you see instead?
```
func (m RawMessage) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	return m, nil
}
```

so, err checking is wrong here, we need to check if returned []byte contains "null" word, instead of checking error

**Comment by davecheney** [comment]
Can you please provide a runnable code sample that demonstrates the issue.

Thank you

**Comment by qJkee** [comment]
@davecheney 
https://play.golang.org/p/XYQ58TDdaC

**Comment by davecheney** [comment]
Thank you. There are several problems with your example.

Your fields should be public so encoding/json can write to them

Your json tags are not correct, please check the example wth Go vet.

**Comment by davecheney** [comment]
@qJkee I don't think this is a bug, json.RawMessage will return the value []byte("null") if nothing was decoded during json decoding. Otherwise it will return the raw bytes of the json for that key.

I think you probably want to use something other than json.RawMessage, but you haven't described your problem in this ticket.

We don't the issue tracker to ask questions, so you should try one of then other  forums, https://golang.org/wiki/Questions for good places to ask for assistance. Thanks.
