### ISSUE TITLE
sync: enhancement: have the new sync.Map use sharding 

### ISSUE THREAD

**Issue by orcaman** [golang/go#20360]
Hi guys,

Was glad to see the new [sync.Map code](https://github.com/golang/go/blob/master/src/sync/map.go) merged into master recently. Did you guys consider using sharding technique such as the one used [here](https://github.com/orcaman/concurrent-map) to reduce time spent between locks? 

Cheers,
Or

**Comment by dgryski** [comment]
Related https://github.com/golang/go/issues/18802

**Comment by ianlancetaylor** [comment]
CC @bcmills 

Note that we don't use the issue tracker for questions.  This may be better discussed on the golang-dev mailing list.  See https://golang.org/wiki/Questions .

**Comment by bcmills** [comment]
The short answer is, "Yes, we considered it."

The longer answer is that `sync.Map` addresses the specific problem of cache contention for maps used in the Go standard library.  Those maps tend to be append-only (no overwriting existing keys) and mostly-read (lots of reads relative to the number of writes), so that is the workload for which `sync.Map` is optimized. In particular, the algorithm in the 1.9 `sync.Map` produces _no_ steady-state cache contention<sup>†</sup> when reading existing keys, regardless of the number of concurrent readers per key. Sharding doesn't help much for that use-case, because concurrent readers of the same shard end up contending on the cache line containing the lock for that shard.

(Also note that sharded data structures can sometimes fail dramatically in the case of unlucky shard assignments: for example, see https://github.com/golang/go/issues/17953.)

All that said, the 1.9 implementation almost certainly has room for improvement.

The "new key" path in particular would likely benefit from some kind of sharding: at the moment all newly-added keys are guarded by a single `Mutex`, which is fine if you don't have new keys in the steady state but not good for maps with a lot of churn. Since I was prototyping in [`x/sync`](https://godoc.org/golang.org/x/sync/syncmap) (outside the standard library), computing a shard for an arbitrary key would have added a lot of complexity, but for `sync.Map` itself you could probably tie in to the runtime's built-in hash functions. If you have a specific workload in mind, I would encourage you to write some benchmarks and see what you can come up with for when the 1.10 window opens.

† Except to the extent that the runtime's memory allocator introduces false-sharing by allocating read-only values on the same cache lines as non-read-only values.

**Comment by bradfitz** [comment]
Okay, I guess there's nothing left to do here. Question was answered. Thanks, @bcmills.

**Comment by bradfitz** [comment]
(But @orcaman, feel free to file other bugs if you you have follow-up info per @bcmills's feedback)

**Comment by orcaman** [comment]
@bcmills thanks for the elaborate answer. 

@bradfitz thanks, if I get to benchmarking as suggested by @bcmills I will follow up here.
