### ISSUE TITLE
io: document that ReadAtLeast and ReadFull can drop errors

### ISSUE THREAD

**Issue by akalin** [golang/go#20477]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8.2

### What operating system and processor architecture are you using (`go env`)?

darwin amd64

### What did you do?

When passing an io.Reader to io.ReadAtLeast or io.ReadFull, if the conditions of the function are fulfilled (i.e., enough bytes are returned) but it also returns an error, I would expect that error to be propagated. Instead, it is dropped. Example:

https://play.golang.org/p/3XvnMqGYMr

The behavior of these functions can't be changed because of backwards compatibility. I would argue that the function comment should call this case out specifically, since it's quite surprising (and even led to a bug in encoding/base32), and it seems that callers do want the error-propagating behavior most of the time.

Split off from https://github.com/golang/go/issues/20044 .

**Comment by niubaoshu** [comment]
io ReadAtLeast doc
// It returns the number of bytes copied and an error if fewer bytes were read.

**Comment by akalin** [comment]
That part doesn't say anything about the error returned if enough bytes are read, but later in the comment:

> On return, n >= min if and only if err == nil.

I think this could be clarified to:

> On return, n >= min if and only if err == nil. In particular, if r.Read() returns an error but fills up buf, that error will get dropped.

**Comment by dsnet** [comment]
The persistence of an error in a `io.Reader` is not specified in the documentation and it is reasonable that there is a class of errors that are transient and do not cause an issue if `Read` were called again. Furthermore, there's nothing that you can do in `ReadAtLeast` since it is a stateless function and cannot affect the stickiness of an error on the `io.Reader` passed in.

This is only relevant to documentation; documentation fixes are okay for Go1.9, but leaving in Go1.10 milestone.

**Comment by akalin** [comment]
You're right about persistence of errors in `io.Reader`, but that's not what I'm referring to here. The loop in `ReadAtLeast` stops as soon as `r` returns an error, but as long as enough bytes are read, that error is dropped. That's the behavior that I'm making a case for being documented.
