### ISSUE TITLE
net/http: false positives checking for Ogg files

### ISSUE THREAD

**Issue by gtownsend** [golang/go#20513]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
MacOS Sierra 10.12.5 

### What did you do?
Wrote a test of http.DetectContentType() after reading the code.
(In net/http/sniff.go, the mask used to test for application/ogg is bogus.)

### If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/jr4yXFJZLZ

### What did you expect to see?
A file beginning with "owow\000" would be classified as application/octet-stream

### What did you see instead?
It is classified as application/ogg

**Comment by odeke-em** [comment]
Hello there @gtownsend, thanks for filing the issue. Nice catch.

My apologies, the bug is that unfortunately I mismatched and used:
* []byte("\x4F\x67\x67\x53\x00")
instead of
* []byte("\xFF\xFF\xFF\xFF\xFF")
as the mask
https://github.com/golang/go/blob/b9daf0a408acb4099eda268ed80203f83ecd3fa5/src/net/http/sniff.go#L109-L113

The algorithm and reference that we use is at:
<img width="717" alt="screen shot 2017-05-27 at 6 21 42 pm" src="https://cloud.githubusercontent.com/assets/4898263/26525089/61354dc8-4309-11e7-9b4e-fb784f670b26.png">


I'll make a CL and a test for it, although Brad is on vacation for a week, but if anyone can help me review and merge it that'd be nice.

Anyways, the catch here is that the bug for "application/ogg" gives a false positive if the byte pattern BITWISE AND'd with `4F 67 67 53 00` in hex matches itself `4F 67 67 53 00`  for example:
* oooS
* owow
