### ISSUE TITLE
Should panic when trying to read or write to nil channel in goroutine

### ISSUE THREAD

**Issue by thanhpk** [golang/go#20524]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
linux xubuntu 17.04/amd64

### What did you do?
I write to a uninitialized channel inside a goroutine. In stead of throwing a panic, the goroutine just exit quitely. It's hard to find bugs if Go doesn't print any message.
https://play.golang.org/p/U0zjeatykp

### What did you expect to see?
```
write to chan
read from chan
Recovered
END
```
### What did you see instead?
```
write to chan
read from chan
END
```

**Comment by cznic** [comment]
The goroutines did not exit quietly, they're both blocked and that's what the specification prescribes.

**Comment by thanhpk** [comment]
@cznic When I try to read or write to a nil channel in main function, nothing is blocked and a panic is thrown
https://play.golang.org/p/Mpdf2AgDMb

So why does it just block in gorountine? Its clear that programmer has forgotten to initialize the channel. I think it's better to throw the error right.

**Comment by dominikh** [comment]
That's not panicking because of the nil channel send/receive itself, but because of the obvious deadlock in your code. https://golang.org/ref/spec#Channel_types specifies the behaviour of using nil channels. Quoting:

> A nil channel is never ready for communication.

This is working as intended. If you have any more questions, I recommend you take them to one of the [various forums](https://golang.org/help/) instead. They may even explain why nil channels can be very useful.

**Comment by thanhpk** [comment]
@dmitris that make sense, but I still don't understand why does it panic in main function but not in goroutine? both have deadlock in it. 
https://play.golang.org/p/wndl-1xLUy
The above code should behave be the same regardless of it is in a goroutine or not.
