### ISSUE TITLE
runtime: cannot generate new project even with Go 1.8.3

### ISSUE THREAD

**Issue by seenickcode** [golang/go#20537]
# System:

MacBook Pro (x86_64)
macOS 10.12.4
go version go1.8.3 darwin/amd64
Xcode 8.3

# What did you do?

`buffalo new` (from the Getting Started page http://gobuffalo.io/docs/getting-started)

I have also tried following this article (https://github.com/golang/go/issues/19734) yet after upgrading to Go 1.8.3 this is still a problem.  Must I really downgrade Xcode to 8.2 instead of 8.3 to get this to work?

# Expected

A project is generated.

# What I see

```
buffalo new coke
[1]    32849 killed     buffalo new coke
```

**Comment by ALTree** [comment]
go1.8.3 should work.

Every single person that in the past weeks reported that the problem was still present with `>=go1.8.1` did not update correctly/actually nuked the old version and was still using programs compiled with go1.8.0 without realizing.

Please check really carefully that a) you removed go1.8.0 b) you have go1.8.3 on your system and you are using it c) that every binary you run was built with go1.8.3

**Comment by vcabbage** [comment]
Also check that you don't have `GOROOT` set to an older Go install. I recently helped someone where that was the culprit.

**Comment by seenickcode** [comment]
Fixed.  While `go version` was showing the correct one, I failed to delete all existing Go bins/pkgs and reinstall buffalo.  Thanks guys!
