### ISSUE TITLE
x/tools/cmd/bundle: discards some comments

### ISSUE THREAD

**Issue by rgeronimi** [golang/go#20548]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/raphaelgeronimi/Local/Sabrina"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/6zwrsm6j6kqgj6vr3hf0_zbw0000gn/T/go-build481562037=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
I looked at http/h2_bundle.go code

### What did you expect to see?
No empty if...then blocks

### What did you see instead?
In http2Server.ServeConn, there is a useless if...then block around lines 3173-3181:
		
```
		if sc.tlsState.ServerName == "" {
  
  		}
  
  		if !s.PermitProhibitedCipherSuites && http2isBadCipher(sc.tlsState.CipherSuite) {
  
  			sc.rejectConn(http2ErrCodeInadequateSecurity, fmt.Sprintf("Prohibited TLS 1.2 Cipher Suite: %x", sc.tlsState.CipherSuite))
  			return
  		}
```

This empty block looks strange, beyond being useless, I dont know if this could create a security issue. The empty line within the next if...then block right below looks strange too.

This also stresses the need to increase linters usage within the go project itself. There are linters which report that kind of error, it's surprising that they are used in most golang projects but still not used within the core project itself.

**Comment by ALTree** [comment]
That file is autogenerated. The original one has a comment explaining what's going on

https://github.com/golang/net/blob/a8e8f92cd65f5ff48599999fa4001d9b95ecea85/http2/server.go#L400

```
if sc.tlsState.ServerName == "" {
		// Client must use SNI, but we don't enforce that anymore,
		// since it was causing problems when connecting to bare IP
		// addresses during development.
		//
		// TODO: optionally enforce? Or enforce at the time we receive
		// a new request, and verify the the ServerName matches the :authority?
		// But that precludes proxy situations, perhaps.
		//
		// So for now, do nothing here again.
}
```

I guess the bundle script removes comments.

**Comment by rgeronimi** [comment]
I understand.

Why does the bundle script strip some comments and not others?

Loosing part of the comments is another layer of indirection for external project users & contributors, it serves no useful purpose.

Raphael

**Comment by mvdan** [comment]
The bundle godoc (https://godoc.org/golang.org/x/tools/cmd/bundle) says that comments may not be preserved. I assume this is to save lines of code, since you can quickly end up with very large files. It does seem to keep comments that serve as godoc for package members, though.

I believe the `h2_bundle.go` file is not supposed to be human-readable or editable. After all, it sits at nearly 10k lines of code. You should look at the source files in `golang.org/x/net/http2` instead.

**Comment by ALTree** [comment]
Closing this, since 1) apparently there's no issue with the code 2) as mvdan says, autogenerated filed are not really supposed to be readable and the header points to the original source

**Comment by bradfitz** [comment]
I'm going to reopen this and repurpose it towards fixing the bundle too.

I think `h2_bundle.go` should be readable or totally gibberish, not halfway in the middle. But I'd prefer readable since we're 95% of the way there.

@alandonovan, do you know why we're losing some comments but only a few?

**Comment by rgeronimi** [comment]
I  fully agree, the documentation policy in that file should be one or the other.

Also I discover this bundle thing for the first time but do not understand why we can’t directly import in http the needed library : isn’t it http2? Importing it may be a cleaner way than copy/pasting code through a script, and would remove 1 level of indirection when analyzing code. But I am surely missing another constraint for which bundle still is the solution.

Raphael

**Comment by bradfitz** [comment]
Go doesn't permit circular dependencies so we can't have net/http import http2, since http2 already depends on net/http (for types, etc).

**Comment by rgeronimi** [comment]
Wow I missed that one. That’s a  large quantity of non-trivial code. In my case I was trying to cleanup a faulty http2 configuration, being linked directly against your http2 package would have made my exploration less painful : human-size files separated by concept, clear delineation between http-generic and http2-specific concepts, ...

With aliases you could resolve that by moving the common part to a deeper net/httpbase package, and, to continue providing the Go1 API guarantees, alias them in net/http.

I am generally biased against aliases (indirection), but if I had to choose, I would prefer aliases over bundling.

Raphael

**Comment by alandonovan** [comment]
I'm not sure yet why bundle is losing some comments, but the way in which comments are associated with syntax nodes has always been a weak aspect of the design of the `go/ast` package.

Deleting all comments is not an option because several kinds of special comment have semantics in the compiler.

**Comment by bradfitz** [comment]
Maybe @griesemer could help.

**Comment by griesemer** [comment]
`x/tools/cmd/bundle`'s `main.go` contains a comment:
```
// TODO(adonovan): this may cause loss of comments
// preceding or associated with the package or import
// declarations or not associated with any declaration.
// Check.
```
i.e., this is a known problem.

As @adonovan pointed out, comment handling is a weak spot in the `go/ast` package (which is one of the very first Go packages ever and which is suffering a bit from age). The problem is that comments are not attached to ast nodes, unless they are documenting a declaration. Instead, they are "free-floating" in a list associated with the `ast.File` node, and must be "interspersed" at the right place based on their positions (and the respective node positions).

I haven't looked at `main.go` in detail but the call to `format.Node` (`main.go:362`) simply takes a declaration node which won't contain any inner comments.

There is (somewhat tedious) way to address this: The [begin, end[ source interval for each declaration node can be used to determine all the comments that belong to the declaration. That list of comments, together with the declaration node, may be be bundled up in a `go/printer.CommentedNode`, which in turn is provided to the `format.Node` call. If the node and comment positions are correct (unchanged), the comments should be correctly interspersed.

Leaving for somebody else to pick this up.

**Comment by fatih** [comment]
@bradfitz I'll take a look at it.

**Comment by fatih** [comment]
oops, seems like @hirochachacha was faster than me :)

**Comment by hirochachacha** [comment]
It seems printer package already addressed @griesemer 's suggestion.
https://github.com/golang/go/blob/master/src/go/printer/printer.go#L1055-L1081
So the fix could be simple.
