### ISSUE TITLE
dev.typealias: update to go1.8.3

### ISSUE THREAD

**Issue by dsnet** [golang/go#20550]
The [`dev.typealias`](https://github.com/golang/go/commits/dev.typealias) branch is supposed to be a mirror of `go1.8.x` with the addition of type aliases bolted on (so that type aliases can be tested with Go1.8). With `go1.8.3` released, we need to [cherry-pick the latest changes](https://github.com/golang/go/issues?q=milestone%3AGo1.8.3) into `dev.typealias`.

What's the process for doing this? Can I just cherry pick the individual changes myself into that branch and set out CLs to Gerrit?

\cc @hyangah @neild @rsc @bradfitz @broady

**Comment by rsc** [comment]
I have been updating it using git merge (the commits are merge commits and the messages say merge), not git cherry-pick, so that the history of what is there and what isn't is preserved. After running 'git merge go1.8.3' you just have to resolve the VERSION file conflict, commit, and then git mail as usual. I'll do that now for 1.8.3.

**Comment by dsnet** [comment]
Completed with 8a5ef1501dee0715093e87cdc1c9b6becb81c882 in https://golang.org/cl/45754
