### ISSUE TITLE
html/template: recognize text/babel as synonym for text/javascript

### ISSUE THREAD

**Issue by jmesyan** [golang/go#20561]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Go\Studio
set GORACE=
set GOROOT=E:\Go\Golang
set GOTOOLDIR=E:\Go\Golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
month ago ,I use go 1.7.4, today I upgrade go to 1.8.3,find the object can't right display in the template,so I compare the source 1.7.4 and 1.8.3, find the difference in text/template next, I don't understand why change this,the template can not parse json object right,and not give a option to user!

1.8.3:
<pre>
// If data is a reflect.Value, the template applies to the concrete
// value that the reflect.Value holds, as in fmt.Print.

func (t *Template) execute(wr io.Writer, data interface{}) (err error) {
	defer errRecover(&err)
	value, ok := data.(reflect.Value)
	if !ok {
		value = reflect.ValueOf(data)

	}
	....
	return
}
</pre>
1.7.4
<pre>
func (t *Template) execute(wr io.Writer, data interface{}) (err error) {
	defer errRecover(&err)
	value := reflect.ValueOf(data)
        ...
	return
}
</pre>

### What did you expect to see?
how to solve the problem ?

**Comment by odeke-em** [comment]
@jmesyan thanks for the issue. Would you mind giving more detail on the exact problem for example a reproducible snippet of your bug? That way we can try to diagnose the problem and see what the bug is.

**Comment by jmesyan** [comment]
## make a example:
I hava a mysql database ,a table named **grade** to record the grade info, it has two fields-**gid,gname.**
I set the read struct next:
<pre>
type Grade struct {
    Gid  int64
    Gname string
}
</pre>

I  select the data from the database by a mysql  Third-Party Libraries and show in the template
<pre>
models:
func GetGradeList() []Grade {
     sql := "select * from grade"
     condition := make([]interface{}, 0)
     result, err := DB.Select(sql, condition)
     utils.CheckError(err)
     var res []Grade 
    json.Unmarshal([]byte(result), &res)
    return res
}

controller:
...
list := models.GetGradeList()
fmt.Fprint(w, list) //I print the origin list in the browser
data := map[string]interface{}{
		"list": list,
}
...
t, err := t.ParseFiles(displayView)
if err != nil {
     fmt.Fprintf(w, "parse template error: %s", err.Error())
    return
}
err = t.Execute(w, data)
if err != nil {
	fmt.Fprint(w, err.Error())
}
...

views:
<script type="text/javascript">
...
var list = {{.list}}
console.log(list) //I print the template parse data in the browser
...
</script>
</pre>

finally, I find in the go version 1.8.3 and 1.7.4 the origin print is the same,just like this:
**[{1 grade1} {2 grade2} ...]** 
but the template parse data is different:

1.8.3 -**[{1 grade1} {2 grade2} ...]**
1.7.4-**[{"Gid":1, "Gname":"grade1"}, {"Gid":2, "Gname":"grade2"},...]**

The result of 1.7.4 is what i want, hope solve the problem quickly！

**Comment by vcabbage** [comment]
Please confirm whether you're using `text/template` or `html/template` as the results are formatted differently.

Here's an example comparing each: https://play.golang.org/p/j8wlM0lN8x

The results of that example are the same for Go 1.6, 1.7, and 1.8.

**Comment by jmesyan** [comment]
I am sure the problem, if use 1.8.3 the javascript can't  traverse the list right  @traverse

**Comment by vcabbage** [comment]
I understand, but the behavior has not change between releases. It appears that `html/template` has the behavior you want. Please try using `html/template` instead of `text/template`.

**Comment by jmesyan** [comment]
i use the html/template,and the html/template use the text/template , i find the problem in the text template, when i replace the 1.8.3 source code  html and text module  with 1.7.4  ,the javascript parse right!@Traverse

**Comment by vcabbage** [comment]
@jmesyan I posted an example above showing the different results with using `html/template` and `text/template`. The output is below. From my understanding of the issue you want the output shown under "html/template". Is that correct?

```
text/template:

<script type="text/javascript">
var list = [{1 Name1} {2 Name2}]
console.log(list)
</script>

html/template:

<script type="text/javascript">
var list = [{"Gid":1,"Gname":"Name1"},{"Gid":2,"Gname":"Name2"}]
console.log(list)
</script>
```

**Comment by jmesyan** [comment]
no , it is all out  buy html/template, but the 1.8.3 is not a object, the javascript cannot parse it right@vcabbage

**Comment by vcabbage** [comment]
Javascript, in my browser, parses this correctly:
```
<script type="text/javascript">
var list = [{"Gid":1,"Gname":"Name1"},{"Gid":2,"Gname":"Name2"}]
console.log(list)
</script>
```

That was produced with Go 1.8.3, using this example:

```go
package main

import (
	"fmt"
	html "html/template"
	"os"
	text "text/template"
)

var textTmpl = text.Must(text.New("").Parse(`<script type="text/javascript">
var list = {{.list}}
console.log(list)
</script>`))

var htmlTmpl = html.Must(html.New("").Parse(`<script type="text/javascript">
var list = {{.list}}
console.log(list)
</script>`))

type Grade struct {
	Gid   int64
	Gname string
}

func main() {
	list := []Grade{
		{1, "Name1"},
		{2, "Name2"},
	}

	data := map[string]interface{}{
		"list": list,
	}

	fmt.Printf("text/template:\n\n")
	textTmpl.Execute(os.Stdout, data)

	fmt.Printf("\n\nhtml/template:\n\n")
	htmlTmpl.Execute(os.Stdout, data)
}
```

You can run it yourself here: https://play.golang.org/p/j8wlM0lN8x

**Comment by jmesyan** [comment]
my result:<h1>Unavailable For Legal Reasons</h1><p>If you believe this is in error, please <a href="https://golang.org/issue">file an issue</a>.</p>

**Comment by vcabbage** [comment]
Ah, sorry, can you run the example I posted above on your computer?

**Comment by jmesyan** [comment]
you out put is http.ResponseWriter?

**Comment by jmesyan** [comment]
I have test your example, it is right in the html/template, but the out device is http.ResponseWriter is different, you can try

**Comment by vcabbage** [comment]
No, I was just putting it into an html file. Here's an example that server via http. Note that setting content-type to "text/html" is required for the browser to render it as HTML.

```go
package main

import (
	"fmt"
	html "html/template"
	"log"
	"net/http"
	text "text/template"
)

var textTmpl = text.Must(text.New("").Parse(`<script type="text/javascript">
var list = {{.list}}
console.log(list)
</script>`))

var htmlTmpl = html.Must(html.New("").Parse(`<script type="text/javascript">
var list = {{.list}}
console.log(list)
</script>`))

type Grade struct {
	Gid   int64
	Gname string
}

func main() {
	list := []Grade{
		{1, "Name1"},
		{2, "Name2"},
	}

	data := map[string]interface{}{
		"list": list,
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("content-type", "text/html")

		fmt.Fprintf(w, "text/template:\n\n")
		textTmpl.Execute(w, data)

		fmt.Fprintf(w, "\n\nhtml/template:\n\n")
		htmlTmpl.Execute(w, data)
	})

	log.Fatal(http.ListenAndServe("localhost:8080", nil))
}
```

**Comment by jmesyan** [comment]
I found the problem ,i use the react babel to parse the data ,you put in the  <script type="text/babel">,it is not right @vcabbage

**Comment by vcabbage** [comment]
We have established that Javascript can parse this then, correct? Do you still believe there is an error with Go? I am uncertain on how to proceed without a concrete example of what Go is doing incorrectly.

**Comment by jmesyan** [comment]
but in the 1.7.4 ,the <script type="text/babel"> can parse data right

**Comment by jmesyan** [comment]
this must have some problem

**Comment by vcabbage** [comment]
I see the issue now. 1.8 checks the script type in order to fix a different bug. However, "text/babel" is not one of the expected tags. Here's the CL where it was implemented https://go-review.googlesource.com/c/14336/ (ffd1c781)

I'm not sure how best to handle this cc'ing the author of that CL for thoughts.

/cc @nodirt

**Comment by nodirt** [comment]
The problem can be solved on the user side by moving the variables initialized in a template to a separate `<script type="text/javascript">` tag:

```html
<script type="text/javascript">
var list = {{.list}};
console.log(list)
</script>

<script type="text/babel">
// Application logic that uses list
</script>
```

In my opinion `html/template` in 1.8 works correctly for this scenario. There is a list of MIME types for scripts derived from [HTML5](http://www.w3.org/TR/html5/scripting-1.html#attr-script-type) spec, [RFC7231](https://tools.ietf.org/html/rfc7231#section-3.1.1) and [RFC4329](http://tools.ietf.org/html/rfc4329#section-3). I don't think stdlib should make an exception for the non-standard `text/babel`.

**Comment by jmesyan** [comment]
the react have been heavily used,i think go should  compatible the scirpt tag, use two kind scirpt tag feel so cumbersome@nodirt

**Comment by nodirt** [comment]
please explain how `html/template` package is incompatible with `<script>` tag. I looked at the `<script>` spec again. It [says](https://www.w3.org/TR/html5/scripting-1.html#script-processing-prepare):
> If the user agent does not support the scripting language given by the script block's type for this script element, then the user agent must abort these steps at this point. The script is not executed.

This implies that unless the script type (`text/babel`) is supported (it is not), the script contents shouldn't be interpreted by the user agent (`html/template`), in particular it should be treated as `text/javascript`. 

Please explain what's the problem in having two tags. Note that I am suggesting to move only variable definitions to the `<script type="text/javascript">` tag. The rest of the code can stay inside `<script type="text/babel">` tag.

**Comment by rsc** [comment]
In Go 1.8 we started looking at the script type, so that we'd only apply escaping to text/javascript (and variants along those lines), because some people had text/template (NOT Go's text/template) and that was getting incorrectly processed. Without the html/template package knowing that text/babel means, it's unclear what it should do. It only knows about javascript. 

It's true that this changed in Go 1.8, but we think it changed for the better.

It's unclear whether there should be an "opt-in" mechanism in html/template to mean "treat this script exactly like we treat javascript". But note that it would have to be compatible in an unspecified way for that to work.

**Comment by jmesyan** [comment]
in my opinion ,if go want widely used, better compatible  with text/babel

**Comment by vcabbage** [comment]
A few for/against reasons to escape `text/babel` as though it is javascript, from my point of view.

Background: `text/babel` is used by the very popular Babel compiler to translate ES2015+ to ES5 in the browser. Alternatively, ES2015+ code can be compiled to ES5 before rendering in the browser.

Against:
* It's not a standard script type as it is not included in any standard I'm aware of.
* It's intended for prototyping rather than production usage due to the compilation overhead.
* Adding every custom script type could be a maintenance burden.
* There is a workaround https://github.com/golang/go/issues/20561#issuecomment-306100907.

For:
* It's presumably not included in standards because the contents should only be interpreted by the Babel JS library, not browsers.
* Not escaping the contents is a change in behavior from previous versions of Go.
* The only other similar types I could find are `text/jsx` (deprecated in favor of babel) and `text/typescript` (not widely used). Additional custom types to be added would likely be rare.

In my opinion, the change is minimal enough to be reasonable and restores backward compatibility.

**Comment by bradfitz** [comment]
What's the relation between this bug and #18569? Superficially they sound similar.

**Comment by vcabbage** [comment]
@bradfitz From my reading this and #18569 are similar, but not necessarily the same. Both are due to script tags with a type other than one of the recognized javascript types.

This issue relates to not applying JavaScript escaping. (Should be recognized as JavaScript, but it's not.)

#18569 is about the application of HTML escaping. (Doesn't necessarily need to be recognized as JavaScript, but the HTML escaping corrupts the custom tags/symbols.)

**Comment by rsc** [comment]
Is Babel a strict subset of Javascript? If not, then I don't see how we guarantee to process it correctly by blindly pretending it is Javascript.

**Comment by vcabbage** [comment]
@rsc ECMAScript is the Javascript language spec. Babel compiles ECMAScript 2015+ to ECMAScript 5 so that developers can write their code using the latest language features without worrying about users with older browsers or browsers that don't implement the latest standard yet.

**Comment by rsc** [comment]
OK, I did not understand that Babel is not some made-up language of its own but just the name of the tool, and that for some reason the script tag is using the name of the tool instead of the name of the language it contains. But now I understand. If the intent is that script with type=text/babel is always (maybe slightly newer) Javascript, then I can see processing it as Javascript in html/template. I think it's probably too late for Go 1.9, but we can try this for Go 1.10.

Is there some way to use Babel with script type=text/javascript instead?

**Comment by vcabbage** [comment]
I believe text/babel is used so that the browser doesn't attempt to execute the contents of the script tag before Babel has a chance to compile it.

The more typical way of using Babel in production would be to compile to ES5 as a build step, rather than doing it client side with text/babel. Using text/babel is more for prototyping.
