### ISSUE TITLE
release: version "go1.4" does not match go tool version "go1.9beta1"

### ISSUE THREAD

**Issue by broady** [golang/go#20674]
```
##### Building packages and commands for linux/amd64.
runtime/internal/sys
# runtime/internal/sys
compile: version "go1.4" does not match go tool version "go1.9beta1"
```

/cc @bradfitz

**Comment by broady** [comment]
Also for linux/ppc64le:

```
compile: version "devel +47c7451 Thu Apr 7 20:41:55 2016 +0000" does not match go tool version "go1.9beta1"
```

**Comment by bradfitz** [comment]
I sent https://golang.org/cl/45778 before I noticed there was a bug number.

**Comment by GwynethLlewelyn** [comment]
Interestingly enough, I have gotten this very same problem when installing go1.9 from source (not beta) on a machine which previously had go1.8.3. Is there a fix?

**Comment by davecheney** [comment]
@GwynethLlewelyn this issue was marked closed a few months ago. Please open a new issue following the template provided. Thank you.

**Comment by GwynethLlewelyn** [comment]
There is no need for opening a new issue — deleting all previous instances of Go and installing a fresh copy of 1.9 (and using the provided binaries) did the trick. The point of making a question four months after the issue was closed was simply because there are next to zero results on searching for this creepy error except for this thread on GitHub (the few other things found by Google do not apply); for future reference, it makes more sense to provide a solution/fix without needing to actually patch the Go lang code. There are other occasions when this issue appears: more specifically, when having multiple instances/installations of Go side-by-side, some libraries/packages might have been compiled with one version and not the other, and this error is common (even desirable!) in such occasions. There might be other, less intrusive ways of avoiding this error to appear besides deleting _everything_ and starting from scratch, but at least, for future reference for poor Go developers in despair, there is at least one possibility they can explore without needing to wait for a future, patched release of Go to be launched...

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
