### ISSUE TITLE
encoding/xml: can't round-trip a slice like in JSON

### ISSUE THREAD

**Issue by audathuynh** [golang/go#20735]
### What version of Go are you using (`go version`)?
go1.8.3

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?

Tried to unmarshal a slice from a string which is obtained by marshalling a slice.

https://play.golang.org/p/Yn57p2--fy

### What did you expect to see?

1. The slice needs to be restored in the variable b2.
2. The method "Unmashal" in the package encoding/xml should work the same as the method "Unmashal" in the package encoding/json.

### What did you see instead?

nil

**Comment by mvdan** [comment]
A smaller repro, with just a couple of ints: https://play.golang.org/p/B8P6xVJkGk

Funnily enough, if you unmarshal into `[]int` instead of `[]interface{}`, JSON still gets `[1 2]` and `XML` gets `[1]` instead of `nil`.

**Comment by SamWhited** [comment]
While it may be unfortunate that Marshal and Unmarshal are not inverse functions, this is working as expected per the rules from the package docs.

> The method "Unmashal" in the package encoding/xml should work the same as the method "Unmashal" in the package encoding/json.

I don't think this statement actually is very meaningful; XML and JSON are two very different serialization formats that are useful for different situations and are not interchangeable. XML does not have a "slice" or "array" type, per say, JSON does, so they cannot do the same thing here.

**Comment by audathuynh** [comment]
Sorry, I don't know what package docs you are talking about.
They could be very very important to you.

However, some questions are in my mind right now.

Who wrote the package docs? Can we change them if they is wrong?

Regarding to the package encoding/xml, if it is not a bug of the library, I think we will need to re-think why we need to build the library.

Why do we need to marshal something and then we cannot unmarshal it?

Thank you very much.

**Comment by SamWhited** [comment]
> Sorry, I don't know what package docs you are talking about.

The docs on the `Marshal` method: https://godoc.org/encoding/xml#Marshal

Specifically:

>  The name for the XML elements is taken from, in order of preference:
>
> - the tag on the XMLName field, if the data is a struct
> - the value of the XMLName field of type Name
> - the tag of the struct field used to obtain the data
> - the name of the struct field used to obtain the data
> - the name of the marshaled type

> Can we change them if they are wrong?
> …
> Why do we need to marshal something and then we cannot unmarshal it?

I agree with you that it's not ideal, I just don't think it can be changed at this point due to the [Go 1 compatibility promise](https://golang.org/doc/go1compat). Maybe someone on the Go team who's opinion actually matters here will correct me though :)

**Comment by mvdan** [comment]
> I can't reproduce this; in the example you posted it still appears to be [<nil>].

https://play.golang.org/p/N5O1MPAMtr

**Comment by audathuynh** [comment]
>XML and JSON are two very different serialization formats that are useful for different situations. They are not interchangeable: XML does not have a "slice" or "array" type, per say, JSON does, 

Yes. I completely understand that.

> so they cannot do the same thing here.

Do you really think that XML does not have a "slice" or "array" type and therefore we cannot implement the method or fix the bug?

> I don't think this statement actually is very meaningful; 

I think we need to separate the logic of the problem and the implementation of the problem.
I talk about the logic of the problem while you just focus on the implementation.

**Comment by rsc** [comment]
JSON encodes data structures. As such, it is fairly straightforward to turn JSON back into data structures when unmarshaling into something with no type information, like interface{}. XML does not encode data structures - it encodes a document stream, which sometimes is written in a way that can be viewed as a data structure. But if you unmarshal XML into an interface{}, with no type information, there's no real way to figure out the types that should be used. I'm sorry about this, but it is what it is.

Note that even JSON is not perfect here: the int turns into a float64, and the time.Time turns into a string. This is for the same reason as XML: there's missing type information in the encoded stream that cannot be reconstructed. It's just that XML carries even less type information than JSON.

Note also the comment in the [BUGS section at the bottom of the xml docs](https://golang.org/pkg/encoding/xml/#pkg-note-BUG):

> Mapping between XML elements and data structures is inherently flawed: an XML element is an order-dependent collection of anonymous values, while a data structure is an order-independent collection of named values. See package json for a textual representation more suitable to data structures.

This is working as best it can, both for XML and JSON (and it can work better in JSON than in XML). The typical way to address this is to unmarshal into an actual data structure instead of []interface{}, and then the missing type information is provided by the data structure type itself.

**Comment by audathuynh** [comment]
Indeed, I don't feel satisfied with the explanation of  @rsc .

I will be more happy if someone just says that it is a bug but we cannot fix, or frankly say that the current design of the library is bad and we cannot fix because of the promise of go1compat.
All of us want Go better and better, don't we?

> XML does not encode data structures - it encodes a document stream, which sometimes is written in a way that can be viewed as a data structure.

XML is just a language to describe what we want. 
Why don't we use the semantics of tags in an xml document to describe the data structure that we want?

Could you please explain the reason why we have the result [1] in the variable b2 in the example given by @mvdan 

https://play.golang.org/p/N5O1MPAMtr

You may say we cannot unmarshal the xml string correctly because we do not have the data type.

Why don't we marshal the slice into the below xml string and then we have the datatype of the data structure? 
We build the library and we can control what we marshal so that we can unmarshal, don't we?

<int-slice>
  <int>1</int>
  <int>2</int>
</int-slice>

Thank you very much.

**Comment by rsc** [comment]
These packages are about processing arbitrary JSON and arbitrary XML, not just a specific hypothetical XML dialect that includes type information in its element tag names. Handling arbitrary XML makes the package useful for documents and XMPP streams and any number of other XML-based protocols. If you have the luxury of controlling the encoding to the point of inventing hypothetical containers like &lt;int-slice>, then you also have the luxury of avoiding XML, and I would strongly encourage you to do that. The encoding/json and encoding/gob packages are both far better for data structures than encoding/xml, because both JSON and Gob are designed for data structures, while XML is not.

If you'd like to read more about XML's general inapplicability to data structures, I highly recommend Siméon and Wadler, “[The Essence of XML](http://homepages.inf.ed.ac.uk/wadler/papers/xml-essence/xml-essence.pdf),” POPL 2003.

As for the int slice, I do see the asymmetry between Marshal and Unmarshal: given a slice, Marshal will emit a sequence of XML elements, but Unmarshal always processes only a single XML element.
I filed #20754 for that. Thanks.

**Comment by audathuynh** [comment]
Thank you very much for the link.
Indeed, I am using encoding/gob to marshal and unmarshal my data in my app :-)

>As for the int slice, I do see the asymmetry between Marshal and Unmarshal: given a slice, Marshal will emit a sequence of XML elements, but Unmarshal always processes only a single XML element.

That is because you accept the tag "int" in XML document and don't accept the tag "int-slice" or "slice" when you describe a slice value.

Please tell me if I am wrong. Below is what I think.

XML is a markup language. In an XML document, tag are actually labels you use to describe what you want. The semantics of tags are defined of human to describe what we want.

Currently, we use the label "int" to describe the datatype integer in the example.
Actually, we can use any label, e.g "int", "integer", "abc" or whatever if you want.
The important thing is the semantics of the labels.

As I guess, you use and accept the label "int" in the xml string because it is the label people use to name the datatype of an integer value in Go language.
If that is correct, my next question is "why do you accept the label "int" for the datatype "int" but you don't accept the label "slice" for the concept of the datatype "slice" in Go?".

To me, all documents including package docs and even the paper about XML are written by human. We read, we learn, we judge and we use. If they are not correct in someway, we will fix it.
That is also the reason we build Go, isn't it?

Anyway, I am very happy with your answer.

Thank you very much.
