### ISSUE TITLE
reflect: FieldByNameFunc can pass field names which don't get found by FieldByName

### ISSUE THREAD

**Issue by aseemk** [golang/go#20745]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`1.8.1`

### What operating system and processor architecture are you using (`go env`)?

`linux/amd64`

### What did you do?

https://play.golang.org/p/6sL_KNiyTZ

1. Create two struct types which share some field name.
1. Create a wrapper struct type which embeds those two struct types.
1. Call `reflect.TypeOf(...).FieldByNameFunc(...)` on it, which passes field names to your match function.
1. Inside your match function, call `FieldByName(...)` to retrieve the actual field.

### What did you expect to see?

If `FieldByNameFunc` passes a field name, `FieldByName` (the only way to retrieve the field from a name, AFAICT) should always return the field.

### What did you see instead?

For duplicate field names, `FieldByNameFunc` still passes those field names, but `FieldByName` fails to find those fields.

So either `FieldByNameFunc` shouldn't pass names for duplicate fields, or `FieldByName` should return (the first matching instance of) duplicate fields. I understand if only the former is viable.

Thanks!

**Comment by ianlancetaylor** [comment]
I don't see a bug here.  Both `FieldByNameFunc` and `FieldByName` are behaving as documented.  `FieldByNameFunc` specifically does not ignore fields at the same level with the same name; it delegates to the function passed as an argument to decide whether the fields should be considered to have the same name.  `FieldByName` does ignore fields at the same level with the same name, as specified by the language.

Closing since I don't think there is anything to do here.  Please comment if you disagree.
