### ISSUE TITLE
fmt: pp should implement WriteString()

### ISSUE THREAD

**Issue by pierrre** [golang/go#20786]
### What version of Go are you using (`go version`)?
1.9beta1

### What did you do?

In my code, I'm implementing `fmt.Formatter`.
In order to write a `string` to the `fmt.State`, I'm calling `io.WriteString()`.
I know that this function has an optimization that allows to call `WriteString()` if `w` implements it.
Sadly, in my case the "real" type of `fmt.State` is `fmt.pp`.
`fmt.pp` only has `Write()`.

### What did you expect to see?

I think we should add:
```go
func (p *pp) WriteString(s string) (ret int, err error) {
	p.buf.WriteString(s)
	return len(s), nil
}
```
in my case, it greatly improve performance and reduces memory allocation.
We could also implement `WriteByte()` and `WriteRune()`, since `fmt.buffer` has these methods.

**Comment by bradfitz** [comment]
Sounds reasonable.

**Comment by nikhita** [comment]
I want to contribute to Go and noticed the `Help Wanted` label. If no one is working on it, I'd like to take it! :)

**Comment by martisch** [comment]
io.WriteString() uses a runtime check so it looks like it should work without changing the State Interface definition. For go2 we could then think about wether it makes sense to update the State Interface.

@nikhita go ahead if you want too. Please add r@golang.org and moehrmann@google.com as reviewers. We can review before go1.10 but we can only submit when the code tree opens for go1.10 start of August.

**Comment by nikhita** [comment]
@martisch will do that, thank you.

**Comment by SCKelemen** [comment]
@SCKelemen

**Comment by martisch** [comment]
@nikhita 
did you have time to start your first CL for go?
Any blockers encountered that we can help with?

**Comment by nikhita** [comment]
@martisch 
sorry, was busy at work - didn't have time to work on it.
But will try working on it on my flight to GopherCon now. :)
Maybe I can even ask any questions I have during the Go contributor workshop at GopherCon? :)

**Comment by martisch** [comment]
no problem. Asking at the contributor workshop sounds good.

**Comment by rajathagasthya** [comment]
Just checking if this is still active. I see in the CL that it needs tests. I can help with that, if need be.

**Comment by stemar94** [comment]
I mailed another way on how to resolve this by. gopherbot will notice soon.

**Comment by robpike** [comment]
Adding WriteString makes some sense, but please let's not open up an internal type to the full pressure of external I/O interfaces.

**Comment by martisch** [comment]
Following up here instead of on the CL discussion.

I would also favor to leave the internal buffer methods unexposed and only implement WriteString on pp as the proposal suggested. As far as i know there has been not yet been data or a request to add more io methods beyond WriteString. Keeping the api footprint low imposes less constraints on internals for future changes and avoids needing to implement them explicitly on pp later if buffer is replaced by something with different interfaces for internal optimization.

If it is decided to expose all the io methods from the buffer it would be good to make sure that there are no regressions due to the compiler not optimizing all the overhead away for the internal use of those methods (e.g. due to inline budget changes).
