### ISSUE TITLE
net: ListenMulticastUDP doesn't work on Solaris

### ISSUE THREAD

**Issue by iamacarpet** [golang/go#20898]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
linux/amd64 and darwin/amd64 building for solaris/amd64

### What did you do?
Trying to set up a multicast UDP listen using `net.ListenMulticastUDP`

On Linux, this runs great, but on Solaris it returns

```listen udp 239.255.255.250:1900: option not supported by protocol```

This is an example of the method that doesn't work: https://gist.github.com/iamacarpet/d0ea5c28f1753c7b624b79b9f5d6504d#file-listen_default-go

And this is an example that does work (using golang.org/x/net/ipv4): https://gist.github.com/iamacarpet/d0ea5c28f1753c7b624b79b9f5d6504d#file-listen_ipv4-go

I wasn't sure if this related to #7399, but then I'd expect it to not work at all, rather than having one method that works and one that is broken.

**Comment by mikioh** [comment]
Basically #7399 is unrelated even though the functionality is required for testing. The reason why ListenMulticatsUDP doesn't work with the standard library (and the external networking library does work well for IP multicasting) is because the solaris port maintainers didn't enable the feature whet they made the solaris port available.

Simply tweaking build constraint lines in the net and internal/poll packages of the standard library could enable the function on Solaris.
