### ISSUE TITLE
doc: document that FreeBSD 9 support will be removed in Go 1.10

### ISSUE THREAD

**Issue by rsc** [golang/go#20930]
Maybe I missed a decision, but I thought we needed to document in Go 1.9 release notes that Go 1.10 will remove support for FreeBSD 9. I don't see that there.

**Comment by bradfitz** [comment]
Go 1.8 works FreeBSD 9.3.
Go 1.8 does NOT work FreeBSD 9.1 (unless CGO_ENABLED=0).

We didn't discover this until recently (#20850 and 25de52eb57e085fae854f6162c42482f6703d5ff), because we ran FreeBSD 9.3 builders, not FreeBSD 9.1.

But sure, we can say that Go 1.10 will remove FreeBSD 9.3 support entirely, but I don't know why we would. I don't recall hearing any benefits of doing so.

**Comment by emaste** [comment]
For reference, FreeBSD releases now unsupported by the FreeBSD security team can be found at https://www.freebsd.org/security/unsupported.html. All 9.x releases are on the list.

Even so, I am sure there are users still on 9.3 that would appreciate being able to run newer Go still.
