### ISSUE TITLE
guru: no object for identifier

### ISSUE THREAD

**Issue by CMGS** [golang/go#20981]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```go version go1.8.3 darwin/amd64```

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/CMGS/.go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jy/197q2fws1hl8blgfvnj50n500000gn/T/go-build540419658=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

I'm using guru to find object's definitions in my project under it's dir. I'm running it's as it should be:
```guru definition 'cluster/calcium/create_container.go:#734'```
which specifies bytes position of start of a my object. I run it inside vim-go, but it's don't work even if I ran it by hand from command line.

my project was not under `$GOPATH`  but I link the dir to `$GOPATH/src/github.com/CMGS/project`. it can build normally and successfully.

in vim, godef can work as I expect, YCM can find definition and auto complete accurately, only guru not working well.

### What did you expect to see?

I expect to find out a position where this element was defined.

### What did you see instead?

guru: no object for identifier

**Comment by mvdan** [comment]
You seem to imply you're using a symlink. Is that correct?

For what it's worth, `GOPATH` is not required to work with symbolic links. See https://github.com/golang/go/issues/15507. `guru` isn't required to support them.

**Comment by CMGS** [comment]
@mvdan yes, I use symlink for build project without vendor. so how can I use guru to find object's definitions or something else in this case? copy whole dir to `$GOPATH` ?

**Comment by mvdan** [comment]
Depends on what you were using symlinks for in the first place. You could use a hard link. You could keep the code only inside `GOPATH`. You could do the symlink the other way.

Also see https://github.com/golang/go/issues/17271.

CC @alandonovan in case he wants to work on a fix, but I presume this will be closed as wontfix.

**Comment by CMGS** [comment]
hmmm, thank you  @mvdan , I will try hard link. hope #17271 become true, it can solve many develop problems in old projects like me.

**Comment by sandipb** [comment]
Directory hardlinks are no longer supported on OSX (High Sierra) with the default APFS filesystem. 

I get that guru is not _required_ to support symlinks because symlinks in GOPATH are not officially supported. But Guru has a different target audience than Go - it is widely used for helping editors and IDEs, which are typically used only on major operating systems. This is unlike Go itself, which has a better excuse for not supporting symlinks - it is not usable on all the operating systems it targets.

Given that, it would really be helpful if Guru would support symlinks. If there any technical reason to find it problematic to implement, it would be helpful to understand the reluctance.
