### ISSUE TITLE
x/review/git-codereview: support WIP mode

### ISSUE THREAD

**Issue by andybons** [golang/go#20991]
Work-in-progress mode is nice for when you want to upload a change but make it clear that it’s not ready for review.

https://gerrit-review.googlesource.com/Documentation/user-upload.html#wip

**Comment by josharian** [comment]
Nice. How does this show up in the gerrit UI? Does it make the CL invisible to others, or just mark it somehow? Note that this is approximated today by putting the words "DO NOT REVIEW" in the commit message.

**Comment by andybons** [comment]
Looks like this: 
<img width="812" alt="screen shot 2017-07-12 at 3 40 03 pm" src="https://user-images.githubusercontent.com/365204/28141111-6f27ed86-6718-11e7-85ec-56acc3516f38.png">

**Comment by rsc** [comment]
If this is meant to be approximately the same as 'DO NOT REVIEW', then let's make git-codereview automatically set the WIP bit for 'DO NOT REVIEW' CLs, or maybe we can even write some logic in the Gerrit config to do that. People already understand 'DO NOT REVIEW' and 'DO NOT SUBMIT'. I'd like to be able to keep using them, and in particular I'd like to be able to keep storing the setting in the CL description itself - in contrast to a git mail command-line flag like we have for --trybot - because I can write that down during commit time, working offline, instead of having to remember to do it later when I eventually git mail. (It would be especially bad if I had to remember every time I run git mail.)

Note also that you can have a CL stack where only some of the CLs are 'DO NOT REVIEW'. The implementation in git-codereview will have to be careful to get the bits right on the individual CLs in the stack. This another reason to keep the bits in the CL descriptions and not be a different mail mode. (It's unclear to me that push %wip handles this at all, but for a multiple-CL push, maybe git-codereview can go back after the push and set the WIP bits individually through the REST API.)

**Comment by andybons** [comment]
Until https://bugs.chromium.org/p/chromium/issues/detail?id=750933 gets fixed I’d like to hold off on this.

**Comment by kardianos** [comment]
New gerrit id: https://bugs.chromium.org/p/gerrit/issues/detail?id=6878
