### ISSUE TITLE
all: can't build go1.4

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#21054]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
n/a

### What operating system and processor architecture are you using (`go env`)?
Arch Linux 64bit
```
➤ gcc --version
gcc (GCC) 7.1.1 20170630
➤ clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
```

### What did you do?
```
➤ git clone https://github.com/golang/go
➤ git checkout release-branch.go1.4
➤ cd src && ./make.bash 
➤ env CC=clang ./make.bash 
```

### What did you expect to see?
Working go1.4

### What did you see instead?
Can't compile it with neither clang nor gcc.

With clang:
```
/usr/bin/ld: -r and -pie may not be used together
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

And with gcc:

```
os/user
# net
cannot load DWARF output from $WORK/net/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
# os/user
cannot load DWARF output from $WORK/os/user/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
```

https://gist.github.com/OneOfOne/a9116d4c85c32141282fcf9a2973fbd2

Discovered while trying to diagnose #21042

**Comment by fazalmajid** [comment]
FWIW, upgrading to GCC 7.2.0 doesn't fix the problem (Ubuntu 16.10 with GCC compiled from source).

    thufir ~/build>gcc --version
    gcc (GCC) 7.2.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    thufir ~/build>uname -a
    Linux thufir 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fazalmajid** [comment]
Workaround: cgo is not needed to bootstrap Go, so you can just build go 1.4 bootstrap with `env CGO_ENABLED=0`and it will build. You can then use it to bootstrap Go 1.9.

**Comment by ianlancetaylor** [comment]
Which Go 1.4 sources are you using?

Setting `CGO_ENABLED=0` is mentioned in the docs at https://golang.org/doc/install/source .

**Comment by fazalmajid** [comment]
go1.4-bootstrap-20170531.tar.gz, the latest one I could find. I suspect it would also work with 1.4.3.

The docs mention CGO_ENABLED=0 as an option in building from source, but I do want a cgo-enabled Go 1.9, it's just setting CGO_ENABLED=0 when building the bootstrap Go 1.4 gets it to compile on systems where it won't otherwise build from source due to the DWARF error message @OneOfOne mentioned above (in my case Ubuntu 16.04 with GCC 7.2).

I then get a bootstrap go 1.4 with cgo disabled that is able to compile a go 1.9 with cgo enabled, and I am no longer blocked by this issue.

I suppose on Ubuntu I could bootstrap from a binary release of Go 1.4, but I have the same automated build from source process on all the platforms I manage, including some that don't have official Go binaries like SmartOS and OpenBSD (it's very similar conceptually to BSD ports).

It may be worth mentioning the bootstrap Go should be built with CGO_ENABLED=0 in the section "Install Go compiler binaries' and the paragraph that begins with "To build a bootstrap tool chain from source...".
