### ISSUE TITLE
cmd/go: transient "unexpected directory layout" error

### ISSUE THREAD

**Issue by tsuna** [golang/go#21057]
### What version of Go are you using (`go version`)?

`go version go1.9beta2 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tsuna/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9beta2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9beta2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8j/3m62t7m92958kqxt9s3chtrr0000gn/T/go-build954574771=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

While trying to update a package:
```
$ go get -u github.com/uber/go-torch
unexpected directory layout:
        import path: github.com/mattn/go-colorable
        root: /Users/tsuna/go/src
        dir: /Users/tsuna/go/src/github.com/fatih/color/vendor/github.com/mattn/go-colorable
        expand root: /Users/tsuna/go/src
        expand dir: /Users/tsuna/go/src/github.com/fatih/color/vendor/github.com/mattn/go-colorable
        separator: /
$ go get -u github.com/uber/go-torch
<success>
```

### What did you expect to see?

`go get` should've either failed consistently or succeeded from the first time.

### What did you see instead?

A transient and somewhat confusing "unexpected directory layout" error.

**Comment by odeke-em** [comment]
@tsuna is this a regression from Go1.8?
/cc @rsc

**Comment by tsuna** [comment]
I don't know, I've never seen this error before.  The only similar issue I've found on GitHub was alecthomas/gometalinter#242 and that was reported with go1.8 already, but I don't know if it's the same problem.

**Comment by odeke-em** [comment]
Aye aye, gotcha. Thanks for the update. I'll mark this as needing investigation and for Go1.10.

**Comment by pbdeuchler** [comment]
I'm seeing this on go1.8.3

```
 → dockerc run --rm api go version
Starting xxx_postgres_1 ... done
go version go1.8.3 linux/amd64
```

**Comment by rsc** [comment]
I can't see how @tsuna's report can happen unless there are symlinks involved. (Symlinks are basically unsupported.) Somehow the package in his $GOPATH/src/github.com/fatih/color/vendor/github.com/mattn/go-colorable has been loaded as if its fully-qualified import path were only "github.com/mattn/go-colorable" when in fact it should be "github.com/fatih/color/vendor/github.com/mattn/go-colorable". The most likely culprit for this kind of confusion is symlinks. I cannot reproduce the problem right now, although it should of course not be transient in any way.

I tried reproducing this with both Go 1.8 and Go 1.9, with no luck:

```
$ mkdir /tmp/gp1
$ GOPATH=/tmp/gp1 go1.9 get github.com/uber/go-torch
$ GOPATH=/tmp/gp1 go1.9 get -u github.com/uber/go-torch
$
```

If anyone can send a set of commands to reproduce this with a specific version of Go, starting with an empty GOPATH directory and not using Docker, that would be great.

@pbdeuchler since you didn't post any command output it's impossible to know whether you're really seeing the same problem @tsuna is or a different bug entirely.

**Comment by F21** [comment]
I believe I am seeing the same issue with symlinks using Go 1.10-beta1 (was fine in Go 1.9.2).

In my case, my project is copied into `/source` in the docker `golang:1.10-rc-alpine` image.

I then symlink the directory to `/go/src/github.com/user/someproject`.

This is the output when I try to run `go test -v $(go list ./... | grep -v /vendor/)t`:
```
unexpected directory layout:
        import path: _/go/src/github.com/user/project/cockroachdb/cockroachdbpb
        root: /go/src
        dir: /go/src/github.com/user/project/cockroachdb/cockroachdbpb
        expand root: /go/src
        expand dir: /source/cockroachdb/cockroachdbpb
        separator: /
```

**Comment by davecheney** [comment]
Sorry, you cannot use symlinks with the go tool, they break its concept of a single path to find a particular package.
