### ISSUE TITLE
x/net/webdav: replace "golang.org/x/net/context" with "context"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#21364]
This is a long term tracking issue for the task of replacing "golang.org/x/net/context" import with "context". Doing so is desirable because otherwise, modern Go packages end up having no choice but to import both of those 2 packages, which is suboptimal (but currently a lesser evil than the alternatives).

This is somewhat similar to #21358, but a complication is that this changes the definition of the [`webdav.FileSystem`](https://godoc.org/golang.org/x/net/webdav#FileSystem) interface. That interface is quite popular (as far as I know) and has many implementations outside.

The conversation about this was started in the CL that added `context.Context` as first parameter to all `webdav.FileSystem` methods:

https://go-review.googlesource.com/c/32421#message-528154c59254446fadf063500da3911231523950

The [latest comment](https://go-review.googlesource.com/c/32421#message-1d44a86148ab488e65dcf2e9532a43b1031c35ff) was from @nigeltao saying that:

> Having 1.7 (and 1.8) importing both context packages is a little annoying, but I think that it's the lesser of two evils, compared to duplicating a lot of code.
>
> In Go 1.9, we might get type aliases back, and it will be even less annoying. If so, longer term, when we don't have to support anything prior to 1.9, I think we will be able to just replace all of the "golang.org/x/net/context"s with "context"s in this package, without breaking any third party code that uses "golang.org/x/net/context" with webdav.

An update on that. Go 1.9 final is close to release. Type aliases have been added indeed, and the implementation of `golang.org/x/net/context` package in Go 1.9+ is just:

```Go
// +build go1.9

package context

import "context" // standard library's context, as of Go 1.7

// A Context carries a deadline, a cancelation signal, and other values across
// API boundaries.
//
// Context's methods may be called by multiple goroutines simultaneously.
type Context = context.Context

// A CancelFunc tells an operation to abandon its work.
// A CancelFunc does not wait for the work to stop.
// After the first call, subsequent calls to a CancelFunc do nothing.
type CancelFunc = context.CancelFunc
```

_([Source](https://github.com/golang/net/blob/1c05540f6879653db88113bc4a2b70aec4bd491f/context/go19.go#L9-L20).)_

So, if my understanding is correct, we are now waiting on "when we don't have to support anything prior to 1.9", which is probably going to be around Go 1.11 or later becoming stable. Is my understanding right @nigeltao?

**Comment by nigeltao** [comment]
We won't drop Go 1.8 support until at least after Go 1.11 is released, but I don't think we need to wait until Go 1.11 to do something now.

For example, we could follow the "< 1.9" vs ">= 1.9" split in the golang.org/x/image/draw package, based on build tags:

```
$ cd golang.org/x/image/draw
$ grep build go1_*
go1_8.go:// +build !go1.9,!go1.8.typealias
go1_9.go:// +build go1.9 go1.8.typealias
```

A year or two from now, we can delete go1_8.go and rename or merge go1_9.go, both in x/image/draw and in x/net/webdav.

**Comment by shurcooL** [comment]
I suggested using build tags [on November 2016](https://go-review.googlesource.com/c/net/+/32421#message-1633f62f83d9e62fe30626b3d23fb6078ebede74):

> With build tags, you can use "x/net/context" with Go 1.6, but "context" Go 1.7. It would require duplicating a lot of code across the Go versions (file.go, prop.go, etc.). Do you think that it's not worth doing that?

You responded [at the time](https://go-review.googlesource.com/c/net/+/32421#message-1d44a86148ab488e65dcf2e9532a43b1031c35ff) with:

> Having 1.7 (and 1.8) importing both context packages is a little annoying, but I think that it's the lesser of two evils, compared to duplicating a lot of code.

You're suggesting build tags as a viable solution now. Or is it because type aliases enable us to do something we couldn't do previously?

If using build tags is an acceptable solution, I'm happy to work on a CL to resolve this issue (unless someone else wants to take it).

**Comment by nigeltao** [comment]
Ah, I forgot that the type in question (context.Context) is defined in a different package, so it's unlike the x/image/draw package where is Op type is defined in the same package can be easily defined/aliased before/after Go 1.9.

Yeah, build tags don't seem as viable for x/net/webdav, even with type aliases, due to all the code duplication it would require.

I agree that we're not going to do anything for now, and are waiting on "when we don't have to support anything prior to 1.9".

**Comment by bradfitz** [comment]
> I agree that we're not going to do anything for now, and are waiting on "when we don't have to support anything prior to 1.9".

We are officially in that state as of Nov 1st. I'm actively deleting any Go 1.8 and earlier code.
