### ISSUE TITLE
x/sys/unix: TestSysctlUint64 fails on freebsd/arm

### ISSUE THREAD

**Issue by bradfitz** [golang/go#21375]
TestSysctlUint64 fails on freebsd/arm:

https://build.golang.org/log/d2619c8b0011d695de308cf3e1fbe159d858d69c

```
--- FAIL: TestSysctlUint64 (0.00s)
	syscall_freebsd_test.go:26: no such file or directory
FAIL
FAIL	golang.org/x/sys/unix	0.075s
```

Test is just:

```go
func TestSysctlUint64(t *testing.T) {
        _, err := unix.SysctlUint64("security.mac.labeled")
        if err != nil {
                t.Fatal(err)
        }
}               
```

It was changed to `security.mac.labeled` in https://github.com/golang/sys/commit/7a6e5648d140666db5d920909e082ca00a87ba2c by @stevenh.

Maybe we need a different one for arm? Or does that FreeBSD kernel not have some kernel options compiled in?

/cc @paulzhol

**Comment by paulzhol** [comment]
Yes I don't have MAC support compiled in.
It appears only in 3 ARM boards, and it's commented out:
```
$ egrep -rn 'options[[:space:]]*MAC' /usr/src/sys/arm
/usr/src/sys/arm/conf/ATMEL:70:#options 	MAC			# TrustedBSD MAC Framework
/usr/src/sys/arm/conf/ETHERNUT5:66:#options 	MAC			# TrustedBSD MAC Framework
/usr/src/sys/arm/conf/SAM9260EK:78:#options 	MAC			# TrustedBSD MAC Framework
```
So maybe it's not a good idea to turn it on just for the test.

How about we use `vm.swap_total` instead? It's a `SYSCTL_QUAD` instead of `SYSCTL_UQUAD` used for `security.mac.labeled`, but it's still a 64-bit value on all platforms.
