### ISSUE TITLE
fmt: improve documentation about how verbs work when printing pointers

### ISSUE THREAD

**Issue by dtjackson** [golang/go#21409]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.9rc2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

https://play.golang.org/p/k89vjAT5Kt

package main

import (
	"fmt"
)

func main() {
	i := 37
	p := &i
	fmt.Printf("Why: %d", p)
}

### What did you expect to see?

I expected to see some sort of error / warning about the implicit conversion of a pointer type into an integer format verb %d. I expected the computer to help me catch the mistake of not derefrencing p to get the expected integer.

### What did you see instead?

No error or warning, and the output contains the address of the pointer printed in base10.

**Comment by cznic** [comment]
Looking at the the docs this seems like a bug in fmt.

**Comment by ianlancetaylor** [comment]
We can't change fmt, but we could change cmd/vet.

**Comment by ianlancetaylor** [comment]
CC @robpike

**Comment by cznic** [comment]
> We can't change fmt, but we could change cmd/vet.

Even when the behavior is not supported by the documentation?

**Comment by dtjackson** [comment]
If the behavior is deemed correct, can the documentation be adjusted to account for it?

**Comment by ianlancetaylor** [comment]
In some cases we can adjust the doc, but in a case like this I personally think that the chances of breaking a currently working program are too high.

**Comment by ianlancetaylor** [comment]
Sorry, I mean in some cases we can adjust the code (but I think this case is too risky).

We can always adjust the doc, and, yes, we should do so.

**Comment by robpike** [comment]
I can't find it now but I seem to remember this was an actual change that went in at some point, and that the docs need to catch up to the change. I might just be confused though.

**Comment by cznic** [comment]
According to the [documentation](https://golang.org/pkg/fmt/), section 'Format errors', passing a pointer to the %d verb is the case of invalid argument, %d is documented to accept only integers - and it should produce `%!d(pointer=0xdeafbeef)` per docs.

Can someone please explain to me why adjusting the docs instead of fixing the bug is considered? IMO 
it breaks the Go 1 compatibility promise, while fixing the bug does not, by definition.

Also, for the %d verb to accept pointers looks to me like a C-ism and the OP readily demostrates why it's good that Go avoids them.

**Comment by martisch** [comment]
AFAICT %d has been supported for pointers since go1.0:
https://github.com/golang/go/blob/release-branch.go1/src/pkg/fmt/print.go#L589

@robike maybe this is the change you were searching for:

fmt: honor integer radix formats (%d etc.) for pointers
https://codereview.appspot.com/6441152
https://github.com/golang/go/issues/3936

this changed the behavior of %d on pointers for go1.1 but did not introduce the %d support for pointers.

**Comment by cznic** [comment]
Thanks for the link. It makes clear that supporting %d and other verbs for pointers is intentional. IIUC now, it's [undocumented](https://github.com/golang/go/blob/release-branch.go1/src/pkg/fmt/doc.go) behavior since Go 1. Programs relying on undocumented behavior are not protected by the Go 1 compatibility promise.

**Comment by robpike** [comment]
@martisch Yes, that's the one I was thinking of. I agree it's a documentation issue at this point.
