### ISSUE TITLE
runtime: possible pointer-to-random-memory during hashmap evacuate

### ISSUE THREAD

**Issue by josharian** [golang/go#21459]
@randall77 [noted while reviewing CL 54653](https://go-review.googlesource.com/c/54653/3/src/runtime/hashmap.go#1152) that we might generate a pointer past the end of a map bucket.

This has been fixed for 1.10, in CL 54653. This issue is to discuss whether we want to also fix it for 1.9.

cc @randall77 @broady

**Comment by dsnet** [comment]
How long has this bug been in existence?

**Comment by randall77** [comment]
Probably since the GC cared about invalid pointers (1.6?).

It's a very hard bug to trigger. You'd have to be evacuating to the last bucket in an array of map buckets, or an overflow bucket, be evacuating just the right number of elements, and get interrupted at just the right time.

But if it did trigger it would be one of those annoying and hard to track down "sweep increased allocation count" bugs.

The fix is super simple.

**Comment by randall77** [comment]
We pushed the overflow pointer to the end of the bucket a while ago to solve exactly this sort of problem, so this actually isn't a bug. Even if the pointer points past the end of the value array, it doesn't point past the end of the bucket.
So no fix needed.
