### ISSUE TITLE
golang program can't run on hp-ux os,why?

### ISSUE THREAD

**Issue by yin-bp** [golang/go#21470]
golang program can't run on hp-ux os,why?

**Comment by davecheney** [comment]
Go doesn't support the hp-ux operating system because nobody had
contributed a port (yet.)

If you're looking to use a pa-risc machine then there will be an additional
hurdle that nobody has written a compiler back end for pa-risc yet.

The policy for adding new operating system or architecture ports is
documented here, https://github.com/golang/go/wiki/PortingPolicy

**Comment by TocarIP** [comment]
You can also try gccgo.
