### ISSUE TITLE
unicode: support version 10

### ISSUE THREAD

**Issue by nightlyone** [golang/go#21471]
see http://blog.unicode.org/2017/06/announcing-unicode-standard-version-100.html for the announcement and further information about what changed.

### What version of Go are you using (`go version`)?

go version go1.9rc2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ioe/sources/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/user/1000/go-build705652549=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
println(unicode.Version) 

as in https://play.golang.org/p/k69zvpQ97S

### What did you expect to see?

10.0.0

### What did you see instead?

9.0.0

**Comment by dsnet** [comment]
\cc @mpvl

**Comment by Manishearth** [comment]
Is there anything that needs to be done here aside from updating the tables? It seems like the IDNA changes aren't relevant to Go, and Go doesn't do collation, so it should just be a matter of updating the tables.

I did this before realizing the bug was already assigned, but here's the commit in case anyone wants it: https://github.com/Manishearth/go/commit/dcb8a6fdc28a581d2613e6946388c567a935b60c

**Comment by nightlyone** [comment]
@Manishearth The repositories under https://godoc.org/golang.org/x/text might be affected, too. So I hope @mpvl will sort this out or can at least provide a todo list for interested contributors.

**Comment by mpvl** [comment]
net/http uses http2 uses idna. It is vendored so it matters.

The IDNA change was quite substantial so 1.10 it will be.
