### ISSUE TITLE
encoding/json: retrieving underlying reader offset in UnmarshalJSON()?

### ISSUE THREAD

**Issue by Julio-Guerra** [golang/go#21589]
I am using big json configuration files and trying to produce useful user error messages, at least including the current line in the file.

So my question is: is there any way to retrieve the underlying reader's offset from `UnmarshalJSON()` to be able to return parsing or validation errors including it?

go version go1.8.3 linux/amd64

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions .  Thanks.

You can check whether the returned error value is a `json.UnmarshalTypeError`, which has an `Offset` field.  See https://golang.org/pkg/encoding/json/#UnsupportedTypeError .

Closing because there is no bug here.
