### ISSUE TITLE
cmd/go: 'go vet --shadow' not detecting shadowed variable

### ISSUE THREAD

**Issue by leonklingele** [golang/go#21638]
### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64, linux/amd64

### Steps to reproduce

```sh
$ git clone https://github.com/leonklingele/pick -b fix-var-shadowing
$ cd pick
$ go vet --shadow ./... 2>&1 | grep "safe/note.go"
```

### Actual & expect result
`go vet` correctly reports three shadowed vars (in line 134, 142, 145, the ones marked with `// nolint: vetshadow`), but misses one in line 152: https://github.com/leonklingele/pick/blob/fix-var-shadowing/safe/note.go#L152

I tried to create a smaller reproducible, but wasn't able to achieve this.

**Comment by robpike** [comment]
The -shadow option on vet is documented to be poor; that's why it's not enabled by default. There are many outstanding bugs against it and maybe someday someone will redo it with a better algorithm to make it more robust.

Regardless, line 152 isn't really shadowing, since the variable it creates doesn't hide one earlier in any semantically detectable way. In other words, although it has the same name as the outer err, renaming it (or using '=' instead of ':=') would have no effect on the program.

**Comment by leonklingele** [comment]
How is line 152 any different than 134, 142 or 145 which are detected by `--shadow`? There is at least some inconsistency.

**Comment by ianlancetaylor** [comment]
The `-shadow` warning is documented to only be issued if the shadowed variable is used after the shadowing variable is declared.  That does not happen at line 152.

Closing because the tool is acting as documented.
