### ISSUE TITLE
Type-defined struct and anonymous struct equivalency when passing by pointer

### ISSUE THREAD

**Issue by matijakevic** [golang/go#21669]
### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
I passed an type-defined struct to a parameter that accepts anonymous struct of the same structure. [Script 1](https://play.golang.org/p/DxjkmiJhtw)
Now I need to alter the struct passed, so I put a pointer in front of anonymous struct. [Script 2](https://play.golang.org/p/bcfpfHt1Ej)

### What did you expect to see?
In the first example, it all works as expected. I thought the expected thing would happen in the second example because the structs have equivalent definition.

### What did you see instead?
Compiler accepts the first example and all works as expected. In the second example compiler refuses to pass pointer to a type-defined struct to anonymous pointer receiver struct.

**Comment by ianlancetaylor** [comment]
That's not how the language works.  For the exact rules see https://golang.org/ref/spec#Assignability.

Closing because there is nothing to fix.  If you want to discuss why the language works this way, please use a forum rather than following up on the issue tracker.  See https://golang.org/wiki/Questions.  Thanks.
