### ISSUE TITLE
net: /etc/hosts parsing truncates to 4KB (os.GetPagesize)

### ISSUE THREAD

**Issue by alexzorin** [golang/go#21674]
Due to the way [`net/file,open` is implemented](https://github.com/golang/go/blob/master/src/net/parse.go#L67-L72), pure-Go DNS resolution cannot handle /etc/hosts files that are larger than the OS page size, which is 4KB by default on Linux platforms.

Go silently truncates the data after 4KB and does not parse lines on the threshold, since EOL is never reached for them.

The cgo equivalents for this functionality handle these files properly, and so should Go.

We often see these large hosts files in the web hosting environment (e.g. cPanel), when servers are behind NAT and require large hosts files.

Env: Go1.9, linux/amd64

I have also attached a Dockerfile tarball that reproduces the issue fully - [go-4kb-hosts.tar.gz](https://github.com/golang/go/files/1258618/go-4kb-hosts.tar.gz)

**Comment by odeke-em** [comment]
Interesting! Thank you @alexzorin for reporting this issue. Just for easier lookup in the future, here is the permalink to the code you referred to https://github.com/golang/go/blob/93471a139085fb58b0416e109ba32a927ccf5719/src/net/parse.go#L67-L72.

**Comment by odeke-em** [comment]
@rsc I suppose that the seemingly arbitrary os.Getpagesize() limit was set because we wanted a performance hit from reads on page boundaries or that we thought that size was sufficient? I don't see a file limit for a hosts file in either of the below:
- https://tools.ietf.org/html/rfc952
- https://tools.ietf.org/html/rfc1123
- https://tools.ietf.org/html/rfc4007
Please advise on what you think and perhaps we can amend this for Go1.10.

**Comment by alexzorin** [comment]
Hello,

I've been tracking the CL and I'm not sure how to add my input, sorry if I'm doing it wrong.

I saw a comment by @rsc that worries me a little:

> Or at least I'm OK with not seeing lines > 4kB

I originally ran into this issue with customers exactly because of lines that exceeded 4kB (big NAT-ted cPanel servers). If the system resolver deals with it without a problem I would not expect Go to introduce such a surprising and arbitrary limitation here.
