### ISSUE TITLE
crypto/rsa: reject short signatures

### ISSUE THREAD

**Issue by rsc** [golang/go#21896]
During dev.boringcrypto work, I discovered that x/crypto/openpgp tests depend on crypto/rsa accepting trimmed RSA signatures, in which leading zeros have been removed, while BoringSSL does not. @agl says that the Go library is in error and that such signatures are not valid. We should fix this (in master, not just dev.boringcrypto) for Go 1.10 and mark it in the release notes. Will need to fix openpgp first.

**Comment by FiloSottile** [comment]
This is very likely to break people, and unlikely to be a security issue (unless someone is relying on verifiable signatures not being malleable, but that is often regrettable anyway) so let's do it in early 1.12 instead of late 1.11.

**Comment by marga-kinvolk** [comment]
Hey! This change broke Flatcar Container Linux build infrastructure.

The signatures for our files are generated with gpg ( `gpg --batch --local-user "${FLAGS_sign}" --output "${sigdir}/${sigfile}.sig" --detach-sign "${sigfile}"`). Later on in the build pipeline, we download the files using a go utility that verifies the signatures. When moving to go1.15, we've started to get random failures on some signatures that don't match the expected size (signatures 594 bytes long validate fine, but those 583 bytes long don't).

I'm surprised that there's no way to disable this check and that there's no error message specific for this check. I had to go down a rather long rabbit hole to find out that this change was what causing my code to suddenly say `openpgp: invalid signature: RSA verification failure`.

I understand that the rest of the Go libraries do the right thing, but I'd expect the library to be able to maintain compatibility with gpg. Maybe through some option or something.

**Comment by FiloSottile** [comment]
crypto/rsa should not accept invalid signatures just because PGP generates them. We had fixed this in golang.org/x/crypto/openpgp years ago, and all its tests pass. If you have an example fo a PGP signature that doesn't validate with the latest golang.org/x/crypto/openpgp, please open a new issue with a reproduction test case.

**Comment by marga-kinvolk** [comment]
Thanks for the reply! After further investigation I found that the issue we were seeing was indeed due to having an old version of golang.org/x/crypto/openpgp in go.mod, which didn't have the fixes you mentioned. I've taken care of this and now the signature verifies correctly, even for the file with 593 bytes. Sorry for the noise.
