### ISSUE TITLE
web: remove content other than documentation from primary Go source tree

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#21917]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
every

### What did you do?
```
$ du -h SRC/blog

19M     blog/content
19M     blog
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
no blog content

### What did you see instead?
no

Now the Go blog content takes about 19MB in source code repos.
As I'd tried to remove blog directory and repack the whole GOROOT, the pkg reduce about 16MB. 

-rw-r--r--  1 root staff  82M Sep 18 11:29 go1.9.linux-amd64..no_blog.tar.gz
-rw-r--r--  1 root root   98M Aug 25 06:44 go1.9.linux-amd64.tar.gz

**Comment by shurcooL** [comment]
If this is done, and one runs `godoc -http=localhost:6060`, what do you expect/want to show up at http://localhost:6060/blog/? Currently, it shows the blog.

**Comment by mengzhuo** [comment]
I think redirect to https://blog.golang.org for the lastest blog is much more appropriate .

**Comment by shurcooL** [comment]
I can't seem to find an issue for it now, but I'm pretty sure there have been thoughts/discussions about moving the golang.org website functionality out of the main repository into a sub-repository or so. This issue seems at least vaguely related to that.

**Comment by mengzhuo** [comment]
(sigh my poor English
I've did the search on Github no move to subrepos issues AFAIK

Most of the user just don't need those images and blog content for their build machine or server.
Those blog contents will grow to huge size if every post is looks alike. 
https://blog.golang.org/community-outreach-working-group

 If they want to check out blog, they will find a way.

**Comment by as** [comment]
Growth rate of the blog is +~2MB/Year. Deleting merits a 20MB reduction with drawbacks: content locality loss. I use the self-hosted blog when demonstrating how easy it is to run a web server in Go. Perhaps I represent a small percentile of Go users, but its hard to ignore convention and convenience.

**Comment by forskning** [comment]
Don't you mean "blog: remove blog content from Go binary downloads"?

https://github.com/golang/blog

FWIW, I don't understand the logic of :

Prefix your issue with "blog:" in the subject line, so it is easy to find.

rather than

Prefix your issue with "x/blog:" in the subject line, so it is easy to find.

the latter being consistent with README.md files of other subrepos (where golang.org/go/issues is the main issue tracker for the subrepo).

Anyways, I think the blog README.md might be more comprehensive with the following changes.

Download/Install

The easiest way to install is to run `go get -u golang.org/x/blog`. You can also manually git clone the repository to $GOPATH/src/golang.org/x/blog. To build a clone (on Unix-like) run `go build -o blog ./blog` or (on Windows) run `go.exe build -o blog.exe ./blog`.

Running the server locally

Unix-like

```
cd $GOPATH/src/golang.org/x/blog
./blog
```

Windows

```
cd %GOPATH%\src\golang.org\x\blog
blog.exe
```


and then visit http://localhost:8080/ in your browser.

Note that the blog executable caches all content and you must kill it (Ctrl-C on Unix-like and Windows) and restart it after editing any files to view changes.

**Comment by forskning** [comment]
I concur with @as on this one.

Work on the repo began in early 2012, as appears from commits, and it's been a part of the binary downloads since at least go1.2.2.

http://nurmi-labs.blogspot.com/2017/08/bootstrapping-go.html

**Comment by mengzhuo** [comment]
@forskning I know blog content is not in the Go source code repo. 
However it's in the binary distributions from https://golang.org/dl/

**Comment by forskning** [comment]
@mengzhuo if it was written into the .msi files 

that blog was an optional feature

net being required for the tools feature (this entry may need more clarification)

and tools with partial or full optional features

probably the similar could be done with the .pkg file

that would not affect the .tar.gz nor .zip binary downloads

I think that with Linux distributions the file trees are not standardised

**Comment by tmack0** [comment]
Just started managing go for our servers here and also perplexed why the "binary distribution" contains the blog and all its contents. I don't need or want someone else's (or any, really) website on my build server. Also, and slightly off subject for the specific topic of blog, why does the binary package contain a "src" dir with 50+mb of source. If this is for compilations (ie: I write a golang app, it needs this src for the includes, etc), should it not be in "lib"... which is another thing, the lib/ dir exists but only has "time" in it. I think the whole golang "binary" distribution packaging needs to be reevaluated/updated.

**Comment by forskning** [comment]
The blog subrepo's Readme file describes how to start the blog server, or see https://github.com/golang/go/issues/22622. 

Prior to https://github.com/golang/go/issues/22041 being closed a Wiki page was created.

https://github.com/golang/go/issues/22041#issuecomment-334622300

A few of the misc rubric's entries have yet to be filled in with textual descriptions.

A tree version format (based on that 'prototype' Wiki page) is linked to in the below.

https://github.com/golang/go/issues/22041#issuecomment-335050412

For me I think (the content of)  https://github.com/golang/go/issues/22041#issuecomment-332454472 would potentially have been helpful in describing the file tree; R.C. https://github.com/golang/go/issues/22041#issuecomment-333660377 was not sure of the applicability of that comparison.

**Comment by bradfitz** [comment]
One potential compromise is we could ship all the files in the source tarball, but strip non-critical files from the binary downloads.

/cc @andybons

**Comment by andybons** [comment]
Ideally we’d separate out (most of) the content from golang.org from the binary distribution and leave `godoc -http` as something akin to what godoc.org looks like (web-based documentation and that’s it).

As we redo our website in the coming months, it will become less and less tenable to have a mirror of golang.org packaged with our primary distribution like we do now.

If users want to be able to run golang.org offline, then they could grab the repo that the website will eventually live in and run it locally.

Repurposing this to cover all web site assets for now. @shurcooL if you find that other bug please dupe it into that one. Thanks 👍

**Comment by tmack0** [comment]
I think there is a disconnect somewhere. When I download a binary package of a programming language/compiler, I do not expect, nor want, someone's blog app,  especially one complete with content, the mirror for the language's web site, or any other non-related program. I also do not expect to get the source code, as that would be in a "source" package. I expect to get a package with pre-compiled programs that allow me to run golang based programs, and compile golang sources into go apps. Not much more than that. Source code belongs in a source package downloaded separate (which go already has, so I really don't know why its packaged again in the binary). Examples and tutorials belong in a tutorial/example package. If Blog is how documentation is done for golang, or if golang is trying to make a major shift from the normal for how things are packaged, that needs to be presented as such in the Readme, on the website, in the install instructions, etc. It is not at all intuitive. This ticket has changed titles and purposes so many times in the comment flow it appears my comments probably no longer even matter, I will open a new issue.

**Comment by forskning** [comment]
An incomplete response but for example the Slackware Linux distribution installation's dialog has the option to install the kernel source.

And some software (above I cited plan9port), and below a Java version is also mentioned, come with the source code.

https://stackoverflow.com/questions/3225663/i-dont-understand-the-purpose-of-the-src-folder-and-seperate-packages

**Comment by bradfitz** [comment]
@tmack0, 

> When I download a binary package of a programming language/compiler, I do not expect, nor want, someone's blog app, especially one complete with content, the mirror for the language's web site, or any other non-related program.

Some history: we've always shipped the "godoc" binary with Go, as is the main (and original) way to browse package documentation, both via the command line and via the browser. We've shipped that with Go since before there was even a $GOPATH, and it was a great developer tool for people to look up APIs. It was great when I was on airplanes without connectivity, to be able to browse localhost and read docs.

And it just so happened that golang.org was served by godoc.

There are plans to split the website into two halves: the package docs ("godoc") and the rest of the site (blob, etc). But that hasn't happened yet.

> Source code belongs in a source package downloaded separate (which go already has, so I really don't know why its packaged again in the binary).

The cmd/go binary ("go install") etc uses the source code of the standard library on disk when you compile a binary. (but we also ship pre-built cached object files, so in practice they're not used. But if you tweak them, they're used. At least in Go 1.10.) It's true that we probably don't need to ship the source code to the compiler or linker or other "package main" things that aren't importable.

I've marked this as needing a decision. The @golang/proposal-review group will discuss in an upcoming meeting.

**Comment by tmack0** [comment]
Thanks for the history. I agree offline docs are useful, though a simple Readme in the base dir of the "blog" folder explaining what it is (or changing the folder name to something like godoc) might be helpful. When I see files like "upcoming-google-io-go-events.article" I do not think "coding docs" though, which is what I assume is the website split you mention.  Thanks!

**Comment by jimmyfrasche** [comment]
@tmack0 there's a wiki page, at least: https://github.com/golang/go/wiki/FileTreeDocumentation

**Comment by forskning** [comment]
@jimmyfrasche

The announcement of the wiki page was linked to here https://github.com/golang/go/issues/21917#issuecomment-361423885, but I see (above) you provide the actual link to the page. Would there be some basis to add to that page info on extra files in compiles/source downloads for 64 bit?
