### ISSUE TITLE
archive/tar: TestSparseFile fails

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#21958]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

./all.bash

#### What did you expect to see?
success

#### What did you see instead?
```
--- FAIL: TestSparseFiles (1.80s)
    --- FAIL: TestSparseFiles/EmptyFile (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/028689629: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/BigData (0.01s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/492668695: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/BigHole (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/643686241: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/DataFront (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/361682491: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/HoleFront (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/025217573: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/DataMiddle (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/420669343: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/HoleMiddle (0.00s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/479895849: inappropriate ioctl for device
    --- FAIL: TestSparseFiles/Multiple (1.76s)
    	tar_test.go:887: unexpected DetectSparseHoles error: seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/275436867: inappropriate ioctl for device
2017/09/21 12:07:55 seek /var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/sparse.db734036422: inappropriate ioctl for device
FAIL	archive/tar	1.934s
```

#### Does this issue reproduce with the latest release (go1.9)?
No

#### System details

```
go version devel +589ea93678 Thu Sep 21 01:01:44 2017 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hiro/.go"
GORACE=""
GOROOT="/Users/hiro/go"
GOTOOLDIR="/Users/hiro/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/go-build263216468=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +589ea93678 Thu Sep 21 01:01:44 2017 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +589ea93678 Thu Sep 21 01:01:44 2017 +0000
uname -v: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
lldb --version: lldb-900.0.45
  Swift-4.0
gdb --version: GNU gdb (GDB) 8.0
```

It happens after 1eacf78858fd18b100d25f7a04c4c62d96a23020

**Comment by dsnet** [comment]
Can you do show me the contents of the `mount` command? I'm interested in knowing what the underlying filesystem of `/var/folders` is.

**Comment by hirochachacha** [comment]
```
$ mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
```
It looks like nothing special.

**Comment by dsnet** [comment]
The odd part is that I'm unable to reproduce this. I am on Darwin 16.4.0, but I'm hoping that doesn't make much of a difference. 

The problem is that my check in `sparse_unix.go:26`:
```go
// Check for seekData/seekHole support.
if _, err := f.Seek(0, seekHole); errno(err) == syscall.EINVAL {
    return nil, nil // Either old kernel or FS does not support this
}
```
is clearly not triggering for some reason on your system.

The man page on `lseek` makes no mention about `ENOTTY` being returned, but does say that `EINVAL` should be returned for an invalid whence, for which this should be the case.

A part of me is tempted to catch `ENOTTY` as well. This [mailing list (not OSX specific)](http://permalink.gmane.org/gmane.comp.standards.posix.austin.general/4073) seems to suggest that `ENOTTY` is a possible return value:

> What should happen if a related filesystem implementation does not support SEEK_HOLE/SEEK_DATA? Note that modern OS implement loadable drivers and thus a binary only filesystem drivers may return e.g. ENOTTY (illegal ioctl) in such a case.

However, the source code for BSD tar [just does a very liberal check](https://github.com/libarchive/libarchive/blob/75a46c77be5e0ab8fe9056b313c0bbfca6a70675/libarchive/archive_read_disk_entry_from_file.c#L962-L964) where it assumes there is _no_ support if any error is returned for `lseek(..., 0, SEEK_HOLE)`. Similarly, GNU tar also [does a blanket check](https://git.savannah.gnu.org/cgit/tar.git/tree/src/sparse.c?id=228d83ed248df3c244ff69bf5104da6fc143e1df#n303) where it assumes any error implies no support is provided.

@hirochachacha, can you test the following variation of the check on `sparse_unix.go:26` and tell if it fixes the issue?
```go
if _, err := f.Seek(0, seekHole); errno(err) == syscall.EINVAL || errno(err) == syscall.ENOTTY {
    return nil, nil
}
```

I'm leaning towards just treating any error as having no support, but I want to make sure I'm on the right track.

**Comment by hirochachacha** [comment]
> @hirochachacha, can you test the following variation of the check on sparse_unix.go:26 and tell me if it fixes the issue?

It works fine! I remembered that my SSD is not made by apple, I replaced it before.
Perhaps, that is related?

**Comment by dsnet** [comment]
Quite possibly, seems to match the statement:
> Note that modern OS implement loadable drivers and thus a binary only filesystem drivers may return e.g. ENOTTY (illegal ioctl) in such a case.

Either way. Rather than playing whack-a-mole with every possible errno representing "not supported", I'm going to take the GNU and BSD tar approach and just consider any error as meaning "non supported".

**Comment by hirochachacha** [comment]
Fair enough. Thank you for your fix.

**Comment by dsnet** [comment]
Thank you for the bug report!
