### ISSUE TITLE
net/http, x/net/http2: update RFC numbers used as normative references

### ISSUE THREAD

**Issue by mikioh** [golang/go#21974]
The documentation in x/net/http and x/net/http2 packages still contains the obsolete RFC 2616 as a normative reference. I think it's better to replace the reference to RFC 2616 with a series of RFCs 7230 through 7235 for avoiding unnecessary confusion.

When we see some inconsistency, for example, RFC 2616 vs. RFC 723x, in the current implementation, that should be addressed as another issue. So this should be a documentation issue.

**Comment by urld** [comment]
Here are the inconsistencies with RFC-7230 i have found in net/http so far:

The handling of "hop-by-hop" Headers is defined differently:

>    Exactly when "close" connection options have to be sent has been
   clarified.  Also, "hop-by-hop" header fields are required to appear
   in the Connection header field; just because they're defined as hop-
   by-hop in this specification doesn't exempt them.  (Section 6.1)

However the current behavior has to be kept to maintain compatibility.

Other than that RFC 7230 defines more forbidden trailer headers for chunked transfers (see section 4.1.2) than currently implemented.

Note that i only looked in the places where rfc 2616 was referenced explicitly , so its hard to tell if there are other non obvious inconsistencies.

**Comment by mikioh** [comment]
> Is there a convention for referring to RFCs?

There's no convention, but the document should look like a document, not a side note writing to the back of a paper napkin.  I'm fine with either ```RFC NNNN```, ```the section X of RFC NNN``` or URL.

**Comment by urld** [comment]
I uploaded a first patch with the documentation changes. It includes todos for inconsistencies.
However, i think these inconsistencies should be cleared up first, before the documentation change is submitted.

**Comment by mikioh** [comment]
Thanks for tackling this issue.

> these inconsistencies should be cleared up first

Please open a new issue for shooting such inconsistencies, for getting more eyeballs. I think that leaving TODOs and issues is fine for now because the transition from H1 to H2 is a bit complicated work and probably takes a bit long time.

**Comment by urld** [comment]
I have created an issue for the incorrect handling of Trailer headers : #23908 

The handling of relative Location URIs in Redirect responses seem to be okay, but could use some addittional tests to ensure that fragments ar not thrown away. However im not sure if `path.Clean` should be called for absolute urls too. I will open another issue for discussion (or at least for additional tests) on this too.
