### ISSUE TITLE
misc/cgo/testcarchive: tests are failing on ppc64le

### ISSUE THREAD

**Issue by mkumatag** [golang/go#22126]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
master

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le

### What did you do?
./all.bash script

### What did you expect to see?
Pass all the tests

### What did you see instead?
Seen failures, with misc/cgo/testcarchive
```
##### ../misc/cgo/testcarchive
--- FAIL: TestCompileWithoutShared (1.26s)
	carchive_test.go:600: [go build -buildmode=c-archive -gcflags=-shared=false -o libgo2.a libgo2]
	carchive_test.go:602: 
	carchive_test.go:609: [gcc -fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build472192193=/tmp/go-build -gno-record-gcc-switches -I pkg/linux_ppc64le_shared -o ./testnoshared main5.c libgo2.a]
	carchive_test.go:611: 
	carchive_test.go:618: [./testnoshared 3]
	carchive_test.go:620: ./testnoshared: error while loading shared libraries: R_PPC64_ADDR16_HA re1028a6ca8 for symbol `' out of range
	carchive_test.go:361: got exit status 127; expected signal broken pipe
FAIL
```

**Comment by laboger** [comment]
What distro are you using, because I don't see this error on any of the systems I'm using, even the Ubuntu 16.04, because I tried it there after my fix.

At first glance, those options look wrong for ppc64le anyway, a c-archive must be built with -shared.

**Comment by mkumatag** [comment]
I'm using ubuntu 16.04 as host and building in `ppc64le/golang:1.9` container.

**Comment by ianlancetaylor** [comment]
The failing test explicitly passes `-shared=false`.   I added it for #20290, which was about incorrect values in the symbol table when compiling with -buildmode=c-archive but without -shared.

It's not obvious to me why this test is failing.  Of course -shared is required if we want to put c-archive into a shared library, and so -shared is the right default, but in this case we are not putting the code into a shared library.  The error is coming from the system dynamic linker, and unfortunately does not report the symbol being referenced.

The failing test is running the commands shown in the log.  Can you run those commands yourself and replicate the problem?  If so, please try setting `LD_DEBUG=all` in the environment when running `./testnoshared`.  Perhaps that will tell us which shared library is failing to load and which symbol is out of range.

**Comment by mkumatag** [comment]
@ianlancetaylor ran the commands with `LD_DEBUG=all` and uploaded results @ https://gist.github.com/mkumatag/a2c5ba4f35c2d9a0c613b4ba626cc50e

**Comment by ianlancetaylor** [comment]
Thanks.  Unfortunately that did not tell me anything useful.

What is the output of `readelf -r --wide ./testnoshared`?

**Comment by mkumatag** [comment]
ran and uploaded @ https://gist.github.com/mkumatag/9862a0e69729b68bb5b7213c53f314c3

**Comment by laboger** [comment]
I did some experiments on this yesterday. I found a system with the same level of ld and libc as your container, built the latest and also built before the commit where the pie testcase was changed/fixed. Those tests all passed. So that means there is something else unique about your container. I am unable to reproduce your latest error anywhere else.

The only case where I can reproduce this is when passing -pie directly to the linker instead of using -buildmode=pie on Ubuntu 16.04. Since that was the same error message, I'm assuming it is the same issue.

I found that the error message comes from dl_reloc_overflow and the output message looks corrupted. I believe the dynamic linker is accessing the wrong location for the relocation entries and as a result the reloc address and string is bad, causing the error. There is obviously some randomness in this problem since it only happens on some environments.

**Comment by laboger** [comment]
We believe the problem is that the test contains the R_PPC64_ADDR16_HA relocation but when the test is loaded by ld64.so, the relocated offset is greater than what will fit into 16 bits so the overflow error occurs. The error depends on the load address for the binary.

I understand the point of the test depended on having a mix of PIC and nonPIC to exercise the problem you had so not sure how to make that happen.  Maybe just simpler code?

**Comment by ianlancetaylor** [comment]
Can you figure out what the relocation is referring to?

If we can make the code simpler, then let's try that.

**Comment by laboger** [comment]
Yes, if you look at the latest readelf output log that was posted by @mkumatag , there are multiple relocation entries of R_PPC64_ADDR16_HA and R_PPC64_ADDR16_LO for .init and .tbss.

**Comment by ianlancetaylor** [comment]
I don't understand why relocs against .init and .tbss would fail.  Those must be relocations from the executable to the executable itself.  And we aren't building this test case with PIE, so I would expect the result to have a fixed address.  So how could the relocs be out of range?

Hmmm, could the problem be that the system compiler defaults to passing -pie to the linker?  Maybe we need to have carchive_test.go pass an explicit -no-pie or -nopie, as cmd/go does.

**Comment by laboger** [comment]
I built this test by hand using the above commands in the container and passed in -no-pie and that fixes the problem. The binary no longer has any relocations for R_PPC64_ADDR16_HA or LO. It's not obvious to me how to add -no-pie as an option in cmd/dist/test.go so I can try it out in the container where it fails.

I know at some point gcc starting passing -pie by default at the link step (maybe gcc 6?). So that would explain why it doesn't happen on older distros.

It doesn't seem right to me that the dynamic binary would have unresolved relocations for R_PPC64_ADDR16_HA and LO, especially if you are saying they should be defined in the executable itself. Shouldn't the system linker have resolved them at link time?

**Comment by ianlancetaylor** [comment]
For background, GCC itself does not pass `-pie` by default.  It only does so when it is configured and built with the `--enable-default-pie` option.  Some distros then build GCC with that option.  So whether PIE is the default depends on the specific distro version.

The system linker can only resolve any `R_PPC64_ADDR16_HA` and `R_PPC64_ADDR16_LO` relocs if it is invoked in normal mode.  If the system linker is invoked with `-pie`, then it can't resolve those relocs, since the address is unknown at link time, and it has to leave them for the dynamic linker.  The relocs are fine if combined with `R_PPC64_ADDR_HIGHERA` and `R_PPC64_ADDR_HIGHESTA`, and they are fine if the program is located in the first 4G of memory.

Adding `-no-pie` as an option for the test amounts to running `go test -buildmode=pie -ldflags=-extldflags=-no-pie`

**Comment by laboger** [comment]
OK I was thinking I had to make a change to cmd/dist/test.go to get the option passed and that was where I was stuck but now I see the change is in carchive_test.go.

Is it OK to pass -no-pie for all GOARCHes or should this only be done on ppc64le?

**Comment by ianlancetaylor** [comment]
It's fine to pass -no-pie on all architectures, but note that clang uses -nopie rather than -no-pie.  See the runtime test for that in cmd/go/internal/work/build.go.
