### ISSUE TITLE
x/net/http2: afterReqBodyWriteError wrapping causes temporary errors to fail type assertion

### ISSUE THREAD

**Issue by vcabbage** [golang/go#22136]
https://golang.org/cl/50471 wraps some errors with `afterReqBodyWriteError`. This wrapping causes type assertions to the [`net.Error`](https://golang.org/pkg/net/#Error) interface to fail even if the underlying error fulfills the interface.

https://github.com/golang/net/blob/a04bdaca5b32abe1c069418fb7088ae607de5bd0/http2/transport.go#L397-L405

Perhaps `afterReqBodyWriteError` should also fullfil `net.Error` and delegate the methods to the underlying error.

/cc @tombergan

**Comment by dsnet** [comment]
\cc @neild as an example of error tagging information lost because of wrapping.

**Comment by bradfitz** [comment]
All that error handling by wrapping is terrible. I kinda wish we'd just get rid of it, somehow.

**Comment by tombergan** [comment]
@vcabbage, are you seeing this problem when calling http2.Transport.RoundTrip, or when calling http2.ClientConn.RoundTrip? I believe the problem should only happen in the latter case, since http2.Transport.RoundTrip should unwrap the error.

The reason we did this is because we need to tell Transport.RoundTrip whether the error happened before or after the request body was written. We could not change the signature of ClientConn.RoundTrip without breaking clients ... but I didn't remember that changing the error type effectively changes the public API due to interface types like `net.Error`.

We can fix this more simply by adding an internal, unexported method like the following, which would be invoked directly by RoundTrip from both Transport and ClientConn:

```go
type roundTripError struct {
  err error  // so the underlying error is not lost
  afterReqBodyWrite bool
}

func (ClientConn*) roundTrip(req *http.Request) (*http.Response, roundTripError)
```

**Comment by vcabbage** [comment]
@tombergan It was happening when calling `http2.Transport.RoundTrip`.  It looks like it's possible to return the wrapped error if `retry` > 6 [here](https://github.com/golang/net/blob/a04bdaca5b32abe1c069418fb7088ae607de5bd0/http2/transport.go#L352-L377).

I'm a little surprised that we'd be hitting that case, but it's the only explanation I can see.
