### ISSUE TITLE
encoding/xml: unmarshaller and whitespace

### ISSUE THREAD

**Issue by md2perpe** [golang/go#22146]
### The issue
I had a file with space padded numbers (`NumberOfPoints="   266703"`) but the XML unmarshaller couldn't handle the spaces.

[Booleans are trimmed](https://github.com/golang/go/blob/99da873/src/encoding/xml/read.go#L647), so why [not numbers](https://github.com/golang/go/blob/99da873/src/encoding/xml/read.go#L617)?

### Does this issue reproduce with the latest release?

The issue exists in the currently latest commit in the GitHub repository:
https://github.com/golang/go/blob/99da873/src/encoding/xml/read.go

### What operating system and processor architecture are you using (`go env`)?
Not relevant as the issue is in architecture-independent library code.

### Examples
* Simple example: https://play.golang.org/p/3O0T3oU3Wy
* My case: https://play.golang.org/p/tF1HZRE-un (Strangely, no error is returned when I run it locally; I just get 0 for NumberOfPoints.)

### Good to know
I first asked about this and was given a workaround on Google Groups:
https://groups.google.com/forum/#!topic/golang-nuts/RtKU05cE9PY

**Comment by leighmcculloch** [comment]
According to the git history 1a37656b7a5aa97b23ec837825c6b30622f11b2c bools have been trimmed since they were first added by @rsc. @rsc: What was the motivation for trimming bools? Was it convenience?

If the reasoning was convenience I think it makes sense for there to be consistency across types where whitespace has no meaning since consistency will result in less wrong assumptions, but I think if it was to be added for consistency it'd need to be added to unsigned ints and floats too.

The no error on an invalid integer isn't intuitive and I think it should be considered a bug if trimming isn't introduced.

**Comment by kostix** [comment]
Not to weigh on any part of the scales, I'd still point out a bit from my response to @md2perpe [over there on the ML](https://groups.google.com/d/msg/golang-nuts/RtKU05cE9PY/_xuzIXi_AQAJ):

> The question of whether the string "   266703" represents a valid 
> integer is hardly decidable in my opinion.  For instance, would the 
> string "\v\v\v\n\n\n\t\t266703\n\n\n\v\v\v\v\t\x20\t" represent a valid 
> integer as well?

That is, while `   266703` looks innocent enough, though mildly annoying as it hints at sloppy
implementation of whatever generated that document, a string containing lots of "weird"
characters considered to be whitespace by Unicode (or Go's `strings` / `bytes` packages)
is, IMO, a bit less easily decidable to represent "valid" data.

**Comment by ianlancetaylor** [comment]
@leighmcculloch Since we don't do our code review on Github it sometimes helps to look over there to get more background on a change.  In this case, https://golang.org/cl/218050 .  In this case it looks like the purpose of the CL was to accept more strings for bool values.  It's not clear that anybody really considered the call to `strings.TrimSpace` in there.

**Comment by rsc** [comment]
Clearly we didn't think much of adding strings.TrimSpace in CL 218050 (which Michael Hoisie wrote and I reviewed), but it seems fine to apply strings.TrimSpace to all those numeric fields. Please make sure to update the docs and add a test. CLs welcome. Thanks.

**Comment by leighmcculloch** [comment]
If no one else is already on it I'd like to submit a CL to make the change. 🖐️
