### ISSUE TITLE
all: revert gratuitous use of strings.IndexByte

### ISSUE THREAD

**Issue by rsc** [golang/go#22148]
CL 65930 changed all uses of strings.Index(s, "x") to strings.IndexByte(s, 'x'). For string constants, this is unnecessary - Index already knows about that optimization; it is more text to type and to read; and it is less general - it doesn't compile for runes >= 0x100 and it is incorrect for runes in [0x80, 0xFF].

We have been (at least I have been) consistently encouraging people to use strings.Index for this case, specifically because it is clearer, more general, more correct, and essentially equally fast (except maybe in very tight loops). Using strings.IndexByte is premature optimization.

If you have a variable byte value v, then by all means use strings.IndexByte(s, v) instead of strings.Index(s, string([]byte{v})), but if you have a constant string, use strings.Index.

Sorry, but we should revert this CL.

**Comment by nightlyone** [comment]
Since the use case of optimizing this is important for some users it might make sense to optimize this better in the compiler (e.g. with partial inlining of trivial cases). 

To avoid building up arcane knowledge of how to optimize Go programs by writing more ugly code, simple rewritings for common string functions in important corner cases could be done by the compiler. GCC does this already.
