### ISSUE TITLE
cmd/compile go:noinline misuse in TestAssembly

### ISSUE THREAD

**Issue by huguesb** [golang/go#22208]
A pragma is placed before a closure and does not appear in the AST (at least not in the corresponding ODCLFUNC node)

```
func f72(a, b int) int {
  //go:noinline
  func() {_, _ = a, b} () // use some frame
  return b
}
```

This test currently passes because calls to closures are never inlined but this will change soon.
See #15561 and https://go-review.googlesource.com/c/go/+/65071

Should `go:noinline` be supported for closures? If so the scanner needs to be fixed. Otherwise the test needs to be updated.

**Comment by randall77** [comment]
I don't think we should support go:noinline for closures.  go:noinline is basically only for tests of Go itself, and we can always work around its restrictions.
f72 (and f13 in that same file) can probably get away with just calling runtime.GC() instead of the closure.  The offsets might need to be adjusted.
@cherrymui @mundaym
