### ISSUE TITLE
spec: type identity section not fully updated for 1.9

### ISSUE THREAD

**Issue by jiaweizhang** [golang/go#22202]
The `Type identity` ([link](https://golang.org/ref/spec#Type_identity)) section of the doc has the following:

these types are identical:
```
A0, A1, and []string
A2 and struct{ a, b int }
A3 and int
A4, func(int, float64) *[]string, and A5

B0, B0, and C0
[]int and []int
struct{ a, b *T5 } and struct{ a, b *T5 }
func(x int, y float64) *[]string, func(int, float64) (result *[]string), and A5
```
`B0` and `B1` are different because they are new types created by distinct type definitions; `func(int, float64) *B0` and `func(x int, y float64) *[]string` are different because `B0` is different from `[]string`.

### Suggested fix

these types are identical:
```
A0, A1, and []string
A2, struct{ a, b int } and struct{ a, c int }
A3 and int
A4, func(A3, float64) *A0, func(x int, y float64) *[]string, func(int, float64) *[]string, and A5
B0 and C0
```
`B0` and `B1` are different because they are new types created by distinct type definitions. Similarly,  `func(int, float64) *B0` and `func(x int, y float64) *A1` are different because `B0` and `A1` are created by distinct type definitions (`A1` is an alias of `[]string` while `B0` is a new, distinct type with the same underlying type as `[]string`.

### Rationale
This section of the docs was not completely updated to reflect the addition of alias declarations. I also recommend moving the "Properties of types and values" section containing "Type identity" down under the "Declarations" (specifically "Type declarations"), so the concept of alias declarations is introduced before they are used.

**Comment by griesemer** [comment]
I don't see any issues here:
- `struct{a, b int}` and `struct{a, c int}` are clearly different as they have different field names.
- Yes `B0` and `C0` are identical but the list is meant to be exemplary, not exhaustive. Otherwise we'd have to add much more. What we have is correct.

Regarding ordering: It's difficult to come up with the "best order" in a language spec that is naturally recursive. Thanks for the suggestion, but for now I prefer leaving it as is, because a) there's hyperlinks that make it easy to jump around, and b) people got used to the current order.

Closing.

**Comment by jiaweizhang** [comment]
The changes I made were more concerning the lines I took out:

```
[]int and []int
struct{ a, b *T5 } and struct{ a, b *T5 }
```

What exactly is the purpose of these two lines?

**Comment by griesemer** [comment]
See https://github.com/golang/go/issues/9226 for a discussion.
