### ISSUE TITLE
name return

### ISSUE THREAD

**Issue by ajaychk** [golang/go#22316]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by davecheney** [comment]
Hello, 

It looks like this might have been a mistake as this issue is blank. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by ajaychk** [comment]
Hi Cheney,

I will follow the process as you mentioned. But as of now my doubt is -
Why do we need to type return at the end of function in case of name return?
My suggestion is compiler should be able to handle this automatically.

Thanks and Regards,
Ajay
Chipmonk
