### ISSUE TITLE
cmd/compile: ARM: add FMA support

### ISSUE THREAD

**Issue by rasky** [golang/go#22400]
Tracking bug for missing FMA (fused multiply-add) support on ARM/ARM64 backends.

I think that, for 32-bit ARM, part of the problem is that FMA support is sparse; it requires a specific FPU type, so it doesn't even correctly map to a specific architecture (as identified by the current `GOARM` environment variable).

**Comment by cherrymui** [comment]
@benshi001 has attempted to do it on ARM32, in CL https://go-review.googlesource.com/c/go/+/63770. It turns out that even GOARM=7 machine may not support fused multiply-add. That CL then added and made use of (non-fused) multiply-add instruction.

Given that we already do multiply-add in one instruction, and the fused version is not widely available (and not sure how much faster it is compared to non-fused version), I'm not sure what we want to do here.

cc @benshi001

**Comment by benshi001** [comment]
the fused mul-add was introduced in VFP-4, which GOARM=7 does not imply.

**Comment by agnivade** [comment]
Closing this as per this [comment](https://github.com/golang/go/issues/8037#issuecomment-551900009). We have a similar code for ARM too.

Please feel free to reopen if this was a mistake.
