### ISSUE TITLE
cmd/gofmt: unexpected comment indentation 

### ISSUE THREAD

**Issue by rakyll** [golang/go#22408]
```
$ go version
go version devel +fb54abe9ce Wed Sep 20 03:54:16 2017 +0000 darwin/amd64
```

```
type Value struct {
	Count           int64   // number of data points aggregated
	Min             float64 // minimum value in the distribution
	Max             float64 // max value in the distribution
	Mean            float64
	SumOfSquaredDev float64   // the sum of the squared deviation from the mean
	CountPerBucket  []int64   // number of occurrences per bucket
	Bounds          []float64 // histogram distribution of the values
}
```

Although I was expecting it to be:

```
type Value struct {
	Count           int64     // number of data points aggregated
	Min             float64   // minimum value in the distribution
	Max             float64   // max value in the distribution
	Mean            float64 
	SumOfSquaredDev float64   // the sum of the squared deviation from the mean
	CountPerBucket  []int64   // number of occurrences per bucket
	Bounds          []float64 // histogram distribution of the values
}
```

/cc @griesemer

**Comment by mvdan** [comment]
The alignment is broken if there is a line without a comment, I believe. Are you suggesting that the design should be different? Have you thought of a change to the rule in particular?

**Comment by rakyll** [comment]
I am suggesting that the alignment shouldn't be broken unless there is a new line.

**Comment by robpike** [comment]
I see this as working as intended. Each set of end-of-line comments will be aligned as a unit. A missing comment initiates a new unit.

**Comment by griesemer** [comment]
What @robpike said.

**Comment by griesemer** [comment]
To clarify: gofmt handled comments like this from day one and it is by design: A "column" of things (comments in this case) ends whenever the thing in question is missing on a new line. There are other mechanisms that end a column (e.g. indentation of a block), but if you want the comment column to continue, you need to add an (empty) comment where there's none in this case.

I can see that aligning all comments **in this case** looks nicer.
