### ISSUE TITLE
Channel for-loop bug

### ISSUE THREAD

**Issue by YannickFricke** [golang/go#22449]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
1.9.2 is the latest release

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yfr/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build370294560=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
https://play.golang.org/p/ETJ0pPUEBH

### What did you expect to see?
Neue Zahl: 1000

### What did you see instead?
Neue Zahl: 999

### Description
The last iteration of will be skipped if something was passed before the for-loop executes. You can verify this behavior on the playground too (link for this is under `What did you do?`).

This is the expected behavior: https://play.golang.org/p/OpNKe-WFsg

**Comment by ALTree** [comment]
You don't see the last number printed because `main` is returning before the goroutine running `compute` has the time to print the last number.

If you add this:

```
time.Sleep(1 * time.Second)
```

at the end of the `main` function, you'll see that the `Neue Zahl: 1000` line will be printed.

In general, you'll need some kind of synchronization mechanism to avoid issues like this in your code (note that the `Sleep` call is not a proper way to fix your code, that was just a dirty fix to demonstrate the issue).

Closing this, since this is not a Go bug.

**Comment by mirza-s** [comment]
main() exists before the last element is printed.

**Comment by YannickFricke** [comment]
@ALTree But why is it working perfectly, when you dont send "test" on the channel first?
I understand what you want to say, but this is contradictory.

**Comment by dominikh** [comment]
Because of timing sensitivity and effectively a race condition. You can get the same result by using different numbers of loop iterations, or repeating the same test multiple times (albeit not on the playground, as it caches executions.)

For questions about Go, please see https://github.com/golang/go/wiki/Questions

**Comment by ALTree** [comment]
> But why is it working perfectly, when you dont send "test" on the channel first?

It's not. Comment the  `channel <- "test"` line and run your program several times. On my machine, this happens:

```
$ while true; do go run prova.go | tail -n1; done

Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 999
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 999
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
Neue Zahl: 1000
```

It *usually* works, except when it doesn't. The result in non-deterministic and likely depends on environment conditions and internal details of the Go scheduler.

**Comment by davecheney** [comment]
@YannickFricke Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process. As this issue is closed I am going to limit conversation to encourage the discussion to move elsewhere. 

Please see https://golang.org/wiki/Questions for good places to ask questions.
