### ISSUE TITLE
cmd/compile: missing wrapper function for call of literal method expression

### ISSUE THREAD

**Issue by griesemer** [golang/go#22444]
https://play.golang.org/p/CE9RBX_L4Z results in:
```
go.struct { main.T }.m2·f: relocation target go.struct { main.T }.m2 not defined
go.struct { main.T }.m2·f: undefined: "go.struct { main.T }.m2"
```
See also #9060 .

**Comment by mdempsky** [comment]
Looking at the compile -S output, it looks like we're not emitting a TEXT symbol for `struct { main.T }.m2`. Reclassifying as a cmd/compile bug.

**Comment by mdempsky** [comment]
Bumping to Go 1.11. This is a long-standing issue that is only now technically an issue because we relaxed the Go spec in #9060.

**Comment by randall77** [comment]
This is breaking the noopt builder, though. We should probably do something for that in 1.10.

**Comment by ianlancetaylor** [comment]
@randall77 @mdempsky Is there anything else to do this on this issue for 1.10?

**Comment by mdempsky** [comment]
@ianlancetaylor Oops, no.

**Comment by mdempsky** [comment]
Just for the record, one of the interesting things about this issue is the particular repro case here only affects `go run` and the Go playground (presumably because it uses `go run`). It does not affect `go build`.

The difference is that `go run` compiles with `-dwarf=false`. Normally, we only produce type descriptors for package-scope declared types, and any other types as they're needed (e.g., types that are allocated on the heap). In the test case, `struct { T }` only appears on the stack, so it doesn't need a runtime type descriptor. But enabling DWARF means we write out DWARF descriptors of all named stack variables, and DWARF descriptors cross-reference the underlying Go type descriptor.
