### ISSUE TITLE
x/image/font/sfnt: implement font.Face

### ISSUE THREAD

**Issue by sbinet** [golang/go#22451]
To ease the migration from `github.com/golang/freetype/truetype` to `golang.org/x/image/font/sfnt`, it would be valuable to have `font/sfnt` provide a type that implements `font.Face` on top of the `sfnt` facilities.

with https://golang.org/cl/67330 it seems possible to implement most of the `font.Face` interface.

`truetype` does it via [NewFace](https://godoc.org/github.com/golang/freetype/truetype#NewFace).
I'd propose to do the same with a new `sfnt.NewFace` function:

```go
// NewFace returns a new font.Face for the given Font.
func NewFace(f *Font) font.Face { ... }
```

@nigeltao what do you think ?

**Comment by nigeltao** [comment]
There totally needs to be a font.Face implementation somewhere under golang.org/x/image/sfnt, either using or being part of golang.org/x/image/font/sfnt. I just haven't had the time to do it myself.

I was thinking it would be a separate package, perhaps golang.org/x/image/font/opentype, so that people could import just the sfnt package if they wanted e.g. metrics and layout without having to pull in all of the rasterization code. But I haven't given a lot of thought to it.

**Comment by sbinet** [comment]
I have mailed what I got so far: https://go-review.googlesource.com/#/c/image/+/73870
(I can of course put all the current `font.Face` implementation under this new `font/opentype` package)

**Comment by hajimehoshi** [comment]
What's up on this issue? Thank you!

**Comment by nigeltao** [comment]
That's for @sbinet to answer. I don't have any time to work on this myself.

**Comment by hajimehoshi** [comment]
Hi, what's going on this?

**Comment by nigeltao** [comment]
I can't speak for others, but for myself, I'll repeat what I've said before: I'd like to see this happen, but I don't have any time to work on this myself.

**Comment by nigeltao** [comment]
See also https://go-review.googlesource.com/c/image/+/170578 "font/opentype: implement Glyph and GlyphBounds" which is incomplete and abandoned, but might be educational for anyone who wants to tackle this themselves.
