### ISSUE TITLE
negative number in fibonacci

### ISSUE THREAD

**Issue by michalswi** [golang/go#22562]
go version go1.8.1 linux/amd64

If I check my code for number like **6** in the output I have got **8** which is correct. If I have **99** then I have got negative number. It seems there is some problem with big numbers. For **99** I should receive **218922995834555169026** where in my script I have got **-2437933049959450366**.
If I use uint64 or int64 it doesn't solve my problem.

```
package main

import (
"fmt"
)

var num = 94

func main() {
  fmt.Printf("%d\n", fibo(num))
}

func fibo(num int) int{
  a, b := 0, 1
  for i := 0; i < num; i++ {
    a, b = b, a + b
  }
  return a
}
```

**Comment by ALTree** [comment]
`int` type is not arbitrary-precision: it's either 32 or 64 bit. After a certain point, Fibonacci numbers get bigger than what an `int` variable can hold, and an *integer overflow* occurs.

Since the Go project does not use its bug tracker for general discussion or asking questions about the language, and this is not a Go bug, I'll close this issue.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions like this one.
