### ISSUE TITLE
net/url parseQuery allows semicolon `;` to be the separator

### ISSUE THREAD

**Issue by larrycinnabar** [golang/go#22641]
In 2014 W3C Recommandation is said:

```
Let strings be the result of strictly splitting the string payload on U+0026 AMPERSAND characters (&).
```

https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data

So, now semicolons are not allowed to be query separators (as it was allowed in 1999 Recommendation).

Golang's `net/url.go` parseQuery function checks for both symbols:
https://github.com/golang/go/blob/master/src/net/url/url.go#L824

And in this case it's not allowed to use semicolon inside query parameters.
```go
// r *http.Request
q := r.URL.Query()
abc := q.Get("abc")

// &abc=1234;567
// abc will be "1234", but not "1234;567"
```

**Comment by dsnet** [comment]
See #2210. I'm going to mark this working-as-intended.

The `url` package does not attempt to be a perfect implementation of RFC 3986, since the internet is full of errant and non-compliant implementations. If a popular enough implementation is non-compliant, it's implementation effectively becomes the "standard" regardless of what the formal specification says.
