### ISSUE TITLE
cmd/compile: character position vs line comments

### ISSUE THREAD

**Issue by rsc** [golang/go#22662]
If the compiler reads //line xxx:10, it understands the next line in the source file to be attributed to file xxx line 10, but it also disables reporting of character position information, because often generated code does not preserve character positions when converting from the original file to the generated code. But sometimes a generator can preserve that information, and it would be nice for our tools to be able to present it.

I suggest that we allow `/*line xxx:10:20*/`, where the `xxx` may be omitted if the file name has not changed since the last comment, to declare that the very next byte after that comment is :10:20, and character position should be tracked and reported until the next line comment. Similarly, `//line xxx:10:20` would say that the next line begins at character position 20. It's important to have a /* */ comment form in order to be able to introduce a line annotation without introducing an implicit semicolon.

With this and some pending CLs I have for cmd/cover and cmd/cgo, the errors reported by the compiler would be exactly as precise when using coverage as when not using coverage, and the same for cgo. 

Also, because the character position would be precise, using cgo-preprocessed sources in source code refactoring tools would no longer prevent those tools from modifying the original sources.

This is orthogonal to #16623 (passing unmodified cgo sources to the compiler and perhaps also go/types), since it would still be very helpful for cover and other converters (we can't put them all in the compiler and go/types).

**Comment by griesemer** [comment]
One thing to consider is the impact of gofmt. For instance, it could make sense to define /*line file:line:col */ as the position of the first Go token following it (rather than the byte immediately following).

Since the /*line ... */ annotations are (likely) produced by a tool, and that tool is using positions of existing tokens, it might make those positions more stable in the presence of minor gofmt formatting changes (extra white space on the same line).

**Comment by griesemer** [comment]
@rsc At least as specified, there is a fundamental problem on Windows because filenames may contain a drive letter followed by a `:`. For instance with
```
//line c:/foo/bar.go:987
```
(from test/fixedbugs/issue18149.go) the pragma processor assumes that we have a filename `c`, followed by an invalid line number `/foo/bar.go` and a column number `987` and parsing will fail.

For line directives with an invalid line number specification one could simply assume that the line number section is the filename; with such a work-around the above example would work. But file names may be numbers, and then the work-around falls flat:
```
//line c:1234:567
```
Is this a line directive with filename `c`, line `1234`, and column `567`; or is it file `c:1234` with line `567` and no column specification?

Without optional column specification we don't have this problem: Currently, a line directive must have a `:`, and the lexer looks for the last `:` to determine the break between file and line specification. With optional columns the notation becomes ambiguous on any file system that permits `:` in filenames.

There's a several ways out of the dilemma: 1) introduce some form of escape mechanism for any `:` in a filename; 2) use a character other than `:` as separator and which is not permitted in filenames; or 3) use a different line directive syntax altogether (see below). There may be other options.

Here is an alternative format that doesn't have the problem. Borrowing from C's line directive, we could use the forms:
```
//line <line>
//line <line> <file>
//line <line> <column> <file>
```
where `<line>`, `<file>` and `<column>` are blank-separated line number, file name, and column number, respectively. If only the line (and/or column) number changes, the file can be left away many times (often after the first //line directive). If we don't want to change the line or column number, but change the file, we could designate the invalid line/column values `0` as "skip" values. And finally, because the line-only form would have to be a valid number that cannot contain a `:`, we could distinguish these forms from the current line directive, allowing for them to co-exist.

But at least on OS X, file names can have blanks in them, so some suitable escape mechanism will still be needed.

**Comment by ianlancetaylor** [comment]
In C's `#line` directive the filename is be a string constant.  That handles spaces and unusual characters in a predictable way.  We could do the same, but make the string constant optional.

    //line "c:/foo/bar.go":987

If the quotes are there, we apply the usual string constant escape handling.

**Comment by griesemer** [comment]
@ianlancetaylor Sounds like a plan.

**Comment by griesemer** [comment]
@ianlancetaylor That's not backward-compatible with what we have now: Existing directive texts with two `:`'s where the first one belongs to the filename would still be misinterpreted. I don't think we can require people to rewrite those.

I think any solution requires some kind of format change.

**Comment by griesemer** [comment]
One could require the filename to always be a string constant (or absent) if a column is specified. Otherwise it's the existing format (with the filename optionally being a string constant).

**Comment by griesemer** [comment]
Created #24143 to track the non-compiler aspects of this issue.
