### ISSUE TITLE
archive/tar: long paths produce incompatible output with dpkg 

### ISSUE THREAD

**Issue by jboelter** [golang/go#22675]
### What version of Go are you using (`go version`)?

1.5.4 - ok
did not try interim releases to narrow it down
1.9.2 - fails

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

The latest version of the archive/tar package in 1.9.2 produces output that is incompatible with dpkg as exposed by the godeb tool. See this related bug - https://github.com/niemeyer/godeb/issues/29

Building the godeb tool with 1.5.4 works (use the pull request w/ the fixes for the new download URLs), building with 1.9.2 fails.

**Comment by dsnet** [comment]
The cause of this issue is that `dpkg` expects tar archives to be the GNU format, and does not understand the PAX format. In Go1.8 (and in Go1.9), I disabled path prefix splitting because the behavior was entirely buggy. This prevented the tar package from being able to use the USTAR format (which `dpkg` still understands), but forced it to use PAX to represent the longer file names. The inability to have control over the output format is the root issue here since both GNU and PAX are popular variants of tar.

For this reason, I filed #18710. In Go1.10, you will be able to explicitly specify that the output format is GNU, which will make `dpkg` happy again.

**Comment by jboelter** [comment]
Confirmed the tip works to translate from PAX -> GNU (at least for this use in the godeb tool).  Thanks @dsnet 

```
in := tar.NewReader(...)
out := tar.NewWriter(...)
defer out.Close()
for {
	h, err := in.Next()
	if err == io.EOF { break }
	h.Format = tar.FormatGNU
	h.PAXRecords = nil
	out.WriteHeader(h)
	if h.Typeflag == tar.TypeDir { continue }
	w, err := io.Copy(out, in)
}
```
