### ISSUE TITLE
doc: remove FirebirdSQL from the list

### ISSUE THREAD

**Issue by giovannigaspar** [golang/go#22765]
I don't think it's worth listing the Firebird driver in the official page anymore cuz it isn't being updated and it isn't working properly... I reported some bugs, the dev doesn't answer and IMO he doesn't care about the driver (probably because just a few people are using it. My guess is like 10) ... Because of that I am migrating to PostgreSQL, which has a huge community and professional developers (excellent driver btw) . GO it's an excellent programming language and the official SQL drivers list should just include supported and updated drivers. 
Nakagami did a good job with his Firebird driver, but he is alone there. If I had the knowledge I would help him or would create a driver of my own, but the reality is different, at least for now... 

Thanks.

**Comment by bradfitz** [comment]
What list?

/cc @kardianos

**Comment by kardianos** [comment]
I'm guessing this list: https://github.com/golang/go/wiki/SQLDrivers
I'll take a look at it.

**Comment by kardianos** [comment]
The repo: https://github.com/nakagami/firebirdsql is reasonably active. I'm not going to de-list it from the wiki because you've had some problems. I will not attest to it's robustness, but really, we should really be testing and verifying drivers. In a sense this falls on us. But for now, I'm not going to de-list them.
