### ISSUE TITLE
build: decide per-repo or per-package which versions of Go are supported?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22786]
Historically we've only supported the past two released versions of Go.

The other day I removed release-branch.go1.7 from https://build.golang.org/ since only Go 1.8 and Go 1.9 are supported.

But then I saw https://go-review.googlesource.com/c/sys/+/78255 go in, fixing the build for Go 1.7 users.

I can probably understand people wanting x/sys still working back to Go 1.7.

Do we care to support that? Best effort only, or do we want test coverage?

If we want test coverage, we need to decide & document the policy per-repo or per-package and have a way to annotate it so the builders know what to do.

/cc @tklauser @ianlancetaylor @rsc

**Comment by tklauser** [comment]
Regarding https://go-review.googlesource.com/c/sys/+/78255 I noticed it while running the tests on an old OpenBSD 6.0 VM with Go 1.6 from ports so I decided to do a best effort fix there.

A general rule (i.e. official support for last two releases) for all repos/packages would be probably easier to communicate to users rather than a per-package or per-repo policy.

I agree with @bradfitz that people might want to use x/sys a bit farther back than just the last two releases. But then again users of older Go versions for whom something doesn't work will hopefully file an issue which we could fix best effort. But committing to supporting these older version and even have test coverage for them is IMO not worth the effort.

**Comment by rsc** [comment]
Per https://golang.org/doc/devel/release.html#policy, Go 1.7 is no longer supported. We don't need to run builders and we don't need to make fixes for Go 1.7 users. If they want to keep using an old copy of x/sys, they can vendor it. If they want a new feature, they'll need to maintain and apply patches to their own copy.
