### ISSUE TITLE
cmd/go: progress bar for "go get"

### ISSUE THREAD

**Issue by longzhizhi** [golang/go#22800]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
mac

### What did you do?
check by myself( waste sometime)
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ALTree** [comment]
Most go tools are quiet by default, and this is unlikely to change (the idea of adding a progress bar was discussed in the past, several times: #17959 #18388).

You can use the `-v` flag to make the output more verbose, though.

**Comment by mvdan** [comment]
I think more issues like this one aren't helpful unless there is a suggestion on how to implement such progress information - preferably, with a prototype of some sort.

For example, I would imagine that a good amount of the time would be spent in commands like `git clone`, since some repositories weigh hundreds of megabytes or the user's connection may not be fast. How would `go get` get the progress information from such a command? And since the go tool also supports `svn`, `hg` and `bzr`, the same should apply to the equivalent command for those.

**Comment by bradfitz** [comment]
As @ALTree said, this is a dup (#17959 #18388). See the comments there. You're welcome to prototype it and it could live as an external tool. Perhaps once it exists, the cmd/go could see if it exists in the $PATH and use it conditionally. Maybe. But first somebody has to prototype. The Go team won't be working on it, sorry.
