### ISSUE TITLE
cmd/compile: inaccurate column number for parameters

### ISSUE THREAD

**Issue by cherrymui** [golang/go#23031]
### What version of Go are you using (`go version`)?
tip (1b9f663)

### Does this issue reproduce with the latest release?
yes

### What did you do?
It seems that the column numbers for parameters are not accurate. Different parameters may get same line and column numbers, as seen in #23020.

I've come up a simple example:
```
package p

//            15     22
//            |      |
func f(x int, x int) int {
	return 3
}
```

### What did you expect to see?
```
/tmp/x5.go:5:15: duplicate argument x
```

### What did you see instead?
```
$ go tool compile /tmp/x5.go 
/tmp/x5.go:5:22: duplicate argument x
```

It seems we don't emit column numbers for variables in DWARF --  if we do, that might be also inaccurate.

**Comment by mdempsky** [comment]
I was looking at this the other day. The issue is we setup the `ONAME` Nodes to represent the parameters with the position information where the identifiers appeared, but then when we call `funcargs` (and in turn `declare`), that information gets clobbered with `lineno` (which happens to be at the last token in the function signature, the `int` return parameter type).

I think the proper fix is that `gc.declare` needs to stop clobbering `n.Pos`, and to just require that callers always setup `n.Pos` correctly. I think this is almost already the case, but needs a review.

**Comment by griesemer** [comment]
This appears to be fixed. I cannot reproduce this.

**Comment by odeke-em** [comment]
@griesemer in deed, this bug was fixed by CL [104275](https://go-review.googlesource.com/104275) aka commit https://github.com/golang/go/commit/26e0e8a840249d13f94596ebb519154505bd15f4 and precisely this line deletion in dcl.go https://github.com/golang/go/commit/26e0e8a840249d13f94596ebb519154505bd15f4#diff-af57b81069f33da91c083d4d5b61aeeeL80
<img width="693" alt="screen shot 2018-06-27 at 1 42 34 pm" src="https://user-images.githubusercontent.com/4898263/41998586-fd300540-7a0f-11e8-9591-5586537479b5.png">
