### ISSUE TITLE
cmd/compile: stack overflow instead of initialization loop error

### ISSUE THREAD

**Issue by griesemer** [golang/go#23093]
https://play.golang.org/p/7e5OO_qt0m correctly reports an initialization loop error. But cmd/compile (1.10 Beta) crashes with a stack overflow.

Superficially looks like a new error in the inlining code.

**Comment by mdempsky** [comment]
The regression was introduced in c4b65fa4cc4b799cad461779564af30dbf232f13.

I think the issue is the new code in `hairyVisitor` doesn't check if the named closure being called is a global or local variable. In `inlnode`, there's extra code in `reassigned` to make sure we don't try inlining a call to a global closure. That code was missed when the logic was copied into `hairyVisitor`.
