### ISSUE TITLE
x/build/cmd/gitmirror: deleted branches/tags are being mirrored to GitHub

### ISSUE THREAD

**Issue by andybons** [golang/go#23099]
I accidentally added some superfluous tags while doing the release last week. I removed them and they no longer show up on https://go.googlesource.com/go/+refs

On GitHub, however, they do show up even after I’ve manually deleted them in the GitHub UI. An example: https://github.com/golang/go/releases/tag/andybons%2Fcachedir.mailed

/cc @bradfitz

**Comment by dmitshur** [comment]
Has something changed here? Both the tag mentioned in the original issue description and the security branches are not currently showing up on GitHub. Is the issue resolved, or is there another explanation?

**Comment by FiloSottile** [comment]
I manually removed the `-security` branch, and it looks like it's not coming back.

**Comment by dmitshur** [comment]
While it may have looked like something changed causing this issue to not be a problem anymore, that is not the case.

I've recently created and later deleted a branch named `dmitshur-test1` in the scratch subrepo. It does no exist on the origin server anymore. However, it didn't get deleted from the GitHub mirror. When I deleted it manually, it re-appeared. I got the following from `gitmirror` logs:

```
[...]
2019/08/19 19:06:33 Reloaded data from log *maintner.netMutSource.
2019/08/19 19:06:33 Updating data from log *maintner.netMutSource ...
2019/08/19 19:06:34 scratch: 1 refs remain to sync to github
remote: 
remote: Create a pull request for 'dmitshur-test1' on GitHub by visiting:        
remote:      https://github.com/golang/scratch/pull/new/dmitshur-test1        
remote: 
To github.com:golang/scratch.git
 * [new branch]      1d5b30010bae27fa3b85e03370c17c837c095fa1 -> dmitshur-test1
2019/08/19 19:07:42 Downloading 33 bytes of https://maintner.golang.org/logs/54 ...
2019/08/19 19:07:42 wrote /cache/golang-maintner/0054.growing.mutlog
2019/08/19 19:07:42 Reloaded data from log *maintner.netMutSource.
[...]
```

### Possible Explanation

I have a theory about what's causing this issue and why it seems to get resolved on its own after some time (but then reoccurs again).

Perhaps the way the origin repository is cloned to a temporary location in the `gitmirror` worker is such that it doesn't track branch/tag deletions from upstream, so `gitmirror` keeps thinking the origin has them and keeps pushing them to the GitHub mirror. However, maybe after `gitmirror` is redeployed it creates a fresh clone of the upstream repositories that no longer has the branches/tags deleted from upstream, and so the problem stops happening.

If that's the case, the fix will be to change `gitmirror` so that it tracks branch/tag removals from the origin repository. I think it can be done by using `--prune` flag, e.g., `git remote update --prune` or `git fetch --prune origin` (see https://git-scm.com/docs/git-remote and https://git-scm.com/docs/git-fetch#_pruning). [This line](https://github.com/golang/build/blob/master/cmd/gitmirror/gitmirror.go#L421) might be a relevant.

**Comment by dmitshur** [comment]
I've investigated this further, it seems the theory above was accurate.

[CL 190879](https://golang.org/cl/190879) is deployed and makes it so that refs deleted from origin repositories are no longer continuously recreated on the GitHub mirrors.

They're not automatically deleted yet, but with a little more work ([CL 190897](https://golang.org/cl/190897) is underway) that should be possible to resolve too.
