### ISSUE TITLE
cmd/fix: incomplete "go tool fix -r cftype" suggestions

### ISSUE THREAD

**Issue by kevinburke** [golang/go#23091]
Go 1.10 introduces some changes to cgo, but I ran "go tool fix -r cftype" and still got compilation failures. Is the team still interested in improving the heuristics for "go tool fix"? I'm just an end user of a lot of these libraries, I haven't done that much with cgo and I'm not sure how to fix them.

Running "go tool fix" on this package makes some changes but there are still a number of compilation failures: https://github.com/keybase/go-keychain/issues/19

Also the "remaining change" listed here: https://github.com/golang/text/commit/572a2b141f625f4360cf42a41a43622067e0510b

Feel free to close as "this library needs to do some work, go tool fix is relatively complete."

**Comment by ianlancetaylor** [comment]
CC @randall77

**Comment by odeke-em** [comment]
Am not sure if this will be for Go1.10. Perhaps let's punt to Go1.11?

**Comment by ianlancetaylor** [comment]
ping @randall77

**Comment by randall77** [comment]
(I responded to this yesterday! Somehow it didn't stick.)

There seem to be 3 different issues here.

1. Incomplete typechecking.  `go tool fix` has a limited typechecker.  It doesn't have the type information for the C functions like `C.CFDataCreate`.  So it doesn't know that the argument or return types are.  For example:
```
cfData := C.CFDataCreate(nil, p, C.CFIndex(len(b)))
```
It doesn't know to rewrite the `nil` to `0` or the subsequent comparison of `cfData == nil` to `cfData == 0`.
I think the problem here is that the typechecker doesn't handle global variables, only functions.  The `C.*` functions are actually variables.  I'll see if I can upgrade the typechecker for these.

2. Converting pointers to CF*Ref types.  Example:
```
		C.CFDictionaryGetKeysAndValues(cfDict, (*unsafe.Pointer)(&keys[0]), (*unsafe.Pointer)(&values[0]))
```
It used to be that `&CFTypeRef` was convertible to `*unsafe.Pointer` as above.  Now it will need an additional `unsafe.Pointer` cast, like this: `(*unsafe.Pointer)(unsafe.Pointer(&keys[0]))`.  We might be able to detect this automatically.

3. There's a whole set of types the rewrite doesn't apply to, and it probably should.  `C.SecAccessRef`, `C.SecTrustedApplicationRef`, `C.SecKeychainRef`, `C.SetKeychainItemRef`.  I've never heard of them before, but they look convertible to `C.CFTypeRef` so they should be covered.  I'll add the `C.Sec*Ref` pattern also.  Maybe also `C.*Ref`?  It will cover future discoveries like this, but also risks including types we might not want to.

I definitely want to handle 1 and 3.  2 is more questionable, as it involves a more complicated rewrite.

**Comment by randall77** [comment]
Actually, number 1 is because cgo isn't run before typechecking, so we don't have the types of the C. functions at all.

**Comment by randall77** [comment]
So it looks like there are a *lot* of types that are upcastable to a `CFTypeRef`.  Grepping though header files, I find 214 of them.  They have no particular prefix, just the `Ref` suffix.
For number 3, I think we need to go with `C.*Ref` as the matching type.
