### ISSUE TITLE
go/doc: does golang offer pdf format reference?

### ISSUE THREAD

**Issue by knightXun** [golang/go#23101]
sometimes, I want use my kindle to read go reference.But i can't find any pdf reference about golang.So how i can get it?

**Comment by ALTree** [comment]
We don't distribute documentation in pdf format. I guess you could write a script that uses one of the many html2pdf tools to convert the output of `godoc -html` to pdf. 

Please note that the project only uses the github issue tracker for Go bugs. See the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions like this one. Thanks!

Closing this, since it's not a Go bug.
