### ISSUE TITLE
io/ioutil: nopCloser should be public

### ISSUE THREAD

**Issue by Kegsay** [golang/go#23118]
As of Go 1.9.2, `ioutil.nopCloser` remains private, meaning you cannot type assert on it. This was brought up [years ago](https://github.com/golang/go/issues/12235) but a valid use case was never proposed.

I am implementing a `RoundTripper` which may need to retry sending its HTTP request. This requires either:
 - A new `req.Body` to read from (aka copying)
 - A way to seek the already-read `req.Body` back to the beginning.

Seeking is preferable but not everything will support that, so I fall back to copying as a last resort. My `RoundTripper` would attempt to type assert on `Seeker`.

In the calling code, I purposefully made a `bytes.Reader` which supports seeking and fed that to `http.NewRequest`, expecting my seeking code to fire. To my surprise, the seeking code failed to execute because it turns out that `http.NewRequest` will wrap up readers in `nopCloser` if they do not implement the `Closer` interface, and `nopCloser` does not implement the `Seeker` interface. I am unable to resolve this because `ioutil.nopCloser` is private, so I cannot type assert on it.

I can obviously work around this by implementing my own `nopCloser` but this severely limits the usefulness of the `RoundTripper` since consumers will expect to be able to just call `http.NewRequest` with a `Seeker` and have it Just Work™

**Comment by davecheney** [comment]
What is your use case for the reader passed to NewRequest implements io.Seeker?

**Comment by Kegsay** [comment]
The use case is to supply an `http.Client` which automatically retries requests without having to copy the request body.

In order for users to 'enable' this, they pass a reader which implements `io.Seeker` to `NewRequest`. If `ioutil.nopCloser` were public, this would be it and the rest would just work as the `RoundTripper` could inspect the `Body` and determine that it is a `io.Seeker`. However, because it is private, the `RoundTripper` cannot introspect in this way.

**Comment by davecheney** [comment]
I think the http rfc defines methods which supply a body like POST, PUT, and PARCH, to be non idempotent so what you’re planning may not be safe.

**Comment by Kegsay** [comment]
This is for use in an internal project whereby I know more about the requests than just things like the method. As an aside, [PUT](https://tools.ietf.org/html/rfc2616#section-9.1.2) should be regarded as idempotent, but the others are not.

**Comment by ianlancetaylor** [comment]
I'm not sure I fully grasp the problem, but exporting `ioutil.nopCloser` so that other code can type assert to it, pull out the internal `io.Reader`, and type assert on that, seems like heaping Pelion upon Ossa.

I think what you are getting at is a language/library issue: there is no way to add a method to an existing value without obscuring the existing methods.  Can we think of a way to solve that general problem?

In the meantime, I think that all net/http cares about is having a `ReadCloser`, so it seems to me that the simpler solution is to give it that, rather than try to undo the choices it makes when it sees something else.  For example, write an adapter type just like `io.nopCloser` but use `io.ReadSeeker` rather than `io.Reader`, and use that adapter before going into net/http.

**Comment by bradfitz** [comment]
https://golang.org/pkg/net/http/#Request.GetBody was added recently explicitly for request retries. You should use that instead.

We won't be exporting weird internals.

**Comment by Kegsay** [comment]
> For example, write an adapter type just like io.nopCloser but use io.ReadSeeker rather than io.Reader, and use that adapter before going into net/http.

I did something similar to this in order to work around this issue.

> https://golang.org/pkg/net/http/#Request.GetBody was added recently explicitly for request retries. You should use that instead.

I noticed this was recently added for the purposes of retrying, but was under the impression that it was used in the guts of `net/http` and not intended to be used by custom `Tripper` implementations. If we're happy to let custom `Tripper` implementations make use of this then I'm happy for this to be closed.

> We won't be exporting weird internals.

I don't find this very helpful because you never state why it's weird. It satisfies an interface which is used throughout the standard library, the implementation is clear and obvious to any Go developer, and the intent of the struct is clear, I fail to see it as a weird internal IMHO.

**Comment by bradfitz** [comment]
> I don't find this very helpful because you never state why it's weird. 

Because it's not the API we want people using. Anything we export becomes a mental burden for people reading the godoc, distracting them from the parts we want them to use.

**Comment by mvdan** [comment]
> `rc := ioutil.NopCloser{r}`

Small point - note that then you'd have to use `ioutil.NopCloser{Reader: r}`, which is more verbose than the current `ioutil.NopCloser(r)`. The reason is backwards compatibility (with imported packages), and there even is a vet warning about it:

https://golang.org/pkg/cmd/vet/#hdr-Unkeyed_composite_literals

**Comment by bradfitz** [comment]
> If we're happy to let custom Tripper implementations make use of this then I'm happy for this to be closed.

SGTM :)
