### ISSUE TITLE
how can i get a same elf binary like gcc?

### ISSUE THREAD

**Issue by wuyeguo** [golang/go#23189]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/work/go"
GORACE=""
GOROOT="/home/work/wuyeguo/source/go"
GOTOOLDIR="/home/work/wuyeguo/source/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build022896224=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
what is the different with the go binary and the C binary?
I Write The program need to protect by  Wibu-Systems
http://trafficlicense01.ptvgroup.com:22400/$help/CmUserHelp/us/cmu.htm

for go binary, the protected binary will segment fault
but for c binary， it will work will

**Comment by ALTree** [comment]
This looks like a bug in that 'CodeMeter' tool you are using. It's possible that it doesn't support Go binaries. I suggest you raise an issue in their tracker. Closing here since it doesn't look like a Go issue and it's unlikely that there's something we can do with the little information you posted here. 

If it turns out this is actually a Go issue, comment here and we'll reopen.

**Comment by wuyeguo** [comment]
I see。 thank you。
