### ISSUE TITLE
math/big: specialize Karatsuba implementation for squaring

### ISSUE THREAD

**Issue by griesemer** [golang/go#23221]
We may be able to get some more performance out of the multiplication code when we know that both operands are the same.

Follow-up for #13745.

**Comment by mvdan** [comment]
@griesemer perhaps you meant to milestone this as Unplanned, not Unreleased?

**Comment by bradfitz** [comment]
Has pending CL so marking release-blocker for Go 1.11. @griesemer can of course choose to not accept it for Go 1.11, but it was mailed pre-freeze so is okay for Go 1.11 and is just awaiting some review.

**Comment by griesemer** [comment]
I will review this but it's certainly not a release blocker. The code works fine as is and the new code is not that much faster.

**Comment by bradfitz** [comment]
We use "release-blocker" also to mean an issue has a CL and needs attention before the release, otherwise they get bulk moved to Go 1.12 and things aren't given attention. So I'm going to re-apply "release-blocker" to this to protect it from bulk moves. Again, this doesn't need to be in Go 1.11 if you don't want it. It just needs to be decided by a human one way or another for Go 1.11 because a human spent the time to mail a CL.
