### ISSUE TITLE
pointer thread unsafe

### ISSUE THREAD

**Issue by a965331268** [golang/go#23220]
```
type Point struct {
	X int
	Y int
}

func main() {
	var p *Point = nil
	test := true
	go func() {
		for test {
			if tmp := p; tmp == nil {
				p = &Point{}
			}
		}
	}()
	go func() {
		for test {
			if tmp := p; tmp != nil {
				p = nil
			}
		}
	}()

	n := 0
	for test {
		n++
		fmt.Printf("test%v....\r\n",n)
		time.Sleep(1000 * time.Millisecond)
	}

	fmt.Printf("test fail")
}
```
Normal should be constant output
test1
test2
........

But only test1 output, the program hung up, there is no response
The assignment of the pointer is the most basic operation, this should be thread-safe to meet the period
But this test has not been able to

**Comment by a965331268** [comment]
test environment： windows 10 / golang 1.92

**Comment by davecheney** [comment]
I am sorry but this is not a bug for the following reasons.

1. This program has a data race and as such it’s output is undefined.
2. Your program busy loops, each of your goroutines will monopolise a cpu core without interruption. Depending on the environment you run this program this could cause starvation and the result you see. 

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by a965331268** [comment]
This program does not fill my CPU, if the pointer into int, there is no problem
`func main() {
	var p int = 0
	test := true
	go func() {
		for test {
			if tmp := p; tmp == 0 {
				p = 1
			}
		}
	}()
	go func() {
		for test {
			if tmp := p; tmp != 0 {
				p = 0
			}
		}
	}()

	n := 0
	for test {
		n++
		fmt.Printf("testing%v....\r\n",n)
		time.Sleep(1000 * time.Millisecond)
	}

	fmt.Printf("test fail")
}`

**Comment by davecheney** [comment]
Your program has a data race, it’s output is undefined. Build your program with the -race flag to see the race. This link has more information on the race detector,  https://blog.golang.org/race-detector  

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

As this is not a bug and the issue is closed I am restricting further comments on this issue. 

Please see https://golang.org/wiki/Questions for good places to ask questions.
