### ISSUE TITLE
in (p *struct) func, p == nil

### ISSUE THREAD

**Issue by RainstormQing** [golang/go#23243]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.9.2 windows/amd64`

### Does this issue reproduce with the latest release?
i don't know.

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
https://play.golang.org/p/DgrxKrWq3OM

### What did you expect to see?
  p == nil: false
  hello, 123
  p == nil: false
  hello, 123

### What did you see instead?
  p == nil: false
  hello, 123
  p == nil: true
  panic...

**Comment by bradfitz** [comment]
You were just using reflect wrong. You were making an alloacating a new `*MarkXLVI` (which has a default value of `nil`) instead of a `MarkXLVI` and gettings its address from `reflect.New`. See the docs on `reflect.New`.

You probably meant to do https://play.golang.org/p/uuKbKe3KrD1

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by RainstormQing** [comment]
thanks
