### ISSUE TITLE
doc syntax error

### ISSUE THREAD

**Issue by rookiejin** [golang/go#23252]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
v1.9.0

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

I found a doc syntax error , with package net/http
client.go 

### What did you expect to see?
A Client is a HTTP client.

### What did you see instead?
A Client is an HTTP client.

pull request is https://github.com/golang/go/pull/23250

**Comment by dominikh** [comment]
The letter `H` can be pronounced either /heɪtʃ/ or /eɪtʃ/, with the latter being the recommended way in Great Britain, and the common way in most of the US. Whether the `a` or the `an` article is used isn't determined by the spelling of a word, but its pronunciation. For example, it is `an hour`, because the `h` in `hour` is silent. Similarly, the popular way of pronouncing HTTP requires using `an`, not `a`.
