### ISSUE TITLE
cmd/go: can't handle relative TMPDIR

### ISSUE THREAD

**Issue by cherti** [golang/go#23264]
It seems like go build is not able to handle non-absolute `TMPDIR` and fails to build instead.

### `go version`
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/tmppath/go-build325593383=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
```
#!/bin/bash

# prepare testsetup
workdir=$(mktemp -d)
echo "Working in $workdir"
demofile=$workdir/gopath/src/a/demo.go
GOPATH=$workdir/gopath
mkdir -p /$workdir/gopath/src/a/
mkdir -p /$workdir/tmpfoo


cat > $demofile <<EOF
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
EOF


# starting the tests

cd $workdir
echo 'This will succeed (1)'
go build a  # this will succeed
echo 'Yep it did (1)'

TMPDIR=$workdir/tmpfoo
echo 'This will succeed (2)'
go build a  # this will succeed
echo 'Yep it did (2)'

cd $workdir
TMPDIR=tmpfoo
echo 'This will fail (3)'
go build a  # this will fail, although the directory is present
echo 'Yep it did (3)'
```

### What did you expect to see?
`go build` (3) in script above succeed as well as (1) and (2)

### What did you see instead?
`go build` (3) in script above failing.

**Comment by ianlancetaylor** [comment]
I'm not sure this is something we want to worry about supporting.  It seems simple enough to not do that.  Do most Unix tools support a relative `TMPDIR`?

**Comment by Merovius** [comment]
I think if this is not supported, we should at least provide a more useful error message (the current error message is something along the lines of `could not create $WORK/src/a/a.a: No such file or directory` which took us a while to figure out).

**Comment by davecheney** [comment]
This sounds like a good idea, if $TMPDIR doesn't fit through
https://godoc.org/path/filepath#IsAbs the go tool (or compiler, or both?)
should quit early with a reasonable error.

**Comment by Merovius** [comment]
I started adding this, but it doesn't reproduce anymore on tip, presumably because of the build cache changes. Some go commands still fail, if TMPDIR does not exist, even if they shouldn't use it at all (like `go version`) or if they seemingly don't actually need/use it (`go build` doesn't seem to actually write anything there anymore). There might still be places where this problem persists, so we might still add the check.

I think *supporting* a relative TMPDIR in the go tool would be as simple as erroring out: We can just call filepath.Abs on what os.TempDir returns to get an absolute path and use that. So I sent [a CL](https://go-review.googlesource.com/c/go/+/85596) to that effect.

I tried some of the POSIX interfaces to create temporary files and they all seem to do the same thing as Go in that regard: Use it just like /tmp and return a relative path. Meaning Go is consistent here with POSIX and that any C tool with a similar case (calling chdir(1), potentially in a child process). We *could* also consider doing that in os.TempDir directly, eliminating this problem in all Go code, but I'm not sure it's actually always the right thing to do.
