### ISSUE TITLE
net/http: should get "ok" but get no response

### ISSUE THREAD

**Issue by AnotherGoogleFan** [golang/go#23336]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64
go version go1.9.2 windows/amd64
both got the same problem

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
one is windows:
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoProject
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

one is linux:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/GoProject"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build038803651=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
code is simple enough:
```
package main

import (
	"context"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/anotherGoogleFan/log"
)

func main() {
	mux := http.NewServeMux()
	mux.Handle("/video/upload", http.HandlerFunc(UploadVideo))
	srv := &http.Server{
		Addr:    ":8848",
		Handler: mux,
	}
	// 如果接收到关闭信号(如 kill -2)则进行graceful shutdown
	go gracefulShutdown(srv)

	// service connections
	if err := srv.ListenAndServe(); err != nil {
		log.Fields{
			"port": "8848",
			"err":  err.Error(),
		}.Error("unexpected service stop")
		return
	}
}

func gracefulShutdown(srv *http.Server) {
	stopChan := make(chan os.Signal)
	signal.Notify(stopChan, os.Interrupt, os.Kill)
	<-stopChan
	log.Info("receive shutdown signal. Ready to exist")
	defer log.Info("program exists")
	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
	srv.Shutdown(ctx)
}

func UploadVideo(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "only post allowed", http.StatusMethodNotAllowed)
		return
	}

	http.Error(w, "ok", http.StatusOK)
}
```

### What did you expect to see?
I post a file 
![uploadwithnoresponse](https://user-images.githubusercontent.com/6881899/34571156-bbcc69ee-f1a8-11e7-87b6-4bc402ac3fc9.png)
with chrome plugin postman. I should get the response "ok".

### What did you see instead?
No response.

**Comment by mvdan** [comment]
Please see https://github.com/golang/go/wiki/Questions for a more appropriate place to ask questions. I don't see a specific bug report here - just a program that isn't doing what you wanted it to do.

If there is one, please clarify and give a short, concise program to reproduce it.

**Comment by brenol** [comment]
This issue seems to happen in Windows only (I'm using Windows 10) specifically in POSTMAN. I tested with a small file first (~3 bytes) and did not repro. Using a bigger one (over ~700KB) and I was able to reproduce this one.

Did not see it happen with curl (even when doing the request with the same headers as Postman). 127.0.0.1 does not suffer from this. 

This issue did not happen in Linux (Ubuntu 17.10) using Postman.

Seems something to do with Postman + Windows but I was unable to pinpoint it. 

Minimal repro: https://play.golang.org/p/UQ6AVD5Lqlj
It seems like sending any file with over 700KB via Postman (when using Windows) to the webserver makes the connection be cut out but I don't believe this is a Go issue as with curl it works correctly.

Seems to me Postman is doing something with the connection.

Tests were made using Go1.9.2/Windows

**Comment by KataKonst** [comment]
You need to read the body.  From what i see it exists a limit for unread request body data.
`// maxPostHandlerReadBytes is the max number of Request.Body bytes not
// consumed by a handler that the server will read from the client
// in order to keep a connection alive. If there are more bytes than
// this then the server to be paranoid instead sends a "Connection:
// close" response.
//
// This number is approximately what a typical machine's TCP buffer
// size is anyway.  (if we have the bytes on the machine, we might as
// well read them)
const maxPostHandlerReadBytes = 256 << 10`

A quick solution for will code can be 
`func UploadVideo(w http.ResponseWriter, r *http.Request) {
	io.Copy(ioutil.Discard, r.Body)
	defer r.Body.Close()
	if r.Method != http.MethodPost {
		http.Error(w, "only post allowed", http.StatusMethodNotAllowed)
		return
	}

	http.Error(w, "ok", http.StatusOK)
}`
