### ISSUE TITLE
net: Dial is slow on localhost

### ISSUE THREAD

**Issue by levrik** [golang/go#23366]
See https://github.com/golang/go/issues/23366#issuecomment-374397983 for more details!

### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

```go
now := time.Now()
net.Dial("tcp", "localhost:3000")
fmt.Println(time.Since(now))
```

This code outputs around 1s.
When replacing `localhost` with `127.0.0.1` it takes around 2ms, sometimes also <1ms.
`google.de:80` is around 60ms.

Is this expected to take so much longer with `localhost`? Took me several hours to find out that this was the root cause of multiple issues in my application.

**Comment by davecheney** [comment]
How fast is it if you dial 127.0.0.1:3000 ?

**Comment by davecheney** [comment]
Oh, sorry, you already answered this. 

I don’t think there is anything that can be done, localhost is a dns name so it goes through the usual dns lookup channels. 

Do you have access to a machine on a different network or with a different networking stack? Can you try to get some comparison results?

**Comment by levrik** [comment]
@davecheney As I said `google.de:80` is working fast (50ms) so I don't think it's an DNS issue.
I will continue to investigate.

**Comment by levrik** [comment]
@davecheney Just tried under macOS. 2ms for `localhost:3000` and 220µs for `127.0.0.1:3000`. Maybe an Windows issue?

**Comment by bradfitz** [comment]
Ephemeral port exhaustion maybe?

**Comment by davecheney** [comment]
My gut says a timeout due to a dns server refusing to looking "localhost"
or balckholing the response.

**Comment by agnivade** [comment]
@levrik - Perhaps you can write a similar program in a different programming language and test it in the same box ? That will eliminate whether its an issue with your networking stack or with Go.

**Comment by davecheney** [comment]
That's a great idea. Another option, which might prove cheaper if it is
conclusive is use `ping` or something and time (with a stopwatch, unless
ping supports a one shot mode on windows) how long it takes for the first
line to appear.

**Comment by as** [comment]
>(with a stopwatch, unless ping supports a one shot mode on windows)

`ping -n 1 localhost`

**Comment by levrik** [comment]
@davecheney @agnivade Let me try later this evening.

**Comment by levrik** [comment]
Sorry for not responding.
Just tried a ping to localhost. Took below 1ms.

**Comment by kkinnunen** [comment]
My connections were taking exactly 1s each with
* dialing to localhost:port
* listening on tcp, localhost:port

Worked around with using dialing and listening on "tcp", 127.0.0.1:port

net.Listen network (tcp, tcp4) and address of ":port", "localhost:port", "127.0.0.1:port" seem affect the outcome (to my adhoc testing). For example: 
* dialing to localhost:port
* listening on "tcp", ":0" -> fast
* listening on "tcp4", ":0" ->slow

go version
go version go1.10 windows/amd64

**Comment by ewxrjk** [comment]
I encountered the same issue, and I've done some digging. The first clue was that if I tried to connect to a port that has no listener at all the delay was 2 seconds, not 1 second.

The delay isn't in the name lookup. But the results of the name lookup do matter: here, `localhost` results in two addresses, `::1` and `127.0.0.1`. In this case `net.Dial` attempts to connect to `::1` first and `127.0.0.1` second.

The delay arises from failed connection attempts. Specifically, [the call to fd.pfd.ConnectEx](https://golang.org/src/net/fd_windows.go#L115) takes almost exactly a second when it fails (for any address, not just local ones). You can see this by modifying the implementation to print before/after timestamps.

In the `localhost` case, if you're listening on both IPv4 and IPv6, then it succeeds immediately. If you're listening on just IPv4 then you get failed connection attempted and a 1s delay followed by success. If you're listening on neither then you get two failed connection attempts and thus a 2s delay.

 [The same issue affects PuTTY](https://gist.github.com/ewxrjk/f3f023727300773b8329677fed46ee56). `tcpdump` reveals that what's going on is that Windows apparently does not believe the RST bits it gets back from the target of the connection (even if, apparently, it is itself the target) and keeps trying for up to a second.

I doubt that Go can do anything about this. For application developers the answer is to bind to both IPv4 and IPv6 addresses, so that it doesn't matter what connection order clients use.

**Comment by levrik** [comment]
Ah, that's really interesting.
The issue I have here is that I'm not in control of the target servers. I built a development proxy which also proxies websockets besides normal HTTP. If you use, for example, create-react-app which uses sockjs for the connection to its live reload server it will fall back first to eventsource and after that to polling. that is caused by some internal dynamic timeout that is calculated based on a normal HTTP call (which is fast). I think it is fine to just use 127.0.0.1 in that case, at least for now.

**Comment by levrik** [comment]
@agnivade Oh sorry. Completely forgot to anwser. Yes. Maybe it'd be an idea to put information about that into the Go docs?

**Comment by agnivade** [comment]
A PR will be much appreciated.

/cc @bradfitz

**Comment by gh67uyyghj** [comment]
Godammit, my mind was going to explode because of the slow responses and I couldn't believe this can be a bug in golang itself

**Comment by inliquid** [comment]
Got same here with `http` package and some profiling tests, f.e. this code seemed broken and program just hanged until _localhost_ was changed to _127.0.0.1_

```golang
func main() {
	ctrl.Setup()

	go func() {
		if err := http.ListenAndServe("localhost:3000", &poms.GZipServer{}); err != nil {
			log.Fatalln("Error listening:", err)
		}
	}()

	f, err := os.Create("cpu.prof")
	if err != nil {
		log.Fatalln("Can't create profiler dump file:", err)
	}

	pprof.StartCPUProfile(f)

	for i := 0; i < 1000; i++ {
		if _, err := http.Get("http://localhost:3000/api/purchaseOrders/1"); err != nil {
			log.Println("Error sending request:", err)
		}
	}

	pprof.StopCPUProfile()
}
```

Note, that in this example both listener and client supposed to bind to same host/interface: ___localhost___, and there is no way to get an idea of what is happening. No errors, no feedback on failed _[::1]_ attempts, what so ever. After replacing _localhost_ with _127.0.0.1_ everything worked.

I expect to receive some errors back from `Get` when there are timed out or refused connect attempts on different interfaces, including attempts to connect on IPv6/IPv4.

**Comment by as** [comment]
@inliquid you have a transactional race in your program. 

There is no guarantee that by the time your listener goroutine resolves the host part of the socket and starts the `http.ListenAndServe` logic, your client hasn't already tried 1000 times to connect and failed.

I wouldn't be surprised if changing it to the IPv4 address made this process quicker, allowing your server to listen before the clients started clienting.

Another question is how you determine success. Nothing happens if the client relieves no error. 

I suggest creating your own listener and attaching it to the http server in two separate steps. This would allow you to implement your own `net.Listener` and `net.Conn` for the connections and add whatever debugging output you want.

**Comment by inliquid** [comment]
@as well, in fact I don't have race problem. I _could_ have such problem as you suggested, but I don't. In there were - I would see an error as a result. I did a lot of experiments before realized what is happening, including running server and client in 2 separate processes and emulating http server to see is `http.Get` even working. Problem is that `http.Get` returns nothing in this case.

**Comment by ewxrjk** [comment]
@inliquid there is not much Go can do about the connect issue. It is just reflecting the behavior of the underlying platform. The best strategies are either (1) bind to both loopback addresses, or (2) bind to just one of them but also only connect to that one.

In general binding to names rather than addresses is risky: if the name resolves to multiple addresses then it will bind to only one of those addresses. There's already a warning about this under [net.Listen](https://golang.org/pkg/net/#Listen).

**Comment by inliquid** [comment]
I agree in general, however, I think it;s clear that _localhost_ in Windows is _exceptional_ case and since it has nothing to do with DNS or _hosts_ I think it must be treated in exceptional manner, explicitly, avoiding such situations were program behavior may change unexpectedly. Maybe just make "localhost" == "127.0.0.1", or even deny "localhost" and require explicit address, smth like
- "localhost_v4" == "127.0.0.1"
- "localhost_v6" == "[::1]"

**Comment by IndieRobert** [comment]
Confirm issue here. Go 1.9. Replacing with "127.0.0.1" fixes it. Useless to say, I've lost quite some hours on that one. It's okay, you guys spend many more maintaining this overall great go code.

Now, let me just tell you how I see things. 

This is a beginner bug. This kind of bugs denote a too-complex or spaghetti-like code that's badly tested either by a lack of ownership, or bad methods.  In my opinion, you should

1. fix the issue
2. reflect strongly on what are the underlying reason beginner-type of bugs like this can still be introduced in your code. If you are a maintainer of this module, you have to be aware you either had bad luck (it happens) or you have beginner-type of bugs in your code regularly and you should improve your skills. 

This module dial a tcp connection and this bug is related with one of the simplest case: dial localhost. If this is not a beginner bug, then what is.

Overall, it smells like a full-of-jumps-type-of-code bug. By jumps, I mean return, continue, break, defers. None of you really understand anymore what is executed and when in a clear and precise way. Please note that traditional functional languages doesn't allow for jumps. I strongly advise you to remove all sort of jumps in your code. Stop thinking code as a list of instructions, start thinking in terms of list of expressions. Add indentations which will show you the complexity and structure of your systems.

The other source of such bugs is battalion of special cases. The best way to avoid complexity I've found is to simply reject it. If the code is too complex, it should not be shipped. Simplify until the code is simple enough to be shipped at all. 

Finally, you should reflect on your testing abilities. You cannot catch this bug using unit tests, I don't think so. I mean you would have to be lucky and notice the delay. How much of your systems are basically well tested by unit tests anyway? I'm saying that because I've seen developer thinking that once a code passes unit tests, the code is tested. Nah, this is not that easy fools. Everything you write must pass through an extensive manual testing phase, done by multiple programmers if possible. Now days, programmers tend to think unit tests are better at catching bugs than manual testing. This is wrong. Manual testing will catch way more bugs than unit tests. You will not replicate in unit tests the 536 thing a human being can do in 2 hours to a piece of code. You will only write 13 unit tests.

I also advise to insert Assert statements right into the module code as the validity of the code will then be tested every time it runs instead of every time it builds. Note the inputs are fixed at build time (unit tests) while they are not fixed a runtime which allow for better testing.

Hopefully that's constructive.

**Comment by EllieLockhart** [comment]
Is this still an issue of concern, and if so do we have potential courses of action? Is this a situation where at least a note in documentation should be made for the time being?

**Comment by ewxrjk** [comment]
@EllieLockhart the root cause is in Microsoft's TCP stack and only they can fix it.

There are some possible application/operator responses and they could be documented in https://golang.org/pkg/net/ (or elsewhere).
* For clients, dial `127.0.0.1` instead of `localhost`. This isn't a general fix but as a tactical response to the problem I suspect it would be widely acceptable.
* For servers that want to listen to loopback only, listen on both `::1` and `127.0.0.1`, if the local platform supports both.

**Comment by inliquid** [comment]
@ewxrjk LOL. Also you can ask Microsoft to "fix" backslash to slash as the path separator.

There is nothing to "fix" from Microsoft part, its stack behaves as expected. The problem is Go standard library which denies to treat this behavior in a right way not forcing users to apply hacks and workarounds.

**Comment by artemsnisarenko** [comment]
I'll just leave this here https://github.com/openjdk/jdk/blob/be4f25b0c885a6405b484e4035b30005311a2802/src/java.base/windows/native/libnio/ch/Net.c#L240-L243

**Comment by qmuntal** [comment]
> I'll just leave this here https://github.com/openjdk/jdk/blob/be4f25b0c885a6405b484e4035b30005311a2802/src/java.base/windows/native/libnio/ch/Net.c#L240-L243

Thanks for the pointer @artemsnisarenko. I've submitted CL 23366 based on that.
