### ISSUE TITLE
database connectoion reuse unexpected

### ISSUE THREAD

**Issue by zhouchengxiang** [golang/go#23396]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/workspace/go"
GORACE=""
GOROOT="/usr/local/go1.9"
GOTOOLDIR="/usr/local/go1.9/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build208949851=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
conn, err := DB.Conn(context.Background())

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

when the life time expired, conn should created correctly

### What did you see instead?
get ErrBadConn

**Comment by davecheney** [comment]
I'm sorry, you have not included enough information in this report to reproduce the problem. I strongly suggest asking a question on one of the support forums, https://golang.org/wiki/Questions for good places to ask questions. Iff it turns out there is a bug in Go they will direct you to raise an issue. You may reference this issue if it helps.
