### ISSUE TITLE
why don't support `switch type`

### ISSUE THREAD

**Issue by dongshimou** [golang/go#23530]
```
func getDouble(v interface{})float64{
	switch t,_:=v.(type){
	case int,int8,int16,int32,int64,uint,uint8,uint16,uint32,uint64,float32:
		return float64(t)
	case float64:
		return t;
	//test
	default:
		return 0;
	}
}
```
case int :
case int8 :
...
to many...

**Comment by mvdan** [comment]
Are you proposing a change to the language? If so, this is missing a lot of information.

For example, in that `return float(t)` statement, what exactly is the type of `t`?

**Comment by dongshimou** [comment]
i mean...
normal `switch`
```
str:="a"
switch str {
case "a","b":
//code
case "c","d":
//code
}
```

but. 
it don't work in:
```
func getDouble(v interface{})float64{
	switch t,_:=v.(type){
	case int,int8,int16,int32,int64,uint,uint8,uint16,uint32,uint64,float32:
		return float64(t)
	case float64:
		return t;
	//test
	default:
		return 0;
	}
}
```

only
```
func getDouble(v interface{})float64{
	switch t,_:=v.(type){
	case int:
		return float64(t)
	case int8:
		return float64(t)
	//other case...
	//case int16
	//case int32

	case float64:
		return t;
	//test
	default:
		return 0;
	}
}
```

**Comment by mvdan** [comment]
Yes, I understand what you're trying to say. But these two switches are vastly different. You can't collapse multiple type cases into a single case because then the variable `t` no longer has any possible valid type.

If you would like to suggest a change to the language to allow for this, it would need to be a proposal (see the link I shared above). The proposal would also need to explain how the language or compiler would actually make it work. For example, what type would the variable have in one of these multi-type cases.

Alternatively, if what you're trying to do is ask questions, see https://github.com/golang/go/wiki/Questions.
