### ISSUE TITLE
testing: example output whitespace trimming can be confusing

### ISSUE THREAD

**Issue by josharian** [golang/go#23542]
Consider the [Example for filepath.Split](https://godoc.org/path#Split).

The code is:

```go
fmt.Println(path.Split("static/myfile.css"))
fmt.Println(path.Split("myfile.css"))
fmt.Println(path.Split(""))
```

The output is:

```
static/ myfile.css
 myfile.css
```

Given that there are three `fmt.Println` calls, it seems to me that there really ought to be three lines of output.

(And if we decide that we don't want to or can't change example output whitespace trimming, we should at least tweak this example so that the last line of output contains non-whitespace, e.g. by prefixing each output line with an asterisk or number.)

**Comment by mvdan** [comment]
Perhaps another solution would be to not leave the empty line print at either end, so that it could not be trimmed. Leaving it in the middle, for example.

**Comment by awoodbeck** [comment]
I could take this one.  I prefer mvdan's suggestion unless we'd like to be more explicit with the whitespace.

Output would of course look like this:
```
static/ myfile.css
 
 myfile.css
```

**Comment by rsc** [comment]
It seems like the simplest fix is to swap the second and third line.

**Comment by awoodbeck** [comment]
This simple change exposed a limitation in example output testing.  The example works if the `fmt.Println(path.Split(""))` line is either the first or third line in the example, but not the second line.  Its single whitespace character and new line are stripped before comparison if it's on either end of the output, but not if it's in the middle (see the example output below).

Adding a whitespace character in the example output doesn't help either because each line is trimmed before being joined with a new line character.

```
--- FAIL: ExampleSplit (0.00s)                            
got:                                                      
"static/ myfile.css\n \n myfile.css"                      
want:
"static/ myfile.css\n\n myfile.css"
```

**Comment by josharian** [comment]
Possibly related: https://github.com/golang/go/issues/6416

**Comment by awoodbeck** [comment]
@josharian I'm making certain to preserve the trailing space on the second line in the example (i.e., omit `gofmt`), two spaces after the `//` since the first space is always removed when building the ast.  But I don't think it will matter either way since [all trailing spaces are stripped](https://github.com/golang/go/blob/master/src/go/ast/ast.go#L127) when parsing the example output.

The unique aspect about this example is the single whitespace character in the middle line as opposed to a blank line.  Stdout will always display the whitespace character but I cannot see a way to preserve the whitespace character in the example output.

**Comment by awoodbeck** [comment]
Here's a proposed compromise:

Code:
```
fmt.Println(path.Split("static/myfile.css"))
fmt.Println(path.Split("myfile.css"))
fmt.Printf("%q", fmt.Sprintln(path.Split("")))
```

Output:
```
static/ myfile.css
myfile.css
" \n"
```

This passes but it may convolute the last example.

**Comment by josharian** [comment]
I dunno. It'd be nice for all three to be constructed similarly. I tried this, but it's even worse:

```go
package main

import (
	"fmt"
	"path"
)

func main() {
	for _, s := range []string{"static/myfile.css", "myfile.css", ""} {
		file, dir := path.Split(s)
		fmt.Printf("path.Split(%q): file=%q dir=%q\n", s, file, dir)
	}
}
```

I can't say I have any better ideas at this point.

**Comment by awoodbeck** [comment]
Here's another suggestion that similarly constructs all 3 examples and passes.
```go
out := func(args ...interface{}) {
	fmt.Printf("%q\n", fmt.Sprintln(args...))
}

out(path.Split("static/myfile.css"))
out(path.Split("myfile.css"))
out(path.Split(""))
```

Output:
```
"static/ myfile.css\n"
" myfile.css\n"
" \n"
```

**Comment by awoodbeck** [comment]
Any opinion on my last example?  I will submit it as a CL if it's received better than the current example.

**Comment by josharian** [comment]
On m phone, but: it is nice for examples to be copy-paste friendly. In particular, having a line that reads:

file, sir := path.Split(x)

with useful mnemonic variable names seems valuable. And then we could avoid nested fmt calls and a code golf flavor.

**Comment by irbekrm** [comment]
Hey folks, I just did a Go contributors' workshop at London GopherCon and was looking at this as potentially my first issue to try to contribute.
Has there been any further decision about this issue?

**Comment by mvdan** [comment]
@irbekrm I don't think there was a consensus so far; I'd say pick a solution you like (or your own solution), and we can always discuss it on the CL.

**Comment by irbekrm** [comment]
Thanks @mvdan
