### ISSUE TITLE
cmd/compile: spurious error when ~ is used as an infix operator

### ISSUE THREAD

**Issue by davecheney** [golang/go#23587]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9.3

### Does this issue reproduce with the latest release?

Unknown

### What operating system and processor architecture are you using (`go env`)?

Go playground

### What did you do?
```
package main

func main() {
	var a bool
	a = a ~ a
}
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

 prog.go:5:8: bitwise complement operator is ^

### What did you see instead?

 prog.go:5:8: bitwise complement operator is ^
 prog.go:5:8: invalid operation: a ^ a (operator ^ not defined on bool)

**Comment by odeke-em** [comment]
Thank you @davecheney for this report and it is great to see you here in the new year!

@griesemer I see that in the scanning phase we recognize that people commonly use the bitwise complement '~'  in other languages, and perhaps intentionally fallthrough to continue lexical analysis as we are doing in the context of the proper operator in Go `^`
https://github.com/golang/go/tree/master/src/cmd/compile/internal/syntax#L232

However, in this context I believe that the entire operation is invalid irrespective of the types of operands i.e, even if it were `2 ~ 2`, this still doesn't make sense since `~` is a unary operator.
Perhaps we could improve the error and only fallthrough as we are doing, if we detect a single operand on the right of the `~`?

**Comment by griesemer** [comment]
The scanner doesn't know about context (are there one or two operands) and thus cannot make that distinction. One could pass through the `~` and make the distinction in the parser, but that seems overkill: The reason for this error message is mostly historic. Go doesn't have a `~` symbol, so maybe it should just complain about an invalid character.

go/types says: `illegal character U+007E '~'`.

**Comment by davecheney** [comment]
Hey all, thanks for looking into this issue. I'm less interested in the first line, and more interested in the second
```
prog.go:5:8: invalid operation: a ^ a (operator ^ not defined on bool)
```
As the code sample never mentions ^

**Comment by griesemer** [comment]
@davecheney Yes, thanks for pointing that out. During lexical analysis, the scanner assumes that if a user typed `~` they actually meant `^`; so it complains but then quietly continues with `^`. That works great if the assumption was correct, but it fails miserably otherwise. Which is why I am thinking that perhaps the compiler should just complain about `~` not being a valid token. The existing behavior was simply brought over from Ken Thompson's original compiler which used to be a C compiler. I suspect this may have been a common error for him to make, hence the current code.
