### ISSUE TITLE
x/net/publicsuffix: publicsuffix.EffectiveTLDPlusOne fails on "*.amazonaws.com"

### ISSUE THREAD

**Issue by llonchj** [golang/go#23671]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64 osX 10.13.3

### What did you do?

https://play.golang.org/p/OoMumbHr1Ou

publicsuffix: cannot derive eTLD+1 for domain \"ec2-34-205-106-31.compute-1.amazonaws.com\"

### What did you expect to see?

exit code 0, not panic

### What did you see instead?

Checking amazonaws.com - s3-website-us-east-1.amazonaws.com...
panic: publicsuffix: cannot derive eTLD+1 for domain "s3-website-us-east-1.amazonaws.com"

goroutine 1 [running]:
main.main()
	/tmp/sandbox037353932/main.go:17 +0x3c0

**Comment by llonchj** [comment]
`cof4srv.alwaysdata.net`, `k12.wa.us` fails too

**Comment by nigeltao** [comment]
I believe that this is working as intended.

(Note that the panic in the example program is not from the library per se, it is from the caller of the library, "package main").

https://publicsuffix.org/list/public_suffix_list.dat contains these lines (amongst others):

com.au
com
*.compute-1.amazonaws.com
s3-website-us-east-1.amazonaws.com

While only one of these, "com", is a TLD (top level domain), all of these are an eTLD (effective TLD), because that's what that list is: a "public suffix" is another name for an eTLD.

An eTLD+1 (spelled EffectiveTLDPlusOne in Go) is an eTLD with one extra label. For example, "google.com" and "google.com.au" are both an eTLD+1, based on the TLD values "com" and "com.au" respectively.

"google.com", "mail.google.com", "maps.google.com", "google.com.au" and "yahoo.com.au" are all domain names. The first three have the same eTLD+1 value: "google.com". The last two have different eTLD+1 values: "google.com.au" and "yahoo.com.au".

What is the eTLD+1 of "com" or of "com.au"? There isn't one. In both cases, the whole string value is an eTLD, so there is nothing extra to derive the "+1" in "eTLD+1".

In your example program, you're asking for the eTLD+1 of "s3-website-us-east-1.amazonaws.com". Again, there isn't one, because it's already an eTLD (without the "+1"). "s3-website-us-east-1.amazonaws.com" is explicitly in that list.

The bug report also mentions "ec2-34-205-106-31.compute-1.amazonaws.com", even though that's not in the https://play.golang.org/p/OoMumbHr1Ou program. Again, that domain is an eTLD, because of the star in "*.compute-1.amazonaws.com", so there is no eTLD+1.

Similarly, "k12.wa.us" is also in the list.

As for "cof4srv.alwaysdata.net", it seems that the Go package needs to be re-generated to pick up https://github.com/publicsuffix/list/commit/836815ae8d9707e5d11e3a64c09259de3c962a28 that was submitted a month ago. I have just sent out that re-generation as https://go-review.googlesource.com/#/c/net/+/91836
