### ISSUE TITLE
x/net/http2: invalid Connection request header

### ISSUE THREAD

**Issue by suconghou** [golang/go#23699]
I meet the error and found the issue here 

https://github.com/golang/go/issues/15422

and the source code

https://github.com/golang/net/blob/6972930/http2/transport.go#L626-L634

as it said the `keep-alive` is valid 

but why it is case-sensitive , 

many request failed due to `Keep-Alive` header 

does HTTP/2 RFC say it  must be case-sensitive ?

**Comment by bradfitz** [comment]
What is your issue?

How did you get this error?

HTTP/2 doesn't have connection-level headers, like the other bug says.

**Comment by suconghou** [comment]
@bradfitz   I made a proxy for some urls

example code  https://gist.github.com/suconghou/50dd30df10bd6faa2abe1805afe3216f 

notice it works well then you use chrome , because chrome send `keep-alive` header 

but some other software and services may send `Keep-Alive` header  , eg: cloudflare , IE ( https://stackoverflow.com/questions/9650236/how-to-send-lower-case-keep-alive-header-through-httpwebrequest/30071784  the answers mentioned IE  )

use `curl -H "Connection:Keep-Alive" http://127.0.0.1:8080/` simulate this behavior

**Comment by suconghou** [comment]
@bradfitz 

please replace this 
```
(v != "" && v != "close" && v != "keep-alive") 
```
with 
```
(v != "" && v != "close" && v != "keep-alive" && v != "Keep-Alive") 
```

in `checkConnHeaders` function

**Comment by szuecs** [comment]
Doesn't it makes sense to handle this transparently?
I think Go should just drop the Connection header if H2 does not support Connection headers.
I see the same problem if I use plain `http.Transport.RoundTrip(req)` in case `Connection: Keep-Alive` is set and the backend called specified in the http.Request supports H2.

For me it sounds really weird to argue you should use `httputil.ReverseProxy`, instead of fixing this.
