### ISSUE TITLE
cmd/go: new cgo protections mix up CFLAGS and LDFLAGS from pkg-config

### ISSUE THREAD

**Issue by jeddenlea** [golang/go#23737]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.4

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Linux

### What did you do?
Tried to build with cgo, like
```
#cgo pkg-config: foo
```

Within our contrived environment, we'll see,
```
$ $PKG_CONFIG --cflags foo
-pthread -I... -I... -I... -I... -I...
$ $PKG_CONFIG --libs foo
-L... -L... -L... -lfoo -lbar -Wl,--export-dynamic ...
```

### What did you expect to see?
The linker flag `-Wl,--export-dynamic` there is rightfully rejected.  It ought to be allowed with the `CGO_LDFLAGS_ALLOW` environment variable.

### What did you see instead?

`go build` returned an error,
```
go build ...: invalid flag in pkg-config --cflags: -Wl,--export-dynamic
```
And, it may be built, but using `CGO_CFLAGS_ALLOW`, not `CGO_LDFLAGS_ALLOW`

I'll have a fix pushed shortly.

**Comment by raff** [comment]
I get a similar error with a package (LuaJIT) that does the following in order to link a *.a file:
`
#cgo LDFLAGS: ${SRCDIR}/../../../LuaJIT/LuaJIT/src/libluajit.a -lm -ldl
`

I was able to "fix" it by doing this, but it would be good if it was at least documented (also, I am wondering if there are any other cases if trying to pass non-flag parameters in CFLAGS/LDFLAGS):
`
#cgo LDFLAGS: -lm -ldl -L${SRCDIR}/../../../LuaJIT/LuaJIT/src -lluajit
`

**Comment by FiloSottile** [comment]
@raff yours seems like a separate issue, where this line is missing support for `.a` files:

https://github.com/golang/go/blob/104445e3140f4468839db49a25cb0182f7923174/src/cmd/go/internal/work/security.go#L91

I submitted a CL for that. https://golang.org/cl/92855

**Comment by ianlancetaylor** [comment]
Closing in favor of a general whitelist issue in #23749.
