### ISSUE TITLE
Can't link to static library anymore

### ISSUE THREAD

**Issue by wheelerlaw** [golang/go#23807]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.4 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
`GOARCH="amd64"`
`GOOS="linux"`

### What did you do?
`git clone https://github.com/wheelerlaw/go-memory-module.git`
`make`

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
On go 1.9.2 (same OS/arch), the file compiles with no problems. 

### What did you see instead?
I updated to 1.9.4, and I receive this error:
```
go build command-line-arguments: invalid flag in #cgo LDFLAGS: MemoryModule/build/MemoryModule.a
```

Project here: https://github.com/wheelerlaw/go-memory-module
I know this has something to do with https://github.com/golang/go/issues/23672, but it does not seem that `*.a` files are whitelisted (or if they are, it is not working).

**Comment by glycerine** [comment]
@wheelerlaw If you read through the entirety https://github.com/golang/go/issues/23672 and https://github.com/golang/go/issues/23749 you'll come to understand that this was an oversight that will be fixed in a shortly-to-be-released go1.9.5.  For `.a` files, the temporary workaround is to add this to your ~/.bashrc / current environment.
~~~
export CGO_LDFLAGS_ALLOW='.*\.a$'
~~~

**Comment by mvdan** [comment]
Closing as duplicate, like @glycerine pointed out.
