### ISSUE TITLE
spec: confusing example in map index expressions section

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#23895]
From [index expressions](https://golang.org/ref/spec#Index_expressions) section:
> An index expression on a map a of type map[K]V used in an assignment or initialization of the special form yields an additional untyped boolean value. The value of ok is true if the key x is present in the map, and false otherwise. 
```go
v, ok = a[x]
v, ok := a[x]
var v, ok = a[x]
var v, ok T = a[x] // <- This one. 4th example
```
It seems like 4th example is only valid when `T` is `bool`, which assumes that map have `bool` as element value type.

If this is correct, then `var v, ok T = a[x]` should be either `var v, ok bool = a[x]` or re-phrased in other way (perhaps even removed).

**Comment by yazsh** [comment]
Considering the map is declared as value type of V using T below is confusing.  I would either remove the example entirely or change it to V.  

I don't see the added value in it's inclusion with respect to map indexing so I am suggesting it be removed.


The both code snippets  below will not compile.  The top snippet because you can't store an int in a bool, the bottom because it considers ok an int which cannot be used in an if statement.
```
k := make(map[string]int)

var v, ok  bool = k["asdf"]
	
```

```
k := make(map[string]int)

var v, ok  int = k["asdf"]

if(ok){
	fmt.Println(ok)
	fmt.Println(v)
	}
```

**Comment by dotaheor** [comment]
I don't think it is much confusing. The type `T` is not  essential to be a `bool`, it can be any boolean type.
The 4th example make the cases completed.

**Comment by Quasilyte** [comment]
@dotaheor, I see now. You are right, thank you.

The `ok` type is not `bool`, but `untyped bool`. Makes sense then.

This, for example, compiles and executes as expected:
```go
	type mybool bool
	m := make(map[string]mybool)
	var v, ok mybool = m[""]
	fmt.Println(v, ok)
```
