### ISSUE TITLE
spec: no mention of "factored" import statements

### ISSUE THREAD

**Issue by mvdan** [golang/go#24011]
@josharian just mentioned them in https://github.com/golang/go/issues/23966#issuecomment-367425848:

> The current format appears to accept single and factored forms. goimports has moved to factored forms only.

I have no idea what it means. The only somewhat-official link I could find via google is https://tour.golang.org/basics/2:

> This code groups the imports into a parenthesized, "factored" import statement.

I can understand if the term "factored" doesn't belong in a formal spec. However, if that is a name that people tend to use for it - and given how the Go spec tries to be helpful with examples and notes for newcomers - I think it would be a good addition.

On the other hand, if this term should be avoided, it should be removed from the tour. In that case, I'd be curious to know how to call them. I assume "grouped imports" isn't an option, as that refers to imports within parentheses that have no empty lines in between them.

/cc @griesemer

**Comment by rsc** [comment]
It's an import block.

**Comment by mvdan** [comment]
That sounds more familiar to me, thanks - forgot to mention it in the issue. The spec doesn't explicitly mention it either, though.

Should the tour page be updated to mention import blocks instead?

**Comment by griesemer** [comment]
I think the tour is pretty clear: First of all the term _factored_  is in double quotes in the tour, making it clear that it's not really a formal term, but it also explains what it is: The `import` keyword is factored out from a sequence of import declarations, and moved in front of the grouped import declaration. It's the same pattern in elementary algebra: Instead of writing `a*b + a*c`, one can factor out the `a`, leading to `a*(b + c)`. Thus for imports: Instead of `import "b"; import "c";` one writes `import ( "b"; "c" );` - the factored form.

In any case, this is not an issue with the spec. If @josharian likes to use the term but doesn't define it enough, perhaps you should take it up with him? Closing.

**Comment by josharian** [comment]
Sorry to have caused confusion. I was on my phone and used the first word that sprang to mind to describe them.
