### ISSUE TITLE
x/vgo: don't allow cycles?

### ISSUE THREAD

**Issue by nilebox** [golang/go#24098]
The [blogpost about minimal version selection](https://research.swtch.com/vgo-mvs) mentions support for cyclic dependencies between modules.
While this is nice that MVS can easily resolve cycles, I am not sure if allowing them is a good idea.
Go doesn’t allow import cycles, why should `vgo` allow cycles between modules then?
Doesn’t that promote bad coding practices?

Also, the blogpost shows the dependencies between the same versions, i.e. `A1 <-> B1`. Such situation has a 'chicken and egg' problem: you can't release `A1` module until `B1` is released, and vice versa. You can probably tag an `A` git repo with `A1` tag with `go.mod` referencing a non-existing-yet `B1` version of the `B` module (not sure if `vgo` would allow that), but it seems fragile and hard to build and test before both `A1` and `B2` are released.

The more likely real-life scenario would probably look closer to something like this:
![cycle_complex](https://user-images.githubusercontent.com/6176360/36630414-15f6663e-19ba-11e8-8a75-c47b51407f40.png)
i.e. no actual cycle between `A1` and `B1`, but implicit cycle between `A` and `B` modules.
And I think it would solve the same problem that @rsc has stated as justification for cycles:
> Declaring this kind of cycle can be important when singleton functionality moves from one module to another. Our algorithms must not assume the module requirement graph is acyclic. 

I am still not sure if such tightly coupled separate modules is a good idea (why not just merge them into one module?), but at least it would mean no 'chicken and egg' problem for releasing process anymore.

**Comment by rogpeppe** [comment]
FWIW we have real repositories that have cycles between them. The cycles usually involve tests. A example is when a server implementation lives in one repo and its client in another. To test the client, its tests import the server so that they can verify properly that the client code runs against a real server. The API parameters live in a package in the client so that the client package can be imported without importing the heavyweight  server package.

Releasing is indeed fairly painful, and I think if I was doing this again, I'd avoid the cyclic repo dependency. Given that we use a git-commit-locked dependencies, the recipe for making a change looks something like:

    - make the change in the client repo.
    - update the server repo so that it works with the client repo.
    - commit the server repo and push to a feature branch, not master.
    - update client lock file to point to new server commit.
    - commit client repo and make a PR for that change (the PR tests pass because the dependency management too is able to pull commits from feature branches).
    - merge into client repo.
    - make a PR on the server repo that merges the feature branch and updates the lock file to point to the new client commit.
    - merge server PR
    - make a PR on the client repo that changes the lock file to point to the latest server master commit.
    - merge client PR.
    - delete feature branch in server repo.
    - breathe a sigh of relief that it's all over.

At this point both client and server lock files point to valid commits on each other and we can proceed as normal.

I think one could probably use a similar approach with vgo.

Thinking about it, I think the main reason this was a problem was that we were making incompatible changes. With major versions as separate import paths, things might be easier.

Knowing what I do now, I think a better approach would be to avoid importing the server code in the client at all and make the tests build the server as an entirely separate binary. That way you can easily  test the client code against different server versions too.

**Comment by nilebox** [comment]
@rogpeppe thanks for the real example. Since `vgo` doesn't support lock files, you would need to reference an unreleased `v0.0.0-20180208041248-4e4a3210bb54` feature branch commit, and the rest should be the same.

What I don't like about this recipe (apart from being very complicated) is that the version you tested is not the same you released, and potentially there could be more (untested) changes in between them.

**Comment by sdboyer** [comment]
Cycles are also used as part of a technique - not sure if it's explored in the blog posts - that allows you to safely (as vgo defines it) move a package out of one module and into another, without breaking existing importers.

**Comment by 4ad** [comment]
Cycles are a killer feature of vgo. One of the primary reasons you might want to use it.

**Comment by rsc** [comment]
Cycles are also important for expressing moments where a module pair must move forward together. See https://github.com/golang/go/issues/24301#issuecomment-377527249 for an example.
