### ISSUE TITLE
cmd/vet: error when returning `nil` inside an `if err != nil` clause

### ISSUE THREAD

**Issue by cgrushko** [golang/go#24141]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

version 1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

amd64, linux

### What did you do?

I mistakenly return `nil` inside a `if err != nil` clause, which hid a bug in my code. Since it almost never makes sense to return `nil` in such a case, I thought it'd be a nice `go vet` error.

func f() error {
	err := ....
	if err != nil {
		return nil
	}
	return nil
}

**Comment by mvdan** [comment]
This seems like it will bring quite a few false positives. Have you prototyped such a change, and seen what it finds in the Go tree?

**Comment by dgryski** [comment]
Seems like the title should be "returning `nil` inside `if err != nil`" instead of "returning `err` inside `if err != nil`".

**Comment by adamdecaf** [comment]
Here's a valid `return nil` from the stdlib. I agree this will bring a lot of false positives.

https://github.com/golang/go/blob/release-branch.go1.10/src/crypto/x509/root_darwin.go#L213-L225

**Comment by cgrushko** [comment]
This example is not what I suggest catching, because the if clause contains things other than `return nil`.

**Comment by mvdan** [comment]
Other reasonable scenarios come to mind, for example:

* Getting `io.EOF` but returning `nil`, because it was expected
* Funcs whose return type isn't error (perhaps obvious, but this issue does not clarify that)
* Expecting an operation to fail, thus returning a nil error when an obtained error is non-nil

And there's also the can of worms that is errors that are always nil. This kind of check probably belongs in a tool that gives a human suggestions, and not a linter that gives warnings that must be accurate.

**Comment by josharian** [comment]
cc @robpike for a final decision, but I think the likely false positives from this make it not a good fit for vet.

cc also @dominikh in general for all things that don’t make it into vet. :)

**Comment by robpike** [comment]
Fails the precision criterion of cmd/vet/README.
