### ISSUE TITLE
reflect: regression in Value.Addr().Elem() roundtrip

### ISSUE THREAD

**Issue by dsnet** [golang/go#24153]
Consider the following:
```go
type child struct{ Field string }
type parent struct{ child }

v := reflect.ValueOf(&parent{}).Elem().Field(0) // v is a child value
fmt.Println(v.Field(0).CanSet())                // Is child.Field settable? Yes.
v = v.Addr().Elem()                             // Perform roundtrip: v = *(&v)
fmt.Println(v.Field(0).CanSet())                // Is child.Field still settable? Maybe?
```
On go1.9, this printed:
```
true
true
```
On go1.10, this printed:
```
true
false
```
I find it very surprising that a round-trip reference/derefence would cause the exported Field to no longer be settable. It's not clear to me whether this is intended behavior or not.

\cc @mdempsky @ianlancetaylor

**Comment by dsnet** [comment]
Git bisect blames https://go-review.googlesource.com/66331.

The CL description seems to indicate that this is intended behavior:
> However, the way this was implemented allowed other operations to be
interspersed between the Field calls, which could grant inappropriate
access.

If this is intended, then for #24152 we'll need to fix the `json` package to not assume that `.Addr().Elem()` is side-effect free.

**Comment by mdempsky** [comment]
I would argue that reflect is working correctly in Go 1.10, and that json will need to fix its Addr/Elem roundtrip.

Rationale: Given

    v := &parent{}

it's legal to write

    (*v).Field

which maps to the reflect operations `v.Elem().Field(0).Field(0)` in your example.

However, it's not legal to write

    (*&(*v).child).Field

because `child` is not exported. Thus reflect should not allow `v.Elem().Field(0).Addr().Elem().Field(0)`.

**Comment by dsnet** [comment]
I argue that:
```
1. (*p).Field            =>  v.Elem().FieldByName("Field")
2. (*p).child.Field      =>  v.Elem().FieldByName("child").FieldByName("Field")
3. (*&(*p).child).Field  =>  v.Elem().FieldByName("child").Addr().Elem().FieldByName("Field")
```

If 2 is permitted (which violates normal visibility rules), I don't see why 3 is forbidden.

**Comment by mdempsky** [comment]
I think case 1 is clearly okay.

Case 2 is tricky though, and shouldn't be used as a precedent to justify case 3.

Earlier, we were talking about Value.Field, not Value.FieldByName. Field doesn't support directly accessing promoted fields. This means `v.Elem().Field(0).Field(0)` needs to be allowed because it's the only way to represent `p.Field` (which is valid), even though it also represents `p.child.Field` (which should be invalid).

It seems FieldByName is acting consistent with Field, even though it doesn't need to: since we can directly allow `v.FieldByName("Field")`, there's not a strong reason to need to allow `v.FieldByName("child").FieldByName("Field")`, IMO.

Maybe we need to continue allowing it for backwards compatibility, or so that FieldByName parallels Field. In either case, I don't think it's a good argument for allowing case 3.

**Comment by dsnet** [comment]
Bleh, the whole situation is funky.

Back-to-back use of `Field` also allows other things not normally allowed:
```go
type child1 struct{ Field string }
type child2 struct{ Field string }
type parent struct {
	child1
	child2
}

p := new(parent)
reflect.ValueOf(p).Elem().Field(0).Field(0).SetString("hello")
reflect.ValueOf(p).Elem().Field(1).Field(0).SetString("goodbye")
fmt.Println(p) // &{{hello} {goodbye}}
```
Here, the existence of a conflict on `Field` makes it such that it would normally be impossible to access this field. However, it is possible with the back-to-back `Field` calls.

**Comment by mdempsky** [comment]
Yeah, it's kind of a mess. :( I'd argue that should be disallowed too, but I'm not sure how to do that efficiently.

**Comment by ianlancetaylor** [comment]
The problem described by this issue is working as intended.
