### ISSUE TITLE
program runs in UTC time if /etc/localtime not exists on embedded system (improvement proposal)

### ISSUE THREAD

**Issue by ljubomirb** [golang/go#24268]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
mips/linux

### What did you do?
On embedded system, running on LEDE box, `time.Now() `and everything time related is always in UTC instead of currently set time zone.
Linux system is however running fine, and commands like `touch`, `DATE ` are showing right date, time, zone.
This is the code to test:
```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(time.Now().Location())
}
```
### What did you expect to see?
Local

### What did you see instead?
UTC

After I just plain simple copied `/etc/localtime `file from Debian machine, everything worked.
My question/proposal is:
-if the Go time subsystem needs that file during init, could it be better to throw error or warning?
-LEDE/OpenWRT system has `/etc/TZ` file with content like: `CET-1CEST,M3.4.0,M10.5.0/3`, so can this be used silently by Go if first case of finding `/etc/localtime` file fails?

**Comment by ianlancetaylor** [comment]
As far as I can tell the `/etc/TZ` file is not standardized across systems, so I don't see a way to use that.  I would be happy to hear otherwise.

If we're on GNU/Linux and the `TZ` environment variable is not set and there is no `/etc/localtime` file, then we don't know the time zone.  But it would not be appropriate to print a warning unexpectedly, and I don't see how it would help to crash the program.  That should be up to the program; it shouldn't be done by the system library.

Closing because I don't think there is anything we can do.  Please comment if you disagree.
