### ISSUE TITLE
net: nil *Resolver not equivalent to zero resolver, despite doc

### ISSUE THREAD

**Issue by philpennock** [golang/go#24330]
### What version of Go are you using (`go version`)?

`go version go1.10 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pdp/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pdp/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vs/7q9nz5955_z7b7zxfz437zrm0000gn/T/go-build515078480=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Tested the assertion at https://golang.org/pkg/net/#Resolver that:
> A nil *Resolver is equivalent to a zero Resolver.

https://play.golang.com/p/B40hcxy_Uuu

In the Go sandbox, it errors out because of the network restrictions.  Run locally, this panics:

`panic: runtime error: invalid memory address or nil pointer dereference`

Swap the commenting-out of the `r` declaration to create a zero resolver, and the code runs perfectly.

### What did you expect to see?

No difference in output between the two ways of declaring the resolver, because the documentation explicitly asserts the behavior of a nil `*Resolver`.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bedd6]

goroutine 5 [running]:
net.(*Resolver).lookupIP(0x0, 0x112e2e0, 0xc4200180f0, 0x1119095, 0xe, 0x0, 0xc420001b00, 0xc420062040, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:90 +0x26
net.(*Resolver).(net.lookupIP)-fm(0x112e2e0, 0xc4200180f0, 0x1119095, 0xe, 0x1028169, 0x8, 0xc420062040, 0x0, 0xc420035ea0)
	/usr/local/go/src/net/lookup.go:192 +0x56
net.glob..func10(0x112e2e0, 0xc4200180f0, 0xc420010370, 0x1119095, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:200 +0xd8
internal/singleflight.(*Group).doCall(0x11bbdf0, 0xc42009e0f0, 0x1119095, 0xe, 0xc420090510)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2d0
exit status 2
```

**Comment by fraenkel** [comment]
There are actually a few places which will panic since access to PreferGo or StrictErrors does not check if the resolver is nil.

**Comment by as** [comment]
Can't reproduce this _exact_ example on  `go version go1.10 windows/amd64` (but is reproductible on `darwin`). The comment seems wrong though, or at least easier to fix than the code. 

- There's already a net.DefaultResolver in stdlib so making your own I would have automatically assumed it would be required to be non-nil. 

- http.Client (which has http.DefaultClient) doesn't guarantee that *http.Client is equal to it's zero value (and would probably crash and burn in the same manner).

/cc @bradfitz

**Comment by odeke-em** [comment]
Thank you for this catch @philpennock! In deed we made this promise but as @fraenkel noted, there are few places in which on UNIX like systems where we directly invoke fields on the *Resolver[1]

On other systems we don't even seem to be touching *Resolver[1]

Anyways this is just an oversight, we made that assertion ~1.5 years ago in September 2016, in this CL https://go-review.googlesource.com/29440 and commit https://github.com/golang/go/commit/2bc5f1258e049e1d59711046e5c865500eefa159 but
changed the UNIX code up ~1.4 years ago in October 2016, in this CL https://go-review.googlesource.com/c/31734/ and commit https://github.com/golang/go/commit/40d4be59ccd83c29a72fb6a9a8c2eee4c91f628b.

I'd suggest perhaps:
a) Remove that documentation promise entirely as I think that at the time it was subjective by consensus(i.e. every other resolver had a method to use the default Resolver if it were nil)
b) Fix it for UNIX systems and then add a test to lock this behavior in. This way if any future edits change up the resolvers, the assertion test will panic and perhaps also clarify that we meant, `Using a nil *Resolver will instead use the default Resolver` because currently `A nil *Resolver is equivalent to a zero Resolver.` is too strong and the equivalence implied could be misunderstood as literally being equivalent like `==`.

[1]

System|Comment|Code
---|---|---
Nacl|Noop|https://github.com/golang/go/blob/c15b7b2a54a8899fac8277cef532676c9f8fb592/src/net/lookup_nacl.go#L18-L20
Windows|Not even referenced in lookup code|https://github.com/golang/go/blob/c15b7b2a54a8899fac8277cef532676c9f8fb592/src/net/lookup_windows.go#L79-L136
Plan9|Not even referenced in lookup method|https://github.com/golang/go/blob/c15b7b2a54a8899fac8277cef532676c9f8fb592/src/net/lookup_plan9.go#L120-L152
UNIX|Definitely, fields are invoked on it and will panic|https://github.com/golang/go/blob/c15b7b2a54a8899fac8277cef532676c9f8fb592/src/net/lookup_unix.go#L77-L103
