### ISSUE TITLE
crypto/cipher: BlockMode.CryptBlocks could return an error?

### ISSUE THREAD

**Issue by siadat** [golang/go#24336]
It is usually preferred that libraries avoid panicking and return errors and delegate error handling to their client. I was wondering if there is a reason that [BlockMode.CryptBlocks](https://tip.golang.org/pkg/crypto/cipher/#BlockMode) does not return an error. Currently both of implementations, i.e., *cbcDecrypter and *cbcEncrypter, have to panic in case there is a problem in their inputs.

**Comment by odeke-em** [comment]
Hello @siadat, thank you for the question.

Firstly, I believe that this behavior cannot change due to the Go1.0 compatibility promise.

In regards to panicking on `len(dst) < len(src)`: this is a short write and a user error while encrypting a block and perhaps a security issue as further supported by @rsc's comment in @minux's CL that documented this behavior long after the API was designed https://go-review.googlesource.com/c/go/+/1754#message-1186b2a59679055900246c2dc8c26aa18d16ca8b 
```
2) Claim that this is a security issue, due to being too easy to use incorrectly, and define that len(dst) != len(src) must panic, updating the existing implementations.
```

/cc @agl for perhaps more words, to explain the API

**Comment by andybons** [comment]
Thanks for the report.

@odeke-em is correct that this would break the [Go1 compatibility promise](https://golang.org/doc/go1compat).

That said, if you wanted to propose an API change for Go2, I would write a [proposal](https://github.com/golang/proposal) with a bit more detail with real-world, motivating examples to support the change. Then /cc @agl and @FiloSottile for feedback.

Thanks
