### ISSUE TITLE
os: Expand eats $s in the middle of the string (but not at the end)

### ISSUE THREAD

**Issue by opennota** [golang/go#24345]
### What version of Go are you using (`go version`)?

go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/opennota/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/opennota/gocode"
GORACE=""
GOROOT="/home/opennota/go"
GOTMPDIR=""
GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build224817525=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

https://play.golang.org/p/ulxC4AgmVNF

### What did you expect to see?

The program outputs `abc$|def$`

### What did you see instead?

The program outputs `abc|def$`

This is unfortunate, because `go generate` uses `os.Expand` to expand environment variables in the command line and if one needs to pass a regexp to the executed command, the regexp gets garbled.

**Comment by peczenyj** [comment]
Hello

This seems an side effect os this:
```
References to undefined variables are replaced by the empty string.
```

https://golang.org/pkg/os/#ExpandEnv

The example of this command shows what happens when both variables are not defined:

“ lives in .”

https://play.golang.org/p/SgYOD-pASWl

My guess is: $var works for alphanum and ${var} works for all chars. Since we have variables like $? $$ etc you must do ${?} to consider this a variable to expand. So $? Seems a corner case where you have an “empty” variable $ follow “?” - and doing `abc${|}edf$` may work

**Comment by agnivade** [comment]
To be consistent, I think the trailing $ needs to be removed too. The first $ is correctly gobbled because | is neither a shell special variable nor an alphanumeric character.  The expected output, IMO, should be `abc|def`.  

Moreover `abc$|def${}` is expanded to `abc|def`, whereas `abc$|def$` is expanded to `abc|def$`.

It's a relatively small change. /cc @ianlancetaylor for decision.

**Comment by opennota** [comment]
@agnivade

Correct me if I'm wrong, but with your proposed change nobody would be able to use a literal `$` in the arguments to a go:generate command, like

```
//go:generate esc -o static.go -ignore "\.map$" build/
```

**Comment by opennota** [comment]
I believe that the correct way to fix it is to leave `$` alone in case it can't be recognized as a variable, as bash does:
```
$ echo -e "$$\n$?\n$+\n$-\n$|\n$"
4292
0
$+
himBH
$|
$
```

**Comment by agnivade** [comment]
My proposal does not _change_ that behavior. It is already the existing behavior. My proposal was to make it consistent. Theoretically, I agree with your proposal, but I am not sure how much of a breaking change is this considered to be.

I will leave it to others to make the call.

**Comment by as** [comment]
>I believe that the correct way to fix it is to leave $ alone in case it can't be recognized as a variable, as bash does:

That's sound's incorrect.

The bug is that `$` doesn't consider the a zero length string/eof to be a valid follow token, [but it works when `${}` is at the end of the string](
https://play.golang.org/p/t9CLzDffWlD). This logic is on the domain of the function during the lexing stage. You're suggesting instead, that the function should look at the range after the evaluation of the mapping function has happened, and treating its output (the empty string) as a special case.

The documentation says that os.Expand replaces the `${var} or $var in the string based on the mapping function`. It doesn't matter if the mapping function returns an empty string, your bug happens because of the lexical scanning never even makes it call the mapping function in the first place.

**Comment by opennota** [comment]
@as 
You're speaking in terms of implementation simplicity. I speak in terms of the expected behavior.

**Comment by as** [comment]
@opennota I don't expect this behavior either. I expect all tokens denoting a potential variable name to be excised after one pass of `os.Expand`

Besides, your desired behavior is trivial to implement: just make your own `func (s string) string` that returns a literal `$` on empty input to it.

**Comment by opennota** [comment]
For the reference, in both Python 2 and 3 [os.path.expandvars](https://docs.python.org/3/library/os.path.html#os.path.expandvars) doesn't even touch variables with non-alphanumeric names:
```
>>> import os
>>> os.path.expandvars('$$ $? $+ $- $| $')
'$$ $? $+ $- $| $'
```
That's the most sane behaviour, IMO.

**Comment by ianlancetaylor** [comment]
This issue seems to be about two different things.

The first is that `os.Expand` ignores a `$` at the end of the input string.  That does seem peculiar though it's also true that there is no obvious way to handle it.  It's not obvious to that we should just remove it.  It seems more consistent to me to call the function with the empty string, but that could break existing code.  Perhaps we should just document the behavior and carry on.  Most people who call `os.Expand` have some control over the input string, and so need not worry about a trailing `$`.

The second problem in this issue is that `go generate` uses `os.Expand`, and that makes it hard to pass a regular expression as an argument in a `go generate` command.  That is true.  I don't see any way backward compatible way to fix that.  That problem doesn't really have anything to do with the way that `os.Expand` handles a trailing `$`, it's a general problem with any use of `$`.  After all, a regular expression can contain `$` at places other than at the end, such as within `[]`.  Actually, I take it back: we could address this with only a minor break in compatibility by expanding `$$` to `$`; currently I believe that `$$` always expands to the empty string.

**Comment by peczenyj** [comment]
How about allow escape \$ as literal $ ?
If it is too bad ( backward compatibility, etc ), we can add an option/flag to escape or add an new explicit method for this (maybe in go 2)

**Comment by ianlancetaylor** [comment]
@peczenyj First let me repeat that I think there there are two separate problems here.  Which one are you trying to address?

That said, I don't agree with adding backslash quoting to either case.  It's not necessary, because we can use `$$`.  It introduces more complexity, since now we need to use backslash quoting for backslash itself.  It naturally leads to people wondering about using backslash quoting for other characters, such as `\n`.  Is that two characters `\` `n`, or one character `n`, or one character ASCII LF?

**Comment by opennota** [comment]
@ianlancetaylor 
How about ignoring `$` altogether unless it is followed by `NAME` or `{NAME}`? I fail to see how the existing code might reasonably depend on `os.Expand` removing single `$`s, and it's not that there were no breaking changes in the past (the cgo pointer passing rules introduced in Go 1.6 come to mind).

**Comment by ianlancetaylor** [comment]
The cgo pointer passing rules were different, as use of cgo is not covered by the Go 1 compatibility guarantee.

The current `os.Expand` implementation has special code to support `$*`, etc., and it doesn't seem right to drop all of that.

**Comment by opennota** [comment]
> The current os.Expand implementation has special code to support $*, etc., and it doesn't seem right to drop all of that.

Why not? It was never officially supported (`Expand replaces ${var} or $var`, unquote), and if someone uses this (is there anyone who does? Go itself doesn't.), they do it on their own risk.

Alternatively, allow only a limited subset of characters to be treated as a variable, otherwise leave `$` alone.

**Comment by ianlancetaylor** [comment]
Let's not change existing behavior unless we are solving a clear problem.

We already check for a list of special characters; is `isShellSpecialVar` in os/expand.go.  But changing `os.Expand` so that `$|` is left as `$|` but `$?` disappears seems to me to increase confusion, not decrease it.

**Comment by spf13** [comment]
We should be consistent. It seems that keeping the $ in both cases is ideal rather than eliminating it only at the end.

**Comment by agnivade** [comment]
@spf13 - So just to be clear, you want $ to remain in the output in case the following character neither a shell special variable nor alphanumeric . So, `abc$|def$` would result in this `abc$|def$`.

**Comment by ianlancetaylor** [comment]
Yes.

**Comment by agnivade** [comment]
Cool. Will send a CL.
