### ISSUE TITLE
x/vgo: OS specific requirements don't appear to be added to the go.mod

### ISSUE THREAD

**Issue by IngCr3at1on** [golang/go#24367]
### What version of Go are you using (`go version`)?
`go1.10`

### What operating system and processor architecture are you using (`go env`)?
`linux/amd64`

### What did you do?
I added a `go.mod` file to an existing project and ran `vgo build`. The following require lines were added to the .mod file as expected:

```
require (
	"github.com/labstack/echo" v1.4.4
	"github.com/sirupsen/logrus" v1.0.5
	"golang.org/x/crypto" v0.0.0-20180312195533-182114d58262
)
```

and vgo attempted to compile the application

### What did you expect to see?
the application to be compiled into a binary

### What did you see instead?

```
# golang.org/x/crypto/ssh/terminal
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:30:12: undefined: unix.IoctlGetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:38:18: undefined: unix.IoctlGetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:54:12: undefined: unix.IoctlSetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:64:18: undefined: unix.IoctlGetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:75:9: undefined: unix.IoctlSetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:80:13: undefined: unix.IoctlGetWinsize
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:98:18: undefined: unix.IoctlGetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:107:12: undefined: unix.IoctlSetTermios
../../../../v/golang.org/x/crypto@v0.0.0-20180312195533-182114d58262/ssh/terminal/util.go:111:8: undefined: unix.IoctlSetTermios
```

----

I can get around this error obviously by running `vgo get golang.org/x/sys`

**Comment by rsc** [comment]
This is a "garbage in" problem, not a problem in vgo itself. 

github.com/labstack/echo has https://github.com/labstack/echo/blob/master/Gopkg.lock which asks for a specific commit of x/sys. golang.org/x/crypto does not declare its dependencies at all, but it turns out to need a newer version of x/sys than the one requested by labstack/echo. Since the requirement on the newer version is unstated, vgo obviously doesn't know about it, so it keeps using the older one, leading to the missing IoctlGet\* symbols.

This is a fundamental problem: if packages depend on something they don't mention in their requirements lists, then they might not get the right version of that thing. There's not much we can do about it once it happens. In the long term, once everything is being built with vgo (when it becomes "go"), everything _will_ declare its requirements, since go.mod is updated automatically, and the problem will not happen anymore.
