### ISSUE TITLE
hashmap question: what does this line of code mean?

### ISSUE THREAD

**Issue by i19** [golang/go#24373]
Hi, i am learning the source code, and i found it's hard to understand ... can any one tell me what does this line of code mean? 

https://github.com/golang/go/blob/3c16934f1638d3d756fb315b847a3805ac06de88/src/runtime/map.go#L260

**Comment by ALTree** [comment]
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Specific questions about internal implementation details can also be asked in the golang-dev mailing list: https://groups.google.com/forum/#!forum/golang-dev

Closing this thread, since it is not a Go bug.
