### ISSUE TITLE
x/build/maintner: GerritCL.Created is not accurate (it equals to "CL Updated" time instead)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#24744]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.10.1 darwin/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

I queried the [`maintner.GerritCL.Created`](https://godoc.org/golang.org/x/build/maintner#GerritCL.Created) value for [CL 92456](https://go-review.googlesource.com/c/go/+/92456).

<details><summary>Sample Program</summary><br>

```Go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"golang.org/x/build/maintner/godata"
)

func main() {
	c, err := godata.Get(context.Background())
	if err != nil {
		log.Fatalln(err)
	}
	cl := c.Gerrit().Project("go.googlesource.com", "go").CL(92456)
	fmt.Println("cl.Created:", cl.Created.UTC().Format(time.UnixDate))
}
```

</details>

### What did you expect to see?

[`maintner.GerritCL.Created`](https://godoc.org/golang.org/x/build/maintner#GerritCL.Created) is not documented, but given the field is named `Created time.Time` and it's inside the `GerritCL` struct, one would expect it to be the time the CL was created.

CL 92456 was created about [2 months ago](https://go-review.googlesource.com/c/go/+/92456#message-ca1f3042ded5036bef9e9c5a952c64cc2f85f0de).

So, I expected to see a date like Feb 6, 2018, 6:57 PM UTC.

### What did you see instead?

A date like Apr 6, 2018, 7:42 PM UTC. Which is around 9~ hours ago.

It's the date the CL was last updated (merged).

---

I've looked at the code and it looks like the `GerritCL.Created` value is assigned to the `CommitTime` of the latest meta commit. That would explain the results I saw.

**Comment by shurcooL** [comment]
I haven't looked too closely, but I suspect the fix might be as simple as using the oldest (rather than most recent) meta commit's commit time instead.

**Comment by shurcooL** [comment]
I tried it, that seems to work. Using the commit time of the root meta commit (instead of the head meta commit, as is currently done) gives me the same CL create time as via Gerrit API (and Gerrit UI).

**Comment by bradfitz** [comment]
Sounds like a bug.

It also needs proper docs: https://godoc.org/golang.org/x/build/maintner#GerritCL.Created

**Comment by shurcooL** [comment]
It was hard to fix this bug with a short diff, because there were too few guarantees inside `finishProcessingCL` that could be relied on. I wanted to improve that as part of my fix.

(The hacky diff I posted earlier worked as a prototype, but it was hard to be sure that it'd work all of the time, and hard to change `finishProcessingCL` without fearing it would break.)

We already established some guarantees for the user-facing CLs (i.e., that their `Commit`, `Meta` fields are non-nil and `len(cl.Metas) >= 1`). I started propagating that in a few more places in internal code.

It allows simplifications such as:

```diff
 // OwnerName returns the name of the CL’s owner or an empty string on error.
 func (cl *GerritCL) OwnerName() string {
-	m := cl.firstMetaCommit()
-	if m == nil {
-		return ""
-	}
-	return m.Author.Name()
+	if !cl.complete() {
+		return ""
+	}
+	return cl.Metas[0].Commit.Author.Name()
 }
-
-func (cl *GerritCL) firstMetaCommit() *GitCommit {
-	m := cl.Meta
-	if m == nil { // TODO: Can this actually happen, besides in one of the contrived tests? Remove?
-		return nil
-	}
-	c := m.Commit
-	for c != nil && len(c.Parents) > 0 {
-		c = c.Parents[0] // Meta commits don’t have more than one parent.
-	}
-	return c
-}
 
 // complete reports whether cl is complete.
 // A CL is considered complete if its Meta and Commit fields are non-nil,
 // and the Metas slice contains at least 1 element.
 func (cl *GerritCL) complete() bool {
 	return cl.Meta != nil &&
 		len(cl.Metas) >= 1 &&
 		cl.Commit != nil
 }
```

Also, previously, it was hard to be sure that the `gc, ok := ...` line wouldn't panic:

```Go
// called with Corpus.mu Locked
func (gp *GerritProject) finishProcessingCL(cl *GerritCL) {

	// What happens if cl.Meta is nil?
	// Should there be a if cl.Meta == nil guard here?
	// What should it do if cl.Meta is indeed nil?
	gc, ok := c.gitCommit[cl.Meta.Commit.Hash]
	if !ok {
		log.Printf("WARNING: GerritProject(%q).finishProcessingCL failed to find CL %v hash %s",
			gp.ServerSlashProject(), cl.Number, cl.Meta.Commit.Hash)
		return
	}
```

By documenting that `cl.Meta` must be non-nil as a precondition of `finishProcessingCL`, it becomes possible to know it won't panic:

```Go
// finishProcessingCL fixes up invariants before the cl can be returned back to the user.
// cl.Meta must be non-nil.
//
// called with Corpus.mu Locked
func (gp *GerritProject) finishProcessingCL(cl *GerritCL) {

	// cl.Meta can't be nil due to precondition.
	gc, ok := c.gitCommit[cl.Meta.Commit.Hash]
	if !ok {
		log.Printf("WARNING: GerritProject(%q).finishProcessingCL failed to find CL %v hash %s",
			gp.ServerSlashProject(), cl.Number, cl.Meta.Commit.Hash)
		return
	}
```

(It would be a bug to call `finishProcessingCL` with a nil `cl.Meta` because it'd be violating the precondition.)

I think stating preconditions and propagating more internal invariants is a good general direction, because it allows the code to be simpler and easier to verify as being correct. Otherwise, you need to keep checking if fields are non-nil everywhere before using them, and that's annoying.

@bradfitz I hope you're okay with that direction, but let me know if you prefer to do things differently.

It'll be a bigger CL, but I think the end result is worth it. Feel free to let me know if it's too hard to review and if there are ways I can make it easier (maybe by splitting it into 2-3 smaller independent changes).
