### ISSUE TITLE
x/mobile: confusing "unsupported basic type" error when targeting Android

### ISSUE THREAD

**Issue by Anyhasgone** [golang/go#24762]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
->go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
->yes

### What operating system and processor architecture are you using (`go env`)?
->linux, amd64

### What did you do?
->programmer

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Please help me.Why unsupported basic type uint32 or uint64

### What did you see instead?

the issues:
use gomobile bind -target=android/arm xxxx,and compile error
unsupported basic type: uint32
unsupported basic type: uint64

**Comment by mvdan** [comment]
I assume this is because gomobile is trying to generate Java code, and Java has no unsigned integer types. However, a quick google search doesn't give a definite answer, and the error message seems like this may be a bug or fixed at some point, rather than a design limitation.

Leaving it to @eliasnaur or someone else to decide if the error message should be improved. For example, something like "cannot use unsigned integer types on Java" for the uint16/32/64 errors.

**Comment by mvdan** [comment]
This doc page does leave unsigned integers out: https://godoc.org/golang.org/x/mobile/cmd/gobind#hdr-Type_restrictions

But it's still hard to reach it if one is googling for the error or searching for "uint", since neither appears on the page.
