### ISSUE TITLE
cmd/compile: failure to compile interface{}(1<<s + 1<<s)

### ISSUE THREAD

**Issue by mdempsky** [golang/go#24763]
https://play.golang.org/p/Pt6pzZ09C_7

    package main

    func main() {
    	var s uint
    	var x = interface{}(1<<s + 1<<s)
    	println(x)
    }

cmd/compile fails to compile this program, and instead outputs "prog.go:5:27: internal compiler error: unhandled binary op + INTER".  go/types accepts it.

**Comment by ianlancetaylor** [comment]
Works with gccgo.

**Comment by IronGopher** [comment]
As of 3a5264, no longer gives an internal compiler error. Instead prints:

    interfaceshift.go:5:21: invalid operation: 1 << s * 1 << s (shift of type interface {})

**Comment by IronGopher** [comment]
`ssaOp` calls `Fatalf` because there is no map entry for `{ADD, TINTER}`. ([cmd/compile/internal/gc/ssa.go:1378](https://github.com/golang/go/blob/704893b16be5ab99913ee04c615d570ad5d57027/src/cmd/compile/internal/gc/ssa.go#L1378)\)

Those values are passed to `ssaOp` by `expr` because the right side of the equation is considered to be an `OCONVNOP` instead of `OCONVIFACE` or `OCONV` as it should be. ([ssa.go:2029](https://github.com/golang/go/blob/704893b16be5ab99913ee04c615d570ad5d57027/src/cmd/compile/internal/gc/ssa.go#L2029)\)

`OCONVNOP` is assigned to the node because the `src` and `dst` types evaluate as the same. ([typecheck.go:1690](https://github.com/golang/go/blob/704893b16be5ab99913ee04c615d570ad5d57027/src/cmd/compile/internal/gc/typecheck.go#L1690)\) The types being checked are that of a node and its left child.

In [typecheck.go:565](https://github.com/golang/go/blob/704893b16be5ab99913ee04c615d570ad5d57027/src/cmd/compile/internal/gc/typecheck.go#L565), there's some code dealing with shifts where a node appears to be explicitly assigned the type of its left child.

**Comment by choleraehyq** [comment]
Seems converting to interface will be handled in convertop, so we shouldn't set type to t directly when t is an interface type ([const.go:249](https://github.com/golang/go/blob/704893b16be5ab99913ee04c615d570ad5d57027/src/cmd/compile/internal/gc/const.go#L249)).
