### ISSUE TITLE
Inconsistent results when using math/big with channels

### ISSUE THREAD

**Issue by tuxether** [golang/go#24769]
### What version of Go are you using (`go version`)?
go version go1.10.1 linux/arm

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="arm"
GOBIN=""
GOCACHE="/home/chronos/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chronos/user/Downloads/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build030124681=/tmp/go-build -gno-record-gcc-switches"
```

```
$ uname -a
Linux localhost 4.4.122-13289-g3ef2bcfe7ed4 #1 SMP PREEMPT Thu Mar 22 14:08:00 PDT 2018 aarch64 ARMv8 Processor rev 4 (v8l) GNU/Linux


ChromeOS Version 67.0.3376.0 (Official Build) dev (32-bit)
```

### What did you do?

https://play.golang.org/p/Bh1o17YTjfl

```
package main
  
import (
        "fmt"
        "math/big"
)

func generate(c chan<- *big.Int) {
        step := big.NewInt(1)

        for i := big.NewInt(1); ; i.Add(i, step) {
                c <- i
        }
}

func main() {
        ch := make(chan *big.Int)

        go generate(ch)

        for i := 0; i < 30; i++ {
                prime := <-ch
                fmt.Println(prime.String())
        }
}
```

### What did you expect to see?

```
1
2
3
4
5
6
7
8
9
10
...
```

### What did you see instead?

```
2
2
3
4
5
6
8
8
10
10
...
```

**Comment by mvdan** [comment]
This has nothing to do with math/big. As you can see, the exact same thing happens if you use `*int`: https://play.golang.org/p/GFdOyvgtKZz

The issue here is that you are reusing the same pointer for every send, so you modify previously sent values. This can be seen very clearly if you add more buffering to the channel, which further accentuates this issue: https://play.golang.org/p/2WkrFmpKXik

In the future, please see https://golang.org/wiki/Questions for more appropriate places to ask questions. You should only open an issue here once you're positive there isn't a bug in your code.
