### ISSUE TITLE
doc: mention GOTOOLDIR in "go help environment"

### ISSUE THREAD

**Issue by rpjday** [golang/go#24794]
Currently running Go 1.10.1 on linux/amd64, and noticed that while "go env" prints (among other things) the value of GOTOOLDIR:

`GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"`

"go help environment" says nothing about the purpose and usage of that variable. Is that deliberate?

**Comment by ALTree** [comment]
The `go help environment` message was written in d23973d23ca19f5c2992467c01e02df1780b576c by Ian. Maybe `GOTOOLDIR` was left out on purpose since the goal was to document "General-purpose environment variables"?

cc @ianlancetaylor for decision.

**Comment by rpjday** [comment]
As a Go newbie, I had no idea what GOTOOLDIR was responsible for, I just noticed the discrepancy in that it was mentioned in one place and not the other, that's all. I suspect I'm not the only person who ever noticed that, just the only one who whined about it. :-)

Are there any other variables that might have been overlooked this way?

**Comment by ALTree** [comment]
`go env` is mostly used for debugging purposes, while the purpose of `go help environment` is to document environment variables that the user may want to set to change the go tools' behaviour. Since the two have different goals, they don't necessarily have to describe the same set of variables.

On the other hand, GOTOOLDIR is currently more or less undocumented, so it may be a good idea to still include it in the `go help environment` output, in case someone like you sees it on `go env` and wants to know what the variable points to.
