### ISSUE TITLE
net/http: shutdown on http.Server serving through net.Listener closes listener twice

### ISSUE THREAD

**Issue by tdewolff** [golang/go#24803]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/taco/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/taco/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build151412356=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
When I run the following code, the listener is closed twice:

``` go
package main

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"time"
)

type Listener struct {
	net.Listener
}

func (l *Listener) Close() error {
	fmt.Println("close")
	return l.Listener.Close()
}

func main() {
	ln, _ := net.Listen("tcp", "localhost:9999")
	listener := &Listener{ln}

	server := &http.Server{}
	go func() {
		err := server.Serve(listener)
		fmt.Println("Serve:", err)
	}()

	time.Sleep(time.Second) // make sure it starts Serving

	server.Shutdown(context.Background())

	time.Sleep(time.Second) // make sure to exit Serve and print error before exit
}
```

The problem appears to be in `http/server.go`, where `Shutdown` will call `srv.closeListenersLocked` which closes our listener. But as `Serve` exits, the first row in that function defines a `defer l.Close()` that closes the listener as well! I think the latter should go, if I understand it correctly.

### What did you expect to see?
I expected the listener to be closed only once, this is causing double closes on underlying structures in our production.

### What did you see instead?
You will notice that `Close` is called twice.

**Comment by gregory-m** [comment]
The first `Close()` is form: https://github.com/golang/go/blob/cf7760360ed5ed5ae3d38e626eaf913329d16778/src/net/http/server.go#L2624

The second is from: 
https://github.com/golang/go/blob/cf7760360ed5ed5ae3d38e626eaf913329d16778/src/net/http/server.go#L2758

The `defer l.Close()` in `Serve` function was added 7 years ago: 876e9d1b89cf87f3791153fa9472142cd5294223 and I doubt if its necessary, because before `Server.Close()` and `Server.Shutdown()` was added closing underlying listener was the only way to shutdown server.

**Comment by pam4** [comment]
@gregory-m Server.Serve may return before Server.{Close,Shutdown} is ever called.
If we expect the listener to be closed after Server.Serve returns, than the defer *is* necessary, though such expectation is not stated in the doc.

**Comment by gregory-m** [comment]
@pam4 right.

Here our options:
1. Do nothing and document double close behaviour.
2. Remove defer and don't close listener on error, I think this will will break backward compatibility promise.
3. Replace defer with explicit close call on errors, since `Serve` have only 2 such places defer can be replaced with 2 close calls.

**Comment by pam4** [comment]
> 1. Do nothing and document double close behaviour.

I've been in the situation of writing similar code before.
In the end I decided to play it safe and be sure to call Listener.Close at most once.
If a Listener user is allowed to call Close more than once, and expect the subsequent calls to be no-ops, than I think it should be documented.

> 3. Replace defer with explicit close call on errors, since Serve have only 2 such places defer can be replaced with 2 close calls.

That would be racy without some synchronization (at least for the second one that is after `srv.trackListener(l, true)`)

**Comment by gregory-m** [comment]
cc @bradfitz. We need decision here.

**Comment by pam4** [comment]
This is also related: #20705
And above I quoted the `net.Listener` doc, but the `io.Closer` doc also apply:
```go
// Closer is the interface that wraps the basic Close method.
//
// The behavior of Close after the first call is undefined.
// Specific implementations may document their own behavior.
type Closer interface {
    Close() error
}
```

**Comment by bradfitz** [comment]
Implementations of net.Listener should be tolerant of multiple Close calls, but users of net.Listeners (net/http) should also try to only call them once, in case implementations aren't tolerant.

What about https://go-review.googlesource.com/#/c/go/+/106715? Does that work for y'all?

**Comment by pam4** [comment]
Ok, thanks for the clarification, then you advise to play it safe on both sides.
An ideal Listener would also return a meaningful error (or nil) on subsequent Close calls instead of something like `"Listener already closed"`, right?

I also noticed that this CL would make [106657](https://golang.org/cl/106657) superfluous since now `l`'s dynamic type is always a pointer :D

**Comment by bradfitz** [comment]
> I also noticed that this CL would make 106657 superfluous since now l's dynamic type is always a pointer :D

Well, at least its test is still valid.
