### ISSUE TITLE
x/build: add playground to build.golang.org

### ISSUE THREAD

**Issue by ysmolski** [golang/go#24823]
Currently running trybots for `x/playground` produces this:
https://storage.googleapis.com/go-build-log/2d26a65f/linux-amd64_e35969e6.log

Add Playground to build.golang.org.
Make builders be able to test Playground in the its docker container.

**Comment by andybons** [comment]
You should also add it to build.golang.org :smile:

**Comment by ysmolsky** [comment]
@andybons, is there any good doc describing how trybots work besides https://go.googlesource.com/build/ ?

**Comment by andybons** [comment]
Good question. @bradfitz ?

**Comment by ysmolsky** [comment]
Something is not clear. We have to test Playground via it's docker container. But where should we run that? I think it does not make much sense to run it on many platforms. Also I fail to find repos tests in similar fashion, but running not a `go test ./...` but rather docker container which will take more than 10 minutes to build from scratch. I will dig further a bit later...

**Comment by bradfitz** [comment]
Yes, we have no way to do this right now. That's why it's not a good starter project. This will be a lot of work and require a number of changes across our build system.

**Comment by bradfitz** [comment]
Rough outline, though:

* make a new `misc-playground` builder (similar to `misc-compile-*`).
* make a new host type in x/build/dashboard/builders.go etc that's VM-based, not container-based. Probably can resurrect docker2boot, which we used to use before Kubernetes. (we don't want to use Kubernetes here because docker build on Kubernetes remains a mess: https://github.com/kubernetes/kubernetes/issues/1806 etc)
* make a "go test" friendly test that runs`exec.Command("docker", "build")` etc if `os.Getenv("GO_BUILDER_NAME") == "misc-playground"
* add some special cases for which tests to run in dashboard/builders.go and cmd/coordinator, like some of the others clarifying which repos run on which builders.

**Comment by dlorenc** [comment]
We just open sourced a tool today to make docker build on kubernetes less of a mess: github.com/GoogleCloudPlatform/kaniko

**Comment by dmitshur** [comment]
Resolving this issue should be easier now compared to 2018 for at least one reason: thanks to module mirror, additional non-golang.org/x dependencies will no longer be a problem to fetch.

I'm not if something Docker-related also needs to be done, but @toothrot may have more context.

/cc @toothrot @findleyr

**Comment by toothrot** [comment]
The integration tests changed in #25224 to require two docker containers running in a docker network, and also require the ability to run `runsc`, which requires root. I have a few ideas on how we can get good coverage, but the current state the TryBots and the Playground's test setup will require a little work.

**Comment by dmitshur** [comment]
Post-submit builders for x/playground have been added in LUCI, for example:

https://ci.chromium.org/p/golang/g/x-playground-gotip/console

(There are more dashboards for release branches and with different commit order if you search for "x/playground" in the https://ci.chromium.org/p/golang list.)

I filed #66002 for getting additional tests to run,
and #66001 to opt-in x/playground for automated golang.org/x updates.
