### ISSUE TITLE
cmd/compile: optimize switch string(byteSlice) lookups

### ISSUE THREAD

**Issue by dchenk** [golang/go#24937]
I see this pattern commonly:
```
switch string(byteSlice) {
case "some_key":
    // Stuff ...
case "another":
    // Stuff ...
// More cases ...
}
```
(Instances of this pattern exist in the standard library.)

Here an allocation is made for the string, copying the contents of the `[]byte`. It'd be great if the contents of the slice could be used without an allocation of a string, using simply a string header pointing to the same location as the slice. This will avoid creating a ton of garbage.

This is the same kind of proposal as #3512 by @bradfitz (and I think the implementation would look similar).

**Comment by bradfitz** [comment]
The compiler already implements `string(byteSlice) == "string literaal"` without an allocation.

So I'm a little surprised that we don't get this for free right now. Maybe if `switch` were rewritten to a series of `if` statements then we'd get it for free?

/cc @mdempsky @josharian

**Comment by josharian** [comment]
> Maybe if switch were rewritten to a series of if statements then we'd get it for free?

We would, but we'd lose the nice binary search properties. This should be an easy fix. I'll look soon.

**Comment by mdempsky** [comment]
The `string(byteSlice) == "string literal"` optimization doesn't extend to switch statements because we're actually doing:

    tmp := string(byteSlice)
    if tmp == "some_key" { ... }
    else if tmp == "another" { ... }

(And actually more complicated, because we handle runs of constants with binary search.)

One easy optimization we could do here is that in swt.go, if s.exprname.Op is OARRAYBYTESTR and **all of the cases are side-effect free** (at least no function calls or channel receives), we can rewrite the Op to ARRAYBYTESTRTMP.

It's important that we check for side-effects, because otherwise we'd miscompile expressions like:

    x := []byte{'a'}
    switch string(x) {
    case func() string { x[0] = 'b'; return "b" }:
        panic("FAIL")
    }
