### ISSUE TITLE
sync: add example for Cond

### ISSUE THREAD

**Issue by kevinburke** [golang/go#24952]
It would be nice to have a complete example for the Cond struct - signaling or broadcasting from one goroutine, and receiving it in another one.

**Comment by ianlancetaylor** [comment]
It's been tried before.  I'm pretty ambivalent.  The problem is that Go has better mechanisms for every simple use of a `sync.Cond`.  To get any benefit from a `sync.Cond` you need a relatively complex use case that is difficult to show in an example.  Personally I'm reluctant to write an example showing a simple use case of `sync.Cond`, because that implies that it would be a good choice for that simple use case, which I believe is not the case.

**Comment by bcmills** [comment]
Duplicate of #20491.

**Comment by kevinburke** [comment]
OK
