### ISSUE TITLE
x/tools/cmd/godoc: frequent “Indexing in progress” failures

### ISSUE THREAD

**Issue by bcmills** [golang/go#24965]
On some large fraction of queries to https://golang.org/search, I get an empty results page like the one shown below. If I reload, the error goes away.

It's the server's responsibility to find data to serve: we shouldn't push that off on the user. If indexing usually finishes quickly, we should just wait to serve the page until it's ready. Otherwise, we should prefer to serve stale data instead of an unhelpful error.

![screenshot 2018-04-20 at 01 38 33](https://user-images.githubusercontent.com/5200974/39032641-59502a44-443c-11e8-916e-c1624fc95baf.png)

**Comment by bcmills** [comment]
(CC: @stamblerre @alandonovan)

**Comment by ChrisALiles** [comment]
I’ve also been seeing this more frequently lately and would appreciate a fix.

**Comment by stamblerre** [comment]
I'm actually not familiar with this codebase, but I can look into it.

**Comment by meirf** [comment]
@stamblerre I was looking around this code for an unrelated search proposal I'm working on so I figured I'd post some notes to make myself useful in case my proposal falters.

I believe the message is set [here](https://github.com/golang/tools/blob/4e70a1b26a7875f00ca1916637a876b5ffaeec59/godoc/search.go#L67-L70):
```
if ts := c.FSModifiedTime(); timestamp.Before(ts) {
    // The index is older than the latest file system change under godoc's observation.
    result.Alert = "Indexing in progress: result may be inaccurate"
}
```

It looks like a reindex happens every 5 minutes: [initialization](https://github.com/golang/tools/blob/4e70a1b26a7875f00ca1916637a876b5ffaeec59/godoc/corpus.go#L111) (not set), [usage](https://github.com/golang/tools/blob/4e70a1b26a7875f00ca1916637a876b5ffaeec59/godoc/index.go#L1542-L1545) (use default). This is actually surprising to me since I recall getting the indexing message multiple times in a 10 minute window in what I remember to be off hours. So it's hard to believe that the filesystem is actually changing. Looks like `fsModified` is only set by `invalidateIndex` which is called by `initFSTree` which is called by `RunIndexer` in _every_ iteration of the forever loop. This tells me that it's not actually based on when fs changes. In any case, you can get more data and maybe prove me wrong by running in verbose mode and seeing timestamps from `UpdateIndex`'s logs and seeing if there were any commits between last index and the time you get the indexing alert.

> Otherwise, we should prefer to serve stale data instead of an unhelpful error.

That might just be removing the `if` code above.

> If indexing usually finishes quickly, we should just wait to serve the page until it's ready.

Maybe use a channel which `UpdateIndex`/`RunIndexer` sends on and then `Lookup` selects on that channel and a short ticket.

**Comment by agnivade** [comment]
> This tells me that it's not actually based on when fs changes.

That is correct. There was a separate issue (https://github.com/golang/go/issues/7524) which tracked changing this to respond to filesystem changes. But that was closed deciding that controlling the index_interval with the flag is good enough.

> That might just be removing the if code above.

Yes, looks like it. I agree that we should just return stale data instead of returning an error.

But then, this is for golang.org. So when it is deployed, it just indexes the standard library. There is no user code here. So, essentially nothing ever changes and we are just re-indexing anyways.

I would suggest setting the index_interval to 1 week or something. So that it effectively becomes a non-issue.

/cc @andybons

**Comment by agnivade** [comment]
Was going through the godoc flags today and realised that a negative `index_interval` just indexes once, effectively disabling indexing after that. I think we should set that for golang.org.

**Comment by broady** [comment]
Closing. Please re-open if you see this on golang.org again.

**Comment by agnivade** [comment]
@broady - I mean it's not a race condition "per se". Because the access is mutex protected.

Still, this `c.readIndex` should happen only _once_ when `godoc` starts. So even if users see the message, it should be for a very thin window, i.e. the time it takes to read the index file. The issue was about "frequent" indexing failures, which I don't think should be happening now.

I don't see any obvious way around this, unless you want to make `c.UpdateIndex()` synchronous ?

**Comment by broady** [comment]
It's a race between the `c.UpdateIndex` and the first incoming request to the search page.

Yes, in production mode, UpdateIndex should be synchronous (i.e., happen before incoming requests are handled).

That said, it doesn't really matter very much (see the last para in my previous comment).

**Comment by bradfitz** [comment]
@broady, do we still ship a pre-built index for golang.org on Flex?

**Comment by broady** [comment]
Yep, the index is built as part of the build process. We don't use a
spliced zip for goroot anymore.
