### ISSUE TITLE
x/vgo: command prompts help text improvements

### ISSUE THREAD

**Issue by hnlq715** [golang/go#24967]
### What version of Go are you using (`go version`)?
v1.10.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?

run this command below
```
vgo vendor -h
```

### What did you expect to see?
```
usage: vendor
Run 'vgo help vendor' for details.
```

### What did you see instead?
```
usage: vendor
Run 'go help vendor' for details.
```

And when I run this command `go vendor -h`, I get this result below.
```
go help vendor
Unknown help topic `vendor`. Run 'go help'.
```
Maybe all vgo command have the same problem.

**Comment by jimmyfrasche** [comment]
This isn't vgo specific.

I have an alias, `gotip`, for the devel version of the go tool but it refers to itself as `go` and not `gotip` in error messages. If it used `os.Args[0]` to create the help messages, it would always be correct.

Since vgo is a temporary fork and it's probably not that usual to have multiple versions of the go command unless you work on Go itself, I doubt the effort to fix the root cause would pay off in any meaningful way. But perhaps this is more common than I'm imagining?
