### ISSUE TITLE
x/vgo: install main package from arbitrary path?

### ISSUE THREAD

**Issue by kybin** [golang/go#24992]
The old `go get` downloads and install the main package, so the binary is automatically created.

The behavior seems invalid now in vgo.

If I run `vgo get` outside of go module directory like this

```
$ vgo get github.com/someone/program
```
It raises error `cannot determine module root; please create a go.mod file there`

I know it is expected, but the old behavior was convenient way of install main packages.

So will it just not supported any more? Or maybe I am missing something?

**Comment by kybin** [comment]
@myitcv Thanks, but vgo install also not working if I run it outside of go module directory.

**Comment by myitcv** [comment]
Sorry, I misunderstood the original post @kybin 

`vgo` will only work within a module:

```
cd `mktemp -d`
export GOPATH=$PWD
echo 'module "rubbish.com/blah"' > go.mod
vgo install github.com/cespare/reflex
```

In the meantime you need to use the `go` tool to do what you want.

When the functionality of `vgo` is merged into the main `go` tool, how the `go` tool should behave in this situation will be well defined.

I'll close for now because this is not expected to work in `vgo`, and let @rsc correct anything above or re-open in case that's necessary.

**Comment by kybin** [comment]
Ah, Okay. Thanks.
