### ISSUE TITLE
x/build/cmd/gerritbot: some pull requests are neither imported nor closed

### ISSUE THREAD

**Issue by ALTree** [golang/go#25020]
In #24938 a contributor sent a pull request against `release-branch.go1.9`. Gopherbot didn't import it into gerrit, but it also didn't close it.

If sending changes to the release branches is not something that is supposed to work, the bot should warn the author about that and then close the pull request.

cc @andybons

**Comment by dmitshur** [comment]
The current behavior is that GopherBot will import PRs into Gerrit (see https://github.com/golang/go/pull/40190 and https://go-review.googlesource.com/c/go/+/242279 for a recent example). However, it's still not possible to make cherry-pick CLs via PRs because of another problem, see #30037.

This is documented in the last paragraph of https://golang.org/wiki/MinorReleases#making-cherry-pick-cls:

> At this time, it's not possible to make a cherry-pick CL by sending a [Pull Request](https://github.com/golang/go/wiki/GerritBot). Only Gerrit is supported. See [golang.org/issue/30037](https://golang.org/issue/30037).

Let's use #30037 to track further improvements.
