### ISSUE TITLE
x/vgo: allow vendor at top level of build

### ISSUE THREAD

**Issue by rsc** [golang/go#25073]
We've agreed to preserve vendoring at the root of the top-level module in a build but we haven't worked out the details. That's this issue.

**Comment by akavel** [comment]
Related use-case/experience report: #24088

**Comment by kostix** [comment]
@rsc can we please have an environment variable—akin to that venerable `GO15VENDOREXPERIMENT`—which would enable the relevant `vgo` operations to always use `-getmode=local` (or whatever it will end up named)?

The reason is that while $enterprise borderline caching proxies are a good thing—in theory, in practice we here at $dayjob are not yet ready to deploy something like this and are already using vendoring as an almost perfect solution to combat both the different variants of the "left-pad problem" (including the "github is down" one) and the versioning problem—everyone get the set of vendored packages of blessed versions, and the vendored packages get upgraded by explicit manual intervention after much discussion and experimentation and tests.
We'd like this to be working as easy as it is now in perpetuity, if possible.
