### ISSUE TITLE
doc/effective_go.html: recommend the race detector

### ISSUE THREAD

**Issue by bcmills** [golang/go#25107]
The race detector is an invaluable tool for detecting bugs in Go programs; ideally, everyone should test with it (and use it before filing bugs or even getting very far into debugging failures).

_Effective Go_ is one of the major starting points for new Go developers, but the string “race detector” doesn't currently appear in it at all. We should update _Effective Go_ to recommend it.

**Comment by robpike** [comment]
I don't think Effective Go should start listing tools to run. That's a neverending tale. The document has been refreshingly stable, too, and it would be nice to keep it that way. Starting to maintain best practices for the ecosystem as well as for the language would break that. As it stands, the document doesn't even cover the libraries well (hardly at all, in fact), and I'm fine with that as well.

There is a kaboodle of stuff available for Go, and Effective Go has no need to encompass them. It's fine as it is.

Effective Go was written as a springboard for the language. It's still a good one, but rather than expand it I'd say go read K&D instead.

**Comment by ALTree** [comment]
@MaerF0x0 

```
The Go Programming Language (Addison-Wesley Professional Computing Series)
    Author: Alan A.A. Donovan and Brian Kernighan
    Publication Date: November, 2015
    ISBN: 978-0134190440
```

**Comment by MaerF0x0** [comment]
Gotcha . K&D is Alan Brian **K**ernighan and A.A. **D**onovan. Thankyou
