### ISSUE TITLE
runtime: "runtime·unlock: lock count" on Go 1.10.1 when cgo is enabled

### ISSUE THREAD

**Issue by SuperQ** [golang/go#25128]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go 1.10.1

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

amd64

### What did you do?

We have an application that makes use of CGO to collect kernel metrics.  When we compile with Go 1.9.5 or with 1.10.1 and CGO_ENABLED=0, we see no crashes.  With CGO enabled an Go 1.10.1 we see crashes.

Our test setup is documented [here](https://github.com/prometheus/node_exporter/issues/870#issuecomment-383914003).

### What did you expect to see?

No crashes

### What did you see instead?

```
fatal error: runtime·unlock: lock count
```

**Comment by daenney** [comment]
@bcmills Unforutunately the rest of the stack trace doesn't seem to get logged. I have no idea why. I ran tests with debug level logging enabled and eventually all I get is that throw. Aside from the normal logging before it done by the node exporter itself, part of the stack trace seems to just go missing. I don't know if that's a consequence of running this under systemd but I'm having a hard time seeing how that would cause part of the stack trace to go missing.

**Comment by daenney** [comment]
- I did a `go build -race` for the node exporter, no errors reported.
- I tried a `go build -msan` and simply got this:
  ```
  # runtime/cgo
  gcc: error: unrecognized argument to -fsanitize= option: 'memory'
  ```
  ```
  $ gcc --version
  gcc (GCC) 7.3.1 20180406
  ```
  I tried this with both Go 1.9.5 and 1.10.1, same story/error. Afaik `fsanitize=memory` is only valid for clang and has no equivalent to gcc. According to `go env` it correctly detected GCC: `CC="gcc"`. I'm guessing the Go tooling gets confused by the fact that `/usr/bin/cc` is symlinked to `/usr/bin/gcc` on Arch
- `env CC=clang env CXX=clang++ go build -msan` resulted in no errors
- Wrt constructing a smaller reproducer, I honestly have no idea where to start. Don't even know if it's in the node exporter itself or one of its dependencies that use a CGO thing. Any pointers on how one could go about tracking this down would be appreciated

**Comment by bcmills** [comment]
> Given it's related to CGO I did a quick search for `"C"` in the code base,

Maybe try searching for `runtime.SetFinalizer`? Given that the behavior changed between 1.9 and 1.10, a bad finalizer seems like one of the more likely causes. (I seem to recall that we had to fix several in the Google codebase during the internal 1.10 rollout.)

**Comment by daenney** [comment]
Thanks. The only call I could find was in logrus:

```
vendor/github.com/sirupsen/logrus/writer.go
44:	runtime.SetFinalizer(writer, writerFinalizer)
```

The code is here: https://github.com/sirupsen/logrus/blob/v1.0.4/writer.go#L21-L47. I have no idea if this looks sane or not. I don't see any import statements for C in logrus. The only thing mentioning runtime in Logrus is `writer.go`, in the import statements and that one call.

**Comment by daenney** [comment]
Can anyone theorize as to what might be causing the stack trace to just not show up?

```
Well, that didn't help.. the notimex variation crashed.

fatal error: runtime·unlock: lock count
fatal error: fatal: morestack on g0

And again, no other useful stack log.
```

**Comment by austin987** [comment]
FWIW, two users (myself and one more) have been able to get stacktraces. I've seen crashes a couple dozen times, not sure why this time was special.

My stack trace is here:
https://github.com/prometheus/node_exporter/files/2032750/node_exporter.log

The other is here:
https://github.com/prometheus/node_exporter/issues/870#issuecomment-390890270

**Comment by daenney** [comment]
@gopherbot Hey now, that's rude. We've provided some more info and asked for further help on how to possibly track it down. Waiting on Go project members here.

**Comment by ianlancetaylor** [comment]
Reopening because we did get a stack trace.

**Comment by ianlancetaylor** [comment]
I don't see anything useful in the stack trace in a quick look.

How reliable is the crash?  Does it fail every time or just occasionally?

Is there any way we can get a copy of the program to recreate the crash ourselves?

The cause is most likely memory corruption from the C code, or invalid cgo pointer passing (see https://golang.org/cmd/cgo/#hdr-Passing_pointers), but it's hard to be sure.

**Comment by SuperQ** [comment]
I can typically crash the node_exporter in about 30 minutes with 3 requests per second, but none of my crashes have provided a stack trace.  I will try and do some feature bisecting this week to see if I can pin it down to a part of the code that causes it.

**Comment by austin987** [comment]
[node_exporter-0.16.0-rc.2-go-1.10.1.tar.gz](https://github.com/golang/go/files/2043607/node_exporter-0.16.0-rc.2-go-1.10.1.tar.gz)

@ianlancetaylor This binary crashes for me pretty reliably, though often taking a few days.

Git repo: https://github.com/prometheus/node_exporter
Tarball for this binary: https://github.com/prometheus/node_exporter/archive/v0.16.0-rc.2.tar.gz

Option used to run it:
command_args="--collector.textfile.directory=/var/lib/node_exporter/ --collector.bonding --collector.buddyinfo --collector.ntp"

**Comment by aclements** [comment]
Unfortunately, in https://github.com/prometheus/node_exporter/files/2032750/node_exporter.log, the "fatal error: schedule: holding locks" happens when a goroutine is in the final throes of exiting (`runtime.goexit0`). The goroutine has already been marked dead, so we don't see it in the stack trace (though it probably wouldn't have any stack anyway, unless it called `runtime.Goexit`).

https://github.com/prometheus/node_exporter/issues/870#issuecomment-390890270 looks like it involves the recursive panic the CL I just sent should help with. But there's also a clear recursive malloc failure in there. That one *definitely* seems like memory corruption, since from the stack trace it's clear that there was no recursive malloc.

If it's possible to bisect this between Go 1.9 and Go 1.10, that could be very useful.

**Comment by hoffie** [comment]
> If it's possible to bisect this between Go 1.9 and Go 1.10, that could be very useful.
I am in the process of doing this. It seems like it has to do with `runtime.LockOSThread`.
My testing is focused on the difference between Go 1.9 and Go1.10. 
Others (@chrj) still observe this problem on go1.11beta2 as well.

I have provided some more (rather node_exporter-specific) analysis in https://github.com/prometheus/node_exporter/issues/870

Also, this issue looks very similar to https://github.com/golang/go/issues/22227 (except for the platform).

We currently do not have a "simple" reproducer as in "some tens of lines of code". However, this crashes pretty reliably for me (after ~1-10 minutes):
`GOMAXPROCS=2 ./node_exporter --no-collector.arp --no-collector.bcache --no-collector.bonding --no-collector.conntrack --no-collector.cpu --no-collector.diskstats --no-collector.edac --no-collector.entropy --no-collector.filefd --no-collector.filesystem --no-collector.hwmon --no-collector.infiniband --no-collector.ipvs --no-collector.loadavg --no-collector.mdadm --no-collector.meminfo --no-collector.netdev --no-collector.netstat --no-collector.nfs --no-collector.nfsd --no-collector.sockstat --no-collector.stat --no-collector.textfile --no-collector.time --no-collector.timex --no-collector.uname --no-collector.vmstat --no-collector.netclass --no-collector.xfs --no-collector.zfs`

The error messages vary between:
- `fatal error: runtime·unlock: lock count`
- `fatal error: systemstack called from unexpected goroutine`
- `panic during panic`
- `fatal: morestack on g0`
Sometimes its one line, sometimes its thousands lines of repeated error messages. Sometimes with stack traces, sometimes with cleanly formatted stack traces, sometimes with broken stack traces (interleaved with fatal error messages).

Will update when I've traced down the actual Go commit which makes the difference here.

**Comment by hoffie** [comment]
One of the nicest stack traces so far (with yet another error message: `fatal error: fatal error: stopm holding locks`): https://gist.github.com/hoffie/ae0fab8aeac60d6283233eeccfe93823
And another one: https://gist.github.com/hoffie/3f55ea14cf977c86d086ac2c9830d55c

The bisect ended by pointing to 4f34a5291317fe959074fb40b85d9be242b8a2fc as the first bad commit. Will verify in the coming days (Go at the mentioned commit definitely contains the problematic change [it crashes]; to verify it is indeed the causing change, I'll have to run some long-term test on the previous commit to make sure).

BTW, `GOMAXPROC=1` seems to avoid this issue.

**Comment by marcan** [comment]
Keep in mind that just because bisect points at a commit does not mean the commit is bad. It could be a perfectly correct commit that is just exposing an issue that already existed. I could certainly see how thrashing OS threads more often by forcing termination when a locked goroutine exits could expose other issues (e.g. memory corruption) elsewhere.

**Comment by squeed** [comment]
Interesting; @mdlayher managed to stop the bug by adding a `runtime.UnlockOSThread()`. Before that, the process was just letting the g die. The bisected change is to let the associated m die when a locked g dies.

If I had to guess, the call sequence is
* g dies
* `gogo(&_g_.m.g0.sched)`, which should be mstart
* `mstart`
* `mstart1`
* `stopm`
* panic

So, how the heck is mstart() being called with locks set?

**Comment by marcan** [comment]
FWIW I'm having rather hit and miss results reproducing - I had it crash in 2 seconds once, but other times it's taking 30 minutes to hours. I'm using vegeta at ~200qps. It doesn't seem like the crashes scale linearly with load. I'm switching to ApacheBench now (which unlike vegeta can max out performance at ~1000 requests/sec without triggering runaway thread creation) but I'm not sure it'll make much of a difference.

It would be helpful to improve reproducibility, otherwise tracking this down is going to be a huge pain. Anyone have any hints?

**Comment by marcan** [comment]
Interestingly, I left it all night running with ApacheBench (at ~800 qps) and it didn't crash. So either there's something different about how ApacheBench does things, or actively having requests always queued prevents the issue from reproducing.

**Comment by mdlayher** [comment]
I was able to cause a couple of interesting crashes this morning.  While I can't fully rule out memory corruption at this point, the race detector-instrumented program crashed before pointing out any data races.  I'm not using very much `unsafe` in these code paths in the package but I'll double check them.

```
matt@nerr-2:~$ go version
go version go1.10.3 linux/amd64
matt@nerr-2:~$ uname -a
Linux nerr-2 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Program: https://github.com/mdlayher/netlink/blob/master/cmd/nlstress/main.go

`go build` + `GOTRACEBACK=crash ./nlstress`: https://gist.github.com/mdlayher/a46edb0cb062a961431ebaad741b5b24
`go build -race` + `GOTRACEBACK=crash ./nlstress`: https://gist.github.com/mdlayher/2079ac2ed8201f183c8de043c8882e14

I'll try again with the following patch applied to see if it makes a difference if I unlock the OS thread when the syscall-handling goroutine exits.

```diff
✔ ~/src/github.com/mdlayher/netlink [master|…1] 
12:16 $ git diff --patch
diff --git a/conn_linux.go b/conn_linux.go
index aeaa38a..5639fb5 100644
--- a/conn_linux.go
+++ b/conn_linux.go
@@ -325,6 +325,7 @@ func newSysSocket(lockThread bool) *sysSocket {
                        // the goroutine exits starting in Go 1.10:
                        // https://go-review.googlesource.com/c/go/+/46038.
                        runtime.LockOSThread()
+                       defer runtime.UnlockOSThread()
                }
 
                defer wg.Done()
```

**Comment by squeed** [comment]
From my perspective, the question is whether or not the bug is purely runtime, or some interaction between the program and the runtime.

In other words, if you create, lock, and kill a bunch of Ms *without* any cgo, unsafe calls, or syscalls, will we still see this crash?

So, I'm running some tests as well. I suspect at least one other factor will be required, and this is not a pure runtime bug.

**Comment by bcmills** [comment]
A lot has changed in the runtime since Go 1.10. 😅

Is anyone on this thread still seeing these failures? They were showing up on the Go builders for a while, but it's not clear to me that the handful of failures there are particularly related to the original report.

`greplogs --dashboard -md -l -e 'runtime.unlock: lock count'`

[2021-11-16T17:13:33-29ec902/freebsd-386-12_2](https://build.golang.org/log/ff742520f5abfc9b38d4ac25ab51a1527d332595)
[2021-11-03T18:37:22-3a5865c-cfd016d/netbsd-amd64-9_0](https://build.golang.org/log/638a7b3a95acd4b40048d3e9fbcc3608d201b12f)
[2021-04-01T15:50:43-45ca9ef/linux-arm-scaleway](https://build.golang.org/log/6872a6587e933903fd2d1436aba4717905442e31)
[2021-04-01T01:26:29-5f646f0/linux-arm-scaleway](https://build.golang.org/log/e47f30bf0ddca80d1556b208e9fb4fbd7032b27a)
[2021-04-01T00:51:26-ec721d9/linux-arm-scaleway](https://build.golang.org/log/297da6b61441509dc05582bb125456b897d36b18)
[2021-04-01T00:51:24-1f29e69/linux-arm-scaleway](https://build.golang.org/log/fe72862d60bc680812c568220073d1a17fba4463)
[2021-04-01T00:51:23-3304b22/linux-arm-scaleway](https://build.golang.org/log/3f256a943ecefc3f1ae80f45f24abf187345602f)
[2021-03-31T20:21:57-5d6581d/linux-arm-scaleway](https://build.golang.org/log/df2c6a43a797b66726cb3dbdf970f9bb402d6069)
[2020-12-15T16:30:24-5046cb8/plan9-arm](https://build.golang.org/log/7aff4e439ef47ccfe9d0af49b8074cfc53ed7ebb)
[2020-11-19T19:30:38-e73697b/plan9-arm](https://build.golang.org/log/0a5794006b56b69564ae3a10fd5abba5c7a38de8)
[2020-05-05T18:32:35-8627b4c/plan9-arm](https://build.golang.org/log/1c7daa02da7d5fbcde0242dc4e45b73a900f299d)
[2020-05-05T18:05:10-a8e83d5/plan9-arm](https://build.golang.org/log/dcf4532055aa55924bebab239373c32ec47e1616)
[2020-05-05T15:41:37-b4ecafc/plan9-arm](https://build.golang.org/log/f00f21f6c94d95ef58d7b5c1ce3f74108a9f692e)
[2020-05-05T05:13:26-9b18968/plan9-arm](https://build.golang.org/log/384a7b71f403708e77b3a98ccd333f00e4342bf8)
[2020-05-05T00:36:44-c9d5f60/plan9-arm](https://build.golang.org/log/63569def204b33a9a286087c5294be79a8ffd9bb)
[2020-05-04T17:40:00-a1ffbe9/plan9-arm](https://build.golang.org/log/3ebcce44b804c387fe7c3e89ec992fcfd3a0ee77)
[2019-11-07T14:53:38-e8f01d5/linux-arm64-packet](https://build.golang.org/log/fa0404faee9f0cf8cd2cfe0c7e61d5d91c56ab04)
[2019-11-07T14:51:06-543c6d2/linux-arm64-packet](https://build.golang.org/log/77ad8084bb659c40f2dd5fc1c59d04a137147200)
[2019-11-07T09:32:43-3b1ae30/aix-ppc64](https://build.golang.org/log/3853d6e2ac4bcb8effad4e27dbeb06f055a8f341)
[2019-11-07T09:32:43-3b1ae30/solaris-amd64-oraclerel](https://build.golang.org/log/9f2a026d269b0c8b518967a476241c2c04c84910)
[2019-11-07T08:25:32-7a2baa9/aix-ppc64](https://build.golang.org/log/491775aa38ac8519148190b8022f74e0a08af427)
[2019-11-07T06:58:44-f5949b6/aix-ppc64](https://build.golang.org/log/80975430aedeba3633753d5970a8f6f5548f9367)
[2019-11-07T06:58:44-f5949b6/linux-arm64-packet](https://build.golang.org/log/8da24351774c9b85b6016594aeb32782fa11fa0b)
[2019-11-07T06:58:44-f5949b6/solaris-amd64-oraclerel](https://build.golang.org/log/104089fa263d99c94b01f4ac136bfaef7300d472)
[2019-11-07T05:59:33-a8f57f4/aix-ppc64](https://build.golang.org/log/61b5b46e5d6c159c8699c277f007f9d252928669)
[2019-11-07T05:59:33-a8f57f4/linux-arm64-packet](https://build.golang.org/log/40361c2d5d7a8cd5df1a49db496c265e4ed07c32)

**Comment by daenney** [comment]
I completely forgot about this thing. At least with regards to the node exporter I've not experienced anything like this in the past 2 years. It's most likely safe to close at this point.

**Comment by cpuguy83** [comment]
I hate a similar issue here: https://github.com/containerd/containerd/actions/runs/3237587338/jobs/5304881990#step:9:56393
This is from this change https://github.com/containerd/containerd/pull/7513 which is purposefully not calling `runtime.UnlockOSThread`  after a `unix.Unshare(unix.CLONE_FS)`

**Comment by cpuguy83** [comment]
This is with go1.19.2.
