### ISSUE TITLE
tour: Errore grammaticale in basics/6

### ISSUE THREAD

**Issue by dariodip** [golang/go#25231]
Contesto: https://go-tour-ita.appspot.com/basics/6

"La funzione swap ritorna due stringhe." dovrebbe essere "La funzione swap restituisce due stringhe."

**Comment by ALTree** [comment]
Tradurre "returns" con "ritorna" non è così inusuale, è qualcosa che ho già visto fare in libri tradotti dall'inglese.

Detto questo, le traduzioni del tour non sono parte del progetto e non ne gestiamo il deployment, sono controllate da utenti esterni... suggerisco di contattare la persona che gestisce `go-tour-ita.appspot.com`.

Closing here, since we don't control the tour translations.
