### ISSUE TITLE
cmd/compile: use expandable columns in ssa.html?

### ISSUE THREAD

**Issue by josharian** [golang/go#25286]
As the number of SSA passes has grown, ssa.html has gotten wider and thus harder to navigate. I'd like to float the idea of having the initial display show just a few columns, with the others be expandable stubs (with names). As to the initial list of columns, maybe something like: start, after early deadcode, after opt, after lower, after late deadcode, after regalloc, genssa.

There's also the question of whether this can be reasonably implemented in standalone javascript, a question about which I know little.

Opinions?

cc @dr2chase @randall77 @cherrymui

**Comment by randall77** [comment]
Yes, please.
It is not possible that your javascript knowledge is less than mine.

**Comment by ysmolsky** [comment]
@josharian is it okay when you reload ssa.html [in a browser] you would get to default state of collapsed columns?

**Comment by josharian** [comment]
Yes. It’d be nice to do some saved local state or query params, but as a first pass, I think always reverting to the default is fine. In the normal case I imagine the reader will be interested in one or two columns at most, so restoring state manually isn’t that big a deal.

**Comment by ysmolsky** [comment]
In case if you want to give a feed without downloading the patch above:

<img width="1265" alt="screen shot 2018-06-12 at 00 12 42" src="https://user-images.githubusercontent.com/140245/41257421-76db07e2-6dd5-11e8-988b-3a8ba1c8a280.png">

<img width="1250" alt="screen shot 2018-06-12 at 00 13 50" src="https://user-images.githubusercontent.com/140245/41257445-86f23f88-6dd5-11e8-8ea5-82f230506836.png">

The vertical text can be expanded by clicking on it. If you want something else, just let me know. I would be glad to help because I learned a thing or two about SSA while making the change. Also I would like to implement some of the TODOs buired in ssa.go regarding graphic representation (nodes->ssa?) or maybe just dumping the log from ssa to the ssa.html, so file can be shared a standalone piece. cc @josharian
