### ISSUE TITLE
x/build: upgrade FreeBSD builders to avoid flakes

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#25289]
[2018-05-01T14:50:33-7f6105f/freebsd-386-11_1](https://build.golang.org/log/845c46605a44378d66eddf83de3f4bfdb235062e)
[2018-05-01T18:22:06-a5b80d4/freebsd-amd64-11_1](https://build.golang.org/log/e6e429c57f80df0df5db2ca76ec0d9639dedcd53)
[2018-05-02T17:52:14-e8d417d/freebsd-amd64-11_1](https://build.golang.org/log/da1d85c4b1b4607ba1f6441ab8874ee563d22875)
[2018-05-04T14:47:49-166c37a/freebsd-386-11_1](https://build.golang.org/log/44cc3294af93eb055a81fb1e1e18a794d341e0f3)
[2018-05-05T00:53:45-2a7e19e/freebsd-amd64-11_1](https://build.golang.org/log/0985d9ec9a68c5a7171dd9d595cfeda6a546bc92)
[2018-05-05T00:54:52-f7c767e/freebsd-amd64-11_1](https://build.golang.org/log/26b8c9ace0db131a98d072c69f3eb958e546a714)
[2018-05-06T04:28:23-a8a60ac/freebsd-386-10_3](https://build.golang.org/log/202636bd6ff15fab100f4f77cf0876668fe02290)
[2018-05-08T13:29:22-b00f72e/freebsd-386-11_1](https://build.golang.org/log/c1b277ec8e3ed233ca7609473001e19222c0fa91)

findflakes reports

```
First observed 7f6105f 01 May 14:50 2018 (92 commits ago)
Last observed  b00f72e 08 May 13:29 2018 (0 commits ago)
100% chance failure is still happening
7.6% failure probability (8 of 93 commits)
Likely culprits:
    8% 7f6105f net, syscall: make ECONNRESET/ECONNABORTED only temporary for Accept
    7% 1129ec2 database/sql: trivial documentation fixes
    6% 60c76f7 cmd/compile: optimize bvec routines
    6% d91e970 runtime: avoid unnecessary scanblock calls
    6% dda4591 runtime: add BenchmarkScanStack
    5% 9ecf899 cmd: remove some unnecessary gotos
    5% 030ac2c cmd/doc: skip directories like other go tools
    4% 8c67ca1 cmd/compile: apply TODO now that gcCompat is gone
    4% 16d1a8e runtime: move open/close/read/write from syscall to libc on Darwin
    4% ce5c387 runtime: move more syscalls to libc on Darwin
No known past failures
```

**Comment by ayang64** [comment]
I just ran this test on 12-CURRENT and 11.1-RELEASE-p4 and it passed.

**Comment by ianlancetaylor** [comment]
@ayang64 Thanks.  To be clear, the test normally passes.  As the message above suggests, it is only failing about 7.6% of the time.  How many times did you run the test?

**Comment by ayang64** [comment]
I just tried 10000 times under 12-CURRNET (02bd6c4)  and 12.0-CURRENT (58e53e526dc) and 500 under 11.1-RELEASE-p4 with no failures.

**Comment by ianlancetaylor** [comment]
Great, thanks!

Changing this issue to upgrade our builders.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bradfitz** [comment]
FreeBSD people, is it reasonable to take down our 10.3 and 11.1 builders and replace them with 10.4 or 11.2? I'd rather not double the number of FreeBSD builder's we're running, but we could if necessary. I don't know what versions are important/commonly used in practice.

/cc @dmitshur

**Comment by paulzhol** [comment]
@bradfitz our builders are horribly out of date, for eg. our 11.1 builder is 11.1-RELEASE and is missing around a year worth of security patches and updates (~15 of them).
10.3-RELEASE was released in April 4, 2016 and was marked EoL since April 30, 2018 (that's over two years of missed updates).

Unfortunately 11.1 is expected to receive EoL on the 30th of September, and 10.**4** a month after that.
https://www.freebsd.org/security/security.html#sup

I think we have no choice but to switch the 10.3-RELEASE to 10.4-RELEASE-p13. Maybe it's worth while having a 11.1 builder as well, but I'd rather we update it to 11.1-RELEASE-p15 if we'd need to test future Go 1.10/1.11 releases?

**Comment by ayang64** [comment]
Since 10.4 and 11.2 are currently supported releases (even though they're close to EoL), I think it is reasonable to bump up the revs used by the builders.

It may also be helpful to start eyeing a 12.0 builder since it is due in Novemberish.

It looks like there are a few system call/ABI changes in 12 that might need addressing.  I wonder how incompatibilities across GOOS versions are handled.  It might be useful to be able to target FreeBSD 11.x and FreeBSD 12.x as separate GOOS.

**Comment by bradfitz** [comment]
>  It might be useful to be able to target FreeBSD 11.x and FreeBSD 12.x as separate GOOS.

That introduces a bunch of complexity which we don't want for ourselves or our users. Making it Just Work is much more preferred.

**Comment by paulzhol** [comment]
@bradfitz can we drop the 10.3 (and maybe 11.1) builders so that we can remove the workaround for regular files being added to kqueue (https://github.com/golang/go/issues/19093)?

**Comment by bradfitz** [comment]
@paulzhol, not until Go 1.13 (#27619).

**Comment by bradfitz** [comment]
I rebuilt the FreeBSD amd64 image with https://golang.org/cl/155977 & updated the coordinator from git rev 7b78c2042368d5c56ee9dbd92ab5fa988c763944 to 9730d8b657054ead7ffc67bfb2dff24b89a368a5
