### ISSUE TITLE
x/vgo: ignores the specified version and changes it to a random version

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#25375]
### What version of Go are you using (`go version`)?
```
┏━ oneofone@Ava ❨☯/g/x/vgo❩ ❨master❩
┗━━➤ vgo version && git describe --always
go version devel +903f095c1a 2018-05-10 20:54:21 +0000 linux/amd64 vgo:2018-02-20.1
9271c4f
```

Bug repo: https://github.com/OneOfOne/vgo-bug

### Starting with just `module github.com/OneOfOne/vgo-bug` in go.mod:

1. `go get github.com/OneOfOne/vgo-bug` (`go` *not* `vgo`).

2. `cd $GOROOT/src/go get github.com/OneOfOne/vgo-bug`.

3.

```
➤ vgo build
vgo: resolving import "github.com/alecthomas/kingpin"
vgo: finding github.com/alecthomas/kingpin (latest)
vgo: adding github.com/alecthomas/kingpin v1.3.7
vgo: resolving import "github.com/alecthomas/units"
vgo: finding github.com/alecthomas/units (latest)
vgo: adding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf

➤ cat go.mod
module github.com/OneOfOne/vgo-bug

require (
        github.com/alecthomas/kingpin v1.3.7 <<<
        github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
)
```

4. edit go.mod and change `v1.3.7` to `v2.2.6` (latest on github).

5.

```
➤ vgo build
vgo: resolving import "github.com/alecthomas/template"
vgo: finding github.com/alecthomas/template (latest)
vgo: adding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc

➤ cat go.mod
module github.com/OneOfOne/vgo-bug

require (
        github.com/alecthomas/kingpin v0.0.0-20171217180838-947dcec5ba9c
        github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
        github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
)

➤ vgo list -m
MODULE                          VERSION
github.com/OneOfOne/vgo-bug     -
github.com/alecthomas/kingpin   v0.0.0-20171217180838-947dcec5ba9c
github.com/alecthomas/template  v0.0.0-20160405071501-a0175ee3bccc
github.com/alecthomas/units     v0.0.0-20151022065526-2efee857e7cf
```

This isn't the same as #24585, however it *might* be a dup of #25007 based on the last comment in it.

**Comment by bcmills** [comment]
Here's what I think is going on:

If you change the major version in `go.mod`, you also need to change the major version in the import path (in the `.go` source files). Only `v0` and `v1` can have unversioned import paths (see https://research.swtch.com/vgo-import), which is why `vgo` accepts `v1.3.7` initially.

When you change the version to `v2.2.6`, `vgo` checks for a corresponding tag or branch in the repo. It successfully finds a tag in the repository, but without a semantic import path it isn't willing to consider that to be an actual major version: it can't coexist with some other major version at the same import path. So instead, `vgo` resolves the tag to a commit ([947dcec5ba9c](https://github.com/alecthomas/kingpin/commit/947dcec5ba9c011838740e680966fd7087a71d0d)) and records that commit itself as a “pseudo-version” (see https://research.swtch.com/vgo-module).

When version selection occurs, the pseudo-version commit will be used to resolve the `v0` import path (that is, the import path without a major-version component), not the `v2`-suffixed import path (which will be resolved separately).

**Comment by OneOfOne** [comment]
That makes sense, but IMHO this needs to be fixed in vgo, a lot of repos are already using v2+ tags, not adding a way to support them and assuming they will add vgo support on their own is really gonna be painful to deal with.

**Comment by OneOfOne** [comment]
It's rather confusing that vgo modifies the file on read-only operation (vgo list, vgo build, etc).

**Comment by OneOfOne** [comment]
@bcmills #25412 explains it better than me, while it is a dup of this, his explanation is much better than mine so feel free to mark this as a dup of it.

**Comment by bcmills** [comment]
Ok, will follow up on #25412.
