### ISSUE TITLE
reflect: the docs of StructOf should mention embedding types with too many method will panic.

### ISSUE THREAD

**Issue by dotaheor** [golang/go#25402]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package main

import "fmt"
import "reflect"
import "time"

func main() {
	type T = struct {
		time.Time
	}
	fmt.Println(reflect.TypeOf(T{})) // struct { x int }
	
	var n time.Time
	tn := reflect.TypeOf(n)
	// panic: reflect.StructOf: too many methods
	tt := reflect.StructOf([]reflect.StructField{
		{Name: "Time", Type: tn, Anonymous: true},
	})
	fmt.Println(tt)
}

```

### What did you expect to see?

not panic, or document it.

### What did you see instead?

panic

**Comment by dotaheor** [comment]
btw, gccgo also panics for this example, but with a different reason
```
panic: reflect.StructOf: embedded field with methods not implemented
```

**Comment by ianlancetaylor** [comment]
I haven't looked at this case, but the reflect package is closely tied to the compiler, since the compiler generates the data structures that it uses, and there are significant differences in the implementation of the reflect package for gc and gccgo.

**Comment by jamdagni86** [comment]
@ianlancetaylor - the number of Exported methods in time.Time is 38 and it looks from the [code](https://github.com/golang/go/blob/master/src/reflect/type.go#L2569) that only 32 methods are supported; that's the reason for the panic. 

Let me know if this issue needs to be fixed.

**Comment by ianlancetaylor** [comment]
Yes, this should be fixed, possibly in the documentation, but it would be better to fix the code.

**Comment by jamdagni86** [comment]
The code inside the individual case statements seems outdated (because of subsequent code changes). [This](https://go-review.googlesource.com/c/go/+/21285/7/src/reflect/type.go#2513) is the original implementation and [this](https://go-review.googlesource.com/c/go/+/41871/1/src/reflect/type.go#2722) the next change to the code. Because of the latter, the variable `t` declared inside each of the case statements has become redundant. Statements at 2590 & 2593 have no meaning anymore and 

https://github.com/golang/go/blob/1174ad3a8f6f9d2318ac45fca3cd90f12915cf04/src/reflect/type.go#L2566-L2596

can potentially be replaced by

```go
typ := &structType{}
ut := &uncommonType{}
``` 
I made a quick test by doing the change, and it seemed to work. 

If the changes are OK, I will do further testing on the same and send a PR for the same.

**Comment by jamdagni86** [comment]
There are two places from where the []methods field gets populated -

1. src/cmd/compile/internal/gc/reflect.go:dextratypeData - compile time. This writes the methods of the given object as an array
2. src/reflect/type.go:StructOf (this bug is from here)

My first solution was to have a struct `structTypeDynamic` like

```go
type structTypeDynamic struct {
	structType
	u uncommonType
	m []method
}
```

and do

```go
default:
	t := new(structTypeDynamic)
	typ = &t.structType
	ut = &t.u
	t.m = make([]method, len(methods))
	copy(t.m, methods)
}
```

This would also require a change in `uncommonType.exportedMethods` as

```go
return (*(*[]method)(add(unsafe.Pointer(t), uintptr(t.moff), "t.xcount > 0")))[:t.xcount:t.xcount]
```

The above code assumes the underlying array is a slice. However, `dextratypeData` writes the backing `[]methods` as array and the `uncommonType.exportedMethods` method would fail.

The simplest fix for this bug is to introduce `structTypeFixed64` (and may be `structTypeFixed128`, like `funcTypeFixedX`) and add another case statement.

```go
case len(methods) <= 64:
	t := new(structTypeFixed64)
	typ = &t.structType
	ut = &t.u
	copy(t.m[:], methods)
```
Only problem with this approach is, we might still end up with a `panic` in case the number of methods is more than 64 (or 128). But I guess, that's still OK considering 64 (or 128) methods is already way too many methods to have on a type.

@ianlancetaylor let me know if the solution looks ok. I will send a PR for the same.

**Comment by ianlancetaylor** [comment]
If you're willing to do a little work, I think the correct approach is for `StructOf` to determine the right number of methods, and then call itself recursively to create a struct type with space for the right number of methods.  We know that that struct type won't itself require any methods.

**Comment by jamdagni86** [comment]
Let me try it out!

**Comment by jamdagni86** [comment]
@ianlancetaylor one other thing I can do to fix this.

Add a flag argument to `uncommonType` called `methodStorageSlice` and modify the the following lines 
https://github.com/golang/go/blob/1174ad3a8f6f9d2318ac45fca3cd90f12915cf04/src/reflect/type.go#L2569-L2596
to
```go
	switch {
	case len(methods) == 0:
		t := new(structTypeUncommon)
		typ = &t.structType
		ut = &t.u
	default:
		t := new(structTypeDynamic)
		typ = &t.structType
		ut = &t.u
		t.m = make([]method, len(methods))
		copy(t.m, methods)
	}
``` 

and set `methodStorageSlice` to `true`.

In the methods `uncommonType.exportedMethods` and  `uncommonType.methods`, we'll have to look for this flag and cast the `unsigned.Pointer` to either an array or a slice.

It would look like:

```go
        methodPtr := add(unsafe.Pointer(t), uintptr(t.moff), "t.xcount > 0")
	if t.methodStorageSlice == true {
		methods = (*[1 << 16]method)(methodPtr)[:t.xcount:t.xcount]
	} else {
		methods = (*(*[]method)(methodPtr))[:t.xcount:t.xcount]
	}
	return methods
```

**The same has to be replicated in `runtime` package as well.**

I would have liked a cleaner approach than this to fix the issue. But this is the only thing I could think of. 

Please let me know!

**Comment by ianlancetaylor** [comment]
@jamdagni86 Sorry, I didn't notice your comment of 22 days ago, and when I read it now I don't understand it.  I'm suggesting that instead of using the existing `structTypeFixedNN` types, which already come with the method arrays where you want them, that if you need space for 100 methods, you have `StructOf` call itself recursively to construct the equivalent of `structTypeFixed100`.

**Comment by ianlancetaylor** [comment]
Before discussing your suggestion, can you explain why you don't want to use my suggestion?  The advantage of the approach that I suggested above is that we allocate memory with the correct type, which simplifies the interface to the garbage collector.

**Comment by jamdagni86** [comment]
As I mentioned in my earlier comment, I can not call `StructOf` recursively since `structType` and `uncommonType` structs have methods. This would result in an infinite recursion. 

Please let me know if I'm missing something :-)

**Comment by ianlancetaylor** [comment]
They have a fixed number of methods.  Can we predefine that specific type?

**Comment by jamdagni86** [comment]
Yeah. I was wrong about infinite recursion though. This worked without infinite recursion, not sure why. 
I will verify it before sending the PR.

```go
switch {
	case len(methods) == 0:
	t := new(structTypeUncommon)
	typ = &t.structType
	ut = &t.u
default:
	tt := New(StructOf([]StructField{
		{Name: "S", Type: TypeOf(structType{})},
		{Name: "U", Type: TypeOf(uncommonType{})},
		{Name: "M", Type: ArrayOf(len(methods), TypeOf(methods[0]))},
	}))

	typ = (*structType)(unsafe.Pointer(tt.Pointer()))
	ut = (*uncommonType)(unsafe.Pointer(tt.Pointer() + unsafe.Sizeof(*typ)))

	copy(tt.Elem().FieldByName("M").Slice(0, len(methods)).Interface().([]method), methods)
}
```
