### ISSUE TITLE
question: channel support multiple parameters

### ISSUE THREAD

**Issue by egorse** [golang/go#25428]
I bet this being asked before but can not find the issue :(
Was there any proposal (dismissed?) to extend channel spec from:
```
ChannelType = ( "chan" | "chan" "<-" | "<-" "chan" ) ElementType .
```
to 
```
ChannelType = ( "chan" | "chan" "<-" | "<-" "chan" ) ChanElementType .
ChanElementType = Parameters | Type .
```

So it would be possible to do
```
ch := make(chan (net.Conn, error))
...
func server() {
    ...
    for { 
        ch <- ln.Accept()
    }
}
...
func accept(net.Conn, error) {
  ....
}

func main() {
    go server()
    for {
        accept(<-ch)
    }
}
```
If it would works within scope of package only that would be ok.
[Anon] structs are fine but requires manual pack\unpack :(

**Comment by mvdan** [comment]
I don't know if this was ever considered, but I would imagine that its inclusion would make the language inconsistent. Why should `chan (T1, T2)` work if others like `[](T1, T2)` and `map[string](T1, T2)` would not?

After all, like you say, it's only a matter of syntactic sugar. Have you considered simply writing a wrapper type around the channel?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  See https://golang.org/wiki/Questions .  Or if you want to make a proposal for a language change, see https://github.com/golang/proposal/blob/master/README.md .

The answer to your question is: yes, it was considered, early in the development of the language.  We decided against it because 1) tuples are not a first class concept in Go; 2) with the current syntax it fails if you want to send two values on the channel and the second value has type `bool`, because that is ambiguous with the current `val, closed = <-c` syntax.
