### ISSUE TITLE
x/build/devapp: show GitHub usernames for CLs from PRs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25447]
Gerritbot brings in PRs to Gerrit with the author "Gerrit Bot", and this makes its way to the dev dashboard:

https://dev.golang.org/reviews?owner=Gerrit%20Bot

We should show GitHub usernames there instead.

/cc @andybons @bcmills @FiloSottile

**Comment by dmitshur** [comment]
We also have issue #23964, which is the root problem. When/if that is resolved, this issue will be obsolete.

If that issue is lot of work and takes a long while, while this one is quick and easy, it might be worth it to solve it with a "// TODO: remove when golang.org/issue/23964 is resolved" comment.

**Comment by dmitshur** [comment]
This is an old bug that happens to be resolved by now. PRs still have "GerritBot" as the CL uploader, but the CL author field is being set correctly, so https://dev.golang.org/reviews shows people's names for PRs. Closing.
