### ISSUE TITLE
test/codegen: wrong test cases not detected

### ISSUE THREAD

**Issue by benshi001** [golang/go#25452]
The following test case in memcombine.go is wrong, the MOVH is never generated, and still two MOVB remain there. But the codegen test framework does not detect that failure.

	func zero_byte_2_idx(b []byte, idx int) {
		// arm64: `MOVH\sZR,\s\(R[0-9]+\)\(R[0-9]+<<1\)`,-`MOVB`
		b[(idx<<1)+0] = 0
		b[(idx<<1)+1] = 0
	}

The failure can only be detected in the below form

	func zero_byte_2_idx(b []byte, idx0 int) {
		b[(idx0<<1)+0], b[(idx0<<1)+1] = 0, 0 // arm64:`MOVH\sZR,\s\(R[0-9]+\)\(R[0-9]+<<1\)`,-`MOVB`
 	}

**Comment by benshi001** [comment]
cc @cherrymui @williamweixiao

**Comment by benshi001** [comment]
cc @randall77 @rasky

**Comment by josharian** [comment]
Can we trim whitespace? I can very easily see myself making that mistake—and am wondering now whether I already have.

**Comment by rasky** [comment]
Technically, it should be a syntax error, but since parsing is made with a regexp, the regexp simply doesn't match and there's no obvious way to tell a comment line in English from a command line with a syntax error -- both don't contain a regexp match. Stripping whitespace is a workaround for this specific bug, but any other syntax error can possibly cause the same problem.

I've sent a CL to strip whitespaces.

**Comment by benshi001** [comment]
Thank you. @rasky
