### ISSUE TITLE
access: make Jimmy Frasche a GitHub "collaborator"

### ISSUE THREAD

**Issue by josharian** [golang/go#25488]
In https://github.com/golang/go/issues/21303#issuecomment-389027461, @jimmyfrasche observed that an issue was "locked and limited to collaborators." I was surprised to learn that he was not already a "collaborator", whatever that is. He has been a thoughtful and helpful voice on many discussions for a long while now. I suggest that he be given more GitHub permissions.

cc @andybons @spf13 @bradfitz @jimmyfrasche 

(Aside: There's a special GitHub team for the proposal team. Should there be one for the open source / community / whatever-this-is team?)

**Comment by ALTree** [comment]
I don't think we ever used the "collaborator" category. We only use "owner" or "member". 

A collaborator is short for "external collaborator", which is a person that has access to a specific repo but it's not a member of the organization. This makes sense for a repository like "google/pprof" because you may want to add someone to pprof without making him/her part of the "google" organization. But Go uses its own organization ("golang"), so being a member of the organization or being added as external collaborator to the golang/go repository it pretty much the same thing.

**Comment by bradfitz** [comment]
I thought I already did this, but perhaps I used the wrong group.

Done.
