### ISSUE TITLE
Installing github.com/sqs/goreturns FAILED

### ISSUE THREAD

**Issue by tharun-d** [golang/go#25641]
Installing github.com/sqs/goreturns FAILED

1 tools failed to install.

goreturns:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/sqs/goreturns
# cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns; git config remote.origin.url
package github.com/sqs/goreturns: remote origin not found
# cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns; git config remote.origin.url

**Comment by agnivade** [comment]
@tharun-d - Thank you for raising the issue. Unfortunately, you have deleted the entire issue template, so there is no additional debug info about your system.

This looks like an issue with your system rather than a problem with Go. If you still see this issue, please file a new issue with the complete issue template. And please paste the full output of `go get -v -u` command.

Thanks.
