### ISSUE TITLE
cmd/go: don't mess up stdout when run go tests with "-json"

### ISSUE THREAD

**Issue by KevinXing** [golang/go#25651]
Currently, we can get a machine readable output through `go test -json` which a side effect to mess up stdout. 
So could we add an option to make the screen clean again?

**Comment by ianlancetaylor** [comment]
This doesn't seem to be a proposal, so dropping the proposal label.

Please tell us 1) what you did; 2) what happened; 3) what you wanted to happen instead.

**Comment by fterrag** [comment]
@KevinXing would you be able to provide more information around what you mean by "mess up stdout"? Thanks!

**Comment by KevinXing** [comment]
Sorry for the delay. When we run `go test -json`, it implicit run with `-verbose`, which will output all much info to my screen. I original idea is when we run `go test -json`, the stdout will be same as `go test` and we can dump the `-json` result in a separate log file. 
Since we have worked around this problem, it is fine to close the issue too.
Thanks.

**Comment by fterrag** [comment]
@KevinXing Ah, I think I understand now. You are looking for the -json flag (without -verbose) to display a JSON formatted summary of test results instead of full output. I believe the current behavior is the intended functionality as the output produced by -json is supposed to be used for automated processing.

**Comment by fterrag** [comment]
@ianlancetaylor Should this issue be closed given the information gathered?

**Comment by ianlancetaylor** [comment]
Closing, thanks.
