### ISSUE TITLE
test: actually run the test/safe test

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25668]
While working on cleaning `errchk` from go/test/ I have found a directory `safe/...`: https://github.com/golang/go/tree/master/test/safe

These tests are not being used anymore and they are related to old pre-go gc, checking some internal state.

Can somebody with expertise look at that and decide if we should remove it or keep it  and include into testing suite?

@ianlancetaylor

**Comment by ianlancetaylor** [comment]
This is a test of the compiler's `-u` option.  I guess ideally we would preserve this test and actually start running it.  The test does pass today (that is, the compilation fails with the expected error).

**Comment by travisby** [comment]
I too a stab at this to get familiar with comitting to go :).

This ends up moving some files and copying another; should I use a new Copyright header (with 2018) since they're technically new files in git's eyes, or should I keep the old ones since in spirit it's the same code?  I opted for the latter for now, but will be happy to change it.

**Comment by ianlancetaylor** [comment]
If you just move a file, keep the copyright header.  If you create a new file, even if it is based on an existing file, use a new copyright header.

**Comment by ysmolsky** [comment]
@travisby  will you be able to handle this?
