### ISSUE TITLE
go/importer: GOARCH=386 can't find import: "crypto/tls"

### ISSUE THREAD

**Issue by gyuho** [golang/go#25723]
### What version of Go are you using (`go version`)?

```
go version go1.10.2 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes. Tried it with cf2c2ea89d.

```bash
$ cd $HOME && $HOME/go-master/bin/go version
go version devel +cf2c2ea89d Mon Jun 4 17:32:17 2018 +0000 linux/amd64

~ $ GOARCH=386 $HOME/go-master/bin/go run main.go
can't find import: "crypto/tls"
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gyuho/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gyuho/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build230277318=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```go
package main

import (
	"fmt"
	"go/importer"
)

func main() {
	_, err := importer.Default().Import("crypto/tls")
	if err != nil {
		fmt.Println(err)
	}
}
```

```bash
$ GOARCH=386 go run main.go
can't find import: "crypto/tls"
```

### What did you expect to see?

No error.

### What did you see instead?

```bash
$ GOARCH=386 go run main.go
can't find import: "crypto/tls"
```

**Comment by ianlancetaylor** [comment]
I believe that this is working as expected.  The docs for `importer.Default` say that it returns an `Importer` for the compiler that built the binary, which in this case is `"gc"`.  The docs for `Importer.For` say that for `"gc"` it returns an importer that works on installed packages.  You presumably haven't installed the `"crypto/tls"` package for `386`.

You should either use `importer.For("source")` or run `GOARCH=386 go install crypto/tls`.

Closing because I don't think there is anything to fix.  Please comment if you disagree.

**Comment by gyuho** [comment]
@ianlancetaylor Makes sense. Thanks for explanation! Please feel free to close it!

**Comment by gyuho** [comment]
`importer.For("source")` worked :)
