### ISSUE TITLE
net/http: can remove function 'cleanHost'?

### ISSUE THREAD

**Issue by Luanana** [golang/go#25754]
https://github.com/golang/go/blob/555eb70db2f7ff4aa22768339425430c1dfdf6ac/src/net/http/request.go#L671
I want to make a tool to test http host inject, but the host header content can't have space or  /.

**Comment by agnivade** [comment]
We cannot make changes like that because it will break existing code for everybody. If you want to suggest something new, it typically needs to go through the proposal process. See https://golang.org/s/proposal.

You can however, create a low-level `net.Listener` object and manually go through http headers if you need access to raw data.

**Comment by bcmills** [comment]
As @agnivade notes, an API change should go through the proposal process. I'm not sure there's anything more to be done about this issue, but please let me know if I've missed something.
