### ISSUE TITLE
Can't cross compile project that uses C from linux to windows

### ISSUE THREAD

**Issue by OGFris** [golang/go#25777]
### What version of Go are you using (`go version`)?

Go Version: 1.10.2 linux/amd64

### Does this issue reproduce with the latest release?

This issue reproduce with every Go Version.

### What operating system and processor architecture are you using (`go env`)?

GOOS=linux / GOARCH=amd64

### What did you do?

I built a simple app using github.com/zserge/webview which uses "C" and when i try to cross compile for windows i get an error.

### What did you expect to see?

I expected to see the cross compiling from linux to windows work but it didn't.

### What did you see instead?

`# runtime/cgo
 gcc: error: unrecognized command line option ‘-mthreads’`

**Comment by ianlancetaylor** [comment]
In order to cross-compile a package that uses C, you need to have a C cross-compiler.  Set the `CC` environment variable to that cross-compiler when you run `go build`.

Closing because there is nothing we can do to fix this.  Note that for questions, such as how best to approach this problem, I encourage you to use a forum rather than the issue tracker.  See https://golang.org/wiki/Questions .  Thanks.

**Comment by OGFris** [comment]
ok so i only have to install the C croos-compiler and compile then. btw why do i always have to set the enrironment variables of Go every time i close the terminal.

**Comment by OGFris** [comment]
even after i installed every C cross-compiler i still get the error :
`gcc: error: unrecognized command line option ‘-mthreads’`

**Comment by ianlancetaylor** [comment]
@OGFris Really, use a forum, as described at https://golang.org/wiki/Questions .  You'll get more helpful answers there than you will here.
