### ISSUE TITLE
regexp: freezing program

### ISSUE THREAD

**Issue by deef0000dragon1** [golang/go#25861]
#### What did you do?
Non functioning repository here
https://github.com/deef0000dragon1/StreamState

#### What did you expect to see?
a continuous stream of messages, or atleast a timer update once per second. 

#### What did you see instead?
after a period of time (20 messages on average/20 seconds on average), the entire program freezes. Nothing else prints or runs, and the debugger disconnects, unable to do anything. The print output that I have used seems to narrow the breakdown to regexp's MatchString and FindAllString. 

 I have been unable to isolate the issue to any particular part of the program other than at that location the code fails (Using Printf debugging). 
FlowModules/MessageSplitter/MessageSplitter.go lines 196, 293

#### System details

```
go version go1.10.3 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\deef\AppData\Local\go-build"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\deef\Desktop\Go-Work"
GORACE=""
GOROOT="C:\Go"
GOTMPDIR=""
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\deef\AppData\Local\Temp\go-build712861246=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.10.3 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
```

**Comment by ysmolsky** [comment]
I am sorry, but it is not very easy to work from your description and repository you mentioned. Can you isolate problem into much smaller program? Try to capture the data and the line in your program which lead to "freezing".

Also have you run your program with -race? It might be a data race somewhere.

**Comment by adamdecaf** [comment]
The only regex I could find in the program is: `regexp.MustCompile("(?s).*")`, which compiles and runs fine on the playground. https://play.golang.org/p/ahQn_GjDIpX

Without a smaller reproduction this issue is hard debug. 

Also, the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

**Comment by adamdecaf** [comment]
@deef0000dragon1 Was there more information you could give us?
