### ISSUE TITLE
x/tools/godoc/static: test failure for go1.9 (static.go is stale)

### ISSUE THREAD

**Issue by griesemer** [golang/go#25880]
From the build log:
```
darwin-386-10_11 at 1746cff738c7c801988f18cd25ca0cb488889873 building tools at c995a088887b4ae00a4c85a984117cbc8d86ca3d

ok  	golang.org/x/tools/benchmark/parse	0.005s
ok  	golang.org/x/tools/blog	0.013s
?   	golang.org/x/tools/blog/atom	[no test files]
...
ok  	golang.org/x/tools/godoc	0.758s
?   	golang.org/x/tools/godoc/analysis	[no test files]
ok  	golang.org/x/tools/godoc/redirect	0.025s
--- FAIL: TestStaticIsUpToDate (0.08s)
	gen_test.go:25: static.go is stale
FAIL
FAIL	golang.org/x/tools/godoc/static	0.085s
```

This is currently preventing the x/tools builders from turning "green".

**Comment by ianlancetaylor** [comment]
This has changed because of a change in the status of the Unicode code point `\u9fe5`.  In Go 1.9 `strconv.IsPrint('\u9fe5')` returns `false`.  In 1.10 and 1.11 it returns `true`.  This changes the behavior of `strconv.Quote`, which changes the behavior of the `%q` used by the `Generate` function being tested.

The change to `strconv.Quote` happened in https://golang.org/cl/63953, which updated the package to Unicode 10.0.0

I think if we want this test to be stable across Go releases we should not be using %q to print non-string data.

CC @agnivade

**Comment by agnivade** [comment]
Thanks for the analysis @ianlancetaylor. I believe you are talking about this part of the code - 

```go
if utf8.Valid(b) {
	fmt.Fprintf(buf, "`%s`", sanitize(b))
} else {
	fmt.Fprintf(buf, "%q", b)
}
```

I think if we are to simply use `%s`, there is some more sanitization that needs to be done. Because if I  try to print with ``` `%s` ```, it throws an `illegal UTF-8 encoding` error.  ping @bradfitz who probably wrote/reviewed the sanitize function.

Or should we maintain per-release copies of static.go and delete it once 1.11 is released ?
