### ISSUE TITLE
bufio: bug in the emptyFinalToken example for Scanner

### ISSUE THREAD

**Issue by pam4** [golang/go#25909]
The `SplitFunc` in the `emptyFinalToken` [example](https://golang.org/pkg/bufio/#example_Scanner_emptyFinalToken) for `bufio.Scanner` doesn't handle the case of requesting more data if necessary.

The example only happens to work because the whole input is returned by a single call to `Read` (it uses a `strings.Reader`).

This should be enough to fix it:
```diff
@@ -21,7 +21,10 @@
        // There is one final token to be delivered, which may be the empty string.
        // Returning bufio.ErrFinalToken here tells Scan there are no more tokens after this
        // but does not trigger an error to be returned from Scan itself.
-       return 0, data, bufio.ErrFinalToken
+       if atEOF {
+           return 0, data, bufio.ErrFinalToken
+       }
+       return 0, nil, nil
    }
    scanner.Split(onComma)
    // Scan.
```
The problem is demonstrated here:
https://play.golang.org/p/CM-sWovg8mg

**Comment by meirf** [comment]
I think we should include logic like the OP includes since that's an important general pattern for the Scanner and none of the other examples directly include logic for requesting more data - all the other examples (transitively) have similar checks but only via their usage of the Scan* `SplitFunc`s.

cc: @ianlancetaylor
