### ISSUE TITLE
syscall: many tests failing due to ENOSYS Pipe on js,wasm

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25913]
https://build.golang.org/log/bf6cae84b57c5946f94da6f3291cb90281882f34

On js/wasm, syscall/fs_js.go is:

```go
func Pipe(fd []int) error {
        return ENOSYS
}
```

That causes many tests to fail.

I thought we were going to use the nacl code here? Did too much of that get ripped out?

/cc @neelance

**Comment by neelance** [comment]
> I thought we were going to use the nacl code here? Did too much of that get ripped out?

The eventual decision was to remove all FD mapping logic and to use FDs given by Node.js directly. Since Node.js has no support for os.Pipe, it had to become unsupported. (Discussion on https://go-review.googlesource.com/c/go/+/109977)

I skipped tests that depend on os.Pipe. However, I'm always running tests with `-short`, since wasm is terribly slow on the tests that are already considered slow on other architectures. I guess that the failures you see are tests that are not `-short`.

**Comment by bradfitz** [comment]
`all.bash` runs tests with `-short`.

**Comment by neelance** [comment]
Found it: What I am also using is `-run=Test` to exclude `Example*`. Running examples depends on os.Pipe: https://github.com/golang/go/blob/05f8b44d5edc2960eff106e5e780cf83535d0533/src/testing/example.go#L66-L71
