### ISSUE TITLE
Upgrade "go tool pprof" to a version that can render flame graphs

### ISSUE THREAD

**Issue by dweitzman** [golang/go#25935]
The vendored version of pprof in golang is more than a year old.

Flame graph support has been added to pprof since them, so it seems worthwhile to update the dependency.

**Comment by ALTree** [comment]
Thanks for the report.

> The vendored version of pprof in golang is more than a year old.

I assume you're talking about the version vendored in go1.10.

Current tip (to be 1.11) includes upstream revision 1ddc9e21ddc9e2, it was vendored recently (see https://go-review.googlesource.com/c/go/+/115295); so for flame graph support there's nothing else left to do except wait for the 1.11 release.

Closing here, since the work has already been done.
