### ISSUE TITLE
runtime: CPU profiles should attribute time spent in runtime.morestack to the function call that triggered it

### ISSUE THREAD

**Issue by richardartoul** [golang/go#25943]
#### What did you do?
Details can be found in #18138 

#### What did you expect to see?
I expected CPU profiles to attribute time spent in runtime.morestack to the function that triggered stack growth.

#### What did you see instead?
Time spent in runtime.morestack is measured properly, but is not tied to any particular stack or series of function calls, making it difficult to determine which code path is experiencing excessive goroutine stack growth.

#### Does this issue reproduce with the latest release (go1.10.3)?
Yes.

#### System details

```
go version go1.10.2 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/richardartoul/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/richardartoul/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/38/w8yq1thn7njcv28q20376y_40000gn/T/go-build965061643=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.10.2 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.2
uname -v: Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212
lldb --version: lldb-370.0.42
  Swift-3.1
```

**Comment by hyangah** [comment]
Should we make the existing cpu profile to show the morestack call stack stitched with the goroutine stack that caused stack growth (that means I guess runtime.gentraceback behavior change)?

Or do we want to create a new built-in profile for stack size changes (per @josharian's comment in the issue 18138)?

cc @aclements

**Comment by richardartoul** [comment]
Just want to add that if this isn’t a terribly complex task I’m happy to contribute engineering time if someone is willing to point me in the right direction

**Comment by ianlancetaylor** [comment]
I have to think that this would be most useful in the standard CPU and memory usage profiles, but I don't know how to implement that.

**Comment by heschik** [comment]
Just back from a Go NYC meetup, where @richardartoul went through the backstory here, so I took a second look at this bug. I think I see at least the first problem, but I haven't actually tested it. Notes for whoever works on this next:

Profiling (on Linux) is driven by the [`sigprof` handler](https://github.com/golang/go/blob/bd98a81dc27a740f4c4192cc8799884da62c4bad/src/runtime/proc.go#L3706). It calls [`gentraceback`](https://github.com/golang/go/blob/bd98a81dc27a740f4c4192cc8799884da62c4bad/src/runtime/traceback.go#L98) with `_TraceJumpStack`, which requests that it trace through transitions to the system stack. But `morestack` is unusual in that it does its [own system stack transition](https://github.com/golang/go/blob/bd98a81dc27a740f4c4192cc8799884da62c4bad/src/runtime/asm_amd64.s#L425) without calling `systemstack`, and `gentraceback` [only handles stack switches done specifically by `systemstack`](https://github.com/golang/go/blob/bd98a81dc27a740f4c4192cc8799884da62c4bad/src/runtime/traceback.go#L203).

I think I'd start by changing that test to do check against a list of functions that switch to the system stack, not just `systemstack`. (I don't think `setsSP` is exactly right because `gogo` isn't doing a system stack transition?) AFAICT that'd do it, but I'm probably missing something.

(All of this is for CPU profiling. @hyangah looked at memory profiling and IIRC concluded that there was a hardcoded test in there somewhere that just cut off the stack trace for runtime functions, but I don't have the link handy.)

**Comment by heschik** [comment]
This should now be fixed for CPU profiles. Note that due to implementation issues `runtime.morestack` function won't appear in the backtrace at all, but `runtime.newstack` will.

Memory profiling of runtime functions is a separate issue which I haven't looked at closely. The change above probably helped, but it doesn't matter due to this policy in the protobuf writer:
https://github.com/golang/go/blob/ae6361e4bd78b85c284881a16b9b3f81133db1bb/src/runtime/pprof/protomem.go#L37-L42
which accounts all memory allocation by runtime functions to the user code that called them. This is probably to hide stuff like string-to-[]byte conversions, which don't show up explicitly in user code.

I'm going to close this issue since the original comment requested CPU only. We can reopen if necessary.

**Comment by josharian** [comment]
> Note that due to implementation issues runtime.morestack function won't appear in the backtrace at all, but runtime.newstack will.

This makes me a bit nervous. Having runtime.morestack in the backtrace is useful as an optimization clue.

**Comment by heschik** [comment]
I agree, but since the morestack call is never returned to, putting it in the backtrace would require a level of specific hackery that I was uncomfortable with. I tried making newstack return normally in the common case but it proved more difficult than I think it's worth.

I don't think newstack is *that* much less clear than morestack. If it actually causes someone trouble we can revisit.
