### ISSUE TITLE
wasm: memory usage

### ISSUE THREAD

**Issue by Jinex2012** [golang/go#25975]
I was monitoring the memory usage (using Safari developer tools)  on an empty wasm program:

```
package main

func main() {

}
```

with the example here https://github.com/golang/go/tree/master/misc/wasm

When the page loads, the memory usage is **1.01GB**. When I click on `run` the memory usage becomes **3.01GB** 

but on Google Chrome the memory usage is **17.5MB / 25.6MB**  (clicking on run has no memory effect)

Is this a browser compatibility issue?

cc @neelance

**Comment by neelance** [comment]
We currently have to request a large amount of initial memory, because requesting more memory later is a relatively slow operation. Most of the memory is never used, so the WebAssembly runtime and/or the operating system should be able to not actually allocate physical memory for it. We will probably revise this in the future.

**Comment by agnivade** [comment]
Looks like there is nothing much to be done here. Closing it. Feel free to comment if you disagree.

**Comment by pwfff** [comment]
I recently had to turn this value down and recompile Go when trying to fit a Go compiled WASM into a Cloudflare Worker, since it only allows you to request 2048 pages of memory: `Uncaught CompileError: WebAssembly compilation: Wasm decoding failed: initial memory size (16384 pages) is larger than implementation limit (2048)`.

Of course, even after I got past that error my worker immediately tried to allocate too much memory and crashed... but there are use cases for low-memory WASM modules.

**Comment by neelance** [comment]
We will definitely address this as soon as WebAssembly has the necessary features.

**Comment by pwfff** [comment]
This may be fixed/better with https://github.com/golang/go/issues/27462
