### ISSUE TITLE
x/crypto/openpgp: add FlagsAuthenticate, FlagsGroupKey and FlagsSplitKey support to packet.Signature

### ISSUE THREAD

**Issue by chaosaffe** [golang/go#25983]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?
Attempted to set _authentication_ flag (`0x20`) in a packet.Signature

```golang
packet.Signature{
  FlagsValid:        true,
  FlagsAuthenticate: true,
}
```

### What did you expect to see?
No error

### What did you see instead?
Error: `unknown field 'FlagsAuthenticate' in struct literal of type packet.Signature`

**Comment by chaosaffe** [comment]
Flag is defined in [RFC 4880 Section 5.2.3.21](https://tools.ietf.org/html/rfc4880#section-5.2.3.21)

**Comment by chaosaffe** [comment]
It seems I can't self-assign, but I am working on a patch and will submit via Geritt hopefully today

**Comment by chaosaffe** [comment]
Two additional flags, FlagGroupKey (`0x80`) and FlagSplitKey(`0x10`) are also missing

**Comment by chaosaffe** [comment]
Relevant Patch: https://go-review.googlesource.com/c/crypto/+/120315

**Comment by abarisani** [comment]
+1 I'd like to see this implemented as well. Thanks!

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
