### ISSUE TITLE
database/sql

### ISSUE THREAD

**Issue by JFixby** [golang/go#26082]
#### Case
1) The following code:

```
import (
	"database/sql"
...



     db, err := sql.Open("sqlite3", pathToDbFile)
     .... db usage ....

```

2) file at ```pathToDbFile``` does not exist.

#### Expected behavior
```sql.Open()``` suppose to create file at the target path defined in the ```pathToDbFile```

#### Actual behavior

Scenario A: Parent folder of the ```pathToDbFile``` exists. ```sql.Open()``` creates the DB-file as expected.

Scenario B: Parent folder of the ```pathToDbFile``` does not exist. ```sql.Open()``` returns error: ```unable to open database file```

#### Solution

While creating DB-file, there should be a statement ensuring all the parent folders exist (create missing one).

**Comment by ianlancetaylor** [comment]
It sounds like you are suggesting that `sql.Open` should call `os.MkdirAll`.  But it can't do that, because we wouldn't know what to pass for the `perm` argument, and there is no safe default.  So, for better or for worse, I think that this is working as expected and there's no reasonable way to fix it at this point.
