### ISSUE TITLE
x/vgo: unexpected list command behaviour

### ISSUE THREAD

**Issue by bench** [golang/go#26176]
### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64 

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build039741224=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

I followed the vgo tour available at [https://research.swtch.com/vgo-tour] with the latest version of vgo (installed via go get -u golang.org/x/vgo)

It appears that  the command `vgo list -m` and `vgo list -t rsc.io/sampler` do not behave as expected.

### What did you expect to see?

**$ vgo list -m**
```
$ vgo list -m  
MODULE                                    VERSION
github.com/you/hello  -
golang.org/x/text                         v0.3.0
rsc.io/quote                              v1.5.2
rsc.io/sampler                            v1.3.0

```

**$ vgo list -t rsc.io/sampler**
```
$ vgo list -t rsc.io/sampler
rsc.io/sampler
	v1.0.0
	v1.2.0
	v1.2.1
	v1.3.0
	v1.3.1
	v1.99.99
```

### What did you see instead?

**$ vgo list -m**
```
vgo list -m  
github.com/you/hello
```

**$ vgo list -t rsc.io/sampler**
```
$ vgo list -t rsc.io/sampler
flag provided but not defined: -t
usage: list [-f format] [-json] [-m] [list flags] [build flags] [packages]
Run 'go help list' for details.
```

This used to work (tried with a past version, 6a94eb3 for instance)

**Comment by myitcv** [comment]
@bench these commands have changed somewhat since Russ posted his articles on vgo.

Per https://go-review.googlesource.com/c/vgo/+/120198, `vgo list -m` is now `vgo list -m all`

Per https://github.com/golang/go/issues/25656#issuecomment-401532425, `vgo list -t` appears to be currently broken, but that issue also captures a number of other changes that Russ has planned for `vgo list`.

I'll close this issue for now because I think both points are covered but please shout if that's not the case.

**Comment by bench** [comment]
@myitcv Thank you for replying fast. I will look forward Russ changes ! :+1:
