### ISSUE TITLE
x/net/http2: remove support for Go 1.8 and earlier

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26302]
Our normal policy for x/* repos is to only support tip and the previous two Go releases.

Once Go 1.11 is out, that means we support tip, Go 1.11, and Go 1.10.

Let's clean up some of all the +build conditional code in x/net/http2 and merge a bunch of the files back together.

Because App Engine is only on Go 1.9, we can be lenient there and support back to Go 1.9.

Verify with grpc & App Engine, though, to make sure we don't break them.

**Comment by bradfitz** [comment]
@dfawley, what is your schedule or rationale for when and how you move grpc-go's minimum Go version? Looks like you still support Go 1.6 (as we kinda do, except for our tests started to accidentally require Go 1.7+?). But you're moving to Go 1.7? Would you be fine with Go 1.9, now that App Engine defaults to Go 1.9?

**Comment by dfawley** [comment]
I would defer to the AppEngine team (cc @broady) on this one.  We were ready to drop support for 1.6 many, many months ago, but kept it in at their request.  My preference would be to only support the same versions that are supported by Go (so, 1.9 & 1.10 now), and require users to vendor/use vgo in order to keep using older Go versions.

**Comment by bradfitz** [comment]
21 more days...
https://groups.google.com/forum/#!topic/google-appengine-go/wHsYtxvEbXI

> We’re writing to let you know that we are deprecating Go 1.8 support on App Engine, and new deployments using this language version will no longer be available on November 1, 2018.
