### ISSUE TITLE
crypto/x509: reject UTF-8 names

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#26362]
Certificates should only have punycode in them, but we tolerate and match UTF-8 if provided. Make this stricter after checking it doesn't break a lot of CT and BoringSSL already rejects them.

**Comment by robpike** [comment]
Can you please be more precise in what the restrictions should be? "UTF-8 names" is not a clear target, as ASCII for instance is a subset of UTF-8.

**Comment by mdp** [comment]
The restriction is that certain x509 extensions should be encoded as an [IA5String](https://en.wikipedia.org/wiki/IA5STRING), which is a restricted character set(Essentially 0x0-127 ASCII). Currently, golang's x509 package performs validation checks on IA5String encoding, but it's not complete. It's still possible to encode several of the Subject Alternative Name extensions ("Domains" "EmailAddresses") as non-IA5Stings. There's also no check on the "URIs" field, but due to `URL.String()` being called before encoding, it's escaped and therefore won't contain any characters outside of the IA5String set.

One thing to be aware of, the Common Name on an X509 certificate doesn't actually have an IA5String restriction on encoding. You need to use punycode if you're creating an SSL certificate, but [RFC 5280](https://tools.ietf.org/html/rfc5280#section-7.1) states that "Standard naming attributes, such as common name, employ the DirectoryString type, which supports internationalized names through a variety of language encodings.  Conforming implementations MUST support UTF8String and PrintableString."

**Comment by mdp** [comment]
As far as comparisons go, `Certificate.VerifyHostname(host string)` will not reject comparisons for non-punycode hostnames in the latest release of go - [Go Playground example](https://play.golang.org/p/iIRcWOdrE0B)

However, a recent change (https://github.com/golang/go/commit/4f9ec2c7568fce3db51cee0bf151ccf8534868aa#diff-14a36701d822b09a804f852a229dfc23R910), was introduced which will result in the rejection of CommonName's with non-ASCII characters in them - caused by `validHostname(c.Subject.CommonName)` 

That being said, if the certificate has a non-ASCII character in the DNSName SAN extension, it will still do the comparison and match. Example below:

```
c := &x509.Certificate{
        DNSNames: []string{"göögle.com"},
	Subject: pkix.Name{
		CommonName: "göögle.com",
	},
}

err := c.VerifyHostname("göögle.com")
if err == nil {
	fmt.Println("VerifyHostname(göögle.com) should have failed, did not")
} else {
	fmt.Printf("VerifyHostname(göögle.com) failed - %q", err)
}
```

**Comment by stefanb** [comment]
Please note that X.509 client certificates contain personal names in the **common name (CN)** attribute! 
 
Those can be encoded in various ways, one of the more exotic cocktail 🍸of UCS-2/UTF-16/UTF-8 being used in Estonian 🇪🇪 electronic ID: https://eid.eesti.ee/index.php/Authenticating_in_web_applications#Add_user_authentication_to_your_application
