### ISSUE TITLE
encoding/json: UnmarshalTypeError missing field & struct values

### ISSUE THREAD

**Issue by Gobd** [golang/go#26444]
### What version of Go are you using (`go version`)?

1.10.2

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

See Go Playground link

### What did you do?

[Go Playground example](https://play.golang.org/p/WUIkw4FxPHK)

### What did you expect to see?

I expect to see field & struct populated in both examples.

### What did you see instead?

Instead field & struct are only populated when the invalid value is the first value in the map.

**Comment by doodlesbykumbi** [comment]
@Gobd As far as I can tell, this is expected behaviour based on the implementation of the `Unmarshaler`. The `Unmarshaler` scans from left to right (byte to byte), and populates the struct as it goes. This results in different behaviours depending on when the invalid value is encountered - because it will error right then and there.

In the playground example you provided it seems you have `payloadField` and `payloadNoField` the opposite way around. Which is to say, the field and struct are only populated when the invalid value is **NOT** the first value in the map. See https://play.golang.org/p/L_BE16ygpxB

**Comment by Gobd** [comment]
I've made our two examples more similar, and they both get different behavior when ran in the playground.

[Example 1](https://play.golang.org/p/ryPfd04rWsw) -- payloadField has field populated

[Example 2](https://play.golang.org/p/xqKsF1FIS2q) -- payloadNoField has field populated

So now in one example field only populates if the invalid value is first, then the reverse behavior occurs in the other example unless I'm missing something.

**Comment by Gobd** [comment]
Just ran the two examples locally with `go version go1.10.3 darwin/amd64` and I see the same behavior. In `go version go1.11beta1 darwin/amd64` when I run the two examples not a single one of them has field populated.

**Comment by doodlesbykumbi** [comment]
In the 2 examples you provided, you're printing the errors but  not printing the request structs. How are you determining if a field is populated ?

**Comment by Gobd** [comment]
Sorry if it wasn't clear, I'm talking [about the field/struct here](https://golang.org/pkg/encoding/json/#UnmarshalTypeError) that will be used to print [this](https://golang.org/src/encoding/json/decode.go?s=4940:5322#L115) error message that will help to find which value caused to unmarshal to fail.

**Comment by Gobd** [comment]
The commit that has made this error message less useful in master is https://github.com/golang/go/commit/74a92b8e8d, with this commit no struct/field is ever printed in the error message in the two examples above.

**Comment by fwhezfwhez** [comment]
why not try to json.Marshal(request) and see what is a standard json []byte,I guess the code of your json part is not well formated.The raw json contains '/'
