### ISSUE TITLE
net/http/pprof: Heap profiler is missing from package

### ISSUE THREAD

**Issue by chasebrewsky** [golang/go#26572]
### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?

Tried to read the pprof heap profiler using the net/http/pprof package, as mentioned [in the documentation](https://golang.org/src/net/http/pprof/pprof.go) line 23, but noticed that it's completely missing. I'm unsure if this was intentional, but there is no http.Handler for the heap profiler. There are handles like `Profile` for CPU profiling, but none for memory insights.

**Comment by agnivade** [comment]
I am not sure what the bug is. Are you saying that you did `go tool pprof http://localhost:6060/debug/pprof/heap` and did not get a heap profile ? Or just simply that you could not find the code for the heap profile ?

If it is the latter, that is because it is inside runtime/pprof. And not just heap profile, allocs, block, mutex are also coming from runtime/pprof.

You just need to look closely here - https://tip.golang.org/src/net/http/pprof/pprof.go#L268.

**Comment by chasebrewsky** [comment]
You're right, my mistake. I was trying to do custom URL mappings to just the heap and couldn't find the individual http handler. I didn't notice that it was grouped with other utilities in the Index handler. Thanks, and sorry for the inconvenience!
