### ISSUE TITLE
error in io.Copy() instead of returning error it panic error while passing nil file

### ISSUE THREAD

**Issue by MohitArora1** [golang/go#26592]

**Comment by mvdan** [comment]
Please use the template when filing bugs. A small, self-contained program to reproduce the bug would also be useful. As it is now, this issue contains very little useful information.

**Comment by ianlancetaylor** [comment]
I assume the problem here is that passing a nil pointer to `io.Copy` will cause a panic rather than returning an error.  That is working as expected.  Many standard library functions will panic if you pass them a nil pointer.  Closing this issue as working as expected.  Please comment if you disagree or if I have misunderstood.
