### ISSUE TITLE
sending nil body of type *bytes.Buffer in http.NewRequest() function is causing panic

### ISSUE THREAD

**Issue by oshankkumar** [golang/go#26666]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/okumar/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/okumar/GO_Workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build577645390=/tmp/go-build -gno-record-gcc-switches"
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/fQfn9BincB-

### What did you expect to see?
Sending a nil body of type *bytes.Buffer should not cause panic

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0x22e622]

goroutine 1 [running]:
bytes.(*Buffer).Len(...)
	/usr/local/go/src/bytes/buffer.go:74
net/http.NewRequest(0x2b335f, 0x3, 0x2b70da, 0x15, 0x2fa500, 0x0, 0x3ae01, 0x6d4, 0x1073a040, 0x0)
	/usr/local/go/src/net/http/request.go:802 +0x662
main.main()
	/tmp/sandbox012127239/main.go:11 +0x60

**Comment by mvdan** [comment]
When a function takes in an `io.Reader`, you should generally only send an untyped nil or an actual variable that can be read from. For example, passing it `nil` directly, or a zero `io.Reader` variable: https://play.golang.org/p/2eYCsyygdZ9

Passing it a nil `*bytes.Buffer` breaks because the `bytes.Buffer.Read` method ends up being called, and a `*bytes.Buffer` cannot be used if it is nil.

In the future, for questions about Go, see https://golang.org/wiki/Questions.
