### ISSUE TITLE
net: ParseIP (IPv6:IPv4 mixed-form) incorrect parsing

### ISSUE THREAD

**Issue by dmitryrpm** [golang/go#26694]
Hi, I got a strange result when do parsing IPv6:IPv4 (mixed-form), no by rfc3513
**0:0:0:0:0:0:13.1.68.3 -> ::d01:4403** 
```
fmt.Printf("Result compresed form: %s", net.ParseIP("0:0:0:0:0:0:13.1.68.3").String())
>>> Result compresed form: ::d01:4403 // need ::13.1.68.3
```
https://play.golang.org/p/mPH9cANDRVO

Is it real correct parsing?

**Comment by ajwsh** [comment]
Yes, it is parsed correctly. What you get is the hexadecimal representation of the mixed address. In an IPv6 address you got 8 groups consisting of 16 bit each. In a IPv4 address are 4 groups consisting of 8 bits each. So your IPv4 will be represented in hexadecimal as 0x**0d01** (= 13.1) and 0x**4403** (= 68.3).

**Comment by dmitryrpm** [comment]
@ajwsh Thank for a answer! 
but in other example I have not convert IPv4 to hex. Why? =)
"0:0:0:0:0:FFFF:129.144.52.38" => 129.144.52.38 // other rfc exmpale need  ::FFFF:129.144.52.38
https://play.golang.org/p/W_YRWzgwUZB

**Comment by ianlancetaylor** [comment]
It sounds like things are working correctly.  We don't use the issue tracker for questions; please see https://golang.org/wiki/Questions .  Thanks.

(I don't know the answer to your question myself.)

**Comment by mikioh** [comment]
In general, it's better to refer to the latest addressing architecture, RFC 4291, instead of RFC 3513. RFC 4291 holds better descriptions on the section "IPv6 Addresses with Embedded IPv4 Addresses", and has a reference to RFC 4038 (Application Aspects of IPv6 Transition).

So taking a look at https://tools.ietf.org/html/rfc4291 will probably answer your question.
