### ISSUE TITLE
cmd/cgo: generate correct column info

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#26692]
### What version of Go are you using (`go version`)?
`go version go1.11beta2 linux/amd64`

### Does this issue reproduce with the latest release?
yes (currently beta2)

This is a regression in go 1.11 since when using go 1.10 there is no such issue (see below).

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kir/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kir/go"
GOPROXY=""
GORACE=""
GOROOT="/home/kir/sdk/go1.11beta2"
GOTMPDIR=""
GOTOOLDIR="/home/kir/sdk/go1.11beta2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build131899104=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Ran unconvert (https://github.com/mdempsky/unconvert) on Moby (https://github.com/moby/moby) sources.

### What did you expect to see?
Filenames and positions (file:line:column) for every error it finds. Example (when using Go 1.10.1):
> kir@kd:~/go/src/github.com/mdempsky/unconvert$ go run unconvert.go github.com/docker/docker/daemon/graphdriver/copy
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:240:28: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:240:50: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:241:28: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:241:50: unnecessary conversion

### What did you see instead?
Column is 0 for files that are cgo-preprocessed (i.e. contain `import "C"`):

> kir@kd:~/go/src/github.com/mdempsky/unconvert$ go1.11beta2 run unconvert.go github.com/docker/docker/daemon/graphdriver/copy
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:240:0: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:240:0: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:241:0: unnecessary conversion
> /home/kir/go/src/github.com/docker/docker/daemon/graphdriver/copy/copy.go:241:0: unnecessary conversion

### Analisys

This appears in cgo-processed files having `//line:<file>:<line>` directive (without column field), so column is 0 in call to go/token's `AddLineColumnInfo()` method. Next, `unpack()` does this
```go
if alt.Column == 0 {
        // alternative column is unknown => relative column is unknown
        // (the current specification for line directives requires
        // this to apply until the next PosBase/line directive,
        // not just until the new newline)
        column = 0
```

and as a result in cgo-preprocessed files we have no column information at all. This is caused by commit 99c30211b1e0b3ac4e5d32f3ae5eaf759c23195f.

### Suggestions

I see two ways of fixing this.
1. Add column 1 to `cmd/cgo` generated `//line:` marks.
2. Treat missing column information as column 1 (not 0 as it is now).

**Comment by kolyshkin** [comment]
> Add column 1 to cmd/cgo generated //line: marks.

Fix is here: https://go-review.googlesource.com/c/go/+/126675. Tested manually by using self-compiled cgo with the patch; it works!

**Comment by kolyshkin** [comment]
@griesemer PTAL

**Comment by mdempsky** [comment]
cmd/cgo inserts/deletes some lines of code (e.g., removing the `import "C"` declaration, and adding other imports necessary for cgo), but it also rewrites some lines of code (e.g., changing `C.foo()` function calls into `_Cfunc_foo()`).

In previous releases, when parsing cmd/cgo processed source files, the `//line` directives gave correct line positions everywhere, but column positions were potentially wrong for lines that were rewritten due to `C.foo` references.

Due to go/scanner changes for Go 1.11, column information is no longer being tracked for cmd/cgo processed files. This is arguably more correct, because it no longer gives bogus column information for rewritten lines. However, it's also arguably a regression, because column information is now lost for lines that weren't rewritten.

From a casual inspection, CL 126675 restores the (questionable) behavior from Go 1.10.

I think the proper long-term fix is for cmd/cgo to emit `/*line*/` directives within rewritten lines, so that we get precise column information everywhere.

For Go 1.11, I'm leaning towards it's better to give suboptimal output consistent with Go 1.10, rather than give a differently-suboptimal output. (I.e., I'm leaning towards CL 126675.)

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Reopening to get correct column info.

**Comment by mdempsky** [comment]
I thought I remembered one of the motivations for `/*line*/` directives was to support cmd/cover, but it looks like cmd/cover actually only needs `//line` directives?

Also, it looks like cmd/cover/cover.go could use the same `//line %s:1:1` treatment as cmd/cgo/out.go.

**Comment by ianlancetaylor** [comment]
I believe that cmd/cover could use `/*line*/` directives.  It currently edits the code by inserting text.

That said I think cmd/cover is a less interesting case since it seems less likely that people will ask for coverage of code that generates compilation errors.  Getting compilation errors on cgo-generated code, on the other hand, seems like a normal stage of development.

**Comment by mdempsky** [comment]
Oops, I was referring to commit 2a39d1e ("Now that cover does not modify the formatting of the original file or add any newline characters"), but forgot to actually link to that in my comment.

**Comment by mdempsky** [comment]
I see. It seems I misunderstood "does not modify the formatting" to mean "does not modify at all."

**Comment by ianlancetaylor** [comment]
Sure, but if you think about it, "does not modify at all" doesn't really make sense here.  The cmd/cover tool has to do something.

**Comment by ianlancetaylor** [comment]
Doesn't seem like a big deal to me in this case, but, OK, filed #26745.
