### ISSUE TITLE
cmd/go/internal/bug: sync issue body format with GitHub template

### ISSUE THREAD

**Issue by myitcv** [golang/go#26751]
`go bug` populates a Github issue in the order below, as opposed to https://github.com/golang/go/blob/b8669ef1ceabd386b58a99b4e2f4e67915fec428/.github/ISSUE_TEMPLATE

Not critical clearly but maybe nice to bring in line? cc @andybons?

---

Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

#### System details

```
go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
GOARCH="amd64"
GOBIN="/home/myitcv/.mountpoints/x/src/myitcv.io/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/.mountpoints/x"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/.mountpoints/x/src/myitcv.io/go.mod"
GOROOT/bin/go version: go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000
uname -sr: Linux 4.15.0-29-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1) stable release version 2.27.
```

**Comment by andybons** [comment]
Really good first bug for anyone interested. Thanks for the report, Paul!

**Comment by joshblakeley** [comment]
Working on this

**Comment by darkLord19** [comment]
Is this issue still open?

**Comment by myitcv** [comment]
Yes @joshblakeley is working on this

**Comment by dmitshur** [comment]
@joshblakeley Please take the latest changes to the GitHub issue template in [CL 138295](https://golang.org/cl/138295) into account (see #28583 for more background).

Adding release-blocker label so we don't forget about this issue, I'd like it to get into 1.12.

**Comment by deblasis** [comment]
Hi guys, any objection if I PR this? 

I started looking into Go few days ago and I fell in love... in order to learn a bit more about it while contributing back, I wanted to pick up an easy task :)

I have worked out an implementation that downloads the issue template straight from github (similarly to the version check) and replaces the `go version`, `go env` and the latest version check bit as well.

The end result is basically along the lines:

https://github.com/golang/go/issues/new?body=%3C%21--+Please+answer+these+questions+before+submitting+your+issue.+Thanks%21+--%3E%0A%0A%23%23%23+What+version+of+Go+are+you+using+%28%60go+version%60%29%3F%0A%0A%3Cpre%3E%0Ago+version+devel+%2B6d5caf38e3+Thu+Nov+22+02%3A59%3A55+2018+%2B0000+linux%2Famd64%0A%0A%0A%3C%2Fpre%3E%0A%0A%23%23%23%23+Does+this+issue+reproduce+with+the+latest+release+%28go1.11.2%29%3F%0A%0A%0A%0A%0A%0A%0A%23%23%23+What+operating+system+and+processor+architecture+are+you+using+%28%60go+env%60%29%3F%0A%0A%3Cdetails%3E%3Csummary%3E%3Ccode%3Ego+env%3C%2Fcode%3E+Output%3C%2Fsummary%3E%3Cbr%3E%3Cpre%3E%0AGOARCH%3D%22amd64%22%0AGOBIN%3D%22%22%0AGOCACHE%3D%22%2Fhome%2Fadeblasis%2F.cache%2Fgo-build%22%0AGOEXE%3D%22%22%0AGOFLAGS%3D%22%22%0AGOHOSTARCH%3D%22amd64%22%0AGOHOSTOS%3D%22linux%22%0AGOOS%3D%22linux%22%0AGOPATH%3D%22%2Fmnt%2Fc%2Fdev%2Fgo%22%0AGOPROXY%3D%22%22%0AGORACE%3D%22%22%0AGOROOT%3D%22%2Fmnt%2Fc%2Fdev%2FOSS%2Fgo%22%0AGOTMPDIR%3D%22%22%0AGOTOOLDIR%3D%22%2Fmnt%2Fc%2Fdev%2FOSS%2Fgo%2Fpkg%2Ftool%2Flinux_amd64%22%0AGCCGO%3D%22gccgo%22%0ACC%3D%22gcc%22%0ACXX%3D%22g%2B%2B%22%0ACGO_ENABLED%3D%221%22%0AGOMOD%3D%22%22%0ACGO_CFLAGS%3D%22-g+-O2%22%0ACGO_CPPFLAGS%3D%22%22%0ACGO_CXXFLAGS%3D%22-g+-O2%22%0ACGO_FFLAGS%3D%22-g+-O2%22%0ACGO_LDFLAGS%3D%22-g+-O2%22%0APKG_CONFIG%3D%22pkg-config%22%0AGOGCCFLAGS%3D%22-fPIC+-m64+-pthread+-fmessage-length%3D0+-fdebug-prefix-map%3D%2Ftmp%2Fgo-build814503179%3D%2Ftmp%2Fgo-build+-gno-record-gcc-switches%22%0Auname+-sr%3A+Linux+4.4.0-17763-Microsoft%0ADistributor+ID%3A%09Ubuntu%0ADescription%3A%09Ubuntu+18.04.1+LTS%0ARelease%3A%0918.04%0ACodename%3A%09bionic%0A%2Flib%2Fx86_64-linux-gnu%2Flibc.so.6%3A+GNU+C+Library+%28Ubuntu+GLIBC+2.27-3ubuntu1%29+stable+release+version+2.27.%0A%0A%0A%3C%2Fpre%3E%3C%2Fdetails%3E%0A%0A%23%23%23+What+did+you+do%3F%0A%0A%3C%21--%0AIf+possible%2C+provide+a+recipe+for+reproducing+the+error.%0AA+complete+runnable+program+is+good.%0AA+link+on+play.golang.org+is+best.%0A--%3E%0A%0A%0A%0A%23%23%23+What+did+you+expect+to+see%3F%0A%0A%0A%0A%23%23%23+What+did+you+see+instead%3F%0A%0A

Shall I PR so that you guys can have a look? :)

**Comment by myitcv** [comment]
@deblasis this is already being worked on, but thank you for the offer in any case. Please see https://golang.org/cl/127495

**Comment by deblasis** [comment]
Oh nice one! I didn't see any reference to the CL on googlesource (I am not familiar with it... yet) and I can't see any link or updates here on github regarding the isue being worked on.
The latest update was this one https://github.com/golang/go/issues/26751#issuecomment-435646192 when I started. 
Well, another time then!
