### ISSUE TITLE
x/build: add OpenBSD 6.4 builder

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26833]
Update OpenBSD to 6.4.

Would've helped with testing e.g. https://go-review.googlesource.com/c/sys/+/127762.

**Comment by 4a6f656c** [comment]
Historically we have only updated the OpenBSD builders every two releases, so that we reduce the effort to once every 12 months while keeping on a supported release. As such, I would have expected that we would go from 6.2 to 6.4, when it is released in November.

Is the plan to upgrade to 6.3 now, then 6.4 in November and then follow every release (once every six months) after that?

**Comment by bradfitz** [comment]
If we did that historically, I'm not sure it's ever been because of some plan. I think we've just fallen behind and that's what's ended up happening by accident. Ideally we'd have ever version as soon as possible. (This is independent of Go's general OpenBSD support policy; but knowing about breakages sooner will help us prepare.)

**Comment by 4a6f656c** [comment]
Fair enough - it has been more planned than accidental, as I would normally raise an issue and handle the upgrade work when the builder was about to drop into an unsupported release. Ideally we'd run both currently supported versions so that we detect breakage across either of those...

**Comment by bradfitz** [comment]
Sorry, I didn't mean to imply you didn't have a plan. I'm just saying I certainly didn't, or I wasn't aware of one.

**Comment by blackgnezdo** [comment]
I'd start sooner with a [6.4-beta in snapshots](https://cloudflare.cdn.openbsd.org/pub/OpenBSD/snapshots/amd64/) if possible. I'm seeing [strange behavior on GCE](https://github.com/google/syzkaller/issues/712#issuecomment-422686539), admittedly with Go 1.10.1 (patched for MAP_STACK).

**Comment by dmitshur** [comment]
I've done some preparatory work, and I'm fairly close to being able to do this. However, it seems that the 6.4 release is due quite soon based on what I'm hearing, and the previous releases:

```
 • 2018-04-02: BSD Release: OpenBSD 6.3
 • 2017-10-09: BSD Release: OpenBSD 6.2
 • 2017-04-11: BSD Release: OpenBSD 6.1
 • 2016-09-01: BSD Release: OpenBSD 6.0
 • 2016-03-29: BSD Release: OpenBSD 5.9
 • 2015-10-18: BSD Release: OpenBSD 5.8
 • 2015-04-30: BSD Release: OpenBSD 5.7
 • 2014-11-01: BSD Release: OpenBSD 5.6
 • 2014-05-01: BSD Release: OpenBSD 5.5
 • 2013-11-01: BSD Release: OpenBSD 5.4
 • 2013-05-01: BSD Release: OpenBSD 5.3
 • 2012-11-01: BSD Release: OpenBSD 5.2
```

We're a week away from October now. At this point, it seems worthwhile to wait a little more for 6.4 to come out and target that instead of 6.3. Let me know if there are strong reasons to either go with 6.3 or a beta snapshot of 6.4 sooner.

Otherwise, I plan to resolve this issue as soon as 6.4 final is released. If there is any additional information about the OpenBSD release schedule and when 6.4 final is expected to be released, please let me know.

**Comment by blackgnezdo** [comment]
I would do some practice runs with 6.4-beta currently in snapshots. I made a few minor tweaks to enable [running with snapshots for syzkaller](https://github.com/google/syzkaller/blob/master/tools/create-openbsd-gce-ci.sh). If things don't seem entirely trivial, I'm happy to back-port the changes to [make.bash](https://github.com/golang/build/blob/master/env/openbsd-amd64/make.bash).

**Comment by dmitshur** [comment]
Okay, I'll start with adding a 6.4 beta snapshot builder, and update it to final 6.4 once that's out. It seems that it'll be helpful at getting us more useful debug information sooner.

> If things don't seem entirely trivial, I'm happy to back-port the changes to make.bash.

If it's fast for you to send a CL to add snapshot support to [make.bash](https://github.com/golang/build/blob/master/env/openbsd-amd64/make.bash) and you'd like to do it, that'd be helpful. Feel free to add me as a reviewer. Otherwise, I'll work on that, and make use of https://github.com/google/syzkaller/commit/b117b6ed3dc89b7e307dab907dafc0e7defd5756 as a reference if needed. Thanks!

**Comment by dmitshur** [comment]
I've started working on this in [CL 139857](https://golang.org/cl/139857).

@blackgnezdo Can you please take a look at my question https://go-review.googlesource.com/c/build/+/133115/8/env/openbsd-amd64/make.bash#52, knowing the motivation behind that change will help me make progress on this. Thanks!

**Comment by dmitshur** [comment]
[CL 139857](https://golang.org/cl/139857) has been merged and `cmd/coordinator` redeployed. There are `openbsd-amd64-64` and `openbsd-386-64` builders running now.

It's not the final OpenBSD 6.4 release, and they haven't been tested yet, so they should be considered experimental for a few days until they prove to be reliable. They're not enabled for trybots yet.

**Comment by bradfitz** [comment]
OpenBSD 6.4 final is out today: https://www.openbsd.org/64.html

**Comment by dmitshur** [comment]
I'll work on updating the images to 6.4 final.

The current 6.4 snapshots have been quite stable on https://build.golang.org/:

<img width=101 src="https://user-images.githubusercontent.com/1924134/47171548-fc264180-d2d6-11e8-8899-f0610a71f5c9.png">

Once the final 6.4 images prove to be equally reliable, we can then make TryBots use them.

**Comment by blackgnezdo** [comment]
FWIW, oct 11 snapshot should be nearly identical to 6.4 release.

**Comment by dmitshur** [comment]
> Will redeploy `cmd/coordinator` later tonight (when it's quieter).

Version golang/build@24469dd429f05bdb34b644430843761abf7e1367 of `cmd/coordinator` is deployed now.

**Comment by dmitshur** [comment]
The latest status is that I've redeployed cmd/coordinator last night with the fix for #28403. Will let the v2 image OpenBSD 6.4 builders run for a few days to get an idea of their reliability and speed, then we can proceed with switching OpenBSD trybots from 6.2 to 6.4.

**Comment by dmitshur** [comment]
The v2 image appears to be equally stable:

<img width=100px src=https://user-images.githubusercontent.com/1924134/48279994-460acf00-e420-11e8-93ef-a488b6f1302a.png>

The performance has improved after resolving #28403. See https://go-review.googlesource.com/c/build/+/144777/4..5//COMMIT_MSG.

**Comment by dmitshur** [comment]
Deployed coordinator. Trybots will now use OpenBSD 6.4 rather than 6.2. E.g.:

<img width=420px src=https://user-images.githubusercontent.com/1924134/48304759-fe05ae00-e4ec-11e8-8f67-e44da78a5254.png>
