### ISSUE TITLE
cmd/go: we're fetching github.com?go-get=1

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26885]
I just noticed with "go install -v" that we're fetching `https://github.com?go-get=1`, which seems wrong:

```
dev:barlogaamp $ GO111MODULE=on go install -v
Fetching https://golang.org/x/crypto/ssh?go-get=1
go: finding github.com/bradfitz/private/sonos latest
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
go: finding github.com/bradfitz/private latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go: finding golang.org/x/crypto/ssh latest
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto?go-get=1
go: finding golang.org/x/crypto latest
go: import "github.com/bradfitz/private/barlogaamp" ->
        import "github.com/bradfitz/private/sonos": cannot find module providing package github.com/bradfitz/private/sonos
```

My program's imports are:

```go
package main

import (
        "context"
        "log"
        "time"

        "golang.org/x/crypto/ssh"
        "github.com/bradfitz/private/sonos"
)
```

Where `github.com/bradfitz/private` is a private github repo.

In my `~/.gitconfig` I have:

```
[url "ssh://git@github.com/"]
     insteadOf = https://github.com/
```

Seems like this only affects modules mode.

**Comment by bcmills** [comment]
That probably comes from this loop:
https://github.com/golang/go/blob/f2131f6e0c6ca016143fc402d9d01f6a730f97cd/src/cmd/go/internal/modload/import.go#L153-L183

(I'm attempting to factor it out in https://golang.org/cl/128136, but that probably doesn't change the symptom.)

Perhaps we should hard-code some well-known constraints on module paths: for example, paths beginning with `github.com` must have at least two subsequent path components. That would at least save some lookup latency for modules that can't be fetched (#26874).

Are you able to fetch the private repos otherwise? (That's #26134 in general, I think.)

**Comment by bradfitz** [comment]
> Are you able to fetch the private repos otherwise? (That's #26134 in general, I think.)

No. I'll leave a comment there.
