### ISSUE TITLE
x/build: fix gomote ssh to COS-based Linux Docker images

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26969]
When I moved the Linux Docker-based container images from Kubernetes to [COS](https://cloud.google.com/container-optimized-os/) I accidentally broke `gomote ssh` support.

We used to ssh proxy to the POD's port 22, which worked, but now we ssh to the COS node's ssh server, which is the wrong one. We're also running an SSH server inside the container (which is also listening on port 22 in its private network namespace), and it's only that inner SSH server that's authenticated.

We need to configure the COS node's konlet YAML to either forward some different port (e.g. host 2200 to container 22) or just make the container image listen on 2200 instead, and then configure that in x/build/dashboard/builders.go and make the coordinator respect that in its `remote.go` when it calls `rb.buildlet.ConnectSSH`.

**Comment by bradfitz** [comment]
Turns out CL 129356 was all that was needed.

**Comment by dmitshur** [comment]
[CL 129356](https://golang.org/cl/129356) and deploying the new version of `cmd/buildlet` were sufficient to resolve the issue. We just needed to move the SSH server being started to a non-22 port to avoid overlapping with the host's sshd. The communication to the new port happens completely inside the `cmd/buildlet`'s `/connect-ssh` HTTP handler. `cmd/coordinator` doesn't need to know about the new port, and hence there's nothing more do.

I tested, and `gomote ssh` now works for COS-based Linux images (e.g., `linux-amd64`).

Closing since the issue is resolved. Huge thanks to @bradfitz for the help with this.
