### ISSUE TITLE
x/net/html: html.Parse should document that it silently ignores invalid/unexpected nodes

### ISSUE THREAD

**Issue by empijei** [golang/go#26973]
### What version of Go are you using (`go version`)?
go1.9.4 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```ini
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/clap/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build659916345=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```go
package main
import (
	"fmt"
	"strings"
	"golang.org/x/net/html"
)
func main() {
	n, _ := html.Parse(strings.NewReader(`<html><head></head><body><tr><td><pre>some text</pre></td></tr></body></html>`))
	fmt.Println(n.FirstChild.Data) // html
	fmt.Println(n.FirstChild.FirstChild.Data) // head
	fmt.Println(n.FirstChild.FirstChild.NextSibling.Data) // body
	// unexpected <tr> is skipped
	// unexpected <td> is skipped
	fmt.Println(n.FirstChild.FirstChild.NextSibling.FirstChild.Data) // pre
}
```

### What did you expect to see?
A line in the documentation warning the users that html.Parse skips and ignores nodes.

Would also be nice to know when and how this happens (at least have an approximative description for this behavior.)

### What did you see instead?
Code silently fixing the html

**Comment by magical** [comment]
FWIW, this is also how browsers interpret that snippet of HTML. `<tr>` and `<td>` are not meaningful outside of `<table>` so they are ignored. 

![Screenshot of firefox dev tools showing a DOM with pre but not tr or td](https://user-images.githubusercontent.com/175539/44061521-3f275842-9f48-11e8-9b6b-a50c612617dc.png)

I believe Go is doing the right thing here.

**Comment by FMNSSun** [comment]
Parsing invalid HTML is a _mess_. Either you try to fix the errors in HTML (which browsers obviously do and do a great job at) or you return a parser error. I'd always advocate for "reject invalid inputs completely" rather than trying to fix it but in the case of HTML there are just so so many invalid HTML documents around that if your parser outright rejects invalid HTML then you restrict it's usage. 

FWIW: The parser generally ignores tokens if they aren't supposed to show up in that context. In the `body` context the following are skipped: `caption, col, colgroup, head, tbody, td, tfoot, th, thead, tr`.

`<tr>` as per spec is only allowed inside `<table>, <thead>, <tbody>, <tfoot>`. 

In my opinion documenting all these would probably be overkill and it should suffice to document _broadly_ that the parser may choose to ignore elements in invalid HTML documents.

**Comment by jimmyfrasche** [comment]
Parsing html is a mess in the sense that it's complicated, but html5 codifies all of the ways in which it is messy and has very specific rules for handling malformed documents to make sure that everyone interprets them the same way.

If these are not supported, it is not an html5 parser. It would be a bug if it did not ignore those tags.

The behavior shown in this issue is documented here https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody (but you have to scroll for a while because there are a lot of rules). I got to this link through the docs for the package.

So this is working as intended and as documented—albeit somewhat implicitly and indirectly.

I agree with @FMNSSun that it would be better for the docs to broadly mention that Parse ignores tags as required by the spec.

I'm going to re-purpose this bug for making the documentation more explicit.

**Comment by empijei** [comment]
I agree with you, Go is doing the right thing here, and pointing it out in the doc is probably the best way to approach this.

Do you think referring to the document you linked would make sense?

**Comment by jimmyfrasche** [comment]
It is albeit indirectly. I got to that link from the links in the docs. The html5 spec has many pages and we could find reasons to point to all of them.

I'm unsure of the best way to document this.
