### ISSUE TITLE
json.Marshal will sort the keys of map.

### ISSUE THREAD

**Issue by xcFelix** [golang/go#27050]
**json.Marshal** will _sort_ the keys of map.
Although I can change this behavior by rewriting the interface of **MarshalJSON**, it would be better if there was another function that does not perform the operation of _sort_.

**Comment by mvdan** [comment]
This is documented:

> The map keys are sorted and used as JSON object keys by applying the following rules, [...]

I presume the reason is so that the output is deterministic. Otherwise, lots of applications that use JSON would not behave consistently and would break in unexpected ways.

Why exactly do you need the order of the keys to be randomized? I can't think of a reason why that would be useful.

**Comment by xcFelix** [comment]
A very magical application scenario.

I think **Ordered dictionary**, currently not provided by go, is very compatible with this funtion.
also **fmt.Println**.

**Comment by xcFelix** [comment]
Just like that type in Python.
[OrderedDict](https://docs.python.org/3.5/library/collections.html#collections.OrderedDict)

**Comment by agnivade** [comment]
Well, we would need to understand what the requirements are before adding new API to the standard library.

Any new API needs to go through the proposal process. I would request you to create a  [proposal](https://golang.org/s/proposal) issue outlining the reasoning behind the need to add additional API in the standard library. Simply saying "magical" won't let us understand why this is necessary and how might it help other users of the standard library.

Also note that there are other scenarios too like https://golang.org/pkg/io/ioutil/#ReadDir where we return entries sorted by filename. In this way, all standard library APIs are coherent in how they return random output.

**Comment by mvdan** [comment]
This issue is a bit all over the place. You seem to be asking for ordered maps, which has very little to do with JSON. This issue has been raised in the past - see #6244.

In short, JSON object keys are unordered, so it would likely not make sense even if Go had ordered mapss. I'm closing this for now.
