### ISSUE TITLE
cmd/go: help for go.mod references example that has now been removed

### ISSUE THREAD

**Issue by thepudds** [golang/go#27083]
### What version of Go are you using (`go version`)?

Documentation on tip.golang.org (`Build version devel +bf80e3b564 Sat Aug 18 18:23:06 2018 +0000`)

### Does this issue reproduce with the latest release?

Yes (tip).

### Issue

The old `go help mod fix` included this example near the top:

```
Fix updates go.mod to use canonical version identifiers and
to be semantically consistent. For example, consider this go.mod file:

        module M

        require (
                A v1
                B v1.0.0
                C v1.0.0
                D v1.2.3
                E dev
        )

        exclude D v1.2.3
```

Much of the content from `go help mod fix` has migrated to `go help go.mod`, and the text has been updated and generally improved.

However, even though example above was removed, many sections of the subsequent prose in the current `go help go.mod` still continue to refer to that now non-existent example, such as:

> The update rewrites non-canonical version identifiers to semver form, so A's v1 becomes v1.0.0 and E's dev becomes the pseudo-version for the latest commit on the dev branch, perhaps v0.0.0-20180523231146-b3f5c0f6e5f1.

Side note: I personally think the new example is much better for someone who is new to Go modules (which at this point of course is most people).

@gopherbot, please add labels modules, Documentation.

**Comment by mvdan** [comment]
ping @rsc for a decision

**Comment by rsc** [comment]
Thanks. golang.org/cl/130140.

**Comment by perillo** [comment]
I'm a bit confused.

With the following go.mod

```
module github.com/perillo/test

require github.com/go-yaml/yaml dev
```

go reports an error: `invalid module version "dev": unknown revision dev`.

When I use v2 it works, because there is a v2 branch on the repository but the resulting version does not became v2.0.0 as reported in the example, but v2.1.0+incompatible.

Finally, when I use v2.2 it reports an error:
`invalid module version "v2.2": no matching versions for query "v2.2"`

Can I suppose that support for non-canonical version identifiers has been removed?

I'm using `go1.11.5 linux/amd64`
