### ISSUE TITLE
os/signal: TestAtomicStop fails on dragonflybsd

### ISSUE THREAD

**Issue by tdfbsd** [golang/go#27137]
I'm seeing a fair amount of flakiness in TestAtomicStop on the dragonflybsd builder. Some recent examples:

https://build.golang.org/log/db81785148210a9493ea8327ebed605e5edb148f
https://build.golang.org/log/c6a7018d2725db0845999d53a48f0f30520c54b8
https://build.golang.org/log/0fdb68deb085ad75fd786b1e498e5f1bf8009269

Using Go 1.10 and a recent dragonfly build.

**Comment by dmitshur** [comment]
/cc @ianlancetaylor as owner of `os/signal`.

There is a lot of red for dragonfly/amd64 on build.golang.org on tip (almost half are fail). I've checked 5 pages worth and none of them are `TestAtomicStop` tests failing. Most of the failures are related to networking timeouts.

I'll close this since it doesn't seem to be an issue anymore, but we can re-open otherwise.

**Comment by tdfbsd** [comment]
Sounds good. There does seem to be persistent but random problem connecting to the local test webservice, but I'm not having much luck tracking it down.
