### ISSUE TITLE
builders: linux-s390x-ibm has no space left on device

### ISSUE THREAD

**Issue by tklauser** [golang/go#27141]
Recent builds have been failing on linux-s390x-ibm with messages like

```
/var/buildlet/go-linux-s390x-bootstrap/pkg/tool/linux_s390x/link: flushing $WORK/_/data/golang/workdir/go/src/cmd/dist/_obj/exe/a.out: write $WORK/_/data/golang/workdir/go/src/cmd/dist/_obj/exe/a.out: no space left on device
```

https://build.golang.org/log/70d02de37115ec58a773a000bdb7d3ad5aa0ee11

/cc @mundaym

**Comment by mundaym** [comment]
The system only has a ~6GB root partition which seems to be slowly filling up, presumably due to updates etc. It was always a bit tight, filling up occasionally with temporary files. I've moved /tmp to a larger partition (~90GB free) to give a bit more breathing room and deleted some other unused files I found. Hopefully that will be enough to fix the issue for the time being.

/cc @billotosyr
