### ISSUE TITLE
all: write release blog post

### ISSUE THREAD

**Issue by andybons** [golang/go#27155]
Move to the next major release milestone once this is completed.

**Comment by cagedmantis** [comment]
The go1.14 blog post has been created. It will be submitted once 1.14 has been released. Moving this ticket to the next major milestone.

**Comment by dmitshur** [comment]
@pearring and I have a Go 1.16 blog post draft ready and will be publishing it as part of the Go 1.16 release.

Because this issue is marked as a release-blocker, @golang/release ends up seeing it throughout the 6 month cycle, but it's usually not at all actionable until the last week. We already track the task of starting the blog post draft and publishing it in our release plan, so it won't be missed. (We can and do filter out by the "recurring" label, but other recurring release blocking issues are still more useful to see occasionally.) So, I'm going to close this.
