### ISSUE TITLE
cmd/compile: math.Float32frombits and math.Float32bits round-trip mismatch

### ISSUE THREAD

**Issue by dsnet** [golang/go#27193]
Consider the following:
```go
var got, want bool
for i := uint32(0x7f8ddc7e); i <= uint32(0x7f8ddc7e); i++ {
	got = i == math.Float32bits(math.Float32frombits(i))
}
i := uint32(0x7f8ddc7e)
want = i == math.Float32bits(math.Float32frombits(i))
if got != want {
	print("FAIL")
}
```
I expect this to work fine.
However, this currently prints "FAIL".

Bisect identifies https://go-review.googlesource.com/62250 as the cause.

\cc @cherrymui @mundaym

**Comment by dsnet** [comment]
Setting Go1.12, since this was introduced in Go1.10.

**Comment by mundaym** [comment]
A runnable link: https://play.golang.org/p/k8rl-o_h97k.

This is a weird one. The constant propagated version of the round trip changes `0x7f8ddc7e` into `0x7fcddc7e`, effectively an OR with 0x00400000.

It is probably worth backporting the eventual fix to 1.11.1 and 1.10.x since it is a codegen bug but we can figure that out once we have a fix.

**Comment by mundaym** [comment]
I think the problem is that the float32 bit pattern `0x7f8ddc7e` corresponds to an sNaN. During the constant propagation we convert that value to a float64 so that it can be stored in an AuxInt. This conversion produces the bit pattern `0x7ff9bb8fc0000000`. So during the conversion the processor has set the MSB of the mantissa to 1 to produce a qNaN. I see two possible remedies:

1. We write our own fully reversible float32 -> float64 and float64 -> float32 implementations using integer operations and use these throughout the backend.
2. Add a Float32 AuxInt type.

I'm leaning towards option (2) since option (1) requires us to remember to use the special conversion functions in future CLs. Any thoughts @cherrymui @randall77?

This is probably obscure enough to wait for Go 1.12.

**Comment by cherrymui** [comment]
I'm also leaning towards option (2). So we don't do a conversion unless the input program needs one. I think this is simpler.

Or maybe we could just store the bit pattern as an uint32 AuxInt? And do `Float32frombits` when we need to do arithmetics on them.

**Comment by randall77** [comment]
I like option 2 as well.
Go 1.12 is fine.  Obscure + easy workaround.

Just so I understand, the underlying problem is that the float32->float64 conversion changes a signaling NaN to a quiet NaN?

Joe, was there some real code that triggered this bug?

**Comment by dsnet** [comment]
> Joe, was there some real code that triggered this bug?

I was writing [unit tests for protobuf serialization](https://go-review.googlesource.com/c/protobuf/+/129404/2/internal/encoding/pack/pack_test.go#251) and wanted to make sure float fields preserved the bits exactly as is round-trip. I don't think this bug is affecting anyone in production. 

I should note that a similar bug also affects the float64 versions of these functions, so I'm not sure why a float32 <-> float64 conversion is the cause.

**Comment by randall77** [comment]
I tried modifying your example for 64-bit and it passes.
Do you have a failing 64-bit example handy?

**Comment by dsnet** [comment]
Hmmm, I just re-ran my tests without the 64-bit workaround and it passes, so it only affects the float32 versions. My mistake.

**Comment by mundaym** [comment]
> Just so I understand, the underlying problem is that the float32->float64 conversion changes a signaling NaN to a quiet NaN?

Yeah, that's right. Happens on both the platforms I've investigated (amd64 and s390x). The behavior on Intel is documented in the architecture manual, section 4.8.3.5. On s390x the behavior is specified by the result tables for the relevant instructions in the principles of operation.

**Comment by mundaym** [comment]
I sent the above CL for now. It's a small change that should fix the issue and can be backported if needed.

The assemblers expect float64 constants to be encoded as float64 values so option (2) is a much bigger change. We can either do the conversions in the compiler (in which case we'll need something equivalent to the functions added in CL 132956 anyway) or we can modify the assemblers to expect float32 values. Either way I think I'd rather fix this bug first and then make the bigger change a bit later.
