### ISSUE TITLE
what is an error ? can't load package: package .: no Go files in c:\go\.vscode exit status 1 Process exiting with code: 1

### ISSUE THREAD

**Issue by jain108shubhamtbt** [golang/go#27273]
can't load package: package .: no Go files in c:\go\.vscode
exit status 1
Process exiting with code: 1

please help

**Comment by jain108shubhamtbt** [comment]
this error is coming when i am going to debug code golang code in vs code

**Comment by agnivade** [comment]
Hi @jain108shubhamtbt,

Thank you for raising the issue. Unfortunately you have deleted the issue template and there is not enough information on what _exactly_ you did so that we can debug this at our end. You have not uploaded any code, nor you have mentioned the steps to reproduce the issue. 

I would request you to open another issue with the complete issue template and possibly a reproducible code sample with the steps to get the error.

Thanks.
