### ISSUE TITLE
misc/cgo: Go 1.10.4 broke Ethereum's cgo

### ISSUE THREAD

**Issue by bradfitz** [golang/go#27280]
@karalabe filed a bug report:

https://twitter.com/peter_szilagyi/status/1034052054732431360

> Dear @FiloSottile and @golang. Your 1.10.4 backport broke CGO projects without warning. E.g. https://travis-ci.org/ethereum/go-ethereum/jobs/420578124#L168 …
>
> At least a warning would have been welcome that you're introducing breaking CGO changes into a patch release.

Copying it here.

@randall77, I think most of those cgo changes were yours? Could you take a look?

/cc @ianlancetaylor

**Comment by randall77** [comment]
Yes, sorry about this.  We had to include a more complete bad-pointer detector to fix other issues.

If you use `C. kCFAllocatorDefault` instead of `nil` for your allocator arguments, that should fix things.
It looks like the owner of the package involved has already [updated his package](https://github.com/rjeczalik/notify/commit/73bc5b1b2ed9497cd7a0b297a5acfef88eb0e3ad). You would just need to revendor it.

**Comment by karalabe** [comment]
We opened that fix and already vendored it too. I guess my concern was mostly that all our build infra used 1.10.x releases on all fronts to push out the builds and all of a sudden everything became red.

**Comment by bradfitz** [comment]
Sorry about this. We try hard to be really conservative in what we put in patch releases, but sometimes stuff happens. Doubly so whenever cgo is involved.

Closing, as it sounds like there's nothing to do.
