### ISSUE TITLE
cmd/compile: GOEXPERIMENT=clobberdead is broken

### ISSUE THREAD

**Issue by cherrymui** [golang/go#27326]
### What version of Go are you using (`go version`)?
tip (618bfb28dc02c410659312f38cd3500352ba15ed)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
```
$ GOEXPERIMENT=clobberdead ./all.bash 
Building Go cmd/dist using /Users/cherryyz/src/go1.8.
Building Go toolchain1 using /Users/cherryyz/src/go1.8.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: /Users/cherryyz/src/go-tip/pkg/tool/darwin_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
```

Not sure if it catches a real bug, or the experiment itself is broken. I may take a look tomorrow.

**Comment by randall77** [comment]
Now that we have stack objects, there's the additional complication that we can't clobber stack objects (all address-taken local variables) because plive doesn't know for sure that they are dead anymore.

`clobberdead` was originally intended to test all the weird ambiguously live logic. Maybe now that all that logic is gone, we can retire this mode.
