### ISSUE TITLE
 just a suggestion

### ISSUE THREAD

**Issue by pennkao** [golang/go#27367]
I think golang's package import heavily dependent on url, not very elegant
example:
package on github.com/abc/def
code:
    import "gitlab.com/abc/def"

If the packet path changes,I need to modify the package path in the code
I can only prevent this from happening

In other countries, I can't access Google, I can only find the address of each package to download
My ideal package is like java package, the package has nothing to do with url

package on github.com/username/packagename
import "packagename"

I like golang, a lot. The only thing I don't feel good about is this.
It's just a suggestion

**Comment by mccolljr** [comment]
I think the module system that is packaged with go as of go1.11 is going to help us move away from url-based imports (slowly). However, there's nothing stopping you from putting code in a different place than the URL-based import path. If your code is the only code importing the package, you can place it wherever you feel it belongs. If other code is expecting the import path to be something like "github.com/blah/blah" then you will get a compiler error and will know where to move the code.

As for just using the last piece of the URL to form the import name, you would probably break a lot of existing code since some packages share a base name but have different import paths.

**Comment by mvdan** [comment]
This seems like a discussion that should be moved to one of the forums, such as golang-nuts. The issue tracker is generally for bugs and specific proposals to the standard library and language. I'm going to close this for now, but please feel free to continue this: https://github.com/golang/go/wiki/Questions
