### ISSUE TITLE
x/build: dragonfly getting stuck on builds

### ISSUE THREAD

**Issue by tdfbsd** [golang/go#27405]
The revert commit a700ae9 fixed a problem that was causing the dragonfly builder to hang forever (instead of failing) when attempting to build anything later than commit e6c1594. Please manually fail commits:

- [x] e6c1594 - https://build.golang.org/log/57c6ebe73af7f9ec841f6fd6072b254458a97a1b
- [x] 38143ba
- [x] b7d3e14
- [x] eae5fc8
- [x] 969b9d8
- [x] 21af0c1

Otherwise, the builder will continue to revisit those commits and hang.

**Comment by dmitshur** [comment]
Ok, I've learned how to do this and manually failed those builds now. It should be safe to keep the dragonfly builder running now. Please let me know if there's anything else.

For posterity, I used the approach @bradfitz recommended, which was to hit the `/result` [endpoint](https://github.com/golang/build/blob/1329dced3a4569a7cd5cb59ca5dfb01adf65be2a/app/appengine/handler.go#L993) of the dashboard (https://build.golang.org) manually with a one-off Go command; I'll clean it up and upstream it if this needs to be done more often. It was based on [code in coordinator](https://github.com/golang/build/blob/1329dced3a4569a7cd5cb59ca5dfb01adf65be2a/cmd/coordinator/dash.go#L92-L126). The endpoint requires a builder key, which I have access to.

Ideally, we should resolve the underlying issue and make it so that the builder has a timeout and doesn't hang forever on some bad commits.
