### ISSUE TITLE
scratch: add doc.go

### ISSUE THREAD

**Issue by kevinburke** [golang/go#27427]
I set up a custom domain so the scratch repo is "go get" able, and godocs are now browsable: https://godoc.org/goscratch.club

However this now makes clear that we should have a `doc.go` alongside the README at the top level of that project, even if it's just really basic and points people elsewhere.

**Comment by dmitshur** [comment]
> I set up a custom domain so the scratch repo is "go get" able, and godocs are now browsable: https://godoc.org/goscratch.club

For posterity, the packages inside the scratch repo were always go gettable at their canonical source:

https://godoc.org/go.googlesource.com/scratch.git

The ".git" suffix is necessary because go.googlesource.com isn't one of the few common code hosting sites that have special syntax. The mechanism is documented at https://golang.org/cmd/go/#hdr-Remote_import_paths, starting at the "For code hosted on other servers" paragraph.
