### ISSUE TITLE
access: marwan-at-work Editor Access

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#27431]
I'd love to help with assigning labels (primarily for Go Modules) so that the appropriate people can get to issues faster :) 

Group URL: https://github.com/orgs/golang/teams/go-approvers

Thanks!

cc: @ianthehat @bcmills @andybons @myitcv

**Comment by myitcv** [comment]
Adding a bit of context here; @marwan-at-work has been very active on the modules stuff in `#modules` on Slack as well as the tooling conversations we kicked off at GopherCon.

**Comment by andybons** [comment]
Hi Marwan,
Thanks for helping out! gopherbot allows you to assign labels without being in the group for precisely this use-case: https://golang.org/wiki/GopherBot#addingremoving-labels

Does that cover your use-case adequately? If not just let me know.

**Comment by myitcv** [comment]
Hi @andybons - it was actually me who suggested @marwan-at-work request access, so mea culpa!

Reason for suggesting is that, yes, this can be done via gopherbot (and @marwan-at-work and others have been doing just that), but anyone subscribed to the issue already (or indeed anyone who has the firehose of issues turned on) gets a message for every such update. Indeed if everyone who updated labels used gopherbot instead of the "silent" issue updates then the issue would be significantly worse.

So I figured that suggesting @marwan-at-work request GitHub access was preferable. 

Thoughts?

**Comment by andybons** [comment]
I suppose one can start with using gopherbot as a signaling tactic and then get access to the project. How I wish GitHub had more granular permissions. Will give access.

**Comment by myitcv** [comment]
> I suppose one can start with using gopherbot as a signaling tactic and then get access to the project. 

That sounds like an excellent way forward.

> How I wish GitHub had more granular permissions.

Seconded.

> Will give access.

Thank you for considering this.

**Comment by marwan-at-work** [comment]
🎉 🎉 thank you both :)
