### ISSUE TITLE
Golang not running function which returns bool, if the bool value is unneeded ahead

### ISSUE THREAD

**Issue by thiremani** [golang/go#27511]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
I'm not sure if this is a bug or intended behaviour. I'm running a function in a for loop, which returns true or false based upon if its execution is proper or no as so:

```
ret := true
for i := 0; i < 10; i++ {
    ret = ret && f(i)
}
```
I'm guessing if the function f returns false for some i < 10, the compiler understands that the variable ret will be false now, since its an && operation in the for loop. Hence it does not execute function f for i greater than this value. This does break the intuition that the function would be run for all values of i given.

https://play.golang.org/p/MMjmK_XW9SV

### What did you expect to see?
The function f(n) should have run for all the values of i from 1 to 10. 

### What did you see instead?
As the function returns false for i = 4, the function is not executed for values greater than this.

**Comment by AlexRouSg** [comment]
When you do a `&&`, it will stop checking the instant something evaluates to false. 
So since `ret` is the first value, it stops running `f(i)` when i > 4.

If you want to use the `&&` operator in this manner, you need to swap the order so that it evaluates `f(i)` first. e.g. `f(i) && ret`

As the bug tracker is not normally used for questions, in the future if you are not sure something is a bug, please ask around in one of the places listed in https://github.com/golang/go/wiki/Questions

**Comment by thiremani** [comment]
Thanks, the spec makes it pretty clear. I wouldn't mind shifting this into questions, or closing the issue.
