### ISSUE TITLE
sync: need a way to guarantee that WaitGroup.state1 fields are always 4-bytes aligned

### ISSUE THREAD

**Issue by go101** [golang/go#27577]
I have noticed and am glad that the suggestion mentioned in https://github.com/golang/go/issues/19149 is adopted. But I feel the current new implementation is still not perfect.

The [current implementation](https://golang.org/src/sync/waitgroup.go?s=574:929#L10) assumes that the `WaitGroup.state1` field is always 4-bytes aligned, but I can't find any such guarantee is written down in any official Go documentation.

So I suggest that we should add a method like the following for `*WaitGroup`. The method will never be called, it just gives compilers a hint that the `WaitGroup.state1` field needs to be 4-bytes aligned.

```golang
func (wg *WaitGroup) _() {
	_ = atomic.LoadUint32(&wg.state1[0])
}
```

**Comment by randall77** [comment]
`WaitGroup.state1` is a `[3]uint32`.  It will be 4-byte aligned on all platforms we support.
It's not _guaranteed_ as we don't talk about alignment in the spec. But we align all Go data types to their natural alignment up to a platform-specific maximum alignment, which is at least 4 on all platforms. It is very likely to remain at least 4 because pointers need to be aligned (to avoid shearing pointers).

**Comment by CAFxX** [comment]
Can't this be solved simply by adding a test that will make all.bash fail if the field doesn't have the expected alignment?

**Comment by ianlancetaylor** [comment]
@CAFxX A `sync.WaitGroup` can appear in user code that all.bash will never see, but it still has to be aligned correctly.

**Comment by go101** [comment]
Closed, for WaitGroup aligns fields by using atomic.Uint64 /
