### ISSUE TITLE
x/crypto/openpgp: implement certification revocation signature

### ISSUE THREAD

**Issue by aviau** [golang/go#27602]
It would be great if the openpgp package implemented Certification revocation signature as defined in RFC4880.

Currently, depending on the packet ordering, the openpgp package can add revoked identities to the entity's identities slice, this can be misleading because there is no possibility to see that it has been revoked.

**Comment by aviau** [comment]
ping @FiloSottile, you reviewed one of the dependencies but not the main changeset.

Cheers,

**Comment by aviau** [comment]
Ping @FiloSottile. You mind me reminding you again?

The changeset is here: https://golang.org/cl/118995

**Comment by aviau** [comment]
I'll try again...

Ping @FiloSottile

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
