### ISSUE TITLE
Incorrect work strings.Replace() when input string has a special formatting symbols like \t

### ISSUE THREAD

**Issue by aleksaan** [golang/go#27637]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?

package main

import (
	"fmt"
	"strings"
)

func main() {

	input := "C:\temp" // \t is a special formatting symbol
	fmt.Printf("Input: %q\n", input)

	//replace : to X - success
	output := strings.Replace(input, ":", "x", -1)
	fmt.Printf("Replace ':' to 'x': %q\n", output)

	//replace emp to X - success
	output = strings.Replace(input, "emp", "x", -1)
	fmt.Printf("Replace 'emp' to 'x': %q\n", output)

	//replace temp to X - fail
	output = strings.Replace(input, "temp", "X", -1)
	//next failed because in the input we have a special symbol \t
	fmt.Printf("Replace 'temp' to 'x' (FAILED): %q\n", output)

}

### What did you expect to see?
After strings.Replace("c:\temp, "\\\\", "/", -1) I expect to get: 
c:/temp

### What did you see instead?
c:\temp

**Comment by dominikh** [comment]
This is working as intended, and caused by a misunderstanding of how string literals and escape sequences work.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by aleksaan** [comment]
There isn't auto-redirecting to go-wiki for no-bug-questions ?
