### ISSUE TITLE
x/text: plural.Zero doesn't work as expected

### ISSUE THREAD

**Issue by olivere** [golang/go#27724]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.11 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/oliver/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/oliver"
GOPROXY=""
GORACE=""
GOROOT="/Users/oliver/go"
GOTMPDIR=""
GOTOOLDIR="/Users/oliver/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vx/tzlnk7sx0bsckdbj2j_0t0k00000gn/T/go-build015279889=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
$ cd feature/plural
$ go test -run=Example -v
=== RUN   ExampleSelect
--- PASS: ExampleSelect (0.00s)
PASS
ok  	golang.org/x/text/feature/plural	0.005s

# Edit example_test.go and replace "=0" with plural.Zero

$ git diff
diff --git a/feature/plural/example_test.go b/feature/plural/example_test.go
index c75408c..2938c4c 100644
--- a/feature/plural/example_test.go
+++ b/feature/plural/example_test.go
@@ -14,7 +14,7 @@ func ExampleSelect() {
        // Manually set some translations. This is typically done programmatically.
        message.Set(language.English, "%d files remaining",
                plural.Selectf(1, "%d",
-                       "=0", "done!",
+                       plural.Zero, "done!",
                        plural.One, "one file remaining",
                        plural.Other, "%[1]d files remaining",
                ))

$ go test -run=Example -v
=== RUN   ExampleSelect
--- FAIL: ExampleSelect (0.00s)
got:
nog één bestand te gaan
klaar!
want:
5 files remaining
one file remaining
nog één bestand te gaan
klaar!
FAIL
exit status 1
FAIL	golang.org/x/text/feature/plural	0.004s
```

### What did you expect to see?

I expect to see the same results regardless if using `"=0"` or `plural.Zero`.

### What did you see instead?

I see the example code silently ignoring pluralization cases.

**Comment by odeke-em** [comment]
Thank you for this report @olivere! Kindly paging @mpvl

**Comment by vikramcse** [comment]
@odeke-em Can I work on this issue?

**Comment by odeke-em** [comment]
@vikramcse, all yours and thank you!

**Comment by vikramcse** [comment]
@bcmills @odeke-em Hello there
Here are my findings 
1. I think in file [gen_common.go](https://github.com/golang/text/blob/master/feature/plural/gen_common.go#L19), the ordering of the constants is wrong. The ordering should be like this.
```go
const (
	Zero Form = iota
	One
	Two
	Few
	Many
        Other
)
```
I did try changing above constants structure and run `go generate` but it did not solved problem.

3. Let's consider below test case
```go
message.Set(language.English, "%d files remaining",
		plural.Selectf(1, "%d",
			plural.Two, "2 files remaining",
		))

p := message.NewPrinter(language.English)
p.Printf("%d files remaining", 2)
```
In above case we are passing `plural.Two` as a case which has byte value `3` (because of the wrong order).
The selector type `3` does not match the `valid cardinal rules` list in this case which is [0, 2] which is returned by [validForms](https://github.com/golang/text/blob/master/feature/plural/plural.go#L133) function; further the valid list is used by this [code](https://github.com/golang/text/blob/master/feature/plural/message.go#L146) but it's throwing error  `s:"plural: form '\x03' not supported for language "en""` as the value `3` does not match with [0, 2]

I am not sure how to take this further, I need some help to solve this issue.

Thanks

**Comment by bcmills** [comment]
> I need some help to solve this issue.

@mpvl is the right person to help. (He's the primary owner of `x/text`.)

**Comment by mpvl** [comment]
Other has special meaning in CLDR and really should be 0. But I will look in to this.

**Comment by mpvl** [comment]
working as intended.
