### ISSUE TITLE
panic: net/rpc: add recover handle goroutine call?it's too easy cause app crash

### ISSUE THREAD

**Issue by chslink** [golang/go#27777]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.11 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH=amd64
GOHOSTOS=windows
GOOS=windows

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/h_dtcgMxj8M

### What did you expect to see?
because nil pointer it's very easy pass compile check,or any other panic,and it'will cause server application crash.

### What did you see instead?
add recover function handle go/src/net/rpc/server.go:481 or go/src/net/rpc/server.go:384 goroutine call

**Comment by bcmills** [comment]
Per https://golang.org/pkg/net/rpc/:
> The `net/rpc` package is frozen and is not accepting new features.

(but I'll CC @robpike just in case he thinks this one is trivial enough.)

In general, I would recommend fuzz-testing your server (e.g. using `go-fuzz`) to root out these sorts of issues. Unexpected `recover`s can leave a binary deadlocked or otherwise compromised, so they're not a panacea.

**Comment by robpike** [comment]
Would rather not make such a substantive change to this frozen package. Leaving closed.
