### ISSUE TITLE
boringcrypto: create the dev.boringcrypto.go1.11 branch

### ISSUE THREAD

**Issue by tzneal** [golang/go#27799]
Can someone create the go1.11 boringcrypto branch?  Not sure how to to it, or I'd put up a PR.

CC @FiloSottile

**Comment by FiloSottile** [comment]
Created `dev.boringcrypto.go1.11` at `7eb1677c01c3decc510270d532ed69d0bf42bffa`, the last commit on `dev.boringcrypto` before it got merged with `master` after `release-branch.go1.11` branched.

https://go-review.googlesource.com/c/go/+/137135 brings it up to date with `go1.11`.

https://go-review.googlesource.com/c/go/+/137136 cherry-picks the only change that happened on `dev.boringcrypto` since.
