### ISSUE TITLE
TempFile "*".suffix not replacing "*" with random string as expected

### ISSUE THREAD

**Issue by AaronKronberg** [golang/go#27882]
### What version of Go are you using (`go version`)?
1.10.3, but getting same result on go playground

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
Creating at temp file with a suffix after the random string does not seem to work. 

Per the docs: "The filename is generated by taking pattern and adding a random string to the end. If pattern includes a " * ", the random string replaces the last " * ".

Here's example in the playground:
(I just added a Println to the example in the ioutil.TempFile GoDoc to show the file name)
https://play.golang.org/p/JAOZUSeNUBB

### What did you expect to see?
/tmp/example.054003078.txt

### What did you see instead?
/tmp/example.*.txt054003078

**Comment by ALTree** [comment]
Thanks for the report.

The `TempFile` `*` thing was introduced in go1.11. The playground is still on 1.10. Your example correctly prints `/tmp/example.740841582.txt` with go 1.11 on my machine. Please try with 1.11 and comment here if it still doesn't work for you. Closing here, in the meantime, since I don't believe this is a bug
