### ISSUE TITLE
spec: two's complement and signed overflow

### ISSUE THREAD

**Issue by seebs** [golang/go#27903]
### What version of Go are you using (`go version`)?

1.11

### Does this issue reproduce with the latest release?

N/A (doc issue)

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

read the spec

### What did you expect to see?

maybe slightly more detail

### What did you see instead?

"The value of an n-bit integer is n bits wide and represented using two's complement arithmetic."

"For signed integers, the operations +, -, *, /, and << may legally overflow and the resulting value exists and is deterministically defined by the signed integer representation, the operation, and its operands."

Intuitively, I assume this intends to express that, in int16, 32767+1 = -32768.

I'm not sure it actually specifies that, though. I believe there have existed CPUs which had 2s complement representations, but implemented (at least as an option) saturating arithmetic, so I don't think it's obvious that knowing that we're using 16-bit two's complement, and have 32767, and 1, and addition, tells us that we're expecting -32768.

More generally, this feels oddly stilted. Why does it specify "the signed integer representation" as though it were a thing which could vary from one circumstance to another, when the spec explicitly mandates two's complement?

On the other hand, I can't figure out how to say it more clearly; trying to actually specify it produces gratuitously complicated expressions. But possibly explicitly stating that it "wraps" would be clear-enough, especially if accompanied by an example, like:

```
i := int16(32767)
i += 1 // i is now -32768
```
This is probably harmless, but it's bugging me that I can't quite get from the words to what i'm pretty sure they mean.

**Comment by cznic** [comment]
CPUs are irrelevant here. On any conforming implementation the program will observe the same result. How it's done for different CPUs is an implementation detail.

**Comment by griesemer** [comment]
The spec is perfectly sufficient here. The section on numeric types mentions the representation (2's complement arithmetic) with a link to a detailed Wikipedia description. There's a no mention of "saturating arithmetic" here, so don't expect that. The section on Integer overflow also is pretty clear. The "stilted language" is simply a work-around to not have to explicitly define 2's complement wrap-around. We refer to the "signed integer representation" (rather than two's complement) here because in this section we don't define this again, we use the definition of the numeric types section.

Maybe this is not 100% bullet-proof, but that's not the point. Any reader familiar with two's complement arithmetic (again, defined in detail through the link in the doc) will make an obvious assumption about how this is supposed to work, and that assumption is the correct one. Anything else would be surprising.

I'm going to close this; I believe this is fine. If you feel strongly about it, feel free to send me a CL that adds 2-3 examples to the Integer Overflow section that will make this abundantly clear. Thanks.

**Comment by seebs** [comment]
Thanks! I wanted a second pair of eyes but consider your response persuasive. I'd mostly worked around to convincing myself that the difficulty of defining 2's complement wrap-around is sufficient justification for this.

I don't think that the representation actually defines wrapping in and of itself, because the representation only defines how any specific number is represented, it doesn't actually tell you that 32767+1 => -32768. But you can infer it from "that is where the carry would put that 1 bit".

(And I might end up sending an additional example for the Overflow section, but I'm not sure it's useful.)

**Comment by griesemer** [comment]
You're right that two's complement refers to the representation of a number; but - again, barring any surprises - an implementation will implement operations such as addition and subtraction in a natural way (treating an n-bit signed integer as an n-bit unsigned integer). After all, that's the whole point of two's complement arithmetic: the representation of negative numbers is cleverly chosen such that there's no separate hardware needed for signed and unsigned numbers (at least for many of the operations). I think one would be hard-pressed to find a modern-day CPU that behaves differently in that respect.
