### ISSUE TITLE
go/types: better error message for invalid method receiver

### ISSUE THREAD

**Issue by griesemer** [golang/go#27996]
For
```Go
package p

type T struct{}

type T1 = *T

func (T1) m() {}

func _() {
	(&T{}).m()
}
```
go/types reports
```
x.go:10:9: invalid operation: (&(T literal)) (value of type *T) has no field or method m
```
which is misleading. The reason is that it drops the method m on the floor completely. Instead it should complain about the receiver.

See also issue #27995 .

**Comment by beoran** [comment]
But when I look in the spec at the definition of alias I see this: 
`Alias declarations
An alias declaration binds an identifier to the given type.
AliasDecl = identifier "=" Type .
Within the scope of the identifier, it serves as an alias for the type.
type (
	nodeList = []*Node  // nodeList and []*Node are identical types
	Polar    = polar    // Polar and polar denote identical types
)`
This suggests to me that T1 is identical to *T, and thus a valid method receiver.
I think with the current spec both examples should compile, although I admit using a type alias to hide a pointer is bad style. Otherwise the spec should be clarified on how aliases work together with method definitions.

**Comment by go101** [comment]
It looks gc think the code is valid.

**Comment by griesemer** [comment]
@beoran @go101 Please discuss the validity of this at #27995. That's why I opened that one. This issue is just a reminder to follow up on go/types. Thanks.

**Comment by griesemer** [comment]
This was fixed with https://golang.org/cl/143179 which made this kind of declaration valid in the first place. Closing.
