### ISSUE TITLE
cmd/go: mod vendor should work offline

### ISSUE THREAD

**Issue by mihaiav** [golang/go#28029]
### What version of Go are you using (`go version`)?
go1.11 darwin/amd64
 
### What operating system and processor architecture are you using (`go env`)?
OSX 10.14  

### What did you do?
go mod vendor -v 
### What did you expect to see?
It tries to download the dependencies from the network. Unfortunately some dependencies are not available over the network because I'm using vanity domain names and the infrastructure that provides support for the vanity domain name(i.e. the http server serving the go vanity meta tags) depends on the program I'm trying to build/vendor.

  I need a way to copy the dependencies into the vendor directory from the local disk/GOPATH instead to download them just like `govendor +external` tool did. Is there any such feature planned?

  I've tried to set GOPROXY to GOPATH ( `export set GOPROXY=$GOPATH/src `) but when I do that go mod vendor reports `no dependencies to vendor`

**Comment by thepudds** [comment]
Hi @mihaiav, is your example a case where `go get` in 1.11 seems to work for you to get X, but `go mod vendor` fails for X?  Or does `go get` in 1.11 seem to exhibit the same issue you are reporting for `go mod vendor`? 

I suspect you have a few options, but probably worthwhile to say a few more words about your goals.

Vendoring with modules in 1.11 might be one approach that ends up working out for you.

That said, an alternative approach might be one of a few different options involving `GOPROXY` environment variable.

For example, `GOPROXY=file:///filesystem/path` environment variable tells the go commands to use a filesystem (local or remote) to resolve dependencies, without any need to have an actual running proxy process. In general for modules, the go command (e.g., `go get` or `go build`) automatically stores downloaded dependencies in its local cache ($GOPATH/pkg/mod), and its cache layout is the same as the requirements for a proxy, so that cache can be used as the content for a filesystem-based GOPROXY or simple webserver used as a GOPROXY. In addition, `go mod download` populates $GOPATH/pkg/mod/cache/download, which means that command can be used to pre-populate or update the contents for a GOPROXY. You can read some more details in the [tip documentation](https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol), especially the description at the end of that 'Module proxy protocol' documentation section.

Also, here is a nice end-to-end example from @myitcv of using GOPROXY with a filesystem:
https://github.com/myitcv/go-modules-by-example/tree/master/012_modvendor

However, the best approach likely depends on exactly what you are trying to do, and what your exact constraints are.

**Comment by bcmills** [comment]
You should be able to set up a `replace` directive pointing to the local filesystem, then run `go mod vendor` to copy the replaced source into the `vendor` directory.

The [mod_vendor_replace](https://github.com/golang/go/blob/master/src/cmd/go/testdata/script/mod_vendor_replace.txt) test verifies that behavior. It's part of the fix for #27859, so you may have to build from source (from commit `
f8153fc` or later) to pick up that fix.
