### ISSUE TITLE
Can't use json.Unmarshal on self inside an UnmarshalText function

### ISSUE THREAD

**Issue by CrushedPixel** [golang/go#28119]
An `encoding.TextUnmarshaler` can't use the `encoding/json` and `encoding/xml` packages to deserialize a json/xml representation of itself. This is probably because `encoding/json` treats types implementing `encoding.TextUnmarshaler` in a special way.

This simple project reproduces the issue: https://play.golang.org/p/huW7nqPqNCW

When unmarshaling, the following error is returned: 
```go
json: cannot unmarshal object into Go value of type *main.Test
```

Unmarshaling the json representation into a `map[string]interface{}` works just fine.

**Comment by ianlancetaylor** [comment]
Your code can't work.  You are implementing the unmarshaling of Test by unmarshaling into Test.  That will simply lead to an infinite recursion.  The package is saving you from that by returning an error.

Do something like this instead: https://play.golang.org/p/KvZogax4MRQ

**Comment by CrushedPixel** [comment]
Can you elaborate why `encoding/json` looks at the `UnmarshalText` implementation when unmarshaling an object?

**Comment by ianlancetaylor** [comment]
It's possible that I've misdescribed what the encoding/json package is doing, but as far as I can see it's still the case that your original program can't work.

**Comment by CrushedPixel** [comment]
I see no reason why `encoding/json` would need to look at its `UnmarshalText` function when mapping a json object to a struct. Nothing in the documentation indicates this, and I honestly expected it to perform the json parsing as usual, without looking at `UnmarshalText`. If I was implementing `json.Unmarshaler`, I'd be on your side with the infinite recursion, but not like this.

**Comment by ianlancetaylor** [comment]
OK, maybe I see what you mean.  Given a type that implements the `UnmarshalText` method and an input that is not a JSON quoted string, we can either ignore the `UnmarshalText` or we can return an error.  Since `UnmarshalText` was implemented, we've returned an error (https://golang.org/cl/12703043).  I suppose that perhaps the question is which operation is less confusing: honoring `UnmarshalJSON` but ignoring `UnmarshalText`, or honoring `UnmarshalJSON` and giving an error for `UnmarshalText`.
