### ISSUE TITLE
go/build: build.Import function doesn't respect go.mod

### ISSUE THREAD

**Issue by go101** [golang/go#28192]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.11.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```golang
if pkg, err := build.Import(pkgpath, "", build.FindOnly); err != nil {
	log.Print(err)
}
```
where `pkgpath` is the import path of a local package in a project supporting modules. 
The project is outside GOPATHs.

### What did you expect to see?

No errors.

The package can be loaded with `conf.Check`.

### What did you see instead?

```
cannot find package "github.com/ghuser/myproject/foo" in any of:
	/home/username/sdks/go/src/github.com/ghuser/myproject/foo (from $GOROOT)
	/home/username/go/src/github.com/ghuser/myproject/foo (from $GOPATH)
```

**Comment by myitcv** [comment]
@go101 - this is happening because you are supplying an [empty `srcDir`](https://github.com/golang/go/blob/master/src/go/build/build.go#L968) as your second argument.

[`go/packages`](https://godoc.org/golang.org/x/tools/go/packages) provides complete support for Go modules and is recognised as the module-aware replacement for `go/build` (as well as `go/loader`).

I'll close this therefore but please shout if `go/packages` doesn't fit your use case because @ianthehat and team will be interested to hear more about that.
