### ISSUE TITLE
cmd/doc: -src not showing comments in function

### ISSUE THREAD

**Issue by kybin** [golang/go#28195]
recently added -src flag does not showing comments in function.

so, when I run

```
go doc -src bytes.Buffer.ReadBytes
```

It prints

```
// ...
func (b *Buffer) ReadBytes(delim byte) (line []byte, err error) {
	slice, err := b.readSlice(delim)

	line = append(line, slice...)
	return line, err
}
```

But the actual function is
```
// ...
func (b *Buffer) ReadBytes(delim byte) (line []byte, err error) {
	slice, err := b.readSlice(delim)
	// return a copy of slice. The buffer's backing array may
	// be overwritten by later calls.
	line = append(line, slice...)
	return line, err
}
```

**Comment by robpike** [comment]
The old godoc command does the same, so this is likely a property of the go/doc package.
/cc @griesemer

**Comment by griesemer** [comment]
go/doc doesn't do anything special here. The problem is that that comments (except for doc strings) are maintained separately in the AST, and thus printing a node (such as a function node) won't know anything about internal (and non-doc) comments if they are not provided explicitly, e.g. via a go/printer.CommentedNode.

**Comment by agnivade** [comment]
So should this be fixed ? Because godoc also had the same behavior.

**Comment by griesemer** [comment]
I think it would be nice if it were fixed. I think with CommentedNode this shouldn't be too hard.
