### ISSUE TITLE
proposal: x/crypto/hkdf: Allow skipping the extract stage

### ISSUE THREAD

**Issue by mastahyeti** [golang/go#28237]
[RFC5869](https://tools.ietf.org/html/rfc5869) suggests that the extract stage of HKDF's extract-and-expand process can be skipped if there is sufficient entropy in the input key material. Would it be worth providing a separate function for initializing the `hkdf` struct directly?

```go
func NewNoExtract(hash func() hash.Hash, secret, info []byte) io.Reader
```

**Comment by FiloSottile** [comment]
This is also useful to TLS 1.3, so I'm going to add the following two APIs:

* `func Extract(hash func() hash.Hash, secret, salt []byte) []byte`
* `func Expand(hash func() hash.Hash, pseudorandomKey, info []byte) io.Reader`

`pseudorandomKey` is ugly to look at, but that's intentional, as it signals that this should have non-obvious properties to the user. The docs will make it clear it's not the thing you should use in most cases.

By the way, you say "can be skipped if there is sufficient entropy in the input key material", but the criteria is not the amount of entropy (which does not increase with the Extract step), but the distribution and length of the value.
