### ISSUE TITLE
spec: add duplicate nil to the implementation restriction for switches

### ISSUE THREAD

**Issue by griesemer** [golang/go#28378]
See #28357 for details.

**Comment by mdempsky** [comment]
For what it's worth, cmd/compile only warns about duplicate nils for switches on non-interface expressions. That is, it doesn't warn about duplicate nil for switches on interface expressions or at all in map literals.

I'm working on a CL to unify this code. My inclination is to just stop warning about duplicate nils, rather than relax the spec to allow this. We don't even report them correctly, so I doubt anyone's triggering this in practice:

    /tmp/r.go:16:2: duplicate case nil (value 0) in switch
    	previous case at <unknown line number>

**Comment by mdempsky** [comment]
Oh, actually the warnings about duplicate nil in interface switch expressions was removed just recently in eb6c433eb38d9a0e9ecfcc1604f9ff8e035768f6 as part of fixing #28078. And that warning did give a correct previous line number.

**Comment by griesemer** [comment]
The implementation now follows exactly the spec: only duplicate integer, floating-point, and string constants are disallowed.

**Comment by ianlancetaylor** [comment]
Note that the implementation also rejects duplicate boolean constants.

**Comment by griesemer** [comment]
@ianlancetaylor That is not the case, neither with [1.17](https://go.dev/play/p/M9NzMPm2i0f?v=goprev), nor [1.18](https://go.dev/play/p/M9NzMPm2i0f).

**Comment by ianlancetaylor** [comment]
When I run https://go.dev/play/p/BHQnDSDJK_T I see "./prog.go:6:37: duplicate key false in map literal".

**Comment by ianlancetaylor** [comment]
Ah, sorry, you are talking about switches and I am talking about composite literals.
