### ISSUE TITLE
cmd/compile: unnecessary error message

### ISSUE THREAD

**Issue by go101** [golang/go#28376]
### What version of Go are you using (`go version`)?

go version go1.11.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```golang
package main

func main() {
	var a int64
	switch a {
	case int64(123):
	case int32(123):
	}
}
```

### What did you see instead?

gc reports:
```
./aa.go:7:2: invalid case int32(123) in switch on a (mismatched types int32 and int64)
./aa.go:7:2: duplicate case int32(123) (value 123) in switch
	previous case at ./aa.go:6:12
```

Although it is not a big problem, I think the second error message is not very necessary, for it implies int32(123) is comparable to int64(123). (gccgo doesn't report the second error)

**Comment by mvdan** [comment]
Sounds to me like something to fix. /cc @griesemer

**Comment by ManushB** [comment]
The issue seems to be in this function. 
https://github.com/golang/go/blob/bc4a10d16ca8582eaa92e5b834616df55c777503/src/cmd/compile/internal/gc/swt.go#L58

I want to take up the issue but am new to this. Can you suggest the approach?  

In my opinion, a flag should be used to return before calling `checkDupExprCases`.

**Comment by cuonglm** [comment]
go1.14 and go1.15 now report only first message, we can close this now.

I think this is fixed when @mdempsky refactoring the typecheck switch code.

**Comment by go101** [comment]
True. Thanks for the noticing.
