### ISSUE TITLE
vgo name suggestion

### ISSUE THREAD

**Issue by atilkan** [golang/go#28502]
vgo repo doesn't have issues section so i write it here.
vgo idea is cool but the name needs to change. I would suggest **cargo** but it has taken by Rust and after this point it would cause confusion and lets not follow the path of javascript there and nowhere.
How about **dingo** or **flamingo**? Suggestions.

**Comment by agnivade** [comment]
Hi @atilkan,

Thanks for the suggestions. However, `vgo` was just an experimental tool. Modules support has been integrated into the Go main toolchain. So we do not need to name anything separately.

vgo will still remain as a separate tool for people who have not upgraded to 1.11 yet. But since it has moved to the background now, I don't see a need to rename it. Thank you.

**Comment by atilkan** [comment]
@agnivade That is even better. I have been stayed far for a time. I should have known this.
