### ISSUE TITLE
x/build/cmd/gopherbot: duplicate github comments mentioning CLs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28561]
https://github.com/golang/go/issues/28434#issuecomment-435450826 has duplicate comments:

> Change https://golang.org/cl/147117 mentions this issue: syscall: add Syscall18 on Windows

> Change https://golang.org/cl/147117 mentions this issue: syscall: add Syscall18 on Windows

> Change https://golang.org/cl/147117 mentions this issue: syscall: add Syscall18 on Windows

/cc @andybons @katiehockman @dmitshur

**Comment by dmitshur** [comment]
GitHub was having issues today according to https://status.github.com/messages:

![image](https://user-images.githubusercontent.com/1924134/47942396-2deafb00-dec8-11e8-9312-da33ecc4f33f.png)

As long as it's not causing significant problems and doesn't happen too often, it's out of scope for us to make gopherbot behave well during a GitHub API outage or partial outage. Closing because it wasn't a problem in gopherbot.

(If we need to address it in the future, a strategy to consider is to pause gopherbot when the [GitHub Status API](https://status.github.com/api) reports that GitHub API has issues.)
