### ISSUE TITLE
Goroutines kill RAM and system

### ISSUE THREAD

**Issue by johnlarfour** [golang/go#28892]
### What did you do?
This simple code kill my RAM and system it's a bug of goroutines or GC? The memory increase, swap and system crash.
https://play.golang.org/p/QTHBOLRkCnF

**Comment by bcmills** [comment]
> it's a bug of goroutines or GC?

Neither: it's a bug in the program. You can't start an effectively-unbounded number of goroutines and expect them to use a bounded quantity of resources.

In production programs, you probably want some kind of semaphore to limit the number of goroutines in flight. (Search for “semaphore” in https://golang.org/doc/effective_go.html#channels, or see slide 91 of [my talk](https://drive.google.com/file/d/1nPdvhB0PutEJzdCq5ms6UI58dp50fcAN/view).)

**Comment by johnlarfour** [comment]
Sorry sir, but I don't agree. If I can destroy my system with 18 lines of code of new school language I think there is a problem in the language. I mean, the compiler should warn me somehow...or not?
It's not a criticism, but only a peaceful thought.

**Comment by johnlarfour** [comment]
@ianlancetaylor this is not completely true because with C I have full control about the memory so if this happens it is a bug in my code. But with Go I don't have this control.

**Comment by nussjustin** [comment]
> You can do the same in any systems programming language. It's just as easy in C or C++ as it is in Go.

Most "main stream" languages will easily let you do this. Just try to write similar code in Java, C#, Python, Ruby, etc. They will all allocate until they run out of memory or other OS resources (file descriptors, etc. which most GC's don't even care about).

> this is not completely true because with C I have full control about the memory so if this happens it is a bug in my code.

The same holds for most other main stream languages, not only for RAM but also for other OS resources.

I would even argue that this is both less of a problem in Go since it gives you much better control over allocations and allows you to easily manage your memory yourself if you want. 

> I mean, the compiler should warn me somehow...or not?

I don't know of a single compiler that does this.

Go's compiler does not even have/use warnings, so it would need to be either an error or part of a different command (e.g. `go vet`)

Also defining some static thresholds that work for everyone is basically impossible. For some applications creating 100 goroutines each doing e.g. an HTTP request can already be considered too much, but for others having a million goroutines doing HTTP requests at the same time can be ok. For some applications a heap size of 5GB is a "bug", others are expected to always use 500GB.
