### ISSUE TITLE
errors: no obvious way to map error to errno values

### ISSUE THREAD

**Issue by jech** [golang/go#29054]
go version go1.11.2 linux/amd64

I'm writing some Go code that is called by C code, and I find there's no obvious way to map an error value to a Unix errno value.  For example, at one point I write:
```
        n, err := conn.WriteToUDP(data, &addr)
	if err != nil {
		e := unix.EIO
		if os.IsTimeout(err) {
			e = unix.EAGAIN
		}
                C.set_errno(e)
                return -1
       }
```
While that keeps the code working, it obviously loses a lot of the error granularity.  Given that the errno value must be available somewhere under the hood, it's infuriating that it's not exported.

(I'd envision for example an interface with a single method `ToOsInteger` and that is implemented for those errors for which it makes sense to map to a Unix errno.)

**Comment by jech** [comment]
Thanks a lot for your code, that seems to do the trick.  Still, would you agree that this is not something you'd expect the average Go programmer to discover on his own?  And that this should either be encapsulated in a standard library function, or at least documented?

**Comment by odeke-em** [comment]
>Still, would you agree that this is not something you'd expect the average Go programmer to discover on his own?

Fair point that it would require a little bit more digging than usual, which is why I mentioned this perhaps being a `docs discovery issue`.

Adding it to the standard library is something to consider carefully because how many people have encountered this issue? It is a cross-package utilitiy i.e. os, syscall, it involves error introspection. But also adding it in means that its signature has to be kept intact. for the lifetime of a GoX series which can be decades
I think that what we can do is, please distill this issue into an "Experience Report" https://github.com/golang/go/wiki/ExperienceReports which will help a lot with informing the design process as we proceed towards Go2.
The "Experience Report" could be a blogpost or Github Gist and then add it to that linked listing, share it with your friends, gather feedback, and the Go maintainers will take a look. Such feedback is highly valuable and will also help with errors redesign (/cc @mpvl)
Concurrently with the report, you can create a small library that does this translation and once we have a tangible reference that's used with various applications but also demonstrates demand, that makes it really easy for decisions into including into the standard library.

**Comment by jech** [comment]
> Adding it to the standard library is something to consider carefully

That makes perfect sense.  (Please take it literally -- I'm not sure whether I agree, but your argument definitely makes sense.)

(I'm not quite sure whether to close this issue — on the one hand, you've solved my immediate technical problem, for which thanks; on the other hand, I still think there's a documentation problem somewhere.)

**Comment by odeke-em** [comment]
>(I'm not quite sure whether to close this issue — on the one hand, you've solved my immediate technical problem, for which thanks; on the other hand, I still think there's a documentation problem somewhere.)

Given that this is an issue that isn't frequently reported and that we have solved it, let's close it. However, as I had suggested in https://github.com/golang/go/issues/29054#issuecomment-443468911 whenever you get some free time, please write an "Experience Report" and share it on the wiki, on golang-nuts, social media etc. In this issue I've also paged some interested parties and as we work towards Go2, the feedback will be considered towards the next design.

**Comment by networkimprov** [comment]
I don't see how a SysErr() or Errno() method fits in the scope of either Go 2 Error Values or Error Handling, as it's specific to errors stemming from syscalls.
https://go.googlesource.com/proposal/+/master/design/go2draft.md

It looks to me like a method of net.Error, os.PathError, and similar types, or a new interface type. And the solution above looks to me like it could be brittle.

I'd suggest leaving it open, with title "proposal: Go2: add SysErr interface type" and tag Go2. That's the common approach to gaps in the stdlib.

**Comment by ianlancetaylor** [comment]
I think this issue is reasonably addressed by `error.As` in the current error design draft (see https://go.googlesource.com/proposal/+/master/design/go2draft.md).

**Comment by tv42** [comment]
@networkimprov: Wanting a C `errno` means you want platform-specific details which means you're dealing with the syscall package, that sounds very reasonable. Consider lack of Errno in https://golang.org/pkg/syscall/?GOOS=plan9
