### ISSUE TITLE
x/tools/internal/lsp: handle nested composite literals

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29153]
Repro:
```go
return &protocol.SignatureHelp{
	Signatures: []protocol.Signatu<>
}
```

In this case (completing at the `<>`), we provide completions for the struct (`Signatures`) rather than the expected type (`protocol.SignatureInformation`).

**Comment by muirrn** [comment]
I'll work on this one if it is available.

**Comment by stamblerre** [comment]
It is. Thank you!

**Comment by muirrn** [comment]
@stamblerre I wanted to check in with you on this one. There are two issues at play:

1. I think there is a slight issue with the getting the right `path` at the start of `Completion` in source/completion.go. I think it should always do the `PathEnclosingInterval(pos - 1)` it currently does conditionally. This issue causes the position in your example to end up with a path leaf node of the parent composite literal "protocol.SignatureHelp{". That is why it offers completions for the other fields of SignatureHelp. This is easy to fix and gives you lexical completion instead of the complit completion (but note that lexical completion doesn't help in your example since it is in another package, and you don't get type aware completion).

2. The bigger issue is that completion of literal slice values like `_ = []fo<>` don't work because it is a syntax error. You end up with an `*ast.BadEpxr` which doesn't get you anywhere looking for smart completions. Things like `_ = []protocol.Signatu<>` will always only give lexical completions, and hence never the completion from the other package you want. I could only think of one idea to work around this and provide the correct completions:

1. Create a local copy of the File
1. Change the File contents to exclude the leading `[]` (so it can parse without BadExpr)
1. Re-fetch the File's ast/type handles
1. If the expected type is a slice type `[]T`, change it to just be `T`
1. Proceed as normal (throwing away local File copy)

I validated the approach (except for step 1), and it seems to work. I like the general idea of making a temporary/local modification to the source to work around certain in-the-middle-of-typing unparsable states. This same approach could probably also fix completions in unterminated string literals.

I am interested to hear if you already have code or ideas to work around this kind of issue. Thanks!

**Comment by stamblerre** [comment]
Thank you for the detailed analysis! I had expected this to be the case, which would put this issue in the same category as things like https://github.com/golang/go/issues/29313. I should probably create some sort of `BadExpr` issue label. 😄 

I agree with you that we will want to have some altered version of the file with the fix, though I think we could do better than deleting file contents. I wonder if we could fix up ASTs containing `*ast.BadExprs` before we type-check them.

**Comment by muirrn** [comment]
Yes, that sounds good. I was mucking with the AST first but saw it would be easier to just change all the contents since that reparses and type checks.

I assume we need to keep the original bad AST and bad types for formatting and diagnostics and the like, right? If so, the approach would be for complete (or some new File method) to perform surgery on a copy of the AST, type check the fixed AST (but don't update the view cache), proceed as normal?

I'd like to keep working on the BadExpr issue if that's okay. Sounds fun. Do you want me to separately push the small fix above to get lexical instead of complit completions in your example?
