### ISSUE TITLE
crypto/x509: CPU denial of service in chain validation

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29233]
Package `crypto/x509` parses and validates X.509-encoded keys and certificates. It's supposed to handle certificate chains provided by an attacker with reasonable resource use.

The `crypto/x509` package does not limit the amount of work performed for each chain verification, which might allow attackers to craft pathological inputs leading to a CPU denial of service. Go TLS servers accepting client certificates and TLS clients verifying certificates are affected.

Thanks to Netflix for discovering and reporting this issue.

This issue is CVE-2018-16875.

**Comment by FiloSottile** [comment]
Fixed in Go 1.11.3 by df523969435b8945d939c7e2a849b50910ef4c25.
Fixed in Go 1.10.6 by 0a4a37f1f0a36e55d8ae5c34210a79499f9f2a9d.

**Comment by abarisani** [comment]
I am experiencing failure in `tls.RequireAndVerifyClientCert` with otherwise previously valid combination of CA - Client Certificate.

The TLS server, compiled with go1.11.2 happily accepts the client certificate validated against the CA.

However the TLS server, compiled with go1.11.3, raises a `tls: failed to verify client's certificate: x509: certificate signed by unknown authority`.

Are there known incompatibilities caused by this patch when evaluating CAs for inclusion `incertPool.AppendCertsFromPEM` or verified with a `tls.Config` using  `ClientAuth:   tls.RequireAndVerifyClientCert` ?
