### ISSUE TITLE
cmd/go: remote command execution during "go get -u" [Go 1.11]

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29232]
This is a tracking issue for #29230, a security vulnerability fixed in Go 1.11.3.

**Comment by jadr2ddude** [comment]
# Looking through the code, I saw the following mistakes that could have caused this error:

Error 1 - `strings.Contains(path, "..")` creates false positives with `something/...`
https://github.com/golang/go/commit/8954addb3294a5e664a9833354bafa58f163fe8f#diff-5b11f198c631a3d489e1be171853ab7bR40

Error 2 - the `...` path would cause this to error too, since it is all `.`
https://github.com/golang/go/commit/8954addb3294a5e664a9833354bafa58f163fe8f#diff-5b11f198c631a3d489e1be171853ab7bR70

# Suggested Fix

Remove the check listed in error 1. In addition to causing false positives, it is rendered unnecessary by the line mentioned in error 2. Leave the line in error 2 unchanged, but add a check that skips this validation for the last element if it exactly matches `...`.
