### ISSUE TITLE
cmd/go: builds fail if neither $HOME nor $GOCACHE are set

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29267]
https://github.com/golang/go/issues/29243#issuecomment-447407065

> Are we committed to not letting users build code unless they set $HOME or $GOCACHE? I'd expect this to break quite a few Docker images, which probably didn't want to keep the cache around anyway. Also, I run some machines with a read-only $HOME, which I guess won't be able to build Go code anymore.
>
> It already broke tip.golang.org and stuff inside Google, too.

@bcmills in https://github.com/golang/go/issues/29243#issuecomment-447416545

> It's what we announced in the 1.11 release notes, and nobody complained about it then.
>
> We could perhaps put the cache in os.TempDir() if we can't find it some other place, though.

I'd argue that https://golang.org/doc/go1.11#gocache does not communicate that if you don't set $HOME, or if it's not writeable, builds will fail. To an outsider it seems to just say you can't force $GOCACHE off manually anymore.

I personally would expect go to still work, and simply not persist the cache.

Anyway, we are seeing breakage, so this should be an explicit decision. I think we should not break build environments as much as possible: modules should make go more flexible, not less.

**Comment by bcmills** [comment]
(CC @rsc)

**Comment by rsc** [comment]
Let's make sure we figure out how the "standard" Go docker images keep being useful to the many users they have. That may mean working with the people who maintain those images to get the base images to set GOCACHE=/tmp by default, so every user doesn't have to.

**Comment by FiloSottile** [comment]
The `golang` images actually set `$HOME`

```
$ docker run golang bash -c 'echo $HOME'
/root
```

but I don't think that solves the problem. I personally run most of my systems with read-only `$HOME`, and just like the Google internal CI as well as tip.golang.org broke because we don't set `$HOME`, surely others will. I guess we can wait and see how many people break in beta.

As for Docker, keeping the cache around in the image will probably be undesirable because minimal size images are considered important, so we will see some `go clean -cache` bolierplate emerge like `rm -vrf /var/cache/apk/*` did before they introduced `apk add --no-cache`. However, this sounds more like an argument to allow `GOCACHE=off` to be honest.

**Comment by FiloSottile** [comment]
It doesn't.

```
$ cat > Dockerfile
FROM alpine
RUN echo _o/ > /tmp/hi
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
4fe2ade4980c: Pull complete
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Downloaded newer image for alpine:latest
 ---> 196d12cf6ab1
Step 2/2 : RUN echo _o/ > /tmp/hi
 ---> Running in 9ce0e929ea2e
Removing intermediate container 9ce0e929ea2e
 ---> f68c5e00ee65
Successfully built f68c5e00ee65
$ docker run --rm f68c5e00ee65 cat /tmp/hi
_o/
```

**Comment by FiloSottile** [comment]
The `golang` images already have a writeable `$HOME` AFAICT.

The part I wanted a decision on is whether we are ok breaking build environments that have a write-only or unset `$HOME`, of which we already have some examples (tip.golang.org, Google's internal stuff, and my personal infrastructure).

(Sorry for derailing with the discussion about Docker image sizes, multi-stage Dockerfiles are a reasonable mitigation.)

**Comment by FiloSottile** [comment]
#29341 is unrelated but mentions another environment with `$HOME` unset.

**Comment by rsc** [comment]
Since it's not a release blocker, milestoning forward.

**Comment by bcmills** [comment]
Is there anything left to be done on this issue?

Given the relative lack of discussion since the betas have been cut, perhaps the improved diagnostics are enough to resolve the usability concerns.

**Comment by rsc** [comment]
SGTM.

**Comment by kalyanac** [comment]
One instance where this is a problem is the startup scripts for GCE VMs. Go Profiler agent [integration test](https://github.com/googleapis/google-cloud-go/blob/master/profiler/integration_test.go) uses a startup template script to build and run go code. When the startup script run, $HOME is not set. 

To avoid breaking existing code, setting GOCACHE to /tmp/.cache would be preferable.

**Comment by lyda** [comment]
Ugh. This also caused breakage in my personal environment. And looking through this issue I see a number of people warned it would.

Really disappointing.

**Comment by bradfitz** [comment]
@lyda, did it help you find that your personal environment was missing $HOME? How did lacking HOME not mess up dozens of other tools?

**Comment by lyda** [comment]
It was an automated deployment system I use for stuff at home. It's worked fine for years w/o HOME being set for lots of tools.

Lots of processes on a normal unix system do not have HOME set. cron jobs, things started by init, cgi scripts, git post-receive hooks, things started by inetd and, in this case, scripts run by [webhook](https://github.com/adnanh/webhook).

Above there was talk about fixing the golang docker container for CI/CD systems - but not everyone uses docker for CI/CD. There are unix platforms that do not support docker - for instance for work I do CI/CD on FreeBSD (I call it my retrocomputing gig - but hey, it works so why not?).

I just don't understand what I've read in this issue. Caches like this are normally nice to have things. And if this cache is needed, the unix world has had pretty standard ways of finding a temp dir for ages. You can add the fancy new XDG var, but TMPDIR and /tmp have been the normal way to get temp space. And with go 1.11 you all had brought in modules and removed the need for any environment variables.

But now we're back to a var being needed. A different one. Which is fine, I'll update my system and build scripts for home and work for the next week or so as they break. It just seems so... unnecessary.

It's honestly just odd. You'd removed this need for environment vars which was great because it was always a minor annoyance with Go. Victory! But then promptly went and required one again. Is there some sort of environment var quota for the Go compiler team? Like, if it ever gets down to zero something bad has to happen - Go 3 gets designed by a committee of Haskell and FORTRAN developers.
