### ISSUE TITLE
x/build: disable openbsd-amd64-64 and freebsd-amd64-12_0 on release-branch.go1.10

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29265]
Those builders are too new for Go 1.10, and they always fail the TryBots.

> Failed on openbsd-amd64-64: https://storage.googleapis.com/go-build-log/74878a24/openbsd-amd64-64_3fe0d458.log
> Failed on freebsd-amd64-12_0: https://storage.googleapis.com/go-build-log/74878a24/freebsd-amd64-12_0_5ecb9125.log

Source: https://go-review.googlesource.com/c/go/+/151343.

/cc @bradfitz @dmitshur

**Comment by bradfitz** [comment]
IIRC we have all the hooks now in dashboard/builders.go to do this easily.

I'll let @dmitshur handle this one.

**Comment by dmitshur** [comment]
I've deployed the fix ([CL 155463](https://golang.org/cl/155463) and confirmed that it works.

For example, see:

https://go-review.googlesource.com/c/go/+/159478/3#message-e8ce116ba7c9213e734f972e5ab033c53ab31769

That's a CL into the main go repo on the `release-branch.go1.10` branch, before the fix was deployed. 2 of the trybots failed: openbsd-amd64-64 and freebsd-amd64-12_0. Then, see:

https://go-review.googlesource.com/c/go/+/159478/3#message-621e6e4793e669e737d7356e2d6e6ff2c515da81

It's the result of re-running trybots on the same CL after deploying the fix. The 2 builders that require Go 1.11+ were excluded and trybots passed.

For other trybot runs where the Go version is 1.11+, those 2 builders are included.
