### ISSUE TITLE
cmd/compile: depth limit reached in type formatting routine

### ISSUE THREAD

**Issue by griesemer** [golang/go#29312]
Place holder issue for cases of overly deep types or (invalid) recursive types. See #29264 for an example.

**Comment by griesemer** [comment]
A recursive type where we currently fail:
```Go
type T interface {
	M(interface {
		T
	})
}
```
(from #16369).

**Comment by ianlancetaylor** [comment]
#32547 is a test case that fails due to the recursion limit, although the test itself does not use recursion.  It just uses a very very very deep pointer type.

**Comment by empijei** [comment]
An update on this bug:

At Google CTF finals this year a team was able to exploit this behavior and obtain remote code execution without importing any package except for "fmt".

The issue is that some code that was supposedly safe had a memory corruption due to a very deep type.

[Here](https://github.com/A-0-E/writeups/tree/master/googlectf-2019-finals/gomium) you can find a write up of the challenge, and [here](https://github.com/A-0-E/writeups/blob/master/googlectf-2019-finals/gomium/exp.go) is the exploit.

When there is a very deep type (253 in this case) the compiler generates an incorrect program. In my opinion this should not be the case and it should instead reject the invalid code (after all, the generated program will not work anyways).

/cc @mvdan @FiloSottile

**Comment by ianlancetaylor** [comment]
Marking as a release blocker for 1.14.

I don't see a reason to block the beta release for this.

**Comment by josharian** [comment]
Is there a threat model in which this attack is possible but https://research.swtch.com/gorace isn’t?

**Comment by randall77** [comment]
This exploit doesn't require multiple threads, unlike Russ' example.
We've tried to keep Go strongly type safe in the absence of unsafe and data races. This exploit breaks that idea.

**Comment by empijei** [comment]
This bug has been there for quite a while and the threat model requires **a lot** of control on the attacker side (almost arbitrary code).

I don't know if this is exploitable by creating the type via reflection but even if it is it would still require the attacker to call arbitrary primitives, which is unlikely.

It would be nice to have this fixed for the next release but I would not say this is a blocker for 1.14.

**Comment by FiloSottile** [comment]
This is a classic type confusion and definitely a mis-compilation (as well as an amazing CTF trick). It also introduces unsafety which can't be detected by looking for usages of `unsafe` or by the race detector. It sounds like something we should fix.

However, I believe we (rightfully) gave up on this threat model with the removal of "safe" mode in Go 1.12 (5185744962d402df083d118036f9bef8c2e2d3b6), so I agree that this is not a security issue.

**Comment by randall77** [comment]
The security hole aspects of this issue have been fixed. Removing release blocker and punting to 1.15.
