### ISSUE TITLE
doc: Go 1.12 runtimes notes contains contradiction about RSS and memory usage

### ISSUE THREAD

**Issue by DmitriyMV** [golang/go#29337]
Quoting:

> The Go runtime now releases memory back to the operating system more aggressively, particularly in response to large allocations that can't reuse existing heap space.
> 
> On Linux, the Go runtime now releases memory back to the operating system only when the OS is under memory pressure. This is more efficient, but means a process's RSS (resident set size) won't decrease unless the OS is running out of memory.

IMHO - the second paragraph contradicts the first. I think it would be good to clarify the second part a bit more, or reword entire note entirely. Right now it worries people.

**Comment by ALTree** [comment]
cc @aclements

**Comment by aclements** [comment]
Hmm. I see what you're saying. The tricky part is that there are actually two levels of "released to the OS" on Linux: there's "release this if you need it" and there's "release this right now". Go now uses "release this if you need it" on Linux instead of "release this right now" *and* is much more aggressive about marking memory as "release this if you need it." Maybe the second bullet needs to be reworded so that it's not about when the Go runtime itself releases memory...

/cc @mknyszek
