### ISSUE TITLE
runtime/race: freebsd race builder is broken

### ISSUE THREAD

**Issue by bradfitz** [golang/go#29340]
https://go-review.googlesource.com/c/go/+/153897 broke the FreeBSD race builder.

**Comment by mknyszek** [comment]
I see the issue. It's unfortunate because this is a Darwin-specific fix, and I had to add it to mem_bsd.go since the two files were merged together since the last release. That's why this leaks into FreeBSD.

Also, the failure is kind of funny; MAP_FIXED does too good of a job using the arena hints it seems, but I'll investigate and try to figure out a fix ASAP.

**Comment by mknyszek** [comment]
Ohhh, no I see. MAP_FIXED is causing us to map over already mapped space without error. Ugh.

**Comment by mknyszek** [comment]
I put up a change which makes it so that MAP_FIXED is only used if `GOOS == "darwin"` (so FreeBSD gets fixed) and then disables the test on Darwin in race mode because the test is also likely broken there, it's just that the builder is failing earlier and masking it.
