### ISSUE TITLE
misc/wasm: importing fmt adds ~500kb to the binary

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#29478]
### What version of Go are you using (`go version`)?

```sh
$ go version
go version devel +bfaf11c158 2018-12-26 05:21:41 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GOOS=js GOARCH=wasm go env                                              
GOARCH="wasm"
GOBIN="/home/oneofone/code/go/bin"
GOCACHE="/tmp/.gocache"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="js"
GOPATH="/home/oneofone/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/src/go"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build733631578=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

This isn't a bug per-se, but I think maybe something can be done to improve that.

Feel free to close it or keep it as a reminder for later.

**Comment by neelance** [comment]
I fully agree that the binary sizes are large measured by current web standards. So far, binary size hasn't been one of the main concerns of Go due to the main use cases it currently has. With WebAssembly this changes and we will see how much influence this will have on Go in the future.

#6853 already covers this issue and I don't see anything immediate we can do specifically for WebAssembly, so let's close this as a duplicate.

Also please always look at the size difference with gzip applied, since this is the only size that really matters. With gzip, a quick experiment shows for me a difference of 1.1MB non-gzipped, but only 230KB gzipped.

**Comment by techtonik** [comment]
#6853 is CFC. 1.1MB is still big. How much is it in memory when running on web page context?

**Comment by neelance** [comment]
For memory related issues see #27462
