### ISSUE TITLE
x/build/cmd/coordinator: subrepo trybots testing against security branch

### ISSUE THREAD

**Issue by bradfitz** [golang/go#29510]
Seen on a trybot run:

https://go-review.googlesource.com/c/tools/+/156078

> Build is still in progress...
> This change failed on linux-amd64 (Go 1.10-security.x):
> See https://storage.googleapis.com/go-build-log/25ca8f49/linux-amd64_578e3eba.log

I suspect there's a bug in the fixes for #17626, or old assumptions that no longer apply now that we have a security branch.

Maybe just filter out the security branch before we find the last N=2 releases?

Or delete the security branch altogether?

**Comment by dmitshur** [comment]
> Or delete the security branch altogether?

We did delete them in the canonical repository (i.e., https://go.googlesource.com/go/+refs). However, it continues to show up in the GitHub mirror repository (even after a manual deletion) due to a bug in `gitmirror`, see https://github.com/golang/go/issues/23099#issuecomment-450975968.

I suspect we'll want to fix this with a quick workaround first, because the underlying issues in gitmirror (and/or in maintner) are going take longer to fix (and can be done independently afterwards).

**Comment by dmitshur** [comment]
This is worse than I originally understood, because trybots are not just testing the security release-branches in addition to normal release-branches, but rather _only_ the security release-branches.

It's not too bad since the security release branches are pretty representative of Go 1.11 and Go 1.10, which is the goal of #17626, but we should still fix it so that the latest release-branches get tested. I'll start looking into this soon.
