### ISSUE TITLE
types should be inferred

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#29577]
I am on `go version go1.10.4 linux/amd64`

I would like to see more type inference in Go. For example:

![screenshot from 2019-01-04 23-43-57](https://user-images.githubusercontent.com/11139560/50721836-dfe6a500-107a-11e9-9d46-315fcec4f435.png)

The above compiles, but if I leave out the types, I get:

![screenshot from 2019-01-04 23-44-18](https://user-images.githubusercontent.com/11139560/50721840-f1c84800-107a-11e9-9143-dd7127132a17.png)

this kinda sux tbh :/

**Comment by mvdan** [comment]
Changes to the language should follow the proposal process: https://github.com/golang/proposal

In particular, there already are proposals about better type inference. For example, see https://github.com/golang/go/issues/12854. There's also https://github.com/golang/go/issues/21498 for making anonymous functions easier to write.

This issue is way too short and informal for a proposal, so I'm going to close it. Feel free to open another one with a well-formed idea.
