### ISSUE TITLE
x/website: inconsistent layout between src and pkg

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#29585]
This is perfect
https://golang.org/src/crypto/ecdsa/ecdsa.go
![image](https://user-images.githubusercontent.com/863731/50732614-d21a4800-117e-11e9-9861-b155f6fbb070.png)

Suggestion to make pkg layout more consistent with src by 
a) use the same title link structure ( Package pkg/crypto/ecdsa )
b) adding a link to source with the same layout ( Source: crypto/ecdsa ) or `<a ref>` the `import "crypto/ecdsa"` line to the source code

https://golang.org/pkg/crypto/ecdsa/
![image](https://user-images.githubusercontent.com/863731/50732619-eeb68000-117e-11e9-8335-9314fb8542b3.png)

**Comment by agnivade** [comment]
> a) use the same title link structure ( Package pkg/crypto/ecdsa )

The source viewer implements a breadcrumb structure where each link is clickable, signifying a directory hierarchy. But the package viewer just displays documentation about a package. And the name of the package is ecdsa. Showing pkg/crypto/ecdsa won't be accurate.

> b) adding a link to source with the same layout ( Source: crypto/ecdsa ) or `<a ref>` the `import "crypto/ecdsa"` line to the source code

I am neutral to this. The source links are already there in the Package files section under index. That gives you the list of source files in the package. Not sure if adding a separate link to the package directory adds much value, since one has to click a source file anyways. 

Overall, I don't see an "inconsistency" between the layouts. Both of them serve different purposes and there is no need to conflate them.

**Comment by gertcuykens** [comment]
Understand your point of view to keep package as clean as possible but still feel and believe many others, that a  header something like this is needed https://godoc.org/crypto/ecdsa If I would be the only one I don't believe godoc would implement this.

**Comment by dmitshur** [comment]
I think this falls under the area of navigation: how to conveniently move from viewing documentation for package a to package b, especially when they're related (e.g., `crypto/ecdsa` and `crypto`).

Having a header with clickable parent elements like at golang.org/src and on godoc.org is a reasonable way of doing this, and we may want to consider other approaches.

There will be some UI changes done to godoc as part of adding support for module-aware mode (#26827) and consolidating UI features between gddo and x/tools/cmd/godoc (e.g., #27714). Let's keep this issue open, we can consider it when that work is being done.

**Comment by seankhliao** [comment]
I don't think this is relevant anymore now that /pkg/ points to pkg.go.dev
