### ISSUE TITLE
access: Trybot Access and GitHub ("go-approvers") Access

### ISSUE THREAD

**Issue by viswesr** [golang/go#29624]
I would like to get

1. Gerrit **Trybot Access ("may-start-trybots")**  and
Ref: https://go-review.googlesource.com/#/admin/groups/1030,members
2. GitHub **Editors Access("go-approvers")**
Ref: https://github.com/orgs/golang/teams/go-approvers 

Gerrit Contributions: https://go-review.googlesource.com/q/owner:r.visweswara%2540gmail.com

Thanks.

**Comment by viswesr** [comment]
If you need any further information, let me know. I would like to use Trybot access for the CLs that I work on. I wish to contribute to Golang Issues - gardening as well. Thanks.

/cc @bradfitz @tklauser

**Comment by andybons** [comment]
Hi @viswesr. Thanks for your interest in contributing.

You can contribute to gardening issues without having the permissions above (golang.org/wiki/Gardening). Keep in mind that [gopherbot](https://golang.org/wiki/gopherbot) allows you to label issues without GitHub permissions. Since you've only been involved with 5 issues so far (https://github.com/golang/go/search?q=involves%3Aviswesr&unscoped_q=involves%3Aviswesr&type=Issues) and 8 changes, it seems premature to provide Trybot access and GitHub permissions at this time.

Let me know if you have any questions.
