### ISSUE TITLE
Why map[time.Time]string doesn't work sometimes?

### ISSUE THREAD

**Issue by smcduck** [golang/go#29683]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
darwin_amd64

<details><summary><code>go env</code> Output</summary><br><pre>

```
GOARCH="amd64"
GOBIN="/Users/***/git/bin"
GOCACHE="/Users/***/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/***/git/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/97/f4bg6tpx1***gn/T/go-build478022581=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</pre></details>

### What did you do?

```
package main
import (
	"fmt"
	"time"
)

type MyDate time.Time

func NewMyDate(year, month, day int, tz time.Location) (MyDate, error) {
	return MyDate(time.Date(year, time.Month(month), day, 0, 0, 0, 0, &tz)), nil
}

func (md MyDate)ToTime() time.Time {
	return time.Time(md)
}

func main()  {
	timeMap := make(map[time.Time]string)

	md1, _ := NewMyDate(2019, 1, 1, *time.UTC)
	md2, _ := NewMyDate(2019, 1, 1, *time.UTC)

	timeMap[md1.ToTime()] = "1"
	timeMap[md2.ToTime()] = "2"

	for k, v := range timeMap {
		fmt.Println(k, v)
	}
}
```

### What did you expect to see?

2019-01-01 00:00:00 +0000 UTC 2

### What did you see instead?

2019-01-01 00:00:00 +0000 UTC 2
2019-01-01 00:00:00 +0000 UTC 1

**Comment by smcduck** [comment]
I found what's going on.

**Comment by zegl** [comment]
@smcduck 

The issue is that `tz` in the row `return MyDate(time.Date(year, time.Month(month), day, 0, 0, 0, 0, &tz)), nil` does not refer to the same `time.Location` instance.

When the non-pointer instance of tz is passed to the NewMyDate function the value tz is _copied_.

If you instead rewrite MyNewDate to receive a pointer to a `time.Location`, the program will work as you expect it to. Here's a working Playground: https://play.golang.org/p/QDNlNNsidv5

In your code, you can see that md1 and md2 have different values by printing them: `fmt.Printf("%+v", md1)`.

It will print something like this:

```
{wall:0 ext:63681897600 loc:0x436100}
{wall:0 ext:63681897600 loc:0x436140}
```
