### ISSUE TITLE
Out of memory: wasm memory

### ISSUE THREAD

**Issue by xxyGoTop** [golang/go#29778]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go.11.2
</pre>

### What did you do?

I wrote an animation, the first time it works fine, but after refreshing the browser multiple times, the program throws an exception.

I tried https://bobcob7.github.io/wasm-rotating-cube/
This problem will also occur

this errors:
`RangeError: WebAssembly Instantiation: [Out of memory: wasm memory]`

**Comment by agnivade** [comment]
There are several issues here -
- From what I see in https://github.com/bobcob7/wasm-rotating-cube/blob/master/bundle.go#L87, there are several typed arrays which are never released.
- And I believe (I could be wrong) that if you just reload the tab without closing the tab, or doing a clean exit from the app, the app does not shut down cleanly. Which means that any held resources are not released. And from the code, I don't see the app allowing the user to exit from main(). https://github.com/bobcob7/wasm-rotating-cube/blob/master/bundle.go#L209. So nothing ever gets released until you close the tab.

/cc @neelance for further comments.

**Comment by aykevl** [comment]
Just discovered this. I think it's a bug in Chrome because I have the same issue with an alternative WebAssembly compiler (after many reloads) and I never had it with Firefox.

If you ask me, all resources should be freed after a page is reloaded. Apparently Chrome doesn't do that (but does after closing/reopening the tab).
