### ISSUE TITLE
cmd/compile: confusing error if composite literal field that is a method is specified

### ISSUE THREAD

**Issue by pwaller** [golang/go#29855]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip, go playground.
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

**Playground link**: https://play.golang.org/p/llL2iikbJmd

```go
package main

type T struct {
	GlobalName string
}
var t = T{Name: "foo"}

func (t T) Name() string {
	return t.GlobalName
}
```

(Note: the field is called `GlobalName` but the composite literal specifies the incorrect field `Name`, which is also a method).

### What did you expect to see?

An error message telling me that I'm trying to declare a composite literal field which doesn't exist (or is a method, not a struct field).

### What did you see instead?

```
prog.go:6:11: cannot use promoted field Name in struct literal of type T
```

This lead to some confusion - in my case because the name of the method (`Name`) was similar to the name of the field I was trying to declare (`GlobalName`). The issue occurred because a dependency I was using changed the `Name` field to `GlobalName` and introduced an accessor method called `(T).Name()`. So I was in a larger process of code repair.

The struct in question also had a number of embedded fields, so it took a moment before I found the root cause (that there was `Name` method defined far away).

See also https://github.com/golang/go/issues/23609 which improved error messages for embedding but perhaps made things more confusing in this case.

**Comment by beoran** [comment]
I agree that this would probably be more clear in this case: 

`prog.go:6:11: cannot use method Name in struct literal of type T`

**Comment by mdempsky** [comment]
@pwaller Thanks for the report, and sorry about the confusing error message.

Looks like

     p, _ := dotpath(l.Sym, t, nil, true)
     if p == nil {
         yyerror("unknown field '%v' in struct literal of type %v", l.Sym, t)

in typecheck.go:typecheckcomplit needs to be changed to used `dotpath`'s `save` parameter, and then we need to validate that the returned `*types.Field` is a field and not a method (i.e., `f.Type.Etype != TFUNC || f.Type.Recv() == nil` -- this should probably be abstracted into a method of `*types.Field` since it's non-intuitive and checked in a few places already).

Should be a relatively easy CL if anyone wants to volunteer to take it.
