### ISSUE TITLE
cmd/asm: bad error about ABI0

### ISSUE THREAD

**Issue by rsc** [golang/go#29852]
I tried to refer to `zero<>(SB)` as a memory operand without defining that symbol.
The error was:

	myfunc: relocation target zero not defined for ABI0 (but is defined for ABI0)

It should have been more like 'zero not defined' (period).

**Comment by aclements** [comment]
Interesting. This happens because the symbol is both static and named "zero". If you change the name to, say, "zeroxxx<>", you get the right error message. It seems that runtime.a contains a reference to (though not a definition of) a symbol named "zero" with ABI0, which causes zero to be entered in the symbol table with ABI0. The code that looks for alternative ABI symbols finds that symbol in the symbol table, but doesn't check that it's actually defined, which is where the "but is defined for ABI0" comes from. The "not defined for ABI0" is because the same code failed to turn the static symbol's version back into an ABI, and it happened to print the zero value for an ABI.

I'll send a fix shortly.
