### ISSUE TITLE
path: Join documentation is misleading regarding Cleaned

### ISSUE THREAD

**Issue by rillig** [golang/go#29875]
As of Go 1.11.4, the documentation of `path.Join` says:

> Join joins any number of path elements into a single path, adding a separating slash if necessary. The result is Cleaned; in particular, all empty strings are ignored.

Since `Cleaned` is written in uppercase, this suggests that `path.Clean` is called on the preliminary result of `Join`. For most cases this is true, but for the case of only empty filenames, it isn't. There, `path.Join("")` returns an empty string while `path.Clean("")` returns dot.

See https://play.golang.org/p/rjq7up_HplU.

**Comment by robpike** [comment]
A bug in the code, but maybe too hard to fix. Might need a documentation fix instead.

**Comment by Avni-Sharma** [comment]
Has this been updated yet?

**Comment by rillig** [comment]
> Has this been updated yet?

No, otherwise the Gerrit change request would be linked with this issue.

**Comment by agnivade** [comment]
There is actually a test case for path.Join which joins two empty strings and checks the output is an empty string. So not sure if it is a bug.

>  For most cases this is true, but for the case of only empty filenames, it isn't. There, path.Join("") returns an empty string while path.Clean("") returns dot.

That is because path.Clean is called only for non-empty strings. Which is what the documentation tries to say. But I agree this part `; in particular, all empty strings are ignored.` is not clear that Clean is being called _after_ ignoring all empty strings. I believe updating the docs is the safest recourse.

**Comment by agnivade** [comment]
@shivi28 - would you like to work on this ?

**Comment by erutherford** [comment]
@agnivade I can work on this unless @shivi28 already has or was planning to.

**Comment by agnivade** [comment]
There hasn't been a response, so feel free to take it up.

**Comment by pam4** [comment]
@erutherford, thanks for the fix, could you also fix `filepath.Join` documentation which has the same problem?

I noticed you removed *"all empty strings are ignored"*, is that ok?
Without that sentence how can I be sure that the result of `path.Join("", "foo")` is "foo" and not "/foo"?
