### ISSUE TITLE
x/build/internal/https: buggy synchronization in ListenAndServe

### ISSUE THREAD

**Issue by bcmills** [golang/go#29941]
This was going to be a drive-by comment on https://golang.org/cl/159698, but it's a separate (existing) bug and can be handled separately.

In this code:
https://github.com/golang/build/blob/ae7c9cf771eea29f108a62746cea3928b5759a2d/internal/https/https.go#L51-L64

If `opt.AutocertCacheBucket != ""`, then as far as I can tell we end up starting two goroutines (`http.Serve` and `serveAutocertTLS`) using the same handler. We only wait for one of them to return, so the other goroutine ends up leaking and its error is ignored.

I suspect that we should only be making one of those two calls in the first place, in which case the need for the goroutine at all is very unclear.

(CC @dmitshur @bradfitz @andybons)

**Comment by dmitshur** [comment]
> If `opt.AutocertCacheBucket != ""`, then as far as I can tell we end up starting two goroutines (`http.Serve` and `serveAutocertTLS`) using the same handler.

It does start two goroutines in that case, but they don't use the same handler. The HTTPS goroutine uses the `handler` parameter that was passed in, but the HTTP goroutine uses the `http.HandlerFunc(redirectToHTTPS)` handler.

> We only wait for one of them to return, so the other goroutine ends up leaking and its error is ignored.

This is true. However, in the most common use of `ListenAndServe`, which looks like `log.Fatalln(https.ListenAndServe(...))`, as soon as either of the two `http.Serve` and `serveAutocertTLS` returns an error, the entire program exits.

This also relies on the property that both `http.Serve` and serveAutocertTLS` only return non-nil errors. If they could return nil errors, then `https.ListenAndServe` could return a nil error from the first and not see a non-nil error from the second goroutine.

> I suspect that we should only be making one of those two calls in the first place, in which case the need for the goroutine at all is very unclear.

As I understand, at least one goroutine is required to start an HTTPS and HTTP server at once. Two goroutines are used simply for symmetry, so both can write their error into the same `errc` channel.

We could improve this, but the value is low. The `x/build/internal/https` package has only [one user](https://godoc.org/golang.org/x/build/internal/https?importers) at this time: `x/build/cmd/gerritbot`.

I can send a CL that fixes the goroutine leak and make the code more readable, but it'll still suffer from the property that when `ListenAndServe` returns due to one of the two servers (HTTPS or HTTP) returning an error, the other server isn't closed (again, because it's expected the command to consider an error from `ListenAndServe` to be fatal and exit). Fixing that is more invasive and probably not worth it at this time.

In general, I prefer this code to live inside the command that's starting up the HTTP(s) servers, then it's easier to customize it for the exact needs of the program and not leak resources.

**Comment by bcmills** [comment]
> as soon as either of the two `http.Serve` and `serveAutocertTLS` returns an error, the entire program exits.

I would really rather we minimize cross-package reasoning like that: it makes package invariants much more difficult to see and maintain. Even in `internal` packages, folks outside the Go project look to our code for examples, so our code should be exemplary.

**Comment by bcmills** [comment]
> Fixing that is more invasive and probably not worth it at this time.

Doesn't seem terribly invasive to me: see https://golang.org/cl/159701.
