### ISSUE TITLE
install: Windows MSI installer should not set GOROOT

### ISSUE THREAD

**Issue by AlexRouSg** [golang/go#30132]
The official Windows msi installer sets GOROOT, this is mostly harmless however causes a problem when dealing with multiple Go versions and may lead to unexpected behavior as the user may not be aware that GOROOT is set and is assuming will be inferred.

This has lead to reports like #30126 (mine)

**Comment by andybons** [comment]
@alexbrainman

**Comment by alexbrainman** [comment]
I don't use installer myself, so I would not know what is the right thing to do here. What do you suggest we do?

Alex

**Comment by mvdan** [comment]
The official install docs haven't recommended setting GOROOT since 1.10; the last remaining bit was https://go-review.googlesource.com/c/go/+/161758, which hopefully will be removed in the 1.12 release.

So unless there's a good reason to set GOROOT on Windows, I think the installer should follow the same rule.

**Comment by alexbrainman** [comment]
> I think the installer should follow the same rule.

I do not use Go installer, so I would not know. When I use / develop Go I use GOROOT in my scripts.

But, if it is safe to remove GOROOT from installer, we can do that.

Alex

**Comment by alexbrainman** [comment]
@andybons CL 163299 LGTM assuming what Daniel said. But I do not know how to test the CL. I, probably, need some tools to build installer. How do I test the CL?

Thank you.

Alex
