### ISSUE TITLE
x/website: tracking bug for tip.golang.org

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30232]
This is a tracking but to make sure the new x/website codebase also does tip.golang.org (which runs on GKE + uses autocert now)

/cc @cnoellekb @katiehockman @andybons @dmitshur

**Comment by bradfitz** [comment]
Looks like x/website still has the autocert code.

This bug might just be validating that the tip service still runs (it'll need slight tweaks) on the go-dashboard-dev staging project's GKE cluster.

**Comment by dmitshur** [comment]
As part of the changes of moving website into x/website, we have to make a decision about the future scope of tip.golang.org.

Previously, tip.golang.org served two purposes: it served the latest content from the main Go repository (e.g., https://tip.golang.org/doc/go1.12, the latest spec.html, latest stdlib package docs), and it was a test of whether Go at tip builds at all. If there was a toolchain breakage (e.g., early in cycle), the latest tip commit couldn't be deployed.

This is because to serve the website, the Go distribution had to be built together with the x/tools/cmd/godoc binary.

Now that the website is served from x/website/cmd/golangorg, it becomes possible to use a fixed stable version of Go (rather than the tip commit) to serve the latest content from the Go repository. That would make tip.golang.org more reliable and change its purpose to only serve the latest Go repo content, not to see if the latest tip commit builds successfully (we have https://build.golang.org/ for that).

Thoughts on this?

**Comment by bradfitz** [comment]
It was never a goal to report or indicate whether any particular thing built at all.

The main goal was just showing tip docs.

But a secondary goal was that changing cmd/godoc meant that cmd/godoc self-deployed with those code changes (or CSS, JS changes).

**Comment by dmitshur** [comment]
@cnoellekb Are you planning on working on this? If so, I'm happy to be a reviewer for the CLs. Otherwise I can take this and you can be a reviewer.
