### ISSUE TITLE
x/sys/cpu: should HWCap and HWCap2 be exported?

### ISSUE THREAD

**Issue by mundaym** [golang/go#30255]
Are `cpu.HWCap` and `cpu.HWCap2` supposed to be exported as part of the `cpu` API? I can't see any discussion about this in [CL 150718](https://golang.org/cl/150718) where they were added. Presumably they should be properly documented if they are supposed to be exposed.

They are only exposed on non-x86 Linux machines so I expect we could just un-export them if they aren't supposed to be exported...

**Comment by tklauser** [comment]
I suspect these were exported because the implementation was based on `internal/cpu` from the standard library where they need to be exported to be used in `runtime`.

IMO it would be fine to unexport them, also given the following comment:

```go
// These are initialized in cpu_$GOARCH.go
// and should not be changed after they are initialized.
```

https://github.com/golang/sys/blob/d0b11bdaac8adb652bff00e49bcacf992835621a/cpu/cpu_linux.go#L23-L24

/cc @ianlancetaylor @bradfitz

**Comment by ianlancetaylor** [comment]
I agree.

**Comment by martisch** [comment]
I also agree to make them unexported. They are an implementation detail that should not be exposed and it is hard to impossible to know from the outside if the value is valid/initialized.
