### ISSUE TITLE
Confusing hosting for Google Go libraries

### ISSUE THREAD

**Issue by mcandre** [golang/go#30358]
Google often serves important Go libraries like the /x/ libs, grpc, and Google Cloud API's, from repositories different than the import paths. And when you try to visit the repository path, you don't see a VCS system, but the Go docs. Finally, the implementation code is also hosted at GitHub mirrors, adding further to the confusion. These differences make it harder for newbies to make use of these important libraries, compared to just matching the import path with a valid VCS (would be nice if GitHub, but by no means necessary).

As a workaround, users can apply careful git-submodule paths, or manual vendoring, or Glide, or Go 1.11+ modules. But we shouldn't have to lean on complicated package resolvers whenever hosting directly from the same place as the import path is an option.

**Comment by dmitshur** [comment]
There are advantages and disadvantages to using vanity import paths like `golang.org/x/tools`. They are more future-proof: it allows the import paths not to change even when the underlying VCS changes. This has happened in the past, when the Go project moved from https://code.google.com/p/go to https://go.googlesource.com.

> Finally, the implementation code is also hosted at GitHub mirrors, adding further to the confusion.

Most of the implementation code is hosted at https://go.googlesource.com. It is mirrored to GitHub, so that's merely a copy for code browsing convenience.

Changing import paths now is not something that can be done easily.

> These differences make it harder for newbies to make use of these important libraries, compared to just matching the import path with a valid VCS

This is one of the disadvantages, that people who are new to Go have to read and become familiar with vanity import paths. They are documented at https://golang.org/cmd/go/#hdr-Remote_import_paths. If you have suggestions for how we can improve documentation to make this better, that'd be helpful.

If you'd like to discuss this further, there is a list of forums at https://golang.org/wiki/Questions that would be a better fit for this, since the Go project uses the issue tracker primarily for tracking bugs.
