### ISSUE TITLE
cmd/go: handle program or library assets

### ISSUE THREAD

**Issue by gopherbot** [golang/go#3035]
by **untheoretic**:

<pre>Please find a reasonable way to transport things that can't be (principally) embedded in
the source code to some place where
they could be found.

An (sad) example would be a go-gtk based program that must have
a several non-go files for the gtk runtime.</pre>

**Comment by gdamore** [comment]
This would be *really* useful.  I have a JSON file that contains a database of terminals -- this file could be compiled into the Go program, but its really extension info, and adding it bloats the text of the program by some 2MB at run time.  Since only about 0.1% of users need it, its better to leave it in JSON.

Ideally, go install could be made to install these resource files (perhaps by having a special file list what they are) in a standard directory based on the location of the binary, and then a little API glue to support picking the file up by the package name  & binary location?

Absent this, I'm inclined to use $HOME/.<packagename> and hope for the best.

**Comment by agnivade** [comment]
Just wanted to bump on this old issue.

For general stuff, the plugin model released in 1.8 should be sufficient for this. You can expose assets as a function or a variable. 

In the golang-nuts thread [above](https://github.com/golang/go/issues/3035#issuecomment-66063134), folks mostly wanted to embed static assets in their binaries, which is usually done with go generate and a tool to generate the files, like [statik](https://github.com/rakyll/statik).

@rsc @bradfitz - Are we looking to do anything more on this ?

**Comment by bradfitz** [comment]
Plugins are not the answer here. (Plugins are hard to use and not very portable)

This bug is about adding some conventions to the $GOPATH file layout, respected by the cmd/go tool, to automatically take files off the filesystem and place their contents (and perhaps their metadata like modtime) into the output, perhaps as a compressed ELF section or some equally efficient depending on the platform.

As a strawman, you could imagine a `//go:embed` directive that works similarly to `//go:generate` that `cmd/go` would respect to do the efficient thing. (`go:generate` doesn't work because we don't want to bloat git repositories by checking in base64 or hex-escaped copies of assets for every image/etc)

**Comment by agnivade** [comment]
Makes sense. Thanks !

**Comment by ngrilly** [comment]
Rust has an include_str! macro which works like this:

```
fn main() {
    let my_str = include_str!("spanish.in");
    assert_eq!(my_str, "adiós\n");
    print!("{}", my_str);
}
```

If the file `spanish.in` contains "adiós\n" then the program prints "adiós".

I haven't look at the implementation, but something similar in Go would be useful for example for templates and SQL queries.

**Comment by rsc** [comment]
Closing as a duplicate of #35950 which now has an active discussion.
