### ISSUE TITLE
go : problem for case : same type name and variable name

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#30466]
### What version of Go are you using (`go version`)?

<pre>
playground
</pre>

### Does this issue reproduce with the latest release?

Not checked.

### What operating system and processor architecture are you using (`go env`)?

No need.

### What did you do?

Run code:
```golang
package main

import (
	"fmt"
	"unsafe"
)

type wb struct {
	i int
}

func wb_test(wb []wb) int {
	return wb[0].i
}

func main() {
	var wb wb
	wb.i = 42
	fmt.Println("wb = ", wb)
	fmt.Println("wb = ", wb_test((*[100000000]wb)(unsafe.Pointer(&wb))[:]))
	//                                     ====== problem here
}
```
see [play](https://play.golang.org/p/8iwKTt3VNkJ)

error: `prog.go:20:33: wb is not a type`

If we change type from `wb` to `wb2` (for example), then all is ok.
see [play](https://play.golang.org/p/HAz6fPGblPI).

### What did you expect to see?

```
wb =  {42}
wb =  42
```

### What did you see instead?

```
prog.go:20:33: wb is not a type
```

**Comment by beoran** [comment]
The behaviour you see is as per the Go specification and correct.
Could you give your variable a different name for an easy fix?

**Comment by bcmills** [comment]
This is the behavior required by the language spec.

Per https://tip.golang.org/ref/spec#Uniqueness_of_identifiers:
> Two identifiers are different if they are spelled differently, or if they appear in different packages and are not exported. Otherwise, they are the same.

Per https://tip.golang.org/ref/spec#Declarations_and_scope:
> The scope of a constant or variable identifier declared inside a function begins at the end of the ConstSpec or VarSpec (ShortVarDecl for short variable declarations) and ends at the end of the innermost containing block.

If you believe that this issue is significant enough to warrant a change to the language itself (a [high bar](https://github.com/golang/proposal#language-changes)), please file a [proposal](https://golang.org/s/proposal), including supporting evidence for the severity of the problem.
