### ISSUE TITLE
x/mobile: get Android builders passing on x/mobile

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30482]
We now have x/mobile running on Android emulators on GCE and the first results are in:

https://build.golang.org/log/63ae018cd1092f5750d53441636171d48aeb8836

Looks like there's some cleanup to do, but not terrible.

We don't yet have those being used for mobile trybots, but we should.

**Comment by eliasnaur** [comment]
I will fix the test failures, but their root cause is trickier: the android builders run with GOOS=android which means that the tests run on the device. So we don't get to run the interesting tests (host builds an Android apk, pushes it to the device and runs it).

So the builder should (also?) somehow run with GOOS=$GOHOSTOS for the x/mobile repository. What do you think?

**Comment by bradfitz** [comment]
I guess we could special case that. I'd reuse the existing buildlets & just run "go test" twice with different env. The host tools should already be compiled from the make.bash. Can you verify that works in a local docker container? That is: a GOOS=android make.bash followed by an x/mobile GOOS=linux go test?

**Comment by eliasnaur** [comment]
> I guess we could special case that. I'd reuse the existing buildlets & just run "go test" twice with different env. The host tools should already be compiled from the make.bash. Can you verify that works in a local docker container? That is: a GOOS=android make.bash followed by an x/mobile GOOS=linux go test?

Works for me with a variant of the Dockerfile from https://go-review.googlesource.com/c/build/+/164658.
