### ISSUE TITLE
cmd/doc: odd formatting when last method lacks documentation

### ISSUE THREAD

**Issue by dsnet** [golang/go#30492]
Using `go1.12`

```
$ go doc -all io | grep -C 8 "LimitedReader) Read"
type LimitedReader struct {
	R Reader // underlying reader
	N int64  // max bytes remaining
}
    A LimitedReader reads from R but limits the amount of data returned to just
    N bytes. Each call to Read updates N to reflect the new amount remaining.
    Read returns EOF when N <= 0 or when the underlying R returns EOF.

func (l *LimitedReader) Read(p []byte) (n int, err error)
type PipeReader struct {
	// Has unexported fields.
}
    A PipeReader is the read half of a pipe.

func (r *PipeReader) Close() error
    Close closes the reader; subsequent writes to the write half of the pipe
    will return the error ErrClosedPipe.
```

The `LimitedReader.Read` method has no documentation, so does not print an empty line below it. This makes the output odd as it visually looks like  `LimitedReader.Read` is more related to `PipeReader` than it does with `LimitedReader`.

What I expected to see:
```diff
 func (l *LimitedReader) Read(p []byte) (n int, err error)
+
 type PipeReader struct {
 	// Has unexported fields.
 }
```

**Comment by agnivade** [comment]
Interesting. On a different note, the `Read` method should be documented :)

/cc @robpike

**Comment by agnivade** [comment]
Found it. I have 2 possible fixes for it.

One is unconditionally change 1 to 2 [here](https://github.com/golang/go/blob/master/src/cmd/doc/pkg.go#L227) in `func (pkg *Package) emit`. 

```go
} else {
	pkg.newlines(1)
}
```
Interestingly this was done to fix https://github.com/golang/go/issues/12756 filed by @dsnet himself, which was also about the `func (l *LimitedReader) Read` method.

There are side-effects to this approach. Since we are always printing a gap after a method, so now functions inside interfaces without a comment do not have a gap.

Before -- 
```
$gotip run .  io.read
func (l *LimitedReader) Read(p []byte) (n int, err error)
func (r *PipeReader) Read(data []byte) (n int, err error)
    Read implements the standard Read interface: it reads data from the pipe,
    blocking until a writer arrives or the write end is closed. If the write end
    is closed with an error, that error is returned as err; otherwise err is
    EOF.

func Read(p []byte) (n int, err error)
func (s *SectionReader) Read(p []byte) (n int, err error)
```

After--
```
$gotip run .  io.read
func (l *LimitedReader) Read(p []byte) (n int, err error)

func (r *PipeReader) Read(data []byte) (n int, err error)
    Read implements the standard Read interface: it reads data from the pipe,
    blocking until a writer arrives or the write end is closed. If the write end
    is closed with an error, that error is returned as err; otherwise err is
    EOF.

func Read(p []byte) (n int, err error)
func (s *SectionReader) Read(p []byte) (n int, err error)

```

To make it consistent, we would need to add a gap after functions too.

Another alternative is cleaner, but conditional. We check if a `fun.Doc` is empty or not in `func (pkg *Package) typeDoc` and accordingly add a gap. This is clinical and does not affect anything else.

@robpike for decision.

**Comment by robpike** [comment]
I'd go for checking fun.Doc but it doesn't really matter much. Either solution is fine.
