### ISSUE TITLE
cmd/go: go mod edit -replace does not accept a module path without a dot

### ISSUE THREAD

**Issue by neclepsio** [golang/go#30513]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPROXY=
set GORACE=
set GOTMPDIR=
</pre></details>

### What did you do?

<pre>
go mod edit -replace=foo=bar
</pre>

### What did you expect to see?

Adding a replace into go.mod, since if it is added manually there is no problem.

### What did you see instead?

<pre>
go mod: -replace=foo=bar: invalid old path: malformed module path "foo": missing dot in first path element
</pre>

**Comment by bcmills** [comment]
This is somewhat related to #28439, in that we're over-validating inputs to `mod edit`.

**Comment by iWdGo** [comment]
This issue and partly the related ones are caused by [`CheckPath`](https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/cmd/go/internal/module/module.go#L123) which was originally a copy of the path strategy of `go get` as this [comment](https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/cmd/go/internal/get/path.go#L14) mentions.

`go mod edit` aim is to edit `go.mod` and not to check existence of modules. Since the Windows checks are not included between others, it seems appropriate to remove the [requirement](https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/cmd/go/internal/module/module.go#L134) of a leading `.` in the path name.

Further, this check is redundant with [IsDirectoryPath](https://github.com/golang/go/blob/06e34e58150a5cb77afdd3807a93f270a3068456/src/cmd/go/internal/modfile/rule.go#L366) which draws the line between paths and module paths.
