### ISSUE TITLE
x/tools/cmd/gopls: define fields for "initializationOptions"

### ISSUE THREAD

**Issue by stamblerre** [golang/go#30578]
This initialize request for LSP allows for arbitrary initialization options to be provided to the server from the editor (https://microsoft.github.io/language-server-protocol/specification#initialize). We should determine what these options should look like, so that we can provide a clear spec to editors. 

This issue was originally raised by @mattn in [golang.org/cl/164779](http://golang.org/cl/164779), and the suggestion was to offer an option to disable diagnostics.

**Comment by mattn** [comment]
At least, I want to add `diagnostics` to off the feature since gopls often crash.

2019/03/08 14:07:12:["<---(stderr)",2,"go-lang",["panic: runtime error: invalidmemory address or nil pointer dereference","[signal 0xc0000005 code=0x0 addr=0x68 pc=0x714014]","","goroutine 20 [running]:","golang.org/x/tools/internal/lsp/source.Diagnostics(0x8dd560, 0xc00005a080, 0x8dd6e0, 0xc000054aa0, 0xc0001a3400, 0x44, 0x117, 0x117, 0xc0000c1f30)","\tC:/Users/mattn/go/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:64 +0xd4","golang.org/x/tools/internal/lsp.(*server).cacheAndDiagnose.func1(0x8dd560, 0xc00005a080, 0xc00003ad40, 0xc0001a3400, 0x44)","\tC:/Users/mattn/go/src/golang.org/x/tools/internal/lsp/diagnostics.go:24 +0x88","created by golang.org/x/tools/internal/lsp.(*server).cacheAndDiagnose","\tC:/Users/mattn/go/src/golang.org/x/tools/internal/lsp/diagnostics.go:23 +0x143",""]]

**Comment by stamblerre** [comment]
That's what I figured, but our goal is to make gopls more reliable, rather than turn off features. I have a few pending CLs that should help with that, but if you are still seeing consistent crashes I would prefer that we investigate them rather than just turn off a key feature.
