### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by grjiq** [golang/go#30626]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
redhat 
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build074244024=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I am trying to use opencv in go, my code doesn't work.

    dst := CreateImage(width, height, 8,interpolation)
    C.cvSet(unsafe.Pointer(dst), (C.CvScalar)(ScalarAll(255.0)), nil)
    points := make([]C.CvPoint, 4)

    points[0] =  C.CvPoint{0,0}
    points[1] =  C.CvPoint{110,110}
    points[2] =  C.CvPoint{0,110}
    points[3] =  C.CvPoint{110,0}
    pts := &points[0]
    cnt := C.int(1)
    C.cvFillPoly(unsafe.Pointer(dst), &pts, &cnt, 1, (C.CvScalar)(ScalarAll(255.0)), 8,0)
////////
    func CreateImage(w, h, depth, channels int) *IplImage {
        size := C.cvSize(C.int(w), C.int(h))
        img := C.cvCreateImage(size, C.int(depth), C.int(channels))
        return (*IplImage)(img)
    }

### What did you expect to see?
I expect "cvFillPoly" function can work correctly.

### What did you see instead?
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:

**Comment by mvdan** [comment]
Please fill in the rest of the issue template.

**Comment by pwaller** [comment]
You need to make sure you understand the cgo documentation in order to make this work properly. It has a section dedicated to this: https://golang.org/cmd/cgo/#hdr-Passing_pointers

If I search online for the error message in the title I can find examples of other people encountering this sort of issue, it is likely you will find help elsewhere.

It seems likely that the go-pointer-to-go-pointer lives inside your `dst` variable.

Failing that, if there is still a problem, please provide a complete reproducer, otherwise it is very difficult for anyone to help.
