### ISSUE TITLE
Link.exe detected as trojan

### ISSUE THREAD

**Issue by razapoonja** [golang/go#30644]
Hi,

I am using go-lang latest version and link.exe is being removed by windows defender because it's treated as trojan without link.exe go does not work.

<pre>
go version go1.12 windows/386
</pre>

![go](https://user-images.githubusercontent.com/31192540/53915099-15ab0880-4081-11e9-9028-fcc34ac810db.PNG)

**Comment by bradfitz** [comment]
We do our Windows release builds on single-use VMs not connected to the Internet. I'm approximately 100% sure this is a false positive, once again. (This comes up regularly, with regular anti-virus vendors)

Please file a bug with Microsoft. But it's possible you just have a virus on your machine, because nobody else has complained about this.

**Comment by ianlancetaylor** [comment]
https://golang.org/doc/faq#virus
