### ISSUE TITLE
cmd/compile: restore walkinrange optimization (by moving to SSA)

### ISSUE THREAD

**Issue by josharian** [golang/go#30645]
I’m on my phone, but I suspect that CL 165617 disabled the walkinrange optimization. This makes sense—order now rewrites away OANDAND and OOROR nodes, but those are what walkinrange operates on.

One symptom (I believe) is this:

https://go-review.googlesource.com/c/go/+/165617/1/test/checkbce.go#36

We have long wanted to move walkinrange to the SSA backend; this is a good motivation.

I’m marking this as a 1.13 release blocker, since IIRC walkinrange is a significant optimization for some hot code (usually parsing/formatting code looking for bytes in a range).

**Comment by josharian** [comment]
cc @randall77 @dr2chase

**Comment by josharian** [comment]
(This is also an indicator that this optimization needs an explicit asm test.)

**Comment by ALTree** [comment]
>I suspect that CL 165617 disabled the walkinrange optimization

It appears that's the case. Given

```
package p

func f(c uint64) bool {
	return 0x10 <= c && c < 0x20
}
```

on 178a2c4225 (a little before that CL):

```
RETURN l(4) tc(1)
RETURN-list
.   AS l(4) tc(1)
.   .   NAME-p.~r1 a(true) g(1) l(3) x(8) class(PPARAMOUT) bool
.   .   LT l(4) tc(1) bool
.   .   .   CONVNOP l(4) tc(1) uint64
.   .   .   .   SUB l(4) tc(1) uint64
.   .   .   .   .   NAME-p.c a(true) g(2) l(3) x(0) class(PPARAM) tc(1) used uint64
.   .   .   .   .   LITERAL-16 l(4) tc(1) uint64
.   .   .   LITERAL-16 l(4) tc(1) uint64
```

on a2ace8ec18 (after):

```
AS l(4) tc(1)
.   NAME-p..autotmp_2 a(true) l(4) x(0) class(PAUTO) esc(N) tc(1) assigned used bool
.   LE l(4) tc(1) bool
.   .   LITERAL-16 l(4) tc(1) uint64
.   .   NAME-p.c a(true) g(2) l(3) x(0) class(PPARAM) tc(1) used uint64

IF l(4)
.   NAME-p..autotmp_2 a(true) l(4) x(0) class(PAUTO) esc(N) tc(1) assigned used bool
IF-body
.   AS l(4) tc(1)
.   .   NAME-p..autotmp_2 a(true) l(4) x(0) class(PAUTO) esc(N) tc(1) assigned used bool
.   .   LT l(4) tc(1) bool
.   .   .   NAME-p.c a(true) g(2) l(3) x(0) class(PPARAM) tc(1) used uint64
.   .   .   LITERAL-32 l(4) tc(1) uint64

RETURN l(4) tc(1)
RETURN-list
.   AS l(4) tc(1)
.   .   NAME-p.~r1 a(true) g(1) l(3) x(8) class(PPARAMOUT) bool
.   .   NAME-p..autotmp_2 a(true) l(4) x(0) class(PAUTO) esc(N) tc(1) assigned used bool

VARKILL tc(1)
.   NAME-p..autotmp_2 a(true) l(4) x(0) class(PAUTO) esc(N) tc(1) assigned used bool
```

And the generated code contains two `CMPQ` instead of one.

**Comment by mundaym** [comment]
Not sure if this is exactly what you're after but I've been tinkering with some simple logical optimizations for control flow graphs (it's very rough code at the moment, I was just experimenting, but it does work):

https://go-review.googlesource.com/c/go/+/165998/

This can do optimizations such as this for disjunctions (and similar optimizations for conjunctions):

```
x == 1 || x == 2 -> unsigned(x - 1) <= 1
x == 4 || x == 6 -> (x | 2) == 6
x != 0 || y != 0 -> (x | y) != 0
```

It also has some optimizations to clean up some uses of `IsSliceInBounds` which maybe shouldn't have been generated in the first place:

```
x >= 0 && IsSliceInBounds(x, y) -> IsSliceInBounds(x, y)
```

I scheduled it after prove since I was a bit worried it might obscure some facts.

Unfortunately it is quite unpleasant adding new optimizations, especially if you want to add handle multiple bit widths. So I was thinking of extending the rewrite rules a bit so you could write something like this and have a new `mergeSuccessor` function handle all the gnarly stuff around assessing cost/mergability and value/phi updating:

```
// x < 0 || y < 0 -> (x|y) < 0
(If (Less(64|32|16|8) x (Const(64|32|16|8) [0])) (If (Less(64|32|16|8) y (Const(64|32|16|8) [0]) yes no) no)
        && mergeSuccessor(b, 0)
        -> (If (Less(64|32|16|8) (Or(64|32|16|8) x y) (Const(64|32|16|8) [0]) t f)
```

**Comment by josharian** [comment]
> Not sure if this is exactly what you're after

Yes, indeed, something like this.

> I scheduled it after prove since I was a bit worried it might obscure some facts.

Makes sense. The right place to document that is an entry in passOrder.

> Unfortunately it is quite unpleasant adding new optimizations

Indeed. That’s why I wrote this optimization during walk the first time around. :)

> I was thinking of extending the rewrite rules a bit

I’m AFK for a while (which is also why I haven’t replied to your comments on the unsafe.Unreachable issue), and it’s not quite obvious to me whether this would work in practice. It’d be lovely if it did. Perhaps we could also move the CMOV optimizations into such a form as well.

In a pinch we could also create a new kind of rewrite rule + rulegen + runner for this kind of optimization, one geared specifically to this kind of optimization.

**Comment by andybons** [comment]
@josharian would you still like to do this for 1.13?

**Comment by josharian** [comment]
I think this is important to do for 1.13, yes. It looked to me like maybe @mundaym was going to do it. I guess I'll take a look at it.

**Comment by josharian** [comment]
I'm going to punt this to 1.14 after all. I finally have a working version, based very loosely on @mundaym's work. But it is definitely non-trivial, and Keith would (very reasonably) prefer to wait for 1.14 for CL 178197, on which my CL depends. I'll see about cleaning up and mailing my CL sooner rather than later, so it can be ready when the tree re-opens or in case of need.

**Comment by randall77** [comment]
@mundaym @josharian Were either of you guys planning on submitting something here?

**Comment by mundaym** [comment]
I'd like to make block rewrite rules more powerful but I don't think I'll be able to get it done before the freeze because it is quite fiddly (happy to help if someone else wants to take a look). I'm happy to write a pass to do this specific optimization though if that would be useful.  Most of the tricky stuff I worked through in the CL I posted previously.

**Comment by randall77** [comment]
Just finishing your CL for this specific optimization would be good.

**Comment by josharian** [comment]
I will also dig up my work in progress and mail it, in case it is helpful. Probably this afternoon.

**Comment by randall77** [comment]
I'm going to punt this to 1.15. There is a CL, but it could use some more work, it's late, and it is just a performance improvement.
