### ISSUE TITLE
x/net/publicsuffix: check for label in EffectiveTLDPlusOne

### ISSUE THREAD

**Issue by dcarriger** [golang/go#30652]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

<pre>
baseDomain, err := publicsuffix.EffectiveTLDPlusOne(".com.au")
fmt.Println(baseDomain, err)
</pre>

### What did you see?

<pre>
.com.au <nil>
</pre>

### What did you expect to see?

If the label is empty, I should get an error message indicating such.

**Comment by bcmills** [comment]
CC @nigeltao @vdobler

**Comment by vdobler** [comment]
Currently the main function PublicSuffix requires its argument to be in a certain form:

- domain name
- lowercase
- punicoded
- not full qualified

(from memory, not authoritative) and will happily apply its algorithm even to inputs in a different form. This problem is addressed in the TODO in https://github.com/golang/net/blob/master/publicsuffix/list.go#L47

This issue here belongs a bit into this category because `PublicSuffix(".com.au") == "com.au", true` but ".com.au" is not a domain name at all. It is like `PublicSuffix("123.45.67.89")) == "89", false` yielding `EffectiveTLDPlusOne("123.45.67.89") == "67.89", nil` which is nonsensical too.

But the problem here might be worth a error message.
