### ISSUE TITLE
cmd/compile: write a test for #30167

### ISSUE THREAD

**Issue by mvdan** [golang/go#30664]
https://go-review.googlesource.com/c/go/+/163019 was sent and submitted without a test, because writing one wasn't possible with the current test suite. David has an idea to refactor the tests to support this kind of test case (see the CL comments); this issue is a reminder to write that test in the future.

/cc @pwaller @dr2chase

**Comment by xinxiao** [comment]
@mvdan May I carry on the task to work on this issue please?

**Comment by mvdan** [comment]
It's not assigned, so you're welcome to try. Though I think @dr2chase has specific plans on how to fix it, and they're non-trivial.

**Comment by dr2chase** [comment]
Ah, plans are changing slightly, and might become simpler.  I experimented with gdb-MI a little bit, and it appears that it might still be flaky (I am not 100% sure of this), plus in practice, people use Delve, not gdb, because gdb doesn't do a good job with goroutines.

And Delve isn't flaky.  I have to be sure that Delve is supported on our test boxes, and then we switch to that as the default.

The fix I imagine is to enhance debug_test.go to do one of the following:

- take a step limit (either read from the file or as part of test specification)
- take an "exit" annotation in the source file, telling to quit out of the process

And then use that to write the test.

**Comment by dr2chase** [comment]
It needs more than just a test; there's something buggy going on, but I won't get to it today.
Recommended attack (in CL above) is
```
cd src/cmd/compile/internal/ssa/testdata
GOSSAFUNC=test go build infloop.go
```
It loops like we should maybe notice that we are creating a one-instruction infinite loop, and throw a nop in there?  I'm not sure, it depends on debugger heuristics, but it is definitely tagged as a statement.

That would make the infinite loop take longer to finish....
