### ISSUE TITLE
Symmetric crypto algorithms to use io.Reader rather than []byte

### ISSUE THREAD

**Issue by stefanberger** [golang/go#30692]
The symmetric crypto algorithms take a byte array as input for encryption and decryption. Would it be possible to add versions that use an io.Reader or implement a New(), Write(), Final() sequence with the Write() being repeatable so that GB of data can be encrypted / decrypted and don't need to be loaded into memory?

**Comment by FiloSottile** [comment]
Unauthenticated cipher modes implement `cipher.Stream` which can be turned into a `io.Reader` by using `cipher.StreamReader`. We don't provide the same for CBC out of the box, but it's something you can build a simple wrapper for, as `cipher.BlockMode` is  stateful.

`cipher.AEAD`s intentionally don't provide a streaming interface because it  encourages processing data before authentication, which has been observed to be a frequent source of security issues in the ecosystem.

**Comment by stefanberger** [comment]
Right, so we would like to use an authenticated cipher for 'our purposes' and have been using the [miscreant](https://github.com/miscreant/miscreant) library for this.

**Comment by lumjjb** [comment]
Hi @FiloSottile , one of the issue that the `cipher.AEAD` interface brings with it is the memory footprint, and inability to pipeline well. The scenario I am considering is writing to a remote storage or local file. In this case, the data is not meant to be directly consumed but can benefit from a streaming interface. 

Do you think that this is a usecase is worth exploring to provide an alternative interface for?

**Comment by FiloSottile** [comment]
The issue is what happens if at the end of reading the stream you find out that the authentication tag is wrong? How do you recall the data you already sent off or processed? There are ways to do it, but they are a significant footgun.

For large sizes, you can use a chunking scheme like [STREAM](https://github.com/miscreant/miscreant/wiki/STREAM).

**Comment by lumjjb** [comment]
Great - Thanks @FiloSottile! By any chance, do you know any information about whether STREAM is on the roadmap for FIPS compliance?
