### ISSUE TITLE
Error in help:   -test.timeout --> ... (default 0, timeout disabled)

### ISSUE THREAD

**Issue by ftjfo** [golang/go#30742]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Run 
    go test -run Mytest -xyz 

produces a helptext where the test.timeout is stated to be disabled, when in fact it is 10 minutes

### What did you expect to see?

default test.timeout should be 10m

### What did you see instead?
It says 'default 0, timeout disabled'
![image](https://user-images.githubusercontent.com/18309904/54139854-ba7f6a00-4422-11e9-8ae1-56bd6af46a37.png)

**Comment by julieqiu** [comment]
@ftjfo, could you provide an example of the code that produced the error, preferably as a Go playground link (https://play.golang.org/). Would you also mind sharing the full output of running `go test -run Mytest -xyz`?

Additionally, what operating system and processor architecture are you using (go env)?

**Comment by ftjfo** [comment]
https://github.com/golang/go/blob/340129e4c8c56a371859b7434de89478610cab81/src/testing/testing.go#L283

If you look at this code line, and compare with: `go help testflag` 

    -timeout d                                                                                                                                                                     
    If a test binary runs longer than duration d, panic.                                                                                                                       
    If d is 0, the timeout is disabled.                                                                                                                                         
    The default is 10 minutes (10m).

**Comment by ianlancetaylor** [comment]
If at all possible please cut and paste text.  Please don't post screenshot images.  Text is much easier to read and understand.  Thanks.

The help output you are seeing is coming from the test binary.  From the test binary's perspective, that is correct.  The ten minute timeout you are referring to is imposed by `go test`.  You are mixing up the test binary flags with the `go test` flags, which I admit is easy to do since they look the same.  I don't think there is anything to change here.
