### ISSUE TITLE
x/tools/gopls: separate imports from formatting

### ISSUE THREAD

**Issue by stamblerre** [golang/go#30843]
LSP has a separation between formatting a document and organizing imports (the code action "source.organizeImports"). We should follow this by only returning diffs of the import block when we return results from goimports.

/cc @ramya-rao-a

**Comment by jbizzle** [comment]
I was actually a little surprised to find this, since [the wiki](https://github.com/golang/go/wiki/gopls) as of today mentions, in the context of configuration with `LanguageClient`:
```
" Run gofmt and goimports on save
autocmd BufWritePre *.go :call LanguageClient#textDocument_formatting_sync()
```
I understood that to mean that results from `textDocument/formatting` would also include fixing imports.

Am I mis-reading this issue or the wiki configuration example (or both)? If so, would you be able to give some more direction about the expected way to get the imports to be fixed via calls from an `lsp` client?

FWIW, I did trace the `gopls` source a bit, and IIUC, the import organizing code would only be invoked as `source.Imports` via `organizeImports` via `Server.codeAction`, and I don't believe there is any connection that I can see between `codeAction()` and the handler for `textFormatting`. Not saying this is news to you, just to give you some context on what I do (or do not) understand about the code.

**Comment by ianthehat** [comment]
The wiki is a little confusing, it is saying that gopls does the same work that gofmt and goimports do, so there is no need to run them any more. It will do the work of those two tools when you save the document with the settings we suggest, but it does it through two very different code paths (the formatting call and a codeAction)
This bug is about the fact that the implementation of the organizeImports code action is the same code that goimports normally invokes, which is intended to both fix the imports and then format the whole file (because goimports replaced gofmt as the file save hook the way editors used to work). We want to extract the parts of the library that fix the imports and be able to do that on it's own.
The formatting call really does just do the formatting, the same way that gofmt would.

**Comment by jbizzle** [comment]
Thanks for the quick reply and clarification. It's possible that there is still a problem, but I'll file it as a separate issue.

**Comment by stamblerre** [comment]
The above change stops formatting for a file that has no import modifications, but a file will still be formatted if we are adding or deleting imports.
