### ISSUE TITLE
math/big: fast path for Cmp if same

### ISSUE THREAD

**Issue by TuomLarsen** [golang/go#30856]
I noticed that math/big.Int [Cmp](https://github.com/golang/go/blob/829c140f149dba8933dea0cead3a78de4c83b529/src/math/big/int.go#L320) method does not have a fast path for the case if `x` and `y` are the same. Wouldn't it be beneficial to have there something along the lines:

    if x == y {
        r = 0
        return
    }

[Mul](https://github.com/golang/go/blob/829c140f149dba8933dea0cead3a78de4c83b529/src/math/big/int.go#L163) seems to do similar.

Same applies for big.Rat and big.Float.

**Comment by ALTree** [comment]
Note that `Mul` has that check because if the two numbers are the same you can do squaring, which is faster than a fully general multiplication. This is a fast-path that cannot be easily implemented by the caller since a fast squaring routine in not trivial to implement. On the other hand, it's easy to avoid an `Int.Cmp` call when the pointers are the same, and you can do that in user code.

**Comment by josharian** [comment]
Seems reasonable, if it fires. You might try putting it in, adding some logging when it does/doesn’t fire, and then running make.bash. If it fires a non-trivial percentage of times it definitely seems worthwhile.

**Comment by rsc** [comment]
Spoke to @griesemer; go ahead, for Go 1.14.

**Comment by IllyaYalovyy** [comment]
Is anyone working on it? I'm looking to start contributing, and need an easy task for a warmup.
