### ISSUE TITLE
x/build/cmd/gomote: warn when gomote binary is too old

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30929]
A common gomote complaint is that the set of builders has changed since the last time the user built the gomote binary.

We could pretty easily get it from the server instead.
 
/cc @ianlancetaylor

**Comment by bradfitz** [comment]
I did create and thought that was enough, but other parts of gomote still use the hard-coded info.

Reopening.

**Comment by bradfitz** [comment]
This stalled a bit because I realized https://farmer.golang.org/builders?mode=json wasn't sufficient, given how many unexported fields are in dashboard.BuildConfig and HostConfig.

Maybe instead we should just hash it all server-side and have the client check that its hash matches, otherwise warm loudly to the user that their gomote binary is old. We could even pull both sides' dates from their module info and tell them how old it is.

**Comment by dmitshur** [comment]
Another possible instance of this problem is in https://github.com/golang/go/issues/33309#issuecomment-532001071 (see last paragraph of the comment).

However, just fetching https://farmer.golang.org/builders?mode=json wouldn't have been sufficient, because the problem was that `gomote` was old enough to be missing a flag and not setting an env var. We probably need something to tell if the binary itself is too old. Maybe module versions and module mirror can come in handy.
