### ISSUE TITLE
cmd/go: building Go distribution from source fails with "missing $GOPATH"

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#30960]
On an amd64 GNU/Linux system with no `GOPATH` set in the environment, and with the Go source code at `$HOME/go` so that the default `GOPATH` setting does not work, running make.bash fails with

```
Building Go cmd/dist using /usr/local/google/home/iant/go1.4.
Building Go toolchain1 using /usr/local/google/home/iant/go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
missing $GOPATH
go tool dist: FAILED: /usr/local/google/home/iant/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

**Comment by jayconrod** [comment]
@ianlancetaylor This happens because modules are on by default in `go_bootstrap`. We need `GOPATH` very early to initialize the module cache. The behavior of `GOPATH` defaulting to `$HOME/go` comes from `go/build.defaultGOPATH`: it specifically avoids using `GOROOT`.

@andybons mentioned a similar error yesterday building the internal toolchain. I'm not sure what the target was, but is it possible to check out the source code somewhere other than `$HOME/go`? Even if we work around this by creating a temporary `GOPATH` in make.bash, the toolchain won't work at all until `GOPATH` is set explicitly.

**Comment by ianlancetaylor** [comment]
So you are saying that we now require a valid `GOPATH` in order to do any Go builds at all?  Seems slightly ironic since one of the goals of the module system is to get away from `GOPATH`.  But OK.  I guess we just need to document this.

**Comment by jayconrod** [comment]
Yep, we still need a place to put `$GOPATH/bin` and `$GOPATH/pkg/mod`. The former can be set explicitly with `GOBIN`, but there's no other way to set the latter.

I'll update documentation in make.bash and emit the error earlier in dist.

**Comment by jayconrod** [comment]
I take it back. It looks like dist is already setting `GOCACHE` to an temporary directory within `GOROOT` in order to avoid depending on anything existing outside `GOROOT`. We can do the same with `GOPATH`.

`GOPATH` may still need to be set to something different than `GOROOT` after the toolchain is built, but at least building the toolchain won't be any more complicated.
