### ISSUE TITLE
x/tools/gopls: make jsonrpc2, lsp, span and friends non-internal

### ISSUE THREAD

**Issue by myitcv** [golang/go#31080]
Per discussion on Slack, adding a placeholder to track making the following packages non-internal once they stabilise:

```
golang.org/x/tools/internal/jsonrpc2
golang.org/x/tools/internal/lsp/...
golang.org/x/tools/internal/span
```

The use case being, people writing LSP clients in Go can then readily leverage these packages.

cc @stamblerre @ianthehat

**Comment by wxio** [comment]
> Per discussion on Slack, adding a placeholder to track making the following packages non-internal once they stabilise:

How do I find the Slack channel?

**Comment by myitcv** [comment]
@wxio - you don't have to join the Slack channel to participate in discussions about the LSP, I was simply noting that I had had a conversation with @ianthehat there. 

More details on the various channels used for tools discussion:

https://github.com/golang/go/wiki/golang-tools

**Comment by fhs** [comment]
`internal/lsp/protocol` API seems to be too strict at the moment and only designed to work with gopls. For example, `ServerCapabilities.renameProvider` can be either `bool` or `RenameOptions,` but the protocol package expects `RenameOptions`. This breaks compatibility with go-langserver, which sends a `bool`. The current protocol package is not going to be very useful to me because I want to write a lsp client that supports all LSP servers that follow the LSP protocol.

**Comment by stamblerre** [comment]
I don't think that we will be moving any of these packages outside of internal in the near future, if ever. Doing so would require us to commit to maintaining stable APIs and would slow down progress on `gopls`. `internal/lsp/protocol` mostly contains generated code anyway, and open-sourcing that would require us to tag versions of x/tools for each version of the LSP.

This is a maintenance burden that I don't think we are able to commit to in the next few years, and I would imagine potential consumers of these APIs will find alternatives before that time comes.
