### ISSUE TITLE
403 Unauthorized client

### ISSUE THREAD

**Issue by mmdmine** [golang/go#31186]
all development services of google is blocked here. from android sdk to golang.com
even 'go get' doesn't work. f*ck

**Comment by DylanMeeus** [comment]
I assume "here" means Iran because I can see that in your profile. 

Unfortunately, I don't think this is the right place to post that issue if all google services are blocked in total. This is more about `go` and less about `google services` in general.  :( 

Are you sure this is not an issue on your network though?

**Comment by agnivade** [comment]
As already mentioned, this issue tracker is only for Go specific bugs. Your issue is outside the scope of this repo.

**Comment by mmdmine** [comment]
> I assume "here" means Iran because I can see that in your profile.
> 
> Unfortunately, I don't think this is the right place to post that issue if all google services are blocked in total. This is more about `go` and less about `google services` in general. :(
> 
> Are you sure this is not an issue on your network though?

![DeepinScreenshot_20190403193236](https://user-images.githubusercontent.com/21140798/55489501-431ab000-5647-11e9-95ce-975aa7e2da93.png)

As you can see, My connection is fine. This is political. I can't use 'go get' as this problem.
Also, they've blocked Tor, I can't use 'go get' through tor.
```
package golang.org/x/tools/godoc/static: unrecognized import path "golang.org/x/tools/godoc/static" (https fetch: Get https://golang.org/x/tools/godoc/static?go-get=1: Tor is not an HTTP Proxy)
```
