### ISSUE TITLE
wiki: CodeReviewComments change

### ISSUE THREAD

**Issue by AlaxLee** [golang/go#31183]
On "Import Dot"，the example code could not due to circular dependencies.
`
package foo_test

import (
	"bar/testutil" // also imports "foo"
)
`

**Comment by AlaxLee** [comment]
I create two package as follow:
1. bar/testutil/haha.go
`
package testutil

import (
	"fmt"
	"foo"
)

func Tt(){
	fmt.Println("Tt")
	foo.F()
}
`
2. foo/foo.go
`
package foo

import "fmt"

func F() {
	fmt.Println("F")
}
`
3. foo/foo_test.go
`
package foo_test

import (
	"bar/testutil" // also imports "foo"
	"testing"
)


func TestF(t *testing.T) {
	testutil.Tt()
}
`

**Comment by agnivade** [comment]
It is not clear to me what exactly do you want to change in this section. Could you clarify ? Your code does not even dot import the foo package in foo_test.

**Comment by AlaxLee** [comment]
In the example, it says, local code will due to circular dependencies
`
package foo_test

import (
	"bar/testutil" // also imports "foo"
)
`
and if we use import dot as follow, we can avoid circular dependencies
`
package foo_test

import (
	"bar/testutil" // also imports "foo"
	. "foo"
)
`

but I find that, if not use import dot, it also avoid circular dependencies.
If something wrong in the document  or  my  code ?

**Comment by GreenHorse** [comment]
[CodeReviewComments#import-dot](https://github.com/golang/go/wiki/CodeReviewComments#import-dot) :
> [...]
In this case, the test file cannot be in package foo because it uses bar/testutil, which imports foo. So we use the 'import .' form to let the file pretend to be part of package foo even though it is not.
[...]

The point is __not__ that you have to __dot__ import the `foo` package. The point is the test file cannot be part of the package foo and to pretend it is you use a dot import.

#### The problem:
Because the test is for the `foo` package we want to make it part of the package, but we cannot, it would result in a circular dependency.

#### Rejected Solution:
We could import it but we will need to prefix every function/variable with `foo.`.
It won't looks like it is part of the foo package

#### Solution:
So instead of just importing it, we do a dot import.
The dot import is to make it looks like the file is part of the `foo` package. There is no need to prefix every function/variable defined in foo with the name of the package. The test file can pretend it is part of the foo package.

#### foo_test.go (without dot import)
```go
package foo_test

import (
	"bar/testutil"
	"foo"
)

func Test_DoSomething(t *testing.T) {
	err := foo.DoSomething("something")
	// use package testutil
}
```
It is clear that the DoSomething function is part of the foo package and that our test is __not__ part of it.

#### foo_test.go (with dot import)
```go
package foo_test

import (
	"bar/testutil"
	. "foo"
)

func Test_DoSomething(t *testing.T) {
	err := DoSomething("something")
	// use package testutil
}
```

At first glance in the second example, we could think Bar function is part of this package.

**Comment by agnivade** [comment]
Nicely explained @GreenHorse. @AlaxLee I hope that clarifies your question. For further queries, please reach out to https://github.com/golang/go/wiki/Questions. Closing.
