### ISSUE TITLE
x/net/icmp: PacketConn.NonPrivilegedPing example is not correct in final expectation

### ISSUE THREAD

**Issue by labulaka521** [golang/go#31204]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
```
switch runtime.GOOS {
case "darwin":
case "linux":
    log.Println("you may need to adjust the net.ipv4.ping_group_range kernel state")
default:
    log.Println("not supported on", runtime.GOOS)
    return
}

c, err := icmp.ListenPacket("udp6", "fe80::1%en0")
if err != nil {
    log.Fatal(err)
}
defer c.Close()

wm := icmp.Message{
    Type: ipv6.ICMPTypeEchoRequest, Code: 0,
    Body: &icmp.Echo{
        ID: os.Getpid() & 0xffff, Seq: 1,
        Data: []byte("HELLO-R-U-THERE"),
    },
}
wb, err := wm.Marshal(nil)
if err != nil {
    log.Fatal(err)
}
if _, err := c.WriteTo(wb, &net.UDPAddr{IP: net.ParseIP("ff02::1"), Zone: "en0"}); err != nil {
    log.Fatal(err)
}

rb := make([]byte, 1500)
n, peer, err := c.ReadFrom(rb)
if err != nil {
    log.Fatal(err)
}
rm, err := icmp.ParseMessage(58, rb[:n])
if err != nil {
    log.Fatal(err)
}
switch rm.Type {
case ipv6.ICMPTypeEchoReply:
    log.Printf("got reflection from %v", peer)
default:
    log.Printf("got %+v; want echo reply", rm)
}
```
output
```
2019/04/02 20:41:11 got &{Type:echo request Code:0 Checksum:10393 Body:0xc00008ea20}; want echo reply
```
in this case , it match `default` option in last, 

but i think it should match `ipv6.ICMPTypeEchoReply`, if i change 
```
switch rm.Type {
case ipv6.ICMPTypeEchoReply:
    log.Printf("got reflection from %v", peer)
default:
    log.Printf("got %+v; want echo reply", rm)
}
```

 to   

```
switch rm.Type {
case ipv6.ICMPTypeEchoRequest:
    log.Printf("got reflection from %v", peer)
default:
    log.Printf("got %+v; want echo reply", rm)
}
```

 `default` is not  be  matched,  i thinks it wrong?

**Comment by odeke-em** [comment]
Thank you for the report @labulaka521 and welcome to the Go project!

To me, yes in deed, it doesn't look correct that we expect from our sender a packet of type of `ipv6.ICMPTypeEchoReply` yet they sent a `ipv6.ICMPTypeEchoRequest`

Kindly paging @mikioh @nigeltao

**Comment by mikioh** [comment]
I believe that you modified and run the example on your node, so your modification is the key because fe80::1 is assigned to only loopback interfaces on darwin.

Please be informed that IPv6 multicast packet delivery via loopback interface depends on each implementation. Some might send back the original packet and ICMP never touches the packet because "loopback interface is just for the maintenance and handling unicast/anycast packets is enough." FWIW, you can control the multicast loopback by using icmp.PacektConn.IPv6PacketConn.

Please try the example w/ non-loopback links. If you have a more better example, not a dumb unicast one, feel free to send a CL. Thanks.
