### ISSUE TITLE
Golang grammar for constants

### ISSUE THREAD

**Issue by ancaemanuel** [golang/go#31207]
See this:
https://play.golang.org/p/50l_XzHNSiS

How it is possible to have this parsed: "-+-+-+-1" ?
I think it is an error on the parser side, or some more...

**Comment by go101** [comment]
Why shouldn't it be parsed? `-+-+-+-1` is equivalent to `-(+(-(+(-(+(-1))))))`.

**Comment by go101** [comment]
Similarly,
```golang
var x int
var y = *&*&*&*&*&x // y == x
```

**Comment by ancaemanuel** [comment]
@go101 in what language did you see that behaviour ?

**Comment by ancaemanuel** [comment]
If we think math, that is simple to parse. But we are in other environment and we need to define very explicit what is ok.

**Comment by ianlancetaylor** [comment]
@ancaemanuel I'm going to close this issue because the language spec clearly accepts these kind of expressions, and the compiler is doing the right thing per the language spec.  If you have questions about this I suggest that you use a forum rather than the issue tracker; see https://golang.org/wiki/Questions .  Thanks.
