### ISSUE TITLE
x/build/dashboard: darwin-arm-mg912baios and darwin-arm64-mn4m2zdaios builders consistently failing

### ISSUE THREAD

**Issue by bcmills** [golang/go#31497]
Starting around https://build.golang.org/log/776c688e90aaa17f09782242647391a368eeabc7 (Apr. 9), the two `darwin-arm*` builders have been failing with lots of messages of the form

```
go_darwin_arm_exec: GOIOS_DEV_ID not set
run $GOROOT/misc/ios/detect.go to attempt to autodetect
FAIL	archive/tar	0.017s
```

It seems like that may be due to a change in the builder configuration, but I'm not really sure.

@eliasnaur, could you look into it (or loop in someone who can)?

**Comment by eliasnaur** [comment]
Yes, I've pinged @steeve. I believe he's on it.

**Comment by steeve** [comment]
I am. I'll try to completely factory reset the arm64 phone. arm32 should be ok I think

**Comment by bradfitz** [comment]
Any update?

**Comment by steeve** [comment]
Yes, the builders seems ok now.

**Comment by bcmills** [comment]
`mg912baios` seems to be unplugged (https://build.golang.org/log/532482aa5995eaeb33bbd8dbeca8064b22a11014):
```
No device found with udid 8e5c23a5d0843d1ffe164ea0b2f2500599c3ebff, is it plugged in?
```

**Comment by steeve** [comment]
@bcmills yes, the 32 bits device is having issues, I'm trying to get another device to test.

**Comment by steeve** [comment]
I bisected the problem in `ideviceinstaller`. The problem is https://github.com/libimobiledevice/ideviceinstaller/commit/4a7f0b01483f2b1e3c11447bb4654b181deacf41

I have opened https://github.com/libimobiledevice/ideviceinstaller/issues/119 to track it. In the mean time I'm going to revert that commit on the build machine.

**Comment by steeve** [comment]
I have downgraded `ideviceinstaller`, and the builder now seems to run ok. I'll monitor.

**Comment by steeve** [comment]
The builder is back online for the two archs, and now they are failing for good reasons

**Comment by bcmills** [comment]
> now they are failing for good reasons

It looks like the current failures are not sending output back to the runner. Is there some change that needs to be made to extract it from the device on failure?

Are there issues filed for the current failures?

**Comment by eliasnaur** [comment]
I don't know of any way than manually running the tests. See

https://github.com/golang/go/issues/34751#issuecomment-539988570
https://github.com/golang/go/issues/34751#issuecomment-540532877

**Comment by steeve** [comment]
Thanks, I'll do it tomorrow!

**Comment by eliasnaur** [comment]
FWIW, you might find https://github.com/golang/go/issues/34501#issuecomment-542535507 useful. You can now use TRY= to target a particular set of builders.

**Comment by eliasnaur** [comment]
I couldn't reproduce the failures on an iPhone 5S running iOS 10. I ran:

    GO_BUILDER_NAME=darwin-arm64-mn4m2zdaios GOARCH=arm64 CGO_ENABLED=1 CC_FOR_TARGET=$(pwd)/../misc/ios/clangwrap.sh ./all.bash

(GO_BUILDER_NAME set runs tests that normally doesn't run).

Perhaps the devices are somehow broken, although it is unlikely. I noticed that the builder test times quite a bit higher than the times for my old 5S. Compare

https://build.golang.org/log/c6e5a939431f25560b0f1b6837fe465f7c1cb0e5

with

<details><pre>
$ GO_BUILDER_NAME=darwin-arm64-mn4m2zdaios GOARCH=arm64 CGO_ENABLED=1 CC_FOR_TARGET=$(pwd)/../misc/ios/clangwrap.sh ./all.bash
Building Go cmd/dist using /Users/elias/go1.10.1.
Building Go toolchain1 using /Users/elias/go1.10.1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for host, darwin/amd64.
Building packages and commands for target, darwin/arm64.

##### Testing packages.
ok  	archive/tar	18.201s
ok  	archive/zip	11.190s
ok  	bufio	7.152s
ok  	bytes	14.369s
ok  	bytes/hash	16.824s
ok  	compress/bzip2	15.776s
ok  	compress/flate	12.629s
ok  	compress/gzip	12.045s
ok  	compress/lzw	13.847s
ok  	compress/zlib	14.690s
ok  	container/heap	16.063s
ok  	container/list	16.188s
ok  	container/ring	14.735s
ok  	context	11.305s
ok  	crypto	12.365s
ok  	crypto/aes	15.064s
ok  	crypto/cipher	14.427s
ok  	crypto/des	13.884s
ok  	crypto/dsa	15.297s
ok  	crypto/ecdsa	15.013s
ok  	crypto/ed25519	15.736s
ok  	crypto/elliptic	15.728s
ok  	crypto/hmac	14.655s
ok  	crypto/internal/subtle	11.942s
ok  	crypto/md5	11.154s
ok  	crypto/rand	13.423s
ok  	crypto/rc4	16.539s
ok  	crypto/rsa	16.583s
ok  	crypto/sha1	16.769s
ok  	crypto/sha256	14.369s
ok  	crypto/sha512	13.625s
ok  	crypto/subtle	13.943s
ok  	crypto/tls	16.474s
ok  	crypto/x509	10.810s
ok  	database/sql	18.426s
ok  	database/sql/driver	21.070s
ok  	debug/dwarf	17.096s
ok  	debug/elf	14.532s
ok  	debug/gosym	16.432s
ok  	debug/macho	16.740s
ok  	debug/pe	16.651s
ok  	debug/plan9obj	15.850s
ok  	encoding/ascii85	12.912s
ok  	encoding/asn1	12.634s
ok  	encoding/base32	12.794s
ok  	encoding/base64	11.628s
ok  	encoding/binary	11.053s
ok  	encoding/csv	13.882s
ok  	encoding/gob	13.455s
ok  	encoding/hex	17.578s
ok  	encoding/json	19.731s
ok  	encoding/pem	20.637s
ok  	encoding/xml	18.714s
ok  	errors	18.430s
ok  	expvar	15.001s
ok  	flag	14.468s
ok  	fmt	13.896s
ok  	go/ast	15.172s
ok  	go/build	15.188s
ok  	go/constant	14.788s
ok  	go/doc	14.414s
ok  	go/format	14.197s
ok  	go/importer	12.109s
ok  	go/internal/gccgoimporter	15.107s
ok  	go/internal/gcimporter	15.507s
ok  	go/internal/srcimporter	15.818s
ok  	go/parser	14.590s
ok  	go/printer	13.898s
ok  	go/scanner	12.324s
ok  	go/token	11.212s
ok  	go/types	10.876s
ok  	hash	13.154s
ok  	hash/adler32	14.959s
ok  	hash/crc32	14.631s
ok  	hash/crc64	13.114s
ok  	hash/fnv	12.926s
ok  	html	13.659s
ok  	html/template	14.707s
ok  	image	14.538s
ok  	image/color	15.613s
ok  	image/draw	16.387s
ok  	image/gif	16.972s
ok  	image/jpeg	17.097s
ok  	image/png	22.929s
ok  	index/suffixarray	22.717s
ok  	internal/cpu	15.546s
ok  	internal/fmtsort	20.220s
ok  	internal/poll	14.344s
ok  	internal/reflectlite	15.453s
ok  	internal/singleflight	12.261s
ok  	internal/trace	13.367s
ok  	internal/xcoff	13.251s
ok  	io	11.707s
ok  	io/ioutil	14.055s
ok  	log	14.236s
ok  	log/syslog	14.328s
ok  	math	12.967s
ok  	math/big	13.534s
ok  	math/bits	15.471s
ok  	math/cmplx	17.359s
ok  	math/rand	20.752s
ok  	mime	17.974s
ok  	mime/multipart	18.536s
ok  	mime/quotedprintable	17.830s
ok  	net	12.891s
ok  	net/http	31.848s
ok  	net/http/cgi	16.170s
ok  	net/http/cookiejar	36.788s
ok  	net/http/fcgi	37.614s
ok  	net/http/httptest	39.733s
ok  	net/http/httptrace	25.852s
ok  	net/http/httputil	27.925s
ok  	net/http/internal	25.935s
ok  	net/http/pprof	24.583s
ok  	net/internal/socktest	25.154s
ok  	net/mail	25.736s
ok  	net/rpc	26.676s
ok  	net/rpc/jsonrpc	23.754s
ok  	net/smtp	24.981s
ok  	net/textproto	23.249s
ok  	net/url	22.979s
ok  	os	22.862s
ok  	os/exec	18.322s
ok  	os/signal	23.432s
ok  	os/user	20.376s
ok  	path	17.529s
ok  	path/filepath	16.829s
ok  	plugin	13.654s
ok  	reflect	8.814s
ok  	regexp	13.082s
ok  	regexp/syntax	14.190s
ok  	runtime	40.523s
ok  	runtime/debug	12.701s
ok  	runtime/internal/atomic	21.586s
ok  	runtime/internal/math	50.398s
ok  	runtime/internal/sys	50.778s
ok  	runtime/pprof	61.725s
ok  	runtime/pprof/internal/profile	48.881s
ok  	runtime/trace	48.433s
ok  	sort	43.406s
ok  	strconv	25.252s
ok  	strings	23.497s
ok  	sync	13.304s
ok  	sync/atomic	15.885s
ok  	syscall	22.605s
ok  	testing	23.282s
ok  	testing/quick	24.825s
ok  	text/scanner	24.583s
ok  	text/tabwriter	13.329s
ok  	text/template	12.708s
ok  	text/template/parse	12.437s
ok  	time	14.342s
ok  	unicode	17.984s
ok  	unicode/utf16	18.413s
ok  	unicode/utf8	18.245s
ok  	cmd/addr2line	14.911s
ok  	cmd/api	16.565s
ok  	cmd/asm/internal/asm	19.435s
ok  	cmd/asm/internal/lex	22.476s
ok  	cmd/compile	14.944s
ok  	cmd/compile/internal/gc	13.900s
ok  	cmd/compile/internal/ssa	14.009s
ok  	cmd/compile/internal/syntax	17.947s
ok  	cmd/compile/internal/test	16.562s
ok  	cmd/compile/internal/types	12.867s
ok  	cmd/cover	7.833s
ok  	cmd/doc	8.944s
ok  	cmd/fix	15.593s
ok  	cmd/go	20.502s
ok  	cmd/go/internal/auth	29.320s
ok  	cmd/go/internal/cache	35.796s
ok  	cmd/go/internal/dirhash	43.076s
ok  	cmd/go/internal/generate	41.227s
ok  	cmd/go/internal/get	43.067s
ok  	cmd/go/internal/imports	43.416s
ok  	cmd/go/internal/load	42.931s
ok  	cmd/go/internal/lockedfile	42.894s
ok  	cmd/go/internal/lockedfile/internal/filelock	43.013s
ok  	cmd/go/internal/modconv	46.200s
ok  	cmd/go/internal/modfetch	46.436s
ok  	cmd/go/internal/modfetch/codehost	45.561s
ok  	cmd/go/internal/modfile	44.536s
ok  	cmd/go/internal/modload	41.002s
ok  	cmd/go/internal/module	41.762s
ok  	cmd/go/internal/mvs	41.725s
ok  	cmd/go/internal/note	40.770s
ok  	cmd/go/internal/par	39.428s
ok  	cmd/go/internal/renameio	42.728s
ok  	cmd/go/internal/search	41.736s
ok  	cmd/go/internal/semver	42.004s
ok  	cmd/go/internal/sumdb	42.078s
ok  	cmd/go/internal/tlog	41.237s
ok  	cmd/go/internal/txtar	44.945s
ok  	cmd/go/internal/web	45.697s
ok  	cmd/go/internal/work	43.101s
ok  	cmd/gofmt	36.385s
ok  	cmd/internal/buildid	27.874s
ok  	cmd/internal/dwarf	19.661s
ok  	cmd/internal/edit	16.184s
ok  	cmd/internal/goobj	14.456s
ok  	cmd/internal/obj	15.065s
ok  	cmd/internal/obj/arm64	14.677s
ok  	cmd/internal/obj/x86	13.805s
ok  	cmd/internal/objabi	14.729s
ok  	cmd/internal/src	15.072s
ok  	cmd/internal/test2json	16.841s
ok  	cmd/link	16.346s
ok  	cmd/link/internal/ld	16.424s
ok  	cmd/link/internal/sym	17.148s
ok  	cmd/nm	15.624s
ok  	cmd/objdump	14.410s
ok  	cmd/pack	15.963s
ok  	cmd/trace	14.936s
ok  	cmd/vet	13.833s

##### os/user with tag osusergo
ok  	os/user	12.085s

##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
ok  	runtime	50.483s

##### sync -cpu=10
ok  	sync	4.940s

##### ../misc/cgo/test
lldb: running program
scatter = 0x1001d7da4
sqrt is: 0
testLibgcc is disabled on ARM64 with clang due to lack of libgcc.
testLibgcc is disabled on ARM64 with clang due to lack of libgcc.
testLibgcc is disabled on ARM64 with clang due to lack of libgcc.
testLibgcc is disabled on ARM64 with clang due to lack of libgcc.
testLibgcc is disabled on ARM64 with clang due to lack of libgcc.
hello from C
PASS
ok  	misc/cgo/test	52.168s

##### ../misc/cgo/testso
ok  	misc/cgo/testso	53.345s

##### ../misc/cgo/testsovar
ok  	misc/cgo/testsovar	16.533s

##### ../misc/cgo/testcarchive
PASS

ALL TESTS PASSED
---
Installed Go for darwin/arm64 in /Users/elias/go-tip
Installed commands in /Users/elias/go-tip/bin
</pre></details>

**Comment by bcmills** [comment]
Looking at just the names of the failing tests, my hypothesis is that they are the memory-intensive ones, and that the tests are being killed by some sort of OOM signal.

That would also explain the lack of output: Go tests buffer their output until the test completes, so if the test binary is killed before it completes, it may well produce no output.

**Comment by bcmills** [comment]
If that hypothesis is correct, then it seems to me that the ideal fix is to have the memory-intensive tests in the affected packages query (somehow‽) for the process's memory limit and invoke `t.Skip` if there is not enough memory to complete the test.

**Comment by bcmills** [comment]
Do these devices already scale the test parallelism down to 1? If not, that might be another good starting point.

**Comment by eliasnaur** [comment]
If the were with memory or parallelism, why can't I reproduce the problem on the modest iPhone 5S? I still believe the devices need a factory reset or replacement. @steeve ?

**Comment by steeve** [comment]
I am giving a a look at the device builder.
I'm trying to run the failing tests in verbose mode, I see in https://build.golang.org/log/a5ca5d49956d984e773f40a0a4c56e79dd7858de
```
FAIL	bytes	114.748s
FAIL	crypto/tls	72.274s
FAIL	crypto/x509	82.845s
FAIL	math/big	79.414s
FAIL	net/http	97.111s
FAIL	runtime	79.566s
FAIL	runtime/pprof	126.951s
FAIL	strings	119.247s
```

That said, when running on `HEAD` I get a weird error:
```
$ GOIOS_DEVICE_ID=8e5c23a5d0843d1ffe164ea0b2f2500599c3ebff GOARCH=arm CGO_ENABLED=1 go test -v archive/tar
# runtime/cgo
clang: error: argument unused during compilation: '-mno-thumb' [-Werror,-Wunused-command-line-argument]
FAIL	archive/tar [build failed]
FAIL
```

**Comment by steeve** [comment]
I got it working:
```
$ PATH=$(pwd)/bin:$PATH GOROOT=$(pwd) GO_BUILDER_NAME=darwin-arm-mg912baios GOARCH=arm CGO_ENABLED=1 CC=$(pwd)/misc/ios/clangwrap.sh ./bin/go test -v bytes
lldb: running program
=== RUN   TestNewBuffer
--- PASS: TestNewBuffer (0.00s)
=== RUN   TestNewBufferString
--- PASS: TestNewBufferString (0.00s)
=== RUN   TestBasicOperations
--- PASS: TestBasicOperations (0.00s)
=== RUN   TestLargeStringWrites
--- PASS: TestLargeStringWrites (0.07s)
=== RUN   TestLargeByteWrites
--- PASS: TestLargeByteWrites (0.06s)
=== RUN   TestLargeStringReads
--- PASS: TestLargeStringReads (0.00s)
=== RUN   TestLargeByteReads
--- PASS: TestLargeByteReads (0.00s)
=== RUN   TestMixedReadsAndWrites
--- PASS: TestMixedReadsAndWrites (0.01s)
=== RUN   TestCapWithPreallocatedSlice
--- PASS: TestCapWithPreallocatedSlice (0.00s)
=== RUN   TestCapWithSliceAndWrittenData
--- PASS: TestCapWithSliceAndWrittenData (0.00s)
=== RUN   TestNil
--- PASS: TestNil (0.00s)
=== RUN   TestReadFrom
--- PASS: TestReadFrom (0.00s)
=== RUN   TestReadFromPanicReader
--- PASS: TestReadFromPanicReader (0.00s)
=== RUN   TestReadFromNegativeReader
--- PASS: TestReadFromNegativeReader (0.00s)
=== RUN   TestWriteTo
--- PASS: TestWriteTo (0.00s)
=== RUN   TestRuneIO
--- PASS: TestRuneIO (0.00s)
=== RUN   TestNext
--- PASS: TestNext (0.00s)
=== RUN   TestReadBytes
--- PASS: TestReadBytes (0.00s)
=== RUN   TestReadString
--- PASS: TestReadString (0.00s)
=== RUN   TestGrow
--- PASS: TestGrow (0.01s)
=== RUN   TestGrowOverflow
--- PASS: TestGrowOverflow (0.00s)
=== RUN   TestReadEmptyAtEOF
--- PASS: TestReadEmptyAtEOF (0.00s)
=== RUN   TestUnreadByte
--- PASS: TestUnreadByte (0.00s)
=== RUN   TestBufferGrowth
--- PASS: TestBufferGrowth (0.01s)
=== RUN   TestEqual
--- PASS: TestEqual (0.00s)
=== RUN   TestEqualExhaustive
--- PASS: TestEqualExhaustive (0.26s)
=== RUN   TestNotEqual
FAIL	bytes	13.790s
FAIL
```

**Comment by bcmills** [comment]
I don't see any actual test failures in the verbose output. Is the `lldb` wrapper somehow injecting a nonzero exit code?

**Comment by steeve** [comment]
@bcmills I'm editing the log in place just in case, you might want to refresh

**Comment by steeve** [comment]
For some reason I can't run the `runtime` test, it just hangs on
```lldb: running program```

**Comment by bcmills** [comment]
`darwin-arm64-mn4m2zdaios` is now failing pretty consistently in `misc/cgo/testcarchive.TestOsSignal`:

[2020-02-20T05:04:39-49f8d45/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/d2ac9cf1f9895eea9b3a257b6cfaafce8e0eb881)
[2020-02-20T03:27:46-715e8bb/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/c247fd1cd44d44bd37427d31ef95b87e9e273ff3)
[2020-02-19T23:28:35-8fa2b6d/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/b1009d3884029e8b5cf9ea06faae36beb587e5e5)
[2020-02-19T22:04:29-f4f7db4/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/d1c5184bb1809087151dbf804489881ef191df20)
[2020-02-19T21:53:23-8a8adc2/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/ea4596bfe43a021cad1dc46bc89f2591600149d6)
[2020-02-19T21:18:17-2f2e97c/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/4d5e8858587aea68ce5b6725c47b33a2113026de)
[2020-02-18T19:44:25-a0cf2c8/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/bd569828202fa376dafcefaadc9db6bbb1fd5da8)
[2020-02-18T17:55:23-a9ea91d/darwin-arm64-mn4m2zdaios](https://build.golang.org/log/17753c636e66ffa2edc4c61127674441a4d9a81f)

**Comment by andybons** [comment]
@steeve this is far outside the four week failure widow specified in our [porting policy](https://golang.org/wiki/PortingPolicy#removing-a-port), which is grounds for removal. Are you able to devote the needed time to maintain this port? Is there someone else who should take over?

**Comment by andybons** [comment]
Since we've already said in the [1.14 release notes](https://golang.org/doc/go1.14):

> Go 1.14 will likely be the last Go release to support 32-bit binaries on iOS, iPadOS, watchOS, and tvOS (the darwin/arm port). Go continues to support the 64-bit darwin/arm64 port.

This may be the time for us to remove the 32 bit darwin ports.

Apple started requiring 64 bit in iOS 11 (released September 2017). Is there a compelling reason for us to continue to support darwin/arm, @steeve @eliasnaur ?

**Comment by andybons** [comment]
Per #37611, we will be removing `darwin/arm` (keeping `darwin/arm64`) so that builder will go away soon.

As there hasn’t been a reply yet about either builder, it’s likely that we’ll remove both from the dashboard as all they’re providing is noise at the moment.

**Comment by steeve** [comment]
Hey guys
I think we can remove the builders. Unfortunately the builds are failing and my attempts at finding the root cause was unsucessful.

In any case, the Corellium builder is way more reliable than what we have at the moment.

If somebody is willing to help me debug it tho, I can take half a day and do so.

**Comment by steeve** [comment]
> Apple started requiring 64 bit in iOS 11 (released September 2017). Is there a compelling reason for us to continue to support darwin/arm, @steeve @eliasnaur ?

The reason was to keep some WatchOS versions working.

**Comment by dmitshur** [comment]
> > Apple started requiring 64 bit in iOS 11 (released September 2017). Is there a compelling reason for us to continue to support darwin/arm, @steeve @eliasnaur ?
>
> The reason was to keep some WatchOS versions working.

Also see #34751 where it was discussed in more detail.
