### ISSUE TITLE
x/build/cmd/buildlet: $PATH miscomputed when set in "env" parameter, causing test failures on aix-ppc64

### ISSUE THREAD

**Issue by Helflym** [golang/go#31567]
The tests of x/tools and x/tour are failing on aix/ppc64, because the builder seems to use an hybrid version between 1.12.1 and master. Any idea of what must be changed/fixed ? 

https://build.golang.org/log/b7b160e7a7e733fbe768d45af70cf1c626ac4289
https://build.golang.org/log/7e28abbbd860c0ea1f212805b15ce5f3e8bf5d14

/cc @bradfitz 

**Edit by @dmitshur:** The root cause of this problem is described in https://github.com/golang/go/issues/31567#issuecomment-484925837.

**Comment by bradfitz** [comment]
I don't know what's going on there.

Per the first line of that first URL, it should only be using Go built at c8aaec2f70c5ccbca1ec2152c57d19981ac09133, which you see later in the log with:

```
# internal/cpu
compile: version "devel c8aaec2f70c5ccbca1ec2152c57d19981ac09133" does not match go tool version "go1.12.1"
```

So I don't know why it's expecting Go 1.12.1 or where that comes from.

/cc @ianlancetaylor @bcmills @dmitshur

**Comment by bcmills** [comment]
There are two `PATH` entries in the command line logged at the top:

`"PATH=/ramdisk8GB/workdir-host-aix-ppc64-osuosl/go/bin:/opt/freeware/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java7_64/jre/bin:/usr/java7_64/bin"`
and
`"PATH=/opt/freeware/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java7_64/jre/bin:/usr/java7_64/bin"`

The latter does not include `GOROOT/bin`, so that's presumably where the `go` at 1.12.1 is coming from.

I don't know why `compile` is coming from the `devel` version, though.

**Comment by Helflym** [comment]
I think the second path comes from https://go-review.googlesource.com/c/build/+/152457. However, they are supposed to be merged together or at least $GOROOT/bin should be added to the $PATH coming from the dashboard.

**Comment by bradfitz** [comment]
> I don't know why compile is coming from the devel version, though.

Because this is a build that's running repo "go" at master (rev `c8aaec2f70c5ccbca1ec2152c57d19981ac09133`) against x/net master.

**Comment by bradfitz** [comment]
But, yeah, double/unmerged PATH definitely looks like the problem here. Thanks for noticing that and for the CL link.

**Comment by bcmills** [comment]
https://build.golang.org/log/18084f24be9cc1f31dbef14b8e398003e21045e0
```
--- FAIL: TestHookChangeGofmt (2.94s)
    hook_test.go:267: invoking commit hook explicitly
    hook_test.go:268: git-codereview hook-invoke pre-commit
    hook_test.go:271: change without hook installed
    hook_test.go:273: git-codereview change
    hook_test.go:276: change with hook installed
    hook_test.go:493: in git-codereview/, ran [go build -o /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/git-codereview-test399063055/git-client/git-codereview]: exit status 2
        # unicode
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # crypto/internal/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/internal/sys
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # math/bits
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # unicode/utf8
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # vendor/golang.org/x/crypto/internal/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/cpu
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # encoding
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # crypto/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/nettrace
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # container/list
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # unicode/utf16
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/race
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # vendor/golang.org/x/crypto/cryptobyte/asn1
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/internal/atomic
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # sync/atomic
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/cgo
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
--- FAIL: TestHookCommitMsgFromGit (2.54s)
    hook_test.go:493: in git-codereview/, ran [go build -o /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/git-codereview-test792055703/git-client/git-codereview]: exit status 2
        # vendor/golang.org/x/crypto/internal/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/cpu
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # unicode/utf16
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # crypto/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # container/list
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # vendor/golang.org/x/crypto/cryptobyte/asn1
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # encoding
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/nettrace
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # unicode/utf8
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/internal/sys
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # crypto/internal/subtle
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # internal/race
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # math/bits
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # unicode
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/internal/atomic
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # sync/atomic
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
        # runtime/cgo
        compile: version "devel 49f8d45994b6782e4925057909e4896832334a26" does not match go tool version "go1.13"
FAIL
FAIL	golang.org/x/review/git-codereview	72.131s
```

CC @cagedmantis @toothrot

**Comment by bcmills** [comment]
> to me it looks like the problem may be that the test code tries to run "go" from PATH, but the Go toolchain that was built and is being tested (the one in GOROOT/bin) is not in PATH.

I agree — that's my assessment of the problem too.

> I'm only seeing one PATH entry …, so though CL 354754 looks like a good change to me, it may not be enough.

My evidence so far is:

* There is a `PATH` entry in [`dashboard/builders.go`](https://github.com/golang/build/blob/79bb74b4be072b7741310726f68175684557ae60/dashboard/builders.go#L2501), and that entry matches what is currently showing in the build logs.

* The coordinator explicitly adds `$WORKDIR/go/bin` to `PATH` when it executes subrepo tests ([`cmd/coordinator/coordinator.go:2815`](https://github.com/golang/build/blob/79bb74b4be072b7741310726f68175684557ae60/cmd/coordinator/coordinator.go#L2815)).

* There were duplicated paths in previous logs for the `aix-ppc64` builder.

* The only other builder that specifies a `PATH` in `dashboard/builders.go` is `js-wasm`, but that builder doesn't run tests that run `go` commands because `js` doesn't support `os/exec` at all.

I don't have request logs, but my hypothesis is that what's happening here is:
1. `cmd/coordinator` sends the `PATH` entry from `dashboard/builders.go` in the builder's environment, and sends the `Path` field from the `ExecOpts` as a separate query parameter.
2. `cmd/buildlet` appends the `PATH` entry to the environment (after the `PATH` entry that was already present in the process's environment) then calls `setPathEnv` to add in the values from the `Path` field.
3. `setPathEnv` edits the former `PATH` (from the process's environment) instead of the one added in step (1).
4.  `envutil.Dedup` keeps the `PATH` value added in step (1) instead of the one edited in step (3).

The fix is to change step (3) to edit the actual path key-value instead of the out-of-date one.

**Comment by dmitshur** [comment]
buildlet.aix-ppc64 is now rebuilt with [CL 354754](https://golang.org/cl/354754).

**Comment by bcmills** [comment]
The `aix-ppc64` builder is now passing for `x/review`!

(https://build.golang.org/log/5d976685f5d214a02a754b4327387f9fa101f256)
