### ISSUE TITLE
cmd/go: add 'go version <binary>'

### ISSUE THREAD

**Issue by rsc** [golang/go#31624]
Many people find rsc.io/goversion useful.
It would be better as 'go version' instead of having
to download a separate tool.

**Comment by mrueg** [comment]
@rsc since this is now part of `cmd/go/internal`  and you mentioned `github.com/rsc/goversion` is going to be deprecated, are there plans to expose the functions for a use in other tools (e.g. https://github.com/mitchellh/golicense/)?

**Comment by mvdan** [comment]
@mrueg note that the API to query Go packages and modules is `go list`, not a Go package. The reason is so that the underlying implementation can change, and one doesn't need to rebuild all tools anytime the Go version changes.

For example, https://godoc.org/golang.org/x/tools/go/packages is a Go API that simply execs `go list` when working with GOPATH or modules.

Following the same idea, I think you should be calling `go version` if you want the feature from Go code. The underlying mechanism is not defined in a stable format that you could implement in a forever-compatible Go package.

**Comment by mrueg** [comment]
@mvdan Thanks for your response. I'm currently implementing a tool that will reconstruct a go.mod file from a given non-stripped go binary, so rsc/goversion works for that case and allows me to extract necessary details.
Parsing the output of `go version -m $binary` is an option as well, but it would be easier to use its internally existing data structure using a function that returns it.

I assume if I want to do and use golang's implementation my only option is extract the package into my repository?
