### ISSUE TITLE
x/build/cmd/gopherbot: remove NeedsDecision on proposals

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31788]
Per @golang/proposal-review, the bot should remove NeedsDecision on proposals. It's redundant and messes with searches.

**Comment by bcmills** [comment]
The `Needs` labels are added by humans. The `Proposal` label is added by bots.

The `NeedsDecision` label indicates that a proposal has been triaged by humans, which is a useful signal for whether the proposal is ready for a more in-depth review by the other humans who own the package(s) in question.

**Comment by bcmills** [comment]
...unless the idea is for the proposal committee to be the ones to loop in the humans? But that seems like it adds needless overhead for the proposal committee and needless delay in getting feedback from owners.

**Comment by ianlancetaylor** [comment]
Every proposal needs a decision.  It doesn't seem to help to add the `NeedsDecision` label to a proposal.

You suggest a possible meaning for `NeedsDecision` on proposals, but in fact the proposal review team doesn't use that label, and doesn't have a need for it.

(For Go 2 proposals, on the other hand, we do use `NeedsDecision`, to mean that the proposal seems ready and we just need to decide whether or not to adopt it.)

**Comment by bcmills** [comment]
The `NeedsDecision` label is more of a cue for folks triaging issues than for the proposal committee: some proposals clearly need more information, or clearly need feedback from specific owners, or are duplicates of existing proposals, so it's useful for folks to have some signal about whether that first-pass check has been completed.

The `Proposal` label does not capture that first-pass check, since Gopherbot applies it automatically based on the issue title.

Currently, the `NeedsDecision` label does, since it is not automatic.

As an alternative, I suppose we could change Goptherbot to stop adding the `Proposal` label. Then that label itself could serve as an indicator of triage status.

**Comment by ianlancetaylor** [comment]
Sounds like we are using `NeedsDecision` for two different unrelated purposes.

**Comment by rsc** [comment]
The triage rotation does not need to triage Proposal issues. It would help the proposal reviewers if the proposals did not say NeedsDecision. @bradfitz says the triage github search shortcut says -label:proposal anyway. 

Can we agree that Proposals can drop the NeedsDecision label automatically?

**Comment by bcmills** [comment]
If y'all really don't want *any* first-level triage on proposals, then I guess it's fine to drop the NeedsDecision label from those issues.

**Comment by rsc** [comment]
Yes, we don't need any first-level triage on proposals. Thanks.
