### ISSUE TITLE
Why interface cannot has method ?

### ISSUE THREAD

**Issue by iamybj** [golang/go#32047]
I am doing a simple web framework that use fasthttp internally.
My custom Handler is an interface, so it should fit the fasthttp.RequestHandler.
<pre>
// Http handler interface
type Handler interface {
	BeforeFilters() []Filter
	Handle(ctx *Context) error
	AfterFilters() []Filter
}

// Fit fasthttp.RequestHandler
func (handler *Handler) fasthttpHandler(ctx *fasthttp.RequestCtx) { //error
	//
}
</pre>
But the interface method cannot be compiled.
What's the solution?

**Comment by ianlancetaylor** [comment]
The language does not permit defining a method for an interface type.  Since the main purpose of methods is to implement interfaces, it doesn't really make sense for an interface type to have a method defined on it; after all, it's already an interface.  I'm not sure what you are trying to do, but perhaps you can just use a function.

Note that you will get better and faster answers in a forum rather than on the issue tracker.  See https://golang.org/wiki/Questions.
