### ISSUE TITLE
Does return func(...)... create new objects every time?

### ISSUE THREAD

**Issue by iamybj** [golang/go#32048]
I am doing a web framework that use fasthttp internally.
My custom Handler is an interface. In order to fit fasthttp.RequestHandler, I wrote a function:
<pre>
// Convert to fasthttp.RequestHandler
func toFasthttpHandler(handler Handler) fasthttp.RequestHandler {
	return func(ctx *fasthttp.RequestCtx) {
...
</pre>
Handler will be called every request come. If there is 100000000 requests, does the return func(...) create 100000000 functions or 100000000 closures or just on function?

**Comment by ianlancetaylor** [comment]
It would be easier to answer your question with a complete example.  It depends on whether the returned function refers to the `handler` parameter.  If it does, then it's likely that each time you call `toFasthttpHandler` it will allocate a closure on the heap.  Exactly what happens will depend on what compiler and version you are using.

You will likely get better answers in a forum rather than the issue tracker.  See https://golang.org/wiki/Questions.
