### ISSUE TITLE
x/tools/cmd/goimports: format is not the same

### ISSUE THREAD

**Issue by tomocy** [golang/go#32165]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes in 1.12.5

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/tomocy/Codes/bin"
GOCACHE="/Users/tomocy/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tomocy/Codes"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/19/1v1v30rd7fn4vzqt6xf_2g580000gn/T/go-build769896193=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When one package is imported in one line
```go
import "error"
```
I imported a package
```go
import (
    "log"
    "error"
)
```
but, I stopped using the package after all and format with goimport.

### What did you expect to see?
Import the first package in one line.
```go
import "error"
```

### What did you see instead?
Import the package with parenthesis.
```go
import (
    "error"
)
```

**Comment by ALTree** [comment]
Thanks for the report.

This is an intentional goimports feature. It was introduced to fix #18051; essentially for two reasons: the fact that it minimizes diff noise when committing, and the fact that switching to the one-line format can misplace comments when there are commented lines between the lines with the packages names in the grouped version, if that is converted to the single-line version.

I'm closing here, since this is WAI.
