### ISSUE TITLE
cmd/go: SUMDB detection from GOPROXY fails when GOPROXY is a file URL

### ISSUE THREAD

**Issue by bcmills** [golang/go#32227]
I believe this is the root cause of the symptom reported in #32216.

`(*modfetch.dbClient).initBase` attempts to derive the `GOSUMDB` setting from the `GOPROXY` setting. `GOPROXY` may be set to a `file://` URL, in which case the call to `web.GetBytes` [here](https://github.com/golang/go/blob/c468ad04177c422534ad1ed4547295935f84743d/src/cmd/go/internal/modfetch/sumdb.go#L164) will fail.

Since the sum database [requires](https://github.com/golang/go/blob/c468ad04177c422534ad1ed4547295935f84743d/src/cmd/go/internal/modfetch/sumdb.go#L82) an HTTPS transport, we should probably default it to either `direct` or `off` if the only `GOPROXY` values are file URLs.

CC @FiloSottile @bradfitz @jayconrod

**Comment by pyjac** [comment]
@bcmills I'm new here, can I send a PR for this?

 base on your suggestion, I believe having a check like this should work 

```go
if strings.HasPrefix(proxyURL, "file://") {
	break
}
```

**Comment by bcmills** [comment]
@pyjac, the behavior here is pretty subtle, so I'd rather have @rsc clarify the intended behavior before we move forward. Thanks!

**Comment by rsc** [comment]
To clarify, it's not trying to derive the GOSUMDB _setting_ so much as the connection transport for getting to it.

I think we do want file:// proxies to be able to provide GOSUMDB files, since the checksum database is (or can be) a static file tree too. But when it does try the file URL, it needs to get a 404 from the sumdb/supported endpoint, so that it can fall back to the next thing it would normally try (probably a direct connection).

So I think we just need to make the checksum fetches use the same access mechanism that the proxy fetches do, so that file:// is implemented during that fetch, and we also need to make sure that the response is a not-found, but that seems like it will work OK, since it is already using errors.Is(err, os.ErrNotExist).

**Comment by rsc** [comment]
Worth remembering to check that <meta> tags can't point at file:/// if you make the general web library handle those.
