### ISSUE TITLE
cmd/compile: use Node.Right rather than Node.RList for OAS2* nodes (cleanup)

### ISSUE THREAD

**Issue by griesemer** [golang/go#32293]
Cleanup suggestion (per e-mail discussion between @griesemer and @mdempsky):

The nodes with ops OAS2FUNC, OAS2RECV, OAS2MAPR, OAS2DOTTYPE, and OASOP, use an RList, but (at least) in the documentation the RHS looks like a single node.

They could be (likely) switched to using the Right field, making that field access slightly more efficient.

**Comment by mdempsky** [comment]
Marking as "help wanted" since this is probably a reasonable task for folks modestly familiar with the Go compiler and wanting to contribute. It should mostly involve:

1. In typecheck.go, finding the places where Op==OAS2 is changed to OAS2FUNC/OAS2RECV/OAS2MAPR/OAS2DOTTYPE, and moving `n.Rlist.First()` to `n.Right` at the same time.
2. Finding all the rest of the compiler code that checks for those OAS2* nodes, and replacing `n.Rlist.First()` or `n.Rlist.SetFirst(x)` with `n.Right` and `n.Right = x`, respectively.
3. Update the documentation in syntax.go to reflect the new Node convention.

Make sure to update esc.go too and test that it works with `-gcflags=all=-newescape=false`, assuming it hasn't been removed yet.

**Comment by Zyqsempai** [comment]
I will take care of this one!

**Comment by Zyqsempai** [comment]
@mdempsky There is a lot of places like that https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/iimport.go#L976 where `r.exprList()` returns list of nodes, how should we assign it to n.Right? Take the first element from `r.exprList()`? Or what?

**Comment by griesemer** [comment]
@Zyqsempai Thanks for volunteering to make this change.

Because this is a very low-priority issue (I filed this mostly as a reminder for myself for a future cleanup), please keep in mind that it may not make a lot of sense for a Go Team member to spend time tracking down a bug you have introduced in your change - there's simply too much higher-priority work to be done. Please do not send a non-working PR, we're not going to fix it for you. Hopefully this makes sense.

That said, in this specific case, the tricky part is to make this change _only_ for nodes with the specified Op values. If the change is made for any other node, arbitrary things might happen. Perhaps you overlooked a case somewhere. I'd go back and manually double-check every single change and corresponding Node Op value.

If you're still stuck, perhaps a community member can help out. It may also be that we overlooked something and this change is more subtle than it looks like.

Thanks.

**Comment by Zyqsempai** [comment]
@griesemer Thanks a lot. Will check everything again.
