### ISSUE TITLE
index.golang.org: document how to obtain list of all modules

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#32312]
A GET of https://index.golang.org/index returns exactly 2000 entries.
There are many entries missing. It would be useful to know how to obtain the entire list.

**Comment by bradfitz** [comment]
Agree more docs would be good. In the meantime, there's a limit parameter:

https://index.golang.org/index?limit=3
```
{"Path":"golang.org/x/text","Version":"v0.3.0","Timestamp":"2019-04-10T12:08:52.997264-07:00"}
{"Path":"golang.org/x/crypto","Version":"v0.0.0-20190404164418-38d8ce5564a5","Timestamp":"2019-04-10T13:30:02.04035-07:00"}
{"Path":"github.com/FiloSottile/mkcert","Version":"v1.3.0","Timestamp":"2019-04-10T13:30:31.325463-07:00"}
```

And there's a since parameter: (note this is scrolling the results above by one line, as this since value is 1 nanosecond past the x/text Timestamp above)

https://index.golang.org/index?limit=3&since=2019-04-10T12:08:52.997265-07:00
```
{"Path":"golang.org/x/crypto","Version":"v0.0.0-20190404164418-38d8ce5564a5","Timestamp":"2019-04-10T13:30:02.04035-07:00"}
{"Path":"github.com/FiloSottile/mkcert","Version":"v1.3.0","Timestamp":"2019-04-10T13:30:31.325463-07:00"}
{"Path":"github.com/DHowett/go-plist","Version":"v0.0.0-20180609054337-500bd5b9081b","Timestamp":"2019-04-10T13:30:36.555706-07:00"}
```

https://index.golang.org/index?limit=3&since=2019-05-28T00:00:00Z
```
{"Path":"golang.org/x/xerrors","Version":"v0.0.0-20190516184347-8115aa61538e","Timestamp":"2019-05-27T17:16:00.182762-07:00"}
{"Path":"github.com/smartystreets/goconvey","Version":"v0.0.0-20190528001852-68dc04aab96a","Timestamp":"2019-05-27T17:23:36.633795-07:00"}
{"Path":"github.com/go-language-server/jsonrpc2","Version":"v0.1.4-0.20190528003553-92c50cd35914","Timestamp":"2019-05-27T17:36:26.812083-07:00"}
```

/cc @hyangah @katiehockman

**Comment by dominikh** [comment]
> note this is scrolling the results above by one line, as this since value is 1 nanosecond past the x/text Timestamp above

Also note that (hopefully) soon `since` won't be inclusive, so you won't have to add a nanosecond to the previous timestamp (/cc @dmitshur)

**Comment by hyangah** [comment]
Agree that it needs documentation.

It currently returns at most 2000 entries sorted by the Timestamp and uses 'since'  as the pagination marker. Users can retrieve the next page using the last entry's Timestamp as the 'since' parameter, and deduplicate the first entries (because the `since` param is inclusive). The Timestamp is the time when the module/version entered our database. I don't think it's guaranteed that they are unique,  strictly speaking. So users who want to avoid dropping entries need to query based on the last entry's Timestamp (assuming that there are no more than ~2k entries with the same timestamp).

**Comment by katiehockman** [comment]
I'll assign the improvements to the documentation at index.golang.org to myself.
Changing the since parameter behavior would be a bigger change, and should be tracked in a different issue.

**Comment by katiehockman** [comment]
The documentation updates to better describe the optional 'since' and 'limit' header params have been checked in and are now live at index.golang.org.
I'm going to close this as resolved, since the main issue has been fixed.
