### ISSUE TITLE
index.golang.org: index.golang.org/index does not return valid JSON

### ISSUE THREAD

**Issue by smswz** [golang/go#32369]
Doing a GET on index.golang.org/index returns something similar to
```
{"Path":"golang.org/x/text","Version":"v0.3.0","Timestamp":"2019-04-10T12:08:52.997264-07:00"}
{"Path":"golang.org/x/crypto","Version":"v0.0.0-20190404164418-38d8ce5564a5","Timestamp":"2019-04-10T13:30:02.04035-07:00"}
{"Path":"github.com/FiloSottile/mkcert","Version":"v1.3.0","Timestamp":"2019-04-10T13:30:31.325463-07:00"}
```
and the headers say that you are returning `application/json`. However, this looks to be JSON lines and not valid JSON. Is returning non-standard JSON the correct approach? I understand the merits of JSONL/NDJSON, but without any indication that it is in this format, it is pretty confusing.

**Comment by heschik** [comment]
Seems that `application/x-ndjson` is the thing for this. TIL.

**Comment by smswz** [comment]
I looked into it. Unfortunately, the only two I've seen are the aforementioned `application/x-ndjson` and `application/jsonl` and they are both non-standard.

**Comment by katiehockman** [comment]
We want to stick with the current output of newline separated json, since it is a valid way of streaming json. But since there isn't a content type that matches this output, we'll just go with application/text for now.
I tried out application/x-ndjson, but as you said, it's non-standard, and had some negative effects when viewing in the browser.

**Comment by smswz** [comment]
Okay, thanks!
