### ISSUE TITLE
runtime: elided panic goroutine stack trace doesn't print "additional frames elided" since go1.8

### ISSUE THREAD

**Issue by maruel** [golang/go#32383]
## Repro

https://play.golang.org/p/zcDltp375Sf
```go
package main

func recurse(i int) {
	if i > 0 {
		recurse(i - 1)
		return
	}
	panic(42)
}

func main() {
	recurse(100)
}
```

Or:
```
$ go get github.com/maruel/panicparse/cmd/panic
$ panic stack_cut_off
```

## Expected

This is the case in go1.7.6:

```
(...)
main.recurse(0x61)
        /home/maruel/go/src/github.com/maruel/panicparse/cmd/panic/main.go:56 +0x33
main.recurse(0x62)
        /home/maruel/go/src/github.com/maruel/panicparse/cmd/panic/main.go:56 +0x33
...additional frames elided...
```

[runtime/traceback.go#L751](https://github.com/golang/go/blob/go1.12.5/src/runtime/traceback.go#L751) is supposed to `print("...additional frames elided...\n")` when the stack trace is more than `_TracebackMaxFrames`, defined as 100 in [runtime/runtime2.go#L786](https://github.com/golang/go/blob/go1.12.5/src/runtime/runtime2.go#L786)

## Actual

It is not effective since go1.8.

```
(...)
main.recurse(0x61)
        /home/maruel/go/src/github.com/maruel/panicparse/cmd/panic/main.go:56 +0x33
main.recurse(0x62)
        /home/maruel/go/src/github.com/maruel/panicparse/cmd/panic/main.go:56 +0x33
```

## Investigation

```bash
cat > ~/test_golang.sh <<EOF
#!/bin/bash
set -eu
cd ~/src/golang/src
./make.bash
go install github.com/maruel/panicparse/cmd/panic
panic stack_cut_off |& grep 'additional frames elided'
EOF
chmod +x ~/test_golang.sh

git bisect start go1.8 go1.7.6
git bisect run ~/test_golang.sh
git bisect reset
```

Found the culprit commit to be f9feaffdf51967bc5cf3c9363db9ddee98c9b3a0 reviewed at https://go-review.googlesource.com/c/go/+/33165/

**Comment by agnivade** [comment]
@ianlancetaylor @rsc

**Comment by maruel** [comment]
While investigating, I realized that stack depth can expand well over 100 (is it due to compile time inlining?). Here's an interesting example: https://play.golang.org/p/lQ_TDHJjyUw

Also I think my "fix" is incorrect. Still investigating.

**Comment by prattmic** [comment]
I took a quick look today.

* We print here: https://cs.opensource.google/go/go/+/master:src/runtime/traceback.go;drc=bf2ef26be3593d24487311576d85ec601185fbf4;bpv=1;bpt=1;l=850
* The max passed to the function controls how many frames we look at: https://cs.opensource.google/go/go/+/master:src/runtime/traceback.go;l=131;drc=bf2ef26be3593d24487311576d85ec601185fbf4;bpv=0;bpt=1
* But the value returned is the number we printed: https://cs.opensource.google/go/go/+/master:src/runtime/traceback.go;l=515;drc=bf2ef26be3593d24487311576d85ec601185fbf4;bpv=0;bpt=1

For this program, after the loop n = 100, nprint = 99. Likely because we skip printing one panic frame at the top?
