### ISSUE TITLE
syscall: CL 178919 breaks use of github.com/kr/pty

### ISSUE THREAD

**Issue by myitcv** [golang/go#32527]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +103b5b6692 Thu May 30 22:02:03 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/myitcv/gostuff/src/github.com/myitcv/govim/cmd/govim/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build470307944=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

[CL 178919](https://go-review.googlesource.com/c/go/+/178919) has broken my test setup with [`govim`](https://github.com/myitcv/govim). 

I'm ever so slightly out of my depth when it comes to understanding what's going on, so I'll simply describe the setup and offer to provide as many further details as necessary (if someone can give me pointers as to how) :smile:!

* I use `github.com/kr/pty` to start an instance of Vim
* The call to `pty.Start` fails with:

```
fork/exec /home/myitcv/usr/vim/bin/vim: inappropriate ioctl for device
```

I haven't yet managed to create a smaller reproduction outside of `govim`, rather I wanted to report the issue first given how close we are to beta1.

cc @ianlancetaylor

**Comment by myitcv** [comment]
Forgot to cc @kr

**Comment by ianlancetaylor** [comment]
When you call `pty.Start`, are you setting the `Stdin`, `Stdout`, and `Stderr` fields?

I don't quite see how github.com/kr/py works today.  It uses `os.OpenFile` to open the tty, but that will mark the file descriptor as close-on-exec.  Maybe it worked before because before CL 178919 we dup'ed the ctty to stdin/stdout/stderr before calling `TIOCSCTTY`, and so the ctty designation carried over.  After the CL we call `TIOCSCTTY` first, and maybe that doesn't survive the later dup'ing.  Or something.

It might help to compare an `strace -f` of your program before and after CL 178919, to see what changed.

It might fix the problem if github.com/kr/pty were changed to use `syscall.Open` rather than `os.OpenFile` for the pty, so that it is not marked close-on-exec.

**Comment by ianlancetaylor** [comment]
CC @gthelen

**Comment by kr** [comment]
I'm happy to help with changes to github.com/kr/pty if necessary, especially if there are steps we can follow to reproduce this.

Also cc @creack.

**Comment by creack** [comment]
Happy to help, however, I cloned and installed 103b5b6692 on linux/amd64 (ubuntu 16.04) and have not been able to reproduce.

I tried vim, bash, emacs, tmux using the sample code form kr/pty readme without a problem.
I tried tried govim, but I think I'm doing something wrong as it didn't start anything in a pty..

Could you provide a more detailed way to reproduce?

Using syscall.Open instead of os.OpenFile could be done as well

**Comment by gthelen** [comment]
I'm also happy to help, but have no problems running creack's vim workload (https://github.com/golang/go/issues/32527#issuecomment-500649457) with golang 103b5b6 on linux/amd64.

**Comment by myitcv** [comment]
Thanks very much for all the offers of help debugging this.

I've not actually managed to create a repro that shows exactly the same symptoms, but I do have a small example that fails pre/post that CL in a slightly different but perhaps related way. That follows at the end of this comment.

In what follows I will use:

* "pre" to refer to a53b46557267492c8f5e6e285c8d4c415183cacf, the commit immediately prior to CL 178919
* "post" to refer to 103b5b66921b351f8db4fc6e83bf147b1a0d7580, the commit that resulted from the merge of CL 178919

I've also tried to keep this issue a bit shorter by putting details in separate repo.

Vim version details for all my tests, attempted repros etc: [`00 - vim version`](https://raw.githubusercontent.com/myitcvscratch/ptyrepro/master/vim.version)

### Original issue

Per @ianlancetaylor I've used `strace -f` on the original problem. This was triggered as part of a test, so I've compiled the test binary and run `strace -f` on that; the issue remains (but I mention that for full disclosure on the setup). 

```
$ go test -c -o test.prog
$ strace -f ./test.prog -test.run TestScripts/scripts/autocmd
```

* [`01 - pre strace -f`](https://raw.githubusercontent.com/myitcvscratch/ptyrepro/master/pre.out)
* [`02 - post strace -f`](https://raw.githubusercontent.com/myitcvscratch/ptyrepro/master/post.out)

In answer to your specific question, @ianlancetaylor :

> When you call pty.Start, are you setting the Stdin, Stdout, and Stderr fields?

No; simply [setting a working directory and environment](https://github.com/myitcv/govim/blob/be409002162bc17fceddcac93455674dfa50d307/testdriver/testdriver.go#L108-L115). 

_Please excuse the code in `testdriver`; it's horrendous and needs a rewrite._

### Small example

The simple example in https://github.com/myitcvscratch/ptyrepro also breaks as a result of CL 178919, but not in the same way. 

Pre:

```
$ go run main.go
```

No output; i.e. no panic.

Post:

```
panic: fork/exec /home/myitcv/usr/vim/bin/vim: operation not permitted

goroutine 1 [running]:
main.main()
        /home/myitcv/dev/ptyrepro/main.go:15 +0xdb
exit status 2
```

Here is the `strace -f` output for both:

* [`01 - pre strace -f`](https://raw.githubusercontent.com/myitcvscratch/ptyrepro/master/pre_simple.out)
* [`02 - post strace -f`](https://raw.githubusercontent.com/myitcvscratch/ptyrepro/master/post_simple.out)

Again, happy to help provide any further details that help to track this down.

**Comment by ianlancetaylor** [comment]
Thanks for the strace listings and the small repro.

When I `go run` your repro, it downloads pty 1.1.4.  That is missing change https://github.com/kr/pty/commit/b6e1bdd4a4f88614e0c6e5e8089c7abed98aae17 which sets the `Ctty` field in `SysProcAttr`.  The effect is that it always sets the controlling terminal to file descriptor 0.  Before CL 178919, that worked for your test case because setting the ctty ran after dup'ing the pty to descriptor 0.  After CL 178919, it fails, because before the dup'ing descriptor 0 is not a pty.

If I change the go.mod file in your small repro to

    require github.com/kr/pty b6e1bdd4a4f88614e0c6e5e8089c7abed98aae17

then your program succeeds.

**Comment by myitcv** [comment]
@ianlancetaylor - thank you for taking the time to look into this, very much appreciated. 

I can confirm that with https://github.com/kr/pty/commit/b6e1bdd4a4f88614e0c6e5e8089c7abed98aae17 both my repro and the original issue are resolved.

I will close this issue and open an issue in https://github.com/kr/pty about cutting a new release.
