### ISSUE TITLE
cmd/go: go get -u fails with local-only replacements

### ISSUE THREAD

**Issue by kenichi-fukushima** [golang/go#32567]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
Run `go get -u` in a module with `replace` with a local module.

You can reproduce the problem by checking out this repository and  run the command in `depending` directory.
https://github.com/kenichi-fukushima/go-local-modules

#### What did you expect to see?
The command finishes successfully.

#### What did you see instead?
The command failed with this message.
```
go get: upgrading example.com/depended@v0.0.0: unrecognized import path "example.com/depended" (parse https://example.com/depended?go-get=1: no go-import meta tags ())
```

#### System details

I got this error with 12.2/12.5 on Linux too.

```
go version go1.12.6 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/keni/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/keni/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/keni/Downloads/go-local-modules-master/depending/go.mod"
GOROOT/bin/go version: go version go1.12.6 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.6
uname -v: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
lldb --version: lldb-1000.0.38.2
  Swift-4.2
```

**Comment by bcmills** [comment]
Coincidentally, @jayconrod and I also noticed that this is broken in the context of https://golang.org/cl/180337.

Any fix is probably too invasive for 1.13, but we're planning to overhaul replacements in general for 1.14.

**Comment by pablote** [comment]
Hi, any fix or workaround for this? Testing this out with go 1.14.1 on darwin. I was usually able to update all dependencies with `go get -u ./...`, but since we moved to a monorepo and using replace in go.mod files this is now failing, it seems to be trying to fetch the replaced dependencies repo online. 

On the other hand, updating specific dependencies `go get some-dep@someversion` works.

**Comment by pablote** [comment]
Not the best workaround in the world, but I just found that if replaced dependencies are temporarily removed from go.mod, then `go get -u ./...` actually updates the rest of the dependencies. It still prints some errors on the console, but it works.

**Comment by microo8** [comment]
All of the private modules I use are just in a fictional `mycompany.com/somemodule`.

So I tried to add the fictional domain to `GOPRIVATE` with: 
`go env -w GOPRIVATE=mycompany.com`

and then run `go get -u all`
But it fails with `go get all: unrecognized import path "mycompany.com/common/utils": reading https://mycompany.com/common/utils?go-get=1: 404 Not Found`

Is it possible, that `go get -u all` ignores the environment variables? (`GOPRIVATE`,`GONOPROXY`,`GONOSUMDB`)

**Comment by jayconrod** [comment]
@microo8 This issue is specifically related to local replacements. It sounds like you're running into a different problem with private modules so please open a new issue instead.

(`go get` does not ignore those environment variables. Please make sure that there is a server at that URL resolving module paths to repository URLs *or* make sure module paths end with `.git`.)

**Comment by microo8** [comment]
I have the private modules replaced with a local module

```
module mycompany.com/clientname/server

go 1.14

require (
    github.com/lib/pq v1.7.0
    github.com/99designs/gqlgen v0.11.3
    github.com/vektah/gqlparser/v2 v2.0.1
    golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
    mycompany.com/clientname/models v0.0.0-00010101000000-000000000000
    mycompany.com/common/utils v0.0.0-00010101000000-000000000000
)

replace mycompany.com/common/utils => ../../common/utils

replace mycompany.com/clientname/models => ../models
```

and that doesn't work. the mycompany.com is just fictional, there isn't a server on the url

`go get -u all` finds the new versions of the github.com modules and then fails with `go get all: unrecognized import path "mycompany.com/common/utils": reading https://mycompany.com/common/utils?go-get=1: 404 Not Found` an doesn't update go.mod

**Comment by jayconrod** [comment]
@microo8 Thanks for that example. It does seem to be the same issue described here.

The error is reported because the `go` command is attempting to find a VCS repository for a module path (`mycompany.com/common/utils`). The module path is replaced with a local directory, so it's a bug that it's doing that.

**Comment by microo8** [comment]
So I report the bug in a new issue. Thanks

**Comment by bcmills** [comment]
I believe this is fixed as of https://golang.org/cl/258220.

@kenichi-fukushima, please try a `go` command built from head (either by following the instructions at https://golang.org/doc/install/source or using [`golang.org/dl/gotip`](https://pkg.go.dev/golang.org/dl/gotip)) and let us know if it still isn't working for you.
