### ISSUE TITLE
cmd/compile: replace indirect call with direct call when target is known after inlining

### ISSUE THREAD

**Issue by marigonzes** [golang/go#32577]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel +ef84fa0 Mon Jun 10 23:23:39 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
I compiled the following functions: https://godbolt.org/z/dHW0pK.
```go
func f(x int) int {
    return x
}

func getf() func (int) int {
    return f
}

func applyf() int {
    return getf()(2)
}
```

### What did you expect to see?
I expected the last function not to contain any unnecessary instructions or, in a perfect world, that it would be compiled to a simple return.

### What did you see instead?
Instead, there was an ineffective instruction on line 37 of the assembly code generated in the website mentioned above.
```asm
leaq    "".f·f(SB), DX
```

PS: Thanks to @mundaym for helping me figure this out.

**Comment by randall77** [comment]
That instruction loads a pointer to the closure into a register for the call.
That is required for the calling convention.
It's not necessary in this case because the closure doesn't close over any variables. But if we know that it doesn't close over any variables, we likely know the exact target and we might as well replace the indirect call with a direct call (which could then inline, which would then match your perfect world).

**Comment by mundaym** [comment]
I think it would be fairly straightforward to convert a `ClosureCall` into a `StaticCall` in SSA when the target is known (perhaps taking a similar approach to the `InterCall` optimization @philhofer added in [CL 38139](https://golang.org/cl/38139)). As far as I know going from a direct call to an inlined function isn't currently possible in the SSA backend though - and inlining is probably more valuable than a `ClosureCall` to `StaticCall` optimization in this scenario.

**Comment by marigonzes** [comment]
No longer reproduces
