### ISSUE TITLE
x/build/cmd/coordinator: fails 'go test' vet check at head

### ISSUE THREAD

**Issue by bcmills** [golang/go#32626]
This causes x/build CLs to fail TryBots. (Why don't we have a builder for x/build?)

https://storage.googleapis.com/go-build-log/6a9b22ce/linux-amd64_3c1e5e69.log

```
# golang.org/x/build/cmd/coordinator
cmd/coordinator/status.go:204:23: Sprintf format %s reads arg #1, but call has 0 args
FAIL	golang.org/x/build/cmd/coordinator [build failed]
```

CC @dmitshur, since I think he's planning to make some changes in `cmd/coordinator` anyway.

**Comment by dmitshur** [comment]
This is already resolved via [CL 182017](https://golang.org/cl/182017). (Existing CLs may need to be rebased to pick up the change.)

> (Why don't we have a builder for x/build?)

I thought we had an issue about it, but I couldn't find one. So I added it to #30640 instead.

Historically, x/build did not have even trybots, that was a relatively recent addition. It wasn't possible before because of third-party packages in x/build, but that's no longer a problem (in module mode, which x/build uses for its trybots).
