### ISSUE TITLE
x/build: misc-compile TryBots are too slow

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#32632]
I am waiting for try-bots on https://go-review.googlesource.com/c/go/+/177959, and generally try-bots are finished withing about 5 minutes, but misc-compile-mips takes more than 11 minutes from https://farmer.golang.org/try?commit=fa91b668
```

• android-amd64-emu | pass
-- | --
• freebsd-amd64-12_0 | pass
• js-wasm | pass
• linux-386 | pass
• linux-amd64 | pass
• linux-amd64-race | pass
• misc-compile-darwin | pass
• misc-compile-freebsd | pass
• misc-compile-linuxarm | pass
• misc-compile-mips | running 11m3s
• misc-compile-nacl | pass
• misc-compile-netbsd | pass
• misc-compile-openbsd | pass
• misc-compile-other | pass
• misc-compile-plan9 | pass
• misc-compile-ppc | pass
• misc-compile-solaris | pass
• nacl-amd64p32 | pass
• openbsd-amd64-64 | pass
• windows-386-2008 | pass
• windows-amd64-2016 | pass
```

Every bot is finished, except misc-compile-mips. Maybe misc-compile-mips should not be part of try-bots, if it is soo slow.

Alex

**Comment by bcmills** [comment]
On https://farmer.golang.org/try?commit=c29ef957, I'm seeing multiple `misc-compile` TryBots (in this case, `mips`, `netbsd`, `openbsd`) taking upwards of 10m, when all of the real (sharded test) builders are already long done.

CC @dmitshur @toothrot @cagedmantis

**Comment by bcmills** [comment]
On https://farmer.golang.org/try?commit=5b2140c8, I'm again seeing `misc-compile` TryBots taking upwards of 10m.

**Comment by dmitshur** [comment]
I too have observed this:

<img src="https://user-images.githubusercontent.com/1924134/108784909-5f2ae180-753e-11eb-88e6-f93311e9c182.png" width=303px>

When these trybots take the longest, they become a bottleneck for overall TryBot completion speed (e.g., #17104).

The "misc-compile" trybots do much less work than normal trybots: they check only that compilation is successful, but don't execute tests. They're generally split by OS, matching all architectures available:

https://github.com/golang/build/blob/f539cd3e8d00b786b2c500b824a0d69d196ea3c6/dashboard/builders.go#L1600-L1609

Those architectures are currently tested sequentially. So one possible explanation is if newly added architectures start to get matched, and there become too many for sequential testing to be viable.

If that's the case, we can fix this by adjusting the split to avoid putting too much work into any single trybot.

**Comment by dmitshur** [comment]
I observed a case where `misc-compile-openbsd` was the slowest run:

<img src="https://user-images.githubusercontent.com/1924134/109840518-34afe700-7c16-11eb-8605-cb96423dd1f1.png" width=305px>

Looking at its logs confirmed it was building as many as 5 different architectures, all sequentially:

```
### Building openbsd-386

### Building openbsd-amd64

### Building openbsd-arm

### Building openbsd-arm64

### Building openbsd-mips64
```

So the root problem here is pretty clear: we need to parallelize the workload better for OSes that have many architectures.

**Comment by FiloSottile** [comment]
I am looking at a TryBot run where misc-compile takes longer than 15 minutes, and longer than linux-amd64-longtest.

![image](https://user-images.githubusercontent.com/1225294/115288626-a6d58000-a11f-11eb-92a9-dd6e103678d7.png)

If there is an easy fix, even if hacky, I would recommend applying it, because this is adding significant latency to everyone's development cycle.

TryBots are supposed to take at most 5 minutes, IIRC, so even running two architectures in a row would probably be too slow. (15min / 4 * 2 = 7.5min)

**Comment by dmitshur** [comment]
With the work done to migrate x/build to OpenCensus in [CL 303669](https://golang.org/cl/303669), we're closer to starting to measure and track TryBot completion time, which has been a blocker for making progress on #17104.

However, the problem here is quite clear and a simple fix is available, so I've sent [CL 313210](https://golang.org/cl/313210) that implements the suggestion in https://github.com/golang/go/issues/32632#issuecomment-789870534. Our updated target time for TryBot completion time is 10 minutes (see subject of issue #17104), so going with at most 2 ports per misc-compile TryBot should be a good compromise until we can measure and find something that works even better.
