### ISSUE TITLE
runtime: struct MemStats in go 1.9.3 and go 1.11.5

### ISSUE THREAD

**Issue by chgitcrazy** [golang/go#32678]
When I use go 1.9.3 , I call the Sys field of the Struct MemStats from package 'runtime' , the result is about 10M , But when I upgrade to go 1.11.5, I call the same api , the result is about 70M. By reading the api source , I couldn't find any difference ,hope for explanation .

**Comment by ianlancetaylor** [comment]
CC @aclements @mknyszek

**Comment by mknyszek** [comment]
`Sys` represents the total amount of virtual memory used. I don't know all the details of what changed between go 1.9.3 and go 1.11.5, but if `Sys` goes up it should generally be regarded as a non-issue, since it doesn't generally reflect the memory actually counted against your process by the operating system. That is, `Sys` is not a measure of how much physical memory your application is using, just how much memory has been "mapped" or reserved. For example, today (Go 1.12, 1.13, and I believe true for Go 1.11 as well), we always map in 64 MiB of memory for use on many platforms (e.g. `linux/amd64`). That's likely where most of the reported 70 MB is coming from.

**Comment by chgitcrazy** [comment]
> `Sys` represents the total amount of virtual memory used. I don't know all the details of what changed between go 1.9.3 and go 1.11.5, but if `Sys` goes up it should generally be regarded as a non-issue, since it doesn't generally reflect the memory actually counted against your process by the operating system. That is, `Sys` is not a measure of how much physical memory your application is using, just how much memory has been "mapped" or reserved. For example, today (Go 1.12, 1.13, and I believe true for Go 1.11 as well), we always map in 64 MiB of memory for use on many platforms (e.g. `linux/amd64`). That's likely where most of the reported 70 MB is coming from.

Thank you. I will look for new method to calculate the physical memory.
