### ISSUE TITLE
Feature request: text/css magic bytes detection for net/http

### ISSUE THREAD

**Issue by teran-mckinney** [golang/go#32732]
This may be a non-starter as CSS may not have enough useful "magic bytes", but in net/http we can only detect CSS files based on extension and not the file's contents.

In my (unusual) case, I have the files stores as hex hashes with no extensions and am relying on the magic byte detection.

Maybe there's a way to do this, so I thought I'd open this up and get it out there.

This is applicable to Go 1.12 and I imagine earlier.

**Comment by agnivade** [comment]
As far as I am aware, there is no way to do this because css is just a text file.

In any case, for MIME sniffing, we follow the https://mimesniff.spec.whatwg.org/ spec. So if there is at all a way, it has to be published there first. I would request you to file an issue at https://github.com/whatwg/mimesniff/ if you want something like this to be investigated.

I will go ahead and close this since there is nothing for us to do here. If the mimesniff spec is updated, then we can go ahead and add whatever new logic is required.

**Comment by teran-mckinney** [comment]
Gotcha, thank you! That sounds good.
