### ISSUE TITLE
doc: the Go 1.13 release notes don't mention the new “%w” verb in fmt

### ISSUE THREAD

**Issue by ainar-g** [golang/go#32914]
[A user](https://www.reddit.com/r/golang/comments/c8at5l/go_113_draft_release_notes/esmzohy/) on Reddit has noticed that the Go 1.13 release notes don't seem to mention the `%w` verb for `fmt.Errorf`.

**Comment by bcmills** [comment]
@neild, @mpvl, @jba: any suggested phrasing for the release note?

**Comment by jba** [comment]
Under `fmt`:

> The `Errorf` function has a new verb, `%w`, whose operand must be an error. The error returned from `Errorf` will wrap the operand of `%w`, so that calling `Unwrap` will return it.

**Comment by neild** [comment]
How about:

> The Errorf function has a new verb, %w, whose operand must be an error. The error returned from Errorf will have an Unwrap method which returns the operand of %w.

(You can "wrap" an error without having an Unwrap method.)

**Comment by rasky** [comment]
As a beginner in this new error handling structure, I find jba’s phrasing much clearer.

Neild’s phrasing is confusing because people not exposed to these new APIs will not immediately understand the implications of “having a Unwrap method”. On the other hand, saying that the new error will wrap the previous one is much clearer, and the following sentence even explains what’s the goal of the Unwrap method
