### ISSUE TITLE
LINQ in golang as part of standart library

### ISSUE THREAD

**Issue by Hedgehogues** [golang/go#32926]
### What version of Go are you using (`go version`)?

go1.12

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?
Ubuntu18.04

### What did you do?
I have a question about [linq](https://en.wikipedia.org/wiki/Language_Integrated_Query). Why is golang still not in the standard of this wonderful thing. All that I have heard so far on this technology from gophers is that it is not goffer. Unfortunately, this argument fades when you need to make a couple of groupings, and then another couple of projections. As a result, 3-4 lines are transformed 3-4 screens. In my opinion the choice is obvious. Yes, there are problems. For example, to implement LINQ, you will most likely need to reflect, which will lead to a decrease in performance. But at the same time, we should not forget that with the same success, we can say that the reflector itself also leads to the fact that productivity sinks. So let's give it up. Of course, nobody will do that. The question is where to use this or that technology correctly.

By the way, there is an analogue of reflect. This is static code generation. For example, [some](https://github.com/json-iterator/go) [non-standard](https://github.com/mailru/easyjson) packages are implemented in golang for working with json.

For acquaintance with LINQ technology in go, I provide [link](https://medium.com/wesovilabs/koazee-vs-go-funk-vs-go-linq-caf8ef18584e).

**Comment by bcmills** [comment]
See https://golang.org/doc/faq#x_in_std.

This issue in its current form does not have enough detail to be a [proposal](https://golang.org/s/proposal-process).

If you want to describe a general area for improvement, please add an [experience report](https://golang.org/wiki/ExperienceReports) instead.

Otherwise, please describe the specific changes you would like to see, including the motivation or background (including a compelling reason why the API must be in the standard library instead of a third-party module), specific API signatures, and concrete examples (ideally drawn from experience reports).
