### ISSUE TITLE
x/sys/windows/registry: the system cannot find the file specified

### ISSUE THREAD

**Issue by Dontmindmes** [golang/go#32965]
```go
func main() {
	path := fmt.Sprintf("C:\\Test\\test\\test.exe")

	key, _, err := registry.CreateKey(registry.CURRENT_USER, "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", registry.ALL_ACCESS)
	if err != nil {
		fmt.Println(err)
	}
	defer key.Close()

	err = key.SetStringValue("ProjectTest", path)
	if err != nil {
		fmt.Println(err)
	}

	err = registry.DeleteKey(key, "ProjectTest")
	if err != nil {
		fmt.Println(err)
	}

}
```

When delete key is ran it throws the error The system cannot find the file specified.

**Comment by mvdan** [comment]
Why is this a Go bug? This is most likely an issue in your code, or in the "registry" library you're using. This issue tracker is only for bugs in Go itself.

**Comment by kardianos** [comment]
@mvdan The issue is vague, but it is most likely using `https://godoc.org/golang.org/x/sys/windows/registry` so this is the correct issue tracker.

@Dontmindmes I would recommend you do the following to your code: In the "if err != nil {" handler, don't call fmt.Println, call `log.Fatalf("failed to delete key: %v", err)`

There is very likely some bug in your code.
