### ISSUE TITLE
wiki: restrict access permissions for the repository wikis

### ISSUE THREAD

**Issue by drenel18** [golang/go#32960]
https://help.github.com/en/articles/changing-access-permissions-for-wikis 

seems the wiki page is editable for anyone and there will be some interfering message every now and then. such as this one

![image](https://user-images.githubusercontent.com/41498639/60753268-4042a900-a002-11e9-8b29-3d5020d030db.png)

what about restrict the access permissions for the repository's wikis

@rakyll @jbuberel @natefinch seems you have discussed it before in this issue https://github.com/golang/go/issues/13226

**Comment by ALTree** [comment]
We already have a place with "official" docs and restricted access: the golang.org website. The point of the wiki being open is to have a place where non-project-members are allowed to freely add documents/links and share knowledge. It's still a curated archive (a few Go organization members are subscribed to wiki changes and usually bad edits are noticed and reverted quickly), but more open than a place where every change needs to be approved.

Since github wikis don't allow PRs, if we restrict access we'll have to take changes suggestions on the issue tracker, and a project member will have to apply the change (no PR means that I can't approve and commit a change by pressing a button: I have to manually edit the page to apply the suggested diff). It's not very convenient.

**Comment by ianlancetaylor** [comment]
I agree.  There is nothing to do here.
