### ISSUE TITLE
net: document that OpError.Err field must be non-nil

### ISSUE THREAD

**Issue by dunjut** [golang/go#33007]
In one of my unit tests, I passed `new(net.OpError)` to the tested function and that function logs the error and does some recovery logic (like re-connect).

Logging such err calls `*OpError`'s `Error()` method, which panics because we [didn't check the Err field](https://github.com/golang/go/blob/master/src/net/net.go#L453-L474).

Though in most cases we won't get an OpError like this in real scenarios, I suggest maybe checking on Err field still gives better preciseness?

**Comment by dmitshur** [comment]
Thanks for the report.

I see that the case of `*net.OpError` being nil is currently supported:

```Go
func (e *OpError) Error() string {
	if e == nil {
		return "<nil>"
	}
	[...]
}
```

But `*net.OpError` being non-nil with a nil `Err` field is not (since it panics).

I'm going to move this issue to the needs decision state.

The decision is whether `*net.OpError` should support users creating it with the `Err` field set to `nil`, or if such use is considered invalid and should not be supported.

If it should be supported, then it should check if `Err` is non-nil before calling `Err.Error()` (to avoid the panic).

If it shouldn't be supported, perhaps we can make the documentation a little more explicit about that:

```diff
 // OpError is the error type usually returned by functions in the net
 // package. It describes the operation, network type, and address of
 // an error.
 type OpError struct {
 	[...]

 	// Err is the error that occurred during the operation.
+	// It must be non-nil.
 	Err error
 }
```

I would argue that it shouldn't be supported, because supporting non-nil `*net.OpError` with a nil `Err` field does not make sense and it's not clear what it would represent. If there was network error, then `OpError.Err` should be non-nil. If there wasn't an error, there shouldn't be a `*net.OpError` type wrapping it.

As far as I can tell, this can only happen if users create `*net.OpError` themselves, and none of the functions in `net` package actually return a `*net.OpError` with nil `Err` field.

/cc @mikioh @ianlancetaylor per [owners](https://dev.golang.org/owners).

**Comment by dmitshur** [comment]
The `if e == nil {` check was added by @adg in [CL 1848049](https://github.com/golang/go/commit/fc4ba1546c787a99fbcd037649575c29728655b4), so I'll /cc him in case he has opinions on this issue.

**Comment by ianlancetaylor** [comment]
The whole point of `OpError` is add details to a lower-level error.  It is meaningless to have a `net.OpError` with an `Err` field that is `nil`.  Let's just document that fact and move on.

**Comment by dunjut** [comment]
Thanks for quick responding!

**Comment by networkimprov** [comment]
@dunjut the issue should remain open until the CL is pushed and Gopherbot closes it.

**Comment by dmitshur** [comment]
Fixed by [CL 187677](https://golang.org/cl/187677).
