### ISSUE TITLE
Segmentation violation / unexpected fault address in runtime

### ISSUE THREAD

**Issue by Varunram** [golang/go#33047]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
This is the latest release

### What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
```

Expected output: byte array / map[int][]byte should return from function / pointer deallocation should work

Output:
```
unexpected fault address 0x165649f
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x165649f pc=0x109ecee]
```

Proof of Concept:
https://gist.github.com/Varunram/4dd7af00be21e018906e1fb64318aec8

Note to reviewers: Since I don't know under which category this bug falls under, please change the issue title, thanks!

**Comment by agnivade** [comment]
There are 2 separate issues in your code-

1. In `b := tx.Bucket(bucketName)`, it returns nil if bucket does not exist. So that is the cause of your first segfault.

2. Now to the real issue, see the documentation of (*bucket).Get - https://godoc.org/github.com/boltdb/bolt#Bucket.Get

>  The returned value is only valid for the life of the transaction.

So the underlying slice is cleared when the tx finishes. You need to fix it by initializing arr and then copying to it.

```
if arr == nil {
	arr = make([]byte, len(x))
}
copy(arr, x)
```
instead of `arr = x`

I will go ahead and close this since this is working as intended and not an issue with Go.

**Comment by Varunram** [comment]
@agnivade The bucket creation bug was on me - I created the bucket inside the test function, so that was why it returned an error. But your fix regarding the slice still stands. (ie you could copy the slice onto the map and it should work fine). Thanks for the response!
