### ISSUE TITLE
runtime: support for HiSillicon Hi3519 V100 Architecture

### ISSUE THREAD

**Issue by mms-** [golang/go#33052]
The HiSillicon Hi3519 V100 is based on ARM but not standard arm, it does use the Cortex-A53 CPU. Possible / hard to add suport for this arch?

It does seem to have fairly wide use.

More info : http://www.hisilicon.com/-/media/Hisilicon/pdf/Surveillance_mobilecam/Hi3519AV100.pdf

**Comment by ianlancetaylor** [comment]
What would have to change in Go in order to add support for this?

Go generally doesn't care about anything other than the CPU, so if it uses a standard ARM CPU what is there to do?

**Comment by mms-** [comment]
That is what I thought. Hisilicon has their own modifications to Standar Library, Linux Kernel, cross compile toolchain, not sure what else, this matters not for GO?

**Comment by ianlancetaylor** [comment]
Changes to the standard library and cross-compiler toolchain are almost certainly irrelevant to Go.  Changes to the kernel could possibly matter, but only if they changed the system call interface which is extremely unlikely.  So I doubt we need to do anything.  Of course please let us know if you find out otherwise.
