### ISSUE TITLE
cmd/go: cache conflict with compiler experiment flags

### ISSUE THREAD

**Issue by dsnet** [golang/go#33091]
This is a re-issue of #26883, which was fixed and then broken again.

There seems to be cache conflict where the compiler experiment is not part of the hash.

Steps to reproduce:
```
# Download the Go toolchain.
mkdir /tmp/cache-conflict
export GOCACHE=/tmp/cache-conflict/cache # clean cache for reproduction purposes
(cd /tmp/cache-conflict/ && curl -s -L https://dl.google.com/go/go1.12.7.src.tar.gz | tar -zxf -)

# Build the Go toolchain normally and use that to build some random target.
(cd /tmp/cache-conflict/go/src && ./make.bash)
/tmp/cache-conflict/go/bin/go build -race archive/tar

# Build the Go toolchain with fieldtracking support and use that to build the same target again.
(cd /tmp/cache-conflict/go/src && GOEXPERIMENT=fieldtrack ./make.bash)
/tmp/cache-conflict/go/bin/go build -race archive/tar
```

The last command fails with:
```
# runtime
/tmp/cache-conflict/go/src/runtime/alg.go:8:2: import /tmp/cache-conflict/cache/28/2829dcccd09b7c1ac1694d626da6e06a28de4470a18c47b518bc0236aa533c48-d: object is [darwin amd64 go1.12.7 X:framepointer
] expected [darwin amd64 go1.12.7 X:fieldtrack,framepointer
]
```

\cc @rsc @ianlancetaylor

**Comment by jayconrod** [comment]
It looks like the most recent change here was [CL 149338](https://go-review.googlesource.com/c/go/+/149338). The go command invokes the compiler with `-V=full` to get the version. For a released version, the output looks like:

```
compile version go1.13beta1 X:framepointer
```

For a released version, the Go command only includes the version in the tool ID. It should include the version and everything after.

For a development version, it will include the content ID (stamped SHA-256) of the binary, so that shouldn't be a problem.
