### ISSUE TITLE
cmd/gofmt: rewrite 'a -> a' transforms 'default:' into 'case :'

### ISSUE THREAD

**Issue by rillig** [golang/go#33103]
### What version of Go are you using (`go version`)?

go version go1.13beta1 windows/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```go
package main

func main() {
	func() {
		switch {
		default: // This is changed to `case :`.
		}
	}()
}
```

```shell
gofmt -r 'a->a' -d .
```

### What did you expect to see?

After rewriting, the code still compiles.

### What did you see instead?

The `default:` is rewritten to `case :`, which is syntactically invalid.
This only happens inside a function literal, but not in main itself.

**Comment by dmitshur** [comment]
Thanks for the report.

I checked, this affects Go 1.12.7 as well as Go 1.10.5, so it's not a new regression in Go 1.13 beta 1.

Given this and the other 2 issues you reported (#33104, #33105), it seems there are some bugs in the rewrite rules when doing an identity replacement (`a -> a`). This issue doesn't come up when doing something else like `(a) -> a`, but that's because `default:` doesn't match `(a)`.

@rillig Have you seen this issue come up in more practical replace rules other than the no-op `a -> a` replacement, or are you reporting this just because it's a valid problem you discovered even though it's unlikely to come up in real-world usage?

I checked https://goissues.org/cmd/gofmt and it doesn't seem that this was reported in the past, so thanks again.

/cc @griesemer

**Comment by rillig** [comment]
@dmitshur The reason I tried out the `a->a` transformation was that gofmt is known to sometimes discard comments and add additional empty lines, which makes it an unreliable tool that needs manual inspection afterwards. I experienced this myself [when I did a large code transformation](https://github.com/rillig/pkglint/commit/349e40f8292d407d322b2121ca886df6ab0fbfc8).

To make sure that gofmt doesn't damage my code, my idea was to first try the transformation by essentially doing nothing, before actually transforming something. So instead of running `gofmt -r 'call(a, b, c) -> call(b)'` directly, I would first run `gofmt -r 'call(a, b, c) -> call(a, b, c)'` to see whether anything is damaged.

The simplest such call is `gofmt -r 'a->a'`, therefore I used that for playing around with gofmt. And since that command found so many inconsistencies, I thought I'd better report them immediately instead of letting gofmt break a whole lot of real life code.
