### ISSUE TITLE
x/website: html end tag missing on golang.org/dl

### ISSUE THREAD

**Issue by tsaarni** [golang/go#33126]
### What did you do?

Download https://golang.org/dl/ and parse it with `gopkg.in/xmlpath.v1.ParseHTML`.

### What did you expect to see?

Parsing should succeed.

### What did you see instead?

Error `XML syntax error on line 11670: unexpected EOF`

The reason seems to be that the web page does not have `</html>` end tag which  `gopkg.in/xmlpath.v1.ParseHTML` is expecting.

This breaks [godeb](https://github.com/niemeyer/godeb/) tool, see issue https://github.com/niemeyer/godeb/issues/44. Workaround is to update parser to `gopkg.in/xmlpath.v2.ParseHTML` which is more forgiving.

**Comment by andybons** [comment]
Thanks for the issue.

HTML5 does not require all tags be closed. The `<html>` tag falls into that category.

There is a JSON API that should be used instead of parsing the HTML (which is brittle and prone to change). https://golang.org/dl/?mode=json[&include=all]

Closing since no change is needed on our side (please use the JSON API or a parser that is more compatible with HTML5).
