### ISSUE TITLE
cmd/go: print information about version changes

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#33284]
Currently, the go command is quite chatty when it downloads and extracts module data, but it doesn't print the information that I really want to see - how resolved versions have changed.

For example, if I run `go get $module`, it may upgrade the version of the module, but it doesn't tell me what version it ended up with, or that other dependencies have changed version as a result.
Running `go get $module@$version` can downgrade dependencies too, which is silent and might break expectations of available features.

It would be great if the go command could show some information whenever the resolved module version has changed.

@bcmills @jayconrod

**Comment by bcmills** [comment]
We should do this in conjunction with the fix for #26152. We can prune down the fetch-spam for modules already in the build list, and add logging for changes to that list.

**Comment by bcmills** [comment]
@rogpeppe, I think this is resolved. Once the tree is a bit less unstable, please try out the new log statements and let us know if we've missed anything.

**Comment by bcmills** [comment]
Hmm, there is one more source of version changes that we should probably log.

If the `go.mod` file specifies some version explicitly, and we are forced to upgrade that version due to a requirement found in some transitive dependency already present in the `go.mod` file, we should give a log line indicating the upgraded version and the transitive dependency that forces it.

**Comment by bcmills** [comment]
#37764 has another case: when the user asks `go get` to downgrade an explicit dependency, we should log other dependencies that were downgraded or removed as a side-effect.

**Comment by jayconrod** [comment]
cc @matloob
