### ISSUE TITLE
cmd/compile: race detector prints mis-leading stack trace

### ISSUE THREAD

**Issue by dsnet** [golang/go#33309]
(discovered while debugging golang/protobuf#838)

Consider the following `main.go`:
```go
package main

import (
	"sync"

	// github.com/golang/protobuf@v1.3.2
	"github.com/golang/protobuf/jsonpb"
	"github.com/golang/protobuf/proto"

	descriptorpb "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

func main() {
	obj := &descriptorpb.FileDescriptorProto{
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String("path/to/my/package"),
		},
	}

	wg := &sync.WaitGroup{}
	defer wg.Wait()

	wg.Add(1)
	go func() {
		defer wg.Done()
		proto.Marshal(obj)
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		(&jsonpb.Marshaler{}).MarshalToString(obj)
	}()
}
```

When running `go run -race main.go`, I see (-go1.12 +go1.11):
```diff
 ==================
 WARNING: DATA RACE
 Read at 0x000000000000 by goroutine 7:
   reflect.typedmemmove()
       /usr/local/go/src/runtime/mbarrier.go:177
   reflect.packEface()
       /usr/local/go/src/reflect/value.go:119
   reflect.valueInterface()
-      /usr/local/go/src/reflect/value.go:1009
+      /usr/local/go/src/reflect/value.go:978
+  reflect.Value.Interface()
+      /usr/local/go/src/reflect/value.go:948
   github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue()
-      /usr/local/go/src/reflect/value.go:979
+      /usr/local/protobuf-golang/jsonpb/jsonpb.go:534
   github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField()
       /usr/local/protobuf-golang/jsonpb/jsonpb.go:488
   github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject()
       /usr/local/protobuf-golang/jsonpb/jsonpb.go:346
   github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal()
       /usr/local/protobuf-golang/jsonpb/jsonpb.go:139
   github.com/golang/protobuf/jsonpb.(*Marshaler).MarshalToString()
       /usr/local/protobuf-golang/jsonpb/jsonpb.go:145
   main.main.func2()
       /Users/rawr/blah/test.go:31

 Previous write at 0x000000000000 by goroutine 6:
   sync/atomic.StoreInt32()
       /usr/local/go/src/runtime/race_amd64.s:229
   github.com/golang/protobuf/proto.(*marshalInfo).size()
       /usr/local/protobuf-golang/proto/table_marshal.go:203
   github.com/golang/protobuf/proto.makeMessageMarshaler.func1()
       /usr/local/protobuf-golang/proto/table_marshal.go:2223
   github.com/golang/protobuf/proto.(*marshalInfo).size()
       /usr/local/protobuf-golang/proto/table_marshal.go:183
   github.com/golang/protobuf/proto.(*InternalMessageInfo).Size()
       /usr/local/protobuf-golang/proto/table_marshal.go:125
   github.com/golang/protobuf/protoc-gen-go/descriptor.(*FileDescriptorProto).XXX_Size()
       /usr/local/protobuf-golang/protoc-gen-go/descriptor/descriptor.pb.go:435
   github.com/golang/protobuf/proto.Marshal()
       /usr/local/protobuf-golang/proto/table_marshal.go:2713
   main.main.func1()
       /Users/rawr/blah/test.go:25

 Goroutine 7 (running) created at:
   main.main()
       /Users/rawr/blah/test.go:29

 Goroutine 6 (finished) created at:
   main.main()
       /Users/rawr/blah/test.go:23
 ==================
```

The interesting line is `/usr/local/protobuf-golang/jsonpb/jsonpb.go:534`, which is missing in the stack trace on Go1.12, presumably because of mid-stack inlining.

**Comment by agnivade** [comment]
@randall77 @dvyukov

**Comment by dvyukov** [comment]
To fix this one would need to extend the interface between tsan and Go runtime to be able to pass multiple frames. The tsan runtime supported multiple frames per PC from day one, so it's just a matter of extending the interface here:
https://github.com/llvm-mirror/compiler-rt/blob/master/lib/tsan/go/tsan_go.cpp#L56-L71

Updating the syso files may be a bit challenging. We don't do this regularly, so some things may get rotten. Not sure if racebuild is working today.

**Comment by randall77** [comment]
CLs out for the fixes in both tsan and the runtime, so they can correctly exchange info about mid-stack inlining.

I'm having trouble with racebuild. I seem to be able to run the steps manually, but just using racebuild itself fails in a strange way:

```
racebuild -goroot ~/sandbox/readonly -platforms linux/amd64 -rev 8a97ee95f2203295e34b7f8ade1092080809fddb
```
does a bunch of setup work (apt-get, ...), then fails with:
```
Cloning into 'go'...
fatal: unable to access 'https://go.googlesource.com/go/': Failed to connect to go.googlesource.com port 443: No route to host
Error running run: exit status 128
```
Why can't the trybots clone the go source code?  It works fine on my machine, and if I `gomote ssh` to the trybot. It is just running `git clone https://go.googlesource.com/go`.  Does `GO_DISABLE_OUTBOUND_NETWORK=1` have anything to do with it? `apt-get` seems to work, so how does `git clone` not? Neither are Go binaries, I think.

@bradfitz @dmitshur

**Comment by dmitshur** [comment]
Hmm. I have not used [racebuild](https://godoc.org/golang.org/x/build/cmd/racebuild), so I'm not sure how it works.

It may be related to `GO_DISABLE_OUTBOUND_NETWORK`, which was added in March (see https://github.com/golang/go/issues/30612#issuecomment-471855726). Is it possible no one has used racebuild since then and so we haven't noticed?

> Why can't the trybots clone the go source code?

For normal trybot runs, the Go repository and other golang.org/x repositories are not `git cloned` on the builder itself, but rather it's fetched by coordinator and then uploaded to the builder via its API (e.g., see [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/internal/buildgo/buildgo.go#L179-L183)).

**Comment by dmitshur** [comment]
Ok, I think I see the problem in the code.

1. Gomote "run" is called [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/racebuild/racebuild.go#L329).

2. `gomote run` uses `buildlet.Exec` [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/gomote/run.go#L74).

  - It uses `conf.Env()`, which includes `GO_DISABLE_OUTBOUND_NETWORK=1` for most builders, [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/gomote/run.go#L79).

3. `buildlet.Exec` makes a POST request to `/exec`, which is handled by `handleExec` [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/buildlet/buildlet.go#L846).

4. If `GO_DISABLE_OUTBOUND_NETWORK=1` is set in the environment, `handleExec` disables the outbound network (permanently for the duration of the builder) [here](https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/buildlet/buildlet.go#L927-L929).

I can send a CL to fix the problem. In the meantime, you can probably just patch racebuild locally to work around the problem with something like:

```diff
-if _, err := p.Gomote(ctx, "run", "-e=REV="+*flagRev, "-e=GOREV="+goRev, p.Inst, targetName); err != nil {
+if _, err := p.Gomote(ctx, "run", "-e=REV="+*flagRev, "-e=GOREV="+goRev, "-e=GO_DISABLE_OUTBOUND_NETWORK=0", p.Inst, targetName); err != nil {
```

The -e env vars are added after and thus take higher precedence.

However, I'm noticing now that `gomote run` should already be doing that by default when `-firewall` flag isn't set to true:

https://github.com/golang/build/blob/1c6297c7b50cad1f0fad91b9aae7241076d0a8b8/cmd/gomote/run.go#L72

@randall77 Maybe the problem is your `gomote` binary is old? It was added in [CL 170397](https://golang.org/cl/170397) in late March. Try building the latest version, it seems like that should fix the problem.

**Comment by randall77** [comment]
Reopening, still need to update the syso files.
