### ISSUE TITLE
x/tools/internal/lsp: log debug server port in the gopls log file, not stderr

### ISSUE THREAD

**Issue by stamblerre** [golang/go#33324]
Because debug.Serve gets called before we get an initialize request, we log to stderr instead of the log.

**Comment by ianthehat** [comment]
Yeah, this came up when talking to Billie.
The idea is that we should enable debug pages by default, but to do that we need to default to :0 so they get unique ports, and that means we need an easy way of finding out what port it picked, and ideally the plugin would be able to find out so that it can just open the debug page.
It is probably worth noting that we could pick other ways of reporting the port number chosen for this purpose.

**Comment by stamblerre** [comment]
@bhcleek: If I recall, you sent out a CL for this, right? Is this still an issue for you?

**Comment by bhcleek** [comment]
My CL, https://go-review.googlesource.com/c/tools/+/211798, was merged. I'll verify it's still working on the pending release, golang.org/x/tools/gopls@v0.3.0-pre2, tonight, and will report back.

**Comment by stamblerre** [comment]
Perfect, thank you!

**Comment by bhcleek** [comment]
v0.3.0-pre2 outputs the port as expected.

**Comment by stamblerre** [comment]
Thanks for confirming! Closing this issue then.
