### ISSUE TITLE
ReactOS support

### ISSUE THREAD

**Issue by SoniEx2** [golang/go#33344]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Tried to run go on ReactOS

### What did you expect to see?

Ideally it would just run

### What did you see instead?

It instead just doesn't run

**Comment by ALTree** [comment]
Thanks for the report (even though you didn't explain very well what the issue actually is... saying "it doesn't run" it definitely not enough).

Go support Windows. Platforms that emulate Windows, or claim to be Windows-compatible (for example Wine or ReactOS) are not explicitly supported, in the sense that if you compile a Go program targeting Windows and the binary doesn't run on Wine or ReactOS, that is a bug in Wine or ReactOS, and it should be reported in their issue tracker.

Closing here, since this does not appear to be a Go bug.

**Comment by jeditobe** [comment]
@ALTree do you support Windows XP?

**Comment by ALTree** [comment]
@jeditobe We don't. From the 1.11 release notes (August 2018):

> [...] Go 1.11 now requires OpenBSD 6.2 or later, macOS 10.10 Yosemite or later, or Windows 7 or later; support for previous versions of these operating systems has been removed.

**Comment by jeditobe** [comment]
ReactOS is an equivalent of XP/2003
