### ISSUE TITLE
x/tools/gopls: surface a diagnostic when opening a file with a DO NOT EDIT comment

### ISSUE THREAD

**Issue by kennytm** [golang/go#33397]
Migrated from microsoft/vscode-go#2617.

When opening a file containing this comment anywhere

```regex
^// Code generated .* DO NOT EDIT\.$
```

it should send a diagnostic, so that the LSP client can display a prominent warning to prevent accidental editting.

**Comment by vincepri** [comment]
Is there a way to disable this warning? Running gopls from master, vscode spams notifications.

**Comment by stamblerre** [comment]
By spams, do you mean that more than one notification is being sent?

**Comment by vincepri** [comment]
That's correct. It seems it happens very frequently when vscode auto-saves on focus or after a timeout, even if I'm just reading the file 😄

**Comment by stamblerre** [comment]
`gopls` should only show this message once - when you open the file for the first time in VSCode. I believe that VSCode-Go itself may also send its own similar diagnostic message and perhaps there is a duplicate there. Do you mind sharing a screenshot?

**Comment by vincepri** [comment]
It seems that these only come from gopls, given that the dropdown doesn't have the option to suppress the warning. On a deeper look it seems that this happens when I'm browsing through different generated files. It'd be great to have an option to remove it though, it seems that's not possible today. WDYT?

<img width="438" alt="Screen Shot 2019-08-12 at 3 19 14 PM" src="https://user-images.githubusercontent.com/3118335/62902533-bed2ea80-bd14-11e9-9a24-592ed8f5bcc4.png">

**Comment by stamblerre** [comment]
Thanks for sharing. One thing I could do is change this diagnostic so that it appears only if a user tries to edit the file, rather than on open.

**Comment by vincepri** [comment]
That sounds great! I can report back when that change goes on master :)

**Comment by stamblerre** [comment]
@vincepri: Just submitted the change. Sorry about the delay!

**Comment by vincepri** [comment]
@stamblerre 24h is more than amazing! :D Thank you so much for working on it! I can confirm it's working as expected 😍 🎉
