### ISSUE TITLE
net/http: logging support

### ISSUE THREAD

**Issue by wvh** [golang/go#3344]
<pre>This is a feature request.

I'm trying to implement Apache-style logging in my program, using camlistore's
logging.go as an example:

<a href="http://camlistore.org/code/?p=camlistore.git">http://camlistore.org/code/?p=camlistore.git</a>;a=blob;f=website/logging.go;hb=HEAD

While the code looks good, it hooks quite deeply into the http package's internals and
requires too much knowledge to be called trivial. Perhaps an easier logging hook should
be provided inside net/http/server.go in the Go standard library itself.

Any thoughts?</pre>

**Comment by rakyll** [comment]
Is this issue still in the plans? We can hook a Logger to an http.Client and an http.Server.

**Comment by bradfitz** [comment]
Update: Camlistore's logging code is now here: https://github.com/camlistore/camlistore/blob/master/website/logging.go

This bug is about an interface for the HTTP server to report back stats about a handler's activity after it's done, to let another layer serialize it or sent it off to logging somewhere.

This can be done with Handler wrappers (as in Camlistore's code, and done by many others), but the HTTP server knows much more and more efficiently, so it could just be built-in.

There are still no plans, but somebody could work on it. I'd be happy to review.

It would need to work with both HTTP/1 and HTTP/2.

A good place to put the stats records is the new https://tip.golang.org/pkg/net/http/httptrace/ package, to not pollute the main http package godoc.

**Comment by tombergan** [comment]
This is now a dup of #18997. See the following comment:
https://github.com/golang/go/issues/18997#issuecomment-296722404
