### ISSUE TITLE
net: typo in src/net/ip.go for private func parseIPv6

### ISSUE THREAD

**Issue by gaissmai** [golang/go#33455]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

read the src file, found a copy paste error in the doc
### What did you expect to see?
// parseIPv6 parses s as a literal IPv6 address described in RFC 4291
// and RFC 5952.
func parseIPv6(s string) (ip IP) {

### What did you see instead?
// parseIPv6Zone parses s as a literal IPv6 address described in RFC 4291
// and RFC 5952.
func parseIPv6(s string) (ip IP) {

**Comment by agnivade** [comment]
Hi @gaissmai , thank you for reporting this. However, this has already been fixed in the latest master by this change - https://go-review.googlesource.com/c/go/+/180037.

In future, you do not need to open issues for minor typos like this. Please feel free to directly send patches. Of course, if you do not feel like sending one, it is okay to file an issue. :) 

I will go ahead and close this as it has already been fixed.
