### ISSUE TITLE
proxy.golang.org returning 410 for k8s.io/client-go@v12.0.0+incompatible

### ISSUE THREAD

**Issue by davecheney** [golang/go#33558]
proxy.golang.org has stoped returning the correct result for k8s.io/client-go v 12.0.0
```
(~/devel/tttt) % cat go.mod 
module whatever

go 1.12

require k8s.io/client-go v12.0.0+incompatible // indirect
(~/devel/tttt) % env GOPATH=$(mktemp -d) GOPROXY=https://proxy.golang.org go1.12 get -x k8s.io/client-go@v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go: k8s.io/client-go@v12.0.0+incompatible: unexpected status (https://proxy.golang.org/k8s.io/client-go/@v/v12.0.0+incompatible.info): 410 Gone
go: error loading module requirements
```

_Note: the `env GOPATH...` is to avoid having to sudo rm -rf my $HOME/pkg/mod directory._

This was working on Friday and has broken our CI.

**Comment by thepudds** [comment]
You have likely already seen this, but some chance related to  https://github.com/golang/go/issues/33513#issuecomment-519186900

**Comment by bcmills** [comment]
Note the error text returned by that URL:
```
not found: k8s.io/client-go@v12.0.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

See https://tip.golang.org/doc/go1.13#version-validation for more detail and advice on fixes and workarounds.

**Comment by bcmills** [comment]
See also #32695.

**Comment by bcmills** [comment]
Duplicate of #32805

**Comment by thepudds** [comment]
FWIW, a bit more detail.

The v12.0.0 `go.mod` file for k8s.io/client-go appears to be missing the required `/v12` at the end of the `module` line:

https://github.com/kubernetes/client-go/blob/v12.0.0/go.mod#L3
```
module k8s.io/client-go
```

From the `cmd/go` [documentation](https://tip.golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)

> In semantic versioning, changing the major version number indicates a lack of backwards compatibility with earlier versions. To preserve import compatibility, **the go command requires that modules with major version v2 or later use a module path with that major version as the final element**. For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2, and packages in that module would use that path as their import path prefix, as in example.com/m/v2/sub/pkg. Including the major version number in the module path and import paths in this way is called "semantic import versioning".

CC @liggitt @nikhita

**Comment by thepudds** [comment]
Some additional context is that proxy.golang.org was recently updated to use 1.13beta1, which including "invalidating some old module versions that are currently being served from proxy.golang.org but are no longer valid in 1.13".

Some more details from the [one of the announcements](https://groups.google.com/d/msg/golang-dev/go6_lZqew6g/b1O8DeRjCgAJ) on golang-dev: 

> As an update, related to https://golang.org/issue/32805 and https://golang.org/issue/32879#issuecomment-507861612:
> Go 1.13 includes some changes to the go command which tighten up the validation of module versions. Now that we have upgraded proxy.golang.org to use the 1.13beta1 version of the go command, we will be invalidating old module versions that are currently being served from proxy.golang.org but are no longer valid in 1.13. We don't expect any major issues from users since the request count is low for each of the module versions that will be invalidated, but please file issues against the issue tracker, prefixed "proxy.golang.org", if you encounter any problems. Thanks to everyone who has filed issues so far and given us feedback!

**Comment by davecheney** [comment]
@bcmills i'm sorry to reopen this but this has broken our Go 1.12 builds, we're not in a position to upgrade to 1.13beta1. We need a solution that restores functionality for Go 1.12.

**Comment by bcmills** [comment]
@davecheney, a `replace` directive (as described in the 1.13 release notes) should also work in 1.12. Please give it a try.

**Comment by thepudds** [comment]
Two other potential options when using the Go 1.12 `go` command:

1. Use an alternate proxy. For example, this seemed to work just now, perhaps because goproxy.io is not yet running Go 1.13:

`GOPROXY=https://goproxy.io  go get -d k8s.io/client-go@v12.0.0`

2. Use `direct`. This also seemed to work just now:

`GOPROXY=direct  go get -d k8s.io/client-go@v12.0.0`

**Comment by davecheney** [comment]
@bcmills this worked last week. Our builds built last week using Go 1.12. They worked on Monday.  Something has broken in proxy.golang.org that means it no longer works as it did just a few days ago.

It's unreasonable to ask users to change their go.mod configuration because proxy.golang.org can no longer serve _valid_ artefacts that it served a few days ago.

**Comment by davecheney** [comment]
Further,

> We don't expect any major issues from users since the request count is low for each of the module versions that will be invalidated, but please file issues against the issue tracker, prefixed "proxy.golang.org", if you encounter any problems.

Clearly this is not true, v12 of client-go is a very popular dependency and now it is inaccessible for Go 1.12 users using proxy.golang.org.

**Comment by thepudds** [comment]
One other possible workaround is I think 1.12 can be forced to use a pseudo-version with a commit hash corresponding to the v12.0.0 tag of k8s.io/client-go.

In particular, this works:

`GOPROXY=https://proxy.golang.org go get -d k8s.io/client-go@78d2af7`

with this result:
```
require k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
```
An alternative path to a similar result:

```
echo 'replace k8s.io/client-go => k8s.io/client-go 78d2af7'
go list -m all
```

**Comment by bcmills** [comment]
> It's unreasonable to ask users to change their go.mod configuration because proxy.golang.org can no longer serve _valid_ artefacts that it served a few days ago.

The `v12.0.0` artifact is _not_ valid and never was — as far as I'm aware the requirement for semantic import paths has been clearly documented since 1.11.

The fact that `v12.0.0+incompatible` could be fetched in certain circumstances by playing games with manually-added suffixes was a bug, plain and simple. The fact that that bug was temporarily facilitated by the proxy's `/list` endpoint is unfortunate, but now that's been fixed too.

**Comment by bcmills** [comment]
See also https://github.com/kubernetes/client-go/issues/631.

**Comment by davecheney** [comment]
> The fact that v12.0.0+incompatible could be fetched in certain circumstances by playing games with manually-added suffixes was a bug, plain and simple. 

It may be a bug, but the bug exists in Go 1.12, the version that produced that line. Saying it' a bug is fine, but breaking projects that were happily working up to a few days ago is pretty unfriendly behaviour.

**Comment by davecheney** [comment]
@bcmills given that go.mod files with lines ending in `+incompatible` can no longer be served via proxies, should the go command reject them completely when operating in proxy mode?

**Comment by bcmills** [comment]
The bug in Go 1.12 required users to manually exploit the bug by adding a `+incompatible` suffix. Otherwise, they would get ether an explicit error or a version rewritten to the valid equivalent.

The only users who would have picked it up without manual intervention would have picked it up from a cache or proxy entry added by some other module that manually exploited the bug.

Moreover, there is a simple workaround available: `replace` the invalid version with its valid equivalent.

**Comment by bcmills** [comment]
Adding the same validation to the proxy path is #32955, but that's a harder problem in general because the protocol erases version control history. (It's possible to do for invalid `+incompatible` versions, but not for invalid pseudo-versions because the proxy does not supply compete version-control history.)

**Comment by davecheney** [comment]
Thanks for clarifying. If `+incompatible` is a bug or represents incorrect manual editing, should the go tool error out when it finds those lines? If the hypothesis is the impact of the proxy.golang.org change is small, then there should only be a small number of `+incompatible` lines in the wild, so rejecting them quickly so module authors can fix the problem seems line a nice thing to do. Would you agree?

**Comment by bcmills** [comment]
`+incompatible` is only a bug when used with a version that either has an explicit `go.mod` file or is not actually incompatible with the given module path.

Those really are rare: we ran several analyses to verify that (see https://github.com/golang/go/issues/27173#issuecomment-504566514, and the folks running `proxy.golang.org` did their own internal analysis before removing the invalid versions).

**Comment by davecheney** [comment]
I don't think they are as rare as you believe.

Here are two that I found in the `go.mod` file for client-go

https://github.com/kubernetes/client-go/blob/master/go.mod#L8

https://github.com/kubernetes/client-go/blob/master/go.mod#L21

**Comment by bcmills** [comment]
@davecheney, please read my replies above more carefully.

> `+incompatible` is only a bug when used with a version that either has an explicit `go.mod` file or is not actually incompatible with the given module path.

The two versions you note in your comment above both lack explicit `go.mod` files, and are therefore correct uses of the `+incompatible` annotation.

**Comment by thepudds** [comment]
One quick comment: `+incompatible` itself is not a problem, nor is it rare.

Any module can import a v2+ package that has not opted into modules, and if the imported v2+ package has a valid semver tag, the imported package will be recorded with an +incompatible suffix in the importing module's go.mod file. 

Using your first example:
`github.com/Azure/go-autorest v11.1.2+incompatible`

That is fine, because github.com/Azure/go-autorest@v11.1.2 itself does not have a `go.mod` file.

The main problem being discussed in this thread is when a v2+ package attempts to adopt modules, but does not follow the requirement listed in the doc quote in 
https://github.com/golang/go/issues/33558#issuecomment-519744620

**Comment by davecheney** [comment]
ahh, ok. Thanks for explaining. So the rules for `+incompatible` are:

1. if the module does not have a `go.mod` file _and_ have a sevmer tag above v1, then it is ok to list it as `+incompatible`. (I'm assuming the go tool, or the proxy, strips off the +incompatable at some point)
2. If the module does have a `go.mod` file _and_ has a semver tag above v1 but does not conform to SIV, then the module cannot be referred to as `+incompatible`, the importer must fall back to the v0 pseudo version.

**Comment by bcmills** [comment]
Correct.

**Comment by bcmills** [comment]
As another data-point: a search for [`k8s.io/client-go` at `v12.0.0+incompatible`](https://www.google.com/search?q="k8s.io%2Fclient-go"+"v12.0.0%2Bincompatible") does not turn up any results in publicly-available code, but the corresponding search for the [`v0.0.0-20190620085101-78d2af792bab`](https://www.google.com/search?q="k8s.io/client-go"+"v0.0.0-20190620085101-78d2af792bab") (the equivalent valid version) shows many results.

That suggests that (consistent with our hypothesis) most users were not affected by the buggy version served by `proxy.golang.org`. And that's to be expected, since `proxy.golang.org` had to be configured explicitly with Go 1.12.

I'm sorry that you were one of the unlucky few, but you do seem to be an outlier here.

**Comment by bcmills** [comment]
CC @katiehockman @hyangah @heschik

**Comment by heschik** [comment]
I agree with Bryan on all fronts. I double-checked the logs and v12.0.0+incompatible has relatively few downloads; I don't think we made a big mistake removing it. Much better to match behavior with 1.13, where it will be the default, even if it causes some trouble for 1.12 users. Hopefully there won't be another upheaval like this in 1.14 -- I can't imagine us doing anything like this once the service is out of beta.

Sorry for the trouble, but this is why it's still in beta. We hope to fully launch very soon.

**Comment by ankushchadha** [comment]
k8s.io/client-go@v12.0.0+incompatible is referred by 130 go module versions and what it means is that their builds will be broken unless they set the GOPROXY to https://gocenter.io. We will continue to serve this version. This specific version was downloaded a lot of times (in thousands) from GoCenter.
More details here - https://search.gocenter.io/k8s.io~2Fclient-go/info?version=v12.0.0%2Bincompatible

**Comment by bcmills** [comment]
@ankushchadha, it appears that most (perhaps all) of those 130 modules only appear to have a dependency due to a bug in GoCenter itself, not due to anything explicitly in their `go.mod` files.

----

Arbitrarily checking the “Mod File” tab for the first five entries listed on the “Used By” tab of https://search.gocenter.io/k8s.io~2Fclient-go/info?version=v12.0.0%2Bincompatible, I see the following note on three of them:
> It seems this project has not adopted Go modules yet. Here's a suggested go.mod file for the latest version.

The two other modules I checked from the “Used By” list entirely different versions of `k8s.io/client-go` altogether!
* [github.com/concourse/concourse](https://search.gocenter.io/github.com~2Fconcourse~2Fconcourse/info?version=v5.4.0%2Bincompatible) lists `k8s.io/client-go v2.0.0-alpha.0.0.20171101191150-72e1c2a1ef30+incompatible`.
* [github.com/pachyderm/pachyderm](https://search.gocenter.io/github.com~2Fpachyderm~2Fpachyderm/info?version=v1.9.3) lists `k8s.io/client-go v0.0.0-20181213230135-6924ba6dfc02`.

So I'm led to believe that what you are seeing is a significant bug in GoCenter's version indexing rather than organic usage of the invalid version.

**Comment by ankushchadha** [comment]
That's the current UX if the dependents have not adopted Go modules. However, there are 58 references for "k8s.io/client-go v12.0.0+incompatible" on GitHub (https://github.com/search?p=2&q=%22k8s.io%2Fclient-go+v12.0.0%2Bincompatible%22&type=Code)

I don't know how many private projects refer to this version of k8s.io/client-go.

In addition, there are 19857 modules above v1 with +incompatible suffix in GoCenter. We don't know how many of them have go.mod file but we imagine that the impact of this change is going to be huge since these modules along with dependents may not be usable anymore.

**Comment by mattn** [comment]
Sorry if my comment is not related on this issue.

https://github.com/mattn/go-sqlite3/issues/755

Last year, in go-sqlite3, topic branch v2.0.0 was created to ready to make release. Unfortunately, v2.0.0 was not merged. https://github.com/mattn/go-sqlite3/pull/611

So I removed the topic branch with `git push origin :v2.0.0` but proxy.golang.org return https://proxy.golang.org/github.com/mattn/go-sqlite3/@v/list

```
v1.9.0
v1.3.0
v1.7.0
v1.8.0
v1.6.0
v1.0.0
v1.12.0
v1.5.0
v2.0.0+incompatible
v1.10.0
v1.11.0
v1.4.0
v1.2.0
v1.1.0
```

Is there any other way to solve this problem without releasing v2.0.1 of go-sqlite3 ?

**Comment by bcmills** [comment]
@mattn, see #34189. As of Go 1.14, if the latest compatible version has a `go.mod` file, the `go` command will prefer the compatible version over any potential `+incompatible` one. So it may suffice to add a `go.mod` file at the root of the `github.com/mattn/go-sqlite3` repo.

**Comment by pierrre** [comment]
What is the short-term solution ?
Go 1.14 is not yet released.
Is it possible to purge the proxy.golang.org cache ?

**Comment by ergoz** [comment]
this issue broke 20+ my packages

**Comment by grosser** [comment]
can we please get a real/automatic fix for this ?
... super annoying to have to google for a bug and then dig through this big issue just to find out that you have to copy-paste some hack into your go.mod :(

**Comment by bcmills** [comment]
@grosser, see https://github.com/kubernetes/client-go/issues/749.

#24031 on the Go side may provide another option, in that it would allow the Kubernetes maintainers to retract all of the releases higher than `v0`.
