### ISSUE TITLE
why can't get input line from stdin when this line end with EOF

### ISSUE THREAD

**Issue by hwhe** [golang/go#33590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.9.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
func main() {
	reader := bufio.NewReader(os.Stdin)
	inputBuffer, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		fmt.Println(err.Error())
		return
	}

	inputBuffer = strings.TrimRight(inputBuffer, "\r\n")
	inputStrings := strings.Split(inputBuffer, " ")
	fmt.Println(inputStrings)
}

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

when i input 123 and Ctrl+D,  can't get the 123? 
 #
123^D
[]

### What did you expect to see?
Ctrl+D is EOF, i should got the 123

### What did you see instead?
i cat't got the 123
i wonder kown the reason

**Comment by dmitshur** [comment]
It should work, it likely has to do with how your terminal interprets Ctrl+D presses. You might have to press it twice, or do Ctrl+D followed by Enter. See https://superuser.com/a/169057 for more about those shortcuts and how they differ between terminals.

That said, our issue tracker is not the best medium for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.

**Comment by andybons** [comment]
Hi there,
We have decided that our experiment to allow questions on the issue tracker has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still curious:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks
