### ISSUE TITLE
doc: ref/gdb should mention compiler flags / go install -gcflags

### ISSUE THREAD

**Issue by the42** [golang/go#3363]
<pre>The Documentation of Debugging Go Code
(eg. <a href="http://tip.golang.org/ref/gdb)">http://tip.golang.org/ref/gdb)</a>
should mention the -N and -l* flags. Both are useful (and in case of a consistent
picture on local variables) essential.

As the go tool has settled it would also make sense to mention

go build|install|... -gcflags '-N -l'

(Btw. the documentation does mention the &quot;-s&quot; flag to omit debug info, so it
should mention the others influencing debug behavior too)</pre>

**Comment by odeke-em** [comment]
Thank you for the report and for the patience @the42, as well as others for the triage and responses.

So that page no longer exists, but now we’ve got references for “Debugging with GDB” https://golang.org/doc/gdb#Introduction  as well as “Diagnostics” and under the section “Debugging” https://golang.org/doc/diagnostics.html?h=gdb#debugging where we mention -gcflags=‘-N -l’
![BD5B06C2-F772-4050-A28A-D89F30702E3B](https://user-images.githubusercontent.com/4898263/74092543-676ec680-4a7a-11ea-980d-47846b15b9c2.png)
![E499BA69-41C6-4F1B-A658-415AED256D00](https://user-images.githubusercontent.com/4898263/74092544-6b024d80-4a7a-11ea-8a76-bcc5fdf47cd9.png)

Thus I shall close this issue.
