### ISSUE TITLE
os/exec: CombinedOutput() segmentation fault (core dumped)

### ISSUE THREAD

**Issue by drwpeng** [golang/go#33663]
### What version of Go are you using (`go version`)?
linux   go1.12.7
<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?
debian in docker
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
![image](https://user-images.githubusercontent.com/30896200/63085040-212f2380-bf7f-11e9-8f26-82fdbce16821.png)

### What did you expect to see?
no segment fault

### What did you see instead?
![image](https://user-images.githubusercontent.com/30896200/63084761-82a2c280-bf7e-11e9-9276-0cb725ad868c.png)

**Comment by mattn** [comment]
As far as I can see your screenshot, the crashed program is mpclient not Go.

**Comment by drwpeng** [comment]
I find "ProcessState" Field. I add  `fmt.Printf("state.....", state) ` to wait() function.As shown:
![image](https://user-images.githubusercontent.com/30896200/63089615-0662ac00-bf8b-11e9-8048-f6b202d3cc8e.png)
Then I saw the output as shown below：
![image](https://user-images.githubusercontent.com/30896200/63089752-85f07b00-bf8b-11e9-9604-121f8a1dfe5e.png)

**Comment by mattn** [comment]
Yes, it is state of child process. So the crashed program is mpclient.

**Comment by agnivade** [comment]
@drwpeng - please let us know if the above diagnosis is incorrect. You can also run the "./mpclient <path>" manually to check if it generates a seg fault. As far as I can see, the Go program runs fine because it prints other lines properly after the seg fault.

And it is preferred to directly have the text output rather than a screenshot. In this case, I could not copy paste your mpclient command just because it was an image. A minor inconvenience, but it could be bigger if I had to use any of the text to reproduce some other issue.

**Comment by drwpeng** [comment]
Yes, it is a problem with mpclient. Thank you for your help.
