### ISSUE TITLE
x/tools/gopls: incorrect diagnostics when navigating through 'git' and 'gitlens' files

### ISSUE THREAD

**Issue by inliquid** [golang/go#33699]
VS Code. Here is what I get into after navigating over some history with Gitlens extension. 
![изображение](https://user-images.githubusercontent.com/6797881/63216390-191ce280-c13d-11e9-86db-27089485dff9.png)

`gopls` returns a lot of errors, in spite that files are actually ok. Other that that I must admit that most of features work, so for instance I can navigate and see some documentation on hover in both git panes. Not for all elements however. One annoying thing is these errors. However, if I close the window, they'll disappear.

**Comment by inliquid** [comment]
Same thing with 'git' urls.

**Comment by dskdas** [comment]
is there any workaround to use vscode with gopls in current state without having to restart vscode after any viewing of git diff (to get rid of the errors)?

**Comment by heschik** [comment]
@dskdas You can restart the LSP with `ctrl-shift-p`, then `Go: Restart Language Server`.

Notes:
An easy to way to reproduce this is to rename some commonly-used type, then open a file affected by the rename in the Source Control pane. VS Code sends a didOpen for a `gitfs:` URI, which we treat as if it were a regular file URI. From there it's a bit of a comedy of errors:

- We do a file= query for some insane combination of the workspace root and the full gitfs URI (?!). Not surprisingly, it finds nothing.
- We don't get a zillion duplicate definition errors, probably because we don't include it when type-checking the package.
- Somehow the file is type checked enough to produce undeclared name errors. I'm confused by this bit.

On the one hand, a lot of features work surprisingly well in the gitfs: file -- basically anything that references a symbol outside the file itself. On the other, this is conceptually impossible: literally anything could have happened to the project since whatever version of the file you're looking at, so there's no reason to expect anything to still exist.

Just suppressing diagnostics in these files might be good enough to paper over a lot of the problems. Let me see how bad the experience is after that.

**Comment by heschik** [comment]
There's a lot of mess under the covers here.
- `span.NewURI` doesn't account for non-`file` schemes. If you pass it a `gitfs` URI, it puts `file://` in front of it.
- `span.(*URI).Filename`, with 102 call sites, panics if you call it on a non-`file` URI.

Putting those two facts together, you can't reliably tell what kind of URI you've got, and if you fix `NewURI` to not mangle its results, then you get panics all over the place when one pops up somewhere unexpected.

I think the only feasible option is to reject non-`file` URIs at the edges. Will think more.

**Comment by mholt** [comment]
I have a similar issue, but I'm not sure if it's the same, because I don't know what `Gitlens` is, so I don't think I have that extension. I see this:

<img width="1065" alt="Screen Shot 2020-02-11 at 12 43 41 PM" src="https://user-images.githubusercontent.com/1128849/74272605-2a017780-4ccc-11ea-9a2a-05639ffd2652.png">

And clicking on any of the problems gives this error:

```
Unable to open 'filestorage.go?%7B%22path%22%3A%22%2FUsers%2Fmatt%2FDev%2Fcertmagic%2Ffilestorage.go%22%2C%22ref%22%3A%22~%22%7D': Unable to read file '/Users/matt/Dev/certmagic/git:/Users/matt/Dev/certmagic/filestorage.go?%7B%22path%22%3A%22%2FUsers%2Fmatt%2FDev%2Fcertmagic%2Ffilestorage.go%22%2C%22ref%22%3A%22~%22%7D' (Error: Unable to resolve non-existing file '/Users/matt/Dev/certmagic/git:/Users/matt/Dev/certmagic/filestorage.go?%7B%22path%22%3A%22%2FUsers%2Fmatt%2FDev%2Fcertmagic%2Ffilestorage.go%22%2C%22ref%22%3A%22~%22%7D').
```

FWIW, `/Users/matt/Dev/certmagic/git` doesn't exist, and never has.
