### ISSUE TITLE
parallel testing: how to collect stdout of _all_ tests (including paused tests) in verbose mode.

### ISSUE THREAD

**Issue by medyagh** [golang/go#33706]
Recenetly we made minikube's integeration tests to run in parallel. (since we spin up 30+ VMs and we wanted to speed up the process)

Recently I added a logging in this PR: 

```
elapsed := time.Since(start) 
glog.Infof("duration metric: took %s to wait for %s ...", elapsed, label)
```

to ouptput how long the health check waited for each component of kubernetes.

however in our more than 30+ tests,  I noticed it only outputs at most 2 times, and sometimes not at all, my initial suspection is: most probably the test go to "Pause" and when they are in "Pause" they do not print out anything and when they are changed from PAUSE to RUN, we loose bunch of logs.

we run our tests with verbose options and `--alsologtostderr -v=8`

is there any way to make sure the stdout logs are recorded somewhere for all the tests ? not just the one in the foreground ?

here is the code snippet if it helps : 

```
	start := time.Now()
	glog.Infof("Waiting for pod with label %q in ns %q ...", ns, label)
	f := func() (bool, error) {
	     /// .... some function that checks for a specific pod to be running
	}
	err := wait.PollImmediate(kconst.APICallRetryInterval, ReasonableStartTime, f)
	elapsed := time.Since(start)
        //  This is the line I wanna see in the logs all the time !
	glog.Infof("duration metric: took %s to wait for %s ...", elapsed, label)
	return err

```

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
