### ISSUE TITLE
cmd/go: unexpected directory layout while building project

### ISSUE THREAD

**Issue by scrumteamravens** [golang/go#33752]
```
    unexpected directory layout:
    	import path: github.com/gruntwork-io/terratest/modules/helm
    	root: /home/vagrant/go/src
    	dir: /home/vagrant/go/src/k8stests/vendor/github.com/gruntwork-io/terratest/modules/helm
    	expand root: /home/vagrant/go/src
    	expand dir: /home/vagrant/go/src/k8stests/vendor/github.com/gruntwork-io/terratest/modules/helm
    	separator: /

```

Can you please help me on where i am going wrong here. 
<br>$ go env

```
    GOARCH="amd64"
    GOBIN=""
    GOCACHE="/home/vagrant/.cache/go-build"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/vagrant/go:/home/vagrant/go/src/k8stests"
    GORACE=""
    GOROOT="/usr/lib/go-1.10"
    GOTMPDIR=""
    GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build737322677=/tmp/go-build -gno-record-gcc-switches"
```
go version go1.10.4 linux/amd64

**Comment by smasher164** [comment]
Can you provide the exact commands you ran to fetch and build this package?

**Comment by scrumteamravens** [comment]
in the project root directory /home/vagrant/go/src/k8stests
go build ...

**Comment by agnivade** [comment]
Since you are using Go 1.10, you need to do everything according to the GOPATH. First of all, you have an incorrect GOPATH setting. There is no need to append `/home/vagrant/go/src/k8stests` to `/home/vagrant/go`. Just `/home/vagrant/go` is fine. And secondly, clone your repo under the correct path. If you are building `github.com/gruntwork-io/terratest`, create that folder structure under `home/vagrant/go/src` and then clone the repo there and build it.

Please see this answer - https://stackoverflow.com/questions/45428744/golang-unexpected-directory-layout.

I will go ahead and close this since this is not a bug. If this still does not solve your issue please feel free to ask it in any of these forums below:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks

**Comment by scrumteamravens** [comment]
@agnivade Its working fine if i pull the dependency using "go get" but as soon as i move to  godep to resolve dependency it pulls everything in vendor folder but while building my project it shows "  unexpected directory layout" . Not sure where i went wrong. 
As per your suggestion i changed the GOPATH to "/home/vagrant/go" still no luck.
