### ISSUE TITLE
x/website: Misleading statement in FAQ

### ISSUE THREAD

**Issue by elliottpolk** [golang/go#33809]
The [FAQ](https://golang.org/doc/faq#Does_Go_have_a_ternary_form) currently states 

> A language needs only one conditional control flow construct.

Go currently has multiple conditional flows, `if-else`, `switch-case`, and (?) `select-case`. This can be potentially problematic for the argument against a _ternary_ operator.

**Comment by ALTree** [comment]
The switch has statement has the type-switching support which is not easily replicable by other means and the select has the whole blocking stuff, they both serve their purpose. Ternary, on the other hand, is literally the same thing as an `if-else` but with another syntax. That's the point the FAQ is trying to make.

Closing here, since I think the current working is fine.

**Comment by elliottpolk** [comment]
The point it's trying to make is valid. The mechanism in which it's making said point isn't. Stating it only needs one of something when it clearly has at least 3 invalidates the argument.
