### ISSUE TITLE
x/tools/gopls: autocomplete keywords

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34009]
They probably should be ranked even lower than builtins.

**Comment by sebsebmc** [comment]
Hi, I am interested in helping with this.

**Comment by stamblerre** [comment]
@sebsebmc: Awesome! A good place to start looking is https://github.com/golang/tools/blob/master/internal/lsp/source/completion.go. Feel free to reach out to me here or on the [Gophers Slack](https://invite.slack.golangbridge.org/) if you need help.

Some things to consider:

1. How should keywords be ranked? My thinking is that they should probably be prioritized lower than lexical completions, but higher than deep completions (what do you think, @muirrn?).

2. We should only suggest keywords if they are reasonable in the context of the code. For example, we shouldn't suggest `continue` outside of a loop.

**Comment by muirrn** [comment]
I think if we do a good job with 2), we can probably just start with the "stdScore" (assuming they are naturally ordered after lexical completions). My guess is typing "cont<>" and getting some weird fuzzy match instead of "continue" will be a more common annoyance than typing "cont<>" and getting "continue" instead of a lexical candidate.

One other thought: most keywords are statements, so we should also limit those to beginning of statements. For example:

```go
for {
  breakDance := 123
  actuate(brea<>) // don't offer "break" completion because it isn't start of statement
}
```

**Comment by stamblerre** [comment]
I actually just ran into the `continue` case a few minutes ago (VSCode offers keyword completions on its own, so they don't work at all with our rankings), but that's exactly why I mentioned the placement between standard and deep completions. I agree, there are enough cases where we can exclude keywords that the ranking system should be fine.

**Comment by sebsebmc** [comment]
Hi, I've been looking at completions.go already, I'll be sure to reach out with any questions.

**Comment by sebsebmc** [comment]
So currently I have reduced the keywords into roughly 2 categories: those that the parser thinks might be an identifier, and those that it doesn't. I've been focusing on the `*ast.Ident` case and trying to return keywords based on the context and erring on the side of not recommending a keyword. 

Currently, the scoring is very rudimentary and there still needs to be some more work on restricting the keywords to beginnings of statements. This is partially being done right now by bailing on keyword suggestion if the path contains certain nodes like: `FieldSet`, `ValueSpec`, `TypeSwitchExpr`... These node types mean we are inside a statement where a keyword is unlikely to be valid.

For nodes that aren't being marked as an identifier, the parser is typically marking them as a `*ast.BadDecl` because it only wants valid declaration keywords at the file level scope. A partially typed keyword here is invalid and the token needs to be retrieved from the file to be able to prefix match on it.

I plan on submitting a patch for the first case once I have it flushed out a bit more and then based on that we can think about how to handle the second case. (Or if there's a different approach altogether that would be better)

**Comment by muirrn** [comment]
> there still needs to be some more work on restricting the keywords to beginnings of statements.

Not tested, but to detect if we are at the start of a statement I would start by checking if `path[0]` or `path[1]` is an `*ast.BlockStmt`. Maybe you already tried something like that.

> the parser is typically marking them as a *ast.BadDecl because it only wants valid declaration keywords at the file level scope

I assume you are talking about cases like this:
```go
package foo
co<> // want to complete to "const".
```
I had a [failed CL](https://go-review.googlesource.com/c/tools/+/195039) that might have helped with this case. The CL would replace the leaf BadDecl in `path` with an `*ast.Ident` to facilitate completion. If that helps you then maybe there is a case to reopen it. On the other hand, maybe not offering completions for file level keywords is fine.

**Comment by sebsebmc** [comment]
I'm not sure that the `BadDecl` needs to be replaced, it would likely be sufficient to be able to get the `co` in your example and match that against the keywords used in declarations (like `var`, `const`, etc.)

> checking if path[0] or path[1] is an *ast.BlockStmt

The problem are nodes like `CaseClause` that don't have `BlockStmt` as bodies.

**Comment by sebsebmc** [comment]
Additional work is needed to add support for keywords used in declarations at the file level. Currently any non-comment text results in `*ast.BadDecl` and so there is no text to match against to provide completions.

The keywords that we want to complete here are: `package`, `import`, `const`, `var`, `type`, and `func`. We can special case things like suggesting a package snippet if the document doesn't yet have an `*ast.Package` node, or we can fix the AST like suggested in https://github.com/golang/go/issues/34332#issuecomment-543369950

Note: I don't believe testing package statements is possible right now because of packagetest not running tests that don't contain a valid package statement.

Another issue is that inside of switch/select statements when there is no case or default statement the the parser expects a right brace so when typing the first case/default keyword users will not get completions.

**Comment by stamblerre** [comment]
It seems that keyword completions are not being proposed in some of the expected cases. It will require a bit more investigation to see what's going on, but I just wanted to note that here.

**Comment by muirdm** [comment]
@stamblerre do you have any other keyword TODOs or can this be closed? I'm ignoring "package" since that will probably be a can of worms.

**Comment by stamblerre** [comment]
One issue I have noticed is this (`internal/lsp/cache/view.go:679`): 

<img width="932" alt="Screen Shot 2020-03-11 at 12 54 29 PM" src="https://user-images.githubusercontent.com/5856771/76442565-84f3c080-6397-11ea-9434-241197762da3.png">
