### ISSUE TITLE
x/tools/gopls: autocomplete in package declaration

### ISSUE THREAD

**Issue by stamblerre** [golang/go#34008]
This can be done for new files in the same package, test files, or new packages based on the name of the directory.

**Comment by kiivihal** [comment]
I would like to pick this up. Any pointers to the best place to start would be appreciated.

**Comment by stamblerre** [comment]
This might be a particularly complicated change actually, because this type of completion would only be triggered when we don't know the name of the package so we won't have good type information. The autocompletion code can be found here: https://github.com/golang/tools/blob/master/internal/lsp/source/completion.go, but I think that you will basically need to create a case that does this here: https://github.com/golang/tools/blob/27d1b4e4f3c75e4e2c92ae1b99a67c7f34185617/internal/lsp/source/completion.go#L394, when we fail to get a package for the given file.

**Comment by dandua98** [comment]
Updating about the progress towards this issue so far, we can't really offer completion for this somewhere in the general completion codebase since that relies on a `pgf` (parsed go file) and we don't really have any type information for the the file to generate that until a package is specified. I got package completion to work but only after we specify a package first (so that we can generate a pgf), which makes the feature irrelevant. It could still be useful if the user types a prefix to search for a package and we could return some suggestions but again at that point this doesn't provide too much value. 

Now we could potentially offer completions at https://github.com/golang/tools/blob/c024452afbcdebb4a0fbe1bb0eaea0d2dbff835b/internal/lsp/source/completion.go#L461 (what @stamblerre mentioned earlier) but it would be tough to integrate it with the way Completion is setup right now.
