### ISSUE TITLE
why using Github. It's a proprietary software 

### ISSUE THREAD

**Issue by lithic** [golang/go#34057]
Use a self hosted alternative like Gitea.

**Comment by ianlancetaylor** [comment]
This is something to discuss on a forum rather than the issue tracker.  See https://golang.org/wiki/Questions.  I will close this issue.

Note that Go's source code is stored in Gerrit at go-review.googlesource.com.  From there it is mirrored to GitHub.  Gerrit is free software (https://www.gerritcodereview.com).

**Comment by lithic** [comment]
This is a issue

**Comment by lithic** [comment]
You can mirror it to gitea. Not that gitea itself is written in go

**Comment by agnivade** [comment]
As Ian said, please discuss this on a [forum](https://golang.org/wiki/Questions). This is not the right place to discuss this.
