### ISSUE TITLE
translation go documentation into Russian

### ISSUE THREAD

**Issue by maxnosib** [golang/go#34063]
I would like to help with the translation of go documentation into Russian how can I do this

**Comment by aofei** [comment]
See: https://github.com/golang/go/issues/33290#issuecomment-516449087

**Comment by ALTree** [comment]
Yep, as the issue that @aofei linked, the Go team doesn't directly host and/or maintain Go tour and documentation translations. The official source of truth is the English version; translation are welcome but you'll have to host them yourself.

Closing here, since I believe your question was answered.
