### ISSUE TITLE
expand span size to decrease heap memory allocation's thread lock conflict

### ISSUE THREAD

**Issue by superajun-wsj** [golang/go#34077]
### What version of Go are you using (`go version`)?

<pre>
$ go version
$ all go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ linux or windows

</pre></details>

### What did you do?
$ design a parallel program to allocate a lot of heap objects, which will result in
$ violent thread lock conflict

### What did you expect to see?
$ there is no serious thread lock conflict

### What did you see instead?
$ there is serious thread lock conflict

**Comment by katiehockman** [comment]
@superajun-wsj can you please finish filling out the rest of the template, including providing the output of `go version` and of `go env`? We also need more details in order to investigate this. Do you have example code that you can provide? What errors are you seeing? What things have you already tried to solve this problem that didn't work?
