### ISSUE TITLE
x/mobile: apps built with go 1.13, still rejected by Apple app store

### ISSUE THREAD

**Issue by mmaxim** [golang/go#34133]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

gomobile for iOS.

### What did you do?

Build an app and try to submit to Apple App Store.

### What did you expect to see?

Acceptance.

### What did you see instead?

The fix provided here https://github.com/golang/go/issues/31628 is not complete. `ptrace` is not the only symbol that is being rejected by the store. Go >= 1.12 (including the latest release with a fix for the aforementioned `ptrace` problem) still triggers a rejection on the `sysctl` symbol. Some sample text from Apple:

```
ITMS-90338: Non-public API usage - The app references non-public symbols in Keybase: ___sysctl
```

The only way we can submit our app to the app store is to run the now unsupported Go 1.10.8, which works.

**Comment by hyangah** [comment]
@khr @eliasnaur 

Can we disable the use of sysctl as well in the syscall package?

**Comment by eliasnaur** [comment]
Sure, should we backport the fix as well?

**Comment by eliasnaur** [comment]
@mmaxim, can you provide exact reproduction steps? I ask because my [scatter.im](https://scatter.im) app went into the App Store (testflight) just fine.

**Comment by mmaxim** [comment]
Unfortunately, I do not have a small repro for this (although I haven't really tried to get one). Right now this just affects when we submit the Keybase (https://github.com/keybase/client) app (which is substantial). We are likely doing something in there that is causing this symbol to get included, but I don't know what it would be. Like I said, it works for us with 1.10.8, but we have been stuck there because of this problem.

Note that before 1.13 we saw `ptrace` in the error from Apple as well, but that is now gone, so that previous fix seemed effective for us on that symbol.

**Comment by mmaxim** [comment]
Also, if you get a patch together at some point, I'd be happy to test it out on Keybase if that would help.

**Comment by eliasnaur** [comment]
What I would like with a reproducer is to avoid the whack-a-mole game of disabling one symbol at a time. Perhaps I can include all syscalls in a synthetic reproducer.

**Comment by mmaxim** [comment]
Yeah that totally makes sense. For what it's worth the error from Apple lists all the offending symbols in our submission. Before 1.13, that list was `ptrace` and `sysctl`. On 1.13, that list is now down to `sysctl`.

**Comment by eliasnaur** [comment]
@mmaxim please test https://golang.org/cl/193843.

**Comment by eliasnaur** [comment]
@gopherbot please consider this for backport to 1.13 to allow Go apps through the App Store checks.

**Comment by mmaxim** [comment]
@eliasnaur sorry for the delay, just got to this today. It worked! Thanks!

**Comment by zx2c4** [comment]
> ITMS-90338: Non-public API usage - The app references non-public symbols in Keybase: ___sysctl

Are you *sure* that ___sysctl is from Go and not from some other library you're pulling in?

I've been shipping Go 1.13-generated binaries in the iOS app store that use sysctl without a problem.

This commit, which was backported to 1.13, wound up breaking `net.InterfaceByName` (operation unsupported, since it uses sysctl under the hood), which means it broke WireGuard.

**Comment by zx2c4** [comment]
I just cloned @mmaxim's keybase client repo, and apparently the issue is actually that it uses a vendored copy of x/sys/unix which uses the non-public symbol `__sysctl`. This is a different symbol than the public symbol `sysctl`. On Go 1.10, which @mmaxim says he was using before, x/sys/unix makes the raw syscall. Beyond 1.10, it uses a jump into libSystem, but improperly.

The issue here seems to be, therefore, with x/sys/unix, not with Go. Go 1.14 and 1.13.3 therefore regress. I'll submit a patch fixing the regression, and @eliasnaur - you can adjust x/sys/unix if you want.
