### ISSUE TITLE
Specification implies assignment is an expression

### ISSUE THREAD

**Issue by fgm** [golang/go#34237]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, doc issue only.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env | sort
AR="ar"
CC="clang"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_ENABLED="1"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
CXX="clang++"
GCCGO="gccgo"
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fgm/Library/Caches/go-build"
GOENV="/Users/fgm/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/p780bc554njc4qj110_8rmbr0000gn/T/go-build495924940=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOMOD=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fgm/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

Navigate to https://golang.org/ref/spec#Operands

### What did you expect to see?

- "The blank identifier may not appear as an operand in an expression."
- "The blank identifier may appear as an operand only on the left-hand side of an assignment, which is not an expression"
- or something equivalent
- or possibly just nothing, as the previous sentence already specifies "An operand may be [...] a (possibly qualified) **non-blank** identifier [...] " (emphasis added)

### What did you see instead?

"The blank identifier may appear as an operand only on the left-hand side of an assignment."

The problem is that this wording, set in the "Expressions" section, implies that assignments are expressions like they are  in some other languages like PHP or JavaScript, although in Go they are instructions but not expressions, as they do not evaluate.

**Comment by mdempsky** [comment]
Thanks for the feedback. However, I think the current wording is okay.

> "The blank identifier may not appear as an operand in an expression."

The blank identifier *can* appear as an operand in an expression; but that expression has to be on the LHS of an assignment.

> "The blank identifier may appear as an operand only on the left-hand side of an assignment, which is not an expression"

This seems unnecessary. Assignments are defined in the statements section, so I'm not sure why a reader would infer maybe they're not actually statements but expressions.

The grammar for Expression also doesn't allow for Assignment (except within function literals).

> The problem is that this wording, set in the "Expressions" section, implies that assignments are expressions

I think this is an unreasonable inference to make as the reader. If the spec defines term T in section A, and the reader should not assume that it instead falls under section B just because it's cross-referenced there.

/cc @griesemer

**Comment by griesemer** [comment]
What @mdempsky said. I believe this is fine.

**Comment by fgm** [comment]
Maybe it's because I'm not a native english speaker, then. The same text translated to french would imply that, so it must have been biasing my reading.
