### ISSUE TITLE
x/tools/gopls: completion breaks with keyword prefixes

### ISSUE THREAD

**Issue by muirdm** [golang/go#34332]
For example:

```go
  variance := 123
  var<>
```

**Comment by sebsebmc** [comment]
I think this is another case where the parser doesn't return an `*ast.Ident` and as a result the text to match against is "". It might be worthwhile to get the preceding token (work backwards until a non [a-zA-Z0-9_] character) as a fallback.

**Comment by sebsebmc** [comment]
In the case of "var", "const", "type", and "import" we get a `*ast.GenDecl` that we can take the token out of and make an `*ast.Ident` to pass to setSurrounding. This at least gets us lexical completions on these keywords. If this seems like a reasonable fix I can submit this patch.

**Comment by muirrn** [comment]
I think the preferred approach is to fix the AST before type checking so type info is as complete as possible (see `fix()` in parse.go).

For accidental keywords I think there are two general cases:

1. Keyword parses properly as in my above example. In this case it parses as an `*ast.ValueSpec` with a single phantom "_" name. We would fix by swapping the parent `*ast.DeclStmt` node with an `*ast.Ident` node.

1. Keyword parses as an `*ast.BadExpr`. This will be much more common, e.g. `someFunc(var)`. This is harder since the BadExpr can wreak arbitrary havoc (e.g. `someFunc(var, foo)` really messes things up). To fix this, I would try something like:
    1. If BadExpr starts with a keyword, alter keyword in source so it no longer is a keyword.
    1. Reparse the containing expression (maybe just reparsing entire file is easier?)
    1. Swap the value of the altered `*ast.Ident` back to the keyword string.

This is easier said than done, though. Probably lots of corner cases and gotchas.

**Comment by atombender** [comment]
I'm still seeing this with latest master:

![gopls2](https://user-images.githubusercontent.com/50314/70194566-d58cbb00-16d0-11ea-98ca-5e67674d0fda.gif)

It is not consistent, but I found a way to consistently reproduce it locally. For me, I can reproduce the issue if I create a file like this:

```
package integration_test

func meh() {
	bad.foo()

	variance := 123
	var // <-- caret
}
```

For me, this triggers the problem in most cases. It appears I need a non-compiling statement in the same file for it to be triggered. (In some cases testing this, I don't get _any_ completions at all, except `var`. I have no idea how to reproduce that, though.)
