### ISSUE TITLE
cmd/go: 'go build -compiler=gccgo' fails silently when the package path is 'm'

### ISSUE THREAD

**Issue by bcmills** [golang/go#34358]
This program silently fails to emit output:

```
cd m
go build -compiler=gccgo

-- m/go.mod --
module m
-- m/hello.go --
package main
func main() { println("hello") }
```

Changing the module path to (seemingly) anything other than `m` causes the test to fail with the symptom in #30344.

If the source file is appropriately located within `GOPATH/src`, varying the value of `GO111MODULE` does not seem to make a difference.

CC @ianlancetaylor @thanm @cherrymui @jayconrod

**Comment by ianlancetaylor** [comment]
This is happening because of the code in `internal/goroot.(*gccgoDirs).isStandard` that tries to determine whether a path exists in the standard library.  The typical set of search directories for Go packages will include `/usr/lib/x86_64-linux-gnu`.  Typically the file `libm.so` will exist in that directory.  That will be enough for `isStandard` to decide that that standard library package exists.

The code there is a replica of what gccgo does internally.  But gccgo goes on to actually open the file and look for gccgo export data.  If it doesn't find any, it moves on.  I think that for purposes of this code it will suffice to only look for .gox files.
