### ISSUE TITLE
x/build/cmd/golangbuild: run subrepo tests from outside their repositories

### ISSUE THREAD

**Issue by bcmills** [golang/go#34352]
(This is essentially the `golang.org/x/[…]` version of #30316.)

`go.mod` files in `testdata` directories cut off the directory from the rest of the module (see #27852). As a result, the corresponding tests are likely to fail.

Unfortunately, at least one of the `golang.org/x` repos already includes such files: I am aware of some in [`golang.org/x/tools/go/packages/testdata`](https://github.com/golang/tools/tree/master/go/packages/testdata/TestName_ModulesDedup/pkg/mod) (CC @heschik, @matloob), and there may be others as well.

Rather than expecting all Go developers to remember to avoid adding extraneous `go.mod` files, we should configure builders and TryBots to run the tests for `golang.org/x` modules outside the module, either in addition to or instead of running them from within a cloned repository.

----

(The simplest alternative I am aware of is to construct a symlink overlay within a temporary directory, as is done in various [`misc/cgo`](https://github.com/golang/go/blob/master/misc/cgo/test/overlaydir_test.go) tests.)

CC @dmitshur @toothrot @bradfitz

**Comment by dmitshur** [comment]
This is implemented in the new build system (LUCI); see https://github.com/golang/go/issues/60666#issuecomment-1650334425. At this point I'm confident we won't go back and implement this in x/build/cmd/coordinator, so closing as wontfix.

**Comment by bcmills** [comment]
> This is implemented in the new build system (LUCI)

The current implementation in LUCI does not appear to be high-enough fidelity to catch the sort of issues that motivated this issue. For example, #65258 is not currently caught by the LUCI builders for the `x/telemetry` subrepo.

Perhaps the tests are currently run from outside their module, but without cutting off the module contents at module boundaries?

At any rate: reopening as “not actually fixed”.

**Comment by dmitshur** [comment]
The reason #65258 is not currently caught by the LUCI builders is because the current implementation requires there not to be local replace directives, and x/telemetry is one of the 3 repos that do and their owners have decided to opt out of this behavior. See [here](https://source.chromium.org/chromium/infra/infra/+/main:go/src/infra/experimental/golangbuild/testmode.go;l=320;drc=f6b3cdea96054392c30f32f53a10ac0038694a42). If the local replace directive is removed and x/telemetry owners would like this check to apply, it's a matter of removing "telemetry" from `keepNestedModsInsideRepo`, but to my knowledge they had no such plans when I last asked.

**Comment by dmitshur** [comment]
This feature was implemented in LUCI and is working for the repos that haven't opted out.
I filed #65267 to track a way of improving it that I'm aware of.

Retitling for LUCI, and closing as fixed via [crrev.com/c/4598622](https://crrev.com/c/4598622) (and [crrev.com/c/4651891](https://crrev.com/c/4651891)).
Please file a new issue if something else comes up, and refer to this one if needed.
