### ISSUE TITLE
x/tools/internal/lsp: Reuse code for other language server

### ISSUE THREAD

**Issue by slrtbtfs** [golang/go#34404]
Hi,

I'm currently working on building a language server for PromQL written in golang.
I plan to reuse large parts of the gopls code for that.

Because most of the code resides in go/tools/internal I will probably have to copy everything to another repo.

Another issue is that gopls is currently designed in a way that the language agnostic code imports the language specific code.

At the same time I'd like to sync my own code base with the one of gopls as much as possible and be also able to contribute my changes back upstream if appropriate.

Are there any Ideas of what would be the best way to handle this?

**Comment by stamblerre** [comment]
What specific packages are you interested in? I imagine you would mostly be interested in the protocol and jsonrpc2 packages?

We're definitely considering making them public at some point (see https://github.com/golang/go/issues/31080), but they are still very much in flux, which is why we haven't yet. I think I would suggest vendoring those packages for now, and then at some point you will be able to import them directly. If you have changes you're interested in making, feel free to send them our way (though it's worth noting that the protocol page is generated code).

**Comment by ianthehat** [comment]
Happy to work with you on this, but as Rebecca said be warned that we are going to be making major changes to many of the packages you might be interested in. jsonrpc2 is probably fairly stable, protocol is not because we need to change it to improve the cancellation behaviour, and the stuff above that is all in flux. We may well make some/all of the packages public in the future, for now they are in internal specifically because we need to be able to make breaking changes all the time.

There are some changes planned that will help in the future as well, as we need to support other "languages" in gopls (go.mod files need to be their own language for instance, as do go template files), and we would happily upstream changes that help you extract only the bits you need as they will probably tend towards cleaner overall architecture if done right anyway.

There are multiple other people "vendoring" some of the packages for other uses, we are fine with that.

Github issues are probably not the easiest mechanism to talk, feel free to reach out to us by [email](iancottrell@google.com), or in [slack](http://gophers.slack.com/) or whichever mechanism you would like to talk some more, we can also video conference if you want to discuss something.

Going to close this issue as it is not really an issue we can take action on, but please do reach out to us to talk some more.
