### ISSUE TITLE
proxy.golang.org: "410 Gone" on tag publicly available for 50 days

### ISSUE THREAD

**Issue by MMulthaupt** [golang/go#34402]
### What version of Go are you using (`go version`)?

<pre>
go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/martin/.cache/go-build"
GOENV="/home/martin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/martin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/martin/gitlab/godown-builder/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build504237898=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Write a go.mod with one of these entries:
`require github.com/shirou/gopsutil v2.19.8+incompatible` ([Released Sep 1](https://github.com/shirou/gopsutil/releases/tag/v2.19.8))
`require github.com/shirou/gopsutil v2.19.7+incompatible` ([Released Jul 31](https://github.com/shirou/gopsutil/releases/tag/v2.19.7))

### What did you expect to see?

`go: finding github.com/shirou/gopsutil v2.19.8+incompatible`

### What did you see instead?

`verifying github.com/shirou/gopsutil@v2.19.8+incompatible/go.mod: github.com/shirou/gopsutil@v2.19.8+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/shirou/gopsutil@v2.19.8+incompatible: 410 Gone`

### Additional Information

`v2.19.6` does work, and has no changes to [the project's](https://github.com/shirou/gopsutil) structure (i.e., still has no `v2` subdirectory):
`require github.com/shirou/gopsutil v2.19.6+incompatible` ([Released Jun 27](https://github.com/shirou/gopsutil/releases/tag/v2.19.6))

**Comment by heschik** [comment]
From https://sum.golang.org/lookup/github.com/shirou/gopsutil@v2.19.8+incompatible: `not found: github.com/shirou/gopsutil@v2.19.8+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required`.

This is new validation in 1.13; see "Version validation" in https://golang.org/doc/go1.13 for details. `v2.19.6+incompatible` is present because it was added before `sum.golang.org` was upgraded to 1.13.

Closing, since everything here is working correctly. gopsutil will need to add the necessary /v2 suffix to its go.mod and use non-+incompatible versions, or remove its go.mod entirely.
