### ISSUE TITLE
What's the right syntax for parameterizing the column name in a WHERE ... IS NOT NULL query?

### ISSUE THREAD

**Issue by mcandre** [golang/go#34406]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.12 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tkmamhf/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tkmamhf/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/tkmamhf/.gvm/gos/go1.11.12"
GOTMPDIR=""
GOTOOLDIR="/Users/tkmamhf/.gvm/gos/go1.11.12/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y6/dbk1vvs179nbpfv38j__10b5rsnf87/T/go-build724406931=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
name := "project"

rows, err := pool.Query(
	`
		SELECT DISTINCT ? AS element
		FROM ?
		WHERE ? IS NOT NULL
	`,
	name,
	"charge_green",
	name,
)
```

### What did you expect to see?

The query returns results, replacing each of the question marks with the corresponding Go arguments to `Query()`.

### What did you see instead?

Go mangles the last `?` and actually sends that raw to MySQL, which of course complains about invalid syntax.

### Workaround

In order to resolve this Go standard library oddity, I am currently using `fmt.Sprintf` to generate the query. This works for this small example, but significantly increases the risk of system compromise by SQL injection.

### Related

Originally, I tried to accomplish this using the upper ORM, but that API does not currently support `DISTINCT` on select columns:

https://github.com/upper/db/issues/338

**Comment by OneOfOne** [comment]
I ran into that recently, the best I could come up with was checking column and/or table names with `if strings.ContainsAny(name, ";()$%{}") { return error }`.

**Comment by toothrot** [comment]
We don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions.

In this case, most databases do not support placeholder values for table or column names. For column and table names, you probably want to be whitelisting which ones are valid, regardless, and not using any kind of user input. `fmt.Sprintf` with one of your whitelisted names is likely your safest bet, but this advice is provided without warranty of any kind.
