### ISSUE TITLE
x/sys/unix: ___getdirentries64 results in app store rejections

### ISSUE THREAD

**Issue by zx2c4** [golang/go#34400]
While the fix for https://github.com/golang/go/issues/30933 addressed go/syscall, it didn't address x/sys/unix. Meanwhile the fix for https://github.com/golang/go/issues/28984 addressed go/syscall and x/sys/unix, but that's just for arm (iOS).

In order to fully fix things, the x/sys/unix patch for iOS needs to apply to macOS too.

CC @eliasnaur

**Comment by eliasnaur** [comment]
Thanks for making sure this is not forgotten. I don't intend to work on this, but perhaps a fix can be pieced together from https://golang.org/cl/168479 and https://golang.org/cl/170892.

**Comment by tklauser** [comment]
> ...but perhaps a fix can be pieced together from https://golang.org/cl/168479 and https://golang.org/cl/170892.

I sent https://golang.org/cl/196478 doing that.

This works fine for Go 1.12, but unfortunately `x/sys/unix` also provides compatibility funcs for Go 1.11 where we still use raw syscalls instead of libSystem. I'm not sure how to solve this there. Any ideas? Do we still need to support Go 1.11 in `x/sys/unix` now that Go 1.13 is out?

/cc @bradfitz @ianlancetaylor @randall77

**Comment by bradfitz** [comment]
Arguably Go 1.11 users can use modules already, so we don't _really_ have to keep GOPATH mode working for them (they can pin an older version). I'm okay removing that support if that's much easier.

But if a bit of build tag work keeps Go 1.11 around for another release, that'd be ideal.

**Comment by tklauser** [comment]
> But if a bit of build tag work keeps Go 1.11 around for another release, that'd be ideal.

Thanks, I think I found a way do solve it using some additional Go version specific files and build tags, ptal at https://golang.org/cl/196478
