### ISSUE TITLE
x/build/cmd/tip: false positive in health check

### ISSUE THREAD

**Issue by bsiegert** [golang/go#34526]
I just noticed on farmer.golang.org that there is an error in tip status monitoring. As of now, https://farmer.golang.org/status/tip says:

```
# "tip" status: tip.golang.org website
# Notes: https://github.com/golang/build/tree/master/cmd/tip
Error: _tipstatus page reports error: builder.Init: checkout of go: reset: fatal: Could not parse object 'a3426f2571bc6f6e55f70ad7a0e7198ecdeb10e4'.
```

/cc @adg

**Comment by dmitshur** [comment]
Thanks for reporting.

I've looked into this and it seems to be a false positive in the health check. The https://tip.golang.org website is currently deployed at the correct version and functioning properly. So the problem is with the health check, not tip.golang.org. I'll update the issue accordingly.

**Comment by dmitshur** [comment]
I've found the root cause. This was a fun one. :)
