### ISSUE TITLE
x/build/cmd/tip: version information and /_tipstatus page are not easily discoverable

### ISSUE THREAD

**Issue by bradfitz** [golang/go#34531]
https://tip.golang.org/ used to show version info in its footer:

http://web.archive.org/web/20180403104659/https://tip.golang.org/

We lost that in the redesign.

/cc @andybons

**Comment by andybons** [comment]
What's the value of having it there? To ensure that it's actually at tip?

**Comment by bradfitz** [comment]
Yes, whether it's at tip, but also to see where it's at for local repros of things. So you can git reset to that exact spot.

Also, it broadcasts to other readers that this is an ugly/debug/temporary version.

**Comment by andybons** [comment]
Gotcha. So to be clear. _Only_ show it on tip as it’s useful for debugging. Thanks for the context.

**Comment by dmitshur** [comment]
I'm not against showing the version in the footer on https://tip.golang.org more visually. However, there are other ways of getting this information.

> So you can git reset to that exact spot.

For this purpose, the [/_tipstatus](https://tip.golang.org/_tipstatus) endpoint is more useful, because it shows the commit of Go and x/website. Both are important if one cares about knowing the exact version of the website that was deployed.

Additionally, the version information is still a part of the website source:

```
 $ curl -s 'https://tip.golang.org/' | grep goVersion
<script>var goVersion = "devel +225f484 Wed Sep 25 23:27:16 2019 +0000";</script>
```

Finally, godoc.org used to scape the version from the footer, and had to be updated when the footer changed. See [CL 193258](https://golang.org/cl/193258). (It's only relevant once every 6 months when a major Go release is made, so it wasn't worth making a bigger change.)

**Comment by bradfitz** [comment]
> For this purpose, the /_tipstatus endpoint is more useful,

I wrote that handler and I can't remember its URL.

I'd still like it to be human-visible. Perhaps it could even link to /_tipstatus.

**Comment by dmitshur** [comment]
This issue was not really resolved, but `golang.org/x/build/cmd/tip` was deleted in [CL 343449](https://golang.org/cl/343449), so closing.
