### ISSUE TITLE
[Feature Request] Add Encryption/Decryption to ECDSA & ED25519

### ISSUE THREAD

**Issue by vzool** [golang/go#34566]

**Comment by bcmills** [comment]
This issue in its current form does not have enough detail to be a [proposal](https://golang.org/s/proposal-process).

If you want to describe a general area for improvement, please add an [experience report](https://golang.org/wiki/ExperienceReports) instead.

Otherwise, please describe the specific changes you would like to see, including the motivation or background, syntax or API signatures, and concrete examples (ideally drawn from experience reports).

**Comment by vzool** [comment]
Hi, I'm looking to use an **ed25519 signing keys** for encryption.
Golang has a `crypto/ed25519` and `crypto/ecdsa` libraries which both of them conclude functions to do:  key generation, signing and verify the signature. But there are no **encryption/decryption** for both of these neat algorithms. So, this is my proposal in a nutshell. ^_^

**Comment by FiloSottile** [comment]
Ed25519 is an instantiation of EdDSA. DSA in both EdDSA and ECDSA means "Digital Signature Algorithm", so they can only be used for signing.

You could convert Ed25519 keys to Curve25519 to then do Ephemeral-Static Diffie-Hellman, but that's not going to always be safe, and I recommend you seek the advice of a cryptography engineer. The standard library won't provide such unsafe tools. https://blog.filippo.io/using-ed25519-keys-for-encryption/

**Comment by zigazeljko** [comment]
Which algorithm exactly did you have in mind? As far as I know, elliptic curves can't be directly used for encryption/decryption, at least not in a way RSA keys can be (if that's what you were thinking of).

**Comment by vzool** [comment]
There are many practical implementations on the web using elliptic curve keys in encryption, e.x:
- [bitchan/eccrypto](https://github.com/bitchan/eccrypto): JavaScript Elliptic curve cryptography library
- [go-ethereum/crypto/ecies](https://github.com/ethereum/go-ethereum/blob/master/crypto/ecies/ecies.go): Ethereum used it at full scale
