### ISSUE TITLE
wiki: reinsert FileTree page

### ISSUE THREAD

**Issue by apparluk** [golang/go#34590]
a wiki page was renamed absent opening an issue

to the purpose solely of shortening the URL 

the administrators subsequently deleted that renamed page

if "what's in $GOROOT and where" remains relevant hosted on the wiki

perhaps the page could be reinserted

or a new page created with that name, the original content I kept a copy of

evidently I neglected to read the [Contributing](https://github.com/golang/go/wiki#contributing) section

and only read the Notes under [Release Specific Information](https://github.com/golang/go/wiki#release-specific-information)

**Comment by dmitshur** [comment]
Thanks for letting us know. It may have been removed unintentionally, because it's harder to see full history for a page after it's renamed. /cc @bcmills

I've reinstated the page and returned it to its original `FileTreeDocumentation.md` name for now (but we may still re-evaluate whether it's a page worth keeping).

As you're aware by now, please only rename wiki pages after discussing and getting approval first. Renaming pages makes their history harder to see and may break external links, so we don't do it very often. Thanks again!
