### ISSUE TITLE
x/mobile/bind: TestGenGo failing due to changes in gofmt output

### ISSUE THREAD

**Issue by bcmills** [golang/go#34619]
The fix for #28082 changed the line-wrapping behavior of `gofmt` in some cases.

One of those changes happens to affect `x/mobile/bind.TestGenGo`, which is asserting a particular golden `gofmt` output (rather than more robustly running both the actual and expected outputs through `gofmt` before comparing them).

CC @griesemer @eliben @odeke-em @steeve @hyangah

**Comment by bcmills** [comment]
https://build.golang.org/log/6ba5c04b305b616cd48d78819d7753a2e7fc2d83

**Comment by eliben** [comment]
Rewriting the tests to do this in a more robust way is a bit tricky due to the way they are structured. In particular `TestGenGoJavaWrappers` arranges to emit multiple packages into the same file, and compares the emitted file to the equivalent `.golden` file.

For example, https://github.com/golang/mobile/blob/master/bind/testdata/java.go.golden has multiple packages in it. We can't just run this file through the formatter because `format.Source` chokes on it upon finding a `package` in an unexpected place.

The test generates some go code *without* gofmt-ing it first, which includes multiple packages (in `genJavaPackages`)

**Comment by eliben** [comment]
A couple of possible solutions:

1. Hacky but relatively simple: when reading the golden file, find `package main` and only reformat that package, leaving the rest of the code unformatted, as today. `package main` comes at the end of the file, so it's easy.

2. More robust, but entails a significant restructuring of `bind_test`: don't generate packages into the same file with the main Go code. Generate them (`genJavaPackages`) into a separate golden file, that gets compared separately. So instead of a single golden file per test, there will be two - and the two are compared separately. The one where the main Go code is generated will pass through `format.Source` for stability.

**Comment by hyangah** [comment]
I will send a cl soon. It is a major change though since the reverse
binding doesn't do formatting, it turned out.
