### ISSUE TITLE
Mockable http.Client ( should be an interface not a type )

### ISSUE THREAD

**Issue by SreeshaKS** [golang/go#34699]
Http.Client should be an interface not a type. Helps in mocking http.Client for testable code.

**Comment by mdlayher** [comment]
This can't be changed today due to the Go 1 compatibility promise, and even then, there would have to be a much stronger argument for this change for it to be considered for a future Go 2 or similar.

You can create an interface in your own code to swap out methods of an HTTP client. There's no need for it upstream.

Closing since I don't think there's much substance here and nothing can be done today.

**Comment by odeke-em** [comment]
In addition to what @mdlayher said, http.Client has a https://golang.org/pkg/net/http/#Client.Transport field which is an http.RoundTripper https://golang.org/pkg/net/http/#RoundTripper, now that's what is usually used to mock responses with the RoundTrip method.
