### ISSUE TITLE
x/blog: Error in defer-panic-and-recover article

### ISSUE THREAD

**Issue by Xerock** [golang/go#34690]
### What did you expect to see?
```
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    defer src.Close()
    if err != nil {
        return
    }

    dst, err := os.Create(dstName)
    defer dst.Close()
    if err != nil {
        return
    }

    return io.Copy(dst, src)
}
```
### What did you see instead?
```
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    defer src.Close()

    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    defer dst.Close()

    return io.Copy(dst, src)
}
```
With the current code example, in the case of a non-nil error, the defer isn't stacked before the return occurs, so the function will return without closing the source file.

Little program to prove my point : https://play.golang.org/p/UAdMVffys_P

**Comment by bcmills** [comment]
This aspect of the example is correct and idiomatic as written.

Like most Go functions, `os.Open` and `os.Create` return zero-values (in this case, nil pointers) for the other arguments when they return a non-nil `error`, and calling `Close` on a nil receiver is generally nonsensical.

In this case, the nonsensical call is masked by the permissiveness of `(*os.File).Close`. Rather than panicking (as many `Close` implementations would), it returns `ErrInvalid`:
https://github.com/golang/go/blob/fc705275c34233ffc1cb34be965f289589de9ba6/src/os/file_unix.go#L230-L232
