### ISSUE TITLE
When using iota, the logic is confused. Is that a bug?

### ISSUE THREAD

**Issue by chezixin** [golang/go#34719]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chezixin/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chezixin/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mr/_x323k891dq9yvmvlgwqf4f40000gn/T/go-build490011880=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

package main

import "fmt"

type T struct {
	Name  string
	Port  int
	State State
}

type State int

const (
	Running State = iota
	Stopped
	Rebooting
	Terminated
)
func (s State) String() string {
	switch s {
	case Running:
		return "Running"
	case Stopped:
		return "Stopped"
	case Rebooting:
		return "Rebooting"
	case Terminated:
		return "Terminated"
	default:
		return "Unknown"
	}
}

func main() {
	t := T{Name: "example", Port: 6666}
	fmt.Printf("t %+v\n", t)
}

###Result：
t {Name:example Port:6666 State:Running}

### What did you see instead?
Although string is rewritten, this is related to State. const.
I print T struct in main. Zero is 0.
But why do we show State:Running?
When T. State = 0, why does the program think T. State = const. Running?
I understand it as follows:
String is an interface type, T. State = 0, const. Running = 0. The two types are the same, the value is the same. Does the program think that the two are equal? Do you not distinguish const from struct at the moment?
Logically, const and struct should be distinguished, but the program thinks they are equal. Is that a bug? Or did I go into a misunderstanding?
Can you tell me how to understand it correctly?
Thanks very much
Thank you

**Comment by DisposaBoy** [comment]
I'm not sure I understand the problem/question, but it's been helpful in the past to state the obvious, so...

`State` implements https://golang.org/pkg/fmt/#Stringer so when you print it, the `fmt` package will call `State.String()` to get its *printable* value instead of printing its underlying value.

**Comment by smasher164** [comment]
As @DisposaBoy has stated, this is because any integral value for State will get stringified when printed with `%+v`, in this case the zero-value value of State is set, so `Running` will be printed instead. See https://yourbasic.org/golang/iota/

For more questions about Go, please feel free to ask it in any of these forums below:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks

**Comment by chezixin** [comment]
@DisposaBoy  
Thank you very much for answering my question.
I built State. String (), but this is only about const.
In switch logic, case judges const.
Why is it related to T (struct)?
This is where I can't figure it out. In switch, the program uses struct = const?
I think Unknown should be printed because the names of the two are different. Can't you tell names when you use iota?

I hope you can help me again.

**Comment by chezixin** [comment]
@smasher164    Thank you very much. The article you recommended is very helpful. Thank you.

**Comment by smasher164** [comment]
Here's an runnable example that demonstrates what I'm talking about: https://play.golang.org/p/GXFC04aBV_2

The switch doesn't see a struct, it still sees the State value. However, when passed the format specifier `"%+v"`, the fmt package will reflect on the struct and recursively print all of a struct's members, calling its String() method if it's available. To not see this behavior, use a format specifier like `"%#v"` instead.
