### ISSUE TITLE
cmd/compile: unexpected write barrier for 1-element slice literal

### ISSUE THREAD

**Issue by cuonglm** [golang/go#34723]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +fc8bef06c4 Sun Oct 6 00:33:51 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cuonglm/Library/Caches/go-build"
GOENV="/Users/cuonglm/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cuonglm/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cuonglm/sources/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cuonglm/sources/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y4/hs76ltbn7sb66lw_6934kq4m0000gn/T/go-build978643304=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ cat t.go
package t

func f25() []string {
	return []string{"a"} // no write barrier here
}

func f26() []string {
	return []string{"a", "b"} // no write barrier here
}
$ go tool compile -d=wb t.go
t.go:4:17: write barrier
```

### What did you expect to see?

No write barrier emitted

### What did you see instead?

Write barrier emitted in `f25`.

**Comment by randall77** [comment]
I see `f26` has the write barrier, and `f25` doesn't.

I think what's happening here is a failure of the zero-memory tracking. The write barrier removal here requires the compiler to know that the target memory is zeroed.

The zero-memory tracking fails because we write the strings out of order (first length, then pointer).  The zero-memory tracker keeps only a single range for each object, so when writes occur to the middle of a zero range it has to throw away the remainder.

I think we just need to update the zero tracker to handle a few ranges. Maybe a bitmap. I'll investigate.

**Comment by randall77** [comment]
> I see f26 has the write barrier, and f25 doesn't.

Sorry, my bad, it is f25 that has the write barrier.

**Comment by av86743** [comment]
https://github.com/golang/go/blob/master/src/cmd/compile/internal/ssa/writebarrier.go#L381 : [CL](https://golang.org/cl/199558) turns range into map.
```
	// This analysis is conservative. We only keep track, for each memory state, of
	// a single constant range of a single object which is known to be zero.
```
