### ISSUE TITLE
x/build: where'd the Go 1.13 nacl builders go?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#34738]
https://build.golang.org/?branch=release-branch.go1.13 has empty cells for the nacl builders.

They should still be running for Go 1.13. Where'd they go?

x/build/dashboard/builders_test.go has:

```go
                {b("nacl-386", "go"), none},
                {b("nacl-386@go1.13", "go"), onlyPost},
                {b("nacl-386", "net"), none},
                {b("nacl-amd64p32", "go"), none},
                {b("nacl-amd64p32@go1.13", "go"), both},
                {b("nacl-amd64p32", "net"), none},
```

Suggesting that they should still be tested for Go 1.13, and the test passes.

So where'd they go?

/cc @andybons @dmitshur @bcmills

**Comment by bcmills** [comment]
Looks like they disappeared at some point in between CL 193269 (Sep. 5) and CL 193264 (Sep. 11).

**Comment by dmitshur** [comment]
They're also not running on release-branch.go1.12, last run was on Sep 6.

Coordinator was last deployed 19 days ago (Sep 18~).

The last run on master branch was on Aug 30 (https://build.golang.org/?page=13&branch=master).

**Comment by dmitshur** [comment]
The problem turned out to be an incompatible intersection of behaviors across `cmd/coordinator` and `app/appengine` (and serves as further motivation to merge the two codebases into one, made issue #34744).

[CL 192537](https://golang.org/cl/192537) modified `cmd/coordinator` to stop running nacl builders on master branch, and only run on release-branches older than 1.14.

However, `app/appengine` determines a list of builders by checking which builders report positively for `bc.BuildsRepoPostSubmit("go", "master", "master")`:

```Go
for name, bc := range dashboard.Builders {
	if !bc.BuildsRepoPostSubmit("go", "master", "master") {
		continue
	}
	builders[name] = true
}
```

_([Source](https://github.com/golang/build/blob/c41ee31c2ed1caabb143ad39d536b27087620bfc/app/appengine/ui.go#L367-L369).)_

So the nacl builders got unintentionally filtered out (see "builders" field in https://build.golang.org/?mode=json). That means `findWork` never considers them, even for release-branches.

---

I also found an unrelated problem in the `TestBuilderConfig` test. It wasn't a cause for this issue, but we should improve `TestBuilderConfig` anyway to remove a potential pitfall and code-readability distraction.

<details><summary>Problem in <code>TestBuilderConfig</code> test</summary><br>

The `b` helper is documented as:

```Go
// builder may end in "@go1.N" (as alias for "@release-branch.go1.N") or "@branch-name".
// repo may end in "@1.N" (as alias for "@release-branch.go1.N")
b := func(builder, repo string) builderAndRepo {
```

It's doing:

```Go
expandBranch(&br.branch)
expandBranch(&br.goBranch)
if br.repo == "go" {
	br.branch = br.goBranch
}
```

That means when the repo is "go", a line like `b("nacl-386", "go@1.13")` would be misinterpreted. The "@1.13" suffix would be dropped/overwritten, and "master" would be used instead.

</details>

**Comment by dmitshur** [comment]
I deployed [CL 199800](https://golang.org/cl/199800) and it was sufficient to resolve this issue.

![image](https://user-images.githubusercontent.com/1924134/66415223-1dd97680-e9c9-11e9-87eb-3b87dd6834cd.png)
