### ISSUE TITLE
x/build/{cmd/coordinator,app/appengine}: combine codebases

### ISSUE THREAD

**Issue by dmitshur** [golang/go#34744]
We've discussed and agreed wanting to merge `app/appengine` into `cmd/coordinator`. The motivation is to have a single codebase, share more code, fewer separate deployments, and tests with more inclusive coverage.

I didn't find an existing issue, so making this one to track the task.

/cc @bradfitz @andybons @toothrot

**Comment by bradfitz** [comment]
I regret that I have but four emojis to give to this bug.

**Comment by bradfitz** [comment]
This is getting pretty close now.

Here's a suggested roadmap for finishing this:

* add an HTTP handler to the coordinator for removing build results. Currently there are only two things remaining that POST to the dashboard (the build.golang.org App Engine app): the coordinator itself, and x/build/cmd/retrybuilds. If we want to get to the coordinator knowing the world state (including keeping the work list in memory), we can't have retrybuilds reaching behind its back and writing to the datastore directly. So we should for now add a proxy handler to the coordinator that just proxies the `/clear-results` path to build.golang.org. Then change `retrybuilds` to use the `farmer.golang.org` hostname instead of `build.golang.org`.

* change the coordinator's `findWork` to not hit the dashboard but instead do the maintnerd GetDashboard API call itself. This'll need to start doing datastore Get calls (to either golang-org's GCP project w/ new service account, or migrate the data, which seems unnecessarily painful)

* modify the coordinator's `/clear-results` handler to do the datastore deletion itself. (And it can then also immediately start the replacement work, to rebuild whatever was cleared, without waiting for `findWork` to run)

* add a JSON handler to the coordinator that lists all the active post-submit builds

* drop the dashboard memcache code for `buildingURLs` (the blue gophers that render on the dashboard for in-progress builds) and instead hit the new JSON endpoint to figure out what's in progress. This then removes all memcache usage in the dashboard, which isn't (as easily) available in the new App Engine Go 1.12+ runtimes.

* update app/appengine from the App Engine datastore package to the Cloud (cloud.google.com/go/datastore) package. This is required to update to the App Engine Go 1.12 runtime. Do that to verify it all works.

* move the app/appengine UI code to a shared spot and make the coordinator also capable of running that handler. Now that it's using cloud.google.com/go/datastore, this should be trivial. Make an HTTP mux that routes to the dashboard UI handler based on Hostname. Say, if `hostname == "build.golang.org" || hostname == "farmer-ui-test.golang.org".

* create DNS record `farmer-ui-test.golang.org` to test that it works.

* change the `build.golang.org` DNS record.

* delete the App Engine app

**Comment by toothrot** [comment]
I've been making some progress on this. I want to add a note to capture @dmitshur's comments in https://golang.org/cl/221920: we should improve how we handle static files.

I did a minimal amount. I think moving them into a static directory and using `go generate` as we do on other projects is a good solution, but we should somehow cause a build failure for a misconfiguration.

**Comment by dmitshur** [comment]
I've been able to pick this up and make good progress this week. My focus is on getting this to a point where the build dashboard is served by cmd/coordinator, so that it's a single deploy rather than 2, and to be able to skip APIs in favor of simpler same-process code.

I've updated the roadmap in the comment above (https://github.com/golang/go/issues/34744#issuecomment-563398753) to make it more visible what's already been done (which is a lot), and came up with a faster path to the single-process milestone. (We can still do clean up and new features, but that can be done later and doesn't need to block the process unification.)

The app/appengine application by now has very few inputs: 
- It uses cloud APIs to access Datastore
- Maintner API for git repository info
- Gets a master builder key from datastore (via the x/build/app/key package)

We have access to all that in the coordinator. So, it's viable to convert app/appengine from a command into a library with a minimal code diff, integrate that into coordinator codebase, and get all that tested and deployed. The //go:embed directive also makes it much easier to deal with static files. I'm mailing a stack of CLs for that soon.

**Comment by dmitshur** [comment]
The stack up to [CL 336791](https://golang.org/cl/336791) has been submitted and deployed. The new coordinator-powered dashboard is being served at https://farmer-ui-test.golang.org.

I'm not spotting any problems in my testing so far, so the next step will be to flip the DNS of build.golang.org over to be served by cmd/coordinator as well. If all goes well, the appengine code base can then be deleted (that's [CL 336792](https://golang.org/cl/336792)).

**Comment by dmitshur** [comment]
Flipping the DNS has been done (in a somewhat bumpy way, see #47580, but it's resolved now).

Coordinator needed additional permissions to be able to write build results, which has also been resolved by now.

The stack up to [CL 340434](https://golang.org/cl/340434) is mostly reviewed but awaiting a few more reviews. We should be able to proceed with it landing it, making sure everything still works, and then this issue can be considered resolved.

**Comment by dmitshur** [comment]
This is now live and submitted to x/build. Notably:

[CL 340433](https://golang.org/cl/340433) reconfigured coordinator to use the build.golang.org URL as the dashboard.  
[CL 336792](https://golang.org/cl/336792) deleted the old app/appengine codebase.  
[CL 340434](https://golang.org/cl/340434) updated documentation to reflect the new state.

[CL 340435](https://golang.org/cl/340435) was a cherry on top, bringing a small enhancement to the now-served-by-coordinator build dashboard.

Filed #47630 for some trivial clean up that can happen (after waiting a bit).   
Other than that, woohoo, this is done! 🎉  🚀

**Comment by zikaeroh** [comment]
After the change, I've noticed that the styling is broken in a few ways, like links being a different color, and the top bar looking like:

![image](https://user-images.githubusercontent.com/48577114/128929407-9b117cd5-6377-45b9-b1d5-44f654326679.png)

I assume you want a new issue to track those regressions?

**Comment by dmitshur** [comment]
@zikaeroh Sure, a new issue would be fine. However, in this case I believe it's just a matter of CSS caching. If you refresh the page it should be okay.

**Comment by zikaeroh** [comment]
Indeed, thanks. I had assumed it was a bug because it was like that for the past day or so, but it worked on a refresh just after you replied. Sorry for the noise. 🙂
