### ISSUE TITLE
x/tools/go/packages: IgnoreFuncBodies implementation and comment mismatch

### ISSUE THREAD

**Issue by zhangyoufu** [golang/go#34806]
https://github.com/golang/tools/blob/567d1c21dc5f922038933aa862c0719a9768eb83/go/packages/packages.go#L827-L830
```go
// Type-check bodies of functions only in non-initial packages.
// Example: for import graph A->B->C and initial packages {A,C},
// we can ignore function bodies in B.
IgnoreFuncBodies: ld.Mode&NeedDeps == 0 && !lpkg.initial,
```

The comment and the given example is self-contradictory. The implementation is actually `type-check bodies of functions only in initial packages`.

---

For my use case, I would appreciate if `IgnoreFuncBodies` could be somehow controlled by `packages.Config`.

I have a script (invoked by `go generate`) parsing source code, harvesting struct definition and generating serialization-related code for those structs. Due to lack of serialization-related code, the type-checking for function bodies always fail because those structs does not implement my serialization interface yet.

I don't have any assertions like `var _ MySerializationInterface = MyStruct{}`. So as long as I can turn `IgnoreFuncBodies` on, everything works for me.

**Comment by adonovan** [comment]
There isn't currently a way to control this field directly, but there are various ways to achieve what you want. The simplest is to supply a ParseFile function to the Config that invokes the parser as normal, and then destroys the function bodies:

```
        // Eliminate bodies of top-level functions, methods, inits.
        for _, decl := range file.Decls {
                if fn, ok := decl.(*ast.FuncDecl); ok {
                        fn.Body = nil
                }
        }
```

Another would be to ignore any type error that is located within a function body.  Or to ignore certain kinds of error message.

You may need to take the last approach because there are likely to be declarations outside of function bodies that assign your struct values to interfaces types (e.g. `var v I = newMyStruct()`) so destroying function bodies may not be sufficient to suppress all errors.

https://go-review.git.corp.google.com/c/tools/+/452578 fixes the documentation. Thanks for pointing that out.
