### ISSUE TITLE
_cgo_export.c:1:0: error: -fPIC ignored for target (all code is position independent) [-Werror]

### ISSUE THREAD

**Issue by Zhangzijing** [golang/go#34871]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\i\AppData\Local\go-build
set GOENV=C:\Users\i\AppData\Roaming\go\env
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=linux
set GOPATH=E:\Sync\onedrive_pluvet\OneDrive - bupt.edu.cn\Code\MemoriBackend;C:\Go;C:\Users\i\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=C:\Users\i\AppData\Local\Temp\go-build664142882=/tmp/go-build -gno-record-gcc-s
witches
</pre></details>

### What did you do?

I'm trying to build for linux
```cmd
mkdir bin 
set GOOS=linux
set GOARCH=amd64
set CGO_ENABLED=1
go get -x
go install -x
```

### What did you expect to see?

Success

### What did you see instead?

```cmd
go build
# runtime/cgo
_cgo_export.c:1:0: error: -fPIC ignored for target (all code is position independent) [-Werror]
 /* Code generated by cmd/cgo; DO NOT EDIT. */
 ^
cc1.exe: all warnings being treated as errors

```

**Comment by dmitshur** [comment]
Hello,

Setting up your Windows system to enable cross-compilation to Linux can be tricky, and I suspect you're running into a problem due to misconfiguration there. Take a look at the [WindowsCrossCompiling](https://golang.org/wiki/WindowsCrossCompiling) wiki page for more information on this topic.

We use this issue tracker for tracking bugs in Go, and this doesn't seem to be one, so I'll close this. If it turns out to be a bug, please provide more specific information and we can re-open.

For asking questions, please see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* IRC channel #go-nuts on Freenode
