### ISSUE TITLE
x/build/cmd/gopherbot: semantically recognize Go<VERSION> in backport messages instead of opening backports for all 

### ISSUE THREAD

**Issue by odeke-em** [golang/go#34887]
Coming here from issue https://github.com/golang/go/issues/34878#issuecomment-541459144 in which I used `<BOT> please backport this issue to Go1.13.` but the bot opened up issues to Go1.12 and Go1.13 and then afterwards I commented to try to close other issues which then caused another set of backporting issues to be opened https://github.com/golang/go/issues/34883 https://github.com/golang/go/issues/34884.

This issue is to request that we understand not only `1.13` but also `Go1.13` which I typed because I wasn't fully aware of the syntax. Thanks @bradfitz for encouraging me to file a bug about this in https://github.com/golang/go/issues/34881#issuecomment-541503060.

**Comment by bradfitz** [comment]
The current code always does past two releases, unless you want it to do three, I guess:

```go
                majorReleases, err := b.getMajorReleases(ctx)
                if err != nil {
                        return err
                }
                var selectedReleases []string
                for _, r := range majorReleases {
                        if strings.Contains(backportComment.Body, r) {
                                selectedReleases = append(selectedReleases, r)
                        }
                }
                if len(selectedReleases) == 0 {
                        // Only backport to major releases unless explicitly
                        // asked to backport to the upcoming release.
                        selectedReleases = majorReleases[:len(majorReleases)-1]
                }
```

**Comment by bradfitz** [comment]
So perhaps the feature request here is to add a way to only backport to the most recent.

**Comment by dmitshur** [comment]
> the bot opened up issues to Go1.12 and Go1.13

A number like "1.13" is enough. There isn't a need for a space in front or after. This is because `getMajorReleases` returns strings like `[]string{"1.9", "1.10", "1.11"}`.

The reason gopherbot opened both issues is because it looks in the entire comment body, and you had mentioned 1.12 in the paragraphs above, before asking gopherbot.

Improving that is tracked in issue #27489.

> which then caused another set of backporting issues to be opened

This is a separate issue and is tracked in #32533.

I'll close this because all of the problems described here are covered by more specific existing issues.
