### ISSUE TITLE
vendor\golang.org\x\net\idna\idna10.0.0.go:46:6: ToASCII redeclared in this block

### ISSUE THREAD

**Issue by ljp1001** [golang/go#34888]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Hi @ljp1001, this is likely because of a bad Go installation. Please nuke your Go installation entirely and install it again. If the issue still happens, please reach out to any of the forums listed below. Unlike other projects, we do not use the issue tracker for questions such as these. It is only used for bugs and feature proposals.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks
