### ISSUE TITLE
wiki: rename FileTreeDocumentation

### ISSUE THREAD

**Issue by apparluk** [golang/go#34940]
I'd like to rename the FileTreeDocumentation page to GoTree.

In alternative the name might simply be shortened to FileTree.

**Comment by julieqiu** [comment]
@apparluk would you mind linking the page that you are referring to?

**Comment by apparluk** [comment]
https://github.com/golang/go/wiki/FileTreeDocumentation

**Comment by ALTree** [comment]
I agree that in "FileTreeDocumentation" the "Documentation" part is redundant, but I wonder if this is important enough to change it. 

Yes, we could avoid breaking links by keeping FileTreeDocumentation and redirecting to FileTree, but the redirect is "manual" (you have to change the page to say "See FileTree", and the user has to click on the link), so they're not a great user experience. Moreover, the old page remains in the list of wiki pages, so when you search "FileTree" you'll see both; so the old "redirected" pages somewhat pollute the wiki.

If there was a way to 1) make the redirect automatic 2) hide the empty redirect-pages from the pages list, then it would be much less painful to rename pages at will to fix bad names; but since you cannot do that, we should only rename when absolutely necessary.

**Comment by apparluk** [comment]
Factually, I don't know whether the page has ever received much traction.

Would you have an opinion on pasting it's contents into a new "GoTree" page, then simply deleting "FileTreeDocumentation"?

**Comment by ALTree** [comment]
> the page has ever received much traction.

It probably hasn't, which would soften the impact of a page-move (not many links broken). OTOH, we usually try not to delete pages.

cc @andybons @dmitshur too for a decision regarding the page rename/move.

**Comment by apparluk** [comment]
> move

my preference is for a move to GoTree

factually, that's what the text is describing
