### ISSUE TITLE
x/tools/gopls: automate daily updates of gopls/go.mod

### ISSUE THREAD

**Issue by ainar-g** [golang/go#34952]
<p>
Not sure if there's something wrong with my installation or the repo.
Here's what I try to do, and what used to work before:
</p>

<details>
<summary>
Shell log
</summary>
<pre>$ go version
go version go1.13.1 linux/amd64
$ go clean -cache -modcache
$ go get golang.org/x/tools/gopls@master
go: finding golang.org/x/tools/gopls master
go: downloading golang.org/x/tools/gopls v0.0.0-20191017101817-846f856e7d71
go: extracting golang.org/x/tools/gopls v0.0.0-20191017101817-846f856e7d71
go: downloading golang.org/x/tools v0.0.0-20190918214516-5a1a30219888
go: extracting golang.org/x/tools v0.0.0-20190918214516-5a1a30219888
go: downloading honnef.co/go/tools v0.0.1-2019.2.3
go: downloading github.com/sergi/go-diff v1.0.0
go: downloading golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: extracting github.com/sergi/go-diff v1.0.0
go: extracting golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: extracting golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: extracting honnef.co/go/tools v0.0.1-2019.2.3
go: downloading github.com/BurntSushi/toml v0.3.1
go: extracting github.com/BurntSushi/toml v0.3.1
go: finding github.com/sergi/go-diff v1.0.0
go: finding golang.org/x/tools v0.0.0-20190918214516-5a1a30219888
go: finding honnef.co/go/tools v0.0.1-2019.2.3
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: finding github.com/BurntSushi/toml v0.3.1
# golang.org/x/tools/gopls/internal/hooks
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/analysis.go:15:12: options.StaticCheck undefined (type *source.Options has no field or method StaticCheck)
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/analysis.go:17:11: options.Analyzers undefined (type *source.Options has no field or method Analyzers)
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/analysis.go:20:11: options.Analyzers undefined (type *source.Options has no field or method Analyzers)
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/analysis.go:23:11: options.Analyzers undefined (type *source.Options has no field or method Analyzers)
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/hooks.go:15:12: options.GoDiff undefined (type *source.Options has no field or method GoDiff)
../../../../pkg/mod/golang.org/x/tools/gopls@v0.0.0-20191017101817-846f856e7d71/internal/hooks/hooks.go:16:10: options.ComputeEdits undefined (type *source.Options has no field or method ComputeEdits)
</pre>
</details>

<b>EDIT:</b>  A colleague of mine has the same issue.

**Comment by dmitshur** [comment]
Thanks for reporting, I can reproduce it too. It's a build problem on https://github.com/golang/tools/commit/846f856e7d713bd2e8112adf3b8649d7bb111cca commit. /cc @stamblerre

For some reason, the builders didn't catch this failure. I'll look into that.

If you just want to install the latest released version, you can use `go get golang.org/x/tools/gopls@latest` instead of `@master` as suggested in https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation.

**Comment by fsouza** [comment]
The problem is that gopls uses [``replace``](https://github.com/golang/tools/blob/master/gopls/go.mod#L12), and go get won't honor that. An alternative is to manually clone the repo and run ``go install``.

**Comment by dmitshur** [comment]
@fsouza Thanks, that explains why builders didn't catch it. The replace directive was used during tests because `go test` runs inside gopls directory, so it was the main module.

**Comment by ainar-g** [comment]
<p>
@dmitshur I know about <code>@latest</code>, but I specifically get
<code>@master</code> from time to time to report bugs like this ASAP :-)
</p>

<p>
Is there an issue about <code>go get</code> not respecting
<code>replace</code> directives?  Should I create one?
</p>

**Comment by stamblerre** [comment]
I think the issue is that we just haven't updated the `go.mod` file for `gopls` in a while, so it's relying on an old version of `x/tools`, so I wouldn't expect it to work outside of the tools module. Because of the replace directive, the correct way to install `gopls` at master would be to clone the repo and run `go install` inside of the `gopls` directory.

**Comment by zikaeroh** [comment]
I typically pull `gopls` and `x/tools` together, i.e. `golang.org/x/tools/gopls@master golang.org/x/tools@master`, since I like to live on the edge and run master all the time. Since `x/tools` and `gopls` don't really place nicely due to `internal` package changes, you basically have to run `latest` of `gopls`, or `master` of both.

(Technically, I use a [custom tool](https://github.com/zikaeroh/gotools) I wrote to manage binaries with modules which can handle copy upstream replacements, though admittedly not relative ones at the moment.)

**Comment by FiloSottile** [comment]
I ran into this and worked around it by making my own go.mod that pulls up the x/tools version to one that works with gopls.

```
module my/gopls

go 1.13

require (
	golang.org/x/tools v0.0.0-20191018212557-ed542cd5b28a // indirect
	golang.org/x/tools/gopls v0.0.0-20191018212557-ed542cd5b28a // indirect
)
```

It feels like the go.mod of golang.org/x/tools/gopls should have a working version at all times (as tested by the builders), or a completely fake one (like v0.0.0, so the build will fail more obviously), if the only allowed way to build is with gopls as the main module.

**Comment by stamblerre** [comment]
Totally agree that getting `gopls@master` should always work. We really ought to have some automation around updating the `go.mod` daily, or something like that.

**Comment by zikaeroh** [comment]
I will be curious about how the new `-g` option going into 1.14 will help in this case. Since it effectively installs something using the tool's module as the main module, replacements will probably work and the `../` replacement for `x/tools` might just work.

**Comment by stamblerre** [comment]
At this point, we are recommending that users download `gopls` at master by running `go get golang.org/x/tools/gopls@master golang.org/x/tools@master`. This has proved to work reasonably well. I also think that we should update the `go.mod` file at master any time we tag a stable release. Other than that, I don't think that it's worth any extra effort to keep `go get golang.org/x/tools/gopls@master` working.
