### ISSUE TITLE
cmd/compile: enable -d=checkptr as part of -race and/or -msan?

### ISSUE THREAD

**Issue by mdempsky** [golang/go#34964]
As [discussed on golang-dev](https://groups.google.com/d/msg/golang-dev/SzwDoqoRVJA/Iozu8vWdDwAJ), the new -d=checkptr instrumentation is compatible with -race and -msan and likely cheaper than either of them (about the cost of two runtime.findObject calls per conversion involving unsafe.Pointer), so maybe it should just be enabled as one of those flags.

It would be easy to tweak cmd/compile to enable -d=checkptr by default when -race or -msan are specified, and then to still allow `-race -d=checkptr=0` to turn it back off (i.e., race instrumentation without pointer checking). I can do that now so we get some extra usage testing of -d=checkptr (thanks to existing builders that use -race, etc), and then closer to release we can re-evaluate the best user experience?

/cc @aclements @bradfitz @rsc

**Comment by mdempsky** [comment]
Pointer checking is now enabled automatically when -race or -msan are specified (except on Windows, because of remaining Windows-specific work for https://github.com/golang/go/issues/34972#issuecomment-545198760).

I've marked this issue as release-blocker for Go 1.14 so we make sure to make an explicit decision on the matter before release. In the mean time, I think it's valuable at least to get extra mileage for the pointer checking instrumentation.

**Comment by mdempsky** [comment]
Another thing to consider before release too: during discussion on #22218, @rsc suggested ["make it a throw, not a panic"](https://github.com/golang/go/issues/22218#issuecomment-378045430), but the current implementation does use panic.

It should be easy to change to throw instead. We could also make it controllable via GODEBUG at runtime. I don't have any strong opinions here.

(I think it only panics because in the moment of trying to debug some corner case behavior, it was quicker to use panic because it automatically handled formatting integers for me.)

**Comment by zikaeroh** [comment]
I don't write unsafe code myself, only via third party dependencies (so take my opinion with a grain of salt), but my main want would be to have a message printed like how race mode prints a message (and during `go test`, fails).

Right now, a panic coming from checkptr can be recovered and you'll never see it unless you're careful (as in yuin/gopher-lua#254 which I got from running gotip in race mode in my CI). A throw could work, but would exit the process.

Configurable is nice too.

**Comment by aclements** [comment]
Since this seems to be working pretty smoothly, we've decided to go ahead and keep -race/-msan setting -d=checkptr by default for the release, except on Windows where it's still disabled because of some remaining issues in std. I've just updated the release notes to mention this.

Since this issue was about making this decision, I'm going to go ahead and close it. We'll continue to track remaining std fixes in #34972.

**Comment by zikaeroh** [comment]
Was there any discussion as to whether checkptr should be using `throw` instead of `panic`? Per: https://github.com/golang/go/issues/34964#issuecomment-550535838 (and my feedback above).

**Comment by mdempsky** [comment]
(Reopening to make sure we resolve the panic vs throw question.)

**Comment by aclements** [comment]
I'm not inclined to make it configurable, since that seems like an unnecessary knob and it fails my knob litmus test of "I can give clear guidance on how to set this knob."

A throw seems pretty reasonable to me. If panics are being silently eaten by a system, that seems like a bug in the system to me, but I'm also fine with not making this a panic.

**Comment by mdempsky** [comment]
Closing again since we've decided to use `throw`, and the change has been committed.
