### ISSUE TITLE
aix: builder is offline

### ISSUE THREAD

**Issue by bcmills** [golang/go#35032]
Per https://farmer.golang.org:
> host-aix-ppc64-osuosl: 0/0 (1 missing)

The `aix-ppc64` column of https://build.golang.org is also notably empty since 17 Oct.

CC @bradfitz @trex58 @Helflym

**Comment by Helflym** [comment]
It's ok now. 
The folder where builds are made, `workdir-host-aix-ppc64-osuosl`, seems to have been removed by something.

**Comment by bradfitz** [comment]
> The folder where builds are made, workdir-host-aix-ppc64-osuosl, seems to have been removed by something.

This doesn't sound like the root cause of the problem was fixed.

If the buildlet deleted it as part of its cleanup and it's failing to re-create it, that's a problem we need to fix in the buildlet.

But if you're passing a certain `--workdir=` flag value to the buildlet and it doesn't exist, perhaps your process supervisor config needs work.
