### ISSUE TITLE
x/website/cmd/golangorg: GoogleCN does not work

### ISSUE THREAD

**Issue by jadekler** [golang/go#35065]
```
$ curl -X POST -F 'googlecn=yes' -H "X-Appengine-Country: CN" localhost:6060/doc/code.html | grep Tour
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20369    0 20223  100   146  3327k  24599 --:--:-- --:--:-- --:--:-- 3949k
Take <a href="//tour.golang.org/">A Tour of Go</a> to learn the language
```

Here's a test that repros this: https://gist.github.com/jadekler/33cb8fc1f96cebaf35c46269be045bc2.

I got as far as writing the test but couldn't figure out the solution. Seems like godoc.org + filesystem is serving all the .html files, instead of x/website? Is that right? If so, I have no idea where to do the template execution. Would love some tips.

cc @dmitshur @andybons @jayconrod

**Comment by dmitshur** [comment]
I'm a little confused by the `curl` example in this issue report. It makes a POST request instead of GET. It targets the `/doc/code.html` page, but the [current `/doc/code.html` page](https://github.com/golang/website/blob/c6c84f4e11bd7b3a28933aaf8473117b29284548/content/static/doc/code.html) doesn't have any `{{if .GoogleCN}}` use. Did you mean to use `/doc/docs.html` instead?

> Would love some tips.

For development purposes, you can force the `GoogleCN` value to be set to `true`  by setting the `googlecn` query parameter to a non-empty value. For example, https://golang.org/?googlecn=1.

See [here](https://github.com/golang/tools/blob/ab6dbf99d1006fd5137765d6950f1e98fcc6b0dd/godoc/page.go#L65-L82) for the relevant logic.

For production purposes, you need to set the `GOLANGORG_CHECK_COUNTRY` environment variable to `true` in order to enable country restrictions. See [here](https://github.com/golang/tools/blob/ab6dbf99d1006fd5137765d6950f1e98fcc6b0dd/godoc/golangorgenv/golangorgenv.go#L20-L23) and [here](https://github.com/golang/website/blob/c6c84f4e11bd7b3a28933aaf8473117b29284548/cmd/golangorg/app.prod.yaml#L6).

**Comment by jadekler** [comment]
Sorry!! The perils of filing bugs late at night. Looks like things somehow _do_ work, after all:

```
$ curl -X POST -F 'googlecn=yes' -H "X-Appengine-Country: CN" https://golang.org/doc/ | grep Tour
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9095    0  8949  100   146  90803   1481 --:--:-- --:--:-- --:--:-- 91316
	  A Tour of Go
```

Closing this.

-----------------

> For production purposes, you need to set the GOLANGORG_CHECK_COUNTRY environment variable to true in order to enable country restrictions. See here and here.

Ahh. Thank you!

**Comment by jadekler** [comment]
FYI for future: for dev mode you also need,

```
"Template": true
```

At the top of the file.
