### ISSUE TITLE
x/website: golang.org homepage has two different Hello worlds, one is not gofmt-ed

### ISSUE THREAD

**Issue by ALTree** [golang/go#35099]
The "Try Go" element on the golang.org homepage has two different _Hello world_, one of which is not gofmt-ed. 

When you load golang.org for the first time, the "Try Go" element on the right look like this:

![hello1](https://user-images.githubusercontent.com/3586803/67381516-50b86880-f58c-11e9-9432-9e8be5a12828.png)

The "Open in Playground" element links to https://play.golang.org/p/MbPUiI4y-IE, which contains a non-gofmt-ed Hello world (it uses 2 spaces to indent the `fmt` line).

If you use the selector below to display another code snippet (say, _Concurrent Pi_), and then you re-select _Hello world_, the Hello that is displayed looks like this:

![hello2](https://user-images.githubusercontent.com/3586803/67381751-bb69a400-f58c-11e9-94ec-61b3fc3f922c.png)

Note how this is a _different_ Hello world (gofmt-ed, and the comment at the top is missing). The "Open in Playground" element links to a different program (https://play.golang.org/p/7vin2BK8_A6).

We should probably settle on one Hello world (gofmt-ed). 

If we want to keep two (one with the "// You can edit this code!" comment at the top, and one without), we should at least gofmt the default one. It looks bad to have a non-gofmt-ed program on the homepage.

**Comment by ALTree** [comment]
cc @andybons @dmitshur

**Comment by dmitshur** [comment]
I think having the "// You can edit this code!" comment is more useful on initial page load, and less so after, because once users have changed between different snippets, it's more likely they'll understand it's editable.

But it should be simpler and more predictable to have just one version of the "Hello World" snippet (with the "// You can edit this code!" comment). It can avoid the surprise of a user changing from hello to another snippet and back, and noticing that something changed and not being sure what.

Let's fix this by consolidating the two "hello world" versions (keeping the "// You can edit this code!" comment) and gofmting it.

**Comment by rhnvrm** [comment]
I can take up this issue :+1:

**Comment by dmitshur** [comment]
First part of this (making the default hello world snippet gofmted) is resolved, and can be previewed at https://tip.golang.org/.
