### ISSUE TITLE
x/sys/unix: __sysctl is used on iOS instead of sysctl

### ISSUE THREAD

**Issue by zx2c4** [golang/go#35103]
In issue #34133, @mmaxim reported that the app store was rejecting his app due to the use of `__sysctl`, which he ascribed to the Go runtime. However, it turns out that the Go runtime uses `sysctl`, whereas it was x/sys/unix using `__sysctl`. So, x/sys/unix should be adjusted to use `sysctl` instead of `__sysctl`.

CC @eliasnaur

**Comment by eliasnaur** [comment]
Thank you. I'm sorry that I wasn't more thorough. Is this a backport candidate?

**Comment by zx2c4** [comment]
> Thank you. I'm sorry that I wasn't more thorough. Is this a backport candidate?

x/sys/unix is not relevant for backports. Perhaps you meant to chime in on https://github.com/golang/go/issues/35101 for which there is already a backport candidate in https://github.com/golang/go/issues/35105

**Comment by alexaliu** [comment]
The change fails for me on macOS 10.14.6 (mojave) with 

```
vendor/golang.org/x/sys/unix.libc_sysctl_trampoline·f: relocation target vendor/golang.org/x/sys/unix.libc_sysctl_trampoline not defined
```

I think the issue is that the assembly files still refer to 
[`libc___sysctl_trampoline`](https://github.com/golang/sys/blob/master/unix/zsyscall_darwin_arm64.s#L43) and `libc___sysctl` instead of `libc_sysctl`. Changing it to `lib_sysctl` fixes the issue for me, at least for amd64.

These files look like they're generated though, so I'm not sure if this analysis is correct.
