### ISSUE TITLE
sync: RWMutex non-reentrant rlock -race check

### ISSUE THREAD

**Issue by av-elier** [golang/go#35138]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### What did you do?

Misused RLock: https://play.golang.com/p/-7UFH11FDRV

> RLock
> It __should not be used for recursive read locking;__ a blocked Lock call excludes new readers from acquiring the lock.

### What did you expect to see?

I want a `-race` mode to detect reentrant RLock calls even if deadlock is not yet happened.

I want to propose to add this check to race detector. I am not familiar with how exactly race detector works. But it seems to me that it should be possible to save RLock/RUnlock  calls for each goroutine in race mode, and when pattern (RLock,RLock,RUnlock,RUnlock) apear in the order of calls - it's a sign that RLock is misused.

Is it a good idea, to add a check for this?

**Comment by dvyukov** [comment]
This is undetectable. Unfortunately. Go does not have mutexes, only semaphores. So the check will have false positives.
But otherwise tsan runtime generally have most things ready for deadlock detection on mutexes:
https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/tsan_interface.h#L27-L105

**Comment by rsc** [comment]
What Dmitry means is that in Go, ownership of a mutex is not tied to a specific goroutine. It is OK to do code like:

    m.RLock()
    go work() // does m.RUnlock when done
    m.RLock()

and that's not a deadlock. Drop the R's and it is still not a deadlock. But a deadlock detector that assumes lock ownership is tied to a thread/goroutine would report it as a deadlock.

I suppose that back to back RLock with no scheduling event between them might be detectable but that's never the interesting thing to detect.

Closing because this is not detectable.
