### ISSUE TITLE
crypto/tls: maxHandshake is not documented

### ISSUE THREAD

**Issue by zhangyoufu** [golang/go#35153]
`crypto/tls` has a hard-coded limitation `const maxHandshake = 65536` for handshake message length.

While a ClientHello message could has a maximum length of `131396` under extreme conditions, according to [OpenSSL source code](https://github.com/openssl/openssl/blob/40dfb8c70514006868344eaabf057aac6a428145/ssl/statem/statem_srvr.c#L1091-L1106).

The 64KiB limitation is good at security perspective, to reduce server resource consumption. But I think it should be documented, as a Go specific behavior.

**Comment by FiloSottile** [comment]
Documenting something makes it a backwards compatibility promise, while this should be just an internal detail. What we do have is a clear error for when the limit is exceeded, so if it starts happening users can open an issue about it.

https://github.com/golang/go/blob/0fb95e788e8639712b7200a5c08ec023fb3588cb/src/crypto/tls/conn.go#L982

(If you opened this issue because you hit the limit and you think we should increase it, feel free to open an issue for that.)
