### ISSUE TITLE
x/build: frequent timeouts running js-wasm TryBots

### ISSUE THREAD

**Issue by bcmills** [golang/go#35170]
I've noticed that the `js-wasm` TryBots on my recent CLs seem to start with one or more spurious failures before finally running successfully.

I suspect that that increases load on the TryBots generally, and may increase overall TryBot latency in some circumstances.

A log from a recent example is here (https://farmer.golang.org/temporarylogs?name=js-wasm&rev=9516a47489b92b64e9cf5633e3ab7e37def3353f&st=0xc00ab39b80):

```
  builder: js-wasm
      rev: 9516a47489b92b64e9cf5633e3ab7e37def3353f
 buildlet: (nil *buildlet.Client)
  started: 2019-10-26 01:37:51.137407213 +0000 UTC m=+287652.939853079
    ended: 2019-10-26 01:38:21.20458221 +0000 UTC m=+287683.007028020
  success: false

Events:
  2019-10-26T01:37:51Z ask_maintner_has_ancestor 
  2019-10-26T01:38:21Z finish_ask_maintner_has_ancestor after 30s; err=context deadline exceeded

Build log:
Error checking whether commit 9516a47489b92b64e9cf5633e3ab7e37def3353f includes ancestor 3dced519cbabc213df369d9112206986e62687fa: context deadline exceeded


Error: context deadline exceeded
```

CC @dmitshur @toothrot @bradfitz

**Comment by agnivade** [comment]
One change was that the builder was recently bumped to Node 13.

**Comment by bradfitz** [comment]
I think that's unrelated. When I've seen this, the error is also as Bryan quoted above: a timeout doing a gRPC call to maintner, asking whether we should even do this build. We used to need to skip builds for js/wasm if the git history of the rev to be built didn't include js-wasm support. But now that we've supported js/wasm for a number of releases (since Go 1.11) and we don't even support Go 1.10 (or even Go 1.11) any more, we can just remove that condition on that builder.

But also: maintner shouldn't be so slow at that query.

**Comment by bradfitz** [comment]
Not very scientific, but the has-ancestor RPCs are taking only 100ms for me. (includes TCP+TLS setup, etc) Not anywhere near 30 seconds.

```
$ time maintq has-ancestor 0ae9389609f23dc905c58fc2ad7bcc16b770f337 3dced519cbabc213df369d9112206986e62687fa
has_ancestor:true

real    0m0.105s
user    0m0.076s
sys     0m0.028s
```

**Comment by agnivade** [comment]
@dmitshur - Would you be able to check if this is still happening ?

**Comment by neelance** [comment]
@dmitshur Do you know if this is still an issue?

**Comment by dmitshur** [comment]
I feel like I've seen some discussion about this still happening occasionally quite recently, more so than the comments in this issue would suggest. Perhaps it was in another thread. I'll keep an eye out on this.

**Comment by rsc** [comment]
Yes, it is still happening. Last week I caught the js-wasm trybot taking 25 minutes when most were done in 15,
and just now I caught it taking 34 minutes when everything else was done in 16. 
That one was https://go-review.googlesource.com/c/go/+/266357 and I gave up waiting and just submitted the CL.

Any advice about what to do when js-wasm looks like it is stuck/very slow and how to debug further would be greatly appreciated.

**Comment by dmitshur** [comment]
> Any advice about what to do when js-wasm looks like it is stuck/very slow and how to debug further would be greatly appreciated.

I suggest trying to determine if there is a specific place where the build progresses more slowly than others. I.e., is it perhaps that time to first test is delayed, then it's fast, or is one of the package tests very slow, while the rest is fast, or is slowness equally distributed across all packages?

I'll also try to look into logs for the two occurrences you've shared and see if I can determine it from that.

**Comment by dmitshur** [comment]
From [CL 266374](https://golang.org/cl/266374) where I recently started trybots:

![image](https://user-images.githubusercontent.com/1924134/97641172-a8e43f00-1a18-11eb-9a55-777339103a6e.png)

In this instance, the js-wasm builder is in waiting_for_machine state for over 10 minutes. That is very unexpected—it's a GCP builder that we should be able to spin up without running out of physical machines. Perhaps we're running out of some quota. Not sure why only js-wasm and not other GCP builders. But this is a lead.

**Comment by bcmills** [comment]
In several occurrences that I saw, the `js-wasm` TryBot started running and partially completed, then descheduled and started over again from the beginning. I think there is some sort of failure being buried by retry logic, rather than just a slow test.

If we don't have the bandwidth to diagnose this at the moment, perhaps we should temporarily demote `js-wasm` to an opt-in SlowBot?

**Comment by dmitshur** [comment]
<details>

I extracted some raw data from some Wasm trybot runs, which I was going to analyze more and post something here, but then this work got pre-empted by other work, and by now I've lost it due to a forced browser update.

From memory, the high-level summary was that the Wasm trybot runs are generally quick, with two components that contribute a fairly significant proportion of the overall time:

- test directory
- reboot test

There's a commonly used dist-test adjust policy [`fasterTrybots`](https://github.com/golang/build/blob/9bcb083a2669cde9154d5bd021d25abebdc32516/dashboard/builders.go#L2675-L2684) that skips precisely those two components during pre-submit tests (but not during post-submit tests), which is an option available to speed up Wasm trybots.

However, it seems the root problem here was with the scheduling of the Wasm builders and starting the trybot runs, not the length of trybot test execution itself under a typical "happy" run. There are many possible places to look next. As @bcmills also pointed out in #42699, there is a problem of stalls sometimes resulting in extended test executions that eventually instead of what should be failures. Stalls could be due to something Wasm-specific (e.g., #31282) or something more general. We also have some possible blindspots on the side of coordinator (e.g., #39349, #39665). As I've recently experienced during https://github.com/golang/go/issues/42379#issuecomment-722054437, it's possible for stalls to happen when a test execution is sharded and not happen during a sequential all.bash test run.

</details>

All this is to say that more work needs to be done to get closer to finding and resolving the root issue(s) here. I think we have confirmation that this problem is intermittent and skipping a deterministically slow test is not an available option.

**Comment by dmitshur** [comment]
Is anyone still observing this issue?

> Is something preventing these buildlets from spawning?

A new idea by now is that it might've been hitting the GCE VM quota. Some of those quotas are visible in the first line of https://farmer.golang.org/#pools.

If there are no frequent timeouts happening by now, perhaps we should close this.

**Comment by dmitshur** [comment]
Sounds good, closing since I haven't seen reports of this in a long while, can reopen or file another issue if this comes up again.

From looking at the initial report, there's also a chance that the same problem as in issue #55947 (fixed as of Oct 2022) may have contributed here too.
