### ISSUE TITLE
x/tools: build failing on windows-amd64-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#35186]
The `windows-amd64-longtest` builder is failing in numerous ways on `x/tools`.

Looks like some of the same out-of-memory issues as in #33951, but there may be other failures too.

https://build.golang.org/log/591874cbe6ad7d7b59ad1f9ef2b3d34e81af20a4

CC @ianthehat @matloob @stamblerre

**Comment by bcmills** [comment]
I believe this is a release-blocker via #11811.

**Comment by dmitshur** [comment]
I've spun up a bunch of VMs/laptops with Windows 7/10 ([WindowsBuild](https://golang.org/wiki/WindowsBuild) was very helpful), some with 8 GB RAM and one with 16 GB.

### 8 GB

On 8 GB configurations, I could not get `go test -race golang.org/x/tools/...` to pass even once, despite multiple attempts and test caching helping out:

![tools race oom 1](https://user-images.githubusercontent.com/1924134/71870030-53821e80-30e2-11ea-803d-9e5d6a13d40a.png)

![tools race oom 2](https://user-images.githubusercontent.com/1924134/71870031-5715a580-30e2-11ea-9a55-6c2fced7400c.png)

All 7-8~ GB RAM were used up during a large portion of the time.

### 16 GB

With 16 GB, `go test -race golang.org/x/tools/...` passed on first try.

![image](https://user-images.githubusercontent.com/1924134/71870145-d3a88400-30e2-11ea-9295-28ab13cebb28.png)

RAM usage still reached nearly all 15~16 GB RAM used up some of the time.

---

I've sent [CL 213557](https://golang.org/cl/213557) which bumps the RAM from 7.2 to 14.4 on windows-amd64-{longtest,race} builders. I think it's a reasonable next step to try, since some other builders already get 16 GB.

**Comment by dmitshur** [comment]
The aforementioned change has had an effect. Both windows-amd64-longtest and -race have been [passing on x/tools](https://build.golang.org/?repo=golang.org%2fx%2ftools) since the builder change was deployed this morning. I'll keep watching a bit more, and then close this issue if the pattern continues.

There have been instances where x/tools has passed on all builders with tip and on release-branch.go1.13:

![image](https://user-images.githubusercontent.com/1924134/71931542-ec10b100-316b-11ea-9fbe-21567f6a741c.png)

![image](https://user-images.githubusercontent.com/1924134/71931609-16fb0500-316c-11ea-9ca4-8d83e7bcd939.png)

The freebsd-amd64-race builder still fails due to low memory occasionally, but that's outside of scope of this issue. I'll use issue #34621 to track increasing its memory to match Linux and Windows if needed.

**Comment by dmitshur** [comment]
This issue is resolved now, based on the current state of the `windows-amd64-longtest` column on https://build.golang.org/?repo=golang.org%2fx%2ftools:

<details><br>

<img src=https://user-images.githubusercontent.com/1924134/72273395-455b6300-35f8-11ea-8bcc-b21cdcefd1c9.png width=54>

</details>
