### ISSUE TITLE
database/sql: failed to send SQL Batch error

### ISSUE THREAD

**Issue by lw-bmc** [golang/go#35215]
<pre>
$ go version
go version go1.12 windows/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\<username>\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\<username>\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
</pre></details>

While using database/sql and jmoiron/sqlx modules, 99% of the time everything works fine. Occasionally, I get the following error:

failed to send SQL Batch: write tcp <ip address>:58725-><ip address>:1433: wsasend: An existing connection was forcibly closed by the remote host. 

This happens randomly; I can't reproduce it reliably, although it seems to happen when the API (gin-gonic) hasn't handled any requests for a few minutes. It only seems to happen when API is running through IIS on my web server (tried both ASP.Net Core and HTTP Platform handlers). Could not reproduce it on my local dev machine. 

Has anyone seen this at all? I have no idea how to go about diagnosing or fixing this, any help at all is much appreciated.

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
