### ISSUE TITLE
cmd/doc: "can't compute 'all' using the vendor directory" in module mode

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#35224]
`GO111MODULE="on"` (force modules to be always on)
then `cd /usr/local/go/src/cmd/go/internal/load` as a example and do `go doc` in that specific goroot directory to get a overview of package load
```
% cd /usr/local/go/src/cmd/go/internal/load
% go doc
go list -m: can't compute 'all' using the vendor directory
        (Use -mod=mod or -mod=readonly to bypass.)
package load // import "cmd/go/internal/load"
Package load loads packages.
...
```

Can I ask a favor please that every maintainer sets there `GO111MODULE="on"` I have no doubt the module system is ready for prime time, but I really think we are heavily underestimating how many go tools are not ready because most of us just keep working in `GOPATH` not knowing we are about to hit a iceberg once we turn off `GOPATH` completely.

**Comment by bcmills** [comment]
This particular error is a side effect of the changes for #33848.
`go list -m all` has never given complete information in vendor mode; now that we're enabling module mode by default, it's important that we not _implicitly_ drop the missing information.

So there are two underlying problems here:

1. Integration test coverage for `cmd/doc` is poor, especially in module mode. (The vast majority of tests for `cmd/doc` are written against the unexported `do` function, rather than the `go doc` command that users actually invoke, and they set an [explicit variable](https://github.com/golang/go/blob/68395a66f9fece387701e1450e3d7a8fa91fb76e/src/cmd/doc/dirs.go#L139) to force that function to run only in GOPATH mode.)

2. `go doc` either needs to know about the `vendor` directory and its use, or needs to list packages instead of modules.

**Comment by jayconrod** [comment]
More generally: #34750
