### ISSUE TITLE
build: skip building toolchain on js/wasm?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35220]
In https://go-review.googlesource.com/c/go/+/203821 it was noted that js/wasm doesn't have syscall.Exec, and it was worked around with build tags.

But why is the linker being built for js/wasm?

Is it even possible to run the linker or other parts of the toolchain in js/wasm?

I always assumed that js/wasm was a target-only port, to be cross compiled from another more regular host.

Should we skip building `cmd` for js/wasm?

/cc @neelance @ianlancetaylor @bcmills @dmitshur @andybons @cherrymui

**Comment by neelance** [comment]
I would be okay with skipping the build of `cmd` for js/wasm. Theoretically it should be possible to run the Go compiler and linker entirely in your browser, to have a Go playground that needs no server any more. In practice this needs some effort which nobody seems interested in atm.

**Comment by bradfitz** [comment]
Um, we already did this in 5d4f0474ecb for the duplicate bug I filed (#25911).

So why did we hit this again?

Maybe we're still running tests?

**Comment by agnivade** [comment]
We already skip building `cmd` for js/wasm in cmd/dist ([CL 120655](https://go-review.googlesource.com/c/go/+/120655/)).

From what I understand, it is the test which is failing, not the build (which is where cmd/dist takes effect).

Does it even make sense to support  `-buildmode=c-archive` in wasm (since it doesn't support CGo) ? I think we can just add `wasm` [here](https://go-review.googlesource.com/c/go/+/203821/4/src/cmd/link/internal/ld/ld_test.go#97).

(crossed responses responses again :/)
