### ISSUE TITLE
strings: TestBuilderAllocs flake on freebsd-386-12_0

### ISSUE THREAD

**Issue by bcmills** [golang/go#35280]
`freebsd-386-12_0` (https://build.golang.org/log/380c04df9641b3e5274073af6c25f56e5607e60d):

```
--- FAIL: TestBuilderAllocs (0.00s)
    builder_test.go:193: got 1 alloc(s); want 0
FAIL
FAIL	strings	1.570s
```

It's not obvious to me whether this is a bug in the test proper or in `testing.AllocsPerRun`.

CC @bradfitz; see previously #24647.

**Comment by bradfitz** [comment]
I see nothing obviously wrong with the test.

Maybe there's a closure allocation that it's counting?

In any case, perhaps we can just delete it. The test at the bottom of the function (which we're not getting to due to the t.Fatal) seems comprehensive at least and more self-contained (no closure either).
