### ISSUE TITLE
runtime: TestFutexsleep failing on freebsd and linux

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35347]
FreeBSD failure I've seen a few times now...

https://storage.googleapis.com/go-build-log/deaf5ba3/freebsd-amd64-12_0_6ba9394d.log
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestFutexsleep (0.02s)
    futex_test.go:65: futexsleep test "before the year 2038" finished early after 20.627855ms
FAIL
FAIL	runtime	14.092s
FAIL
2019/11/04 18:30:12 Failed: exit status 1
2019/11/04 18:30:12 FAILED
```

/cc @ianlancetaylor

**Comment by mdempsky** [comment]
Got the same flake on the linux-amd64 trybot just now: https://storage.googleapis.com/go-build-log/dec1040d/linux-amd64_babdf1c2.log

**Comment by ianlancetaylor** [comment]
My first guess is that the test is failing because the futex sleep is being interrupted by a preemption signal.  The test works by making a direct call to `futexsleep`, which on GNU/Linux calls `futex` and on FreeBSD calls `sys_umtx_op`.  The intent is to sleep for a long time.  However, these sleeps are interruptible; if a preemption interrupt is delivered, the sleep will wake up and return without error.

CC @aclements @cherrymui
