### ISSUE TITLE
syscall: TestSyscallNoError failing on linux-mipsle-rtrk

### ISSUE THREAD

**Issue by bcmills** [golang/go#35422]
`linux-mipsle-rtrk` (https://build.golang.org/log/7c41de40632a6e8445e6c90e94cb825c3aabdbd8):
```
--- FAIL: TestSyscallNoError (0.02s)
    syscall_linux_test.go:366: expected 4294967295 / 2 / 4294967294, got 4294967294 / 0 / 4294967294
FAIL
FAIL	syscall	6.696s
```

See previously #30258 (CC @ianlancetaylor @bradfitz)

**Comment by bcmills** [comment]
CC @bogojevic @milanknezevic

**Comment by bradfitz** [comment]
cc @tklauser

**Comment by tklauser** [comment]
Do I understand it correctly that `linux-mipsle-rtrk` is `linux/mipsle` actually running on 64-bit MIPS hardware/kernel? Maybe that has something to do with it?

**Comment by bradfitz** [comment]
Correct.

**Comment by cherrymui** [comment]
On MIPS, the kernel returns whether the syscall has error in a separate register, R7 (https://go.googlesource.com/go/+/refs/heads/master/src/syscall/asm_linux_mipsx.s#107), instead of a negative result.

I'm not sure I understand why TestSyscallNoError expects syscall.RawSyscall returns an error while the syscall is not erred. It looks to me that the intent of TestSyscallNoError is that RawSyscallNoError does the right thing, not RawSyscall (incorrectly) returns an error.

**Comment by bradfitz** [comment]
It's not just the error value that's got an unexpected value.

The first value is also unexpected. It's easier if it's reformatted like this:

```
expected 4294967295 / 2 / 4294967294,
     got 4294967294 / 0 / 4294967294
```

**Comment by cherrymui** [comment]
The first value, 4294967295, is just -1, as set by e.g. https://go.googlesource.com/go/+/refs/heads/master/src/syscall/asm_linux_386.s#79 when RawSyscall thinks it gets an error.

Assuming there is no error, 4294967294 is the expected result.
