### ISSUE TITLE
cmd/go:build: fails to build private gitlab repository

### ISSUE THREAD

**Issue by Aukstkalnis** [golang/go#35421]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.4
</pre>

### Does this issue reproduce with the latest release?
If latest release you mean 1.13.4 version, then yes.

### What operating system and processor architecture are you using (`go env`)?
Windows 10 Pro build 18362
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\aukstkalnis.de\AppData\Local\go-build
set GOENV=C:\Users\aukstkalnis.de\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=gitlab.com/Aukstklanis/go-teltonika
set GONOSUMDB=gitlab.com/Aukstklanis/go-teltonika
set GOOS=windows
set GOPATH=D:\Projects\Go_Projects\GoPath
set GOPRIVATE=gitlab.com/Aukstklanis/go-teltonika
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=D:\Temp\go-build914382358=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Tried to build gitlab's private repository

### What did you expect to see?
Normal build result.

### What did you see instead?

go: finding gitlab.com/Aukstkalnis/go-teltonika latest
go: finding gitlab.com/Aukstkalnis/go-teltonika/server latest
go: finding gitlab.com/Aukstkalnis/go-teltonika/trace latest
verifying gitlab.com/Aukstkalnis/go-teltonika@v0.0.0-20191107082349-140b3a47d8fd: gitlab.com/Aukstkalnis/go-teltonika@v0.0.0-20191107082349-140b3a47d8fd: reading https://sum.golang.org/lookup/gitlab.com/!aukstkalnis/go-teltonika@v0.0.0-20191107082349-140b3a47d8fd: 410 Gone

### go.mod:
<pre>
$go.mod
module gitlab.com/Aukstklanis/go-teltonika

go 1.13
</pre>

**Comment by Aukstkalnis** [comment]
And why go build tries to download repository that i am working on? I might have changed something and server do not have these changes...

**Comment by bcmills** [comment]
> why go build tries to download repository that i am working on?

It doesn't, unless the main module transitively depends on some previous version of itself.
Does the `module` directive in your `go.mod` file match your repo path?

**Comment by bcmills** [comment]
The error during the `verifying` phase seems to be working as designed.
See https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules.

**Comment by Aukstkalnis** [comment]
I don't  know about working as designed, but builds fails... My repo does not mach with module name defined in go.mod file. Only las folder mach.

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
