### ISSUE TITLE
math/cmplx: TestAtan and friends failing on several platforms

### ISSUE THREAD

**Issue by mknyszek** [golang/go#35443]
These tests started failing on several platforms as of https://go-review.googlesource.com/c/go/+/169501.

The following platforms are definitely failing:
* linux-s390x: https://build.golang.org/log/17bb5d8c71826a7bc7b7b2589ac5dc34049949ac
* linux-mips: https://build.golang.org/log/12e67c4d1626dac693c081fb1f6db31d27453e64
* linux-mips64: https://build.golang.org/log/1d150a2765bbf07b67cb3d922fa1fc9c7b01afa0 (trybot run)

There may be more, but these are the most visible to me.

@griesemer @bmkessler

**Comment by mundaym** [comment]
/cc @billotosyr for the s390x failures.

I'll try disabling the s390x vector implementations of `math.Atan`, `math.Log` and `math.Log10` tomorrow. I suspect there could be subtle differences in there that are affecting these new tests (Atan looks like a ~1 ulp difference while the Log/Log10 tests look like zero sign differences).

**Comment by bmkessler** [comment]
for s390x

```
--- FAIL: TestAtan (0.00s)
    cmath_test.go:1018: Atan((1+0i)) = (0.7853981633974484+0i), want (0.7853981633974483+0i)
    cmath_test.go:1026: Atan((1-0i)) = (0.7853981633974484-0i), want (0.7853981633974483-0i)
    cmath_test.go:1030: Atan((-1-0i)) = (-0.7853981633974484-0i), want (-0.7853981633974483-0i)
--- FAIL: TestLog (0.00s)
    cmath_test.go:1163: Log((+Inf-1i)) = (+Inf+0i), want (+Inf-0i)
--- FAIL: TestLog10 (0.00s)
    cmath_test.go:1184: Log10((+Inf-1i)) = (+Inf+0i), want (+Inf-0i)
```
The first failures are due to the test being too strict for checking the value of `math.Atan(re)` it should be converted to use `cVeryClose` instead of `cAlike`

The failures on Log are actually a discrepancy in s390x handling of `math.Atan2(imag(x), real(x))`

 Log(x)  == complex(math.Log(Abs(x)), Phase(x)) == complex(math.Log(Abs(x)), math.Atan2(imag(x), real(x))

so the issue is that `math.Atan2(-1, +Inf)` should equal `-0`, but does not on s390x.

Note C99 Annex F. 9.1.4 specifies:

atan2(±y,+∞) returns ± 0 for finite y>0.

But the go documentation for math.Atan2 doesn't actually specify the sign.

`//	Atan2(y, +Inf) = 0`

However, the pure go implementation matches the C99 handling of the sign of zero.

The mips failures 

```
--- FAIL: TestAtan (0.00s)
    cmath_test.go:1030: Atan((-Inf+NaNi)) = (-1.5707963267948966+0i), want (-1.5707963267948966-0i)
--- FAIL: TestCosh (0.00s)
    cmath_test.go:1124: Cosh((-0+NaNi)) = (NaN-0i), want (NaN+0i)
--- FAIL: TestTanh (0.00s)
    cmath_test.go:1357: Tanh((-Inf+NaNi)) = (-1+0i), want (-1-0i)
```

are due to errors in the test code with respect to NaN sign handling.  The tests have cases that check f(x) == f(-x) for appropriate functions, but -x does not necessarily change the sign bit of NaN and `math.Copysign` should be used instead.

The two issues with the test code are easy fixes, but a decision should be made about the Atan2 special case that disagrees between the Go documentation (s390x implementation) and the C99 standard (pure go implementation).
