### ISSUE TITLE
UX lacking for tools management with go mod

### ISSUE THREAD

**Issue by mcandre** [golang/go#35494]
This is the recommended way to track tools dependencies in Go involves parsing a `tools.go`:

https://marcofranssen.nl/manage-go-tools-via-go-modules/

That's a far cry from the tool management experience available today in Node.js, Python, and Ruby, where tools are already supported on par with libraries.

We could have a short term solution available very quickly, with some minor changes to the Go ecosystem to promote `tools.go` to an official standard:

* `golint`, `go vet`, etc. would accept applications in imports.
* `go mod tidy` would install any applications noted in `tools.go`.
* `go mod tidy` and `go install` would improve support and documentation for specifying any custom build tags.

I'm not sure if tools.go is a long term strategy for tracking tools dependencies, but it's a start. Can we please get a better developer workflow than parsing Go code with *awk*?

**Comment by mvdan** [comment]
There has been lots of discussion in this space in the last two years, such as https://github.com/golang/go/issues/30515, https://github.com/golang/go/issues/34506, and https://github.com/myitcv/gobin.

Is what you're suggesting a proposal? It seems a bit all over the place; for example, I hardly imagine `go mod tidy` will ever build or install anything. Also, `golint` doesn't play a part in the `go` tool.

If this is a proposal, it needs to take into account the previous work. If it's not a proposal, please clarify what exactly the issue is about.
