### ISSUE TITLE
x/tools/internal/imports: TestScanNestedModuleInLocalReplace and 3 more failing on Go tip

### ISSUE THREAD

**Issue by dmitshur** [golang/go#35505]
From https://build.golang.org and https://go-review.googlesource.com/c/go/+/204830/4#message-7c1298f605c9bae9bf98fc61fbd88c2b029bdcb1:

```
--- FAIL: TestScanNestedModuleInLocalReplace (0.03s)
    mod_test.go:66: running go: exit status 1 (stderr:
        invalid version ""
        )
--- FAIL: TestModReplace2 (0.03s)
    mod_test.go:395: running go: exit status 1 (stderr:
        invalid version ""
        )
--- FAIL: TestModReplace3 (0.02s)
    mod_test.go:421: running go: exit status 1 (stderr:
        invalid version ""
        )
--- FAIL: TestModReplaceImport (0.01s)
    mod_test.go:454: running go: exit status 1 (stderr:
        invalid version ""
        invalid version ""
        invalid version ""
        invalid version ""
        invalid version ""
        )
FAIL
FAIL	golang.org/x/tools/internal/imports	27.104s
```

https://build.golang.org/log/3a4fbffe75af5fddd26d444d1dd2af3d805edee6

/cc @heschik

**Comment by bcmills** [comment]
I've tried to reproduce this locally but haven't had any success. It seems to have something to do with the builder configuration.

```
~/src/golang.org/x/tools$ gotip version
go version devel +275a7be3 Mon Nov 11 17:44:21 2019 +0000 linux/amd64

~/src/golang.org/x/tools$ gotip test golang.org/x/tools/internal/imports
ok      golang.org/x/tools/internal/imports     21.546s
```

**Comment by jayconrod** [comment]
I was able to reproduce this locally. The test is setting up a workspace and running `go mod download` there as part of the setup. An empty version gets passed to one of the `modfetch` functions.

**Comment by bcmills** [comment]
It's probably related to [CL 189797](https://golang.org/cl/189797), then.

I'm honestly more worried about the non-reproducibility of the failure than the failure itself — neither @iWdGo nor I were able to reproduce it locally, despite attempting to do so.

**Comment by heschik** [comment]
Like many x/tools tests, these run the go command, so `gotip test` is insufficient. Tip go needs to be the first thing on $PATH. Should be easily reproducible from there.

**Comment by bcmills** [comment]
`GOTIP` adds itself to `PATH`, but at the end rather than the beginning:
https://github.com/golang/dl/blob/530a690d93eb507301a30e1a91f5819971abaec8/internal/version/version.go#L59-L63

Probably it should add itself to the beginning of `PATH` instead.

OTOH, it's not uncommon for me to run something like `~go-review/bin/go test […]` and expect that to actually test against the `go-review` build of the `go` standard library and toolchain. Arguably the tests of packages in `x/tools` should be verifying their behavior against the `go` command that runs them, not whatever `go` command happens to be in `PATH`. That suggests that the test itself should update `PATH` to prefer `GOROOT/bin`.

**Comment by bcmills** [comment]
(There are likely many tests in the standard library that need a similar fix.)

**Comment by dmitshur** [comment]
> Tip go needs to be the first thing on $PATH.

All other `golang.org/dl/go...` binaries arrange for that to happen, as @bcmills just said. `golang.org/dl/gotip` needs to be fixed to do the same. Filed #35507.
