### ISSUE TITLE
proxy.golang.org: Proposal: maintain mod file for old packages and package list 

### ISSUE THREAD

**Issue by lcwj3** [golang/go#35522]
I am working on building a dependency graph for golang packages, the proxy.goalng.org do help me a lot, thanks for your great work! Here I have two small questions according to my concerns:

- Since we can get mod file from `https://proxy.golang.org/<module>/@v/<semver>.mod`, which is from source code, do you have any plans for old packages which don't have a mod file?

- We can get all versions of a module by `https://proxy.golang.org/<module>/@v/list`, do you also have an API to query a full package list?

Looking forward to your kind reply, thanks!

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks

**Comment by bcmills** [comment]
That said, you may want to investigate http://index.golang.org as a starting point.

(CC @katiehockman @julieqiu)

**Comment by lcwj3** [comment]
> That said, you may want to investigate http://index.golang.org as a starting point.
> 
> (CC @katiehockman @julieqiu)
Thank you for your kind reply!
Yes, but I have tried this index api `https://index.golang.org/index#`, it seems I can only get package publishing records after April 10 2019, so I may want a full list of all package id and their versions; Besides, there are a lot of old packages that have no dependency files, I also want an api to get all dependency information, e.g. we can get mod file from `https://proxy.golang.org/<module>/@v/<semver>.mod`, but for packages that don't have a mod file, it will return an empty mod file, so I was wondering if there is any API to get dependency information for old packages. 
Thanks again for your help!
