### ISSUE TITLE
go/scanner: potential inefficiency

### ISSUE THREAD

**Issue by danaugrs** [golang/go#35588]
I noticed a potential scanner inefficiency here:

https://github.com/golang/go/blob/3f21c2381d9b0f0977f388cc89104f557a7d2c88/src/go/scanner/scanner.go#L791-L793

`s.scanIdentifier()` calls `isLetter(s.ch)` with the same char that was just checked in the case condition: 

https://github.com/golang/go/blob/3f21c2381d9b0f0977f388cc89104f557a7d2c88/src/go/scanner/scanner.go#L350-L356

I think that instead of calling `s.next()` on line 809 we should both record the current char and call `s.next()` immediately before the entire nested switch statement. That would remove the double call to `isLetter` and also remove the need for the `s.peek()` on line 805. What do you think? It's very possible I'm overlooking something. Let me know if I should put together a PR.

**Comment by mvdan** [comment]
There are benchmarks. Does any change you can come up with actually improve the benchmarks with benchstat? If not, then it's probably not worth optimizing.

**Comment by danaugrs** [comment]
Before modifying and benchmarking something I find it beneficial to discuss it with those familiar with the matter. Is anyone familiar with the scanner logic interested in reasoning about the inefficiency I described and my proposal? @griesemer

**Comment by rsc** [comment]
It is almost always better to write code that is clear and easy to adjust in the future than code that is awkward but saves a few cycles. In this case, the string conversion far outweighs the cost of potentially looking up the first character twice. Even if the string conversion were not here, the current code can't be running slower than if every identifier were just one character longer, which we know doesn't really affect time. (Otherwise everyone would be saying to use short names in your program to make it parse faster.)

There's no change to make here, but thanks for taking the time to file the issue.
