### ISSUE TITLE
RWMutex panic stack is confuse

### ISSUE THREAD

**Issue by Petelin** [golang/go#35614]
this problem not happen in go1.10, but happen on go1.12,1.13

```
package main

import (
	"sync"
)

type client struct {
	sync.Mutex
	sync.RWMutex
}

func (c *client) do() {
	c.RWMutex.RLock()
	defer c.RWMutex.Unlock()
}

func (c *client) do2() {
	c.Mutex.Lock()
	c.Mutex.Unlock()
}

func main() {
	var c *client
	c.do()
	// c.do2()
}
```

what i expected is do and do2 should have almost same panic stack. 

but the RLock panic print is not say c.RWMutext is nil point but RLock function have problem. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x104f17c]

goroutine 1 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/sync/rwmutex.go:48
main.(*client).do(0x0)
        /Users/xiaolin.zhang/Project/gogo/test_main.go:13 +0x2c
main.main()
        /Users/xiaolin.zhang/Project/gogo/test_main.go:24 +0x2a
```

**Comment by randall77** [comment]
This looks like it is already fixed at tip.
Up to go1.13 it looks like the nil check in `do` is dropped because there is an unconditional load in the inlined body of RLock that does the nil check for us. But that gives an extra stack frame that doesn't really make sense.
At tip we no longer do that. I'm not sure what CL fixed this, maybe CL 200197?
