### ISSUE TITLE
net: LookupHost("localhost") returning "no such host" error

### ISSUE THREAD

**Issue by james4k** [golang/go#3575]
<pre>The attached source file reproduces the issue, by simply calling LookupHost in a loop,
in a few hundred goroutines.

It seems to be related to performing a large number of (concurrent?) DNS requests, and
localhost is not the only host name it happens on. It just highlights the fact that
something is not quite right. In my case, it happened with a basic web crawler which
makes a lot of concurrent requests, and eventually it would fail to connect to a local
DB, or any other host.

This was tested on Mac OS X Lion, using the binary release of Go1.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/3575/0/main.go">main.go</a> (238 bytes)

**Comment by mikioh** [comment]
I close this issue for the following reasons.

1. A glibc bug described in #6336 has been fixed in glibc-2.20 and beyond.
2. In go1.4, the internal lookup function lookupIPDeadline has been fixed in the case of slow simultaneous query-response exchanges. It is used by both CGO_ENABLED=1 and CGO_ENABLED=0 lookup functions.
3. In go1.4, built-in DNS stub resolver (which is enabled when CGO_ENABLED=0) has been improved in the case of simultaneous query-response exchanges.

In addition, go1.4 has a test case that is able to invoke simultaneous query-response exchanges.
```
cd $GOROOT/src/net
go test -v -run=TestLookupIPDeadline -dnsflood
```
Please try it for troubleshooting, when you have a question with regard to DNS behavior within dial, lookup APIs.

**Comment by pmoust** [comment]
@mikioh I think this is still happening..
```
 /usr/local/Cellar/go/1.4/libexec/src/net ⮀ ⭠ master  ⮀ go test -v -run=TestLookupIPDeadline -dnsflood
=== RUN TestLookupIPDeadline
--- PASS: TestLookupIPDeadline (3.58s)
	z_last_test.go:98: 59 succeeded, 9941 failed (9941 timeout, 9941 temporary, 0 other, 0 unknown)
PASS
ok  	net	3.605s
```

**Comment by pmoust** [comment]
Hm, 
wrong output pasted..
Still, I get lookup errors when launching about 250 goroutines that involve net.LookupIP()

**Comment by mikioh** [comment]
@pmoust,

Please open a new issue with https://github.com/golang/go/blob/master/CONTRIBUTING.md.
