### ISSUE TITLE
x/tools/gopls: errors when navigating through `git` ir `gitlens` URIs do not disappear anymore

### ISSUE THREAD

**Issue by inliquid** [golang/go#35846]
1. VS Code
2. gopls@master

Previously these errors would disappear after `git` or `gitlens` tab was closed. Now they stay until language server restart.

![изображение](https://user-images.githubusercontent.com/6797881/69646184-6a136f80-1078-11ea-9a37-904c7f0d1e09.png)

**Comment by stamblerre** [comment]
This is a result of [CL 208237](https://go-review.googlesource.com/c/tools/+/208237), which removed the previous behavior of clearing diagnostics when a file was closed. This change was made because `gopls` now shows diagnostics for an entire workspace. I think the right approach here will be for us to handle these files correctly (without showing errors). As a result, I will close this issue in favor of https://github.com/golang/go/issues/33699.
