### ISSUE TITLE
code organization of if conditions

### ISSUE THREAD

**Issue by RaymondReddington** [golang/go#35925]
now if conditions code structure:
if a &
   b &
   c {
}

i dont think this is clearly if a/b/c is long expression.
how about organize if conditions like this:
if a
   & b
   & c {
}
i think this will make relations between a,b,c clearly.

**Comment by ALTree** [comment]
Hi,

this is prevented by the automatic semicolon insertion rule. From [the spec](https://golang.org/ref/spec#Semicolons):

> The formal grammar uses semicolons ";" as terminators in a number of productions [...]
> 
> When the input is broken into tokens, a semicolon is automatically inserted into the token stream immediately after a line's final token if that token is
> 
> - an identifier 

`if a` would be turned into `if a;` so it's mandatory that the line ends with the logical operator.

Also the gofmt format has been quite stable since the Go1 release, and at this point it's unlikely to change much.

Closing here.
