### ISSUE TITLE
os: fix Windows (*os.File).Seek on directory handle

### ISSUE THREAD

**Issue by bradfitz** [golang/go#36019]
Half of our Windows builders (windows-386-2008, windows-amd64-2016, windows-amd64-longtest) fail to seek an *os.File opened on a directory.

But windows-amd64-2008 and windows-amd64-2012 work.

Figure this out and re-enable the test on Windows. (The test was added late in the Go 1.14 cycle, just before beta)

**Comment by networkimprov** [comment]
cc @alexbrainman @mattn @zx2c4

**Comment by alexbrainman** [comment]
Go use FindFirstFile, FindNextFile and FindClose Windows API to implement directory reading. The API does not provide functionality to seek to random position of the directory. I don't know what the alternatives are, if any.

Alex

**Comment by networkimprov** [comment]
Could File.Seek(0, os.SeekStart) be mapped to FindFirstFile() ?

**Comment by mattn** [comment]
`man 3 fdopendir` say:

>fd is used internally by the implementation, and should not otherwise be used by the application.

https://linux.die.net/man/3/opendir

As far as I can see the doc, Go should not support Seek for directory.

**Comment by zx2c4** [comment]
NtQueryDirectoryFile may be of use.

**Comment by alexbrainman** [comment]
> Could File.Seek(0, os.SeekStart) be mapped to FindFirstFile() ?

Yes. But people will still complain that File.Seel(1, os.SeekStart) fails. So, lets not pretend.

> NtQueryDirectoryFile

Yes, it might work. But is all extra new code worth ability to File.Seek?

Alex

**Comment by networkimprov** [comment]
>> Could File.Seek(0, os.SeekStart) be mapped to FindFirstFile() ?
>
>Yes. But people will still complain that File.Seel(1, os.SeekStart) fails. So, lets not pretend.

Well you could FindNextFile() in a loop for i < seek_pos?

**Comment by alexbrainman** [comment]
> Well you could FindNextFile() in a loop for i < seek_pos?

I don't understand what you are proposing. Please, send a CL with the change, if you know what to do.

Thank you.

Alex

**Comment by networkimprov** [comment]
I can't sign a copyright-transfer agreement, sorry. That's the only reason I don't make CLs.
```
func (f *File) Seek(pos int, from int) error {
   if is_directory(f) {
      if from != SeekStart { return &PathError{...} }
      FindFirstFile(...)
      for i := 0; i < pos; i++ {
         FindNextFile(...)
      }
   }
}
```

**Comment by alexbrainman** [comment]
> can't sign a copyright-transfer agreement, sorry. That's the only reason I don't make CLs.

Fair enough. Then I won't look at any of your code postings.

Alex

**Comment by networkimprov** [comment]
By that logic, you must check for the poster's CLA before reading __any post__ about Go, whether or not it contains code. The relevant clause:

_"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to Google for inclusion in, or documentation of, any of the products owned or managed by Google (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Google or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Google for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."_

From https://cla.developers.google.com/about/google-individual

cc @rsc

**Comment by odeke-em** [comment]
Punting to Go1.17 as we didn’t get much action for the Go1.16 development cycle.
