### ISSUE TITLE
how to setup vscode for reading golang runtime code?

### ISSUE THREAD

**Issue by coreyzzp** [golang/go#36069]
I have checkout the golang source code (1.13) and ready to jump into it, but found difficult to browser the code base (unable to find definition of a symbol, references etc.), not like normal go project. 

Is there anything I need to setup specially for the golang source code project?

---
after add the "go.goroot" setting to link to the work directory of go source, it solves the problem~

**Comment by ALTree** [comment]
> after add the "go.goroot" setting to link to the work directory of go source, it solves the problem~

It appears your problem is solved, then? 

Anyway we don't really use the github issue tracker for questions (only Go bugs), and this is a question about vscode, so it's more likely that someone in the vscode issue tracker/forum will be able to help you if you have any other question.

Closing here.
