### ISSUE TITLE
go mod local lib

### ISSUE THREAD

**Issue by woshihuo12** [golang/go#36143]
### What version of Go are you using (`go version`)?
1.13
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
windows10 64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

one private lib on bitbucket. has the source code local. go mod use local lib. but it still use bitbucket privileged. so other person has the local lib while not have the privilege. still can't use local lib. 

### What did you expect to see?

when use local lib. not need privileged. 

### What did you see instead?
still need privileged

**Comment by TheTannerRyan** [comment]
There are two possible solutions:

1. The privileged user (access to private repository) can run `go mod vendor`. This will vendor all of the dependencies locally. 
When using `go run`/`go build`, passing the `-mod=vendor` flag will instruct Go to resolve the dependencies locally instead of remote repos. See [this](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away) Wiki entry for more information.

2. If the unprivileged user (no access to private repository) has a local copy of the private repository, they can add a `replace` directive to the `go.mod` file. Also see [this](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) Wiki entry.

```
replace github.com/private/private => ../private
```
In this example, Go modules would resolve `github.com/private/private` in the local `../private` directory. After running `go mod vendor`, the `replace` directive can be removed as the dependencies will be present in `vendor/`.

Whether using option 1 or 2, `-mod=vendor` will have to be used for running/building.

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
