### ISSUE TITLE
cmd/vet: line numbers don't show up for "internal package not allowed" errors from _test files

### ISSUE THREAD

**Issue by yuanlai** [golang/go#36173]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
1. Set the env variable in .zshrc:
```
export GOPATH=$HOME/Github/service
```

2. Open my test file:
```
// $HOME/Github/service/src/github.com/myName/project/internal/user/user_test.go
package user_test

import (
    ...
    "github.com/myName/project/internal/platform/web"
)

...
```
3. It report a suspicious state from go-vet checker, the warm message is:
```
imports github.com/myName/project/internal/platform/web:
use of internal package github.com/myName/project/internal/platform/web not allowed
```

**Comment by cagedmantis** [comment]
Hi @yuanlai. I've attempted to reproduce the scenario posted above. `go vet` did not return any errors in my sample scenario. Can you post what command you are running that is producing these results?

**Comment by yuanlai** [comment]
I using emacs flycheck wrap the go-vet, the error occurs seems happen between flycheck and go-vet. https://github.com/flycheck/flycheck/issues/1659#issuecomment-565778463

**Comment by agnivade** [comment]
If the error comes from flycheck and not go-vet, then I'm afraid there is nothing we can do here.

But the issue you linked to shows that the issue is with vet. Could you please clarify ?

Please post the exact instructions that we can run from the command line to reproduce this. Thank you.

**Comment by yuanlai** [comment]
It seems a homebrew issue, I use the go install package directly download from web site, the problem has been removed.

**Comment by nicks** [comment]
I think there are two bugs here (one in flycheck and one in the `go` tool) and they stack in weird ways.

The `go tool` bug is that when it finds a bad "internal package" use in a test file, it doesn't report line numbers properly.

For example:

```
$ go vet /tmp/scratch/podmonitor.go
/tmp/scratch/podmonitor.go:11:2: use of internal package github.com/windmilleng/tilt/internal/k8s not allowed
$ go vet /tmp/scratch/podmonitor_test.go 
package command-line-arguments (test)
	imports github.com/windmilleng/tilt/internal/container: use of internal package github.com/windmilleng/tilt/internal/container not allowed
```

Notice that the first invocation reports line numbers, and the second invocation does not.

This confuses `flycheck`, because flycheck's Go mode expects all Go error messages to have line numbers attached.

How hard is it to fix this error message to have the right line numbers?

**Comment by cpitclaudel** [comment]
To be clear, Flycheck is failing because go-vet is producing error messages that don't match the usual pattern (which includes a line number).  Fixing that is just a matter of making that message conform to the usual template.

Now, the reason users are running into this message is that we create a temporary copy of their file (including unsaved changes) in a temporary directory before running go-vet; this breaks imports.

The ideal solution for us would be a way to feed file contents to go vet on stdin; then we wouldn't have to create temporary files: we'd just pass unsaved file contents on stdin and tell go-vet what the original file name was, so it could look up the imports properly.  (this is what we're doing with most other checkers).

**Comment by agnivade** [comment]
Thanks for the clarification ! I have a few follow-up questions:

- Is this was a regression or was it always there ?
- Is "use of internal package not allowed" the only error that does not have line number or are there other errors too ?

**Comment by cpitclaudel** [comment]
> Thanks for the clarification !

My pleasure! I'll let go users answer the two questions, since I don't know the answers myself :)

**Comment by nicks** [comment]
Yes, this is a regression. The bug is in Go 1.13, but not in Go 1.12

Repro steps:

Create a Dockerfile like

```
FROM golang:1.13
WORKDIR /go/src/github.com/fake/pkg
RUN echo 'package pkg' > pkg.go
RUN echo 'package pkg\n\nimport "golang.org/x/tools/internal/gopathwalk"\n' > pkg_test.go
RUN go get golang.org/x/tools/internal/gopathwalk
RUN go test ./
```

Run

```
docker build .
```

Result:
```
# github.com/fake/pkg
package github.com/fake/pkg (test)
	imports golang.org/x/tools/internal/gopathwalk: use of internal package golang.org/x/tools/internal/gopathwalk not allowed
```

Note that if I change the go version to 1.12 in the Dockerfile I get:

```
# github.com/fake/pkg
pkg_test.go:3:8: use of internal package golang.org/x/tools/internal/gopathwalk not allowed
```

which has the correct error message

**Comment by nicks** [comment]
I did a git bisect and confirmed the bug was introduced by this commit: https://github.com/golang/go/commit/f1d5ce0185fe184c016016d55f1718778b799f6d

The commit before that one does not have the bug
