### ISSUE TITLE
Dead lock happen with global mem map

### ISSUE THREAD

**Issue by youkpan** [golang/go#36252]
the var comes with a global map, a thread get and init it .  it runs ok with the first loop .dead at 2nd loop .

var g map[string ] w

type w struct{
 d map[int]int
sync.RWMutex
}

func c(b w){
b.Rlock()
// if not lock at a(),will panic here. 
...
b.RUnlok()
}

func a (){
//g has read lock too ,but no error
b:=g["t"]
c(b)
//dead lock here,the 2nd time enter a()
b.Lock()
b[1]=1
b.Unlock()
}

func main(){
 go a()
go a()
go a()

//mine is gin
g.GET("api",func(c *gin.Contex){
 a()
})
}

**Comment by youkpan** [comment]
centos 6

**Comment by randall77** [comment]
You are copying a mutex, which isn't allowed:

> A RWMutex must not be copied after first use.

The copy happens because you're passing b by value to c.

Unlike other projects, we do not use the issue tracker for questions such as these. It is only used for bugs and feature proposals. I will close this issue, but please feel free to ask it in any of these forums below:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks

**Comment by youkpan** [comment]
thanks!
