### ISSUE TITLE
cmd/go: how to use the git tag for the mod version?

### ISSUE THREAD

**Issue by chai2010** [golang/go#36314]
```
$ go version
go version go1.14beta1 darwin/amd64

$ git clone https://github.com/chai2010/fuckgomod.git
$ cd fuckgomod
$ git checkout v0.0.3

$ go build
$ go version -m ./fuckgomod 
./fuckgomod: go1.14beta1
	path	github.com/chai2010/fuckgomod
	mod	github.com/chai2010/fuckgomod	(devel)	
	dep	github.com/golang/glog	v0.0.0-20160126235308-23def4e6c14b	h1:VKtxabqXZkF25pY9ekfRL6a582T4P37/31XEstQ5p58=
$ 
```

mod version is **(devel)**:

```
	mod	github.com/chai2010/fuckgomod	(devel)	
```

https://github.com/chai2010/fuckgomod

**Comment by smasher164** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain. For questions about Go, please visit:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
