### ISSUE TITLE
Unable to run go in solaris 5.10

### ISSUE THREAD

**Issue by chakri-stark** [golang/go#36335]
### What version of Go are you using (`go version`)?
Using this port "https://github.com/4ad/go" to use for Solaris 5.10. Compiled the above port using go1.13.3

### Does this issue reproduce with the latest release?
No support for GOOS=solaris/GOARCH=sparc64 combination with Go out of box

### What operating system and processor architecture are you using (`go env`)?
Compiled sparc64 port on Linux 4.15.0-72-generic ubuntu 16.04.1

### What did you do?
Compiled the sparc64 port(https://github.com/4ad/go) in Linux machine with GOOS=solaris and GOARCH=sparc64
Copied the compiled sparc64 GO package to solaris 5.10 to compile usql, but unable to check go version command also
file command output is as follows:
$file go
go : ELF 64-bit MSB executable SPARCv9 version 1, dynamically linked, not stripped, no debugging information available

./go version output is attached in screenshot

### What did you expect to see?
Go running so that I can build usql (https://github.com/xo/usql)

### What did you see instead?
Attached the screenshot
![Go-solaris_sparc64](https://user-images.githubusercontent.com/43817788/71613881-b6e5eb00-2bce-11ea-8b43-bfc6b8de7ec6.jpg)

**Comment by ALTree** [comment]
Hi,

unfortunately solaris/sparc is not an officially supported combination, so issues encountered when using the port at github.com/4ad/go should not be reported in this issue tracker.

In this [golang-dev message](https://groups.google.com/d/msg/golang-dev/naOWkC6QuMo/qIJXbKKdBQAJ), Aram wrote:

> The solaris/sparc64 port for some version of Go between 1.7 and 1.8
> was more or less completed, but for various reason it was never
> integrated upstream. It currently ships with Solaris. I may or may not
> bring it up to date and upstream it. 

Moreover, in [this other message](https://groups.google.com/d/msg/golang-dev/U6BeWzVzERQ/qg85ghCSAQAJ) he noted that

> Sorry, Solaris 11+ only. Solaris 10 is not supported. 

If this information is up to date and `SunOS 5.10` corresponds to `Solaris 10`, then it appears that even the port at `4ad/go` does not support the system you are using; since it's Solaris 11+ only.

I'm closing this issue, since I don't believe this is actionable from the official Go compiler side.

**Comment by ianlancetaylor** [comment]
For what it's worth, gccgo does support SPARC Solaris.

**Comment by chakri-stark** [comment]
@ianlancetaylor , can you brief a little on how I can make use of this to build the usql library that I have mentioned. Thanks in advance.

**Comment by ianlancetaylor** [comment]
The simplest way would be to find a prebuilt version of GCC for Solaris that has been configured to include gccgo support.  If you want to build gccgo yourself, which is not an easy task, see https://golang.org/doc/install/gccgo .
