### ISSUE TITLE
runtime:remove unused code in rruntime.gcStart

### ISSUE THREAD

**Issue by jingyugao** [golang/go#36401]
```go
func gcStart(trigger gcTrigger) {
	mp := acquirem()
	if gp := getg(); gp == mp.g0 || mp.locks > 1 || mp.preemptoff != "" {
		releasem(mp)
		return
	}
	releasem(mp)
	mp = nil	// this line seems useless
```
https://github.com/golang/go/blob/master/src/runtime/mgc.go#L1232
I think this line should be removed.It is useless and redundant.

**Comment by mvdan** [comment]
Can you clarify why you think it's useless?

**Comment by jingyugao** [comment]
> Can you clarify why you think it's useless?

go compiler can do this automatically. 
After i remove this line, the md5 of binary doesnt change.

**Comment by ianlancetaylor** [comment]
`gcStart` is a big function.  Setting `mp = nil` ensures that nothing later in the function tries to use `mp` on the erroneous assumption that it is still valid even after the call to `releasem`.  This will protect against later changes to the function.  As you've already observed, doing this costs nothing.

**Comment by jingyugao** [comment]
> `gcStart` is a big function. Setting `mp = nil` ensures that nothing later in the function tries to use `mp` on the erroneous assumption that it is still valid even after the call to `releasem`. This will protect against later changes to the function. As you've already observed, doing this costs nothing.

https://github.com/golang/go/blob/05511a5c0ae238325c10b0e4e44c3f66f928e4cf/src/runtime/mgc.go#L1810
How about this line. It appeared at the end of function.
Though this costs nothing, it makes  confusion for many people.

**Comment by ianlancetaylor** [comment]
That `mp = nil` is the same pattern: after calling `releasem(mp)` set `mp = nil` so that nothing later in the function accidentally used a value that is not held.

This pattern may be confusing for people the first time they see it, but then they learn it and it is clear.  The runtime package is not designed to be read by people who are not working on the runtime package.  Anyone can read it, of course, but to understand it requires understanding the conventions and the limitations that it works under.  There are many special things about the runtime package.
