### ISSUE TITLE
go get done but nothing changes in src

### ISSUE THREAD

**Issue by denglouping** [golang/go#36483]
### What version of Go are you using (`go version`)?

<pre>
$ go version
D:\go-test>go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
didnt try

### What operating system and processor architecture are you using (`go env`)?
windows 7
<details><summary><code>go env</code> Output</summary><br><pre>
D:\go-test>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\suzumiya\AppData\Local\go-build
set GOENV=C:\Users\suzumiya\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go\code;D:\Users\administrator\go\src\awesomeProject
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go-test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

</pre></details>

### What did you do?
D:\go-test>go get -t -v github.com/golang/protobuf/proto
go: finding github.com/golang/protobuf v1.3.2
go: downloading github.com/golang/protobuf v1.3.2
go: extracting github.com/golang/protobuf v1.3.2

### What did you expect to see?
my code runs successfully.

### What did you see instead?
still telling me cannot find and nothing new in src
D:\Go\code\src\k8s.io\client-go\discovery\discovery_client.go:28:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	D:\Go\src\github.com\golang\protobuf\proto (from $GOROOT)
	D:\Go\code\src\github.com\golang\protobuf\proto (from $GOPATH)

![image](https://user-images.githubusercontent.com/11494366/72086023-3b5c0a80-3341-11ea-945d-d3b245171b10.png)

**Comment by seankhliao** [comment]
Run the go get command from the directory your code is in or with GO111MODULE=off

For future questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by bcmills** [comment]
This issue seems to be a question about how to use Go, rather than a feature request or defect report about the Go language and/or toolchain.

We have decided that our [experiment to allow questions on the issue tracker](https://golang.org/issue/23745) has not had the outcome we desired, so I am closing this issue. I'm sorry that we can't answer your question here.

There are many other methods to get help if you're still looking for answers:

* The [golang-nuts](https://groups.google.com/d/forum/golang-nuts) mailing list.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go), with questions tagged `go`.

* The [Go Forum](https://forum.golangbridge.org/), a web-based forum hosted by GoBridge.

* The [Gophers Slack](https://gophers.slack.com) hosted by GopherAcademy; use the [invite app](https://invite.slack.golangbridge.org/) for access.
   The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* **IRC** channel #go-nuts on Freenode

Thanks
