### ISSUE TITLE
CGO call in init() blocks forever

### ISSUE THREAD

**Issue by muthukrishnan24** [golang/go#36530]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/path/.cache/go-build"
GOENV="/usr/path/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/path/gopkg:/user/path/go_repo/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/usr/path/rocksdb/include/"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/usr/path/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd -ldl"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build809657240=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

small reproducible go file available here 
https://play.golang.org/p/DtuWWXs43dn
(not runnable in play, needs rocksdb and for setup refer https://github.com/tecbot/gorocksdb)

steps to reproduce:
1. run the file once, it will populate data into rocksdb
2. run the file again,
when called from init(), open() takes forever to execute
when called from main(), open() takes milliseconds to execute

### What did you expect to see?
open() should execute in ~milliseconds

### What did you see instead?
in init(), execution of open() does not complete (waited for 20mins+)

```
SIGQUIT: quit
PC=0x7f202241826b m=0 sigcode=128
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5bcd10, 0xc0000c7b40, 0xc0000ae020)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0000c7b10 sp=0xc0000c7ad8 pc=0x50913b
github.com/tecbot/gorocksdb._Cfunc_rocksdb_open_column_families(0x1b67ae0, 0x1b6eef0, 0xc000000002, 0xc0000943c0, 0xc0000943d0, 0xc0000943e0, 0xc0000ae020, 0x0)
	_cgo_gotypes.go:2358 +0x4e fp=0xc0000c7b40 sp=0xc0000c7b10 pc=0x5b3fce
github.com/tecbot/gorocksdb.OpenDbColumnFamilies.func3(0xc000082040, 0x1b6eef0, 0x2, 0xc0000c7d18, 0xc0000c7d00, 0xc0000c7d30, 0xc0000ae020, 0x5618f5)
	/usr/path/gopkg/src/github.com/tecbot/gorocksdb/db.go:120 +0x334 fp=0xc0000c7bb8 sp=0xc0000c7b40 pc=0x5b88c4
github.com/tecbot/gorocksdb.OpenDbColumnFamilies(0xc000082040, 0x8fa5c0, 0xc, 0xc0000c7e68, 0x2, 0x2, 0xc0000c7e20, 0x2, 0x2, 0x0, ...)
	/usr/path/gopkg/src/github.com/tecbot/gorocksdb/db.go:120 +0x350 fp=0xc0000c7d58 sp=0xc0000c7bb8 pc=0x5b62e0
main.openDb(0xc7a240, 0xc7a240, 0xc000094380)
	/usr/path/sample.go:88 +0x2fd fp=0xc0000c7eb8 sp=0xc0000c7d58 pc=0x5ba63d
main.open()
	/usr/path/sample.go:37 +0x26 fp=0xc0000c7f20 sp=0xc0000c7eb8 pc=0x5b9f96
main.init.0()
	/usr/path/sample.go:23 +0x20 fp=0xc0000c7f30 sp=0xc0000c7f20 pc=0x5b9f10
runtime.doInit(0xc465e0)
	/usr/local/go/src/runtime/proc.go:5222 +0x8a fp=0xc0000c7f60 sp=0xc0000c7f30 pc=0x53e2da
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x1da fp=0xc0000c7fe0 sp=0xc0000c7f60 pc=0x53229a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000c7fe8 sp=0xc0000c7fe0 pc=0x55a971

goroutine 17 [chan receive, locked to thread]:
runtime.gopark(0x901580, 0xc000084058, 0x170e, 0x3)
	/usr/local/go/src/runtime/proc.go:304 +0xe0
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
runtime.chanrecv(0xc000084000, 0x0, 0x1, 0x0)
	/usr/local/go/src/runtime/chan.go:524 +0x2e8
runtime.chanrecv1(0xc000084000, 0x0)
	/usr/local/go/src/runtime/chan.go:406 +0x2b
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:237 +0x207
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xc1
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:793 +0x9b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1

rax    0xca
rbx    0x1b6fc88
rcx    0x7f202241826d
rdx    0x2
rdi    0x1b6fc88
rsi    0x80
rbp    0x7ffddbf02e80
rsp    0x7ffddbf02dd8
r8     0x1b6fc88
r9     0x7f2023f4fa80
r10    0x0
r11    0x202
r12    0x0
r13    0x3b
r14    0x7ffddbf03100
r15    0x1b6f720
rip    0x7f202241826b
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by ianlancetaylor** [comment]
I don't see the cgo call in the test case that you provided.  I assume it is somewhere in rocksdb?

It would be extremely helpful if you or somebody could provide a standalone test case that does not rely on a large external package that requires setup.  Thanks.

(Note that this is expected behavior if rocksdb uses any Go shared libraries, though that is not particularly likely.)

**Comment by Ihtkas** [comment]
@tecbot Can you help with this to find the issue?

**Comment by Ihtkas** [comment]
@ianlancetaylor Does go have any restrictions on things done in init() calls like limited memory or thread limits as such? 

> Package initialization—variable initialization and the invocation of init functions—happens in a single goroutine, sequentially, one package at a time. An init function may launch other goroutines, which can run concurrently with the initialization code. However, initialization always sequences the init functions: it will not invoke the next one until the previous one has returned.

**Comment by ianlancetaylor** [comment]
There are no particular limits on `init` functions.

I took another look at the backtrace, and I see the problem.  When C code calls into Go code, we need to ensure that the Go code is fully initialized.  This particularly matters when C code starts a new thread that then calls into Go code.  Go code that is not invoked by an init function always assumes that initialization is complete--all init functions have been called, all package-scope variables have been set.  To implement that guarantee, we block the callback until Go initialization is complete.

That is what is happening here.  The call to rocksdb from an `init` function is causing a callback into Go code.  That callback is suspending until all `init` functions are complete, but the `init` function is waiting for rocksdb to return.  So there is a deadlock.

I don't think there is any to fix this in the Go tools or standard library, so closing the issue.  Please comment if you feel otherwise.
