### ISSUE TITLE
x/build/cmd/coordinator: reject unsupported builder types in slowbot requests

### ISSUE THREAD

**Issue by dmitshur** [golang/go#36560]
[CL 212101](https://go-review.googlesource.com/c/go/+/212101/4#message-0693a88a5e7c4056612617e13d5e6756eee7b6a4) has a comment from Dec 19 2019 that included `darwin-amd64-10_8` in a slowbot request. darwin-amd64-10_8 is not a builder type that we support.

https://farmer.golang.org/try?commit=8f9ad60e currently has the darwin-amd64-10_8 build for 8+ hr in waiting_for_machine state:

<img src="https://user-images.githubusercontent.com/1924134/72393547-2e546800-3701-11ea-8fa3-8326ce96a7d5.png" width="305px">

![image](https://user-images.githubusercontent.com/1924134/72393558-36aca300-3701-11ea-9084-2f137601f3a2.png)

`coordinator` should probably do something better than attempt to wait for a machine that we know will never become available.

I'm not sure if this is a general feature that needs to be implemented, or if there's something specific regarding darwin builder versions and perhaps this issue affects only darwin-amd64-10_8.

/cc @bradfitz @cagedmantis @toothrot

**Comment by bradfitz** [comment]
> darwin-amd64-10_8 is not a builder type that we support.

It's listed at https://farmer.golang.org/builders, so technically we do support it. Or at least that's what the code thinks.

Remember we maintain old builder images so we can still test older supported releases of Go. (But 10.8 is so old we can drop support for it: Go 1.12 is our oldest supported release and it requires macOS 10.10+: https://golang.org/doc/go1.12#darwin)

But if macOS 10.8 were still supported, the reason `darwin-amd64-10_8` takes forever to spawn is because of the TODO in cmd/makemac (#35698).

In this case, we just need to delete it from the builder config map.
