### ISSUE TITLE
libgo: regression in runtime test TestCallersNilPointerPanic on ppc64le with Go 1.14beta1 update

### ISSUE THREAD

**Issue by laboger** [golang/go#36696]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14beta1 gccgo (GCC) 10.0.1 20200122 (experimental) linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux/ppc64le
</pre></details>

### What did you do?
run the libgo tests

### What did you expect to see?
Passing tests

### What did you see instead?
=== RUN   TestCallersNilPointerPanic
    TestCallersNilPointerPanic: callers_test.go:82: wanted [runtime.Callers runtime_test.TestCallersNilPointerPanic..func1 runtime.gopanic runtime.panicmem runtime.sigpanic runtime_test.TestCallersNilPointerPanic], got [runtime.Callers runtime_test.TestCallersNilPointerPanic..func1 runtime.gopanic runtime.panicmem runtime_test.TestCallersNilPointerPanic testing.tRunner]
--- FAIL: TestCallersNilPointerPanic (0.00s)

**Comment by ianlancetaylor** [comment]
Nit: this is technically not a regression as such, as the test did not exist before the update to 1.14beta1.

Looks like the difference is that the test expects to see `runtime.sigpanic` on the stack, but it's not there.

Can you see whether adding `//go:noinline` before `panicmem` in libgo/go/runtime/panic.go fixes the problem?

**Comment by laboger** [comment]
Oh right, I didn't check to see if it was a new test. Do you want me to change the title?

I tried the //go:noinline suggestion and the test still failed.

**Comment by ianlancetaylor** [comment]
Nah, the title doesn't matter.

I guess there is some difference in the unwind results somehow.

**Comment by cherrymui** [comment]
This test also fails with gollvm (linux/amd64). I think it is because gollvm always generate an explicit nil check first, and may optimize it out at a late stage if there is a load or store. In this test, where we do `var p *int; *p = 3`, the backend sees `p` is constant nil so the faulting branch in the explicit nil check is certainly taken, and it eliminates the load and compiles it to a call to `panicmem`. This happens before the optimization of nil checks.

The PPC failure is probably different, if it uses implicit nil check (which I think it does for gccgo).

**Comment by laboger** [comment]
This test works now.
