### ISSUE TITLE
x/tools/go/gopackage: add Dir field to the Package struct

### ISSUE THREAD

**Issue by perillo** [golang/go#36730]
Currently, the `Package` struct does not have a `Dir` field, but instead there is a `Dir` field in the `Config` struct, specifying the directory in which to run the build system's query tool.

With *relative* queries, like `.` or `./...` it is possible to get a relative path to a .go source file.
However with queries like `fmt` or `golang.org/x/time/rate`, the caller has no way to obtain relative file names.

This may be a problem for some tools, like my https://github.com/perillo/goprint.
Showing something like `golang.org/x/time/rate  ...  /home/manlio/.local/lib/go/pkg/mod/golang.org/x/time@v0.0.0-20191024005414-555d28b269f0/rate/rate.go` instead of `golang.org/x/time/rate ... rate.go`  on the page top header is a bit problematic.

**Comment by matloob** [comment]
We don't plan to add a Dir field to the Package struct because not all build systems have a concept of a directory for the package.

So in a sense, the concept of a relative file name to a package doesn't exist in general, for all build systems.

But I'd like to understand your example better, by asking a question to help me understand: Is `golang.org/x/time/rate ... rate.go`, in the format of `<package path> ... <package-relative file name>` ?  If so, why wouldn't it work to emit `<package path> ... <file base name>`?  It should be what you want almost all of the time. Could we do something else to make it work ?

**Comment by perillo** [comment]
@matloob The file base name should be fine. I did not think about it since I was fixated on using the `Dir` field.  Thanks.

However probably I will still have to use `go list` directly instead of gopackages, since I may need to include the ignored files and test files in the generated document.

**Comment by matloob** [comment]
Okay, that's reasonable. I'll close this issue.
