### ISSUE TITLE
website: go 1.13.7 is out, but golang.org/VERSION?m=text still 1.13.6

### ISSUE THREAD

**Issue by ukai** [golang/go#36886]
go 1.13.7 is out
https://groups.google.com/forum/#!msg/golang-announce/Hsw4mHYc470/WJeW5wguEgAJ

but golang.org/VERSION?m=text still shows go1.13.6

**Comment by ALTree** [comment]
Thanks for reporting this.

cc @katiehockman @dmitshur

**Comment by bcmills** [comment]
CC @toothrot @cagedmantis

**Comment by cagedmantis** [comment]
Thank you for reporting this. We are aware of the issue and are working towards resolving it.

**Comment by dmitshur** [comment]
This will be done in the next few days. If you're looking for more up-to-date Go release information, I suggest using either the https://golang.org/dl/?mode=json endpoint, which is updated as soon as release downloads are available, or the [maintner API](golang.org/x/build/maintner/maintnerd/apipb) (see usage example [here](https://dmitri.shuralyov.com/talks/2019/whats-new-in-go1.12/go1.12.slide#3)), which is updated as soon as releases are cut (the tag is published).

In order to resolve this, we need to merge the `release-branch.go1.13-security` into `release-branch.go1.13` branch, and redeploy golang.org. Doing that merge is currently blocked until we finish making improvements to permissions. I'm working with @FiloSottile and @katiehockman on resolving that.

We need to finish this before we can cut the next minor releases, which are generally done at the beginning of each month, so soon.

**Comment by mvdan** [comment]
I've filed an idea very much related to this problem at https://github.com/golang/go/issues/36898, if you are interested.

**Comment by dmitshur** [comment]
This is fixed now.

```
$ curl 'https://golang.org/VERSION?m=text'
go1.13.7
```
