### ISSUE TITLE
x/lint: golint does not recognize Unwrap methods

### ISSUE THREAD

**Issue by perillo** [golang/go#36997]
`golint` does not complain if a method implementing *know* interfaces is not documented.
However when I define the `Unwrap` method, it complains:
```
exported method Error.Unwrap should have comment or be unexported
```

By the way, how I'm supposed to document the method?
```
// Unwrap implements support for error unwrapping.
```
or
```
// Unwrap implements the Unwrapper interface.
```
?

**Comment by cagedmantis** [comment]
Could you provide more information for this issue? Could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link?

**Comment by perillo** [comment]
Sure, sorry.

https://play.golang.org/p/8Zy-WTR7J9B

`golint` will report:
```
test/unwrap.go:17:1: exported method Error.Unwrap should have comment or be unexported
```

Note how there is no warning about the Error method not having a comment since it is a *well know* interface.

**Comment by perillo** [comment]
Here is the code that should be updated:
https://github.com/golang/lint/blob/master/lint.go#L836

Thanks

**Comment by cagedmantis** [comment]
Thank you for the clarification.

**Comment by matloob** [comment]
Lint is really noisy and my preference is to keep its behavior fixed. If you want to send a CL to add Unwrap to the list of known methods I'd be okay with it.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all golint issues before we freeze its repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!

**Comment by perillo** [comment]
Thanks for the notification.
