### ISSUE TITLE
x/pkgsite: automatically fetch a requested package if it does not exist on pkg.go.dev

### ISSUE THREAD

**Issue by natefinch** [golang/go#37002]
Currently, if you request package docs from pkg.go.dev for a package that hasn't been sent to the go proxy yet, then it just returns 404.  

Requesting a url from pkg.go.dev should do whatever "add your package" does, if that's required to view the docs, because clearly I want to view the docs and the server knows exactly what step is missing to allow me to view the docs, so just do it, please.

By returning a 404 page, it looks like there's a bug in the website. The suggested "how to add your package" requires some arcane steps (I presume? it's not actually spelled out) that simply shouldn't be necessary.  

See https://github.com/golang/go/issues/36986 for an example of someone reporting a "bug" because a package didn't show up.

This is actually super common when using godoc.org in my experience, as I will often want to view the docs on godoc.org as I'm writing the code, to see how they look there.  I'm sure others will want to do the same on pkg.go.dev.

This can also easily happen if most people in your company use a corporate proxy, so the code isn't in go's proxy yet, but then you decide you want to view the docs and you're just used to doing it on pkg.go.dev (which I do all the time for random go packages on godoc.org... rather than download them and view the docs locally, I view 99% of docs directly on godoc.org).

**Comment by hunterloftis** [comment]
I remember the "magic" of having my open-source projects auto-doc'd for me. Someone had to point out to me that I no longer needed to build my own markdown-generating toolchain for docs - instead, they would "just exist" and even be searchable, alongside major, important packages.

I believe this suggestion aligns with that beginner-friendly "it just works" philosophy that has long been a part of the language and community.

**Comment by stephenandwood** [comment]
If immediate fetch is not possible for some reason, then add a "request documentation" button to the 404 page.  Clicking the button kicks of whatever needs to be done and shows UI explaining when the documentation will be available.

**Comment by deeper-x** [comment]
I'm joining this thread because I consider this as a detrimental change in the language.
The way godoc.org works is how things should be, [as Andrew Gerrand says](https://blog.golang.org/godoc-documenting-go-code)
> [...] it should be coupled to the code itself so the documentation evolves along with the code. The easier it is for programmers to produce good documentation, the better for everyone

Plain and simple: in Go, code & documentation are tightly coupled by default. No surprises expected, because publishing your code you're publishing the documentation on godoc.org as well.  

What you quietly introduced with pkg.go.dev and mention [there](https://go.dev/about#adding-a-package) breaks this flow, silently assuming that now could exist code-without-documentation.  
Furthermore, suggesting a workaround, forcing a faking a download and triggering the documentation generation, cannot be considered a stable solution.

**Comment by deeper-x** [comment]
I'm joining this thread because I consider this as a detrimental change in the language.
The way godoc.org works is how things should be, [as Andrew Gerrand says](https://blog.golang.org/godoc-documenting-go-code)
> [...] it should be coupled to the code itself so the documentation evolves along with the code. The easier it is for programmers to produce good documentation, the better for everyone

Plain and simple: in Go, code & documentation are tightly coupled by default. No surprises expected, because publishing your code you're publishing the documentation on godoc.org as well.  

What you quietly introduced with pkg.go.dev and mention [there](https://go.dev/about#adding-a-package) breaks this natural flow introducing a weird exception, silently assuming that now could exist public code-without-documentation.  
Furthermore, suggesting a workaround like forcing a fake download in order to trigger the documentation generation, cannot be considered a stable solution.

**Comment by deeper-x** [comment]
I'm joining this thread because I consider this as a detrimental change in the language.
The way godoc.org works is how things should be, [as Andrew Gerrand says](https://blog.golang.org/godoc-documenting-go-code)
> [...] it should be coupled to the code itself so the documentation evolves along with the code. The easier it is for programmers to produce good documentation, the better for everyone

Plain and simple: in Go, code & documentation are tightly coupled by default. No surprises expected, because publishing your code you're publishing the documentation on godoc.org as well.  

What you quietly introduced with pkg.go.dev and mention [there](https://go.dev/about#adding-a-package) breaks this natural flow introducing a weird exception, silently assuming that now could exist public code-without-documentation.  
Furthermore, suggesting a workaround like forcing a fake download in order to trigger the documentation generation, cannot be considered a stable solution.

**Comment by julieqiu** [comment]
Users can now request a package by clicking a button on the 404 page. 

Here's an example:


<img width="1419" alt="Screen Shot 2020-07-30 at 4 03 01 PM" src="https://user-images.githubusercontent.com/5943521/88968973-2663ac00-d27e-11ea-96c3-d7384ce31792.png">

**Comment by criscola** [comment]
> Users can now request a package by clicking a button on the 404 page.

Is there any way to retrigger the request for the module? I've updated my module (same version, forgot small addition, no users are relying on my package) but I still see the older version.

**Comment by julieqiu** [comment]
@criscola you can either visit pkg.go.dev/<your-module-path>@master, or follow the instructions at https://go.dev/about#adding-a-package.

**Comment by criscola** [comment]
@julieqiu I've tried but my godocs is still not getting updated to the latest commit.

**Comment by julieqiu** [comment]
@criscola - since this is a closed issue, could you please file a new issue at https://golang.org/s/pkgsite-feedback?

https://github.com/golang/go/issues/43096 also seems related.
