### ISSUE TITLE
doc/install: update “Test your installation” step to be agnostic to module mode

### ISSUE THREAD

**Issue by tkl4230** [golang/go#37042]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOENV="/Users/xxxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5k/x27nkdh9605dcjwmgmxbdr0c0000gn/T/go-build407033626=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I tried to create a go environment and proceeded according to the tutorial.

https://golang.org/doc/install?download=go1.13.7.darwin-amd64.pkg

Do you need `go mod init` before `go build`??
or execute `go build hello.go`.

<pre>
$ pwd
/Users/xxxx/go/src/hello
$ ls
hello.go
$ go build
go: cannot find main module; see 'go help modules'

$ cat hello.go
package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}
</pre>

**Comment by ianlancetaylor** [comment]
This is happening because you have the environment variable `GO111MODULE=on`.  That is telling the go tool that you will always be building in module mode.  The go tool is complaining because it can't find a go.mod file for your program.

@bcmills @jayconrod We need a better error message here, or different behavior.

**Comment by bcmills** [comment]
@ianlancetaylor, do you have a specific suggestion? `cannot find main module` seems pretty unambiguous, and at this point in time we don't expect Go users to get very far without learning the basics of modules.

**Comment by bcmills** [comment]
The issue as originally reported seems like a documentation problem: [_How to Write Go Code_](https://tip.golang.org/doc/code.html) has been updated to include the necessary `go mod init` step, but users will typically read and follow the Testing step in `doc/install.html` before they get to _How to Write Go Code_.

Probably we should suggest testing the installation using `go build hello.go` (which works regardless of the `GO111MODULE` setting) instead of just `go build`.

**Comment by bcmills** [comment]
Heh, the “workspace” link in that section is broken too. (It uses a `#Workspaces` anchor that no longer exists.)

**Comment by tkl4230** [comment]
I did not notice `GO111MODULE = on`.

I know that the default value is `auto`.
https://golang.org/doc/go1.13#modules

Previously, when I installed another version of Go, I set `GO111MODULE = on`, but this time, I did not set` GO111MODULE = on` myself after installing ...

Is it possible that the values from the previous installation are cached?
Is there any way to change the settings other than `go env -w GO111MODULE = on`?

**Comment by ianlancetaylor** [comment]
@bcmills Think about what this is like for someone who knows nothing.  Maybe people have to learn the basics of modules, but they can only do that if we help them.  For a beginner to Go, "cannot find main module" means nothing.  Better might be something like

cannot determine module because no go.mod file found; see "go help modules"

and, at least until module mode is the default,

(running in module mode because environment variable GO111MODULE=on)

And then "go help modules" (if that is indeed the right link) could use some cleanup as it is written from the perspective of someone who understands GOPATH.

**Comment by ianlancetaylor** [comment]
@tkl4230 Yes, if you used `go env -w` then those values are cached.  You can remove the setting with `go env -u`.

You can also set the environment variable for just one session using your shell, typically

    export GO111MODULE=on

**Comment by tkl4230** [comment]
@ianlancetaylor 
Thank you for your reply.
I understand.

**Comment by bcmills** [comment]
I think that even `because no go.mod file found` would be confusing at this point in the flow: nothing in the “Getting Started” doc describes what a `go.mod` file is or how to create one, so “`go.mod file`” is nearly as mysterious as `main module`.

Similarly, `GO111MODULE=on` implies that the user explicitly set that variable at some point, so they probably have at least seen an introduction to using modules before that point. So I'm not sure that detail would be helpful to beginners either.

We certainly do need to clean up `go help modules` to make it more approachable, though. (That is #33637.)

**Comment by ianlancetaylor** [comment]
Can we at least have the error message point people to "go help modules" (if that is the best place)?

I don't really agree that "no go.mod file" is nearly as mysterious; at least it tells you exactly what is missing, and gives you a starting point for progress.

**Comment by bcmills** [comment]
> Can we at least have the error message point people to "go help modules" (if that is the best place)?

The error text already ends with: `see 'go help modules'`.

**Comment by ianlancetaylor** [comment]
Oh, right, sorry.

**Comment by bcmills** [comment]
This should now be fixed in http://tip.golang.org/doc/install: the “Test your installation” instructions are now module-agnostic (and more concise), and the descriptions of `GOPATH` and `go install` now occur after the introduction to modules in the new-user flow.
