### ISSUE TITLE
x/tools/godoc: struct field anchor is added to wrong location when another field comment above it has same prefix

### ISSUE THREAD

**Issue by c-yan** [golang/go#37041]
[Certificate.Leaf](https://tip.golang.org/pkg/crypto/tls/#Certificate.Leaf) is linked to Certificate.PrivateKey instead of the location in the Certificate.Leaf field.

**Comment by odeke-em** [comment]
Thank you for this report @c-yan!

Kindly paging @katiehockman @FiloSottile.

**Comment by FiloSottile** [comment]
Hah, it's because there's a documentation line that starts with `Leaf` in the `PrivateKey` docs.

This is an x/tools/cmd/godoc bug.

/cc @dmitshur

**Comment by dmitshur** [comment]
Good analysis @FiloSottile.

As an observation, this bug is not present in the documentation rendering algorithm used by pkg.go.dev:

https://pkg.go.dev/crypto/tls/#Certificate.Leaf

/cc @julieqiu

We can use this issue to track the problem in `golang.org/x/tools/cmd/godoc`. If it's not fixed separately, it should get resolved when its rendering algorithm is unified with the others.

**Comment by c-yan** [comment]
Documentation has been moved to https://pkg.go.dev/ and fixed, so I'm closing it.
