### ISSUE TITLE
x/website/{internal/dl,content/static}: there is no closing tag for <div class="Header-menuButtonInner">

### ISSUE THREAD

**Issue by c-yan** [golang/go#37075]
Looks like there is no closing tag for \<div class="Header-menuButtonInner">.
https://github.com/golang/website/blob/master/internal/dl/tmpl.go#L87

**Comment by dmitshur** [comment]
Thanks for reporting.

I see another place where the same unclosed div tag occurs:

[https://github.com/golang/website/blob/60ca7b88/content/static/godoc.html#L45](https://github.com/golang/website/blob/60ca7b88d9f3483502691e0ce811391b1baae864/content/static/godoc.html#L45)

I know HTML5 allows certain tags to be omitted, and some HTML style guides suggest doing that (e.g., see https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags).

However, \<div\> is not one of the elements whose closing tag is allowed to be omitted according to the [HTML5 spec](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission). Running validator.w3.org on golang.org [confirms](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgolang.org%2F) that it is an error:

<img src="https://user-images.githubusercontent.com/1924134/74003047-3b025f80-493f-11ea-816c-8a4e0f033e8e.png" width="424px">

So the fix to this issue is to add a \</div\> closing tag in those two places in x/website.

/cc @andybons

**Comment by bradford-hamilton** [comment]
Submitted PR for this through Gerrit
