### ISSUE TITLE
go.dev: README with ".markdown" extension rendered as plain text on overview tab

### ISSUE THREAD

**Issue by stephenandwood** [golang/go#37137]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/dustin/go-humanize?tab=overview
 
### What is your user agent?
 
Issue is independent of user agent. 
  
### What did you do?
 
I visited the page. 
 
### What did you expect to see?
 
I expected to see the markdown in the readme file rendered as HTML. The file is rendered as HTML on GitHub. [link](https://github.com/dustin/go-humanize#readme).
 
### What did you see instead?

I saw the markdown source as text.

**Comment by dmitshur** [comment]
The reason pkg.go.dev is rendering it as plain text instead of Markdown is because the README file in the https://github.com/dustin/go-humanize repo has a ".markdown" extension rather than the more common ".md", and pkg.go.dev currently doesn't recognize it.

According to https://tools.ietf.org/html/rfc7763, the file extensions for text/markdown are:

```
File extension(s): .md, .markdown
```

/cc @julieqiu

**Comment by julieqiu** [comment]
Fixed.
