### ISSUE TITLE
dl: add go1.5.4, go1.6.4 and go1.7.6

### ISSUE THREAD

**Issue by perillo** [golang/go#37156]
The `golang.org/dl` module for some reasons does not include `go1.5.x`, `go1.6.x` and `go1.7.x`.
I tested on my PC and they can be installed correctly.  Is there a reason why they should not be included?

Rationale:
I was finding the minimal required Go version to build and test a package, for fun.  It worked until go1.8.x.  Now I found that it works up to go1.7.x.

**Comment by dmitshur** [comment]
Issue #18136 was the proposal for implementing this that has more context. It likely wasn't done because `golang.org/dl/...` (which was originally located in `golang.org/x/build/version/...`) was created [in December of 2016](https://github.com/golang/build/commit/071a06af6abd38e55f9f8643f0ba90697a68171f#diff-2af72f100c356273d46284f6fd1dfc08) and Go 1.8 beta was coming out at that time. Go 1.7 was released earlier in 2016. /cc @andybons @bradfitz Let me know if you're aware of reasons not to do this, but I'm currently not aware of any.

We have downloads available for Go 1.5.x, 1.6.x, and 1.7.x. I think it's reasonable to add commands for them to `golang.org/dl`. /cc @toothrot @cagedmantis

The latest minor releases of those versions are:

- go1.7.6
- go1.6.4
- go1.5.4

Let's start by adding just those 3 versions. If there's a good reason to add other minor versions and beta/rcs or even older major versions of Go; we can consider doing that afterwards.

The `goX.Y.Z` command are generated with the [`golang.org/dl/internal/genv`](https://pkg.go.dev/golang.org/dl/internal/genv) command.

**Comment by shihanng** [comment]
I would like to try to work on this one if no one is currently working on it.

**Comment by dmitshur** [comment]
Thanks @shihanng, based on the comments in this issue, it’s all yours.

(Please see https://golang.org/doc/contribute.html if it’s your first time sending a CL or PR.)
