### ISSUE TITLE
x/tools/gopls: add support for 'refactor.extract.constant' code actions

### ISSUE THREAD

**Issue by stamblerre** [golang/go#37170]
See https://github.com/microsoft/vscode-go/issues/3040.

https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_codeAction has more details on the possibilities here.

The function refactoring can be implemented by making use of guru's freevars code.

**Comment by joshbaum** [comment]
https://golang.org/cl/241957 and https://golang.org/cl/240182 support extracting a function and variable, respectively, as a code action. The following are open issues with function extraction:

- [ ] Extraction does not include comments. Comments are replaced with newlines in the extracted function. 
- [ ] You cannot extract a selection that begins with or ends with a comment.
- [ ] Control flow statements (break, continue, goto, etc.) are not handled specially. This can produce bad code if extracted poorly.
- [ ] Defer statements are not handled specially. This can also produce bad code if extracted poorly.
- [ ] Identifiers can be on the left-hand side of an assignment statement even if they are never used again. This produces a yellow line with the message "_variable_ is never used." This occurs when a variable name is used later in scope, but the first time it is used after the selection, it is defined again (using :=) rather than assigned. This does not produce incorrect code, but should be fixed.

**Comment by stamblerre** [comment]
Ok, if you are seeing a refactoring there but it doesn't work with the hotkey, then this is probably a VS Code bug, not a bug in the extension. Please file an issue with https://github.com/microsoft/vscode.

**Comment by suerta-git** [comment]
Hi @stamblerre thanks for your reply. I tried to reinstall my vscode and restore to the initial state. Then set one customized shortcut like this in `keybindings.json` (refer to [official doc](https://code.visualstudio.com/docs/editor/refactoring)):

```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "alt+cmd+v",
        "command": "editor.action.codeAction",
        "args": {
          "kind": "refactor.extract.variable"
        }
    }
]
```

The issue still exists: 

**Using quick fix (`cmd + .` in mac os)**:

<img width="580" alt="Screen Shot 2021-10-17 at 5 48 44 PM" src="https://user-images.githubusercontent.com/59438603/137621817-7efccb6b-9b30-479e-9eb1-4645a767a4a4.png">

**Using shortcut (`alt+cmd+v` defined above)**:

<img width="672" alt="Screen Shot 2021-10-17 at 5 37 57 PM" src="https://user-images.githubusercontent.com/59438603/137621904-d95d6435-4868-4bea-b0cb-8aca38cb1fa7.png">

As a reference, for other languages,`refactor.extract.constant` shortcut is avaiable on TypeScript (doesn't support `refactor.extract.variable`), but both of two shortcuts aren't avaiable on Python and C#.

Seems even though vscode provides the ability for customizing shortcuts, this feature is not well supported by language extensions. Not sure if it is due to some bugs in vscode.

**Comment by suzmue** [comment]
gopls sets the codeActionKind for `Extract variable` to be `refactor.extract`. So the keybinding would need to be

```
{
        "key": "alt+cmd+v",
        "command": "editor.action.codeAction",
        "args": {
          "kind": "refactor.extract"
        }
    }
```

We should definitely consider being more specific for the code action kinds to enable keybindings like this.

**Comment by NateWilliams2** [comment]
I've started attacking this issue at https://go.dev/cl/564338 and added tests/enabled the usage of `refactor.extract.constant`, `refactor.extract.function`, and `refactor.extract.variable`. 

One possible issue is that I have not implemented a new type of code action for constants- the `refactor.extract.constant` still calls `internal/golang/extract.go:extractVariable`. The issue here is if someone calls `refactor.extract.constant` on a non-constant variable, the typical variable extraction will occur rather than an error stating that the target must be a constant. 
I am not well-versed in the [ast](https://pkg.go.dev/go/ast) package that `extractVariable` uses to analyze the type of variable, but I imagine it would be possible to confirm that the target is a constant and then run the extraction. Does anyone have advice here? Thanks in advance.
