### ISSUE TITLE
go.dev: Examples title is not generated, anchor link to examples is not working

### ISSUE THREAD

**Issue by rakyll** [golang/go#37198]
On https://pkg.go.dev/cloud.google.com/go, the "Examples" anchor link is not working because there is no "Examples" title in the page. I couldn't reproduce it in other pages.

**Comment by dmitshur** [comment]
Thanks for reporting.

**Comment by dmitshur** [comment]
There was an issue in the template for the edge case when a package has examples, but no exported identifiers.

The fix is to display the "Index" section (which includes the "Examples" subsection) in that case, so that the link on top is valid. This is consistent with x/tools/cmd/godoc and gddo. I've sent a fix CL.

**Comment by dmitshur** [comment]
This issue is resolved at https://pkg.go.dev/cloud.google.com/go by now, so I'll close this. Please let me know if there's anything more.
