### ISSUE TITLE
x/website: some sub-repositories are missing from golang.org/pkg/#subrepo

### ISSUE THREAD

**Issue by perillo** [golang/go#37265]
The *sub-repositories* `arch`, `lint`, `mod`, `oauth2`, `term`, `website` and `xerrors` are missing from https://tip.golang.org/pkg/#subrepo.

They are also missing (with `debug`, `perf`, `review` and `time`) from https://godoc.org/-/subrepo.

**Comment by dmitshur** [comment]
See also #24432.

This is intentional. That list is not exhaustive, it includes repos that are more noteworthy.

Commit https://github.com/golang/tools/commit/370143dbcae1edc3c1c0f447e98e00a837bddd2d made it more clear that it was intentional, but that code has been factored into `x/build/repos` by now.

**Comment by dmitshur** [comment]
That said, we may want to consider including some of the newer repos, such as `x/mod` and `x/xerrors`.

**Comment by seankhliao** [comment]
I believe https://pkg.go.dev/golang.org/x is the canonical advertised list now.
