### ISSUE TITLE
x/pkgsite: example code should be displayed as package main when rendering

### ISSUE THREAD

**Issue by fishy** [golang/go#37291]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/reddit/baseplate.go@v0.0.0-20200327042237-1365288992e4/thriftclient?tab=doc#example-package

### What did you expect to see?
 
On godoc.org, the `Example*` functions will be renamed to main when rendering, for example: https://godoc.org/github.com/reddit/baseplate.go/thriftclient#example-package
 
### What did you see instead?

On pkg.go.dev we kept the original Example function name in the code.

**Comment by julieqiu** [comment]
Thanks for reporting the bug, @fishy! We'll look into it. 

/cc @dmitshur

**Comment by AceroM** [comment]
This issue was fixed in https://golang.org/cl/240685, and will be available soon on pkg.go.dev. It is currently behind the [executable-examples experiment flag](https://github.com/golang/pkgsite/blob/56517e4b414745c963a2b1b9250c236631d9011f/internal/experiment.go#L29).

If you would like to test it out locally, you can run `go run ./devtools/cmd/experiment create executable-examples`.

The output should look like this:
![image](https://user-images.githubusercontent.com/21187304/90787625-ec148a00-e2d2-11ea-854e-6836f2b70a2e.png)
