### ISSUE TITLE
golang alpine docker image should include git

### ISSUE THREAD

**Issue by relax-admin** [golang/go#37314]
Since go mod needs git to download `private libraries`, such as gitlab, do you consider adding `git` to `docker golang alpine`?

### What version of Go are you using (`go version`)?

<pre>
$ go version
docker: golang:1.13-alpine
</pre>

### What did you do?

There is a go mod project that references the gitlab private library. When I execute go build, it prompts an error.

### What did you expect to see?

``` shell
go: downloading gitlab.srxcloud.com/test-group/utils v0.0.1
go: extracting gitlab.srxcloud.com/test-group/utils v0.0.1
go: finding gitlab.srxcloud.com/test-group/utils v0.0.1
```

### What did you see instead?
``` shell
go: gitlab.srxcloud.com/test-group/utils@v0.0.1: git init --bare in /go/pkg/mod/cache/vcs/4057063b4e5edfa5f3fcb02ce9e41e5fbddacd674d24e08a9780bd04e1bc7d74: exec: "git": executable file not found in $PATH
```

**Comment by ALTree** [comment]
Hi,

we don't control or distribute the Go docker images, so you should file an issue in the docker image issue tracker, here: https://github.com/docker-library/golang

In any case, someone already did file an issue asking for git: https://github.com/docker-library/golang/issues/297.

Closing here, since this is not an issue related to the Go Project.
