### ISSUE TITLE
x/crypto: edwards25519.go has unnecessary code that does not appear in reference or other implementations

### ISSUE THREAD

**Issue by WernerVasquez** [golang/go#37536]
The following code located at https://github.com/golang/crypto/blob/2aa609cf4a9d7d1126360de73b55b6002f9e052a/ed25519/internal/edwards25519/edwards25519.go#L750 is unnecessary and is not in the reference or many other widely used implementations:

```
		FeToBytes(&tmpX, &p.X)
		for i, v := range tmpX {
			tmp2[31-i] = v
		}
```
While FeToBytes does change the form of p.X, but it does not impact the point represented by p.

tmpX and tmp2 are never used for anything beyond this snippet.

Obviously, the declaration of the variables at line 738 is also not needed.

See the following to verify this code is not present in the ref10 implementation:

https://github.com/floodyberry/supercop/blob/a351f2c29235512a042d4b6989d241a67e86ad23/crypto_sign/ed25519/ref10/ge_frombytes.c#L42

Perhaps this was debugging code that was left in on accident? Or is there some real utility that I am just not seeing?

**Comment by ALTree** [comment]
cc @FiloSottile

**Comment by WernerVasquez** [comment]
@FiloSottile It seems questionable to have off reference code with no documented purpose in a crypto package.

It is especially strange since it "appears" to do nothing.

It doesn't change the answer. 

It does process a meaningful number. It changes the representation of that number. But to what end....?

I'd like to believe it is there to mitigate some side channel attack. But without any documentation, I am far more concerned that it could create a side channel attack.

**Comment by AlexanderYastrebov** [comment]
* `Sep 2, 2013` it looks like a debug residue to reverse bytes and was there since at least initial commit https://github.com/agl/ed25519/commit/5613cf01b3df739fcda8f197edaf754fa9e627b1#diff-6028ef115d234d026c54c74b0385933c410a436f30cb14890dfa602623bebe02R1107 of the source library 
* `Apr 26, 2016` it was later imported https://github.com/golang/crypto/commit/c9aef117f53e16ed3a6cc3d93cd357dbf2005065 into x/crypto golang/go#8581
* `Apr 26, 2019` then x/crypto was vendored into the main repo https://github.com/golang/go/commit/3cafbeab2a56f52f7c8265a0b0c45d494b541f84#diff-c8a9a0e49597c0d07d7b6c959dffc5da54229d5d4c66ef5089d17c4d6c87a909R738
* `May 7, 2019` then promoted to the stdlib crypto https://github.com/golang/go/commit/53374e7e068c032b9e6278e592974e973a554365 #25355
* `Jun 19, 2019` x/crypto/ed25519 was turned into a wrapper for crypto/ed25519 beginning with Go 1.13 https://github.com/golang/crypto/commit/ea8f1a30c4438cc8b13f05538385ad8dc6049b43 #25355
* `May 5, 2021` finally stdlib implementation was replaced https://github.com/golang/go/commit/b0c49ae9f59d233526f8934262c5bbbe14d4358d#diff-173c944c84e5280f8a8b138130977fa846a3bb394718a72e0b4948d7c51fc8c4L738 and does not contain tmp variables

So it looks like that stdlib now contains maintained implementation and x/crypto/ed25519 is a wrapper
