### ISSUE TITLE
x/website/internal/dl: ?mode=json&include=all don't list older unstable releases when there are newer stable releases

### ISSUE THREAD

**Issue by perillo** [golang/go#37581]
The documentation at https://godoc.org/golang.org/x/website/internal/dl says that
```
An additional query param, include=all, when used with the mode=json query param, will serve a full list of available downloads, including stable, unstable, and archived releases in JSON format
```

However currently https://golang.org/dl/?mode=json&include=all does not include unstable releases.

Another issue is that for go < 1.6, the `SHA256` field is empty, but there is no `SHA1` field that is instead present  on the HTML page, in the **archived versions** section.

**Comment by dmitshur** [comment]
The `include=all` query parameter was proposed in issue #29380 and implemented in [CL 163741](https://golang.org/cl/163741). The intention was to include all unstable releases. It looks like there's a bug in that implementation that's preventing older unstable releases from showing up when a newer stable release is available.

This bug needs to be fixed. We should add test cases for this so this behavior doesn't regress.

> Another issue [...]

Mind filing a separate GitHub issue for that? I'm not sure if we'll want to fix it because those versions are old, but in any case, it'll be easier to discuss and track it separately.

**Comment by perillo** [comment]
Done: #37586

Thanks.

**Comment by myitcv** [comment]
Just to point out, per #43975, that every time this happens GitHub actions builds that are helpfully testing out new unstable versions stop working:

> This is turn has caused any GitHub actions builds that have `go1.16beta1` in their build matrices, kicked off since the release of `rc1`, to fail.

**Comment by myitcv** [comment]
Just to reiterate the previous point that now Go 1.16 has been released all GitHub builds using rc1 have stopped working

**Comment by dmitshur** [comment]
This is fixed. Old pre-release Go versions are now considered archived rather than not being included at all, and they show up both at the bottom of https://golang.org/dl/#archive and in the API with when `include=all` is set.

Thanks for the report, and thanks to @seankhliao for investigating the problem and sending the fix CL.
