### ISSUE TITLE
ConfigureWebAssembly1.13.3

### ISSUE THREAD

**Issue by ali2210** [golang/go#37628]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
Hello Assembly on my console

### What did you see instead?
LinkError: "import object field 'runtime.nanotime' is not a Function"

![Screenshot from 2020-03-03 18-11-29](https://user-images.githubusercontent.com/20568079/75779007-aabb0d00-5d7a-11ea-9627-274ec8912043.png)

**Comment by dmitshur** [comment]
How did you produce the .wasm file? Did you follow the steps at https://golang.org/wiki/WebAssembly#getting-started or something else?

Which version of `wasm_exec.js` file are you using?

**Comment by ali2210** [comment]
WASM_EXEC.JS vERSION i DON'T KNOW. However I FOLLOW ALL STEPS STEPS COPY
BECAUSE IT THROW ERROR cp. So I copy from github. When i run command it
produce wasm file. However I already in my go directory
This Message send through secure channel called BBM

**Comment by dmitshur** [comment]
> So I copy from github.

If you copied it from GitHub, you might have gotten the version from Go 1.14. In your original issue report, you said you were using Go 1.13.3. If that's the case, that could explain the problem you're seeing.

You should ensure you're using a matching version of the Go compiler and the `wasm_exec.js`.

If you're looking to get help or have more questions about this, I recommend the resources listed at https://golang.org/wiki/Questions. They are better suited for asking questions. We use the issue tracker for tracking bugs in the Go project, so fewer people will be able to answer questions here.

**Comment by ali2210** [comment]
how to check version wasm_exec.js
This Message send through secure channel called BBM

**Comment by agnivade** [comment]
The version of wasm_exec.js is tied to the Go repo version. If you are taking wasm_exec.js from Github, you likely have taken from the master branch. That will not be compatible with your installed Go distribution, which is Go 1.13.3.

To get the right wasm_exec.js, you need to get it from `$(go env GOROOT)/misc/wasm/wasm_exec.js`.

I will close this issue now since this is not a bug. If you still have problems, please feel free to ask your question in any of the forums below:
* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks
