### ISSUE TITLE
Feature Request/Proposal: Envoirment based newline

### ISSUE THREAD

**Issue by Philippjambit** [golang/go#37655]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yee

So basically it would be nice to have a envoirment library which one could use to achieve cross compatibility. The only example i have is a \<something\>.Newline Function which would return a (probably runtime.GOOS based) string containing newline characters (for windows (\r\n) because innovation is poison and you need that typewriter backwards compatibility). This might be integratable in the syscall or strings library.

Needed like 5mins of code.

**Comment by DisposaBoy** [comment]
> Needed like 5mins of code.

I'm not the one you need to convince, but I think you just explained why it's not a good fit for inclusion in the std lib :p.

I personally can't remember a case where I've ever seen a valid use of such a feature and it only takes 10? seconds to write the 2-6 lines of code - most of which you don't even need to actually type if you're using IDE-like tools like goimports.

	nl := "\n"
	if runtime.GOOS == "windows" {
		nl = "\r\n"
	}

**Comment by ianlancetaylor** [comment]
If you want to propose a change, you need have at least some specific suggestions, such as a package name and a function.  If you think this idea is worth pursuing I recommend that you use a forum to refine it.  See https://golang.org/wiki/Questions.

I'm going to close this issue because I don't see anything actionable here.
