### ISSUE TITLE
x/pkgsite: tag like v17.03.1 is not recognized as a version

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#37851]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/mod/github.com/docker/docker?tab=versions

 
### What is your user agent?
 
Google Chrome  Version 80.0.3987.132 (Official Build) (64-bit)
 
### Screenshot

n/a
 
### What did you do?
 
Opened the page
 
### What did you expect to see?

v17, v18 and v19 versions, with the latest one being  v19.03.8
 
### What did you see instead?

v1.3.1 is shown as the latest version
v17.x, v18.x, v19.x is not shown at all.

### More info

Docker (https://github.com/moby/moby aka github.com/docker/docker) has switched to date-based versions a few years ago. The latest non-date-based version was `v1.3.1`, and after it `v17.03.0-ce-rc1` was released (see https://github.com/moby/moby/tags?after=v17.05.0-ce-rc1).

Apparently, pkg.go.dev do not recognize versions > 9, as a result it shows documentation from 2017 and there's no way to change that.

This is a regression, since godoc.org shows the latest docs.

// Cc @thaJeztah

**Comment by kolyshkin** [comment]
OK it seems like the leading zero (as in `03` from `v19.03.1`) is the source of a problem. Not sure how to deal with it though

**Comment by thaJeztah** [comment]
it only supports SemVer format, not CalVer

**Comment by thaJeztah** [comment]
In addition to expecting tagging to be done on the master branch (no support for release branches) which I think is why v1.13.1 is no longer picked up (later than v1.3.1, but not tagged on master)

**Comment by thaJeztah** [comment]
oh, ignore the last comment, that may be have been with go mod itself

**Comment by dmitshur** [comment]
pkg.go.dev interprets versions in the same way as the `go` command in module mode. The problem here seems to be that repository doesn't publish versions that are compatible to be used with the `go` command.

> OK it seems like the leading zero (as in `03` from `v19.03.1`) is the source of a problem. Not sure how to deal with it though

Right, `v19.03.1` is not a valid semver tag because of a leading zero in the minor version component. https://semver.org/#spec-item-2 says:

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT contain leading zeroes**.

---

> Not sure how to deal with it though

There a few relevant issues in that project's issue tracker, you can leave a 👍 reaction to show your support:

- https://github.com/moby/moby/issues/31842
- https://github.com/moby/moby/issues/39302
- https://github.com/moby/moby/issues/39056

/cc @julieqiu

**Comment by jba** [comment]
Filed moby/moby#41382.
