### ISSUE TITLE
math/cmplx: Tan incorrect on s390x for large arguments

### ISSUE THREAD

**Issue by bmkessler** [golang/go#37854]
s390x fails the tests for Tan with large arguments due to incorrect argument reduction in the trigonometric routines for the base math packages.
```
--- FAIL: TestTan (0.00s)
    cmath_test.go:839: Tan((-1.329227995784916e+36+0i)) = (NaN+NaNi), want (0.40806638884180424+0i)
    cmath_test.go:839: Tan((1.7668470647783843e+72+0i)) = (NaN+NaNi), want (-0.37603456702698074+0i)
    cmath_test.go:839: Tan((2.037035976334486e+90+0i)) = (NaN+NaNi), want (4.60901287677811+0i)
    cmath_test.go:839: Tan((-3.1217485503159922e+144+0i)) = (NaN+NaNi), want (3.391359650547799+0i)
    cmath_test.go:839: Tan((1.8919697882131776e+69+0i)) = (NaN+NaNi), want (-6.76813854009065+0i)
    cmath_test.go:839: Tan((-2.514859209672214e+105+0i)) = (NaN+NaNi), want (-0.7641769501660493+0i)
```
This is due to the fix for #31566, but the underlying issue has been present since #6794 was fixed.  The temporary solution after that change was to just disable the tests for s390x.

I think the s390x assembly implementations need to be fixed or they should just revert to the pure go versions for large arguments.

@griesemer @mundaym

**Comment by Vishwanatha-HD** [comment]
Found a fix and made code changes. Tested the fix and made sure that its working fine. I will raise my code changes for review in Gerrit...

**Comment by mknyszek** [comment]
CC @golang/s390x

**Comment by Vishwanatha-HD** [comment]
I have raised a CL to fix this issue and its under review. Please note that my fix has been tested and its working fine.

Please find the link below:
https://go-review.googlesource.com/c/go/+/470595

Benchmark details of Tan function with table driven inputs are as below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/003RNA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/003RNA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Benchmarks | Without any code   changes: | With assembly   code changes | With native Go   code changes
-- | -- | -- | --
Tan/2^(-1)-8 | 10.17 ns/op | 10.23 ns/op | 13.53 ns/op
Tan/2^(1)-8 | 10.02 ns/op | 10.16 ns/op | 13.16 ns/op
Tan/2^(10)-8 | 9.852 ns/op | 10.11 ns/op | 13.32 ns/op
Tan/2^(20)-8 | 10.62 ns/op | 10.69 ns/op | 12.77 ns/op
Tan/2^(40)-8 | 10.25 ns/op | 10.76 ns/op | 13.42 ns/op
Tan/2^(50)-8 | 10.69 ns/op | 10.89 ns/op | 13.16 ns/op
Tan/2^(51)-8 | 10.38 ns/op | 10.52 ns/op | 13.55 ns/op
Tan/2^(52)-8 | 2.505 ns/op | 31.63 ns/op | 40.26 ns/op
Tan/2^(60)-8 | 2.507 ns/op | 33.48 ns/op | 40.60 ns/op
Tan/2^(80)-8 | 2.520 ns/op | 31.57 ns/op | 42.28 ns/op
Tan/2^(100)-8 | 2.503 ns/op | 31.94 ns/op | 40.70 ns/op
Tan/2^(200)-8 | 2.617 ns/op | 27.24 ns/op | 37.57 ns/op
Tan/2^(400)-8 | 2.809 ns/op | 28.51 ns/op | 37.43 ns/op
Tan/2^(-10)-8 | 10.13 ns/op | 10.48 ns/op | 13.25 ns/op
Tan/2^(-15)-8 | 10.17 ns/op | 10.29 ns/op | 12.52 ns/op
Tan/2^(-20)-8 | 10.26 ns/op | 10.53 ns/op | 13.54 ns/op
Tan/3^(-10)-8 | 10.07 ns/op | 10.18 ns/op | 12.25 ns/op
Tan/3^(-15)-8 | 10.14 ns/op | 10.31 ns/op | 12.51 ns/op



</body>

</html>

From the above table, please note that the time taken for all the inputs beyond "2^51" till "2^400" is just around "2ns" (as shown in the first column) with the existing code, because the Tan function was only returning a "NaN" value as soon as the control enters it. No logic was getting executed and hence no time was spent in the function.
