### ISSUE TITLE
go: github.com/fsnotify/fsnotify@v1.4.7 used for two different module paths

### ISSUE THREAD

**Issue by xenolinux** [golang/go#37911]
### What version of Go are you using (`go version`)?
go version go1.13.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/go/src/github.com/rook/rook/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fv/vj47yds914l85mffr16rzynm0000gn/T/go-build095961487=/tmp/go-build -gno-record-gcc-switches -fno-common
</pre></details>

### What did you do?
Forked repo twice. (by deleting the old repo)

It gives me this error in my editor after saving the file.
`go: github.com/fsnotify/fsnotify@v1.4.7 used for two different module paths (github.com/fsnotify/fsnotify and gopkg.in/fsnotify.v1)`

Also `$ go mod tidy
go: finding github.com/yanniszark/go-nodetool latest
github.com/rook/rook/pkg/operator/cassandra/sidecar imports
	github.com/yanniszark/go-nodetool/nodetool imports
	github.com/yanniszark/go-nodetool/version tested by
	github.com/yanniszark/go-nodetool/version.test imports
	github.com/yanniszark/go-nodetool: module github.com/yanniszark/go-nodetool@latest found (v0.0.0-20191206125106-cd8f91fa16be), but does not contain package github.com/yanniszark/go-nodetool
github.com/rook/rook/pkg/operator/cassandra/controller imports
	k8s.io/kubernetes/pkg/controller/endpoint imports
	k8s.io/kubernetes/pkg/controller imports
	k8s.io/kubernetes/pkg/apis/core/validation tested by
	k8s.io/kubernetes/pkg/apis/core/validation.test imports
	k8s.io/apiserver/pkg/util/feature/testing: module k8s.io/apiserver@latest found (v0.17.4), but does not contain package k8s.io/apiserver/pkg/util/feature/testing
`

**Comment by agnivade** [comment]
Likely a duplicate of https://github.com/golang/go/issues/26904.

The issue is somewhere in the code, you are importing gopkg.in/fsnotify.v1 whereas the right module path is github.com/fsnotify/fsnotify. As evident from here: https://github.com/fsnotify/fsnotify/blob/45d7d09e39ef4ac08d493309fa031790c15bfe8a/go.mod#L1.

If the code is something you can control, then it's something you should fix. If it's something you cannot control, then a replace directive won't help and you probably have to wait for 1.15.

But from your report, it does look like it's in your code.

Your second issue does not look like a Go bug. Ulike other projects, we do not use the issue tracker for questions such as these. It is only used for bugs and feature proposals. Please feel free to ask it in any of these forums below:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Thanks

**Comment by rodrigc** [comment]
@agnivade I ran into the same problem.  Is there any workaround?

I did `go mod why | grep fsnotify` and see:

```
github.com/spf13/viper@v1.3.2 github.com/fsnotify/fsnotify@v1.4.7
github.com/onsi/gomega@v1.4.2 github.com/fsnotify/fsnotify@v1.4.7
github.com/onsi/gomega@v1.4.2 gopkg.in/fsnotify.v1@v1.4.7
github.com/prometheus/prometheus@v2.9.2+incompatible gopkg.in/fsnotify/fsnotify.v1@v1.3.1
github.com/onsi/gomega@v1.4.3 github.com/fsnotify/fsnotify@v1.4.7
github.com/onsi/gomega@v1.4.3 gopkg.in/fsnotify.v1@v1.4.7
github.com/maxbrunsfeld/counterfeiter@v0.0.0-20181017030959-1aadac120687 github.com/fsnotify/fsnotify@v1.4.7
github.com/maxbrunsfeld/counterfeiter@v0.0.0-20181017030959-1aadac120687 gopkg.in/fsnotify.v1@v1.4.7
github.com/improbable-eng/thanos@v0.5.0 github.com/fsnotify/fsnotify@v1.4.7
github.com/improbable-eng/thanos@v0.5.0 gopkg.in/fsnotify/fsnotify.v1@v1.4.7
sigs.k8s.io/controller-runtime@v0.2.2 gopkg.in/fsnotify.v1@v1.4.7
```
