### ISSUE TITLE
go.dev: help reset a package on pkg.go.dev

### ISSUE THREAD

**Issue by adamluzsi** [golang/go#37938]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
The issue is unrelated to the go compiler.

### What operating system and processor architecture are you using (`go env`)?
The issue is unrelated to the go compiler.

### What did you do?
Dear Go team,

I would like to request help to reset my package cached data on the pkg.go.dev website.
In my project: [github.com/adamluzsi/testcase](https://github.com/adamluzsi/testcase)
I had to edit/rebase an early commit in my git history
and changed all the commit hash for the project.
After I noticed this, I made things worst by panicking and deleting the tags.
Now, this resulted in the situation where the pkg.go.dev and my repo not in sync.

I would like to request help to remove data of my package from pkg.go.dev,
so it can have an initial state again and no tags from the past.
Like it would be a new freshly made package.

### What did you expect to see?
When I open the following link after the pkg reset: https://pkg.go.dev/github.com/adamluzsi/testcase
It will will show the package and only the latest state.

Cheers,
Adam

**Comment by julieqiu** [comment]
Hey Adam - Unfortunately we can't reset packages. 

The reason is because we fetch our data from the Go Module Mirror (http://proxy.golang.org). The mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin.

See: `I removed a bad release from my repository but it still appears in the mirror, what should I do?` under the FAQ section of https://proxy.golang.org. 

My recommendation would be for you create a new version of the package, so that is the latest version that users would see by default instead.

Alternatively, we can only remove the module entirely from the site. However, you would need to start over until a different module path.

**Comment by myitcv** [comment]
In this regard also take a look at https://github.com/golang/go/issues/24031#issuecomment-597263309, planned for 1.15.

**Comment by adamluzsi** [comment]
Thank you @julieqiu and @myitcv ,
Then I will proceed like that and create a tags as suggested.
Thank you for your time! : )
