### ISSUE TITLE
Proposal: Permitting dead code with "go run"

### ISSUE THREAD

**Issue by es20490446e** [golang/go#38001]
https://youtu.be/lkD6u0kiv-Y

**Comment by ALTree** [comment]
Uuh... I don't think we accept bug reports / proposals that consist in a link to a 10 minutes youtube video.

Regarding your title:

> Proposal: Permitting dead code with "go run"

Go run just calls the compiler, puts the generated binary in the temp folder, and executes it; so everything that you cannot do in a program that you compile and run, you cannot do when invoking `go run`.

I also think it would be unwise to have a run-flavoured Go and a build-flavoured Go, which behave differently (e.g. some program compiles with `go run` but it doesn't with `go build`). Consistency is important. 

Finally, what you're asking here is essentially a way to turn off certain kind of errors, but this kind of proposal has been rejected many times in the past. Since it's unlikely that what you're asking will happen, I'm closing this issue.

**Comment by es20490446e** [comment]
@ALTree The proposal isn't about omitting errors, it's a way of speaking for not making the title overly complicated.

It's about how you treat them, why on quality assurance we have two ways of dealing with errors and not only one.

Mistake proofing can be either hard or soft. Hard is stopping further processing as soon as an error appears for encouraging sooner fixing, as Go does. This is the preferred way for most cases.

But there's also soft error proofing. Soft error proofing just makes any error obvious, but without forcing its correction.

This latest is interesting when the error could be left ON PURPOSE. For example, when you are just prototyping code, and you don't want to be constantly commenting and uncommenting unused variables and imported modules, cause that duplicates the amount of work.

For that context hard error proofing isn't preventing any real error, but just making your life harder.

That's why 'go build' and 'go run' shall be different in that regard, because they refer to different user cases. 'go build' is used for building the final product, where 'go run' is used for prototyping.

**Comment by ALTree** [comment]
I understand this, but as I wrote: you are essentially asking for warnings instead of errors, but with the additional gotcha that some things (but not others) are warning in `go run` and errors in `go build`. Proposals to add warnings (or ways to turn off some errors, like unused variables) have been posted again and again and again, and they were rejected again and again and again. I just don't see it happen.

**Comment by es20490446e** [comment]
May I ask why you decided to reject it, just out of my personal curiosity? 👀

**Comment by randall77** [comment]
The rationale is described here: https://golang.org/doc/faq#unused_variables_and_imports

**Comment by es20490446e** [comment]
Ah, thanks 👌
