### ISSUE TITLE
runtime: timer self-deadlock due to preemption point

### ISSUE THREAD

**Issue by mknyszek** [golang/go#38070]
The problem was discovered in kubernetes/kubernetes#88638, where Kubernetes was seeing some kubelets get wedged. They grabbed a stack trace for me, and after combing over it I summarized the problem. Below are the highlights:

> [...] There's a self-deadlock going on in the timer system.
> 
> 1. A goroutine does: `timer.Reset -> resettimer -> modtimer -> wakeNetPoller`
>     * At this point, the timer its resetting is in the `timerModifying` state.
> 1. Now, at the beginning of `wakeNetPoller`, we get a preemption request (synchronous, so unrelated to asynchronous preemption), so we call into `morestack`.
> 1. The chain now goes `morestack -> gopreempt_m -> goschedImpl -> schedule -> checkTimers -> runtimer`
> 1. Now we try to run the timer _we were modifying_, but it's currently being modified, so we loop and `osyield`. It never stops being in `timerModifying`, though.

(https://github.com/kubernetes/kubernetes/pull/88638#issuecomment-603918184)

> [...] this can only happen if the timer is in the `timerDeleted` and at the top of the heap, and indeed `(*time.Timer).Reset` does stop (delete) the timer before resetting it. So, this doesn't imply a racy use of timers on Kubernetes' end.
> 
> Looking at the state machine in `time.go` again, [...] it could _only_ ever happen with the `wakeNetPoller` call, because in `addInitializedTimer` we grab a runtime lock around `cleantimers` and `doaddtimer`, which prevents preemption. 
> 
> Maybe what happened is that we accidentally inserted a preemption point? What if it was the case that in `resettimer` before `wakeNetPoller` was actually inlined, but in `addInitializedTimer` it's not. This means we added in a preemption point unintentionally.
> 
> One idea for the fix is to just... make sure `wakeNetPoller` gets inlined (and maybe https://go-review.googlesource.com/c/go/+/224902 actually does that), but that seems fragile. We should probably say that while a goroutine owns a timer in `timerModifying` it should not be allowed to be preempted, because it can cause an operation that waits (perhaps the same for other `-ing` states).

(https://github.com/kubernetes/kubernetes/pull/88638#issuecomment-603935042)

CC @ianlancetaylor

**Comment by mknyszek** [comment]
@gopherbot Please open a backport to 1.14.

**Comment by bcmills** [comment]
Does this deadlock account for the test failures observed in #37894?

**Comment by bcmills** [comment]
(Looks like probably not.)

**Comment by mknyszek** [comment]
@bcmills It looks to me like those test failures are in fact this bug.

**Comment by mm4tt** [comment]
@mknyszek, thanks for debugging it and fixing it so quickly.
When can we expect the fix to be released?

**Comment by mvdan** [comment]
I think I've hit the same bug in a long-running server with many thousands of goroutines. This early morning, the process just froze forever - even a goroutine that was simply logging some trivial stats every minute or so was not responding. One of the runnable goroutines is at `runtime.resettimer`, so that's a bit suspicious, and how I found this bug.

[2020-03-26-hang-log.txt.gz](https://github.com/golang/go/files/4387446/2020-03-26-hang-log.txt.gz)

@mknyszek do you think it's the same bug, or should I file a new one?

I should note that this is a server that works fine with Go 1.13.x, but started hanging like this since we jumped to 1.14.x. I had been testing it with 1.14.x for weeks before, but we hadn't started running the long-lived staging servers with 1.14.x.until earlier this week.

**Comment by ianlancetaylor** [comment]
@mm4tt The normal schedule for the next release would be next week some time.

@mvdan That is almost certainly the same bug.
