### ISSUE TITLE
net: call WSAGetLastError on Windows

### ISSUE THREAD

**Issue by networkimprov** [golang/go#38134]
Winsock API calls don't set `errno`, instead you call `WSAGetLastError()`. It looks like Go doesn't. Have I missed something?

https://docs.microsoft.com/en-us/windows/win32/winsock/error-codes-errno-h-errno-and-wsagetlasterror-2

This affects net.isConnError() and a fix for #35131.
```
func isConnError(err error) bool {
        if se, ok := err.(syscall.Errno); ok {
                return se == syscall.WSAECONNRESET || se == syscall.WSAECONNABORTED
        }
        return false
```
cc @bcmills @ianlancetaylor @iWdGo @alexbrainman @zx2c4 @mattn @jstarks
@gopherbot add OS-Windows

**Comment by ianlancetaylor** [comment]
`WSAGetLastError` is just a synonym for `GetLastError`.  At least on amd64 the Go runtime cheats by inlining `GetLastError` to just load directly from `%gs`.  See `asmstdcall` and `getlasterror` in runtime/sys_windows_amd64.s.

If we get this wrong somewhere lets look at that specific case, but I'm going to close this general issue because there shouldn't be a general problem here.

**Comment by networkimprov** [comment]
Ah, sorry; that's not mentioned in the MS docs, but described in
https://stackoverflow.com/questions/15586224/is-wsagetlasterror-just-an-alias-for-getlasterror
