### ISSUE TITLE
x/tools/cmd/stringer: support for upper / lower / title case

### ISSUE THREAD

**Issue by maltegrosse** [golang/go#38229]
Hi Everybody,

it would be great to have stringer works with different case styles like
-case=toUpper 
-case=toLower
-case=title
using the strings function
https://golang.org/pkg/strings/#ToUpper
https://golang.org/pkg/strings/#ToLower
https://golang.org/pkg/strings/#Title
(also in combination with "trim-prefix")

### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13

</pre>

### Does this issue reproduce with the latest release?
Feature Request, yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...
</pre></details>

### What did you expect to see?
fmt.println(SomeTypeZero ) --> "zero" or "ZERO"

### What did you see instead?
"Zero"

**Comment by andybons** [comment]
Thanks for the issue.

It’s difficult to know the exact behavior you want because you don’t provide example code or shell output.

That said, cmd/stringer is considered feature complete and no work aside from bug fixes will likely be done on it. You can easily fork it to support your use-case, however.
