### ISSUE TITLE
x/build/cmd/coordinator: no "Trybots beginning" message when running multiple times on the same patchset

### ISSUE THREAD

**Issue by stamblerre** [golang/go#38235]
I occasionally want to run TryBots multiple times on the same patchset. Based on the behavior on https://golang.org/cl/227117, it seems like this works, but it doesn't send out the "TryBots beginning" message with a link to their progress. This makes me think that the TryBots aren't running.

/cc @dmitshur @cagedmantis @toothrot

**Comment by dmitshur** [comment]
Thanks for reporting. This is indeed a problem for usability.

The reason it happens is because the message that coordinator constructs when trybots are restarted on the same commit ends up being identical to a previously posted one (because the commit hash is unchanged), and there is code to prevent duplicate messages from being posted:

https://github.com/golang/build/blob/61705b562fc995a53af15476c91f6ad3dcf1aae8/cmd/coordinator/coordinator.go#L1363

When that spam filter was created, we probably didn't anticipate this situation where duplicate messages are expected.

We should fix this either by adjusting the spam filter to permit duplicate "TryBots beginning" messages, or perhaps better, make it so that the message it posts isn't duplicate by adding " (attempt 2)", " (attempt 3)", etc., suffixes (if it's not too hard to compute what attempt it is).

**Comment by dmitshur** [comment]
Based on commit message and discussion in [CL 310186](https://golang.org/cl/310186),
I understand this is fixed in https://github.com/golang/build/commit/c328b2763bf4ffb82cfcc32b9ac9ac5f2bb0afd7 ([CL 310015](https://golang.org/cl/310015)).
(CC @FiloSottile, @ianlancetaylor.)
