### ISSUE TITLE
version choose

### ISSUE THREAD

**Issue by caleb-letsgo** [golang/go#38289]
There are so many versions of golang, which one should I choose? Like is 1.12.17 better than 1.12.1? Is 1.12 better than 1.11? If I don't think about new features but stability, which version should I choose?

**Comment by ALTree** [comment]
Go 1 release cycle is 6 months long, which means that every 6 months a new version gets released; that's when the second number gets incremented. For example:

- Go 1.12  (February 2019)
- Go 1.13 (August 2019)
- Go 1.14 (February 2020)

All Go 1.X version are retro-compatible, which means that you should always choose the latest (today, it's 1.14).

Minor releases gets issued to fix problems in the released Go version (but never to add features). When that happens, the third number is incremented. So for example, Go 1.13 had these bugfix releases:

- Go 1.13.1
- Go 1.13.2
- ... Go 1.13.9

Once you have chosen a Go1 release (now, Go 1.14), you should always download the latest bugfix release for that version. Which, right now, means Go1.14.1

Closing here, since I've answered your question.
