### ISSUE TITLE
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?) Still exists in 1.14.2 release.

### ISSUE THREAD

**Issue by GiridharSamanth** [golang/go#38366]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build869160065=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you see instead?
Web application getting terminated constantly.
Two fatal errors:
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
and
fatal error: sweep increased allocation count

**Comment by ianlancetaylor** [comment]
Looks like memory corruption.  Have you tried your program with the race detector (https://golang.org/doc/articles/race_detector.html)?  Does your program use the unsafe package?  Does it use cgo?

**Comment by GiridharSamanth** [comment]
@ianlancetaylor. I didn't tried the race detector. We aren't using cgo directly but have to check with the third party libraries.
Our's is a web service with very high throughput, and to deliver faster responses, we highly relied on waitgroups.

**Comment by GiridharSamanth** [comment]
@dmitshur May i know, what more information is required.

**Comment by ianlancetaylor** [comment]
We can help you look into the problem yourself.  That is what I tried to do by suggesting that you try the race detector.

If you want us to look into the problem for you, we will need a copy of your program and exact instructions for how to replicate the problem.  We aren't going to be able to say anything else without that kind of information.

As I said above, this is almost certainly memory corruption.  As memory corruption is impossible in pure Go without races, this is almost certainly due to a race in your program, or due to incorrect use of the unsafe package, or due to incorrect use of cgo.

Of course, there could be a bug in Go that is causing this problem.  But in my experience, this sort of problem is almost always a bug in the program, not in Go.

FYI, you may get better help if you ask on a forum.  See https://golang.org/wiki/Questions.

**Comment by GiridharSamanth** [comment]
Thanks @ianlancetaylor i will try to debug and update the thread.

**Comment by GiridharSamanth** [comment]
Fixed the issue. It was a global variable used inside with waitgroups. Thanks all.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
