### ISSUE TITLE
crypto/ecdsa: remove unnecessary external package imports

### ISSUE THREAD

**Issue by hallazzang** [golang/go#38392]
https://github.com/golang/go/blob/83bfe3b1bf25021d0a33352bed12696f5abe420a/src/crypto/ecdsa/ecdsa.go#L107-L112
https://github.com/golang/go/blob/83bfe3b1bf25021d0a33352bed12696f5abe420a/src/crypto/ecdsa/ecdsa.go#L318-L330

Here `golang.org/x/crypto/cryptobyte` package is used to marshal/unmarshal ASN.1 data structures, although there is `encoding/asn1` already.
It is easy to replace `cryptobyte` with standard `asn1` package, as shown below.

```go
return asn1.Marshal([]*big.Int{r, s})
```

```go
var seq []*big.Int
if _, err := asn1.Unmarshal(sig, &seq); err != nil {
	return false
}
return Verify(pub, hash, seq[0], seq[1])
```

**Comment by andybons** [comment]
@katiehockman @FiloSottile

**Comment by FiloSottile** [comment]
`golang.org/x/crypto/cryptobyte` is not a third-party package, but part of a module maintained by the Go team and already vendored into the standard library. Its use here is deliberate because it allows us to check that the ASN.1 sequences have no extra tags, which the `encoding/asn1` version would allow.
