### ISSUE TITLE
x/playground: UI disappears with a small window

### ISSUE THREAD

**Issue by egonelbre** [golang/go#38482]
In https://play.golang.org/ when you click "Share" and the browser window area is less than 900px then the UI disappears.

![2020-04-16 13_05_13-Window](https://user-images.githubusercontent.com/192964/79443757-efc19880-7fe2-11ea-9616-c8ac69c725ce.png)

**Comment by smasher164** [comment]
Before the dropdown was added to the banner, that breakpoint was 775px.
Moving `#shareURL`, `#embedLabel`, and `.js-playgroundToysEl` from under `#controls` to under `#banner` fixes this issue, but extra styling must be applied to keep those elements inline with those inside `#controls`.

**Comment by egonelbre** [comment]
Any reason not to switch to using flexbox which should behave better in presence of wrapping?

**Comment by smasher164** [comment]
My solution above is more of a stop-gap measure. I believe the styling used in the updated golang.org design already has flexbox. There is a [pending CL](https://go-review.googlesource.com/c/playground/+/188557) to update the playground with this design.

That being said, I agree with you that it's probably better to just switch to flexbox to address this issue, since future additions to the playground would only exacerbate this breakpoint.

/cc @andybons Thoughts?

**Comment by andybons** [comment]
@egonelbre flexbox is fine with me. The playground UI was written far before that became a widely-supported feature.

**Comment by smasher164** [comment]
I am working on a CL for this. Will send it shortly.
