### ISSUE TITLE
Ambiguous defer's behavior

### ISSUE THREAD

**Issue by actopolus** [golang/go#38504]
### What version of Go are you using (`go version`)?
<pre>
$ go version go1.13.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/go/bin"
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5646"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5646/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build798787028=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Run simple code: (https://play.golang.org/p/z2YsplDZOfp)
<pre>
package main

import (
    "fmt"
)

func a() error {
  err := fmt.Errorf("Errorrrrrrooo")

  defer func() {
     err = nil
  }()

  return err
}

func b() (err error) {
  err = fmt.Errorf("Errorrrrrrooo")

  defer func() {
     err = nil
  }()

  return err
}

func main() {
  fmt.Println(a())
  fmt.Println(b())
}
</pre>

### What did you expect to see?
<pre>
Errorrrrrrooo
Errorrrrrrooo
</pre>

or

<pre>
nil
nil
</pre>

### What did you see instead?
<pre>
Errorrrrrrooo
nil
</pre>

**Comment by urandom** [comment]
There appears to be nothing ambiguous with the posted code.

**Comment by randall77** [comment]
This is expected behavior.

In `a`:

1. Assign non-nil `error` to a local variable
2. Evaluate that local variable (to a non-nil `error`), set return value to it
3. Run defer, set local variable to nil

That returns the non-nil `error`.

In `b`:

1. Assign non-nil `error` to return variable
2. Evaluate return variable (to a non-nil `error`), set return value to it
3. Run defer, set return variable to nil (overwriting what was written in step 2)

That returns a `nil` error.

We generally discourage `return x` when there are named return variables. Set them using `=` and use a bare `return`.

**Comment by actopolus** [comment]
Thank you for answers.
I'm sorry. I found it in old good post https://blog.golang.org/defer-panic-and-recover
