### ISSUE TITLE
x/pkgsite: subdirectories are missing for nested modules

### ISSUE THREAD

**Issue by tschaub** [golang/go#38596]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/cloud.google.com/go?tab=subdirectories
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/41094/80014826-17ef4280-848e-11ea-9152-a95fdff56c2b.png)
  
### What did you expect to see?

I was looking for a link to the [storage](https://pkg.go.dev/cloud.google.com/go/storage) package.  This is listed on the [godoc.org](https://godoc.org/cloud.google.com/go#pkg-subdirectories) as a subdirectory.
 
![image](https://user-images.githubusercontent.com/41094/80015182-96e47b00-848e-11ea-8610-9c5d80344e53.png)
 
I don't see a link to the same under the subdirectories tab from [pkg.go.dev](https://pkg.go.dev/cloud.google.com/go?tab=subdirectories).
 
### What did you see instead?

The list of subdirectories does not include [storage](https://pkg.go.dev/cloud.google.com/go/storage).

**Comment by julieqiu** [comment]
Thanks for the feedback! The reason storage is not listed there is because cloud.google.com/go/storage is a nested module:
https://github.com/googleapis/google-cloud-go/blob/v0.56.0/storage/go.mod

This means that it is not a subdirectory of cloud.google.com/go. When you download cloud.google.com/go via proxy.golang.org (https://proxy.golang.org/cloud.google.com/go/@v/v0.56.0.zip), you will notice that it is not there.

We understand that this is confusing from a UI perspective and plan to address it in the upcoming round of design changes. 

/cc @fflewddur @Joanne881107

**Comment by tschaub** [comment]
Thanks for the explanation, @julieqiu.  I see that the old documentation is actually misleading in this case.

I wonder if it would help if the UI were explicit about packages and nested modules instead of using "subdirectories" to describe these things.  I don’t know if "nested" is a formal class of modules, but it would help clarify what you get when installing a module (packages) vs. what you need to install separately (modules that may share part of the same path).

**Comment by AceroM** [comment]
Hey there! We’re planning to add nested modules to the bottom of the subdirectories page. For example, https://pkg.go.dev/cloud.google.com/go?tab=subdirectories will show:
![image](https://user-images.githubusercontent.com/21187304/92760499-b35e5280-f35e-11ea-9b94-58e98e74e66d.png)

**Comment by AceroM** [comment]
The issue is now closed because the feature is slowly being rolled out now! 👍

**Comment by tschaub** [comment]
Thanks for the improvements!
