### ISSUE TITLE
cmd/go: go get dropping Windows proxy settings (WSL)

### ISSUE THREAD

**Issue by mcandre** [golang/go#38610]
### What version of Go are you using (`go version`)?

14

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows Subsystem for Linux (Ubuntu)

Windows 10 64-bit

### What did you do?

Ran `go get` for tyk dependencies.

### What did you expect to see?

The dependencies install.

### What did you see instead?

Network errors indicating Go in WSL was dropping the Windows host network settings.

Not sure if this is a Go thing or just a WSL thing.

**Comment by mattn** [comment]
You can use `$http_proxy` or `$https_proxy` on Linux.

**Comment by andybons** [comment]
@jayconrod @bcmills @matloob

**Comment by bcmills** [comment]
> Not sure if this is a Go thing or just a WSL thing.

I think we need a firmer answer on what the WSL proxy behavior is expected to be before we can pursue this as a Go bug. (To my knowledge, nobody on the Go team is an expert on WSL usage.)

However, note that the Go [porting policy](http://golang.org/wiki/PortingPolicy) requires a maintainer and builder for each supported platform. We have builders for (and do support) many Linux systems in general, but since we do not have builders or specific maintainers for WSL (#17365), to the extent that WSL differs from other Linux environments we cannot in general support it. (This is similar to the current situation for QEMU; compare #1508.)

If you require Go-on-WSL support, you should either escalate those issues to the WSL developers (presumably at Microsoft?), or volunteer (or find some one to volunteer) to set up and maintain a WSL builder environment.
