### ISSUE TITLE
x/mobile: X11 events freeze when not constantly redrawing

### ISSUE THREAD

**Issue by bergwerf** [golang/go#38632]
`go version go1.13.5 linux/amd64`

This issue only happens on X11 and not Android. I want to `a.Send(paint.Event{})` only when an update is needed, but if I do this other events do not come through. After some debugging I found that this is because `Publish()` unblocks the select statement and runs `C.processEvents()`. So if no publish is happening, then X11 events are not checked. See: https://github.com/golang/mobile/blob/master/app/x11.go#L63

I think `C.processEvents()` should happen in a separate goroutine (unless a more lightweight solution is possible).

**Comment by bergwerf** [comment]
Indeed adding this fixes the issue.
```
go func() {
	for {
		C.processEvents()
	}
}()
```

Perhaps one of the authors can look at this and decide if this can be added.

**Comment by andybons** [comment]
@hyangah

**Comment by changkun** [comment]
Separating the event processing loop into a different goroutine is potentially problematic and may cause frame buffer race when handling window resizing and sometimes even cause the app crash. Close because I don't think we could do much here yet. The current design works as intended. If there are any further discussions on this, feel free to comment.
