### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by BigGitWorld** [golang/go#38673]
Hello. 
I'm not familiar with the Go language. I was using a service (written in Go lang) in one the my projects that disconnected its process with the below error:
```
panic: runtime error: makeslice: len out of range
```
I was sending 500 messages per second via socket to this service.
does Anybody know what is the problem?

Go version : go version go1.11 linux/amd64

**Comment by ALTree** [comment]
Hi @BigGitWorld,

that error is triggered by the `makeslice` function in the runtime, when the `len` argument of `make( )` called on a slice is either negative of unreasonably big; e.g:

```
n := -1
sl := make([]int, n)   // ERROR: make argument is negative
```

```
n := 1<<60
sl := make([]int, n)   // ERROR: make argument is too big
```

This means that the Go application you are using has a programming error and it doesn't check that a number that is passed to `make` somewhere is negative or too big.

Since this is not a Go bug, but an issue in the user code that needs to be fixed in the application, I'm closing this issue. If you believe that this actually may be a bug in the Go compiler on in the runtime, please provide an autocontained code snippet that 1) is correct 2) triggers the error; and we'll re-open this issue.

**Comment by robinsoon** [comment]
make slice：I had a similar problem ,  make slice( 500 MB )  out of memory!
What is the upper limit of slice, whether there is clear explanation or variable limit

[my case make slice](https://github.com/robinsoon/makeslice)

**Comment by davecheney** [comment]
@robinsoon the upper limit of a slice is some significant fraction of the address space of a process. For 32 bit processes, between 1-2 gb, perhaps a little less on 32 bit windows because of DLL address space fragmentation. For 64 bit processes, in excess of a terrabyte, 10^40 bits. 

Thank you for posting your sample code. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
