### ISSUE TITLE
go.dev: Missing documentation and misleading link on godoc.org

### ISSUE THREAD

**Issue by cugu** [golang/go#38671]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/golang.org/x/vgo/vendor/cmd/go/internal/modfile
  
### What did you do?
 
Open https://godoc.org/golang.org/x/vgo/vendor/cmd/go/internal/modfile
which says I should check out https://pkg.go.dev/golang.org/x/vgo/vendor/cmd/go/internal/modfile
 
### What did you expect to see?
 
Documentation of golang.org/x/vgo/vendor/cmd/go/internal/modfile
 
### What did you see instead?

![image](https://user-images.githubusercontent.com/653777/80304753-636c5e00-87b8-11ea-8214-a52667644bf7.png)

**404 Not Found**

**Comment by hdost** [comment]
It looks like it's a combination of the project itself being moved, and the fact that the new https://github.com/golang/vgo repository is not configured for it to be there.

**Comment by hdost** [comment]
I tried the instructions on the 404 page, and I'm assuming that soon https://pkg.go.dev/github.com/golang/vgo should be available.

**Comment by andybons** [comment]
Thanks for the report. We’ll take a look.

**Comment by andybons** [comment]
https://pkg.go.dev/github.com/golang/vgo will not ever be there since the import path is golang.org/x/vgo, which is available at https://pkg.go.dev/golang.org/x/vgo.

As for the link in the header, we will likely update it simply to point to pkg.go.dev. It’s not ideal, but we don’t plan to support vendor directories.
