### ISSUE TITLE
x/pkgsite: const block comment not rendered in some cases

### ISSUE THREAD

**Issue by fishy** [golang/go#38699]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/reddit/baseplate.go@v0.0.0-20200427171913-839af98823fe/httpbp?tab=doc#pkg-constants, the first const block

### What did you expect to see?
 
The [code](https://github.com/reddit/baseplate.go/blob/839af98823fe610b5ef59b509d5ecd14686e3a7e/httpbp/errors.go#L11-L61) actually have comments on them, but they are not rendered in go.dev.

One thing to note is that they are not rendered on godoc.org either. I think it might has something to do with the long string const?

**Comment by dmitshur** [comment]
Thanks for reporting.

This is due to a limitation of the algorithm used to trim excessively large string literals and slices (see relevant code [here](https://github.com/golang/gddo/blob/a4ebd2f7e574802bb51643d0c43d8879073278ea/doc/code.go#L202-L226)). Documentation rendering on pkg.go.dev used the same algorithm as on godoc.org, so it was equally affected.

I've looked into it, and it is possible to resolve this issue. I'll send a fix.

**Comment by jba** [comment]
This is fixed for this package, but see #42425 for ongoing (minor) formatting issues.
