### ISSUE TITLE
x/build/cmd/gopherbot: label 'Help Wanted' issues with pending CLs

### ISSUE THREAD

**Issue by obeyda** [golang/go#38695]
It would be helpful if we could use label filters to filter for issues we can contribute to, most of the times 'help wanted' issues may have CLs attached, 
having a label like 'CL Pending' will help reduce the noise so we can see only issues where Help is really wanted.

**Comment by ALTree** [comment]
The problem is that sometimes a linked CL doesn't fix the issue at all (wrong solution, author unresponsive for a long time after review comments, etc...) but it's hard for the bot to understand that. This is often true for `Help Wanted` issues that attract inexperienced contributors.

If you click on an `help Wanted` issue you can check if any CL is linked and what's its status. Sometimes the CL is semi-abandoned or wrong and the issue is actually still up for grabs. On the other hand if you ignore every HelpWanted with a `Pending CL` label you'll probably miss them.

Also you can already search for `HelpWanted` issue with no comments from `gopherbot` and you'll get a reasonable approximation of what you want:

[is:issue is:open label:"help wanted" -commenter:gopherbot ](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+-commenter%3Agopherbot+)

**Comment by andybons** [comment]
@ALTree’s query seems like the best approach. Any objections, @obeyda?

**Comment by obeyda** [comment]
@andybons, that query is enough for me, thanks @ALTree your explanation makes sense.
