### ISSUE TITLE
runtime: "sweep increased allocation count" on linux-amd64-staticlockranking builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#38702]
[2020-04-27T15:53:46-9b9556f/linux-amd64-staticlockranking](https://build.golang.org/log/d022407f2af95b7ec09e04ccef0a777e6fd7e2ee)

CC @danscales @mknyszek @aclements 

Tentatively marking as release-blocker because this seems to indicate memory corruption in the runtime.

**Comment by mknyszek** [comment]
There was an uptick in March, but then it slowed down considerably. Either something is masking the bug now, or it got fixed (also all those failures are on 386, interestingly enough). The last one before that block was plan9-arm in November.

**Comment by aclements** [comment]
I'm going to put together a CL to at least improve the debugging output from this.

**Comment by toothrot** [comment]
Hello! This is one of [the few remaining issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+milestone%3AGo1.15+label%3Arelease-blocker+-label%3Aokay-after-beta1) blocking the Beta release of Go 1.15. We'll need to make a decision on this in the next week in order to keep our release [on schedule](https://golang.org/wiki/Go-Release-Cycle).

**Comment by mknyszek** [comment]
@toothrot I don't think we've seen this crash since the failure that caused Bryan to open this issue. @aclements' CL should give us a lot more information should we see this crash again, though. I think it's probably safe to not mark this as a beta-blocking issue, but we should keep an eye out for more such failures.

Also an interesting data point: it looks like all the failures that were happening through March were happening with the same size class (`s.nelems=512` in every case I've looked at, which is size class 2; unclear whether they're `noscan` just from the crashes, could be tiny allocator related?). The two most recent failures aren't for the same size class. I tried to trace this back to a particular CL, but nothing seems obviously wrong. These failures are also all very consistently on 386. I think whatever failures were going on in March are distinct from the last two which happened in April. Ah, digging through issues I found that those build failures are referenced by #37881 which is declared fixed.

I think the only two crashes relevant to this thread are:

```
2020-04-27T15:53:46-9b9556f/linux-amd64-staticlockranking
2020-04-08T18:35:49-f7e6ab4/solaris-amd64-oraclerel
```

**Comment by aclements** [comment]
Thanks for that sleuthing, @mknyszek ! I agree that given that this now seems rare, it shouldn't block the beta. There's also not much we can do until we get some more debugging information.

**Comment by aclements** [comment]
Updated query to catch failures with the new zombie detection: `greplogs -dashboard -E "error: sweep increased allocation count|runtime: marked free object" -l -md`. There haven't been any new failures since the one of 2020-04-27.

I think we should continue to keep this bug open for now. If we don't see any more failures once we're close to the release, we should just close it.

**Comment by aclements** [comment]
Still no failures since 2020-04-27.

**Comment by andybons** [comment]
Closing for now. If this pops up again we can reopen.
