### ISSUE TITLE
VS Code Warns When Multiple Go Module Based Projects Are Opened

### ISSUE THREAD

**Issue by comradequinn** [golang/go#38770]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build821638436=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I opened a directory in VS Code containing a number of separate, but related, Go projects; each with a go.mod file

### What did you expect to see?
No warning

### What did you see instead?
A warning advising me to re-open the editor with the go.mod file at the root - essentially not to open multiple go projects. The message advised that if I felt the warning was incorrect, I should raise the issue here

**Comment by hyangah** [comment]
Are you using `gopls` (iow the default go language server)? (I guess so based on the error messages :-)

Currently `gopls` does not support  a workspace with multiple modules. 
If you are using `gopls`, please take a look at this: 
https://github.com/golang/go/issues/32394#issuecomment-498385140
And follow up with the issue for progress.

Otherwise, please open an issue in github.com/microsoft/vscode-go and include your vscode go extension settings. Thanks!
