### ISSUE TITLE
Doc issue installing gomock?

### ISSUE THREAD

**Issue by keshlam** [golang/go#38798]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/keshlam1/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/keshlam1/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build680358799=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Downloaded latest Go, unzipped it using the sudo command on the README.MD, changed the profile and did a local EXPORT to add it to my current session's path.

At the next step in the README, installing mockgen, executing the command as given failed:
<pre>
$ GO111MODULE=on go get github.com/golang/mock/mockgen@latest
go: cannot find main module; see 'go help modules'
$ 
</pre>

Running it under sudo didn't change that response.

With help from a friend, we found something that ran without errors: leaving out the module setting and the @latest suffix.
<pre>
$ go get github.com/golang/mock/gomock
$ go get github.com/golang/mock/mockgen
$
</pre>

As a Go novice, I haven't tested it beyond that point, so I don't know whether this actually worked or merely failed to fail. Nor do I have any guesses about why my system didn't like the command you gave in README.MD. But you might want to investigate that, and/or update the documentation.

If you need more info, of course, ping me.

**Comment by ALTree** [comment]
Hi @keshlam,

you are hitting #24250. It was fixed in Go1.12, but you are using Go1.11, an ancient Go release. As you discovered, omitting the GO111MODULE=on part bypasses the issue.

We *could* keep this open to track the fact that the gomock README assumes you are using >= Go1.12, but the Go release policy says that Go1.11 is now no longer supported:

>  Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. 

(https://golang.org/doc/devel/release.html#policy) so I don't believe we should change the gomock README to workaround an issue that is only present in a Go version that is no longer supported.

I encourage you to upgrade to a recent Go release (Go1.14 is best); and I'm closing this issue since I don't believe there's anything else to do. Feel free to comment if you disagree, we'll re-open the issue if necessary.

**Comment by keshlam** [comment]
Makes sense..... except that I downloaded the file that the Go home site pointed to as 1.14, so I don't understand how I wound up with 1.11 in the first place.

**Comment by keshlam** [comment]
Ah. Found it. Old version on paths/alternates. _Sigh_. Thanks.
