### ISSUE TITLE
x/crypto/acme: Client.FetchCert hangs even with timeout context

### ISSUE THREAD

**Issue by gholt** [golang/go#38790]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Unknown as I'm unable to run go 1.14 right this moment. This shouldn't have anything to do with Go itself though, it's about the acme library.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="redacted/.cache/go-build"
GOENV="redacted/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="internal stuff redacted"
GONOSUMDB="internal stuff redacted"
GOOS="linux"
GOPATH="redacted/go"
GOPRIVATE="internal stuff redacted"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="redacted/play/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build704151629=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
package main

import (
        "context"
        "time"

        "golang.org/x/crypto/acme"
)

func main() {
        ctx, cancel := context.WithTimeout(context.Background(), time.Second)
        defer cancel()
        (&acme.Client{}).FetchCert(ctx, "garbage", true)
}
</pre>

### What did you expect to see?

Program to exit at some point, preferably with an error due to the garbage url given.

### What did you see instead?

Program never exits.

### Additional Information

It seems that the acme code is buggy around its use of the cacheMu mutex. https://github.com/golang/crypto/blob/master/acme/acme.go#L143 will grab the lock, but can call getRegRFC which can then call post, etc. until it tries to grab the lock again, and deadlocks.

**Comment by andybons** [comment]
@FiloSottile @katiehockman

**Comment by rolandshoemaker** [comment]
Looks like a combination of a deadlock and an infinite loop. FetchCert causes the following execution chain `FetchCert -> fetchCertRFC -> postAsGet -> post -> postNoRetry -> accountKID -> getRegRFC -> post -> postNoRetry -> accountKID` and then deadlocks waiting for cacheMu to become available. If you fix the locking you just get an infinite loop of `accountKID -> getRegRFC -> post -> postNoRetry -> accountKID`.

This happens because both `c.kid` and `c.Key` are not populated, which makes it impossible to lookup the KID (or do anything else really). Fix seems to be to just check for `c.Key == nil` in postNoRetry if `key == nil`.
