### ISSUE TITLE
Question: Why EpollEvent Pad?

### ISSUE THREAD

**Issue by neeilan** [golang/go#38857]
Hi,

I am wondering why the EpollEvent struct type (under sys/unix as well as syscall) has a 32 bit pad at the end:

```
type EpollEvent struct {
            Events uint32
            Fd     int32
            Pad    int32
 }
```

I can't tell any obvious alignment benefits - the equivalent `epoll_event` C struct is also 96 bits [1], but the fields don't map directly to the Go type anyway. I've looked at older CLs, and they only refer to changes to the Pad field and not the underlying reasoning. Some advice here would be much appreciated!

[1] http://man7.org/linux/man-pages/man2/epoll_wait.2.html

**Comment by ianlancetaylor** [comment]
Note that the Go project does not use the issue tracker for questions.  Please ask questions on a forum.  See https://golang.org/wiki/Questions.  Thanks.

That said, I do happen to know the answer to this one.  It's because the definition in C is

```C
typedef union epoll_data
{
  void *ptr;
  int fd;
  uint32_t u32;
  uint64_t u64;
} epoll_data_t;

struct epoll_event
{
  uint32_t events;	/* Epoll events */
  epoll_data_t data;	/* User data variable */
} __EPOLL_PACKED;
```

In Go we currently only expose the `fd` field, but the other fields are still there.  Without the padding field, `EpollEvent` would not be as large as the kernel expects, leading to disaster.

**Comment by neeilan** [comment]
Thanks Ian!
