### ISSUE TITLE
cmd/nm: decide on symbol index presentation

### ISSUE THREAD

**Issue by josharian** [golang/go#38875]
Sample reproduction:

Run `go tool nm ../pkg/darwin_amd64/net.a`. With tip, I see entries like:

```
../pkg/darwin_amd64/net.a(_go_.o):        1bedb2 T net.(*TCPConn).readFrom#423
```

Note the trailing `#423`. Those are not present with Go 1.14:

```
../pkg/darwin_amd64/net.a(_go_.o):         a5e67 T net.(*TCPConn).readFrom
```

cc @cherrymui @jeremyfaller @thanm

**Comment by cherrymui** [comment]
Yeah, this was done in CL https://go-review.googlesource.com/c/go/+/229246 . The reason is that in the new object files, symbols are referenced by indices instead of by names. So, if you objdump an object file which imports the fmt package and call `fmt.Printf`, instead of `CALL fmt.Printf`, you'll see `CALL fmt.#33`. The object file itself doesn't have any information about what name that symbol actually is. To make it more usable, I think there should be a way to tell what symbol `#33` is in the fmt package, and `nm fmt.a` seems a natural place to me. Therefore I added the index to the symbol name.

Does this format cause any problem for you? Should we add a flag to switch it on/off? I'd also be happy to hear if you have a better suggestion of the format. Thanks!

**Comment by cherrymui** [comment]
cc @aclements

**Comment by aclements** [comment]
I just added a RELNOTE marker on that CL. It may be worth mentioning this to golang-dev@, too, since I imagine Josh won't be the only person surprised by this!

**Comment by josharian** [comment]
> Does this format cause any problem for you? Should we add a flag to switch it on/off? I'd also be happy to hear if you have a better suggestion of the format. Thanks!

It confused some tools I have that parse the output of `go tool nm`. Easy enough to unmangle, now that I know I can safely ignore the numbers.

Although there would be some value in having a flag (default on or off? not sure.) Or maybe another column in the output for easier parsing (perhaps enabled by a flag)? Those would move the knowledge about how to unmangle from N tools--each possibly using different algorithms and thus getting it wrong in the future in different ways--to one tool.

An alternative, which I would like even better, since I would no longer have to exec `nm`, would be to expose `cmd/internal/objfile`, maybe without a Go 1 compatibility guarantee, or living in the Go 1 compat gray zone that other rarely used packages like debug/* occupy. Then we could just add a field for the index instead of having to squish it into the name,

**Comment by cherrymui** [comment]
> Or maybe another column in the output for easier parsing

I originally had a space between the index and the name. Austin pointed out that adding a space may makes tools harder to parse.

**Comment by aclements** [comment]
To close the loop on this, nm and objdump now print full symbol names even for cross-package references, so we don't need to print the index any more. Cherry did this by adding a table of referenced symbol names to object files so they're self-contained (but only tools use these tables). We may add an option in the future to show these indexes again, since they can be useful for debugging linker issues. (And I'd love a similar option to show ABI information.)
