### ISSUE TITLE
go build command fails with "$GOPATH/go.mod exists but should not"

### ISSUE THREAD

**Issue by PradeepJigalur** [golang/go#38896]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

$GOPATH/go.mod exists but should not
### What did you expect to see?

nothing is working go build or go env all fail with this
$GOPATH/go.mod exists but should not

### What did you see instead?
$GOPATH/go.mod exists but should not

**Comment by PradeepJigalur** [comment]
I had set the wrong GOPATH 

we should set GOPATH in such a way that when we go inside the GOPATH we should able to see src directory

**Comment by ksravana** [comment]
I set it such that there is a src directory under GOPATH directory but I still get the exact same error

**Comment by excrispy** [comment]
I had this problem and it ends up that the GOPATH was pointing to a directory that had `go.mod` file. I thought just by removing it, it would solve the problem. But it ends up that if a directory has a go.mod file, it may not be the right GOPATH because a GOPATH directory structure follows a strict format and must contain the following three specific directories as defined in the Go docs: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable (bold added for emphasis)

`Each directory listed in GOPATH must have a prescribed structure:

The **src** directory holds source code. The path below src determines the import path or executable name.

The **pkg** directory holds installed package objects. As in the Go tree, each target operating system and architecture pair has its own subdirectory of pkg (pkg/GOOS_GOARCH).

If DIR is a directory listed in the GOPATH, a package with source in DIR/src/foo/bar can be imported as "foo/bar" and has its compiled form installed to "DIR/pkg/GOOS_GOARCH/foo/bar.a".

The **bin** directory holds compiled commands. Each command is named for its source directory, but only the final element, not the entire path. That is, the command with source in DIR/src/foo/quux is installed into DIR/bin/quux, not DIR/bin/foo/quux. The "foo/" prefix is stripped so that you can add DIR/bin to your PATH to get at the installed commands. If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin. GOBIN must be an absolute path.`

In my case, somehow a directory that was a Go project was created that was the same path as the default GOPATH path. Deleting that directory and reinstalling Go fixed it for me. I probably could have manually changed the GOPATH path in my .bash_profile / .zshrc to the location where the actual desired Go dir was located, and I imagine that could have worked too. But in general, except for special cases, I don't think we should be setting GOPATH and just let Go automagically figure all that out for us. (Read this article if you're interested in why: https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really)

There might be other reasons why this error is happening but this solved it for me. Hope that helps!

**Comment by sanyaele** [comment]
changing my go directory from **`~/go`** to something else did it for me

**Comment by lehuuthoct** [comment]
it worked when i renamed my repo to something not includes go in its name!

**Comment by hussain-khalid** [comment]
I removed go. mod file from GOPATH/src folder and it started working.

**Comment by BasiliskOps** [comment]
Haha, I totally went the newbie route:

mkdir Go/
cd Go/

Not realizing how SPECIFIC the pathing was to build a Go package

**Comment by ManChrys** [comment]
i just added to the bashrc file the following lines and fix for me.

export GO111MODULE=on
export GOPATH=$HOME/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

**Comment by Sonali-Rajput** [comment]
> i just added to the bashrc file the following lines and fix for me.
> 
> export GO111MODULE=on export GOPATH=$HOME/work export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

same for me :)

**Comment by shariqahmkhan** [comment]
To fix it, go to GOPATH ( to find GOPATH type go env GOPATH ), delete go.mod file. It worked for me.

**Comment by hazraa** [comment]
For me;

go env
$GOPATH/go.mod exists but should not

There was a  GOPATH in ~/.config/go/env
