### ISSUE TITLE
go.dev: delete daifuyang/cmf package

### ISSUE THREAD

**Issue by daifuyang** [golang/go#38897]
### What is the URL of the page with the issue?
 delete pkg https://github.com/daifuyang/cmf
reset version! i am very sorry

**Comment by ALTree** [comment]
We can't reset a version, we can only delete the whole package. Can you confirm this is what you want? 

cc @julieqiu

**Comment by daifuyang** [comment]
yes ,just do it!thanks

**Comment by daifuyang** [comment]
Can I add it again after deleting the package?

**Comment by daifuyang** [comment]
If you can, delete it

**Comment by ALTree** [comment]
I *think* that if it gets deleted, you won't be able to create a new one with the same path (but @julieqiu can confirm this).

If this is not okay for you, I suggest you keep it and fix the issue by releasing a new version so that *that* one is shown on the website.

**Comment by daifuyang** [comment]
@julieqiu 
Sorry to bother you! The wrong version was included by mistake! I want to delete the wrong code package. Can I recreate the same path code package after deleting this project?

**Comment by julieqiu** [comment]
@ALTree is correct - we can only remove an entire module from the site, not a specific version. 

The reason is because we monitor the [Go Module Index](https://index.golang.org) for versions to download, and even if we delete the version from our site, it will still be cached by the [Go Module Mirror](https://proxy.golang.org).

See this FAQ question on https://proxy.golang.org:

> I removed a bad release from my repository but it still appears in the mirror, what should I do?
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

As @ALTree mentioned, our suggestion is that you just create another commit and tag it at a higher version number. That way, https://pkg.go.dev/github.com/daifuyang/cmf will default to the higher version.

Closing this issue since there doesn't seem to be any action items left on our end. Feel free to reopen if you would like us to remove github.com/daifuyang/cmf entirely from pkg.go.dev.
