### ISSUE TITLE
Go 1.13.9 Error  /var/folders/w6/kzlc3_4n7f19wyl7r11mwk1r0000gq/T/go-build911347615/b001/exe/main warning

### ISSUE THREAD

**Issue by Anjali-Saha** [golang/go#38967]
### What version of Go are you using (`go version`)? 1.13.9

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)? Mac Cataline(10.15.4)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/asaha/Library/Caches/go-build"
GOENV="/Users/asaha/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/asaha/Development/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w6/kzlc3_4n7f19wyl7r11mwk1r0000gq/T/go-build528700209=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Updated from go1.10 go 1.12.17 initally and was receiving cmd linker warnings when running my application.  Issue was closed and the solution was to update to go 1.13.9 

So now I have updated to go 1.13.9 and when running my go program. I see the following: 

dyld: Library not loaded: iclis09b.dylib
  Referenced from: /var/folders/w6/kzlc3_4n7f19wyl7r11mwk1r0000gq/T/go-build911347615/b001/exe/main
  Reason: image not found
signal: abort trap

**Comment by agnivade** [comment]
Hello @Anjali-Saha , unlike other projects, we do not use the issue tracker for questions such as these. It is only used for bugs and feature proposals. I will close this issue, but please feel free to ask it in any of these forums below:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Personally, I don't know the answer to your question. Mainly because there is very little information about what is your application and what are the steps you have performed. So it would be very hard for anyone to debug this by just looking at the error message. Please feel free to redirect the question to any of the forums above.

Thanks
