### ISSUE TITLE
Add GOARM constant to runtime package

### ISSUE THREAD

**Issue by AhmedSayed77** [golang/go#38987]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?
Building a program that will execute logic that is dependent on the OS and architecture of the device it's running on. the `runtime` library provides GOOS and GOARCH constants, but not GOARM.

```golang
package main

import "runtime"

func main() {
	println("OS", runtime.GOOS)
	println("ARCH", runtime.GOARCH)
	println("ARM", runtime.GOARM)
}
```

### What did you expect to see?

The OS, ARCH and ARM printed

### What did you see instead?

`GOARM not declared by package runtim` error

**Comment by martisch** [comment]
What does GOARM provide that is needed and whats the specific use case?
For CPU feature detection there is x/sys/cpu:
https://github.com/golang/sys/tree/master/cpu

**Comment by AhmedSayed77** [comment]
The application I'm building will download some other executables on the host machine. So I need to detect the the os and the architecture to build the url that I will use to download them

**Comment by martisch** [comment]
It seems detecting what the host supports (e.g. arm v7) instead of what the downloading application was build with (arm v5) would have some advantages.

Looking at:
https://github.com/golang/go/blob/97d0505334c71a8d7a1e7431c1e1515c93b59e2b/src/runtime/os_freebsd_arm.go#L15

goarm 6 requires: cpu.ARM.HasVFP 
goarm 7 requires: cpu.ARM.HasVFPv3

goarm 5 and 6 can not run on multicpu. (there might be cpu flags for atomics we can check instead)

Another option when building the downloading binaries directly would be to encode the build version into a string (including goarm set in environment): 
https://polyverse.com/blog/how-to-embed-versioning-information-in-go-applications-f76e2579b572/

**Comment by AhmedSayed77** [comment]
That was very helpful. Thank you very much
