### ISSUE TITLE
What is the relationship between the Go project and other projects?

### ISSUE THREAD

**Issue by ChinX** [golang/go#38991]
In the golang organization (https://github.com/golang), what is the relationship between the Go project and other projects? Will other projects are affected by the release period of Go?

**Comment by ALTree** [comment]
> In the golang organization (https://github.com/golang), what is the relationship between the Go project and other projects? 

All these project are developed under the same organization, and thus controlled by ~the same people (but not everyone works/cares about everything). 

`golang/go` is the main repository, all the others are either:
- useful libraries that are not in the Go standard library, and thus not automatically bundled with the Go toolchain (e.g.: crypto)
- several command line tools that are useful when working with Go, but are developed separately from the main Go toolchain (e.g.: everything in tools/cmd)
- tools that supports the project infrastructure (website code, continuous building)
- random various old experiments, sometimes not still maintaned (this is usually noted in the README)

> Will other projects are affected by the release period of Go?

No. https://github.com/golang/go/wiki/Go-Release-Cycle only applies to the golang/go repository.

Closing here, since we don't really do questions on the issue tracker, it's just for Go bugs.
