### ISSUE TITLE
x/pkgsite: support definition jumping for repositories from gitea.com or other gitea instances

### ISSUE THREAD

**Issue by lunny** [golang/go#39019]
I noticed that repositories from https://gitea.com (i.e. https://pkg.go.dev/xorm.io/xorm ) have no definition jumping but repositories from github have. I would like to send a PR to fix this but cannot find the sources of pkg.go.dev . Any chance to do that?

**Comment by julieqiu** [comment]
Thanks for the feedback! We are working on open sourcing the codebase (#36747) and would love to receive a contribution from you once that is done.

**Comment by lunny** [comment]
@julieqiu Will try that after it becomes open source.

**Comment by jba** [comment]
Part of the problem is with gitea itself. See the end of https://github.com/golang/go/issues/39559#issue-637799595, specifically "there is no template that will work with the abbreviated hash at the end of a pseudo-version." If you are a gitea maintainer or know one, we could use some help with that.

**Comment by lunny** [comment]
@jba I'm the founder of Gitea, Thanks for your reply. I will follow your link.

**Comment by jba** [comment]
@lunny Is there a bug we can point to for adding short hashes to gitea?

**Comment by lunny** [comment]
@jba There is a PR to do that https://github.com/go-gitea/gitea/pull/6452 but not merged yet.

**Comment by lunny** [comment]
Looks like this has been resolved.
