### ISSUE TITLE
cmd/go: tell go install to install deps from a certain github.com org first

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#39058]
We sometimes have to wait for a long time for 3rd party libs to install before our org's dependencies are installed. Since our deps change all the time, but the 3rd party libs are more static, we want a fail fast methodology to be in place - and install our deps first.

One idea is to have two separate go.mod files or contents. Copy our org's deps to one, go install, and then install 3rd party libs as a second step. Might that work?

**Comment by ianlancetaylor** [comment]
CC @bcmills @jayconrod

**Comment by bcmills** [comment]
Since the `go` command now requires a build cache, running `go install` on library dependencies should be unnecessary anyway.

Moreover, since the `go` command now requires a build cache, the static third-party libraries should take essentially no time to install when they are unchanged. Can you give some more detail about why that caching is not effective for your use-case?

**Comment by ORESoftware** [comment]
cache is not good bc we are in dockerfile / docker build

**Comment by bcmills** [comment]
Docker is capable of saving caches. (You can relocate the Go build cache to a specific location for later reuse by setting the `GOCACHE` environment variable.)

See the discussion on #27719.

**Comment by ORESoftware** [comment]
yes but of course I am taking about the first call to `go mod download` or `go install` not the subsequent calls. roger?
