### ISSUE TITLE
x/mobile, x/exp: build failing due to link errors on linux-386-longtest builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#39156]
[2020-03-29T12:56:38-4c31acb/linux-386-longtest](https://build.golang.org/log/cec00fabb49f3ba601b2118c759e5e2e8e484d8b)

```
# golang.org/x/mobile/gl
/usr/bin/ld: cannot find -lGLESv2
collect2: error: ld returned 1 exit status
# golang.org/x/mobile/exp/audio/al
/usr/bin/ld: cannot find -lopenal
/usr/bin/ld: cannot find -lopenal
collect2: error: ld returned 1 exit status
FAIL	golang.org/x/mobile/app [build failed]
```

This is likely a side-effect of [CL 234520](https://golang.org/cl/234520) (CC @dmitshur @toothrot @cagedmantis).

**Comment by dmitshur** [comment]
This is affecting x/exp too (because it uses x/mobile/gl).

All other 32-bit linux builders (linux-386, linux-386-387, linux-386-clang, linux-386-sid) are disabled on both x/mobile and x/exp repos. Both are experimental, so not supporting 32-bit seems reasonable. Perhaps we should do the same for linux-386-longtest?

@gopherbot, please add NeedsDecision label.

/cc @hyangah @hajimehoshi

**Comment by dmitshur** [comment]
I think a reasonable next step here is to disable the linux-386-longtest builder on the x/mobile and x/exp repositories.

If it's determined that those repositories should support linux/386, then we should fix the known failures, and then re-enable both linux-386 and linux-386-longtest builders.

@gopherbot, please move to NeedsFix.

**Comment by hajimehoshi** [comment]
The error seems like a test environment issue rather than Go compiler's issue.
