### ISSUE TITLE
Safer slice pops

### ISSUE THREAD

**Issue by mcandre** [golang/go#39230]
Please offer standard functions for deleting elements from a slice, instead of people using poor quality snippets from Stack Overflow.

**Comment by ianlancetaylor** [comment]
In order to add these functions in the standard library, we need generics.  I don't think it's worth adding predeclared functions for these.  Closing this issue in favor of generics; it can be reopened if generics is not added to the language.

In the meantime see https://golang.org/wiki/SliceTricks for possibly higher quality snippets.

**Comment by mcandre** [comment]
Fascinating. So `append` doesn't need generics, but somehow undoing `append`s requires generics?

**Comment by ianlancetaylor** [comment]
The predeclared `append` function was added to the language in 2010, when there was no prospect of adding generics to the language.  Now in 2020 we are much closer to adding generics.  For example, see https://blog.golang.org/why-generics.  It may also be interesting to read https://www.airs.com/blog/archives/559.
