### ISSUE TITLE
x/pkgsite: documentation misparsed as an anchor

### ISSUE THREAD

**Issue by dottedmag** [golang/go#39270]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/ridge/must@v0.2.0?tab=doc#Do
 
### What is your user agent?

Vivaldi 81.0.4044.142 
 
### Screenshot
 
<img width="1025" alt="Screenshot 2020-05-27 at 13 47 39" src="https://user-images.githubusercontent.com/16120/83015470-c9027300-a020-11ea-9513-2f77d0465c64.png">

### What did you do?

Nothing
 
### What did you expect to see?

"Do calls the function and panics on error"  is not an anchor.
 
### What did you see instead?

"Do calls the function and panics on error" is an anchor.

godoc.org handles it properly: https://godoc.org/github.com/ridge/must#Do

**Comment by julieqiu** [comment]
Thanks for reporting the bug! We'll work on a fix.

**Comment by kisunji** [comment]
According to this [comment](https://github.com/golang/pkgsite/blob/master/internal/fetch/dochtml/internal/render/render.go#L112), this is expected behaviour (albeit one which maybe didn't exist in godoc)

This line does not end in a punctuation:
https://github.com/ridge/must/blob/v0.2.0/must.go#L42

Is this something to be fixed?

**Comment by dottedmag** [comment]
No, it's fine.
