### ISSUE TITLE
doc/go1.15: Vet notes typo

### ISSUE THREAD

**Issue by MaerF0x0** [golang/go#39566]
link: https://tip.golang.org/doc/go1.15#vet

### What did you expect to see?
Allow string conversion from byte _slice_

> to only permit string(x) for integer x when the type of x is rune or byte slice. 

### What did you see instead?

> We are considering prohibiting the conversion in a future release of Go. That is, the language would change to only permit string(x) for integer x when the type of x is rune or byte. Such a language change would not be backward compatible. We are using this vet check as a first trial step toward changing the language.

I didnt know where to submit a CL

**Comment by dmitshur** [comment]
Thanks for reporting.

My understanding is that the current text is correct and intentional. It refers to conversions like `string(x)` where `x` is not a slice type, but rather a rune or byte. Conversions of []byte to string are not the topic being discussed; that's out of scope of #3939.

I'll let @ianlancetaylor who authored [CL 234517](https://golang.org/cl/234517) confirm. If it turns out more people find the current wording confusing, perhaps we can try to improve it.

**Comment by ianlancetaylor** [comment]
Yes, the existing text is correct.  Thanks for asking about it.

**Comment by MaerF0x0** [comment]
I see, yes. Prompted by your notes as I read it closer I came to understand the text block is only talking about `for integer x`. The text had me concerned I'd lose the ability to convert `[]byte` when I want to print as strings, something like: 

```
data, _ := json.Marshal(map[string]interface{}{"JSON": "Yes"})
// data is []byte
fmt.Println("json is", string(data))
```
