### ISSUE TITLE
sync/waitgroup: why `v == int32(delta)` is required when judging if the waitgroup is misused? 

### ISSUE THREAD

**Issue by cncal** [golang/go#39571]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Question?
Why `v == int32(delta)` is required [here](https://github.com/golang/go/blob/b05b254e9da137a599b309f4c5158a05e9e11d32/src/sync/waitgroup.go#L76)? Is `w != 0 && delta > 0` insufficient to judge if a waitgroup is misused for Add called concurrently with Wait?

**Comment by davecheney** [comment]
Because `delta` is declared in the function declaration as `int`. There are ~~no~~ few implicit conversion rules in Go, so `int` and `int32` are not the same type, even if the program is compiled on a 32 bit platform.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
