### ISSUE TITLE
cmd/go2go: error when a type parameter name and an interface name are same

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#39659]
### What version of Go are you using (`go version`)?

n/a

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

https://go2goplay.golang.org/p/6CjvnnMekvf

```go
package main

type Foo interface{}

func F(type Foo Foo)() {
}

func main() {
}

```

### What did you expect to see?

Compilation succeeds, or a better error message?

### What did you see instead?

```
type checking failed for main
prog.go2:5:17: Foo is not an interface
```

**Comment by ianlancetaylor** [comment]
This is expected behavior.  It's a consequence of the fact that within a type parameter list, all type parameters are visible throughout the list (https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#mutually-referencing-type-parameters).  In `(type Foo Foo)` the second `Foo` refers to the first `Foo`, so it is indeed not an interface type.

CC @griesemer in case he sees a way to get a better error message.
