### ISSUE TITLE
Another heap sort improvement?

### ISSUE THREAD

**Issue by Windsooon** [golang/go#39676]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?

The heap data structure implemented in `src/sort/sort.go`, `src/container/heap/heap.go` and `src/runtime/time.go`. There are two opened PRs trying to improve the heap sort already and they are doing the same thing.

[PR1](https://go-review.googlesource.com/c/go/+/56070/9/src/container/heap/heap.go)
[PR2](https://go-review.googlesource.com/c/go/+/237437/1/src/sort/sort.go)

### What did you expect to see?

At this moment, there is no PR for `src/runtime/time.go`, (for the `siftupTimer()` function). Should we create another similar PR as before or we can somehow just maintain one version of the heap then use it anywhere?

**Comment by martisch** [comment]
# unifying the code into one:
The runtime wont likely be made depedent on any other package unless its very low dependency and doesnt generate a lot of init work (or needs complex init work). e.g. `internal/cpu` or `internal/bytealg` are fine.

The other way around sort and container cant import a runtime function unless it is exported which runtime likely wont for a heap data structure.

This leaves making a new `internal/heap` package.

The runtime `siftupTimer` however doesnt use the sorting interface (Swap and Less) and shouldnt to avoid the overhead. There might be an optertunity to use a generic heap package wonts generics are available but even there its unclear whether this could introduce a performance regression depending on the generics implementation used.

For http://golang.org/cl/237437 I am not sure the added code is a good fit for the sort package as it will be triggered not very often.

**Comment by andybons** [comment]
Hi there,

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

Please ask the question on one of the above forums.

(Quoted from https://golang.org/wiki/Questions)

**Comment by Windsooon** [comment]
@andybons Thank you for pointing it out. I can submit a PR for the `src/runtime/time.go`. However, maintain several parts of the heap data structure seems not a good idea that is why I want to discuss it before submitting a PR. Maybe I should ask this at The Go Forum? 

PR request based on the comment  from [@Brad Fitzpatrick](https://go-review.googlesource.com/c/go/+/56070)

> Btw, have you looked to see whether the runtime's heap implementation is optimal?
> Because speed-ups there affect all programs (all timers, of which real programs have many).

**Comment by davecheney** [comment]
@Windsooon one of the [Go proverbs](https://go-proverbs.github.io/) is "a little copying is better than a little dependency". This advice applies strongly within the runtime and the standard library because it is easy to create import loops -- we even have tooling inside the bootstrap process to catch new inter package dependencies.

I would advise if you are looking to reduce the number of heap sort implementations in the runtime to consider; are these implementations identical? do they take the same inputs? do the have the same guarantees with regards to stability? do they have the same performance requirements? do they operate allocation free, or can they generate temporary allocations -- this is something which cannot happen inside the runtime.

Is the engineering effort spent to make your change, review it, and then the maintenance of having to use a shared code path in the future justified by the reduction in lines of code, or number of implementations.  

I don't wish to discourage you from contributing to the project, but I would suggest that this particular area may not be the best place to start.

**Comment by Windsooon** [comment]
@davecheney Thank you. I agreed with you. I would spend some time to understand the project before submit the PR.
