### ISSUE TITLE
cmd/go2go: go2goplay does not have feature parity with play.golang.org

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#39675]
### What did you do?
https://go2goplay.golang.org/p/Qho_zVlH3vu

### What did you expect to see?
```
0
```

### What did you see instead?
```
package name must be main
```

**Comment by andybons** [comment]
When initially implementing the go2go playground I remember running into some issues but I’m forgetting what they were.

/cc @ianlancetaylor @griesemer @toothrot

**Comment by ianlancetaylor** [comment]
I also forget, if I ever know.  I guess it is the playground code reporting that error?  What happens if you just remove that check?

I've never actually built the playground myself, maybe I'll try it later if I find time.

**Comment by thepudds** [comment]
Perhaps related, or perhaps not related, but go2goplay.golang.org also does not seem to recognize test cases. It instead reports:

```
# play
runtime.main_main·f: function main is undeclared in the main package
```

This does not work: 
https://go2goplay.golang.org/p/iw-9AIAjutO

But this does:
https://play.golang.org/p/rtBwSht8Urf

Those are from  #39634.

**Comment by smasher164** [comment]
@andybons Out of curiosity, where does the code for the go2go playground live? I'd like take a stab at adding multifile support.

**Comment by andybons** [comment]
I should have been more clear: it is known that go2goplay only handles single-file, non-test, main-package cases only for now. None of the additional functionality that the playground has accumulated over the years (multiple files, test cases, modules support, etc.) works. I remember looking into supporting these things but time-boxed myself into just getting the basic use-case up and running. I don’t remember the specific details of what issues I ran into when adjusting the playground code, nor do I know how long the go2go tool will be viable for.

@smasher164 https://golang.org/cl/238518 has the changes that are currently deployed. We may put that in its own branch since the `dev.go2go` branch now exists so there’s precedent.

**Comment by seankhliao** [comment]
No longer relevant
