### ISSUE TITLE
cmd/go2go: compile or not depending on whether or not a type is local or global declared

### ISSUE THREAD

**Issue by TapirLiu** [golang/go#39686]
Playground code:
```golang
package main

type Int interface {
    type int
}

func Foo(type T Int) ([]T) {} // compilation error: undefined: MyInt


func main() {
    type MyInt int // If the type is declared outside, then then program compiles okay
    Foo([]MyInt(nil))
}
```

**Comment by TapirLiu** [comment]
sorry, wrong code posted. Corrected now.

**Comment by griesemer** [comment]
This is a problem with the translator. It type-checks fine.

**Comment by ianlancetaylor** [comment]
This is a documented shortcoming of the translation tool.  As `go doc cmd/go2go` reports:

> Because this tool generates Go files, and because instantiated types and functions need to refer to the types with which they are instantiated, using function-local types as type arguments is not supported.

**Comment by TapirLiu** [comment]
Are local types instantiated at runtime?

**Comment by TapirLiu** [comment]
BTW, is this a temporary limit?

**Comment by ianlancetaylor** [comment]
This is a limitation of the translation tool.  It will not be fixed in the translation tool.  The translation tool is a temporary program designed to let people experiment with generics as described in the current design draft.

This is not a limitation of the language change described in the design draft.  If the design draft becomes a language change proposal, and if the language change proposal is adopted, then the implementation in the Go compiler will not have this limitation.
