### ISSUE TITLE
Updating system

### ISSUE THREAD

**Issue by sadesakaswl** [golang/go#39700]
"Go get" command is useless.You can use old versions in linux.We want "rustup update stable" like updating system("go update version/latest")."Go get" command must be for getting libraries etc.

**Comment by dmitshur** [comment]
Hi there,

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"
* [The Go Forum](https://forum.golangbridge.org/), a web-based forum
* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.
* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"
* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)
* **IRC** channel #go-nuts on Freenode

If you believe there is a bug, please answer the 5 questions in the issue template:

1. What version of Go are you using (`go version`)?
2. What operating system and processor architecture are you using (`go env)`?
3. What did you do?
4. What did you expect to see?
5. What did you see instead?

Without that information, it's hard to understand where the problem is.

See [CONTRIBUTING.md#filing-issues](https://github.com/golang/go/blob/master/CONTRIBUTING.md#filing-issues) and [golang.org/wiki/Questions](https://golang.org/wiki/Questions) for more information.

Thank you.

**Comment by sadesakaswl** [comment]
I installed golang my ubuntu via apt-get(installs 1.13.8) and i entered "go get golang.org/dl/go1.14.4" after bash can't found go1.14.4(I know because of PATH environment).So "go upgrade" command can be add(like flutter).(I can't add this request list sorry)

**Comment by dmitshur** [comment]
It shouldn't be necessary to change `PATH` after each install. The `go1.14.4` binary and others like it get installed in `$HOME/go/bin` by default, so if you add that one location to `PATH`, it should work for all future Go versions.

**Comment by sadesakaswl** [comment]
I reinstalled golang and bin folder changed now, whatever i can install via
tar.gz file but it can be easily like other.Also your method does not
delete previous versions automatically.

Dmitri Shuralyov <notifications@github.com>, 19 Haz 2020 Cum, 03:43
tarihinde şunu yazdı:

**Comment by dmitshur** [comment]
> I reinstalled golang and bin folder changed now

What was it before? What did it change to?

**Comment by sadesakaswl** [comment]
Before it was in /bin folder as linked(/usr/lib/go-1.13) and after /usr/bin as linked(/usr/lib/go-1.13)

**Comment by dmitshur** [comment]
Those paths don't look related to the `$HOME/go/bin` path I mentioned earlier. There may be an issue, but it's hard to know where it is.

Please take a look at the existing Go installation instructions at https://golang.org/doc/install, and the install troubleshooting wiki page at https://golang.org/wiki/InstallTroubleshooting.

If you're still having a problem, it'll be easier to get to the bottom of it by using one of the mediums listed at https://golang.org/wiki/Questions, as they're better suited for discussing these kind of questions. If you think there's something specific we should change, please open a new issue and fill in the template fully. I'll close this now.
