### ISSUE TITLE
cmd/go2go: the Graph example doesn't compile

### ISSUE THREAD

**Issue by TapirLiu** [golang/go#39734]
### What did you do?

code:  https://go2goplay.golang.org/p/6EKNV4FQ4KI

### What did you expect to see?

Compiles

### What did you see instead?

Doesn't compile

BTW, is `type (v *Vertex) Edges() []*FromTo { ... }` a typo of `func (v *Vertex) Edges() []*FromTo { ... }`

**Comment by arl** [comment]
I'm not saying it's normal, but FTR if you want to make the example compile you need provide explicit type parameters when instantiating `Graph`:

```go
g := New(*Vertex, *FromTo)([]*Vertex{}) // ok
```

Also, while I understand the error message for:
```go
g := New(Vertex, *FromTo)([]*Vertex{}) // error: *Vertex does not satisfy NodeConstraint(Edge) (missing method Edges)
```

I'm not sure I understand why it says the same thing in the following case, since the `Vertex` type parameter is now correct:
```go
g := New(*Vertex, FromTo)([]*Vertex{}) // error: Vertex does not satisfy NodeConstraint(Edge) (missing method Edges)
```

Or maybe is it because Vertex is also inferred from `FromTo` first?

**Comment by TapirLiu** [comment]
OK, but maybe it is possible to deduce the `Edge` type from the `New([]*Vertex{})` call, `*Vertex` has a `Edges() []*FromTo` method.

**Comment by cagedmantis** [comment]
This seems like a question which has been answered.
