### ISSUE TITLE
database/sql/sql.go: I wonder why 'defer' is not used to release mutex in the '(db *DB) putConn' function.

### ISSUE THREAD

**Issue by Miss-you** [golang/go#39814]
### What version of Go are you using (`go version`)?

<pre>
$ go version
master version
</pre>

### Does this issue reproduce with the latest release?

I don't know.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yousa/Library/Caches/go-build"
GOENV="/Users/yousa/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yousa/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yousa/Documents/git/ingress/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qf/l8cy5cs9595967p86th95mk40000gn/T/go-build730450384=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Learn the code for the database/sql connection pool part.

### What did you expect to see?

I wonder why 'defer' is not used to release mutex in the 'putConn' function.
![image](https://user-images.githubusercontent.com/3816205/85564638-04648180-b661-11ea-9d9c-db44ca0ba5d4.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/3816205/85564744-19411500-b661-11ea-8d30-6459036279a4.png)

**Comment by davecheney** [comment]
Because defer does not run until the end of the function.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode
