### ISSUE TITLE
wanted: prettier (or useful) debug info of compile, like "Rust"

### ISSUE THREAD

**Issue by yam8511** [golang/go#39826]
Like title above, I like go, so I hope `go build` can more friendly help for gopher to develop programming.

1. compile info of `Go`

![image](https://user-images.githubusercontent.com/13272737/85586743-bf961600-b673-11ea-8731-b264eb1e7de2.png)

2. compile info of `Rust`

![image](https://user-images.githubusercontent.com/13272737/85586696-b6a54480-b673-11ea-9496-0d80becb25d3.png)

Thank everyone who contribue to `go`.

**Comment by ianlancetaylor** [comment]
When posting plain text, please use plain text, perhaps with Markdown markers.  Please do not post images.  Images are harder to read and don't support cut-and-paste.  Thanks.

The additional comments that the Rust compiler emits don't make sense for Go.  There is no way to avoid the warning by doing anything like prefixing an underscore.  There is no way to disable the warning, so the `#[warn(unused_variables)]` note doesn't help.

More generally, the Go compiler adheres to the standard Unix philosophy of preferring to be quiet.  The place to report more information is not the compiler, but the IDE.  Go supports easy tooling for operations like detecting unused variables.

I'm going to close this issue because we aren't going to take any action here.  Please comment if you disagree.
