### ISSUE TITLE
regexp.QuoteMeta does not escape "-"

### ISSUE THREAD

**Issue by xopoww** [golang/go#39867]
<pre>
$ go version go1.14.4 windows/amd64
</pre>

Sample code recreating an issue [(playground)](https://play.golang.org/p/NXY8EBYO_ox):
```go
package main

import (
	"fmt"
	"regexp"
)
var (
	re1 = regexp.MustCompile("["+regexp.QuoteMeta("+-=|")+"]")
	re2 = regexp.MustCompile("["+regexp.QuoteMeta("-+=|")+"]")
)

func main() {
	fmt.Println(re1.ReplaceAllString("123456", "☺"))
	fmt.Println(re2.ReplaceAllString("123456", "☺"))
}
``` 
```
Output:
☺☺☺☺☺☺
123456
```
regexp.QuoteMeta function does not escape "-" character. I don't know if this is intentional design, but in some situations this may lead to an unexpeted behavior, e.g. instead of group of 4 symbols I got a group of "|" and a range betweeen "+ and "=".

**Comment by mvdan** [comment]
You should use QuoteMeta on the entire expression, and that will quote your `[` character.

**Comment by junyer** [comment]
`regexp.QuoteMeta("+-=|")` returns a pattern string that matches the input string `"+-=|"`. You can't put it inside a character class because the rules inside character classes are completely different. Instead, try splitting `"+-=|"` into single-character strings, running `regexp.QuoteMeta` on each string and joining the results with `|`. (Enclose the whole thing in `(?:` and `)` if necessary.) The Go `regexp` package should optimise that down to a character class.
