### ISSUE TITLE
cmd/go2go: type inference doesn't work when casting to generic type

### ISSUE THREAD

**Issue by arl** [golang/go#39866]
### What version of Go are you using (`go version`)?

`dev.go2go` branch
<pre>
go version devel +4dfbf5ab9c Thu Jun 25 02:57:14 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Tried with latest commit `dev.go2go` branch.

### What did you do?

```go
package main

type stack(type T) []T

func main() {
	slice := []int{}

	_ = stack(slice) // Error: slice (variable of type []int) is not a type
	// _ = stack(int)(slice) // Ok
}
```

https://go2goplay.golang.org/p/jACGE-qTJ5L

### What did you expect to see?

Type inference to work when casting to generic type though to be fair I couldn't find anything related to that specific point in the design draft.

### What did you see instead?

I had to provide the type parameter, then it worked.

**Comment by ianlancetaylor** [comment]
In the current design draft type inference only works for function calls, not for type conversions.  So this is working as expected.

In order to add this feature to the design draft I'd like to see some realistic code that would use it.  It strikes me as being likely to be more confusing than readable.
