### ISSUE TITLE
x/crypto/openpgp: E-mail address is not detected and misplaced into the name field

### ISSUE THREAD

**Issue by notcdk** [golang/go#39879]
### What version of Go are you using (`go version`)?
The Go Playground say's it's the latest stable so 1.14.3

### Does this issue reproduce with the latest release?
Yes, it does.

### What operating system and processor architecture are you using (`go env`)?
Irrelevant, reproduceable on the playground

### What did you do?
When generating a key with GnuPG if you skip the "Real name" by hitting enter it leaves just the email address without angled brackets.
[A very big screenshot](https://i.vgy.me/1LNwZe.png)

What the library sees:

- [With only email UID](https://play.golang.org/p/vAZ6mRpMZIo)
- [With second UID that has a name](https://play.golang.org/p/5tIfOCMhMeA)

As GitHub uses this library to parse e-mail addresses from the key it did not detect my e-mail address. You can verify this by adding a key like this one to your GitHub account. (Screenshot provided.) I opened a ticket and I was made aware that GitHub uses this library, so I headed here to open this issue.
![Screenshot from 2020-06-24 20-25-40](https://user-images.githubusercontent.com/28454922/85891114-e2006e80-b7ee-11ea-9f9f-b17cae1e7bc7.png)

As a consequence of that, the commits I sign don't appear with the "Verified" badge.

![Screenshot from 2020-06-24 20-29-45](https://user-images.githubusercontent.com/28454922/85891752-fbee8100-b7ef-11ea-859f-4082c7afc06d.png)

As most people use GnuPG to generate their keys some might be in this form. I think it is a good idea to try and detect this pattern and not necessarily require angle brackets.

### What did you expect to see?
```
id: yesplease <no@thanks>     name:yesplease       mail:no@thanks      
id: yes@please                name:                mail:yes@please
```   

### What did you see instead?
```
id: yesplease <no@thanks>     name:yesplease       mail:no@thanks      
id: yes@please                name:yes@please      mail:            
```   
(Now that I think of it, this might be a bad example as it misses the TLD e.g. please.com but it wouldn't recognize it as email either way)

**Comment by notcdk** [comment]
Whoops miss click sorry

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
