### ISSUE TITLE
Can't find package test

### ISSUE THREAD

**Issue by kstenerud** [golang/go#39937]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/karl/.cache/go-build"
GOENV="/home/karl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/karl/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/karl/tmp/x/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build520807521=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go.mod:

```
module x

go 1.14
```

main.go:

```golang
package main
```

main_test.go:

```golang
package main

import (
	"testing"
	"x/test"
)

func TestX(t *testing.T) {
	var x test.TEvent
	if x != 0 {
		t.Error("Not 0")
	}
}
```

test/common_test.go

```golang
package test

type TEvent int
```

test/hack.go:

```golang
package test

// Workaround for "no non-test Go files in x/test"
```

### What did you expect to see?

I expected the tests to compile

### What did you see instead?

```
# x [x.test]
./main_test.go:9:8: undefined: test.TEvent
FAIL	x [build failed]
```

**Comment by davecheney** [comment]
The underlying issue is when testing package `A` only the files in that package are compiled in testing mode--files ending in `_test.go` are included in the scope. In your case package `test` is imported, but `common_test.go` is not part of the import set because package `test` is not compiled in test mode.

nb. I say package `A` rather than package `main` because this is not specific to package main.

This is working as designed, although perhaps not how you intended. Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode
