### ISSUE TITLE
cmd/go2go: unclear error message for type parameter

### ISSUE THREAD

**Issue by crawshaw** [golang/go#40047]
```
package main

type X(type T) T

var m = make(map[string]X(int))

func main() {}
```

Fails to compile with:

```
type checking failed for main
prog.go2:5:25: cannot use generic type X(type T) without instantiation
```

Presumably there is an unresolvable ambiguity (though honestly I haven't figured out what it is yet). An extra pair of parentheses makes it work:

```
package main

type X(type T) T

var m = make(map[string](X(int)))

func main() {}
```

Assuming this is working as intended, a clearer error message would be nice.

**Comment by thepudds** [comment]
Possibly related to https://github.com/golang/go/issues/39670#issuecomment-645672039

**Comment by thepudds** [comment]
Taking Robert's type conversion [example](https://play.golang.org/p/V4IkaXevq8K) from that comment, here is a quick attempt to adapt his example to the example here:

https://play.golang.org/p/cxWiCJ1SskS

Note that is a regular playground link.

**Comment by griesemer** [comment]
@crawshaw The problem here is that `map[string]X(int)` must be parsed as `(map[string]X)(int)` for backward-compatibility; i.e., is looks like a conversion. To make it work, we need extra parentheses, as in: `map[string](X(int))`.

Now, in "type context", we know that it cannot be a conversion and we can do the right thing. For instance, `var _ map[string]X(int)` doesn't require those extra parentheses.

Arguably, in the `make` call above, the map type is in "type context". But we don't know this until type-checking time: we cannot know that `make` actually refers to the built-in `make` function and not some user-defined version that may possibly be defined in another file of the same package. Thus, the parser cannot know better. The type-checker may be able to re-associate the AST but it's tricky (I haven't thought that through in detail). For the same reason it's not easily possible to provide a better error message: The AST is a call/conversion node, where the LHS is `map[string]X` and the argument is `int` - when we look at `X` we're very far removed from the respective context.

This, and many other problems would go away if our keyboards had one more style of easily accessible parentheses...

**Comment by crawshaw** [comment]
Thanks for the detailed explanation. That is indeed a sticky situation.

It seems unlikely I have any novel thoughts about syntax given the effort you have put into this, but I would point out that the Go spec has some unused characters that could be used to prefix type parentheses: `X#(int)` or `X~(int)`, which could also remove the extra use of "type" in definitions: `type X~(T) T`, etc.

**Comment by griesemer** [comment]
A type parameter on the RHS of a type definition is not permitted anymore. Closing.
