### ISSUE TITLE
net: remove dependency on fmt, unicode via golang.org/x/net/dns/dnsmessage

### ISSUE THREAD

**Issue by rsc** [golang/go#40070]
net should not depend on fmt and unicode. 

golang.org/x/net/dns/dnsmessage contains one line using fmt:

	return nil, off, fmt.Errorf("invalid resource type: %d", hdr.Type)

But dnsmessage is vendored into the standard library and imported by net,
and this use is making net depend on fmt, and in turn on unicode.

This one line should be changed, to remove the use of fmt.

go/build.TestDependencies claims to check that net does not
depend on unicode, which should have detected this, but that
test does not look inside vendored packages.

I have a fix that I will send out for that problem as well.

**Comment by ianlancetaylor** [comment]
Is there anything else to do here?  As far as I can tell this issue can be closed.

**Comment by dmitshur** [comment]
I've confirmed the package `net` does not import `fmt` nor `unicode`, not even indirectly. It was resolved via [CL 241257](https://golang.org/cl/241257), and [CL 241078](https://golang.org/cl/241078) added a regression test (see [this line](https://github.com/golang/go/blob/e88ea87e7b886815cfdadc4cd3d70bf5ef833bd7/src/go/build/deps_test.go#L334)).

Closing as this issue is fixed. Please comment if I missed something.
