### ISSUE TITLE
ipv6 header was stripped from the ip packets in packetConn read apis

### ISSUE THREAD

**Issue by yusong0926** [golang/go#40143]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/songyu/Library/Caches/go-build"
GOENV="/Users/songyu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/songyu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/82/ywnjzhzn0bv_9w46jyyxp5kh0000gp/T/go-build674890034=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

tried all apis (ipConn, icmp packetConn), couldn't get ip header from the ip packets especially for ipv6 using read or readFrom api.

func main() {
    conn, err := icmp.ListenPacket("ip6:ipv6-icmp", "::")
    if err != nil {
        log.Fatal(err)
    }

    for {
        var msg []byte
        length, sourceIP, err := conn.ReadFrom(msg)
       //msg was only the payload of the packets, ipv6 header was stripped from it. I want to get hopLimit from the header
        if err != nil {
            log.Println(err)
            continue
        }

        log.Printf("message = '%s', length = %d, source-ip = %s", string(msg), length, sourceIP)
    }
    _ = conn.Close()
}

### What did you expect to see?
read ipv6 header and read hopLimit or ttl from ip header for icmp packets.

### What did you see instead?
ipv6 header was stripped. Read or readfrom only receive ip payload.

**Comment by davecheney** [comment]
Can you please provide some sample code. Thank you.

**Comment by yusong0926** [comment]
@davecheney  added

**Comment by acln0** [comment]
Go is only giving you what the operating system network stack is giving you. Here is the relevant code:

[Here](https://github.com/golang/net/blob/ab3426394381/icmp/listen_posix.go#L51-L62), package `icmp` selects the protocol for the `ip6` transport. [Here](https://github.com/golang/net/blob/ab3426394381/icmp/listen_posix.go#L89-L91), it calls [`net.ListenPacket`](https://github.com/golang/go/blob/master/src/net/dial.go#L731) in order to create the socket. Through `ListenConfig`, it ends up calling [`listenIP`](https://github.com/golang/go/blob/master/src/net/iprawsock_posix.go#L132) on a `*net.sysDialer`. `listenIP` calls [`internetSocket`](https://github.com/golang/go/blob/574dac9d9707ddd35d57aaea646710dfae67bd89/src/net/ipsock_posix.go#L136), which is a thin wrapper around [`socket`](https://github.com/golang/go/blob/574dac9d9707ddd35d57aaea646710dfae67bd89/src/net/sock_posix.go#L18). Moving back up the stack, the `netFD` created in `socket` is wrapped in an `*IPConn` and returned as the `net.PacketConn` implementation from `ListenPacket`.

When you call `ReadFrom` on an `*IPConn`, the [inner implementation](https://github.com/golang/go/blob/574dac9d9707ddd35d57aaea646710dfae67bd89/src/net/fd_posix.go#L60) is only a thin wrapper around [`(*poll.FD).ReadFrom`](https://github.com/golang/go/blob/574dac9d9707ddd35d57aaea646710dfae67bd89/src/internal/poll/fd_unix.go#L199), which, itself, is a thin wrapper around [`syscall.Recvfrom`](https://github.com/golang/go/blob/574dac9d9707ddd35d57aaea646710dfae67bd89/src/syscall/syscall_unix.go#L281).

Based on this, it is my understanding that none of the Go code in your call stack strips IPv6 headers away. A C program which calls `socket()`, `bind()`, followed by `recvfrom()`, would also not return the IPv6 headers, as far as I can tell. Perhaps there is another way to tell the operating system to return this data to you, but I am not aware of it. Perhaps something connected with using recvmsg() and requesting it in the ancillary data section? I skimmed through the man pages for a little bit, but I couldn't find anything.

**Comment by davecheney** [comment]
@yusong0926 could you describe a little more what you mean by IPv6 header? Do you mean the ethernet frame data?

**Comment by seankhliao** [comment]
@yusong0926 L2/L3 headers are only accessible through raw sockets, you'll need to make syscalls to get them, as explained in https://css.bz/2016/12/08/go-raw-sockets.html

**Comment by davecheney** [comment]
Closing, answered. Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode
