### ISSUE TITLE
text/scanner add date scan

### ISSUE THREAD

**Issue by publicocean0** [golang/go#40182]
1.14

It is very usefull if you can add also the possibility to scan the date format in this scanner

**Comment by ALTree** [comment]
`text/scanner` is an utf-8 tokenizer, it seems to me that parsing a date is an operation that is much more high level that that; you can already parse dates using [`time.Parse`](https://golang.org/pkg/time/#Parse). I'm not sure a date parser belongs in `text/scanner`. I'm closing this issue, since I think the problem of parsing a date can already be solved using the `time` package, but feel free to comment if you want to explain why having one in `text/scanner` would be better.
