### ISSUE TITLE
x/website: Orientation about trailing dots in comments on the Effective Go website

### ISSUE THREAD

**Issue by rogerlucena** [golang/go#40259]
### What did you do?
In your [Effective Go](http://www.golang.org/doc/effective_go.html) website you set a standard of indeed using trailing dots by the end of comments on the "Commentary" section, as shown below:

```
// Compile parses a regular expression and returns, if successful,
// a Regexp that can be used to match against text.
func Compile(str string) (*Regexp, error) {
```

But just above it, in the "Formatting" section, you write brief comments without dots by the end:

```
type T struct {
    name string // name of the object
    value int // its value
}
```

What is the **<ins>Go readability standard</ins>** then?

### What did you expect to see?
A standardized way of writing comments in Go with regards to trailing dots.

### What did you see instead?
Two different ways inside your [Effective Go](http://www.golang.org/doc/effective_go.html) website.

**Comment by andybons** [comment]
As stated in Effective Go, doc comments (the first type you mention) work best as complete sentences, which implies a period at the end.

We make no recommendation for end-of-line comments (the second example you provide). Since Effective Go is frozen at the point, we are unlikely to change this.

Our advice is to remain consistent with the code around you and/or follow your team’s style guides.
