### ISSUE TITLE
cmd/compile: better error message for type arguments used with unsatisfiable constraints (empty type sets)

### ISSUE THREAD

**Issue by komuw** [golang/go#40350]
# What did you do?
Ran this program: https://go2goplay.golang.org/p/S4MLyTi6yA-
```go
package main

import (
	"fmt"
)

type interger32 interface {
	type int32
}

type number interface {
	type float64, int, int32
	interger32
}

func Largest[type T number](s []T) T {
	var largest T
	for _, v := range s {
		if v > largest {
			largest = v
		}
	}
	return largest
}

func main() {
	arr := []int{101, -1, 45, 646, 3}
	l := Largest[int](arr)

	fmt.Printf("largest in %v is: %v", arr, l)
}
```

### What did you expect to see?
- Either it runs or produces a comprehensible error message about `int32` been repeated in interfaces `interger32` & `number`

### What did you see instead?
```
type checking failed for main
prog.go2:28:15: int does not satisfy number (int not found in int32)
```

**Comment by griesemer** [comment]
Just for the record, the problem is not that `int32` is repeated in both interfaces, the problem is that `int` is _not_ repeated in both interfaces: When interfaces are embedded, all the type lists are intersected. This way we can guarantee that if a type T satisfies an interface that embeds an interface E, T also satisfies E.

Agreed that we could use a better error message. Not urgent.

**Comment by komuw** [comment]
seems resolved at tip.

**Comment by griesemer** [comment]
I'm going to re-open this. The error message at tip could be better. For:
```Go
package p

type interger32 interface {
	~int32
}

type number interface {
	~float64 | ~int | ~int32
	interger32
}

func f[T number]() {}

func _() {
	_ = f[int]
}
```
we get:
```
x.go:15:8: int does not satisfy number
```
We should say a bit more as to why.
