### ISSUE TITLE
cmd/go2go: failure to compile dot import

### ISSUE THREAD

**Issue by mdempsky** [golang/go#40379]
I think this program should be okay: https://go2goplay.golang.org/p/WBPOXmHnT9S

But it currently fails to compile with output:

```
# play
./prog.go2:11: syntax error: unexpected ., expecting expression

Go build failed.
```

/cc @griesemer

**Comment by griesemer** [comment]
This type-checks fine. Looks like an issue with the translator.

**Comment by griesemer** [comment]
This is unrelated to the name of the type parameter, or generic code for that matter. [This code](https://go2goplay.golang.org/p/-s7xSfOiqde) has the same problem.

**Comment by ianlancetaylor** [comment]
This is a bug in the translation tool.  It's hard to fix, because go/types doesn't keep track of the package alias, so it's hard for the translation tool to see that the package alias is ".".  When rewriting generic the tool needs to qualify lots of identifiers with the package name, and all those qualifications fail with a package alias of ".".

The translation tool is just an experimental tool that isn't expected to handle all possible Go code.  I don't think this is an important case, and I don't plan to work on it.  If someone wants to send a fix, that would be fine.

Sorry.

**Comment by seankhliao** [comment]
No longer relevant
