### ISSUE TITLE
x/sys: windows.GetCurrentThreadId() returns same thread id.

### ISSUE THREAD

**Issue by burakkoken** [golang/go#40386]
go 1.13

When I create more than one  go routine and use the calling of windows.GetCurrentThreadId function in their function body, it returns same thread id. **Note:** go routine body contains time.Sleep() not to be stop its execution immeditately. I mean all go routines are still executed.

```go
go func() {
   threadId := windows.GetCurrentThreadId()
   log.Print(fmt.Sprintf("Go Routine 1 : %d", threadId ))
   time.Sleep(10E9)
}()
...
go func() {
   threadId := windows.GetCurrentThreadId()
   log.Print(fmt.Sprintf("Go Routine 10 : %d", threadId ))
   time.Sleep(10E9)
}()
```

**Comment by davecheney** [comment]
Go uses a user space scheduling model whereby a large number of goroutines are mapped onto a small (usually on the order of the number of cores your operating system exposes) number of operating system threads. When a goroutine executes `time.Sleep`, it is no longer runnable (obviously) and as part of going to sleep to yields back to the scheduler so that the thread can service other runnable goroutines.

It is possible (although I can't test it as I don't have access to a windows system) that over time calling `windows.GetCurrentThreadId()` will return essentially random values. To avoid this some users call `runtime.LockOSThread` to _reserve_ the current thread for only the runnable goroutine.

Thank you for raising this issue. Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

**Comment by burakkoken** [comment]
Thanks for your answer, It is totally obvious for me. But I would like to ask a question another. I know here is not place for discussion.  Let's say we have a running go routine in a thread. Does Go allow to be executed another go routine in the same thread before running thread does not end?
