### ISSUE TITLE
Permission denied while running go install

### ISSUE THREAD

**Issue by Jbiloki** [golang/go#40417]
When running `go install` on my `cmd` folder I get the error:

```go install cmd/
go install cmd/go: copying 
/var/folders/wh/9y99138n2w1bvcwxz3tbb8zw0000g
n/T/go-build195667123/b150/exe/a.out: open 
/usr/local/go/bin/go: permission denied
```

It looks like my env variables are set correctly:

```GOBIN=""
GOCACHE="/Users/<USER>/Library/Caches/go-build"
GOENV="/Users/<USER>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<USER>/src/unbias"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
```
Here's my directory of my current project: which is inside my go path:
`/Users/<USER>/src/unbias`

[![enter image description here][1]][1]

Since it looks like the permission error is not in my project but in my go install path, I am not sure if I should change ownership of such files.

```ls -lah /usr/local/go/bin   
total 37032
drwxr-xr-x   4 root  wheel   128B Jul 16 15:53 .
drwxr-xr-x  20 root  wheel   640B Jul 16 15:29 ..
-rwxr-xr-x   1 root  wheel    15M Jul 16 15:52 go
-rwxr-xr-x   1 root  wheel   3.4M Jul 16 15:53 gofmt
```

  [1]: https://i.stack.imgur.com/p7spO.png

Go version: go1.14.6 darwin/amd64

**Comment by ALTree** [comment]
> When running go install on my cmd folder [...]

You didn't write the *exact* command you're running, but if you're running `go install cmd` then be aware that it doesn't do what you want. `go install cmd` will try to (re)install the Go toolchain commands (`go`, `gofmt`); since these are usually in `/use/local/go`, if you try that without being `su` the `install` command will fail with permission errors.

What you want is `go install ./cmd` or similar.

**Comment by Jbiloki** [comment]
I see, yeah that does seem to be the issue I changed my structure and have a shell script runs `cd project_name` `go install .` that seems to do the trick. Is a shell script the correct way to orchestrate building/running a go binary or should I use a Makefile?

**Comment by ALTree** [comment]
>  Is a shell script the correct way to orchestrate building/running a go binary

In general, unless the project is really big and the build steps complicated, you just directly run the `go` commands in the command line (or this is at least what I like to do). If you have many steps, a makefile can be used, too.

Please note that the Go project does not use its bug tracker for general discussion or asking questions about the language. See the [Questions wiki page](https://github.com/golang/go/wiki/Questions) if you have further questions.

I'm now closing this issue, since we don't have a Go bug.

**Comment by Jbiloki** [comment]
Thanks for clarifying and for your help!
