### ISSUE TITLE
== test reports false for the mismatched types? but why can it be compiled successfully?

### ISSUE THREAD

**Issue by xgfone** [golang/go#40493]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitlab.sndaurl.cn"
GONOSUMDB="gitlab.sndaurl.cn"
GOOS="linux"
GOPATH="/root/gopath"
GOPRIVATE="gitlab.sndaurl.cn"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build349278088=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
// main.go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	var i interface{}

	i = uint(0)
	switch v := i.(type) {
	case uint, uint8, uint16, uint32, uint64:
		fmt.Println("111:", v == 0) // Why is v not equal to 0?? Because of mismatched types??
	case int, int8, int16, int32, int64:
		fmt.Println("222:", v == 0)
	default:
		panic(v)
	}

	// ------------------------------------------------------------------------ //

	switch vf := reflect.ValueOf(i); vf.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fmt.Println("333:", vf.Int() == 0)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		fmt.Println("444:", vf.Uint() == 0)
	default:
		panic(i)
	}

	// v1 := int(0)
	// v2 := uint(1)
	// fmt.Println(v1 == v2) // Cannot compile because their types are mismatched.
}
```

### What did you expect to see?
```shell
$ go run main.go
111: true
444: true
```

### What did you see instead?

```shell
$ go run main.go
111: false
444: true
```

**Comment by davecheney** [comment]
Smaller reprodution
```
package main

import (
	"fmt"
)

func main() {
	var v interface{} 
	v = uint(0)
	switch v.(type) {
	case uint, int:
		fmt.Println(v == 0)
	}
}
```
the answer is because v is of type uint while 0 is of type int. 

Thank you for raising this issue. Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode
