### ISSUE TITLE
x/website: Improve "getting started" experience with simplified install steps and tutorials.

### ISSUE THREAD

**Issue by stevetraut** [golang/go#40496]
This is an issue requesting additional documentation.

The current [Getting started](https://golang.org/doc/install) topic includes information that is likely not needed (at least, at first) by most new users. A new user is likely not installing multiple Go versions, nor are most likely to be concerned about system requirements. We could break up the topic's information to help new users focus on what's essential to begin.

We could make the following changes:

- Streamline the install experience to include merely a download link for the installer and instructions for installing. 
- Detect user OS and present only the information they are likely to need (but give easy access to the rest).
- Move other information from the existing [Getting started](https://golang.org/doc/install) into a separate topic where it can be found by those users who need it.
- Add a very brief tutorial that introduces a small amount of code, a few Go commands, and a few key concepts. We can then link to this tutorial from the install topic.
- Add a longer tutorial that introduces concepts and code fundamental to programming generally (functions, loops, data types, and so on). Sections of the tutorial would be connected by a narrative thread.

@andybons @dmitshur

**Comment by stevetraut** [comment]
I have a branch with changes in progress.

**Comment by stevetraut** [comment]
I think this is closed with the commit on 8/31.

**Comment by dmitshur** [comment]
I found that there's a little more that needs to be done here.

Specifically, [CL 246499](https://golang.org/cl/246499) copied doc/install.html and doc/install-source.html files from the main repository. We need to also delete those files from the main repository, otherwise contributors may accidentally send their changes to the old copy, not realizing the file has moved to x/website.

It seems there were changes to doc/install-source.html since then that'll need to copied over:

- [ ] [CL 250997](https://golang.org/cl/250997) added the linux/riscv64 pair, but it's not there in the x/website copy
- [ ] [CL 254740](https://golang.org/cl/254740) added new GOOS=ios value, but it's not there in the x/website copy
