### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by tutoraddicts** [golang/go#40534]
# It is regarding the instruction about how to install go in linux

here are the steps you mention :
1. tar -C /usr/local -xzf go1.14.6.linux-amd64.tar.gz
2. export PATH=$PATH:/usr/local/go/bin    // yah it is fine but 
 
*** `sudo ln -s /usr/local/go/bin/go /bin/go` **** 
// just symlink the file into bin then we can access go without using the second command every time and it will be easy for other new users to who don't know about this commands.

**Comment by ALTree** [comment]
> we can access go without using the second command every time 

You add `/usr/local/go/bin` to PATH in the bash_profile file once, and then you'll always be able to just call `go`; you don't need to manually export the modified `PATH` every time you open a terminal. It actually says so:

> you can do this by adding this line to your /etc/profile (for a system-wide installation) or $HOME/.profile: 

Closing here, since it seems to me you have misunderstood the instructions.
