### ISSUE TITLE
x/tools/gopls: improve workspace/symbol ranking

### ISSUE THREAD

**Issue by macintacos** [golang/go#40548]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

- I asked something in the `#vscode` Slack that ended up in me opening this feature request: https://gophers.slack.com/archives/C2B4L99RS/p1596297841207700

**Is your feature request related to a problem? Please describe.**

Right now there are a couple of things that I don't particularly like about how this extension handles symbols when using the `Go to Symbol in Workspace...` action in VSCode:

1. It doesn't seem to populate results immediately (for me). The prompt comes up and it doesn't give me a list of variables immediately without needing to type in a search (FWIW, the Python extension does this, not sure what's going on with this extension). I don't know if this is related to the next issue I have with it, which is...
2. When I search for a symbol that I know is in my workspace, the extension seems to provide all of the symbols in my _dependencies_ as well, and doesn't seem to rank the symbols in my project above the others. Here's me searching for `start` (looking for the `startCmd` variable) which appears more than halfway down the list somehow:

![image](https://user-images.githubusercontent.com/8128941/89139874-1cf07300-d50e-11ea-90d5-837e4fccc9d5.png)

**Describe the solution you'd like**

One of two things (preferably an option between either because why not):

1. Rank symbols in my workspace above others that return when searching for symbols in a workspace.
2. Remove symbols that aren't in my project entirely; I'd personally argue that all of those other symbols shouldn't be in the list of options, and should only be exposed if you've checked an option somewhere in settings.

**Describe alternatives you've considered**

I've went through a bunch of options in this extension and couldn't figure out how to make this work. Definitely could've missed something though, so please feel free to school me and tell me that this functionality already exists.

**Comment by myitcv** [comment]
There is a stack of changes to improve the workspace symbol support in progress: https://go-review.googlesource.com/c/tools/+/228760/31. This work needs to be rebased but will then hopefully form the basis of more advanced search modes, including better ranking (I experimented with an advanced query syntax in https://go-review.googlesource.com/c/tools/+/227677/41)

cc @findleyr

**Comment by macintacos** [comment]
Awesome, thanks @myitcv! I'll follow along.

**Comment by findleyr** [comment]
The above [CL](https://golang.org/cl/247818) (based on Paul's original [CL](golang.org/cl/228760)) improves ranking for fuzzy matching, and prepares for further ranking improvements.

I jump to symbols outside of my workspace all the time, so would object to removing that feature altogether :)  Let's start by downranking symbols outside of the workspace and see if that is good enough -- I'd like to avoid adding another configuration option if possible.  Regarding "preferably an option between either because why not": because it takes effort to support!

Also, regarding this
> It doesn't seem to populate results immediately (for me). The prompt comes up and it doesn't give me a list of variables immediately without needing to type in a search

@macintacos what would you like to see without a search query?  In any moderately sized project there will be so many symbols that whatever arbitrary N symbols are returned for the empty query are unlikely to be relevant.  We're also limited by the LSP in what we can do here: we don't know which buffer(s) are currently visible in the editor, so we can't do something like prefer symbols in the current file.  We *could* do something, like show recently used symbols or symbols in *open* files, but I'm not convinced either of those are worth implementing. In practice, the user will almost always type something.

CC @heschik

**Comment by macintacos** [comment]
@findleyr Fair enough on all the initial points!

As for what to show without a search query, showing the most recently used symbols in open files makes sense to me, but I understand the motivation to leave it the way it is. I use VSCode for Python as well, so perhaps that's a good point of reference, considering that it's such a widely used extension? From what I can tell, it just lists symbols in the project in alphabetical order, but I'm not sure of their motivation behind doing it that way. The only thin I can think of is that it's reassuring to see some visual feedback that the extension _knows_ about symbols in your project before you begin typing, so showing symbols alphabetically is "good enough".

I don't have any string opinion about showing symbols before you begin typing though; that has less of an impact in relation to the ranking behind the search itself.

**Comment by findleyr** [comment]
With the combination of dynamic symbols becoming the default, and the downranking that was added, I think the situation is significantly better now. Going to close this as I have no other concrete ideas for what to improve. Please re-open if workspace symbol ranking is not working for you.

**Comment by myitcv** [comment]
The only thing I would like to see being added is, as we discussed previously, some means of predefining the scope of a search. I find myself regularly wanting to jump to an identifier within the current package (where "current" is defined by the file in which the cursor was sitting when the command was triggered) - having the search space be "everything" means:

* it's slower
* it's more typing to get to the precise answer

But I'll raise this in a separate issue, and/or implement if I find some time.
