### ISSUE TITLE
x/pkgsite: move package files to bottom of doc page

### ISSUE THREAD

**Issue by myitcv** [golang/go#40611]
### What is the URL of the page with the issue?

https://pkg.go.dev/cuelang.org/go/cue?tab=doc

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
</pre>

### Screenshot

![Screen Shot 2020-08-06 at 11 15 58](https://user-images.githubusercontent.com/3374574/89520751-417e7080-d7d6-11ea-8b54-860f32492f53.png)

### What did you do?

Visited the page.

### What did you expect to see?

As a user of the package, the most important information about this package at the top of the page.

### What did you see instead?

A long list of the package files. 

As a user of the package, I don't really have any need for this information. 

If this is required (see https://github.com/golang/go/issues/37863) then it should appear towards the bottom, as the primary user of this page is a user of the package.

**Comment by julieqiu** [comment]
We can move the package files to the bottom of the page. They were added to that position to match the structure on godoc.org.

Example for https://godoc.org/cuelang.org/go/cue:

![Screen Shot 2020-08-17 at 11 03 49 PM](https://user-images.githubusercontent.com/5943521/90465705-ebff6900-e0dd-11ea-9ab0-6bac124dfae2.png)

We'll move the package files section to the bottom of the page. Mock to be implemented:

![Screen Shot 2020-08-17 at 11 06 29 PM](https://user-images.githubusercontent.com/5943521/90465865-4d273c80-e0de-11ea-8582-f31dff3b56d2.png)

**Comment by myitcv** [comment]
Thanks @julieqiu. I think my eye/mind must have simply skipped this before because the amount of space this section currently takes up on godoc.org is markedly less that pkg.go.dev. But moving to the bottom sounds sensible - this is useful information, but only to a small percentage of people (citation required).

**Comment by tooolbox** [comment]
I agree that, with the page exactly as it is, the file listing should be at the bottom.

However, I would venture to say that this problem is really "created" by a combination of:

1. The exploded formatting of the file listing.  Godoc has them jammed together, which is perhaps ugly but *very* useable, and takes an appropriate amount of space for its significance.  I am sure there is a clever solution which can look nicer without requiring as much whitespace as it does now.
2. The missing index as per #40612 and #40577

I am fairly certain that solving (reverting, perhaps?) those two points would make this a non-issue.
