### ISSUE TITLE
cmd/go/internal: duplicate initialization of buildcontext

### ISSUE THREAD

**Issue by liu-xuewen** [golang/go#40707]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.4.2
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Linux amd64
</pre></details>

### What did you do?

nothing

### What did you expect to see?

Remove the build.Context Repeated initialization
https://github.com/golang/go/pull/40581/files

### What did you see instead?

During variable initialization, the build.Context Repeated initialization

**Comment by dmitshur** [comment]
Thanks for reporting an issue. There's not enough information here to understand what the problem is.

You mention "Repeated initialization". What is repeated? In the PR you've linked, it looks like initialization of GOPATH, GOOS, GOARCH, and CgoEnabled fields from environment variables is being removed, but I don't see where else it's being done. Can you please elaborate?

/cc @jayconrod per [owners](https://dev.golang.org/owners).

**Comment by jayconrod** [comment]
@liu-xuewen Please explain exactly what the problem is. We're not sure what you're trying to fix. There is no duplicate initialization being removed in [CL 246797](https://go-review.googlesource.com/c/go/+/246797). That change appears to break cross-compilation when `GOOS` and `GOARCH` have been written with `go env -w`.
