### ISSUE TITLE
go 1.15 release note fix

### ISSUE THREAD

**Issue by ostcar** [golang/go#40716]
As descried [here](https://github.com/golang/go/issues/39776#issuecomment-672727961), there is a backwards incompatible change between go 1.14 and go 1.15. It was a bug in go 1.14 and therefore is not guarded by the [golang 1 promise](https://golang.org/doc/go1compat#expectations).

I think, there should be a note in the [go 1.15 release notes](https://golang.org/doc/go1.15) about this backwards incompatible change.

**Comment by mvdan** [comment]
FYI @andybons @dmitshur

**Comment by dmitshur** [comment]
> As descried [here](https://github.com/golang/go/issues/39776#issuecomment-672727961),

@ostcar Can you please answer these questions from the issue template:

1. What version of Go are you using (`go version`)? (Go 1.15, I understand.)
2. What operating system and processor architecture are you using (`go env)`?
3. What did you do?
4. What did you expect to see?
5. What did you see instead?

Without complete information, it's hard to understand where the problem is. Thank you.

See [CONTRIBUTING.md#filing-issues](https://github.com/golang/go/blob/master/CONTRIBUTING.md#filing-issues) for more information.

**Comment by ostcar** [comment]
I am really sorry. When I was filling out the template and build an example program, I released, that there was a concurrency bug in my code. The behavior with go 1.14 and go 1.15 are the same. Only the goroutines run in a different order.

I thought, the issue template was not necessary, since it was only an issue with release notes. But this showed me, that it is always important to fill out the template. I promise to do better the next time. Sorry for all the noise. And thank you for your great work!

**Comment by dmitshur** [comment]
No worries, thanks for getting to the bottom of this!
