### ISSUE TITLE
x/pkgsite: standard library packages are not discoverable

### ISSUE THREAD

**Issue by penmanglewood** [golang/go#40785]
### What is the URL of the page with the issue?
 https://pkg.go.dev/
 
 
### What is your user agent?
 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15 
 
 
### Screenshot
 

 
<img width="1430" alt="Screen Shot 2020-08-14 at 3 29 13 PM" src="https://user-images.githubusercontent.com/1224356/90224861-ec300800-de42-11ea-8b87-b8fa78f378f8.png">

 
 
### What did you do?
 

I clicked on "Discover Packages".
 
 
### What did you expect to see?

I expected to have the ability to _discover_ packages, especially from the standard library, as the link promises.
On https://golang.org/pkg/, I am able to see at a glance the entire standard library and _discover_ new packages I haven't used before.
 
### What did you see instead?

Instead, I see a search bar. This indicates that I need to already know what I'm looking for.

**Comment by dmitshur** [comment]
On https://golang.org/pkg/, only the packages from the standard library are included, so it is viable to list every single package in an exhaustive list on the front page. On https://pkg.go.dev, there are many more packages that can be discovered, so exhaustively listing them all on the front page is not viable.

Do you think something else can be done? Or is your suggestion to make it easier to understand how to find a list of packages that are only in the standard library?

One more question. Are you already aware of the https://pkg.go.dev/std page, which has a "Packages" tab that lists all packages? I'm asking because if you weren't aware of it, it's possible that making _that_ page more discoverable can be a way to improve the situation.

/cc @julieqiu @jba @jamalc per [owners](https://dev.golang.org/owners).

**Comment by penmanglewood** [comment]
> Do you think something else can be done? Or is your suggestion to make it easier to understand how to find a list of packages that are only in the standard library?

Yes I was suggesting making it easier to discover standard library packages without needing to know about their existence in the first place.

https://godoc.org lists the top 25 packages by popularity and has links to the standard library, golang.org/x packages, and various search filters on Github. This level of discoverability is nice, in my humble opinion.

Given that a flash message on https://godoc.org is currently offering to "Always use pkg.go.dev" instead of godoc.org, it would be great to keep this level of discoverability in the new offering.

**Comment by penmanglewood** [comment]
> One more question. Are you already aware of the https://pkg.go.dev/std page, which has a "Packages" tab that lists all packages? I'm asking because if you weren't aware of it, it's possible that making that page more discoverable can be a way to improve the situation.

I wasn't aware of this page. Thank you for pointing it out.

For the purposes of making this issue actionable, I second your suggestion of linking to https://pkg.go.dev/std from the "Discover Packages" page.

**Comment by themowski** [comment]
I'd like to give a strong +1 for this issue. I would really like to see the standard library documentation explicitly linked somewhere instead of hidden behind the search functionality.

Right now, my solution to this problem is having a bookmark that takes me to https://pkg.go.dev/std -- but I'm an experienced Go user, and I knew that that was what I was looking for, and that it's the standard library documentation. From the perspective of a new user of any language, I like to know what packages are available in the standard library, and right now that information is not intuitive to find on pkg.go.dev at all.

In addition to the proposed option of adding some kind of link to the main "Discover" page, I would also recommend adding a "Standard Library" link under "Packages" in the page footer (where the red box is in this screenshot):

![image](https://user-images.githubusercontent.com/13295249/133268562-a61aa406-b0e4-4218-a175-1c3de9714d1e.png)

While putting the link in the footer isn't ideal, it would be a lot better than not having it anywhere, and I'm honestly surprised every time I go to pkg.go.dev without using my standard library bookmark that it's _not_ there already.

**Comment by jinhongy** [comment]
Thanks for the feedback. We are in the process of unifying the experience for golang.org and go.dev, with the new design, we will include the standard library link on the secondary navigation on top, which I think will solve this issue.

**Comment by fzipp** [comment]
The new unified experience was launched today, but there still doesn't seem to be a link to the standard library overview https://pkg.go.dev/std in the navigation.

**Comment by seankhliao** [comment]
The updated footer seems to only affect go.dev but not pkg.go.dev?

**Comment by seankhliao** [comment]
Closing as done
