### ISSUE TITLE
cmd/compile: some 386 builders fails after CL 244917

### ISSUE THREAD

**Issue by cuonglm** [golang/go#40808]
After [CL 244917](https://go-review.googlesource.com/c/go/+/244917), some 386 builders fails, e.g:

https://build.golang.org/log/d7370db05067093ad2de2afd5cadd573bcfcf779

It's not clear to my why, any idea @mdempsky 🤔

**Comment by mdempsky** [comment]
Seems like it affects all 32-bit architectures. E.g., reproduce locally with:

```
$ cd $GOROOT/test
$ go build run.go
$ GOARCH=386 ./run -- fixedbugs/issue39292.go
$ GOARCH=arm ./run -- fixedbugs/issue39292.go
$ GOARCH=mips ./run -- fixedbugs/issue39292.go
```

**Comment by cuonglm** [comment]
> Seems like it affects all 32-bit architectures. E.g., reproduce locally with:
> 
> ```
> $ cd $GOROOT/test
> $ go build run.go
> $ GOARCH=386 ./run -- fixedbugs/issue39292.go
> $ GOARCH=arm ./run -- fixedbugs/issue39292.go
> $ GOARCH=mips ./run -- fixedbugs/issue39292.go
> $ GOARCH=mipsle ./run -- fixedbugs/issue39292.go
> ```

Only freebsd 11_2 386 passed.

**Comment by mdempsky** [comment]
Oh, lol, it's because the threshold for forcing heap allocations is 64kB, and an array of `[10000]*int` has size 80kB (>64kB) on 64-bit architectures, but 40kB (<64kB) on 32-bit architectures.

I think bumping the array length from 1e4 to 1e6 should be robust.

> Only freebsd 11_2 386 passed.

I wouldn't be surprised if that builder skips running regression tests.

**Comment by mdempsky** [comment]
@cuonglm Thanks for flagging this.
