### ISSUE TITLE
cmd/go2go: cannot infer T in an embedded field.

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#40814]
Program https://go2goplay.golang.org/p/L5jQWGZvxDe cannot be compiled:

```go
package main

import "fmt"

type X[type T] struct {
}

func (x X[T]) Hello() (T, bool) {
	var v T
	return v, true
}

type Y[type T] struct {
	X[T]
}

func (y Y[T]) Foo() {

	s, ok := y.Hello()
	if ok {
		fmt.Println(s)
	}

}

func main() {
	y := Y[string]{}
	y.Foo()
}
```

```
type checking failed for main
prog.go2:19:11: type Y(T) of y does not match X(T) (cannot infer T)
```

**Comment by griesemer** [comment]
This is a variation of the same problem that plagues #39758. It's not yet implemented and thus leads to odd errors.

**Comment by griesemer** [comment]
This type-checks and compiles fine outside the playground (e.g., `go tool compile -G=3 bug.go`). It also [type-checks fine in the playground](https://go2goplay.golang.org/p/PzHXZSpyTkM)*. The new error:
```
./prog.go2:19: y._X undefined (type instantiate୦୦_Y୦string has no field or method _X)
```
appears to be due to a bug in the go2go translator. Leaving for @ianlancetaylor to decide if he wants to address this. 

*) This code was adjusted to match the currently supported syntax, and the generic types were unexported so that the compiler can handle it (as generic type export is not working yet).

**Comment by ianlancetaylor** [comment]
We are no longer fixing bugs in the go2go translator.  In any case it has many problems with embedded fields.

**Comment by YoshikiShibata** [comment]
Now this is no issue.
