### ISSUE TITLE
x/build: linux-arm builder can't finish an all.bash run when test sharding isn't used

### ISSUE THREAD

**Issue by randall77** [golang/go#40872]
When I run a trybot on linux/arm, I get "out of memory" or "no space left on device" errors.
```
ok  	reflect	3.259s
ok  	regexp	0.949s
ok  	regexp/syntax	4.910s
# cmd/compile/internal/ssa
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x29ca71, 0x16)
	/workdir/go/src/runtime/panic.go:1116 +0x5c
runtime.sysMap(0x11400000, 0x3000000, 0x42bc70)
	/workdir/go/src/runtime/mem_linux.go:169 +0xa8
runtime.(*linearAlloc).alloc(0x41d280, 0x3000000, 0x400000, 0x42bc70, 0x0)
	/workdir/go/src/runtime/malloc.go:1447 +0x94
```
```ok  	unicode/utf8	0.055s
ok  	cmd/addr2line	28.924s
ok  	cmd/api	113.949s
ok  	cmd/asm/internal/asm	33.778s
ok  	cmd/asm/internal/lex	0.233s
# cmd/fix.test
panic: no space left on device

goroutine 1 [running]:
cmd/link/internal/ld.Main(0x3f33c0, 0x4, 0x8, 0x1, 0xd, 0xe, 0x0, 0x0, 0x285316, 0x12, ...)
	/workdir/go/src/cmd/link/internal/ld/main.go:319 +0x1c08
main.main()
	/workdir/go/src/cmd/link/main.go:68 +0x12c
/workdir/go/pkg/tool/linux_arm/vet: fork/exec /workdir/go/pkg/tool/linux_arm/vet: cannot allocate memory
/workdir/go/pkg/tool/linux_arm/vet: fork/exec /workdir/go/pkg/tool/linux_arm/vet: cannot allocate memory
/workdir/go/pkg/tool/linux_arm/vet: fork/exec /workdir/go/pkg/tool/linux_arm/vet: cannot allocate memory
```

Is there anything we can do to fix this? Can we get more memory and/or disk space on these builders?

I could work on making cmd/compile/internal/ssa tests take less memory, perhaps. Not sure how much we could save.

**Comment by randall77** [comment]
How do the trybots succeed? Is it because they shard out the tests to multiple machines?

**Comment by dmitshur** [comment]
Can you please include links to CLs where you've seen this? That way we'll have more information (e.g., which commit was being tested exactly, etc.). How often is this happening? Did it start recently?

The linux-arm builder is defined https://github.com/golang/build/blob/148ff27ab5b70970002d390c9e1da4b861f6da9f/dashboard/builders.go#L1736-L1756. They run on Scaleway, so adjusting resources will be limited to what's available there (we might already be maxed out; but need to look again to be more confident).

I see that linux-arm trybots are currently disabled because of other issues:

```Go
tryBot:            nil, // Issue 22748, Issue 22749
```

Is this issue about that builder when requested via SlowBots or something else?

/cc @cagedmantis @toothrot @andybons per [builder owners](https://farmer.golang.org/builders).

**Comment by randall77** [comment]
This happens when using gomote to run all.bash manually:
```
gomote create linux-arm
gomote push user-khr-linux-arm-0
gomote run go/src/all.bash
```
Sorry, I guess I'm using the term "trybot" to mean both the thing that tests CLs as well as manual gomotes. I mean the latter (except in the context of my second comment).

**Comment by dmitshur** [comment]
@cagedmantis Do you expect #36841 will be able to help with this?

**Comment by cagedmantis** [comment]
@dmitshur Yes, I'm actively working on the linux-arm-aws builder with more resources. I will assign myself to this issue.

**Comment by dmitshur** [comment]
Oh, I believe this is the same issue as #35628. /cc @cherrymui I'll close it in favor of that one, and move your assignment @cagedmantis if you don't mind.

**Comment by cherrymui** [comment]
This is not exactly the same. #35628 is about trybot, this is about "when test sharding isn't used" e.g. manual gomote runs. The trybot one has weird STALE errors, whereas this one is OOMing or out of disk space.

About disk space, if I remember correctly, last time I looked, the machine actually has reasonably sizable disk space, but we're running on a very small partition.

**Comment by dmitshur** [comment]
We can re-open this if it'd be helpful to confirm this issue is fixed when #35628 is fixed, but as I understand, this builder is broken in all contexts other than as a post-submit builder (on build.golang.org).

**Comment by erikwilson** [comment]
Also ran into a similar `panic: no space left on device` error building go with an RPi4. 
In my case the `/tmp` partition is only 64MB, and it looks like the go building stuff needs slightly more.
Might be nice to put a check in the build script or have a better error message on the specific location since those files are cleaned up. 
As a workaround was able to `export GOTMPDIR=/dev/shm` and the build was able to succeed.

**Comment by cagedmantis** [comment]
Instead of dedicating more time to the linux-arm builders which is hosted on Scaleway, I think it may be best to replace the current linux-arm builder with the one hosted on AWS. The new builders have additional resources which should resolve all of these issues. Please comment if you disagree with this plan.
