### ISSUE TITLE
net/url: unexpected url encoding for ! in path

### ISSUE THREAD

**Issue by mh47838704** [golang/go#40894]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
alway Exist

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
func TestEncodedUrlPathEncode(t *testing.T) {
	urlString := "http://www.xyz.com/!^test.jpg"
	parsedUrl, _ := url.Parse(urlString)
	rawUrl := parsedUrl.EscapedPath()
	fmt.Println("encodedUrl：",rawUrl)
}

func TestEncodedUrlPathEncode(t *testing.T) {
	urlString := "http://www.xyz.com/!test.jpg"
	parsedUrl, _ := url.Parse(urlString)
	rawUrl := parsedUrl.EscapedPath()
	fmt.Println("encodedUrl：",rawUrl)
}
```
### What did you expect to see?
for example
```
originUrl：https://github.com/!test.jpg
encodedUrl: https://github.com/!test.jpg    --- result is expected

originUrl: https://github.com/!^test.jpg
encodedUrl: https://github.com/%21%5Etest.jpg
expected: https://github.com/!%5eds.jpg
```

### What did you see instead?
```
func (u *URL) EscapedPath() string {
	if u.RawPath != "" && validEncoded(u.RawPath, encodePath) {
		p, err := unescape(u.RawPath, encodePath)
		if err == nil && p == u.Path {
			return u.RawPath
		}
	}
	if u.Path == "*" {
		return "*" // don't escape (Issue 11202)
	}
	return escape(u.Path, encodePath)
}
```
i found the code int sdk, "validEncoded" method treat the "!" as encoded,  but in "escape" define "!"  need encoed when mode is “encodePath”， where is judged in method "shouldEscape", logic conflict, so the result is not expected. 

and i found other language do not encode "!" "(" ")" , such as python

**Comment by davecheney** [comment]
Looking at RFC 3986 `^` must always be percent encoded while `!` may avoid percent encoding depending on its position in the URL. Section 3.3 indicates that `!` need not be escaped. However any character in a path element _may_ be percent escaped, for example `https://google.com/a` and `https://google.com/%61` are identical.

I agree that the addition of a character that must be escaped into a path element triggering other sub-delims to be percent encoded is surprising, but by my reading of the RFC not wrong. 

Can you explain how you found this issue and what problem is it causing for you?

**Comment by mh47838704** [comment]
i found this，cause i build a web proxy use go，a url through this proxy，the “!” has been encoded to "21%"，but the dest server also a proxy， dest server has a lot of rules to dispatch the request ，one of them is match the char “!”，because  the "!" was encoded to "21%" when the request  pass through my proxy server,  so the dest server can not match correctly

**Comment by buddhika-ranasinghe** [comment]
I also faced the same issue while I try to utilize Microsoft's Graph API.

What I experienced was the password which I need to get a JWT in below post request fails

https://login.microsoftonline.com/{{TenantID}}/oauth2/v2.0/token



`package main

import (
	"fmt"
	"net/url"
)


func main() {
	password := "my!pass*w'-ith(and)%[]"
	
	
	fmt.Println("Password : " + password)
	fmt.Println("Password QueryEscape" + url.QueryEscape(password))
	fmt.Println("Password PathEscape" + url.PathEscape(password))

	fmt.Println("Expected Output : my!pass*w'-ith(and)%25%5B%5D")
	

}`

Output : 

`$ go run main.go 
Password : my!pass*w'-ith(and)%[]
Password QueryEscapemy%21pass%2Aw%27-ith%28and%29%25%5B%5D
Password PathEscapemy%21pass%2Aw%27-ith%28and%29%25%5B%5D
Expected Output : my!pass*w'-ith(and)%25%5B%5D`


My experience with postman can get the token without any issue.
But when I do the same in Go Native I face the issue since we need to encode the password to generate x-www-form-urlencode. I believe this happens because Go is strict rfc-3986 compliance. But this could lead to many of the API Services built with JS will fail to communicate with Go applications since they use encodeURIComponent()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

Posman Screenshot : 

![image](https://user-images.githubusercontent.com/13096009/120408833-72372400-c36d-11eb-8f5e-aa6380bb5066.png)

**Comment by seankhliao** [comment]
it seems that we produce a valid encoding. use RawPath if you need some kind of unescaped variant.
