### ISSUE TITLE
x/net/http/httpproxy: http_proxy is being used for https requests

### ISSUE THREAD

**Issue by tkopecek** [golang/go#40909]
Go handles ``http_proxy/https_proxy/no_proxy`` in non-standard way. According to source [comment](https://github.com/golang/go/blob/01aad9ea939fed313d5c51778485349435302ead/src/vendor/golang.org/x/net/http/httpproxy/proxy.go#L29) ``http_proxy`` is used even for https urls. This is counterintuitive and not-working if it is not overriden.

My usecase is that I've local squid running with ``http_proxy`` exported. Nevertheless, squid is configured to handle also https but it is not propagated because it is using untrusted self-signed certificate. Go tries to connect to https via the proxy and fails with the reasonable ``certificate signed by unknown authority`` message. But at first place it shouldn't have used that proxy at all.

Code failing on this is referenced [here](https://github.com/containers/podman/issues/7367)

**Comment by bradfitz** [comment]
That CL's code seems fine, @fraenkel, but it's a behavior change away from the documented behavior (and changes the documented behavior), so the decision on whether to do this should be made intentionally.
 
I'm pretty sure the old behavior (of HTTP_PROXY also applying to "https" scheme URLs when HTTPS_PROXY was not present) was intentional but I don't have the time to go digging through git history to figure out whose behavior we were copying at the time, but I thought we were.

/cc @rsc who might also remember and should decide who makes this decision.

**Comment by bradfitz** [comment]
@neild, this should probably go in now-ish with release notes for Go 1.16 so we can see if anybody is surprised during the rcs/betas.

**Comment by neild** [comment]
Googling for `http_proxy` and `https_proxy` turns up mostly references to `curl` and `wget` in the first page of results, and I've confirmed that `curl`/`wget` don't use the value of the `http_proxy` environment variable for HTTPS connections. So while on one hand this is a behavioral change, it appears to be a change that brings `http/httpproxy`'s behavior in line with the most common definition of these environment variables.

Tentatively SGTM.

**Comment by dmitshur** [comment]
Closing as fixed. (We still need to document this change in Go 1.16 release notes, but that's tracked separately.)

The code change has happened in x/net in [CL 249440](https://golang.org/cl/249440), which got pulled into the standard library in [CL 266898](https://golang.org/cl/266898).

**Comment by dmitshur** [comment]
@taylanisikdemir This change is documented in the Go 1.16 release notes, see the 5th paragraph at https://golang.org/doc/go1.16#net/http.
