### ISSUE TITLE
x/tools/gopls: fix handling of end of file in internal/span

### ISSUE THREAD

**Issue by dandua98** [golang/go#41029]
Package `span` currently treats end of file as start of a new line (https://github.com/golang/tools/blob/c024452afbcdebb4a0fbe1bb0eaea0d2dbff835b/internal/span/token.go#L117), which is inaccurate for files with end of file not being a newline. This affects completion on end of file line and we're currently considering a temporary fix there (https://go-review.googlesource.com/c/tools/+/249706). A better fix should come from `span` itself and the package should check if a final new line is present before converting end of file to start of new line. Just removing this check breaks diff tests and is not a viable fix currently.

**Comment by stamblerre** [comment]
I think that, rather than changing the span package, we should do our best to work-around this in the cases where it comes up (so far, completion, and perhaps other features that insert edits like code actions). The work-around added in [CL 249706](https://go-review.googlesource.com/c/tools/+/249706) is not ideal because it is untested, so once we have support for completion in package declarations, we should see if we can improve and test it.

/cc @findleyr since we discussed this, and it's relevant to https://github.com/golang/go/issues/37702.

**Comment by stamblerre** [comment]
Given that we have a reasonable work-around for this in completion, removing from the 1.0 milestone.

**Comment by findleyr** [comment]
I don't understand how this isn't just a bug. Presumably the limitation is driven by the behavior of token.File, which IIRC ignores a trailing newline.

**Comment by findleyr** [comment]
I believe this is a non-issue now that we've switched to the new `protocol.Mapper`.
