### ISSUE TITLE
x/build:  linux-arm5spacemonkey builders are offline

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#41027]
Per https://farmer.golang.org:
```
host-linux-arm5spacemonkey: 0/0 (3 missing)
```

/cc @andybons @dmitshur @toothrot @esnolte

**Comment by cagedmantis** [comment]
@esnolte agreed to become the maintainer for the builder in #34973. It's been down for some time now and they have not responded since the creation of this issue. I believe we should consider removing this builder.

**Comment by cagedmantis** [comment]
`host-linux-arm5spacemonkey: 0/0 (3 missing)`

The builders are still missing. Can anybody work on bringing these up? If not, Is there any other person interested in taking over the builders?

@esnolte @zeebo @jtolio

**Comment by esnolte** [comment]
We were never able to get the builder running a few years ago and gave up.  I forget who on the golang team was looking into the problem, but there seemed to be a problem in the build script.   Something like trying to write to a read-only directory or something IIRC.

**Comment by cagedmantis** [comment]
It seems like you are referring to #35740. Do you have any interest in picking this issue up again?

**Comment by cagedmantis** [comment]
@esnolte Are you willing to work with our team to get the builder back up and running at this point? I understand that it was not prioritized at the time that it happened. If not, do you know of anybody willing to provide the builder? If we can't find somebody to support it, we will have to remove the builder.

**Comment by esnolte** [comment]
I can look at getting the builders back online.  What would you like me to do?

- Erik

**Comment by cagedmantis** [comment]
@esnolte Can you ensure that the latest version of the buildlet is configured and running on the hosts? Once we get them connected to the coordinator, we can work on any additional problems we encounter.

**Comment by esnolte** [comment]
I'm running into errors building buildlet as per https://github.com/golang/go/wiki/DashboardBuilders <https://github.com/golang/go/wiki/DashboardBuilders>.

***@***.***:~# go get -u golang.org/x/build/cmd/buildlet
# golang.org/x/oauth2/google/internal/externalaccount
gopath/src/golang.org/x/oauth2/google/internal/externalaccount/aws.go:130:18: undefined: strings.Builder
# google.golang.org/grpc/internal/credentials
gopath/src/google.golang.org/grpc/internal/credentials/spiffe.go:39:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
gopath/src/google.golang.org/grpc/internal/credentials/spiffe.go:48:24: cert.URIs undefined (type *x509.Certificate has no field or method URIs)
gopath/src/google.golang.org/grpc/internal/credentials/spiffe.go:52:26: cert.URIs undefined (type *x509.Certificate has no field or method URIs)
gopath/src/google.golang.org/grpc/internal/credentials/spiffe.go:70:14: cert.URIs undefined (type *x509.Certificate has no field or method URIs)

There's a weird version of Go on that host that's probably the underlying problem.

***@***.***:~# go version
go version devel +af74ab6 Wed Jun 14 17:51:12 2017 +0000 linux/arm

Is there another way to get buildlet?  Otherwise it will take a while to figure out a cross compile.

**Comment by cagedmantis** [comment]
I believe you can try downloading and running this buildlet: `https://storage.googleapis.com/go-builder-data/buildlet.linux-arm-arm5`. If that doesn't work, you can try and update the version of go that is installed on the machine to one of the latests releases.

**Comment by esnolte** [comment]
The buildlet runs, but I'm not sure what I'm suppose to do next.  https://github.com/golang/go/wiki/DashboardBuilders says I have to modify stage0.  I don't have a stage0.  Was I suppose to go get it like buildlet?

I wasn't able to find a golang distribution that works on armel.  The armv6l distro on golang.org is for armhf.  Also I don't have much room on the device (only 2 GB of a 4 GB SD card) so I keep running out of room when trying to build things.

**Comment by PaschaC420** [comment]
- [ ]

**Comment by cagedmantis** [comment]
Stage0 can be downloaded at `https://storage.googleapis.com/go-builder-data/buildlet-stage0.linux-arm`. The storage restriction would almost defiantly be a blocker. 

Now that the tree is back open and we are reviewing all the builders for the next release, do you think we can get over these barriers? If not then we should probably just remove this builder.

**Comment by cagedmantis** [comment]
@esnolte Do you have strong thoughts or feelings about this in either direction?

**Comment by esnolte** [comment]
I'd say remove these builders.  We haven't been in the office in almost 2 years and aren't likely to return until next year.

**Comment by bcmills** [comment]
If nothing else, it would be nice to shrink the build dashboard by a column. 😅
