### ISSUE TITLE
x/tools/go/analysis/passes/nilness: detect nil-checking helpers

### ISSUE THREAD

**Issue by ainar-g** [golang/go#41135]
<p>As&#xA0;of&#xA0;<code>v0.0.0-20200828161849-5deb26317202</code>,
the&#xA0;<code>nilness</code> command doesn't seem to&#xA0;take
into&#xA0;account nil-checking helpers, which are popular in&#xA0;e.g.
small scripts.&#x2003;Consider:</p>

<pre><code>     8	func check(err error) {
     9		if err != nil {
    10			panic(err)
    11		}
    12	}
    13	
    14	func f() (err error) {
    15		err = e1()
    16		if err != nil {
    17			return err
    18		}
    19	
    20		// Oops!  Forgot to replace "_" with "err" after debugging.
    21		_ = e2()
    22		if err != nil {
    23			return err
    24		}
    25	
    26		return nil
    27	}
    28	
    29	func g() {
    30		var err error
    31	
    32		err = e1()
    33		check(err)
    34	
    35		// Oops!  Forgot to replace "_" with "err" after debugging.
    36		_ = e2()
    37		check(err)
    38	}</code></pre>

<p><a href="https://play.golang.org/p/CdzEfHniCqv">Full&#xA0;code</a>.&#x2003;Currently,
<code>nilness</code> reports line&#xA0;22,
but&#xA0;not&#xA0;line&#xA0;37.</p>

**Comment by matloob** [comment]
I myself have used this style when starting code on a new project, but this isn't something that we want our tools to encourage: errors should be handled explicitly instead of using these sorts of helpers, even if it makes code more clunky.

(This is the sort of thing that would have been solved if we went forward with the "try" error handling proposal... alas...)
