### ISSUE TITLE
cmd/compile (types2, go/types): cannot infer generic interface types

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#41176]
commit 8ea0120a21b75837e38de2d04d9bc121757999e8

The type inference algorithm does not work when the actual parameter is a concrete type and the formal parameter is a generic interface type. It looks like the type inference description in the proposal doesn't cover interfaces, but I suspect it should.

https://go2goplay.golang.org/p/C53vOfwA9vq

```
package main

type S struct {}

func (S) M() byte {
	return 0
}

type I[T any] interface {
	M() T
}

func F[T any](x I[T]) {
	x.M()
}

func main() {
	F(S{})
}
```

This fails with the error:
```
prog.go2:18:4: type S of (S literal) does not match I[T] (cannot infer T)
```

FWIW type interfence doesn't work when the interface argument is a type parameter either, but I can't work out if that's covered by the proposal or not: https://go2goplay.golang.org/p/pAouk3xkmOX

```
func F[X I[T], T any](x X) {
	x.M()
}
```

**Comment by ianlancetaylor** [comment]
I agree that the current inference algorithm doesn't permit this inference.  I'm not at all sure that it should.  It requires that we go beyond looking at the type of the argument, to looking at the method set of the argument.  And as far as I can see it would only be useful to infer the type parameter of a parameterized interface type.  There is a pretty long step from argument method set to type argument for interface type.  Our goal for type inference is not all possible type inference, it's straightforward and easily understood type inference.  At least at first glance, I don't think this meets that goal.

**Comment by griesemer** [comment]
Marked as FeatureRequest as this is not a bug in the prototype.

**Comment by dmitshur** [comment]
@griesmer An issue should have one of NeedsInvestigation, NeedsDecision, or NeedsFix labels after being triaged (per https://golang.org/wiki/HandlingIssues#issue-states). I'll re-add NeedsInvestigation, but please feel to change it if another Needs label is more appropriate.

**Comment by griesemer** [comment]
@dmitshur ACK. Thanks for the reminder.

**Comment by rogpeppe** [comment]
FWIW I ran across this when experimenting with [making the `io` package generic](https://go2goplay.golang.org/p/jZL62aUhvHt). When dealing with generic interfaces I suspect it will be very common to pass a concrete implementation to a function that accepts the generic interface as an argument, just as in current Go it's common to pass a concrete type to an interface parameter.

This issue will tend to arise when using any generic iterator interface AFAICS, so I think it would be worth addressing. It certainly seemed like it _should_ work when I was adapting the code - I was surprised that it didn't.

**Comment by ianlancetaylor** [comment]
One of the common requests for the design draft is support for methods that have their own generic type parameters.  We don't currently know how to implement that (https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#no-parameterized-methods).  But if ever do figure out how to implement it, there is going to be some sort of relationship to parameterized interface types.  I at least don't fully understand how this should all work together, so I'm wary of adding type inference into the mix.

**Comment by rogpeppe** [comment]
> But if ever do figure out how to implement it, there is going to be some sort of relationship to parameterized interface types.

I'm sure there will be, but won't there also be some sort of relationship to concrete types too, and also to non-parameterized interface types? AFAICS adding methods with their own type parameters will largely be orthogonal to type inference in general, because the method type parameters are free and thus unrelated to the outer level type parameters.

As I see it, type inference on interfaces is not _that_ far off from type inference on constants, which has good treatment in the proposal.

**Comment by rogpeppe** [comment]
Here's a little motivational example: https://go2goplay.golang.org/p/SqTLFCSmUnc

Function types and single-method interfaces are generally quite similar, so it's surprising,
I believe, that type inference works when passing a function value, but not when passing
an interface implementation.

```
package main

import (
	"fmt"
)

func main() {
	i := intGetter(99)
	// This works fine.
	fmt.Println(getf(i.get))
	// ... but not when the argument is an interface.
	// An explicit [int] type parameter is needed.
	fmt.Println(geti(i))
}

type getter[T any] interface {
	get() T
}

type getterFunc[T any] func() T

func getf[T any](f getterFunc[T]) T {
	return f()
}

func geti[T any](f getter[T]) T {
	return f.get()
}

type intGetter int

func (i intGetter) get() int {
	return int(i)
}

```

**Comment by ianlancetaylor** [comment]
I think that what we are talking about here is extending the type inference rules so that if the function parameter's type T is a parameterized interface type I, then given type argument A we infer the arguments to I based on the methods of A.  We would presumably do this by walking through the methods of I, finding the identically named methods of A, and trying to unify the types of the two methods.  I agree that the results are likely to be unsurprising if A is a fully concrete type.  I am much less certain about the case where A is a parameterized type, in particular where we are compiling a parameterized function for which A's methods are defined by a constraint.

Maximizing potential type inference is definitely not a goal.  The primary guideline is that type inference must never be surprising.  A secondary guideline is that it must come up often enough to be useful.  I have no idea whether people will write many parameterized interface types (other than for use as constraints).  I don't quite see the point of a parameterized interface type.  Of course it must work, but will they be used frequently enough that it's worth writing type inference rules for them?

**Comment by rogpeppe** [comment]
> I am much less certain about the case where A is a parameterized type, in particular where we are compiling a parameterized function for which A's methods are defined by a constraint

The rules would obviously need to be thought about, and codified but my intuition is that the method set of any type is known (if generically typed) and once we've established the set of common methods, unifying should be very similar to unifying func types in the existing proposal.

>  I have no idea whether people will write many parameterized interface types (other than for use as constraints). I don't quite see the point of a parameterized interface type. Of course it must work, but will they be used frequently enough that it's worth writing type inference rules for them?

I have only one data point: my own experience; but I've played around with a couple of not-entirely-trivial pieces of generic Go code (I ported a concurrent ordered map implementation and I made the stdlib io library generic).

In both cases, generic interfaces were a key part of the design, and I'm pretty sure that they will continue to be as useful in general as I found them there.

This is a Good Thing IMHO. It's showing that Go's existing generic feature, the interface value concept, is entirely orthogonal to, and composible with, the proposed new type parameter feature.

One nice property of generically typed interface types is that values inside them can "hide" their own type parameters, which is something that a struct type cannot, because any generic member of the struct must have its type parameters declared on the containing type. Thus generic interface types are an important part of the backward-compatibility story: they are a way of adding potentially generic functionality without changing the type parameters (any change to type parameters being a backwardly incompatible change)

And that's quite apart from the more direct applications such as for iterators (the io package being an example of a batched iterator package - it could [be made (https://twitter.com/rogpeppe/status/1301189885836001281?s=19) without much difficulty. Why shouldn't we be able to use the `io.Pipe` to pipe batches of floating point numbers, for example).

**Comment by rogpeppe** [comment]
@griesemer Here's another example. Here we're passing an interface type that actually embeds the expected interface. I think it should be able to infer the type in this case at least.

```
package main

func main() {
	var x I2[int]
	F(x)
}

type I[T any] interface {
	Get() T
}

type I2[T any] interface {
	I[T]
	Foo()
}

func F[T any](i I[T]) {
}
```

I get the error:
```
./prog.go:5:4: type I2[int] of x does not match I[T] (cannot infer T)
```

**Comment by rogpeppe** [comment]
One other motivational example that I haven't explicitly mentioned above:
It's common in Go to return a concrete type that implements an interface and adds extra methods to that interface (e.g. strings.Reader, bytes.Buffer, etc). If we want to do the same thing with type-parameterised interface types, there's
more friction because the type parameter must be passed explicitly.

**Comment by jordanorelli** [comment]
I think this limitation will encourage people to make their generic interfaces recursive as a matter of habit and convenience.

Here's an example of what I mean:

```go
package main

import "fmt"

type A struct{}

func (a A) Open() string             { return "open" }
func (a A) AsOpener() Opener[string] { return a }

type B struct{}

func (b B) Open() bool             { return true }
func (b B) AsOpener() Opener[bool] { return b }

type Opener[X any] interface {
	Open() X
	AsOpener() Opener[X]
}

func Open[X any](o Opener[X]) X {
	x := o.Open()
	fmt.Printf("Opened Value: %v of type %T\n", x, x)
	return x
}

func main() {
	a, b := A{}, B{}

	Open(a.AsOpener())
	Open(b.AsOpener())
}
```
https://gotipplay.golang.org/p/0OVkKqxzRPH

Practically speaking you wind up with the situation that in order to utilize `A` with `Open`, you can either type `Open[string](a)` or `Open(a.AsOpener())`. You're incentivized to use `Open(a.AsOpener())` because now if you want to alter the definition of `A` to change the type to which it opens, you don't have to update your call sites as you would if you had written `Open[string](a)` instead.

**Comment by neild** [comment]
A surprising case which I ran into today, in which the compiler confusingly rejects a parameter after already inferring the type:

```go
package main

type Setter[T any] interface {
	Set(T)
}

type Int32Setter int32

func (v *Int32Setter) Set(x int32) { *v = (Int32Setter)(x) }

func SetAToB[T any](x T, target Setter[T]) { target.Set(x) }
func SetBToA[T any](target Setter[T], x T) { target.Set(x) }

func main() {
	target := new(Int32Setter)
	value := int32(0)

	SetAToB[int32](value, target)         // ok
	SetBToA[int32](target, value)         // ok
	SetAToB(value, Setter[int32](target)) // ok
	SetBToA(Setter[int32](target), value) // ok
	SetAToB(value, target)                // type *Int32Setter of target does not match inferred type Setter[int32] for Setter[T]
	SetBToA(target, value)                // type *Int32Setter of target does not match Setter[T] (cannot infer T)
}
```

https://go.dev/play/p/QUMBrOsblkP

In the second to last line, the compiler infers that the type parameter `T` is `int32`, but then complains that the second function parameter does not match the inferred type. This is technically true, because the inferred type is the interface type `Setter[int32]` and the parameter is a concrete `*Int32Setter`, but confusing because the parameter type is assignable to the inferred type.

**Comment by ianlancetaylor** [comment]
Replying to @neild 

Type inference never pays attention to assignabillity.

That said, there is something interesting about that example.  We can infer `T` from the first argument: `T` must be `int32`.  And at that point we have inferred all the type parameters.  So this is different from the earlier examples.  Here the problem is that function type inference always tries to unify all the function argument types with the type parameters.  I think that is important for reasonable handling of untyped constants.  But it's not necessarily important for handling of typed arguments.  For typed arguments we could skip cases where the types do not unify.  In this example that would tell us that `T` is `int32`, and then postpone everything else to the actual function call type checking.  In this case that would succeed through the implicit conversion to an interface type.

I don't know whether that is a good idea or not.  It depends on how often people want to use interface types with type parameters.  I don't know often that will happen.  In particular, I would write this code like this, which works today.

```Go
package main

type Setter[T any] interface {
	Set(T)
}

type Int32Setter int32

func (v *Int32Setter) Set(x int32) { *v = (Int32Setter)(x) }

func SetAToB[T any, Set Setter[T]](x T, target Set) { target.Set(x) }
func SetBToA[T any, Set Setter[T]](target Set, x T) { target.Set(x) }

func main() {
	target := new(Int32Setter)
	value := int32(0)

	SetAToB[int32](value, target)         // ok
	SetBToA[int32](target, value)         // ok
	SetAToB(value, Setter[int32](target)) // ok
	SetBToA(Setter[int32](target), value) // ok
	SetAToB(value, target)                // ok
	SetBToA(target, value)                // ok
}
```

**Comment by rogpeppe** [comment]
> It depends on how often people want to use interface types with type parameters. I don't know often that will happen.

As one data point, in the generic code I've written, interface types with type parameters seem to come up about as often as interface types without type parameters in regular code. It's often seems preferable to use an interface value rather than an interface constraint on a type parameter because it's more flexible (such an interface can go inside a struct, for example, and be added later while preserving backward compatibility, something an additional type parameter cannot) and more ergonomic (type parameters tend to pollute all the code they touch, so having several type parameters is a pain because they have to passed through to every data structure and function that operates on them).

In fact, I wouldn't be surprised if interface types with type parameters become more popular than constraints on type parameters because they're more general. For example, a generic interface can define behaviour over arbitrary types that aren't necessarily owned by the package implementing the interface.

For example, rather than defining graph type by [mutually recursive constraint types](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#mutually-referencing-type-parameters), it's arguably less awkward to define a graph [like this](https://gotipplay.golang.org/p/-HY85oQiLp_f):

```
type Graph[Node, Edge any] interface {
	Edges(n Node) []Edge
	Nodes(e Edge) (from, to Node)
}

func ShortestPath[Node, Edge any](graph Graph[Node, Edge]), from, to Node) []Edge
```

This allows the user to define a graph over any existing type that has a similar graph-like arrangement and also allows the interface methods to use arbitrary contextual information (stored in the `Graph` value) to influence behaviour.

**Comment by zephyrtronium** [comment]
Quick interjection: I think this issue should be categorized under go/types and types2, not cmd/go. Hopefully I'm not being needlessly pedantic.

**Comment by rogpeppe** [comment]
As a demonstration of how using generic interfaces can result in cleaner code, here's a concrete example of such a cleanup: https://github.com/ajwerner/btree/commit/b6ce38b6ffd95bd9fe2129b982bee8822e750ca. The interface that made the difference is [here](https://github.com/ajwerner/btree/commit/b6ce38b6ffd95bd9fe2129b982bee8822e750ca3#diff-139958cfa57aaab60b850c433455d910ce504da7876d32203d3e0128373a5ee8R28). In many places, the number of type parameters in use went from 5 to 3, and I suspect that given the GC stenciling approach used by Go generics, the performance characteristics would stay quite similar.

**Comment by jordanorelli** [comment]
hmm, I've been very curious about the distinction between a generic constraint versus a generic interface, so I've been playing around with the distinction. It's been hinted at earlier in this thread. What I mean is, given this type definition:

```go
type Fuses[X any] interface {
	FuseTo(*X)
}
```

We can write a function that just takes two arguments and executes that method. We can notate such a function in two different ways: by utilizing the name `Fuses` to express an interface type, or by utilizing the name `Fuses` to express a constraint.

Here we utilize `Fuses` to express an interface type:

```go
func Fuse[X any](a *X, b Fuses[X]) {
	b.FuseTo(a)
}
```

and here we utilize `Fuses` to express a constraint:

```go
func Fuse[X any, Y Fuses[X]](a *X, b Y) {
	b.FuseTo(a)
}
```

The second form gives me the behavior that I want. Given this type:

```go
type Total int

func (t Total) FuseTo(v *Total) { *v += t }
```

Now we try to call our `Fuse` function:
```go
v := Total(5)
Fuse(&v, v)
```
Utilizing the first definition (a generic interface), compiling the above code results in the following compile-time error:

```
type Total of a does not match inferred type Fuses[Total] for Fuses[X]
```

But the second definition (a generic constraint) works just fine. 

Here's a runnable example:
https://gotipplay.golang.org/p/LsItkZjDHft

When I saw this thread, I saw @ianlancetaylor 's comment:

>  It requires that we go beyond looking at the type of the argument, to looking at the method set of the argument.

And I thought "huh, that's weird, the error message clearly already knows that type".


I was finding it peculiar that one works, and one does not. I believe it works this way, but I may be out of my depth:
- `Fuse[X any, Y Fuses[X]](a *X, b Y)` can utilize inference, because `X` is known via function argument type inference, and `Y` is known via constraint inference
- `Fuse[X any](a *X, b Fuses[X])` cannot utilize inference. This seems supportable without having to look at the method set of the argument by having the compiler instantiate the `Fuses[X]` interface on your behalf with the known type of `X`. Instantiate the interface type off of the other type parameter and you're done, no need to look at anything other than the parameter types.

In regards to the original question posed:
```go
type I[T any] interface {
	M() T
}
```

We could intentionally rewrite the interface to something pretty similar to leverage parameter inference:

```go
type I[T any] interface {
	M(*T)
}
```

Now we just use the same technique of using a parametric constraint instead of a parametric interface:

as constraint:
```go
func F[P I[V], V any](v *V, p P) {
	p.M(v)
}
```

Same as before, the inference works fine because we have a parameter to start the sequence.

The example that @neild gives fits this pattern; the signature using an interface doesn't infer, the signature using a constraint does, because we have the means of rewriting the interface as a constraint instead.

Let's say we're dead set on keeping the original interface but instead of using a parametric interface parameter, we use a parametric constraint instead:

```go
type Opener[X any] interface {
	Open() X
}

func Open[E any, O Opener[E]](v O) {
	return v.Open()
}
```

Now the problem becomes very clear: E doesn't exist in the parameter list, so we can't use parameter inference to get E, which means we can't use it to derive O. Now this is I think accurately described: it can't be inferred without looking at the method set of the parameter. This seems harder to support, so the reasoning behind not doing it seems much more justified here.

Anyway, I think the utility of parametric interfaces is extremely high. In particular I'm really looking forward to a day when I can utilize a generic iterator type, because there are just too many different patterns for making iterator types. The standard library has many examples, and I've always wished they were more consistent.

Stateful iterators, that define `Next() bool`, where after testing the result of `Next()` you do some other thing that's specific to that type:
```
./database/sql/sql.go:2942:func (rs *Rows) Next() bool {
./testing/benchmark.go:725:func (pb *PB) Next() bool {
./reflect/value.go:1611:func (it *MapIter) Next() bool {
./reflect/all_test.go:6074:func (x *exhaustive) Next() bool {
```

Iterators that return (T, error):
```
./archive/tar/reader.go:47:func (tr *Reader) Next() (*Header, error) {
./debug/dwarf/typeunit.go:133:func (tur *typeUnitReader) Next() (*Entry, error) {
./debug/dwarf/entry.go:876:func (r *Reader) Next() (*Entry, error) {
```

Iterators that just return a value:
```
./container/list/list.go:31:func (e *Element) Next() *Element {
./net/textproto/pipeline.go:36:func (p *Pipeline) Next() uint {
./vendor/golang.org/x/text/unicode/norm/iter.go:124:func (i *Iter) Next() []byte {
./text/scanner/scanner.go:305:func (s *Scanner) Next() rune {
```

None of these on their own is bad, but it's awkward to have to know which style is used in which case, whether you have to check an `.Err()` method like in the sql.Rows example, etc. That one in particular can easily cause bugs, because you have to call Next, check errors, and call Scan; three methods that you have to call in the correct manner in order to get what you want, and it's very easy to screw up.

I've been thinking of what I'd like a generic iterator type to look like and playing around, but I got stopped in my tracks by this inference thing and got weirdly into understanding it. I'd love to see something like this:

```go
type Iterable[T any] interface {
    Iter() Iterator[T]
}

type Iterator[T any] {
    Iterable[T]
    Next(*T) bool
}
```

I think many people are going to be playing with similar interfaces so that they can write functions to take iterators or generic iterable objects instead of slices.

**Comment by ianlancetaylor** [comment]
> And I thought "huh, that's weird, the error message clearly already knows that type".

Your example is different.  Your example is the kind that I discussed in my recent comment https://github.com/golang/go/issues/41176#issuecomment-984723164.

**Comment by jordanorelli** [comment]
Sometimes you have to use a generic interface parameter, because using a generic constraint can't represent the same thing conceptually; it's not always a matter of taste/style. So for example, here's two functions that use the same interface definition, but that definition used as an interface parameter versus as a constraint on a type parameter have different semantic meanings.

```
type Boxed[N constraints.Integer] interface {
	Unbox() N
}

func SumAllI[N constraints.Integer](vals ...Boxed[N]) N { }

func SumAllC[N constraints.Integer, B Boxed[N]](vals ...B) N { }
```
runnable example: https://gotipplay.golang.org/p/364x5zVd9-S

SumAllI can be called with values of heterogenous types, but SumAllC cannot. So in this case, they're completely separate concepts; you have to use the generic interface if you want to sum generic containers,  and there's no way to rewrite it to use a generic constraint.

Another case I noticed is constraints of the form `[X M[X]]`, which describes a type that satisfies an interface by operating on other values of its own type. I don't really think that concept is representable using generic interfaces, so when you want that situation, you have to use the generic constraint on a type parameter and there's no way to rewrite it to use a generic interface on a regular parameter (... do we say "non-type parameter?")

**Comment by jordanorelli** [comment]
the cases where you get inference through the explicit function parameters is a case where using a constraint lets you instantiate fewer type parameters explicitly; you do a little bit more when you define the function, but it's easier on callers. There are some cases where it's the opposite: using an interface parameter type lets you instantiate fewer type parameters explicitly.

```
type Boxed[N constraints.Integer] interface {
	Unbox() N
}

func SumAllI[N constraints.Integer](vals ...Boxed[N]) N { }

func SumAllC[N constraints.Integer, B Boxed[N]](vals ...B) N { }
```

If `a`, `b`, `c` are values of different types that all define `Unbox() int`, you call `SummAllI[int](a, b, c)` with the interface parameter definition, but `SumAllC[int, Boxed[int]](a, b, c)` with the constraint definition. So in that case, a generic interface parameter is generally preferable to a constraint; both the definition and the call site are more clear.

https://gotipplay.golang.org/p/x1zFyQbYLiK

**Comment by zhuah** [comment]
> It depends on how often people want to use interface types with type parameters. I don't know often that will happen.

I'm recently refactored my framework code to using generics, in my  experiments, it seems a bit redundant and stupid  to adds a type arg in such case  again and again.

It would be very great if go could support this type inference on  interface.

**Comment by zhuah** [comment]
```
package main

type Setter[T any] interface {
	Set(T)
}

type Int32Setter int32

func (v *Int32Setter) Set(x int32) { *v = (Int32Setter)(x) }

func Set1[T any](target Setter[T], x T) { target.Set(x) }
func Set2[T any, Set Setter[T]](target Set, x T) { target.Set(x) }
```
 in this case, `Set1` and `Set2` are two different function, `Set1` has only one type arg, and `Set2` has actually two,
`target` in `Set1` is `Setter[T]` interface, and in `Set2` it will be the real argument type that just implements `Setter[T]`,

when using reflection, these two function is not identical.

**Comment by go101** [comment]
A similar problem?

```Go
package main

func foo[E any](v struct{x E}) {}

func main() {
	foo(struct{n int}{123}) // type struct{n int} of struct{n int}{…} does not match struct{x E} (cannot infer E)
}
```

**Comment by go101** [comment]
sorry, my mistake, the field names are different.

**Comment by bmhatfield** [comment]
I wanted to offer that I've hit this in practice refactoring existing interface-heavy code to be generalized. In particular, this code has 4 _very_ similar interfaces except that they each handle some different concrete type. This is a great use-case for generics!

I have a function like:
```go
func handler.NewHandler[T any](r reducer.Reducers[T], vec handler.Vector[T], f filter.Filters[T]) handler.Handler[T]
```

`handler.Vector[T]` is an interface:

```go
type Vector[T any] interface {
	Length() int
	Get(int) (*T, bool)
}
```

if I call the function:

```go
handler.NewHandler(itn.Reducers(), vec, itn.Filters())
```

According to gopls, the first and last arguments infer properly, but `vec` does not, even though the argument _is_ correct.

If I modify the call to:

```go
handler.NewHandler[ConcreteType](itn.Reducers(), vec, itn.Filters())
```

The code compiles as expected.

It took me a long time staring at the error to understand what had occurred, as it felt very unexpected that the inference of this function was only partially supported.

**Comment by arvidfm** [comment]
I've also run into this in practice (I think, at least. If this is a separate issue let me know). Consider this code:

```go
package main

type X[T any] struct{}

type Y struct{}

func F[T any](x X[T], y T) {}

func main() {
	x := X[any]{}
	F(x, any(Y{})) // works
	F[any](x, Y{}) // works
	// F(x, Y{})   // error: type Y of Y{} does not match inferred type any for T
}
```

Intuitively I would have expected `F(x, Y{})` to be the same as `F[any](x, Y{})`, but apparently not. Having to explicitly specify the type to each call of `F` is very cumbersome in my case.

**Comment by lawrencejones** [comment]
If I'm identifying the right issue, I think I've been hitting against the lack of inference for generic interfaces recently.

In hope that it's a useful example, we've been modelling modal forms in our app as the following:

```go
type Modal[Props, State any] interface {
  DefaultState() *State
  BuildProps(context.Context, *State) (Props, error)
  Render(Props, *State) *slack.ModalViewRequest
}
```

With a lot omitted, but the basic principle being that you can implement a modal as a struct that operates on Props (built-at-runtime properties) and State (provided from the current state of the form) types.

One function that is very hard to write is an initial `Render`.

If we want to render the modal for the first time from the rest of the app, we'd like to build a generic `Render` function that can make this easy and type-safe.

Ideally:

```go
func Render[Props, State any](modal Modal[Props, State], props Props) (*slack.ModalViewRequest, error) {
	return modal.Render(props, modal.DefaultState()).Build(modal)
}
```

So we can call it like so:

```go
// We provide an IncidentPostCreate type, which implements DefaultState returning an
// IncidentPostCreateState pointer, which means we should be able to infer State.
Render(IncidentPostCreate{IncidentID: inc.ID}, IncidentPostCreateProps{
	Organisation: identity.Organisation,
	Incident:     inc,
})
```

But because Go doesn't look at the first modal parameter type and understand that `DefaultState()` returns `*State`, and infer the `State` type from being provided with a modal, we're forced to explicitly type the call:

```go
// Required to provide Props and State
Render[IncidentPostCreateProps, IncidentPostCreateState](IncidentPostCreate{IncidentID: inc.ID}, IncidentPostCreateProps{
	Organisation: identity.Organisation,
	Incident:     inc,
})
```

It's not the end of the world, but it is pretty ugly. We can do something convoluted so we only need provide a State type parameter, rather than both:

```go
func RenderView[State, Props any, ModalType Modal[Props, State]](modal ModalType, props Props) (*slack.ModalViewRequest, error) {
	return modal.Render(props, modal.DefaultState()).Build(modal)
}

// This works, as we can infer Props from the function argument, and explicitly typing
// the parameters of the Modal interface means we can identify they relate.
//
// But we still need to provide State, even though ModalType must implement a DefaultState
// that could help us infer it.
Render[IncidentPostCreateState](IncidentPostCreate{IncidentID: inc.ID}, IncidentPostCreateProps{
	Organisation: identity.Organisation,
	Incident:     inc,
})
```

Of course, the compiler will shout if we ever provided types that didn't match along these boundaries, so it felt intuitive that it could also make inferences.

This given with an understanding that full inference is a non-goal, but figured it would be worth an additional case study.

**Comment by abraithwaite** [comment]
Here's a relatively simple yet somewhat surprising case which I think relates to this issue:

https://go.dev/play/p/eyX9kn3H4X7

Maybe I'm misunderstanding what's happening or what should happen, but I'd expect either a compiler error or `T` to be correctly identified as `main.TT` rather than `nil` in `printLnGen`.

```
package main

import (
	"fmt"
	"reflect"
)

func main() {
	type TT struct{ K int }
	var c any
	c = TT{K: 1}

	printLn(c)
	printLnGen(c)

	fmt.Println(reflect.TypeOf(c))
	fmt.Println(typeOf[TT]())
}

func printLn[T any](v T) {
	fmt.Println(reflect.TypeOf(v))
}

func printLnGen[T any](v T) {
	fmt.Println(typeOf[T]())
}

func typeOf[T any]() reflect.Type {
	var v T
	return reflect.TypeOf(v)
}
```

Is the right issue to watch or should I watch another one / open a new one?

Thanks!

**Comment by griesemer** [comment]
This also needs a concrete proposal outlining what's in scope.

**Comment by griesemer** [comment]
Directly related to #40055 with a similar [solution](https://github.com/golang/go/issues/40055#issuecomment-1553973509).

**Comment by griesemer** [comment]
Submitted accidentally, revert in progress. Reopening.
