### ISSUE TITLE
x/tour: Turkish Go Tour Website is unavailable

### ISSUE THREAD

**Issue by talhabw** [golang/go#41219]
When i tried open [Turkish Go Tour Website](https://go-tour-turkish.appspot.com/) i saw this error "Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.".

**Comment by dmitshur** [comment]
Thanks for reporting. It looks like the Turkish Go Tour needs to be redeployed with a newer version of Go.

Someone else runs the Turkish Go Tour, its GitHub project seems to be https://github.com/golang-tr/tour, so this issue should be reported there. There is one open at https://github.com/golang-tr/tour/issues/7, although it doesn't provide much detail.

**Comment by fatih** [comment]
I don't have access to the deployment environment, but I know that @roktas and his team were handling it. Not sure if things have changed since then. He'll probably going to respond here, if not I'll make sure to followup with him in other channels.

**Comment by ALTree** [comment]
Thanks @TalhaK15 for reporting this issue and @fatih for looking into it. I've created an issue in the tour tracker (where we usually track tour issues) to track the issue of translations offline due to the 1.9 deprecation: https://github.com/golang/tour/issues/1039.

**Comment by roktas** [comment]
@dmitshur Sorry for the late reply (could not reply immediately due to my busy schedule).  The Turkish Go Tour was run by a group of volunteers, which unfortunately, I haven't been able to reach at the moment.  I cannot give an exact date, but I will try my best to keep it updated. In the meantime, if anyone wants to help, I will gladly make the necessary directions.

/cc @fatih

**Comment by ALTree** [comment]
Link was removed, we can add it back when it goes back online. Closing here since no further action is required on the Go Project's side.
