### ISSUE TITLE
caller of func called by goroutine is goexit

### ISSUE THREAD

**Issue by wjh000123** [golang/go#41423]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.8
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

### What did you do?

get caller of some func
https://play.golang.org/p/gKjf1xNTCOK

### What did you expect to see?
see the correct caller

### What did you see instead?
for func called in goroutine mode, the caller is `goexit `

**Comment by davecheney** [comment]
This is caused by inlining. I don’t believe there is a bug here. 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

**Comment by randall77** [comment]
I don't think this has anything directly to do with inlining. It's just that in
```
func f() {
    go g()
}
```
`f` is not the caller of `g`. At least, not according to the runtime. For instance, the stack frame of `f` can be long gone while `g` is still running.

The caller of the function `g` is `goexit`. That's just a placeholder, we could just as well have decided that `g` doesn't have a caller. But `goexit` makes it clear that when `g` returns, the goroutine is going to exit (ala `runtime.Goexit`).

If you want to know where a goroutine was spawned from, that information is available in the output of `runtime.Stack`.

**Comment by wjh000123** [comment]
@randall77 thanks for your detail explanation!

What I want to do is to create a helper function to track caller in log without any injection code. After investigation, I did find `runtime.Stack` could do the trick, but somehow it is not elegant, and also performance.

It could be better to have a new function to get the spawner.
