### ISSUE TITLE
cmd/go: building 1.4 bootstrap toolchain failing on solaris 10

### ISSUE THREAD

**Issue by GrassInWind2019** [golang/go#41468]
I am trying to install Go1.15.2 on solaris 10 from source and it need Bootstrap toolchain.
I download  https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz, set CGO_ENABLED=0 in the environment, and run make.bash. 
It failed due to "ld.so.1: go_bootstrap: fatal: relocation error: file /export/home/dongsongz/go/go1.4-bootstrap/go/pkg/tool/solaris_amd64/go_bootstrap: symbol sem_reltimedwait_np: referenced symbol not found".

Following is the output:

```
[root@test:/export/home/dongsongz/go/go1.4-bootstrap/go/src]# export CGO_ENABLED=0
[root@test:/export/home/dongsongz/go/go1.4-bootstrap/go/src]# ./make.bash 
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, solaris/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
cmd/6g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
/export/home/dongsongz/go/go1.4-bootstrap/go/pkg/tool/solaris_amd64
ld.so.1: go_bootstrap: fatal: relocation error: file /export/home/dongsongz/go/go1.4-bootstrap/go/pkg/tool/solaris_amd64/go_bootstrap: symbol sem_reltimedwait_np: referenced symbol not found
./make.bash: line 167: 12294 Killed                  "$GOTOOLDIR"/go_bootstrap clean -i std
```

```
[root@test:/export/home/dongsongz/go/go1.4-bootstrap/go/src]# uname -a
SunOS test 5.10 Generic_147148-26 i86pc i386 i86pc
```

**Comment by ALTree** [comment]
I don't think Solaris 10 (aka SunOS 5.10) is supported. According to [this](https://github.com/golang/go/wiki/MinimumRequirements#solaris), you need 11+. And even then I think it's amd64 only. There's a solaris/spark out-of-tree port, but that one is also 11+ only. 

Since your combination of OS and architecture is not supported (and untested), I'm closing this issue. Feel free to comment if you also fail to build Go on a supported Solaris version (e.g. Solaris 11+ on amd64).
