### ISSUE TITLE
cmd/compile: confusing error message for non-bool comparison

### ISSUE THREAD

**Issue by smasher164** [golang/go#41500]
### What version of Go are you using (`go version`)?
go version go1.15.2 darwin/amd64

### What did you do?
I tried to compile the following program: https://play.golang.org/p/k1xIda2_lTk
```Go
package main

type Struct struct {
	Slice []int
}

func main() {
	var x *Struct
	if x == nil || len(x.Slice) {
	}
}
```
I forgot to add `len(x.Slice) == 0`.

### What did you expect to see?

```
non-bool len(x.Slice) (type int) used as if condition
```

### What did you see instead?

```
cannot use x == nil (type untyped bool) as type int
```

**Comment by cuonglm** [comment]
This is at least, working as intended per Go spec. `x == nil` yields an *untyped bool*, `len(x.Slice) yields an *int*, so `x == nil` is first converted to `int`, which produces that error.

I'm not sure is there anything we should fix here cc @mdempsky

**Comment by mdempsky** [comment]
The issue here is when type-checking binary operations like `X op Y`, the Go compiler:

1. Checks that `X` and `Y` have the same type.
2. Checks that `op` is a valid operation on `X` and `Y`'s type.

As @cuonglm points out, `x == nil` has type "untyped bool", so we try to convert it to "int". But that's not allowed, hence the error.

In this case though, that leads to a slightly suboptimal error message. Because `||` and `&&` are only valid on boolean types anyway, so it's perhaps a bit misleading to users to focus on converting "untyped bool" to `int`, rather than not being able to use `int` as a bool.

I suspect a check like:

```
if n.Op == OANDAND || n.Op == OOROR {
    if !n.Left.Type.IsBoolean() {
        yyerror("non-bool %L used as %v operand", n.Left, n.Op)
        n.Type = nil
        break
    }
    if !n.Right.Type.IsBoolean() { ... }
}
```

before the `defaultlit2` call might give an error message similar to the suggested one.
