### ISSUE TITLE
x/tools/gopls: support renaming a package

### ISSUE THREAD

**Issue by golopot** [golang/go#41567]
#### What did you do?
1. Open a go file in vscode
2. Put keyboard cursor on the line `package somepackage`.
3. Press F2 (rename symbol)

#### What did you expect to see?
Let me rename package.

#### What did you see instead?
This element cannot be renamed.

#### Build info
golang.org/x/tools/gopls v0.5.0
go version go1.15 linux/amd64

**Comment by msAlcantara** [comment]
There is some tips to implement this? I think that this could be super useful and I would like to implements. I think that the implementation should be in [qualifiedObjsAtProtocolPos](https://github.com/golang/tools/blob/master/internal/lsp/source/implementation.go#L216) function, I'm in the right way?

**Comment by stamblerre** [comment]
@msAlcantara: Thanks for your interest! I think this is slightly more complicated than that because the package name declaration does not have a `types.Object`, so I don't think it would work in the framework of `qualifiedObjsAtProtocolPos`. Still, renaming a package should be a lot simpler than a standard rename, because you can access the position of the package name by looking at the AST of each file in the package (https://pkg.go.dev/go/ast#File.Package). There will be some complexity with test packages, but hopefully it's as simple as updating their names too. Does that help at all?

**Comment by msAlcantara** [comment]
Thanks very much for your awnser, but I have some question about it. 
1. There something that tell me that the rename is of package name? 
2. Do you think that is better change `qualifiedObjsAtProtocolPos` to support rename a package or is better do something like this: `if isPackageRename(...) { ... }`?

Sorry is this questions is too dump, I'm a just getting started with gopls source code and I'm trying to understand

**Comment by stamblerre** [comment]
Please don't apologize--this is a tricky issue! I think the easiest thing would be to do something like `if isPackageRename(...)` in the rename logic itself (not in `qualifiedObjsAtProtocolPos`).

**Comment by jan-xyz** [comment]
Should an implementation for this also rename the directory and the package comment? And if "yes", is this still possible by looking at the position in the AST? What would happen if the `package` declaration and directory are already different? Should they become harmonised or only rename the `package` declaration in that case? We probably also need to account for blackbox test packages, right (e.g. `package foo_test`)?

**Comment by findleyr** [comment]
Hi I think this is something that @dle8 might look into.

> Should an implementation for this also rename the directory and the package comment?

IMO yes it should do both (note that LSP supports renaming files via TextDocumentEdits, so I think this should be possible).

To start we can implement `textDocument/references` on package names (`package foo`).

**Comment by findleyr** [comment]
Right now our protocol package only supports DocumentChanges that are [`TextDocumentEdits`](https://cs.opensource.google/go/x/tools/+/master:internal/lsp/protocol/tsprotocol.go;l=5702;drc=b7d757405fe14c924baefbdedd785e4c6a7a0f88), that needs to be fixed in order to support renaming files/directories. CC @pjweinb

It's probably also worth researching exactly how well supported renaming files is among LSP clients, as I can imaging this might be a tricky operation.

**Comment by findleyr** [comment]
The initial version of this was implemented in [CL 420958](https://go.dev/cl/420958), though there are several improvements yet to land.

**Comment by ajlive** [comment]
This is awesome. Thanks!

**Comment by findleyr** [comment]
With [CL 443637](https://go.dev/cl/443637), I think the basics of this feature are in place. #56184 tracks additional improvements / handling of edge cases that we can add for v0.11.0.
