### ISSUE TITLE
go/packages: switch to native overlays for 1.16

### ISSUE THREAD

**Issue by stamblerre** [golang/go#41598]
https://github.com/golang/go/issues/39958 will be part of the 1.16 release. As soon as https://golang.org/cl/253747 is merged, we can start adding a flag to use native Go command overlays in go/packages and begin testing with `gopls`.

/cc @matloob @heschik @findleyr

**Comment by stamblerre** [comment]
It's looking like we will need to get the Go version for every call to packages.Load.

@heschik: Would it be reasonable to cache the go version in the go command runner, and consequently, enforce a requirement that a given runner can only be used with a single `go` binary?

**Comment by heschik** [comment]
There is currently no clear rule about what the lifetime/scope of a Runner is, and it's currently one per gopls session, so that would definitely not be correct given differing environments.

We already do multiple go command invocations per Load call (size loading, in particular) and I don't think this is the time to try to reduce them. That said, I think the approach I took in `imports.(*ProcessEnv).init` is a reasonable template, but the Go version and size information are somewhat different since they are not actually directly user-overridable.

**Comment by stamblerre** [comment]
Ok, thanks--I wasn't sure if it was OK that we would be adding another `go list` call to go/packages. I will file a separate issue as a reminder to look into this.
