### ISSUE TITLE
x/pkgsite: Help to remove package, please.

### ISSUE THREAD

**Issue by huyungtang** [golang/go#41597]
#### Please remove the following packages
- github.com/huyungtang/golang.library 
- github.com/huyungtang/golang.library/helpers
 
### What did you expect to see?
Please refer to the following suggestions, maybe it's a easier way to remove packages:
- When users click the package link (with version tag) on tab overview, check the tag if still exists.
- If it were untagged (with return HTTP status code 404), the tag "Latest" could be also untagged.

Sometimes the wrong version published and downloaded for testing.
That would be more real-time to make sure less users downloaded the package with errors or unexpected results.

Thank you.

**Comment by julieqiu** [comment]
Removed these packages.

Because our data is downloaded from the Go Module Mirror, we will not delete a package even if the repository is deleted. 

From the https://proxy.golang.org FAQ:
> **I removed a bad release from my repository but it still appears in the mirror, what should I do?**
>
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

Given that, If you have a design proposal for these suggestions though, please feel free to [file a new issue](http://golang.org/s/pkgsite-feedback).
