### ISSUE TITLE
x/pkgsite:https://pkg.go.dev/github.com/dgoffredo/go-batch/batch

### ISSUE THREAD

**Issue by dgoffredo** [golang/go#41661]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/dgoffredo/go-batch/batch 
 
 
### What is your user agent?
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
 
### Screenshot
![Screenshot from 2020-09-27 15-42-09](https://user-images.githubusercontent.com/5205367/94374125-28a88200-00d8-11eb-9cff-82a928a66770.png)

  
### What did you do?
I searched for my recently-created Go package, and the website says that my project does not have one of the whitelisted licenses. I then changed the license (from SQLite to Unlicense), and waited a while (caches, I figure) before refreshing on multiple browsers. pkg.go.dev still doesn't like the license. You can see that my project uses the Unlicense here: <https://github.com/dgoffredo/go-batch/blob/master/LICENSE.md>.
 
 
 
### What did you expect to see?
I expected to see a rendering of my projects documentation, as is currently shown on the older website <https://godoc.org/github.com/dgoffredo/go-batch/batch>.
 
 
### What did you see instead?
I saw the aforementioned license restriction message.

**Comment by jamalc** [comment]
Your module is not valid because its path is incorrectly declared in your [go.mod](https://github.com/dgoffredo/go-batch/blob/master/go.mod#L1) file. The [about page](https://go.dev/about#adding-a-package) has more information on adding a package to pkg.go.dev. You can see details when you attempt to download your module from the module proxy with the steps listed.

```
❯ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/dgoffredo/go-batch
go: github.com/dgoffredo/go-batch upgrade => v0.0.0-20200927192038-4d50eff3369e
go get: github.com/dgoffredo/go-batch@v0.0.0-20200927192038-4d50eff3369e: parsing go.mod:
	module declares its path as: github.com/dgoffredo/go-batch/batch
	        but was required as: github.com/dgoffredo/go-batch
```

Once you've updated the go.mod file `go get` the new version through the module proxy. After a few minutes the documentation should be visible on pkg.go.dev.

**Comment by dgoffredo** [comment]
Following your instructions resolved the issue, thank you.
