### ISSUE TITLE
Equivalent to Rust's rlib

### ISSUE THREAD

**Issue by mcandre** [golang/go#41739]
Please provide a Go library format for portable plugins, similar to how Rust's rlib system works. So that developers need not manage a slew of build bots in order to support Go plugins for a diverse array of target environments.

**Comment by andybons** [comment]
Please flesh this out more properly per https://golang.org/s/proposal

**Comment by mvdan** [comment]
Also, please don't file issues like this one [if you're not going to provide the necessary information](https://github.com/golang/go/issues?q=+is%3Aissue+author%3Amcandre+label%3Awaitingforinfo) when asked. I'm tempted to just close this issue immediately, because I know from experience you're not going to reply.

**Comment by mvdan** [comment]
As expected, no reply. Closing.
