### ISSUE TITLE
cmd/go: `go list` add position in go.mod file in the `Module` struct

### ISSUE THREAD

**Issue by Trane9991** [golang/go#41879]
Would be nice to have line number in the `go.mod` file in the `go list --json` of module entry in the `Module` struct output:

https://github.com/golang/go/blob/2be7788f8383c2330cd96db53273e2995d4468f8/src/cmd/go/internal/list/list.go#L207-L221

# Use case

I want to implement the CI check with annotated Pull Request about outdated dependencies (with help of [reviewdog](https://github.com/reviewdog/reviewdog)).
Similar to what `gopls` does in the `upgradeLens` function here: 

https://github.com/golang/tools/blob/96877f285f7e9048cc5e405a8c798ecf58e84f90/internal/lsp/mod/code_lens.go#L59-L66

Screen Shot from VS Code:
![Screen Shot from VS Code](https://user-images.githubusercontent.com/9948629/95570637-dea49200-0a2f-11eb-9747-c61aadf3c913.png)

# Current behavior
I can get the dependencies to update with following command:
```sh
$ go list -u -f '{{if and (.Update) (not .Indirect)}}{{.}}{{end}}' -m all
github.com/alicebob/miniredis/v2 v2.13.2 [v2.13.3]
github.com/aws/aws-sdk-go v1.34.31 [v1.35.6]
github.com/mediocregopher/radix/v3 v3.5.2 [v3.6.0]
github.com/sirupsen/logrus v1.6.0 [v1.7.0]
```

However, it is missing the position in the `go.mod` file to be able to annotate in the PR.

I tried to build the bash one-liner and the closest I could get is following:
```sh
$ grep -EnHo $(go list -u -f '{{if and (.Update) (not .Indirect)}}{{.Path}}{{end}}' -m all | tr '\n' '|' | rev | cut -c 2- | rev) go.mod 
go.mod:17:github.com/alicebob/miniredis/v2
go.mod:21:github.com/aws/aws-sdk-go
go.mod:48:github.com/mediocregopher/radix/v3
go.mod:52:github.com/sirupsen/logrus
```

Problem with the above command:
- doesn't contain the latest version to upgrade to
- non-obviois
- ugly

I could write a helper tool to get this data for me, however, this looks like a good place to add this data.

**Comment by jayconrod** [comment]
cc @bcmills @matloob

The line number in which file? If you mean `go.mod` in the main module, it usually only lists direct dependencies, not everything shown by `go list -m all`. I don't think the `Module` struct would be the right place.

In general, I don't think we should add positional information. `go list` doesn't provide positional information for anything except errors. Rather than expanding the scope of `go list`, it would be better for custom tools to parse `go.mod` directly using `golang.org/x/mod/modfile`.

**Comment by Trane9991** [comment]
> The line number in which file? If you mean go.mod in the main module, it usually only lists direct dependencies, not everything shown by go list -m all. I don't think the Module struct would be the right place

Yeah, I meant the main `go.mod`. Because usually when you upgrade dependencies, you upgrade the direct dependencies while updating direct dependency will recursively update the direct dependency of your dependency, etc.

> The line number in which file?

Since we already have the `GoMod     string       // path to go.mod file used when loading this module, if any` I would say the line the file `GoMod` pointing to.

> Rather than expanding the scope of go list, it would be better for custom tools to parse go.mod directly using golang.org/x/mod/modfile.

Thanks for sharing the `golang.org/x/mod/modfile` I didn't know about that package.

**Comment by jayconrod** [comment]
`GoMod` in that struct is the path to the `go.mod` file that defines that module; each module has its own `go.mod`.

A single module version could be required from multiple places in the module graph. That's part of the reason I don't think it would be meaningful to add a position there.

I'll close this, since I think `golang.org/x/mod/modfile` is the right tool for the job here. `gopls` [uses that](https://github.com/golang/tools/blob/96877f285f7e9048cc5e405a8c798ecf58e84f90/internal/lsp/mod/code_lens.go#L159), too.

**Comment by Trane9991** [comment]
> GoMod in that struct is the path to the go.mod file that defines that module
But if we have path to the "go.mod file that defines that module" we could have a line in that file as well.

**Comment by jayconrod** [comment]
What line though? How would it be used?

**Comment by Trane9991** [comment]
> What line though? How would it be used?

Ok, I think I misunderstood the path to which `go.mod` it references.
Now I see your point and you are right, this will be not the right place to add this data.

Thanks for your explanations!
