### ISSUE TITLE
proposal: Go 2: add optional types

### ISSUE THREAD

**Issue by yazver** [golang/go#41992]
Add optional types:

```go
func (v *Value) Convert(to string?, from string?) {
    if from, ok := to?; ok {
        v.Value = from // *from
    }
    ...
}

v.Convert(from: "some value")
```

**Comment by ALTree** [comment]
This would be a fairly major language change, and this issue doesn't have enough details (not even remotely) in it. Major changes to how the language work need to come with a *detailed*, *comprehensive* discussion of the proposed change.

Here's the proposals template: https://github.com/golang/proposal/blob/master/design/TEMPLATE.md

If you're interested, you may want to fill that out *in detail*. Feel free to open a new issue when you're done. I'm closing here since we don't really use the Issue Tracker as a dumping ground for barely-sketched out ideas. Thanks!
