### ISSUE TITLE
x/build/cmd/coordinator: SlowBot requests are sometimes not recognized (seemingly when re-requested on same patch set)

### ISSUE THREAD

**Issue by bcmills** [golang/go#42084]
On https://golang.org/cl/263357, I repeatedly tried to trigger a `nocgo` SlowBot, and repeatedly failed to do so. (See the comment log there for details.)

I had thought that any builder at all could be triggered via a `TRY=` line, but now I'm not so sure. At the very least, it appears that the SlowBot configuration is missing a `nocgo` shorthand entry.

CC @golang/release

**Comment by dmitshur** [comment]
I've looked over relevant code and wasn't able to spot a problem that would explain this. The linux-amd64-nocgo builder should be available as a SlowBot, like all other builders. It's possible I missed something, or maybe the problem is something subtle and rare (for example, maybe maintner corpus was behind, and the code that handles that edge-case has a problem).

From looking over CL 263357's more recent history, I see that the linux-amd64-nocgo slowbot was eventually picked up, which confirms this was an intermittent problem.

We can keep this issue open to track similar occurrences, should they happen again, and investigate further.

Adding a nocgo → linux-amd64-nocgo alias sounds reasonable. I've broken it out into #42105.

**Comment by laboger** [comment]
For ppc64 and variants the experience I've had is that even if a newer TRY alias list is requested, it will sometimes run the initial list specified for the CL. An example is in the second TRY list in https://go-review.googlesource.com/c/go/+/266202. 

Another problem is that if an alias is mentioned in the TRY list which doesn't match anything, there is no message telling you that.

**Comment by dmitshur** [comment]
Some experimenting in CL 266202 suggests there's a good chance there is a problem with determining the "latest" TRY= request on the same patch set. So an (unpleasant) workaround until this issue is resolved is to make a new patch set when needing to make a different request.

**Comment by dmitshur** [comment]
I suspect the fix may be as short as described in my previous comment. CL 324763 is a recent occurrence and a good test case.
