### ISSUE TITLE
x/pkgsite: add a package to pkg.go.dev failed, while godoc.org works fine 

### ISSUE THREAD

**Issue by hujun-open** [golang/go#42106]
### What is the URL of the page with the issue?
 
github.com/hujun-open/zouppp/
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

 
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/10714828/96665545-fd493980-1309-11eb-89b5-9b2051c5a95c.png)

 
 
### What did you do?
try to add  github.com/hujun-open/zouppp, but failed, got msg says not a valid pkg, but meanwhile godoc.org works fine: https://godoc.org/github.com/hujun-open/zouppp

 
 
 
### What did you expect to see?
 
 pkg gets added
 
### What did you see instead?

add failed, the website says not valid pkg

**Comment by julieqiu** [comment]
It looks like the module path was fixed in https://github.com/hujun-open/zouppp/commit/682d339c053352cd76a235721681c6a0d99ab28d, so this is no longer an issue.

https://pkg.go.dev/github.com/hujun-open/zouppp now returns this page for me:

![image](https://user-images.githubusercontent.com/5943521/96792255-0698db80-13c8-11eb-8c74-7773ff82e42a.png)

**Comment by hujun-open** [comment]
Great, thanks
