### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by Toberd** [golang/go#42336]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/inexio/thola
 
### What did you expect to see?
 
 Documentation of the GitHub.com/inexio/thola project.
 
### What did you see instead?

Not Found. We renamed the project from `thola` to `GitHub.com/inexio/thola`. Can you please renew the request of the project?

Thanks!

**Comment by jba** [comment]
As far as I can tell, everything is working as intended.

https://pkg.go.dev/github.com/inexio/thola is present and the Overview page shows the readme. There is no doc because that package consists of a single file, `main.go`, that has no godoc.

If you look at sub-packages, you will see the doc. For example,  https://pkg.go.dev/github.com/inexio/thola@v0.1.1/doc.

If you intended `doc/docs.go` to apply to the top-level package, move it up to that directory and change the package clause to `package main`. Godoc does not recognize a special `doc` directory or a special package named `doc`.
