### ISSUE TITLE
encoding/base64: URLEncoding padding is optional

### ISSUE THREAD

**Issue by gjemiller** [golang/go#4237]
<pre>It appears that under certain circumstances, padding characters are not needed in a
valid base64 encoding.  Specifically, when using the &quot;url encoding&quot; they are
optional.  This presents a problem when trying to decode base64 code from a third party
that omits them.

What steps will reproduce the problem?
<a href="http://play.golang.org/p/RWV_Nd34wr">http://play.golang.org/p/RWV_Nd34wr</a>

// reproduced here:
package main

import (
    &quot;bytes&quot;
    &quot;encoding/base64&quot;
    &quot;fmt&quot;
    &quot;io&quot;
    &quot;os&quot;
)

func main() {
    decode(&quot;c3VyZS4=&quot;)    // example from wikipedia
    decode(&quot;c3VyZS4&quot;) // should be the same without padding
}

func decode(s string) {
    dec := base64.NewDecoder(base64.URLEncoding, bytes.NewBufferString(s))
    n, err := io.Copy(os.Stdout, dec)
    fmt.Printf(&quot;\n%d %v\n&quot;, n, err)
}

What is the expected output?
sure.
5 &lt;nil&gt;
sure.
5 &lt;nil&gt;

What do you see instead?
sure.
5 &lt;nil&gt;
sur
3 &lt;nil&gt;</pre>

**Comment by kennygrant** [comment]
Perhaps this issue can be closed now? 

The base64 pkg has changed a bit since it was filed. Specifically with this change in 2014:

https://github.com/golang/go/commit/2e0a1a7573bd69c18c3a3932422a9507031e5321

RawURLEncoding can be used if you wish to decode data which uses no padding, so for the example given above, to avoid errors you can just use the appropriate raw encoding:

https://play.golang.org/p/skWYiMHk3j

**Comment by bradfitz** [comment]
@kennygrant, thanks! Closing.
