### ISSUE TITLE
cmd/link: -gcflags=-race causes panic

### ISSUE THREAD

**Issue by cuonglm** [golang/go#42396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +3ef8562c9c Thu Nov 5 02:48:05 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
$ cd "$(go1.15.3 env GOROOT)/src/strings"
$ go1.15.3 test -gcflags=-race .
```

### What did you expect to see?

Friendly error messages like go1.14.x does:

```
# strings.test
type..eq.[6]string: relocation target runtime.racefuncenter not defined
type..eq.[6]string: relocation target runtime.raceread not defined
type..eq.[6]string: relocation target runtime.racefuncexit not defined
type..eq.[2]string: relocation target runtime.racefuncenter not defined
type..eq.[2]string: relocation target runtime.raceread not defined
type..eq.[2]string: relocation target runtime.racefuncexit not defined
type..eq.[3]string: relocation target runtime.racefuncenter not defined
type..eq.[3]string: relocation target runtime.raceread not defined
type..eq.[3]string: relocation target runtime.racefuncexit not defined
type..eq.[4]string: relocation target runtime.racefuncenter not defined
type..eq.[4]string: relocation target runtime.raceread not defined
type..eq.[4]string: relocation target runtime.racefuncexit not defined
type..eq.[10]string: relocation target runtime.racefuncenter not defined
type..eq.[10]string: relocation target runtime.raceread not defined
type..eq.[10]string: relocation target runtime.racefuncexit not defined
type..eq.[8]string: relocation target runtime.racefuncenter not defined
type..eq.[8]string: relocation target runtime.raceread not defined
type..eq.[8]string: relocation target runtime.racefuncexit not defined
strings.(*Builder).String: relocation target runtime.racefuncenter not defined
strings.(*Builder).String: relocation target runtime.raceread not defined
strings.(*Builder).String: relocation target runtime.racefuncexit not defined
/home/cuonglm/sdk/go1.14.10/pkg/tool/linux_amd64/link: too many errors
FAIL	strings [build failed]
FAIL
```

### What did you see instead?

Panic on go1.15.x and tip:

```
# strings.test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51dbbb]

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).FuncInfo(0xc00061c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/cmd/link/internal/loader/loader.go:1900 +0x9b
cmd/link/internal/ld.(*stkChk).check(0xc000138e78, 0xc000138d08, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:2359 +0x130
cmd/link/internal/ld.(*stkChk).check(0xc000138e78, 0xc000138e60, 0x0, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:2418 +0x585
cmd/link/internal/ld.(*Link).dostkcheck(0xc000115880)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:2319 +0x2bc
cmd/link/internal/ld.Main(0x86f840, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x6da8bf, 0x1b, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:254 +0xe65
main.main()
	/usr/local/go/src/cmd/link/main.go:68 +0x1dc
FAIL	strings [build failed]
FAIL
```

**Comment by mvdan** [comment]
Out of curiosity, why do you use `-gcflags=-race` instead of just `-race`?

**Comment by thanm** [comment]
I can take a look at this.

**Comment by cuonglm** [comment]
> Out of curiosity, why do you use `-gcflags=-race` instead of just `-race`?

Actually, what I did it `-gcflags=-l -race`, then I want to remove `-gcflags=-l`, but mis-typing enter :)

**Comment by thanm** [comment]
Just FYI, with the fix I submitted to the linker, we no longer get the panic. The error message is slightly different from before however. Instead of "relocation target runtime.racefuncexit not defined" it will be an error of the form "reference to undefined builtin 'runtime.racefuncexit' from package <something>". Hope that is ok.

**Comment by jayconrod** [comment]
@katiehockman and I ran into an error which I think might be caused by [CL 267881](https://golang.org/cl/267881). Specifically, we're trying to merge `master` into the `dev.fuzz` branch in [CL 275448](https://go-review.googlesource.com/c/go/+/275448). The failure we're seeing is https://storage.googleapis.com/go-build-log/cffd0112/linux-amd64_018f19d1.log.

* In `misc/cgo/testshared`, the `TestTestInstalledShared` test is failing.
* `TestMain` copies a number of packages into a temporary `GOROOT` and installs with `go install -buildmode=shared runtime sync/atomic`. That writes `pkg/linux_amd64_dynlink/libruntime,sync-atomic.so`.
* `TestTestInstalledShared` runs `go test -linkshared sync/atomic`, which fails with:

```
reference to undefined builtin "runtime.morestack_noctxt" from package "crypto/sha256"
```

* In this CL, `crypto/sha256` is imported indirectly by the test main generated by `go test`. So the presence of that package isn't surprising.
* I've verified `runtime.morestack_noctxt` is present in `pkg/linux_amd64_dynlink/libruntime,sync-atomic.so`.

@thanm Any idea why this is happening? If it's helpful, I can try to make a more minimal test case in a new issue.

**Comment by thanm** [comment]
This looks like a slightly different problem from the original bug, I think it might make sense to file another issue.  The CL in question is mainly there to convert a linker panic into a regular link error, whereas in this case it looks as though it should be possible for the link to succeed. I can pull your CL and try taking a closer look at it.

**Comment by thanm** [comment]
New issue filed with smaller repro: https://github.com/golang/go/issues/43107
