### ISSUE TITLE
x/pkgsite: allow hiding of left menu

### ISSUE THREAD

**Issue by v-byte-cpu** [golang/go#42487]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/net/http
 
### What did you expect to see?

Please, allow hiding of the left menu. It is really inconvenient to read docs on half screen..

### Screenshot
 
![image](https://user-images.githubusercontent.com/65545655/98707530-33219100-2391-11eb-9345-5d96c643a258.png)

**Comment by woat** [comment]
It looks like there are CSS rules to automatically close the menu (rather, open the menu since mobile is default), I think this is the relevant breakpoint: https://github.com/golang/pkgsite/blob/master/content/static/css/sidenav.css#L97

My guess is that your half-screen size is probably not small enough to trigger the breakpoint. Might be worth mentioning your screen size + resolution.

So far, the paths I see is that the breakpoint could be adjusted or a toggle be implemented. I'd be happy to help with this issue once a resolution has been made.

**Comment by v-byte-cpu** [comment]
Outer window size:

```
console.log(`${window.outerWidth}x${window.outerHeight}`)
==> 1366x768
```

Inner window size:

```
console.log(`${window.innerWidth}x${window.innerHeight}`)
==> 1238x277
```
I usually use chromium on my laptop with 110% and 125% zoom levels and it is very irritating to scroll code snippets..

110% zoom level:

![image](https://user-images.githubusercontent.com/65545655/98741589-fae47780-23bd-11eb-996e-df7b8316c874.png)

125% zoom level:

![image](https://user-images.githubusercontent.com/65545655/98741719-32ebba80-23be-11eb-9620-dc85d6d61972.png)

 
Toggle is a great idea !

**Comment by julieqiu** [comment]
Thanks for the feedback! 

/cc @georgehu @Joanne881107 @fflewddur for UX input

**Comment by fflewddur** [comment]
I think supporting a user option to hide the left-hand menu is a good idea. That menu is designed to support faster navigation when screen size permits, but if our heuristic isn't 100% accurate, a user-controlled fallback makes sense. 

One additional option to consider is whether we'd be able to detect overflow in the code blocks and automatically hide/minimize the nav menu when that happens (assuming we can also add line breaks to abnormally long lines, otherwise some packages might always have this menu hidden).

**Comment by thomasf** [comment]
And the right hand bar as well please, before godoc.org goes away bu I'll guess I can add some browser extension to force it if it doesn't. The choice should be persistent by saving a a cookie or something.

These are some differences how the two sites looks for me and one of them is quite horible when browsing/reading.

![image](https://user-images.githubusercontent.com/330847/103090943-e61d1580-45f2-11eb-9193-c35ac31e6538.png)

![image](https://user-images.githubusercontent.com/330847/103090832-8fafd700-45f2-11eb-8607-737260654e29.png)

It looks like the godoc.org only has a fixed max width for it's content and pkg.go.dev also has that but the side menus are prioritized over it. 

Maybe it would be a good idea for the user to be able to choose that as the width threshold where the left and right hand stuff goes away? I don't know what the solution is but as it works now it's not even a remotely comfortable reading experience for me .

**Comment by jamalc** [comment]
We are testing out layout changes on the beta site related to this issue. Although the current set of changes do not provide an option to hide the left nav, at 1366x768 with 110% zoom the page should render in the single column layout. Take a look at https://beta.pkg.go.dev/net/http.

**Comment by jamalc** [comment]
Layout changes are live on pkg.go.dev. I think we can close this for now. Let's start a new issue on layout change feedback if new issues crop up.
