### ISSUE TITLE
x/blog: (Too?) Few links to go.dev from golang.org

### ISSUE THREAD

**Issue by maxekman** [golang/go#42492]
### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Visited golang.org.

### What did you expect to see?

Links on the front page to go.dev and/or pkg.go.dev.

### What did you see instead?

No links, I really tried to find some. Not even in the blog post announcing the overhaul of pkg.go.dev, at least what I could see.

**Comment by ALTree** [comment]
I agree the first time  pkg.go.dev is mentioned in https://blog.golang.org/pkgsite-redesign (3rd word of the first sentence) should probably be a link to it. It's less clear where (if) it should be mentioned on golang.org.

cc @julieqiu

**Comment by ALTree** [comment]
Oh and below there's a bad html tag:

```
The main change is that the pkg.go.dev/<path> 
```

**Comment by julieqiu** [comment]
Thanks for the suggestion! 

> I agree the first time pkg.go.dev is mentioned in https://blog.golang.org/pkgsite-redesign (3rd word of the first sentence) should probably be a link to it.

Agreed - I'll add a link to pkg.go.dev in the first reference in the article as well as some captions for the images with links.

>  Oh and in the blog post, below, there's a bad html tag:
> The main change is that the pkg.go.dev/<path> 

I think that is intentional - see also https://github.com/golang/go/issues/41586, which refers to that page as the "pkg.go.dev/<path> page". @ALTree let me know if I am missing something.

> Links on the front page to go.dev and/or pkg.go.dev.

I think this is a separate issue that isn't related to https://blog.golang.org/pkgsite-redesign, so I'll leave this issue open for that suggestion.

**Comment by ALTree** [comment]
> I think that is intentional - see also #41586, which refers to that page as the "pkg.go.dev/ page". @ALTree let me know if I am missing something.

Oh, I see, you're using `/<path>` as a placeholder... I thought it was a misplaced xml tag, sorry for the confusion.

**Comment by julieqiu** [comment]
No problem, thanks for clarifying!

**Comment by seankhliao** [comment]
with everything merged into go.dev, this seems to be no longer relevant
