### ISSUE TITLE
x/sys/windows/svc: example service fails to start

### ISSUE THREAD

**Issue by aapi-rp** [golang/go#42596]
### What version of Go are you using (`go version`)?

<pre>
$ 1.14.7

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ Windows 10 64bit

</pre></details>

### What did you do?

I ran the example as built via the terminal, example can be found here: https://github.com/golang/sys/tree/0a15ea8d9b02651b828a1b41989a6af25c24cb64/windows/svc/example

Commands run:
"go run main.go install"  This command worked, it installed the service
"go run main.go start" This command failed with "failed to start myservice: could not start service: The system cannot find the file specified"

### What did you expect to see?

I expected the service to actually work, and show in the services menu.

### What did you see instead?

"failed to start myservice: could not start service: The system cannot find the file specified"

**Comment by networkimprov** [comment]
cc @alexbrainman @mattn 

@gopherbot add OS-Windows

**Comment by alexbrainman** [comment]
> Commands run:
> "go run main.go install" This command worked, it installed the service

Not true.

The way Windows service is installed is by calling CreateService Windows API

https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-createservicew

And that API requires you to provide full path to your service executable (see lpBinaryPathName parameter). And, once installed, the service executable cannot be moved (until service is deleted), because Windows will try to run it when you request Windows to start your service.

When you use `go run ...` command, your executable is built inside of TEMP directory, executed and gets deleted immediately. So when you run `go run main.go start` your service executable is gone. That is why Windows is complaining.

Do not use `go run ...` command with this example. Build executable instead. Copy built executable to a location where it could remain until you remove your service.

Alex

**Comment by cagedmantis** [comment]
This issue has received a sufficient response from @alexbrainman. Please re-open the issue if you believe it's been close in error.
