### ISSUE TITLE
x/term: Fails to build with golang < 1.12

### ISSUE THREAD

**Issue by aclindsa** [golang/go#42665]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It fails with the latest release of x/term and an older version of the go compiler, but *not* with the latest of both.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.11.13.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.11.13.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build186938083=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Attempted to build [ofxgo](https://github.com/aclindsa/ofxgo) on travis using go 1.11.

### What did you expect to see?

<pre>
golang.org/x/term
</pre>

### What did you see instead?

<pre>
golang.org/x/term
# golang.org/x/term
../../../golang.org/x/term/term_unix_linux.go:9:7: ioctlReadTermios redeclared in this block
	previous declaration at ../../../golang.org/x/term/term_unix_aix.go:9:26
../../../golang.org/x/term/term_unix_linux.go:10:7: ioctlWriteTermios redeclared in this block
	previous declaration at ../../../golang.org/x/term/term_unix_aix.go:10:27
</pre>
https://travis-ci.com/github/aclindsa/ofxgo/jobs/441671582

**Comment by FiloSottile** [comment]
Go 1.11 is not supported anymore (the earliest supported version is Go 1.14 at the moment), so it's to be expected that _new versions_ of some modules will not build with it. (In this case, I think it's because Go 1.11 does not recognize the `aix` build tag.)

Due to how Minimum Version Selection works, the version of a dependency in use by a module is stable and will never update itself: you can continue to build the same code with an old version of the compiler forever. However, if you want to update a dependency you need to be prepared to update the compiler as well.

In general, Go 1.11 is lacking multiple security fixes that have been published over the last year, so I can't recommend running Go 1.11 at all. Remember that Go provides a strong backwards compatibility promise in order to make updates easier.
