### ISSUE TITLE
x/build: dragonfly-amd64-master builder is offline

### ISSUE THREAD

**Issue by tklauser** [golang/go#42719]
Noticed that a SlowBot run on https://golang.org/cl/271177 has been waiting for several hours for this builder. It is currently reported on https://farmer.golang.org as missing:

```
host-dragonfly-amd64-master: 0/0 (1 missing)
```

/cc @cagedmantis @dmitshur @toothrot @tuxillo

**Comment by tuxillo** [comment]
Thanks for notifying @tklauser , how can I know when one of the builders is down? Any notification mechanism?

the master builder is failing more than expected lately, not sure why yet.

**Comment by dmitshur** [comment]
Thanks for bringing the builder back online.

At this time, we don't have a notification mechanism beyond someone spotting that a builder is missing by looking at [build.golang.org](https://build.golang.org) or via a SlowBot request, and then filing an issue about it. (Issue #14603 is about improving this.)

Since the `dragonfly-amd64-master` builder is restored now, I think we can close this issue, and open new ones about the failures it is detecting as needed.
