### ISSUE TITLE
dev.go2go: translator generates incorrect code for type switches, leading to duplicate cases

### ISSUE THREAD

**Issue by tdakkota** [golang/go#42758]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +165ceb09f9 Tue Nov 3 12:31:40 2020 -0500 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
- windows/amd64
- go2go playground 

### What did you do?
https://go2goplay.golang.org/p/dTkkesE4GCX.
Error is printing when go1 compiler tries to compile translated code.
Also I ran on `dev.typeparams` 
```
go tool compile -G ./issue.go
```
where `issue.go` is code from playground

Here instantiated `createRequest[io.Writer]` look something like:
```go
func createRequest_ioWriter(w io.Writer) {
	switch (interface{})(w).(type) {
	case io.Writer:
		fmt.Println("W")
	case io.Writer:
		fmt.Println("io.Writer")
	}

}
``` 
### What did you expect to see
An error from go2go like `type parameter cannot be case of type switch`.

### What did you see instead?
Code passes go2go and `dev.typeparams` type checker.

**Comment by tdakkota** [comment]
CC @griesemer

**Comment by griesemer** [comment]
The typeparams draft doesn't disallow type parameters in type switch cases (or type assertions for that matter). A type parameter is a type like any other, so it's not obvious that this should be prohibited.

At the moment I consider this a limitation of the source-to-source translator (prototype).

**Comment by ianlancetaylor** [comment]
I agree, but I don't plan to do any more work on this experimental tool.  If anybody else wants to send a fix, that would be fine.

**Comment by griesemer** [comment]
Just for the record: The CLs above don't address this issue - they only clean up related handling of type parameters in type switches (which are carried forward into the dev.typeparams branch).

**Comment by tdakkota** [comment]
> The typeparams draft doesn't disallow type parameters in type switch cases (or type assertions for that matter). A type parameter is a type like any other, so it's not obvious that this should be prohibited.

 I didn't fully understand,
```go
var t io.Writer
switch t.(type) {
case io.Writer:
   return
case W:
    panic("W")
}
```
what behavior is expected when `W` is `io.Writer`?

**Comment by ianlancetaylor** [comment]
The first case should be chosen, and the function should `return`.

We recently updated the design draft for this. See https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#generic-types-as-type-switch-cases .

**Comment by mdempsky** [comment]
Relatedly, naive type parameter substitution can result in duplicate constants in value switch statements and map literals: https://go2goplay.golang.org/p/fB_3R56ivQE I know cmd/go2go isn't likely to be updated to address these issues, so I'm commenting this more for posterity.

I think it may be worthwhile to keep a doc with implementation notes about cases like these to beware of when implementing generics, esp. adding generics to an existing implementation. E.g., unified IR currently has these same issues, because it works somewhat similarly to cmd/go2go (naive type substitution during the frontend, and then handing off the rewritten AST to an existing compiler backend; just it doesn't have to deal with the limitations of using Go source as an intermediate representation). I knew to expect these limitations (and that the backend would eventually need some additional features), but it could save future implementers some trouble to document them up front.
