### ISSUE TITLE
[Feature]extend stardard errors.New() struct field

### ISSUE THREAD

**Issue by li1234yun** [golang/go#43016]
### What version of Go are you using (`go version`)?

<pre>
go1.15.4

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

extend standard `errors` package to include more detail info field to make it more useful.

### What did you expect to see?

Maybe consider the following code, it just a suggestion.

```go
/*
Custom Error Handle
*/
package errs

import "fmt"

// Custom Error for convenience extend
type customError struct {
	// Error message as error category string
	Message string
	// Error detail description
	Detail string
	// Wrapped error
	Err error
}

// error interface achieve
func (e *customError) Error() string {
	if e.Detail != "" {
		return fmt.Sprintf("%s: %s", e.Message, e.Detail)
	} else if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Message, e.Err)
	} else {
		return e.Message
	}
}

// Wrap an error
func (e *customError) WrapE(err error) error {
	e.Err = err
	return e
}

// Wrap string
func (e *customError) WrapS(detail string) error {
	e.Detail = detail
	return e
}

// New custom error
func New(msg string) *customError {
	return &customError{
		Message: msg,
	}
}

// Wrap an error with new detail
func Wrap(e error, msg string) *customError {
	return &customError{
		Message: msg,
		Err:     e,
	}
}

```

When I handle error, I can define some error category firstly, then I can extend error info. 

```go

const CustomError = errs.New("custom error")

func t() error {
    ...

    return CustomError.WrapS("line 3 error")
}
```

### What did you see instead?

Reference only.

**Comment by ianlancetaylor** [comment]
A lot of people have looked at this kind of issue, and there is no clear consensus on what should be done in this area.  So rather than try to provide this in a standard errors package, Go provides the tools that you need to implement it yourself.  Or you can use a package like https://pkg.go.dev/github.com/pkg/errors.

Closing because as is this issue isn't going to lead to any changes.  Please comment if you disagree.  If you want to make changes here, the first step is to build a consensus.
