### ISSUE TITLE
x/crypto/nacl/box: Precompute calls deprecated function

### ISSUE THREAD

**Issue by kevinburke** [golang/go#43148]
box.Precompute is:

```go
// Precompute calculates the shared key between peersPublicKey and privateKey
// and writes it to sharedKey. The shared key can be used with
// OpenAfterPrecomputation and SealAfterPrecomputation to speed up processing
// when using the same pair of keys repeatedly.
func Precompute(sharedKey, peersPublicKey, privateKey *[32]byte) {
	curve25519.ScalarMult(sharedKey, privateKey, peersPublicKey)
	salsa.HSalsa20(sharedKey, &zeros, sharedKey, &salsa.Sigma)
}
```

However, `curve25519.ScalarMult` is deprecated, with the following notice.

```go
// ScalarMult sets dst to the product scalar * point.
//
// Deprecated: when provided a low-order point, ScalarMult will set dst to all
// zeroes, irrespective of the scalar. Instead, use the X25519 function, which
// will return an error.
func ScalarMult(dst, scalar, point *[32]byte) {
	scalarMult(dst, scalar, point)
}
```

A replacement would be, roughly (some casts omitted):

```go
// Precompute calculates the shared key between peersPublicKey and privateKey
// and writes it to sharedKey. The shared key can be used with
// OpenAfterPrecomputation and SealAfterPrecomputation to speed up processing
// when using the same pair of keys repeatedly.
func Precompute(sharedKey, peersPublicKey, privateKey *[32]byte) {
	sharedKey, err := curve25519.X25519(privateKey, peersPublicKey)
        if err != nil {
            // ????
        }
	salsa.HSalsa20(sharedKey, &zeros, sharedKey, &salsa.Sigma)
}
```

My question is what should happen if err != nil? It seems bad that we would let callers use insecure things without noticing it. It also seems bad that a function that did not previously panic is now panicking. 

One option would be e.g.

```go
var InsecureAllowLowOrderPoints = false
```

at the package level; if that is set to false, we panic when we get a bad point, if set to true, we follow the old behavior.

I will be honest that I don't understand the security aspect of this that well - how likely it is to pass a low-order point into the function, and the severity with which bad data should be treated.

**Comment by kevinburke** [comment]
cc @FiloSottile since it appears you wrote the deprecation notice in the first place.

**Comment by kevinburke** [comment]
Another option would be to preserve the current behavior as `InsecurePrecompute` or something and change `Precompute` to return an error, or add a new `PrecomputeStrict(sharedKey, peersPublicKey, privateKey *[32]byte) error` function and related `SealStrict`, and `OpenStrict` functions.

**Comment by kevinburke** [comment]
Alternatively, we could add new helpers - in my library I've named these `EasySeal` and `EasyOpen` - that generate a cryptographically secure nonce for you and prepend it to the message, that probably represent 95% of cases. These methods could expose the returned error and we could avoid changing the old methods at all. 

https://godoc.org/github.com/kevinburke/nacl/box#EasySeal

**Comment by FiloSottile** [comment]
Low order points can be a problem depending on the application. The curve25519 package errs on the side of safety, but nacl/box is fine letting those outputs go to zero. I remember doing the analysis when I did the deprecation but it's good to document it: the low order point here would be the peer's public key, and it would force the shared key to zero, discarding the private key contribution; this is fine because if an attacker controls the public key they can simply decrypt the message by selecting a public key for which they know the private key.

For an example of when this is not fine, see the Tamarin attack in https://eprint.iacr.org/2019/526.pdf. Tamarin was using X25519 to derive both a key and a challenge value that they would then sign (instead of signing a full transcript). If the challenge went to zero, the signature on it could be replayed against anyone.

A quick note about EasySeal and EasyOpen: box has a design flaw in that it generates the same keys for a->b and b->a; randomly generating the nonce makes that impossible to mitigate that by using different nonces in each direction. You might want to consider offering an API that helps with that instead. You can read more [here](https://buttondown.email/cryptography-dispatches/archive/59c99d2e-9fd7-4859-934b-f52cf254e6b2).
