### ISSUE TITLE
x/tools/gopls: makes http requests to random websites while editing module directive

### ISSUE THREAD

**Issue by josharian** [golang/go#43187]
In an attempt to make a small reproducer for https://github.com/golang/go/issues/43186, I created a go.mod that started:

module vanilla.xyz

After saving, I selected the word vanilla and started typing "chocolate" as a replacement. As I typed, gopls started attempting to retrieve results from intermediate domains choco.xyz, chocola.xyz, chocolat.xyz, despite me not hitting save. Sample alert from Little Snitch:

<img width="573" alt="Screen Shot 2020-12-14 at 2 36 33 PM" src="https://user-images.githubusercontent.com/67496/102145443-11964800-3e1c-11eb-8022-4005546cc23b.png">
 
The partial module import path seemed to get cached, because well after I finished typing an hit save, I still got this error:

<img width="483" alt="Screen Shot 2020-12-14 at 2 37 22 PM" src="https://user-images.githubusercontent.com/67496/102145470-24a91800-3e1c-11eb-95cd-bd38f0066039.png">

**Comment by stamblerre** [comment]
`gopls` currently tries to reload package metadata as you modify import statements in your file, which is why you saw these requests. We have made some changes in recent weeks to default to GOPROXY=off--can you try the latest `gopls` pre-release and confirm that it fixes the issue? You can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.6.0-pre.1`.
