### ISSUE TITLE
runtime: corrected issue11656 test fails on ppc64 and mips

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#43283]
In https://golang.org/cl/278473 I corrected $GOROOT/test/fixedbugs/issue11656.go to actually test what it was trying to test: executing a trap instruction at a PC value larger than zero.  That fix caused the test to fail on:

* [ppc64](https://build.golang.org/log/95a3e0559dae136ffcdad42fe86578f2da8b68c8)
* [mips](https://build.golang.org/log/5c257183417d9cb19ddfe7a62bcd3764d58a4d28)
* [mips64](https://build.golang.org/log/13e3c819a8e0d8edf8308b568e64a3655a13e5a0)

In each case the test failed reporting `runtime: unknown pc`, which is more or less what the CL in #11656 was supposed to fix.

For now I'm going to skip the tests for these targets.

**Comment by laboger** [comment]
Why does this apply to ppc64 but not ppc64le?

**Comment by ianlancetaylor** [comment]
@laboger I don't know.  I haven't looked into it.

**Comment by cherrymui** [comment]
I _think_ what happens is that on machines that the test passes, it faults with SIGSEGV (or maybe SIGBUS) at the CALL instruction when it is jumping to `fn`, because that address is not executable. On machines that this fails, it actually jumped to `fn` and executed the trap instruction (somehow the kernel allowed to execute that address), and faulted with SIGTRAP, where it failed to unwind, because the PC doesn't match any function.

It might be possible to do something for better traceback, for example, if the PC is not in any known function, maybe use the LR? Assume the frame size is 0 and hope for the best? Not sure...

> Why does this apply to ppc64 but not ppc64le?

Perhaps the kernel on the AIX builder allows execution on that address whereas the Linux/PPC64LE builder doesn't.

**Comment by laboger** [comment]
I think the test only needs to be disabled on aix-ppc64, but it is disabled for aix-ppc64 and linux-ppc64. The failure log posted above is from aix-ppc64. Not a big deal, I just didn't understand why linux-ppc64 and linux-ppc64le would behave differently for this case.
