### ISSUE TITLE
x/tools/gopls: investigate regtest performance on linux-arm builder

### ISSUE THREAD

**Issue by findleyr** [golang/go#43355]
The gopls regtests are slow, particularly on openbsd and darwin due to (we believe) kernel locking behavior. For this reason we've excluded them when testing with `-short` on several builders where they regularly time out.

But they usually run relatively quickly on Linux, so it's surprising (to me at least) that they are timing out on the ~new~ linux-arm builder. This is probably worth investigating at some point.

**Comment by dmitshur** [comment]
Do you know about the regtest performance on the `linux-arm-aws` builder?

The `linux-arm` builder is not new, has a [known issue](https://github.com/golang/go/issues/35628) and is known to be slow (we disabled trybots because of [many problems](https://github.com/golang/build/blob/0a4bf693f6139da99647cdcccd3fd0b8a6fbfd70/dashboard/builders.go#L1911)). The `linux-arm-aws` builder is newer (#41867) and has more resources allocated, so you may get a better siginal about gopls behavior on linux/arm from it.

CC @cagedmantis.

**Comment by findleyr** [comment]
Ah I see, I probably only noticed the `linux-arm` failure due to recent awareness of other failures (particularly openbsd).

I can try out the `linux-arm-aws` builder in 2021.

**Comment by findleyr** [comment]
No issues on linux-arm-aws, so I think this is simply that the linux-arm builder is too small for gopls regtests.

Closing in favor of #32834.
