### ISSUE TITLE
text/template: improve documentation for creating templates

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4338]
by **Shifter1**:

<pre><a href="http://play.golang.org/p/YfvMjcI7b5">http://play.golang.org/p/YfvMjcI7b5</a>

Errors from that code are unhelpful, and the documentation for 
* <a href="http://golang.org/pkg/text/template/#New">http://golang.org/pkg/text/template/#New</a>
* <a href="http://golang.org/pkg/text/template/#Template.ParseFiles">http://golang.org/pkg/text/template/#Template.ParseFiles</a>

No mention is made in the docs that when using .New() and then .ParseFiles(), the
orginal temaplte's name needs to tbe the same as the base name of the first file.</pre>

**Comment by odeke-em** [comment]
Perhaps this issue was fixed by https://github.com/golang/go/commit/f2662f2c938f2f9fd21067169b2aaec89f8d0e9f ie CL https://go-review.googlesource.com/#/c/11329?

In particular the documentation after that CL says 
<img width="917" alt="screen shot 2016-07-10 at 2 35 38 am" src="https://cloud.githubusercontent.com/assets/4898263/16712843/274bbf16-4648-11e6-86ba-1033b097eb43.png">


The example provided in the issue is incomplete/unrunnable even locally, but I wonder if was meant for html/template instead since that's what referred to there. Although, html/template documentation says the same thing
<img width="1034" alt="screen shot 2016-07-10 at 2 46 27 am" src="https://cloud.githubusercontent.com/assets/4898263/16712846/87d3c824-4648-11e6-8db2-6e7de6a99532.png">

**Comment by adg** [comment]
Thanks for finding this @odeke-em. I think we can close it.
