### ISSUE TITLE
cmd/cgo: wrong value of exported variables in a DLL

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4339]
by **hwang.dev**:

<pre>What steps will reproduce the problem?
1. Create a DLL with an exported variable(which has been properly initialized within the
DLL).e.g. (the code is in the attachment)
In &quot;adll.h&quot;
    typedef struct {
        char *name;
        void (*bar)();
    } T;
   __declspec(dllexport) const T exported_var;

In &quot;adll.c&quot;
const T exported_var = {&quot;var&quot;, &amp;bar_impl};

2. Write a go program to access the variable:
   fmt.Println(C.exported_var, C.GoString(C.exported_var.name))
   C.foo(&amp;C.exported_var) // foo calls exported_var.bar

What is the expected output?
1. The correct value of C.exported_var can be obtained.
2. C.foo(&amp;C.exported_var) calls exported_var.bar without a problem.

Or

An error message that the use case cannot be supported.

What do you see instead?
1. It just compiles without an error message.
2. During run, wrong values got.
3. C.foo(&amp;C.exported_var) causes panic with message &quot;runtime error: invalid
memory address or nil pointer dereference&quot;.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Windows 7 64 bit

Which version are you using?  (run 'go version')
go1.0.3
C compiler: Mingw-w64/MSYS/gcc 4.7.1

Please provide any additional information below.
I've found a workaround that a wrapper written in C will be able to get the correct
variable value. e.g.

/*
const T* getVar() {
    return &amp;exported_var;
}
*/
import &quot;C&quot;

and then:
    fmt.Println(C.getVar(), C.GoString(C.getVar().name))</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/4339/0/dllvar.zip">dllvar.zip</a> (1326 bytes)

**Comment by varialus** [comment]
I think this is fixed in the current development branch. I was encountering this bug on Windows XP with Go 1.4.2 and my own DLL, but I built the master branch of Go today and I'm no longer getting the error. My build environment may be slightly different than the official Go build machines, so it's probably advisable to retest it yourself.

**Comment by minux** [comment]
It's very likely fixed by #4069.

@alexbrainman, we might want a test for this in misc/cgo/testso.

**Comment by alexbrainman** [comment]
This is now works (most likely fixed by #4069). Here https://go-review.googlesource.com/8523 is the test for it.

Alex

**Comment by mikioh** [comment]
https://go-review.googlesource.com/8523 was reverted.

**Comment by alexbrainman** [comment]
https://go-review.googlesource.com/#/c/8523/ contained test for issue #4339, not the fix. Issue #4339 was fixed by a series of CLs that fix issue #4069. We also have issue #10360 to keep track of progress fixing broken test https://go-review.googlesource.com/#/c/8523/ on darwin and netbsd. So I think this issue is resolved.

Alex
