### ISSUE TITLE
x/tools/gopls: include function literals as outgoing callhierarchy calls 

### ISSUE THREAD

**Issue by leitzler** [golang/go#43438]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +6d2b3351f6 Thu Dec 10 18:34:40 2020 +0000 darwin/amd64
x/tools: 929a8494
</pre>

### What did you do?
Called `callHierarchy/outgoingCalls` from `func fn()`:
```
package foo
func fn() { // Listing Outgoing calls at "fn" here returns none
	func() {
		fn2()
	}()
}
func fn2() {}
```
### What did you expect to see?
I expected to get one result; the function literal at the line below.
The main reason is for consistency, since calling `callHierarchy/incomingCalls` from `func fn2()` will return the function literal.

### What did you see instead?
No outgoing calls from `fn()`.

**Comment by KarthikNayak** [comment]
I'm interested to pick this up!

**Comment by KarthikNayak** [comment]
I did some investigation here and see that the problem lies here: 

https://github.com/golang/tools/blob/4061312594fc4c553ddda40109133239c66553b2/internal/lsp/source/call_hierarchy.go#L218-L234

We skip going into the child nodes when the type is `ast.FuncLit`. So potentially:
1. We could change the _default_ case to return true, that way even if that type is not marked as an outgoing function call, we still check it's children to see if there is an outgoing function call
2. We could add a case for `ast.FuncLit` which would return true. 

I prefer 1, but I'm not sure if there are implications which can arise due to this change. Please advice!
