### ISSUE TITLE
embed: FS root directory is always the package directory, while os.DirFS may have another root

### ISSUE THREAD

**Issue by alicebob** [golang/go#43431]
### What version of Go are you using (`go version`)?

<pre>
go version devel +2ff33f5e44 Thu Dec 17 16:03:19 2020 +0000 linux/amd64
</pre>

(that's 1.16beta1)

### Does this issue reproduce with the latest release?

yes

### What did you do?

I want to serve static documents in a webserver using the new `embed` package, but with an option to use local files.

https://play.golang.org/p/hyBgSUBUhf3

There is a subdir `./docroot/` with an index.html file:

```
myuser@mymachine:/tmp/root$ ls -R
.:
docroot/  go.mod  main.go  root

./docroot:
index.html
```

When I use the `os.DirFS()` version (`./root -docroot ./docroot`) I get the `index.html` nicely at http://localhost:6602/index.html. If I use the `embed` version (`./root`) it ends up at http://localhost:6602/docroot/index.html

### What did you expect to see?

I expect either none or both to have the `./docroot/` subdir in there. This way I can't use `http.StripPrefix()`. But maybe I missed something else.

### What did you see instead?

The embed.FS and os.DirFS seem to behave inconsistently.

If embed.FS implemented fs.SubFS I think I could make this work by using `docroot.Sub("./docroot/")`

**Comment by changkun** [comment]
You can do something like this:

```go
//go:embed docroot/*
var static embed.FS

// myFS implements fs.FS
type myFS struct {
	content embed.FS
}

func (c myFS) Open(name string) (fs.File, error) {
	return c.content.Open(path.Join("docroot", name))
}
```

Then:

```go
r.Handle("/", http.FileServer(http.FS(myFS{root})))
```

**Comment by dmitshur** [comment]
It seems to me that `embed.FS` and `os.DirFS` are working as intended, you will need to arrange your code to either handle different roots, or have the same root by running your program with `./root -docroot=.` instead of `./root -docroot=./docroot`.

Since it's a new API, I'll let @rsc consider if anything more should be done.

**Comment by alicebob** [comment]
Thanks for the quick responses.

Is there anything against embed.FS implementing `fs.SubFS`? That would make it easier to deal with this case.

**Comment by alicebob** [comment]
@changkun solution would work great. I ended up adding a single file _inside_ the docroot:
```
$ cat docroot/fs.go 
package docroot

import "embed"

//go:embed *
var FS embed.FS
```
and importing that. It's not pretty, but works.

(as far as I'm concerned this issue can be closed)

**Comment by changkun** [comment]
@alicebob Indeed. I noticed the behavior you reported in this thread while I was trying to convert my static website [here](https://github.com/changkun/main/blob/d6ce973f50b2ef2a46f5c743aa5c3640c3962b3a/main.go#L21-L31).

I didn't report this simply don't know that is the actually expected behavior from these new set of APIs. The design draft is just a draft, as far as I partially skimmed with the ongoing discussion. The current implementation is already apart from the draft design (lack of documentation).

For more instance, I'd like to directly embed everything in a repository (and of course exclude the `.git` folder):

```
$ l
total 16
drwxr-xr-x   5 changkun  staff   160B Dec 31 13:56 .
drwxr-xr-x  29 changkun  staff   928B Dec 31 13:49 ..
drwxr-xr-x   9 changkun  staff   288B Dec 31 13:50 .git
-rw-r--r--   1 changkun  staff    18B Dec 31 13:56 go.mod
-rw-r--r--   1 changkun  staff   102B Dec 31 13:54 main.go

$ cat main.go
package main

import "embed"

//go:embed *
var static embed.FS

func main() {
        println(static)
}
```

With the (undocumented) https://github.com/golang/go/commit/37588ffcb221c12c12882b591a16243ae2799fd1, the `.git` should be ignored and have a successful build.

But unfortunately, build such a simple program can result in the following compile error:

```
$ go build
pattern *: cannot embed directory .git: invalid name .git
```

**Comment by carlmjohnson** [comment]
Am I misunderstanding or does this use of fs.Sub do what you want? https://github.com/carlmjohnson/exembed/blob/main/web/main.go

**Comment by changkun** [comment]
> Am I misunderstanding or does this use of fs.Sub do what you want? https://github.com/carlmjohnson/exembed/blob/main/web/main.go

Oh, how cloud I miss the `fs.Sub`, thanks for the hint. It would be great to have an example like this in a `*_example.go` and demonstrate in the document.

**Comment by alicebob** [comment]
@carlmjohnson awesome, yes that solves everything.

I misread the output of `go doc`: I saw `SubFS` interface, which `embed.FS` doesn't implement, but I missed the pure `Sub()` function.
