### ISSUE TITLE
crypto/x509: reconsider the expansion of CertificateRequest

### ISSUE THREAD

**Issue by AGWA** [golang/go#43477]
Go 1.16 adds a number of [additional convenience fields to `CertificateRequest`](https://go-review.googlesource.com/c/go/+/233163/).  I think these fields are a bad idea and should be removed before Go 1.16 is released and these fields have to be supported forever.

Go's [Cryptography Principles](https://go.googlesource.com/proposal/+/master/design/cryptography-principles.md) state that the Go crypto library should be easy to use securely.  Unfortunately, there are numerous examples of CAs accidentally copying unverified data from CSR fields into final certificates:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1551374
* https://bugzilla.mozilla.org/show_bug.cgi?id=1551372
* https://bugzilla.mozilla.org/show_bug.cgi?id=1551369
* https://bugzilla.mozilla.org/show_bug.cgi?id=1551364
* https://bugzilla.mozilla.org/show_bug.cgi?id=1551371
* https://bugzilla.mozilla.org/show_bug.cgi?id=1567456
* https://bugzilla.mozilla.org/show_bug.cgi?id=1390979
* https://bugzilla.mozilla.org/show_bug.cgi?id=1551363

Ingesting CSRs is so error-prone that a prudent CA should be discarding everything in a CSR except the public key.  Of course, the library can't prevent people from copying raw extensions out of `Extensions`, but it could try to avoid nudging people in the wrong direction, and making CSR fields more conveniently accessible seems like a nudge in the wrong direction.

The Cryptography Principles also state that the library should focus on "common use cases."  However, the bug which proposed this change (#37172) doesn't explain the use case for taking these fields from CSRs, and received only one positive reaction from a non-Go-teammember.  I don't think there's any reason to believe that this is a common use case, particularly in the WebPKI, which crypto/x509 is [aimed towards](https://github.com/golang/go/issues/26624).

I'm particularly alarmed by the addition of the BasicConstraints fields (e.g. `IsCA`).  In a robust PKI, the process for issuing a CA certificate should be distinct from the process for issuing an end-entity certificate.  It's not something that should ever be based on the contents of the CSR.

**Comment by ALTree** [comment]
cc @FiloSottile

**Comment by FiloSottile** [comment]
I admit I did not consider the use case at length when recommending that proposal be approved. My bad.

I agree that applications should not be encouraged to extract any of these values from CSRs. Moreover, if they really need to, they can parse the extensions themselves, which presumably is what they've been doing so far.

I'm in favour of rolling back these new APIs. In practice this would look like removing some code rather than rolling back a commit because the commit also did some refactoring that I tink would be more risky to remove than leave in place.

I assume this needs to be speed-tracked to make the RC?

/cc @golang/proposal-review @golang/release

**Comment by rsc** [comment]
Please prepare the CL so we can see the change, and make it as small as possible. Thanks.

**Comment by rsc** [comment]
I discussed this with proposal review and everyone agrees with rolling this back and using the CL you sent.
No need for more approvals.
