### ISSUE TITLE
cmd/compile: odd escaping in error message

### ISSUE THREAD

**Issue by rsc** [golang/go#43762]
https://play.golang.org/p/WX5BJVLjIkR

```
package main

func main() {
	_ = true == '\\'
}
```

produces

	./prog.go:4:11: invalid operation: true == '\u005c' (mismatched types untyped bool and untyped rune)

It should almost certainly say `'\\'` not `'\u005c'`.
Took me a while to decode the first time I saw it.

**Comment by cuonglm** [comment]
Seems if we make it to print the rune literal, export will be broken https://codereview.appspot.com/5472046.

Although even without that special condition, we will say `\`, not `\\`.

**Comment by mdempsky** [comment]
I don't think export data should be affected by changing how fmt.go prints rune literals. fmt.go hasn't been involved in the export data format since the introduction of bexport.

We should certainly escape characters correctly though. Maybe we can just use `%q` for printing rune values less than 128: https://play.golang.org/p/MZ6CoEORrZN

**Comment by mdempsky** [comment]
This is fixed on dev.regabi.
