### ISSUE TITLE
internal/execabs: disable tests on js-wasm

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#43791]
`os/exec.{LookPath,Command}` is disabled on js-wasm so `internal/execabs` won't work on the platform.

**Comment by rolandshoemaker** [comment]
This is also a problem on 1.14 and 1.15.
@gopherbot please open backport issues.

**Comment by oiooj** [comment]
The execabs calls `os.exec`, `os.exec` already disabled on js-wasm.

```
package main

import "fmt"
import "golang.org/x/sys/execabs"

func main() {
	fmt.Println(execabs.LookPath("go"))
}
```

`GOARCH="wasm" GOOS="js" go run main.go` output:
```
fork/exec /.../T/go-build404657744/b001/exe/main: exec format error
```

**Comment by bcmills** [comment]
Note that a robust fix should probably use `internal/testenv.MustHaveExec` and/or `internal/testenv.MustHaveExecPath`, not a hard-coded `runtime.GOOS` or `runtime.GOARCH` value.

**Comment by oiooj** [comment]
Oh, I did not see the word `tests` in the title.

**Comment by dmitshur** [comment]
This problem does not exist at tip now, the `js-wasm` builder is passing at https://build.golang.org. It will be introduced in [CL 284783](https://golang.org/cl/284783) if that CL is submitted as is. I agree with @ianlancetaylor's [suggestion](https://go-review.googlesource.com/c/go/+/284952/1#message-93bdf2cdc34da9d0ed5088b8f2ea400df9a20c3f) that we should just squash [CL 284952](https://golang.org/cl/284952) (which fixes this issue) into [CL 284783](https://golang.org/cl/284783) and avoid introducing this known problem into the tree. (This issue was useful for creating backports, since the problem did exist on release branches.)

I'll close this issue since it is currently resolved. (If needed, it can be reopened.)
