### ISSUE TITLE
cmd/go2go: type inference fails for embedded interface coercion

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#43933]
I'm not entirely sure that this is a bug and not just a limitation of the current inference implementation, but it was definitely a bit unexpected to me.

[Example in the playground.](https://go2goplay.golang.org/p/dJBpULHfvrQ)
```go
package main

import (
	"strconv"
)

type Value[T any] interface {
	Get() T
}

type MutValue[T any] interface {
	Value[T]
	Set(T)
}

type value[T any] struct {
	val T
}

func NewMutValue[T any](val T) MutValue[T] {
	return &value[T]{
		val: val,
	}
}

func (v value[T]) Get() T {
	return v.val
}

func (v *value[T]) Set(val T) {
	v.val = val
}

type subValue[T, S any] struct {
	p Value[S]
	t func(S) T
}

func Sub[T, S any](p Value[S], t func(S) T) Value[T] {
	return subValue[T, S]{
		p: p,
		t: t,
	}
}

func (v subValue[T, S]) Get() T {
	return v.t(v.p.Get())
}

func main() {
	v1 := NewMutValue(3)
	v2 := Sub(v1, func(v int) string {
		return strconv.FormatInt(int64(v), 2)
	})
	println(v2.Get())
}
```

This fails for the call to `Sub()` at the bottom with the error `type MutValue[int] of v1 does not match Value[S] (cannot infer T and S)`. Manually wrapping the usage of `v1` there in `Value[int](v1)` fixes it, however.

**Comment by ianlancetaylor** [comment]
CC @griesemer

This code expects that a value of type `MutValue[int]` can match a value of type `Value[S]`.  But `MutValue[int]` is not `Value[S]` for any `S`.  It's true that a value of type `MutValue[int]` is assignable to a value of type `Value[S]`, but type inference does not consider assignability.  This is an explicit decision to reduce confusion.  We want it to always be clear exactly what types are inferred.  If we consider assignability, the range of possible inferred types grows considerably.  We want to keep it small.

I'm going to close this because I don't think it's a bug, but please comment if you disagree.
