### ISSUE TITLE
x/website: Use HTML <details> element instead of Javascript

### ISSUE THREAD

**Issue by ghost** [golang/go#44000]

**Comment by mdlayher** [comment]
What exactly are you asking for? Can you clarify?

**Comment by inet56** [comment]
There are those widgets which can be opened and closed like example codes in pkg documentation. It would be nice if those are done using HTML details element instead of custom widget via Javascript thus making the webpage more useable without Javascript.

Another thing can be done is to make those example codes visible when Javascript isn't available.

**Comment by seankhliao** [comment]
the examples are already using details/summary though?

![2021-01-30-164335](https://user-images.githubusercontent.com/11343221/106360704-50c02000-631a-11eb-9e33-d2ed808f7fca.png)

**Comment by inet56** [comment]
But they don't open without Javascript being enabled.

**Comment by seankhliao** [comment]
they open/close fine for me with js disabled on Chrome 88.0.4324.96 (Linux)

**Comment by seankhliao** [comment]
Oh, I see on golang.org ex https://golang.org/pkg/encoding/json/#example_Decoder

**Comment by inet56** [comment]
@mdlayher Any more information?

**Comment by mdlayher** [comment]
I know nothing about modern frontend development and just asked for clarifying details for others who might.

**Comment by seankhliao** [comment]
Seems no longer relevant and pkgsite uses details
