### ISSUE TITLE
x/pkgsite: images in README.md do not appear

### ISSUE THREAD

**Issue by robpike** [golang/go#44032]
Possibly related to #43325.

If you look at github.com/robpike/ivy, you'll see an image at the bottom of the README.

At pkg.go.dev/robpike.io/ivy, the text appears but the image is replaced by the "broken image" icon and the alternate text.

I can think of various reasons this could be happening, including the custom domain, but I thought it worth reporting.

**Comment by fzipp** [comment]
The broken image source URL is

  https://github.com/robpike/ivy.git/raw/v0.1.0/ivy.jpg

but it should be

  https://github.com/robpike/ivy/raw/v0.1.0/ivy.jpg

Pkgsite tries to convert a relative markdown image URL to an absolute URL by prepending the repository URL, but for some reason the repository URL ends in ".git", as can be seen in the repository link on the right side of the page. Probably because the "go-import" meta tag under https://robpike.io/ivy?go-get=1 ends in ".git":

`<meta name="go-import" content="robpike.io/ivy git https://github.com/robpike/ivy.git">`

https://golang.org/cmd/go/#hdr-Remote_import_paths says:

"The meta tag has the form:

`<meta name="go-import" content="import-prefix vcs repo-root">`

The repo-root is the root of the version control system containing a scheme and not containing a .vcs qualifier."

**Comment by jba** [comment]
Thanks for the accurate diagnosis, @fzipp. 

The `.git` also broke source links.

We deploy daily so this should be live by tomorrow.
