### ISSUE TITLE
runtime: probably unwanted integer division in scavenger pacing

### ISSUE THREAD

**Issue by dominikh** [golang/go#44036]
I've stumbled across the following code, which IMO is incorrect:

https://github.com/golang/go/blob/6ac91e460c294bda5a50e628b7556bf20525fa44/src/runtime/mgcscavenge.go#L371-L378

The value of minFraction is `0`, which makes the check pointless. 

/cc @mknyszek to confirm my suspicion, as I'm not familiar with any of this code.

**Comment by mknyszek** [comment]
Erg, yeah good catch, thank you. I like to think that constants are truly untyped, but that's wrong. :)

Luckily, it looks like we didn't hit this case much in practice or not any case that was important enough for someone to report a bug about it. This makes sense since the scavenger isn't quite as useful in the context of, say, a CLI tool, where it's more likely this case could happen (e.g. laptop lid closes during the section where we're measuring time). I'll send a fix, but it's probably not worth backporting.
