### ISSUE TITLE
x/pkgsite: short summary of package on search page unreadable

### ISSUE THREAD

**Issue by katiehockman** [golang/go#44174]
For certain packages, the high-level summary of the package is unreadable in the search page. For example, searching for "fmt" comes up with the standard library package (which is easy to read) and another package "github.com/astaxie/beego/orm":

![fmt_page](https://user-images.githubusercontent.com/28789760/107286054-13504680-6a2e-11eb-8b98-8acfa319a2fb.png)

It's actually not totally clear to me what is being printed in the search page, since the [README of that package](https://pkg.go.dev/github.com/astaxie/beego/orm) appears to be different for me when I actually click into it. It also has an image that doesn't render.

I don't actually know if there is anything you can/want to do about this, since it's likely working as intended. But I wanted to bring it up as a UX issue.

@julieqiu

**Comment by julieqiu** [comment]
The issue here is that the package synopsis is missing a period at the end of the first sentence:
https://github.com/astaxie/beego/blob/v1.12.3/orm/orm.go#L17

I think it makes sense for us to truncate the package synopsis after a certain length on the search results page. For example:

![image](https://user-images.githubusercontent.com/5943521/107288219-16006b00-6a31-11eb-8594-33abbaabed26.png)


/cc @georgehu
