### ISSUE TITLE
cmd/go: go list -m -json GoMod field is not populated sometimes

### ISSUE THREAD

**Issue by hyangah** [golang/go#44289]
go version: 1.16rc1

I ran the `go list` command back to back, and noticed the GoMod field was not populated during the very first try.

```
$ GOPROXY=direct GOSUMDB=off GOPATH=/tmp/x /Users/hakim/sdk/go1.16rc1/bin/go  list -m -json --versions github.com/hyangah/retracttest/a@latest
{
        "Path": "github.com/hyangah/retracttest/a",
        "Version": "v0.0.0-20201117044135-c0d2dc84e45f",
        "Time": "2020-11-17T04:41:35Z",
        "GoVersion": "1.15"
}
$ GOPROXY=direct GOSUMDB=off GOPATH=/tmp/x /Users/hakim/sdk/go1.16rc1/bin/go  list -m -json --versions github.com/hyangah/retracttest/a@latest
{
        "Path": "github.com/hyangah/retracttest/a",
        "Version": "v0.0.0-20201117044135-c0d2dc84e45f",
        "Time": "2020-11-17T04:41:35Z",
        "GoMod": "/tmp/x/pkg/mod/cache/download/github.com/hyangah/retracttest/a/@v/v0.0.0-20201117044135-c0d2dc84e45f.mod",
        "GoVersion": "1.15"
}
```

**Comment by iWdGo** [comment]
Issue still occurs on `go1.16.3`. The first `go list` command loads the cache reported by `GoMod` as in the second use of the command. Manually deleting the folder reported by `GoMod` repeats the behavior.

On [tip]( https://go-review.googlesource.com/c/go/+/308329), issue seems solved probably because of [CL 293689](https://go-review.googlesource.com/c/go/+/293689) which updates #40775 by refactoring `modload.LoadFile(ctx)`

It seems that issue can be closed for now.

**Comment by ianlancetaylor** [comment]
This is in the Go1.18 milestone.  Is it likely to happen for 1.18?  Thanks.

**Comment by ianlancetaylor** [comment]
@bcmills This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by bcmills** [comment]
> On tip, issue seems solved probably because of CL 293689 which updates #40775 by refactoring modload.LoadFile(ctx)
>
> It seems that issue can be closed for now.

Closing on the theory that this may have been fixed by changes in `modload/list.go` and/or `cmd/go/internal/list/list.go` (there have been substantial changes in both since 1.16rc1).

Please reopen (or open a new issue) if you observe this in Go 1.18beta2 or higher.
