### ISSUE TITLE
x/lint: go:embed gives false positives about comment format 

### ISSUE THREAD

**Issue by howardjohn** [golang/go#44354]
Source:
```go
var (
        //go:embed charts/* profiles/*
        //go:embed charts/gateways/istio-egress/templates/_affinity.tpl
        //go:embed charts/gateways/istio-egress/templates/_helpers.tpl
        //go:embed charts/gateways/istio-ingress/templates/_affinity.tpl
        FS embed.FS
)
```

Execution:
```
$ go version
go version go1.16 linux/amd64
$ go install golang.org/x/lint/golint@master
$ golint ./manifests/...
manifests/manifest.go:24:2: comment on exported var FS should be of the form "FS ..."
```

I would expect this to not require a comment starting with `FS` since I am not trying to write a comment with go:embed, but rather compiler instructions.

**Comment by cespare** [comment]
(Updated the title to be about lint.)

That's definitely a bug, but also x/lint is really not maintained and will probably be deprecated. See #38968.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all golint before we freeze its repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
