### ISSUE TITLE
[dev.fuzz] proposal: default timeout should be disabled

### ISSUE THREAD

**Issue by dsnet** [golang/go#44483]
Running the following flags:
```
go test -fuzz=MyFunc
```
eventually crashes with:
```
*** Test killed with quit: ran too long (11m0s).
exit status 2
FAIL	path/to/my/module	660.015s
```

I would expect the use of the `fuzz` flag to implicitly disable the `timeout` flag (i.e., set it to `0`). The fact that it crashes after around 10min matches the default value for `timeout`, which is 10min. I'm not sure where the additional 60s comes from.

**Comment by dsnet** [comment]
The [current proposal mentions a possible `fuzztime` flag](https://go.googlesource.com/proposal/+/master/design/draft-fuzzing.md#go-command). I wonder if it is better to overload the existing `timeout` flag instead.

\cc @jayconrod @katiehockman

**Comment by ulikunitz** [comment]
I suggest that timeout should be also applied to fuzzing but use the default 0 instead 10 minutes. If a timeout value is provided it should be used for testing and fuzzing. This way we can avoid -fuzztime and all confusion resulting from it.

To be honest users will not care for tests on the seed corpus and timeouts on it.  For me it was always stuff in a directory. I started often with one simple seed. What was important to me where the crashers, because I needed them to create the test cases for the required fixes.

**Comment by AlekSi** [comment]
I think there needs to be one other timeout: timeout for one fuzz function invocation. This will allow one to find not only crashers, but hangs due to endless loops, large memory consumption, blocking on reading, etc. https://github.com/dvyukov/go-fuzz has this flag:
```
  -timeout int
    	test timeout, in seconds (default 10)
```

I think we can redefine what `-timeout` means when `-fuzz` is passed.

**Comment by AlekSi** [comment]
> To be honest users will not care for tests on the seed corpus and timeouts on it. For me it was always stuff in a directory.

As a user, I respectfully disagree. I used [unit tests for filling seed corpus](https://github.com/Percona-Lab/PromHouse/blob/master/utils/gofuzz/gofuzz_enabled.go) even before `dev.fuzz` made it much easier. I do care about testing seed corpus and timeouts on it.

**Comment by katiehockman** [comment]
This issue is focused on two main points: 1) the default timeout should be disabled when fuzzing and 2) we should consider a way to specify how long an execution of a fuzz function can run before it should be considered a "crash".

https://golang.org/cl/313072 fixes (1), and I'll track (2) in my list of feature requests/bugs to be filed all at once in a few weeks.

**Comment by katiehockman** [comment]
I have filed https://github.com/golang/go/issues/46220, so will go ahead and close this one as fixed.
