### ISSUE TITLE
cmd/compile: `-l` does not disable intra-package inlining

### ISSUE THREAD

**Issue by egonelbre** [golang/go#44585]
`-l` seems to have different behavior depending on whether the func is imported from another package or not. This came up in this changeset: https://go-review.googlesource.com/c/go/+/295989.

Test with `-N -l` failed with this version of the code:

```
func EncodeQuad(d []uint32, x [6]float32) { // ERROR "can inline EncodeQuad" "d does not escape"
	_ = d[:6]
	d[0] = math.Float32bits(x[0]) // ERROR "inlining call to math.Float32bits"
	d[1] = math.Float32bits(x[1]) // ERROR "inlining call to math.Float32bits"
	d[2] = math.Float32bits(x[2]) // ERROR "inlining call to math.Float32bits"
	d[3] = math.Float32bits(x[3]) // ERROR "inlining call to math.Float32bits"
	d[4] = math.Float32bits(x[4]) // ERROR "inlining call to math.Float32bits"
	d[5] = math.Float32bits(x[5]) // ERROR "inlining call to math.Float32bits"
}
```

It's weird that `-l` only disables some of the inlining.

**Comment by josharian** [comment]
cc @mdempsky

**Comment by mdempsky** [comment]
On the noopt builder, package math will have been compiled with `-l`, so `Float32bits` will have been marked as not inlinable. So I think that failure makes sense.

I'm a little less sure why the local function would fix it. Maybe because test/run.go doesn't pass GO_GCFLAGS through to the compiler when invoked for errorcheck tests? I seem to remember some inconsistency like that. And if package A imports package B, and B was compiled with `-l`, then even if package A is compiled without `-l` then functions imported from B won't be inlinable.

**Comment by egonelbre** [comment]
I was looking into test/run.go and it does have some special behavior for noopt. https://github.com/golang/go/blob/37ca84a9cd6a8a76dfe91263a17d2b92b17a24b3/test/run.go#L396

And some of the tests are disabled with those flags https://github.com/golang/go/blob/37ca84a9cd6a8a76dfe91263a17d2b92b17a24b3/test/checkbce.go.

But, the code looks like it does pass the gc flags: https://github.com/golang/go/blob/master/test/run.go#L1113

**Comment by mdempsky** [comment]
test/inline.go is an "errorcheck" test case. That last link (line 1113) is for "run" test cases.

**Comment by egonelbre** [comment]
Hmm, so it does look like the code does what it is written to do :D. And the explanation that math was compiled with `-l` does make sense.

I don't really have anything actionable that could be done here, since the tooling seems to work as intended.

**Comment by josharian** [comment]
Thanks for investigating. This makes sense now; or anyway, I understand now. :)
