### ISSUE TITLE
x/website: use all gopher images on the website

### ISSUE THREAD

**Issue by fzipp** [golang/go#44651]
Some gophers did not survive various website reorganisations over the time and are no longer featured on the website:

- https://golang.org/doc/gopher/ref.png
- https://golang.org/doc/gopher/run.png

This gopher is also endangered:
- https://golang.org/doc/gopher/pkg.png
It's currently featured on https://golang.org/pkg/ but the redirect to https://pkg.go.dev/std is imminent (#44356). Maybe it can find a new home over there?

I think the 'ref' gopher belongs in this section: https://golang.org/doc/#references

**Comment by dmitshur** [comment]
We should certainly not delete the gophers without reason, but I think it's okay for some of them not to featured on the website. What's important is they're available to be featured when there is a need or desire. Until then, the gophers can enjoy some rest in the tunnels.

I'll close this because I don't think we need a tracking issue for this, but thanks for thinking of the gophers!
