### ISSUE TITLE
cmd/go: prevent import modules that may cause import cycles

### ISSUE THREAD

**Issue by changkun** [golang/go#44669]
Assume we have two modules: A (cyclemod) and B (cyclemod2). Go module does not complain about the following dependency relationship:

- A@v1.0.0 depends on B@v2.0.0
- B@v2.0.0 depends on A@v0.2.0
- A@v0.2.0 depends on B@v0.1.0
- B@v0.1.0 depends on A@v0.1.0
- A@v0.1.0 has no dependency

However, it is possible in a version of A:

```
import "cyclemod2/v2" // or "cyclemod2"
```

and in B:

```
import "cyclemod"
```

This leads to:

```
package cyclemod
        cyclemod2/v2
        cyclemod: import cycle not allowed
```

The dependency cycle might happen at `go mod tidy`, but the import cycle is not detected. Maybe, Go module should either:

1. prevent importing module that involves import cycle at import time instead of compile-time
2. allow import "import cycle" for modules with different versions

**Comment by seankhliao** [comment]
Are you sure it's not just a plain import cycle? From the info you gave only A@v1.0.0 and B@v2.0.0 would be selected for build

**Comment by bcmills** [comment]
A module may contain many packages. Cycles in the module requirement graph often _do not_ correspond to cycles in the package import graph.

The `import cycle not allowed` error message that you observed reports a cycle in the package graph, not the module graph. The fix for that error is to update the `import` statements in the `.go` source files, not the `require` directives in the `go.mod` files.

**Comment by changkun** [comment]
Thought import cycle might work using different versioned modules. Thanks for the explanation, clear and close...
