### ISSUE TITLE
x/tools/gopls: suggests invalid package names

### ISSUE THREAD

**Issue by seankhliao** [golang/go#44680]
go: tip
gopls: v0.6.6

With module / directory names with `-` in them, `gopls` uses that directly as a suggested package name, which is invalid

![2021-02-28-115235](https://user-images.githubusercontent.com/11343221/109415943-cb349c00-79bb-11eb-8217-265e5ae70092.png)

**Comment by ShoshinNikita** [comment]
We can replace `-` with `_`. But there are other cases:

* directory name starts with a digit
* directory name contains one of these characters: `-`, `.` or `~`
* directory name contains invalid characters (whitespace, comma, etc.)

I think we can ignore the last case and don't show suggestions at all because it's not possible to import such packages (https://golang.org/ref/mod#go-mod-file-ident). But what is the expected behavior in other situations?

**Comment by msAlcantara** [comment]
What do you think about ignoring anything that is not a letter? So in case of `foo_bar`, `123foobar`, `foo bar` will be always suggest `foobar`

**Comment by ShoshinNikita** [comment]
@msAlcantara Thanks for the idea! I was planning to convert all punctuation to `_`, but it would conflict with the package name convention. So, ignoring the punctuation is a better strategy.
