### ISSUE TITLE
cmd/go/internal/lockedfile: os.Chmod call in openFile ignores overlays

### ISSUE THREAD

**Issue by fhs** [golang/go#44700]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +master Sun Feb 28 22:38:43 EST 2021 plan9/386
</pre>

### What did you do?

```
cd src/cmd/go
go test -run TestScript/mod_overlay
```
### What did you expect to see?

Test pass

### What did you see instead?

```
go test proxy running at GOPROXY=http://127.0.0.1:65174/mod
--- FAIL: TestScript (0.02s)
    --- FAIL: TestScript/mod_overlay (0.24s)
        script_test.go:213: 
            # Test overlays that affect go.mod files
            # The go.mod file can exist only in the overlay. (0.012s)
            > cd $WORK/gopath/src/no-go-mod
            $WORK/gopath/src/no-go-mod
            > go list -overlay overlay.json .
            [stderr]
            go: chmod $WORK/gopath/src/no-go-mod/go.mod: stat $WORK/gopath/src/no-go-mod/go.mod: '.../tmpdir4282295690/script-mod_overlay/gopath/src/no-go-mod/go.mod' does not exist
            [exit status: 'go 1689: 1']
            FAIL: testdata/script/mod_overlay.txt:5: unexpected command failure
            
FAIL
exit status: 'go.test 1537: 1'
FAIL	cmd/go	7.377s
```

The error is from [os.Chmod in lockedfile package](https://github.com/golang/go/blob/5ff7ec98b7727b3641df25200345b1aa50b6ff35/src/cmd/go/internal/lockedfile/lockedfile_plan9.go#L64), which of course couldn't find the overlayed `go.mod` file. There is no `Chmod` function in `cmd/go/internal/fsys`, so either that can be added or have some other workaround.

@gopherbot NeedsFix, OS-Plan9

**Comment by bcmills** [comment]
CC @matloob @jayconrod

**Comment by jayconrod** [comment]
Echoing a comment from https://golang.org/cl/299029, I think we should take this in a different direction.

With the overlay, the expectation should be that the go command will not modify any replacement file. The overlay should be entirely read-only.

The problem described in this issue is that on Plan 9, we need to call `os.Chmod` to acquire a lock on `go.mod`. Rather than adding `fsys.Chmod`, it would be better to have a special case *not* to acquire locks on `go.mod` files in the overlay.
