### ISSUE TITLE
x/pkgsite: markdown parsing of `code` inside a link

### ISSUE THREAD

**Issue by jakesyl** [golang/go#44798]
### What did you do?

Currently, on say github I can wrap a link inside a code block [`like so`](https://github.com/golang/go). I did this on [github.com/xplorfin/netutils](https://github.com/xplorfin/netutils).

### What did you expect to see?

This to render correctly on `pkg.go.dev` like above.

### What did you see instead?

[See here for original link](https://pkg.go.dev/github.com/xplorfin/netutils)
![image](https://user-images.githubusercontent.com/6392429/110039143-cdc22900-7d0e-11eb-90a5-6a5862d9fd51.png)

**Comment by julieqiu** [comment]
Would you mind clarifying where the issue is? Here's what I see on:

https://github.com/xplorfin/netutils:

![image](https://user-images.githubusercontent.com/5943521/110050333-afb1f400-7d21-11eb-9e87-6da9e1cd9523.png)


and https://pkg.go.dev/github.com/xplorfin/netutils:

![image](https://user-images.githubusercontent.com/5943521/110050343-b6406b80-7d21-11eb-88aa-636ae9ee0707.png)

**Comment by jakesyl** [comment]
Yep! I'm on mobile right now so I just circled it in your screenshot:

![image](https://user-images.githubusercontent.com/6392429/110237898-873a1d80-7f0c-11eb-9711-f9e0b76bbef6.jpeg)

**Comment by seankhliao** [comment]
seems like a bug in the project's readme, it's currently
```
`mock_test`[testutils/mock_test]
```
when it should be
```
[`mock_test`](testutils/mock_test)
```
note httmock a few lines above has the correct syntax/renders properly

**Comment by jakesyl** [comment]
Got it - was looking at a local version with that fixed. Thanks!
