### ISSUE TITLE
testing: Helper line number has changed in 1.16

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#44887]
This is the test program.

```Go
package main_test

import (
	"testing"
)

func TestHelper(t *testing.T) {
	helperA(t)
}

func helperA(t *testing.T) {
	t.Helper()

	t.Run("subtest", func(t *testing.T) {
		t.Helper()
		t.Fatal("fatal error message")
	})
}
```

When run using `go test foo_test.go` with Go 1.14 or Go 1.15, this program prints

```
--- FAIL: TestHelper (0.00s)
    --- FAIL: TestHelper/subtest (0.00s)
        foo_test.go:8: fatal error message
FAIL
FAIL	command-line-arguments	0.009s
FAIL
```

When run with Go 1.16 it prints

```
--- FAIL: TestHelper (0.00s)
    --- FAIL: TestHelper/subtest (0.00s)
        foo_test.go:14: fatal error message
FAIL
FAIL	command-line-arguments	0.007s
FAIL
```

The line number has changed from 8 to 14.  Line number 14 is in a function that called `t.Helper`, so line 8 seems correct and line 14 seems wrong.

This appears to be due to https://golang.org/cl/231717.  If I revert that CL, I see line number 8.

CC @bboreham

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.16

In some cases `t.Helper` seems to be ineffective.  It's not critical but it's definitely annoying.  We should fix it.

**Comment by dnephin** [comment]
I just ran into this problem. I have been using a function `runCase` (see below) to make it easier to work with very large table tests. When a test spans thousands of lines it can be difficult to find the data for a specific failure. This `runCase` pattern has made it much easier to debug failing tests, and it no longer works due to this regression.

I notice this issue has been pushed out a couple patch releases. Please let me know if I can be of any help in restoring the old behaviour or testing a fix.

Example use case:

```go
func runCase(t *testing.T, name string, fn func(t *testing.T)) {
	t.Helper()
	t.Run(name, func(t *testing.T) {
		t.Helper()
		t.Log("case:", name)
		fn(t)
	})
}
```
