### ISSUE TITLE
request the chinese document page got the error

### ISSUE THREAD

**Issue by jiawei666** [golang/go#44938]
##### step
1. click this button
![1615457102(1)](https://user-images.githubusercontent.com/24775116/110771085-13459f80-8295-11eb-98f7-f6ab9efc618c.png)

2. got error
![1615457552(1)](https://user-images.githubusercontent.com/24775116/110771385-661f5700-8295-11eb-970d-ef501c16856f.jpg)

**Comment by ALTree** [comment]
That link looks wrong to me, the simplified chinese tour translation is at https://tour.go-zh.org, not at https://go-tour-zh.appspot.com/ (where an old copy probably was).

But anyway that chinese translation of the website (at https://go-zh.org/) is not part of the Go Project; so you should report the issue to whoever translated the website to mandarin.

Closing here since we cannot fix this.

**Comment by jiawei666** [comment]
thanks
