### ISSUE TITLE
cmd/go: go vet does not support -overlay

### ISSUE THREAD

**Issue by eandre** [golang/go#44957]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/eandre/Library/Caches/go-build"
GOENV="/Users/eandre/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/eandre/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/eandre"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hc/w9bwjfwd69dd6_6thw6xqmkw0000gn/T/go-build2213810525=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Consider the following txtar:

```
-- go.mod --
module test.pkg
-- foo/foo_test.go --
package foo

import "testing"

func TestFoo(t *testing.T) { }
-- tmp/bar.go --
package foo
-- foo/overlay.json --
{"Replace": {"bar.go": "../tmp/bar.go"}}
```

I ran `cd foo && go test -overlay=overlay.json .` and expected the tests to pass.

### What did you expect to see?

```
$ go test -overlay=overlay.json .
ok  	test.pkg/foo 0.123s
```

### What did you see instead?

```
$ go test -overlay=overlay.json .
# test.pkg/foo
vet: open bar.go: no such file or directory
FAIL	test.pkg/foo [build failed]
FAIL
exit status 2
```

The issue is because the overlay is added to `GoTestFiles` but `go vet` does not support (or receive information about) overlays, so it tries to read the overlaid file directly from the filesystem where it does not exist.

**Comment by jayconrod** [comment]
cc @matloob @bcmills

**Comment by vithalklrk** [comment]
Hi, alldocs.go says this:
`// 	-overlay file
// 		read a JSON config file that provides an overlay for build operations.
// 		The file is a JSON struct with a single field, named 'Replace', that
// 		maps each disk file path (a string) to its backing file path, so that
// 		a build will run as if the disk file path exists with the contents
// 		given by the backing file paths, or as if the disk file path does not
// 		exist if its backing file path is empty. Support for the -overlay flag
// 		has some limitations: importantly, cgo files included from outside the
// 		include path must be in the same directory as the Go package they are
// 		included from, and **overlays will not appear when binaries and tests are
// 		run through go run and go test** respectively.
`
Is the above description saying that this is not an issue? I am new, so I could be getting it wrong

**Comment by dolmen** [comment]
Also: `go vet` accepts a `-overlay <file>` flag, but seems to ignore it: 
```
$ go vet -overlay=overlay.json .
```

**Comment by matloob** [comment]
We should implement this for Go 1.24.
