### ISSUE TITLE
image/jpeg: support for CMYK images

### ISSUE THREAD

**Issue by gopherbot** [golang/go#4500]
by **samuel.stauffer**:

<pre>To reproduce:

1. Decode CMYK jpeg (attached)

What is the expected output?

A successfully decoded image. Works in Preview.app and ImageMagick.

What do you see instead?

Error &quot;unsupported JPEG feature: SOF has wrong length&quot;

Which version are you using?  (run 'go version')

go version devel +a5efcd1675eb Thu Dec 06 09:47:12 2012 -0800

Please provide any additional information below.

I'm seeing this error for all CMYK jpegs I've tried.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/4500/0/err1.jpeg">err1.jpeg</a> (902176 bytes)

**Comment by nigeltao** [comment]
alexander.lobunets: the "bad Pq value" is a different issue, #9888.

**Comment by foresmac** [comment]
@nigeltao So, if I `go get image`, should CMYK decoding now work? (Or more probably I need to `go get -u`...)

**Comment by nigeltao** [comment]
CMYK decoding works with the latest (unstable) release of the standard library, which is due to be released as Go 1.5 on August 1.

If you need it before then, you should be able to fork the image/... packages from 1.5 and run them on 1.4.

If you are on 1.4, though, it won't be as easy as running "go get", since image/jpeg, image/color and image are part of the standard library.

**Comment by foresmac** [comment]
@nigeltao Yeah, I wasn't sure if the std lib was tightly versioned with the Go runtime or not. Not a major issue, but I'll definitely try out the CMYK support when Go 1.5 drops. Thanks so much for this improvement!
