### ISSUE TITLE
Why isn't there a heap library in the standard library similar to Python 3's heapq library?

### ISSUE THREAD

**Issue by irfanshaik11** [golang/go#45011]
Hi all,

### What version of Go are you using (`go version`)?
Go Version 1.15

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Minimum heaps allow for insertion and removal in log(N) time. Python 3's heapq library (https://docs.python.org/3/library/heapq.html), provides this functionality. 

Creating a heap in golang, however, requires boilerplate code, below is an example implementation of a heap in golang. Why isn't this included as a standard library in golang?

```
type Heap [][]float64

func (p Heap) Len() int            { return len(p) }
func (p Heap) Less(i, j int) bool  { return p[i][2] > p[j][2] }
func (p Heap) Swap(i, j int)       { p[i], p[j] = p[j], p[i] }
func (p *Heap) Push(i interface{}) { *p = append(*p, i.([]float64)) }
func (p *Heap) Pop() interface{}   { v := (*p)[len(*p)-1]; *p = (*p)[:len(*p)-1]; return v }
```

Thanks in advance!

**Comment by cherrymui** [comment]
Hi, we don't really use our issue tracker for questions. More people will see your question, and you will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions . Thanks.

The `container/heap` package may be improved when generics is added (#43651).
