### ISSUE TITLE
x/tools/cmd/godoc: godoc suggests using arguments it doesn't understand when confused by vendoring

### ISSUE THREAD

**Issue by lpar** [golang/go#45126]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
godoc -http=localhost:6060
using module mode; GOMOD=/home/meta/go/src/github.com/cbroglie/mustache/go.mod
failed to determine if vendoring is enabled: err: exit status 1: stderr: go: inconsistent vendoring in /home/meta/go/src/github.com/cbroglie/mustache:
	github.com/yuin/goldmark@v1.3.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/mod@v0.4.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/net@v0.0.0-20210316092652-d523dce5a7f4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sys@v0.0.0-20210319071255-635bc2c9138d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/tools@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

However:

```
% godoc -http=localhost:6060 -mod=mod
flag provided but not defined: -mod
usage: godoc -http=localhost:6060
[ rest of help text omitted ]
```

**Comment by cherrymui** [comment]
Are you using golang.org/x/tools/cmd/godoc ? What version are you using? Thanks.

**Comment by cherrymui** [comment]
cc @dmitshur

**Comment by lpar** [comment]
I'm using the version installed by running `go get -u golang.org/x/tools/...` a few minutes ago.

**Comment by agnivade** [comment]
The `-mod` flag is for the underlying Go command, which you'll have to pass via the `GOFLAGS` env var. The error is coming from the underlying Go command, I agree this can be a bit confusing.

**Comment by dmitshur** [comment]
As far as I can tell godoc is doing the right thing, it is reporting that it "failed to determine if vendoring is enabled" and provides stderr output from cmd/go to provide more context (without that context, it would be very hard to understand why it failed).

It goes poorly because the cmd/go stderr output includes advice that's meant to be helpful when a human runs cmd/go directly, but is misleading when another tool runs cmd/go.

Perhaps it makes sense to file a cmd/go feature request issue to see if there's a way to invoke cmd/go in a way that doesn't include its human-facing advice. Otherwise, godoc has to either not include the details (cmd/go's stderr) when saying that it failed to determine if vendoring is enabled, or try to do work itself to filter out advice that isn't directly applicable.

@jayconrod Any thoughts or preferences on this? Have there been requests to omit human-facing advice from other tools that need to invoke cmd/go?

**Comment by jayconrod** [comment]
#30134 is an issue for machine-readable error codes in cmd/go messages. I don't think it's likely to be fixed soon though.

Maybe godoc could make it clearer this output is coming from the go command, and specifically, what command was run? At least the advice to run `go mod vendor` is useful.

**Comment by lpar** [comment]
I also don't really understand why godoc needs to look at vendored dependencies. I mean, I'm not expecting to read the documentation for those, just for my project.

**Comment by dmitshur** [comment]
godoc serves documentation for all packages in the [build list](https://golang.org/ref/mod#glos-build-list), which includes packages in the main module as well as dependencies. It follows the logic of the go command and uses automatic vendoring (see #35429).

Hopefully the inconsistent vendoring problem is rare. If someone runs into it, it means the normal go command cannot build code either. Let me know if that's not the case.

> Maybe godoc could make it clearer this output is coming from the go command, and specifically, what command was run?

This seems like a good solution. I don't see much else that can be done.

**Comment by matttproud** [comment]
I can confirm this when running `godoc` on the standard Go distribution (e.g., to prototype and preview local changes to package documentation).

**Comment by seankhliao** [comment]
@matttproud that is unrelated and you should be using the `-goroot` flag

**Comment by seankhliao** [comment]
cmd/godoc was deprecated.
