### ISSUE TITLE
x/pkgsite: ignore import path casing

### ISSUE THREAD

**Issue by pashaosipyants** [golang/go#45140]
pkg.go.dev regards the case of the package import path
see examples below

### What version of Go are you using (`go version`)?

_irrelevant_

### Does this issue reproduce with the latest release?

_irrelevant_

### What operating system and processor architecture are you using (`go env`)?

_irrelevant_

### What did you do?

_irrelevant_

### What did you expect to see?

https://pkg.go.dev/github.com/reactivex/rxgo
https://pkg.go.dev/github.com/ReactiveX/RxGo

no difference between pages by these 2 links

### What did you see instead?

https://pkg.go.dev/github.com/ReactiveX/RxGo - does not contain info about **v2**
This is actually very confusing. I've spent some time learning RxGo v1, because the link above said it's the latest version... :(

**Comment by julieqiu** [comment]
I would recommend asking the authors to  request for github.com/ReactiveX/RxG  to be excluded from pkg.go.dev, per https://go.dev/about#removing-a-package.

The reason that both versions appear is because github.com/ReactiveX/RxG does not have a go.mod file at [v1.0.0](https://github.com/ReactiveX/RxGo/tree/v1.0.0). At that version, both `github.com/ReactiveX/RxG` and `github.com/reactivex/rxg` are valid module paths. If pkg.go.dev were to redirect, it's not clear which one would be the "canonical" path.

A go.mod file was added in https://github.com/ReactiveX/RxGo/commit/0994d7fdbf949a4d679745c43ee768335c414212#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6 for v2, with the module path `github.com/reactivex/rxgo/v2`. 

Once the go.mod file was added, github.com/ReactiveX/RxGo/v2 was no longer a valid module path. https://pkg.go.dev/github.com/ReactiveX/RxGo/v2 redirects to https://pkg.go.dev/github.com/reactivex/rxgo/v2 as a result.

**Comment by jba** [comment]
Just to add to Julie's comments: case is, and always has been, significant in import paths. Thus it would be wrong for us (or any go tool) to treat paths case-insensitively.

GitHub does treat repo URLs case-insensitively, which causes the kind of problems you're seeing. The presence of a go.mod file fixes those problems by establishing the definitive import path. But without the go.mod file, pkg.go.dev (or any go tool) cannot tell what the right import path is.

**Comment by pashaosipyants** [comment]
@julieqiu @jba 
Thx guys for your answers!
Will address this issue to `ReactiveX` owners.
