### ISSUE TITLE
embed: document go.mod exclusion

### ISSUE THREAD

**Issue by codefromthecrypt** [golang/go#45197]
We have a use case for serving example go projects via `go:embed`. This is particularly important as alternatives to `go:embed` have less maintenance now that they are obviated. The problems is that the file `go.mod` is special cased and prevents serving a directory that contains it.

@opennota did research here and found this behavior to be intentional, notable "stopping at module boundaries" https://github.com/golang/go/issues/41191#issuecomment-805431807

When serving static assets, module boundaries may not be important and in fact be a surprising limitation, as surprising as files outside the directory or via symbolic links might be. Right now, the latter constraints like symbolic links are [documented](https://golang.org/pkg/embed/), but go.mod, and why it doesn't work is not entirely obvious.

Ideally, there could be a way to allow go projects to serve go projects as static assets via `go:embed`. Until then, it would be handy to change the documentation to note this surprising constraint explicitly, as it would save folks time and head scratching.

Ex a line like this "Matches for a directory containing "go.mod" is invalid and fail to build".

### What version of Go are you using (`go version`)?

1.16.2

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

amd64 darwin

### What did you do?

```go
//go:embed /path/to/goproject/*
var exfs embed.FS
```

### What did you expect to see?

I expected to have `go build` not fail

### What did you see instead?

An error like "pattern X: cannot embed directory Y in different module"

**Comment by Merovius** [comment]
Note that the primary distribution mechanism of modules are zip-files, which will only include the files that are considered part of the module. As I understand it, the zip you download from the module proxy (as opposed to using the repo) won't contain the nested module. So, module boundaries are very important - you can't embed a file that isn't there.

A workaround for your case is to name the file differently - e.g. `go.mod_` - and rename it after the fact by wrapping the `embed.FS`.

**Comment by carlmjohnson** [comment]
Name rewriting seems to come up a fair amount as a workaround for edge case problems with embedding. Someone should write a module to wrap an io.FS in a name rewriter. I volunteer to click the star button on Github and then link to it in comments when someone brings up an issue solved by rewriting, when someone else creates it.

**Comment by codefromthecrypt** [comment]
one problem with the rename `go.mod` to `go.mod_` approach is that running `go mod tidy` in the root, ends up importing whatever is in `go.mod_`. I'm not sure how to work around this, but it is annoying.

It would be nice to have a clean way to allow go:embed to opt-out of interpreting go.mod...

**Comment by Merovius** [comment]
> It would be nice to have a clean way to allow go:embed to opt-out of interpreting go.mod...

That can't work. It would mean your module can't be build from the zip-file uploaded to the mirror. Third-party embedding solutions don't have this problem only because they generate code which is compiled in - so they effectively create a copy (but in Go syntax) of the files from the nested module in the current module, so it's not a problem if the nested module isn't distributed.

This really can't be solved on the `//go:embed` side, as far as I can tell. It might be possible to add a way to distribute subdirectories with a `go.mod` without interpreting them as a module - I don't know. But as long as the files are not part of the module, `//go:embed` can't use them, full stop.

**Comment by codefromthecrypt** [comment]
great explanation, @Merovius. I didn't quite get it last time, but I do now, both the what and the why. awesome!

**Comment by crhntr** [comment]
I ran into this and decided to use go:generate to tar the embedded module and then include the tape-archived file. It worked. https://github.com/crhntr/disaster-recovery-acceptance-tests/blob/embed-fixtures/fixtures/fixtures.go#L22-L28

**Comment by carlmjohnson** [comment]
For the record, there are [zip](https://pkg.go.dev/archive/zip#Reader.Open) and [txtar](https://pkg.go.dev/github.com/josharian/txtarfs) fs.FS implementations.

**Comment by wagslane** [comment]
My use-case is that I'm building a server (in Go ofc) that serves Go projects as downloadable zip files. I have a workspace structure like this:

```
go.work
go.mod
main.go
projects/
  project-1/
    go.mod
    main.go
```

I want the top-level main.go to be able to embed nested project directories so I can zip them up at runtime and serve them over the wire. The reason it's convenient to keep the nested file named `go.mod` is because the `go.work` file at the top of the repo makes it easy to make updates to those nested projects without breaking tooling.

Are there any *simple* solutions for what I'm trying to do here? It would be *so nice* if there was a directive that allowed nested modules to be embedded (esp because they aren't a part of the package embedding them, they are essentially flat files)

**Comment by oktalz** [comment]
it really is interesting, you can embed any kind of code (python, rust, c#, ...) 
but you can't embed go code, and to be precise, you can embed go code, but not if you use go.mod

my solution (and it is a bad solution) is to have a makefile that 
- rename `go.mod` to `go.mod.embed` (then internally while serving i rename it back) - then you can embed it
- do a go build with embedded go files
- rename `go.mod.embed` back to `go.mod` 
purely because only go code projects are making problems (to repeat again, all other languages you can embed)

ziping it seems awkward although a bit easier to to.

newly added gonew tool is also not a good solution (but it is a good option) because does not support air-gapped environment

**Comment by ianlancetaylor** [comment]
While I'm sure the documentation could be improved, this is already documented.  The docs already say "Patterns must not match files outside the package's module".  If a subdirectory has a go.mod file, then it is by definition in a different module.

**Comment by francois76** [comment]
In go 1.18, the prefix "all:" has been added for the embed directive, to include dotFiles (for instance). However, go.mod directories are still not included. Maybe the "all:" prefix could also include these files too.

**Comment by seankhliao** [comment]
as explained above, modules inherently cannot contain other modules.

**Comment by fgm** [comment]
One thing which makes it weird is that AIUI the contents of `testdata` directories are not compiled so they should not be considered modules, but they still are.
```
/
/go.mod
/demo.go
/testdata
/testdata/go.mod
/testdata/other.go
```

In this layout, `testdata` is skipped by `./...` patterns like `go list ./...` but if `demo.go` tries to embed `testdata/` it is still considered as another module although it is not handled as code.

**Comment by Merovius** [comment]
"Not being compiled" is not the same as "not being part of the module". They are still used in tests and tests can be run on downloaded modules, so `testdata` needs to be included in the module zip.

**Comment by codefromthecrypt** [comment]
the last referenced CL will close this out to my satisfaction. thanks!
