### ISSUE TITLE
cmd/go2go: Compose generic types by interface

### ISSUE THREAD

**Issue by jumale** [golang/go#45310]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +a4b4db4cde Mon Mar 22 22:48:13 2021 +0000 darwin/amd64
</pre>

### What did you do?

Having a validator type which can validate some value `T` and return `true/false`:
```go
type Validator[T any] func(T) bool
```
and a couple of its implementations for some common interfaces:
```go
func hasContent(v fmt.Stringer) bool {
	return len(v.String()) > 0
}

func isRed(v color.Color) bool {
	r, g, b, _ := v.RGBA()
	return r == 0xffff && g == 0 && b == 0
}
```
and having some value which implements both `fmt.Stringer` and `color.Color`  interfaces:
```go
type Text string

func (t Text) String() string {
	return string(t)
}

func (Text) RGBA() (r, g, b, a uint32) {
	return 0, 0, 0xffff, 0
}
```
then it's possible to validate our value with both of the existing validators:
```go
text := Text("foo")
fmt.Println(hasContent(text))
fmt.Println(isRed(text))
```
but it's not possible to collect these validators into a generic list of validators for the `Text` type:
```go
textValidators := []Validator[Text]{
	hasContent,
	isRed,
}
```

### What did you expect to see?

Every validator, which is applicable to the `Text` type, can be also put into a generic collection for this type.

### What did you see instead?

Compiling errors:
```bash
$ ../go-mainline/bin/go tool go2go build
type checking failed for main
main.go2:36:3: cannot use hasContent (value of type func(v fmt.Stringer) bool) as Validator[Text] value in array or slice literal
main.go2:37:3: cannot use isRed (value of type func(v color.Color) bool) as Validator[Text] value in array or slice literal
```

### Additional info

Looking at the compiled code in `main.go`, I understand the reason why it's not possible - because we end up with different signatures of functions which do not match. But feature-wise it does not sound right to me - i.e. if `T` passes requirements for `A` and `B` - then I'd expect to be able to group `A` and `B` under a common type.

There is a workaround to make it work by wrapping every rule with adapting functions:
```go
textValidators := []Validator[Text]{
	func (v Text) bool {
		return hasContent(v)
	},
	func (v Text) bool {
		return isRed(v)
	},
}
```
As you can see, in this example we actually do not add any additional mappings or conversions - we just proxy the value from adaptor to the target function, and it actually solves the problem.
So, I was wondering if it could be possible to make compiler a bit smarter to auto-resolve such cases?

<details>
<summary>Full example</summary>

```go
// main.go2go
package main

import (
	"fmt"
	"image/color"
)

func main() {
	text := Text("foo")

	fmt.Println(hasContent(text))
	fmt.Println(isRed(text))

	textValidators := []Validator[Text]{
		hasContent,
		isRed,
	}
	fmt.Println(textValidators)
}

type Validator[T any] func(T) bool

func hasContent(v fmt.Stringer) bool {
	return len(v.String()) > 0
}

func isRed(v color.Color) bool {
	r, g, b, _ := v.RGBA()
	return r == 0xffff && g == 0 && b == 0
}

type Text string

func (Text) RGBA() (r, g, b, a uint32) {
	return 0, 0, 0xffff, 0
}

func (t Text) String() string {
	return string(t)
}
```
</details>

**Comment by ianlancetaylor** [comment]
What you suggest doesn't work because, as you know, the type of `hasContent` is `func(fmt.Stringer) bool` but the type of `Validator[Text]` is `func(Text) bool`.  So what you are suggesting is form of covariance, which Go intentionally does not support (https://golang.org/doc/faq#covariant_types).

More generally, you want to put functions of different types into your `textValidators` slice.  I don't think we are ever going to permit that.  Those functions are called in different ways, because they require an implicit conversion to different interface types.  If they are stored in the same slice, there is no place to write that conversion.

If we supported expressing convertibility in a constraint then you could use a generic wrapper function, but we don't (https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#no-way-to-express-convertibility).  Still, I think that would be a more profitable approach than the one you suggest here.

I'm going to close this because I don't see a path forward.
