### ISSUE TITLE
"crypto/md5" security issues

### ISSUE THREAD

**Issue by luoyuctl** [golang/go#45486]
### What version of Go are you using (`go version`)?

$ go version 1.16.2

### Does this issue reproduce with the latest release?

true

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

when i run golangci-lint , i found this

G501: Blocklisted import crypto/md5: weak cryptographic primitive (gosec)
        "crypto/md5"

G401: Use of weak cryptographic primitive (gosec)
                h := md5.New()

Why do official code testing tools treat official package code as unsafe?
Can you give me advice to resolve it ? plz.

### What did you expect to see?
golangci-lint run pass

### What did you see instead?

golangci-lint run failed

**Comment by ulikunitz** [comment]
[RFC6151](https://tools.ietf.org/html/rfc6151):

MD5 is no longer acceptable where collision resistance is required
such as digital signatures.  It is not urgent to stop using MD5 in
other ways, such as HMAC-MD5; however, since MD5 must not be used for
digital signatures, new protocol designs should not employ HMAC-MD5.
Alternatives to HMAC-MD5 include HMAC-SHA256 [HMAC] [HMAC-SHA256] and
[AES-CMAC] when AES is more readily available than a hash function.

[Wikipedia](https://en.wikipedia.org/wiki/MD5):

On 24 December 2010, Tao Xie and Dengguo Feng announced the first published single-block (512-bit) MD5 collision.[14] (Previous collision discoveries had relied on multi-block attacks.) For "security reasons", Xie and Feng did not disclose the new attack method. They issued a challenge to the cryptographic community, offering a US$10,000 reward to the first finder of a different 64-byte collision before 1 January 2013. Marc Stevens responded to the challenge and published colliding single-block messages as well as the construction algorithm and sources.[15]

**Comment by dominikh** [comment]
> Why do official code testing tools treat official package code as unsafe?

Neither golangci-lint nor gosec are official, they are maintained by third parties.

**Comment by seankhliao** [comment]
These are not part of the Go project

**Comment by luoyuctl** [comment]
> [RFC6151](https://tools.ietf.org/html/rfc6151):
> 
> MD5 is no longer acceptable where collision resistance is required
> such as digital signatures. It is not urgent to stop using MD5 in
> other ways, such as HMAC-MD5; however, since MD5 must not be used for
> digital signatures, new protocol designs should not employ HMAC-MD5.
> Alternatives to HMAC-MD5 include HMAC-SHA256 [HMAC] [HMAC-SHA256] and
> [AES-CMAC] when AES is more readily available than a hash function.
> 
> [Wikipedia](https://en.wikipedia.org/wiki/MD5):
> 
> On 24 December 2010, Tao Xie and Dengguo Feng announced the first published single-block (512-bit) MD5 collision.[14] (Previous collision discoveries had relied on multi-block attacks.) For "security reasons", Xie and Feng did not disclose the new attack method. They issued a challenge to the cryptographic community, offering a US$10,000 reward to the first finder of a different 64-byte collision before 1 January 2013. Marc Stevens responded to the challenge and published colliding single-block messages as well as the construction algorithm and sources.[15]

thx！
