### ISSUE TITLE
cmd/go: malformed import path app/系统模块/后台/内部模块/逻辑 invalid char '系'

### ISSUE THREAD

**Issue by xushushun** [golang/go#45507]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
go run

### What did you expect to see?
By compiling

### What did you see instead?
malformed import path app/系统模块/后台/内部模块/逻辑 invalid char '系'

### Notes:
This issue should be similar to the [#43985](https://github.com/golang/go/issues/43985)

Since my system language is Chinese, Chinese often appears in the path. After upgrading version 1.16, many projects cannot be compiled

**Comment by seankhliao** [comment]
Seems unfortunate, see also #44970 #43052

cc @bcmills @jayconrod

**Comment by jayconrod** [comment]
cc @matloob as well on cmd/go issues.

Sorry, but for now at least, this is working as expected in 1.16. [`module.CheckImportPath`](https://pkg.go.dev/golang.org/x/mod/module#CheckImportPath) lists the character restrictions on import paths. Those restrictions didn't technically change in 1.16, but the go command started checking them for packages in the main module, in order to avoid surprising failures when publishing a module for the first time.

[Unicode restrictions](https://pkg.go.dev/golang.org/x/mod/module#hdr-Unicode_Restrictions) gives the rationale for the restrictions. Essentially, we're concerned that files will get different names on different file systems, and may end up overlapping or being compiled differently. As stated there, this may be relaxed in the future.

**Comment by xushushun** [comment]
> [Unicode restrictions](https://pkg.go.dev/golang.org/x/mod/module#hdr-Unicode_Restrictions) gives the rationale for the restrictions. Essentially, we're concerned that files will get different names on different file systems, and may end up overlapping or being compiled differently. As stated there, this may be relaxed in the future.

I understand, but at present, this limitation has a great probability of causing trouble to non English operating system developers. Can I change the error into a warning, or add the relevant configuration switch here

**Comment by jayconrod** [comment]
We generally avoid reporting warnings or adding configuration options if we can avoid it.

I do think we should expand the set of allowed characters though. I've opened #45549 to come up with a broader set of allowed characters that won't cause compatibility problems.

**Comment by xushushun** [comment]
> I do think we should expand the set of allowed characters though. I've opened #45549 to come up with a broader set of allowed characters that won't cause compatibility problems.
It would be great if we could expand the allowed character set. Thank you

**Comment by konglong87** [comment]
also  do this error,now back to 1.15,,,cry
