### ISSUE TITLE
x/vulndb: new repository

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#45519]
Per https://golang.org/design/draft-vulndb, I am creating golang.org/x/vulndb following the instructions at https://golang.org/wiki/CreatingSubRepository.

This repository will host the Go Vulnerability Database source of truth, and the tooling that generates the client-facing database.

Unlike other repositories, github.com/golang/vulndb will have its own issue tracker, used to triage vulnerability reports.

Until a proposal is filed and approved for the Checksum Database, nothing in this repository will be covered by any compatibility promise, and the repository might get changed, renamed, or deleted.

**Comment by dmitshur** [comment]
[golang.org/x/vulndb](https://golang.org/x/vulndb) is now live. Please comment or reopen if there's anything more.

I'll mention that since this x repo has its own issue tracker, you may or may not be interested in turning on some of GopherBot's general gardening tasks (see list [here](https://github.com/golang/build/blob/89ed42092221f729d3712ad902d7302cb38d8f4a/cmd/gopherbot/gopherbot.go#L372-L376)), as controlled by [`gardenIssues`](https://github.com/golang/build/blob/89ed42092221f729d3712ad902d7302cb38d8f4a/cmd/gopherbot/gopherbot.go#L391-L398).
