### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by I-Cat** [golang/go#45613]
### What is the URL of the page with the issue?
 https://pkg.go.dev/cloud.google.com/go/kms/apiv1?tab=licenses
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/68921721/115128021-ea59ae00-9fa8-11eb-9171-6c4dd09a84e9.png)

^^ as above 
 
 
### What did you do?
 Went to the website
expected a secure urls
I got a licence with an insucure url
http://
There is Also many other http://    that should be https://
Best Practices is to make urls https://

Go to the url expect https://
Get http:// url refrences in the go lang url repo that I provided above

### What did you expect to see?
 Well honestly a secure web urls aka https:// 

 
 
### What did you see instead?
 Found many http:// url instead

**Comment by smasher164** [comment]
> I got a license with an insucure url

That is the official text of the Apache 2.0 License: https://www.apache.org/licenses/LICENSE-2.0.txt. What you're seeing is the license text displayed verbatim. Or do you mean to say the pkgsite should modify the license text?

**Comment by I-Cat** [comment]
> > I got a license with an insucure url
> 
> That is the official text of the Apache 2.0 License: https://www.apache.org/licenses/LICENSE-2.0.txt. What you're seeing is the license text displayed verbatim. Or do you mean to say the pkgsite should modify the license text?

@smasher164

```
The Licence file you showed me is not hosted by https://www.apache.org
The Licence File is being hosted by https://sectigo.com
This licence looks out dated too as it states it is for the year 2004
Also new web browers and devices block http:// requests
```

**Comment by smasher164** [comment]
> The Licence file you showed me is not hosted by https://www.apache.org

I the license URL definitely displays **apache.org** as its domain name, unless I'm missing something very obvious. You can also check by going to https://www.apache.org/licenses/LICENSE-2.0, and seeing the link to the text version there.

Regardless, I don't see it as the responsibility of the documentation site to modify a license in a package's repository. If you have an issue with the package's license, I suggest you contact the package authors. Because of that, I will be closing this issue.
