### ISSUE TITLE
how to instantly release memeory to system from tcmalloc memory pool

### ISSUE THREAD

**Issue by Jun10ng** [golang/go#45616]
Hi Go team,

AFAIK tcmalloc will temporarily hold some idle memory resources. 
Is there any way i can instant release these idle memory to System like calling `MallocExtension::instance()->ReleaseFreeMemory()` in C++.
Thanks.

**Comment by ALTree** [comment]
Hi,

Go doesn't use tcmalloc, it has a [memory allocator written in Go itself](https://github.com/golang/go/blob/master/src/runtime/malloc.go). 

The runtime will slowly release unused memory pages back to the OS, but I don't think there's a way to force it to do so. Closing here, since I believe I did answer your question (and we don't use the github issue tracker for questions, it's just for bugs in Go and proposals).
