### ISSUE TITLE
spec: clarify that short variable redeclaration cannot redeclare the same variable multiple times

### ISSUE THREAD

**Issue by griesemer** [golang/go#45652]
It is not obvious from the spec on [short variable declarations](https://golang.org/ref/spec#Short_variable_declarations) that
```Go
package p

func _() {
	var b int
	a, b, b := 1, 2, 3
	_ = a
	_ = b
}
```
should be invalid: the variable `b` is redeclared, but it is redeclared twice. The compiler reports an error but `go/types` and `types2` do not. It makes sense to disallow it as it's likely an error (and the same effect can be achieved in different ways).

Will fix the `go/types` and `types2` issue as part of #43087.

**Comment by griesemer** [comment]
cc: @findleyr 
cc: @mdempsky

**Comment by ianlancetaylor** [comment]
gccgo reports:

```
foo.go:5:15: error: ‘b’ repeated on left side of :=
    5 |         a, b, b := 1, 2, 3
      |               ^
```

**Comment by mdempsky** [comment]
Agreed, the current spec wording seems to support go/types behavior. But if cmd/compile and gccgo already make it an error, I support codifying that to make the risk of accidental reuse less likely. Users can just as easily write `a, _, b := 1, 2, 3` if they needed.

**Comment by findleyr** [comment]
Agree that the language should be clarified. I think it's at least _implicit_ in the current wording that names should not be repeated, in that it is "shorthand for a regular variable declaration with initializer expressions but no types". Since names cannot be repeated in a normal variable declaration, they shouldn't be repeated in a short variable declaration, notwithstanding the allowance for redeclaration of names earlier in the block.

**Comment by mdempsky** [comment]
> Since names cannot be repeated in a normal variable declaration

I don't think that's directly stated though, no? I believe it's just a consequence of "No identifier may be declared twice in the same block," whereas a short variable declaration does not actual declare identifiers that have already been declared.

--

Incidentally, it seems a bit confusing that https://golang.org/ref/spec#Short_variable_declarations defines:

> Unlike regular variable declarations, a short variable declaration may *redeclare* variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-blank variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original.

because earlier https://golang.org/ref/spec#Declarations_and_scope said

> An identifier declared in a block may be redeclared in an inner block.

That is, we have both a defined term "redeclare" that actually means *not* [declaring](https://golang.org/ref/spec#Declarations_and_scope) something; but then we also use the term "redeclare" to mean "declare again in a different scope".
