### ISSUE TITLE
crypto/rsa: pss with zero salt length for backward compatiblity with openssl

### ISSUE THREAD

**Issue by karanjmu92** [golang/go#45684]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes.

### What did you do?

I have an application which is doing rsa pss sign using openssl and it is allowing zero salt length. Go crypto handles zero length in a different way, it maximizes the salt length.
I am migrating it to go crypto and there might be users who are using zero salt length in openssl and it may break for them.

### What did you expect to see?

I expected it to work in same way as openssl because it may break some users.

### What did you see instead?

I see that go crypto does not allow zero salt length, it maximizes the salt length when zero is passed for salt length.

**Comment by cherrymui** [comment]
cc @FiloSottile 

This may be working as intended.

**Comment by FiloSottile** [comment]
Indeed, there is no way to cause a signature to be generated with a zero-length salt, because 0 is the value of PSSSaltLengthAuto, which we can't change now. I believe we do verify zero-length salt signatures generated by other systems. Is there a compatibility issue that requires generating, not just verifying, zero-length salt signatures?
