### ISSUE TITLE
debug/gosym: (*Table).PCToLine reports wrong file/line for call site PCs

### ISSUE THREAD

**Issue by eandre** [golang/go#45900]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/eandre/Library/Caches/go-build"
GOENV="/Users/eandre/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/eandre/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/eandre"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/opt/homebrew/Cellar/encore/0.13.2/libexec/runtime/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hc/w9bwjfwd69dd6_6thw6xqmkw0000gn/T/go-build515741722=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I used `debug/gosym.(*Table).PCToLine` to get the file and line number corresponding to a PC returned from `runtime.Callers`.

### What did you expect to see?

 I expected `PCToLine` to report the same information as `runtime.CallersFrames`. However, for some PCs they differed.

From `runtime.CallersFrames` (this is the correct output):

```
PC=3988140: /Users/eandre/tmp/demo/board/board.go:99: encore.app/board.Get
PC=3952120: /Users/eandre/src/encr.dev/compiler/runtime/storage/sqldb/sqldb.go:320: encore.dev/storage/sqldb.(*Row).Scan
PC=3988264: /Users/eandre/tmp/demo/board/board.go:103: encore.app/board.Get
PC=3988456: /Users/eandre/tmp/demo/board/board.go:105: encore.app/board.Get
PC=3988504: /Users/eandre/tmp/demo/board/board.go:106: encore.app/board.Get
```

(PC here refers to the address offset from the start of the text segment)

### What did you see instead?

From `debug/gosym.(*Table).PCToLine`:
```
PC=3988140: /Users/eandre/tmp/demo/board/board.go:99 (encore.app/board.Get)
PC=3952120: /Users/eandre/src/encr.dev/compiler/runtime/storage/sqldb/sqldb.go:320 (encore.dev/storage/sqldb.(*Row).Scan)
PC=3988264: /Users/eandre/tmp/demo/board/board.go:104 (encore.app/board.Get)
PC=3988456: /Users/eandre/src/encr.dev/compiler/runtime/beta/errs/builder.go:23 (encore.app/board.Get)
PC=3988504: /Users/eandre/tmp/demo/board/board.go:106 (encore.app/board.Get)
```

I compared the implementation of parsing the symbol table in the `debug/gosym` and `runtime` packages.

It appears `debug/gosym` is missing this if statement: https://github.com/golang/go/blob/master/src/runtime/symtab.go#L95-L101

If I add a corresponding if statement to `debug/gosym`, the issue is resolved on my end, but would be good to verify this fix with somebody who is more familiar with the code.

**Comment by cherrymui** [comment]
The PCs you got runtime runtime.Callers are the function return addresses, which is the instruction immediately after the CALL instruction. The runtime function subtracts the PC by one so it will get the PC of the CALL instruction, which is usually what people want.

The debug/gosym package uses the actual PC instead. It should not the -1 because it should not assume the input PC is a return PC, nor you're trying to get back to the CALL instruction. If you want that semantic, you'd want to do the -1 yourself. Thanks.

**Comment by eandre** [comment]
That's a bit surprising because the `*Func` reported corresponds to the correct function, but the file and line do not. Is that ever the expected result for those PCs? I'm happy to do the subtraction myself in that case, but the API is a bit awkward there's no way to avoid the `*Func` lookup twice (once to determine whether to subtract `-1`, and then once more within `(*Table).PCToLine`).

**Comment by cherrymui** [comment]
The function is correct because it is the same function.

The runtime function and the debug/gosym package serve different purpose. The runtime function is specific to traceback. The debug/gosym package is not. You can look up for arbitrary PCs. Only for the traceback case the -1 is the right thing to do. If you know you are getting the PCs from a backtrace, you probably can always do the -1 (the runtime function has a condition to handle signals, like if you're taking a traceback from a signal handler triggered by a panic. If you know that's not your case you probably can skip the check). Otherwise never.

**Comment by eandre** [comment]
I'm not sure what you mean by "it is the same function". The file and line information refer to a completely different file, so those don't seem consistent with the `*Func` in any plausible interpretation. Either way, if you believe this is correct I have no problem doing the subtraction myself.

**Comment by cherrymui** [comment]
With inlining, the file and line number can change, but it is still in the same (machine code) function.

Yes, runtime.FuncForPC can be used to look up arbitrary PCs. But I'm not sure I understand your question.
