### ISSUE TITLE
go/types, types2: TestStdlib is accidentally skipped

### ISSUE THREAD

**Issue by findleyr** [golang/go#46027]
I noticed that testing go/types had recently gone from 8s->1.5s, which bisected to https://golang.org/cl/276272.

That CL has a change to go/types' `TestStdlib`, which purports to skip submodules, but actually skips everything (`src` has a `go.mod`).

I'm not sure how that change relates to go/types, so I'm not sure if I can back out this modification.

CC @griesemer @FiloSottile @katiehockman

**Comment by dmitshur** [comment]
Nicely spotted. Also CC @bcmills.

**Comment by findleyr** [comment]
This also affects cmd/compile/internal/types2.

I guess the intent is to skip src/crypto/ed25519/internal/edwards25519/field/_asm.  If that's necessary we should probably just skip that one directory, along with a more detailed explanation of why skipping is necessary.

**Comment by FiloSottile** [comment]
Oh good catch! Sorry about that 😓 

The skip was meant for nested, non-std/cmd submodules, which might not have all source vendored and available. I wanted to avoid special-casing that one module to make it easier to use modules to track versions of code generator tools (without shipping them and their entire dependency tree with the Go project, since that code doesn't contribute to the build.)

Feel free to fix that test however you see fit, or I will look into it tomorrow.

**Comment by findleyr** [comment]
No worries, I'll send a fix.

For now I'll just skip this one module. If this type of thing becomes a pattern we can re-evaluate.
