### ISSUE TITLE
x/build/cmd/gopherbot: don't mark issues as fixed if the “fix” verb is part of a larger sentence

### ISSUE THREAD

**Issue by bcmills** [golang/go#46081]
Gopherbot attempted to close #45999 in response to [CL 317300](https://golang.org/cl/317300), for which the commit message included this fragment:

> ```
> If we fix #45999, we will be able to make these error checks more
> precise.
> ```

No human fluent in English would construe that sentence as intending to “fix #45999”, so Gopherbot shouldn't parse it that way either. One simple heuristic might be to ignore the word “fix” if it is not the first word on the line (or perhaps the first word in its sentence.)

CC @golang/release

**Comment by dmitshur** [comment]
This behavior is implemented by GitHub and not GopherBot per se. See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword and https://github.blog/2013-01-22-closing-issues-via-commit-messages/.

This GitHub behavior has been this way for years, and I've observed it some intentional edge case uses of it (such as writing "likely fixes #nnn" with the intention of the issue still getting closed, and later reopened if turns out more is needed). To avoid an issue being closed, the exact phrase needs to be avoided.

I don't think it's feasible for us to fix.

**Comment by dmitshur** [comment]
Closing but let me know if I missed something.
