### ISSUE TITLE
cmd/compile: panicking composite literals not properly flushed to globals

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#4608]
<pre>This program causes an inconsistent memory state:

package main

import &quot;fmt&quot;

type L struct {
        x, y int
}

var x L

func main() {
        foo(0)
        fmt.Println(x)
}

func foo(bar int) {
        defer func() {
                _ = recover()
        }()
        x = L{ 1, 1/bar}
}

The expected output from this program is {0 0}, but it outputs {1 0} instead.

Potential solution is evaluating the non-const parts of the literal into temporaries
before copying the static data.</pre>

**Comment by odeke-em** [comment]
Thank you for reporting this issue @DanielMorsing and for the patience!

Indeed this was an inconsistency, but @cherrymui's CL https://go-review.googlesource.com/c/go/+/36410/ for Go1.8 in 2017, appears to have fixed the issue. To me the issue seems to have been incorrect writer barriers for globals before panics were evaluated.

In Go1.8 and later, we now get {0, 0} as per https://play.golang.org/p/f2SppbMf9bc which as per Go1.13.7 prints
```shell
go1.13.7
{0 0}
```

I shall close this issue now.
