### ISSUE TITLE
%v verb of Printf doesn't print "integer" float's properly

### ISSUE THREAD

**Issue by purpleidea** [golang/go#46118]
### What version of Go are you using (`go version`)?

<pre>
playground
</pre>

### Does this issue reproduce with the latest release?

Yes, or whatever is on playground.

###  Code?

https://play.golang.org/p/tYrQOwJFKal

aka
<details>
<pre>
package main

import (
	"fmt"
)

func main() {
	f := float64(42.0) // I'm really sure this is a float

	// from: https://golang.org/pkg/fmt/
	// The default format for %v is:
	// ... float32, complex64, etc: %g
	// Okay, what's %g ?
	// %e for large exponents, %f otherwise. Precision is discussed below.
	// Okay what's %f ?
	// %f	decimal point but no exponent, e.g. 123.456

	// So before you run this, what should all of these print?
	// Do you expect them to all be the same?

	fmt.Printf("%f\n", f)
	fmt.Printf("%g\n", f)
	fmt.Printf("%v\n", f)
	fmt.Printf("%+v\n", f)

}

</pre></details>

### What did you do?
Ran the above code.

### What did you expect to see?
I expect either the values to all be 42.0 (with some number of zeros) or the docs to be clearer about explaining why this isn't the case for %v

### What did you see instead?

%v prints "42" instead of "42.0"

**Comment by purpleidea** [comment]
From https://golang.org/pkg/fmt/ annotated with my comments:

	// The default format for %v is:
	// ... float32, complex64, etc: %g
	// Okay, what's %g ?
	// %e for large exponents, %f otherwise. Precision is discussed below.
	// Okay what's %f ?
	// %f	decimal point but no exponent, e.g. 123.456

	// So before you run this, what should all of these print?
	// Do you expect them to all be the same?

**Comment by ALTree** [comment]
I think you missed a detail:

> Okay, what's %g ?
> %e for large exponents, %f otherwise. Precision is discussed below.

Note:

> *Precision is discussed below.*

So you're using `%g == %f` in your inference chain, but that's not necessarily the case, because precision and default values. Below:

> The default precision for %f [..] is 6; for %g it is the smallest number of digits necessary to identify the value uniquely. 

So when you manually use `%f`, it's actually `.6f%`, so you get `42.000000`, but when `%v` defaults to `%g` for floats then the precision is "the smallest number of digits necessary to identify the value uniquely", which for `42.0` is `42`. If you start with `42.123456` they all print the same value.

The documentation doesn't claim `%f == %g` (which in of course incorrect); it does specifically note that the difference between the two is the way precision is handled.

**Comment by purpleidea** [comment]
@ALTree I see. I guess that's what I missed then. Sorry for the noise. It came up as something unexpected, because as %v is often used for debugging, we expected to see 42.0 or something to let us know it was actually a float. Oh well, thanks for your time!
