### ISSUE TITLE
encoding/json: Panic when parsing JSON strings containing slashes

### ISSUE THREAD

**Issue by bt** [golang/go#46115]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I'm trying to parse some SSL certificate metadata and encountered this error when decoding/unmarshaling from a JSON file containing the following input string:

```
"CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\, Inc.,L=Scottsdale,ST=Arizona,C=US"
```

After further investigation, I found it to be related to the following lines: https://github.com/golang/go/blob/master/src/encoding/json/scanner.go#L340-L343 -- it's expecting that a slash will correspond to an escaped quote `"` character, but this is not always the case.

Relevant Go Playground Link: https://play.golang.org/p/tovEHscZFes

### What did you expect to see?

The above input string should be parsed to:

```
CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\, Inc.,L=Scottsdale,ST=Arizona,C=US
```

### What did you see instead?

You will get the following panic:

```
panic: invalid character ',' in string escape code
```

**Comment by davecheney** [comment]
Thank you for raising this issue. It looks like the panic is coming from your error handling code, not the json package. What is the issue here? Is it the panic, or a difficulty parsing json? If it’s the latter the issue tracker may not be the best place for this discussion. 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://golang.org/s/proposal-process) only.

For asking questions, see:

* [Stack Overflow](https://stackoverflow.com/questions/tagged/go) with questions tagged "go"

* [The Go Forum](https://forum.golangbridge.org/), a web-based forum

* [Gophers Slack](https://gophers.slack.com), use the [invite app](https://invite.slack.golangbridge.org/) for access. The `#general` channel is a good starting point.

* [Go Community on Hashnode](https://hashnode.com/n/go) with questions and posts tagged with "go"

* [The golang-nuts mailing list](https://groups.google.com/d/forum/golang-nuts)

* **IRC** channel #go-nuts on Freenode

**Comment by bt** [comment]
Hi @davecheney, thanks for the reply.

I think I might be experiencing a bug with an upstream library that relies on `encoding/json` but the error is making it look like it's a bug with `encoding/json`. Let me do a bit more investigation on my part and confirm.

**Comment by davecheney** [comment]
`\,` is not a valid json string. It must be encoded.
