### ISSUE TITLE
x/build/cmd/releasebot: add an upper limit to the total log posted to GitHub

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#46130]
During a release, releasebot will post the release log as GitHub comments. In very rare occasions the release log will grow to an extremely long length which will mostly contain useless information. As originally suggested in [CL 318070](https://go-review.googlesource.com/c/build/+/318070/comment/07294631_319d0660/), we should agree upon a limit on how much of the log we post to GitHub.

@golang/release

**Comment by dmitshur** [comment]
I think it's hard to determine what an optimal value for this is, given how infrequently it may happen. I wanted to suggest 2 MB to match our current limit in x/build logs, but imagining releasebot posting 32 full-length comments (2 MB / 64 KB = 32) in an issue seems a bit too much (these will also contribute to making maintner dataset larger). Perhaps 4? Anything is better than unbounded IMO, and the human release coordinator can always add more context if needed.

Sorry about the unfortunate timing on the review comment and thanks for following up!

**Comment by dmitshur** [comment]
Issue #47148 is a data point involving fairly verbose output, spanning 20 comments. Perhaps it can help make a decision here.

As a straw proposal, how about if `len(bodyParts) <= 4`, post them all, otherwise post the first 3 and the last one, since there may be more interesting stuff on the last page.
(If there's something exceptionally interesting in the middle, the release coordinator can access it from the terminal and share as needed.)

**Comment by dmitshur** [comment]
releasebot has been superseded by relui, and relui doesn't post to GitHub issues, so this issue no longer applies. Closing.
