### ISSUE TITLE
x/pkgsite: Third party badges rendering inconsistently between Github readme and package site

### ISSUE THREAD

**Issue by ross-spencer** [golang/go#46191]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/ross-spencer/wikiprov#section-readme

### What is your user agent?

* `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Screenshot

![image](https://user-images.githubusercontent.com/1880412/118390149-9075f380-b5fb-11eb-9942-c8dedbbba6f5.png)

vs. Github:

![image](https://user-images.githubusercontent.com/1880412/118390172-a4215a00-b5fb-11eb-94fc-6d7ce3518488.png)

### What did you expect to see?

The different badges shown on the README.md rendering on pkg.go.dev in the same way. 

### What did you see instead?

The Go report card badge does not render showing just the underlying placeholder structure in HTML. 

### Related issues

There seem to be related issues around markdown rendering, relative images, or other badge display issues when using non-markdown. I can't quite figure out how directly related they are to this particular issue (if confirmed).

**Comment by crossphoton** [comment]
Hi,
This seems to be fine to me.
Try loading the page again. If it doesn't appear try hard refreshing [Ctrl+Shift+R].

This can happen mainly due to some connection issue.
You can also use your browser's dev tools to investigate more at personal level.

![image](https://user-images.githubusercontent.com/38404790/118412524-27a08100-b6b8-11eb-9dca-98635de4fb9b.png)

**Comment by ross-spencer** [comment]
Thanks @crossphoton I am seeing the same. I appreciate the response. Looks like I was a little hasty submitting this one 😊
