### ISSUE TITLE
[dev.fuzz] cmd/go: add fuzzseed flag for deterministic testing

### ISSUE THREAD

**Issue by katiehockman** [golang/go#46221]
Some of the fuzz tests may be improved with the introduction of a `-fuzzseed` flag. This isn't something we would expect the average developer running with `-fuzz` to ever need, but would allow the mutation engine to be seeded with the same value every run. This could allow some of the tests of the fuzzing infrastructure to become more deterministic, and allow us to test things more exactly without introducing flakes.

We don't necessarily have to expose these options in the CLI; they could be in GODEBUG or something similar. Deterministic options are usually good for debugging though, and these both might come in handy for users.

**Comment by josharian** [comment]
Is there any expectation of stability across Go versions? That could effectively prevent making any improvements to the fuzzing engine.

**Comment by AlekSi** [comment]
https://github.com/golang/go/issues/28592 introduced a similar flag for testing. Maybe that flag can be renamed to `-seed` and used by both normal testing and fuzzing until it is too late? I'm a bit worried about UX of having several similar flags.

**Comment by katiehockman** [comment]
@josharian I'm not sure I understand your question. Could you clarify?
This `-fuzzseed` flag wouldn't be used by default unless it's set. The default behavior is that the fuzzing engine generates a new seed each time it runs. How could this prevent improvements to the fuzzing engine?

**Comment by josharian** [comment]
If I understand correctly, the goal of `-fuzzseed` is reproducibility: If I set `-fuzzseed`, the same thing happens as happened last time. In order to achieve that, the fuzzing engine needs to behave the same: The same number of calls to the PRNG, interpret those results the same way, and so on. But this would prevent us from (say) adding a new mutator, as that would cause different PRNG calls.

I'm concerned that the request for perfect reproducibility would also prevent concurrent fuzzing, as the only way to guarantee the same results would be to avoid scheduler-induced randomness.

This also would mean that we'd have to pay a higher execution cost every time we want to iterate over a map, and a higher coding overhead cost every time we make a change, to think about reproducibility.

The compiler has perfect reproducibility. It's worth it, but the cost is definitely quite high. However, the compiler is a bit different than a fuzzing engine; a fuzzing engine, by design, is supposed to have a significant amount of randomness, and throughput is paramount to success. I'm worried we'll end up painting ourselves into a corner with this flag, or that the flag's guarantees will end up being so weak as not to be useful.

All that is to say, I think I'd like to know exactly what "deterministic" means in this context. :)

**Comment by katiehockman** [comment]
This was done in https://go-review.googlesource.com/c/go/+/313651
