### ISSUE TITLE
x/build/cmd/coordinator: misc/cgo/testplugin.TestIssue25756pie fails on darwin-arm64 builder deterministically but only in sharded mode

### ISSUE THREAD

**Issue by cherrymui** [golang/go#46239]
CL https://go-review.googlesource.com/c/go/+/319489 added a test to misc/cgo/testplugin. The test is failing in the darwin-arm64 builder.

Interestingly, I cannot reproduce the failure locally on a darwin-arm64 machine, by running `cd GOROOT/misc/cgo/testplugin; go test`. I also cannot reproduce the failure on gomote, by running `gomote run $VM go/bin/go tool dist test testplugin` or `gomote run $VM go/src/all.bash`.

But it does fail consistently on the build dashboard and with trybot ( https://storage.googleapis.com/go-build-log/d4df70bf/darwin-arm64-11_0-toothrot_5af7c061.log )

Maybe there is some unusual setting on the builder?

cc @toothrot  @cagedmantis @dmitshur

**Comment by dmitshur** [comment]
This test has also passed for me locally on an M1 machine with macOS 11.3.1, so it seems like a builder issue. I'll try to look at why it's failing in post-submit but not via gomote.

**Comment by dmitshur** [comment]
The test also passes on the builder as invoked during release tests (i.e., with something like `release -target=darwin-arm64 -version=go1.17beta123 -watch -rev=ff7d5f97b3375a87e2de90f42e96983e5f0f95a4`). This supports a theory that the problem could be related to coordinator using SplitMakeRun mode (where it compiles, then snapshots, then run the tests) during TryBots and post-submit builds.

**Comment by bcmills** [comment]
> This supports a theory that the problem could be related to coordinator using SplitMakeRun mode

That suggests a possible connection to #33598.

**Comment by dmitshur** [comment]
I've investigated this more today. The test is passing on a physical darwin/arm64 machine, via sequential (non-sharded) test execution, when executed on its own, but failing specifically when executed by cmd/coordinator in sharded test mode on this builder. It's really nice that it fails so reproducibly and gives us a chance to investigate it, as it's likely the root cause for this problem may shared across more builder issues, though the feedback loop is quite slow.

Getting to the bottom of it will take longer, so I'll send a CL to skip the test for now, so that its failure doesn't mask other darwin/arm64 regressions in the mean time.

**Comment by heschi** [comment]
I confirmed that the test passes on MacOS 12 as a simple all.bash invocation. I'll add a skip matching https://go-review.googlesource.com/c/go/+/321349/.

**Comment by ianlancetaylor** [comment]
This seems to be fixed.  We are running the test and nobody is complaining.
