### ISSUE TITLE
x/tools/gopls: support folding regions in block comments

### ISSUE THREAD

**Issue by stamblerre** [golang/go#46253]
See the issue in the vscode-go repository: https://github.com/golang/vscode-go/issues/1511.

> **Is your feature request related to a problem? Please describe.**
> 
> I want to be able to comment out large portions of tests and then collapse them.
> 
> I tried the obvious (select a region and cmd+/), but that doesn't work:
> [microsoft/vscode#124104 (comment)](https://github.com/microsoft/vscode/issues/124104#issuecomment-843452790)
> 
> **Describe the solution you'd like**
> either cmd-/ + folding works, or toggle block comment + folding works
> 
> **Describe alternatives you've considered**
> I filed [microsoft/vscode#124104](https://github.com/microsoft/vscode/issues/124104)
> 
> **Additional context**
> ![image](https://user-images.githubusercontent.com/2119212/118651096-2dc75800-b7b3-11eb-9fb6-5277a730c9b2.png)
> ![image](https://user-images.githubusercontent.com/2119212/118651129-361f9300-b7b3-11eb-9906-bc86aa7e3282.png)
> ![image](https://user-images.githubusercontent.com/2119212/118651176-4172be80-b7b3-11eb-99be-a66f2ed68dd3.png)

**Comment by ShoshinNikita** [comment]
I don't think it's a gopls issue. Rather, it's the unfortunate default behavior of VS Code. There's an option `editor.comments.ignoreEmptyLines` to toggle comments even for empty lines:

![image](https://user-images.githubusercontent.com/30220965/119985576-7d83fb80-bfcb-11eb-83eb-6fd560d2743a.png)

**Comment by stamblerre** [comment]
Thanks for finding that, @ShoshinNikita! @jsoref, does that resolve the issue for you?

**Comment by jsoref** [comment]
I guess? It seems like it's designed for this use case (and applies evenly across the platform).

I pretty much never use this feature (perhaps because I've never trusted an IDE to be remotely smart, and this reenforces that opinion). (I tried it because colleagues were using it, and I needed to perform a routine task of isolating test cases until I could figure out which ones were failing.) (I'm actually quite impressed w/ VSC in general, and am using it to replace Notepad or similar.)

I expect I'm more likely to not use the comment-lines feature at all and return to manually adding `/*`...`*/` around blocks.

**Comment by stamblerre** [comment]
Ok, thanks for following up. Looks like this setting resolves the issue, so I will close this, as well as the upstream issue.

**Comment by suzmue** [comment]
I think this issue also covers that there is no folding range for block comments `/* .. */` (which is also available as a command in VS Code), which could be addressed in gopls:

<img width="653" alt="Screen Shot 2021-06-04 at 6 46 16 PM" src="https://user-images.githubusercontent.com/6634754/120869757-26e76600-c565-11eb-9bdb-3dfe2b896c1a.png">
