### ISSUE TITLE
x/pkgsite: github.com/bluecmd/go-tcg-storage has wrong redirect

### ISSUE THREAD

**Issue by bluecmd** [golang/go#46331]
### What is the URL of the page with the issue?

https://godoc.org/github.com/bluecmd/go-tcg-storage 
  
### What is your user agent?
 
N/A 
 
### Screenshot
 
 
![image](https://user-images.githubusercontent.com/149442/119267138-b13adc00-bbed-11eb-9f10-af7ca219f245.png)

 
### What did you do?
 
I enabled godoc for my package just after I renamed the Github repository. I think that confused the software which is now redirecting back to the older (non-existent) library.
 
### What did you expect to see?
 
 The site showing the documentation of the current library.
 
### What did you see instead?

The site showing the documentation of the old library, frozen in time.

**Comment by jba** [comment]
Everything seems like it's working for me. The godoc URL redirects to https://pkg.go.dev/github.com/bluecmd/go-tcg-storage, which shows v1.1.0. The repository link on that page is github.com/bluecmd/go-tcg-storage, and when I click on that I  visit a valid github repo.

Can you clarify what the problem is?

**Comment by bluecmd** [comment]
Hi, it seems the page has re-synced overnight. Nothing to see! :-).
