### ISSUE TITLE
x/tools/gopls: support matching directories at arbitrary depth using the directoryFilters setting

### ISSUE THREAD

**Issue by cespare** [golang/go#46438]
I have some very large `node_modules` trees that cause gopls to fail. The recently-added [`directoryFilters` configuration setting](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#directoryfilters-string) is a partial workaround for this, but the paths it accepts are always interpreted relative to the workspace root.

There are multiple large `node_modules` directories in my workspace and the set might change in the future. I don't want to keep `directoryFilters` in sync with this. Instead, I want to globally ignore `node_modules` directories everywhere, in all workspaces, forever. But there doesn't seem to be any way to specify an unrooted path in `directoryFilters`.

I suggest adding a way to do this. One question is the syntax to use. If we were designing this from scratch, perhaps a rooted path (`-/myproj/node_modules`) could indicate workspace-relative and unrooted path (`-node_modules`) could indicate "match this directory at any depth". (This would be similar to how, for example, gitignore works.)

But since that option is foreclosed at this point, here are some other ideas to get us started. A leading `*` could be used to indicate "match at any depth": `-*/node_modules`. That resembles, yet is confusingly different from, shell glob syntax, so perhaps `*` could mean "match any single directory" and `**` could mean "match any depth"; then I could use `-**/node_modules`.

**Comment by myitcv** [comment]
In the somewhat related https://github.com/golang/go/issues/41504#issue-705054795 I suggested using the `.gitignore` approach - that would seem to work here too?

**Comment by heschi** [comment]
As you say, it's moot now, but FWIW I think using `/` for the project root would be very ambiguous with absolute paths, which is why I started with relative paths. I suspect it's not a problem in the context of a Git repository, but editor settings have a much weaker context.

I'm in favor of using `**` to mean match any number of folders, including 0; I just didn't get around to implementing it.

**Comment by adonovan** [comment]
Let's use `...` (which must be a complete slash-delimited segment of the pattern) to mean "zero or more complete segments of the file name", just as we do in the go command (e.g. go build ./foo/...)

**Comment by hyangah** [comment]
@adonovan the main motivation of this issue is to specify rules like "exclude any directory that has name 'node_modules'" (e.g. `node_modules` or `**/node_modules` in `.gitignore` style, or `"**/node_modules": true` in vscode setting style ([`"search.exclude"` or `"files.exclude"`](https://code.visualstudio.com/Docs/editor/codebasics#_search-across-files)). If we use `...`, should this be `.../node_modules/...`? That is odd.

This is more about file paths, rather than package paths, and is more about editor settings, rather than go build setting. I wonder why we want to invent our own wheel instead of already widely used glob patterns, `.gitignore` style settings, editor settings?

**Comment by cespare** [comment]
@dle8 Thanks very much for your work on this!

Should there be a [doc update](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#directoryfilters-string) reflecting the change?

Should we change the default value of `directoryFilters` from `["-node_modules"]` to `["-**/node_modules"]`?

**Comment by findleyr** [comment]
@cespare raises good points, thanks.

IMO, the answer to both questions is "yes" :)
