### ISSUE TITLE
proxy.golang.org: remove cached module 

### ISSUE THREAD

**Issue by mfridman** [golang/go#46440]
Please remove `github.com/golang-jwt/jwt` module from Go module proxy cache. 

I understand the recommendation is to tag a newer version, but this would effectively force the project into a v2+ and SIV which would like to avoid.
 
### What is the URL of the page with the issue?
 
https://github.com/golang-jwt/jwt

### Screenshot
 
![image](https://user-images.githubusercontent.com/6278244/120068139-31799b00-c04d-11eb-9f36-a258a0e25dc8.png)

### What did you do?
 
The goal was to clone a repo, remove the existing tags and start with a fresh import path and thus a clean v0 and v1 without SIV.

**Comment by seankhliao** [comment]
I think this should be covered by [retract](https://golang.org/ref/mod#go-mod-file-retract)

cc @katiehockman @heschi @hyangah

**Comment by oxisto** [comment]
> I think this should be covered by [retract](https://golang.org/ref/mod#go-mod-file-retract)
> 
> cc @katiehockman @heschi @hyangah

There are several issues preventing us from using retract.
1) Unless I have done something majorly wrong, having a retract statement in a go.mod does not compile in Go <= 1.15. We are taking over the maintenance of one of the bigger jwt libraries in the Go ecosystem (http://github.com/dgrijalva/jwt-go) from the original author under this new import name and want/need to support some older Go versions as well
2) The project (as taken over from the original author) does not have a go.mod file, but has a `v3.x.x+incompatible` release scheme. Our original plan was to fix that issue by re-releasing with go modules support as `v1`, without any breaking changes to the  `v3.x.x+incompatible`, so that we have a drop-in replacement for people without API changes. We would then move to a `v2`-SIV-style version afterwards.

These two releases currently block us from re-releasing as `v1.0.0`, forcing us to stick with the `v3.x.x+incompatible` release scheme at least for one version with a major security fix and then moving to a new `v4`-SIV-style. This is something we wanted to avoid. I hope this explanation makes it a little more clearer where we are coming from and why this is important to us.

**Comment by mfridman** [comment]
Closing this issue. We'll continue with the recommended suggesting from the [proxy FAQ](https://proxy.golang.org/):

> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

cc @oxisto Any concerns? The goal of this ticket was solely to get those versions removed from the proxy, and this isn't likely to happen.

**Comment by oxisto** [comment]
> Closing this issue. We'll continue with the recommended suggesting from the [proxy FAQ](https://proxy.golang.org/):
> 
> > Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.
> 
> cc @oxisto Any concerns? The goal of this ticket was solely to get those versions removed from the proxy, and this isn't likely to happen.

Yup, lets go with plan "b". We can close this then
