### ISSUE TITLE
cmd/compile: error message dumps internal details

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#46558]
Using a compiler built at 6d9830111402d9bd69893a8ad6074ac92a5ddd0d, compiling this erroneous file gives a strange error message that seems to dump an internal compiler data structure.

```Go
package p

func F(s string) {
	switch s[0] {
	case 'a':
		case s[2] {
		case 'b':
		}
	}
}
```

```
> go build foo.go
# command-line-arguments
NOT NTYPE [0xc00034e0c0]
.   INDEX # foo.go:6
.   .   NAME-p.s Class:PPARAM Offset:0 OnStack # foo.go:3
.   .   NAME-ntype
.   .   .   NONAME-p.string # foo.go:3
.   .   LITERAL-2 untyped int # foo.go:6
../foo.go:7:3: syntax error: unexpected case, expecting expression
../foo.go:8:4: syntax error: unexpected newline, expecting :
```

This does not happen with Go 1.16.

CC @mdempsky

**Comment by mdempsky** [comment]
I think there are two minor issues here:

1. cmd/compile/internal/parser is now trying to parse `s[2] { case 'b': }` as a composite literal of instantiated type `s[2]`. This then fails during noding, because `s[2]` isn't a valid syntactic form for a type expression (prior to generics, which noder doesn't support). (I'm inferring this because of the change in error message/lines from 1.16 to master.)
2. cmd/compile/internal/noder has an ir.Dump call that Russ added for debugging some ir.Node refactoring stuff. It will never print on valid input, and (I think) it also never printed before the change in parser semantics.

Maybe a parser change is appropriate here (/cc @griesemer). But I also think it's fine that we just remove the spurious ir.Dump. It's not serving any purpose now that things have stabilized.

**Comment by griesemer** [comment]
Yeah, the parser should probably handle this case as it gets badly into the weeds otherwise. Will fix.

**Comment by griesemer** [comment]
This was fixed with the above CLs
