### ISSUE TITLE
x/pkgsite: docs for new Github repo using old repo name is not updated

### ISSUE THREAD

**Issue by johan3141592** [golang/go#46621]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/rubrikinc/rubrik-polaris-sdk-for-go
 
 
### What is your user agent?
Chrome/90.0.4430.93
 

 
  
### Screenshot
![Screenshot from 2021-06-07 08-40-18](https://user-images.githubusercontent.com/79966026/120970792-2c62cd00-c76c-11eb-8f90-810115c169d4.png)

 
 
### What did you do?
Enter https://pkg.go.dev/github.com/rubrikinc/rubrik-polaris-sdk-for-go in my browser

 
 
### What did you expect to see?
The documentation for the new version of https://github.com/rubrikinc/rubrik-polaris-sdk-for-go
 
 
### What did you see instead?
The documentation for the old version https://github.com/rubrikinc/rubrik-polaris-sdk-for-go

Note, the old repository was deprecated and a new previously private repository was made public with the same name.

**Comment by jba** [comment]
Let me see if I can reconstruct the events here. I've included what happens with the Go module mirror (proxy.golang.org) and with pkgsite.

1. You created github.com/rubrikinc/rubrik-polaris-sdk-for-go, made a v1.0.6 tag.
2. You or someone else used `go get` to get the module, with the default settings for the `go` command. This caused proxy.golang.org to fetch your repo and note that the latest tag was 1.0.6. It published that information to its complete list of modules, index.golang.org.
3. pkgsite read the index, saw v1.0.6 of your module, and added it to its database.
4. You deleted the repo and re-created it with the same name. Nothing in the proxy changed. (Indeed, the proxy's data is effectively immutable: nothing is ever deleted.)
5. You added some v0 tags.  The proxy and pkgsite picked them up, as before.
6. You visited your module path on pkgsite without an explicit version, so pkgsite find the latest version, using semantic versioning. The latest version with that path is v1.0.6, so that's what it shows.

You can publish a version greater than v1.0.6, but I believe you don't want to do that while the software is beta. The only other option is to change the module path.
