### ISSUE TITLE
spec: Clarify assignability of channels

### ISSUE THREAD

**Issue by aurora-vasiliev** [golang/go#46738]
The [documentation](https://golang.org/ref/spec#Assignability) for Assignability is stating:

```A value x is assignable to a variable of type T ("x is assignable to T") if one of the following conditions applies:```
- ```x is a bidirectional channel value, T is a channel type, x's type V and T have identical element types, and at least one of V or T is not a defined type. ```

I suppose, the section stating ```at least one of V or T is not a defined type``` can be omitted as it's already stating that ```T is a channel type```.
If T is a channel type, that would inherently fulfil the last condition.

**Comment by seankhliao** [comment]
cc @griesemer

**Comment by griesemer** [comment]
In the spec, when we talk about a specific type (e.g. a "channel type") we may still have a defined channel type. For instance
```Go
type T chan int
```
declares the defined type `T` but `T` (i.e., its underlying type) also happens to be a channel type. Because usually (for operations other than methods) we care about the underlying type, we are not always explicitly mentioning the underlying type.

So this is correct as is.

(I agree that it could be more formally correct, but there's a thin line between making it reasonably easy to read at the cost of some formal precision, and making it formally precise at the cost of making it harder to read. We may not have always struck the perfect balance, but that's ok.)
