### ISSUE TITLE
x/pkgsite: Stop changing banner class

### ISSUE THREAD

**Issue by 89z** [golang/go#46745]
I am not interested in seeing the banner here:

https://pkg.go.dev

and on every single package in the Go ecosystem. To this end, I set a filter in uBlock Origin:

~~~
go.dev##.Banner
~~~

However I noticed that the class will randomly change, then I have to use this:

~~~
go.dev##.go-Banner
~~~

can you please stop changing the class? Or at least add an ID attribute, so users can filter the element more reliably.

**Comment by 89z** [comment]
CC @ALTree

**Comment by 89z** [comment]
Looks like the code is here:

https://github.com/golang/pkgsite/blob/71cd678b/static/shared/header/header.tmpl#L9

CC @jamalc

**Comment by ALTree** [comment]
Unfortunately I don't think it's reasonable to ask for the banners ids not to change... it was done as part of normal work on the website. You'll have to change your blocker filter with the new ID. I doubt it'll change very often.

An alternative would be a dynamic filter like:

```
go.dev##div:has( > a[href*="eji.org"])
```

This would block every `div` with an embedded `a` element going to a certain url, and will work regardless of the html element ID. But a static filter based on the ID is more efficient, so changing your rule to match the new ID is actually a better solution.

Closing here since I don't think there's anything else to do.

**Comment by 89z** [comment]
> Unfortunately I don't think it's reasonable to ask for the banners ids not to change

I didnt ask for the ID not to change, I asked for the class not to change. The element doesnt currently have an ID. If it did, then this wouldnt be a problem. Its a single line fix. If someone could just add an ID here:

https://github.com/golang/pkgsite/blob/71cd678b/static/shared/header/header.tmpl#L9

then boom, issue over.

**Comment by 89z** [comment]
https://github.com/golang/pkgsite/pull/34

**Comment by ALTree** [comment]
If that's your proposal I would use something like "blm-banner" as the id, this way you could block specifically that and still see other generic banners they may add to the website.

**Comment by 89z** [comment]
Nope. As I feel the Go team has long abused the banner for non-Go related items, I dont want to see the banner anymore, regardless of what it says. Also, a more generic ID will be better in the long term anyway.

**Comment by sgon00** [comment]
I suggest you don't set any filters and leave the banner on. "Closing your eyes isn't going to change anything. Nothing's going to disappear just because you can't see. In fact, things will even be worse the next time you open your eyes."

**Comment by 89z** [comment]
@sgon00 youre right. In fact, lets make the banner larger as well, dont want people to miss it!

Even better, lets make it fixed, so you always see it, even when scrolling. In fact why are we even wasting space with the Go documentation? Lets just make the entire page the banner! That way we can reach the most people!

**Comment by sgon00** [comment]
@89z I think you misunderstand what I mean. I can not express too much because they don't want people to speak. There is no freedom of speech here. They lock topic and kick people out. If you disable the filter, I am afraid next time when you enable it, you will see XXX as a background-image. That is what I mean. Setting a filter won't make a difference. You have to see it to remind you. I think I will shut my mouth up now and will not comment anymore. I am terrified to speak.

**Comment by 89z** [comment]
@sgon00 maybe because they dont want people talking about crap that has nothing to do with Go? I am not trying to take a position on the matter, I dont want the blocking process to simple simple, for people who might choose to block it. The existance or content of any banner is the decision of the Go team.
