### ISSUE TITLE
cmd/go: documentation doesn't mention GOENV=off

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46840]
The documentation at https://golang.org/cmd/go/#hdr-Environment_variables doesn't mention that `GOENV=off` is a special case for disabling the use of a Go environment configuration file. It probably should, and maybe to mention `GOENV=./off` is a workaround if they actually want to use a file named "off" in the current directory.

**Comment by ianlancetaylor** [comment]
Perhaps also worth noting that

    GOENV=off go env GOENV

just prints a newline.  It does not print `off`.  I can't tell whether this is a bug or not.

**Comment by tpaschalis** [comment]
I think the reason why `GOENV=off go env GOENV` prints a newline instead of 'off' is that in [EnvFile](https://github.com/golang/go/blob/f6591839727e09cc5cb11d08b333fd2386e8aa1b/src/cmd/go/internal/cfg/cfg.go#L181-L185) we handle this case by returning an empty string and an error; the empty string is eventually printed out and the error [is discarded](https://github.com/golang/go/blob/f6591839727e09cc5cb11d08b333fd2386e8aa1b/src/cmd/go/internal/envcmd/env.go#L69-L70) during the `go env` invocation.

I'm not the best person to point out if this is a bug or not, but for my 2¢, a) the fact that it returns an empty string is utilized in `updateEnvFile`, and b) returning `off` instead of this empty string would be weird (returning both a valid value *and* an error), so to me, the current implementation feels okay.

I can drop a small documentation CL for this; hopefully it's innocuous enough to fit in this cycle.

**Comment by odeke-em** [comment]
Please go ahead @tpaschalis with the documentation CL, this issue is meant for Go1.18 :-)
