### ISSUE TITLE
cmd/cover: cannot dispose function parameters with inner function 

### ISSUE THREAD

**Issue by jnlunsb** [golang/go#47054]
The Issue Example is shown as below
<img width="884" alt="图片" src="https://user-images.githubusercontent.com/30978443/124412496-3da9f400-dd81-11eb-9bb7-3f8e8568496a.png">

red cicle means, go tool cover cannot acquire these uncvoered lines

It's  go/cmd/go/cover.go bug

**Comment by mknyszek** [comment]
I'm having a hard time following what the problem is.

Could you provide an example of the code that produced the error as text, preferably as a [Go playground](https://play.golang.org/) link?

Also, since this appears to be related to the coverage tool, can you please provide the precise steps you took to reproduce your error?

And finally, please share the Go version you're using and the platform you're executing these commands on. Thanks.

**Comment by thanm** [comment]
I typed in your example code (or something approximating it) and did a coverage run on it. Attached 
[files.zip](https://github.com/golang/go/files/6786800/files.zip) with the files I am using. When I run 

```
go test -test.count=2 -coverprofile=cov.dat .
go tool cover -html=cov.dat
```

I get this output from the second step:

![Screenshot from 2021-07-06 08-30-29](https://user-images.githubusercontent.com/12280172/124978894-596efd80-e000-11eb-9c7e-f4575accd560.png)

So, you are correct in that the coverage tool doesn't seem to be treating lines 13 and 14 as executable, but given that the reported coverage is 100%, why is this a problem?
