### ISSUE TITLE
log: document Print and Printf adding newlines more

### ISSUE THREAD

**Issue by thalesfsp** [golang/go#47060]
Ref.: https://github.com/golang/go/issues/16564

Why not a flag (e.g.: `log.Ldate`) to disable that (newline)? What's the problem? Such change would be so easy to be implemented.

_Note: `fmt` isn't `log`, and `log` has everything needed minus this newline.

Thank you!

**Comment by ianlancetaylor** [comment]
If you want complete control over output formatting, use the fmt package.  If you want a simple way to generate logs, use the log package.  There is no reason for the log package to provide all the capabilities of the fmt package.

I'll add that there a number of third party log packages out there, you aren't required to use the one in the standard library.

I'm going to close this issue because it doesn't add anything to the existing #16564, which was already closed.

**Comment by thalesfsp** [comment]
Hello, @ianlancetaylor! I don't want complete control over output... I'm asking for just that: a flag...

**Comment by ianlancetaylor** [comment]
Again, this issue doesn't add anything to the existing #16564.  In general we don't want to continually revisit decisions that have already been made.  Thanks.
