### ISSUE TITLE
x/exp/event: poor package comment

### ISSUE THREAD

**Issue by robpike** [golang/go#47154]
I ran `go doc` in x/exp/event to see what it does. This is what is reported for the package comment:

```
% go doc 
package event // import "golang.org/x/exp/event"

Package event provides the core functionality for observability that allows
libraries using it to interact well. It enforces the middle layer
interchange format, but allows both frontend wrappers and back end exporters
to customize the usage.
...
%
```

I learned nothing from this. Please provide a package comment that explains the purpose of the package.

**Comment by ianlancetaylor** [comment]
CC @ianthehat

**Comment by dmitshur** [comment]
Possibly related issue #36238. Also CC @stamblerre.

**Comment by ianthehat** [comment]
The package and all things below it are very very experimental, not ready for anybody to actually use, and might still just be deleted (some of the sub packages definitely will be).
If it turns out to be a success, it will move out of experimental to somewhere real.
I do think it is reasonable to ask for a better package comment even in it's current state though, to at least make that much clear to anyone looking, I know that technically applies to all of x/exp but that package is even more experimental that most right now.
I will take this bug and close it when I do that.
