### ISSUE TITLE
x/tools/go/ssa: a phi instruction is not emitted when possible

### ISSUE THREAD

**Issue by pupiles** [golang/go#47165]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
darwin/amd64
</pre></details>

### What did you do?

the code same as 
```
https://github.com/tmc/ssaview/blob/master/ssaview.go
```
when parse the code below,it should be product `phi` inst,but not
```go
package main

func test11(n int) {
	if n > 1 {
		n += 2
	} else if n == 2 {
		n += 3
	} else {
		n -= 1
	}
	fmt.Println(n)
}
func main(){}
```

### What did you expect to see?

product `phi` inst

**Comment by timothy-king** [comment]
ssa currently emits what looks like a valid translation that uses a memory address for n instead of using phi instructions. While this is sub-optimal and it would be nice to fix, the ssa does not look incorrect.

The place to start addressing this is `func lift(fn *Function)` in `ssa/lift.go`.

This is a reasonable place for a community contribution if this is a pressing concern. Moving this to Unplanned.

**Comment by dominikh** [comment]
From `ssaview`'s code:

```
	ssaProg := ssautil.CreateProgram(prog, ssa.NaiveForm|ssa.BuildSerially)
```

this is building the "naive" representation, which means the lifting phase gets skipped entirely. If we don't skip lifting, then we do get the expected phi nodes.

**Comment by pupiles** [comment]
@dominikh yes
```go
if f.Prog.mode&NaiveForm == 0 {
		// For debugging pre-state of lifting pass:
		// numberRegisters(f)
		// f.WriteTo(os.Stderr)
		lift(f)
	}
```
if mode&NativeForm equal 0,i will get phi node correctly
thanks a lot
