### ISSUE TITLE
cmd/go: go get <module> is not restricted to desired module

### ISSUE THREAD

**Issue by andig** [golang/go#47195]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
❯ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build187128154=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Update module using `go get`

### What did you expect to see?

`go.mod` updated, no error.

### What did you see instead?

Error on unrelated module:

    ❯ go get github.com/bogosj/tesla
    go: gitlab.com/bboehmke/sunny@v0.14.2: Get "https://proxy.golang.org/gitlab.com/bboehmke/sunny/@v/v0.14.2.mod": dial tcp 142.251.36.241:443: i/o timeout

    ❯ GOPROXY=off go get -d github.com/bogosj/tesla
    go: gitlab.com/bboehmke/sunny@v0.14.2: module lookup disabled by GOPROXY=off

While the error is transient, it is not clear why updating a single module should regard all others. It should be possible to update a single module even if others fail to resolve.

**Comment by cherrymui** [comment]
cc @bcmills @jayconrod @matloob

**Comment by jayconrod** [comment]
Sorry, it's not feasible to fix this without making a major change to the semantics of `go get`.

`go get`, like other module-aware commands, loads the build list (set of selected module versions) when it starts. That requires loading the `go.mod` file for each dependency, which may require fetching those files if they aren't in the module cache.

`go get` can't work without the build list because upgrading (or adding or downgrading or removing) a dependency can affect other dependencies. For example, suppose A 1.1 depends on B 1.5, but A 1.2 does not depend on B. If you upgrade to A 1.2, you could unintentionally downgrade or remove B. `go get` prevents that from happening by adding an explicit `// indirect` requirement.

Also perhaps more importantly, `go get` may operate on either packages or modules. When an argument refers to a package, `go get` loads all the transitively imported packages, and the build list is certainly required for that.
