### ISSUE TITLE
x/pkgsite: pageless search

### ISSUE THREAD

**Issue by jba** [golang/go#47315]
Our data shows that people seldom look past the first page, and almost never past the first three pages. To simplify both the user experience and the logic, we're going to do away with paginating search. Instead, we will show the top 10 results by default, and users can select more results from a dropdown.

**Comment by cespare** [comment]
What does "select more results from a dropdown" mean, if there are no pages?

**Comment by fzipp** [comment]
@cespare Probably like the "More results" button below Google search results on mobile.

**Comment by jba** [comment]
You won't be able to get more results indefinitely, though. You'll have a choice of, say, 10, 30 or 100 results.

**Comment by pwaller** [comment]
Why stop at 100?

I'm disappointed when I came to go.dev after a hiatus that I don't get the full list of packages like the good old days on godoc.org. Sometimes you search for something and get a lot of hits -- when that happens it can be useful to be able to press ctrl-f in your browser to jump through them to look for something specific.

Is there any good reason to paginate vs show everything? What is the most extreme case of number of results and what detriment is there to showing them all? My recollection was skimming through hundreds or even thousands of packages and finding what I was looking for that way with the scroll bar. Like glancing at a bookshelf -- serendipitously discovering things.

**Comment by jba** [comment]
Our data shows that very few people went past the tenth page. We added a limit for reliability reasons.

**Comment by changkun** [comment]
I think that very few people went past the tenth page because there are no more interesting results and a lot of duplications of forked packages. The pkg.go.dev should improve the search results instead of removing pagination.

If we want to discover what's out there, the pkg.go.dev search page says too little until we click the page. In the worst case, we still have to go to the package repository to see why it receives a high ranking.

Comparing to GitHub's search page, pkg.go.dev shows only 100 results removes the discovery functionality completely. (The whole Go world is not dominant by packages who being imported the most, diversity is also important)

See a comparison:

- pkg.go.dev: https://beta.pkg.go.dev/search?limit=100&m=package&q=clipboard
- GitHub: https://github.com/search?l=Go&q=clipboard&type=Repositories

For instance, the [second](https://beta.pkg.go.dev/github.com/go-vgo/robotgo/clipboard) (a fork of the [first](https://beta.pkg.go.dev/github.com/atotto/clipboard)) and the [third](https://beta.pkg.go.dev/github.com/gopasspw/gopass/pkg/clipboard) results (an internal package) in pkg.go.dev is completely useless. The [fourth](https://beta.pkg.go.dev/github.com/zetamatta/go-readline-ny) result -- completely irrelevant. Comparing to what's showed on GitHub, one see differences.

**Comment by jba** [comment]
Launched.
