### ISSUE TITLE
runtime: spurious cycles in time.Now pprof output (vdsoPC and vdsoSP not WAI?)

### ISSUE THREAD

**Issue by josharian** [golang/go#47324]
On linux:

`go test -bench=kNow$ -run=NONE -count=3 -cpuprofile=c.p time`
`go tool pprof -pdf -lines c.p > o.pdf`

Result:

[o.pdf](https://github.com/golang/go/files/6858335/o.pdf)

Observe the cycles in the graph. The actual call graph doesn't have any cycles in it.

**Comment by thanm** [comment]
@cherrymui per owners (I am assuming that this is a runtime/pprof problem).

**Comment by cherrymui** [comment]
I assume this is Linux/ARM64? (from sys_linux_arm64.s in the profile)
What version of Go is this? I assume this is not tip, where walltime1 is gone.

It appears to me in sys_linux_arm64.s we probably store the wrong value into m.vdsoSP. I think we should store the caller's SP instead of its own SP.

I'll work on a fix. (But would still be good to know the information above. Thanks.)

**Comment by josharian** [comment]
Sorry, yes, linux/arm64. I’ve also seen it on linux/amd64, and it wouldn’t surprise me if it were also present on other platforms. The reproduction above was with 1.16, I believe. (I’m AFK.)

**Comment by cherrymui** [comment]
Does CL https://go-review.googlesource.com/c/go/+/337590 help? (It's on tip.) Thanks.

**Comment by josharian** [comment]
> Does CL https://go-review.googlesource.com/c/go/+/337590 help? (It's on tip.) Thanks.

Sure does!

**Comment by cherrymui** [comment]
Thanks. I'll make it a real CL then.

**Comment by mengzhuo** [comment]
@cherrymui should we fix other architectures in CL 337590  or submit separate CLs for this issue?
