### ISSUE TITLE
go/types: change in embedded type ordering on dev.typeparams branch

### ISSUE THREAD

**Issue by mdempsky** [golang/go#47352]
The test program at https://play.golang.org/p/O5DRq3UlQRa currently prints `type x.J interface{x.I; error}`

But on dev.typeparams, since fe4f13404d553958c5b5889ce8b94144798d07bf, it prints `type x.J interface{error; x.I}`.

This broke a Google-internal test. I'm okay with fixing the test, but @findleyr suggested that maybe we should restore the original sort order. Filing the issue to decide.

/cc @griesemer @dominikh

**Comment by griesemer** [comment]
If this is an isolated incident, I vote for fixing the test. The print output is still deterministic, it's just that now it's based on source order rather than sort order.

We could just sort when printing, but then the output doesn't match the API order.

We could keep the (original) sorted order, but that would require a bit more work when sorting (we need to sort positions as well). It doesn't seem worth the effort. The `go/types` API doesn't make any guarantees with respect to the ordering of embedded interfaces, I believe.

**Comment by heschi** [comment]
Any further comments on this? If not, I'll change the test.

**Comment by griesemer** [comment]
Please change the test - this seems the easiest way forward.

**Comment by heschi** [comment]
OK. Close the bug if you like.
