### ISSUE TITLE
x/pkgsite: don't store retracted versions

### ISSUE THREAD

**Issue by jba** [golang/go#47461]
Pkgsite will never display a retracted version as the latest version of a module. But it will process a retracted version, and it won't remove a version if it is later retracted. The page for a retracted version can be visited by providing the version number, and the version may appear in search if it was later retracted.

pkgsite should not process retracted versions, and should remove a version when it discovers it is retracted.

**Comment by bcmills** [comment]
> pkgsite should not process retracted versions, and should remove a version when it discovers it is retracted.

Will it still at least show a landing page indicating that the requested version is retracted?

Retracted versions can still be cached and fetched from a proxy, and users can continue to build existing modules against  them — I feel like we ought to at least leave some kind of breadcrumb to let them know that `pkgsite` knows about the existence of the thing they're asking for.

**Comment by jba** [comment]
Can the page simply say "This version is retracted" and link to the latest version?

**Comment by bcmills** [comment]
That seems fine to me. That said, thinking about this some more: users can continue to use retracted versions, so maybe it's worth indexing them if they are requested explicitly.

For example: suppose that module `example.com/m` `v0.2.3` is retracted because of a CVE in package `example.com/m/vulnerable`, which was only found and fixed much later (say, `v0.6.0`). If there are breaking changes in between `v0.2.3` and `v0.6.0`, then I might _really want_ to see the docs for `v0.2.3` to figure out how to migrate past those breaking changes — _especially_ if my code doesn't even import package `vulnerable` in the first place.

**Comment by jba** [comment]
Good point, Bryan. We will keep processing retracted versions. (But we'll continue omitting them from search results.)

**Comment by bcmills** [comment]
> (But we'll continue omitting them from search results.)

Is that behavior live? https://beta.pkg.go.dev/search?q=rerpc shows `github.com/akshayjshah/rerpc` as the second hit, but all known versions of that module are retracted (https://beta.pkg.go.dev/github.com/akshayjshah/rerpc?tab=versions).

**Comment by jba** [comment]
Thanks for catching. That's an un-done TODO in the code. Tracked at #47590.
