### ISSUE TITLE
crypto is widely used. hope to see some speed up by 2x etc. coz net/http ssl is very slow compared with c / c++ / rust

### ISSUE THREAD

**Issue by hiqsociety** [golang/go#47586]
thanks for golang. it's a great software.
cant thank enough all contributors who made this language happen.
understand the difficulty to get other priorities done but so far, the only thing i see having more opportunity for optimization is the speed of crypto parsing. not sure if it's fixed.
2 more areas will really help speed up go to be closer to c++ is rust/go and cgo / c++ calling. the overhead is there.

appreciate all the hard work on this. for now only crypto is most useful speed up i guess.

thank you all!

**Comment by seankhliao** [comment]
Thanks for filing the issue, while everyone would like better performance, this issue is not very actionable without benchmarks and/or actual proposals for improving performance. There are open issues such as #21525 and #40171 which track specific plans for improvement. Note there is also an assembly policy #37168

Closing as I believe this is covered by other, more specific, in progress issues
