### ISSUE TITLE
The Authelia project's releases aren't in the indexing server

### ISSUE THREAD

**Issue by yurivict** [golang/go#47611]
The Authelia project made several releases in July and August https://github.com/authelia/authelia/tags but they aren't reflected in the indexing server.

Files retrieved by this script don't contain it:
```
cat go-retrieve-all-packages.sh
#!/bin/sh

SINCE=$1 # like 2021-08-01T00:00:00Z

while [ -n "${SINCE}" ]; do

        # download
        echo "downloading SINCE=${SINCE}"
        wget "https://index.golang.org/index?limit=2000&since=${SINCE}" -q -O output-${SINCE}.json

        # get last since
        SINCE_NEW=`tail -1 output-${SINCE}.json | sed -e 's|.*"Timestamp":"||; s|".*||'`

        # EOF?
        if [ "${SINCE_NEW}" = "${SINCE}" ] || [ -z "${SINCE_NEW}" ]; then
                echo "=== End of project list reached @ ${SINCE} ==="
                exit 0
        else
                SINCE=${SINCE_NEW}
        fi
done
```

**Comment by D1CED** [comment]
One obvious issue is that the projects module path does not match its major version. It is currently at major version 4 but the module import path (see https://golang.org/doc/modules/gomod-ref#module) indicates a version 0/1. Because of this mismatch the Go infrastructure does not pick up any new releases.

**Comment by seankhliao** [comment]
As stated above, authelia is setup incorrectly (using `go.mod` but not declaring a matching major version path).
Additionally, the index is based on the things people pull through the proxy, if noone downloads authelia through the proxy, the index never knows about it. 

Pulling in `master` results in the following entry being created (note the generated pseudoversion because of the above invalid config):
```
{"Path":"github.com/authelia/authelia","Version":"v1.0.12-0.20210810031905-c67d78587905","Timestamp":"2021-08-10T09:20:18.393111Z"}
```

Closing as it's a problem for authelia and not Go / index/proxy
