### ISSUE TITLE
x/pkgsite: suport MulanPSL and MulanPSL2

### ISSUE THREAD

**Issue by ystyle** [golang/go#47613]
### What is the URL of the page with the issue?
my repo is  MulanPSL2 license
https://pkg.go.dev/github.com/ystyle/sqlmanager
 
### What did you expect to see?
suport MulanPSL and MulanPSL2

**Comment by jba** [comment]
Only PSL-2.0 is on the OSI list, so that's the only one we'll allow.

https://go-review.googlesource.com/c/pkgsite/+/375275 adds it. However, the LICENSE file in github.com/ystyle/sqlmanager at commit ed7598d2e7af does not match it. I don't see the reason for the discrepancy, but you can see the template at https://github.com/google/licensecheck/blob/v0.3.1/licenses/MulanPSL-2.0.lre, and a matching LICENSE file at https://gitee.com/daqingshu/eurekaplugin/blob/v1.0.1/LICENSE.
