### ISSUE TITLE
cmd/compile: local type declarations in generic code don't work

### ISSUE THREAD

**Issue by randall77** [golang/go#47631]
```
package main

func F[T1 any]() {
	type x struct{}
}
func main() {
}
```
```
$ go run -gcflags=-G=3 tmp1.go
# command-line-arguments
<unknown line number>: internal compiler error: cannot export DCLTYPE (50) node
```
This looks like a general problem that we can't export/import local type declarations, including for inlining.

**Comment by danscales** [comment]
@findleyr pointed out that local generic types in non-generic functions somewhat work now:

```
package main

import "fmt"

func main() {
        type N[T any] struct{ t T }

        type N2[T comparable] struct{ t T }
        var x N[int]
        var y N2[string]
        fmt.Println(x, y)
}
```

Of course, if instead of main, we had an exported, inlinable function F, then we would get the same failure, since we would try to export F.

But just wanted to mention this case, since we need to either support it or disable it, depending on whether we support local generic types in Go 1.18.

**Comment by vearutop** [comment]
For additional information (or test), here are a couple more examples where this issue is exposed:
https://github.com/bool64/cache/pull/10  (https://github.com/bool64/cache/runs/4090475198?check_suite_focus=true#step:5:28)
```
<autogenerated>:1: internal compiler error: cannot export DCLTYPE (50) node
	==> please file an issue and assign to gri@

```
And https://github.com/bool64/cache/pull/11 (https://github.com/bool64/cache/runs/4090471755?check_suite_focus=true#step:5:28)

```
panic: runtime error: slice bounds out of range [:-1]
```

**Comment by randall77** [comment]
This feature is being pushed back to 1.19.

**Comment by zhuah** [comment]
can we support type alias in generic code?
```Go
package main

type S1[T any] struct {
}

func (s S1[T]) Build(fn func(t *T)) T {
	var t T
	fn(&t)
	return t
}

type Container[T any] struct {
	Value T
}

type S2[T any] struct{}

func (s S2[T]) Build() Container[T] {
	type valueType = Container[T]

	return S1[valueType]{}.Build(func(t *valueType) {
		*t = valueType{}
	})
}

func main() {

}
```

this type alias could significantly improve code readability, typically in complicate code.

**Comment by mknyszek** [comment]
Should this be moved to Go 1.20? This is a new feature and we're already in the freeze. CC @randall77

**Comment by mknyszek** [comment]
I'm told this is no longer a release blocker, so I'm dropping that label. I'll otherwise leave it as Todo and assigned to Keith.

**Comment by randall77** [comment]
This is now fixed with unified IR.
@mdempsky
