### ISSUE TITLE
x/tools/gopls: allow 'any' in completion results everywhere (remove filtering to constraints)

### ISSUE THREAD

**Issue by findleyr** [golang/go#47669]
When built with Go 1.18, gopls completion results erroneously include the new predefined type `any` in contexts where it is invalid (`any` is only valid for constraints).

We should exclude it whenever we are not completing constraints.

CC @stamblerre @griesemer

**Comment by findleyr** [comment]
I just looked into this, and we seem to be suggesting completion to 'any' in places where we shouldn't. Needs more investigation.

**Comment by findleyr** [comment]
Ok, it seems that completion just includes more results than I had assumed.

For example, from `internal/lsp/testdata/rank/binexpr_rank.go.in`:

```
func _() {
  _ = 5 +  ; //@complete(" ;", apple, pear)
}
```

We suggest `any` as a completion here, albeit with a low score, even though its type does not match. Specifically, we get [here](https://cs.opensource.google/go/x/tools/+/master:internal/lsp/source/completion/deep_completion.go;l=243;drc=15a2ab852e19848ec9846e071e4ff9e41fe52022), and keep going even though `c.matchingCandidate(cand)` returns false.

Given that we downrank, this is fine, but it does seem a bit noisy. @muirdm do you have an opinion on whether we should be suggesting `any` at all in this context? I would trust your intuition as to whether (1) we shouldn't offer completions that don't match the inferred type, or (2) we should offer (but downrank) all lexical completions.  It may eb

I don't think this it is a high priority to resolve this for v0.8.0, so moving it to the v0.8.1 milestone while we discuss.

**Comment by muirdm** [comment]
I think you want to add "any" to tools/internal/lsp/tests/util.go:isBuiltin. That is used to filter buiiltin candidates in completion tests.

We don't filter type names in general because it's hard to predict what the user wants to do. For example, they may want to complete to an incompatible type "someType" so they can write "someType(foo).someMethod()". Or maybe they don't realize the type is incompatible and would be confused by it not showing up. Or maybe they are composing an expression inside-out where they first insert "someType{}" and then wrap it in "somethingElse(someType{})".

"any" in particular doesn't seem useful, but unless there is a compelling reason to filter it I wouldn't bother.

**Comment by findleyr** [comment]
Haven't gotten to this, and it's a low priority because including 'any' in results doesn't add a huge amount of value. Bumping to the backlog.
