### ISSUE TITLE
cmd/compile: some unreasonable in BCE decision making for global slices

### ISSUE THREAD

**Issue by go101** [golang/go#47736]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

var s = make([]int, 100)

func f() (r int) {
	for i := range s {
		r += s[i] // bound check eliminated
	}
	return r
}

func g() {
	for i := range s {
		s[i] = i // need bound check
	}
}

func main() {
}
```

### What did you expect to see?

Both bound checks are eliminated or both not.

### What did you see instead?

One is eliminated but the other is not.

**Comment by mknyszek** [comment]
CC @randall77 @mdempsky via https://dev.golang.org/owners

**Comment by randall77** [comment]
I believe this is because there are no writes in `f`. All the loads of `s` get coalesced into a single load, so prove can tell that the slice you're ranging over is the same as the one you're indexing.
In `g`, there's a write, so the `s` inside the loop is reloaded every time. That `s` might have a different length, so a bounds check is needed.

I don't think this qualifies as a bug. Closing. Maybe there's something that could be done with `g`, like proving that the location written doesn't alias the `s` global, but we haven't gone there yet.
