### ISSUE TITLE
x/pkgsite: grouped search fails to group some modules

### ISSUE THREAD

**Issue by jba** [golang/go#47839]
On https://beta.pkg.go.dev/search?q=xxhash, `github.com/cespare/xxhash/v2` and  `github.com/cespare/xxhash` aren't grouped together as "Other major versions."

For mvdan.cc/sh, is listed under v3, but also duplicated below it.

**Comment by julieqiu** [comment]
Here's an example for a gopkg.in package:

https://beta.pkg.go.dev/search?m=package&q=yaml

<img width="694" alt="Screen Shot 2021-08-20 at 9 37 46 AM" src="https://user-images.githubusercontent.com/5943521/130241789-af38dd5a-24e8-414d-851f-5f9ec7d7b525.png">

In this case gopkg.in/yaml.v3 should be grouped under gopkg.in/yaml.v2, since gopkg.in/yaml.v3 does not have a tagged version.
