### ISSUE TITLE
x/build/cmd/coordinator: health check for tip.golang.org reports a false positive of "404 not found"

### ISSUE THREAD

**Issue by mknyszek** [golang/go#47848]
https://farmer.golang.org/ is reporting https://tip.golang.org as down, but it's clearly up.

CC @rsc @dmitshur

**Comment by mknyszek** [comment]
Just kidding, this is likely due to a recent redeploy, and there's a lag. Closing.

**Comment by mknyszek** [comment]
Just kidding again. Turns out this is weird. @dmitshur said he'd look into it.

**Comment by dmitshur** [comment]
tip.golang.org is served by x/website/cmd/golangorg as of [CL 335049](https://golang.org/cl/335049), and we need to update this health check. It still points to a /_tipstatus URL, which isn't served by the new tip server, hence the 404 report.

We added that health check in [CL 185981](https://golang.org/cl/185981), since back then it was served by an x/build service. I expect websites (tip.golang.org, go.dev, etc.) will have their own monitoring, and now that it's not tied to x/build infrastructure, there's no need for just a tip.golang.org health check to show up on https://farmer.golang.org/#health.

CC @rsc, @golang/release.
