### ISSUE TITLE
x/website/go.dev: playground snippets in blog posts fail to run

### ISSUE THREAD

**Issue by ElvisAttro** [golang/go#48011]
### What is the URL of the page with the issue?
The issue seems to appear on  playground code snippets of any article on **The Go Blog**,  like [Strings, bytes, runes and characters in Go](https://go.dev/blog/strings)

### What is your user agent?

<pre>

Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0

</pre>

### OS
<pre>

Linux 5.13.12_1 #1 SMP Wed Aug 18 11:48:14 UTC 2021

</pre>

### What did you expect to see?

Code results output from playground remote server.

### What did you see instead?
<pre>

Error communicating with remote server.
Program exited.

</pre>

### Screenshot
![Screenshot_20210827-120509~3](https://user-images.githubusercontent.com/10562122/131125606-75682062-63f1-48e2-9f4a-817b90b4bb1a.png)

**Comment by citizen233** [comment]
@dmitshur The changes you mentioned can indeed solve the problem
But I found that the problem is：`playground.Proxy()` 
`mux.Handle("/compile", playground.Proxy())`
(Source:  #[cmd/golangorg/server.go#193](https://go.googlesource.com/website/+/80d620c2e526e20cc1da185ba5a47a1d2dc47c62/cmd/golangorg/server.go#193))
After I debugged with a breakpoint, I found that the expected content could not be obtained through `req.Body`
So I modified:
`r, err := post(ctx, url, req.Header.Get("Content-Type"), req.Body)`   ->  `r, err := post(ctx, url, req.Header.Get("Content-Type"), strings.NewReader(req.Form.Encode()))`
Then it can work normally

**Comment by citizen233** [comment]
> I think this issue can be fixed by changing go.dev's playground.js script as follows:
> 
> ```diff
> -$.ajax('/compile', {
> +$.ajax('https://play.golang.org/compile', {
> ```
> 
> _(Source: [go.dev/_content/js/playground.js#L126](https://go.googlesource.com/website/+/80d620c2e526e20cc1da185ba5a47a1d2dc47c62/go.dev/_content/js/playground.js#126).)_
> 
> And adding `https://play.golang.org` to go.dev Content Security Policy's `connect-src` field:
> 
> ```diff
>  "connect-src": {
>  	"'self'",
> 	"https://golang.org",
> +	"https://play.golang.org", // For running playground snippets on the blog.
> ```
> 
> _(Source: [cmd/golangorg/csp.go#L44](https://go.googlesource.com/website/+/80d620c2e526e20cc1da185ba5a47a1d2dc47c62/cmd/golangorg/csp.go#44).)_

Hi @dmitshur The changes you mentioned can indeed solve the problem, my solution is to solve the problem of the `playground.Proxy` method
