### ISSUE TITLE
Runtime: Deleting the key in the map has a probability of unexpected results

### ISSUE THREAD

**Issue by TOXICAKE** [golang/go#48051]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/cnl9hc5s7tj4ww_jzzq0sz4m0000gn/T/go-build2258945684=/tmp/go-build -gno-record-gcc-switches **-fno-common"**
</pre></details>

### What did you do?

https://play.golang.org/p/6rUpr0zUo_t
The function problem() has a 12 percent probability of running with different results

### What did you expect to see?

5000 Right   0 Wrong

### What did you see instead?
4396 Right    626 Wrong
4377 Right    622 Wrong
4366 Right    633 Wrong
.....
Each run results differently

**Comment by dsnet** [comment]
I believe this is working as intended. According to the [Go specification on range semantics](https://golang.org/ref/spec#For_range):
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next. If a map entry that has not yet been reached is removed during iteration, the corresponding iteration value will not be produced. *If a map entry is created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next. If the map is nil, the number of iterations is 0.*

The relevant section is italicized. In the range loop on L14-16, the test code is inserting new entries into the map. Since the specification says that these newly added entries may or may not be visited in future iterations, the result of calling `problem` is going to be non-determinstic. In fact, a valid implementation of Go could theoretically cause `problem` to loop indefinitely and consume all memory since it keeps trying to visit newly added entries.
