### ISSUE TITLE
the builtin function `append` annotations looks like should be updated

### ISSUE THREAD

**Issue by Jeyrce** [golang/go#48089]
### What version of Go are you using (`go version`)?

<pre>
1.16.7

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
amd64

</pre></details>

### What did you do?

I saw the annotation for builtin function `append`, found it seems make mistake

```
// The append built-in function appends elements to the end of a slice. If
// it has sufficient capacity, the destination is resliced to accommodate the
// new elements. If it does not, a new underlying array will be allocated.
// Append returns the updated slice. It is therefore necessary to store the
// result of append, often in the variable holding the slice itself:
//	slice = append(slice, elem1, elem2)
//	slice = append(slice, anotherSlice...)
// As a special case, it is legal to append a string to a byte slice, like this:
//	slice = append([]byte("hello "), "world"...)
func append(slice []Type, elems ...Type) []Type
```

### What did you expect to see?

I tried  append([]byte("s"), "x"), but can not run it

### What did you see instead?

Is the annotation should be updated?

**Comment by robpike** [comment]
You said you can run it. Can you? I get

```
./prog.go:4:12: cannot use "x" (type untyped string) as type byte in append
```

which is the error I expected. Perhaps you think "x" is a byte, but it is not: it is a string containing one byte. Try 

```
append([]byte("s"), 'x')
```

instead.

**Comment by Jeyrce** [comment]
Yeah, `rune` type is the same as `byte` so it works, but the annotation in builtin.go is:

```
// As a special case, it is legal to append a string to a byte slice, like this:
//	slice = append([]byte("hello "), "world"...)
func append(slice []Type, elems ...Type) []Type
```

It doesn't work, so do we need to update the annotation?

**Comment by rsheasby** [comment]
I think @Jeyrce misunderstood the annotation a bit. The relevant part of the annotation is this:
```
// As a special case, it is legal to append a string to a byte slice, like this:
//	slice = append([]byte("hello "), "world"...)
```

Note that what @Jeyrce tried was this:
```
append([]byte("s"), "x")
```

This is incorrect, because you're missing the `...` after `"x"`.

The way that special case works is like so:
When you add `...` to the end of a slice, it separates it out into an individual argument per element, to be passed to a variadic function (like append). So by adding `...` to the end of the string literal (since strings are byte slices under the hood), it's being separated out into a bunch of bytes, which then appended to the slice of bytes.

**Comment by Jeyrce** [comment]
@rsheasby @robpike Thank you, I really did misunderstand the annotation,  ignored the ... syntax.

**Comment by rsheasby** [comment]
@robpike In the interest of preventing future confusion, maybe that part of the annotation should be removed entirely, since as far as I can tell that's not actually a special case at all, is it? It seems to me that it's no different to ordinarily passing a byte slice:
https://golang.org/ref/spec#Passing_arguments_to_..._parameters

> If the final argument is assignable to a slice type []T and is followed by ..., it is passed unchanged as the value for a ...T parameter. In this case no new slice is created.

As string is assignable to a slice type []byte, this doesn't seem like a special case?
