### ISSUE TITLE
cmd/compile: -B on 32bit GOARCHs causes internal compiler error

### ISSUE THREAD

**Issue by divVerent** [golang/go#48092]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rpolzer/.cache/go-build"
GOENV="/home/rpolzer/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rpolzer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rpolzer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rpolzer/homedir/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rpolzer/homedir/src/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1448838183=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ cat > hello.go
package main

func main() {
}
^D
$ GOOS=windows GOARCH=386 go build -gcflags='all=-B' hello.go
</pre>

### What did you expect to see?

A Win32 PE EXE file that does nothing.

### What did you see instead?

```
# internal/abi
/home/rpolzer/homedir/src/go/src/internal/abi/abi.go:52:30: internal compiler error: '(*IntArgRegBitmap).Get': not lowered: v16, Unknown UINT8

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

Note: without the `-B` flag, the issue does not occur. On `linux/amd64` and `windows/amd64` `-B` is fine to use and improves performance.

**Comment by ALTree** [comment]
It looks like the crash is triggered when compiling internal/abi:

```
$ GOARCH=386 go build -gcflags=-B internal/abi

# internal/abi
/usr/local/go/src/internal/abi/abi.go:42:29: internal compiler error: '(*IntArgRegBitmap).Set': not lowered: v14, Unknown UINT8
```

Tip also crashes. Other GOARCHs are also affected. Both `arm` and `mipsle` crash too.

cc @randall77 @mknyszek @aclements

**Comment by randall77** [comment]
This happens when we do:
```
type A [0]int
var a A
x := a[i]
```
The compiler uses an explicit "never use me" value for `x`, because it knows that the bounds check can never succeed, and thus the value of `x` must be on a dead path in the CFG. But then with `-B`, uses of `x` *aren't* on dead paths, and the compiler rightly complains it is trying to use a "never use me" value.

This happens in `internal/abi` for all the architectures that haven't been converted yet (everything except amd64 and arm64), because `IntArgsReg` is 0, and thus `IntArgRegBitmap` is `[0]uint8`.

It's not entirely clear to me that this is a bug worth fixing. `-B` is really a bleeding edge kind of request. Asserting to the compiler that all bounds checks will pass, while giving it code where the bounds check cannot possibly pass, is asking for trouble. That said, the fix is easy (use the zero value of `x`'s type), and it's probably worth having the stdlib at least compile with `-B`, even if it would never run correctly like that.

**Comment by randall77** [comment]
I don't think this is worth backporting, though. It's easy enough to work around by either not indexing 0-length arrays, or not using `-B`.

**Comment by divVerent** [comment]
I agree that a backport is not needed here.

However it puzzled me to seriously think this was not worth fixing. It
means that library code that comes with Go did not compile with the
compiler it comes with, assuming a specific flag that doesn't have such an
indication.

(But a fix in the library code to not index 0-sized arrays would of course
have been just as good)

Anyway, thanks for the fix!

**Comment by randall77** [comment]
`-B` isn't really intended to be used by anybody. When you use `-B` the compiler isn't adhering to the Go spec any more. It's intended just to be used for measuring the overhead of bounds checks. We've been discussing removing `-B` altogether.
