### ISSUE TITLE
refspec: wrong underlying type?

### ISSUE THREAD

**Issue by krmpotic** [golang/go#48162]
https://github.com/golang/go/blob/065f3808156c92d957fc1ad2a2a37e147ee628f4/doc/go_spec.html#L828

isn't the underlying type []string and not []B1?

**Comment by deanveloper** [comment]
No, "underlying type" is defined as follows:
> Each type T has an underlying type: If T is one of the predeclared boolean, numeric, or string types, or a type literal, the corresponding underlying type is T itself.
Otherwise, T's underlying type is the underlying type of the type to which T refers in its type declaration.

So for `type T2 T1; type T1 string`, the underlying type of `T2` is `string`, because the underlying type of `T2` is the underlying type of `T1`, which is `string` (whose underlying type is itself).

For `type T3 []T1`, the underlying type of `T3` is `[]T1` because `[]T1` is a type literal, which means that its underlying type is itself.

**Comment by seankhliao** [comment]
See above and https://golang.org/ref/spec#Type_identity

> Two slice types are identical if they have identical element types.

**Comment by krmpotic** [comment]
thanks!
