### ISSUE TITLE
x/tools/gopls: use conventional variable names when filling function signatures

### ISSUE THREAD

**Issue by seankhliao** [golang/go#48260]
Given the following example

```go
package main

import "context"

type Foo struct {
	F func(context.Context, error)
}

func main() {
	foo := Foo{
		F: <cursor here>,
	}
	_ = foo
}
```

gopls will offer to generate the function signature

```go
	foo := Foo{
		F: func(c context.Context, e error) {
                },
	}
```

It would be nice to have it use the more conventional variable names of `ctx` and `err` for the 2 types

**Comment by muirdm** [comment]
Another notable instance of this problem is `http.HandleFunc` where you get a ResponseWriter named "rw" instead of "w".

A workaround for now is to give the parameters names in the type signature (e.g. `F func(ctx context.Context, err error)`).

**Comment by ShoshinNikita** [comment]
The fix is pretty simple. But I think it would be better to add more common acronyms. I could come up with the following list:

| Type                         | Current | Common |
| ---------------------------- | ------- | ------ |
| `context.Context`            | `c`     | `ctx`  |
| `error`                      | `e`     | `err`  |
| `sql.Tx`, `sqlx.Tx` and etc. | `t`     | `tx`   |
| `http.ResponseWriter`        | `rw`    | `w`    |

Did I forget something?
