### ISSUE TITLE
archive/tar: rounding timestamps to the nearest second may result in archives from the future

### ISSUE THREAD

**Issue by milahu** [golang/go#48275]
when a tar archive, generated by `archive/tar/writer.go`, is extracted immediately,
tar shows warnings that some timestamps are in the future

downstream issue: https://github.com/ipfs/go-ipfs/issues/8406
downstream workaround: https://github.com/ipfs/go-ipfs-files/pull/41

probably here, `Floor` should be used

https://github.com/golang/go/blob/b86e8dd0f3a27bc9577690523c9feeb25593bec7/src/archive/tar/writer.go#L83-L92

**Comment by dsnet** [comment]
I don't think there's a right answer here. The current logic is entirely reasonable as it optimizes for accuracy at the cost of occasionally being in the future for 500ms. The suggested logic is 500ms less accurate, but avoids being in the future. Both are reasonable and I don't think it's a compelling reason to change, since this will probably break many use-cases that have come to depend on `archive/tar` for deterministic outputs (see [Hyrum's Law](https://www.hyrumslaw.com/)).

Have you considered using [`FormatPAX`](https://pkg.go.dev/archive/tar#FormatPAX)? That supports high-precision timestamps and may entirely avoid this problem. Also, whatever is flagging archives from the future should probably tolerate an error on the same order as the smallest representable time unit (1s in this case).

**Comment by milahu** [comment]
> this will probably break many use-cases that have come to depend on `archive/tar` for deterministic outputs (see [Hyrum's Law](https://www.hyrumslaw.com/)).

yepp, api consumers hate surprises

its just unexpected behavior, cos usually float-to-int casts mean rounding down

> Have you considered using [`FormatPAX`](https://pkg.go.dev/archive/tar#FormatPAX)? That supports high-precision timestamps and may entirely avoid this problem.

workaround in ipfs: pass integer time to archive/tar

```diff
 func writeFileHeader(w *tar.Writer, fpath string, size uint64) error {
 	return w.WriteHeader(&tar.Header{
 		Name:     fpath,
 		Size:     int64(size),
 		Typeflag: tar.TypeReg,
 		Mode:     0644,
-		ModTime:  time.Now(),
+		ModTime:  time.Now().Truncate(time.Second),
 	})
 }
```


> whatever is flagging archives from the future should probably tolerate an error on the same order as the smallest representable time unit (1s in this case).

yes. in this case nixos [unpackFile](https://github.com/NixOS/nixpkgs/blob/7c38b03f742a657bf38e9579adeb608fc7cc5f1a/pkgs/stdenv/generic/setup.sh#L851) &rarr; _defaultUnpack &rarr; `tar xf "$fn"`
this should be `tar xf "$fn" --warning=no-timestamp`

thanks! : )

closing

**Comment by dsnet** [comment]
That seems like an entirely reasonable and easy workaround.
