### ISSUE TITLE
spec: contradiction in the definition of terminating statements

### ISSUE THREAD

**Issue by 3bodar** [golang/go#48323]
According to [https://golang.org/ref/spec#Terminating_statements](https://golang.org/ref/spec#Terminating_statements), the `if` statement below is a terminating statement by virtue of `1.`, `3.`, and `4.`:

```go
func main() {
    if true {
        goto L
    } else {
        goto L
    }
L:  println("this gets printed")
}
```

At the same time, the first sentence reads:

> A terminating statement prevents execution of all statements that lexically appear after it in the same block.

The labeled statement, however, gets executed.

**Comment by ALTree** [comment]
You don't need an *if* to find a contradiction if you read that sentence about preventing execution in that way, just take:

```
func main() {
	goto L
L:
	println("hi")
}
```

`goto L` is terminating due to (1) and yet the println( ) call gets executed.

But really it seems to me that in this sentence:

> A terminating statement prevents execution of all statements that lexically appear after it in the same block

"prevents execution" only means that the control is transferred elsewhere. But if the control goes back to these  statements (for example due to a GOTO) then nothing forbids them to be executed.

cc @griesemer

**Comment by 3bodar** [comment]
Good point.

Btw, I found the backstory of that sentence: [https://github.com/golang/go/issues/23215](https://github.com/golang/go/issues/23215).

**Comment by griesemer** [comment]
Actually, I think @3bodar has a point - the informal clarification I added in [CL 85215](https://go-review.googlesource.com/c/go/+/85215) looks incorrect to me, now. The definition clearly says that a `goto` statement is a terminating statement. Yet, the labeled statement following it is in the same block and it _is_ executed.

The notion of a _terminating statement_ is only used in one place in the spec, for functions returning results. For that purpose, the definition is correct (if a labeled statement is the final statement in a statement list of such a function, that statement list is not terminating, if it's a `goto` statement, it is terminating). The informal clarification doesn't matter for this.

But the clarification is misleading as it is.

**Comment by 3bodar** [comment]
If that's the only role of the concept of terminating statements, something like

"The final non-empty statement in a function declaring result parameters must be a terminating statement."

might make more sense.

**Comment by griesemer** [comment]
@3bodar The spec [says that](https://tip.golang.org/ref/spec#Function_declarations) already. The original prose for terminating statements was correct; it's just the additional sub-sentence added with [CL 85215](https://go-review.googlesource.com/c/go/+/85215), intended to provide some intuition, was imprecise. We can make that more precise, or we can just remove it again.

**Comment by 3bodar** [comment]
@griesemer 
I see, that is said in the "Function declarations" section.

But even though the proposed change in [CL 349172](https://go-review.googlesource.com/c/go/+/349172/) fixes the incorrect sentence, it seems to me there are a couple issues with it:
- when I read the (correct) statement `A terminating statement terminates the regular flow of control in a block.`, it leaves me asking why aren't `break` and `continue` terminating statements.
- if I understand correctly, [https://github.com/golang/go/issues/23215](https://github.com/golang/go/issues/23215) was about clarifying to the reader the reason why the spec defines the notion in the first place. The changed version does not do that, I think.

So I would suggest a rewording of my original suggestion, to make it fit as an introcutory sentence:

"Terminating statements define the subset of statements permissible as the final non-empty statement in a function declaring result parameters."

This would repeat what is said elsewhere, but if prepended to the currently proposed change, would serve the purpose of clarifying why these are there at all.

P.S. I don't yet have a good grasp of the spec, so I may be making some wrong assumptions. If so, please ignore the above.

**Comment by griesemer** [comment]
"Terminating statements define the subset of statements permissible as the final non-empty statement in a function declaring result parameters." is a fine sentence to start the section - but as a matter of style and to avoid having subtle inconsistencies in the spec we have tried to avoid repeating ourselves. And as you say yourself, the sentence would only explain why this section is here in the first place, and not provide much intuition about the terminating statements.

I agree with you that trying to provide a precise intuitive explanation is likely going to be cumbersome which is why the pending CL doesn't try much in that direction. Let's see what the other reviewers say. We can always just say nothing and revert to the original prose which was correct. The primary goal here is to fix the inconsistency.

An alternative might be to put the definition of "terminating statements" into an appendix of the spec, as it primarily serves as a precise definition for a specific function requirement. Looking forward to the changes for generics, we may have more such sections in the near future which would fit best into an appendix.

But again, let's see what others think.
Thanks.
