### ISSUE TITLE
dev.boringcrypto: 1.17 release

### ISSUE THREAD

**Issue by sodul** [golang/go#48391]
1.17.0 and 1.17.1 have been released. What is the ETA for the release with BoringCrypto?

Thanks again for maintaining this great branch!

@katiehockman @FiloSottile

**Comment by ALTree** [comment]
Jeremy Faller has provided an update on a (tangentially) related [thread on golang-dev](https://groups.google.com/g/golang-dev/c/ZYMr6tFldhk/m/S3Io1PEaAwAJ):

> We had a small snafu with boringcrypto, as we're transferring responsibilities for it's maintenance around internally. This branch will be updated with the next point release for Golang. Following our published process, unless a security release causes rescheduling, that next point release will happen this week, and boringcrypto will be updated soon after now that we've sorted out responsibilities.

I'm closing here since I don't think we need an issue to track the boringcrypto work (it's internal to Google I believe, and traditionally there never was a github issue).
