### ISSUE TITLE
io: ReadAll doesn't respect io.ErrShortBuffer

### ISSUE THREAD

**Issue by utrack** [golang/go#48432]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
(not relevant)

### What did you do?
I create an `io.Reader` that sometimes returns `io.ErrShortBuffer`. Then, I try to slurp data from it via `io.ReadAll()`.

### What did you expect to see?
`io.ReadAll()` manages its buffer properly and retries `r.Read()` with a bigger buffer.

### What did you see instead?
`io.ReadAll()` returns `io.ErrShortBuffer` on a first `ErrShortBuffer` encounter.

### Notes
I believe that it should handle the `ErrShortBuffer` gracefully by default.

There's a memory management problem: faulty Reader might spam `ErrShortBuffer` and the buffer would grow exponentially; however, `ReadAll` doesn't care about that by default since the source itself is unbounded and data can outgrow available memory pretty easily.

Edit: oh, I've noticed that many reader implementations incl. bufio, bytes etc don't support ErrShortBuffer as well. Is there any canonical way to signal upstream that a buffer must be grown?

**Comment by ianlancetaylor** [comment]
> There's just no way for a downstream Reader to signal to upstream that this buffer isn't big enough for the read.

The `io.Reader` API does not provide any mechanism for that.  The expectation is that any type that implements `io.Reader` and can only read entire chunks at a time will do its own buffering.  There is no other way to honor the `io.Reader` interface.

As @ericlagergren says, an implementation of `io.Reader` should never return `io.ErrShortBuffer`.

I'm going to close this issue because I don't think there is anything to change here.  Please comment if you disagree.
