### ISSUE TITLE
x/build: Add GOAMD64 builders for go1.18

### ISSUE THREAD

**Issue by martisch** [golang/go#48505]
WIth #45453 we are introducing new compilation variants for AMD64. We should have dedicated builders that test these as these will make the go compiler use new instructions and generate different binaries in go1.18.

As far as I understand none of the current try or slow bots will test binaries that are generated with the new v2, v3, v4 setting of GOAMD64.

We can likely leave the v4 builder out for now as its unlikely to be used soon and if so we can defer having one until then.
If we need one we need to make sure that one runs on a cloud machine hardware that supports AVX512 (e.g. skylake server): https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

/cc @mdempsky @dmitshur @cagedmantis @randall77

**Comment by zx2c4** [comment]
> We can likely leave the v4 builder out for now as its unlikely to be used soon 

Worth noting that laptops are now shipping with AVX512, with this year's Tiger Lake laptops being somewhat popular. Or did you mean that Go doesn't yet use any avx512 instructions so it wouldn't be in use anyway?

**Comment by martisch** [comment]
Neither the runtime nor compiler use AVX512 and I dont expect them to do so anytime soon.

**Comment by ianlancetaylor** [comment]
@golang/release  This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by dmitshur** [comment]
This issue remains in our queue, but moving out of the 1.18 milestone since it can happen independently of the release, and is not deemed critical enough to block it.

Since I've already paged in the relevant context, sent [CL 386116](https://go.dev/cl/386116) for review to get the ball rolling on this. Once it works well, we can consider making it a TryBot.

@randall77 made a suggestion of starting with just the v3 builder first, leaving v2 (and v4) for later, which is what I've done so far.

**Comment by dmitshur** [comment]
Data so far shows the builder is working well. It caught one small test problem in CL 391694 (fixed in CL 392994).

It's hard to definitively predict whether making it a TryBot by default is worthwhile, especially since it can be requested as a [SlowBot](https://go.dev/wiki/SlowBots) when needed. I'll mail a CL that just removes the known issue for now, and we can come back to the decision later, when there's more data.
