### ISSUE TITLE
runtime: crash shows autogenerated type parameters

### ISSUE THREAD

**Issue by rsc** [golang/go#48578]
I have a parameterized type named Treap[K, V].
Here's a crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x108e2e5]

goroutine 1 [running]:
math/big.(*Int).Cmp(0x30, 0x10aee80)
	/Users/rsc/go/src/math/big/int.go:328 +0x25
main.(*Treap[.shape.*uint8_0,.shape.*uint8_1]).Get(0x10d7ec0, 0xc0000c0570, 0xc0000d7d40)
	/Users/rsc/complex.go:145 +0x7b
main.explore(0x10d6500, 0xc0000ae008, 0x10b7929)
	/Users/rsc/complex.go:73 +0x4b
main.main()
	/Users/rsc/complex.go:51 +0x585
```

Note the `main.(*Treap[.shape.*uint8_0,.shape.*uint8_1]).Get`.

I understand why the name is needed in the binary, but it's not a great name to see in the stack trace.
It seems like we should probably elide that part, as in `main.(*Treap[...]).Get`,
or else make it more readable somehow.

/cc @randall77 @danscales

**Comment by danscales** [comment]
Seems like a good suggestion.

I think this might be the first case where we slightly change a function name in a backtrace, rather than completely omit the function entry (as with wrappers).    I guess maybe we can use the '...' as a good indication that the user that the name is not exactly what is in the binary (i.e. the user will see something different if they debug the crash in gdb).  Or maybe we can think of some further way to highlight the change (something at the beginning of the line?).

**Comment by randall77** [comment]
If we had access to the dictionary we could print the real type(s) the code is instantiated with, as if it was fully stenciled. That could be tough, though, as we'd need to keep the dictionary reference alive and in a known location.
