### ISSUE TITLE
net/http: Server.Close may not able to close all connections

### ISSUE THREAD

**Issue by shinny-chengzhi** [golang/go#48642]
I encountered lingering connection after calling Server.Close and it's not closed by Server.Close

Here is reproducible example: https://play.golang.org/p/9aLVDwWPQhH

The problem is http/server.go: Server.Serve function didn't check if Server is already closed before calling handler, and if Server.Close been called after l.Accept return but before c.setState(c.rwc, StateNew, runHooks), the new connection is not registered in the activeConn map when Server.Close try to close all connections.

The example code simulate this condition by sleep one second during ConnContext call. Program can exit corrected if this sleep is removed.

**Comment by mknyszek** [comment]
CC @neild

**Comment by AlexanderYastrebov** [comment]
@neild 

I think this was not the correct fix.
The change closes accepted connection also in graceful shutdown which
breaks the fix for #33313 (and apparent duplicate #36819).

The proper fix should close accepted connection only if server is closed
but not in graceful shutdown.

As I am not sure what is the correct way to revert the change I've created a #52823

**Comment by ianlancetaylor** [comment]
Fix is being reverted.

**Comment by ianlancetaylor** [comment]
@neild What is the status of this issue?  It's currently in the 1.19 milestone.  Thanks.

**Comment by RileyR387** [comment]
Also still seeing this in 1.19rc2... Who needs integration tests anyways!!
