### ISSUE TITLE
invalid AST: method must have no type parameters，methods cannot have type parameters

### ISSUE THREAD

**Issue by a97077088** [golang/go#48793]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel go1.18-123393a535 Tue Oct 5 01:30:56 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release? 

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

<pre>
package main

import (
	"fmt"
	"sync"
)

type A struct {
	mp sync.Map
}

func (a *A) Set(k string,v interface{})  {
	a.mp.Store(k,v)
}
func (a *A) Get[T any](k string) T {
	v,_:=a.mp.Load(k)
	return (interface{})(v).(T)
}
func NewA()*A{
	return &A{mp:sync.Map{}}
}

func main() {
	a:=NewA()
	a.Set("a","1")
	fmt.Println(a.Get[string]("a"))
}
</pre>

https://go2goplay.golang.org/p/ZzVGxEHe9QP

### What did you expect to see?

If everything is OK, he should return a value of type string

### What did you see instead?

.\main.go:15:17: invalid AST: method must have no type parameters
.\main.go:15:23: methods cannot have type parameters

**Comment by seankhliao** [comment]
This is working as intended

Ref: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods

**Comment by a97077088** [comment]
Thank you for your answer, so how should we implement this get [string]. Does it seem that we can only write one function? Is there no method that can execute chain calls

**Comment by LazarenkoA** [comment]
> 



> This is working as intended
> 
> Ref: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods

well it's very inconvenient

**Comment by ianlancetaylor** [comment]
We would implement it if we could.

**Comment by quenbyako** [comment]
I think the problem is in how generics works under the hood, in current implementation allowing type parameters in methods is impssible except using generics directly in type which owns this method. (@ianlancetaylor correct me please, if i'm wrong).

How to solve it? At this time, when this option is not allowed, try to build it in functional way, like

```go
func GetFrom[T any](from *A, k string) T {
   ...
}
```

Is it shiny and cool-looking? Not really. But at least, this way is better than using interfaces before 1.18.

----------

And btw: Hi people from future! 👋 We are you in the past, we still have these problems 🙃 Yeah, i know, i know, you have already flight cars already, and banned protobuf in your time, so i think now these issues is not a problem for you...


Right?...

**Comment by aadog** [comment]
It looks weird if it doesn't support method types

**Comment by ti** [comment]
> This is working as intended
> 
> Ref: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods

Does anyone know the time line for this basic feature?

**Comment by ianlancetaylor** [comment]
@ti There is on timeline for this feature because, as explained at the link, we do not understand how to implement it.

**Comment by ti** [comment]
The question is the generics function in the package is works well, but if the  generics function in a struct is will be panic.

for exp:

Package generic function:

```go
package p1
// this is works ok
func Identity[T any](v T) T { return v }
```

Package generic function in a struct:

As the Type Parameters Proposal:
https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods

```go
package p1
type S struct{}
// this will be error in go 1.19 and go 1.18, the T is dynamic in runtime, it can not be init in the struct S
func (S) Identity[T any](v T) T { return v }
```

@ianlancetaylor Can you help us explain the current difficulties with dynamic generics in structs?

**Comment by ti** [comment]
As the explained at the link, we do not understand  Where is the design error of the interface below?

```go
package p1

type SI interface {
	Identity[T any](v T) T { return v }
}

// the implement of the SI 
type S struct{}
func (S) Identity[T any](v T) T { return v }
```

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand what you are asking.

In https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods I explained that we need to instantiate `p1.S.Identity[int]` but there is no clear way to do that.

**Comment by ti** [comment]
thanks for the explained, but  I still do't understand why you need to instantiate p1.S.Identity[int] , but do not need to instantiate p1.Identity[int]

**Comment by ianlancetaylor** [comment]
There is no `p1.Identity`, so I'm not sure what you mean.  Sorry.

**Comment by ti** [comment]
```go
package p1
// this is works ok
func Identity[T any](v T) T { return v }

type S struct{}
// this will be error in go 1.19 and go 1.18, the T is dynamic in runtime, it can not be init in the struct S
func (S) Identity[T any](v T) T { return v }
```

When I reread your explanation, I realized that there may be a series of problems caused by the interface having to initialize design，May be `interface design` and `generic design` has some conflict.

**Comment by esimov** [comment]
I know that Go is not a functional programming language, but with the official adoption of generics it can be headed towards a functional type of approach, so this is very inconvenient at least for the following reason. Let's suppose that I define a struct in the following way:

```go
type Bound[T constraints.Signed] struct {
	Min, Max T
}
```

Then there is this very simple generic function of checking the slice bounds. Of course this could be a little bit of an overhead of what we want to achieve, but for the sake of a functional programming approach I think this is acceptable. 

```go
func Bounds[C int, T any](s []T) Bound[int] {
	min, max := 0, len(s)

	return Bound[int]{
		Min: min,
		Max: max,
	}
}
```
Now if I want to introduce another functional style alike method of checking if a number is in between the bounds, the only way to achieve this is to write a method like `func (b *Bound) In[T any](min, max T) bool {}` which could be invoked in the following way.

```go
if Abs(nth).In(Bounds(s)) {...}
```
instead of checking in the defacto Go way: `if Abs(nth) >= bounds.Min && Abs(nth) <= bounds.Max {}`

**Comment by aadog** [comment]
Generic implementation is terrible
