### ISSUE TITLE
internal/fuzz: internal panics are reported as unexpected crashes and written to testdata

### ISSUE THREAD

**Issue by katiehockman** [golang/go#48804]
There are a few things that could go wrong in the worker that we know is our fault, so we panic in those situations. For example: https://cs.opensource.google/go/go/+/e213c72fb9492a409bd0ed9620ca9aaaa96ddebe:src/internal/fuzz/worker.go;l=691;bpv=1

However, in playing around locally, it looks like if a panic like this occurs, then we just end up printing something like this:

```
  fuzz: elapsed: 0s, execs: 0 (0/sec), new interesting: 0 (total: 1)
  fuzz: elapsed: 0s, execs: 1 (6/sec), new interesting: 0 (total: 1)
  --- FAIL: FuzzFoo (0.15s)
      fuzzing process terminated unexpectedly: exit status 2
      Crash written to testdata/fuzz/FuzzFoo/bdb8f273...
      To re-run:
      go test m -run=FuzzFoo/bdb8f273...
  FAIL
```

First of all, the panic text is lost, so the developer has no idea what went wrong.
Secondly, it writes the crash to testdata even though we already know this is a bug in our code, so we shouldn't do that.

/cc @golang/fuzzing

**Comment by dmitshur** [comment]
Thanks for asking about this.

To me, it seems like resolving this issue is in scope of the freeze as it's fixing a known bug in the fuzzer—a feature that is already in scope for Go 1.18. A freeze exception would be needed if requesting to start completely new work after the freeze, whereas this issue was filed a month ago and is improving stability/UX of something that has already landed.

So, I'll remove the suffix for now and I think you should proceed. Thanks.
