### ISSUE TITLE
cmd/vet: printf analysis no longer flags interfaces that don't implement error

### ISSUE THREAD

**Issue by findleyr** [golang/go#48931]
I'm not sure if this is a bug or a feature.

In [CL 177601](https://go-review.googlesource.com/c/tools/+/177601/6/go/analysis/passes/printf/types.go#43), it was explicitly noted that `%w` verbs would not match `interface{}`.

Subsequently, in [CL 217180](https://golang.org/cl/217180), printf analyzer logic was changed to account for the fact that any argument of interface type _could_ be a `fmt.Formatter`. More context in #36564.  As a side-effect, we no longer report diagnostics if arguments for `%w` of interface type do not implement `error`.

Either one of these outcomes is reasonable to me:
- the type system allows us to express 'implements' relationships between interfaces, so it is likely a user error if the argument type for `%w` does not implement error (the same is not true of, say, `%d`, as we can't currently express that an interface's dynamic type is integral).
- ...but on the other hand we have very low tolerance for false positives in vet. If reasonable user code is generating a false positive, it should be fixed.

I just wanted to flag this inconsistency. What is correct here?

CC @neild @timothy-king

(FWIW, I'm interested in this as a matter of precedent, as I'm trying to figure out what to do with type parameters, where users may express structural restrictions on the underlying of a type parameter).

**Comment by neild** [comment]
My opinion in [CL 177601](https://go-review.googlesource.com/c/tools/+/177601/6/go/analysis/passes/printf/types.go#43) was that I couldn't think of any real-world cases where you would want to use the `%w` verb on an interface value that doesn't implement `error`, and that you can trivially write a `x.(error)` type assertion to convert back to an `error` in the unlikely case that this comes up.

In the time since the check being added, I don't think I've ever heard of a `vet` false positive for this case.

I think `vet` should continue to flag using the `%w` verb with a value that is not an `error`.

**Comment by timothy-king** [comment]
Bit late to the party. I am having a hard time recalling a real false positive, and I am struggling to think of a realistic false positive. A piece of support for being strict (/ suggesting `x.(error)` as a replacement) is the documentation for `fmt.Errorf`:
> It is invalid to include more than one %w verb or to supply it with an operand that does not implement the error interface.
