### ISSUE TITLE
cmd/go: missing version diagnostic when a package in the main module imports a package from a newer release

### ISSUE THREAD

**Issue by andig** [golang/go#48966]
Given

```
module example.com/M

go 1.16
```

and using `embed` as part of that module, I'm experiencing a lot of user's questions where compilation fails due to go versions below 1.16. Having declared dependency on go1.16 syntax/libraries as part of `go.mod` it would be nice if the compiler would fail if the module version of the main module or it's dependencies are not met during build. It could be optional behaviour behind a flag.

I realise this might cause breakage for modules who's authors use the highes available go version as part of their `go.mod` to be "compatible", but that approach seems flawed anyway.

**Comment by bcmills** [comment]
What kind of errors are your users reporting? When the build fails, they should be getting an explicit notice about the version mismatch already.

**Comment by zacho314** [comment]
I'd like to look into this issue - @bcmills do you some pointers on how to fix it?

**Comment by bcmills** [comment]
@zacho314, the error message that we see is from an `ImportMissingError`:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modload/import.go;l=54-56;drc=master

Generally when we see an `ImportMissingError` we attribute that to the package being imported, but in this case we want to *also* attribute the error to the importing package, since we can't tell whether the error is due to a missing standard-library package or a missing package to be provided by a `replace` directive.

I suspect that the point where we're reporting the error today is here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modload/load.go;l=1205;drc=master

What we need to propagate this error correctly is something like:
For each package `pkg`, if all of:
* `pkg` imports a package with an `ImportMissingError` for which `isStd == true`
* `pkg.mod` specifies a higher Go version than the current version,
* and `pkg.err` is nil,
then set `pkg.err` to an error that indicates the mismatched version.

We already have a “for each package `pkg`” loop that also iterates over imports today in `(*loader).buildStacks`; that might be a decent place to put the above logic as well.

**Comment by lazerkat** [comment]
I plan on looking into this if @mzacho isn't actively working on it.
