### ISSUE TITLE
crypto/tls: support ECDHE key exchanges when ec_point_formats is missing in ClientHello extension

### ISSUE THREAD

**Issue by yang-wei** [golang/go#49126]
### What did you do?

Per [rfc8422#section-5.1.2](https://datatracker.ietf.org/doc/html/rfc8422#section-5.1.2), 

> For backwards compatibility purposes, the point format list extension MAY still be included and contain exactly one value: the uncompressed point format (0).  RFC 4492 specified that if this extension is missing, it means that only the uncompressed point format is supported, so interoperability with implementations that support the uncompressed format should work with or without the extension

We are seeing TLS handshake failure (client and server failed to agree on ECDHE_ECDSA key exchange algorithem) when `ec_point_formats` is missing because we expect it to be listed in [tls/handshake_server.go](https://github.com/golang/go/blob/dc00dc6c6bf3b5554e37f60799aec092276ff807/src/crypto/tls/handshake_server.go#L317-L323)

```go
// supportsECDHE returns whether ECDHE key exchanges can be used with this
// pre-TLS 1.3 client.
func supportsECDHE(c *Config, supportedCurves []CurveID, supportedPoints []uint8) bool {
...
	supportsPointFormat := false
	for _, pointFormat := range supportedPoints {
		if pointFormat == pointFormatUncompressed {
			supportsPointFormat = true
			break
		}
	}

	return supportsCurve && supportsPointFormat
}
```

### What did you expect to see?

If `ec_point_formats` is missing in ClientHello, we will allow ECDHE key exchanges because  `it means that only the uncompressed point format is supported`

**Comment by yang-wei** [comment]
Hey, how is everything? Any updates on this?

**Comment by wqweto** [comment]
This issue is affecting Windows 11 and Windows Server 2022 built-in Schannel library latest TLS 1.3 implementation.

It seems TLS1_3_CLIENT sends `supported_groups` (10) extension but does not send `ec_point_formats` (11) on ClientHello message.

**Comment by ianlancetaylor** [comment]
CC @golang/security 

Looks like this didn't make 1.19.  Moving to backlog.  Please recategorize as appropriate.

**Comment by cipherboy** [comment]
@ianlancetaylor Any movement on this? Hashicorp is also affected, per duplicate ticket. Though, in this case it is TLSv1.2-only client, not a TLSv1.3 client (unlike this OP).

**Comment by wqweto** [comment]
@cipherboy Btw, the PR #49127 above is from Oct 23, 2021 and modifies a [single line](https://github.com/golang/go/blob/9bcac6a60c75bc329b0116fc86b221bc4620304c/src/crypto/tls/handshake_server.go#L319).

**Comment by rolandshoemaker** [comment]
We're planning on landing a fix for this in 1.20.

**Comment by torntrousers** [comment]
So am i right in thinking 1.20 will be about early 2023? Is there really no way to get it out before then? Go is clearly broken and doesn't support the TLS spec properly and there is a one line fix...

**Comment by heavenisme** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by FiloSottile** [comment]
Interestingly, this is only hit when using the Windows TLS1_3_CLIENT (or a different client that omits the extension) to reach a TLS 1.2-only Go server, because the extension is ignored entirely when negotiating TLS 1.3. This probably explains why it was only noticed for test sites (https://github.com/golang/go/issues/49126#issuecomment-972987103) which might disable TLS 1.3 to test for vulnerabilities, and why it didn't cause widespread breakage.

Still, considering the duplicates that were filed, the fact that we're the odd one out in getting this wrong, the fact that we're off-spec, the fact that this is not something applications can workaround (unless they can upgrade to TLS 1.3), how this kind of issue tends to add complexity to the ecosystem in the form of workarounds, and the simplicity of the fix, I think we should backport it.

PR #49127 / [CL 358116](https://golang.org/cl/358116) is an incomplete fix because we should not send the extension back when the client didn't send it. I'll send a new fix in a second.

@gopherbot please open backport issues for both supported releases.
