### ISSUE TITLE
x/tools/cmd/godoc: document as deprecated 

### ISSUE THREAD

**Issue by jba** [golang/go#49212]
Document this program as deprecated, and point users to golang.org/x/pkgsite/cmd/pkgsite.

**Comment by derCodemeister** [comment]
I do not think that godoc should be deprecated. It serves a different purpose from pkgsite.
I use godoc as a local webserver for the documentation to my unpublished packages and as a reference for the go standard library. I do not want a local copy of the go.dev website. pkgsite also assumes you have a working internet connection, since all links but pkg-search connect to go.dev, while godoc is completely local. With pkgsite  I have to know what I am looking for, since there is no index of the packages in the standard lib. Also a local pkgsite seems to me to be quite unrealiable. After 
go install golang.org/x/pkgsite/cmd/pksite@latest it claimed to be installed, but just does not work. The website comes up at port 8080, but all searches fail. 
Hence I am wondering why a working program is supposed to be replaced by some much more unreliable and fragile piece of software that does not even cover the use cases of the orignal software. Also pkgsite has way too many dependieces which are not used at all in a local setup - this makes the software much more fragile and also increases its size by a factor of 4. I am wondering how this holds up to gos principle of simplicity.  godoc serves a simple purpose, pkgsite does not. I consider local use of pkgsite wrong and against the principles of go.
