### ISSUE TITLE
database/sql : Unsigned integer for affected rows and last insert id

### ISSUE THREAD

**Issue by Naidile-P-N** [golang/go#49311]
https://github.com/golang/go/blob/6458b2e8db7c4529248934f7e491df02d1e89318/src/database/sql/sql.go#L3367

Affected rows are always positive and usually the auto increment ID is preferred to be positive, so can we have new unsigned fields for these two props in the result

Issue for similar change in go-sql-driver/mysql : https://github.com/go-sql-driver/mysql/issues/1278

**Comment by Naidile-P-N** [comment]
Would like to contribute if accepted

**Comment by thanm** [comment]
Thanks for raising this issue.  

Use of unsigned would seem to make sense as you point out, but unless I am misreading the code, making such a change would wind up breaking the Go compatibility guarantee, set out in https://golang.org/doc/go1compat.

@bradfitz @kardianos

**Comment by Naidile-P-N** [comment]
@thanm Yes. Updating existing fields wouldn't be feasible, we may introduce new properties though.

**Comment by ianlancetaylor** [comment]
In general Go prefers to use signed integers for numeric values, even if those values can never be negative.

This is because computer arithmetic, as compared to ordinary arithmetic, always has strange behaviors at some point.  For signed types the strange behavior is at very large or very small values.  For unsigned types the strange behavior is at zero.  In practice numbers close to 0 are much much more common than numbers that are very large or very small.  So it's better to use signed types.

Closing because we can't make this change in any case, as it would break the compatibility guidelines.
