### ISSUE TITLE
x/build: remove host-linux-riscv64-unleashed builder

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#49325]
From https://farmer.golang.org/#pools:

```
host-linux-riscv64-unleashed: 0/0 (1 missing)
```

@bradfitz Are you able to take a look?
@golang/release

**Comment by dmitshur** [comment]
Brad has provided root SSH access in [the past](https://github.com/golang/go/issues/41956#issuecomment-860333859). I've tried it now, and though the machine responds to pings, SSHing fails with "Network is unreachable".

Since @mengzhuo is running a `linux-riscv64-unmatched` builder, and @4a6f656c is running a `linux-riscv64-jsing` builder, which seem to be fairly stable and provide coverage for `linux/riscv64`, we can consider dropping this one if desired. Thoughts?

**Comment by bradfitz** [comment]
It does seem increasingly flaky.

I have it using a network block device for all storage so it doesn't wear out its SD card (which is basically only read-only and used for booting) but even with that, I find myself having to reboot it every few weeks. Maybe it's reached the end of its useful life.

I'm more than happy to stop running it if we have coverage otherwise. :)

**Comment by bradfitz** [comment]
Or: I do have an APC network PDU in the rack that it's in, so I can probably rig up some remote network reboot mechanism.
