### ISSUE TITLE
cmd/compile: improve messaging for Go version requirements

### ISSUE THREAD

**Issue by alecthomas** [golang/go#49368]
From helping out in the `#generics` channel on Gophers Slack, I've noticed that numerous people run into the following (or similar) error message when writing generics code against gotip:

```
embedding interface element ~int|~int8|~int16|~int32|~int64 requires go1.18 or later
```

As they _are_ using go-1.18, and the error message doesn't say anything about the "go" stanza in the `go.mod` file, they are left confused as to how to solve this.

I suggest that this error message be improved to include more detail, similar to:

```
embedding interface element ~int|~int8|~int16|~int32|~int64 requires go1.18 or later but go.mod specifies go 1.17
```

or

```
embedding interface element ~int|~int8|~int16|~int32|~int64 requires go1.18 or later but go 1.17 is being used
```

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by findleyr** [comment]
We don't want a type checker error message mentioning go.mod as we can't assume modules, but perhaps we could say something like 
```
embedding interface element ~int|~int8|~int16|~int32|~int64 requires go1.18 or later (-lang=go1.17)
```

I think we're unlikely to patch Go 1.17 or earlier for this.

**Comment by findleyr** [comment]
Another thought: something we've had on the back-burner for a while is exposing more structured data from type checker errors: an error code or wrapped error that can be interpreted by tools like the go command or gopls.

This is an example of where such additional signal could be useful, as the Go command or gopls could detect that an error was due to language version and suggest changing the go.mod `go` version.  Unfortunately that's not going to happen for 1.18, but perhaps we can still make the error message clearer.

**Comment by griesemer** [comment]
The type checker used by the compiler does know that it's used by the compiler (it's configured to issue compiler-specific error messages), so it could actually just use the old message of the compiler here that refers to the -lang flag. I will take care of this.
