### ISSUE TITLE
cmd/compile: wrong pcln entry for instruction

### ISSUE THREAD

**Issue by aarzilli** [golang/go#49436]
`go version devel go1.18-9e6ad46bcc Sun Nov 7 04:57:22 2021 +0000 linux/amd64`

Given https://play.golang.org/p/wsCMMD9Jk9J compiled with `-gcflags='-N -l'` the method PushBack compiles to:

```
TEXT main.(*List[go.shape.int_0]).PushBack(SB) ./buggy.go
...
  buggy.go:22		0x454a90		488b00			MOVQ 0(AX), AX					
  buggy.go:31		0x454a93		8400			TESTB AL, 0(AX)					
  buggy.go:22		0x454a95		c6400801		MOVB $0x1, 0x8(AX)				
...
```

The instruction 0x454a93 gets assigned to a line outside of the PushBack function, in this case it's the call to PushBack but in more complex examples can be something completely unrelated. Can't make this happen without embedding and type parameters.

cc @dr2chase

**Comment by hanchaoqun** [comment]
The error seems occurred in the stenciling, when transformDot is doing the XDOT to DOT conversion, the NewSelectorExpr called in AddImplicitDots passed the wrong Pos parameter, that should use n.X.Pos instead of base.Pos

https://github.com/golang/go/blob/9e6ad46bccfa7a63e768236bcd1fd54dab38e4d1/src/cmd/compile/internal/typecheck/subr.go#L163

<pre>
after noder2 (*List["".List.PushBack.V]).PushBack
...
.   .   .   AS tc(1) # pcln.go:22:22
.   .   .   .   XDOT main.Circular bool tc(1) # pcln.go:22:12
.   .   .   .   .   <b>XDOT main.root PTR-*ExtNode["".List.PushBack.V] tc(1) # pcln.go:22:7</b>
.   .   .   .   .   .   NAME-main.list Class:PPARAM Offset:0 OnStack PTR-*List["".List.PushBack.V] tc(1) # pcln.go:19:7
.   .   .   .   LITERAL-true bool tc(1) # pcln.go:22:24
...
</pre>

<pre>
stenciled (*List[%2eshape.int_0]).PushBack
...
.   .   .   AS tc(1) # pcln.go:22:22
.   .   .   .   DOT main.Circular bool tc(1) # pcln.go:22:12
.   .   .   .   .   <b>DOTPTR main.Node Implicit main.Node tc(1) # pcln.go:31:2</b>
.   .   .   .   .   .   <b>DOTPTR main.root PTR-*ExtNode[%2eshape.int_0] tc(1) # pcln.go:22:7</b>
.   .   .   .   .   .   .   NAME-main.list Class:PPARAM DictIndex:2 Offset:0 OnStack Used PTR-*List[%2eshape.int_0] tc(1) # pcln.go:19:7
.   .   .   .   LITERAL-true bool tc(1) # pcln.go:22:24
...
</pre>

**Comment by hanchaoqun** [comment]
Seems break #33724

**Comment by hanchaoqun** [comment]
> TryBot seems break #33724 on this CL： https://storage.googleapis.com/go-build-log/0fb605f4/linux-amd64-unified_8e0ac5a2.log

Ah..., n.X.Pos still the wrong Pos, we should use the SelectorExpr's Pos, not the X's. i think is ok now.
