### ISSUE TITLE
x/tools/gopls: Would it be possible to run `gopls.run_test` command in `json` mode?

### ISSUE THREAD

**Issue by tjdevries** [golang/go#49464]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, but it's more of a feature request (I can put this somewhere else if that's what is desired)

###  Feature Request?

Currently, the `gopls.run_test` works really great for viewing the test results! I love it. I was hoping it could be possible though to get the JSON results back to programmatically do something if there is a test failure.

An additional argument to [run_tests](https://github.com/golang/tools/blob/master/gopls/doc/commands.md#run-tests) of `JSON` would be appreciated. I understand if it's too odd of a request though.

Thanks!

**Comment by jadekler** [comment]
I'm taking a stab at this.

https://go-review.git.corp.google.com/c/tools/+/425954 is one quick hot take, using the easiest approach of just passing JSON to `protocol.ClientCloser`, rather than trying to do something more sweeping. The output is on `window/showMessage` and looks like this:

```
window/showMessage. params: {Type:3 Message:{"tests":{"ran":3,"passed":["TestYyy"],"failed":["TestXxx","TestZzz"]},"benchmarks":{"ran":0,"passed":["TestYyy"],"failed":null}}}
```

The structure is:

```
type Result struct {
    NumRan int      `json:"ran"`
    Passed []string `json:"passed"`
    Failed []string `json:"failed"`
}
type AllResults struct {
    Tests      *Result `json:"tests"`
    Benchmarks *Result `json:"benchmarks"`
}
```

@tjdevries is this kind of what you were looking for? Or, are you looking for something different? If so, maybe could you sketch out a "here's what I have in non-JSON form, where's how I would like to see it in JSON" to make the conversation a bit more concrete?

---------------

I came up with https://github.com/jadekler/lsprobe as a way to integration test a client and (gopls) server.

**Comment by jadekler** [comment]
Since this has been sitting for a bit now, I'll close the issue. We can circle back around if there's more discussion to be had later! =)

**Comment by findleyr** [comment]
Thanks @jadekler for looking into this!
