### ISSUE TITLE
runtime: more frequent TestFreeOSMemory failures starting 2021-11-05

### ISSUE THREAD

**Issue by bcmills** [golang/go#49478]
`greplogs --dashboard -md -l -e 'FAIL: TestFreeOSMemory'`

[2021-11-08T21:52:47-955f9f5/aix-ppc64](https://build.golang.org/log/f0b8a3e5affac34494294f1ccb862b865b4ede59)
[2021-11-08T21:30:25-0e39946/linux-s390x-ibm](https://build.golang.org/log/b6e9719d1c9b7864707799a72f9f70e5c77102fb)
[2021-11-07T04:57:22-9e6ad46/linux-ppc64le-buildlet](https://build.golang.org/log/2e9c5e39d7937a47e168971e07cfdfc8760a7401)
[2021-11-05T22:00:16-755ede0/linux-ppc64le-buildlet](https://build.golang.org/log/6ede0797657e77b242f91c542b9f11d5adb863de)
[2021-08-23T17:51:41-8486ced/linux-arm64-packet](https://build.golang.org/log/5fd1b8bfbecc88ea23f9c92eef67629a8a15babb)
[2020-12-03T16:05:09-5246fa5/linux-arm64-packet](https://build.golang.org/log/35c1531a73d5bae451a3b81c850f227f1b31c227)

(@mknyszek: I'm guessing this is more fallout from enabling the new GC pacer?)

**Comment by mknyszek** [comment]
I'm somewhat worried about this. If `debug.FreeOSMemory` isn't working as expected, that can be a significant regression.

**Comment by mknyszek** [comment]
OK, I think I know the problem. It's fairly benign. Previously `debug.FreeOSMemory` would block the whole runtime from doing anything with allocation, but now it doesn't. So, the background scavenger is just getting to the memory before `debug.FreeOSMemory` is, because a GC is forced and it gets woken up. I think the fix here might be to just set `GOMAXPROCS=1`, so it doesn't really get a chance.

This test is more of a problem on `mips64` and `ppc64` because the page sizes are much bigger, so the scavenger can do a whole lot more bytes of work before going to sleep. Not really any issue on usually small page size architectures like `amd64` and `arm64`.

As for a fix... I'm not sure. The goal here is to test `debug.FreeOSMemory`. Ideally, we could just turn off the background scavenger for this, but that's difficult to do from the `runtime/debug` tests. `GOMAXPROCS=1` might be good enough? `debug.FreeOSMemory` is not preemptible. Raising the amount that's available to be scavenged would also help, because the test just checks if it gets *something*, not necessarily *everything*. It probably should check that, but I don't think it'll be able to do that from the `runtime/debug` package.

**Comment by mknyszek** [comment]
Unfortunately `GOMAXPROCS=1` didn't work. Moving the test into runtime isn't great, though, and I'd rather not add hooks to disable the background scavenger. Though, maybe a `GODEBUG` mode that disables the background scavenger would be reasonable?

**Comment by mknyszek** [comment]
I got inspiration from my fix to #49411: we can make a test that's robust to the background scavenger if we recognize that we don't care if the test occasionally passes because the background scavenger stepped up. Currently this test is fragile because it can be perturbed by the background scavenger -- it does work the test expects that `debug.FreeOSMemory` does. We just care that we have a test that mostly fails if the tested mechanism *isn't* there.

So, my fix is to read `HeapReleased` *before* the allocation is freed. Then, check to make sure at least that much has been returned to the OS. Nothing else is going on in the test, so all the background mechanisms should only ever make `HeapReleased` go up. If it goes up more, who cares! It just needs to go up at least by that much.

CL incoming.
