### ISSUE TITLE
cmd/go: embed directory fails when at /

### ISSUE THREAD

**Issue by thomaspeugeot** [golang/go#49570]
### What version of Go are you using (`go version`)?

<pre>
/ # go version
go version go1.16.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I do not know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 # go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.10"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2312574173=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Training for docker with go, I forked `github.com/olliefr/docker-gs-ping` and added `embed` directive

```go
//go:embed foo
var foo embed.FS
``` 
it worked fined in my working directory.
But when I configured Dockerfile for having everything at root, it did not work.

```docker
# Set destination for COPY
WORKDIR /
```

To reproduce the bug

```
git clone https://github.com/fullstack-lang/docker-gs-ping.git
cd docker-gs-ping
docker build --tag docker-gs-ping .
```

### What did you expect to see?

a successfull go build

### What did you see instead?

```
 > [7/8] RUN go build -o /docker-gs-ping:
#11 2.002 # github.com/olliefr/docker-gs-ping
#11 2.002 /main.go:14:5: embed oo/foo.txt: open /oo/foo.txt: no such file or directory
```

A workaround is to have the WORKDIR different from "/"

**Comment by seankhliao** [comment]
cc @bcmills  @matloob

**Comment by ronaldpetty** [comment]
This fails for 1.18rc1 as well.

**Comment by tenkoh** [comment]
Hi, I have investigated about this issue.

### My guess:

This issue would be caused by  `resolveEmbed` function in  `src/cmd/go/internal/load/pkg.go`.



### Detail:

#### Reproduce and check the problem:

First of all, I had confirmed `go list` output changing working directory. I focused on `EmbedPattern` and `EmbedFiles` fields.

```shell
./
 |- Dockerfile
 |- main.go
 |- go.mod
 |- foo/
     |- foo.txt
```

main.go
```go:main.go
package main

import (
	"embed"
	"fmt"
)

//go:embed foo
var foo embed.FS

func main() {
    // do something
}
```

Dockerfile
```Dockerfile
FROM golang:1.18-alpine
# git is required to run `go list`
RUN apk add git --no-cache

WORKDIR /
COPY ./ ./

CMD ["go", "list", "-f", "'pattern: {{.EmbedPatterns}}, files: {{.EmbedFiles}}'"]
```

Result: 

EmbedPatterns are same in both cases. But EmbedFiles is different. So, some codes generating EmbedFiles would have a problem.

| working directory | EmbedPattern | EmbedFiles  |
| ----------------- | ------------ | ----------- |
| /                 | foo          | oo/foo.txt  |
| /app              | foo          | foo/foo.txt |



#### Read codes:

I found a suspicious part in `resolveEmbed` function in  `src/cmd/go/internal/load/pkg.go`.

https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/cmd/go/internal/load/pkg.go;l=2089;drc=c016133c50512e9a83e7442bd7ac614fe7ca62de

```go:pkg.go
err := fsys.Walk(file, func(path string, info os.FileInfo, err error) error {
    if err != nil {
      return err
    }
    rel := filepath.ToSlash(path[len(pkgdir)+1:])
```

This function recursively walks around in the working directory, then picks up files. The files' paths are stored as `rel` shown in the code above.

Here, `pkgdir` varies by working directory. It is set in `GoFilesPackage` in `src/cmd/go/internal/load/pkg.go`

https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/cmd/go/internal/load/pkg.go;l=2929;drc=c016133c50512e9a83e7442bd7ac614fe7ca62de

```go
if dir == "" {
    dir = base.Cwd()
}
dir, err = filepath.Abs(dir)
if err != nil {
    base.Fatalf("%s", err)
}
bp, err := ctxt.ImportDir(dir, 0)
```

The `dir` is equal to `pkgdir` and it differs from the working directory. It is trivial.

| working directory | dir  |
| ----------------- | ---- |
| /                 | /    |
| /app              | /app |

Considering all above, the `rel` (i.e. `EmbedFile`) becomes as below. Wow, we got `oo/foo.txt` !

| pkgdir | path (just an example) | rel = filepath.ToSlash(path[len(pkgdir)+1:]) |
| ------ | ---------------------- | -------------------------------------------- |
| /      | /foo/foo.txt           | oo/foo.txt                                   |
| /app   | /app/foo/foo.txt       | foo/foo.txt                                  |



#### Solution (guess):

So, solution could be adding an exception when `pkgdir`='/'. 

If I have a time, I will challenge a bugfix. But it's the first time to try, so it will take a little long...

**Comment by tenkoh** [comment]
I have fixed `resolveEmbed` and confirm the result.

https://github.com/tenkoh/fix-resolveEmbed-on-root
