### ISSUE TITLE
internal/fuzz: limit the number of consecutive mutations applied to an input

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#49601]
Currently, each time an input is sent to the worker a very large number of mutations can be consecutively applied. Resulting in a significantly different input at the end of the fuzzing than at the start. This significantly reduces the diversity of inputs, since a new "interesting" input is likely to be very different from the original input.

Instead we should limit the number of mutations to some small number, resetting the input back to its initial state if nothing new if found after that number of mutations (this matches the behavior of libFuzzer.) This is related to #47090.

Requesting a freeze exception, since this isn't a bug but has a significant impact on the efficiency/performance of the fuzzing engine, and has little risk.

cc @golang/release

**Comment by dr2chase** [comment]
@dmitshur @toothrot @cagedmantis  are y'all the keeper(s) of freeze exceptions?
(It looks reasonable to me, it's a serious performance/usability problem)

**Comment by dmitshur** [comment]
Yes, we've discussed this on the release team. Thanks for letting us know. We don't have objections to this since it's a part of a feature that's already in scope for 1.18, and this change is based on new data from testing/experience.

If the fuzzing team would like to proceed with this change, please do proceed.
