### ISSUE TITLE
x/tools/gopls: better handling of “scripts” with //go:build ignore?

### ISSUE THREAD

**Issue by ainar-g** [golang/go#49657]
I have a directory with several Go “scripts”.  That is, files each of which has a `//go:build ingore` directive and its own `main`.  Currently, `gopls` doesn't seem to handle this pattern very well, as when I add `ignore` to the list of tags, `gopls` is confused by several `main`s in what it sees as a single package.

Is there a way to make `gopls` treat such files as separate binaries?

Or, perhaps, there should be a separate marker build tag for these things, like `//go:build run`?

**Comment by findleyr** [comment]
I think we've talked about this in the past; it would require making 'ignore' special, but that seems fine to me.  We have a long-standing issue to improve handling of build tags (#29202), that this will probably be prioritized behind.

> Or, perhaps, there should be a separate marker build tag for these things, like //go:build run?

I'd rather just have gopls understand `ignore`. There's plenty of code in the wild that uses this already. If this causes problems for anyone (because they use `ignore` to define multi-file packages), we can make it configurable. But I would be surprised if that happened.

**Comment by findleyr** [comment]
This is perhaps a medium-sized project, but would resolve some of the pain points around build tags. While it requires an understanding of the complicated way that gopls resolves packages, it does not require duplicating the package graph, or even signficant refactoring of how we track packages: we simply need to teach our package loader (`snapshot.Load`) how to build synthetic packages for a special tag or sets of tags.  In fact, supporting this for a single file only (i.e. not synthesizing multiple files into a package) is probably a *small* project.

I think it makes sense to try to land this for the next gopls release (v0.10.0).

**Comment by wonderfate** [comment]
> This is perhaps a medium-sized project, but would resolve some of the pain points around build tags. While it requires an understanding of the complicated way that gopls resolves packages, it does not require duplicating the package graph, or even signficant refactoring of how we track packages: we simply need to teach our package loader (`snapshot.Load`) how to build synthetic packages for a special tag or sets of tags. In fact, supporting this for a single file only (i.e. not synthesizing multiple files into a package) is probably a _small_ project.
> 
> I think it makes sense to try to land this for the next gopls release (v0.10.0).

Hi. [findleyr](https://github.com/findleyr)

How should I fix this quesion now?

https://github.com/golang/go/issues/54317

**Comment by findleyr** [comment]
@wonderfate I replied on that issue, which I had not seen. I don't see a bug there: it looks like it is working as intended.

Meanwhile, let's please keep discussion here about adding support for `//go:build ignore`.

**Comment by wonderfate** [comment]
@findleyr
  
PLS doesn't support `//go:build ignore` and it miserable me

![image](https://user-images.githubusercontent.com/43459833/184552316-5e27807e-e15f-4bd1-a912-f1d5ea658fdb.png)

**Comment by findleyr** [comment]
@wonderfate this issue is currently scheduled for the next gopls release, in September. There's always a chance it may miss that milestone, but barring some unforeseen technical obstacle it should get done soon.

We understand that gopls doesn't work for ignored files, which is why this is prioritized.

**Comment by wonderfate** [comment]
Thank you for your answer. I look forward to it.

**Comment by wonderfate** [comment]
@findleyr  Thank you for your answer. I look forward to it.

**Comment by mvdan** [comment]
Oh boy, I can't wait to test this out :) Do we need to do anything special with gopls master for it to work?

**Comment by findleyr** [comment]
@mvdan please hold off for a few minutes -- I'm about to cut v0.10.0-pre.1; I embarassingly left a print statement in that will be fixed by https://go.dev/cl/442782 (I was debugging why parser.PackageClauseOnly parsed some comments after the package clause...)

But to answer your question: there's a new configuration option "standaloneTags", which defaults to ["ignore"]. You can customize it if you use a a different set of tags to identify scripts. Otherwise it should just work.

**Comment by mvdan** [comment]
Gotcha. I can definitely wait a few minutes :) I will be trying it out tomorrow.

**Comment by findleyr** [comment]
Very interested to hear about anyone's experience with this feature, negative or positive:

```
go install golang.org/x/tools/gopls@v0.10.0-pre.1
```

**Comment by ainar-g** [comment]
@findleyr, just checked in a couple of projects.  If there are lots (tens to hundreds) of `go:build ignore` files in the same directory, gopls seems to struggle for some time, but after a while it does work as expected.  Custom standalone tags work well too.  Thanks!

**Comment by CHATALOT1** [comment]
Just tested in a small project of mine in vscode, works perfectly. Been watching this for a while, thanks for implementing it @findleyr!

**Comment by mvdan** [comment]
I too confirm that it appears to work perfectly, on neovim :)

**Comment by RafalSkolasinski** [comment]
@findleyr am I doing something wrong or my issue is something else?

**Comment by findleyr** [comment]
@RafalSkolasinski sorry we don't always catch comments on closed issues.

I can't reproduce based on your description. Can you please file a new issue, following the issue template? For example, I would be interested to see your full version information (gopls and go command), as well as your settings. A reproducer would be ideal.
