### ISSUE TITLE
misc/cgo/test: Test9400 in TestCrossPackageTests hangs on ppc64le

### ISSUE THREAD

**Issue by pmur** [golang/go#49695]
While trying to reproduce some sporadic failures on seen on the ppc64le CI machines, I came across a hang in Test9400 on a POWER10 machine with GOMAXPROCS=2.

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel go1.18-e8cda0a6c9 Fri Nov 19 00:05:59 2021 +0000 linux/ppc64le
</pre>

### What did you do?
`cd $GOPATH/misc/cgo/test`
`go test -buildmode=pie -ldflags=-linkmode=internal -tags=internal,internal_pie -c`
`export GOMAXPROCS=2`
`while [ 1 ]; do ./test.test -test.v -test.short ; done`

Eventually this hangs on TestCrossPackageTests running Test9400.

This kind of looks like it may be an untimely GC starting while `issue9400.RewindAndSetgid` is spinning on a condition.

I inserted a call to `runtime.GC` prior to the above call, and was unable to reproduce the hang.

**Comment by mknyszek** [comment]
Update on the root cause here: the fixes for #49680, #49695, and #45867 all assumed that `SetGCPercent(-1)` doesn't block until the GC's mark phase is done, but it actually does. The cause of those failures is that at the beginning of the sweep phase, the GC does try to preempt every P once, and this may run concurrently with test code that has non-preemptible goroutines that create the potential for a deadlock.
