### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by jordanlewis** [golang/go#49697]
Hi, I'd like to request access for the may-start-trybots privilege, so I can request trybots on the viewcore (x/debug) repo.

Thanks!

Here is the group URL: https://go-review.googlesource.com/#/admin/groups/1030,members

My Gerrit email address is jordanthelewis@gmail.com.

**Comment by mvdan** [comment]
cc @golang/release

**Comment by heschi** [comment]
@jordanlewis: since the trybots are relatively sensitive infrastructure, we try to keep the set of people who can trigger them low. We're happy to expand the set to include frequent contributors for whom it'll be a big time-saver, but so far it looks like you've only sent a CL or two. For a low volume of changes, we hope that relying on your reviewers to trigger trybots should be acceptable.

I'm going to close this issue. Feel free to reapply if you find that not being able to trigger trybots is a major impediment to your work.
