### ISSUE TITLE
x/website: 'Packages' link mistakenly points to search box instead of standard package docs

### ISSUE THREAD

**Issue by eikenb** [golang/go#49737]
New go.dev website's `Packages` link should go to the standard package docs (https://pkg.go.dev/std), not a search box. That is the new site has a regression in usability and should be reverted to the direct link.

**Comment by rsc** [comment]
golang.org and go.dev were inconsistent in what the top bar 'Packages' link pointed to.
On golang.org it pointed to the standard library (like https://go.dev/pkg/?m=old).
On go.dev it pointed to pkg.go.dev.

We have to pick just one, and it seems far more useful to me
to go to a page that lets you find _any_ package,
instead of a page that only shows some packages.

I believe the current behavior, of linking to pkg.go.dev, is working as intended.

**Comment by ALTree** [comment]
It makes sense for the `Packages` item on https://go.dev/ to go to the general pkgs search, but how do you discover https://pkg.go.dev/std now? Searching for "std" on https://pkg.go.dev/ doesn't work. 

There has to be a way to find out what packages Go actually ships with. The quickest way appears to click on Docs to reach https://go.dev/doc/, then scrolling down to


> [Package Documentation](https://pkg.go.dev/std)
>
> The documentation for the Go standard library. 

which then links to https://pkg.go.dev/std, under the cryptic "Package Documentation" title (what package?) But that's like two thirds down, in a page with other 25 links, all equally prominent.

IMO there should be a link to https://pkg.go.dev/std prominent on https://pkg.go.dev/. So I would see something like "Standard library documentation" that jumps to https://pkg.go.dev/std, or I'd use the search bar if instead I wanted to look for 3rd party packages.

**Comment by seankhliao** [comment]
I believe that part is #40785

**Comment by ALTree** [comment]
Ah, that's right. I forgot about that one. It certainly got more relevant now that the migration to go.dev is in progress.

**Comment by rsc** [comment]
I sent a CL to put "Standard Library" in the footer menu under "Packages".
