### ISSUE TITLE
runtime: support preemption on windows/arm and windows/arm64

### ISSUE THREAD

**Issue by zx2c4** [golang/go#49759]
There's this old CL that needs a rebase (CL 207961) and recently there was a discussion in https://github.com/golang/go/issues/49458 about a bug stemming from the lack of preemption on windows/arm64.

We should implement preemption on windows/arm and windows/arm64. This issue is to track that work.

CC @bufflig @aclements @cherrymui @mknyszek @bcmills @rsc

**Comment by zx2c4** [comment]
Turned out to be pretty quick to implement. Trybots passed for the arm64 commit.  We're now waiting for #47019 to land so that we can run the trybots on arm32 too. Then we'll have preemption on Windows on all platforms and can merge those two CLs.

CC @toothrot @dmitshur @heschi

**Comment by zx2c4** [comment]
@rsc - do you have opinions on this with regards to 1.18 vs 1.19?

**Comment by bcmills** [comment]
(Just FYI: I don't think Russ receives GitHub notifications; freeze exceptions are in general up to the release team to decide.)

**Comment by zx2c4** [comment]
Oh, okay, this is freeze thing, not general Go planning, makes sense.

@dmitshur - up to you then.

**Comment by dmitshur** [comment]
@zx2c4 We've discussed this on the release team, and in general we are okay with this happening for Go 1.18, especially if it can help fix other bugs. It seems the CLs are reviewed and ready to go, so if submitted before Beta 1 they'll undergo all the testing it receives. If it causes new problems, I hope it'll be possible to attribute it back to this change and revert it (the change is very small and so doesn't pose a significant risk of conflicts).

Please note that #47019 is not resolved yet, and though we're hoping to make progress on it (latest update on it is from yesterday), it's hard to say exactly how soon it will be resolved. Perhaps you'd prefer to land this change for the windows/arm64 port independently of the windows/arm one, unless you think it is better to bundle them and land at the same time.

We are in the part of the release process where the goal is to fix bugs and increase stability/reliability of the upcoming release, so if you think this can be integrated safely for 1.18, please proceed. Otherwise it will be safe to target this for 1.19 during its development cycle. Thank you Jason.

**Comment by zx2c4** [comment]
@dmitshur Rather than waiting for #47019, for this particular CL, I'll just run all.bat on my own ARM machine at home and report the result back to the CL.

**Comment by zx2c4** [comment]
![Screenshot_20211125-005204](https://user-images.githubusercontent.com/10643/143326727-aa4e85af-a74c-4fda-bed3-84adea715a93.png)

So far so good...
