### ISSUE TITLE
x/website: some important pages seem to not be linked to

### ISSUE THREAD

**Issue by mvdan** [golang/go#49768]
For example, https://go.dev/doc/contribute is an invaluable resource for contributing to Go, but I can't find it under https://go.dev/doc/.

I imagine other pages also fell off the radar given the website redesign, but I'm not sure how to check.

**Comment by rsc** [comment]
There shouldn't be very many unlinked pages, since all the content on golang.org moved over verbatim except for the front page. Looking at the [old front page](https://web.archive.org/web/20211121044728/https://golang.org/), the old header linked to /project and /help/, which may not have links anymore. I've put both of them into the footer in [CL 366577](https://go.dev/cl/366577). Thanks!

**Comment by fzipp** [comment]
The "Contribution Guide" is reachable via the website, but it's deeply buried:

"Docs" -> "Installing Go" -> "Installing Go from source" -> "(Optional) Switch to the master branch" -> "contribute your changes"

I think it was the same on the old website, so it's not a regression.

**Comment by mvdan** [comment]
Ah, so now "About" will point to https://go.dev/project, which does have a direct link to the contribution guide. That seems like a big improvement, thanks!

> I think it was the same on the old website, so it's not a regression.

That's entirely fair - I don't recall exactly the layout of the old site, and I don't have a way to check easily now that the site redirects.

**Comment by JeremyLoy** [comment]
There also doesn’t seem to be links to the standard library collection of packages either
