### ISSUE TITLE
cmd/compile: Go 1.18 (types2 typechecker) doesn't report "channel element type too large"

### ISSUE THREAD

**Issue by danscales** [golang/go#49771]
One error message that we are not reporting in Go 1.18 is at least one kind of "channel too large" error.  In particular, see `test/fixedbugs/issue42058a.go` and `test/fixedbugs/issue42058b.go`.  In Go 1.17 or `-G=0` mode, we give errors like:

```
fixedbugs/issue42058a.go:9:7: channel element type too large (>64kB)
fixedbugs/issue42058a.go:13:7: channel element type too large (>64kB)
```

but no errors in Go1.18 default mode (which is why those tests are currently disabled in run.go).  This is for statically declared channels whose element are too large.

Looks like there is a separate just-reported issue [#49767](https://github.com/golang/go/issues/49767) for Go 1.17.2 and Go 1.18 that causes a compiler crash when a channel with a too-large element size is created via `make` and a channel type literal.

@griesemer @findleyr 

Definitely fine for after beta1.

**Comment by mengzhuo** [comment]
@griesemer this may help you debug this issue
on the tips

The nod of CHANARGS is nil which causing an internal error "bad type [65536]byte".

**Comment by griesemer** [comment]
@danscales This is really a compiler/runtime specific error. There's several ways how this could be fixed:

1. The type checker (types2) could have additional configuration information such as max. channel size and use it to report an error if necessary.
2. The type checker is provided a size computation function by the compiler that may return an error as needed. This would be a variant of option 1.
2. The compiler (noder) could do the type specific check instead.

At the moment I lean towards option 3 because the type-checker doesn't really care for type-checking and certainly couldn't hardwire the limit.
