### ISSUE TITLE
github: Go Organization website points to golang.org

### ISSUE THREAD

**Issue by ALTree** [golang/go#49784]
At https://github.com/golang:

![image](https://user-images.githubusercontent.com/3586803/143282516-1fc6e116-349c-4185-a09f-c6fef9bc2b22.png)

Since apparently golang.org has been dismissed and now it only redirects, the link should probably be changed to go.dev, if that is the new website of the Go Project. 

cc @golang/release @toothrot

**Comment by dmitshur** [comment]
Thanks for reporting. Updated. Unfortunately that means no more "Verified" badge for now, but we'll get that back after some time.

Though go.dev is the new shorter URL where the Go websites have been consolidated as described in https://go.dev/blog/tidy-web, golang.org will exist and continue to redirect so that existing links don't break.
