### ISSUE TITLE
compress/zlib: NewWriterLevel(&in, zlib.BestCompression) is not good as other lauguages at the same level

### ISSUE THREAD

**Issue by walter1045** [golang/go#49780]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17.3 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\my\AppData\Local\go-build
set GOENV=C:\Users\my\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\my\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\my\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\gopro\mygo\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=D:\cache\Temp\go-build312801471=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1: I have origin data which is compressed by zlib of C/C++;
2: And I use golang zlib uncompress it , then re-compress it back;

### What did you expect to see?

3: Then I found that cannot get the same data with origin data:
4: I change language to Python3, then I get the correct data.

### What did you see instead?

5: So, I think the function "zlib.NewWriterLevel(&in, 9)" is not good as other language at the same compress level.

Attach:

origin data size : 125154

Golang result:
0 1801955
1 138636
2 139037
3 136736
4 123597
5 120754
6 121741
7 121694
8 125187
9 125185

Python3 result: level, compress size whith same origin data
0 1801950
1  133128
2  140130
3  137284
4  124565
5  121315
6  122151
7  122118
8  125165
9  125154

**Comment by seankhliao** [comment]
cc @dsnet

**Comment by dsnet** [comment]
Compression ratios are heavily dependent on the input data set. Without a reproducer, there isn't much that can be done here.

A few years ago, @klauspost optimized the encoder. As part of the optimization, it made the assumption that matches were always at least 4 bytes long. This means that we don't perform 3-byte matches, which may be the cause of lower compression ratio. See #15622. However, we cannot verify this without a reproduction.

**Comment by ulikunitz** [comment]
If you want the same compression rate as another compression tool, you need to replicate the Lempel-Ziv-Encoder exactly and use the same parameters. So this is actually a request to implement the zlib Lempel-Ziv-Encoder exactly as in zlib.

**Comment by klauspost** [comment]
1) A sample size of one says nothing about a compression scheme. 

Test on a large set of inputs. Your input clearly has some special properties since it is uncommon for higher levels to have worse compression than medium. This is not 

2) Size cannot be compared without considering speed.

For example, this is [4 GB web content](https://files.klauspost.com/compress/webdevdata.org-2015-01-07-4GB-subset.7z) speed vs compression with Go stdlib:

![image](https://user-images.githubusercontent.com/5663952/143412260-0793bea6-eeeb-4a72-b474-3bc68430d44d.png)

3) Compression levels should not be compared across implementations. They should reflect the tradeoff between speed an compression as an average in a given implementation. Looking at the graph above anything above level 6 looks like a waste of CPU cycles, and level 4 would be the reasonable "default", and not level 6.

For my own [deflate](https://github.com/klauspost/compress) I have tried to make the tradeoff more "linear", with a reasonable default level 5.

![image](https://user-images.githubusercontent.com/5663952/143415489-4f29cf29-f91a-42e3-8da5-ff7f06dbf79f.png)

It is not perfect, and some inputs will skew it, but that is the measure I use for balancing the compression levels.

Typically I only really find the "fastest", "default" (the reasonable tradeoff) and "best" (smallest) levels to be useful anyway, so for most implementations that are the only ones I focus on.

Short story: Choose the compression level that makes sense for your use case. Don't copy+paste from other languages.

@dsnet 3 vs 4 byte is rarely a gain since encoding 3 byte matches in most cases yield the same or larger output than the entropy encoding of the immediate values. You can estimate both, but it is rather expensive and relies on incomplete information.

FWIW, I tried adding 3 byte matches to deflate level 9, without comparing entropy coded sizes similar to old implementation. Total output size went from 730389060 -> 738349365 bytes on `webdevdata.org-2015-01-07-subset`.
