### ISSUE TITLE
hash/adler32: TestGolden failures on freebsd starting 2021-11-26

### ISSUE THREAD

**Issue by bcmills** [golang/go#49862]
`greplogs --dashboard -md -l -e FAIL\\s+hash/adler32\\s+ --since=2020-01-01`

[2021-11-29T19:45:58-f598e29/freebsd-amd64-12_2](https://build.golang.org/log/0de256f8904dabfacf48f1e2f4f517b87d00ca8d)
[2021-11-26T13:18:11-7703804/freebsd-amd64-12_2](https://build.golang.org/log/46d12b0622c0a0cc8f7ede6959235b1b06f6ecef)

This may be another symptom of #46272 (CC @mknyszek @jeremyfaller), but it seems suspicious to see two such failures within a week and none at all for a year preceding.

**Comment by bcmills** [comment]
Marking as release-blocker at least until we understand whether this is a recent regression.

**Comment by toothrot** [comment]
Checking on this as a release blocker. Are there any updates? @mknyszek

**Comment by aclements** [comment]
This *has* to be memory corruption. The test is passing 1e5 0s to

```go
func checksum(p []byte) uint32 {
	s1, s2 := uint32(1), uint32(0)
	for _, x := range p {
		s1 = (s1 + uint32(x)) % mod
		s2 = (s2 + s1) % mod
	}
	return s2<<16 | s1
}
```

and getting the wrong answer sometimes.

I find it very interesting that [2021-11-29T19:45:58-f598e29/freebsd-amd64-12_2](https://build.golang.org/log/0de256f8904dabfacf48f1e2f4f517b87d00ca8d) and [2021-11-29T22:02:45-1970e3e/freebsd-amd64-13_0](https://build.golang.org/log/4ffe656fea8ed1bef9533abf39e0f72ffc4941ec) got the *same* wrong answer.

Since this can only be memory corruption, closing as a dup of #46272. I'll leave a comment on that bug because this is a potentially interesting test case.
