### ISSUE TITLE
runtime/metrics: add contention metrics

### ISSUE THREAD

**Issue by znkr** [golang/go#49881]
Right now lock contention is only possible to debug with pprof using the block profile. This is very useful once contention has been identified as the issue, but since it has to be turned on manullay it doesn't help in identifying that contention is an issue. Exporting the cumulative wait time via runtime/metrics would allow continouous monitoring of contention and help in debugging Go programs.

**Comment by prattmic** [comment]
cc @mknyszek @aclements

**Comment by mknyszek** [comment]
Interesting... Looks like we already measure time spent blocked for starvation purposes anyway. I suppose this wouldn't be too hard to expose. Is cumulative wait time the right metric? It's useful for comparison, but it doesn't really tell you much on its own.

An approximate distribution of latencies might be more useful for this, because you can correlate that with e.g. request latency, but it's slightly more expensive and it requires a bit more post-processing. Its other downside is that it's approximate -- I'm not sure if there's some special use case enabled by having a precise cumulative wait time.

**Comment by mknyszek** [comment]
To be clear I'm not opposed to cumulative wait time. If that's the convention we can move forward with that. Just want to make sure we considered our options.

**Comment by znkr** [comment]
Latency distribution would be even better. Approximate time would be good enough for all use cases I can think of.

**Comment by znkr** [comment]
cc @jeremyfaller

**Comment by ianlancetaylor** [comment]
Moving to Backlog.  Please recategorize as appropriate.  Thanks.

**Comment by znkr** [comment]
Would it be a lot of work to get this into 1.20? It would help a lot in understanding performance issues in production jobs and a lot of Google internal users have expressed interest in this.

**Comment by aclements** [comment]
Given that there's known demand for this and that I think it wouldn't be hard to add (though I might be wrong), I'll move this to 1.20, but given our focus on core project health and PGO for 1.20, I'm not sure we'll get to this.

**Comment by mknyszek** [comment]
I'll probably do some other `runtime/metrics` stuff this release, so I'll put it on my plate.
