### ISSUE TITLE
cmd/compile: cannot import "package" (type parameter bound more than once)

### ISSUE THREAD

**Issue by csgura** [golang/go#49893]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-a412b5f Wed Dec 1 06:03:27 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
The Gotip Playground 

### What did you do?

https://gotipplay.golang.org/p/MFUJGGC_uWf

### What did you expect to see?
Compiled without error

### What did you see instead?
`./prog.go:5:2: could not import tptest/option (cannot import "tptest/option" (type parameter bound more than once), possibly version skew - reinstall package)`

**Comment by danscales** [comment]
I'm looking at this, since it may relate to confusion with import/export, but @findleyr , you may also want to take a look when you get a chance, since the error happens in types2.  Seems like we may somehow confused distinct type parameters during export/import across multiple packages.

@griesemer

**Comment by findleyr** [comment]
Thanks for the repro. This should be a release blocker: there is something wrong with our type-parameter scoping.

**Comment by findleyr** [comment]
> the error happens in types2

@danscales the error is coming from types2, but the bug must be in the importer. Type parameters are local to their function/type, and so must be bound only once.

**Comment by danscales** [comment]
The bug relates to the type parameter B being specified in Ap1, but not actually being used in Ap1 (applies to Ap2 as well).  Because B is not used, we are somehow referencing the wrong B during definition and then export.  Doesn't always cause a visible problem, but sometimes does (as in this issue).
