### ISSUE TITLE
go/types, types2: always set the receiver type of interface methods to the defining interface type

### ISSUE THREAD

**Issue by griesemer** [golang/go#49906]
When setting up methods for interfaces, we set the recv to the interface type (its definition if we have one). We are (probably - I don't remember for sure) doing this so we can tell that those `Func` objects are methods; there may be other reasons. Investigate if this is something we can or might want to change.

See also #49888 and the respective CL which would be affected.

cc: rfindley

**Comment by mdempsky** [comment]
I'd like to suggest that the Func's receiver parameter always points to the `types.Interface` that represents the underlying interface type literal that declared the method, and never to the `types.Named` for defined interface types.

For example, I suggest https://go.dev/play/p/weOZB-AO-w2 should print:

```
func (interface).M()
func (interface).M()
func (interface).M()
```

rather than

```
func (p.A).M()
func (p.A).M()
func (interface).M()
```

like it does currently. I think this would be more consistent and also simplify importers.

**Comment by griesemer** [comment]
Marking for Go 1.19 so this stays on the radar.

**Comment by griesemer** [comment]
I am ok with this change. As far as I can tell, it's important to have a non-nil receiver (so we know that we have a method), but for interface methods it doesn't matter whether the receiver is the declaring interface proper or the named type if one was given to the interface. [CL 396516](https://go.dev/cl/396516) makes the relevant changes in `types2`.

@findleyr Do you see any problems with tools (backward-compatibility)?

**Comment by griesemer** [comment]
We have now pending [CL 396516](https://go-review.googlesource.com/c/go/+/396516/) that implements [the suggestion](https://github.com/golang/go/issues/49906#issuecomment-1027364136) by @mdempsky , but for the [failures in the `x/tools` repo](https://storage.googleapis.com/go-build-log/aba5a74c/linux-amd64_2da89cbd.log). However, these failures give me pause: it does seem that we are going to lose quite a bit of information that's useful by tools when reporting errors. It's not clear to me that this is a change/simplification worth doing.

@mdempsky mentions that the chance would simplify importers. That's true, and it also simplifies the type checker slightly. But leaving the requirements as is doesn't seem particularly difficult either.

@mdempsky @findleyr for comments.

**Comment by mdempsky** [comment]
Agreed we shouldn't make this change if it negatively impacts end-user experience. I'd like to take a deeper look at the x/tools failures though, before ruling out this change.

My intuition is the defined receiver type information should still be available via the go/types API, just the consumer code isn't worrying about getting it, because in the common case (e.g., `type A interface { M() }` from the https://go.dev/play/p/weOZB-AO-w2) it just works already. But for the same reason that the tests are failing for CL 396516, I suspect they'd similarly provide non-ideal end-user results for types `B` and `C`.

**Comment by griesemer** [comment]
Agreed that there are scenarios (https://go.dev/play/p/weOZB-AO-w2) where the reported receiver type is not ideal. The "correct" solution might be to adjust the various tests that are failing.

Postponing for now as this is neither urgent nor a major issue at the moment.

**Comment by dr2chase** [comment]
Did the updating CL perhaps fix this?

**Comment by mdempsky** [comment]
@dr2chase Not entirely. It brought the unified IR importer's behavior closer to what go/types currently implements itself, but there are still some minor inconsistencies.

For example, in https://go.dev/play/p/weOZB-AO-w2 (the test case from above), importing the package from unified IR will now report `func (p.C).M()` for the last line, rather than `func (interface).M()` like go/types still does.

I doubt the discrepancy affects users in practice, and it would be awkward to exactly emulate go/types's current behavior without bumping the unified IR export format. If necessary, we can certainly do that though.

**Comment by griesemer** [comment]
@mdempsky Is there anything left to do here? I think we want to keep pointing to the defined type for better error messages.

**Comment by mdempsky** [comment]
No, I think we can close this.
