### ISSUE TITLE
cmd/link: misc/cgo/testshared failure on boringcrypto branches 

### ISSUE THREAD

**Issue by mknyszek** [golang/go#49965]
I released the 1.17.4 and 1.16.11 to the boring crypto versions of Go, and I noticed a link failure in the trybots:

https://storage.googleapis.com/go-build-log/f967062a/linux-amd64_0dc21008.log

@heschi noticed that it appeared first in https://go.dev/cl/362654 but it looked unrelated so it was ignored. We suspect this is a real failure of a ~flaky~ (EDIT: I was wrong, it's deterministic) test that was recently exposed. Low priority because it doesn't actually block boring crypto releases, but it does add noise to the process.

CC @cherrymui @randall77

**Comment by cherrymui** [comment]
Do you mean that failure is nondeterministic? That would be weird as it seems from the C linker.

**Comment by heschi** [comment]
Yeah, I don't think it's flaky, just that it was hidden by the clobber test before.

**Comment by cherrymui** [comment]
Is it failing now? I don't see a failure in the dashboard or @mknyszek 's recent CLs.

**Comment by heschi** [comment]
See https://build.golang.org/?repo=&branch=dev.boringcrypto (the dev.boringcrypto branch). The [most recent row](https://build.golang.org/log/6e22cabc46797147ae3e7d6f96092bf88764a271) has the failure for me.

**Comment by cherrymui** [comment]
Thanks. I was looking at boringcrypto.go.1.17 branch...

**Comment by cherrymui** [comment]
The boringcrypto syso references pthread functions, so we need to pass -pthread to the C linker.

I spent a while looking into why this is not failing before. It turns out that on 1.17 the tests there simply don't depend on any crypto packages, so the syso is not linked in. On tip, it does depend on crypto, possibly though fuzzing as a test dependent. I can reproduce the error with 1.17 branch with a test explicitly using crypto, e.g. `go test -linkshared crypto/sha1`. Will send a CL soon.

**Comment by dmitshur** [comment]
I understand this is resolved via https://go.dev/cl/369161, it just didn't get closed because the "Fixes" syntax doesn't close issues on dev.* branches. Notably, https://build.golang.org/?branch=dev.boringcrypto (as well as 1.17 and 1.16 ones) is green.
