### ISSUE TITLE
x/website: /blog/ should show more entries

### ISSUE THREAD

**Issue by seankhliao** [golang/go#49969]
https://go.dev/blog/

The old blog index page used to inline the blog entries, so it made sense to limit the number of posts there.
Now it just shows the short description so it should make sense to display more (all?) of them.

cc @dmitshur @rsc

**Comment by dmitshur** [comment]
If the blog entries won't be inlined, it seems reasonable to display more entries. It doesn't need to show all, since that's what https://go.dev/blog/all is for. Unless /blog simply replaces the need for /blog/all.

If they'll be inlined, then the current amount is probably okay.

I don't know the future plans for the blog page, but maybe Russ or @jamalc would have a better idea.

**Comment by seankhliao** [comment]
[CL 371894](https://go.dev/cl/371894) changed it to 10
