### ISSUE TITLE
github: two items in the issue templates list say "to report a vulnerability" 

### ISSUE THREAD

**Issue by ALTree** [golang/go#49962]
https://github.com/golang/go/issues/new/choose has two different options to report security vulnerabilities:

---

**Report a security vulnerability**
Please review our security policy for more details

---

**Security Vulnerabilities**
See here for our security policy 

---

this seems confusing. 

cc @seankhliao @dmitshur

**Comment by dmitshur** [comment]
Thanks for reporting. Indeed.

We can either:

1. Remove the custom "Security Vulnerabilities" contact link from `.github/config.yml`:

https://github.com/golang/go/blob/c4a8550421ce16f233b48a85dc5dd04b16469b7f/.github/ISSUE_TEMPLATE/config.yml#L6-L8

2. Or somehow get the GitHub-generated "Report a security vulnerability" button not to show up, if that's possible. @seankhliao Any thoughts on this? Do you know what happens if SECURITY.md file isn't present? I think @FiloSottile may have expressed not wanting that file in the past, so this might be a good time to revisit.

@golang/security Any preferences on this? If it's hard to find the optimal choice, we can default to the simpler option of removing the custom contact link.

**Comment by dmitshur** [comment]
> Do you know what happens if SECURITY.md file isn't present?

I checked: https://github.com/seankhliao/testrepo-666 does not have a SECURITY.md, and https://github.com/seankhliao/testrepo-666/issues/new/choose doesn't lead to that extra button appearing. So this should a viable path to resolve this issue.

**Comment by seankhliao** [comment]
I don't think it's possible to only disable the github-generated button. 

The SECURITY.md can be moved into the .github directory if it's only for GitHub to show something in the policy tab. There's also a SUPPORT.md file in there (though it may be out of date?). Both show up as additional links under "Helpful Resources" on the right once you've selected an issue template, though I don't think many people notice it.

**Comment by dmitshur** [comment]
> If it's hard to find the optimal choice, we can default to the simpler option of removing the custom contact link.

Okay, let's do this for now to resolve this issue.
