### ISSUE TITLE
spec: the word terms not used properly in EBNF description

### ISSUE THREAD

**Issue by Cages-hub** [golang/go#50074]
https://github.com/golang/go/blob/61ba0bcf8eebd1515d1af7a0e918bf912db6eb46/doc/go_spec.html#L50

This line seems to ignore Alternative in the EBNF specification above it:
```
Expression  = Alternative { "|" Alternative } .
Alternative = Term { Term } .
```
The line would make more sense if it was using identifiers used in Wirth's EBNF specification:

```
expression = term {"|" term}.
term = factor {factor}.
```

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
Fair point. The notion of a `term` would also be closer to the usual mathematical use as an operand in a sum (or a list of alternatives as the case is here). That said, `factor` - while again the usual mathematical nomenclature - does not seem very evocative in this context. Perhaps we should say

> Productions are expressions constructed from Alternatives and the following operators, in increasing precedence:

and look for a better name than `term`.

The current writing deliberately skips `Alternatives` because at the end all we have is `Terms`.

**Comment by Cages-hub** [comment]
Skipping `Alternative` implies the description does not apply to  `binary_digit  = "0" | "1" .`

Using the specs current nomenclature I would suggest:
```
Expression = Sequence { "|" Sequence } .
Sequence = Alternative { Alternative } .
Alternative = production_name | token [ "…" token ] | Group | Option | Repetition .
```
