### ISSUE TITLE
x/tools/gopls: 0.7.4 fails to handle vendor dir when experimentalWorkspaceModule is enabled

### ISSUE THREAD

**Issue by islishude** [golang/go#50214]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, I use gopls 0.7.4, and 0.7.3 works fine

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lishude/Library/Caches/go-build"
GOENV="/Users/lishude/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lishude/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lishude/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lishude/project/coding/gopls-vendor-bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6g/lnymwz651hg5mmplm29_4scm0000gn/T/go-build2470115460=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```sh
mkdir app
cd $_
go mod init
```

create main.go

```go
package main

import "golang.org/x/crypto/blake2b"

func main() {
	blake2b.New()
}
```

```sh
go mod tidy && go mod vendor
```

### What did you expect to see?

no errors

### What did you see instead?

vscode reports this error

```
Inconsistent vendoring detected. Please re-run "go mod vendor".
See https://github.com/golang/go/issues/39164 for more detail on this issue.
```

**Comment by hyangah** [comment]
Thanks for the report. @islishude 
Can you please share your editor settings (i.e. `gopls` settings) or `gopls` trace?
I could reproduce this issue with `"build.experimentalWorkspaceModule": true` and want to double check if it's the same reproducer.

cc @findleyr

**Comment by islishude** [comment]
```json
  "gopls": {
    "usePlaceholders": true,
    "completeUnimported": true,
    "deepCompletion": true,
    "hoverKind": "FullDocumentation",
    "staticcheck": false,
    "experimentalWorkspaceModule": true
  },
```

**Comment by islishude** [comment]
set experimentalWorkspaceModule to false, it works!

**Comment by findleyr** [comment]
It sounds like this bug might be biting several issues: the likely scenario is that a fix for `go` directive resolution in the multi-module `go.mod` file (https://golang.org/cl/365737) actually broke this workflow (because now we're subject to new vendoring semantics).

I'll see if it is easy to fix this for the next gopls release, though it may be a better use of time to focus on `go.work` support, which shouldn't have this problem.

**Comment by alexzielenski** [comment]
I'm also finding that in the kubernetes repository using workspace mode. Unless I run `go mod vendor`), gopls shows this error. I would like to avoid having to do that, since kubernetes symlinks source from `staging` into `vendor`, so running `go mod vendor` is unnecessary to build.

Upon reading this issue, I disabled `experimentalWorkspaceModule` and suddenly `gopls` now accepted kubernetes' quirk of symlinking `vendor` modules from a `staging` folder without me running `go mod vendor`. No more spurious error messages. I imagine this only works for me because I am using a vscode workspace which excludes nested modules.

**Comment by aronatkins** [comment]
I have seen the same problem when using emacs, lsp-mode, and gopls-0.7.4; I have continued using gopls-0.7.3 to avoid this issue.

```lisp
(use-package lsp-mode
  :ensure t
  :commands (lsp lsp-deferred)
  :hook (go-mode . lsp-deferred)
  :config
  (lsp-register-custom-settings
   `(
     ("gopls.experimentalWorkspaceModule" t t)
     ))
)
```

Using a two-module layout like:

```
repo/
    src/
        a/main.go
        b/main.go
```

The `a/main.go` and `b/main.go` are identical to the one included by @islishude.

```bash
mkdir repo
cd repo
git init
mkdir -p src/a src/b
# populate src/a/main.go and src/b/main.go
cd a
go mod init a && go mod tidy && go mod vendor
cd ../b
go mod init a && go mod tidy && go mod vendor
```

The following `.dir-locals.el` is in use because lsp-mode + gopls didn't understand multiple modules beneath the repo:

```lisp
; repo/.dir-locals.el
((nil . ((eval . (setq repo-root (expand-file-name (locate-dominating-file default-directory ".dir-locals.el"))))))
 (go-mode . (
             (eval . (lsp-workspace-folders-add (concat repo-root "src/a")))
             (eval . (lsp-workspace-folders-add (concat repo-root "src/b")))
             )
          ))
```

Upon opening `src/a/main.go` in emacs, the `*lsp-log` buffer becomes filled with:

```
2022/03/14 13:13:51 errors loading workspace: err: exit status 1: stderr: go: inconsistent vendoring in /var/folders/8j/pt4fjhkj11d3xd9344pdspmh0000gn/T/gopls-workspace-mod217891956:
	a@v1.9999999.0-goplsworkspace: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	a: is replaced in go.mod, but not marked as replaced in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
: packages.Load error
	snapshot=1
	directory=file:///Users/aron/repo/src/a

```

Our `src/a` and `src/b` directories define separate modules that do not depend upon each other.
