### ISSUE TITLE
net/http/pprof: TestDeltaProfile failures missing mutexHog2 on ARM architectures

### ISSUE THREAD

**Issue by bcmills** [golang/go#50218]
```
--- FAIL: TestDeltaProfile (53.30s)
    pprof_test.go:206: want mutexHog2 but no mutexHog1 in the profile, and non-zero p.DurationNanos, got PeriodType: contentions count
        Period: 1
        Time: 2021-12-16 19:51:59.42219359 +1100 AEDT
        Duration: 32.041535781s
        Samples:
        contentions/count delay/nanoseconds
        Locations
        Mappings
        1: 0x0/0x0/0x0   [FN]
    pprof_test.go:214: want both mutexHog1 and mutexHog2 in the profile, got PeriodType: contentions count
        Period: 1
        Time: 2021-12-16 19:51:59.43107526 +1100 AEDT
        Samples:
        contentions/count delay/nanoseconds
                  9   17621016: 1 2 3 
                  1     149081: 1 4 3 
        Locations
             1: 0x851d3 M=1 sync.(*Mutex).Unlock /home/gopher/build/go/src/sync/mutex.go:214 s=0
             2: 0x2d249f M=1 net/http/pprof.mutexHog1 /home/gopher/build/go/src/net/http/pprof/pprof_test.go:107 s=0
             3: 0x2d2937 M=1 net/http/pprof.mutexHog.func1 /home/gopher/build/go/src/net/http/pprof/pprof_test.go:148 s=0
             4: 0x2d24ab M=1 net/http/pprof.mutexHog1 /home/gopher/build/go/src/net/http/pprof/pprof_test.go:108 s=0
        Mappings
        1: 0x0/0x0/0x0   [FN]
FAIL
FAIL	net/http/pprof	57.491s
```

`greplogs --dashboard -md -l -e 'FAIL: TestDeltaProfile ' --since=2021-01-01`

[2021-12-16T00:34:10-7f23145/openbsd-arm-jsing](https://build.golang.org/log/3dc87c9fe6e5f594cf4ab68acd69394507c437e2)
[2021-11-25T00:02:52-b2a5a37/openbsd-arm-jsing](https://build.golang.org/log/b34de17d2240e537661f2e775934483480e6fdd4)
[2021-06-04T17:33:24-831f937/openbsd-arm-jsing](https://build.golang.org/log/9239fcacfff3a9b462fee2d7fefe2cfd190d1b97)

(Forked from #38544, which was mitigated in [CL 229498](https://golang.org/cl/229498).)

CC @4a6f656c @hyangah

**Comment by bcmills** [comment]
`greplogs --dashboard -md -l -e 'FAIL: TestDeltaProfile ' --since=2021-12-17`

[2022-02-04T22:34:05-f9763a6/android-arm64-corellium](https://build.golang.org/log/0a18347eaf4d649a9909d2b942122177cdf0a925)

**Comment by bcmills** [comment]
(CC @cherrymui)

**Comment by bcmills** [comment]
Another `android/arm64` today:

`greplogs --dashboard -md -l -e 'FAIL: TestDeltaProfile ' --since=2022-02-05`

[2022-02-07T21:00:02-7db75b3/android-arm64-corellium](https://build.golang.org/log/a4582cf69a4d7cb357e26af4e9c7c1ad7698f7f3)

**Comment by bcmills** [comment]
Marking as release-blocker for Go 1.19 due to the high failure rate on the builders (CC @golang/release).

If we don't care about this test, we can merge [CL 383997](https://go.dev/cl/383997) (mailed ~3 weeks ago) to encode that decision as a test-skip. Otherwise, this test failure needs to be addressed.

`greplogs --dashboard -md -l -e 'FAIL: TestDeltaProfile ' --since=2022-02-08`

[2022-03-01T20:52:30-f4722d8/android-arm-corellium](https://build.golang.org/log/2842df3640682d7a6931c07778d0033fe54d37fb)
[2022-02-28T21:56:43-f04d5c1/android-arm-corellium](https://build.golang.org/log/e97bf1d3f09b90380a970024af9d3d8114313e8a)

**Comment by aclements** [comment]
@golang/runtime needs to decide whether to fix and unskip this test, or to drop the test.

**Comment by mknyszek** [comment]
We should decide what to do here. I'll take a look at this.

**Comment by mknyszek** [comment]
So, this hasn't happened since March. I have a feeling this is related to a few things that were fixed with respect to profiles recently. Curiously, the failures stopped happening on March 7th, and on March 8th ttps://go-review.googlesource.com/c/go/+/384239 was landed to fix [#50996](https://golang.org/issue/50996). There aren't any other pprof or profile related CLs around this one. The previous one landed in February, and the following one in May. That CL, I think, only affected proto output, but then again that's exactly what the `net/http/pprof` test is checking, because it obtains the profile via query.

This test is checking a mutex profile, but I imagine it uses the same stack frame information that anything else does. I think it's possible that what's happening in this test is call frames are dropped because these NOPs are actually (created when inlining for a "fake" PC for the inlined function) weren't handled correctly.

However, I'm not totally clear on what the failure mode for #50996 is. Specifically, neither `mutexHop1` nor `mutexHog2` are inline-able, but they have a few calls that are (like the `Lock` calls). So is it the parent frame that could get lost? Just the inlined call? The entire stack? I suspect it's the entire stack because if we land on one of these NOPs and don't handle them correctly (but only sometimes?). It's also not clear whether these NOPs play a role here. They probably play *some* role, given that this is a mutex profile and the `Lock` and `Unlock` calls are inlined.

I'm inclined to call this fixed. I haven't fully figured out the details, but I think there is a plausible connection here.

**Comment by mknyszek** [comment]
CC @rhysh @prattmic @cherrymui who were involved to varying degrees in https://go.dev/cl/384239. It might be clearer to y'all what exactly *was* the problem here and whether that CL fixed this particular issue. What's also puzzling me is, if there was a problem handling these NOPs, the failure should intuitively be more deterministic for a mutex profile, but I'm also not terribly familiar with how the mutex profile works.

**Comment by bcmills** [comment]
> I'm inclined to call this fixed. I haven't fully figured out the details, but I think there is a plausible connection here.

In that case, shall we close the issue until / unless it recurs?

**Comment by mknyszek** [comment]
I'm not opposed, I wanted to give others a chance to chime in, but it's probably less work to just close it and move on. :) If it happens again we can take some of this information forward.

**Comment by mknyszek** [comment]
Ha, OK. I missed that when I was walking back over the commit log. Thanks @rhysh. I'm going to reopen this. Still not certain this should block the release at this point, but it looks like there's a real problem and it's currently being masked.
