### ISSUE TITLE
affected/package: sort

### ISSUE THREAD

**Issue by hasanerken** [golang/go#50238]
### What version of Go are you using (`go version`)?
<pre>
$ go version
 go1.17.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hasanerken/Library/Caches/go-build"
GOENV="/Users/hasanerken/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hasanerken/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hasanerken/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hasanerken/GolandProjects/udemy-works/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1q/_s4y26zs2glbg5kh0ykg5fqr0000gn/T/go-build2332049829=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
There is problem in the sorting of Turkish characters.
In Turkish ğ is before h. But in the sortStrings h is before ğ.

Here is the link for the case, output and the expected output.
https://go.dev/play/p/OP4QtYwInkz
Best,
Hasan

**Comment by robpike** [comment]
It's an internationalization issue. SortStrings uses the Unicode values for its comparisons. The Turkish ğ is U+110F, but h is ASCII, U+0068. This is widespread problem in Unicode. Different languages order the some characters opposite to the same characters in other languages, and the simple < operator in Go won't always "work" because it doesn't have the language-specific remapping.

The more general, language sensitive solution starts with collation using  something like the tools in "golang.org/x/text/collate".

**Comment by mdlayher** [comment]
This seems unactionable for package sort per the above, and x/text can be used instead, so closing.

**Comment by hasanerken** [comment]
> 

It is a great honour  for me to get an answer from you. Thanks...
