### ISSUE TITLE
x/vulndb: labels not applied when issue is created

### ISSUE THREAD

**Issue by julieqiu** [golang/go#50300]
When an issue is created on the x/vulndb issue tracker, the `NeedsTriage` label should be applied and it is not. See https://github.com/golang/vulndb/blob/552ce2251f67e44f2553e39b7b878d03d586a8ff/internal/worker/worker.go#L215 and https://github.com/golang/vulndb/issues/145 (as an example).

**Comment by dmitshur** [comment]
Is it because the label in x/vulndb doesn't have a space ([NeedsTriage](https://github.com/golang/vulndb/labels?q=NeedsTriage)),  
but in [worker.go](https://github.com/golang/vulndb/blob/552ce2251f67e44f2553e39b7b878d03d586a8ff/internal/worker/worker.go#L215) it does (`Labels: []string{"Needs Triage"}`)?

**Comment by julieqiu** [comment]
Closing since we don't use this label anymore.
