### ISSUE TITLE
Redundant type specification when passing one generic function to another

### ISSUE THREAD

**Issue by siggimoo** [golang/go#50319]
### What version of Go are you using (`go version`)?
<pre>
go version go1.18beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Latest beta release, yes.

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
<pre>
package main

import "fmt"

func mapValues[T int64 | float64 | uint64](in []T, mapper func(T)T) []T {
	out := make([]T, len(in))

	for i, n := range in {
		out[i] = mapper(n)
	}

	return out
}

func adder[T int64 | float64 | uint64](n T) T {
	return n + 1
}

func main() {
	intValues := []int64{1, 2, 3, 4, 5}
	floatValues := []float64{1.1, 2.2, 3.3, 4.4, 5.5}

	fmt.Printf("map of ints: %v\n", mapValues(intValues, adder))
	fmt.Printf("map of floats: %v\n", mapValues(floatValues, adder))
}
</pre>

### What did you expect to see?
<pre>
map of ints: [2 3 4 5 6]
map of floats: [2.1 3.2 4.3 5.4 6.5]
</pre>

### What did you see instead?
<pre>
./main.go:22:55: cannot use generic function adder without instantiation
./main.go:23:59: cannot use generic function adder without instantiation
</pre>

The compiler requires me to specify types for `adder` when passing it to `mapValues`:
<pre>
fmt.Printf("map of ints: %v\n", mapValues(intValues, adder[int64]))
fmt.Printf("map of floats: %v\n", mapValues(floatValues, adder[float64]))
</pre>

However, if I change the first one to `uint64` like this:
<pre>
fmt.Printf("map of ints: %v\n", mapValues(intValues, adder[uint64]))
</pre>

... then I get the following error:
<pre>
./main.go:22:55: type func(n uint64) uint64 of adder[uint64] does not match inferred type func(int64) int64 for func(T) T
</pre>

This begs the question: if the compiler knows what type `adder` should be why do I have to say it?

**Comment by ianlancetaylor** [comment]
> This begs the question: if the compiler knows what type adder should be why do I have to say it?

There are two different things going on here: determining the type argument to pass to `adder`, and then calling `mapValues`.  The compiler is able to infer the type argument for `mapValues` from the first argument (`intValues` or `floatValues`) so there is no need to specify a type argument for `mapValues`.  And that means that the compiler knows the type that the second argument to `mapValues`, `adder`, must have.

However, there is no type inference rule that uses a known type to infer the type arguments for `adder`.  In the current language there are only two type inference rules, function argument type inference and constraint type inference.  You are looking for a different kind of type inference rule, that we might perhaps call context type inference.  Without that sort of type inference, the compilation fails if you don't specify type arguments for `adder`.

When you do specify type arguments for `adder`, the compiler is able to determine the complete type for the second argument to `mapValues`.  It can then see whether that type is assignable to the second argument to `mapValues`, based on the type arguments inferred for `mapValues` based on the first argument.  In the `adder[uint64]` case the types are not assignable, and compilation fails as you have seen.

The new inference rule you want is mentioned in the proposal document at https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#type-inference-for-generic-function-arguments .

Since this is known and documented, I'm going to close this issue.  Thanks for raising it.

**Comment by ghostsquad** [comment]
@siggimoo at least this works: https://go.dev/play/p/3qD8okY5duZ?v=gotip

see `valueOper` function. Demonstration that when you don't know the type `T` you can still pass around/use generic function types without additional `[T]` there.

Seems this is slightly annoying, but not a blocker for making generic libraries.
