### ISSUE TITLE
cmd/compile: misleading error message when using type parameter in typeset

### ISSUE THREAD

**Issue by icholy** [golang/go#50420]
### What version of Go are you using (`go version`)?

<pre>
devel go1.18-c8861432b8 Sun Jan 2 14:27:43 2022 +0000
</pre>

### What did you do?

``` go
type X[T any] interface {
	T | string
}
```

https://go.dev/play/p/v-8zaOs_d3r?v=gotip

### What did you expect to see?

"cannot use type parameter in typeset"

### What did you see instead?

"cannot embed a type parameter"

**Comment by go101** [comment]
This is specified in https://tip.golang.org/ref/spec#Interface_types

> In a union, a term cannot be a type parameter ...

**Comment by thanm** [comment]
@griesemer per owners.

Personally I think "cannot use type parameter in typeset" is perfectly clear as it is.

**Comment by griesemer** [comment]
Just to be clear (@thanm ), the current error message is: `cannot embed a type parameter`.
cc: @findleyr for suggestions.

**Comment by findleyr** [comment]
I'm not sure if the word(s) 'type set' (or typeset) are appropriate here, since it refers to the entire type set of the interface type.  Maybe "cannot use a type parameter in a union", which is the phrasing currently used in the spec.

**Comment by findleyr** [comment]
...though it may also be confusing that `*T` is valid here, as in 

```
type X[T any] interface {
	*T | string
}
```

Maybe `union terms cannot be type parameters` is sufficiently specific.

**Comment by go101** [comment]
Some off-topic, should the "union" be replaced with "intersection"? `int | string` means allowing the operations which are legal for both `int` and `string`, instead of for either `int` or `string`.

**Comment by ianlancetaylor** [comment]
`int | string` means that both `int` and `string` are in the type set of the interface.  More generally `T1 | T2` means that the union of the type sets of `T1` and `T2` are in the type set of the interface.  So union is the correct term.

It's true that because an operation is supported if it is supported by all types in the type set, one can view operations as going by the intersection.  But from a type set perspective it is definitely a union operator.

See #45346.
