### ISSUE TITLE
go get downloads the older version of the package

### ISSUE THREAD

**Issue by SidharthBihary** [golang/go#50462]
The latest version for "https://pkg.go.dev/github.com/hasura/ApplicationInsights-Go" is v0.4.2 in https://pkg.go.dev/, where as the github repo "github.com/hasura/ApplicationInsights-Go" has the latest version v0.4.4
How the "https://pkg.go.dev/" updates the repos to the latest version?

**Comment by fraenkel** [comment]
It is now showing v0.4.5 for me.

**Comment by bcmills** [comment]
See https://pkg.go.dev/about#adding-a-package.

The versions known to `pkg.go.dev` are only the ones fetched via `proxy.golang.org`. If you do not fetch the package via the proxy (for example, because you have set `GOPRIVATE` to exclude that path, or have set `GOPROXY` to `direct` or another proxy, or are using the Fedora fork that defaults `GOPROXY` to `direct`), then `pkg.go.dev` won't know to update it.
