### ISSUE TITLE
cmd/compile: cannot use .this ( type *T[interface{}]) as type T[go.shape.interface {}_0] in  T[go.shape.interface {}_0].Method

### ISSUE THREAD

**Issue by csgura** [golang/go#50486]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-07525e1 Fri Jan 7 00:15:59 2022 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

The gotip playground

### What did you do?
https://gotipplay.golang.org/p/vuF7acfKTIv

### What did you expect to see?
No Error.

### What did you see instead?

```
# goerror
<autogenerated>:1: cannot use .this (type *fp.Seq[interface {}]) as type fp.Seq[go.shape.interface {}_0] in argument to fp.Seq[go.shape.interface {}_0].Append
<autogenerated>:1: cannot use .this (type *fp.Seq[interface {}]) as type fp.Seq[go.shape.interface {}_0] in argument to fp.Seq[go.shape.interface {}_0].Iterator
<autogenerated>:1: cannot use .this (type *fp.Seq[interface {}]) as type fp.Seq[go.shape.interface {}_0] in argument to fp.Seq[go.shape.interface {}_0].Size
```

If I remove  ToSeq or Map method of Iterator, the error goes away.

**Comment by cuonglm** [comment]
Maybe related https://github.com/golang/go/issues/50419 cc @danscales

**Comment by danscales** [comment]
Even though the gotip playground example is still failing, I can't seem to reproduce this locally.  I create the module directory with main.go, go.mod, and fp/fp.go, and when I do 'go run main.go, everything runs fine.  Everything runs fine locally at both 07525e1 and current tip 11b28e7e98 (and also the beta1 release becaeea119).  I also tried building with GOARCH=386 (since I thought the playground is sometimes a 32-bit machine), but that also worked fine.  Is there something different about the gotip playground that I need to account for?

Can anyone else reproduce locally?  I'm missing something.

@randall77 @cuonglm @ianlancetaylor

**Comment by danscales** [comment]
Oops, sorry about that, there was something mixed up in my local setup.  Now I can reproduce it fine.  Will take a look.

**Comment by danscales** [comment]
OK, I understand the issue and have a fix.  (Not related to #50419, since that relates to the use of blanks for typeparams.)
