### ISSUE TITLE
cmd/go: yet another case where time stamps lead us astray

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#5064]
<pre>When building packages outside of the GOROOT (i.e. GOPATH != GOROOT), go may still
attempt to rebuild packages in the GOROOT if they depend on a package in the GOROOT that
appears to be stale.

This is easily reproduced as follows:

$ sudo tar -C /usr/local -xzf go1.0.3.linux-amd64.tar.gz
$ sudo touch /usr/local/go/pkg/linux_amd64/reflect.a
$ echo $GOPATH
/home/jsing/src/mygo
$ cat example/example.go 
package example

import _ &quot;encoding/binary&quot;
$ go install example
go install encoding/binary: open /usr/local/go/pkg/linux_amd64/encoding/binary.a:
permission denied

In the above case, encoding/binary is marked as stale and go attempts to rebuild it
since reflect is considered stale, even though encoding/binary is under the GOROOT. This
results in problems when users are not able to write to GOROOT; the packaging comments
from issue/4106 are also applicable here.</pre>

**Comment by rsc** [comment]
I don't understand what this bug is about anymore, especially given the work that has gone into the go command since it was originally filed. If something is not working for you, please create a new issue explaining exactly how to reproduce.

The original report in this issue appears to have been fixed by commit b03a5f66, a year before the report. Again, please file a _new_ issue with details if some specific case is not working for you today (using Go 1.4).
