### ISSUE TITLE
cmd/compile: internal compiler error: shape types have no methods go.shape.int_0

### ISSUE THREAD

**Issue by mishapoiuytrewq** [golang/go#50642]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. 
https://go.dev/play/p/L0FDK8tRORW?v=gotip
or
https://gotipplay.golang.org/p/L0FDK8tRORW

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/misha/.cache/go-build"
GOENV="/home/misha/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/misha/.asdf/installs/golang/1.18beta1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/misha/.asdf/installs/golang/1.18beta1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/misha/.asdf/installs/golang/1.18beta1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/misha/.asdf/installs/golang/1.18beta1/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/misha/GolandProjects/awesomeProject/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1277497051=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://go.dev/play/p/L0FDK8tRORW?v=gotip
or
https://gotipplay.golang.org/p/L0FDK8tRORW

### What did you expect to see?
panic: interface conversion: interface {} is nil, not <-chan int

### What did you see instead?
./main.go:17:14: internal compiler error: shape types have no methods go.shape.int_0

**Comment by ianlancetaylor** [comment]
CC @randall77 @danscales

**Comment by danscales** [comment]
The CONVIFACE that is needed to convert "<- ch.(<-chan T)" (which has type T) to any (empty interface, the type of temp) is currently being created only during the walk phase, but we need it to be created during the transforms after instantiation, so it is available during the dictionary pass.  I can fix the transform pass to do that, but it may be a bit tricky, because of the tight connection between the AS2RECV and RECV operations.  I looks like we have a similar problem with AS2MAPR and AS2DOTTYPE (when the first rhs is implicitly being converted to an interface from a type-param-derived type).
