### ISSUE TITLE
spec: Document rules for recursive type and other self-referential decls

### ISSUE THREAD

**Issue by nico** [golang/go#5069]
<pre>The spec says &quot;An interface type T may not embed itself or any interface type that
embeds T, recursively.&quot;, but nothing like this is mentioned for structs.

(A struct containing itself would obviously need infty memory, but the spec should
probably still explicitly mention that these are illegal while a struct containing a
pointer to itself is fine</pre>

**Comment by jub0bs** [comment]
Any update on this issue? As a Go trainer, I'd like to be able to point participants to an authoritative passage of the spec that would elucidate the restriction. The question also comes up from time to time on Stack Overflow; see https://stackoverflow.com/questions/68016706/nested-structures-in-golang-struct-a-in-struct-b-and-struct-b-in-struct-a

**Comment by griesemer** [comment]
No, this has not been addressed yet, sorry.

But the rules are fairly simple:
1) Array and struct types are invalid if they require infinite amounts of memory.
2) For interface types the rule is written down in the spec.
3) For all other types, there are no restrictions on self-reference.

There's a rule of thumb for 1):
Is it possible to write down a corresponding composite literal in a finite amount of source text, without using a variable of the type in question? If not, the type is invalid.

For example, given:
```Go
type S struct {
   a S
}
```
there is no way to write down a composite literal for `S` in a finite amount of source text:
```Go
var s = S{a: S{a: S{a: ... // never ends
```
(and note that you're not allowed to use a variable of type S inside the composite literal to "shortcut": `var t = S{s}` is not permitted because it's using `s` of type `S`).

This may be a reasonable and intuitive way to teach this restrictions to new Go programmers. It's also accurately reflecting the reason for the restriction (the type checker does exactly this test).

**Comment by ianlancetaylor** [comment]
@griesemer This issue is in the 1.18 milestone; time to move to 1.19?

**Comment by griesemer** [comment]
Yes. This will be hard (and thus take time) to document sufficiently precisely without being too prescriptive. Moving to 1.19.
