### ISSUE TITLE
The git-town project doesn't get into the Go indexing server

### ISSUE THREAD

**Issue by yurivict** [golang/go#50759]
The [git-town](https://github.com/git-town/git-town) project isn't in Go indexing server despite me rebuilding it which should have pulled info from the server.

**Comment by seankhliao** [comment]
It's there now https://pkg.go.dev/github.com/git-town/git-town/v7
looks like it was added when I pull it: https://index.golang.org/index?since=2022-01-22T22:15:10.414478Z
Rebuilding is not enough, you have to pull it through the proxy, see https://pkg.go.dev/about#adding-a-package

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by yurivict** [comment]
Thank you for your help.
