### ISSUE TITLE
cmd/go: follow root dir symlink in fsys.Walk (though not other symlinks in the tree)

### ISSUE THREAD

**Issue by matloob** [golang/go#50807]
cmd/go currently doesn't follow symlinks when looking for packages when module roots (or the current directory in the case of ...). Though we don't want to follow symlinks within modules, it is often confusing to users when their current working directory is a symlink. When walking a directory tree, use stat rather than lstat when reading the root directory to follow the symlink. This will allow users to use the go command as they'd expect when the working directory is a symlink following symlinks within modules.

@bcmills

**Comment by bcmills** [comment]
I filed #50804 for the equivalent behavior in `filepath.Walk`, although I'm not particularly hopeful that anything will change on that side.

**Comment by bcmills** [comment]
@sternopanko, this issue is about a specific workaround in `cmd/go`.

I filed #50804 for a more general `filepath` behavior, but withdrew that issue as it didn't seem worth a breaking change to me. (But note that on that issue I suggest that we treat the working directory as the symlink, not that we walk _through_ the symlink.)

It is certainly possible to implement a `Walk`-like function that traverses symlinks outside of the standard library; see, for example, [`github.com/facebookgo/symwalk`](https://pkg.go.dev/github.com/facebookgo/symwalk).

**Comment by sternopanko** [comment]
That facebook solution is a nice one
I already finished a solution locally, it is very simple to implement
Also, if we are in linux we can check the inode to see if we have been at this point before

**Comment by sternopanko** [comment]
@ianlancetaylor the solution is slightly less intuitive than you might think but is very easy to implement
The facebook solution should probably be part of go

**Comment by sternopanko** [comment]
Of course to detect a loop in the tree (at least for linux)
Just use the inode

**Comment by ianlancetaylor** [comment]
@bcmills @matloob This issue is marked for 1.19.  Should it move to Backlog?  Thanks.

**Comment by bcmills** [comment]
Reopened because I reverted the attempted fix as https://go.dev/cl/461959.
