### ISSUE TITLE
x/tools/go/types/objectpath: frequent use of scope.Names burns significant cycles

### ISSUE THREAD

**Issue by amscanne** [golang/go#51017]
### What version of Go are you using (`go version`)?

go1.18-pre10

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Linux, amd64. Not dependent on OS or architecture, however.

### What did you do?

The objectpath.For method relies on frequent calls to scope.Names(), which always performs a sort of all names. For large-scale analysis trees, this can consume a significant portion of cycles (30-50% in my case) and can easily be memoized. This can either be done by objectpath as a consumer of the API, or within the *types.Scope object.

### What did you expect to see?

Fewer cycles spent sorting.

### What did you see instead?

Lots of cycles spent sorting.

**Comment by findleyr** [comment]
Thanks for filing.

Need to think about this. I'll just note that in the profile linked on that CL, there is also significant amount of time spent in `Scope.Lookup`. But objectpath just needs to walk all the objects, and doesn't care about sorting. I wonder if we should be considering an entirely new `Scope` API...  Or maybe that is further evidence that it would be better for us to build a layer in object path that can significantly optimize the calculation of paths. Compare `x/tools/go/ast/inspector`.

**Comment by findleyr** [comment]
@griesemer @alandonovan what do you think about this change? https://go.dev/cl/383075 appears to be stuck in limbo, and it would be good to make a decision for 1.20.

Being conservative, I am inclined to say that changing scope.Names to return a memoized slice is a breaking change, may increase steady-state memory, and is inconsistent with the rest of the go/types API which goes to lengths to avoid exposing internal data (consider `Struct.NumFields`, etc.). If the problem is mostly isolated to usage of objectpath, we could expose a batch or memoizing API.

But I don't feel strongly. If it is most expedient to save sorted names on the scope, in reality it is _probably_ harmless.

**Comment by adonovan** [comment]
The actual code review hasn't addressed all the comments (e.g. re: atomicity) required for +2, but perhaps that's just because the author doesn't know if the design is worth pursuing.

I agree that if the problem is really just in objectpath, then that's a safer place for the fix: perhaps objectpath could compute the paths for the entire package more cheaply in a single pass, then serve a large number of queries on that---like the AST inspector. Even if we don't implement all that at once, the same API could take the first step of memoizing scope.Names() across multiple calls, but it seems likely there are even bigger potential wins if we take that approach.

**Comment by timothy-king** [comment]
https://go-review.git.corp.google.com/c/tools/+/405354 (WiP for memoizing) was stuck due to not having a clear performance justification yet.

**Comment by findleyr** [comment]
@griesemer and I don't think we want to make this change in go/types, and would prefer improving the objectpath API. Even if we pre-sorted, we'd still want to make a copy and so would lose some of the benefit of memoizing. Moving out of the Go1.20 milestone.

**Comment by mvdan** [comment]
I had an overly simplistic form of `objectpath.For` which I wrote a while ago, which you can see here: https://github.com/burrowers/garble/blob/98466a1f64dfc9a3b9d4bb49dcdb2b3a5ff5f245/main.go#L1533

I tried to switch to objectpath, as it's clearly more complete and I think it might fix two bugs I've been struggling with. However, re-running `go test` prompty crashed my computer out of memory :) It of course was due to all the `Scope.Names()` calls.

In my use case, the tool will be calling `objectpath.For` for almost every object reachable from a package. I know that's perhaps the worst case scenario, but I don't think I could avoid the majority of those calls. I need to essentially record and retrieve a "fact" about every exported name in a package: whether its name was changed or not.

I don't think I can use objectpath right now, but I'd be more than happy to help review or test any improvement or new API in objectpath itself. Memoization or a batch API are likely to make a big difference.

**Comment by adonovan** [comment]
I'd approve a CL that added new API to the object path that allowed it to memoize lookups, e.g. new Encoder(pkg).For(obj). Internally, the Encoder could assert that obj.pkg = enc.pkg. The first time a For call falls through to the need for Scope.Names ("step 4"), the encoder could call Names once (using sync.Once if concurrency is required) then sort the slice into two parts, a slice of TypeName and one of non-TypeName, and retain these two. Then subsequent calls could skip the Names call, its allocation and sort, all the name-based Lookups and type assertions. Would that significantly improve performance in your case? Care to measure it?

**Comment by findleyr** [comment]
I just ran into this while working on the new incremental scalability work.  I observed that building our xrefs Index takes ~50% as long as type checking (6s vs 12s in my benchmark), largely due to calls to scope.Names.

So we're going to need a new API for gopls to use, anyway. We can experiment with it internally first, but should be sure to file a proposal once we're satisfied.

**Comment by findleyr** [comment]
Another place that burned significant cycles was `objectpath.canonicalize`, which could also be optimized with a stateful encoder.
