### ISSUE TITLE
cmd/compile: less helpful error message for invalid array types

### ISSUE THREAD

**Issue by Merovius** [golang/go#51145]
[Originally reported on golang-nuts](https://groups.google.com/g/golang-nuts/c/yHIxVgZpqpk).

It seems the go 1.18 type checker provides less helpful error messages in some cases of invalid array type declarations. For this declaration:

```go
type A [float64]int
```

The go 1.17 compiler prints [(playground link)](https://go.dev/play/p/7BIGcvdvEG0):

> ./prog.go:3:8: invalid array bound float64
> ./prog.go:3:9: type float64 is not an expression

While the go 1.18 compiler prints [(playground link)](https://gotipplay.golang.org/p/7BIGcvdvEG0):

> ./prog.go:3:9: float64 (type) is not an expression

Note that it omits the "invalid array bound float64" message. This seems like a regression to me.

**Comment by KZiemian** [comment]
Thank you @Merovius for taking initiative. I hesitated about posting it myself, because I guess that problem error message "invalid array bound float64" was possible, when compiler know that "[something]" means definition of array. But now it can also mean definition of type parameter and compiler can't/doesn't decide which case it is.

Of course, I may be wrong.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr

**Comment by griesemer** [comment]
This happens to be trivial to fix and it is not invasive. CL forthcoming.
