### ISSUE TITLE
net: silently ignore trust-ad option in /etc/resolv.conf and not to fallback to the cgo resolver

### ISSUE THREAD

**Issue by mateusz834** [golang/go#51152]
The `/etc/resolv.conf` file often includes: `options edns0 trust-ad`. Golang does not recognize either of those options, so it fallbacks to the cgo reoslver. 
I think that `trust-ad` should be silently ignored. Golang does not use the ad flag anywhere, so it should be safe to silently ignore that option and not cause fallback to the cgo resolver.
Edit: [edns0 option](https://go-review.googlesource.com/c/go/+/415579)

**Comment by cherrymui** [comment]
cc @ianlancetaylor @neild

**Comment by DasSkelett** [comment]
This would make sense, Go doesn't have the ability to do DNSSEC validation, so there isn't any alternative to trusting the AD bit.

There is one difference in behavior for glibc with this option though: If it's set, glibc sets the AD bit in queries, otherwise it doesn't. Some DNS recursors might be configured to only do DNSSEC validation if the AD (or DO) bit is set, and otherwise return everything even if it's bogus.
So in theory this could lead to Go receiving bogus data while it would've been filtered for the CGO resolver.
In practice however I think this recursor behavior is getting rare, most of them are configured to always validate DNSSEC (regardless of AD/DO bit) nowadays.

**Comment by mateusz834** [comment]
Thanks for including that link to the PowerDNS docs. It is even the default behavior of PowerDNS since 4.5.0.
It can still affect programs when `trust-ad` is set and the go resolver is forced (via `GODEBUG` env).
I don't knot if forcing the go resolver (via `GODEBUG`) is common, but someone might be doing it.

**Comment by mateusz834** [comment]
Also it looks like it might affect when compiled with musl libc. It does not set the AD flag when trust-ad is set.
![test](https://user-images.githubusercontent.com/19653795/153934334-51e920cc-1755-4555-b730-f7dc22c74b5d.png)

**Comment by mateusz834** [comment]
This are the changes that I will create a PR for: [`trust-ad`](https://github.com/mateusz834/go/commit/5ac19fccf7e9cf86058162759a91138e0c4e76c1)
But I don't know if I can create a PR before merging the golang/net#136 and updating the vendor directory (in this repo).
