### ISSUE TITLE
https://pkg.go.dev/encoding/base64

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51288]
https://pkg.go.dev/encoding/base64

There should not be a DecodeString function if there is no EncodeString function.

Both can be accomplished by using a []byte.

**Comment by randall77** [comment]
We can't remove the method `(*Encoding).DecodeString` due to the [Go 1 compatibility guarantee](https://go.dev/doc/go1compat).
I'm going to close this issue, as I don't think we want to do this. Maybe given a mulligan we could redesign this API, but as we have to support the existing API I don't see any way to reconcile this minor inconsistency without breaking existing programs.

**Comment by andrewhodel** [comment]
Why would you want to confuse people by not having an encode and decode function with the same name structure?

I opened the previous issue and the guy closed it because it said to add it, now you are saying maintain forward compatibility but that is possible by adding the missing function with the same name structure.

**Comment by randall77** [comment]
Our naming convention would imply that `EncodeString` and `DecodeString` both take a `string` as *input*. The function `EncodeToString` generates a string as *output*, that is why its name has the `To` in it.

It is possible to add a `EncodeString` function (which would take a `string` as input), feel free to propose that if you wish. Please read the [proposal process](https://github.com/golang/proposal) first and follow its instructions.

**Comment by andrewhodel** [comment]
That's what the bug report is for, a bug in the Go language.

Someone was typing out that module and forgot the EncodeString() function.
