### ISSUE TITLE
about import

### ISSUE THREAD

**Issue by cotiAutonomousCar** [golang/go#51310]
can't import file, only can import package; so this will lead to the possibility of import cycle increase。
for example:
import util package, general, util package has many file, these files import other package, other package import util package, in this case,
import cycle easy to happen

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

Close this issue for now.
--------------
p.s. You might want to split different purpose files into different package instead of one "util" package 
https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

Specfication about package
https://go.dev/ref/spec#Packages
> A set of files sharing the same PackageName form the implementation of a package. An implementation may require that all source files for a package inhabit the same directory.
