### ISSUE TITLE
os/exec: TestNohup fails inside tmux

### ISSUE THREAD

**Issue by petar** [golang/go#5135]
<pre>darwin
amd64
08d20469cc20 tip

When running ./all.bash inside a tmux session, one of the tests fails.

When running it from the &quot;normal&quot; console (in Terminal), it passes fine.</pre>

**Comment by jacobsa** [comment]
FWIW, this still happens to me when attempting to build Go 1.5 in tmux 2.0 on OS X 10.10.5. Does anybody understand exactly what's going on?

**Comment by ianlancetaylor** [comment]
I wouldn't say I know exactly what's going on, but the broad details seem clear enough: you can't run /usr/bin/nohup on a tmux.  If you do, it will fail with the inappropriate ioctl error message.  You should be able to create this yourself in a tmux: "/usr/bin/nohup ls".

What we should do in Go is recognize that error message and, if we see it, skip the test rather than failing it.  I don't use Darwin so I can't recreate the problem myself (tmux on GNU/Linux works fine), but it ought to be an easy fix for anyone who can.

**Comment by davecheney** [comment]
Googling results are inconclusive

http://thread.gmane.org/gmane.comp.terminal-emulators.tmux.user/4450

It seems that nobody really cares about this use case on darwin, well, from
the tmux side at least.

Tmux makes itself known with env vars, perhaps I can skip the test if we
see those env vars.

**Comment by jacobsa** [comment]
@davecheney: Are you looking at this further? If not, I'll send a CL.

**Comment by davecheney** [comment]
I am not actively looking at this at the moment.

**Comment by jacobsa** [comment]
Okay, I'll prepare a CL.

For the record, the issue is misnamed: the failing test is in os/signal.
