### ISSUE TITLE
types2, go/types: the scope of a type parameter identifier in a method of a generic type is too large

### ISSUE THREAD

**Issue by zigo101** [golang/go#51503]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
type T[T any] struct {} // okay

func (T[T]) Bar() {} // error: T is not a generic type
```

### What did you expect to see?

Compiles okay.

### What did you see instead?

Fails to compile.

Honestly, the behavior conforms to the tip spec:

> The scope of an identifier denoting a type parameter of a generic function or declared by a method receiver is the function body and all parameter lists of the function. 

However, I think , for a method of a generic type, the scope should begin after the name of the generic type in the receiver, instead of beginning the start of receiver part.

**Comment by ALTree** [comment]
cc @griesemer

**Comment by griesemer** [comment]
Hm. We're treating the receiver declaration like any other parameter list (including type parameter lists) for simplicity. I suppose [we could say](https://tip.golang.org/ref/spec#Declarations_and_scope):

> The scope of an identifier denoting a type parameter of a generic function or declared by a method receiver _starts after the function name and ends at the end of the function body_.

This seems just as simple, perhaps even simpler. And it would avoid this arguably confusing error; even though I don't recommend choosing identifiers like this. But traditionally we have been paying attention to the ergonomics of scopes, so I think this warrants some attention.

But it seems that we should be able to make this change later (1.19) as I can't see how it would invalidate programs that are now possible.

(It's not an easy change, implementation-wise though, due to the way methods are represented: a method declaration corresponds to an instantiation of the method with the type parameters declared by the receiver which currently requires that the type parameters by the receiver are in scope in the receiver. This allows us to re-use a lot of code; but has also caused trouble. We were planning to change that part of the implementation independently. In any case, I wouldn't think this to be an impediment to making this spec change.)

@ianlancetaylor @findleyr thoughts?

**Comment by go101** [comment]
More precisely, the scope of type parameter identifier in a generic type method declaration should be the current definition excludes the receiver generic type name part.

The following error should be expected. The type parameter is declared firstly, then the value parameters (including receiver).

```Go
func (T1 T[T1]) Bar() {} 
// ./main.go:n:7: T1 redeclared in this block
//	./main.go:n:12: other declaration of T1
```

**Comment by griesemer** [comment]
@go101 The suggestion for the new scope rule [I gave](https://github.com/golang/go/issues/51503#issuecomment-1059822040) seems good enough: the scope of ordinary parameters (including the receiver) is the function body and type parameters are also declared in that block. The same block cannot have the same identifier twice.

**Comment by go101** [comment]
A similar problem:

```Go
type C any

type _[C C] struct{} // cannot use a type parameter as constraint
func _[C C] () {}    // cannot use a type parameter as constraint

func _(C C) {} // okay
```

**Comment by ianlancetaylor** [comment]
Yes, the scope of identifiers in a type parameter list is different from the scope of identifiers in a function parameter list.  This is intended and documented.  It's a necessary inconsistency, as we can't change function parameter lists, but we must permit forward references in a type parameter list.

**Comment by griesemer** [comment]
The corresponding proposal has been accepted. This issue now tracks the implementation.

**Comment by griesemer** [comment]
@smowton The actual spec change was made. This issue tracks the fact the the compiler doesn't follow the spec.

**Comment by smowton** [comment]
Heh, that might be worth mentioning in the notes -- Go is now supposed to support this snippet... but there are no implementations of the spec yet :)

**Comment by inliquid** [comment]
So release notes for go1.19 says this has been changed, however I see that problem still exists. This is the only opened issue with regard to it, another one locked. 

Do above comments mean that change was made **_only to documentation_** and not implementation? Sounds weird. Why even mention it then?

**Comment by griesemer** [comment]
The change was made in the documentation (spec) because we want the spec to be correctly describing the design (which it didn't). We haven't done the implementation yet, which requires #51343 first (and that one is non-trivial).

**Comment by griesemer** [comment]
This depends on #51343. Moving to 1.21.

**Comment by griesemer** [comment]
This depends on #51343 which moved to 1.22. Moving to 1.22.

**Comment by griesemer** [comment]
This depends on https://github.com/golang/go/issues/51343 which moved to 1.23. Moving to 1.23.

**Comment by griesemer** [comment]
This depends on https://github.com/golang/go/issues/51343 which moved to 1.24. Moving to 1.24.
