### ISSUE TITLE
affected/package: internal compiler error: expected an error about append

### ISSUE THREAD

**Issue by rohitdrake** [golang/go#51524]
**go version: go version go1.17.7 darwin/amd64**
**os: macOS Catalina , Version: 10.15.5 (19F101)**
**Processor: 1.8 GHz Dual-Core Intel Core i5**

`package main

import "fmt"

func main() {
	var notes []string
	notes = make([]string, 7)
	notes[0] = "sa"
	append = append(notes, "re")
	fmt.Println(notes)
}`

Above code after compilation gives the following output:

> # command-line-arguments
> ./slice.go:9:9: internal compiler error: expected an error about append
> 
> Please file a bug report including a short program that triggers the error.
> https://golang.org/issue/new

Meanwhile below code works as intended:
`package main

import "fmt"

func main() {
	var register []string
	register = make([]string, 7)
	register[0] = "rohit"
	register = append(register, "bhardwaj")
	fmt.Println(register)
}`

**Comment by ianlancetaylor** [comment]
Thanks for reporting the issue.

This has been fixed on tip.  I get:

```
# command-line-arguments
foo.go:9:2: append (built-in) must be called
```

It is still broken in 1.17, but we don't normally backport fixes for problems with invalid code.  In effect 1.17 is giving a really bad error message.  1.18 will give a better one.  Closing the issue since there is nothing to change.  Thanks for reporting it.
