### ISSUE TITLE
cmd/go: type set overlapping implementation for interface types might be not correct

### ISSUE THREAD

**Issue by go101** [golang/go#51607]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
// okay
type C1 interface {
	interface {bool | int} | interface {bool | string}
}

// okay
type C2 interface {
	interface {bool | int} ; interface {bool | string}
}

// okay
type C3 interface {
	interface {bool; int} ; interface {bool; string}
}

// error: overlapping terms interface{bool; string} and interface{bool; int}
type C4 interface {
	interface {bool; int} | interface {bool; string}
}
```

### What did you expect to see?

C1 contains overlapping. C4 doesn't.

### What did you see instead?

Neither is true thought by the compiler.

**Comment by ianlancetaylor** [comment]
The rule about overlapping type sets only applies to unions, so `C2` and `C3` are OK.  The rule only applies to non-interface types, so `C1` is OK.  And for that matter `C4` is OK too for the same reason.  I'm not sure why the compiler would give an error for that.

This doesn't matter for 1.18, especially since for `C4` the type sets are empty anyhow.  We can fix this one way or the other for 1.19.

CC @griesemer

**Comment by griesemer** [comment]
Pretty esoteric case. This can wait even past 1.19 if need be.

**Comment by go101** [comment]
The rule for non-interface might be unnecessary, for each solo term could be enclosed in `interface{ ... }`.

**Comment by go101** [comment]
It looks overlapping is hard to removed totally.

```Go
type Ptr[T any] *T

type MyConstraint[E any] interface {
	Ptr[int] | Ptr[E]
}

type YourConstraint MyConstraint[int] // okay
```

**Comment by griesemer** [comment]
@go101 That is ok. We identify overlaps as errors because most likely they indicate a programmer error: e.g., code that says `~int|MyInt` (where the underlying type of `MyInt` is `int`) is likely the result of not fully understanding the effect of the constraint, which is why we point it out. Similar to how we point out duplicate explicit method entries in an interface. But we accept duplicate method entries through embedding of interfaces, and so do we accept duplicate/overlapping type elements through interfaces in unions. For parameterized types we can't say anything before use, and that's ok.

**Comment by griesemer** [comment]
@gopherbot please backport to 1.18, this bug leads to confusing and misleading errors, and the fix is straight-forward.
