### ISSUE TITLE
cmd/cgo: cannot convert from type *_Ctype_char to type _Ctype_HANDLE (1.18 regression)

### ISSUE THREAD

**Issue by josharian** [golang/go#51726]
This code compiled on Windows with Go 1.17, but not with Go 1.18:

```
package p

/*
#include <windows.h>
*/
import "C"

func Error() {
	var x *C.char
	_ = C.HLOCAL(x)
}
```

The error message is:

> p.go:10:15: cannot convert x (variable of type *_Ctype_char) to type _Ctype_HANDLE

Reverting 635e49388bf746a2b8c7ab1e9026aede0eb88b31 allows the code to compile again.

cc @eliasnaur @randall77 @dsnet @bradfitz

**Comment by ALTree** [comment]
@josharian is this a problem in tip too? (I assume it is). If that's the case, this issue should be put in the 1.19 milestone, and the backport issue that you can ask gopherbot to open will be the one in the 1.18.1 milestone.

**Comment by josharian** [comment]
@ALTree oh right. thanks.

@gopherbot please open a backport issue for Go 1.18. This is a compilation regression.

**Comment by bradfitz** [comment]
(This bug was minimized from https://github.com/cyolosecurity/certstore/blob/main/certstore_windows.go#L666)

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
CL 350070 is based on the valid observation that although the type of Windows `HANDLE` is `void*`, the values stored in variables of type `HANDLE` are normally not pointers.  Since Go's GC really wants to know whether something is a pointer or not, telling it that values of type `HANDLE` are not pointers seems like the right move in general.

Now, perhaps it's true that `HLOCAL` values happen to be pointers to memory.  As far as I can tell the correct way to get an `HLOCAL` value is to call [`LocalHandle`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-localhandle); I guess that's a pointer to memory?  And it appears that new code is supposed to call [`HeapAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) which doesn't have this problem.

Anyhow, if we are expected to convert Go pointers to `HLOCAL` and thus to `HANDLE`, we are in trouble, because now a `HANDLE` is sometimes a pointer to memory and sometimes not.

I don't see a problem with the code in cyolosecurity, and the code can easily be changed to compile by writing

```Go
	defer C.LocalFree(C.HLOCAL(unsafe.Pointer(cmsg)))
```

So it seems to me that the Go 1.18 behavior is safer and code that plays fast and loose with pointers should be adjusted.  (Note that the Go 1 compatibility guarantee does not apply to cgo code.)

Of course it would be better if that code could continue to work, and I'm certainly open to suggestions.

**Comment by dblohm7** [comment]
I'll offer a bit more context here:

The `LocalAlloc`, `LocalFree`, `GlobalAlloc`, `GlobalFree` and their other adjacent APIs are holdovers from 16-bit Windows. In those days, when we allocated heap memory, those functions would truly return a handle. The programmer would have to then call `LocalLock` or `GlobalLock` to convert that handle into a pointer, and then call `LocalFree` or `GlobalFree` when done accessing the memory.

Nowadays, for better or worse, the `HLOCAL` handle is frequently treated as synonymous with the pointer. `HGLOBAL`s often are as well (though my personal preference is not to do so).

In general, I'd suggest that the best rule of thumb is to avoid allocating memory using those functions unless other APIs involved specifically require it -- eg the Win32 clipboard APIs expect to work with `HGLOBAL`s. If some some reason a block of memory must absolutely be allocated via the Windows heap, [HeapAlloc](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) should be the default API choice.

**Comment by ianlancetaylor** [comment]
@dblohm7 Thanks.

It looks like the code that led to this issue is calling `FormatMessage` with the `FORMAT_MESSAGE_ALLOCATE_BUFFER` which [does indeed](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage) allocate memory using `LocalAlloc`.  It's then casually converting that memory to `char*`, which I guess is fine today but it should really be calling `LocalLock`, and should really be passing the original value to `LocalFree`.

So I think there is a plausible argument that the code in question is technically incorrect and this change caught the error.

**Comment by josharian** [comment]
OK, sounds like this working as intended. Thanks, @ianlancetaylor and @dblohm7.

**Comment by ianlancetaylor** [comment]
Thanks, closing this issue as there currently doesn't seem to be anything to change in the Go tools.  Please comment if you disagree.
