### ISSUE TITLE
Replace all indications of golang.org with go.dev throughout the documentation

### ISSUE THREAD

**Issue by devilHorns13** [golang/go#52273]

**Comment by mvdan** [comment]
I don't think this needs a tracking issue; you should be able to send patches to fix these up.

**Comment by dmitshur** [comment]
The golang.org domain is still used in module paths like `golang.org/x/tools`, those aren't changing. As a result, a global replace-all isn't viable, and individual instances can be addressed over time. Since golang.org redirects just fine, as Daniel said, it seems we don't really benefit from a tracking issue (without any additional information).
