### ISSUE TITLE
time: TestTruncateRound failure on `windows-amd64-race`

### ISSUE THREAD

**Issue by bcmills** [golang/go#52409]
```
--- FAIL: TestTruncateRound (0.08s)
    time_test.go:327: Time.Round(292277024745-03-22T05:19:12.046916062Z, 1911567h18m9.24972109s) = 292277024812-12-10 14:07:35.54851097 +0000 UTC, want 292277024845-12-31T06:48:18.54851097Z
        -9223372033153436463953083938 round 6881642289249721090 =
        -9223372031016300760451489030 want
        -9223372029973133517451489030
FAIL
FAIL	time	2.300s
```

`greplogs --dashboard -md -l -e 'FAIL: TestTruncateRound'`

[2022-04-15T23:25:46-e398266/windows-amd64-race](https://build.golang.org/log/1f3400c1a75d7a11fd1098e66c0031e5f924af10)

**Comment by bcmills** [comment]
Since `windows/amd64` is a [first-class port](https://go.dev/wiki/PortingPolicy#first-class-ports), marking as release-blocker for triage.

It's not obvious to me whether this failure was for one of the hard-coded inputs or the randomly-generated ones.

**Comment by rsc** [comment]
Looks like that was a 1-in-300,000,000 guess on the part of the windows-amd64-race builder. The short builder was doing 1000, so really 1-in-300,000. And then there were four of those tests that could have failed, so 1-in-75,000. It seems like we should have seen this a few times already given the number of trybot and CL checks we run. Anyway, it should be fixed by the pending CL.

**Comment by bcmills** [comment]
Oh, neat! I think that overflow is exactly #20678. 😅
