### ISSUE TITLE
proposal: - symbol

### ISSUE THREAD

**Issue by switchupcb** [golang/go#52415]
Add an assignment symbol (`-`) that returns a named variable if it's not it's zero value. This is definitely NOT an error proposal. If you think it is, I know a doctor who can check your eyes for you. For free! Call me, :wink:.

The zero value of an error (which is a value) is nil.
```go
func bezo(baller, dollers string) error {
    bucko, - := strconv.Atoi(baller)
    bucks, _ := strconv.Atoi(dollers)
    fmt.Println("$:", bucko + bucks)

    return nil
}
```

> The supreme art of war is to subdue the enemy without fighting. Let them handle their errors.
> — Sun Tzu

Implications: https://github.com/golang/go/issues/52380

**Comment by ianlancetaylor** [comment]
I'm sorry, this is clearly not going to happen.  The `-` and `_` symbols look too similar to have such radically different effects.  And nothing in Go permits change in flow of control based on an operator.  I could run the proposal through the whole process, but frankly that would just be wasting people's time.  I'm going to close out this issue.  Sorry.

I encourage you to discuss language issues in a forum like golang-nuts rather than by filing proposal issues.  Thanks.
