### ISSUE TITLE
cmd/compile: incorrect handling of iota in 1.18

### ISSUE THREAD

**Issue by willeccles** [golang/go#52438]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cactus/.cache/go-build"
GOENV="/home/cactus/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cactus/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cactus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cactus/git/golua/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2033115951=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Using [golua](https://github.com/arnodel/golua), 1.18.1 causes panics which did not occur on previous versions of go. I have narrowed down the issue to [this source file](https://github.com/arnodel/golua/blob/dfcf252b6f86c467bde74de962f7d0e110b5fa2c/ops/ops.go) which functions differently now. Running [this program](https://play.golang.com/p/Bp2aMqcdKOl) on 1.18.1 yields different results than 1.17.9, but according to [the language spec](https://go.dev/ref/spec#Iota), 1.18.1 is exhibiting incorrect behavior.

### What did you expect to see?

In the above program, OpAnd should have a value of 1 (`1 + iota<<8` should be `1 + (0)<<8`).

### What did you see instead?

On go 1.17.9, the value is indeed 1. However, on go 1.18.1, the value is 257, meaning that `iota` here is incorrectly being set to 1 instead of 0. The language spec says that each constant declaration should reset `iota` to 0, which is not happening on 1.18.1.

**Comment by willeccles** [comment]
Original discussion of this issue can be found here: https://github.com/arnodel/golua/issues/87

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport to 1.18.

This is an invalid compilation of a valid Go file.  Earlier releases are unaffected.

**Comment by zikaeroh** [comment]
FWIW I tried to bisect this, and it blamed the commit where `-G=3` was enabled by default; re-bisecting between 1.17 and 1.18 with `-G=3` fails immediately because the issue appears to predate those releases. Going back further gets into the weeds since it's probably not something that was introduced via some specific commit thanks to the WIP-ness of the compiler at that point.

**Comment by griesemer** [comment]
No need to bisect. This is due to a completely new type checker, so it won't be useful to pin-point to a single change. I've identified the bug and will have a fix in a little bit.

This is clearly a bad bug; but only manifests itself when using iota outside a grouped constant declaration, twice.

As a temporary work-around, you can change your code to:

```Go
// OpOr is a logical or (precedence 0)
const (OpOr Op = 0 + iota<<8)

// OpAnd is a logical and (precedence 1)
const (OpAnd Op = 1 + iota<<8)
```

(put parentheses around the const declarations).
