### ISSUE TITLE
cmd/compile: cannot convert v (variable of type *Bar[T]) to type *Foo[T]

### ISSUE THREAD

**Issue by b97tsk** [golang/go#52529]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Irrelevant.

### What did you do?

```go
package main

type Foo[T any] struct {
	_ *Bar[T]
}

type Bar[T any] Foo[T]

func (v *Bar[T]) M() {
	_ = (*Foo[T])(v)
}

func main() {}
```

### What did you expect to see?

The code compiles.

### What did you see instead?

main.go:10:16: cannot convert v (variable of type *Bar[T]) to type *Foo[T]

The code does compile if the compiler sees type Bar first.

**Comment by ianlancetaylor** [comment]
It does seem that the behavior changes based on the location of the line `type Bar ...`.  That can't be right.

CC @griesemer

**Comment by griesemer** [comment]
Changing the `M` method to a function also makes it work:
```Go
// func (v *Bar[T]) M() {
// 	_ = (*Foo[T])(v)
// }

func _[T any](v *Bar[T]) {
	_ = (*Foo[T])(v)
}
```
Definitely a bug. Possibly some bad interaction with method type parameter instantiation/renaming.
cc @findleyr

**Comment by findleyr** [comment]
@gopherbot, please open a backport issue for 1.18, this is a bug causing valid code not to compile.

**Comment by findleyr** [comment]
This turned out not to be entirely trivial, so I will fix it later this week.

The root cause of the problem is that when we collect a methods, we check that method names are unique among existing methods and fields **before** adding each method. As a result, we have an invariant that recorded method names are always unique among methods and fields. But enforcing this invariant results in us expanding underlying types too soon, before they are fully set-up.
