### ISSUE TITLE
cmd/compile: internal compiler error: 'main': Value live at entry. It shouldn't be

### ISSUE THREAD

**Issue by lurenjia528** [golang/go#52590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lurenjia\AppData\Local\go-build
set GOENV=C:\Users\lurenjia\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\softwarelocation\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=D:\softwarelocation\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\work\code\archer\archer-all\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\lurenjia\AppData\Local\Temp\go-build2952525131=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
```bash
.\main.go:17:23: internal compiler error: 'main': Value live at entry. It shouldn't be. func main, node bbb..autotmp_0, value nil

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

### recurrent
```bash
 tree
.
├── aaa
│   └── main.go
└── bbb
    └── bbb.go

 # cat aaa/main.go 
package main

import (
        "archer-all/test/bbb"
)

func main() {
        bbb.InitOrUpdateTable()
}
# cat bbb/bbb.go 
package bbb

func InitOrUpdateTable() {
        println(T())
}

func T() (int, int) {
        return 1, 1
}

```
then

```bash
 go build aaa/main.go 
# command-line-arguments
aaa/main.go:12:23: internal compiler error: 'main': Value live at entry. It shouldn't be. func main, node bbb..autotmp_0, value nil

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

```

but if modify bbb/bbb.go 
```go
package bbb

import "fmt"

func InitOrUpdateTable() {
	fmt.Println(1)
	println(T())
}

func T() (int, int) {
	return 1, 1
}
```
then

```bash
 # go run aaa/main.go 
1
1 1

```

### What did you expect to see?
why is the println() error

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by mdempsky** [comment]
Playground link: https://go.dev/play/p/V1I_NzFDws5

**Comment by mdempsky** [comment]
I think the issue is we're missing export/import for n.Init for OPRINTLN, and other multi-argument builtins:

Good:

https://github.com/golang/go/blob/89044b6d423a07bea3b6f80210f780e859dd2700/src/cmd/compile/internal/typecheck/iexport.go#L2053-L2063

Bad:

https://github.com/golang/go/blob/89044b6d423a07bea3b6f80210f780e859dd2700/src/cmd/compile/internal/typecheck/iexport.go#L2036-L2040

Should be a straightforward fix (just matching changes to iexport.go and iimport.go, and a regress test case). I'll send a CL tomorrow, unless any contributors want to tackle it.

**Comment by mdempsky** [comment]
FWIW, I think the fix is small and could be easily backported, but I don't think it's necessary here.

It looks like the same issue existed back in Go 1.16, so it's not a recent regression. So there's probably no existing code running into this.

There's also two easy workarounds: (1) rewrite the code to manually spill the multi-value results to temporary variables (e.g., rewrite `println(T())` to `x, y := T(); println(x, y)`; or (2) mark the function as `//go:noinline`.

If anyone else thinks it deserves a backport, I encourage opening a backport issue and we can discuss further there. Thanks.
