### ISSUE TITLE
wiki: TestComments change

### ISSUE THREAD

**Issue by achew22** [golang/go#52625]
I would like to make 2 changes to the wiki page [`TestComments`](https://github.com/golang/go/wiki/TestComments). Per the doc

> Please discuss changes before editing this page, even minor ones. Many people have opinions and this is not the place for edit wars.

This is an attempt to start that discussion.

1. I would like to chagne the link "discuss changes" to have `TestComments` as the wiki article the issue is being filed for. I believe this is a copy/pasta error from when this page was split out of `CodeReviewComments`.
2. I would like to add a table of contents to the top of the page like there is for `CodeReviewComments` that links to all the subsections below. I wish there was a g3docs style `[toc]` tag, but there doesn't appear to be one.

**Comment by dmitshur** [comment]
Thanks for discussing the changes before editing.

1. Yes, this is clearly a typo, and fine to fix.
2. Adding a table of contents, like there is one in `CodeReviewComments`, sounds good. It would be nice if it could be automated, but it's not a big deal if not since the page changes very infrequently. So just doing it manually for now is fine.

Please feel free to apply them to the wiki, and thanks again.

**Comment by achew22** [comment]
Completed in https://github.com/golang/go/wiki/TestComments/63daed209ad1089e9a88557ed76308e9646bef53.

Thank you!
