### ISSUE TITLE
os: File.Stat on Windows doesn't use file handle for directories

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#52747]
On Windows `File.Stat` doesn't use the file handle to retrieve attributes when the file is a directory, due to the lack of a `...ByHandle` Windows API which works on directories (`GetFileInformationByHandle` only works on files), using the path instead.

This means there may be a TOCTOU issue, as the results returned by `Stat` represent the attributes for the file at the path passed to `Open`, which may no longer be the file represented by the file handle if the file has been moved/replaced.

**Comment by qmuntal** [comment]
I've been investigating this issue lately, and I've found that `GetFileInformationByHandle` does support directory handles. The trick is to specify the `FILE_FLAG_BACKUP_SEMANTICS` flag as part of `dwFlagsAndAttributes` when creating the handle via `syscall.CreateFile`. This is the relevant docs: [CreateFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#directories).

This change breaks directory traversal, as [readdir](https://github.com/golang/go/blob/1ce7fcf139417d618c2730010ede2afb41664211/src/os/dir_windows.go#L13) is expecting a handle created via `FindFirstFile`, not the `CreateFile` one. This can be solved by creating a new traversal-enabled handle the first time `readdir` is called. This has the nice benefit of only allocating a `dirInfo` if it is really needed, instead of every time a directory is opened.

I've done a quick prototype of this idea in [CL 405275](https://go-review.googlesource.com/c/go/+/405275), and it seems to work pretty well.
I'm wondering if changes `syscall.Open` to support directories (only in read mode) would be a breaking behavior change.

I'm also pretty sure that there is no need to use the path-based `Find*` API for traversing directories, and that we can instead use [FILE_FULL_DIR_INFO](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_full_dir_info) retrieved from [GetFileInformationByHandleEx](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyhandleex).

**Comment by qmuntal** [comment]
Another side effect of CL 405275: The directory handle created by `syscall.Open` does not have the share mode `FILE_SHARE_DELETE` set (see #32088), but the handle created by `syscall.FindFirstFile` did.

This means it wouldn't be possible to move or remove an opened directory, just as it is already happening with normal opened files. @alexbrainman @mattn thoughts?

**Comment by mattn** [comment]
How does `os.File.Fd()` work? It should always return the handle of the file. Because the user passes that handle to the function that expect the file descriptor. I think this might possibly makes another side-effect with this change. To put it simply, I think `File` should return ErrNotSupported or whatever for listing files.

**Comment by qmuntal** [comment]
> How does os.File.Fd() work? It should always return the handle of the file. Because the user passes that handle to the function that expect the file descriptor. I think this might possibly makes another side-effect with this change. To put it simply, I think File should return ErrNotSupported or whatever for listing files.

`os.File.Fd()` returns whatever handler is stored in `file.pfd.Sysfd`.

This is the current behavior:
- If the opened file is not a directory, the handle is created using `syscall.Open`, which internally calls `syscall.CreateFile`. This handle works in most win32 apis expecting file handles.
- If the opened file is a directory, the handle is created using `syscall.FindFirstFile`. This handle mostly only works in `syscall.Find*` apis, i.e., it doesn't work in `syscall.GetFileInformationByHandle`, which is used by `os.File.Stat`.

So one could say that the current behavior of `os.File.Fd()` for directories is only good if you need to traverse it, but not for the general case.

[CL 405275](https://go-review.googlesource.com/c/go/+/405275) changes how directory handles are constructed, instead of using `syscall.FindFirstFile` it uses `syscall.Open`, unifying regular file handles with directory handles. This means `os.File.Fd()` will return the same type of handle regardless if it is pointing to a directory, but it won't be directly usable in `syscall.FindNextFile`.

**Comment by qmuntal** [comment]
Summary of behavior changes in [CL 405275](https://go-review.googlesource.com/c/go/+/405275):

- `File.Stat()` TOCTOU is fixed because it uses a file handle instead of a path
- `os.Open()` opens, when in read-only mode, files and directories with the `FILE_FLAG_BACKUP_SEMANTICS` flag. This means that the returned file handler will have additional restore and backup permissions. See [docs](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea). I don't expect this to pose any security concern, as the process still need `SE_BACKUP_NAME` and/or `SE_RESTORE_NAME` privileges to perform this operate with these additional capabilities.
- Directories opened via `os.Open()` will not be removable nor renamable until `File.Close()` is called, as they won't have the `FILE_SHARE_DELETE` permission. Note that this is already the behavior of files opened via `os.Open()`, but it might break some fragile tests.

I don't see how we can avoid these behavior changes if we want to fix the TOCTOU issue, using `FILE_FLAG_BACKUP_SEMANTICS` is required to get a directory handle.

@alexbrainman @rsc @ianlancetaylor

**Comment by alexbrainman** [comment]
> Summary of behavior changes in [CL 405275](https://go-review.googlesource.com/c/go/+/405275):

I am not against these changes. Mainly because it is @bcmills and others will be dealing with new bugs introduced by this change.

I don't see TOCTOU as a problem. But I am not security expert. It is hard for me to judge if these changes actually help any users or not.

On the hand @qmuntal mentioned that CL 405275 also fixes #36019 and #43322 .

Up to others if we should submit CL 405275 or not.

Alex

**Comment by bcmills** [comment]
> Directories opened via `os.Open()` will not be removable nor renamable until `File.Close()` is called, as they won't have the `FILE_SHARE_DELETE` permission.

At the risk of reopening a can of worms, we've had a lot of discussion in the past about `FILE_SHARE_DELETE` (see #35150, #34681, #32088). I'm not sure that this would really make things on that front any worse, but it is already something of a source of friction.

**Comment by bcmills** [comment]
> `os.Open()` opens, when in read-only mode, files and directories with the `FILE_FLAG_BACKUP_SEMANTICS` flag.

The documentation for that flag says that it means “[t]he file is being opened or created for a backup or restore operation.” In general `os.Open` is not performing a backup or restore operation, so that flag seems a little odd, and I can't find much other documentation on it beyond that it allows opening directory handles. (See previously #23312.

I wonder, though: when we call `FindFirstFileW` we get a search handle for the directory, and the `WIN32_FIND_DATAW` structure that we use to iterate over that handle lists files by basename (in the `cFileName` field), not by returning handles to the individual files.

So, I'm wondering: does that search handle itself not prevent the directory from being renamed, akin to opening it without the `FILE_SHARE_DELETE` flag? Otherwise, how is one intended to open sequential files in a directory without a similar TOCTOU problem?

**Comment by qmuntal** [comment]
> At the risk of reopening a can of worms, we've had a lot of discussion in the past about FILE_SHARE_DELETE (see https://github.com/golang/go/issues/35150, https://github.com/golang/go/issues/34681, https://github.com/golang/go/issues/32088). I'm not sure that this would really make things on that front any worse, but it is already something of a source of friction.

It would make things more homogeneous. The current `os.Open` behavior is to open files without `FILE_SHARE_DELETE` (see #32088) and directories with `FILE_SHARE_DELETE`. The latter is probably not a conscious decision but just a side effect of `FindFirstFileW` implicitly setting `FILE_SHARE_DELETE`. We can decide

**Comment by qmuntal** [comment]
> The documentation for that flag says that it means “[t]he file is being opened or created for a backup or restore operation.” In general os.Open is not performing a backup or restore operation, so that flag seems a little odd, and I can't find much other documentation on it beyond that it allows opening directory handles. (See previously https://github.com/golang/go/issues/23312.

It is unfortunate that `FILE_FLAG_BACKUP_SEMANTICS` conflates backup operations and directory handling, don't know the reasoning. For what I understand, the main reason #23312 was closed was due do to this argument from @alexbrainman:

> We only use FILE_FLAG_BACKUP_SEMANTICS to open directories and symlinks. There is no way to open them without FILE_FLAG_BACKUP_SEMANTICS flag. We do not use FILE_FLAG_BACKUP_SEMANTICS to open files, because everything we do with files work just fine without FILE_FLAG_BACKUP_SEMANTICS.

IMO this argument no longer holds, this discussion has some examples of operations that can only be applied to directory handlers opened via `FILE_FLAG_BACKUP_SEMANTICS`, e.g., #36019.

Having said this, I agree with @alexbrainman that [CL 405275](https://go-review.googlesource.com/c/go/+/405275) will cause troubles to some, mainly to the lack of `FILE_SHARE_DELETE` flag.

> So, what I'm wondering is: does that search handle itself not prevent the directory from being renamed, akin to opening it without the FILE_SHARE_DELETE flag? Otherwise, how is one intended to open sequential files in a directory without a similar TOCTOU problem?

A `FindFirstFileW` handle does not prevent the directory from being renamed or deleted. TOCTOU problems can be avoided by holding a proper file handle created using `CreateFileW` without the `FILE_SHARE_DELETE` flag while traversing the directory, which is in fact what CL 405275 does.

**Comment by alexbrainman** [comment]
> IMO this argument no longer holds, this discussion has some examples of operations that can only be applied to directory handlers opened via `FILE_FLAG_BACKUP_SEMANTICS`, e.g., #36019.

I agree with @qmuntal . Back in #23312 there was nothing to fix - the proposal was to make code less "inconsistent". But [CL 405275](https://go-review.googlesource.com/c/go/+/405275) will actually fix some real issues.

Alex

**Comment by qmuntal** [comment]
> I'm also pretty sure that there is no need to use the path-based Find* API for traversing directories, and that we can instead use [NtQueryDirectoryFile](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfile). These should also be far more efficient, e.g. https://github.com/git-for-windows/git/commit/b69c08c338403a3f8fd2394180664cb9f8164c78#diff-4b6d4f2af4b31f0bc3ff43eac9a2a437.

As promised, now that we have proper file directory handlers there is no need to use Find*, we can switch to a more performant alternative: https://go-review.googlesource.com/c/go/+/452995
