### ISSUE TITLE
gollvm/gofrontend: Should EPOLLET be positive or negative?

### ISSUE THREAD

**Issue by tsqua** [golang/go#52843]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
gollvm
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
Debian
Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (Cascade Lake)
### What did you do?

error case:
```
package main

import (
    "fmt"
    "syscall"
)

func main() {
    b := foo2()
    fmt.Println(b)
}

//go:noinline
func foo2() uint32 {
    var evt uint32
    //evt = (-syscall.EPOLLET) | syscall.EPOLLOUT
    evt = (-syscall.EPOLLET)
    fmt.Println(evt)
    return evt
}
```

### What did you expect to see?
2147483648
2147483648

### What did you see instead?
error: integer constant overflow

### Error description
Found in netpoll building, the user assume this value is negative and get its opposite value. But it's positive in gollvm.
In golang/go, EPOLLET is set to -0x80000000. Is it better to be consistent between the two compilers? Therefore, there is no programming gap when programmers use different compilers. (https://github.com/golang/go/blob/master/src/syscall/zerrors_linux_amd64.go)

**Comment by heschi** [comment]
cc @thanm

**Comment by ianlancetaylor** [comment]
The value varies with the gc syscall package also.  Sometimes it is `0x80000000`, sometimes it is `-0x80000000`, depending on the target.  It does happen to be `-0x80000000` on linux-amd64.

The code in question should be rewritten to use the golang.org/x/sys/unix package instead, where the value is consistently `0x80000000`.

Closing because although the situation is unfortunate, I don't think there is anything to do here.
