### ISSUE TITLE
x/website: Content scrolls up when text is selected

### ISSUE THREAD

**Issue by a3y3** [golang/go#52917]
### What is the URL of the page with the issue?
 Every page on go doc, but I'll refer to https://go.dev/doc/tutorial/workspaces in the examples below.
 
 
### What is your user agent?
[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes) 
 
### Screenshot
![image](https://user-images.githubusercontent.com/3104686/168496650-00436140-9274-40a9-8396-bfb4f6ac4796.png)
 
 
### What did you do?
 - Scrolled down the page a bit.
 - Selected any part of the top text. For example, in the above screenshot: "The use directive tells Go that the module …" using double click.
 
 
### What did you expect to see?
 The text should get selected/highlighted.
 
 
### What did you see instead?
The page scrolls up quickly, creating a very uncomfortable user experience.

**Comment by ZekeLu** [comment]
I can not reproduce this issue. It looks like there is an extension which changes the behavior of the double click. Can you disable all the extensions and try again?

**Comment by a3y3** [comment]
I disabled all the extensions but I can still see the issue. I could even reproduce it on Firefox and Chrome across several Windows versions using [browserling](https://www.browserling.com/).

Here's a gif that shows the bug: https://imgur.com/a/76BN8iG

**Comment by ZekeLu** [comment]
Thank you for providing the information. Since you observed the same behavior across different browsers, I guess that the scroll event (or other events that causes the page to scroll up) is emitted by your system. Maybe the mouse is broken, maybe there is an application capturing the double click events and emitting other events.

Can you try two more things to confirm the root cause of the issue?

1. Try to double click pages from other websites, will the pages scroll up?
2. Try to double click https://go.dev/doc/tutorial/workspaces on another computer, will the page scroll up?

If you know how to use [Spy++](https://docs.microsoft.com/en-us/visualstudio/debugger/messages-view?view=vs-2022), you can use it to check what messages are emitted. It's shipped with Visual Studio. If you don't want to install Visual Studio, you can download it from https://github.com/westoncampbell/SpyPlusPlus. Here is my message options:

![1](https://user-images.githubusercontent.com/1063615/168731797-b6a80c62-32d7-4af8-8f73-fe35576d3a7e.png)
![2](https://user-images.githubusercontent.com/1063615/168731828-12b36a52-f399-4fc7-b0e1-acc4f2f85a84.png)

And here is the messages captured on my computer:

![3](https://user-images.githubusercontent.com/1063615/168731887-a1a5dfd5-2651-4df7-bc0d-f35a66b23d33.png)

**Comment by a3y3** [comment]
Looks like this doesn't happen if you use a mouse. It only happens on laptop touchpads (I verified this on 2 separate laptops, both on Windows), and to a certain extent, touch devices. I could reproduce this issue on an iPhone 13 as well, on both Chrome and Safari.

**Comment by ZekeLu** [comment]
OK, I have managed to reproduce the described behavior.

- touchpad on desktop: `click`->`tap`->`move up`
- mobile phone: `long tap`->`move up`.

If this is your case, then I think the behavior is expected and there is nothing wrong.

**Comment by a3y3** [comment]
I'm not sure how this is expected behavior. Double tap on a touchpad should select the text, not scroll it up automatically.

The Go docs website is the only website where this happens. All other websites select text when double tapped with a touchpad.

**Comment by ZekeLu** [comment]
If you move your finger unintentionally on the second tap, the double tap will be recognized as `click`->`tap`->`move` by the system. Can you confirm whether this is your case first?

**Comment by a3y3** [comment]
Nope. The issue happens without moving your finger at all, with a simple double tap on a word.

**Comment by ZekeLu** [comment]
Can you use Spy++ to capture the messages as suggested in https://github.com/golang/go/issues/52917#issuecomment-1128410732?

**Comment by a3y3** [comment]
I could use it if you really wanted me to, but I don't think this is a problem of my system or my mouse emitting random events. I discussed this with my friend (who could reproduce this issue too, btw, on a completely different computer) and it seems this is a widespread chrome issue, actually. It affects all websites, just to a far lesser extent than it affects the golang documentation website. Also, even with using a touchpad, it should be a "double-tap", not a "double-press", if that makes sense.

To reproduce it on other websites, if you double tap to select a word and the word is almost (but not completely) out of the screen, Chrome will scroll up in the same weird manner. For example, double tapping any of these "half" words will reproduce this issue on Wikipedia. 
![image](https://user-images.githubusercontent.com/3104686/169407631-69202359-3a23-4d60-9a72-3d83d8fe52c8.png)

Now, I don't know why it affects the Go website more than the other websites. Double tapping any of these words will reproduce the issue:
![image](https://user-images.githubusercontent.com/3104686/169407807-14285cec-377f-44f2-a4d3-2a47a55018fa.png)

It probably has to do something with the `line-height` of the body, I think. I increased the `line-height` on `body` to 10 and I could reproduce the issue when the words were far below the screen too.

**Comment by ZekeLu** [comment]
Since this issue is not specific to the golang documentation website, and it's more like a browser, system or hardware issue, maybe we should avoid discussing it here so that we won't make too many noises.

I still incline to the guess that the behavior is a **"select and drag outside of the viewport"**. If you still want to diagnose this issue, please find me on slack. And if we find something, we can report back here.

Thank you!

**Comment by a3y3** [comment]
How do I find you on slack?

**Comment by looshch** [comment]
@a3y3 is right, I can reproduce this as well. @ZekeLu please make sure to position the text **exactly** as on the GIF. The problem is in [_content/css/styles.css on line 250](https://github.com/golang/website/blob/554288cff2951a09f574072446267af094384c07/_content/css/styles.css#L250) `scroll-padding-top: 4.6875rem`. Disabling this rule solves the issue

**Comment by looshch** [comment]
I can create a CL for this, but I asked the original author of this line about his intent. It was almost 2 years ago, probably he won’t recall the reason behind the line, but let’s wait and see

**Comment by ZekeLu** [comment]
@looshch Excellent!

I don't have a touchpad right now. But when I set `scroll-padding-top` to a big value (for example, `100rem`), select the text near the top of the veiwport, and move my mouse at a very little distance, it scrolls to the top of the page very fast. When I set it to `0` and do the same thing, it just scrolls up a little. So obviously, `scroll-padding-top: 4.6875rem` will cause trouble on touchpad more easily (I can not reproduce it on touchpad before because I have the habit to touch the touchpad carefully :smiley: ).

The value is set in this commit: https://github.com/golang/website/commit/5571d04a21b8cfbb7936592f38e955205a52d7d1. But there is not information about why it's set. I think it's safe to remove it.

**Comment by a3y3** [comment]
I’m glad it could be reproduced! As you can imagine, it can get annoying because some people like to read by double tapping on text and selecting it as they read along - and that’s not possible because of the scrolling issue. 

I do wonder why the content scrolls up only on touchpad and not a mouse, though.

**Comment by jamalc** [comment]
This was probably added with the sticky header to make anchor links snap their scroll position below the header content. We removed the sticky header at some point so this scroll fix is no longer necessary. Thanks for the investigation and fix!
