### ISSUE TITLE
cmd/compile: allocation when string key already exists in a map when using map[string([]byte{})]

### ISSUE THREAD

**Issue by renthraysk** [golang/go#52971]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.19-41b9d8c75e Tue May 17 03:26:28 2022 +0000 linux/amd64
$ go version
go version go1.18.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

</details>

### What did you do?
Modify an existing string key value within a map, causes an allocation when using string([]byte{}) conversion, whereas using a string direct doesn't.

https://go.dev/play/p/q5XXrMngkZV

### What did you expect to see?
0 allocations for when using map[string([]byte{})] when the map contains the key.

### What did you see instead?
1 allocation using map[string([]byte{})] when the map contains the key.

**Comment by randall77** [comment]
`m[string(b)]` is allocation free only on map lookup. It is not allocation free on map assignment.
That's because we need to store the key if it isn't in the map yet.
Conceivably we could allocate only when the insert actually inserts (as opposed to updates), but actually inserting is probably the common case.

**Comment by renthraysk** [comment]
Was raised again in issue #55930
