### ISSUE TITLE
cmd/compile: unsafe.Offsetof returns incorrect value  in embedded struct with type parameters

### ISSUE THREAD

**Issue by kazu** [golang/go#53137]
I checked in 1.18.2 / go1.19-52f68efa45.

https://go.dev/play/p/nSbR4HtjOSv

**Comment by kazu** [comment]
https://go.dev/play/p/9Joi2y5p8oE

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky

**Comment by cuonglm** [comment]
It seems that when instantiating generic function, all implicit dot operations are resolved, so `unsafe.Offsetof(d.B)` becomes `unsafe.Offsetof(d.Embedded.B)` at the time we call `evalunsafe`. Thus the base selector is `d.Embedded` instead of `d`.

Maybe we just need to clobber any implicit dot, something like this should work:

```
// Remember base of selector to find it back after dot insertion.
// Since r->left may be mutated by typechecking, check it explicitly
// first to track it correctly.
sel.X = Expr(sel.X)
sbase := sel.X

var clobberBase func(n ir.Node) ir.Node
clobberBase = func(n ir.Node) ir.Node {
	if x, ok := n.(*ir.SelectorExpr); ok && x.Implicit() {
		return clobberBase(x.X)
	}
	return n
}
sbase = clobberBase(sbase)
```

**Comment by cuonglm** [comment]
Should we backport this cc @ianlancetaylor @randall77 ?
