### ISSUE TITLE
cmd/compile: maps doesn't recognize map-clearing range idiom after be inlined

### ISSUE THREAD

**Issue by cwbhhjl** [golang/go#53157]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.2
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

linux & windows , amd64

### What did you do?

https://go.dev/play/p/wi_i3Dx8Hpa

```go
package main

func clearMap(m map[string]string) {
	for k := range m {
		delete(m, k)
	}
}

//go:noinline
func clearMap2(m map[string]string) {
	for k := range m {
		delete(m, k)
	}
}

var m map[string]string

func main() {
	clearMap(m)
	clearMap2(m)
}
```

-----
In go1.18, the compiler will inline clearMap by default, then generates:
```asm
CALL runtime.mapiterinit(SB)
JMP 0x45b3c9
MOVQ 0(DX), CX
MOVQ 0x8(DX), DI
LEAQ type.*+23744(SB), AX
MOVQ 0x20(SP), BX
CALL runtime.mapdelete_faststr(SB)
LEAQ 0x28(SP), AX
CALL runtime.mapiternext(SB)
MOVQ 0x28(SP), DX
TESTQ DX, DX
JNE 0x45b3a7
```

and clearMap2 will call runtime.mapclear. 

Is this expected behavior?

(go1.17 will not inline clearMap)

**Comment by randall77** [comment]
Yes, this is unfortunate. Due to how we do inlining, declarations that were formally local to the `for` loop in the inlined body are moved up to the top of the containing function. That loses the association between `k` and the `for` loop. We need that association because that's how the optimization knows that `k` is not used after the loop.

It would be nice to fix this, but I don't think it is easy.

**Comment by wdvxdr1123** [comment]
I notice unified ir can fix this issue.

**Comment by randall77** [comment]
Fixed in unified IR, which is now enabled by default.
