### ISSUE TITLE
affected/package: parser or text/template

### ISSUE THREAD

**Issue by Quaqmre** [golang/go#53151]
### What version of Go are you using (`go version`)?
go version:1.18.2

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH=amd64
GOOS=wind

### What did you do?
I got  illegal label declaration when i use dash(-) in template string,
Code example here :https://go.dev/play/p/kc70-fvdSax 
if I replace dash to colon(:) it is okey , code work correctly ,
How can i solve this problem i need to use dash in template ,

### What did you expect to see?

services1-

services2-

services3-

### What did you see instead?

 illegal label declaration 

---
label: help wanted
---

**Comment by Quaqmre** [comment]
[proposed Label] help wanted

**Comment by fahrettinEmre** [comment]
hi,   i had this problem too.

**Comment by dmitshur** [comment]
> I got illegal label declaration when i use dash(-) in template string,
> Code example here :https://go.dev/play/p/kc70-fvdSax

Running that snippet produces no output. There's no label declaration error. Modifying the snippet to print errors shows the error comes from the call to `format.Source`.

This appears to be a question about using the text/template or go/format packages rather than a bug report. Please see https://go.dev/wiki/Questions for a list of better places to ask questions. Thanks.

**Comment by mvdan** [comment]
See the comment above. I do not see a bug in text/template here, so closing for now.
