### ISSUE TITLE
go.dev is down

### ISSUE THREAD

**Issue by grumpits** [golang/go#53227]
It's completely unavailable

**Comment by rsc** [comment]
There are no indications of an outage here. Is it still down for you? Anything interesting about your network?

**Comment by grumpits** [comment]
Nothing out of the ordinary. It's completely vanilla. I get the attached from Chrome
![image](https://user-images.githubusercontent.com/61156566/171934871-1cc06600-8210-4c80-8a0b-c8d36d7315cd.png)

**Comment by rsc** [comment]
That's very strange. No one else has shown up to say they are seeing the same thing. If it's still happening now then it is probably worth digging into the "Checking the proxy and the firewall" link.

I'd be curious whether https://swtch.com/ works for you - it is served by the same IP addresses (along with many other App Engine sites).

**Comment by ianlancetaylor** [comment]
Worth checking https://downforeveryoneorjustme.com/go.dev

**Comment by grumpits** [comment]
I /can/ reach swtch.com. I don't use a proxy, and my firewall is just set to the defaults of the OS. On my router, same deal. Maybe I'll try going to a Starbucks and see if that solves anything

**Comment by grumpits** [comment]
@ianlancetaylor yeah, it says it's just me... I'm not sure /why/, though. I'm not doing anything unusual AFAIK

**Comment by bernstein7** [comment]
<img width="730" alt="Screenshot 2022-07-02 at 17 59 41" src="https://user-images.githubusercontent.com/4922362/177005836-afff1a1f-3365-42e8-8f60-825d916e9e91.png">

**Comment by ianlancetaylor** [comment]
@bernstein7 This issue is closed, and the site appears to be working.

I'm sorry you are having trouble, but I don't know what to suggest.  The Go issue tracker is not a useful place to ask that kind of question, as we are unlikely to know the answer.  You are more likely to get the answer from somebody who understands networking and firewall issues.  You can also try one of the forums mentioned at https://github.com/golang/go/wiki/Questions (I hope that you are able to reach GitHub, as you were able to post the question here).  Sorry we can't be of more help.
