### ISSUE TITLE
x/tools/gopls: Default setting of GOPROXY=off causes problems with downloading modules

### ISSUE THREAD

**Issue by Jefftree** [golang/go#53313]
### gopls version

```
golang.org/x/tools/gopls v0.7.5
    golang.org/x/tools/gopls@v0.7.5 h1:8Az52YwcFXTWPvrRomns1C0N+zlgTyyPKWvRazO9GG8=
```

### What did you do?

Hi, I recently upgraded from a gopls version from over a year ago (0.1.0). I was getting an error `module lookup disabled by GOPROXY=off` but my project ([kubernetes](github.com/kubernetes/kubernetes)) has no private repos. (It does use a mod file with replace directives and a vendor directory). 

As a fix, I was able to fix the problem via toggling `allowImplicitNetworkAccess`, but it looks like this is not recommended. I'm not sure if this is a problem with my environment or the go.mod for Kubernetes (everything works smoothly for other repos).

### Editor and settings

Emacs, using lsp-mode and gopls

**Comment by jamalc** [comment]
Is this a problem only when the mod file changes or during startup as well?

**Comment by Jefftree** [comment]
startup as well

**Comment by findleyr** [comment]
Hmm, the initial workspace load is supposed to allow network access.

Also: does `go build` succeed from the command line?

Could you share logs from your gopls session?
https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capture-logs

**Comment by rski** [comment]
for what its worth, https://github.com/NixOS/nixpkgs/issues/177632 was diagnosed to be due to dns resolution issues. I will open another issue because the error ends up being misleading and that is a problem of itself, but maybe there are dns issues going on here too?

**Comment by WhyNotHugo** [comment]
Regarding the above mention on https://github.com/NixOS/nixpkgs/issues/177632, see https://github.com/golang/go/issues/53676

**Comment by hyangah** [comment]
As explained in https://github.com/golang/go/issues/53676#issuecomment-1176223070 `GOPROXY=off` setting is intentional to prevent implicit network access - previously, the go command gopls depends on went to the network at the  unexpected moment and causes unpredictable delays, so gopls attempts to control the network access by setting `GOPROXY=off` when necessary.

Ideally, the required modules should be already locally available in the module cache, or users should explicitly request to download them (`go build`, `go mod tidy` commands, or various code lenses and quick fixes in `go.mod` files or in the import statements). Gopls also attempts to download the missing modules when it starts (aka initial package loading), but it sounds like the initial package loading failed due to the network issue, and the subsequent `GOPROXY=off` error message distracted users. Since there is another issue open (#53676), let's follow up the issue there.
