### ISSUE TITLE
sync: TestMutexLinearOne / TestMutexLinearMany  flaky failure

### ISSUE THREAD

**Issue by cherrymui** [golang/go#53381]
TestMutexLinearOne fails on the PPC64LE builder
https://build.golang.org/log/fc2fadae8dafff0cd6113611853fe2571c0f2e2c
```
--- FAIL: TestMutexLinearOne (0.65s)
    testenv.go:461: [/workdir/tmp/go-build4248153014/b089/sync.test -test.v -test.run=^TestMutexLinearOne$ -test.benchtime=1x] exit status: exit status 1
    testenv.go:490: exit status 1
    testenv.go:491: --- subprocess output ---
        === RUN   TestMutexLinearOne
            testenv.go:528: failure to scale linearly: µ_1=7.7411ms µ_2=23.893656ms p=0.000026
        --- FAIL: TestMutexLinearOne (0.63s)
        FAIL
FAIL
FAIL	sync	1.732s
```

I just got a failure of TestMutexLinearMany running all.bash locally on darwin/arm64.
```
--- FAIL: TestMutexLinearMany (0.12s)
    testenv.go:461: [/var/folders/tf/nsc4z0p112vc_drrjn299ds80000gn/T/go-build1041557856/b1502/sync.test -test.v -test.run=^TestMutexLinearMany$ -test.benchtime=1x] exit status: exit status 1
    testenv.go:490: exit status 1
    testenv.go:491: --- subprocess output ---
        === RUN   TestMutexLinearMany
            testenv.go:528: failure to scale linearly: µ_1=2.0716ms µ_2=6.609958ms p=0.000102
        --- FAIL: TestMutexLinearMany (0.12s)
        FAIL
FAIL
FAIL	sync	0.723s
```

cc @mknyszek @prattmic @aclements @golang/runtime

**Comment by Jorropo** [comment]
Shows up on freebsd amd64 too:
https://storage.googleapis.com/go-build-log/33e4c052/freebsd-amd64-12_3_33e019af.log

**Comment by mknyszek** [comment]
Ugh, OK. Looks like I didn't really make it any better. Maybe I should just disable these tests.

**Comment by mknyszek** [comment]
I'll look into resolving this tomorrow.

**Comment by mknyszek** [comment]
I have a sneaking suspicion that on these platforms, the old version of the test would fall into the "run with a bigger N to water down constant overheads" case. I'll test this theory.

**Comment by mknyszek** [comment]
A full list of failures since landing the new version of the test:

[2022-06-15T00:06:24-2a78e8a/freebsd-386-12_3](https://build.golang.org/log/7b63b132d788c4bc92ee68d183c392ef467eea99)
[2022-06-14T23:44:35-0dffda1/openbsd-386-70](https://build.golang.org/log/4ec583e972ddc513ad71ad70dbd779a9df197025)
[2022-06-14T14:49:40-cad477c/linux-ppc64le-power9osu](https://build.golang.org/log/fc2fadae8dafff0cd6113611853fe2571c0f2e2c)
[2022-06-13T21:24:54-c29be2d/windows-arm64-10](https://build.golang.org/log/8231f81c6c79e304c4d472ae45efa3d96d95fe91)
[2022-06-13T21:19:00-c5be77b/linux-amd64-longtest](https://build.golang.org/log/06f257b6fb0be1e9909c8436ad35a0d02d5b3c6e)

**Comment by aclements** [comment]
For reference, this is really a continuation of #32986, but we just moved and renamed that test.

Should we just turn these into benchmarks that we monitor as benchmarks?

**Comment by mknyszek** [comment]
Well, alrighty. Even running locally on my `linux/amd64` machine, I can tell that the timings coming out of the test are pretty noisy when I stress test it. The test involves lots of locking and blocking goroutines so we're also at the mercy of the underlying OS's thread schedule. The test is inherently flaky in that way.

What's disappointing is that what the test is really trying to check is just that the runtime semaphore implementation, assuming no hash collisions, runs in constant time (except, I don't see why that would be true, because the situations it sets up does force an `E[log(n)]` walk of the treap (and it's a treap, so we could get profoundly unlucky!).

@aclements I think yeah, maybe this should just be a benchmark, but any ideas on how? Ultimately we want to check that there's some asymptotic growth in the underlying algorithm. I'd argue that we should just check the performance of the semaphore implementation directly (which is, unfortunately, deeply entangled with the scheduler).

**Comment by mknyszek** [comment]
I just rewrote this test as a very, very direct one. It should be much closer in flakiness level to `test/maplinear.go` since it's just checking the scalability of operations on a single-threaded data structure.

**Comment by mknyszek** [comment]
"This time for sure."
