### ISSUE TITLE
cmd/trace: document event trace viewer [freeze exception]

### ISSUE THREAD

**Issue by adonovan** [golang/go#53486]
https://go-review.googlesource.com/c/go/+/412876 adds documentation to the main page of the cmd/trace event viewer.
This issue is a request that it be granted a freeze exception, since it is essentially an addition of missing user documentation, and has no real impact on the program behavior.

@prattmic @golang/release

**Comment by dmitshur** [comment]
Since as https://go.dev/s/release says, "During the freeze, only bug fixes and doc updates are accepted.", this seems okay, and I don't think a freeze exception is needed.

This particular documentation is implemented as HTML in a Go template rather than comments or plain HTML files, but it should still be safe. We're still before RC 1.
