### ISSUE TITLE
x/tools: increased timeouts/flakes on windows TryBots

### ISSUE THREAD

**Issue by findleyr** [golang/go#53493]
https://build.golang.org/?repo=golang.org%2fx%2ftools shows six flakes on Windows since https://go.dev/cl/412779 was submitted. Given our low flake rate, I suspect a real regression. (thanks again @bcmills for leading efforts to reduce flakes).

CC @bcmills @matloob

**Comment by bcmills** [comment]
Looks like the failure mode is timeouts. We could either fall back to not indexing GOROOT at all, or maybe a special case to allow `devel` Go versions to be cached by default on the builders.

**Comment by findleyr** [comment]
@bcmills sorry for the naive question, but isn't that CL about _avoiding_ unnecessary work? How would it have caused more work, relative to its parent?

**Comment by bcmills** [comment]
It also fixed a bug in the condition that triggered indexing in `GOROOT` at all.

**Comment by findleyr** [comment]
Aha, thanks. Assuming the index is written to GOPATH, I suppose the problem is therefore that each gopls regression test has a fresh GOPATH and now incurs the cost of indexing GOROOT.

Perhaps we could add a shared GOPATH that is pre-seeded with an indexed GOROOT? Would that be possible?

I'd prefer not to disable go command behavior for our regression tests, as a big part of what the regression tests exercise is interaction with the go command.

**Comment by bcmills** [comment]
> Perhaps we could add a shared GOPATH that is pre-seeded with an indexed GOROOT? Would that be possible?

I suspect that the bottleneck at the moment is just verifying that `GOROOT/src` itself hasn't been invalidated since it was last indexed. We key off of `runtime.Version()` for that: we assume that a `go` built at a release or pre-release version (like `go1.19` or `go1.19beta1`) is unmodified, whereas a `go` built at a development version (like `devel devel go1.19-be0b2a393a Wed Jun 22 02:40:04 2022 +0000`) may have local changes to the standard library on top of the named commit.

The trouble is, to detect local changes we need to walk the entire `GOROOT/src` directory tree to check modification times. On Linux that is fast, but on Windows it is apparently not. (At least, that's my working theory.)

I did add a `GODEBUG=goindexsalt=foo` environment variable to indicate that the source tree is unmodified since the last change to `goindexsalt`, so one option might be to set that explicitly in the `x/tools` tests.

Another option might be to also treat a `devel` version as stable if `GO_BUILDER_NAME` is non-empty. That would have the advantage of speeding up tests on the builders, but the disadvantage of being another way in which the builders differ from running `go test` locally.

**Comment by bcmills** [comment]
(Marking as release-blocker for Go 1.19 because this is due to changes slated for release in `cmd/go` in the release.)
