### ISSUE TITLE
x/website: download button opens new tab

### ISSUE THREAD

**Issue by willfaught** [golang/go#53637]
### What operating system and ~~processor architecture~~ browser are you using ~~(`go env`)~~?

macOS Monterey 12.4 (21F79), Safari 15.5 (17613.2.7.1.8)

### What did you do?

Went to https://go.dev. Clicked on Download.

### What did you expect to see?

The same tab navigate to https://go.dev/dl/.

### What did you see instead?

A new tab open and navigate to https://go.dev/dl/.

Please don't spam with extra tabs. I just want to go to the page. I can Cmd-click to open a new tab if I need to.

**Comment by jinhongy** [comment]
This suggestion make a lot of sense. We opened in a new tab is because by that time it opened the page in "golang.org". Since we have merge this two sites, we should not open in a new tab as the page is no longer an external page.  

For the downloading, we can also consider downloading the package based on the operating system instead of taking developers to the "All download" page since we merged these two sites.

**Comment by hyangah** [comment]
Thanks for the background.

For general Download/installation UX improvement see

https://github.com/golang/go/issues/52491 
https://github.com/golang/go/issues/52487
https://github.com/golang/go/issues/47578

If we can detect the underlying architectures correctly, utilizing go.dev/doc/install (that already detects OS) instead of go.dev/dl is another option.
