### ISSUE TITLE
x/pkgsite: LeftTrim example is not clear 

### ISSUE THREAD

**Issue by monkrus** [golang/go#53772]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/strings#TrimLeft
 
### What is your user agent?
Chrome
Version 103.0.5060.114 (Official Build) (64-bit)

 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/12500447/178158583-a8f4a78b-a6a2-404b-976f-72bc9430932b.png)

 
### What did you do?
 Click on run
```package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Print(strings.TrimLeft("¡¡¡Hello, Gophers!!!", "!¡"))
}

 ```

 Run an example
 
 
### What did you expect to see?
```fmt.Print(strings.TrimLeft("¡¡¡Hello, Gophers!!!", "¡"))```

### What did you see instead?
```fmt.Print(strings.TrimLeft("¡¡¡Hello, Gophers!!!", "!¡"))```

**Comment by seankhliao** [comment]
The example is there to show that from the given cutset, only those matching on the left will be removed. just `"¡"` wouldn't be clear on what happens if `¡` appears elsewhere, eg on the right.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
