### ISSUE TITLE
x/tools/gopls: measure and audit completion performance

### ISSUE THREAD

**Issue by findleyr** [golang/go#53992]
While working in x/tools recently, I observed that I was sometimes missing struct fields in completion results. This should *never* be the case.

It turns out these results are missing due to completion budget being exhausted. Setting "completionBudget" to "1s" worked.  Bisecting, I discovered that prior to https://go.dev/cl/347563 I generally (though not always) got the results I expected.

Clearly our regression testing is not catching regressions in completion performance, and the default completion budget of 100ms can lead to significantly degraded results.

We need to:
1. Investigate why struct fields could ever be missed in completion results.
2. Evaluate our current completion benchmarks, improve them if necessary, and hook them into performance monitoring (see also #53538).
3. Look for low-hanging improvements to completion performance (there must be some, for example the performance hit of https://go.dev/cl/347563 should be easy to mitigate).

**Comment by muirdm** [comment]
I think [this](https://github.com/golang/tools/blob/master/internal/lsp/source/completion/deep_completion.go#L176) return is likely the problem. Even "shallow" completion candidates still go through the deep search stuff, so that return could stop before even depth=0 candidates have been processed.

The easy fix would be to finish processing the current queue before returning. Or maybe only finish the current queue if it is depth=0.

**Comment by findleyr** [comment]
Thanks @muirdm! We should guarantee that depth=0 stuff completes, in addition to fixing the performance regression.

**Comment by findleyr** [comment]
Oh my goodness, a huge chunk of time is spent in go/types.missingMethodReason, via `types.AssignableTo` and `types.ConvertibleTo`, which is totally wasted work...

Will file an issue if one does not already exist... (later)
