### ISSUE TITLE
unsafe: Slice does not panic on nil pointer when element size is 0

### ISSUE THREAD

**Issue by randall77** [golang/go#54092]
This program should panic:

```
package main

import "unsafe"

func main() {
	var p *struct{}
	_ = unsafe.Slice(p, 5)
}
```

From the `unsafe.Slice` docs:

> if ptr is nil and len is not zero, a run-time panic occurs.

A zero-sized element is a *very* special case here, so just a doc fix would be fine also.

@cuonglm @mdempsky

**Comment by cuonglm** [comment]
Isn't it https://github.com/golang/go/issues/46742?

**Comment by randall77** [comment]
That issue is about `Slice(nil, 0)`. This one is about `Slice(nil, >0)`. Which correctly panics if the element type has nonzero size. It's just when the element type is zero sized, no panic happens. We get a slice with {ptr:nil, len:5, cap:5}.

**Comment by cuonglm** [comment]
> That issue is about `Slice(nil, 0)`. This one is about `Slice(nil, >0)`. Which correctly panics if the element type has nonzero size. It's just when the element type is zero sized, no panic happens. We get a slice with {ptr:nil, len:5, cap:5}.
> 
> 
> 
> 
> 
> 

Ah right, it does panic with go.17, though https://go.dev/play/p/bpbEmh22qZA?v=goprev

**Comment by mdempsky** [comment]
Nice find. It looks like the issue is we rely on `size * len > -ptr` to detect this, but this fails when size is 0.

We can add an extra explicit `ptr == nil && len > 0` check, but that adds an extra branch on a code path we're trying to keep fast.

Maybe we can add it to the 64-bit entry point, and just force use of that function for zero-size types?

**Comment by randall77** [comment]
We could generate entirely different code for the elemsize==0 case.
