### ISSUE TITLE
reflect/type: reflect.FuncOf does not support more than 50 arguments 

### ISSUE THREAD

**Issue by super-harsh** [golang/go#54669]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/harsh/Library/Caches/go-build"
GOENV="/Users/harsh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/harsh/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/harsh/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/opt/homebrew/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mm/ky8h1xr924z0y0rmk45zwr3m0000gn/T/go-build872986808=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
https://go.dev/play/p/uiJRuATUUE6

### What did you expect to see?

Should allow up to 128 function args as per [funcTypeFixed128](https://github.com/golang/go/blob/master/src/reflect/type.go#L2055).

### What did you see instead?
Panic [here](https://github.com/golang/go/blob/master/src/reflect/type.go#L2080) with error below
`reflect.FuncOf does not support more than 50 arguments `

**Comment by robpike** [comment]
Seems like a feature, not a bug. :)

**Comment by theunrepentantgeek** [comment]
Under normal circumstances, I'd completely agree with you, and I think @super-harsh would as well. (I work on the same team.)

In our project, we are generating go structs based on API definitions that are outside our control.

When we use [gopter](https://github.com/leanovate/gopter) to test these structs, it panics - seemingly due to the inconsistency @super-harsh has identified:  
Why have specific support for 65-128 arguments (line [2055](https://github.com/golang/go/blob/8c8429fe4113b399355c11203e60e6b37bc823ba/src/reflect/type.go?rgh-link-date=2022-08-25T01%3A32%3A01Z#L2055)) only to panic a few lines later (line [2080](https://github.com/golang/go/blob/8c8429fe4113b399355c11203e60e6b37bc823ba/src/reflect/type.go?rgh-link-date=2022-08-25T01%3A32%3A01Z#L2080)) for any count over 50?

**Comment by mdempsky** [comment]
That `len(args) > 50` check does seem spurious.
