### ISSUE TITLE
x/pkgsite: add Affected Symbols section to vulnerability pages

### ISSUE THREAD

**Issue by julieqiu** [golang/go#54812]
For example, https://pkg.go.dev/vuln/GO-2021-0113 should have an "Affected Symbols" section explicitly listing these symbols from the ecosystem_specific.imports.symbols section:

"MatchStrings",
"MustParse",
"Parse",
"ParseAcceptLanguage"

**Comment by neild** [comment]
See https://github.com/golang/vulndb/issues/967 and https://pkg.go.dev/vuln/GO-2022-0646.

**Comment by hyangah** [comment]
Blocked by https://github.com/golang/go/issues/54992

**Comment by hyangah** [comment]
![Screen Shot 2022-09-10 at 9 53 21 AM](https://user-images.githubusercontent.com/4999471/189486521-ddc5d23a-d08f-4fde-9396-4c475b5c7f45.png)

I am afraid the table view can be a bit too crowed depending on the number of symbols.
Suggestions are welcome.

**Comment by julieqiu** [comment]
It might make sense to list the information vertically, as opposed to in a table. It is also likely that in many reports, all exported symbols will be affected.

/cc @jinhongy @fflewddur for UX input

We should also only list exported symbols on this page, and maybe link to the corresponding pkg.go.dev/<path>#<symbol> page (This is #52660). We compute [derived symbols](https://vuln.go.dev/ID/GO-2022-0236.json) when creating the reports, for this use case on pkgsite.

**Comment by hyangah** [comment]
@julieqiu Where is the derived symbols field? I don't see derived symbols in [the example data](https://vuln.go.dev/ID/GO-2022-0236.json) nor the osv package types (https://pkg.go.dev/golang.org/x/vuln/osv#EcosystemSpecificImport).

**Comment by hyangah** [comment]
This is cl/429678 [patchset 3](https://go-review.git.corp.google.com/c/pkgsite/+/429678/3/)

List affected symbols (exported only) in the next `<tr>`.
<img width="500" alt="Screen Shot 2022-09-13 at 9 04 41 PM" src="https://user-images.githubusercontent.com/4999471/190035964-98a1cc21-5cdf-4a23-a10e-dd83ac417de8.png">

When multiple packages are affected:

<img width="500" alt="Screen Shot 2022-09-13 at 9 05 07 PM" src="https://user-images.githubusercontent.com/4999471/190035970-33239619-4100-49c6-9745-812a96f7db0e.png">

When there are more than N (e.g. 5) symbols for a package, use `<details>` or javascript to show more.

<img width="500" alt="Screen Shot 2022-09-13 at 9 04 06 PM" src="https://user-images.githubusercontent.com/4999471/190035952-8ef1c0fd-d05a-4e45-b3a6-fd09452b466d.png">
<img width="500" alt="Screen Shot 2022-09-13 at 9 04 24 PM" src="https://user-images.githubusercontent.com/4999471/190035957-f6111dc8-7f50-4001-9b76-5fb3e5357dad.png">

**Comment by jinhongy** [comment]
I would recommend to use the table considered the case that we might have multiple packages with multiple affected symbols. We can make it clear even with huge amount of affected symbols with following adjustment:

- One symbol for each line
- Only show max symbols by default, it there are more, add a " # more" link behind
- Expand the rest of all affected symbols in the table if developers click on the more link
<img width="578" alt="image" src="https://user-images.githubusercontent.com/8199471/190686025-f1b14fda-e1a0-4163-ae28-4fc94e34de44.png">

**Comment by julieqiu** [comment]
Thanks @jinhongy! Would you mind sharing what the mobile design would look like? Here's the current mobile view: 

<img width="336" alt="Screen Shot 2022-09-16 at 12 31 57 PM" src="https://user-images.githubusercontent.com/5943521/190686695-8061b347-d3ab-4979-89d4-238219a00b6b.png">

**Comment by jinhongy** [comment]
Here is my recommendation for responsive table in mobile view
<img width="401" alt="image" src="https://user-images.githubusercontent.com/8199471/190689552-b33495d7-792f-4002-90f5-2f0d44d87ac9.png">

**Comment by hyangah** [comment]
Thanks @jinhongy 

In the [cl/429678 patchset 4](https://go-review.git.corp.google.com/c/pkgsite/+/429678/4), I made it to the three-column (Package, Versions, Symbols) table for wide screens, and made it similar to @jinhongy's mock for narrower screens. 
I hope use of grid gives us more flexibility.

To make it look more polished, I need help from @jamalc or @jinhongy who are more capable of js/css.

### Wide screen

<img src="https://user-images.githubusercontent.com/4999471/190874335-226b7846-18d2-4967-b2fc-d82eb05df87e.png" width=600></img>

* Differences from @jinhongy 's[ suggestion](https://github.com/golang/go/issues/54812#issuecomment-1249561689)
   - three columns instead of 4 columns: because there can be multiple version ranges.
   - versions before symbols: because IMO version range info is more important than individual symbol list.
   - use `<details>` instead of the delicate expansion feature: I hope someone more capable of CSS & JS handle the issue if we decide to show the first N.
   - print full package path only instead of the package name: **Need investigation**
   - didn't linkify symbols - that is https://github.com/golang/go/issues/52660   
   
### Mobile view
   
* Collapsed
<img src="https://user-images.githubusercontent.com/4999471/190874329-3961670e-8e5a-4b2a-a060-a24c4953ef04.png" width=300></img>

* Expanded
<img src="https://user-images.githubusercontent.com/4999471/190874325-7474412c-636b-4416-b7f1-3d5d811698d9.png" width=300></img>
