### ISSUE TITLE
cmd/link: runtime.firstmoduledata: missing xsym in relocation on AIX

### ISSUE THREAD

**Issue by cuonglm** [golang/go#54814]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
go run run.go -- fixedbugs/issue42032.go
```

### What did you expect to see?

Test passes

### What did you see instead?

Test failed: https://build.golang.org/log/fdb5399c8575237752fd316a7d8fa97dc712e5d6

**Comment by cuonglm** [comment]
cc @cherrymui @thanm

**Comment by bcmills** [comment]
(CC @golang/aix)

**Comment by cherrymui** [comment]
`go run issue42032.go` works on AIX. But the special "compile+link" recipe from test/run.go https://cs.opensource.google/go/go/+/master:test/run.go;l=1141 fails. The reason is that it doesn't pass the `-buildid` linker flag, yet we're adding a reference to`go:buildid` symbol (which assumes the symbol exists). Sending a CL to fix.
