### ISSUE TITLE
x/vuln: govulncheck should report vulnerabilities for all GOOS/GOARCH values 

### ISSUE THREAD

**Issue by jba** [golang/go#54841]
Running govulncheck on one platform shouldn't limit reports to vulnerabilities that apply to that platform. For example, running govulncheck on Linux should report Windows vulnerabilities as well.

We might want to have a flag that limits reports to just a subset of platforms, so users who don't care about Windows or WASM can get a more focused set of reports if they want.

**Comment by adamdecaf** [comment]
What about a `-platforms <comma-separated-list>` flag that could accept `all` or `linux,windows` values.

**Comment by hyangah** [comment]
@zpavlinovic If I run `govulncheck` on my macOS machine (without any `GOOS`, `GOARCH` overrides), after this fix, will it discover the callpaths  that affect only Windows, automatically? Or will this vulnerability get reported in the "Informational vulnerabilities" section (non-affecting vulnerabilities)?

**Comment by jba** [comment]
It will discover vulns that affect only Windows. They will be reported with
```
platforms: windows/amd64
```
so you can tell.

Imagine that you develop on Mac but deploy to Linux servers. We don't know that, but we don't want you to miss a vulnerability.

**Comment by hyangah** [comment]
To clarify my question - will it be in the "Affecting vulnerability" section that with call info or in the "Non-affecting vulnerability" section that without call info?

**Comment by zpavlinovic** [comment]
With this change, govulncheck will create vulnerability graphs as if all of the vulnerabilities apply to all of the platforms. When we present the vulnerability info in the end, then we will simply mention which specific platforms this vulnerability applies to.

I guess in theory it could happen that different underlying platforms can produce different compiled code, but I am not sure will that affect vulnerability detection in practice. I guess this mostly applies to the standard library?

**Comment by hyangah** [comment]
For example https://pkg.go.dev/vuln/GO-2022-0493 is a vulnerability in `golang.org/x/sys/unix` or `syscall` for unix. I guess users who run `govulnceck` on windows wouldn't hit this code path even though their cross-platform projects may be affected if they are built on unix platform.

Hmm, I just realized this vulnerability won't be even reported in the informational section since `golang.org/x/sys/unix` package won't be imported. Or is the "Informational vulnerability" section based on the module requirement graphs?

**Comment by zpavlinovic** [comment]
> For example https://pkg.go.dev/vuln/GO-2022-0493 is a vulnerability in `golang.org/x/sys/unix` or `syscall` for unix. I guess users who run `govulnceck` on windows wouldn't hit this code path even though their cross-platform projects may be affected if they are built on unix platform.
>

This was the behavior before. This issue is about showing them that path regardless of what platform they are using: we show them that path and then mention that it would be exercised on the windows platform.

We want to do this because, although we document everything, users still might run govulncheck on one platform during development where the vulnerability does not exist. That could give them a false sense of security if they also don't run govulncheck on other platforms for which some vulnerabilities do apply. Also, it is probably a better user experience doing things this way rather than the user running govulncheck on all possible platforms. 

> Hmm, I just realized this vulnerability won't be even reported in the informational section since `golang.org/x/sys/unix` package won't be imported. Or is the "Informational vulnerability" section based on the module requirement graphs?

It should be based on the package imports graph.
