### ISSUE TITLE
spec: document that `x[i,]` (trailing comma) is permitted

### ISSUE THREAD

**Issue by adonovan** [golang/go#55007]
The spec does not seem to permit a comma after the index in an expression such as `a[i,]`, yet both the compiler and the go/parser package permit it, presumably because without type information it's impossible to distinguish an array index expression `a[i,]` from a parameterized type such as `M[K,V,]` where a comma is permitted after the list of instantiating types. The spec should probably be updated to say that a comma is allowed but ignored. The alternative, of having the type checker allow the comma in a type but reject it in a term, would require recording the presence of the comma in the syntax tree, which seems undesirable.

https://go.dev/play/p/JcES0elTHiG

**Comment by griesemer** [comment]
Your analysis is correct. Array/slice index expressions do not permit a trailing comma, but instantiations do because they follow the syntax of (type) parameter lists, which generally allow a training comma.
 
The other approach is to consider an expression of the form `x[t,]` (with a trailing comma) always as instantiation, i.e., a trailing comma indicates that we do not have an array/slice index expression.

Related: https://twitter.com/robertgriesemer/status/1283142956153573376

**Comment by griesemer** [comment]
@ianlancetaylor agrees that we should not report a syntax error during type checking. I will update the spec accordingly. Notably, `gofmt` will remove any such trailing commas.
