### ISSUE TITLE
x/tools/gopls/internal/regtest/modfile: TestUnknownRevision failure with `All files must be saved first`

### ISSUE THREAD

**Issue by bcmills** [golang/go#55070]
```
#!watchflakes
post <- pkg == "golang.org/x/tools/gopls/internal/regtest/modfile" && 
        test == "TestUnknownRevision" && `All files must be saved first`
```

`greplogs -l -e 'FAIL: TestUnknownRevision.*(?:\n\s+.*)*All files must be saved first' --since=2022-02-01`
[2022-09-07T18:17:13-3ee1710-dfdf551/linux-s390x-ibm](https://build.golang.org/log/05f4e49bc3f6294fedb13f6cc4ddb35864a550be)
[2022-09-07T16:39:44-dd1bab2-027ff3f/linux-s390x-ibm](https://build.golang.org/log/928900ef148d503da168e362f8fa3b5c34220a17)

**Comment by findleyr** [comment]
I see the race in this test: the test may advance to applying code actions before changes are processed (because there is both a didChange and didSave notification being processed, and we proceed once *either* of them is done, not both).

I have an in-progress improvement to our expectations that should make it easy to fix this.

**Comment by findleyr** [comment]
Confusingly, there was a second bug (root caused in https://go.dev/cl/461418) which I believe was causing *the same symptom*, albeit with less frequency and only on s390x, which must have low clock precision.

I'm pretty confident in the fix.
