### ISSUE TITLE
gerrit, x/review/git-codereview: give may-forge-author permission to approvers

### ISSUE THREAD

**Issue by cherrymui** [golang/go#55841]
Currently, on Gerrit, the "Rebase" and "cherry-pick" buttons on the Gerrit UI require may-forge-author permission, if you're not the author of the original CL. This sometimes causes inconvenience. We are considering giving all Gerrit approvers (who can +2 CLs) may-forge-author permission.

A concern is that one might accidentally mail a CL that overwrites someone else's pending CL. To prevent that we're considering making the `git-codereview` tool check the author before mailing the CL, and adding a flag so if one actually needs to upload a forged CL one can use `git mail -forge`.

cc @golang/release @rsc

**Comment by mvdan** [comment]
I would love to be able to rebase CLs. In particular, when an older CL was reviewed and ready, but I want to re-test it on master before landing it.

**Comment by heschi** [comment]
It turns out that our `may-forge-author` group conflates two permissions, and I didn't realize it:
- The `Forge Author Identity` permission, which allows exactly what it says: setting the Author field to something that isn't the uploader. This seems pretty harmless; Author and Uploader are right next to each other in the UI, so I don't see much risk of confusion.
- `Add Patch Set` on all CLs, which allows someone to upload a patchset to someone else's CL. Presumably they also need `Forge Author Identity` to do this. This is the dangerous one.

It seems to me that there's no reason not to grant `Forge Author Identity` to all approvers right now - it makes cherrypicks easier and has no downsides I can see.

That still leaves `Add Patch Set`. We can make a decision about that later. For my reference, are there use cases other than doing trivial rebases? The Gerrit team is working on improvements for that specific case that don't open up misuse concerns.

**Comment by heschi** [comment]
I've granted `Forge Author Identity` to the approvers group.

**Comment by heschi** [comment]
In an effort to remove unused permissions, I cleared out `may-forge-author`.

@FiloSottile, you were the only active non-Googler in the group as far as I could tell from a quick glance. Would you like me to add you back?

**Comment by FiloSottile** [comment]
I do use `Add Patch Set` for a couple of purposes: occasionally I pick up an old CL from the review queue, and fix it up and get it reviewed by someone else without breaking the review history; and I often clean up the commit message before submitting. They're both ways to cut down on review round-trips, so not critical but convenient. The former I could also do less elegantly by abandoning and opening a new CL, the latter not so much.

**Comment by heschi** [comment]
Added.

**Comment by heschi** [comment]
The Gerrit team has launched support for trivial rebases without special permissions; you can see an example of @dmitshur using it at https://go-review.git.corp.google.com/c/build/+/477775/6#message-6beb8aa86e9796a603ef6de08318fa52b3ca80ac.

I believe that takes care of enough of the use cases for `Add Patch Set` that we can consider this fixed. I'll leave the Gerrit group alone since there are only 4 people in it.
