### ISSUE TITLE
x/tools/imports: Process do not remove used but duplicated imports

### ISSUE THREAD

**Issue by Antonboom** [golang/go#55982]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

https://go.dev/play/p/QEVFgl-HPhb

### What did you expect to see?

```go
import (
    "fmt"
)
```
For all cases.

### What did you see instead?

```go
import (
    "fmt"
)
```

```go
import (
    "fmt"

    "fmt"
)
```

```go
import (
    "fmt"

    "fmt"

    "fmt"
)
```

```go
import (
    "fmt"

    "fmt"

    "fmt"
)
```

P.S. Related to https://github.com/golang/go/issues/37689, because fix for my issue is to add import aliases.

**Comment by dmitshur** [comment]
This looks related to but not the same as #45398.

CC @golang/tools-team.

**Comment by findleyr** [comment]
I don't think this is related to #45398. The issue here is that these are in multiple import groups, and goimports (as a principle) processes import groups separately.

Note that if the duplicate imports are in the same group (as below) they are cleaned up as expected (as below):

```
import (
	"fmt"
	"fmt"
)
```

CC @heschi to confirm that this is expected behavior.

**Comment by heschi** [comment]
Correct AFAIK.

**Comment by findleyr** [comment]
Thanks. Closing this as WAI.
