### ISSUE TITLE
cmd/compile: cannot convert (constant 10000 of type float64) to type int64

### ISSUE THREAD

**Issue by NOMORECOFFEE** [golang/go#56220]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
package main

import (
	"fmt"
)

func main() {
	v := int64((float64(0.03) - float64(0.02)) * 1_000_000)
	fmt.Println(v)
}
```

https://go.dev/play/p/V0KH5qKf6u4

### What did you expect to see?

10000

### What did you see instead?

cannot convert (float64(0.03) - float64(0.02)) * 1_000_000 (constant 10000 of type float64) to type int64

**Comment by randall77** [comment]
The problem is that `(float64(0.03) - float64(0.02)) * 1_000_000` is not an integer. `0.03` is not representable exactly as a `float64`, so the total expression is not *exactly* an integer. That's what the compiler is complaining about.
The error message could certainly be better.
Note that `(0.03 - 0.02) * 1_000_000` does work, because the compiler maintains many more significant digits than a `float64` does.
