### ISSUE TITLE
os: Consider providing a VFS layer

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#5636]
<pre>We have various different VFS layers in different programs, such as
cmd/godoc/filesystem.go.  Can we have the os package provide a VFS layer?  Or can we
provide a vfs package that wraps the os package?  Or something else to provide a simple
unified approach?</pre>

**Comment by rsc** [comment]
@robpike and I worked out a design for a general file system interface for Go. I've posted a draft design doc, video, and code (links below). Instead of comments on this issue, please use the Reddit Q&A for comments on this specific draft design - Reddit threads and scales discussions better than GitHub does. Thanks!

Video: https://golang.org/s/draft-iofs-video
Design: https://golang.org/s/draft-iofs-design
Q&A: https://golang.org/s/draft-iofs-reddit
Code: https://golang.org/s/draft-iofs-code

**Comment by rsc** [comment]
I've filed #41190 to propose accepting the draft design mentioned in my previous comment.
I am going to close this issue as superseded by that one.
