### ISSUE TITLE
text/template: new keywords (e.g. break, continue) breaks older working programs [1.19 backport]

### ISSUE THREAD

**Issue by bep** [golang/go#56591]
Backport rationale; a “serious” problem is one that prevents a program from working at all.

See #56538

**Comment by eliben** [comment]
I would vote against packporting in this case.

Rationale: @bep's is the only report we have of this issue, and even in their case the problem didn't actually manifest but was foreseen for future keywords like `return`. The problem is very easy to work around if it occurs (rename function to be something other than `break` or `continue`, which are very untypical function names in the first place)

In addition, backporting this CL would be tricky because the template lexer was rewritten by @robpike during the recent cycle to remove concurrency. The original CL that introduced the problem was fixing a race condition, and the fix for https://github.com/golang/go/issues/56538 could be simple because there are no longer concurrency issues in master. So this wouldn't be a straightforward merge fix to 1.19 - we'd have to figure out how to make the fix while still avoiding the race condition in the original code. I don't think it's worth the effort.

**Comment by mknyszek** [comment]
Given that we haven't heard any other reports of this issue, and the fix is complex, we're deciding not to backport this. If we start getting reports we can reconsider. Closing for now.
