### ISSUE TITLE
x/vuln: panic: runtime error: invalid memory address or nil pointer dereference with golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe/cmd/govulncheck/print.go:40 +0x3f

### ISSUE THREAD

**Issue by jerome-laforge** [golang/go#56689]
```
go install -trimpath golang.org/x/vuln/cmd/govulncheck@latest
govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7da49f]

goroutine 1 [running]:
main.printText(0x0, 0x0, 0x1)
        golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe/cmd/govulncheck/print.go:40 +0x3f
main.doGovulncheck({0xc000024050?, 0x1, 0x1}, 0x1)
        golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe/cmd/govulncheck/main.go:138 +0x3a5
main.main()
        golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe/cmd/govulncheck/main.go:69 +0x127
```

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
yes

### What operating system and processor architecture are you using (`go env`)?
$ go env

GOHOSTARCH="amd64"
GOHOSTOS="linux"

**Comment by mknyszek** [comment]
CC @golang/vulndb

**Comment by timothy-king** [comment]
@jerome-laforge I cannot reproduce the above error. I think we would need more details about the directory this is being run in to do this. In case you cannot provide more details, I have spotted a candidate bug that could cause this. You can try out the patch in  https://go.dev/cl/449675 and let us know how that goes. If this is it, you will just get a better error message instead of a nil pointer dereference.

**Comment by zpavlinovic** [comment]
The patch is now in, please let us know if it solves the problem.

**Comment by jerome-laforge** [comment]
Thanks, the problem is fixed.
