### ISSUE TITLE
cmd/go: document GOROOT/bin/go PATH entry for `go test` and `go generate`

### ISSUE THREAD

**Issue by bcmills** [golang/go#57050]
[CL 404134](https://go.dev/cl/404134) (in Go 1.19) changed `go test` and `go generate` to always place `GOROOT/bin` at the beginning of the `PATH` list for the subprocess.

I added a release note for it (in [CL 409176](https://go.dev/cl/409176)), but forget to update the documentation for the actual commands. It should be mentioned explicitly in the documentation for [`go test`](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/test/test.go;l=50-166;drc=575964d42c7b3001c09f2676d0ee9d520debb5eb) and [`go generate`](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/generate/generate.go;l=36-160;drc=c6be7103a5ab8cd45e08d822efa24da4fd88b9c5).

**Comment by shogohida** [comment]
Hi @bcmills, can I work on this? I assume I need to update the documentation in these files.

https://github.com/golang/go/blob/master/src/cmd/go/internal/generate/generate.go
https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go

**Comment by dmitshur** [comment]
@gopherbot Please consider this as a backport to Go 1.20 and 1.19.

This is a documentation-only fix to document a Go 1.19 feature added to `go test` and `go generate`. It'll be easier for users who wish to rely on it to do so when it's documented, and avoids confusion about it otherwise only being documented in Go 1.21 onwards.
(I'm happy to help with preparing backport CLs if approved.)
