### ISSUE TITLE
spec: constraint type inference for struct fields

### ISSUE THREAD

**Issue by iangudger** [golang/go#57270]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```go
type Element[T any] interface {
	*T
}

type Entry[T any, U Element[T]] struct{}

type testEntry struct {
	Entry[testEntry]
}
```

https://go.dev/play/p/RbzMxIySi3f

### What did you expect to see?
Compiles.

### What did you see instead?
```
./prog.go:10:2: got 1 arguments but 2 type parameters
```

If we modify the code above to the following, it compiles:
```go
type Element[T any] interface {
	*T
}

type Entry[T any, U Element[T]] struct{}

type testEntry struct {
	Entry[testEntry, *testEntry]
}
```

https://go.dev/play/p/taePA8Kizz1

**Comment by griesemer** [comment]
The issue here is not missing inference for struct fields but missing type inference for generic types (Entry is a generic type). If Entry is a generic function, type inference does work ([adjusted example](https://go.dev/play/p/n3nRWj6HC31)).

We don't do type inference for types because it is significantly more complex than type inference for functions: generic types may refer to themselves recursively in ways that may influence type inference. We don't have a good understanding what that means.

We are not planning to do this any time soon, if at all. In any case, it would require a thorough proposal. Closing this issue.
