### ISSUE TITLE
cmd/link: error building standard lib using -buildmode=shared Go 1.20rc1

### ISSUE THREAD

**Issue by derekparker** [golang/go#57334]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, it does not reproduce with the latest 1.19.x release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deparker/.cache/go-build"
GOENV="/home/deparker/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/deparker/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/deparker/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/deparker/Code/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/deparker/Code/goroot/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1198116115=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

pushd src
./make.bash
popd
GOROOT=$(pwd) ./bin/go install -buildmode=shared -v -x std

### What did you expect to see?

No error building shared stdlib.

### What did you see instead?

https://gist.github.com/derekparker/d391d9bb492f9ee611c8ad136e813ab3

**Comment by derekparker** [comment]
cc @alexsaezm (found this issue while building Go 1.20rc1 for Fedora)

cc @ianlancetaylor @randall77 @heschi

**Comment by ianlancetaylor** [comment]
CC @cherrymui @thanm

**Comment by cherrymui** [comment]
> go install -buildmode=shared -v -x std

This command includes _all_ packages in std, in particular, both `runtime/race/internal/amd64v1` and `runtime/race/internal/amd64v3`. Both of these packages contain the race syso, so both syso's get into the link, causing duplicated symbols. This seem all but the last error.

In normal build, only the `runtime/race` package is directly imported, and one of the internal packages is actually imported based on the GOAMD64 setting. But this package selection doesn't work for `go install -buildmode=shared std`.

I wonder if `go install -buildmode=shared std` could start with all user-importable packages in std and only pull in internal packages on demand...

> /usr/bin/ld: /tmp/go-link-2738326382/go.o: relocation R_X86_64_PC32 against undefined symbol `runtime_test.callerStartLine' can not be used when making a shared object; recompile with -fPIC

The last error is due to a package that is used only in test, and calls a function defined in test. Again building `std` includes this package, but not the function defined in test. We could probably work around this one. Pulling only user-importable part of std would help this as well.

**Comment by ianlancetaylor** [comment]
CC @bcmills

**Comment by bcmills** [comment]
For the `runtime/race/internal` packages, would it suffice to add `go:build` constraints to the `doc.go` files so that only one or the other package actually exists? (Or does the package exist because of the `syso` files even if all of the `.go` files are constrained away?)

**Comment by bcmills** [comment]
For the test-only package, does it suffice to move that package inside a `testdata` directory? It will probably still be importable...

**Comment by cherrymui** [comment]
> would it suffice to add go:build constraints to the doc.go files so that only one or the other package actually exists?

Thanks. This works.

For the other issue I worked around it using a function pointer.
