### ISSUE TITLE
testing: fix missing preposition in docstring

### ISSUE THREAD

**Issue by AndreyBozhko** [golang/go#57389]
The phrase in docstring here https://github.com/golang/go/blob/0b2ad1d815ea8967c49b32d848b2992d0c588d88/src/testing/testing.go#L16 reads
```
... file whose name ends _test.go ...
```
which instead should probably say
```
... file whose name ends with _test.go ...
```

**Comment by mvdan** [comment]
Thanks. Want to send a patch? There's no need to track this change in an issue. See https://go.dev/doc/contribute.

**Comment by robpike** [comment]
It's also fine as is, no fix needed.

**Comment by mvdan** [comment]
@robpike do you have a link to an explanation, or a name for this form of omitting "with"?

All I can say as a non-native speaker is that I had never seen it before, so I'd definitely find the doc easier to read with the explicit "with".

**Comment by robpike** [comment]
It's idiomatic English. I probably wrote that sentence myself. The preposition is either assumed or unnecessary. Putting it is correct, but so is leaving it out. To me it sounds right. But if it's bothersome to some, change it.

If I were asked to make it clearer, instead of adding the preposition I would likely add quotes:

 ```
// To write a new test suite, create a file whose name ends "_test.go" that 
```

**Comment by mvdan** [comment]
Ah, I see what you mean. I agree that the quotes make it clearer as well.

**Comment by lovelytingy** [comment]
Using the word "with" after "ends" clarifies that it is the name of the file that ends with the specified string, rather than the file itself.

In general, it is important to use precise and clear language in order to avoid misunderstandings. In this case, using the word "with" after "ends" helps to make the intended meaning clear.


I am non-native speaker. I find the string easier with the explicit "with".

**Comment by AndreyBozhko** [comment]
Thanks, I will send a patch then. It would also make the language consistent with what is used in other places in the codebase - one example is here https://github.com/golang/go/blob/a5a47442502e8e42b390f458f8f91dea3de872eb/src/cmd/go/internal/get/get.go#L212.
