### ISSUE TITLE
x/website/_content/blog/vuln: instructions should mention where govulncheck will be installed

### ISSUE THREAD

**Issue by fflewddur** [golang/go#57412]
On https://go.dev/blog/vuln we include instructions for installing govulncheck, but don't mention where this will install. We recently received feedback via our govulncheck survey from someone who installed govulncheck correctly, but got a 'command not found' error when trying to run it. They expected it to be in /usr/local, since this is where Go itself was installed, and it looks like they hadn't yet added ~/go/bin to PATH.

**Comment by dr2chase** [comment]
CC @golang/vulndb

**Comment by zpavlinovic** [comment]
Should we just effectively copy text from [here](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies)

```
govulncheck is installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set
```

**Comment by ianthehat** [comment]
I think we would be better off linking to that section from the blog, with some text like "See <here> for details of what the go install command does and where it puts the binary"
Otherwise we run the risk of the text going out of sync, and we don't reinforce that this is a normal go install command that the developers need to understand for everything else in the ecosystem as well.
