### ISSUE TITLE
build: test cleanup wrt wg.Done

### ISSUE THREAD

**Issue by chai2010** [golang/go#5746]
<pre>just like this test example:

func TestFailed(t *testing.T) {
    var wg sync.WaitGroup
    for i := 0; i &lt; 2; i++ {
        wg.Add(1)
        go func(id int) {
            // defer wg.Done()
            t.Fatalf(&quot;TestFailed: id = %v\n&quot;, id)
            wg.Done()
        }(i)
    }
    wg.Wait()
}

go test
fatal error: all goroutines are asleep - deadlock!

---

When the t.Fatalf panic, goroutine can't reach wg.Done().
So wg.Wait() deadlock!

There are lots of similar iusses, eg:
<a href="http://golang.org/src/pkg/net/rpc/server_test.go?s=12968:13320#L548">http://golang.org/src/pkg/net/rpc/server_test.go?s=12968:13320#L548</a>

If the issue verified, i can submit patch.</pre>

**Comment by odeke-em** [comment]
Thank you for this bug report @chai2010 and everyone for responding! I examined this issue last week and sent [CL 212920](https://go-review.googlesource.com/c/tools/+/212920) for a go vet analysis pass that will be added in Go1.15 and has been merge into x/tools currently. It also found 3 misuses in the standard library as per this [CL 213097](https://go-review.googlesource.com/c/go/+/213097/) 

I am going to close this issue since it was more of a question that was answered in the replies, it is also now answered in the documents for testing.T and testing.B but also as mentioned above, go vet will start flagging those cases in >=Go1.15.

Thanks y'all and happy New Year!
