### ISSUE TITLE
x/playground: selecting Go dev branch uses arbitrary older version

### ISSUE THREAD

**Issue by rittneje** [golang/go#57495]
### What did you do?

Ran a sample program to get the version that the playground uses for "Go dev branch" (aka gotip). https://go.dev/play/p/V9tVDS4adLm?v=gotip

### What did you expect to see?

I expected to see it report some reasonably recent commit of the master branch.

### What did you see instead?

It reported commit 537c4354cb, which is from October.

**Comment by dmitshur** [comment]
Thanks for reporting.

The 1.19 and 1.18 branches may also be affected: running that program with Go 1.19/Go 1.18 in the dropdown prints go1.19.2/go1.18.8 (while Go 1.19.4 and 1.18.9 are the latest minor releases right now).

CC @toothrot, @findleyr.

**Comment by goferHiro** [comment]
![image](https://user-images.githubusercontent.com/103487904/209910102-b1734a99-116d-4bdb-8f01-6bb5cbbfc6f6.png)

Just checked the recent commits
![image](https://user-images.githubusercontent.com/103487904/209910132-96647564-dcd7-4ae8-b1c9-80b5a1c01880.png)

**Comment by rittneje** [comment]
> The is discrepancy b/w the timing of the commits as well. In playground its reported as Oct 28 but in git log its july 11

@goferHiro July 11 is the author date. The commit date is July 28 (UTC), which aligns with what `runtime.Version()` is reporting. See [here](https://stackoverflow.com/questions/11856983/why-is-git-authordate-different-from-commitdate) for more details on the distinction.

**Comment by goferHiro** [comment]
@rittneje  Thanks for the clarification

**Comment by findleyr** [comment]
Looked at this today. The 1.18 and 1.19 deployment failures were unrelated (we hit a GCP resource limit). This is now fixed, and both are updated.

The tip failure appears to be related to https://go.dev/cl/432535. My knowledge of this is vague, but since builds don't share GOCACHE I think they're all rebuilding std, and health checks (which do a build) are timing out. Presumably we need to add a shared cache for the build.

CC @bcmills @matloob

**Comment by findleyr** [comment]
This is now fixed.
