### ISSUE TITLE
x/tools/gopls: filter intermediate test variants when resolving package for file

### ISSUE THREAD

**Issue by findleyr** [golang/go#57795]
https://go.dev/cl/455615 simplified our package APIs, but dropped the explicit filtering of intermediate test variants from `snapshot.PackageForFile`.

I believe as a result of this change, we may get an intermediate test variant at the call sites where we previously would not. This can cause needless type-checking.

Not yet released, but we must address this before v0.12.0

CC @adonovan

**Comment by findleyr** [comment]
This is important to fix, and should be straightforward.

**Comment by adonovan** [comment]
FWIW I just audited all calls to MetadataForFile and found that all but one of them either:
- discard ITVs from the result;
- compute rdeps and then discard ITVs (see typeCheckReverseDependencies in rename.go);
- use only metas[0], the narrowest variant; or
- use the widest variant but don't type-check it (see packageReferences in references.go).

The only caller that does not is implementations, which acknowledges in a comment that it wants test variants, though it is not explicit about whether it means ordinary or intermediate.

I'm struggling to remember why we would ever want to care about ITVs, if we're happy to disregard the possible cross-package effects such as changes to selectors caused by method declarations in the ordinary test variant.
