### ISSUE TITLE
x/website: "Run" buttons don't work

### ISSUE THREAD

**Issue by robpike** [golang/go#58013]
Go to a blog page - say https://go.dev/blog/constants - and try the Run button on an example. When I do, I always get this error, albeit with more color:

```
package play: build constraints exclude all Go files in /tmp/sandbox497940979

Go build failed.
```

I am mystified what constraints would make all examples fail to run, but it's a shame that the examples have become unrunnable.

**Comment by ianlancetaylor** [comment]
I don't know this code but I wonder if this could be due to https://go.dev/cl/388016.  The files in question all have `// +build OMIT`.  I see some handling of strings containing "OMIT" in x/website/internal/web, and it seems possible that that handling is being skipped by the singleProxy code.

CC @jamalc

**Comment by seankhliao** [comment]
is this still broken? seems to work for me now

**Comment by robpike** [comment]
Working for me too. Did someone fix something?
