### ISSUE TITLE
cmd/compile: reduce PGO profile processing overhead

### ISSUE THREAD

**Issue by prattmic** [golang/go#58102]
Currently, each cmd/compile invocation parses the full PGO pprof profile, builds a full weight graph, and then determines what is relevant to that package. This is a lot of work that scales poorly with the size of the profile and the size of the build (number of packages). For particularly large profiles, this can lead to extremely long build times.

Follow-up to #55022.

cc @cherrymui @aclements

**Comment by cherrymui** [comment]
#62400 has a prototype that significantly reduce build time overhead for PGO. It is too late to be integrated in for Go 1.22. Bump to Go 1.23.

**Comment by CAFxX** [comment]
Just as a practical example of this in the wild: I just tried to pull a production profile (from GCP cloud profiler; 16MB gzip compressed, 60MB uncompressed) of one of our services and drop it into its repo as `default.pgo` (we are currently on go 1.21).

This caused the build time (GCP Cloudbuild, e2-highcpu-32) to skyrocket from 2.5 minutes to... 34 minutes (before being killed, presumably due to OOM, since the build timeout is 60 minutes).

It's clear we won't really be able to enable PGO until the PGO build overhead is curbed to reasonable levels.

**Comment by CAFxX** [comment]
Will try as soon as I have a bit of more time to dedicate. 

A couple of further notes:

- Using an uncompressed profile seems to already reduce CPU usage quite a bit. Haven't checked the CL, but if it doesn't do this already it may be a good idea to somehow avoid decompressing (and maybe also parsing) the profile for each package being compiled.
- In general it seems like PGO significantly increases peak memory usage during compilation. Maybe the build driver should dial down the number of parallel builds if it detects that there is not enough free memory and/or if children are getting killed because of OOM (similar to what can be done with [`parallel`](https://www.gnu.org/software/parallel/man.html): see `--term-seq`, `--retries`, `--memsuspend`, and `-memfree`)
