### ISSUE TITLE
x/build: add misc-compile TryBots for x/ repos

### ISSUE THREAD

**Issue by bcmills** [golang/go#58163]
Various recent changes in the `x/tools` have broken the build for various second-class ports (`aix`, `plan9`, `solaris`) without being detected in TryBot runs.

Given that tests can be cross-compiled using `go test -c` (albeit currently a bit awkwardly because of #58162), we should enable the `misc-compile` TryBots for the `x` repos for all platforms that support internal linking.

(The platforms that require external linking do not currently have `misc-compile` builders at all — that's #25963.)

**Comment by bcmills** [comment]
(CC @golang/release)

**Comment by mknyszek** [comment]
Since I'm currently on rotation I'll try to get to this this week, but no promises since I'm working on the release.

**Comment by dmitshur** [comment]
> The logic around `misc-compile` builders is unfortunately kind of hairy. There's every indication that it should be already running for x/ repo trybots (albeit failing by trying to run `buildall.bash`), but there's basically a deeply buried exception for any builder that uses `buildall.bash`.

Yep.

> I think I figured out how to fix that (just get rid of the exception), then the coordinator just needs to notice the `CompileOnly` flag on the builder and do the right thing.

Yeah, in `runSubrepoTests`.

> There's one remaining question after that and it's how to plumb the build targets through. [...] I guess that just means another field to the builder configuration?

This question really comes up because misc-compile trybots are the only builder types that try to multiple GOOS/GOARCH builds in one. In other ways, BuildConfig is always one test execution of an environment, so its `env []string` (one environment) field is enough. But here, you really want multiple environments. To illustrate this point—consider that if the misc-compile x repo trybots were to handle one GOOS/GOARCH port, it'd be sufficient to just set GOOS/GOARCH env vars in the `BuildConfig.env` field.

To keep the multiple-builds-per-one-BuildConfig property in the x repo CompileOnly trybots, I think adding another field to the builder configuration is reasonable.

Then runSubrepoTests can notice it in addition to CompileOnly and perform multiple GOOS/GOARCH compiles in one. You could technically avoiding new fields by instead using a special env var, for example, `GO_TEST_COMPILE_ONLY_PORTS=dragonfly-amd64,linux-loong64`, but I doubt that's better than a new field since it still needs to be handled specially.

**Comment by prattmic** [comment]
> There's one remaining question after that and it's how to plumb the build targets through. Currently buildall.bash just has it installed as one of its arguments, but we can't do that for go test -c.

You also need extra work to make sure any nested modules are built. e.g., `./...` or `golang.org/x/tools/...` won't build `golang.org/x/tools/gopls` because it is a nested module. You either need to  run `go test` inside each module, or create a workspace including all nested modules (`go work use -r .`).

**Comment by mknyszek** [comment]
I think everything is hooked up properly, except `go test -c` can't handle multiple packages. #15513 actually totally solves this by allowing for `go test -c -o /dev/null` but although it's been accepted, it hasn't been implemented. :(

Would it be sufficient to just say `go build -o /dev/null` for now, since that should just work? It doesn't test that test packages compile, which is unfortunate, but the workaround is considerably more complex, since every package needs to be manually listed with a separate `go test -c` invocation. (I can make this work if it's critical, but it adds more complexity to the coordinator.)

**Comment by mknyszek** [comment]
Also @dmitshur, as discussed offline, I did actually break up the `misc-compile` builders as well. Still not totally sure it's desirable because of the extra VMs started (although they're each shorter-lived than before), but it does make the code a little easier to reason about.

**Comment by mknyszek** [comment]
@prattmic pointed out to me that `go test -c` alone might not be sufficient either, because it'll miss packages that don't have tests. `go test` kind of has that problem in general.

As a workaround to the fact that `go test -c` only works with a single package, I also considered `go test -exec` where we pass some dummy script that never actually invokes the binary.

**Comment by mknyszek** [comment]
@prattmic points out I can just pass `-exec /bin/true`. I think that actually fully works around the `go test -c` issue.

**Comment by mknyszek** [comment]
OK actually, it looks like `go test -exec /bin/true` is sufficient. Even packages without tests are built and vetted.

**Comment by dmitshur** [comment]
Provided /bin/true is present on all the platforms to be compile-checked, or special handling of any platforms that need it.
