### ISSUE TITLE
proposal: Unable to test login with OTP affected/package: testing

### ISSUE THREAD

**Issue by wade-welles** [golang/go#58160]
Right now, any fmt.ScanX() style function will be skipped over during testing. This makes it pretty much impossible to test a login with an OTP without needing to include some sort of TOTP/HOTP library to convert an example MFA key into its current OTP. 

Is there any specific reason to not simply allow the ability to input during a test? I understand that in most conditions you would want to automate the running of tests for CI but in those situations the HOTP/TOTP library could be included.

Preventing these functions from working affect smaller programs and projects using MFA. Enabling it wouldn't affect functionality either. 

If there is a specific reason why this is not allowed, I would not mind knowing, and you can feel free to close this after an explanation is provided; it will likely help others too since this is not an entirely uncommon problem.

**Comment by seankhliao** [comment]
There are many contexts where stdin may not be available, eg parallel tests. It's better for it to be consistent and reproducible rather than as an alternative command runner.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
