### ISSUE TITLE
path/filepath: Clean changed in Go 1.20

### ISSUE THREAD

**Issue by bep** [golang/go#58348]
I have some GitHub action tests that started to fail on Windows after I bumped the build matrix to Go 1.20.

I have distilled the issue into this small repo: https://github.com/bep/go120winpathregression

```
--- FAIL: TestTo (0.00s)
    lib_test.go:12: 
        error:
          values are not equal
        got:
          "\\\\\\\\post"
        want:
          "\\post"
        stack:
          D:/a/go[12](https://github.com/bep/go120winpathregression/actions/runs/4102512994/jobs/7075566395#step:11:13)0winpathregression/go120winpathregression/lib_test.go:12
            c.Assert(Clean("////post/////"), qt.Equals, filepath.FromSlash("/post"))
```

I have looked closely in the release notes for Go 1.20 about this, but that does not mention this change. Also, the GoDoc for `filepath.Clean` is pretty clear about what happens to "multiple Separator elements":

> 1. Replace multiple Separator elements with a single one.

**Comment by seankhliao** [comment]
cc @neild regression from #56336 ?

**Comment by bep** [comment]
Looking back at the original failing test, I don't see why that should not use `path.Clean`, so I'm going to fix that, but I still think the above test case looks like a regression (esp. considering the documentation).

**Comment by neild** [comment]
`filepath.Clean` doesn't clean the volume name component of Windows paths. This is longstanding behavior:

```
filepath.Clean(`\\a\b\\c`) = `\\a\b\c`
```

I see that this isn't documented, however. It should be.

As of Go 1.20, we do a better job of identifying volume names, and we're more lax about accepting invalid volume names. `\\\\post` is not a valid Windows path, because it contains empty host and share components (the first two path components after a leading `\\`). Previously, `filepath` considered this to have a zero-length volume name component; it now considers it to have the (invalid) volume name `\\\\`.

I don't think this is a regression, since `filepath.Clean` has always (or at least long) preserved a `\\` prefix in valid Windows filenames.

But we should fix the docs.

**Comment by bhavyastar** [comment]
Hey @bep @bcmills , Can I work on this issue?

**Comment by ianlancetaylor** [comment]
@bhavyastar Better documentation is always welcome.  Thanks.
