### ISSUE TITLE
runtime: some linkname signatures do not match

### ISSUE THREAD

**Issue by amscanne** [golang/go#58440]
The two affected functions are:

* internal/poll.runtime_pollWaitCanceled
* sync/atomic.runtime_procPin

### What version of Go are you using (`go version`)?

go1.19rc2

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

This was identified as an error by a [linkname analyzer](https://github.com/google/gvisor/commit/1b265d1fb49b51af62d7d79768cc376f131c76f6). A [patch](https://go-review.git.corp.google.com/c/go/+/466615) was posted, and a suggestion was made to file a specific bug.

### What did you expect to see?

I expected signatures of these functions to match. If they did not, they should at least have the same shape (i.e. they may intentionally mismatch as in the case of runtime.ifaceI2E).

### What did you see instead?

They were identical except return values (or lack thereof). This could cause problems with assumptions regarding the stack layout for those calls.

**Comment by prattmic** [comment]
To add more detail:

`internal/poll.runtime_pollWaitCanceled` had an extra return value in the calling package. This means callers reserved an extra stack slot for the return value which the function would not set. This shouldn't cause problems unless the callers tried to use the non-existent return value (they don't). This bug was introduced in https://go.dev/cl/10485043 (the CL adding the symbol).

`sync/atomic.runtime_procPin` is missing a return value in the calling package. This means that callers _do not_ reserve a stack slot for the return value, and the function is clobbering some other stack slot. This is scary, though as far as I know it has never caused problems [1]. This bug was introduced in https://go.dev/cl/136710045 (the CL adding the linkname).

[1] I suspect, though I haven't verified, that we are clobbering the stack slot for [`typ`](https://cs.opensource.google/go/go/+/master:src/sync/atomic/value.go;l=97;drc=8fb9565832e6dbacaaa057ffabc251a9341f8d23) which is already dead by the call to `procPin`.

**Comment by prattmic** [comment]
These are fixed in https://go.dev/cl/466615, which is already merged.

**Comment by prattmic** [comment]
@gopherbot please open a backport to 1.20 and 1.19. This bug has the opportunity to cause memory corruption in combination with other seemingly innocuous changes. We should backport for safety, as the fix is trivial.

**Comment by amscanne** [comment]
A new instance of this bug was just introduces with the metrics functionality. It actually saves a pointer to a function of the wrong type, but presumably it is still compatible. 

I've posted a patch to fix this here: https://go-review.googlesource.com/c/go/+/470915
