### ISSUE TITLE
cmd/compile: zero-sized type increases size of struct when it's used as a field

### ISSUE THREAD

**Issue by badisch87** [golang/go#58483]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
set GOARCH=amd64
...
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...
set GOOS=windows
...
</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	"unsafe"
)

type s1 struct {
	a uint16
}

type s2 struct {
	a uint16
	_ [0]int16
}

func main() {
	fmt.Println(unsafe.Sizeof(s1{}))
	fmt.Println(unsafe.Sizeof(s2{}))
}
```

### What did you expect to see?

```
2
2
```

### What did you see instead?

```
2
4
```

**Comment by robpike** [comment]
Not always. See https://go.dev/play/p/b-Cwofn7RmC

Putting the zero-length field in the middle has no effect on the size in this example.

**Comment by Jorropo** [comment]
This an edge case of an edge case.

The original reason this is done to is to prevent issues when doing stuff like this:
```go
type zero struct{}

type S struct {
	a uint16
	b zero
}

func F(s *S) *zero {
  return &s.b
}
```
If the struct were the same size of `uint16` the pointer returned by `F` would point to `s + sizeof(uint16)` this means it would actually point outside of the allocation.
Unlike many other languages, (C, C++, Rust, ...) creating pointer past the allocation (but not using it) is legal. In go it isn't because the GC may at anytime inspect any pointer.

This is the same reason why `slice[x:]` compiles to a handfull instruction instead of the 1 or 2 programers exists (if you reslice a slice to nothing, the pointer to the data get zeroed out in order to not confuse the GC).

In your case your extra empty field is using the blank identifier making expressions like `&s._` impossible.
I wonder how much that really happens in practice tho.
