### ISSUE TITLE
cmd/cover: regression in 1.20, cover tool no longer includes packages without tests

### ISSUE THREAD

**Issue by abraithwaite** [golang/go#58770]
### What version of Go are you using (`go version`)?

<pre>
11:55:14 $ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
11:56:28 $ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/abraithwaite/Library/Caches/go-build"
GOENV="/Users/abraithwaite/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/abraithwaite/dev/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/abraithwaite/dev/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/abraithwaite/dev/github.com/runreveal/runreveal/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x5/_x8ny1d57k717yy0m92c02zh0000gn/T/go-build1870615753=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran our unit tests under both go1.19 and go1.20 and observed different coverage results.

To calculate coverage, we have this makefile testing target:

```
test:
    $(GO) test -vet=off -tags='$(GOTAGS)' $(GOTESTFLAGS) -coverpkg="./..." -coverprofile=.coverprofile ./...
    grep -v 'cmd' < .coverprofile > .covprof && mv .covprof .coverprofile
    $(GO) tool cover -func=.coverprofile
```

### What did you expect to see?

I expected the coverage reporting to stay the same between releases, assuming no code changes.

### What did you see instead?

The reported coverage falsely increased with go1.20 because it's no longer tracking coverage for packages that are missing tests.

As a workaround, I've put TODO tests in every package missing tests, but can't count on that manual practice to catch packages not being covered that I want to include in the coverage report.

**Comment by thanm** [comment]
I took a look at this issue.

What's happening here has to do with how the coverage machinery is handling "-coverpkg", specifically regarding imports.

You haven't supplied any specific code examples, but I will assume that this example will do for the discussion:

  https://go.dev/play/p/253gWw8ItV5

Code from the link above:

```
-- go.mod --
module bug.example

go 1.20
-- a/a.go --
package a

func A() int {
	return 42
}
-- a/a_test.go --
package a

import "testing"

func TestPackageCoverageInA(t *testing.T) {
	A()
}
-- b/b.go --
package b

func B() int {
	return -42
}
-- main/main.go --
package main

import (
	"bug.example/a"
	"bug.example/b"
)

func main() {
	println(a.A() + b.B())
}
```


We have three packages: "a", "b" and "main", where main imports "a" and "b" but neither "a" nor "b" imports anything.  If you run this with Go 1.20 at the top level (where the "go.mod" is) you get:

```
$ go test -count=1 -coverpkg=./...  -cover ./...
ok  	bug.example/a	0.018s	coverage: 100.0% of statements in ./...
?   	bug.example/b	[no test files]
ok  	bug.example/main	0.033s	coverage: 100.0% of statements in ./...
$
```

whereas in Go 1.19 you would get

```
$ go test -count=1 -coverpkg=./...  -cover ./...
ok  	bug.example/a	0.017s	coverage: 33.3% of statements in ./...
?   	bug.example/b	[no test files]
ok  	bug.example/main	0.028s	coverage: 100.0% of statements in ./...
$
```

Some background on how "go test" works: when you kick off a run of "go test -cover" in package "a", the Go command builds the test binary by combining the code from the package of interest (package 'a' in this case) with a test harness (`_testmain.go') that includes the test code, the testing package, and a synthetically generated "main" routine.

In Go 1.19 and prior versions, when given a command like

```
go test -coverpkg=./... -cover ./...
```

When building the test binary for "a", the Go command would construct a `_testmain.go` file that did a force import of all the packages matching the "./..." pattern, e.g.

```

// Code generated by 'go test'. DO NOT EDIT.
package main

import (
	"os"
	"testing"
	"testing/internal/testdeps"
	_test "bug.example/a"
	_cover0 "bug.example/b"
	_cover1 "bug.example/main"
	_cover2 "bug.example/a"
)
...
```

and would register the coverage counter variables for all of these packages with the testing runtime.

Forcing imports of "b" and "main" into the package "a" test binary is strange, since package "a" has no imports, and in particular importing "main" into "a" is especially weird given that normally it is the other way around. 

The forced imports does provide a mechanism for computing the correct result (here 33% of all statements in "./...") for package "a", but it also creates lots of confusion for users, who are surprise when various init functions in the "./..." packages that take actions that perturb the semantics of the run when testing "a".

Here are some of the bugs that users have filed regarding this quirk:

  https://github.com/golang/go/issues/21283
  https://github.com/golang/go/issues/23883
  https://github.com/golang/go/issues/23910
  https://github.com/golang/go/issues/27336
  https://github.com/golang/go/issues/46212

There are others as well (variants of this problem have been reported as bugs by Go users internal to Google). For this reason, in the coverage redesign rolled out in Go 1.20 we did away with the forced import mechanism.

Getting back to the bug at hand: you are quite correct however that this is a regression, we should be reporting the 33% number for package "a" and not 100%.

Rather than going back to forced imports, I believe that the best way to handle this is to have the Go command delay reporting of coverage numbers in this case (when "-coverpkg" is used).  Internally the new implementation collects raw profiles for each tested packed ("a" and "main") into a separate directory, so if we process the directories in combinatoin at the end of all test runs it should be possible to get the right result.

In the mean time, as a workaround you can restore the 1.19 behavior by setting adding this to your environment:

  `export GOEXPERIMENT=nocoverageredesign`

This will turn off the new implementation and revert back to the 1.19 scheme. Let me know if this works for you until the bug can be fixed.

**Comment by onsi** [comment]
thanks for the clear explanation @thanm  - I was about to submit a related issue but came across this and figured I'd provide an additional data point.  I've put together a reproducer [here](https://github.com/onsi/test-coverage) (which you can clone and run `make` on) for what I'm seeing but tl;dr I have the following setup:

```
---A/A.go---
package A
func A() bool { return true }

---B/B.go---
package B
func B() bool { return true }
   
---tests/tests.go---
package tests

import (
	"testing"
	"github.com/onsi/test-coverage/A"
)

func TestA(t *testing.T) {
	A.A()
}
```

when I run:

```
go test  -coverpkg=./... ./tests
```

I always get 100% coverage on both 1.19 and 1.20

When I run:

```
go test  -coverpkg=./... ./...
```

I get 50% coverage on 1.19 and 100% coverage on  1.20


That `100% coverage on 1.20` is this issue.  But the fact that 1.19 behaves differently for `./tests` vs `./...` (which is _kind of_ reported [here](https://github.com/golang/go/issues/23883) but I don't see the root issue being addressed there)  is confusing - particularly in light of your explanation.  it seems that `tests` is built differently when invoked as single package than when invoked as `./...`

I'm primarily sharing this here to call out that there is an opportunity in 1.20 not simply to fix the regression that's been identified but also to improve on the behavior in 1.19.    I'm also trying to avoid opening a near-duplicate issue but would be happy to do so if y'all would prefer.

**Comment by thanm** [comment]
Thanks for that addition @onsi .  

New issue: probably not needed, but up to you.

Regarding fixing things in 1.19, it would be nice, but in general the Golang policy on back-porting fixes is fairly conservative/restrictive. Unless a change is to fix a compiler error or runtime crash or some other serious problem (where there are no workarounds), the release team tends to be discourage this sort of back-port.  We'll see.

**Comment by onsi** [comment]
oh for sure - i wouldn't backport it to 1.19 either.  just noting that previous behavior wasn't quite working here either.

**Comment by abraithwaite** [comment]
I think that's totally reasonable.  Might be confusing for some, but the primary results I look at are the totals after all the tests are ran since I often have code exercising other packages in opaque and distance ways.

Looking great!  Thanks so much for taking a look at this @thanm!  Really appreciate your work.  💯

**Comment by Nov1kov** [comment]
A dirty workaround is to add an empty file with the name `*_test.go` to each package that is not included in coverage.
