### ISSUE TITLE
net/http/server.go：Incomplete judgment?

### ISSUE THREAD

**Issue by hktalent** [golang/go#58888]
go:
1.19.1
net/http/server.go：
<img width="584" alt="image" src="https://user-images.githubusercontent.com/18223385/223074433-e3d932d0-d35c-47c8-acc5-8100b82c9f2a.png">
#### defect
```
CONNECT、DELETE、PATCH、TRACE
```
### reference
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT
-

**Comment by cagedmantis** [comment]
Could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link? I don't understand what is being reported.

**Comment by bobby-stripe** [comment]
(I was looking at this code recently) -- this is a best effort helper so that, if a server listening for incoming HTTPS connections sees a handshake error, it sniffs the first 5 bytes of the request and tries to see "is this the most-easily-imaginable-case of someone sending a plaintext HTTP request to our HTTPS port?", and if so it returns a HTTP error response rather than _only_ closing the connection.

It seems ~ fine to add the first 5 letters of `CONNECT`, `DELETE`, PATCH`, `TRACE`, but also not very necessary as those are much less common than the verbs listed.  The request is _never_ going to succeed if this function is being called, it only affects quality of the user-facing error.
