### ISSUE TITLE
net/mail: mail.ParseAddress() allows invalid characters in local-part and domain-literal

### ISSUE THREAD

**Issue by lpar** [golang/go#59039]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Fedora release 37 (Thirty Seven)

<pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre>

### What did you do?

https://go.dev/play/p/SWpZqP2Xxed

### What did you expect to see?

An error.

Per RFC5322:
```
addr-spec       =   local-part "@" domain
local-part      =   dot-atom / quoted-string / obs-local-part
dot-atom        =   [CFWS] dot-atom-text [CFWS]
dot-atom-text   =   1*atext *("." 1*atext)
atext           = (Defined set of printable US-ASCII characters not including specials, see section 3.2.3)
```

So as I'm reading it the local-part is a single dot-atom-text (optionally with comments and folding whitespace around it but not inside it), dot-atom-text is a run of (atext or dot), and atext can only contain a defined set of printable ASCII characters.

Similarly, domain-literal doesn't seem to allow Unicode inside it either.

### What did you see instead?

An invalid email address was parsed as valid.

**Comment by ConradIrwin** [comment]
RFC 6532 updated the definition of a-text to include all multibyte characters (aka "UTF8-non-ascii") (https://www.rfc-editor.org/rfc/rfc6532#section-3.2) and they specifically call out that domains are included. (I updated go to support this here: https://go-review.googlesource.com/c/go/+/19687).

I do get that the domain you specify is (probably?) not allowed to be registered due to the unicode whitespace character (exaµple.com would be totally valid); but I don't think this is the right level of abstraction for the mail package to care about.

**Comment by lpar** [comment]
Yikes, so email addresses can now have whitespace in? Boy do I have opinions about that. Still, behavior is as per RFCs, so sorry for the bogus bug report.
