### ISSUE TITLE
net: copy from Unix socket to os.Stdout fails with "waiting for unsupported file type"

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#59041]
On HEAD this test function fails:

```Go
func TestCopyUnixToStdout(t *testing.T) {
	sockPath := filepath.Join(t.TempDir(), "unixsock")
	addr, err := net.ResolveUnixAddr("unix", sockPath)
	if err != nil {
		t.Fatal(err)
	}

	ln, err := net.ListenUnix("unix", addr)
	if err != nil {
		t.Fatal(err)
	}
	defer ln.Close()

	go func() {
		server, err := ln.Accept()
		if err != nil {
			t.Error(err)
			return
		}
		defer func() {
			if err := server.Close(); err != nil {
				t.Error(err)
			}
		}()
		for i := 0; i < 100; i++ {
			if _, err := server.Write(bytes.Repeat([]byte{'a'}, 1024)); err != nil {
				t.Error(err)
				return
			}
		}
	}()

	conn, err := net.Dial(ln.Addr().Network(), ln.Addr().String())
	if err != nil {
		t.Fatal(err)
	}

	if _, err := io.Copy(os.Stdout, conn); err != nil {
		t.Fatal(err)
	}
}
```

I see

```
foo_test.go:50: write /dev/stdout: waiting for unsupported file type
```

Here line 50 is the `t.Fatal` called when `io.Copy` fails.

This test passes with Go 1.20.

This is most likely due to https://go.dev/cl/466015.  CC @panjf2000

**Comment by ianlancetaylor** [comment]
Actually it looks like this can happen with TCP as well, so it may not be CL 466015.

**Comment by nightlyone** [comment]
I don't understand why there is a stat call needed asking the inode caches to achieve this instead of the much cheaper and more obviously correct normal tty check that only checks for presence a kernel file operation (equivalent to a static itab compare in Go). See e.g. https://github.com/mattn/go-isatty how to achieve this.

Checking for terminal only would still allow splicing to high speed device drivers that implement it correctly.

**Comment by bcmills** [comment]
Honestly, we've accumulated so many special-case checks on that path by now that I wonder if it would be more efficient to just try the `splice` call and fall back if it fails.

**Comment by andybalholm** [comment]
@ianlancetaylor 

Was removing `spliceNonblock` a mistake?

We've been running into an issue on a couple of our proxy servers (running github.com/andybalholm/redwood) where certain downloads time out instead of completing normally. We can't reproduce the issue on other machines, and the effects aren't even quite the same on the two machines. But it's quite consistent on those machines.

So we did a `git bisect`, and the commit associated with this issue is where the problem starts. The problem goes away if we revert the part of the change that relates to `spliceNonblock`:

```diff
diff --git a/src/internal/poll/splice_linux.go b/src/internal/poll/splice_linux.go
index 9505c5dcfc..4690962ae6 100644
--- a/src/internal/poll/splice_linux.go
+++ b/src/internal/poll/splice_linux.go
@@ -13,6 +13,9 @@ import (
 )
 
 const (
+       // spliceNonblock makes calls to splice(2) non-blocking.
+       spliceNonblock = 0x2
+
        // maxSpliceSize is the maximum amount of data Splice asks
        // the kernel to move in a single call to splice(2).
        // We use 1MB as Splice writes data through a pipe, and 1MB is the default maximum pipe buffer size,
@@ -89,7 +92,7 @@ func spliceDrain(pipefd int, sock *FD, max int) (int, error) {
                return 0, err
        }
        for {
-               n, err := splice(pipefd, sock.Sysfd, max, 0)
+               n, err := splice(pipefd, sock.Sysfd, max, spliceNonblock)
                if err == syscall.EINTR {
                        continue
                }
@@ -127,7 +130,7 @@ func splicePump(sock *FD, pipefd int, inPipe int) (int, error) {
        }
        written := 0
        for inPipe > 0 {
-               n, err := splice(sock.Sysfd, pipefd, inPipe, 0)
+               n, err := splice(sock.Sysfd, pipefd, inPipe, spliceNonblock)
                // Here, the condition n == 0 && err == nil should never be
                // observed, since Splice controls the write side of the pipe.
                if n > 0 {
```
When we make this change to the tip of the master branch, our problem goes away, and all tests still pass. 

Interestingly, the removal of `spliceNonblock` is not mentioned in the commit message. So maybe it was not really intended…?

**Comment by ianlancetaylor** [comment]
I removed `spliceNonblock` because it didn't seem to be serving any purpose, and because all the tests passed even when it was removed.  I still don't see any purpose for it.  The descriptors are expected to already be in non-blocking mode anyhow.

Is there any difference in the kernel version on the machines where your code fails?

Can you share a test case that demonstrates the failure?  Thanks.

**Comment by andybalholm** [comment]
Both of the machines with the problem are running Linux kernel 3.10.0 (from CentOS 7). We do have a few different kernel versions in use, but some of the ones that are not affected are also running 3.10.0.

I have no idea how to make a test case. For my `git bisect` work, I would compile a new binary of Redwood, deploy it to one of the routers, and message a user on the LAN behind the router, asking him to download a URL that was giving him problems. I don't even know whether the problem was on the client side or the server side of the proxy.

**Comment by andybalholm** [comment]
Looking at the documentation for `SPLICE_F_NONBLOCK` in the man page for splice(2), it looks like it's somewhat of a separate thing from the nonblocking status of the file descriptors:

> Do  not  block  on  I/O.  This makes the splice pipe operations nonblocking, but splice() may nevertheless block because the file descriptors that are spliced to/from may block (unless they have the O_NONBLOCK flag set).

If the files are blocking, the splice call can block even if SPLICE_F_NONBLOCK is set. It doesn't say what could happen if the files are nonblocking but SPLICE_F_NONBLOCK is set, but maybe there are circumstances where the splice pipe operations themselves can block.

**Comment by panjf2000** [comment]
Actually, I believe that the `SPLICE_F_NONBLOCK` flag was removed by mistake.

As far as I can tell, the original intent of `SPLICE_F_NONBLOCK` added by Linus Torvalds in this [commit](https://github.com/torvalds/linux/commit/29e350944fdc2dfca102500790d8ad6d6ff4f69d) was for the flag to affect the buffering, not the endpoints. As you can see in that commit, it took effect after the data transfer, even though it doesn't make the splice itself necessarily nonblocking, but it could, with `O_NONBLOCK` set in file descriptors.

Furthermore, the Linux kernel added `SPLICE_F_NONBLOCK` along with `O_NONBLOCK` implicitly since kernel v5.1, to avoid the inconsistent behaviors with pipe file descriptors with `O_NONBLOCK` in `splice`, check out this [commit](https://github.com/torvalds/linux/commit/ee5e001196d1345b8fee25925ff5f1d67936081e) for more details, which means that we don't need to explicitly assign `SPLICE_F_NONBLOCK` for `splice` since kernel v5.1 while we still have to do it in versions before v5.1.

I've drafted a [CL](https://go.dev/cl/536015) for this.

**Comment by ianlancetaylor** [comment]
@panjf2000 Thanks for the analysis.

**Comment by panjf2000** [comment]
Could you pull the latest code of Go from the `master` branch by which you can verify if your issue is fixed?
@sandeshrk

**Comment by sebastien-rosset** [comment]
> Could you pull the latest code of Go from the `master` branch by which you can verify if your issue is fixed? @sandeshrk

We have executed a test program with go 1.21.3: the program hangs. With go HEAD of master, the program completes successfully.

**Comment by sandeshrk** [comment]
The attached go file can be used to recreate/validate the fix.
The go program...
1. Starts a goProxy in a goroutine which blocks to accept a connection ([127.0.0.1:9090])
2. Starts a Downloader connects in another goroutune. Downloader connects to the proxy ([127.0.0.1:9090]) and attempts to download a file.

Stalled:
linux#./proxy
Starting GoProxy
Download Started
Downloading... 31 MB complete

Success:
./proxy
Starting GoProxy
Download Started
Downloading... 1.1 GB complete
Download Finished

[proxy.go.txt](https://github.com/golang/go/files/13193884/proxy.go.txt)

**Comment by panjf2000** [comment]
We should open a new issue for the subsequent discussions and link it to this issue.

Could you open a new issue to which you can move those previous comments and attachments about the suspicious behaviors (including what @andybalholm mentioned earlier)? Thanks! @sebastien-rosset @sandeshrk

**Comment by sebastien-rosset** [comment]
I have created #63795
