### ISSUE TITLE
go/printer: Strange indentation behavior/ broken output under some circumstances

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5946]
by **tobias.schwerdtfeger**:

<pre>What steps will reproduce the problem?
<a href="http://play.golang.org/p/MmaG6179Zk">http://play.golang.org/p/MmaG6179Zk</a>

Inside an ast.Block with a leading comment and at least 2 following &quot;Nodes&quot; (I
don't know how to call it correctly, e.g. X int  or  CallFunc()  etc.), the, beginning
from the second Node is indented wrong. This issue only happens, when
Mode:printer.SourcePos and a Tabwitdh greater than 0 is set in printer.Config{}.

Increasing the Tabwidth will result in smaller indention and vice verse.

Fix:

Delete both:
p.output = append(p.output, tabwriter.Escape)
surrounding:
p.output = append(p.output, fmt.Sprintf(&quot;//line %s:%d\n&quot;, pos.Filename,
pos.Line)...)
at file printer.go in method:
func (p *printer) atLineBegin(pos token.Position)

This will fix the issue with the indention, but has probably unwanted side effects.

---

In case of struct { ... } as seen in the example above, the indention between the 'X'
and 'int' or 'Y' and 'int' is false too. (This is unrelated to the issue described
above). Changing the Tabwidth to 0 will result in broken output =&gt; 'Xint' instead of
'X int'.
Example:
<a href="http://play.golang.org/p/pKlx5IZT89">http://play.golang.org/p/pKlx5IZT89</a>

Which version are you using?  (run 'go version')
go version devel +84cafba689b1 Wed Jul 24 17:48:13 2013 +0900 linux/amd64</pre>

**Comment by lukechampine** [comment]
I am also observing this behavior. Here's the smallest case that I was able to reproduce: https://play.golang.org/p/2eixeOb1i8

Using `printer.RawFormat` seems to fix the problem, which makes sense if the tabwriter is responsible.

Since this is low-priority, is there any downside to using `printer.RawFormat`?

**Comment by griesemer** [comment]
I cannot reproduce this anymore at tip (note that the playground will be updated once Go 1.9 is out). This may have been fixed indirectly as part of the fix for #5945.

(Also, please note that if you want to see the comments in your examples, you need to set the `parser.ParseComments` mode when invoking the parser. But this is orthogonal to this specific issue).

Feel free to re-open if you still see a problem.
