### ISSUE TITLE
proposal: cmd/vet:  Better unused variable handling

### ISSUE THREAD

**Issue by xbt573** [golang/go#59660]
The fact that Go compiler treats unused variables as error is cool, but it's annoying, so many developers uses code like this:
```go
x := dummy() // get variable
_ = x        // assign to void to suppress error
```
If it's a temporary solution it is OK, but if variable really not used anywhere, it can lead to unnecessary resource or time consumption. For example:
```go
func dummy() int { // dummy simulates long running operation
    time.Sleep(time.Second * 5)
    return random.Int()
}

func main() {
    x := dummy()
    _ = x

    fmt.Println("Hello World!")
}
```

```
xbt573 $ go run main.go
... waits 5 seconds ...
Hello World!
```

Therefore, i propose some changes to go vet:
1. Warn user if variable used or assigned only to void register
2. Warn user if variable used, but there is a unnecessary void register assign
3. Warn user if all of function return values are assigned to void register

It will help remove really unused variables and unnecessary void register assigns

**Comment by seankhliao** [comment]
The blank identifier is the standard way of indicating that a value is not to be used. It seems counter productive to make vet warn on it.
1 is intentional, 2 does not seem to a frequent issue, nor does it affect correctness. 3 will cause serious churn for projects that use things like https://github.com/kisielk/errcheck

Given the current state of the ecosystem, I don't think this meets the bar for frequency or precision for cmd/vet.
It may make sense as an external linter.

See also #20803
