### ISSUE TITLE
runtime: `netpoll failed` on `darwin`

### ISSUE THREAD

**Issue by bcmills** [golang/go#59679]
```
#!watchflakes
post <- goos == "darwin" && log ~ `^fatal error: runtime: netpoll failed`
```

(Pulled out from https://github.com/golang/go/issues/34988#issuecomment-1499690928; CC @ianlancetaylor @golang/darwin)

**Comment by ianlancetaylor** [comment]
```
> runtime: kevent on fd 3 failed with 60
> fatal error: runtime: netpoll failed
```

Error 60 is `ETIMEDOUT`.  This shouldn't happen, and is not listed on the man page.  When a call to `kevent` reaches the timeout, it is documented to return `0`.

It would be easy for us to ignore a `ETIMEDOUT` error but it shouldn't be necessary.

**Comment by mknyszek** [comment]
In triage, we think this is either a bug in Darwin or a bug in the Darwin documentation. @prattmic thinks maybe an error is bubbling up from somewhere deeper, in which case maybe we just ignore it like @ianlancetaylor suggested.

**Comment by mknyszek** [comment]
We agree we will wait until it fails again to make a decision.

**Comment by panjf2000** [comment]
Since this failure always happened during runtime/pprof.TestCPUProfileWithFork.

The `ETIMEDOUT` error from `kevent` in this context can be related to a variety of factors (just some thoughts, not quite sure):

- Profiling Overhead: CPU profiling adds overhead. When combined with the process of forking, there might be a scenario where the system is unable to complete an operation in a timely manner, leading to the timeout.
- Concurrency Issues: Forking in a multithreaded environment (like a Go program) can be tricky. If there are race conditions or other concurrency issues, it might cause unexpected behaviors.
- Resource Limitations: As with any stress test, if the system is resource-constrained, it could contribute to timeouts.
- File Descriptors and Locks: Forking can duplicate file descriptors, and if there's any form of locking mechanism (like for files being used in the profiling), it could potentially cause delays or deadlocks, leading to timeouts.

Furthermore, I found some old links where people came across that error of `kevent`:
- https://www.mail-archive.com/freebsd-net@freebsd.org/msg17338.html
- https://bz.apache.org/bugzilla/show_bug.cgi?id=59914

I think before we dive deep and figure out what really happened there, ignoring `ETIMEOUT` is a temporary but sufficient solution.
