### ISSUE TITLE
net/url: url.Query() is not returning the correct value

### ISSUE THREAD

**Issue by aayush-sib** [golang/go#59821]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Code -> https://go.dev/play/p/pLLAs_g3v1l

### What did you expect to see?

`map[query1:[test]]`

### What did you see instead?

`map[]`

**Comment by Snaddyvitch-Dispenser** [comment]
This looks to be correct behaviour, javascript agrees:
![image](https://user-images.githubusercontent.com/28988626/234228353-673f4ae0-38fc-4f44-8cd3-9f482865f230.png)

I think this is as it comes after the `#`, which is considered the anchor, which always has to come after the query string, and since it sees the `#` it considers that the anchor rather than the query string as you'd expect

![image](https://user-images.githubusercontent.com/28988626/234229699-323d47b3-c826-4833-8fe7-0fb678aad0a7.png)
[Source](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL)

i.e. the Anchor for this URL is `/1?query1=test`. It would have to come before the # in order to be parsed as the query string.

Hope this helps :)
