### ISSUE TITLE
x/website: dl page overflows from downloads table

### ISSUE THREAD

**Issue by mcandre** [golang/go#59949]
![Screenshot_20230503-103132](https://user-images.githubusercontent.com/5316/235964932-d55fe927-0683-427c-974d-466ed60bfb6c.png)

**Comment by mvdan** [comment]
I can reproduce as well; below is a video on Firefox 112.2.0 on Android 13 on a Pixel 4a, visiting https://go.dev/dl:

https://user-images.githubusercontent.com/3576549/236195885-be76b8bf-d16b-443b-b00f-80ce15a403e1.mp4

The problem is that I can horizontally scroll away from the entire page content, including the top bar. This appears to be due to the table containing each of the downloads with their info, since it doesn't fit the vertical and rather narrow phone screen.

**Comment by cagedmantis** [comment]
cc @golang/tools-team

**Comment by seankhliao** [comment]
@adonovan sounds unrelated? this is a css issue on the main site
