### ISSUE TITLE
crypto/x509: TestPlatformVerifier fails on windows-amd64-longtest-oldcc builder on 1.19 release branch 

### ISSUE THREAD

**Issue by cherrymui** [golang/go#60118]
It fails on the dashboard for 1.19 release branch
https://build.golang.org/log/e91a530bfdb6f096ad81e08a8fbaf88aa62d957b
https://build.golang.org/log/3d0f6bb48b4df90269fac5cf522a37332c150955
Interestingly it did not fail at the latest commit 484330d on the branch.

Failed also pretty consistently in trybot runs at CL https://golang.org/cl/492697
https://storage.googleapis.com/go-build-log/ea1147d1/windows-amd64-longtest-oldcc_a8321ffb.log

Might be related to #58810 ?

**Comment by cherrymui** [comment]
cc @dmitshur @golang/release

**Comment by bcmills** [comment]
(CC @rolandshoemaker; see also #52108.)

**Comment by cagedmantis** [comment]
Are there any plans to fix this before the next release? Should we just skip the test?

**Comment by dmitshur** [comment]
This test is being fixed at tip in #52108, but the changes required to fix it are very large and not a great fit for backporting. So skipping the test is fine. But since we got through many minor releases by working around this flaky test, I expect we can get through one more. If that isn't the case, I'll reopen.
