### ISSUE TITLE
all: update go directive to be at least 1.18 in all golang.org/x modules

### ISSUE THREAD

**Issue by neild** [golang/go#60268]
The  Go version in the `go.mod` for `x/net`, `x/crypto`, `x/text`, and other `x/` repos is currently go1.17, which prevents use of generics or `any`.

The oldest Go version within the support window is 1.19.

Is it time to update the `x/` repos to depend on a post-generics version of Go? If so, perhaps we should also update packages in those repos to switch from `interface{}` to `any` at the same time.

**Comment by dmitshur** [comment]
I ended up doing something along these lines as part of work for #56530. Previously, some golang.org/x repos were on Go language version as old as 1.12, which missed out on module graph pruning, made go.sum very verbose, and otherwise got in the way of the automatic tagging/updating workflow from doing its job. I semi-arbitrary picked 1.18 because it was already used by a number of x repos even before I started [updating more](https://go-review.googlesource.com/q/author:dmitshur@golang.org+%22go+directive+to+1.18%22), and was enough to get some nice new features like module graph pruning, removed // +build lines, and so on.

By now, the oldest Go version within the support window is Go 1.20, but there's not much to be gained when going from 1.18 to 1.19 and 1.20—see https://go.dev/ref/mod#go-mod-file-go—so I stopped at 1.18 for now.

Since I was already working in x/net today for the release, I also mailed [CL 534241](https://go.dev/cl/534241) to get x/net up to the same 1.18 minimum bar. I'll take care of x/text and x/crypto too.

I did incorporate high confidence changes that are implemented in `go fix` into the CLs, like removing old-style "// +build" lines, but I'll leave other opportunities like `interface{}` to `any` or ioutil to io/os rewrites out of scope. I think they too can be done with tooling to some extent (see [CL 527016](https://go.dev/cl/527016) for example).

**Comment by dmitshur** [comment]
I noted in [CL 534224](https://go-review.googlesource.com/c/xerrors/+/534224/2#message-e9f645bb7ddc705c173e3c0f6fef0bb87a047412):

> I think it'll get easier sometime after Go 1.22.0 is out, whenever we wish to bump x repos to `go 1.21.0` or higher. A relui workflow that handles all repos might be helpful.

Okay, calling this round of updates done.

**Comment by delthas** [comment]
This breaks updating Go from an old Go version. Significant bug?

`go get golang.org/dl/go1.19.13` run from any Go version <= 1.16 now fails with:
```
# golang.org/dl/internal/version
go/src/golang.org/dl/internal/version/signal_unix.go:14: signalsToIgnore redeclared in this block
	previous declaration at go/src/golang.org/dl/internal/version/signal_notunix.go:13
go/src/golang.org/dl/internal/version/version.go:151: undefined: os.WriteFile
go/src/golang.org/dl/internal/version/version.go:322: undefined: io.ReadAll
```
because `//+build` was removed and `//go:build` is not supported on those versions.

My CI pipeline run from an old Debian that tries to download a newer Go version now fails because of this change.
