### ISSUE TITLE
x/pkgsite: retracted tags still show up as latest for `flashbots/mev-boost-relay`

### ISSUE THREAD

**Issue by metachris** [golang/go#60336]
The repository https://github.com/flashbots/mev-boost-relay retracted the latest 5 tags and we published a new version v0.24.0

- https://github.com/flashbots/mev-boost-relay/blob/v0.24.0/go.mod#L109-L116

But the retracted tags still show up as "latest" on https://pkg.go.dev/github.com/flashbots/mev-boost-relay

Shouldn't v0.24.0 be used as latest tag now?

**Comment by bcmills** [comment]
Retractions are loaded from the latest tagged version of the module (necessarily ignoring retractions).

In order to retract `v1.15.2`, you will need to tag a higher version (`v1.15.3`?) and fetch that tag through the module proxy.

(Presumably you will also want `v1.15.3` to retract itself, so don't forget to add it to the `retract` list.)

**Comment by bcmills** [comment]
I would expect so, yes.

**Comment by metachris** [comment]
works, thanks!

**Comment by notrepo05** [comment]
Thanks @metachris
