### ISSUE TITLE
Fail to build library similar to C# and Rust

### ISSUE THREAD

**Issue by hkpeaks** [golang/go#60357]
Today I plan to reclassify more source code files from proprietary into open source https://github.com/hkpeaks/peaks-consolidation as an Apache Parquet-Go contributor requests me helping them to develop parallelism CSV-Go reader https://github.com/apache/arrow/issues/35688

So I build a library file for one source code file "data_bending.go with file size 44KB". At the end, nothing binary file can output to disk. Using Rust and C#, build library (without main) is a very easy task.  If no way to build library, I may use Rust to continue my Peaks Consolidation project. Today I have tested Rust and see a output library file.

### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19

</pre>

### What operating system and processor architecture are you using (`go env`)?
Windows for x86

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
see the library

### What did you see instead?
nothing

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by hkpeaks** [comment]
This is not a general discussion. Fail to build library is obviously a bug. Please help to follow.

**Comment by hkpeaks** [comment]
It is not appropriate to close a bug report.

**Comment by Bobby-Wan** [comment]
I am sorry, but the description is confusing to me. This doesn't look like a bug in Go by the way you describe it, although I might be totally missing the point.

**Comment by hkpeaks** [comment]
Since I cannot accept single exe file, I have confirmed with my wife and users the Peaks Consolidation will be rewritten in Rust. I will try more hard work by the end of next month to publish 2nd pre-release of runtime for 64-bit Windows/Linux. Wrote Rust code is no new for me.

Go community will lost this one of fastest dataframe library written in Go https://github.com/hkpeaks/peaks-consolidation/releases . The crazy fact that Go does not allow the existence of library, it is unbelievable. It look like future human being has no leg.

**Comment by randall77** [comment]
Go does allow building libraries. It depends on what kind of libraries, though. Compile-time? Link-time? runtime?
This issue does not provide enough information to figure out what you're trying to do and what didn't work.
For instance, the "what did you do" section is empty. Please provide detailed instructions so that we can reproduce.
If you are willing to gather that information, please open a new issue.

**Comment by YuWaiPang** [comment]
I opened source most of project code except one file "databending.go" which I want to keep proprietary. It is used to finance the contunuing development of the open source project. In order to support users to build a runime for Windows/Linux, I shall allows them to make reference to a binary library (complied version of databending.go). When I use other programming language such as C# and Rust, it is very common to pack some of proprietary source code files as a binary library and be referenced by other projects.

Now I know that this function is droped https://github.com/golang/go/issues/28152 in 2018
which is created in 2016
https://github.com/golang/proposal/blob/master/design/2775-binary-only-packages.md

If it is re-created now, please let me know how to do it.

If no way to do it, I will replicate my current project to Rust in order to fit for my original plan. 

I consider purely open source for a tiny project which is focus on hyper speed on data consolidation for billions of rows, it is not possible to main the project financially. I am retired for over 3 years from COVID-19 layoff exercises. I start this project in Feb 2023 to support my back to either employment or self-employed. Most valuable source code is the databending.go. If I open source it, it will be the end of the project. I prefer to find a new employment directly when HK is lacking of IT professions.

**Comment by hkpeaks** [comment]
I opened source most of project code except one file "databending.go" which I want to keep proprietary. It is used to finance the contunuing development of the open source project. In order to support users to build a runime for Windows/Linux, I shall allows them to make reference to a binary library (complied version of databending.go). When I use other programming language such as C# and Rust, it is very common to pack some of proprietary source code files as a binary library and be referenced by other projects.

Now I know that this function is droped https://github.com/golang/go/issues/28152 in 2018
which is created in 2016
https://github.com/golang/proposal/blob/master/design/2775-binary-only-packages.md

If it is re-created now, please let me know how to do it.

If no way to do it, I will replicate my current project to Rust in order to fit for my original plan.

I consider purely open source for a tiny project which is focus on hyper speed on data consolidation for billions of rows, it is not possible to maintain the project financially. I am retired for over 3 years from COVID-19 layoff exercises. I start this project in Feb 2023 to support my back to either employment or self-employed mode. Most valuable source code is the databending.go which involve significant knowhow on the backbone in advanced accounting automation. I am a qualified accountant and have over 20+ years of experience in accounting. If I open source it, it will be the end of the project. I prefer to find a new employment directly when HK is lacking of IT professions.

**Comment by ianlancetaylor** [comment]
You are correct: Go does not support binary-only packages.  In this regard Go is more like Python or JavaScript than it is like C or Rust.  There is of course a big difference between providing source code to paying customers and making a project open source, but if your work requires not providing source code then Go is not the language for you.  Sorry.

**Comment by hkpeaks** [comment]
In fact my dream is if I can support Peaks Consolidation become fully open source.
As it will make change of many software such as Pandas, dbDuck, Polars and etc when they demand for achieving ultimate processing speed when I am successfully to innovate a set of databending algorithms using bytearray (same as file bytestream) as in-memory table.

https://h2oai.github.io/db-benchmark/

**Comment by hkpeaks** [comment]
If Google can support my open source project become fully open source, in fact no need to use Rust.

**Comment by hkpeaks** [comment]
Recently I explored how to implement Apache Parquet-Go. One of Apache Parquet-Go contribute provide me technical support
https://github.com/apache/arrow/issues/35688

**Comment by hkpeaks** [comment]
When I ready to build rust code, I try whether Bing Chat can be increased its 2000 upper limit. Bing reply how to do it. 
Since many of my Peaks function the code is over 2000 chars. After increase to 10,000 chars and having a test, seem it is very simple to do the code transplantation exercise from Golang to Rust. I noticed that Windows team is trying use Rust to write some of windows code.

**Comment by hkpeaks** [comment]
Yesterday I success to complete python binding for a sample app easily, becuase Rust can output dll for Windows platform.
Now I can effect to migrate my Go project to Rust.
Thanks for the simplicity of Golang for parallel computing, so I can success in many peformance game including billions of rows sorting and jointable - no need using so called very expensive cloud computing service. Using desktop PC with 32GB memory can do it very well. My demo video here: https://www.youtube.com/@hkpeaks/videos
