### ISSUE TITLE
net/http: insufficient sanitization of Host header

### ISSUE THREAD

**Issue by neild** [golang/go#60374]
The `net/http` client does not sufficiently sanitize or check the validity of the `Request.Host` field. A maliciously-crafted `Host` field can inject request headers or entire new requests into the sent request. For example, setting `Request.Host` to `"hostname\r\nX-Header: oops"` adds an `X-Header: oops` header to the request.

Whether this is a vulnerability or just a bug depends on whether the `Request.Host` field is expected to be secured against untrusted inputs. We don't document this one way or the other. Exploiting this in practice seems difficult, since it requires requests to be sent using an unsanitized and untrusted `Request.Host` value, so if this is a vulnerability it seems reasonable to treat it as PUBLIC track. Either way, we should fix it.

This is a continuation of #11206, which reports the same issue but had an incomplete fix.

Thanks to @bartekn for reporting this issue.

**Comment by neild** [comment]
@gopherbot please open backport issues. This is a (fairly minor) security issue.

**Comment by tatianab** [comment]
This is CVE-2023-29406.

**Comment by dmitshur** [comment]
@neild CL 506995 and CL 506996 both say "For". Is the only thing left to resolve this issue to regenerate src/net/http/h2_bundle.go, or is there more that needs to be done for Go 1.21?

This is being backported to the next 1.20 and 1.19 minor releases, so adding release-blocker here since Go 1.21 shouldn't be released while this issue is still open. (CC @joedian.)

**Comment by eliben** [comment]
@neild what's the status here?

**Comment by jmurret** [comment]
THank you for this change.  This does cause an issue for unix sockets that have hostnames starting with a slash.  I think we are seeing the community that uses sockets now have to react to this change and put in conditional logic to check their host and if it begins with a slash or ends with `.sock` change the host name to something like `localhost`.  Is it possible to have this baked into net/http host header validation?

**Comment by andresvia** [comment]
> Thank you for this change. This does cause an issue for unix sockets that have hostnames starting with a slash. I think we are seeing the community that uses sockets now have to react to this change and put in conditional logic to check their host and if it begins with a slash or ends with `.sock` change the host name to something like `localhost`. Is it possible to have this baked into net/http host header validation?

@jmurret I will dare to say that the security fix went too hard and broke a *feature* which many of us relied on and now there's really no right (clean) way to proceed, if the validation gets baked, workarounds will need to remain because there will be always people running some go release which doesn't have the thing baked. I'm sorry I know I'm not really commenting anything useful, I'll just move on with my life 😄 and let you guys think about what you just did.

**Comment by ChristianSch** [comment]
Have to agree with @andresvia here. This essentially broke everything using docker. In a patch version update as well.

**Comment by ianlancetaylor** [comment]
This fixes a security issue so we are unlikely to roll it back.  Could somebody please open a new issue describing the problem that was introduced?  Ideally please include a small self-contained test case.  Thanks.

**Comment by nicks** [comment]
@ianlancetaylor sure! i wrote up https://github.com/golang/go/issues/61431 to try to express my understanding of the problem.

**Comment by ianlancetaylor** [comment]
@nicks Thanks.
