### ISSUE TITLE
x/tools/gopls/internal/regtest/marker: TestMarkers failures

### ISSUE THREAD

**Issue by bcmills** [golang/go#60584]
```
#!watchflakes
post <- pkg == "golang.org/x/tools/gopls/internal/regtest/marker" && test == "TestMarkers" && date >= "2023-05-01"
```

**Comment by bcmills** [comment]
(attn @findleyr @adonovan)

**Comment by findleyr** [comment]
These tests are far too noisy, and should have been skipped weeks ago -- my bad. I believe the failing tests are real races in gopls (I believe that orphaned file reloading can sometimes bypass the 'critical error' logic in gopls).

Skipping the addgowork test to start, since it is overwhelmingly the most noisy.

**Comment by findleyr** [comment]
Looks like the changes to completion budget made this flake more likely. I will disable completion budget entirely for this test.

**Comment by adonovan** [comment]
The s390 failure in https://github.com/golang/go/issues/60584#issuecomment-1793192593 is really weird: it's reading the wrong file out of the gopls/internal/regtest/marker/testdata/diagnostics/parseerr.txt txtar archive. The file named go.mod contains the contents of the (Go) file named bad.go.

**Comment by findleyr** [comment]
Absolutely bizarre. Also, note this:
```
/data/golang/workdir/tmp/TestMarkersdiagnosticsparseerr.txt1145313885/001/work/go.mod:6:2: unknown directive: x
```

There is no line starting with 'x' in that file (though the character 'x' occurs in the word 'syntax'. Is this file just entirely corrupted?

**Comment by findleyr** [comment]
The other failure is similarly confusing, though less obviously corruption: somehow gopls is otherwise working, but excludes pkg.go.dev links. These links should only be omitted if the "linksInHover" option is set, or if the link matches GOPRIVATE. It doesn't seem likely that a bug causes one of those conditions to be set, yet everything else appears to work normally. I would expect that e.g. a configuration race or `go env` corruption would manifest in more errors.

**Comment by findleyr** [comment]
These tests have been moved, and are no longer flaking. Marking as fixed.
