### ISSUE TITLE
x/website: Tutorial contains stale code/advice (no need to seed rand anymore)

### ISSUE THREAD

**Issue by medkhabt** [golang/go#60627]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/random-greeting
 
 
### What is your user agent?
 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
 
### Screenshot
 
<img width="1440" alt="Bildschirmfoto 2023-06-06 um 11 45 42" src="https://github.com/golang/go/assets/34715586/812f2858-8091-4cfd-a398-cd7b785011b8">

 
### What did you do?
-- 
 
 
### What did you expect to see?
 I expect to not see that paragraph. I assumed that there was an init() function for older versions of the code but forgot to change also the paragraph that explains the code.
 Or maybe I am missing something about the language, I am new to GO. 
 
 
### What did you see instead?

The paragraph inside the blue border of the screenshot. 

Have a great day!

**Comment by dr2chase** [comment]
@golang/tools-team
Looks like an issue to me, too.

**Comment by jexlock** [comment]
I think it would be worth adding additional context rather than completely removing. I happened to be working through this example with go1.19.5 which seems to not init() the rand function, and as such had some mild confusion when my code matched but the output did not (fixed by adding a seed the example code did not have).

Installing 1.20.5 seems to have solved the seed issue, but I think for newer users it may be nice to have this section call out the change of functionality from version X to version X and that older versions require manual init seeding.

**Comment by findleyr** [comment]
CC @ansaba

**Comment by ianlancetaylor** [comment]
I think this was fixed by https://go.dev/cl/507096.  Sorry for the delay.

**Comment by Jaculabilis** [comment]
I would like to echo @jexlock's sentiment. I started going through the tutorial on a Linux Mint machine, and the Go version I get from `sudo apt install golang` is 1.18.1. It would be helpful to at least have a note that this requires 1.20, or that users below 1.20 may need to add additional code to get the example to work. Removing any mention of `init` entirely just makes the subsequent un-seeded behavior even more mysterious.

**Comment by leimao** [comment]
Why there is no version control for the tutorial?
