### ISSUE TITLE
doc update: https://go.dev/ref/spec#Size_and_alignment_guarantees

### ISSUE THREAD

**Issue by SweetGeneral** [golang/go#60638]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS="darwin"
GOARCH=:amd64:
</pre></details>

### What did you do?
Read the doc https://go.dev/ref/spec#Size_and_alignment_guarantees and experiment with few cases :-
https://go.dev/play/p/97P05PazlKQ

### What did you expect to see?

Complete info in the doc for above shared cases.

### What did you see instead?

Incomplete info in the doc for the above shared case.

**Comment by dr2chase** [comment]
The behavior you propose to document isn't actually guaranteed -- it might change -- which is why it does not appear in the list of guarantees.

**Comment by SweetGeneral** [comment]
@dr2chase Thank you so much for reviewing. Also, could you please point me to resource(s) or help me understand the reason for this behavior and dependent things.

**Comment by dr2chase** [comment]
The reason things are the way they are, now, is that it allows accidental compatibility with C data types, and as long as that is the rule, your advice to order in decreasing size is generally the best plan of packing storage (even if that does not belong in a specification).  It's unclear if we'll ever change that, but doing so would probably have some advantages since not everyone takes the time to shuffle structure fields, and there are also likely advantages to shuffling pointers to the front of a structure, too.

The main impediment to changing this is that Go programmers would need to stop relying on "accidents" for C compatibility.  Cgo could handle this automatically and that is a large important case, but it is not the only case.

**Comment by SweetGeneral** [comment]
Got it! Thanks for the detailed explanation.
