### ISSUE TITLE
cmd/go: "loadPackageData called with empty package path" build panic

### ISSUE THREAD

**Issue by d-enk** [golang/go#60686]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 linux/amd64
</pre>

### What did you do?

go build

```go
package main

import ""

func main() {}
```

### What did you expect to see?
go 1.19

```prog.go:3:8: invalid import path: ""```

### What did you see instead?
```
panic: loadPackageData called with empty package path

goroutine 29 [running]:
cmd/go/internal/load.loadPackageData({0xb45d70, 0xc00019a000}, {0xc000028e0e, 0x0}, {0xc00019a938, 0x4}, {0xc00033bf20, 0x1f}, {0xc000032064, 0x1f}, ...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.5/libexec/src/cmd/go/internal/load/pkg.go:815 +0x65d
cmd/go/internal/load.(*preload).preloadImports.func1({0xc000028e0e?, 0x0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.5/libexec/src/cmd/go/internal/load/pkg.go:1076 +0xa5
created by cmd/go/internal/load.(*preload).preloadImports
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.5/libexec/src/cmd/go/internal/load/pkg.go:1075 +0x2aa
 ```

**Comment by dr2chase** [comment]
@bcmills I fear this is another one for you to look at.

**Comment by matloob** [comment]
https://go-review.git.corp.google.com/c/go/+/424855 removed the check that (among other things) the import path was not empty. Before that, the file would have a parse error returned, go/build would move it to InvalidGoFiles, and the loader would ignore it. Now it's treated as a valid go file, we try to load the import and panic because the path is empty.

I'll try to get a fix on monday.
