### ISSUE TITLE
os/exec: LookPath uses a hard coded "/", assuming this is broken on Windows

### ISSUE THREAD

**Issue by martinrode** [golang/go#60680]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

My assumption here is that `os.LookPath` will not work the same on Windows as it does on Linux / Mac. It will try to check the `PATH` environment even if the prog passed is `utils\myprog.exe`.

### What did you do?

Read through the source code of `LookPath`.

### What did you expect to see?

Something like `filepath.Separator` used instead of `/`.

### What did you see instead?

A `/`

**Comment by qmuntal** [comment]
Thanks for reporting this @martinrode.

Could you link to the offending code using just `/`? I can't find it myself on the windows implementation at https://github.com/golang/go/blob/b9baf4452fe949a5a159eec4d4a437ad2833ead1/src/os/exec/lp_windows.go#L65.

Take into account that the unix implementation is not the same as the windows one. Could it be that you are looking at the former (located [here](https://github.com/golang/go/blob/b9baf4452fe949a5a159eec4d4a437ad2833ead1/src/os/exec/lp_unix.go#L52) instead of the later?

**Comment by martinrode** [comment]
Right, I am sorry for the confusion. The OS suffix is something I keep forgetting about ;-)
