### ISSUE TITLE
x/mod/zip: TestCreateFromDirSpecial/ignore_symlink failing on wasip1-wasm-wasmtime

### ISSUE THREAD

**Issue by prattmic** [golang/go#60795]
This test is failing consistently, see https://build.golang.org/?repo=golang.org%2fx%2fmod.

Sample: https://build.golang.org/log/ee8bf87a4deeaf417d36761289c1fb43ff648869

```
--- FAIL: TestCreateFromDirSpecial (0.01s)
    --- FAIL: TestCreateFromDirSpecial/ignore_symlink (0.00s)
        zip_test.go:543: symlink /tmp/TestCreateFromDirSpecialignore_symlink3388003329/001 /tmp/TestCreateFromDirSpecialignore_symlink3388003329/001/link: Operation not permitted
FAIL
FAIL	golang.org/x/mod/zip	6.086s
FAIL
```

Note that wasip1-wasm-wazero is OK.

cc @golang/wasm

**Comment by johanbrandhorst** [comment]
Hm, symlink tests should be disabled on the wasmtime runner, courtesy of https://go.googlesource.com/go/+/refs/heads/master/src/internal/testenv/testenv_notwin.go#16. Does this test check for symlink support before running?

**Comment by bcmills** [comment]
> Does this test check for symlink support before running?

It checks after the fact, with the operation allowed to fail after the fact based on a hard-coded list of `runtime.GOOS`:
https://cs.opensource.google/go/x/mod/+/master:zip/zip_test.go;l=538-545;drc=ad6fd61f94f8fdf6926f5dee6e45bdd13add2f9f

Probably that list should explicitly list the `GOOS` values for which `Symlink` is expected to always succeed, instead of its current behavior of explicitly listing the ones for which it is allowed to fail. That would make it more robust to new `GOOS` values going forward.
