### ISSUE TITLE
GPG error: http://deb.debian.org/debian bookworm InRelease

### ISSUE THREAD

**Issue by brianbrookes-wk** [golang/go#60803]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.10

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

We are using using 1.19 `FROM golang:1.19` in our Dockerfile and we do a `RUN apt-get update && apt-get upgrade -y` 

Up until today it has been working fine. I believe because `FROM golang:1.19` was pulling 1.19.9 until today when it switched to 1.19.10, where you switch from using debian:11 to debian:12

### What did you expect to see?
The build to compile.

### What did you see instead?

we get this error: 
`
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var
`

**Comment by seankhliao** [comment]
not a go issue

**Comment by brianbrookes-wk** [comment]
Yeah, just thought you might want to know since your docker images also use debian 12 now.

**Comment by icholy** [comment]
Those images are maintained here: https://github.com/docker-library/golang

**Comment by kuldeepsolanki04** [comment]
@brianbrookes-wk  Are you able to resolve this issue, I am also facing the same issue for 1.20.6

FROM golang:1.20.6
ENV GOBIN="/go/bin"
RUN mkdir -p /root/.ssh
 RUN echo "  StrictHostKeyChecking no" >> /etc/ssh/ssh_config   && echo "  UserKnownHostsFile=/dev/null" >> /etc/ssh/ssh_config
 RUN apt-get update   && apt-get install -y   ant   openjdk-11-jdk   unzip   zip   autoconf   automake   libtool   make   g++   && apt-get clean all


Getting below error

14:02:04   Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
14:02:04   Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
14:02:04   Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
14:02:04   Err:1 http://deb.debian.org/debian bookworm InRelease
14:02:04     The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY F8D2585B8783D481
14:02:04   Err:2 http://deb.debian.org/debian bookworm-updates InRelease
14:02:04     The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
14:02:05   Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
14:02:05     The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
14:02:05   Reading package lists...
14:02:05   W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY F8D2585B8783D481
14:02:05   E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
14:02:05   W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
14:02:05   E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
14:02:05   W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
14:02:05   E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
14:02:05   E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
14:02:05   E: Sub-process returned an error code
14:02:05   The command '/bin/sh -c apt-get update   && apt-get install -y   ant   openjdk-11-jdk   unzip   zip   autoconf   automake   libtool   make   g++   && apt-get clean all' returned a non-zero code: 100
