### ISSUE TITLE
unicode: IsLetter check char 231 have error

### ISSUE THREAD

**Issue by epowsal** [golang/go#60863]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.3
</pre>

### What operating system and processor architecture are you using (`go env`)?

windows 11 intel 64

char 231  is half chinese char, it is not a letter.
unicode/utf8 package should add IsEnLetter and IsUtf8Letter. This cause my program too many error.

**Comment by epowsal** [comment]
atleast should add IsEnLetter or IsUtf8Letter. this cause my program many error.

**Comment by ianlancetaylor** [comment]
Whether a Unicode code point is a letter or not is defined by the Unicode standard.  I don't know precisely what you mean by character 231.  The code point with the value decimal 231 is ç, which is a letter.  Closing because I think the function is behaving as documented and intended.  Please comment if you disagree.

I don't know precisely what you mean by `IsEnLetter` or `IsUtf8Letter`.
