### ISSUE TITLE
x/tools/go/packages/gopackages: better documentation of -mode flag

### ISSUE THREAD

**Issue by 4cq2** [golang/go#60995]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Steven\AppData\Local\go-build
set GOENV=C:\Users\Steven\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Steven\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Steven\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Windows\TEMP\go-build2434007380=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

using this input:

~~~go
package tls

type dsaSignature struct { }

type lruSessionCache struct {}

func NewLRUClientSessionCache() lruSessionCache {
	return lruSessionCache{}
}
~~~

### What did you see instead?

I get this result:

~~~
> gopackages -mode types -private tls
Go package "tls":
        package tls
        has complete exported type info
        file D:\Desktop\etc\common.go
        func NewLRUClientSessionCache() lruSessionCache
        type lruSessionCache struct{}
~~~

one type is listed, but the other is not.

**Comment by 4cq2** [comment]
https://github.com/golang/go/issues/60831

**Comment by adonovan** [comment]
When you specify `-mode=types`, you're requesting (only) complete type information for the package's exported API. This includes exported declarations such as NewLRUClientSessionCache, but it additionally includes named types referenced by them (even if unexported), such as lruSessionCache, plus all of their methods, and any types required by them, and so on. But it does not include types that are unreachable from the public API.  (This information can be efficiently obtained from the cached output of the compiler.)

If you want the types for all declarations, you'll need `-mode=syntax`, which loads the package from syntax and type-checks the whole thing, including the internals. This is a more expensive operation. (More expensive than you need, because it type-checks function bodies, which are by far the majority of the syntax yet are irrelevant to you. There is a way to suppress that (IgnoreFuncBodies in https://pkg.go.dev/go/types#Config), but not from the command-line interface of gopackages.)

I agree this could be better documented, but I think the tool is working as intended.

**Comment by 4cq2** [comment]
ah OK yes that works, thanks - I will leave this open since it seems the documentation part is still a valid concern
