### ISSUE TITLE
cmd/compile: less export data

### ISSUE THREAD

**Issue by robpike** [golang/go#6110]
<pre>From the &quot;SPLASH&quot; talk:

&quot;[W]e measured the compilation of a large Google program written in Go to see how
the source code fanout compared to the C++ analysis done earlier. We found it was about
40X, which is fifty times better than C++ (as well as being simpler and hence faster to
process), but it's still bigger than we expected. There are two reasons for this. First,
we found a bug: the Go compiler was generating a substantial amount of data in the
export section that did not need to be there. Second, the export data uses a verbose
encoding that could be improved. We plan to address these issues.&quot;

Writing this down so it gets addresses. This was written a year ago but nothing has
happened.</pre>

**Comment by mdempsky** [comment]
I think this was addressed with the binary export format (mentioned by gri above) and later the indexed export format (e.g., ca2f85fd3f32b2a4c863a2de602876bd31e9d956). We currently use a compact binary format (rather than textual) and we're also better about only including necessary inlinable bodies (8684534321b0ebbc7ee0c5bf3bc3a3c19a196621).
