### ISSUE TITLE
x/pkgsite: Version lists seem to not always be up to date

### ISSUE THREAD

**Issue by rhalar** [golang/go#61312]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/goharbor/harbor
https://pkg.go.dev/github.com/goharbor/harbor/src/core/api

### What is your user agent?
Chromium or Firefox of some sort

### What did you do?
Visited the URLs above

### What did you expect to see?
See all releases present on https://github.com/goharbor/harbor in the version list on the pkg.go.dev page.

### What did you see instead?
The harbor module link stopped updating after version 1.8.6, which is listed as the latest release, even though it is a few years old now. The second URL does not list any versions at all, I am not sure if this is expected though.

Running
`go list -m -versions github.com/goharbor/harbor`

returns all of the expected versions, though with the `incompatible` suffix.

**Comment by gophun** [comment]
I don't see a go.mod in [github.com/goharbor/harbor](https://github.com/goharbor/harbor)

I see one under `src/`, but that constitutes a different module: https://pkg.go.dev/github.com/goharbor/harbor/src
This one doesn't have any version tags, because they would have to be prefixed with the subdirectory name: `src/vX.Y.Z`. Also, a version >= 2.0.0 would require a `/v2` suffix to the module path in the go.mod file.

It seems to me that the maintainer of harbor doesn't understand the interplay of go.mod files, versions, tags and module paths.

**Comment by seankhliao** [comment]
see above, I believe pkgsite is working as intended.
