### ISSUE TITLE
runtime: `fatal error: all goroutines are asleep - deadlock!` since 2023-07-18

### ISSUE THREAD

**Issue by prattmic** [golang/go#61454]
```
#!watchflakes
post <- `fatal error: all goroutines are asleep - deadlock!` && date >= "2023-07-18"
```

cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
This was most likely triggered by https://go.dev/cl/503923 for #60782.

However, my current thinking is that that CL is just exposing a pre-existing bug and making it more likely to occur.  Before that change, `netpollWaiters` was rarely zero.  The CL fixed the code so that `netpollWaiters` would be zero if there were in fact no waiters.

The scheduler has an optimization: it it doesn't bother to poll the network if `netpollWaiters` is zero.

The `netpollWaiters` count indicates the number of goroutines waiting for the network.  However, the count is currently adjusted before the goroutines are actually marked ready to run.  So there is a period of time when `netpollWaiters` is zero but the scheduler doesn't see any ready goroutines.  If `checkdead` is run during that period of time, it may think that the program is deadlocked.

Before the CL, when `netpollWaiters` was almost never zero, the last step in `findRunnable` is to call the network.  In the cases that fail there are no timers running, so `findRunnable` would block until there was some network activity.  That blocking is enough to prevent the deadlock detector from firing.  That gives the scheduler the time to collect the ready goroutines and mark them as ready to run.

Now that `netpollWaiters` can be zero, that last `findRunnable` step is not executed.  That opens up the gap in time when the deadlock detector can think that no goroutines are ready--because they haven't yet been marked as runnable.
