### ISSUE TITLE
cmp: package name collides with de facto stdlib 'go-cmp' 

### ISSUE THREAD

**Issue by bitfield** [golang/go#61535]
I missed the memo where `constraints` was renamed to `cmp`, but if I'd seen it, I would have pointed out that this name collides with an extremely widely-used package, [go-cmp/cmp](https://github.com/google/go-cmp). As in, for example:

```go
if !cmp.Equal(want, got) {
  t.Error(cmp.Diff(want, got))
}
```

Sure, the stdlib is privileged: it can name packages whatever it wants, and it's for third-party package authors to change _their_ names to avoid collisions. But, in this case, `go-cmp` was there first, and it's so commonly used I'd say it's part of the _de facto_ stdlib.

I'd like to see a `cmp` package in Go, and I'd like it to have the functionality of `go-cmp` (I think this has been proposed). Until then, I think it would be wise to keep this part of the namespace open.

**Comment by robpike** [comment]
The naming decision was discussed and made in the original proposal: https://github.com/golang/go/issues/59488. And as discussed at length in many places, package names have no uniqueness requirement, and it's easy to provide a distinct name in the import if there is a collision.

Note too that existing code will be unaffected because no existing code uses the new package.

This is truly not a problem.

**Comment by seankhliao** [comment]
as mentioned above, it was raised multiple times in the original proposal and addressed in https://github.com/golang/go/issues/59488#issuecomment-1554911781
