### ISSUE TITLE
cmd/cgo: offset generated as padding

### ISSUE THREAD

**Issue by cosnicolaou** [golang/go#61707]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes, and with head.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/cnicolaou/Library/Caches/go-build"
GOENV="/Users/cnicolaou/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cnicolaou/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cnicolaou/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cnicolaou/Dropbox/go-dev/go/src/go.mod"
GOWORK="/Users/cnicolaou/Dropbox/go-dev/go/go.work"
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d6/chtwn8h176z9_pf85ym_f_600000gn/T/go-build3910481843=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

While developing https://go-review.googlesource.com/c/go/+/503919 it is necessary to generate the go struct corresponding to the C struct vm_region_basic_info_data_64_t. Unfortunately the generated output is incorrect forcing a hand-edit of the generated code.

To reproduce the problem use:

cd $GOROOT/src/runtime/pprof
go tool cgo -godefs defs_darwin.go > tmp-go
diff defs_darwin_arm64.go tmp-go

### What did you expect to see?

The offset field in the original C struct should appear as Offset uint64 in the generated output.

### What did you see instead?

The generated code contains```Pad_cgo_0		[8]byte``` rather than the named field.

**Comment by mknyszek** [comment]
In triage, our theory is that because the `offset` field is defined as `memory_object_offset_t` (https://github.com/apple/darwin-xnu/blob/main/osfmk/mach/vm_region.h#L81C2-L81C24), cgo is just giving up because it can't find a header file or something.

**Comment by cherrymui** [comment]
But that is defined in mach/memory_object_types.h, which is #include'd in vm_region.h. I also tried manually #include mach/memory_object_types.h in defs_darwin.go but that didn't help either. Other fields are also have types from #include'd files, like `vm_prot_t`. Not sure why that one is different...

**Comment by ianlancetaylor** [comment]
It's an alignment problem.  The `offset` field is type `unsigned long long`.  In the C struct it appears at byte offset 20.  In Go the corresponding type is `uint64`.  A `uint64` field in Go is always aligned at an 8 byte boundary.  Therefore, the field can't be represented correctly in a Go struct, so cgo falls back to adding padding bytes.

The reason C is using a 4 byte alignment rather than an 8 alignment is because the struct is defined within the scope of a `#pragma pack(push, 4)`.  You can see this near the top of `<mach/vm_region.h>`.

Hand editing the code to change the type of field to `uint64` is going to produce a Go struct that does not match the C struct.  That is, passing an instance of the Go struct to C code will not pass the right values.  I see that a pointer is currently being passed to `mach_vm_region`; I would guess that Go sees the wrong values for the `Offset`, `Behavior`, and `User_wired_count` fields.

There is no really good workaround for this kind of thing.  One approach is to hand write the struct in defs_darwin.go, but write the `Offset` field as `[2]uint32`.  Then also pick up the struct from the C file as we do today.  Then write an `init` function that uses `unsafe.Offsetof` to verify that the field offsets are the same in the hand written struct and the C struct, and panic if they differ.  Normally the `init` function will compile down to nothing.   In the code that uses the `Offset` field, manually convert from `[2]uint32` to `uint64`.

Closing this issue because I don't think there is anything to do in the Go toolchain.  Please comment if you disagree.

**Comment by cherrymui** [comment]
Thanks. This makes sense. I forgot to check the alignment. I'll send a CL to change it back to [8]byte and convert to uint64 manually.

That said, would it be better for the cgo command to preserve the name `Offset`, instead of `Pad_cgo_0`?

**Comment by ianlancetaylor** [comment]
> That said, would it be better for the cgo command to preserve the name `Offset` even if the type is `[8]byte`, instead of `Pad_cgo_0`?

What's happening internally is that cgo says "I can't represent this C field, so I'm just going to drop it."  Then it moves to the next field, and says "this field is at offset 28, and to make that work I need to insert 8 bytes of padding."  That's why we wind up with `Pad_cgo_0` as the field name.

That said, sure, I think that for a case like this it would be feasible to keep the name `Offset`.  It might break some existing code, though.

**Comment by cosnicolaou** [comment]
At the very least a warning is warranted, either as a comment in the generated code or as an error message. If there is a lot of legacy code then maybe generate the new code as a comment with a flag to switch to the new behaviour.

eg.

// <field> is skipped because it cannot be represented in go as a <type> due to alignment rules, use -flag to include <field> as a byte array
Pad [8]byte

**Comment by cosnicolaou** [comment]
Or alternatively, add a -explain-alignments, that doesn't generate code, just explanations for the alignment decisions made. Either of these would have avoided the confusion here which thankfully you caught quickly, but I'd worry that similar errors are made in the broader go codebase.

**Comment by ianlancetaylor** [comment]
I honestly don't know how likely errors are, because `-godefs` is rarely used, and the default generated code should be safe to use.  The problem only arises when somebody hand edits the generated code.

**Comment by cosnicolaou** [comment]
Well, if there was even a warning about dropping the field because it
couldn’t be represented then I would have known to dig further and not
checked in broken code! The many other edits to generated code in the go
runtime suggest that generated code is a starting point rather than the
final code which undermines confidence in any such generated code. Anyway,
feel free to close this issue which hopefully will end being indexed.
Thanks for the help!


Cheers, Cos.

**Comment by cosnicolaou** [comment]
I’m not being sarcastic here, I really do mean thanks for the help with
getting this pr done!

Cheers, Cos.
