### ISSUE TITLE
Go compiler does not recognise it has to compile a package

### ISSUE THREAD

**Issue by sentinelb51** [golang/go#61994]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. It's consistent with 1.18 and 1.21.0 (which are the only versions I tested)

### What operating system and processor architecture are you using (`go env`)?
Windows 11 (amd64)
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Sentinel\AppData\Local\go-build
set GOENV=C:\Users\Sentinel\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Sentinel\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Sentinel\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Sentinel\AppData\Local\Temp\go-build1934835298=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I am creating a project with 2 directories: `handler` and `command`
In `handler` I have a `Command` struct, and a `NewCommand` function which are relevant to this issue.
Here is the code for NewCommand:

```go
func NewCommand(cmd *Command) *Command {
	if cmd.Name == "" {
		log.Fatalln("Command name cannot be empty")
	}

	if cmd.Callback == nil {
		log.Fatalln("Command callback cannot be nil")
	}

	_, exists := Commands[cmd.Name]
	if exists {
		log.Fatalf("Command %s already exists\n", cmd.Name)
	}

	Commands[cmd.Name] = cmd
	return cmd
}
```

The idea is that I use NewCommand to create instances of a command outside of the handler directory. NewCommand modifies a map called `Commands` which I then use later on.

So I try in `command`:

```go
var CmdUser = handler.NewCommand(&handler.Command{
	Name:        "user",
	Description: "Get information about a user",
	Callback: func(ctx *handler.Context) {
		fmt.Println("I was called.")
	},
})
```

However, the code inside `command` is never ran. In fact, it's like the compiler doesn't know it exists. I can type whatever I want inside there, and it will simply ignore it. I tested this by adding a print statement inside NewCommand to see if the function gets called; it never does.

**UNTIL** I reference something from the `command` package from somewhere else, like main.go:
```go
fmt.Printf("Hey compiler, did you know of %s?\n", command.CmdUser)
```

Then the compiler recognises the directory, and my code works as expected:

**Sample output without the main.go intervention:**
```
SYSTEM @ 20:43:47 instance.go:14: Fetching all instances...
SYSTEM @ 20:43:47 main.go:15: no commands to register
```

**Sample output with the main.go intervention:**
```
SYSTEM @ 20:48:03 instance.go:14: Fetching all instances...
Hey compiler, did you know of user?
  [VOID] 20:48:04 instance.go:111: Registering 1 commands
  [VOID] 20:48:04 instance.go:160: Instance started as VOID beta#6536
  [VOID v3] 20:48:05 instance.go:111: Registering 1 commands
  [VOID v3] 20:48:05 instance.go:160: Instance started as VOID v7#5737
```

### What did you expect to see?
I expected to see **Sample output with the main.go intervention:**

### What did you see instead?
I saw **Sample output without the main.go intervention:**

**Comment by seankhliao** [comment]
please provide a self contained reproducer, eg as a git repo.

**Comment by Jorropo** [comment]
@sentinelb51 this is expected and is how the go toolchain is meant to work, it compiles everything that is in the import graph.
If you want this to make theses registers this automatically the canonical way is to do `import _ "example.com/command"`.
See: https://grep.app/search?q=_%20%22&filter[lang][0]=Go

---

***IMO***, this is a terrible pattern:
- it is very *magic* :sparkles:, as in it makes hard to know where the fuck anything is for unfamiliar devs
- it makes it hard to maintain your project because instead of having a simple list of commands, imports do not have to centralised, this create situation where you import a new service which 4 imports down the line import new comands, and then you accidently expose some debug admin commands on production
- makes it very hard to be tested and mocked (because you rely on globals).
- it makes it very hard to customize anything or evolve your code, because the register code can just always run, things like options such as only provide certain commands for customers who pay.

I think you should consider dependency injection (without globals).

**Comment by bcmills** [comment]
This seems to be working as documented, per https://go.dev/ref/spec#Program_execution.
