### ISSUE TITLE
x/pkgsite: package removal request for [github.com/jefferyjob/go-redis-lock]

### ISSUE THREAD

**Issue by jefferyjob** [golang/go#62081]
### What is the path of the package that you would like to have removed?

github.com/jefferyjob/go-redis-lock

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

The original github warehouse has been deleted

**Comment by bcmills** [comment]
> The original github warehouse has been deleted

Presumably you still control the GitHub account. Can you recreate the repo to publish a retraction, as described in https://github.com/golang/go/issues/60985#issuecomment-1607712161?

**Comment by jefferyjob** [comment]
The version has not been revoked, and the license has not been updated

**Comment by bcmills** [comment]
@jefferyjob, the commit containing the `retract` directive needs to be tagged with a release version so that `cmd/go` can notice that the retraction is supposed to be live.

I would suggest adding `v1.1.1` to the `retract` directive and tagging the resulting commit as `v1.1.1` (which will then retract its own tag as well).
