### ISSUE TITLE
x/build/cmd/relui: go1.21.0.linux-armv6l built with GOARM=7

### ISSUE THREAD

**Issue by ksgriggs** [golang/go#62164]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21.0
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux raspberrypi 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux

Raspbian GNU/Linux 11 (bullseye)

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Illegal instruction
</pre></details>

### What did you do?

Installed go 1.21.0 onto two different Raspberry Pi zero w and get the same illegal instruction output when running go.
I installed https://go.dev/dl/go1.21.0.linux-armv6l.tar.gz.  Version 1.20.7 works.

1.   rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.0.linux-armv6l.tar.gz
2.    go version

### What did you expect to see?
When running "go version" I expected to see the go version output and not "illegal instruction"

### What did you see instead?

illegal instruction

**Comment by seankhliao** [comment]
seems like it was built with `GOARM=7` instead of `6`

```
go: go1.21.0
	path	cmd/go
	build	-buildmode=exe
	build	-compiler=gc
	build	-gcflags=cmd/...=-dwarf=false
	build	-trimpath=true
	build	DefaultGODEBUG=panicnil=1
	build	CGO_ENABLED=0
	build	GOARCH=arm
	build	GOOS=linux
	build	GOARM=7
```

The arm64 artifact by contrast has no explicit `GOARM` set

```
go: go1.21.0
	path	cmd/go
	build	-buildmode=exe
	build	-compiler=gc
	build	-gcflags=cmd/...=-dwarf=false
	build	-trimpath=true
	build	DefaultGODEBUG=panicnil=1
	build	CGO_ENABLED=0
	build	GOARCH=arm64
	build	GOOS=linux
```

cc @golang/release

**Comment by dmitshur** [comment]
Indeed, thanks for reporting.

It was set to GOARM=6 in 1.20 and older because the release target used the [linux-arm-aws builder](https://cs.opensource.google/go/x/build/+/master:internal/releasetargets/releasetargets.go;l=89-92;drc=5b87af8af145f2131e774b2b56216d8168b0421b), and that builder has GOARM=6 in [its environment](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=2944;drc=172906411707240281dc0fa12bfa932463ad4d69). For Go 1.21.0, it's built on a linux-amd64 builder via make.bash -distpack, and GOARM wasn't set in the release target's [environment explicitly](https://cs.opensource.google/go/x/build/+/master:internal/releasetargets/releasetargets.go;l=164-184;drc=5b87af8af145f2131e774b2b56216d8168b0421b).
