### ISSUE TITLE
spec: update unification rules [1.21 backport]

### ISSUE THREAD

**Issue by griesemer** [golang/go#62207]
Reminder issue to update unification rules per fix for #62157.

**Comment by dmitshur** [comment]
@griesemer Sorry, I just noticed this issue in the Go1.21.1 milestone now. It was missed earlier because it didn't have the usual CherryPickCandidate label and "[1.21 backport]" suffix (see https://go.dev/wiki/MinorReleases).

The release branches are have recently been frozen in the preparation for the upcoming minor release. Is it okay for this backport to land for Go 1.21.2 instead, or is it worth adding release-blocking label to make sure this is is reviewed for Go 1.21.1? Thanks.

**Comment by griesemer** [comment]
Yes that's fine. I haven't even gotten to this yet and it won't really impact anyone for real. There's no urgency.

(The changes are in the Appendix section of the spec.)

**Comment by thanm** [comment]
Hi @griesemer looking at the schedule for Go 1.21.2 I think we are supposed to have all cherry-picks done by this Tues in order to freeze the release branch Wed and pre-announce on Thu. Will the fix for this bug make the release do you think, or should we bump to 1.21.3? Thanks.

**Comment by griesemer** [comment]
Late here, but what is the status here?
I think this specific issue can be closed since we tend to direct people to the public (and thus latest) spec, rather than a downloaded version.

**Comment by cherrymui** [comment]
If we usually don't backport spec changes, I think we can close this. Thanks.
