### ISSUE TITLE
runtime: malloc flags should be subsumed by the type information provided to mallogc

### ISSUE THREAD

**Issue by lexprfuncall** [golang/go#6237]
<pre>Today, we pass flags to malloc to help it decide what constraints are required on the
storage allocated for an object.  However, all of this information can be derrived from
the type of an object.

For example, instead of passing the &quot;not pointers&quot; flag mallocgc can do a
&quot;no pointers&quot; allocation whenever it is passed a type which contains no point
values.

There are some flags which cannot be subsumed by the type information, this includes the
zeroing flag (sometimes we know we are going to initialize an object and do not need
zeroing) and the no invoke gc flag.  The &quot;no gc&quot; flag is a gray area, in
theory types could encode this information (for example, mspans, stacks) but today those
kinds of allocation have no type.  Maybe they should.</pre>

**Comment by martisch** [comment]
Current runtime malloc takes a type and derives the pointer or no-pointer properties from the type.
https://github.com/golang/go/blob/d83168eb385f7ae38710028fff5c84252267adbc/src/runtime/malloc.go#L903

This issue seems to have therefore been adressed sometime in the last 5+ years and can be closed.
