### ISSUE TITLE
os: Stdin.Stat().Size() always returns 0 with GOOS=wasip1 GOARCH=wasm

### ISSUE THREAD

**Issue by williamwebb** [golang/go#62392]
### What version of Go are you using (`go version`)?
<pre>
go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes, but only tested against `GOOS=wasp1 GOARCH=wasm`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOOS=wasp1 GOARCH=wasm
</pre></details>

### What did you do?
read Stdin, check stat.size
```
stdin := os.Stdin
stat, _ := stdin.Stat()
fmt.Println("size:", stat.Size())             
```
run via wasi runtime, piping input to stdin
```
echo "input" | wasmer run wasi_binary
```

### What did you expect to see?
size should match contents of stdin

### What did you see instead?
size of 0 is always returned

**Comment by dmitshur** [comment]
CC @golang/wasm.

**Comment by achille-roussel** [comment]
Hello @williamwebb, thanks for reporting the issue.

I believe that the behavior you expect is not something that Go can satisfy; the webassembly runtime is in charge of implementing host system calls such as the one involved in getting the size of an open file, the Go standard library (and in particular the `os` package in this case) only expose what the runtime returns.

in your example, it appears that wasmer returns a zero size for the standard input stream; this behavior will be the same regardless of the original programming language from which the webassembly module was compiled.

That being said, I was curious to explore how other platforms may behave, so I tested your code snippet:

* on darwin/arm64
```
$ echo input | go run main.go
size: 6
```

* on linux/amd64
```
$ echo input | go run main.go
size: 0
```

As you can see, programs that rely on the behavior of asking the size of stdin will not be portable across platforms; combinations of operating systems and webassembly runtimes will produce different results.

@dmitshur I believe we can close this issue since Go behaves as expected in this case.

**Comment by dmitshur** [comment]
Thanks for investigating this report.
