### ISSUE TITLE
log/slog: JSONHandler can produce empty groups

### ISSUE THREAD

**Issue by jba** [golang/go#62512]
In 1.21, a JSONHandler configured with a ReplaceAttr function that deletes all attributes can output empty groups. Handlers are supposed to drop empty groups.

Case 1: https://go.dev/play/p/323LJrdFALG
`slog.Info("hello", slog.Group("g", "a", 1)` outputs `{"g":{}}`.

Case 2: https://go.dev/play/p/RnacoygwUE9
`logger.WithGroup("g").Info("hello", "a", 1)` produces the same output.

This is hard to fix because we can't know that the group is going to be empty until after we call ReplaceAttr on all its members. That suggests that any fix is going to be expensive: we either have to compute the replaced attrs and store them somewhere to count them, or we have to write the group elements somewhere other than the main buffer, then copy that into the main buffer if non-empty. Another idea would be to write the group name and brace into the buffer as usual, but then if it turns out the group is empty, back up and erase what we wrote.

**Comment by seankhliao** [comment]
I opted for a write and rollback approach with I wrote mine https://github.com/seankhliao/svcrunner/blob/main/jsonlog/jsonlog.go

**Comment by jba** [comment]
Nice.

**Comment by dsnet** [comment]
In the [v2 JSON experiment](https://pkg.go.dev/github.com/go-json-experiment/json), we're aiming to change the definition of `omitempty` to elide a Go struct field if it marshals as a JSON null or empty JSON string, object, or array. That bit of detail doesn't help you since these are dynamically generated.

That said, the implementation of `omitempty` supports the ability to unwrite an empty object member:
https://github.com/go-json-experiment/json/blob/699550ab4a68a9d525a8d0b09d77125692a4c1d9/jsontext/encode.go#L239-L241

If `slog` one day switches over that implementation, we could look into exporting the `UnwriteEmptyObjectMember` member.
