### ISSUE TITLE
cmd/compile: Mac M1 bug

### ISSUE THREAD

**Issue by egonelbre** [golang/go#62725]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Mac M1

### What did you do?

```
package main

import (
	"math"
	"time"
)

func main() {
	period := uint(30)
	x := time.Time{}
	counter := int64(math.Floor(float64(x.Unix()) / float64(period)))
	counter2 := uint64(math.Floor(float64(x.Unix()) / float64(period)))
	println(counter, counter2)
	// Output: -2071186560 0
}
```

### What did you expect to see?

I would've expected `counter2 == 18446744071638365056`. It does work when running with `GOARCH=amd64 go run .`

**Comment by bcmills** [comment]
Per https://go.dev/ref/spec#Conversions, “In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.”

Since `uint64` cannot represent a negative value, the result here is implementation-dependent.

**Comment by egonelbre** [comment]
Ah, indeed I forgot about that.
