### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/kkrypt0nn/logger.go

### ISSUE THREAD

**Issue by kkrypt0nn** [golang/go#62726]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/kkrypt0nn/logger.go

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

Repository has been renamed, seeing it hasn't worked properly I've deleted it and created a new repository for the new name.

When visiting the page with the new name it's redirecting to the old one, same when using `go install ...`.

Currently created the repository again for the `retract` directive but unsure if that's accurate.

**Comment by kkrypt0nn** [comment]
> You should be able to add a `retract` directive in the `go.mod` file at the new location retracting the range of versions that were published for the old path.

How would that work if the old module had v1.0.0 and the new starts at v1.0.0 - means I would have to add the `retract` directive to the new repository, publish a higher version, remove the directive and publish a higher version?

**Comment by kkrypt0nn** [comment]
Both modules are separated at the moment in different repositories. One tagged version `v1.6.0` - on pkg.go.dev it's on [`v1.5.1`](https://pkg.go.dev/github.com/kkrypt0nn/logger.go@v1.5.1) and marked as retracted (which I want to be entirely removed) and the new one tagged [`v1.0.1`](https://pkg.go.dev/github.com/kkrypt0nn/acrux@v1.0.1) which I want to not redirect to the old one which it currently does.

**Comment by bcmills** [comment]
Unfortunately, due to the security properties of the checksum database, the contents of the version for a given repo path cannot be changed once it has been fetched and checksummed.

https://proxy.golang.org/cached-only/github.com/kkrypt0nn/acrux/@v/v1.5.1.info unfortunately shows that the proxy has already processed `v1.5.1` for that path, so the remaining options at this point are to pick up at `v1.6.0` or so (instead of `v1.0.0`), to `retract` the old versions pointwise and use the next patch number after the old version (`v1.0.2, v1.1.2, v1.2.1, etc.), or to abandon that repo path and start fresh with an entirely new one.

**Comment by kkrypt0nn** [comment]
So I could make a new tag `v2.0.0` for `acrux` and it would be just fine?

**Comment by kkrypt0nn** [comment]
That sounds amazing, I can live with the `v2`! Will do that tomorrow :)
