### ISSUE TITLE
cmd/compile: merge temporaries and named variables by GC shape

### ISSUE THREAD

**Issue by mknyszek** [golang/go#62737]
Once upon a time (~10 years ago) the Go compiler would merge temporaries on the stack (https://golang.org/cl/12829043). At some point, however, this optimization was removed. 

Stack space is generally cheap compared to heap space (since it doesn't generally increase the rate of garbage collection), but in some circumstances, the lack of merged temporaries can lead to a substantial amount of stack space waste.

Some applications have a lot of stacks floating around (e.g. Kubernetes' API server, via "watch" requests), in which case the cost is direct: additional memory use. Another cost is that a larger stack may means more stack growth, which takes CPU time. Lastly, the GC has to scan these stacks, and while the cost mostly proportional to the number of live pointers on the stack, the GC would still have less work to do overall for each stack.

Work by Uber and Kubernetes has shown that stack space overheads can be significantly reduced by manually re-scoping named variables.

It would be tricky to change the locations of pointers on the stack mid-function, but we can at least merge stack slots where the pointer/scalar data (GC shape) is the same. Credit to @mdempsky for the idea for reviving this.

This is a more general version of #62077, which focuses on aggregates.

**Comment by dmitshur** [comment]
Reopening since the fix in [CL 553055](https://go.dev/cl/553055) was rolled back in [CL 575236](https://go.dev/cl/575236).

**Comment by thanm** [comment]
I have a roll-forward CL currently being tested that should resolve the PPC64/S390x problems that caused the original CL to be reverted.

**Comment by thanm** [comment]
Postscript on this issue:  the CLs I've submitted enable merging of stack slots for disjointly accessed local variables. The optimization targets regular user-declared variables, variables that are imported into a function as a result of inlining, and most autotmp vars (we stay away from those created late in the SSA backend). The new optimization does not handle stack-allocated vars that are address-taken and read/written indirectly; I have some ideas on how to do this but it is a bit of a larger project.

One other note is that the merging/overlapping algorithm doesn't actually look at GC shape, this turns out to not be necessary. If you have two vars X and Y whose access patterns are entirely disjoint, then it will never be the case that both X and Y are live across a call, so putting them in the same stack slot is fine even if they have different types.

Closing out this issue.
