### ISSUE TITLE
x/crypto/openpgp: a signature verification method for PublicKey

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6328]
by **casey.marshall**:

<pre>Need to add a signature verification method to *PublicKey for newly added
*packet.UserAttribute, and a test case per
<a href="https://golang.org/cl/13464044/#msg3">https://golang.org/cl/13464044/#msg3</a>. (My current user attribute signature
verification is in Hockeypuck but really belongs here)

I'll add it as:

func (pk *PublicKey) VerifyUserAttributeSignature(signingKey *PublicKey, uat
*UserAttribute) { ... }</pre>

**Comment by FiloSottile** [comment]
Per the accepted #44226 proposal and due to lack of maintenance, the golang.org/x/crypto/openpgp package is now [frozen](https://golang.org/wiki/Frozen) and [deprecated](https://golang.org/wiki/Deprecated). No new changes will be accepted except for security fixes. The package will not be removed.

If this is a security issue, please email security@golang.org and we will assess it and provide a fix.

If you're looking for alternatives, consider the [crypto/ed25519](https://pkg.go.dev/crypto/ed25519) package for simple signatures, [golang.org/x/mod/sumdb/note](https://pkg.go.dev/golang.org/x/mod/sumdb/note) for inline signatures, or [filippo.io/age](https://pkg.go.dev/filippo.io/age) for encryption. You can read a summary of OpenPGP issues and alternatives [here](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html).

If you are required to interoperate with OpenPGP systems and need a maintained package, we suggest considering one of multiple community forks of golang.org/x/crypto/openpgp. We don't endorse any specific one.
