### ISSUE TITLE
runtime: allocated pages below zero on openbsd/riscv64

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#63385]
```
#!watchflakes
post <- log ~ `fatal error: allocated pages below zero` && goos == "openbsd" && goarch == "riscv64"
```

The openbsd/riscv64 port is regularly failing with errors like:

```
runtime: inUse=0 npages=4
fatal error: allocated pages below zero?
```

https://build.golang.org/log/bb95405e34149982611770caf632d58e9bc50ff4
https://build.golang.org/log/e5fb11bcae4d4dab31c13f7e271852e39ae5a6df

This seems particularly reproducible (although still intermittent) via the `TestArenaCollision` test:

```
$ ../bin/go tool dist test -run runtime:cpu124                                          
                                                                                                                  
##### Test execution environment.                                                                                 
# GOARCH: riscv64                                                                                                 
# CPU:                                                                                                            
# GOOS: openbsd                                                                                                   
# OS Version: OpenBSD 7.4 OpenBSD 7.4 (GENERIC.MP) #423: Tue Oct  3 07:33:24 MDT 2023     deraadt@riscv64.openbsd.org:/usr/src/sys/arch/riscv64/compile/GENERIC.MP  riscv64
                                                                                                                  
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick                                                                      
--- FAIL: TestArenaCollision (0.26s)                                                                              
    malloc_test.go:284: === RUN   TestArenaCollision                                                              
            malloc_test.go:301: reserved [0x60000000, 0x64000000)                                                 
            malloc_test.go:301: reserved [0x54000000, 0x58000000)                                                 
            malloc_test.go:301: reserved [0xa0000000, 0xa4000000)
            malloc_test.go:301: reserved [0x70000000, 0x74000000)                                                 
            malloc_test.go:301: reserved [0xc8000000, 0xcc000000)                                                 
        runtime: inUse=0 npages=1                                                                                 
        fatal error: allocated pages below zero?
```

`inUse` always appears to be zero, while `npages` is some small positive value.

It would seem that this is specific to openbsd/riscv64 and possibly even a kernel/mmap related problem.

/cc @mknyszek any pointers in tracking this down would be greatly appreciated.

**Comment by mknyszek** [comment]
Hm, unfortunately this doesn't seem like it would be a kernel/mmap problem. This is a check that's failing when one or more pages are freed back to the page heap. What's happening is that some of the bookkeeping maintained per 4 MiB aligned address range indicates that the region is totally free, so it doesn't make sense to try and free memory back to it. I think it implies some kind of corruption of the data structure, or a data race. It could also mean that when the check *isn't* firing, some pages are getting allocated twice (which could lead to other memory corruption symptoms).

It may just be reproducing in `TestArenaCollision` because it allocates a whole bunch of memory and likely triggers a GC (causing other memory to be freed, since all the memory it allocates stays live indefinitely).

If this is straightforward to reproduce, my first thought would be to pepper debuglog calls around the various allocs and frees to the page heap and make sure nothing is being allocated (and thus later possibly freed) twice.

If you haven't used debuglog before, it's a very handy low-overhead tool for identifying what actually happened in the runtime. Because it's low overhead, it maintains a low chance of perturbing bugs involving race conditions and tends to reproduce real thread orderings. You can enable it by passing `-tags debuglog` to `go test` or `go build`. You use it in the runtime by calling `dlog().s("string example").u64(5).end()` from almost anywhere in the runtime. The only place you might run into trouble is trying to call it from signal handlers. It's safe, but you may run out of nosplit stack space. Don't forget to call `.end()`!

**Comment by 4a6f656c** [comment]
@mknyszek many thanks for the pointers (especially re debuglog!) - I managed to find some time to investigate further and finally tracked the issue down to a bug that was introduced in 91f863013e6. In summary, the min index value is incorrectly updated, which results in an in-use part of the chunk backing store being remapped and zeroed. Thankfully building the runtime test and then running `TestArenaCollision` in a loop was sufficient to reproduce the problem.

The bug effectively boils down to an incorrect `haveMin == 0` test when updating the minimum index - this is triggered when the base addresses for page allocations are low, then higher and then lower again:

```
[0.000000000 P -1] scavengeIndex.sysGrow base 2080374784 limit 2084569088
[0.000000000 P -1] scavengeIndex.sysGrow have base 5681364992 size 0 min 0 max 0 need base 5681364992 size 4096 min 0 max 512
--
[0.025940577 P 0] scavengeIndex.sysGrow base 2483027968 limit 2487222272
[0.025943577 P 0] scavengeIndex.sysGrow have base 5681364992 size 4096 min 0 max 512 need base 5681369088 size 4096 min 512 max 1024
--
[0.038413604 P 0] scavengeIndex.sysGrow base 1476395008 limit 1480589312
[0.038416354 P 0] scavengeIndex.sysGrow have base 5681369088 size 4096 min 512 max 1024 need base 5681364992 size 4096 min 0 max 512
```

During the second `scavengeIndex.sysGrow` min is incorrectly changed from 0 to 512, which then results in the third call believing that the [0, 512) range is not yet allocated. It then sysMaps that region zeroing all of the existing chunk data.

I'm still somewhat perplexed by the fact that this only ever seems to be hit on openbsd/riscv64 - it would make sense if it was all 64 bit OpenBSD architectures, since they randomise memory allocations, which could lead to this allocation pattern.
