### ISSUE TITLE
spec: iota and constant expressions

### ISSUE THREAD

**Issue by petar-dambovaliev** [golang/go#63391]
Hello,

by reading the spec section on [constant expressions](https://go.dev/ref/spec#Constant_expressions) and [iota](https://go.dev/ref/spec#Iota) i didn't understand the behavior currently exists with the Go compiler.
In my opinion, the spec should define how mixing in tuple and none tuple constants behave.

For example, the first line has a tuple `A` and `B`.
The second line has a single constant `C`, which a tuple cannot be assigned to.
Therefore, it seems that the rule is, in such a case the compiler requires a right hand side expression.
Thus, the following code does not compile.

```go
const (
   A, B = iota, iota
   C
)
```

Also, the spec mentions `Its value is the index of the respective [ConstSpec](https://go.dev/ref/spec#ConstSpec) in that constant declaration, starting at zero.` but there is no example of this behavior.
It might be useful to add it to the examples.

In the following code, `A` and `B` will both have 0 values and `C` will have a value of 1.

```go
const (
   A, B = iota, iota
   C = iota
)
```

**Comment by Deleplace** [comment]
A, B, C being 0, 0, 1 surprised me!

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by petar-dambovaliev** [comment]
@ianlancetaylor @griesemer after talking to several experienced Go programmers on the Go slack workspace, it seems quite a lot of them were surprised at this behavior. If we agree that this needs to be added to the spec (i hope, i have the honors to do so 😄 ), it would probably help to prevent some bugs and/or confusion.
I am currently making a VM for Go and although there aren't many people implementing the language, it would be nice to have a well defined spec.

**Comment by griesemer** [comment]
@petar-dambovaliev `iota` doesn't increase with each mention, otherwise one couldn't write "coupled" constants that depend on the same iota value. Instead, `iota` increases with each `ConstSpec`. The spec is pretty clear about it and has [many examples](https://golang.org/ref/spec#Iota), so I don't know what you mean with "there is no example of this behavior".

Mixing "mixing in tuple and none tuple constants" is completely orthogonal to the use of `iota` - it simply makes most sense together with `ioata`. Either way, it's also well defined. Per the [spec](https://golang.org/ref/spec#Constant_declarations):

> Within a parenthesized const declaration list the expression list may be omitted from any but the first ConstSpec. Such an empty list is equivalent to the textual substitution of the first preceding non-empty expression list and its type if any. Omitting the list of expressions is therefore equivalent to repeating the previous list. The number of identifiers must be equal to the number of expressions in the previous list.

So obviously one cannot simply change the number of the LHS constant names w/o changing the number of the RHS expressions (which may be implicitly copied down).

I also note that all this has been hashed out in great details years ago and hasn't really caused problems since.
Yes, the spec is terse, but it's meant as a reference, not a tutorial.

Unless you can point me specifically at a conflict in the spec or a behavior that is not implied by the spec phrasing I am inclined to close this issue. Thanks.
