### ISSUE TITLE
cmd/compile: error message should not mention -lang when //go:build set file version

### ISSUE THREAD

**Issue by rsc** [golang/go#63489]
```
% cat go.mod
go 1.21

module m
% cat x.go
//go:build go1.4

package p

const c = 0o123
% go build
# m
./x.go:5:11: 0o/0O-style octal literals requires go1.13 or later (-lang was set to go1.21; check go.mod)
% 
```

The parenthetical misleads. It should say something like "(file declares //go:build go1.4)" or just be removed unconditionally.

**Comment by cuonglm** [comment]
How about making the error more generic, something like:

```
./x.go:5:11: 0o/0O-style octal literals requires go1.13 or later (check go.mod or //go:build tag)
```

**Comment by mdempsky** [comment]
@cuonglm I think it's worthwhile to keep the current language version in the error message. For example, if the error message for Russ's example mentioned "go1.4", then users can grep for occurrences of that string to find immediately what needs to be changed.

Also, the compiler knows whether the version was set by -lang or //go:build, so I think we should just tell users which file it came from, rather than making them look in both places.

**Comment by cuonglm** [comment]
> Also, the compiler knows whether the version was set by -lang or //go:build, so I think we should just tell users which file it came from, rather than making them look in both places.

Yeah, I realized that now we have `types2Info.FileVersions` after my comment.
