### ISSUE TITLE
encoding/csv: reader runs out of memory on Windows 32-bit

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6352]
by **gaijin.shenoy**:

<pre>When processing a large (2.6 GB) CSV file on Windows 32-bit, using the encoding/csv
package, the program fails after approximately 530,000 lines (each line is approximately
840 characters with 175 fields).

What steps will reproduce the problem?
Run attached program that simply reads an entire file without doing anything else on a
large CSV file (as per above)
<a href="http://play.golang.org/p/slFg6cS8o4">http://play.golang.org/p/slFg6cS8o4</a>

What is the expected output?
Should complete without errors

What do you see instead?
fatal error: runtime: cannot map pages in arena address space

Which compiler are you using (5g, 6g, 8g, gccgo)?
8g

Which operating system are you using?
Windows XP

Which version are you using?  (run 'go version')
1.1.2

Please provide any additional information below.</pre>

**Comment by rsc** [comment]
This out of memory appears to have been caused by reading the entire input as one row, because of a bad quote in the input file. There's not much we can do about that: maybe there really is a 2.6 GB string in that field. This bad input was semantically indistinguishable from a very large valid input, and in general we don't try to harden APIs like this against very very large inputs.
