### ISSUE TITLE
compiler: "type parameter K is not comparable with <" when the parameter is comparable

### ISSUE THREAD

**Issue by meling** [golang/go#63523]
### What version of Go are you using (`go version`)?

<pre>
$ GOEXPERIMENT=range gotip version
go version devel go1.22-2fba42cb52 Wed Sep 20 14:52:38 2023 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

It reproduces in the playground (dev branch). It is not relevant for the latest release since the code depends on for-range-func.

### What did you do?

Tried to compare the key K of a map with a field in a struct. Both are `comparable` and of the same type. See the [reproducer code](https://go.dev/play/p/_GwwFSLSLrk?v=gotip).

### What did you expect to see?

That the code would compile since the parameter K is comparable.

### What did you see instead?

The code fails to compile:

```
./prog.go:41:26: invalid operation: k < prefix.Start (type parameter K is not comparable with <)
./prog.go:41:46: invalid operation: k >= prefix.Limit (type parameter K is not comparable with >=)
```

**Comment by ianlancetaylor** [comment]
It's not a great error message.  In Go a constraint of `comparable` means that values may be compared using `==` and `!=`.  In order to compare with `<` the type must be ordered.  There is a limited number of ordered types; you can use [`cmp.Ordered`](https://pkg.go.dev/cmp#Ordered) as a type constraint to permit any ordered type as a type argument.

**Comment by meling** [comment]
Here is a [simplified reproducer](https://go.dev/play/p/IRpHY6Cm1AE).

**Comment by ianlancetaylor** [comment]
I filed #63524 to improve the error message.
