### ISSUE TITLE
cmd/compile: "constant V overflows T" now reported as "cannot convert V to type T"

### ISSUE THREAD

**Issue by odeke-em** [golang/go#63563]
### What version of Go are you using (`go version`)?
Go1.21

### Does this issue reproduce with the latest release?

Yes

### What did you do?
I ran this program
```go
package main

import "fmt"

const maxInt = 18446744073709551614

func main() {
	fmt.Printf("%d => %d\n", int64(maxInt), int64(maxInt*2))
}
```

which prints out

#### Go1.21.1
```shell
./main.go:8:33: cannot convert maxInt (untyped int constant 18446744073709551614) to type int64
./main.go:8:48: cannot convert maxInt * 2 (untyped int constant 36893488147419103228) to type int64
```

#### Go 1.17
```shell
./main.go:8:32: constant 18446744073709551614 overflows int64
./main.go:8:47: constant 36893488147419103228 overflows int64
```

### What did you expect to see?
The old message until Go1.17 was much clearer

### What did you see instead?

A clear message about an overflow

**Comment by mdempsky** [comment]
I agree that technically we've lost some error message details here. The compiler used to specifically report that the issue was the constant value wasn't representable as the converted-to type, whereas now it just reports that the expression can't be converted to the type without mentioning why not.

The only reason an untyped constant can't be converted to a type is because it's not representable in that type, but non-expert users may not know that.

Maybe we can tweak the wording slightly to clarify the conversion is not allowed because of overflow or that the value isn't representable? (Note that if the destination type is instead a user-defined type like MyInt, it's not obviously apparently from the error message what the representable set of values is for the named type.)

/cc @griesemer @findleyr @alandonovan
