### ISSUE TITLE
x/build/dashboard: add OpenBSD 7.3 and 7.4 builders (for 386, amd64)

### ISSUE THREAD

**Issue by mauri870** [golang/go#63568]
OpenBSD 7.4 [has been released](https://www.openbsd.org/74.html).
This is a tracking issue for adding OpenBSD 7.3 and 7.4 builders for amd64 and 386 architectures.

CC @golang/release, @golang/openbsd.

**Comment by mauri870** [comment]
@gopherbot add Builders, NeedsFix, new-builder, OS-OpenBSD

**Comment by dmitshur** [comment]
Also see #61090 and #61122.

**Comment by mauri870** [comment]
@dmitshur Thanks. Is there anything I could do to help get these LUCI builders up for openbsd? I have to admit that I don't know much about LUCI builders at all, but it appears that we are discontinuing the old builders so we need to get this sorted at some point.

**Comment by dmitshur** [comment]
Yes, you can find more context on the builder migration to LUCI in #63471, and especially in the https://go.dev/wiki/DashboardBuilders#luci-builders page it links to.

For openbsd/amd64, there's already a builder in LUCI that uses the "openbsd-amd64-72" image (#61090), so I think this would be mostly a matter of creating equivalent "openbsd-amd64-7{3,4}" images, and configuring them in LUCI. That is, the equivalent of [CL 535755], but in the [luci-config](https://go-review.googlesource.com/q/repo:build+branch:luci-config) branch of x/build. We'll have to sort out the exact details since this might be the first OS update we're doing for an existing LUCI builder.

For openbsd/386, the LUCI builder and its image still need to be built (#61122), so this could be a good starting point. Again, start at #63471 and try to follow the directions there, and post on the issue as you make progress.

Thanks for your help with moving these builders forward.

**Comment by 4a6f656c** [comment]
OpenBSD 7.3 and 7.4 are no longer supported releases, closing in favour of https://github.com/golang/go/issues/69823

**Comment by dmitshur** [comment]
Marking this as "not planned" so the issue outcome is more visible at a high level.
