### ISSUE TITLE
x/tools/gopls: a replacement for guru's whicherrs

### ISSUE THREAD

**Issue by danp** [golang/go#63574]
The guru command used to have a [`whicherrs`](https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit#heading=h.fy71cgl3pqh2) query that:

> reports the set of possible constants, global variables, and concrete types that may appear in a value of type error.

In our work projects we try and follow the [Whether to wrap](https://go.dev/blog/go1.13-errors#whether-to-wrap) section of the Working with Errors in Go 1.13 blog post. We have some legacy code that we've had to convert to wrapping unconditionally and something like `whicherrs` would greatly help us understand where it's safe to stop doing that.

**Comment by findleyr** [comment]
Thanks for filing. @adonovan has also recently lamented the loss of some guru features.

It would be fun to have a mini project to reimplement some of these features in the LSP. Perhaps a good candidate for an upcoming team code jam.

**Comment by adonovan** [comment]
Clever though it was, `whicherrs` was one of many features of guru that relied on pointer analysis, which we made the decision to stop supporting because of the inherent problems of that technology described in https://github.com/golang/go/issues/59676. So I don't think this is a feature of guru that anyone should attempt to bring back, at least not using its previous approach.
