### ISSUE TITLE
x/build: configure TryBots for google.golang.org/protobuf 

### ISSUE THREAD

**Issue by hoeppi-google** [golang/go#63597]
Changes to the google.golang.org/protobuf module are currently not automatically tested before submission. It would be great if we could add TryBots for the repo. Testing for linux amd64 should be sufficient.

**Comment by dmitshur** [comment]
The trybots (and post-submit builders) have been turned up for this repo in [CL 540496](https://go.dev/cl/540496).
The permissions have been updated to require a passing trybot result in [CL 540478](https://go.dev/cl/540478).

Please don't hesitate to let us know if you run into problems, or something doesn't work as expected.

**Comment by stapelberg** [comment]
Thank you @dmitshur for setting this up!

AFAICT, the current configuration is to run "go test -short". 

That’s a good first signal, but we also have an integration test that’s started by running https://github.com/protocolbuffers/protobuf-go/blob/master/test.bash, which we would like to run automatically.

Would that be possible to configure as well? Thanks.

**Comment by dmitshur** [comment]
That seems reasonable to me, especially since this repo only has Linux builders enabled so far, and would save you the trouble of having to opt-in to a longtest builder on each CL via [slowbots](https://go.dev/wiki/SlowBots). Mailed [CL 540278](https://go.dev/cl/540278).

**Comment by dmitshur** [comment]
That's done.

If at some point you think it might make sense to test on more than just Linux, please feel to open a new issue to figure out those details.

**Comment by stapelberg** [comment]
Thanks for setting up the longtest.

However, I think the longtest might just be doing `go test` (without `-short`), which is not sufficient to run the protobuf repository’s integration test. 

https://github.com/protocolbuffers/protobuf-go/blob/master/test.bash explicitly runs integration_test.go, which is marked as `//go:build ignore` and is not included in `go test`.

Can we get a `./test.bash` run as well please?

**Comment by dmitshur** [comment]
Apologies, I read your comment quickly and failed to realize there was more to getting the integration test started by tesh.bash to run than just configuring longtest builders to always run.

I took a look at what it might take to make it work in [CL 541123](https://go.dev/cl/541123), and the good news are that I think there's a good path forward. It's passing on a Linux machine I tried it on in about 7 minutes with a clean cache, and in about 9 minutes with -race flag, but not yet on our LUCI builders because of a problem with bazel dependency, which I want to discuss. I opened #64066 to track that work, so let's continue the conversation there. Thanks.

Closing this issue with the scope limited to turning on basic builders in LUCI.
