### ISSUE TITLE
x/build: add LUCI netbsd-arm64 builder

### ISSUE THREAD

**Issue by bsiegert** [golang/go#63614]
Hostname: rpi4.bentsukun.ch
[rpi4.bentsukun.ch.csr.txt](https://github.com/golang/go/files/13030815/rpi4.bentsukun.ch.csr.txt)

There are two machines in this builder. Should I add a second CSR for the other one, or should they share a hostname and CSR?

**Comment by cagedmantis** [comment]
cc @golang/release

**Comment by cagedmantis** [comment]
@bsiegert Yes, `netbsd-arm64-bsiegert` would be a better hostname for the CSR.

**Comment by bsiegert** [comment]
Sorry for the misunderstanding then. New CSR: [netbsd-arm64-bsiegert.csr.txt](https://github.com/golang/go/files/13063056/netbsd-arm64-bsiegert.csr.txt)

**Comment by dr2chase** [comment]
Here is the certificate. 
[netbsd-arm64-bsiegert-1698683802.cert.txt](https://github.com/golang/go/files/13207758/netbsd-arm64-bsiegert-1698683802.cert.txt)

**Comment by bsiegert** [comment]
The swarming bot is now running on one machine. Are you able to see it?

**Comment by heschi** [comment]
Yep!

Unfortunately it seems to believe that its CPU architecture is `evbarm`, which is an exciting new way to spell `arm64`. Is there some Python 3 API we could call that would return `arm64`? Or do we need to map it ourselves?

**Comment by bsiegert** [comment]
Haha! In NetBSD terminology, the port is called `evbarm-aarch64`. `evbarm` is "ARM evaluation board".

In Python, you can get these names as follows:

```
>>> platform.processor()
'aarch64'
>>> platform.machine()
'evbarm'
```

On the 32-bit ARM builder, you instead get:

```
>>> platform.processor()
'earmv7hf'
>>> platform.machine()
'evbarm'
```

From http://wiki.netbsd.org/ports/evbarm/:

> Various CPU variants are supported, e.g:
> 
>  -   earmv6hf - ARMv6-A with EABI and hardware floating point, e.g. the original Raspberry Pi.
    earmv7hf - ARMv7-A with EABI and hardware floating point, e.g. most recent and common 32-bit ARM boards. Supports up to 8 CPUs.
> -   earmv7hfeb - Same as the above, but with the CPU running in big endian mode.
> -   aarch64 - 64-bit ARMv8-A boards, e.g. all 64-bit hardware. Fully 64-bit kernel and userland. Running 32-bit binaries is supported with compat32.
> -   aarch64eb - Same as the above, but with the CPU running in big endian mode.

**Comment by bsiegert** [comment]
So for the ones Go cares about:

- `platform.processor()` = earmv7hf: arm
- `platform.processor()` = aarch64: arm64

**Comment by dmitshur** [comment]
Now that the swarming bot is correctly reporting `cipd_platform = netbsd-arm64` ([crrev.com/c/5013353](https://crrev.com/c/5013353), thanks @heschi) and the builder definitions are added ([go.dev/cl/545536](https://go.dev/cl/545536)), it's up and running!

https://ci.chromium.org/ui/p/golang/g/z-port-netbsd-arm64/builders
https://chromium-swarm.appspot.com/bot?id=netbsd-arm64-bsiegert

It's passing on release-branch.go1.20 and many golang.org/x repos, and reporting failing tests at tip.

I think we can close this tracking issue since the builder is up and use new issues for everything else. Thanks very much @bsiegert!
