### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by 1AderoWycliff** [golang/go#63840]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
write a code

package main 
import "fmt"
func iterativecalculation (index int) int{

	result := 0
	for i := o ; i < index + 1 ; i++{

		result := result + 1
	}
	func main () {

		result := 0+1+2+3+4+5+6+7+8+9+10
		fmt.Println(result1)
		resulr2 := iterativecalculation(10)
		fmt.Println("the result of the iterative function is : %v, result2")
	}

### What did you expect to see?

55

### What did you see instead?

unexpected main

**Comment by shashaneRanasinghe** [comment]
Hi, There seem to be a few issues with your code.

The output that you get which is 'unexpected main' is since you have an unclosed bracket at the end of the 'iterativecalculation' function.

Additionally there are a few more compilation errors.

In line 5, in the for loop, it should be '0' (zero)  instead of 'o'
In line 6, you have used := (colon equals), instead of = (equals), we use := when we are declaring a new variable, which you have done in line 4, In line 6 what do we need to do is assign the updated value to the variable result, therefore we need use =
Also since the function is returning a value, which is an int in this case, we have to return an int, result in this case.

In the main function
In the Second line, you have printed out, result1, a variable which has not been declared before, therefore it gives an complilation error, What you need to do in your case is that you need to print out result instead.
In the last line you have again printed an undeclared variable, also the closing quotes( ") should be before the variable name. and if you want to use formated strings, you can use fmt.Printf instead of fmt.Println.

You might also need to check the logic of the iterativecalculation function.

Checkout the sample code below for better understanding

`package main

import "fmt"

func iterativecalculation(index int) int {

	result := 0
	for i := 0; i < index+1; i++ {

		result = result + i
	}
	return result
}
func main() {

	result := 0 + 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10
	fmt.Println(result)
	result2 := iterativecalculation(10)
	fmt.Printf("the result of the iterative function is : %v", result2)
}`

Hope you find this helpful
