### ISSUE TITLE
all: stop using indirect system calls on openbsd

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#63900]
The indirect syscall call interface ([syscall(2)](https://man.openbsd.org/syscall.2)) will be [removed from OpenBSD](https://marc.info/?l=openbsd-tech&m=169841790407370&w=2), most likely before the 7.5 release. This effectively means that Go's `syscall.Syscall*` interfaces will no longer work on this platform and that direct system calls (using the appropriate libc system call stub) will need to be used instead.

**Comment by jrick** [comment]
I would perhaps reword this issue, as "direct system calls" could be misinterpreted to mean applications performing syscall instructions in their text, instead of using the particular libc stubs.

When we started requiring libc for system calls in dynamically linked executables, I believe that was also referred to switching away from "direct system calls".
