### ISSUE TITLE
cmd/trace: port to v2 traces [freeze exception]

### ISSUE THREAD

**Issue by felixge** [golang/go#63960]
Tracking issue for updating cmd/trace for the v2 overhaul (https://github.com/golang/go/issues/60773) in [CL 538515](https://go-review.googlesource.com/c/go/+/538515).

Main Viewer:

- [x] Basic P Lanes with G slices
- [x] Heap Metrics
- [x] Thread Metrics
- [x] Goroutine Metrics
- [x] Trace Splitting
- [x] GC Lane
- [x] [STW Events](https://go-review.googlesource.com/c/go/+/538515/19..20)
- [x] [Proc Start/Stop Events](https://go-review.googlesource.com/c/go/+/538515/20..21)
- [x] [Syscalls](https://go-review.googlesource.com/c/go/+/538515/27..28)
- [x] [Flow Events](https://go-review.googlesource.com/c/go/+/542218/4..5)
- [x] [focustask Filter](https://go.dev/cl/543596)
- [x] [taskid Filter](https://go.dev/cl/543937)
- [x] [goid Filter](https://go.dev/cl/543595) ([Plus some refactoring work.](https://go-review.googlesource.com/c/go/+/542218/7..9))
- [x] [Network Lane](https://go-review.googlesource.com/c/go/+/542218/2..3)
- [x] [GWaitingGC State](https://go-review.googlesource.com/c/go/+/542218/1..2)
- [x] [CPU Samples](https://go-review.googlesource.com/c/go/+/542218/6..7)
- [ ] Add `totalDuration` arg for blocking syscalls (nice-to-have, see [comment](https://github.com/golang/go/issues/63960#issuecomment-1806101329))

Sub-Pages:

- [x] PPROF ([CL 541999](https://go.dev/cl/541999))
- [x] MMU ([CL 541258](https://go.dev/cl/541258))
- [x] Goroutine Analysis ([CL 541257](https://go.dev/cl/541257))
- [x] Tasks ([CL 542077](https://go.dev/cl/542077))
- [x] Regions ([CL 542077](https://go.dev/cl/542077))

cc @mknyszek

**Comment by heschi** [comment]
cc @golang/runtime

**Comment by mknyszek** [comment]
@golang/release

Hey release folks, I'd like to request a freeze exception for this work. It's a little early and there's a solid chance that we'll get this all done before the freeze rolls around, but I wanted to get this on your radar ASAP.

My reasoning for the freeze exception is as follows:

This is a blocker for enabling the new execution tracer (https://github.com/golang/go/issues/60773) by default, because we shouldn't ship a runtime that produces traces that users have no tooling for.

However, this codebase is far from mission-critical. If it has bugs, it's not going to break any production services. The new execution tracer on the other hand is in good shape and will easily land before the freeze.

Simultaneously, because the new execution tracer work is largely targeting developers that build services for other developers, asking downstream users to set a `GOEXPERIMENT` is a fairly high hurdle to overcome, and would effectively delay building on top of the new foundation from February to August.

Note that I'm also suggesting to enable the new execution tracer by default after the freeze window. While this seems risky, I designed the new tracer's tests to run even if the `GOEXPERIMENT` is disabled, so we'll still get exactly the same coverage from CI until cmd/trace is fully finished. I can also easily expand this testing to running several std packages' tests under the new tracer and validating the results if that would help ease concerns about test coverage.

I propose we also set a hard cutoff on this work at the first release candidate. If we can't get it done by the time the release candidate is being built, then we'll drop it for Go 1.22.

Note that we can still land all the in-progress changes before then (to avoid carrying an inventory of unsubmitted CLs) because cmd/trace selects its behavior based on the trace version. As a result, it'll still work exactly the same for old traces; cmd/trace will only be left in a partially-working state for new traces. This further reduces the risk and provides us with an easy off-ramp.

**Comment by heschi** [comment]
Approved if needed: we don't expect to get a lot of coverage of this feature before RC1 anyway, so as long as it lands before that it should be okay. However, please try to test with large-scale Google services as early as possible.

**Comment by felixge** [comment]
Syscall rendering now works. Instead of rendering them as instant events, they are now rendered as slices. For example:

![CleanShot 2023-11-10 at 18 02 15@2x](https://github.com/golang/go/assets/15000/36f04294-a548-4df1-afa8-9bfe2ec580c4)

For blocking syscalls, only the time they are executing on a P (before sysmon declares them "blocking") is displayed on the P lane. The Arg label "blocked" indicates that the syscall got blocked:

![CleanShot 2023-11-10 at 18 00 53@2x](https://github.com/golang/go/assets/15000/ac265dd6-a582-4ec1-bb30-a1c80b8ad66b)

While typing this I realize that it might be nice to display the `totalDuration` of blocked syscalls. I added it as a nice-to-have item in the list above.
