### ISSUE TITLE
x/pkgsite: Golang GC Time And Memory limit 

### ISSUE THREAD

**Issue by VEDANTDOKANIA** [golang/go#64004]
Server specification
32 core 64 GB , linux ubuntu 22
Memory limit set (75%) 48 GB

Go version - 1.21
I have a live application built in golang . One of the problems we are facing is with golang GC. As soon as our heap touches 30 GB the application starts running GC with GC pause greater than 1 sec , but my system has enough memory than GC should not run in that case as per my understand . Can anyone suggest me what other GC parameter should be set and why issue is there . And also how much time go takes to free certain amount of me? 
@cherrymui  can you pls help us in the same

**Comment by cherrymui** [comment]
> Memory limit set (75%) 48 GB

Do you mean you set environment variable `GOMEMLIMIT` to 48 GiB ? If not, you may want to try setting it.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. See https://golang.org/wiki/Questions . You may want to ask on a forum or another channel.

Closing this issue as this sounds like a question. If you think there is an actual bug, please follow the issue template and provide more information, like what your application is and does, what is the expected behavior and what you saw. For a GC issue, some GC trace or execution trace may be helpful. Thanks.
