### ISSUE TITLE
x/tools/gopls: prioritise explicit upper case matches in completion results

### ISSUE THREAD

**Issue by alecthomas** [golang/go#64224]
In the general case I can see why case-insensitive completion makes sense, but if I've explicitly provided an upper case letter I would expect it to prioritise exact matches.

<img width="485" alt="image" src="https://github.com/golang/vscode-go/assets/41767/d4992e87-83af-4f19-a8fc-350f1a2ead6c">

What's even stranger is that without entering any text at all, `Name` is the first option:

<img width="397" alt="image" src="https://github.com/golang/vscode-go/assets/41767/547a5085-f391-4799-90c5-9a16d525f6c6">

**Comment by muirdm** [comment]
There is a bonus for case sensitive match already [here](https://github.com/golang/tools/blob/98b4b1465a8eaf97f19c711ed90a25473be6d268/internal/fuzzy/matcher.go#L284). I think the problem is we use the same bonus for matching the first letter of a segment, so the match bonus doesn't differentiate the case in this issue. It might work to just split those apart into separate bonuses.
