### ISSUE TITLE
iter: add GOEXPERIMENT=rangefunc-limited version [freeze exception]

### ISSUE THREAD

**Issue by rsc** [golang/go#64277]
CL 543319 needs to be submitted for the release.

**Comment by heschi** [comment]
cc @golang/release

**Comment by mknyszek** [comment]
@cherrymui and @heschi both looked at https://go.dev/cl/543319 and concluded that it has no effect with the experiment disabled, so it's safe to land after the freeze.

@rsc in the release meeting, we'd appreciate it if you could elaborate on the justification in the issue, but otherwise the freeze exception is tentatively accepted.

**Comment by rsc** [comment]
The justification is that this change is necessary for people to try GOEXPERIMENT=rangefunc and see the high-performance iter.Pull that we expect rather than the low-performance one that can be implemented without runtime changes. The changes are limited to the implementation of iter.Pull - if you're not using it, there is no risk. And the change are only visible when using GOEXPERIMENT=rangefunc - if you don't set it, you can't get at any of this code. So the risk to the overall release is as close to zero as a change can be.
