### ISSUE TITLE
internal/chacha8rand: tests failing on big-endian builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#64284]
```
#!watchflakes
post <- (goarch == "ppc64" || goarch == "mips" || goarch == "mips64" || goarch == "s390x") && pkg == "internal/chacha8rand"
```

(Example: https://build.golang.org/log/889a11fa5066e2b265c65416d28270a42f2f1226)

**Comment by bcmills** [comment]
Note that this is a test of a new API added for Go 1.22.

**Comment by mknyszek** [comment]
CC @rsc @FiloSottile 

Perhaps we should disable the tests on these platforms until there's a fix?

**Comment by bcmills** [comment]
Given that it's a new API and failing on all big-endian platforms, my guess is it's an actual bug in the implementation — I would prefer to roll back the new API until it is fixed, unless there is some compelling reason that #61716 absolutely must land in 1.22.

**Comment by mknyszek** [comment]
This issue (and #64285) appear to only affect non-first-class ports. The endianness issue seems like a result of some of the type punning done by the `internal/chacha8rand` package. If we suspect it's a bug on big-endian platforms (and riscv64) only, doesn't that mean it only affects non-first-class ports? I'm a little unclear as to where exactly this falls with respect to the policy. I agree this should be fixed before the release, and is probably not a great reason to call a port "broken" or anything if it's failing, but at least the big-endian issue seems fixable in the short-term.

I'll send out test skips for now to unblock the builders ASAP. If I'm wrong and we want to revert the whole thing I'll do that afterwards. (There will be a conflict to revert fully with the test skips, but since this is new API and there's no other development on it, fixing the conflict will be trivial.) Not trying to make a final decision here by any means.

**Comment by mknyszek** [comment]
FWIW I also sent out a revert. I'm pretty sure I'm overthinking this.

**Comment by bcmills** [comment]
> If we suspect it's a bug on big-endian platforms (and riscv64) only, doesn't that mean it only affects non-first-class ports? I'm a little unclear as to where exactly this falls with respect to the policy.

I agree that in principle the porting policy would allow us to just notify the big-endian port maintainers and leave those platforms with a known bug.

On the other hand, that wouldn't be very friendly toward those maintainers, especially for a problem as general as endian-sensitivity, and the porting policy encourages us to notify port maintainers of potential problems ahead of time. Since this breakage does not appear to have been expected (no TODOs in the code or mentions of the breakage in the commit message), a rollback seems like an appropriate starting point pending further investigation / discussion.

**Comment by laboger** [comment]
This looks suspicious in rand_test.go function TestBlockGeneric
```
seed := *(*[4]uint64)(unsafe.Pointer(&seed))
```
The seed on the right is a byte array, but then is assigned to a [4]uint64. The order of the bytes in the byte array are going to be in opposite order for big and little endian.

**Comment by FiloSottile** [comment]
The seed in TestBlockGeneric is arbitrary, but src/internal/chacha8rand/chacha8.go and src/internal/chacha8rand/chacha8_generic.go have a few similar conversions which are probably the issue.
