### ISSUE TITLE
internal/trace/v2: TestTraceStacks failures with `inconsistent status`

### ISSUE THREAD

**Issue by bcmills** [golang/go#64318]
```
#!watchflakes
post <- log ~ `--- FAIL: TestTraceStacks` && log ~ `inconsistent status`
```

Example: https://build.golang.org/log/0363b758c96007771274efb4241cfe0c1fd49827
(pulled from #61069)

Marking as release-blocker because this test is new as of Go 1.22 (attn @mknyszek).

**Comment by bcmills** [comment]
Also, you might want to consider making this test fail less verbosely when the `-v` flag is not set. 😅

**Comment by mknyszek** [comment]
Thanks; I have a small backlog of broken trace failures I intend to fix ASAP.

RE: the verboseness, that was intentional -- it's incredibly useful for debugging these traces because basically every time so far, all I've needed to figure out what went wrong (even if the bug was in the runtime) was the trace itself. (The broken trace is an excellent source of information about what codepaths were actually exercised. :)) Unless you think this is significantly hindering development, I would prefer to leave it on for now and collect the failures; it'll let me work through the issues a lot faster.

Also, running the tests locally, it just dumps the bad trace to a file. On the builders I don't really have any other choice but to print them, so part of the problem is a limitation of the infrastructure. :( And reproducing these issues can be hard.

**Comment by bcmills** [comment]
My main concern with the verboseness is that the log truncation causes `watchflakes` to not classify the failure as well — maybe we could keep the verbosity but explicitly truncate the portion of the log printed to stdout?

(It looks like the coordinator truncates after a little under 2MiB: https://cs.opensource.google/go/x/build/+/master:livelog/livelog.go;l=14-26;drc=852e1a2874a999848b08be16859dc2274e5c29a9)

**Comment by mknyszek** [comment]
Ah yeah, if it's going to cause the log to get truncated we should avoid that. I'll write a CL for that.

**Comment by dmitshur** [comment]
This is currently a blocker for the RC 1, scheduled in about two weeks. What is the latest status here?

**Comment by mknyszek** [comment]
I am actively working on trace issues, starting with ones that are easier to fix in hope that they're related to the harder ones like this. But I'm pretty sure this will be reproducible in a gomote, and I'll make sure this gets fixed.

**Comment by mknyszek** [comment]
Reproduced and found the root cause of the issue. It's an easy fix.

**Comment by mknyszek** [comment]
To summarize: the issue is that the `GoSyscallBegin` event is a signal for both the P and the G to enter a syscall state for the tracer. (Ps can't have their own event because it's too hard to model. As soon as the P enters `_Psyscall` it can get stolen out of it.) But there's a window in time between when that event is emitted and when the P enters `_Psyscall` where the P's status can get emitted. In this window the tracer will emit the wrong status: Running instead of Syscall. Really any call into the tracer could emit a status event for the P, but in this particular case it's when running a safepoint function that explicitly emits an event for the P's status.

The fix is straightforward. The source-of-truth on syscall status is the G's status, so the function that emits the P's status just needs to check the status of any G attached to it. If it's in `_Gsyscall`, then the tracer should emit a `Syscall` status for the P if it's in `_Prunning`.
