### ISSUE TITLE
runtime/trace: OOM in TestTraceStressStartStop on openbsd/386

### ISSUE THREAD

**Issue by bcmills** [golang/go#64322]
```
#!watchflakes
post <- goos == "openbsd" && log ~ `fatal error: runtime: out of memory` && log ~ `^runtime/trace_test.TestTraceStressStartStop`
```

Example: https://build.golang.org/log/0be8c98902db83cc7880a398efe8f7d6c9225606
(from #53576)

(attn @mknyszek; CC @golang/openbsd)

**Comment by mknyszek** [comment]
I'm a bit baffled as to why this is happening now. That test only ever runs the old execution tracer. Coincidentally, I recently landed a CL that switches to the new tracer, so this test should be skipped now. (There's an equivalent test in internal/trace/v2, but it's already been running on the builders and hasn't had an OOM issue on OpenBSD yet.)

**Comment by mknyszek** [comment]
Note: a bunch of these failures also showed up at #53576.

**Comment by bcmills** [comment]
Maybe some other test is running in parallel, or expanding the runtime's memory footprint in a way that leaks some additional pages?

**Comment by mknyszek** [comment]
This has probably stopped happening since the new tracer was turned on by default, since this test isn't run anymore. In that sense it's fixed, but if for whatever reason the new tracer gets rolled back, watchflakes will probably reopen this if I close it. So, I'm going to optimistically close it but leave it open so I remember to resolve it if that happens.

I am not particularly concerned that this is going to be anything more than a test issue.

**Comment by rsc** [comment]
Optimistically closing again.
