### ISSUE TITLE
x/tools/gopls: BundledQuickFixes bug reported by telemetry

### ISSUE THREAD

**Issue by adonovan** [golang/go#64503]
This stack `CRoOPw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2023-11-30.json):
```
	var fix quickFixesJSON
	if err := json.Unmarshal(*diag.Data, &fix); err != nil {
		bug.Reportf("unmarshalling quick fix: %v", err)
		return nil
	}
```
```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Reportf:1
golang.org/x/tools/gopls/internal/lsp/source.BundledQuickFixes:6
golang.org/x/tools/gopls/internal/lsp.(*Server).codeActionsMatchingDiagnostics:4
golang.org/x/tools/gopls/internal/lsp.(*Server).codeAction:92
golang.org/x/tools/gopls/internal/lsp.(*Server).CodeAction:1
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch:142
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.ServerHandler.func3:5
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.handshaker.func4:52
golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.MustReplyHandler.func1:2
golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.AsyncHandler.func2.2:3
runtime.goexit:0
```
```
golang.org/x/tools/gopls@v0.14.2 go1.21.0 darwin/amd64 (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by findleyr** [comment]
> a misbehaving client is sending a non-null but empty array for BundledFixes, which is not a valid JSON value. Possible?

That seems probable. Note that the client in the link above is `neovim`. It may be worth trying to reproduce.
However, I looked at the neovim code and didn't see anything broken... (it appears that the diagnostic data is forwarded unmodified, and vim json decoding defaults to `"omitempty"` behavior: https://github.com/neovim/neovim/blob/69ffbb76c237fcbba24de80f1b5346d92642e800/runtime/lua/vim/lsp/diagnostic.lua#L127)

Nevertheless, this should probably not be a bug report since it involves the LSP client. Bug reports should be reserved for things that are definitely bugs.

**Comment by findleyr** [comment]
Upon consideration, I'm not sure what to do with this. I don't *really* want to turn this into an RPC error or a log. I think it warrants further investigation.

Since the report rate is low, let's leave it until v0.16.0.

**Comment by adonovan** [comment]
> That seems probable.

Ah, well in that case the fix is easy: permit "" or "null" JSON strings for the Diagnostic.Data value, and treat them both as "no data". I've sent you a CL.

Thanks.
