### ISSUE TITLE
runtime: lock order violation between gscan and profInsert after CL 544195

### ISSUE THREAD

**Issue by prattmic** [golang/go#64706]
```
#!watchflakes
post <- builder ~ `.*-staticlockranking` && log ~ `lock ordering problem` && log ~ `profInsert`
```

https://build.golang.org/log/9ef94ae07bd07605e17fcd241ef0d38d5064b41f
https://build.golang.org/log/3f80d959a6cc683334f8521b8a3b002dda1bd6b3
https://build.golang.org/log/a5bfdd06fa69808fe6378b412610e65b06ddd8ff

Taking `profInsert` after `gscan` is indeed an explicit violation based on our defined lock order: https://cs.opensource.google/go/go/+/master:src/runtime/mklockrank.go;l=125-138;drc=23c0d30244d5e38d928e68661bf39458eb85d2b2.

That said, I am currently confused about the entire `STACKGROW` category (long day, perhaps). As far as I can tell, the gscan "lock" is only ever held from the system stack, so I don't understand how any of these other locks could "grow the stack", or what exactly we are protecting against.

cc @rhysh @mknyszek

**Comment by bcmills** [comment]
Should this be a release blocker? Lock inversion in the runtime seems like a pretty severe bug. 😅

(Or is this an existing issue that was only recently exposed by testing?)

**Comment by prattmic** [comment]
It should be a release blocker until we understand better. It is a new issue, not just uncovered.

**Comment by rhysh** [comment]
I'd thought this was an issue with instrumentation / reporting, but it's not: Although the (new in Go 1.22) code for adding runtime-internal lock contention events to the mprof hash table is guarded by a check to run only when the last lock is released (https://github.com/golang/go/blob/400e24a8be852e7b20eb4af1999b28c20bb4ea21/src/runtime/mprof.go#L673, checking `gp.m.locks==1` because its caller has yet to decrement the count down to zero, https://github.com/golang/go/blob/400e24a8be852e7b20eb4af1999b28c20bb4ea21/src/runtime/lock_futex.go#L134), the `gscan` lockrank appears to not be an actual "lock/unlock" mutex. The lock rank is used directly (https://github.com/golang/go/blob/400e24a8be852e7b20eb4af1999b28c20bb4ea21/src/runtime/proc.go#L1082) without (it seems) resulting in a change to `gp.m.locks`.

I'm not up to speed on gscan / casgstatus / castogscanstatus.

Does that look like an accurate description, @prattmic ? If so, then it seems the lock rank builder is trying to warn us of a real problem.

**Comment by mknyszek** [comment]
Come to think of it, I think I may have been the one that added the Gscan lock rank. It was because we'd encountered a few Gscan-related deadlocks and they were hard to debug, so we wanted to avoid that in the future. Gscan acts like a kind of spinlock on ownership of the G, but indeed, it does not increment `gp.m.locks`. Perhaps it should.

**Comment by prattmic** [comment]
I haven't yet been able to come up with a way that this could cause an actual deadlock, but I agree that having gscan increment `gp.m.locks` seems like it would fix this problem if there is one.

**Comment by mknyszek** [comment]
Oof. I think we narrowly miss a real deadlock issue here and it turns out to just be a limitation of our lock modeling.

Here's an *almost* problematic ordering:

(1) G1 is running on T1 and calls into `blockevent`, say for a mutex. It eventually calls `stkbucket`, acquires `profInsertLock`, and realizes G1 is out of stack space. G1 goes to acquire its own Gscan bit.
(2) Meanwhile the GC is enabled and T2 acquires G1's scan bit for scanning its stack. It then acquires and releases a lock, calling `unlock`, leading to trying to acquire `profInsertLock`.

(2) can't actually happen but the reasons are very subtle. There are only three cases where the GC tries to acquire a goroutines Gscan bit.

One is after asynchronously preempting, but asynchronous preemption will back out early if any locks are held by the target goroutine, so that can't happen.

Another case is where the Gscan bit is acquired and it's on a running goroutine in anticipation of a preemption, here: https://cs.opensource.google/go/go/+/master:src/runtime/preempt.go;l=199?q=preempt.go&ss=go%2Fgo. Luckily nothing happens that could cause a lock to be acquired between the acquire and release of the Gscan bit.

Finally, the Gscan bit can be acquired for a blocked goroutine, but if that was the case for G1 above, then (1) couldn't have been happening, since the goroutine needs to be running to acquire it's own scan bit.

One other possibility is that two GC threads compete for the same Gscan bit. One acquires and releases a lock while that bit is held, causing `profInsertLock` to be acquired. The other somehow starts trying to scan a goroutine while `profInsertLock` is held. The latter can't happen because nothing happens while `profInsertLock` is held that could cause a goroutine to get scanned (i.e. no memory allocations leading to a GC assist).

Modeling this properly in the lock ranking is going to be a pain. And I'm not a fan of incrementing `gp.m.locks` when acquiring the Gscan bit right now just because it could conceivably cause some "holding locks" failure. It's risky at this point in the release.

OK, that's all the bad-ish news. Our saving grace for the release is that this can only happen with `GODEBUG=runtimecontentionstacks=1`, so it's not a true release blocker. Note that all three failures happen during `TestRuntimeLockMetricsAndProfile` which enables the `GODEBUG` explicitly. This test was disabled by https://go.dev/cl/550775, so we're fine for now.

Moving out of release-blocker and into Go 1.23.

**Comment by mknyszek** [comment]
Like #64253, I think this can be worked on as a test-only fix for Go 1.22 still. The lock ranking mode is entirely for our own testing, and this issue only pops up with `TestRuntimeLockMetricsAndProfile` currently.

But there's no reason this has to block the Go 1.22 release at all, hence why I moved it to Go 1.23.

**Comment by bcmills** [comment]
I'm also seeing a similar problem in `TestDeltaProfile`, between `gscan` and `profBlock`:
https://ci.chromium.org/ui/p/golang/builders/try/gotip-linux-amd64-staticlockranking/b8757359611155253553/test-results?q=ExactID%3Anet%2Fhttp%2Fpprof.TestDeltaProfile+VHash%3A3abbce2caef9f684&sortby=&groupby=

**Comment by rhysh** [comment]
#66004 looks similar. @mknyszek , is this an acceptable point in the release cycle to have Gscan users modify `gp.m.locks`?

**Comment by prattmic** [comment]
Yes, I think so
