### ISSUE TITLE
x/pkgsite: package removal request for [github.com/bongochat/utils]

### ISSUE THREAD

**Issue by sajib1066** [golang/go#64848]
Please remove this module

**Comment by adonovan** [comment]
> Please remove this module

You can find instructions for retracting a module so that it is no longer available to the Go command or to pkg.go.dev here;  https://pkg.go.dev/about#removing-a-package

If this isn't satisfactory, please provide details on the problem so that we can advise you. The GitHub repository and its version tags still exist, which is unusual for typical requests to remove a package from the index.
