### ISSUE TITLE
misc/wasm: three version of wasm_exec.js

### ISSUE THREAD

**Issue by mvestnik** [golang/go#64940]
### Proposal Details

It would be very nice to make three versions of wasm_exec.js - for node.js, for the browser, and for node.js and browser at the same time. 
This is necessary to shorten the file code, and will allow correct linting. 
The code of wasm_exec.js looks like a bundle, probably made with Esbuild. It allows you to build a bundle for different platforms.

**Comment by Jorropo** [comment]
There already exists [`misc/wasm/wasm_exec_node.js`](./misc/wasm/wasm_exec_node.js)
After looking at [`misc/wasm/wasm_exec.js`](./misc/wasm/wasm_exec.js) I don't see what code would be removed if node support is dropped. I never tried it I don't know if it works now, but it seems to me that if it works on node it's because node is providing the same API as the browsers, not because there is special node code.

I don't think it is made with eslint, if you look at https://github.com/golang/go/commits/master/misc/wasm/wasm_exec.js they literally edit the file directly.
