### ISSUE TITLE
x/pkgsite: show if package is seeking funding

### ISSUE THREAD

**Issue by mitar** [golang/go#65002]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/alecthomas/kong

### What is your user agent?

Firefox

### What did you do?

I am trying to find all Go packages in my codebase which seek funding.

### What did you see happen?

Find some information somehow already in the Go ecosystem/tooling. But it seems it does not exist.

### What did you expect to see?

I think there could be a button inviting funding with a link to information from `.github/FUNDING.yml` file. ``.github/FUNDING.yml`` is a pretty simple file format and Go already expects git repositories, so I think reusing that file and showing links to funding ways, like GitHub itself does, would be awesome on pkg.go.dev.

**Comment by hyangah** [comment]
IMO that is beyond what pkgsite is meant for. - versioned, package documentation.
The pkgsite renders README.md, so you can add the info there if you really want.

**Comment by seankhliao** [comment]
That's even worse

**Comment by hyangah** [comment]
> pkgsite already links to Open Source Insights, they show imports and imported by, they show license. Why not also link to places to fund the project? It could be under same Links section as "Open Source Insights" is.

Open source insights presents information about the specific version of the package, mostly computed based on the information listed in the [spec](https://go.dev/ref/mod). Moreover, most info pkgsite shows won't change over time (maybe except vulnerabilities, or deprecation status). I am not sure if the state of seeking fund is a property of a versioned package. Even the package owner can change over time.

> But I think having it also be integrated into cli, same as npm has it, would even more improve the package ecosystem.

Unlike `npm` or other language toolings, go commands try to stay quiet unless there is an error or problem that prevents operation. I don't think go cli is an appropriate integration point. If you want to change it, it should go through a proposal process and strong community-wide support.

Closing since this is beyond the scope of pkgsite.
