### ISSUE TITLE
x/website/cmd/golangorg: loading and sharing Go Playground snippets on go.dev/play isn't working

### ISSUE THREAD

**Issue by dmitshur** [golang/go#65081]
**Update:** See https://github.com/golang/go/issues/65081#issuecomment-1890745508 and later comments.

---

testdata/live.txt has these test cases to check that POSTing to the playground share endpoint works:

```
POST https://golang.org/share
postbody
	package main
body !contains UA-

POST https://go.dev/_/share
postbody
	package main
body !contains UA-
```
_([source](https://cs.opensource.google/go/x/website/+/master:cmd/golangorg/testdata/live.txt;l=50-58;drc=e2dd66fc34eaa6b7477059e04215f675a293f6ab))_

They sometimes (but seemingly not always) fail with with an unexpected status code 451:

```
webtest.CheckHandler failed:
# testdata/live.txt
## POST https://go.dev/_/share
testdata/live.txt:55: POST https://go.dev/_/share
testdata/live.txt:58: code = "451", want "200"
```

When it happens during a deployment, it prevents the new version from being [promoted to serve traffic](https://github.com/golang/website/blob/master/cmd/golangorg/README.md#deploying-to-godev-and-golangorg).

CC @golang/tools-team.

**Comment by findleyr** [comment]
Indeed, playground share seems flaky today.

Per https://cs.opensource.google/go/x/playground/+/master:share.go;l=55;drc=bb2a4ed2d77c5ebb58ace5e1466acec69a729a68, I believe this should only happen if `r.Header.Get("X-AppEngine-Country") == "CN"`. Hmm.

**Comment by fis** [comment]
Just as a data point, this seems to be pretty consistently happening to me today on the current live Playground version, from the UK. (And other IP-based geolocation services don't seem to think I'm in China.)

**Comment by jub0bs** [comment]
I'm observing the same issue from a French IP.

**Comment by nalgeon** [comment]
Same problem with German IP (207.154.221.x). Both sharing and loading shared snippets does not work:

```
POST https://go.dev/_/share
451 (Unavailable For Legal Reasons)

GET https://go.dev/_/share?id=YJeYpEjdBF
451 (Unavailable For Legal Reasons)
```

**Comment by dmitshur** [comment]
Thanks for the reports. This is indeed now happening on each request, and affects website visitors in the US and many other locations.

I've updated the issue and pinned it for visibility, but it's unlikely someone will have a chance to look into it until after the weekend.

**Comment by x1unix** [comment]
I got the same issue. I host a frontend for Go Playground - https://goplay.tools which is hosted in the US and get `451 Unavailable For Legal Reasons` on each share call.

**Comment by findleyr** [comment]
I looked into this briefly today. It appears that one of the internal IPs used for proxied traffic from the go.dev frontend to the playground backend was briefly categorized as CN, causing these spurious failures.

I think that IP has since been recategorized as US, but it will probably take several more days for that to propagate. Additionally, go.dev has it's own [mechanism](https://cs.opensource.google/go/x/website/+/master:internal/play/proxy.go;l=51;drc=fe2f2e7c055698c2a06fa5b90ef33d26522783c4) for handling CN-based traffic, so this check on internal IPs is both pointless and unnecessary. We should remove it for proxied traffic, though we still need it for direct traffic to the playground backend.

Unfortunately, due to the timing around the holiday weekend in the US, we're unlikely to be able to mitigate this until Tuesday at the earliest. It may resolve naturally before then. In the meantime, if you're up for a blast from the past, the old frontend is still available at https://play-dot-golang-org.appspot.com/.

**Comment by nalgeon** [comment]
So the sharing feature has been down since Friday, and as of Tuesday, it still appears to be unresolved.

Understanding that the team doesn't work on weekends, I'm concerned about the length of downtime for such a critical component.

Could we get an update on the expected timeline for a fix?

**Comment by findleyr** [comment]
@nalgeon the Go team is primarily based in the US, where Monday was a holiday. We're working on this now.

**Comment by findleyr** [comment]
Update for today: the above CLs temporarily mitigate the problem by allow listing several Google IP prefixes that have been observed to follow the problematic pattern: a transient recategorization as CN in early January, since reverted back to US. This short list covers all the traffic we've seen over the past week, and playground snippet sharing seems to be working again. However, there's no guarantee that this list will remain valid.

We're still pursuing several more permanent fixes.

**Comment by hyangah** [comment]
This is mitigated and now @findleyr is actively working on a longer term solution. Unpinning.
