### ISSUE TITLE
cmd/go: get can't fetch packages sources without dots in the base name

### ISSUE THREAD

**Issue by msiebuhr** [golang/go#6520]
<pre>What steps will reproduce the problem?
1. Run go get -x localhost/foo.git
2. Run go get -x 127.0.0.1/foo.git

What is the expected output?
The output of the two commands should match (except hostname/ip difference).

What do you see instead?
The command that fetches from localhost fails (unrecognized import path), while the one
that explicitly gets the loopback IP succeeds.

Which version are you using?  (run 'go version')
go version devel +664c8763de42 Tue Oct 01 11:24:24 2013 +1000 linux/amd64

This also breaks imports from file-system paths, ie

    &gt; go get shared/go/foo.git

Even though it works with a dot in the base name:

    &gt; go get -x shared.dot/go/foo.git
    ...
    git clone shared.dot/foo/foo /home/$USER/Source/go/src/shared.dot/foo/foo.git

(Go get clearly tries to fetch from the file-system too, where having a dot in the path
isn't all that usual.)</pre>

**Comment by ysmolsky** [comment]
I am triaging it again. 

Design of "go get" is about downloading packages from remote internet hosts, it means a domain with dot. If one wants to handle this for the local hostnames then it is possible to use local hostnames with a dot. 

I am not sure that we want to handle this case on the side of `go get` because the proposed behaviour is rather an exception to the rule. 

ping @msiebuhr
