### ISSUE TITLE
cmd/compile: instantiation cycle error in method

### ISSUE THREAD

**Issue by leaxoy** [golang/go#65366]
### Go version

1.21

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOOS='darwin'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.6/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.6/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_5/gqm2bdhs6jg5vpcqx9rp17qh0000gn/T/go-build1059361469=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://go.dev/play/p/Rs1R0zaMrys

### What did you see happen?

./prog.go:14:12: instantiation cycle:
	./prog.go:16:38: E instantiated as []E

### What did you expect to see?

no error occurred

**Comment by mknyszek** [comment]
CC @golang/compiler, perhaps @griesemer specifically?

**Comment by griesemer** [comment]
This is working as intended. Since the type parameter E is not used, you can simply remove it and the code will compile.

If the type parameter were used, this code couldn't be compiled, at least with the current implementation of Go which monomorphizes code (doesn't box generics): say, `T` is instantiated with `int`. That means it will have a method `m(T[[]int]`) producing a type `T` instantiated with `[]int`. That type will have a method `m(T[[][]int])`. Which will give rise to that new type `T[[][]int]`, etc. ad infinitum. Code generation would never stop.

**Comment by griesemer** [comment]
@mdempsky In case you want to add something to this.

**Comment by mdempsky** [comment]
I agree the error here is expected and the monomorpic  checker is working as intended.

**Comment by leaxoy** [comment]
@griesemer Thank for your explain. But I still have some doubts.

Is the limitation here caused by the current implementation of generics, or will there always be this limitation. Or as the generics iterate, this limitation will disappear.

If this restriction will disappear in the future, when will it happen and whether it will rely on other preparatory work?

In addition, I have not encountered similar problems in other languages. I am not sure about the implementation in go, but I believe this can be solved.

Going back to the original proposition, that is to say, I have no way to implement the chunk method on slice?

So is there any compromise way to implement chunks? It doesn't involve implementing a lot of top-level functions.

**Comment by leaxoy** [comment]
I'm not sure I understand the unused E above.

The following example uses E, but still reports an error:
```go
type slice[E any] struct{ elems []E }

func (s slice[E]) chunk(n int) slice[[]E] {
	return slice[[]E]{elems: [][]E{}}
}
```

**Comment by mdempsky** [comment]
> Is the limitation here caused by the current implementation of generics, or will there always be this limitation.

We want to ensure instantiation is guaranteed to reach a finite fixed point. If instantiating type T[X] requires instantiating type T[[]X], then we'll need T[[][]X], and so on. It never stops.

**Comment by griesemer** [comment]
@leaxoy The limitation could (perhaps) be removed if we'd always box generic values. But because our implementation uses a hybrid approach that monomorphizes code (generates code for each kind of type, for speed), your source would lead to endless code generation as @mdempsky pointed out. There are no plans to change this.

Your `chunk` implementation can be written like so:

```Go
func chunk[E any](s []E, n int) [][]E {
	do something sensible here
}
```

It's not a method but it also doesn't refer to itself anymore.

**Comment by leaxoy** [comment]
> ```go
> func chunk[E any](s []E, n int) [][]E {
> 	do something sensible here
> }
> ```

But this break method chaining, maybe `pipe-operator` like cpp's [ranges](https://en.cppreference.com/w/cpp/ranges) can solve user experience problems to a certain extent, but it's a separate topic.
