### ISSUE TITLE
encoding/json: int as map key error

### ISSUE THREAD

**Issue by jk2K** [golang/go#65368]
### Go version

1.21

### Output of `go env` in your module/workspace:

```shell
https://go.dev/play/p/sM0eZ_HtJuW
```

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	input := `{
    "aa": "bb",
    "636": {
        55538944: [
            {
                "bi": {},
                "clk": "99#null-null-null#55538944#dct&&&&",
                "deliveryId": 55538944,
                "itemid": "20373"
            }
        ]
    }
}`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(input), &data); err != nil {
		fmt.Printf("errors\n %v", err)
	}
	fmt.Println(data)
	fmt.Println("Hello, 世界")
}
```

### What did you do?

https://go.dev/play/p/sM0eZ_HtJuW

### What did you see happen?

```
invalid character '5' looking for beginning of object key stringmap[]
```

### What did you expect to see?

no error

**Comment by mengzhuo** [comment]
```
{55538944: []}
```

According to json spec, the key should be string instead of number https://www.json.org/

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
For questions please refer to https://github.com/golang/go/wiki/Questions
