### ISSUE TITLE
x/tools/gopls: unusedparams analysis does not check

### ISSUE THREAD

**Issue by ilya-rusyanov** [golang/go#65401]
### gopls version

v0.14.2

### go env

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/rusyanov/go/bin'
GOCACHE='/home/rusyanov/.cache/go-build'
GOENV='/home/rusyanov/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/rusyanov/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/rusyanov/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go-1.21'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go-1.21/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/rusyanov/src/proj/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3362930225=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Defining a function that does something (for e.g. fmt.Println("sometext")) but is not using it's arguments does not raise a warning.

```go
func F(a int) { // << no warning is raised here, although a is clearly not used and the function has body
	fmt.Printf("test")
}
```

### What did you see happen?

No diagnostic is generated about unused function parameter. Other analyses are ran and displayed as expected.

### What did you expect to see?

Warning about unused parameter.

### Editor and settings

nvim v0.9.5

```lua
local capabilities = require('cmp_nvim_lsp').default_capabilities()

local lspconfig = require("lspconfig")
-- Setup language servers.
lspconfig.gopls.setup({
  capabilities = capabilities,
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
        shadow = true,
        unusedwrite = true,
        unusedvariable = true,
      },
      staticcheck = true,
      gofumpt = true,
    },
  },
})
require'lspconfig'.clangd.setup{
  capabilities = capabilities
}
```

full configuration: https://github.com/ilya-rusyanov/nvim-config

**Comment by adonovan** [comment]
The [unusedparams](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/unusedparams) analysis, like most gopls analyzers, uses the golang.org/x/tools/go/analysis framework for modular analysis, which is analogous to separate compilation in a compiler. That means that the analysis of a given package can access the package itself, and summaries of information obtained from the package's dependencies, but it cannot access information from packages that import the current package.

For the specific problem of unused parameters, that means it cannot report that a parameter of an exported function (such as your F) is unused, because another package could assign F to a variable of type `func (int)` (or a method to an interface of type `interface{F(int)}`), in which case applying the suggested fix to remove the parameter would break the program. The fix would be unsound.

Until recently, the unusedparams checker was disabled by default because it made exactly that unsound assumption, causing it to frequently give harmful advice. We recently rewrote it so that it is completely sound (no false positives), allowing us to enable it by default. Of course this means that may miss some true positives, but we believe that is the better trade-off.

So this is working as intended. You may find it helpful to periodically run a global analysis tool for detecting dead code, unused fields, unused parameters and so on, as such tools may have better precision; but gopls cannot run such analyses in real time.
