### ISSUE TITLE
cmd/compile: Go 1.22 build fails with 1.21 PGO profile on internal/saferio change

### ISSUE THREAD

**Issue by konradreiche** [golang/go#65615]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GOARCH='amd64'
GOOS='linux'
GOVERSION='go1.22.0'
```

### What did you do?

We are continuously collecting PGO profiles and apply them to new builds, a process that worked seamlessly with Go 1.21. I upgraded to Go 1.22 and attempted to compile our build using the Go 1.21 PGO profile.

```
go build -pgo=auto .
```

### What did you see happen?

The `go build` command failed, producing the following error:

```
go build -pgo=auto .
# encoding/gob
/usr/lib/go/src/bufio/bufio.go:47:6: internal compiler error: saferio.SliceCap has 0+1 params, but instantiated with 0+0 args
```

This error suggests a change made to the `SliceCap` method in the `internal/saferio` package between Go 1.21 and Go 1.22:

https://github.com/golang/go/blob/release-branch.go1.21/src/internal/saferio/io.go#L116
https://github.com/golang/go/blob/release-branch.go1.22/src/internal/saferio/io.go#L128

The build compiles successfully with PGO turned off:
```
go build -pgo=off .
```

### What did you expect to see?

Expected the go build command to compile the build successfully, as it did with Go 1.21.

**Comment by konradreiche** [comment]
I assume this isn't expected because according to the [PGO documentation](https://go.dev/doc/pgo) a change to the source code could result in performance degradation but not necessarily compilation failure.

**Comment by prattmic** [comment]
Thanks for filing this! We discovered this same crash with a different symbol independently this morning and I was coming to file an issue only to find you've done so for me. :D

This is indeed a bug in the way we lookup functions for PGO. Internally, the compiler internally is trying to look up the function as non-generic (because the profile contains the non-generic symbol name), but the function is actually generic and the compiler chokes. We should fix this.

**Comment by prattmic** [comment]
@gopherbot Please backport to 1.21. This is a build failure with PGO if a hot function is changed from non-generic to generic. Only workarounds are to rename the symbol or disable PGO.
