### ISSUE TITLE
proposal: slices: Use make instead of `Grow` in `Concat`

### ISSUE THREAD

**Issue by justinhwang** [golang/go#65884]
### Proposal Details

`slices.Concat` unnecessarily uses `Grow` instead of make which unnecessarily increases time/op

**Comment by justinhwang** [comment]
Seeing the comment now - https://go-review.googlesource.com/c/go/+/504882#:~:text=Aug%2007%2C-,2023,-Since%20we%20don%27t

**Comment by ianlancetaylor** [comment]
See the discussion on https://go.dev/cl/504882.

**Comment by OhJuhun** [comment]
@ianlancetaylor Thank you for your reply.
But, I already read this discussion.
"But I feel like I didn't fully understand the comment's exact meaning. I agree that there is no need to explicitly set the capacity; there is no particular reason for doing so. However, the variable name generated internally is also 'newSlices,' and the 'Grow' used in Concat always returns a slice with the size of 'size.' I believe the intent of 'Grow' is to increase the size of the provided slice, not to create a new slice. But in Concat, a new slice is being created by passing 'nil' as the original slice to 'Grow.' Considering this, I am curious if there is really a need to use 'Grow' instead of 'make' from a readability perspective. Performance also seems better when generating 'newSlices' using 'make.' I don't quite understand what issues can arise from guaranteeing the capacity. Could you please explain this in more detail? Sorry to trouble you."

<img width="777" alt="image" src="https://github.com/user-attachments/assets/4af2e126-8173-42f5-a158-3e972c00fc58">

**Comment by randall77** [comment]
The reason we want to round up to the next size class is to avoid reallocation on a subsequent `append`.
```
s := slices.Concat(...)
s = append(s, 7)
```
With `make`, that second line will always do a reallocation+copy. If we round up to a size class using `Grow`, then probably that second line will not have to do that extra work.

**Comment by OhJuhun** [comment]
@randall77 
I misunderstood about slices.Grow.
I missed the comment: After Grow(n), "AT LEAST" n elements can be appended
Thank you for your reply.
