### ISSUE TITLE
cmd/compile: hash of unhashable type [4]int32

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#65957]
### Go version

gotip

### Output of `go env` in your module/workspace:

```shell
GOARCH="arm64"
GOOS="darwin"
```

### What did you do?

playground link: https://go.dev/play/p/WAX0OTneh60

### What did you see happen?

```
panic: runtime error: hash of unhashable type [4]int32

goroutine 1 [running]:
main.main()
	/tmp/sandbox3460698193/prog.go:15 +0xc7
```

### What did you expect to see?

no panic

**Comment by randall77** [comment]
Here's a simpler reproducer: https://go.dev/play/p/NGky0OURi8R

**Comment by wdvxdr1123** [comment]
I can reproduce with go1.21 and go1.22. Should we backport this fix?

**Comment by randall77** [comment]
I'm on the fence. We only backport [serious issues with no workaround](https://go.dev/wiki/MinorReleases), which I'm not sure this qualifies. It has been a bug since 1.18 and this is the first anyone has reported it. I'm not sure what a workaround might be, though. Does introducing a use of the array type in both packages work as a workaround?

I'll open backports and we can discuss on those issues.

@gopherbot please open backport issues. This issue may warrant backporting. It causes program crashing in some very particular circumstances. (Use of `reflect.ArrayOf`, and just the right use / nonuse of the corresponding language type in particular packages.)
