### ISSUE TITLE
net/url: ResolveReference ignores Opaque value

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#66084]
### Go version

go version go1.21.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/santhosh/Library/Caches/go-build'
GOENV='/Users/santhosh/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/santhosh/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/santhosh/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Volumes/Backup/github.com/santhosh-tekuri/jsonschema/cmd/jv/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/3s/8z1m0ns10s1bdl3bl1dx8nbh0000gn/T/go-build2151327207=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

run the code https://go.dev/play/p/QndsQIeIA73

### What did you see happen?

prints: `urn:#abcd`

### What did you expect to see?

print: `urn:uuid:deadbeef-1234-ffff-ffff-4321feebdaed#abcd`

**Comment by mknyszek** [comment]
CC @neild

**Comment by fmata97** [comment]
I was able to reproduce the issue and from my research on the reference resolution algorithm specified in [RFC 3986 section 5.2](https://www.rfc-editor.org/rfc/rfc3986.html#section-5.2), the given example should, in fact, print `urn:uuid:deadbeef-1234-ffff-ffff-4321feebdaed#abcd`.
Since the base URI (`"urn:uuid:deadbeef-1234-ffff-ffff-4321feebdaed#xxx"`) is opaque and the reference doesn't have a scheme defined neither an authority section, the result should be the base scheme and opaque followed by the reference query and/or fragment.

The code for `ResolveReference` doesn't support this case, as it ignores the base opaque value (`u.Opaque`):

https://github.com/golang/go/blob/b38b1b2f9ae710ee2c16a103bb21644f1adbc5d3/src/net/url/url.go#L1114-L1118

I believe the solution would be to check for this case before reaching the referenced piece of code and setting the URI parameters accordingly.
If this sounds all good, feel free to assign me the issue as I would like to fix it with a PR.
