### ISSUE TITLE
cmd/cover: (html output) UI accessibility issues

### ISSUE THREAD

**Issue by cznic** [golang/go#6623]
<pre>The color scheme has IMO some troubles:

1. It's inverted, ie. light text on dark background. Please be aware that some people
are not able to read comfortably it or read it at all for more than a brief time period
without physical troubles. I suggest to never ever default to inverted colors anywhere
whatsoever.

2. To make thing worse, the light gray text on black background has so low contrast that
the people having already trouble from the inversion scheme has now one more source of
pain. (Also a big sin of many Android UI screens.)

3. People can select default fonts they're comfortable with in the browser. Please
respect that and do not force another font where it's completely unnecessary. It's a
tooling report, not a design studio website front page or similar.

Suggestions:

- Select a font-family only, eg. 'monospace', not 'Menlo, monospace'.
- Remove 'font-weight: bold;'
- Support how many report styles you wish, but keep the default one which is plain black
text on white background by default (like this issues page.). The green/red emphasizes
on covered/not covered source lines is IMO ok.
- If a B/W scheme is considered too &quot;plain&quot;, then I suggest to adopt the color
scheme already used for source code by the the godoc tool. It has no accessibility
problems I'm aware of. The typographical consistency would be a nice bonus, I believe.

My apologies for I haven't followed the design of the cover tool before so I could
provide such feedback earlier.</pre>

**Comment by dr2chase** [comment]
Recently on golang-nuts, "Is it possible to get code coverage information in a way that does not assume you can see color?"

https://groups.google.com/g/golang-nuts/c/DY4O9UXMr9M?pli=1

In this case, "see color" refers to a screen reader for a totally blind person.
That's not what this bug was originally exactly about, but the bug title is very general and includes this problem.

Reopening, so this can get some attention.
This is a bug, not an enhancement, because accessibility is important.
It does need someone who knows something about UI accessibility to look at it.

**Comment by robpike** [comment]
Reopening this issue is perhaps not the right action. The problem mentioned on the list is about having a non-visual way to see the data; this issue is arguing about the colors.

**Comment by dr2chase** [comment]
See also, for the screen reader version of html UI accessibility issues, #36685.
