### ISSUE TITLE
gosumdb: "not found: create zip: docker/node:alpine: malformed file path "docker/node:alpine": invalid char ':'"

### ISSUE THREAD

**Issue by inteon** [golang/go#66243]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

```bash
$ go get github.com/DopplerHQ/cli@v0.5.9
go: downloading github.com/DopplerHQ/cli v0.5.9
go: github.com/DopplerHQ/cli@v0.5.9: create zip: docker/node:alpine: malformed file path "docker/node:alpine": invalid char ':'
docker/python:alpine: malformed file path "docker/python:alpine": invalid char ':'
docker/ruby:alpine: malformed file path "docker/ruby:alpine": invalid char ':'
```

### What did you see happen?

gosumdb is returning an unexpected error (see https://sum.golang.org/lookup/github.com/!doppler!h!q/cli@v0.5.9):
```
not found: create zip: docker/node:alpine: malformed file path "docker/node:alpine": invalid char ':'
docker/python:alpine: malformed file path "docker/python:alpine": invalid char ':'
docker/ruby:alpine: malformed file path "docker/ruby:alpine": invalid char ':'
```

### What did you expect to see?

No error or a different error.

**Comment by SgtCoDFish** [comment]
It looks like this is because there are files in this repo which have colons in them: https://github.com/DopplerHQ/cli/tree/v0.5.9/docker

The error appears to be propagated to the sumdb. Same happens with v0.5.10:

- https://github.com/DopplerHQ/cli/tree/v0.5.10/docker
- https://sum.golang.org/lookup/github.com/!doppler!h!q/cli@v0.5.10
