### ISSUE TITLE
cmd/compile: surprising behavior for doubly declared methods

### ISSUE THREAD

**Issue by griesemer** [golang/go#66285]
Before Go 1.13, it was an error for a method to appear more than once (via embedding) in an interface. For instance, [this code](https://go.dev/play/p/Efvw3oJf8Qd) produced an error ("duplicate method Read"). With 1.14, [such code](https://go.dev/play/p/Jn2SGKUonuZ) was permitted.

Similarly, [this code](https://go.dev/play/p/FEBubhc8zIt) also produces the same error under 1.13 as one would expect:
```Go
type T interface {
	io.Reader
	Reader
}

type Reader interface {
	Read(p []byte) (n int, err error)
}
```

However, [this code](https://go.dev/play/p/t1obQLFn19h) does not:
```Go
type T interface {
	io.Reader
	io.Reader
}
```

The reason is that here the method `Read` both times is imported (through `io.Reader`): because the `io` package is "correct", the imported `Read` method is "exempt" from the 1.13 version check. This seems odd: even though `io` is valid, the actual embedding of `Read` happens in the current package (or file) and thus the 1.13 rules should apply irrespective of where the method came from.

A method's origin package should not matter for the version test, only the (file) version of the source where the embedding happens.

**Comment by griesemer** [comment]
cc: @findleyr @rsc for visibility

**Comment by rsc** [comment]
I agree that the error should be present even when io.Reader is imported from a newer package. If we don't understand why this is happening, then maybe it is worth understanding better, just in case it is symptomatic of some larger bug in the way we think about or handle versions.

That said, if we do understand it and it's just annoying to fix, I think it would be fine to take the check out entirely. The only reason for the check would be to help users keep their code compatible with Go 1.13, but Go 1.13 has been unsupported for many years now, so that's not a reason anymore.

**Comment by griesemer** [comment]
We do understand where it's coming from and the fix is trivial (actually simplifies the code). Thanks for the comment.
