### ISSUE TITLE
x/build: bump Xcode versions on darwin builders

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#66394]
Bump available Xcode versions to 15.3 on macOS 14 and 15.2 on macOS 13 (the last supported Xcode version). This should unblock some testing for #66360.

**Comment by thanm** [comment]
At one point during the pre-LUCI era we actually had two flavors of windows builders, one with ancient compilers (GCC 4.X) and one with more recent compilers. We did tip testing with the "new cc" builders (since the tip linker worked with the newer compilers) but sent CLs on release branches to the "old-cc" builders.

I wonder if it might be possible to do something like this in the LUCI world, e.g. have a "darwin-xcode-bleeding-edge" builder or equivalent (caveat: not a LUCI expert, so unsure as to whether this is a viable option).

**Comment by rolandshoemaker** [comment]
We re-applied the change, and the versions have now been bumped.
