### ISSUE TITLE
cmd/compile: debugger support for range-over-func

### ISSUE THREAD

**Issue by aarzilli** [golang/go#66468]
Range-over-func (https://github.com/golang/go/issues/61405) statements are going to be compiled into closures passed to the iterator function. I.e. the following code:

```
for range f {
    body
}
```

becomes:

```
f(func() {
    body
})
```

Delve (and potentially other debuggers) needs a way to correlate the stack frame where the body's closure is executing with the stack frame that it logically belongs to (the "parent" frame), for two reasons:

1. to display variables from the parent frame while the the program is stopped inside the loop's body
2. to make stepping work seamlessly (i.e. step-over from the header line of the loop will move to the first line of the loop's body)

We have discussed during the go team/delve meetings possible solutions for this and the current plan is to keep the closure struct alive and make it accessible through a specially named variable DIE.

This issue is to track this problem (and also for cases where the binary is optimized and a lot of inlining happens to the range-over-func statement).

cc @derekparker @dr2chase

**Comment by thanm** [comment]
Thanks for filing this tracking issue.

**Comment by cherrymui** [comment]
Discussed with @aarzilli , @derekparker , and other Delve contributors, we think that there are two parts:
- Give special name for the range body closure, so the debugger can identify which functions are range body closures. This is addressed in CL https://go.dev/cl/584596 , which gives range body closure name (say) `F-range1`, instead of the regular closure name `F.func1`.
- Keep the closure pointer live on stack with a special name, so the debugger can find it, and from there find the outer function. This is done in CL https://go.dev/cl/586975 , which keeps the closure pointer live on stack with the name `.closureptr`.

These two should have addressed the issue. If it turns out that this is not sufficient, feel free to reopen. Thanks!
