### ISSUE TITLE
access: Application to join golang/mips maintainer team

### ISSUE THREAD

**Issue by HeliC829** [golang/go#66786]
As I described in #66778, I had left CIP United.Co., Ltd. I still aim to keep maintaining goarch/mips and continue working on my unfinished CLs and proposals. 
I'd like to apply to join the golang/mips maintainer team so that I can receive team ping on mips-relevant issues and work on fixing them in time.

My previous contributions: https://github.com/golang/go/commits?author=HeliC829

cc @Rongronggg9 @4a6f656c

**Comment by Rongronggg9** [comment]
I confirm the fact that @HeliC829 has left CIP United Co., Ltd.

Our earliest discussions decided that I would accept the maintainership transfer. After that, some adjustments made me responsible for other internal projects. From then on, I made some time weekly to work with @HeliC829 on golang stuff. Since I mostly provided technical guidance and helped debug, most CLs were submitted by @HeliC829.

We will continue maintaining the MIPS ecosystem as always, including golang. Glad to see @HeliC829 going forward with the same goal.

**Comment by ALTree** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Also CC @golang/mips (for completeness; almost everyone in it was already CC'ed).

**Comment by 4a6f656c** [comment]
I'm not exactly sure what access of membership golang/mips provides, however in general terms I have no objection - the Go mips* ports can use all the help they can get!

**Comment by dmitshur** [comment]
Thank you for contributing, and sorry this access request took us a while to process. You should have a pending invite to join the golang/mips team.

**Comment by dmitshur** [comment]
Yes, for that please file a new issue as described at https://go.dev/wiki/GerritAccess#requesting-access. Thanks.
