### ISSUE TITLE
runtime,reflect: reflect.bitVector and runtime.bitvector not sync

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#66822]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
no need.
```

### What did you do?

See https://github.com/golang/go/blob/master/src/runtime/stack.go#L580-L583 and https://github.com/golang/go/blob/master/src/reflect/type.go#L2914-L2918 .

### What did you see happen?

reflect.bitVector and runtime.bitvector not sync.

### What did you expect to see?

Implement matching annotations.

**Comment by novitoll** [comment]
[runtime/stack.go](https://github.com/golang/go/blob/master/src/runtime/stack.go#L580-L583) has `n int32`. Should it be changed to `n uint32` as in [reflect/type.go](https://github.com/golang/go/blob/master/src/reflect/type.go#L2914-L2918) and keeping the name struct name `bitvector` w/o camelCase for consistency?

If so, there are [conditions](https://github.com/golang/go/blob/master/src/runtime/heapdump.go#L259-L277) where `-1` is returned where we don't have a valid pcdata, and pc* functions and [type pcvalueCacheEnt struct](https://github.com/golang/go/blob/master/src/runtime/symtab.go#L860).

Please advise if it's OK to change to uint32 and use uint32(0) instead of int32(-1) for the condition above, I can send a patch.

**Comment by cherrymui** [comment]
They need to match semantically, and they do. The code may not look identical at surface level. If you think the code and/or the comment can be adjusted, feel free to send a CL.

There is no need to file an issue like this. In general, this is internal implementation detail, not a user-observable issue. Thanks.
