### ISSUE TITLE
x/tools/gopls: remove the "allowImplicitNetworkAccess" setting

### ISSUE THREAD

**Issue by findleyr** [golang/go#66861]
Following up on #66860, this issue tracks removing the "allowImplicitNetworkAccess" setting. As stated on that issue:

> We should not have settings that affect low level behavior like this, as such settings are inevitably insufficiently tested and hard to maintain. Gopls should work well with its default decisions about allowing network access

If you are here because you use this setting and received a warning that it will be removed, please explain why you use it!

**Comment by nikzayn** [comment]
@findleyr can I take this up?

**Comment by findleyr** [comment]
@nikzayn sorry but this is really just a process issue, not a good candidate for contribution.

**Comment by francislavoie** [comment]
In my VSCode, I've been getting `Invalid settings: setting option "allowImplicitNetworkAccess": this setting is deprecated` error on startup for a while now. For the life of me, I can't figure out where to look to clear this up. I'd appreciate some help! 😅

**Comment by gitsomebit** [comment]
I got this warning just now:

```
Invalid settings: setting option "analyses": the 'fieldalignment' analyzer was removed in gopls/v0.17.0; instead, hover over struct fields to see size/offset information (https://go.dev/issue/66861)
```

I would like to make an appeal, that the 'fieldalignment' analyzer was very useful tool, as it gave me a visual warning sign when I misaligned struct fields by underlining the struct with a yellow line and warned in the vscode warnings. 

The new way of hovering over the fields to check the alignment and offset feels clunky and like a step back from an already good system where you would get visual feedback when you misaligned things, but the program still runs when compiled.

Now I need to manually check the struct fields and must not forget to check the fields since there is no visual feedback any more, if fields are misaligned.

Is there a way to get the old way back or add an option to give visual feedback for when fields are misaligned?

**Comment by gitsomebit** [comment]
what I find strange is that this thread is about "allowImplicitNetworkAccess" and the setting for "fieldalignment" links to this issue

**Comment by findleyr** [comment]
@gitsomebit thank you! I'm sure that is an oversight -- probably a copy-pasted error message that wasn't update with the correct issue number. We'll fix.

**Comment by gitsomebit** [comment]
@findleyr updated to gopls@v0.20.0 and the message still persists:

```
Invalid settings: setting option "analyses": the 'fieldalignment' analyzer was removed in gopls/v0.17.0; instead, hover over struct fields to see size/offset information (https://go.dev/issue/66861)
```

should I open a seperate issue for this?
