### ISSUE TITLE
cmd/go: Support C/C++ compiler flags when using SWIG through the build tool

### ISSUE THREAD

**Issue by ane** [golang/go#6696]
<pre>In tip, there's support for using SWIG through the build tool. This works actually
really well now, but one problem is that if one wishes to pass compiler options to the
C/C++ compiler, none of the flags supported by the build tool seem to support that. 

An example workaround is to run:

    &quot;CC=gcc &lt;flag1&gt; &lt;flag2&gt; &lt;flag3&gt;&quot; go build

but it's rather awkward. Something similar how Cgo handles compiler flags, perhaps.</pre>

**Comment by michael-schaller** [comment]
@slimsag 
Stephen, do you still have plans to get this in before the Go 1.5 feature freeze?

**Comment by slimsag** [comment]
@michael-schaller apologies for my latency on this issue.

I've just checked and we do not need to do anything to support this use case anymore.

Since SWIG code is now built using CGO instead of the old plan-9 C compilers, you can simply use a `build.go` file containing `import "C"` and `#cgo key: value` directives as part of your package containing the `.swig` file. I've put together a simple example to demonstrate this (see below).

*At this point, unless there is opposition to using the `#cgo` directives in combination with SWIG code for some reason, **we can close this issue.***

```
$ tree
.
├── main.go
├── mylib
│   ├── build.sh
│   ├── mylib.c
└── mypkg
    ├── code.c
    ├── mypkg.go
    └── mypkg.swig

2 directories, 6 files
```

The `main.go` program is very simple (and external from the SWIG wrapper package):

```
$ cat main.go
package main

import "cflags/mypkg"

func main() {
  mypkg.DoStuff()
}
```

`mylib` is a simple C dynamic library I built:

```
$ cat mylib/build.sh 
gcc -c -Wall -Werror -fPIC mylib.c
gcc -shared -o libmylib.so mylib.o
```

```
$ cat mylib/mylib.c
int mylib_add(int a, int b) {
	return a + b;
}
```

Then I declared a simple C function in the SWIG package to retrieve a preprocessor-defined value (see `-DGENERIC_VALUE=32` below):

```
$ cat mypkg/code.c 
int generic_value = GENERIC_VALUE;

int get_generic_value(void) {
	return generic_value;
}
```

The SWIG package has the grunt of the code and our `#cgo` build directives:

```
$ cat mypkg/mypkg.go
package mypkg

// #cgo CFLAGS: -DGENERIC_VALUE=32
// #cgo LDFLAGS: -L${SRCDIR}/../mylib/ -lmylib
import "C"

import "log"

func DoStuff() {
	// Test that the GENERIC_VALUE defined in the C compiler flags is correct.
	v := Get_generic_value()
	if v != 32 {
		log.Fatal("got unexpected value")
	}
	log.Println("got the right value", v)
	log.Println("mylib_add(2, 2):", Mylib_add(2, 2))
}
```

```
$ cat mypkg/mypkg.swig 
/* A trivial example of using CGO compiler flags with SWIG.  */

int get_generic_value(void);

int mylib_add(int a, int b);
```

Build and run it:

```
cd mylib/
./build.sh # builds libmylib.so
cd ..
go build # builds the main program binary named 'cflags'

# run the program with libmylib.so on LD_LIBRARY_PATH:
LD_LIBRARY_PATH=mylib/ ./cflags
```

which produces:

```
2015/04/02 12:22:27 got the right value 32
2015/04/02 12:22:27 mylib_add(2, 2): 4
```

**Comment by ianlancetaylor** [comment]
Thanks for the worked example.

**Comment by michael-schaller** [comment]
@slimsag 
Stephen, thank you for testing this. I gave my code also a test run and I confirm that it works fine with current Go 1.5 and SWIG 3.0.6 snapshots. In the past I still needed a dummy .cpp file for cgo to properly link against a C++ library wrapped with SWIG. With the current code this workaround is no longer necessary. Awesome! :-D
