### ISSUE TITLE
x/tools/gopls: func parameter completions should pick up accessible type aliases of a parameter type

### ISSUE THREAD

**Issue by frankli0324** [golang/go#67219]
**Is your feature request related to a problem? Please describe.**

When a module provides an API that takes a private type parameter in an internal package, and exports that type with type alias in public packages, currently the code completion simply copies the literal func definition:

![image](https://github.com/golang/vscode-go/assets/20221896/ccc0d2dc-dc1b-4d29-a65e-cac33dda6621)

![image](https://github.com/golang/vscode-go/assets/20221896/ac8d7c1d-32e2-46b7-93db-0477f39a613d)

**Describe the solution you'd like**

I think the golang extension should be smarter in completion and use gopls to understand the function signature and replace the inaccessible types with accessible ones if possible.

![image](https://github.com/golang/vscode-go/assets/20221896/b6314f0c-f0bb-416f-b8be-4b378a8d6371)

That is *already* the case where type aliases are used in simpler cases, under which the extension *could* find the correct type

![image](https://github.com/golang/vscode-go/assets/20221896/0d40f08c-1121-49cd-9d54-b798cd9aaad1)

**Describe alternatives you've considered**

I find that if I create a package with the same name of the public package my type alias is in, I could workaround this thing, but still, it's a literal copy of the func signature.

**Additional context**

None

**Comment by muirdm** [comment]
I'm assuming the signature of UseCoreDialer uses the exported type alias? This should be fixed in Go 1.23 since the alias name will be preserved in the type info gopls uses.

Note that currently gopls is explicitly unaliasing types, so it doesn't work yet even on tip. @adonovan I'm assuming there is work planned to make gopls preserve alias names in general?

> That is already the case where type aliases are used in simpler cases

That looks like another example of the same issue. Based on the desired behavior of gopls showing the type alias, the completion should be `&Response{}`, not `&http.Response{}`.

**Comment by adonovan** [comment]
> This should be fixed in Go 1.23 since the alias name will be preserved in the type info gopls uses.

Indeed, I just verified that the latest gopls release candidate built with the latest Go toolchain retains the alias in this case, and offers completions involving type aliases.

You can try it out by running this command with a pre-go1.23 toolchain:
```
$ go install golang.org/x/tools/gopls@v0.16.0-pre.3
```

**Comment by findleyr** [comment]
I believe this is (effectively) fixed with the upgrade to use materialized aliases.
