### ISSUE TITLE
x/pkgsite: package adding request for github.com/wttech/pulumi-aem/sdk

### ISSUE THREAD

**Issue by dominik-przybyl-wttech** [golang/go#67523]
I'm having trouble finding the package github.com/wttech/pulumi-aem/sdk on [pkg.go.dev](https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk). When I try, I just get a 404 error.

Steps to Reproduce:

1. Visit https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk.
2. Observe the 404 error page.

I also tried adding this package by sending a request to https://pkg.go.dev/github.com/wttech/pulumi-aem, but I got another 404 error with the message "github.com/wttech/pulumi-aem could not be found."

When I run:
`go list -m -versions github.com/wttech/pulumi-aem/sdk`
I get:
`github.com/wttech/pulumi-aem/sdk v0.1.1 v0.9.0 v0.9.1 v0.9.30 v0.9.31 v0.9.32 v0.9.33 v0.9.34`

Questions:

1. How can I add github.com/wttech/pulumi-aem/sdk to [pkg.go.dev](https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk)?
2. How do I remove the v0.9.* versions?

Please let me know if any additional details are needed.

**Comment by seankhliao** [comment]
it cannot be found because there is no module at the root of the repo
they've put it under /sdk
https://github.com/wttech/pulumi-aem/blob/main/sdk/go.mod

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
