### ISSUE TITLE
cmd/pprof: negative numbers in go tool pprof heap report in 1.22.3, but not in 1.22.2

### ISSUE THREAD

**Issue by ruz** [golang/go#67584]
### Go version

1.22.3

### Output of `go env` in your module/workspace:

```shell
---

Not sure how to get it from env where docker image is built and where service is executed.
```

### What did you do?

Took a heap profile from a running service (docker/k8s/linux) using instrumentation server opened on a dedicated port with built in pprof handlers. The service was built with 1.22.3. As far as I know all allocations tracking settings are at default values. Opened the profile using go tool pprof 1.22.3 on mac os. Got negatives all over, see screenshot.

Restarted service. Repeated experiment. Same result.

Built the service with 1.22.2. No negatives in the report.

In all experiments used 1.22.3 to view profiles.

Not sure I can provide more details, hope that it's easy to track regression in allocations tracking code.

<img width="759" alt="sceenshot 2024-05-22 в 12 29 45" src="https://github.com/golang/go/assets/42598/d368344b-bb0d-491f-99b4-543984a621f3">

### What did you see happen?

allocation report contained a lot of negative numbers

### What did you expect to see?

report without negative "memory in use" numbers

**Comment by seankhliao** [comment]
is it possible for you to show the profile?

**Comment by ruz** [comment]
I've tried to reproduce with a simple script that leaks goroutines and memory, but failed.

Hope somebody realize problem without me spending more time. If not then I will try to get around to it and cook some reproducible example. Not sure that I can publish profile as it is from a closed source project.

**Comment by nsrip-dd** [comment]
Are you using the `seconds` query parameter? Something like `/debug/pprof/heap?seconds=30`? If so, it's possible to see negative values for the live heap sample values (`inuse_space` and `inuse_objects`). The `seconds` parameter gives the _difference_ of two profiles collected that many seconds apart. If some memory was freed between when the profiles were collected, the values associated with some call stacks can be negative. Going off the example you shared, if there were open `Broker` connections when the first profile was collected, and they closed and their associated resources were freed by the time the second one was collected, it would be reasonable to see negative values for `inuse_space` and `inuse_objects` since there are fewer live allocations associated with the connections. As for the difference between 1.22.2 and 1.22.3, that could just be a coincidence. Perhaps memory usage happened to be increasing while you collected a profile running 1.22.2.
