### ISSUE TITLE
x/website: add more detail about GOPATH and where to clone src code in contribution guide

### ISSUE THREAD

**Issue by brite107** [golang/go#67659]
### What is the URL of the page with the issue?

https://go.dev/doc/contribute#checkout_go

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

### Screenshot

<img width="1236" alt="image" src="https://github.com/golang/go/assets/24356621/abbff6d6-b890-47ee-a2c2-542098137167">

### What did you do?

I followed the contribution guide, installed Go to ~/, and cloned the source code to ~/code/

### What did you see happen?

When I open the source code to get an idea of the code before picking an issue to work on, I have some errors. I will submit a screenshot: 
<img width="976" alt="image" src="https://github.com/golang/go/assets/24356621/92005690-9f22-460a-8c77-c6fb4c36eeef">
<img width="815" alt="image" src="https://github.com/golang/go/assets/24356621/1ee2ddc2-c14a-4bb1-9105-fcf031599c3b">

### What did you expect to see?

I expected to open the source code and not see any errors related to installation. I would love to see some more detail in the contribution guide about where to put the go installation and the go source code. As a first contribution, I would be interested in finding the information and adding it to the documentation myself.

**Comment by ansaba** [comment]
@dmitshur , can you check the loading error ?

**Comment by dmitshur** [comment]
The loading error happens because the main Go repository contains a development version of Go 1.23, which isn't released yet. In general, setting up gopls to work on the main Go repository is considered an advanced topic and documented in [x/tools/gopls/doc/advanced.md](https://github.com/golang/tools/blob/master/gopls/doc/advanced.md#working-on-the-go-source-distribution).

I don't currently see much discussion of setting up the editor, but perhaps something can be added under https://go.dev/doc/contribute#advanced_topics that at least links to relevant resources.
