### ISSUE TITLE
x/tools/gopls: spurious 'unused write' in package reflect

### ISSUE THREAD

**Issue by rsc** [golang/go#67684]
I opened reflect/type.go and gopls started telling me:

	/Users/rsc/go/src/reflect/type.go:1795.5,1795.5: unused write to field Dir
	/Users/rsc/go/src/reflect/type.go:1798.5,1798.5: unused write to field Elem
	/Users/rsc/go/src/reflect/type.go:2816.8,2816.8: unused write to field Elem
	/Users/rsc/go/src/reflect/type.go:2831.8,2831.8: unused write to field Slice

This is false. The code for the first two errors is:

	// Make a channel type.
	var ichan any = (chan unsafe.Pointer)(nil)
	prototype := *(**chanType)(unsafe.Pointer(&ichan))
	ch := *prototype
	ch.TFlag = abi.TFlagRegularMemory
	ch.Dir = abi.ChanDir(dir)
	ch.Str = resolveReflectName(newName(s, "", false, false))
	ch.Hash = fnv1(typ.Hash, 'c', byte(dir))
	ch.Elem = typ

	ti, _ := lookupCache.LoadOrStore(ckey, toRType(&ch.Type))
	return ti.(Type)

What the analyzer doesn't see is that &ch.Type provides access to all of ch.

/cc @rfindley @adonovan

**Comment by findleyr** [comment]
CC @timothy-king 

I suspect it would be enough for the analyzer to differentiate between implicit field access and explicit field references, bailing out for the latter. That would preserve most of the usefulness and avoid these types of false positives.

This looks (naively) like a pretty straightforward fix. Putting in the gopls@v0.17.0 milestone.

**Comment by adonovan** [comment]
> What the analyzer doesn't see is that &ch.Type provides access to all of ch.

`toRType` involves a C-stylt case to coerce a `*T` a pointer to a `*struct{T; ...}` pointer. I don't expect the analysis to be able to handle that, nor do I imagine this is a common thing to do in Go code outside the runtime.

Perhaps the analyzer should just be silent in packages that import `"unsafe"`?

**Comment by findleyr** [comment]
> Perhaps the analyzer should just be silent in packages that import "unsafe"?

That was my first thought as well, but there's no reason the cast must be in the same package as the field addr.

**Comment by adonovan** [comment]
> there's no reason the cast must be in the same package as the field addr.

Well, there kind of is: it is very bad form to expose unsafe public API.

There could be a constellation of internal packages working together this way, but that may be rare enough to justify the heuristic.

**Comment by MikeMitchellWebDev** [comment]
> > What the analyzer doesn't see is that &ch.Type provides access to all of ch.
> 
> `toRType` involves a C-style cast to coerce a `*T` pointer to a `*struct{T; ...}` pointer. I don't expect the analysis to be able to handle that, nor do I imagine this is a common thing to do in Go code outside the runtime.
> 
> Perhaps the analyzer should just be silent in packages that import `"unsafe"`?

According to the information available here a significant number of  packages import [unsafe ](https://pkg.go.dev/unsafe?tab=importedby)

**Comment by findleyr** [comment]
@MikeMitchellWebDev pkg.go.dev reports over 4m importers of fmt, so the number of packages importing unsafe is at most 2-3%, probably more like 1-2%. Skipping this specific heuristic in the presence of unsafe seems acceptable.

**Comment by findleyr** [comment]
Circling back, I'm rethinking this after making the above CL.

Why don't we just mark all fields in the value as live if any of them are address-taken? That seems like a more principled fix, and I still think the analyzer would catch most of the bugs it currently catches.

**Comment by adonovan** [comment]
> Circling back, I'm rethinking this after making the above CL.
> 
> Why don't we just mark all fields in the value as live if any of them are address-taken? That seems like a more principled fix, and I still think the analyzer would catch most of the bugs it currently catches.

In the course of reviewing your CL I have been studying this analyzer, which is sorely lacking in documentation. Its approach is to work back from stores of the form `x.f=v` and `x[i]=v` to find all references to x. If it finds a non-storing use of x it considers the original store x to be live. Unsafe pointer conversions `u.P(&x)` are not considered to make x.f live, nor are unsafe.Pointer conversions of the first field or element, `u.P(&x.field0)` or `u.P(&x[0])`, which can be coerced to `&x`.

The analyzer only works on simple local control flow because it has no alias analysis. So, `if cond { ptr=new(T) } else { ptr=nil }` would confuse it because the value of ptr after the `if` statement is a phi, which is distinct from new(T).

I think the analyzer would be clearer expressed as a forwards analysis (instead of using SSA referrers) that marked every storing and non-storing use of each object and field, as this would allow it to see unsafe.Pointer conversions easily, and to traverse through phi nodes conservatively.

Back to your question: I suspect marking the all fields live if any is address-taken would be far too conservative. In any case it would require a similar restructuring to what I just described.
