### ISSUE TITLE
encoding/csv: add the true number of lines to ErrFieldCount

### ISSUE THREAD

**Issue by btracey** [golang/go#6770]
<pre>In Reader.Read(), if the true record length is not equal to the FieldsPerRecord field,
an ErrFieldCount error is returned. It would be nice if this error also included the
expected and found number of lines. So, for example, instead of the error string being
&quot;wrong number of fields in line&quot;, it would be instead &quot;wrong number of
fields in line. 15 read, 10 expected&quot;. The specific problem I encountered was that
my csv file had an extra delimiter at the end of the line, so one more record was read
than I expected. If the error message had also listed that there was one more record
than expected it would have been much easier to debug.</pre>

**Comment by nussjustin** [comment]
I think the easiest fix here is to add a new field "Field" to ParseError, which would contain the number of the field where the error occured (e.g. `a,b"", c` would report Field == 2), which for the ErrFieldCount case would contain the number of fields.

/cc @bradfitz

**Comment by nussjustin** [comment]
Both 11 and 15 could make sense, although I think 11 makes more sense especially since in the ErrFieldCount case Read also returns the record along with the error, so the user can get the field count using len(record) even now.

15 would make sense as the code always reads the whole record before checking the field count. Although this could be seen as an implementation detail it is exposed as the returned slice.

I'm personally fine with both.

Field could also be 0-based. This basically only matters for the ErrFieldCount case as it's the only case where the user has an error and the records read. It would make accessing the fields more simpler (no -1 required), but I think that's all it does.

**Comment by bradfitz** [comment]
The problem with 0-based (even if it makes more sense) is then you either have to always use it, or document on on the new ParseError.Field docs when it's defined and when it's not. Saying "when it's non-zero" is much easier than enumerating a list of reasons.

**Comment by nussjustin** [comment]
I agree with you that the 1-based variant is easier.

I'm still unsure about the value of Field for ErrFieldCount, but am leaning towards FieldsPerRecord+1. What's your opinion on this?

**Comment by bradfitz** [comment]
> especially since in the ErrFieldCount case Read also returns the record along with the error, so the user can get the field count using len(record) even now.

If the user can already get 15 and they set 10, I think this whole bug is kinda useless. Who cares if we report 11, 12, 13, 14, or 15? The user set 10 and we returned len() of 15 and ErrFieldCount. Can't they draw their own conclusions?

**Comment by nussjustin** [comment]
Yes. It would probably make more sense for the non-ErrFieldCount cases where the field could be more important and the user has just the column (rune index) of the error, although I can't currently think of a real use case where just the column isn't enough. I only thought about the possibility of using len(record) when writing my second comment. 

So yeah, this whole bug is really kinda useless in retrospective.
