### ISSUE TITLE
cmd/compile: invalid for range loop executes w/o error message

### ISSUE THREAD

**Issue by griesemer** [golang/go#6772]
<pre>This program

<a href="http://play.golang.org/p/RXFJJh5KRw">http://play.golang.org/p/RXFJJh5KRw</a>

reports an error as expected, albeit a confusing one. This is related to, or the same as
<a href="https://golang.org/issue/6764">issue #6764</a>.

A short variable declaration in a for range loop can never redeclare an existing
variable because a for statement opens a new scope and thus there are no variables
declared earlier in that scope. So there should be a double declaration error.

Interestingly, adding an external declaration appears to &quot;fix&quot; the problem:

<a href="http://play.golang.org/p/4spddNy6Ki">http://play.golang.org/p/4spddNy6Ki</a>

The code compiles and runs without errors. Output:
0
1
2
3

Here it looks like the short variable declaration actually was handled like a
redeclaration of the outer a. Interestingly, value assigned to a is the index and not
the indexed element. Contrast this (and its output) to the following correct program:

<a href="http://play.golang.org/p/BWZD1fCWKj">http://play.golang.org/p/BWZD1fCWKj</a>

Output:
1
2
3
3</pre>

**Comment by odeke-em** [comment]
@griesemer, it seems like CL https://go-review.googlesource.com/c/4851 solved the
issue(the CL is from February 2015, while this issue is from November 2013) repros
in https://github.com/golang/go/issues/6772#issue-51285695
* https://play.golang.org/p/RXFJJh5KRw
* https://play.golang.org/p/4spddNy6Ki
both fail to compile with error `a repeated on left side of :=`
which are the expected results.

Let me write a CL to lock in this behavior with tests.
