### ISSUE TITLE
math: trigonometric argument reduction fails for huge arguments

### ISSUE THREAD

**Issue by lexprfuncall** [golang/go#6794]
<pre>Here is a test program

<a href="http://play.golang.org/p/lROOy0Hekp">http://play.golang.org/p/lROOy0Hekp</a>

The value 2^120 is exactly represented as a float64.  A different, incorrect answer is
returned by 8g (0.4779...).  The right answer is returned by gccgo on an 64-bit x86
(-0.9258...).  The wrong answer is returned by gccgo on 32-bit x86 where the cos
function doesn't seem to compute anything and behaves like the identity function.</pre>

**Comment by dr2chase** [comment]
I'm pretty sure use of fdlibm would fix this.  That's the case for Java, for instance, where I did an implementation of FP stuff once upon a time.  387 math uses a 66-bit approx of pi for arg reduction (bits 67 and 68 are zero), so things fall apart for inputs as small as sin(machine_rep_of_PI), where by "fall apart" I mean that a float64 answer has (about) 15 correct bits in its mantissa instead of the hoped-for (about) 53.  (sin(machine_rep_of_pi) approx= pi - machine_rep_of_pi. mrop = first 53 bits of pi, appropriately rounded, so what the subtraction is supposed to give you is the NEXT 53 bits of pi (ignore rounding for now), but only 15 (68-53) are available, and the rest are zero.

This is substantially worse than the claimed precision at the time, which was one ulp.

Once upon a time, Sun's JIT would wrongly use the hardware instruction when it decided that your code was hot, which meant that it would work right at first, then change to wrong, and it would change to wrong faster on multiprocessors because the JIT compiler got a chance to run early.

**Comment by MichaelTJones** [comment]
The right answer is indeed -0.9258... as stated above.

cos(2^120) = -0.925879022854837867303861764107414946730833209928656460236049372618839291445382039698667367235188503605454959090834167176783445531614718194354868603064477383826066930073681426232927237014395564232737502670263136419514308982212308324981128756091768991384727116127182343614687859734231062568153628963751154387657011813354119526431689238651865868571354193068903448888710998317926597877246757860980497318

**Comment by robpike** [comment]
Ivy says
-0.92587902285483786730386176410741494673083320992866
and it's got lots of bits (I ran with 1024, far more than 120) and uses a Taylor series. I trust the result.

**Comment by bmkessler** [comment]
Quoting the relevant literature list from #7110 to have it centralized here:

> The problem is due to catastrophic errors introduced during argument reduction. There's
> very little literature besides the classic Payne & Hanek argument reduction paper:

> Payne & Hanek: "Radian reduction for trigonometric functions"
> http://dl.acm.org/citation.cfm?id=1057602 (ACM paywall)
> Sun's implementation:
> K. C. Ng, "Argument Reduction for Huge Arguments: Good to the Last Bit"
> http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.67.5616&rep=rep1&type=pdf and:
> http://www.validlab.com/arg.txt
> A newer approach:
> http://www.imada.sdu.dk/~kornerup/papers/RR2.pdf
> http://perso.ens-lyon.fr/jean-michel.muller/RangeReductionIEEETC0305.pdf

Note, the last two papers actually fall back to use Payne & Hanek's method when the argument is >= 2^63-1 so it seems like Payne & Hanek is the method to use for very large arguments.

Also, since root cause of the issue was already identified, it might make sense to rename this issue to something more like "math: trigonometric argument reduction fails for huge arguments" or similar.

**Comment by griesemer** [comment]
Related: The default calculator on Android version 9 also produces accurate results rounded to 32 decimal digits of mantissa for trigonometric functions, even for very large inputs (such as the test cases in https://golang.org/cl/153059, e.g. sin(1234567891234567 * 2^300)).

(Use calculator in "horizontal" mode for the extended mantissa).
