### ISSUE TITLE
sync: incorrect documentation for `(*RWMutex).RLocker`

### ISSUE THREAD

**Issue by gazerro** [golang/go#68250]
Commit cab90c8 has incorrectly changed the documentation of `(*sync.RWMutex).RLocker` to reference `RWMutex.Lock` and `RWMutex.Unlock` instead of `Locker.Lock` and `Locker.Unlock`:

```
// RLocker returns a [Locker] interface that implements
// the [RWMutex.Lock] and [RWMutex.Unlock] methods by calling rw.RLock and rw.RUnlock.
```

The correct documentation should be

```
// RLocker returns a [Locker] interface that implements
// the Lock and Unlock methods by calling rw.RLock and rw.RUnlock.
```

**Comment by MikeMitchellWebDev** [comment]
Wouldn't it be sufficient to say `"// RLocker returns a [Locker] interface"` since it wouldn't be a Locker interface unless the  Lock and Unlock methods had been implemented by rlocker. It's redundant to say anything more unless you're trying to educate about what an interface is but that's probably not necessary here.
