### ISSUE TITLE
x/website: show anchor links for article headings

### ISSUE THREAD

**Issue by hyangah** [golang/go#68596]
Reveal anchor links to headings, so users can copy the link to the specific part of the doc easily.

Before
<img width="184" alt="Screenshot 2024-07-26 at 5 40 31 AM" src="https://github.com/user-attachments/assets/b237bf4b-3233-4d9c-a26b-4872e1594d47">

After - the "¶" symbol appears when hover. On Chrome, right click on it will show the context menu so users can operate on the anchor link.
<img width="270" alt="Screenshot 2024-07-26 at 5 43 04 AM" src="https://github.com/user-attachments/assets/c2111b44-a393-4721-bdf2-1d3ec9fb4eb1">

**Comment by matttproud** [comment]
@hyangah, thank you so much for doing this!  The lack of this has bothered me for years and caused me to open up the inspector for each heading's ID to deep link to blog article sections!  I am elated I no longer have to do this.

**Comment by mvdan** [comment]
@hyangah just one request - when I hover over "Doc Links", nothing happens - which is why I didn't even realise this got fixed earlier today. I have to move my cursor to the right of the heading - where the "reverse P" anchor symbol would be - for it to appear, as if I had to know ahead of time it would be there.

Can we make the anchor link show up whenever I hover over any of the heading area too? I think this is how anchor link hovers usually work on other websites, or at least that's how I intuitively think they work.

**Comment by cespare** [comment]
> Can we make the anchor link show up whenever I hover over any of the heading area too? I think this is how anchor link hovers usually work on other websites, or at least that's how I intuitively think they work.

In particular, it's how the anchor links work on pkgsite ([example](https://pkg.go.dev/net/http)).

@mvdan I think you should just file a separate bug so it doesn't get dropped.
