### ISSUE TITLE
regexp: confusing ReplaceAllString result when using patterns like `$1_$2`

### ISSUE THREAD

**Issue by 17thread** [golang/go#68712]
### Go version

go version go1.20.3 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zhouchi9\AppData\Local\go-build
set GOENV=C:\Users\zhouchi9\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\CodeEnv\Go\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\CodeEnv\Go\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\CodeEnv\Go\Go1.20.3
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\CodeEnv\Go\Go1.20.3\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\zhouchi9\AppData\Local\Temp\go-build2519956868=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

我想将驼峰的字符串中间插入一个下划线，可是并没有达到预期

[问题复现链接](https://go.dev/play/p/1BN__f6iOZV)

### What did you see happen?

输入参数：cNcHDhCh
程序结果：NHDCh

### What did you expect to see?

预期：c_Nc_HDh_Ch

**Comment by ALTree** [comment]
From the [Expand documentation](https://pkg.go.dev/regexp#Regexp.Expand):

> In the template, a variable is denoted by a substring of the form $name or ${name}, where name is a **non-empty sequence of letters, digits, and underscores.**

Since the underscore _ in a valid character for an $-name, Expand is seeing two $-variables: one named $1_ and a numeric one ($2). The second work, the first doesn't refer to anything, so the [a-z] part of the match is simply not included in the replacement.

Unfortunately I think it's not possible to insert a `_` character in this was. You could use "`$1 _$2"` (the space prevents $1_ from being recognized as a single token) and then do a second pass on the string to strip the spaces before the `_`.

**Comment by tdakkota** [comment]
It is possible to insert `_` via `${1}_${2}`.

https://go.dev/play/p/3GUENtz8VQA

**Comment by 17thread** [comment]
谢谢， 看了文档，做了下改动 ${1}_${2}

**Comment by 17thread** [comment]
resolved

**Comment by ALTree** [comment]
> It is possible to insert `_` via `${1}_${2}`.
> 
> https://go.dev/play/p/3GUENtz8VQA

Nice! Closing.
