### ISSUE TITLE
io: define SeekStart, SeekCurrent, SeekEnd constants for use with Seeker

### ISSUE THREAD

**Issue by minux** [golang/go#6885]
<pre>see <a href="https://golang.org/issue/6873">issue #6873</a>, and <a href="https://golang.org/cl/36810043/">https://golang.org/cl/36810043/</a>.

&gt; We already have these in pkg/os, also with this TERRIBLE_CASE. Let's stop the
bleeding.
&gt; In Go 2 we could move them and fix the case or maybe even change the signature to
not be so C-like.</pre>

**Comment by extemporalgenome** [comment]
Could we just duplicate those three "whence" consts into io, with properly cased names? (i.e. `io.SeekEnd`)

@nightlyone `Size() int64` is a method that shows up occasionally, and its semantics are consistent across implementations. Instead of having separate methods for rewind and such, why not just use the existing interface, but have no-random-access implementations return errors on seeks they don't support?

**Comment by rsc** [comment]
I like @extemporalgenome's suggestion. Maybe for Go 1.7.
