### ISSUE TITLE
cmd/go: "go env GOTELEMETRY" should not be an alias of "go telemetry"

### ISSUE THREAD

**Issue by zigo101** [golang/go#68936]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
.
```

### What did you do?

```
$ go env GOTELEMETRY
off
$ go telemetry
off
$ go env -changed
GOSUMDB='off'
GOTOOLCHAIN='local'
GCCGO='/usr/bin/gccgo'
```

### What did you see happen?

`go env` treats `GOTELEMETRY` as env var.

### What did you expect to see?

`go env` sometimes treats `GOTELEMETRY` as env var, sometimes not. It is confused.

Consistency is important. `go env` and `go env -changed` should have the same attitude.

Related: https://github.com/golang/go/issues/68930

**Comment by seankhliao** [comment]
`go env` already reports various unsettable settings for debugging purposes such as `GOVERSION`, `GOMOD`, `GOWORK` in addition to `GOTELEMETRY`. It is quite useful for troubleshooting issues.

**Comment by zigo101** [comment]
It is reasonable that `go env -changed` doesn't include `GOVERSION`, `GOMOD` and `GOWORK`.

But the value of `GOTELEMETRY` is configurable. If is confused that if is not reported by `go env -changed` when it isn't default.

**Comment by seankhliao** [comment]
GOTELEMETRY is not configurable, it's a separate setting set form `$user_config_dir/go/telemetry/mode`

**Comment by zigo101** [comment]
```
$ go telemetry local
$ go env GOTELEMETRY
local
$ go telemetry off
$ go env GOTELEMETRY
off
```

**Comment by ianlancetaylor** [comment]
@zigo101 It sounds like you are saying that the bug here is that `go env -changed GOTELEMETRY` does not correctly report that `GOTELEMETRY` has changed after someone runs a command like `go telemetry on`. Is that correct?

The bug title is that `go env GOTELEMETRY` should not be an alias of "go telemetry"`, but I don't see any obvious reason that that is buggy.

If I've misunderstood, can you show  a sequence of commands that demonstrates a problem?  I don't see any problem in the original post or in https://github.com/golang/go/issues/68936#issuecomment-2295940214.  Thanks.

**Comment by zigo101** [comment]
If is just that the value of the env var of `GOTELEMETRY` is user configed, but when it is not the default value, it is not listed in `go env -changed`. That is werid. So either remove this env var or fix `go env -changed` will remove the weirdness.
