### ISSUE TITLE
encoding/json, encoding/xml: option to treat unknown fields as an error

### ISSUE THREAD

**Issue by lukescott** [golang/go#6901]
<pre>Currently unknown fields are silently ignored when decoding into a struct. I would like
to have an option to treat unknown fields as an error.

This would be extremely helpful for a REST API to help third-party developers identify
typos. In this particular case I don't need an &quot;inline&quot; tag as I don't need to
do anything with the extraneous fields. I just need to tell the recipient that they
included something the server doesn't understand.</pre>

**Comment by adg** [comment]
One way to do this would be to add a `Strict` method to the `Encoder` and `Decoder` types. While we're at it we could also make indentation on `Encoder` possible with an `Indent` method.

**Comment by h4ck3rm1k3** [comment]
I have a simple patch for this for json #10134

**Comment by cespare** [comment]
We should do this. Today, I'm aware of two workarounds:

- Separately unmarshal the object into a map in order to obtain and inspect the key set.
- Use pointers for all field values. For example, the github.com/google/go-github API wrapper [uses pointer fields](https://github.com/google/go-github/blob/master/github/issues.go#L22-L38) as a rule for this reason. (But even then, you can't distinguish between `"k":null` and a missing key.)

Besides some way to change the decoder "mode" (as @adg suggested), here's another way it could work: add a `,required` struct field tag which causes Unmarshal to give an error if no key matches that field.

**Comment by adg** [comment]
Closing this in favor of #15314, which is identical and more active.
