### ISSUE TITLE
website: retina favicon

### ISSUE THREAD

**Issue by josharian** [golang/go#6938]
<pre>Any chance the golang.org favicon could get a retina-display-friendly refresh? That
little fellow is all over my tabs, and while I hear that the pixelated look is all the
rage nowadays, I can't help but think that the gopher might feel more comfortable in
crisp, high-definition blue.</pre>

**Comment by egonelbre** [comment]
Because github doesn't support uploading [favicon.ico](https://dl.dropboxusercontent.com/u/4300994/Go/favicon.ico) and [svg here](https://github.com/egonelbre/gophers/blob/master/mini/icons.svg) with some alternatives. I can make it a CL, but not sure how good go-review is for discussing images.

favicon.ico contains sizes 16, 32, 48, 64, 110, 114, 128, 256... I can cut some of them, if necessary, because the size increase was from 1kb -> 180kb. Alternatively I can submit multiple files. However, not sure which [sizes](http://www.visualpharm.com/articles/icon_sizes.html) we should add.

**Comment by bradfitz** [comment]
@broady, @adg, @robpike?

**Comment by broady** [comment]
This lil guy looks so perfect, but having one similar to the current but in high res would be good, too.
![screen shot 2016-08-10 at 3 20 27 pm](https://cloud.githubusercontent.com/assets/24982/17573249/074330a8-5f0e-11e6-9fa1-1537abc816c6.png)

A CL via Gerrit would be fine. I can pull apart the ico file to see what's in there.

From about 2 minutes of research, I think we just want 16 and 32.

**Comment by adg** [comment]
I asked Renee and she prefers the straight one (similar to the current one). I concur. We should stick with the same color too.

**Comment by broady** [comment]
adg, do you have the original? Or is it pixel art?

**Comment by adg** [comment]
The original is pixel art

**Comment by bradfitz** [comment]
Comparison of before & after CL 26850:

<img width="108" alt="compare" src="https://cloud.githubusercontent.com/assets/2621/17580157/485b5ac8-5f51-11e6-8723-89a192732113.png">

**Comment by egonelbre** [comment]
![Comparison with different background colors](https://cloud.githubusercontent.com/assets/192964/17617951/8ef662b8-6085-11e6-9287-dc8b8c209437.png)

**Comment by dsnet** [comment]
What's up with the lack of alpha channels (e.g., the gross looking white outline above the head) in these previews?

**Comment by egonelbre** [comment]
@dsnet those are artifacts in the old favicon. Usually caused by first drawing the image on white background, then deleting the background color. Such method can only give good results when the outline isn't blended with the background.
