### ISSUE TITLE
spec: incorrect comment in example for method set of newly defined type

### ISSUE THREAD

**Issue by TutiFrouti** [golang/go#69598]
### What is the URL of the page with the issue?

https://go.dev/ref/spec#Type_declarations

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/user-attachments/assets/d8a413f6-1531-4bdb-857d-7b9b23aaaa3b)

### What did you do?

In one of the example for a type definition related to the method set of the newly defined type, the specification states the following (I bolded myself)::

> // A **Mutex** is a data type with two methods, Lock and Unlock.
> `type Mutex struct         { /* Mutex fields */ }`
> `func (m *Mutex) Lock()    { /* Lock implementation */ }`
> `func (m *Mutex) Unlock()  { /* Unlock implementation */ }`

However, it is not accurate. `Mutex` is a base type in method declaration for both methods, but `*Mutex` data type has a `Lock` and `Unlock` methods, not `Mutex`.

### What did you see happen?

Inaccurate comment in the example.

### What did you expect to see?

I expect the specification to be updated, that is, to change the following:

> // A Mutex is a data type with two methods, Lock and Unlock.

to:

> // A *Mutex is a data type with two methods, Lock and Unlock.

**Comment by zigo101** [comment]
BTW, `Mutex` has 3 methods now.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by zigo101** [comment]
So, a type `T` may have a method but its method set has not the method.

Wording is hard ...

**Comment by zigo101** [comment]
It looks the error message of the following code indicates that `Lock` is only a pointer method.

```Go
package main

func main() {
	Mutex{}.Lock() // error: cannot call pointer method Lock on Mutex
}

// A Mutex is a data type with two methods, Lock and Unlock.
type Mutex struct { /* Mutex fields */
}

func (m *Mutex) Lock()   { /* Lock implementation */ }
func (m *Mutex) Unlock() { /* Unlock implementation */ }
```

**Comment by griesemer** [comment]
@zigo101 The statement "type T has a method m" is a colloquial (and thus somewhat imprecise) way of saying "type T has a method m _declared_ with receiver T". On the other hand, the term "method set" is defined precisely in terms of methods and their receiver types ([spec](https://golang.org/ref/spec#Method_sets)).

Regarding your error message example: You are calling Lock on a (non-addressable!) _value_ of type Mutex. The method set of the (non-pointer) Mutex consists of all methods declared with Mutex (not *Mutex!) as receiver type. Hence the error message is correct. In fact, Lock _is_ only a pointer method.

On the other hand, if you had a _variable_ of type Mutex, it would work because Go automatically takes the address of the variable in that case and then you have a *Mutex ([playground](https://go.dev/play/p/PwwQv8kFRgS)). See the [spec about Calls](https://golang.org/ref/spec#Calls), last paragraph:

> A method call x.m() is valid if the [method set](https://tip.golang.org/ref/spec#Method_sets) of (the type of) x contains m and the argument list can be assigned to the parameter list of m. If x is [addressable](https://tip.golang.org/ref/spec#Address_operators) and &x's method set contains m, x.m() is shorthand for (&x).m():

**Comment by zigo101** [comment]
I understand all the logic and think the descriptions in spec are okay, though maybe they can be improved.

**Comment by TutiFrouti** [comment]
@griesemer Is then the following a correct way to interpret @zigo101 example:

> Data type **Mutex** (not *Mutex) has the method `Lock` with the receiver `*Mutex` and the method `Unlock` with the receiver `*Mutex`. Method set of the pointer receiver of the base type `Mutex`, which is `*Mutex`, consists of both `Unlock` and `Lock` methods, whereas method set of the non-pointer receiver of the base type `Mutex`, which is `Mutex` itself, is empty.

**Comment by griesemer** [comment]
@TutiFrouti Yes. A method set is always relating to a value of a given type, so a clearer way of saying this is: the method set of a value _of type_ `*Mutex` consists of the methods `Lock` and `Unlock`. Thus, given such a value, you can call one of these methods on it. And yes, if the value has type `Mutex`, its method set is empty.

To make it intuitively clear: if you have a value of type `T`, obviously you can call a method (declared with `T`) with receiver `T`. Similarly, if you have a value of type `*T`, obviously you can call a method with receiver `*T`. After all, the receiver is just an ordinary argument and the types must match.

The only addition to this is that if you have a value of type `*T` you can also call methods with receiver `T` (hence this method set includes methods with pointer and non-pointer receivers). Why is that? Because given a `*T` value, you can always get `T` value by dereferencing it.

On the other hand, if you have a `T` _value_ `x`, you cannot in general get a `*T` from it: `&x` is not always allowed. Hence the asymetry in the type set rules.

But, and that's the other rule, if you have an _addressable_ `v` (such as a variable) of type `T`, one can always determine `&v` and thus get a `*T` value. Hence, in that case even a non-pointer method may be called (even though those are not in the `T` method set).

Hope this helps.

For further discussion, please reach out to the community. This issue is now closed. Thanks.
