### ISSUE TITLE
x/website: code and other elements no longer display in TOC

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#69816]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Looked at https://go.dev/doc/faq.

### What did you see happen?

See, for example, https://go.dev/doc/faq.  The TOC has several incomplete entries, such as "Why is" and "Why does Go not have the".  These are because the headers in _content/doc/faq.md uses header lines like

    ### Why is `len` a function and not a method? {#methods_on_basics}

and

    ### Why does Go not have the `?:` operator? {#Does_Go_have_a_ternary_form}

In https://go.dev/cl/601055 for #68596 the TOC code was changed to only display the first element. That is causing the truncation we see here.

CC @hyangah @dmitshur

### What did you expect to see?

Untruncated TOC lines.

**Comment by dmitshur** [comment]
[CL 601055](https://go.dev/cl/601055) added made the change to start using `node.firstChild.textContent` as the TOC item text, instead of `$(node).text()`. It looks like it was trying not to include the '¶' symbol that the new setAnchors adds. Their current order is:

One of the ways to fix this is to go back to using text, but arrange for setAnchors to run after generateTOC, not the other way around as it currently happens:

```
setAnchors is being scheduled
generateTOC is being scheduled
setAnchors is starting
generateTOC is starting
```

Another approach might be to leave their current running order as is, but modify generateTOC to take into account it ran after setAnchors and not include the '¶' symbol in a different way, one that doesn't cut off text content beyond the first child element.

**Comment by dmitshur** [comment]
[CL 618635](https://go.dev/cl/618635) changes the order to be:

```
setAnchors is being scheduled
generateTOC is being scheduled
generateTOC is starting
setAnchors is starting
```

<img width="320" alt="image" src="https://github.com/user-attachments/assets/864930a6-8aba-40a2-9e0f-3a1722b9ba77">
