### ISSUE TITLE
proposal: x/net/quic: add LocalAddr and RemoteAddr to quic.Conn

### ISSUE THREAD

**Issue by jfgiorgi** [golang/go#70138]
### Proposal Details

LocalAddr() and RemoteAddr() are missing from quic.Conn (to be on par with net.Conn).

**Comment by neild** [comment]
I think this can be considered a continuation of #58547 rather than go through the official proposal process. #58547 was accepted with the understanding that the package API would evolve over the course of implementation.

Adding LocalAddr and RemoteAddr to quic.Conn seems reasonable--this is information that's useful to have, and we currently don't have any way to report the remote address for connections we accept.

The comparison to net.Conn isn't a good one, though: A net.Conn is a stream-oriented connection, and a quic.Conn multiplexes many streams. They aren't the same thing, and quic.Conn will never implement net.Conn.
