### ISSUE TITLE
syscall: SyscallN always escapes the variadic argument

### ISSUE THREAD

**Issue by qmuntal** [golang/go#70197]
### Go version

go version devel go1.24-bea9b91f0f Tue Nov 5 01:16:03 2024 +0000 windows/amd64

### What did you do?

Run `go build -gcflags=-m .`
```go
package main

import (
	"syscall"
	"unsafe"
)

var sink byte
var procProcessPrng = syscall.NewLazyDLL("bcryptprimitives.dll").NewProc("ProcessPrng").Addr()

func main() {
	var buf [10]byte
	syscall.SyscallN(procProcessPrng, uintptr(unsafe.Pointer(&buf[0])), uintptr(len(buf)))
	sink ^= buf[0]
}
```

### What did you see happen?

The `syscall.SyscallN` variadic argument escaped to the heap.

```
./main.go:13:18: ... argument escapes to heap
```

### What did you expect to see?

The `syscall.SyscallN` variadic argument didn't escape to the heap, just as other `syscall.SyscalX` functions.

```
./main.go:13:18: ... argument does not escape
```

Note that `syscall.SyscallN` is implemented by `runtime.syscall_syscalln`, which makes sure that the variadic argument doesn't escape:

https://github.com/golang/go/blob/bea9b91f0f4be730c880edbe496ab25c9b742cad/src/runtime/syscall_windows.go#L519

@golang/compiler @golang/windows

**Comment by qmuntal** [comment]
This issue is blocking the use of `syscall.SyscallN` in `x/sys/windows/mkwinsyscall`, see [CL 623821](https://go-review.googlesource.com/c/go/+/623821/comments/b75078a6_06cf4afe).

**Comment by dmitshur** [comment]
@qmuntal I'm a bit confused by the specifics in your question (maybe you got the wrong CL number mentioned? that one pulls in many x/sys CLs all at once), but in general, if there is a serious issue without a workaround and we can be confident the fix is narrow and small, please [create the backport issues](https://go.dev/wiki/gopherbot#backporting-issues) with the rationale and we will consider it. See https://go.dev/wiki/MinorReleases#cherry-pick-cls-for-vendored-golangorgx-packages for details on a single x/sys CL can be backported to the vendored packages on 1.23/1.22 release branches.

**Comment by qmuntal** [comment]
> I'm a bit confused by the specifics in your question (maybe you got the wrong CL number mentioned?

Wops, I linked the wrong CL. I was referring to [625297](https://go-review.googlesource.com/c/go/+/625297).

I'll create the backport issue, thanks for the pointer.

**Comment by qmuntal** [comment]
@gopherbot please open the backport tracking issues. `syscall.SyscallN` alternatives are deprecated, and there is the risk of users switching back to them if `syscall.SyscallN` is less performant.
