### ISSUE TITLE
net: DNS lookup on Windows returns "server misbehaving"

### ISSUE THREAD

**Issue by piclemx** [golang/go#70191]
### Go version

1.23

### Output of `go env` in your module/workspace:

```shell
CGO_ENABLED=1 
GOOS=windows 
GOARCH=amd64 
CC=x86_64-w64-mingw32-gcc
```

### What did you do?

We did upgrade one of CLI to go 1.23 and we started to get this
```
Simple HTTP call to a service result every time with an dial tcp: lookup DNS on IP:53: server misbehaving
```

That service is working when using the browser or just a simple curl command.

### What did you see happen?

dial tcp: lookup DNS on IP:53: server misbehaving

### What did you expect to see?

I was expecting that this will do a normal http call has before and just return back the response from the backend.

**Comment by piclemx** [comment]
Downgrading to go 1.22 make everything works again

**Comment by ianlancetaylor** [comment]
This happens when the Go program receives a DNS packet with a response code that is neither NoError nor NXDomain.  It would help to see a dump of the DNS packets, if possible.  It's hard to see why this change between 1.22 and 1.23, though.

One thing you could try is setting `GODEBUG=netedns0=0` in the environment.

CC @golang/windows

**Comment by piclemx** [comment]
Ok, let me check tomorrorw.

**Comment by shreevari** [comment]
@piclemx Did you check this out? I'm seeing this issue too, while connecting to AWS via their golang SDK

**Comment by piclemx** [comment]
no, I did have a hard time getting it since i don't own a windows computer
