### ISSUE TITLE
docs: log/slog: ExampleDiscardHandler not shown on pkg site

### ISSUE THREAD

**Issue by earthboundkid** [golang/go#70782]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

Went to https://pkg.go.dev/log/slog@master#DiscardHandler

### What did you see happen?

No example code

### What did you expect to see?

The ExampleDiscardHandler from https://cs.opensource.google/go/go/+/master:src/log/slog/example_discard_test.go

**Comment by ianlancetaylor** [comment]
Names like `ExampleName` are only attached to types and functions with those names.  `DiscardHandler` is a variable.  So I think the problem is that there is no place to attach `ExampleDiscardHandler`.  Perhaps we should rename it to `Example_DiscardHandler`, so that it becomes a package-level example.

CC @jba

**Comment by jba** [comment]
Agreed.
