### ISSUE TITLE
net, syscall: implement network interface API on Solaris

### ISSUE THREAD

**Issue by mikioh** [golang/go#7177]
<pre>Solaris supports routing socket, so it would not be tough.</pre>

**Comment by postwait** [comment]
This should provide the support for interfaces and addresses (sans Multicast for which there is a separate issue files).

https://github.com/postwait/go/commit/d482dd74bcdc1b712d7929f321b56488335379b8

**Comment by bradfitz** [comment]
@postwait, we can't take patches that way. Everything that goes into one of the Go repos needs a CLA agreement. See https://golang.org/doc/contribute.html . That page is a wall of text, but it's easier than it looks.

**Comment by postwait** [comment]
@bradfitz I just posted it here for other people to play with.... I already put it here as well..

https://go-review.googlesource.com/#/c/29190/

**Comment by postwait** [comment]
One issue with the code is that it fails the net.TestInterfaces

It would seem that the go code assumes that an ifindex on an interface unique refers to a set of properties on the interface.  On Solaris... ifindex+family uniquely describe this.

So, on my box there are two interfaces with ifindex: 1... one is IPv4 and the other is IPv6... the test fails because these two interfaces have different MTUs.

I see two solution... fake an ifindex, or unbreak this uniqueness assumption.

**Comment by bradfitz** [comment]
@mikioh, preferences?

**Comment by postwait** [comment]
A "bad solution" but flexible is to have this make the ifindex's act as

go_ifindex := (ifindex * 256) + family

It would then be sparse, but allow for all families to be be uniquely indexed... It's a nasty approach though.

**Comment by postwait** [comment]
Actually fudging the ifindex isn't useful.  That test does a check by name as well.  There are certainly two lo0's on my box... and they definitely have different MTUs.  So, back to square one... almost need to simply annotate that the test assumptions aren't valid on Illumos/Solaris.

**Comment by postwait** [comment]
Not so good at this Gerritt thing... super different workflow 👎

**Comment by bradfitz** [comment]
It grows on you. I can't do a Github code review these days.

**Comment by postwait** [comment]
The latest change proposed skips the test as invalid on Solaris.
