### ISSUE TITLE
net/http/httputil: DumpRequest doesn't dump Content-Length field in the header

### ISSUE THREAD

**Issue by better0332** [golang/go#7215]
<pre>see <a href="http://play.golang.org/p/8UNjmEa6AP">http://play.golang.org/p/8UNjmEa6AP</a></pre>

**Comment by odeke-em** [comment]
What is the status on this issue?  Has it been accepted that we should improve `DumpRequestOut` or should `DumpRequest` be fixed?
I ask because I've worked offline on a CL https://go-review.googlesource.com/21790 to get this behavior in for `DumpRequest` it but I have no trouble scrapping or updating it (it was just a warm up CL).
