### ISSUE TITLE
cmd/compile: top-level var does not respect , rule

### ISSUE THREAD

**Issue by adonovan** [golang/go#7320]
<pre>The following program fails with gc but succeeds with 'ssadump -run', because gc is
computing the initialization order incorrectly.

---------------

package main

// The package-level var initialization dependency graph contains the           
// following edges:                                                             
//      order     -&gt; makeOrder                                                  
//      makeOrder -&gt; b                                                          
//      makeOrder -&gt; a                                                          
// Since a and b are incomparable in this partial order, we initialize          
// them in lexical order, a before b.  The total order of                       
// initialization is thus: [a, b, order].                                       
//                                                                              
// ssadump -run succeeds but go run fails.                                      
//                                                                              
// Interestingly, reversing the order of {b, a} in makeOrder (and {1,           
// 0} in the assertion) causes it to succeed with both tools, meaning           
// that gc uses the lexical order of the references within makeOrder,           
// not the lexical order of the declarations of a and b, to resolve             
// incomparability.                                                             

var counter int

func next() int {
        c := counter
        counter++
        return c
}

func makeOrder() [2]int {
        return [2]int{b, a}
}

var order = makeOrder()

func main() {
        if order != [2]int{1, 0} {
                panic(order) // gc panics (got {0, 1})                          
        }
}

var a, b = next(), next() // 0, 1                                               

---------------

(Again I feel a vague sense of deja vu, but couldn't find a duplicate report.)</pre>

**Comment by odeke-em** [comment]
Thank you for the report, and for the patience @alandonovan, and thank you for the discussion and attention @rsc and @griesemer!

I have just investigated this issue and good news:
 @alandonovan your repro in https://github.com/golang/go/issues/7320#issue-51286527 now works, @rsc your repro in https://github.com/golang/go/issues/7320#issuecomment-66091337 also works. @rsc however the repro in https://github.com/golang/go/issues/7320#issuecomment-66091335 seems faulty to me as it doesn't seem to respect the left to right initialization order from the spec, but you corrected that in your follow-up in https://github.com/golang/go/issues/7320#issuecomment-66091337 :)

This bug was fixed for Go1.13 by @mdempsky's CL [170062](https://go-review.googlesource.com/c/go/+/170062) after an identical bug https://github.com/golang/go/issues/22326 was filed calling out a mismatch with the spec's expectations in an example.

I am going to close this bug as it is now fixed. Thank you all!
