### ISSUE TITLE
runtime/cgo: implement for Solaris

### ISSUE THREAD

**Issue by 4ad** [golang/go#7466]
<pre>Implement cgo for Solaris, most of the bits are there, just enable them.</pre>

**Comment by trondn** [comment]
@minux From the comment above it seems like you've been working on this? what's the status here?

**Comment by minux** [comment]
I didn't do it, but there is an implementation of cgo on solaris/amd64
in https://github.com/wesolows/golang, it's based on the the old dev.cc
branch and hasn't been updated for some time, but last time I heard,
the cgo support is done. The remaining work is to merge it with the
upstream master branch and propose CLs.

**Comment by gdamore** [comment]
We really really want this please!

**Comment by minux** [comment]
The CLs are in review now. cgo support for solaris will be in Go 1.5.

**Comment by gdamore** [comment]
Excellent.  I probably should start contributing to go on Solaris -- I need to add support for a few sys calls that are absent  (e.g. getpeerucred().)

**Comment by minux** [comment]
FYI, the syscall package is locked down. Please contribute to the x/sys
subrepo instead.

https://godoc.org/golang.org/x/sys/unix

**Comment by gdamore** [comment]
Got it.

**Comment by binarycrusader** [comment]
Since this is now integrated following these commits:

https://github.com/golang/go/commit/2b90c3e8edf36c0a76545fa13c195bca68a29420
https://github.com/golang/go/commit/2d18ab75e6f828811ff205b4bf968809e2d8fdb2
https://github.com/golang/go/commit/2230e9d24bc4a6241e2eb2603ebc151e1167a5bb
https://github.com/golang/go/commit/649c7b6daca6e29a719c9d29c65148a4628e729f
https://github.com/golang/go/commit/121489cbfd082161d86dd5e6f5653dc654beeaf7

...can this bug be closed?

**Comment by mikioh** [comment]
Closing, as per https://github.com/golang/go/blob/master/doc/go1.5.html#L259.
