### ISSUE TITLE
cmd/link: valgrind compatible output

### ISSUE THREAD

**Issue by alberts** [golang/go#782]
<pre>RFE:

As discussed here:

<a href="http://groups.google.com/group/golang-">http://groups.google.com/group/golang-</a>
nuts/browse_thread/thread/c7d548974abdda92

it would be very useful if 6g could be modified to produce binaries that can 
be run with Valgrind.</pre>

**Comment by kodabb** [comment]
Right now (go 1.4) valgrind reports

```
bad executable (__PAGEZERO is not 4 GB)
valgrind: ./program: cannot execute binary file
```

**Comment by thefallentree** [comment]
any progress on this? use valgrind for CGo libs will be a big plus

**Comment by minux** [comment]
It seems the valgrind developer probably have fixed the issue on their side.

I tried to run reflect.test under valgrind --tool=none (version 3.11.0),
and the test passes.
various other tests are also passing, including the main cgo test
($GOROOT/misc/cgo/test).

That said, Memcheck still reports a lot of warning for the simplest go code
($GOROOT/test/helloworld.go), and I don't think we can fix those because
valgrind seems to make some C ABI assumptions that are invalid in Go ABI
and don't understand Go's moving stack.
https://gist.github.com/minux/957dbc35a48be75588cb0f386cda6a60

Perhaps we should close this issue instead, I think Memcheck is never going
to work and Nulgrind already runs all the Go programs that I tried. Any
objections?

**Comment by thefallentree** [comment]
Is there a way to have memcheck ignore Go code part ? after all, like
previous message suggest, we only want it to check linked C-libraries.

**Comment by rsc** [comment]
I don't know. It would be better to bring this up with the memcheck authors. If you find out something simple that can be done, great.

Note that Go does work with https://github.com/google/sanitizers/wiki/MemorySanitizer and https://github.com/google/sanitizers/wiki/AddressSanitizer.
