### ISSUE TITLE
runtime: GC: Clarify what behavior or side effects are guaranteed or not

### ISSUE THREAD

**Issue by didenko** [golang/go#7868]
<pre>The current documentation at <a href="http://golang.org/pkg/runtime/#GC">http://golang.org/pkg/runtime/#GC</a> describes: GC runs a
garbage collection.

Although a correct description, a first-time reader may benefit from more details,
something like this:

GC runs a garbage collection. Mark and sweep (GC pause) complete before the call
returns. Operating system reclaims the freed memory at it's own pace. Do not expect to
have the memory return to the OS immediately.</pre>

**Comment by ysmolsky** [comment]
Current documentation for the function states: 

> GC runs a garbage collection and blocks the caller until the garbage collection is complete. It may also block the entire program.

@didenko, It looks to me that staying away from false promises in documentation is the right approach. Some facts from 4 years ago are not valid anymore. So it is good that we have not added any promises there. Also the general documentation for the runtime package have improved a lot since that time: https://golang.org/pkg/runtime/ 

Do you think that we can close this issue?

**Comment by didenko** [comment]
@ysmolsky I do not see a reason to keep the ticket open now. As a bit of feedback: it would be great to avoid judgemental (and so confrontational) statements like "false promises". No one in this issue intended to introduce misleading documentation - neither at that point in time nor as a promise.

**Comment by ysmolsky** [comment]
I am sorry that it sounded that way. What I meant: it is good that we have not added more documentation there because some things that were true 4 years ago are not true anymore. Thanks for the feedback and response.

**Comment by ianlancetaylor** [comment]
@didenko Thanks for pointing out that "false promises" sounds judgemental and confrontational.  I would say that in English it is not confrontational; it means something like "a good intention that turned out to be a mistake."  Personally I'll try to be aware in the future of how it sounds to others.
