### ISSUE TITLE
x/tools/go/types:  Move field Recv from Signature to Func

### ISSUE THREAD

**Issue by gordonklaus** [golang/go#8187]
<pre>The Recv field is misplaced.  A function type (types.Signature) cannot have a receiver;
only a function object (types.Func) can.</pre>

**Comment by griesemer** [comment]
I have tried this a couple of times, only to run into problems when doing the respective source change. If I recall correctly, in some places we only have (or return) the function type and need access to the receiver, but wouldn't have it anymore if the receiver were moved to the function object; and we cannot easily change that w/o changing a lot of unrelated code as well. Perhaps this can be tried in a version 2...

Independently though, the time for API changes has passed and we cannot change this even if it were easily possibly due to the backward API guarantee we have for the std libs to which go/types now belongs.
