### ISSUE TITLE
cmd/go: go build fails on directory with only test files (behavior change from 1.2)

### ISSUE THREAD

**Issue by pmezard** [golang/go#8279]
<pre>What does 'go version' print?

go version go1.3 windows/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

In a working Go environment:

  $ mkdir src/somedir/dummy
  $ echo &quot;package dummy&quot; &gt; src/somedir/dummy/dummy_test.go
  $ go build somedir/...
  go build somedir/dummy: no buildable Go source files in /path/to/somedir/dummy
  $ echo $?
  1

There are other valid packages under somedir/

What should have happened instead?

In go 1.2, the build was successful. A simple workaround is to add a dummy non-test file
in the package.

Since it broke our build and I cannot see it mentioned in the release notes I wondered
if the change was intentional. And if so, I was curious to know why.</pre>

**Comment by rsc** [comment]
This is difficult to support nicely, because it's hard to 
distinguish "no Go source files" from "no Go source files
due to build tags excluding them all", and you do want
to behave differently in those cases. 
But then a directory with just a "// +build ignore" file
is kind of a mix of both.

Since we've been living with this since 1.3, I think it is
fine to keep living with.
