### ISSUE TITLE
x/build/builders: build race runtime on all supported OSes

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8653]
Currently when I need to rebuild race runtime (syso files) I need to find a linux,
windows, darwin and freebsd machine; ssh into them and do some manual
actions. This is painful, non-reproducible and only I know how to do
it. If we have linux/windows/darwin/freebsd VMs on GCE, we could automate the process of
building the race runtime. Basically you give it revision number, and it gives you 4
race_goos.syso files.
Brad says it's totally possible.

**Comment by dvyukov** [comment]
For the record, here is sequence of commands I used to build race runtime for freebsd. It did not work fully, but I just want to store it somewhere so it can be used as a starting point later.

```
gomote create -timeout=3h0m0s freebsd-amd64-race
gomote run freebsd-amd64-race /usr/sbin/pkg install -y gcc-4.8.4
gomote run freebsd-amd64-race /usr/local/bin/g++48 -v
gomote run freebsd-amd64-race /usr/sbin/pkg install -y subversion
gomote run freebsd-amd64-race /usr/local/bin/svn checkout -r 229396 http://llvm.org/svn/llvm-project/compiler-rt/trunk/lib tsan
gomote run -e CC=/usr/local/bin/gcc48 freebsd-amd64-race tsan/tsan/go/buildgo.sh
gomote put14 freebsd-amd64-race
gomote run freebsd-amd64-race /usr/local/bin/git clone https://go.googlesource.com/go
gomote run -e CC=/usr/local/bin/gcc48 freebsd-amd64-race go/src/make.bash
gomote run freebsd-amd64-race go/bin/go version
gomote run freebsd-amd64-race /bin/cp tsan/tsan/go/race_freebsd_amd64.syso go/src/runtime/race
gomote run freebsd-amd64-race go/bin/go install -race -a -v std
gomote run freebsd-amd64-race go/bin/go test -race -short -cpu=2 std # this does not work because go is not in PATH
gomote gettar -dir=go/src/runtime/race freebsd-amd64-race > /tmp/tar
tar -zxf /tmp/tar # this copies whole dir
```

**Comment by cyphar** [comment]
Is there any possibility that we could build `compiler-rt` as part of the normal build process (even if it was optional)? The reason I ask is because we recently [hit a bug in openSUSE](https://bugzilla.suse.com/show_bug.cgi?id=1052528) where we were missing the `.syso`s (they weren't installed for some reason). While we can just copy them in our packages, openSUSE has a strict policy against shipping pre-compiled binaries (everything needs to be rebuilt) and as such we would need to recompile `compiler-rt` as part of our package.

That's not a _huge_ issue but there's also the fact that since you effectively vendor `compiler-rt` the commit messages for the updates don't actually mention the SVN revision that you use (making it guesswork to figure out the right version of the binaries).

Not to mention that if we just built from source, you would be able to support every platform. I'm not sure exactly what @bradfitz was referring to about it being difficult to cross-compile though.

**Comment by dvyukov** [comment]
This is fixed with https://go-review.googlesource.com/c/16823

You can extract the current build process from (which is basically running a single script):
https://github.com/golang/build/blob/master/cmd/racebuild/racebuild.go

**Comment by cyphar** [comment]
Ah okay. Though, you can't access the internet in an openSUSE build context :wink:. That's okay, I should be able to work around that (and maybe I'll send a patch to make `racebuild` work in offline mode).

**Comment by dvyukov** [comment]
@cyphar you don't want to take the whole program, just extract the (local) build steps. It does not just access internet, it creates GCE machines and requires permissions to do that.
