### ISSUE TITLE
x/net/context: flaky test TestAllocs

### ISSUE THREAD

**Issue by ribrdb** [golang/go#8709]
<pre>The context.TestAllocs test is flaky on our jenkins continuous build. It seems to fail
more often when the machine is heavily loaded.

=== RUN TestAllocs
--- FAIL: TestAllocs (0.11 seconds)
	context_test.go:349: WithTimeout(bg, 1*time.Nanosecond) allocs = 8.000000 want 7</pre>

**Comment by Sajmani** [comment]
ribrdb: is this still an issue?  Since this report, there have been changes to TestAllocs to use a longer timeout and changes to AllocsPerRun in the testing package.  Since I don't have a way to reproduce this, I cannot easily determine whether those changes have resolved this.  Please reopen if so, ideally with reproduction steps.
