### ISSUE TITLE
net/http: DetectContentType does not detect the mp4 mimetype

### ISSUE THREAD

**Issue by verokarhu** [golang/go#8773]
<pre>What does 'go version' print?
Go 1.3.1

What steps reproduce the problem?

1. Write mp4 data to ResponseWriter

What happened?
The Content-Type header is set to &quot;application/octet-stream&quot;

What should have happened instead?
The Content-Type header is set to &quot;video/mp4&quot;</pre>

**Comment by Francesco149** [comment]
any plans on implementing this yet? it would help a lot with stuff like file uploading tools that have to detect mime types.

**Comment by dsymonds** [comment]
Contributions welcome. I'm not planning to do it myself.

**Comment by dominikh** [comment]
@dsymonds Any chance to get some input, though? Your todo reads "Re-enable this when the spec is sorted w.r.t. MP4." – Do you, by any chance, remember what had to be sorted? Only the little-endian <-> big-endian issue? I realise this code is 4 years old, so it might be hard to remember.

Also: The current version of the spec only looks for "mp4", not all the other types (iso, M4V, ...) that the original code checks for. How closely should the spec be followed here?

In order to follow the current version of the spec, only a number, and which strings to consider valid, need to be changed.

**Comment by dsymonds** [comment]
I can't remember. I think at the time the spec didn't actually specify the MP4 string to match, but it looks like it does now. If you add a `sniff.go` entry for the MP4 string(s) that the spec specifies, that seems fine to me.

**Comment by odeke-em** [comment]
CL mailed to https://go-review.googlesource.com/#/c/16951/
