### ISSUE TITLE
cmd/compile: large literal causes stack overflow

### ISSUE THREAD

**Issue by jbardin** [golang/go#8819]
<pre>go1.3.2 and
go version devel +cd24f5ff3db8 Fri Sep 26 12:10:13 2014 -0400 darwin/amd64

The following code causes a stack-overflow

func func1() {
	a := [100000000]int64{1}
	a[1] = 1
}

What happened?

runtime: goroutine stack exceeds 1000000000-byte limit

What should have happened instead?

The compiler seems to check for a stack overflow with the message:
&quot;stack frame too large (&gt;2GB)&quot;, but the runtime aborts at 1GB. 

This stackframe comes in at 800000016, though at runtime still overflows.</pre>

**Comment by osocurioso** [comment]
The following does not panic:

func func1() {
    // var a [100000000]int64 // also ok
    a := [100000000]int64{}
    a[1] = 1
}

It seems the temporary on the right is only moved to the heap when it is zero-initialized.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by ALTree** [comment]
This is probably out of my reach, but I'll write a few notes for the posterity.

In both 
```go
a := [100000000]int64{}
```
and

```go
a := [100000000]int64{1}
```
the compiler correctly marks `a` as escaping and moves it to the heap. 

The problem is that the for the latter the compiler generates an `autotmp_0001` variabile to hold the array literal. `autotmp`s are generated by the `Tempname` function in `gen.go` and they're always marked as not escaping (`n.Esc = EscNever`). For this reason when the compiler computes the stack size of the function (`allocauto` function in `pgen.go`), looping over the function variables, `a` is skipped (because it's marked as escaping), while `autotmp_0001` is not. The compiler add the size of `autotmp_0001` (which is > 1 GB) to the total stack size, and then at runtime the program calls morestack and it panics because the stack is too big.

**Comment by ALTree** [comment]
This issue (at least in the current form) was fixed by https://go-review.googlesource.com/#/c/22192

**Comment by ianlancetaylor** [comment]
Thanks.
