### ISSUE TITLE
cmd/compile: off-by-many in line number reported for compile error

### ISSUE THREAD

**Issue by dominikh** [golang/go#8836]
<pre>What does 'go version' print?
go version go1.3.2 linux/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. Compile <a href="http://play.golang.org/p/V41ws9TExS">http://play.golang.org/p/V41ws9TExS</a>
2.
3.

What happened?
# _/tmp/foo
./foobar.go:12: cannot use 42 (type int) as type *C.int in argument to _Cfunc_foobar

What should have happened instead?
# _/tmp/foo
./foobar.go:15: cannot use 42 (type int) as type *C.int in argument to _Cfunc_foobar

Please provide any additional information below.
The error is always reported for line 12, even if more arguments are added to the
function. If the first argument of foobar is changed from int* to int, (and the call
adjusted appropriately), the error is instead reported for line 16, which is another
off-by-one error.</pre>

**Comment by rsc** [comment]
@dr2chase another

**Comment by dr2chase** [comment]
This looks intractable and annoying -- I think the root cause is our tendency to sometimes construct ASTs that aren't trees, so that when an argument to a function call is a shared node in the AST its line number is not trustworthy.  It is possible to get it right for numbers, but not for boolean constants true and false.

You can see the hackiness in setlineno around line 230 of subr.go; that uses the line number of a node to set the global lineno (a hack in itself if you ask me) but only when the node is not a ONAME, OTYPE, OPACK, or OLITERAL.
