### ISSUE TITLE
cmd/gc: escape analysis considers pointer assignments within objects as leaking.

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#9043]
<pre>The following go file:

package foo

type y struct {
	b *byte
}

func foo(z *y) {
	z.b = z.b
}

Gives the following -m output

/home/daniel/src/test/foo.go:7: can inline foo
/home/daniel/src/test/foo.go:7: leaking param: z

The place where this is hitting the hardest is the bytes.Buffer type. Because of
assignments within the object, if you create one on the stack, it will escape to the
heap if you call any method on it</pre>

**Comment by dvyukov** [comment]
bytes.Buffer escapes due to 2 things:

1. Assignment of the form b.buf = b.buf[n:m] as in:

func (b *Buffer) Truncate(n int) {
	...
	b.buf = b.buf[0 : b.off+n]
}

2. Assignments of the form b.buf = b.bootstrap[0:]
But it is worse than that, because it is:

buf := b.bootstrap[0:]
...
b.buf = buf

as in:

func (b *Buffer) grow(n int) int {
	var buf []byte
	...
	b.buf = b.bootstrap[0:]
	...
	b.buf = buf
}

I see how to fix 1. b.buf = b.buf[n:m] can be simply ignored by escape analysis, as it does not introduce any new flows.

b.buf = b.bootstrap[0:] can't be ignored, because it does introduce new flows.
Currently Bytes method:
func (b *Buffer) Bytes() []byte { return b.buf[b.off:] }
does not lead to b leakage.
If we ignore b.buf = b.bootstrap[0:] *and* Bytes does not lead to b leakage; then caller of Bytes will get dangling reference to b.bootstrap.

Moreover, the following code:

buf := b.bootstrap[0:]
...
b.buf = buf

requires substantially more complex flow analysis than we have now, and SSA analysis as we need to know that b refers to the same object in both statements.

**Comment by dr2chase** [comment]
Fixed, probably by 7fbb1b36c37ac49db78042adc7533fb4ab83a4bcn .
Retested example code, is now tagged as "leaking param content".
```
foo1.go:7: can inline foo
foo1.go:7: leaking param content: z
```
This is still overconservative (it could infer that rearranging fields of z is a leak no-op), but since z itself no longer leaks, I'm closing it.
