### ISSUE TITLE
net/http: TimeoutHandler header race on timeout

### ISSUE THREAD

**Issue by wongak** [golang/go#9162]
<pre>Hi, this might be related to 

<a href="https://golang.org/issue/8414">https://golang.org/issue/8414</a>
and
<a href="https://golang.org/issue/8209">https://golang.org/issue/8209</a>

What does 'go version' print?

$ ./go version
go version devel +59dbd878547f Tue Nov 25 08:42:00 2014 +0100 linux/amd64

What steps reproduce the problem?

A slight modification to the test:

diff -r 493ad916c3b1 src/net/http/serve_test.go
--- a/src/net/http/serve_test.go	Sun Nov 23 15:13:48 2014 -0500
+++ b/src/net/http/serve_test.go	Mon Nov 24 15:50:11 2014 +0100
@@ -1171,6 +1171,7 @@
 	sendHi := make(chan bool, 1)
 	writeErrors := make(chan error, 1)
 	sayHi := HandlerFunc(func(w ResponseWriter, r *Request) {
+		w.Header().Set(&quot;Content-Type&quot;, &quot;text/plain&quot;)
 		&lt;-sendHi
 		_, werr := w.Write([]byte(&quot;hi&quot;))
 		writeErrors &lt;- werr

modifying a header before timing out.

What happened?

$ go test -race

produces a race warning.

What should have happened instead?

No data race should occur.

Please provide any additional information below.

After digging a little bit, it seems like the way the cloning is set up prevents
handlers to be run in another goroutine other than the one created by http.Server.

WARNING: DATA RACE
Read by goroutine 20:
  net/http.(*response).Header()
      /home/user/gotip/src/net/http/server.go:609 +0x62
  net/http.(*timeoutWriter).Header()
      /home/user/gotip/src/net/http/server.go:1944 +0x5b
  net/http_test.func·073()
      /home/user/gotip/src/net/http/serve_test.go:1174 +0x4d
  net/http.HandlerFunc.ServeHTTP()
      /home/user/gotip/src/net/http/server.go:1265 +0x4e
  net/http.func·018()
      /home/user/gotip/src/net/http/server.go:1918 +0xfe

Previous write by goroutine 17:
  net/http.(*response).WriteHeader()
      /home/user/gotip/src/net/http/server.go:639 +0x17d
  net/http.(*timeoutHandler).ServeHTTP()
      /home/user/gotip/src/net/http/server.go:1928 +0x4c3
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /home/user/gotip/src/net/http/httptest/server.go:200 +0xf7
  net/http.serverHandler.ServeHTTP()
      /home/user/gotip/src/net/http/server.go:1703 +0x1f6
  net/http.(*conn).serve()
      /home/user/gotip/src/net/http/server.go:1204 +0x1087

Goroutine 20 (running) created at:
  net/http.(*timeoutHandler).ServeHTTP()
      /home/user/gotip/src/net/http/server.go:1920 +0x2ca
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /home/user/gotip/src/net/http/httptest/server.go:200 +0xf7
  net/http.serverHandler.ServeHTTP()
      /home/user/gotip/src/net/http/server.go:1703 +0x1f6
  net/http.(*conn).serve()
      /home/user/gotip/src/net/http/server.go:1204 +0x1087

Goroutine 17 (running) created at:
  net/http.(*Server).Serve()
      /home/user/gotip/src/net/http/server.go:1751 +0x3cd</pre>

**Comment by bradfitz** [comment]
A mutex doesn't help here. The problem is that the TimeoutHandler executes the handler in a separate goroutine, which may obtain the headers via `ResponseWriter.Header()` and the TimeoutHandler's main ServeHTTP, upon timeout, may also access `ResponseWriter.Header()`.  Even with a mutex there guarding the acquisition of the map, they both may subsequently race on accessing the header, for which there's no place to put a mutex.

I think the solution is to change the design of the Timeout Handler to instead Hijack the connection if possible and write the timeout response headers & body by hand, if possible.  There are still problems with that, though: requires the ResponseWriter to be a Hijacker, and assumes HTTP/1.n  (but this isn't the first such problem), and prevents wrapper Handlers from intercepting the error and writing a prettier failure HTML body.

So I think I'll change things to avoid this in the common case but I think the bigger problem is that TimeoutHandler isn't compatible with the ResponseWriter & Header design.  We probably should've propagated a Context type (like https://godoc.org/golang.org/x/net/context#Context) through ServeHTTP instead, to which we could attach deadlines and do cancelation. Alas.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by ianlancetaylor** [comment]
Ping @bradfitz .  Is anything here going to happen for 1.6?

**Comment by extemporalgenome** [comment]
Can timeoutWriter store a separate "inner" header map specifically for use by the wrapped Handler? When WriteHeader (or the first Write) occurs, if timedOut is false, the inner map can be key-wise copied (with mutex protection) into the original ResponseWriter's map. In any case, the two maps remain isolated.

Some special handling would need to occur for trailers to function properly.
