### ISSUE TITLE
os/exec: broken pipe writing into djpeg 

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9173]
<pre>Go's os/exec seems to have a problem piping into the djpeg program.

To reproduce, at least on Linux:

1) $ apt-get install libjpeg-turbo-progs
2) Download the attached image (7.8 MB, which seems to matter, or its JPEG structure
matters)
3) Run boat.go: <a href="http://play.golang.org/p/cHra0dvPr6">http://play.golang.org/p/cHra0dvPr6</a>

ante:tmp $ go run boat.go
2014/11/26 14:26:46 Process state: exit status 0 (success = true)
2014/11/26 14:26:46 Stdout: 11943953 bytes
2014/11/26 14:26:46 Stderr: &quot;&quot;
2014/11/26 14:26:46 cmd.Wait = write |1: broken pipe

Of note:

The djpeg process ends successfully, and outputs its resultant image to stdout.

But djpeg seems to end before reading all of its input, causing a SIGPIPE to the
goroutine trying to write all the data to it. strace says:

21770 &lt;... write resumed&gt; )             = 4096
21772 read(5,  &lt;unfinished ...&gt;
21770 write(1,
&quot;2\10\0002\10\0007\t\0007\t\0008\t\0007\10\0009\n\0008\7\0008\7\0&lt;\t\0=\n\0&gt;\v\0@\f\0?\v\0E\r\0F\16\0J\16\0M\16\0T\22\0Z\24\0]\24\0]\23\0^
\23\0f\30\0o\36\0n\32\0{$\0\205)\0\2212\0\236&lt;\0\2369\0\2405\0\2423\0\254:\0\272C\0\317W\0\351m\0\342g\0\344h\0\336e\0\334d\0\356w\0\363}\0\377\207\0\377
\213\0\377\220\0\377\221\0\377\222\0\377\221\0\377\224\0\377\224\0\377\220\0\377\217\0\377\223\0\377\227\0\377\234\0\377\244\0\377\264\0\377\276\0\377\30
5\0\377\311\0\377\312\0\377\301\0\377\266\0\377\243\0\377\226\0\377\201&quot;..., 4096
&lt;unfinished ...&gt;
21772 &lt;... read resumed&gt;
&quot;\4\v\2\5\v\2\5\v\2\5\v\2\5\n\1\4\n\1\4\v\0\4\v\0\4\f\1\5\r\2\6\17\5\6\21\5\7\21\5\7\23\4\7\22\3\10\22\3\10\22\3\10\21\2\7\21\2\
7\21\2\7\17\3\7\20\4\10\17\5\6\20\6\7\20\6\7\20\6\7\20\6\7\20\6\7\22\6\6\22\6\6\24\6\6\24\6\6\22\6\6\23\7\7\21\5\7\20\4\6\17\3\5\17\3\5\r\3\4\f\2\3\r\3\4
\f\2\3\v\2\3\n\1\2\n\1\2\n\1\2\v\2\3\f\3\4\f\3\4\r\4\5\17\5\6\20\6\7\22\6\6\24\6\6\25\7\6\31\7\7\33\10\4\37\7\5!\10\3#\7\3&amp;\t\3'\10\3*\t\4-\n\6,\t\5*\t\4
'&quot;..., 4840960) = 4096
21770 &lt;... write resumed&gt; )             = 4096
21768 &lt;... select resumed&gt; )            = 0 (Timeout)
21770 write(1, &quot;\7\3\32\7\3\31\7\3\31\7\3\27\10\5\27\10\5&quot;, 17 &lt;unfinished
...&gt;
21772 read(5,  &lt;unfinished ...&gt;
21770 &lt;... write resumed&gt; )             = 17
21772 &lt;... read resumed&gt;
&quot;2\10\0002\10\0007\t\0007\t\0008\t\0007\10\0009\n\0008\7\0008\7\0&lt;\t\0=\n\0&gt;\v\0@\f\0?\v\0E\r\0F\16\0J\16\0M\16\0T\22\0Z\24\0]\2
4\0]\23\0^\23\0f\30\0o\36\0n\32\0{$\0\205)\0\2212\0\236&lt;\0\2369\0\2405\0\2423\0\254:\0\272C\0\317W\0\351m\0\342g\0\344h\0\336e\0\334d\0\356w\0\363}\0\377
\207\0\377\213\0\377\220\0\377\221\0\377\222\0\377\221\0\377\224\0\377\224\0\377\220\0\377\217\0\377\223\0\377\227\0\377\234\0\377\244\0\377\264\0\377\27
6\0\377\305\0\377\311\0\377\312\0\377\301\0\377\266\0\377\243\0\377\226\0\377\201&quot;...,
4836864) = 4113
21770 exit_group(0)                     = ?
21772 read(5,  &lt;unfinished ...&gt;
21768 select(0, NULL, NULL, NULL, {0, 20} &lt;unfinished ...&gt;
21772 &lt;... read resumed&gt; &quot;&quot;, 4832751)   = 0
21771 &lt;... write resumed&gt; )             = 16384
21772 --- SIGCHLD (Child exited) @ 0 (0) ---
21771 --- SIGPIPE (Broken pipe) @ 0 (0) ---
21772 rt_sigreturn(0x11 &lt;unfinished ...&gt;
21771 rt_sigreturn(0xd &lt;unfinished ...&gt;
21772 &lt;... rt_sigreturn resumed&gt; )      = 0
21771 &lt;... rt_sigreturn resumed&gt; )      = 16384
21769 &lt;... read resumed&gt; &quot;&quot;, 512)       = 0
21772 futex(0xc208020b58, FUTEX_WAIT, 0, NULL &lt;unfinished ...&gt;
21771 write(4,
&quot;\320\272\232\376k\3375]\303\23\222s\232\350-\265\375B\35&gt;8e-*\216\273\2115\340Q\251\316\365=\372\270w\rN\206\312\366K\233r\321)R\6p\5G|\3
42\342\300\227\373\303\257=k*\362J\3461\2475Qhqo\2435\345\336-\321\244'?*\212\307}\&quot;t\274uTl\251
\203\317\326\276S\33\213\214*8\263\356\362\374\33\2355;\
31\222Gq\25\323\0\33\203\3152k\233\270\234lc\327\247\255c\32\221\234N\207Ft\246\333?\377\325\374\264\203R\270\23\3(\301\34\327Og\251\31\\n\373\247\257\32
6\277\25\305PR\367\217\333\360\265\332vf\270\322WUF).$\7\345^\231\253\326\336\27\271\213L/\&quot;&quot;...,
16384 &lt;unfinished ...&gt;
21769 futex(0xc208020458, FUTEX_WAIT, 0, NULL &lt;unfinished ...&gt;
21771 &lt;... write resumed&gt; )             = -1 EPIPE (Broken pipe)
21768 &lt;... select resumed&gt; )            = 0 (Timeout)
21771 --- SIGPIPE (Broken pipe) @ 0 (0) ---
21768 futex(0x593ac0, FUTEX_WAIT, 0, {60, 0} &lt;unfinished ...&gt;
21771 rt_sigreturn(0xd &lt;unfinished ...&gt;
21767 &lt;... wait4 resumed&gt; [{WIFEXITED(s) &amp;&amp; WEXITSTATUS(s) == 0}], 0,
{ru_utime={0, 496000}, ru_stime={0, 36000}, ...}) = 21770
21771 &lt;... rt_sigreturn resumed&gt; )      = -1 EPIPE (Broken pipe)

... note you can see the djpeg exit_group(0), then the SIGPIPE and the wait4 call return.

We can work around this in Go by knowing that this program does this and ignoring the
return value from cmd.Run() or cmd.Wait() and only looking at the
cmd.ProcessState.Success. But is that best?

Or are we doing something wrong?

Should Go ignore the Stdin copy error if the program ended successfully?

Camlistore bug: <a href="http://camlistore.org/issue/550">http://camlistore.org/issue/550</a>
Upstream djpeg bug from Mathieu: <a href="http://sourceforge.net/p/libjpeg-turbo/bugs/80/">http://sourceforge.net/p/libjpeg-turbo/bugs/80/</a></pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/9173/0/PA190470.JPG">PA190470.JPG</a> (7781878 bytes)

**Comment by bradfitz** [comment]
@ianlancetaylor, any wisdom here?

**Comment by ianlancetaylor** [comment]
Don't be misled by the SIGPIPE in the strace output.  Nothing is happening because of that signal.  It is caught and ignored.

In the os/exec package, the io.Copy call in Cmd.stdin is returning an EPIPE error.  That is the error being reported by the call to the Wait method.  The name of the write side of the pipe is "|1" (from os.Pipe).  The error is an os.PathError generated by os.File.Write, called by io.Copy.

I think that your suggestion of ignoring an EPIPE error in os/exec.stdin is reasonable.  Cmd.Wait will already only return that error if the program exited successfully.  In that scenario, returning EPIPE conveys little useful information.

Or, we could document the behaviour.

Most C programs in this situation will receive the SIGPIPE signal, fail to handle it, and exit.  In a shell pipeline, nothing much will happen, because the shell will use the exit status of the final process in the pipeline.

If you do this, using bash:

set -o pipefail
cat boat.jpg | /usr/bin/djpeg > /dev/null
echo $?

you will see that the cat program died due to a SIGPIPE signal.

If you do this:

trap "" PIPE
cat boat.jpg | /usr/bin/djpeg > /dev/null

then the cat program will not get a SIGPIPE signal, but will instead fail because write returned EPIPE.

cat: write error: Broken pipe

Anyhow, the only real question is whether we should return the EPIPE error from os/exec, or just drop it.  Personally I think it would be fine to drop it.  That is the natural implementation of the default behaviour of shell pipelines.

**Comment by bradfitz** [comment]
Excellent, thanks. I'd prefer to drop the error then. I'd prefer people go out of their way to get the failure for the weird case.
