### ISSUE TITLE
encoding/xml: newlines in char data should not be escaped

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#9204]
<pre><a href="http://play.golang.org/p/KeJh6ASgx0">http://play.golang.org/p/KeJh6ASgx0</a>

This actually has real-world issues, as some clients
(e.g. Chrome's SVG renderer) do not treat the &amp;#xA;
escape as white space and fail as a result.

Solving this would make for smaller output too.</pre>

**Comment by xogeny** [comment]
I recently ran across this issue as well.  Am I correct that this won't be fixed until 1.5?  Any suggested workarounds?

**Comment by roblillack** [comment]
@xogeny, it's not a real plug-in replacement, but for my use case (modifying specific text content in otherwise untouched XML files) I just wrote a pretty dump, quick-and-dirty XML tokenizer from scratch. There's no namespace handling or even parsing of attributes but it works for me: https://github.com/roblillack/gockl

**Comment by nightlyone** [comment]
@rogpeppe didn't you just fix that yestday with https://golang.org/cl/9310 merged as https://github.com/golang/go/commit/4a3e000a48fdfe4cbcfe8970db9c1ebec9c4b89d?

**Comment by minux** [comment]
It's fixed by https://golang.org/cl/9310.
