### ISSUE TITLE
x/review/git-codereview: add 'patch' subcommand

### ISSUE THREAD

**Issue by adg** [golang/go#9255]
Like the old 'hg clpatch'.

**Comment by cmarcelo** [comment]
Taking into account @rsc comments from previous CL, I've mailed https://go-review.googlesource.com/#/c/20101

Opted for detached checkout instead of creating branches to avoid the problem of having a special branches that we could decide to handle differently in every command: "what sync means in cl.1401.2", "if I change cl.1401, will the new sync lose my changes due to a newer version online?", and so on.

For the case of trying a CL which seems the common case, detached seems enough; the user can always create a new branch on top of that.
