### ISSUE TITLE
runtime: lots of time spent in sweepone

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9265]
Here is repro program:
http://play.golang.org/p/giKY6IcWjU

If you run it as-is, it runs for 1.357s and profile looks as:
 21.94%  test  test               [.] runtime.memclr
 12.24%  test  test               [.] runtime.MSpanList_IsEmpty
 11.02%  test  test               [.] runtime.xchg
  7.94%  test  test               [.] MHeap_AllocLocked
  5.19%  test  test               [.] runtime.MSpan_Sweep

If you uncomment "y = make([]byte, 1<<30)" line, it runs for 26.696s and profile looks as:
 37.52%  test  test               [.] runtime.sweepone
 27.15%  test  test               [.] runtime.xadd
 24.96%  test  test               [.] markroot
  1.96%  test  test               [.] runtime.memclr
  0.75%  test  test               [.] runtime.xchg

The problem is that the program creates 131221 spans when the live set is 1GB and the heap grows to 2GB. Later the live set drops to 1MB and GCs become very frequent, but each GC has to iterate over all of 131221 spans in sweepone and markroot. The total time spent in span handling becomes 90%.

This was reported on golang-nuts:
https://groups.google.com/forum/#!topic/golang-nuts/-Dq4WkivD2E

We need to either (1) re-partition allspans so that we don't iterate over the dead part, or (2) remove and deallocate dead spans from allspans after some time of inactivity.

**Comment by DanielMorsing** [comment]
I can't reproduce this after https://go-review.googlesource.com/2349 was applied.

However, I think we're seeing this issue in production on one of the services at my job. I'll report back after I've grabbed some data.

**Comment by aclements** [comment]
I just tried @dvyukov's test program on latest master and it runs in 1.3s and has the same profile with and without the "y = ..." line.

@DanielMorsing, are you still seeing this issue?

**Comment by DanielMorsing** [comment]
No, the issue in production turned out to be a case of some spurious allocations being made by application code.

I still think we're doing excessive sweeping, but it runs concurrently with mutator code, so the effects aren't as apparent. Should be easier to figure out what's happening after https://go-review.googlesource.com/#/c/9506/ was applied.

**Comment by dvyukov** [comment]
@aclements I guess you now need a different program to trigger this issue. Probably now GC collects the large span before the program allocates sufficient amount of small spans.

**Comment by rsc** [comment]
No repro program, so no issue.

**Comment by dvyukov** [comment]
Such approach to bug handling is kind of discouraging.
Catch a new repro program:
```go
package main

import (
	"fmt"
	"os"
	"runtime"
	"time"
)

var z []byte
var x [][]byte

func main() {
	t0 := time.Now()
	if len(os.Args) > 1 {
		for i := 0; i < 1<<20; i++ {
			x = append(x, make([]byte, 1<<13))
		}
		x = nil
		runtime.GC()
	}
	fmt.Println(time.Since(t0))
	t0 = time.Now()
	for i := 0; i < 1e5; i++ {
		z = make([]byte, 1<<13)
	}
	fmt.Println(time.Since(t0))
}
```
```
$ ./test
2.245µs
582.776723ms

$ ./test 1
3.470712076s
19.764293403s
```

That's 34x slowdown.

**Comment by rsc** [comment]
This didn't happen in time.

**Comment by adg** [comment]
Missed again.

**Comment by aclements** [comment]
Just to expand on the original report a bit, when the heap is full of dead spans like in this test case, half of the time in sweepone is spent just incrementing the sweepidx and the other half is spent in cache misses just to check the span state (and determine that it's dead). This particular test amplifies this because it drives so many GC cycles in the second phase and, since the number of spans never goes down from the peak, between the closely spaced GC cycles in the second phase, sweeping has to sweep all of the dead spans.

This isn't going to happen for 1.7, but my hope for 1.8 is that we can eliminate proportional sweeping entirely, which will fix this problem at its root.

**Comment by quentinmit** [comment]
ping @aclements, is this still going to make 1.8?
