### ISSUE TITLE
x/crypto/openpgp: PromptFunction infinite loop

### ISSUE THREAD

**Issue by AndrewVos** [golang/go#9315]
ReadMessage PromptFunction is called forever.

If PromptFunction returns the correct key the first time, then decryption succeeds. If, however, you return the correct key any time after the first time then decryption will never succeed and PromptFunction gets called forever.

**Comment by marete** [comment]
I am happy to tackle this if no one else is working on it. You may assign it to me.

**Comment by mikioh** [comment]
@marete, feel free to send a cl (changelist); http://golang.org/doc/contribute.html

**Comment by marete** [comment]
AndeweVos: Please download and test this CL, which should fix the problem: https://go-review.googlesource.com/2570

**Comment by odeke-em** [comment]
@marete and @bradfitz, I think @agl fixed this issue with https://go-review.googlesource.com/#/c/14038 but since in the commit message of that CL the magic word `Fixes golang/go#9315` wasn't used but instead used `Fixes #9315` yet openpgp project belongs under `golang/x/crypto`, this issue was not auto-closed nor referenced here. This also means that CL https://go-review.googlesource.com/2570 may not be needed either.
Please get the latest @AndrewVos and verify.

**Comment by odeke-em** [comment]
Ping!
