### ISSUE TITLE
mobile/audio: OpenAL bindings

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9328]
OpenAL is a common subset of both the audio systems on Android and iOS, so it serves as a good place to get audio support for all-Go mobile apps.

We should start with a very thin cgo wrapper, in the style of the gl package. Probably called golang.org/x/mobile/audio.

As the API is significantly smaller than OpenGL, it may be possible to build one canonical, pleasant Go library on top of it. In which case we may want to have the cgo library in x/mobile/audio/al and keep x/mobile/audio for the user-friendly library. But it is still an open question if one nice Go library is possible.

**Comment by rakyll** [comment]
I was able to talk to a lawyer. If we use cgo to build OpenAL and statically link it to the bindings package, the package has to be licensed with GPL.

So, we will require libopensl to be linked dynamically and will not be building it from the source.

We should add libopenal as a part of the new toolchain, distribute the so or make the user to build it on their own. It is not going to be as easy as go-getting, but we don't seem to have any other options.

Mailed https://go-review.googlesource.com/#/c/3115/.

**Comment by rakyll** [comment]
I've been trying to get the audio done on Android, and this is so far I've discovered:

1. We cant statically link libopenal.a as we discussed earlier, because it requires multiple definitions of JNI_Onload to exist due to OpenAL's android.c [1].

2. We need to dynamically link libopenal.so while building an apk and load it dynamically on app/android.c's JNI_OnLoad on the app startup. I don't understand the Go's execution modes well and not quite sure we can output an app shared object that has an external dynamic library dependency.

3. Android linker has limitations about where an external library could exist on the disk. So, we need to pack libopenal.a/so into the stripped Android NDK archive that is downloaded on gomobile init and copy the library to certain places before building.

My current strategy is to do a System.loadLibrary("openal"); on Go.java and add libopenal.so to the final apk. I couldn't make it work yet and not sure it can ever work. I need to read more about Go shared libraries.

[1] https://github.com/rakyll/al/blob/master/android.c (for reference)

**Comment by crawshaw** [comment]
Ideally any System.loadLibrary call would be done from android.c in JNI_OnLoad or one of the initialization functions, so it is compatible with NativeActivity.

And while I cannot recommend it, there is always dlsym(3)

**Comment by rakyll** [comment]
From the native context, there is not an equivalent of System.loadLibrary, dvmLoadNativeCode could be a candidate. I've decided to go with dlopen/dlsym. One drawback is that you have to load all of the dependencies before invoking application's ANativeActivity_onCreate.

Our current model doesn't allow this scenario. We may need to have a libbootstrap.so that will dynamically load the dependencies and then the lib<app>.so and invoke its ANativeActivity_onCreate.

**Comment by crawshaw** [comment]
Why can't the C code in the openal package call System.loadLibrary, and provide function pointers that are filled in by dlsym?

Something like a lazily called init function in the al package with:

jclass system_clazz = find_class(env, "System");
jmethodID loadlibrary = find_method(env, system_clazz, "loadLibrary", "(Ljava/lang/String;)");
...
(*env)->CallVoidMethod(env, ..., loadlibrary, lib_name_jstring);

Some recent code along similar lines:

https://github.com/golang/mobile/blob/master/app/android.c#L80

**Comment by rakyll** [comment]
We don't know about the current vm until app/ANativeActivity_onCreate is invoked, but the symbols should have been loaded before it's invoked.

I'm thinking about stripping the android.c from the OpenAL build and go for static linking. It's a more attainable approach for this case, but we need to find a long-term solution for those who are willing to load libs dynamically.

**Comment by crawshaw** [comment]
The Go runtime is not started until after ANativeActivity_onCreate is called. No code in the OpenAL package can execute before it is called.

package al

/*
#include <jni.h>
...

void al_init(void* vm) {
    // System.loadLibrary
    // dlsym
}
*/
import "C"
import "golang.org/x/mobile/app"

func init() {
    vm := app.State.(interface{
        JavaVM() unsafe.Pointer
    }).JavaVM()
    C.al_init(vm)
}

**Comment by rakyll** [comment]
It doesn't matter. We link, let's say, libbasic.so with an libopenal.so dependency with symbols from OpenAL. It will complain if one of the needed shared libraries is not already loaded while libbasic is being loaded.

```
$ gobjdump -x libbasic.so

libbasic.so:     file format elf32-littlearm
libbasic.so
architecture: armv5te, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000

Dynamic Section:
  PLTGOT               0x00278c58
  PLTRELSZ             0x00000738
  JMPREL               0x00078a10
  PLTREL               0x00000011
  REL                  0x00006158
  RELSZ                0x000728b8
  RELENT               0x00000008
  RELCOUNT             0x0000e515
  SYMTAB               0x00000128
  SYMENT               0x00000010
  STRTAB               0x00002138
  STRSZ                0x000033f8
  HASH                 0x00005530
  NEEDED               liblog.so
  NEEDED               libandroid.so
  NEEDED               libEGL.so
  NEEDED               libGLESv2.so
  NEEDED               libopenal.so
  NEEDED               libm.so
  NEEDED               libc.so
  NEEDED               libdl.so
  FINI_ARRAY           0x00278a74
  FINI_ARRAYSZ         0x00000008
  INIT_ARRAY           0x00278a7c
  INIT_ARRAYSZ         0x00000004
  TEXTREL              0x00000000
  SYMBOLIC             0x00000000
  FLAGS                0x0000000e
  FLAGS_1              0x00000001
```

So we have two options:
- Extend NativeActivity and System.loadLibrary libopenal and libbasic in this particular order.
- Export a bootstrapper library that loads libopenal first, then libbasic and invokes it's entry point.

**Comment by rakyll** [comment]
A third option is to dlopen, dlsym and invoke each call dynamically, which is horrific and doesn't deserve being mentioned :-) That's the only way to lazily load libopenal in our case.

**Comment by crawshaw** [comment]
When I originally suggested dlsym I was imagining the case so horrific it doesn't deserve to be mentioned. I'd be happy to consider alternatives if you have one.

**Comment by rakyll** [comment]
The seond alternative I've mentioned above is to have a loader library that basically does the following:

```
The alternative is to build an entry point library that will do the loading and invoke application's entry point.

In this loader library,

void ANativeActivity_onCreate(ANativeActivity* native_activity, void* savedState, size_t savedStateSize) {
    // TODO: Handle errors.
    dlopen("libopenal.so", ...);
    void (*on_create)(ANativeActivity*, void*, size_t) = dlsym(dlopen("libapp.so", ...), "ANativeActivity_onCreate");
    if (!on_create) {
        LOG_FATAL("cannot find ANativeActivity_onCreate in the native library ...")
    }
    on_create(native_activity, savedState, savedStateSize);
}
```
Extending NativeActivity will require gomobile to dex the Java source files, and will end up gomobile having the SDK as a dependency. That's why I don't suggest following that path.

**Comment by slimsag** [comment]
> A third option is to dlopen, dlsym and invoke each call dynamically, which is horrific and doesn't deserve being mentioned :-) That's the only way to lazily load libopenal in our case.

FWIW we took that approach (see [al.c](https://github.com/azul3d/native-al/blob/master/al.c) and [al.go](https://github.com/azul3d/native-al/blob/master/al.go)) and, indeed, it's pretty horrific. If it's useful feel free to use it as a reference.

It does have the added benefit of allowing self-extraction (single-binary-'like' deployment) on desktop OS's though (see [docs here](https://godoc.org/azul3d.org/native/al.v1)).

**Comment by rakyll** [comment]
We shouldn't go for that approach, because it's not scalable. The point we need another external dependency, we will require the bindings to do the dlopen/dlsym dance for Android.

I haven't mentioned earlier but, one drawback of having to dlopen is that Android is not setting the LD_LIBRARY_PATH to a sane value. So, you have to load the libraries packed in the APK from /data/data/PACKAGE_NAMESPACE/lib as the installer unpacks them to that exact directory. If you don't want to deal with this, we can call System.loadLibrary from the native context.

**Comment by crawshaw** [comment]
What do you mean not scalable? I'm not planning any other dynamic library dependencies. What others are you thinking of?

To me OpenAL is an unfortunate abberation. I would sooner implement the high level audio package directly on OpenSL and remove it than add another library like it.

**Comment by rakyll** [comment]
> I'm not planning any other dynamic library dependencies. What others are
you thinking of?

None, but that's an ambitious assumption that we will ever need another
dynamic library dependency.

> I would sooner implement the high level audio package directly on OpenSL
and remove it than add another library like it.

If you're OK to remove al/alc packages, fine. I can switch to an OpenSL
backend for Android for the higher level player.

**Comment by crawshaw** [comment]
My current reasoning on dynamic libraries:

1. Every API we build in the mobile repository is for both Android and iOS.
2. We cannot load dynamic libraries on iOS.
3. We can statically link on Android, except where licenses prohibit it.
    License prohibitions on Android apply to iOS too.
4. We strongly prefer working in Go and minimizing C.
    (If everything we needed from Android and iOS was available as a
    syscall, I would make this work with CGO_ENABLED=0.)

So for us to need a dynamic library: it must be necessary for implementing an API on Android that is available on iOS some other way, and licensing must prohibit static linking. I'm amazed we found even one example.

It may be expedient to implement your audio package directly on OpenSL and you can if you like, but I think it would be of great value to game developers to have the full OpenAL available. So it would be nice to solve this, even if it means writing a script to generate a bunch of dlsym-based function bindings.

**Comment by rakyll** [comment]
My reasoning on dynamic libraries was related to user packages rather than
what we will provide in the mobile repo. But the users can always depend on
the NDK toolchain and System.loadLibrary if they have additional external
dependencies and they are only targeting Android -- it should be case if
you're loading a dynamic lib.

So, fine. We should move on, I'll dlsym. If we don't like it, we can
rethink and reimplement.

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/6240/.
