### ISSUE TITLE
runtime: Extend Go's map crypto hash guarentee to all platforms in 1.5

### ISSUE THREAD

**Issue by tildeleb** [golang/go#9365]
I originally wrote this as a response to #9295 but then realized that issue is closed and a patch is pending.
Also see https://github.com/OneOfOne/xxhash/issues/2

**It would be much better to extend Go's map crypto hash guarentee to all platforms.**

With all due respect I think the proposed new fallback hash function is a mistake. Seriously, I was about to make a "Merry Christmas" post on go-nuts thanking the Go Authors for using a crypto quality hash to implement maps on X86-64. As many other languages struggle with their hash functions being hacked with differential crypto, Go is in much better shape.

My proposal is SipHash.
https://131002.net/siphash/

On that page note "C++ program to find universal (key-independent) multicollisions for CityHash64"
Run the program and see how trivial it is to generate multi collisions.

I wonder how many users have Go programs and APIs that accept uncontrolled input over the web and pump that into a map? The Go team has an opportunity here to protect users from themselves starting with 1.5.

There is already an X86_64 optimized version of SipHash here and it's in the "public domain".
https://github.com/dchest/siphash

I'll try to post some numbers in a few days showing that SipHash could be a viable replacement for the fallback hash.

FWIW, I am working on Go project to offer a large number of hash functions along with testing and benchmarking under one project here:
https://github.com/tildeleb/hashland

I took SMHasher and aeshash code from the Go  runtime. There is also a proposal for a new, non streaming hash interface, and more. It's still in pretty rough shape, as I've been hacking on it every day. The benchmarking that it does is currently kind of broken and suffers from using an generic adapter function. I am working on that.

*I really hope Go 1.5 can extend map's crypto guarentee to all platforms.*

**Comment by minux** [comment]
Modifying the language for optional security feature won't work well,
because that ultimately
depends on the author of a package, who can't control where the package is
going to be
used.

The author of a package might think that a certain map in this package is
not going to hold
values controllable by external attackers, but that really depends on where
the package is
used. What if the package is later used to receive inputs controlled by
external attackers?

Even if we had such a feature of optionally using hardened hash functions
for certain maps,
the only safe option for a package author is to always enable that for
every map, because
the author can't be certain all the use cases of the package.

That said, I don't think there is any evidence that the current hash
functions are insecure
against algorithmic DDoS. Unless there is concrete proofs, I don't think we
need to do any
thing for this.
(By concrete proof, I really mean that you need to at least point out how
the attacker can
reasonably get around of the per-map seed. Don't just cite some papers
discussing some
other hashes, read the source, and see if the attack in those papers are
applicable to ours.)

**Comment by minux** [comment]
I'm closing this issue, because I think there is nothing left to do.
