### ISSUE TITLE
runtime: pointer to struct field can point beyond struct allocation

### ISSUE THREAD

**Issue by rsc** [golang/go#9401]
If a non-zero-size struct contains a final zero-size field f, the address &x.f may point beyond the allocation for the struct. This could cause a memory leak or a crash in the garbage collector (invalid pointer found). This is a more general version of #9384.

**Comment by randall77** [comment]
This looks a bit tricky.  We have several structs like the following in the runtime:

type interfacetype struct {
	typ  _type
	mhdr []imethod
	m    [0]imethod
}

The [0] is really a placeholder for a variable-length array to follow.

Then to get the address of the nth imethod in interfacetype i, we do:
   add(unsafe.Pointer(i), unsafe.Sizeof(interfacetype{}) + n * unsafe.Sizeof(imethod{}))

That math is all wrong if we add a byte and then round the size of interfacetype.
(Why don't we use &i.mhdr[n] instead of that math?  I'm not sure.  Maybe just to avoid the bounds check?  Could do &i.m + n * ... also.)

Other structs which use the [0] at the end trick include m, g, stackmap, itab, and uncommontype.

It is possible that users depend on this trick as well.
I'm thinking the add-a-byte at malloc time for objects with trailing zero fields is the safer way to go.  We already round up to size classes so I don't think any code would be surprised by the allocated size being slightly larger than the requested size.
