### ISSUE TITLE
cmd/6a: go-1.4's "6a" lost an x86 addressing mode

### ISSUE THREAD

**Issue by rakitzis** [golang/go#9443]
I have been using Go's assembler to optimize some code by using SSE instructions.

I am running go-1.4 on MacOS 10.8.5.

I see that 6a has lost an x86 addressing mode due to a bug fix for Solaris in liblink.c. This code could previously compile:

```
; cat a.go  
package main

var x = 10

func foo() int

func main() { println(foo()) }
; cat a.s
TEXT ·foo(SB),4,$0-0
	MOVQ $0,CX
	MOVQ ·x(SB)(CX*1),AX
	MOVQ AX,ret+8(SP)
	RET
; go build
; a
10
```

Whereas now I get the error:

```
asmand: bad address "".x+0(SB)(CX*1)
asmand: bad address "".x+0(SB)(CX*1)
```

Looking for `asmand` I see the following change in liblink/asm6.c:

```
                        case D_STATIC:
                        case D_EXTERN:
                                if(ctxt->flag_shared || ctxt->headtype == Hnacl)
                                        goto bad;
```
became
```
                        case D_EXTERN:
                        case D_STATIC:
                                if(!isextern(a->sym))
                                        goto bad;
```

`isextern` turns out to be this:

```
// isextern reports whether s describes an external symbol that must avoid pc-relative addressing.
// This happens on systems like Solaris that call .so functions instead of system calls.
// It does not seem to be necessary for any other systems. This is probably working
// around a Solaris-specific bug that should be fixed differently, but we don't know
// what that bug is. And this does fix it.
static int
isextern(LSym *s)
{
        // All the Solaris dynamic imports from libc.so begin with "libc·", which
        // the compiler rewrites to "libc." by the time liblink gets it.
        return strncmp(s->name, "libc.", 5) == 0;
}
```

and so I am guessing this was an unintended regression.

**Comment by rsc** [comment]
This was an intended change. x(SB)(CX*1) turns into offset(CX) where offset is the address of x. As part of making Go binaries work at any link address, we changed the toolchain to use PC-relative addressing for all global symbol references. The only PC-relative memory reference is PC + int32 displacement. There is no opportunity to add more registers.

We had code in the Go tree that used this too, and we changed it to load the address of x into a register and then use that instead of x(SB) in the more complex form.

For simplicity, there is no option to build the toolchain without the PC-relative addressing assumption.
