### ISSUE TITLE
net/http: make Server.SetKeepAlivesEnabled(false) drop currently-open connections

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9478]
When adjusting the firewall configuration on a GCE instance today, I was confused that I could toggle my new firewall rule and see the changes immediately affect my ability to telnet to the http server, but my browser continued to work fine, regardless of the firewall setting.

What I realized (too slowly) was happening was that once the keep-alive connection was open, the firewall permitted it forever, as designed and documented.

It would be nice of the `google.golang.org/cloud/compute/metadata` package or similar could listen for metadata changes (the GCE metadata service supports long polling on changes) to see when the firewall or tags change, and then call `Server.SetKeepAlivesEnabled(false)` to drop existing connections and force them to (try) to reconnect.

Currently Server.SetKeepAlivesEnabled only affects future connections and not active idle ones.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by bradfitz** [comment]
Related: #4674

**Comment by tpng** [comment]
Any plan on fixing this?
Default support for http2 is included in Go 1.6, and browsers supporting http2 are reusing single connection by design.
`Server.SetKeepAlivesEnabled(false)` only affecting new connection means there are currently no way to close the only connection opened by browsers gracefully.
We can close the connection using the `Server.ConnState` hook, but it causes Chrome to display a error page before opening a new connection.
And I don't think we have enough info to send a GOAWAY frame inside the `Server.ConnState` hook.

**Comment by kevinpostal** [comment]
+1

**Comment by rsc** [comment]
@bradfitz, too late for Go 1.8, yes?

**Comment by bradfitz** [comment]
A couple of the other issues might make this easy. I'll close this at the end of the week if it doesn't happen, but let's keep it open until then.

**Comment by bradfitz** [comment]
I'm going to reopen this. The solution I have now is okay, but it's not great. It closes all currently-idle conns, but it should mark all conns for death as soon as they become idle. (For both http1 and http2).

I was thinking this before, but the flaky #17754 really drove it home.
