### ISSUE TITLE
cmd/cover: cgo produces incorrect coverage profiles

### ISSUE THREAD

**Issue by jonlawlor** [golang/go#9479]
What version of Go are you using (go version)?
`go1.4 darwin/amd64`

What operating system and processor architecture are you using?
OSX Yosemite (10.10.1) x86_64

What did you do?
On OSX:

``` bash
export CGO_LDFLAGS="-framework Accelerate"
go get -u -t github.com/gonum/blas
go test -coverprofile=coverage.out github.com/gonum/blas/cblas/
go tool cover -html=coverage.out
```

These commands would be different on other OSes, because the Accelerate framework is not available on them.  Alternate installation instructions are available on the github.com/gonum/blas README.md.  The important thing is that I'm running the cover tool's html option with a package that uses cgo.

What did you expect to see?
I expected 16% of the lines of code to show green, consistent with the test tool's coverage report.  

What did you see instead?
Only a 3 lines were highlighted green, and there were hundreds of lines colored red.
![screen shot 2014-12-30 at 10 29 04 pm](https://cloud.githubusercontent.com/assets/4468162/5585284/bda4c0a6-9074-11e4-9182-fe2be6d4a99c.png)

The issue https://github.com/golang/go/issues/6333 seems to be related.  That one appears to be focused on the command line tool, which is working correctly in this case (I think).  The html report is not.

**Comment by adg** [comment]
Are you sure you're running the latest version of the cover binary?

`go get -u golang.org/x/tools/cmd/cover`

**Comment by jonlawlor** [comment]
I double checked by removing everything and go get-ing everything again.  This produces the same result:

```bash
jonlawlor: ~/go/src/github.com/gonum/blas $ go get -u golang.org/x/tools/cmd/cover
jonlawlor: ~/go/src/github.com/gonum/blas $ go version
go version go1.4 darwin/amd64
jonlawlor: ~/go/src/github.com/gonum/blas $ export CGO_LDFLAGS="-framework Accelerate"
jonlawlor: ~/go/src/github.com/gonum/blas $ go get -u -t github.com/gonum/blas
jonlawlor: ~/go/src/github.com/gonum/blas $ go test -coverprofile=coverage.out github.com/gonum/blas/cblas/
--- FAIL: TestIdamax (0.00s)
	level1double.go:1155: idamax: mismatch NaN: expected 0, found 1
	level1double.go:1155: idamax: mismatch NaNInc: expected 0, found 1
FAIL
coverage: 16.0% of statements
FAIL	github.com/gonum/blas/cblas	0.207s
jonlawlor: ~/go/src/github.com/gonum/blas $ go tool cover -html=coverage.out
```
(except that there was some work in gonum/blas which makes it fail a test)

I really have tried to eliminate any PBCAK, but if I've missed something I apologize.

**Comment by robpike** [comment]
The problem here is that the line and column numbers in the cover profile refer to the cgo-rewritten file, but the file named is the original Go source file. For this particular case, a profile line refers to column 157 of line 91 of blas.go, whereas the actual data for that counter comes from 157 of line 91 of blas.cgo1.go. Line 91 of blas.go has only 122 characters; the cgo rewrite lengthens the line.

When the HTML processor for the cover tool reads, as instructed, blas.go, line 91 has only 122 characters but the block termination is written to happen at column 157. The tool decides the block never terminates, and the HTML output is compromised.

We are fixing the cover tool to terminate the block at the end of the line so the rest of the file will work. This is a simple fix, but not fully correct: the column numbers for blocks that start or stop on all rewritten lines will be incorrect. They always were, for cgo files.

A real fix will require much more complex computation to refer the column numbers back to the original Go source file, which is the one that the HMTL annotation refers to. This is not impossible, but it's close to infeasible.

We will leave this bug open to record this possibility, but don't expect it to be fixed. The updated cover tool will at least not fail so badly. Only the column numbers will sometimes be wrong. Lines will always be right.

**Comment by robpike** [comment]
It occurs to me that a feasible solution is to run the cover analysis on two files, the original and the cgo output. Rewrite the cgo output file as usual, but append the position data from the scan of the original. To work without bringing the diff algorithm in, which I would like to avoid, it would require that all cgo rewriting is within a line, that is, that it does not add or delete any lines. It does this today (otherwise coverage wouldn't work at all), but I am a little nervous to add this requirement.

**Comment by mattn** [comment]
It seems working good to me.

http://bl.ocks.org/mattn/raw/7d41ecb1c25c09d9a198/

**Comment by mattn** [comment]
BTW, OT, the file path should be ToSlash-ed?

**Comment by adg** [comment]
@mattn if it works well for you then you're just lucky. It only fails under certain circumstances.
