### ISSUE TITLE
cmd/gc: report unreachable code

### ISSUE THREAD

**Issue by fhermeni** [golang/go#9501]
Hi

Because I am stupid from times to times when I update my code, I create some unreachable statements. Some languages like Java report such issues. The current compiler does not seem to do so. Is it on purpose or not ?

Attach is a classical double return. The second one can never be executed:
http://play.golang.org/p/1JvAR4Yari

BR

**Comment by titanous** [comment]
vet reports this:

```text
$ go vet
foo.go:7: unreachable code
```

**Comment by fhermeni** [comment]
Ok, my bad.
On the other side, the compiler detects unused variables, packages, but not code. This might however be justified by the complexity to detect unreachable code wrt. unused variables/package ?

**Comment by griesemer** [comment]
Generally, Go's philosophy is not to protect the programmer at all costs from his/her mistakes. It's deliberate to not raise an error for unreachable code. It's also not a very common kind of mistake. Besides, it's often useful to introduce early returns for debugging which may cause plenty of unreachable code. It's not clear the benefits outweigh the costs and disadvantages.

Unused variables can lead to subtle find bugs in conjunction with Go's re-declaration mechanism in short variable declarations - hence the error message for unused variables. This is a mechanism that evolved from experience and is a pragmatic solution for a concrete problem.

Unused imports are reported because it helps keeping dependencies under control - an important tool in large-scale systems design and as a side-effect it also keeps compile times fast. Again a very deliberate design decision.

Finally, making dead code an error would be a significant language change which is out of the question at this point.

Use go vet.

**Comment by fhermeni** [comment]
Hi
Thanks for the clarifications
