### ISSUE TITLE
cmd/go: unhelpful error message from go get when custom import has moved

### ISSUE THREAD

**Issue by robpike** [golang/go#9540]
% go get -u rsc.io/github/issue
package rsc.io/github/issue
	imports 9fans.net/go/acme
	imports 9fans.net/go/plan9
	imports 9fans.net/go/plan9/client
	imports 9fans.net/go/draw
	imports 9fans.net/go/draw/drawfcall
	imports github.com/google/go-github/github
	imports github.com/google/go-querystring/query
	imports golang.org/x/oauth2
	imports golang.org/x/net/context: /Users/r/src/golang.org/x/net is from https://code.google.com/p/go.net, should be from https://go.googlesource.com/net

The error is the last line, but "should be" doesn't tell me much, as this is a transitive dependency I don't know about. It should say something about what went wrong (vanity import has changed target) or how to fix it (remove stale repo) or .... ?

I found this difficult to understand but easy to fix, implying the error message could be improved.

**Comment by rsc** [comment]
We don't know exactly what went wrong. We can't say that the custom import changed target, because maybe it was never code.google.com/p/go.net and you just happened to run an hg command to populate /Users/r/src/golang.org/x/net from there. We could suggest removing the directory and re-running go get, but that assumes there are no changes that need to be kept. I am always wary of tools suggesting that people remove directories: people will do it blindly.

We could make the error more explicit about the operations, saying

imports golang.org/x/net/context: /Users/r/src/golang.org/x/net is **checked out** from https://code.google.com/p/go.net, **but golang.org/x/net** should be **checked out** from https://go.googlesource.com/net

Is that enough to make the problem clearer?

**Comment by adg** [comment]
Perhaps the message should say *why* "golang.org/x/net *should* be checked out from xxx". Otherwise it's like "uhh, but why should it be checked out from there?"

**Comment by rsc** [comment]
golang.org/x/net is a custom import path for https://go.googlesource.com/net, but /Users/r/src/golang.org/x/net is checked out from https://code.google.com/p/go.net
?

**Comment by adg** [comment]
That's much clearer IMO. LGTM.

**Comment by rsc** [comment]
Fixed but forgot to write the magic line. golang.org/cl/2808

**Comment by samuell** [comment]
Would be nice with some line on possible ways to resolve what's went wrong. E.g., I'm now getting a lot of:

```bash
github.com/<repopath>: github.com/<repopath> is a custom import path for https://github.com/<repopath>, but ~/go/src/github.com/<repopath> is checked out from git@github.com:<repopath>
```

I get this even for packages I have just checked out with `go get`, and am a bit confused about what is happening. Seems like `go get` has somehow started to check things out using `git@...` instead of `http://...` as git urls ...
