### ISSUE TITLE
net: setKeepAlivePeriod may be wrong on Solaris

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#9614]
In revision f956740163ad4b46237cea83357b962cada1c2df the function setKeepAlivePeriod in the net package was changed on Solaris to use TCP_KEEPIDLE and TCP_KEEPINTVL.  However, I am told that on Solaris 11.2, those symbols are not defined.  They are defined in our syscall package because they are defined on Illumos, which is derived from OpenSolaris.  If we want Go to have support for Solaris proper, not just OpenSolaris, we should probably go back to the earlier Solaris-specific version of setKeepAlivePeriod.
￼

**Comment by 4ad** [comment]
The problem here is that it impossible to perfectly emulate TCP_KEEPINTVL + TCP_KEEPIDLE using TCP_KEEPALIVE_THRESHOLD and TCP_KEEPALIVE_ABORT_THRESHOLD.

Generally speaking, TCP_KEEPALIVE_ABORT_THRESHOLD = TCP_KEEPCNT * TCP_KEEPINTVL, however, when using TCP_KEEPALIVE_ABORT_THRESHOLD, Solaris will not send probes at equal intervals, but will use an exponential backoff algorithm. That is not what we want.

If it's "good enough", and we decide to go with it, we need to find a good value for TCP_KEEPCNT. I don't know what a good value is.

**Comment by 4ad** [comment]
Mikio, do you know what a good TCP_KEEPCNT value is?

**Comment by mikioh** [comment]
Maybe 2^3? Agree that TCP_KEEPALIVE_THRESHOLD is equivalent to TCP_KEEPIDLE, TCP_KEEPALIVE_ABORT_THRESHOLD is equivalent to TCP_KEEPINTVL x TCP_KEEPCNT.

**Comment by binarycrusader** [comment]
A future release of Solaris now supports these interfaces in a Linux-compatible way, so perhaps once a path for issue #15227 is figured out, we can figure out a way to use these on Solaris as well if they are available.

As an example, the values on a development version of Solaris are currently:

``
TCP_KEEPIDLE			0x1D
TCP_KEEPINTVL			0x1E
```

...while they are this on some OpenSolaris-based derivatives:

``
TCP_KEEPIDLE			0x22
TCP_KEEPINTVL			0x24
```

**Comment by panjf2000** [comment]
> A future release of Solaris now supports these interfaces in a Linux-compatible way, so perhaps once a path for issue #15227 is figured out, we can figure out a way to use these on Solaris as well if they are available.
> 
> As an example, the values on a development version of Solaris are currently:
> 
> ```
> TCP_KEEPIDLE            0x1D
> TCP_KEEPINTVL           0x1E
> ```
> 
> ...while they are this on some OpenSolaris-based derivatives:
> 
> ```
> TCP_KEEPIDLE            0x22
> TCP_KEEPINTVL           0x24
> ```

Hi @binarycrusader, first thank you for the helpful tips! 

I'm working on [CL 577195](https://go.dev/cl/577195) that sets `TCP_KEEPIDLE`, `TCP_KEEPINTVL`, and `TCP_KEEPCNT` on Solaris 11.4 and falls back to `TCP_KEEPALIVE_THRESHOLD` + `TCP_KEEPALIVE_ABORT_THRESHOLD` when Solaris kernel <11.4. It turns out that the `TCP_KEEPCNT` on  Solaris 11.4 is also inconsistent with the OpenSolaris-based derivatives, check out this [failed test](https://storage.googleapis.com/go-build-log/3e856681/solaris-amd64-oraclerel_d8d203a3.log). Unfortunately, I don't have a machine with Solaris 11.4 installed where I can seek out these three macros. I've searched the entire Internet for the `<sys/socket.h>`, `<netinet/in.h>`, and `<netinet/tcp.h>` header files and got nothing. Could you please share how you looked up these macros on Solaris in the first place? Also, if you could provided the value of `TCP_KEEPCNT`, it would be a big help, thanks!

**Comment by panjf2000** [comment]
Never mind, I've found it in [Rust libc](https://github.com/rust-lang/libc/blob/a0f5b4b21391252fe38b2df9310dc65e37b07d9f/src/unix/solarish/solaris.rs#L59-L61).
