### ISSUE TITLE
fmt: mismatch between explicit argument index documentation and behaviour

### ISSUE THREAD

**Issue by kortschak** [golang/go#9632]
The documentation describing explicit argument indexes in format strings does not state that if an argument is refered to by an explicit argument index in the first place that following verbs must also have an explicit index.

Currently this gives surprising results:
```
package main

import "fmt"

func main() {
	fmt.Printf("%[2]d is the %[1]s\n", "answer", 42)
	fmt.Printf("%d is the %[2]s\n", 42, "answer")
	fmt.Printf("%[2]d is the %s\n", "answer", 42)
}
```
```
42 is the answer
42 is the answer
42 is the %!s(MISSING)
```
http://play.golang.org/p/HP11QHqa_p

**Comment by minux** [comment]
“After processing a bracketed expression [n], arguments n+1, n+2, etc. will be processed unless otherwise directed.”

Working as intended.

**Comment by kortschak** [comment]
The wording is less than entirely clear.

**Comment by minux** [comment]
Then we have:

Because an explicit index affects subsequent verbs, this notation can be
used to print the same values multiple times by resetting the index for the
first argument to be repeated:

fmt.Sprintf("%d %d %#[1]x %#x", 16, 17)
will yield "16 17 0x10 0x11".

It states very clear that explicit index affects the following verbs, and
then you should
be able to understand the preceding statement:
"After processing a bracketed expression [n], arguments n+1, n+2, etc. will
be processed unless otherwise directed."

What confuses you?

**Comment by kortschak** [comment]
What left me confused was that that final sentence does not explicitly mention that the argument cursor will be used as in the updated state (or words to that effect). I think a single clause between "processed" and "unless" making this clear would improve the explanation.

**Comment by minux** [comment]
OK. Perhaps processing is confusing here. How about changing:
"After processing a bracketed expression [n], arguments n+1, n+2, etc. will be processed unless otherwise directed."
to:
"After processing a bracketed expression [n], subsequent verbs will use arguments n+1, n+2, etc. unless otherwise directed."

**Comment by kortschak** [comment]
SGTM
