### ISSUE TITLE
cmd/cgo: document that static functions work, static variables do not

### ISSUE THREAD

**Issue by jscheel** [golang/go#9673]
Discussion from #go-nuts on irc:
```
[6:34pm] hyphenated: jscheel: you're right, it should make up its mind about the scope there..
[6:34pm] hyphenated: jscheel: either it's file-scope and it should be able to access C.foo, or it's not and it shouldn't be able to access C.init_foo
[6:36pm] hyphenated: jscheel: if another go file also had an import "C" defining an init_foo, it should be a different one from the above. right now, can call C.init_foo and if it's defined twice in the same package, it uses the first one it finds and ignores the other
```

Sample code:
```
package main
 
/*
static int foo;

static void init_foo() {
  foo = 5;
}
*/
import "C"
 
import (
	"fmt"
)
 
func main() {
	C.init_foo()
	fmt.Println(C.foo)
}
```

**Comment by minux** [comment]
It depends on how cgo is implemented, you shouldn't rely on being able to
access static C variables or functions from Go.

**Comment by ianlancetaylor** [comment]
It does seem inconsistent, though, and I think it should be fixed or documented.

**Comment by minux** [comment]
Do you want to fix it or document it?

I think the correct fix is to disallow calling static functions defined in
the cgo preamble, however that might break current code that is working.
(BTW, the fix is not trivial because we need the function prototype to call
it, however, it is not easy to get the function prototype out.)

Given that we have never documented about this, the safest way is to
document it as a bug.

What do you prefer?

**Comment by ianlancetaylor** [comment]
I agree that people call static functions today, and that it seems undesirable to break that.  We even test it in misc/cgo/test, and I seem to recall fixing cgo so that those tests worked with gccgo.

I guess I don't see why static variables can't work in principle.  We could generate static getters and setters and rewrite references in the Go code.  Unless that seems infeasible perhaps we should leave this open in case somebody wants to fix it.

**Comment by minux** [comment]
Seems easy to fix because we already use a pointer to access C variables,
we just need to move the definition of the pointer from _cgo_gotypes.go to
.cgo2.c. But we also need to add unique hash to the global name in case
the static C variable is used in multiple cgo packages.

The only problem is that we must make sure to only emit the pointer definition
once. Can cmd/cgo detect if one variable definition is static?

I don't want to go the SWIG way, because Go is more capable than common
scripting languages and can access most C variables/constants without going
through accessor functions.

**Comment by ianlancetaylor** [comment]
I think cgo can detect a static variable by looking at the ELF symbol binding in the symbol table of _cgo_.o (or equivalent for the other formats).

**Comment by rsc** [comment]
As I understand it, static functions have always worked, and static variables have never worked. That seems perfectly fine. Let's document it and move on.
