### ISSUE TITLE
cmd/gc: map access on lhs of range clause not supported

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9691]
The following program does not compile:

```go
package main
func main() {
	m := make(map[int]int)
	for m[0] = range m {
	}
}
```
prog.go:4: cannot assign to int(autotmp_0003)

http://play.golang.org/p/fZG7UibXtr

**Comment by griesemer** [comment]
See also issue 9695 (similar problem for gccgo).

Definitively a compiler bug since the spec permits this explicitly:

"As with an assignment, if present the operands on the left must be addressable or map index expressions; they denote the iteration variables."

(http://tip.golang.org/ref/spec#For_statements)
