### ISSUE TITLE
x/tools/go/types: Type checker does not handle some imported types

### ISSUE THREAD

**Issue by obeattie** [golang/go#9702]
Using Go 1.4.1, it seems that the type checker cannot handle some imported type declarations. This was found using [stringer](https://godoc.org/golang.org/x/tools/cmd/stringer). By way of example, I can create a project with two packages, `domain` and `impl`:

**domain/domain.go**:
```go
package domain

type Value map[string]string
```

**impl/impl.go**:
```go
package impl

import (
	"github.com/obeattie/test/domain"
)

type Foo interface {
	Bar(domain.Value)
}
```

Upon invoking `go generate` (and therefore stringer, and therefore the type checker), I get the following error:

    stringer: checking package: impl.go:8:6: Value not declared by package domain

I would not expect this to cause an issue, given this will compile just fine.

**Comment by minux** [comment]
What if you first do
   go install domain
And then invoke go generate on impl directory?

**Comment by ianlancetaylor** [comment]
You wrote domain/domain.go but your impl/impl.go imports test/domain.  Can you confirm that your impl.go is importing the domain package that contains domain/domain.go?

**Comment by obeattie** [comment]
@ianlancetaylor Yes. I wrote the code above as an example, but did a bad job of making it clear. I originally encountered the issue in [this code](https://github.com/obeattie/sase/tree/go-9702) (you need to checkout that specific branch if you want to see for yourself).

To @minux's point, yes, running `go install github.com/obeattie/sase/domain` first does fix this. Is this, in fact, expected behaviour?

**Comment by minux** [comment]
It seems a lot of tools expect you to have installed all dependent
packages, so in that sense, it's expected behavior, as of today.

However, that is certainly not ideal, given that source code is
available, it probably should fallback to source code if the installed
package is not available or stale.

I will leave the judgement to the x/tools developers.

/cc @alandonovan and @griesemer

**Comment by adonovan** [comment]
Used directly, the type checker satisfies direct import dependencies by loading export data for installed packages.  This assumes that the packages have been built and installed more recently than their source code was edited.

Because this is assumption is often false, the golang.org/x/tools/go/loader package provides a means of loading all dependencies from source code as needed.  I recommend that you use that.

The stringer tool doesn't use go/loader; perhaps it should.

**Comment by robpike** [comment]
Expected behavior as explained above.
