### ISSUE TITLE
spec: some way to analyze or enforce data lifetimes

### ISSUE THREAD

**Issue by tv42** [golang/go#9743]
I wish -race or oracle or a new tool in the spirit of errcheck could help prevent these kinds of mistakes:
1. io.Writer Write is not allowed to hold on to the buffer past its return. Yet that's an easy bug to cause; e.g. send the buffer on a channel.
2. Anything that uses sync.Pool (or its own pool) for e.g. incoming network requests, and calls handler functions, has this issue if the handler holds on the value returned to the pool. This might include net/http.Handler Request, ResponseWriter, etc.
3. As a more complex case, https://github.com/boltdb/bolt has `func (db *DB) View(fn func(*Tx) error) error` where the function passed in can do `val := txn.Bucket(b).Get(key)` and the val []byte is only valid inside that View transaction. It's quite easy to accidentally write

``` go
var result []byte
get := func(txn *bolt.Tx) error {
    result = txn.Bucket("widgets").Get("frobnizer")
    return nil
}
if err := db.View(get); err != nil { ... }
```

but the database is free to reuse the memory pointed to by `result` immediately after `get` returns.

**Comment by minux** [comment]
I think reliably checking this is equivalent to solving the halting problem.
(because in general, data lifetime is undecidable, otherwise why do
we need GC at all? Just make the compiler intelligently insert malloc
and free and we're done.)

And unreliable checking will probably annoy the user. (Trivial cases
are easily checked, but what the user really wants is to be able to
check for those non-trivial cases.)

**Comment by extemporalgenome** [comment]
Indeed, such analysis isn't tractable in the general case. Even in specific cases, it can be difficult in practice: for example, lifetime requirements can be maintained even when sending a []byte down a channel as long as the slice is no longer used by the time the return from, i.e., Write, occurs.

Because of the practical need for such a tool to strike some balance between accuracy and usefulness, it'd likely have to be a 3rd party tool with some kind of annotations or hinting (preferably outside of the Go code, perhaps similar to the API checking tool).

**Comment by minux** [comment]
A dynamic checking tool for this is possible, but I'm not sure if it could
be done without runtime changes.

**Comment by dvyukov** [comment]
A rough idea:
Provide a function:
foo.AssertThisIsTheOnlyReferenceTo(ptr interface{})
Calls to this function are either inserted by user manually, or using code transformation technique similar to 'go test cover'.
The function dumps heap, analyzes it and ensures that the pointer is indeed the only reference to the object.

**Comment by bradfitz** [comment]
@alandonovan, are there existing checkers using your guru fanciness?

**Comment by alandonovan** [comment]
@bradfitz nope. A static analysis for this problem would need to understand both control flow and aliasing, which makes it basically intractible.  You could do it if the user supplied lots of information about ownership, but then you'd be programming in Rust, not Go.

**Comment by ianlancetaylor** [comment]
This is not a Go 2 issue.  It is a request for a different sort of tool.  It might require some way to annotate the program, but if so that could be discussed separately as a general issue, not specific to this idea.

**Comment by rsc** [comment]
This is a wish, not a proposal. Nothing concrete is being proposed. I would love to have this too, but I don't know how to do it. Removing the proposal label again, and the prefix too, so gopherbot doesn't put the label back.

**Comment by rsc** [comment]
On second thought I don't think this is appropriate as an open issue. There's no concrete next action.
