### ISSUE TITLE
spec: remove "strings are immutable" statement

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9816]
This statement causes numerous confusion in mailing lists, people try to tie it to thread-safety and inability to assign to string variables. And it does not have any formal meaning behind it. The formal part here is that string indexing operation cannot be assigned to and is not addressable. And that is stated right in the next paragraph: "if s[i] is the i'th byte of a string, &s[i] is invalid" and duplicated in description of addressability and assignment statement.

The kind of "immutability" that statement refers to is implementation ground. And so better be described in Effective Go in extended form with implications to thread-safety and string copying.

The proposed changes:
1. Remove "Strings are immutable: once created, it is impossible to change the contents of a string".
2. Add it is illegal to assign to s[i] right after "if s[i] is the i'th byte of a string, &s[i] is invalid" for consistency.
3. Remove "non-constant" in "a[x] is the non-constant byte value at index x and the type of a[x] is byte".
4. Add a section to Effective Go with the discussion of string "immutability".

**Comment by dvyukov** [comment]
@robpike @griesemer @ianlancetaylor @rsc @bradfitz

**Comment by griesemer** [comment]
I don't see any problems with this statement. In fact, if you look up immutability, Wikipedia says:

"In object-oriented and functional programming, an immutable object is an object whose state cannot be modified after it is created."

as the very first sentence. This is exactly how we see Go strings (http://en.wikipedia.org/wiki/Immutable_object)

It may not be "formal" but the spec is on purpose semi-formal, which is why it is actually readable.

Also, we cannot remove 3): "non-constant" is crucial here because even if you have a constant string and constant index, say "hello"[0], this expression is not constant.

I'd be ok to add that one cannot assign to s[i] (your proposal 2), for consistency, and to add to Effective Go if there's a good spot.

Leaving to r, rsc, iant to chime in.

**Comment by robpike** [comment]
I think things are fine, correct, and clear as presented now.

**Comment by dvyukov** [comment]
> I think things are fine, correct, and clear as presented now.

Do you want me to count number of messages on this topic? It is clearly not clear.
Just from few previous days:
https://groups.google.com/d/msg/golang-nuts/zyQnord8hyc/dOQbi0IgpUQJ
Where topic starter assumes that string variables are not subject for data races.
Another one "Strings in go : immutable or not ?" is on internal mailing list, where topic started assumes that if you do println(s) several times it will always print the same string.

> "In object-oriented and functional programming, an immutable object is an object whose state cannot be modified after it is created."

The spec does not introduce notion of "string buffer" as something separate and visible. And you clearly can mutate _strings_ themselves. Strings would be immutable if you are not able to assign to a string variable.

Making it an informal note sounds good to me. But then it needs to be moved to the bottom of the Strings section and extended to mention string buffers and cheap copying.

**Comment by ianlancetaylor** [comment]
I honestly feel that these arguments over terminology makes things less clear rather than more.  Both threads you cite are confusions about variables: one about variables in data races, one about variables in a range statement.  These exact same confusions arise in practice about int variables, so I see nothing special about strings in those threads.

I continue to believe that in Go string values are immutable just as int values are immutable.  I continue to believe that this not true in C/C++.  Therefore I continue to believe that it is useful to state clearly in the spec that string values are immutable.  I do not agree that it is equivalent to say that &s[i] is invalid.  The fact that &s[i] is invalid is a technical statement that follows from the general concept that string values are immutable.

**Comment by griesemer** [comment]
There's a difference between a string value and a string variable. Variables are by definition modifiable, otherwise they wouldn't be called variables. String values are not modifiable and thus immutable. There's nothing unusual here about the use of the term "immutable".

The spec is sometimes lax when it talks about things X - sometimes we mean the type X, sometimes we mean a value X, sometimes we mean a variable of type X. But usually it's clear from context; being always 100% explicit is overly pedantic and will make the spec unreadable.

I don't doubt that there's a lot of discussion about the subject, as there's a lot about almost everything. But the notion of immutable strings is non-controversial and exists in many other languages.

**Comment by dvyukov** [comment]
I have at least two optimizations in mind that introduce string buffer mutation.
1.  Replace the following with s[0] = 'b':
s := "rob"
b := []byte(s)
b[0] = 'b'
s = string(b)
This can be extended to a general ToUpper kind of loop, so looks useful.
2. When you do:
s += "\n"
If runtime sees that there is an unused space in the string buffer of s, then it will just mutate it by appending \n to it.

Do you want to say that they are prohibited by the spec?...

**Comment by ianlancetaylor** [comment]
Neither of those optimizations are prohibited by the spec, any more than the spec prohibits optimizing "a++" by modifying the memory location where a is stored.

String values are not the same as string buffers.  The spec doesn't discuss how strings are laid out in memory.  In fact gccgo used to use a different layout, although I have since converted to the gc layout because the old gccgo layout did not permit efficient string slicing.
