### ISSUE TITLE
x/mobile: use java:openjdk docker base image

### ISSUE THREAD

**Issue by proppy** [golang/go#9823]
What do you think of using the [official openjdk image](https://github.com/docker-library/java) as the base for the docker image instead of `ubuntu`?

Is there a specific reason you default on installing the oracle JDK?

Just tested that android 21 + openjdk seems to be able to build .apk just fine, see:
https://gist.github.com/proppy/e41195a41bea12e8c205

**Comment by hyangah** [comment]
I guess oracle jdk was chosen just because it's in the system requirement page of the android developer site https://developer.android.com/sdk/index.html#Requirements 

The current way of building go mobile apps using docker image will be obsolete soon when @crawshaw 's gomobile tool becomes ready. golang/go#9508.

https://docs.google.com/document/d/1cePOQ35PNEb_QqxnPAmBv0cEnAm7AQSGuz9wVeJ-lBs/edit?disco=AAAAAT-St2U
