### ISSUE TITLE
math/big: Exp function returns puzzling results when exponent = 1

### ISSUE THREAD

**Issue by royalfork** [golang/go#9826]
I'm using Go 1.4 on 64 bit Debian.

I run the following:
import "math/big"
a := new(big.Int).Exp(big.NewInt(5), big.NewInt(1), big.NewInt(3))

I expect 'a' to be 2, because 5**1 % 3 = 5 % 3 = 2.  Instead, Go gives a = 5.

Code can be found here: http://play.golang.org/p/TCWWiXXZhf

**Comment by ALTree** [comment]
In nat.go expNN ([here](https://github.com/golang/go/blob/master/src/math/big/nat.go#L873)), when `y` is 1, `v` is set to `1` ([here](https://github.com/golang/go/blob/master/src/math/big/nat.go#L906)) and `shift` on the next line to `64`. Then on the line

`w := _W - int(shift)`

`w` is set to `0` `(64 - 64)`, so the code inside the loop on line 921 is never run. Since `z` (the result) was set to `x` (on line 895) and never changed  the function returns `x` (5 in the example) instead of `x mod m`.

Patch: https://go-review.googlesource.com/#/c/8409
