### ISSUE TITLE
Go Spec: ENBF contradictory for variadic function parameters

### ISSUE THREAD

**Issue by danmane** [golang/go#9877]
The Go Language Spec has the following specification for functions:

```
FunctionType   = "func" Signature .
Signature      = Parameters [ Result ] .
Result         = Parameters | Type .
Parameters     = "(" [ ParameterList [ "," ] ] ")" .
ParameterList  = ParameterDecl { "," ParameterDecl } .
ParameterDecl  = [ IdentifierList ] [ "..." ] Type .
```
Since any `ParamaterDecl` can have a `"..."` for a variadic function, this implies that a function parameter signature could have multiple variadic declarations. However, beneath this paragraph the text states "The **final** parameter in a function signature may have a type prefixed with .... A function with such a parameter is called variadic and may be invoked with zero or more arguments for that parameter." (emphasis mine).

To have the ENBF specification match the description, something like the following should be used. 

```
FunctionType   = "func" Signature .
Signature      = Parameters [ Result ] .
Result         = Parameters | Type .
Parameters     = "(" [ ParameterList [ "," ] ] ")" .
ParameterList  = ParameterDecl { "," ParameterDecl } ["," VaradicDecl ] .
ParameterDecl  = [ IdentifierList ] Type .
VariadicDecl = [ IdentifierList ] "..." Type .
```

**Comment by ianlancetaylor** [comment]
There are many cases where the text imposes limitations on the EBNF syntax.  This is just one.  In general, this is fine, as it keeps the syntax simpler.

Sending this particular case to Robert to see if he wants to change it.

**Comment by griesemer** [comment]
@iant has already made this very clear.

The EBNF accepts a wider syntax by design, because it makes the syntax simpler. It's also easier to see the big picture this way - special cases are handled in the prose.

Note that the correct fix would be more complicated than your suggestion because you can have a variadic parameter in the first position (no leading "," in that case), as in:

func f(...T)

If you have a correct suggestion that's just as simple as what we have now, I'm happy to consider it.

Finally, even for a parser it makes sense to accept a wider syntax (and have the restrictions checked separately) because it permits better error handling.

**Comment by danmane** [comment]
Interesting, thanks
