### ISSUE TITLE
the "nil is overloaded" problem (go2)

### ISSUE THREAD

**Issue by robzan8** [golang/go#9883]
Hi (and forgive my bad English).
I was writing my first attempt to a "serious" project in Go and one crazy idea came into my mind. I think one possible solution to make the semantics of nil less confusing could be to make nil even "more overloaded" :D
And with that I mean: make nil the zero value of every type, not just reference types, including user defined structs. This way, just saying that an interface is a pair (type, pointer) and a slice is a triplet (pointer, len, cap) would be enough to understand what a nil interface and a nil slice really are (instead of claiming that a slice is a reference type, which is not totally true). Also "effective Go" encourages people to "arrange that the zero value of each type can be used without further initialization". So, it would be convenient to be able to check user defined structs for nil equality and to use nil instead of (for example) image.ZP and image.ZR.
This would be really different from what other languages do (but f*ck them, right?), and would have far reaching implications; checking if and array value is nil would mean scanning the whole array, but it seems to me that this would make the specs more consistent.
What do you think?
(hope this is the right place to post this)

**Comment by griesemer** [comment]
There is a _difference_ between a nil slice (say, []int(nil)) and an empty slice (say, []int{}). That's why there's a nil value. It does represent the "not present" value (as in a pointer that is not present).

If nil were the "zero" value for other types as well, say a type S struct{ x int }, one would expect similar behavior. But the zero value of an S is S{}. So S(nil) would have to mean the same, and that's odd. Or at the very least there would be two different ways to express the same basic construct, for not very good reasons - something we rather want to avoid (of course there's other things in the language that can be expressed in various ways, var decls come to mind, but those fall out from more general rules).

So thanks for the idea, but this is working as intended. Also, the right forum for suggestions like this is golang-nuts where you will find a much more rich ground for fruitful discussions of the pros and cons of language ideas.

PS: Please let's not offensively disgrace other languages - language design is very hard, and almost all languages have borrowed important ideas from predecessors. Thanks.

**Comment by robzan8** [comment]
Ok. Sorry for wasting your time :)
