### ISSUE TITLE
{gofmt,goimports}: consider harmonising import sorting and clustering

### ISSUE THREAD

**Issue by kortschak** [golang/go#9922]
See discussion https://groups.google.com/d/topic/golang-nuts/eAtUvHC6moQ/discussion

This issue is filed at the suggestion of @josharian.

goimports has an extended opinion of how import lists should appear that goes beyond the behaviour of gofmt. The result of this is that users of goimports create diff noise in teams where both gofmt and goimports are used by different users.

**Comment by bradfitz** [comment]
/cc @griesemer 

This is my fault. I added opinions to goimports, because I made goimports for me, and for use within Google, and inside Google we sort our imports in groups.

But FWIW, gofmt won't revert goimport's extra opinionated changes. The output of goimports is still gofmt-compliant.  So it's not like things are flipping back and forth. With enough time and non-zero developers using goimports, all the code should converge on the goimports style.

I'd really rather not add options to either gofmt or goimports, and I'd rather not remove the goimports behavior.

I'm not sure whether we want to make gofmt have the same opinion, though.

Personally I puke up a little in my mouth when I see "github.com" sorted between "fmt" and "io". It just looks weird to me.

**Comment by kortschak** [comment]
FWIW I have similar opinions about the direction of the change, though I'm still conflicted.

**Comment by rogpeppe** [comment]
I personally don't mind the status quo - even though gofmt enforces quite a bit, there are still significant areas of style freedom, and I think it's fine if some tools choose something different within that space when generating new code.

FWIW we use a slightly different style - imports are sorted into three sections: stdlib, external and repo-local. I have a separate tool (github.com/rogpeppe/sortimports) that enforces that opinion. I don't think it matters at all whether other projects use that style, but it's useful for us to be consistent. If there was general agreement that that style was in fact a Good Thing, then perhaps it might be considered for inclusion in goimports, I guess.

**Comment by anacrolix** [comment]
Thanks for linking to sortimports, @rogpeppe .

**Comment by rsc** [comment]
gofmt doesn't need and shouldn't have goimports's opinions.
But it should respect goimports's opinions, which it does.
So I think everything here is working as intended.

**Comment by kortschak** [comment]
That is only half of the relationship. The issue also raises the question of whether goimports should hold the opinions it does.

**Comment by bradfitz** [comment]
Dup that wasn't cross-linked for some reason: #18905
